doc/admin/how-to/mutate-user-api.md
=> Update mutate user api md

client/web/src/enterprise/code-monitoring/CodeMonitoringNode.tsx, client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.tsx, client/web/src/enterprise/code-monitoring/action-converters.ts, client/web/src/enterprise/code-monitoring/components/FormActionArea.tsx, client/web/src/enterprise/code-monitoring/components/actions/EmailAction.story.tsx, client/web/src/enterprise/code-monitoring/components/actions/SlackWebhookAction.story.tsx, client/web/src/enterprise/code-monitoring/components/actions/WebhookAction.story.tsx, client/web/src/enterprise/code-monitoring/components/actions/WebhookAction.test.tsx, client/web/src/enterprise/code-monitoring/components/actions/WebhookAction.tsx, client/web/src/enterprise/code-monitoring/testing/util.ts
=> code monitoring: add UI to edit generic webhook

internal/actor/http.go
=> add path label to incoming actors metric

internal/actor/actor.go
Add link to brief notebook about actor propagation: https://sourcegraph.com/notebooks/Tm90ZWJvb2s6OTI=
=> actor: add link to search notebook about actors

cmd/frontend/graphqlbackend/search_alert.go, cmd/frontend/graphqlbackend/search_results.go, cmd/frontend/graphqlbackend/search_results_test.go
LOOK 👀  
(putting up for review before `main-dry-run` completes)
=> search: remove logic on searchAlertResolver type

client/web/src/hooks/usePersistentCadence.ts
=> Update "usePersistenceCadence" to be deterministic in chromatic

dev/sg/internal/migration/squash.go
Pulled from #29831. This PR updates the squash command to run migrations via our own tool rather than shelling out to the `migrate` command on the host.
=> sg migration squash: Fix running migrations up

internal/workerutil/main_test.go
=> workerutil: Turn off logs in unit tests

internal/database/migration/runner/logger.go, internal/database/migration/runner/options.go, internal/database/migration/runner/run.go, internal/database/migration/runner/runner.go, internal/workerutil/dbworker/resetter.go, internal/workerutil/logger.go, internal/workerutil/main_test.go, internal/workerutil/worker.go
Reduce logs from worker and migration tests.
=> go test: Reduce log output

cmd/frontend/graphqlbackend/search_results.go
This is a PR into #29308, building on Ryan's work to do sub-repo filtering on search results.
=> Sub-repo permissions: move search filtering to a stream wrapper

internal/database/migration/definition/testdata/cycle-traversal/10003/metadata.yaml, internal/database/migration/definition/testdata/cycle-traversal/10004/metadata.yaml
=> migrations: Fix testdata naming

enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
See https://github.com/sourcegraph/sourcegraph/issues/30477
=> ci-flake: skip faulty code monitor tests

doc/dev/how-to/deploy_executor_image.md, doc/dev/how-to/index.md, doc/dev/index.md
Follow up to bug and discussion. I'd rather have something here than nothing, so I don't think this requires a lot of polish.
=> Add docs on how to deploy executor image to k8s/cloud

.tool-versions
don't use asdf to install python due to long CI run time
=> use system python

enterprise/cmd/frontend/internal/compute/resolvers/resolvers.go, enterprise/cmd/frontend/internal/compute/resolvers/resolvers_test.go
=> chore: preallocate some list copies

doc/dev/how-to/deploy_executor_image.md
=> executor docs: also mention how to update AWS ami

internal/database/migration/runner/options.go
Pulled from #29831. This PR improves the error conditions in desugaring operations. In particular, we check the length before referencing the leaf versions slice within the `desguarRevert` function. This change also makes the remaining behavioral diff of #29831 in this file trivially understandable.
=> migrations: Refactor desguar operations

doc/admin/how-to/troubleshoot-sg-extension.md
=> Search exporter doc update

client/web/src/enterprise/insights/pages/getting-started/CodeInsightsGettingStartedPage.tsx, client/web/src/enterprise/insights/pages/getting-started/components/code-insights-learn-more/CodeInsightsLearnMore.module.scss, client/web/src/enterprise/insights/pages/getting-started/components/code-insights-learn-more/CodeInsightsLearnMore.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/30159
[Desings](https://www.figma.com/file/EFgTP7gpdpQSEo1n4FUfsW/In-product-landing-page-WIP?node-id=1128%3A9814)
This PR just adds another section to the getting started page.
=> Code Insights: Add Code Insights Learn more section

dev/release/release-config.jsonc
=> Update release config for 3.36.3 patch release

CHANGELOG.md
=> Add 3.36.3 changelog entry

cmd/frontend/graphqlbackend/search_results.go
Now that we know that `r.evaluate()` is always called with a non-nil stream, we can depend on the stream to handle capturing the results and the stats, so we don't need to return them in addition to sending them on the stream. This modifies `evaluateJob`, `evaluateAnd`, `evaluateOr`, `evaluatePatternExpression`, and `evaluate` to only return a `*search.Alert` and an `error`. 
Stacked on #30578
=> Search backend: simplify returns

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/install/docker-compose/aws.md, doc/admin/install/docker-compose/digitalocean.md, doc/admin/install/docker-compose/google_cloud.md, doc/admin/install/docker-compose/operations.md, doc/admin/install/docker/aws.md, doc/admin/install/docker/digitalocean.md, doc/admin/install/docker/google_cloud.md, doc/admin/install/docker/index.md, doc/admin/install/docker/operations.md, doc/admin/install/kubernetes/configure.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/pure_docker.md, doc/dev/how-to/testing.md, doc/index.md
This pull request is part of the Sourcegraph 3.36.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30562)
cc @michaellzc
=> release: sourcegraph@3.36.3

cmd/gitserver/server/vcs_syncer_npm_packages.go, cmd/gitserver/server/vcs_syncer_npm_packages_test.go
Fixes issue https://github.com/sourcegraph/sourcegraph/issues/30554.
=> Fix OOB indexing in gitserver's NPM-related code.

cmd/server/Dockerfile
Copied the steps from our `gitserver` [Dockerfile](https://github.com/sourcegraph/sourcegraph/blob/main/cmd/gitserver/Dockerfile) and tested that I can build
the image locally.
=> server: Add p4-fusion to image

dev/release/release-config.jsonc
Part of https://github.com/sourcegraph/sourcegraph/issues/30553
=> Update 3.35.2 release config

doc/code_insights/explanations/viewing_code_insights.md
Now that we have a graphQL API and are able to simplify this model, we did – updating the docs to be accurate.
=> Update dashboard permissions  doc

internal/diskcache/cache_test.go
Adds a test for properly deleting nested files in the diskcache https://github.com/sourcegraph/sourcegraph/pull/30647
=> diskcache: Test multi-key eviction

cmd/gitserver/server/vcs_syncer_jvm_packages.go
We shouldn't need both error checks but we're continuing to see the
error in production logs which implies `Is` is not matching.
=> gitserver: Double check error type

client/web/src/global/GlobalAlert.story.tsx, client/web/src/global/GlobalAlert.tsx, client/web/src/global/GlobalAlerts.tsx
Regression from the Alert migration
=> Fix GlobalAlert variant

dev/sg/config.go, dev/sg/config_test.go, dev/sg/internal/usershell/usershell.go, dev/sg/sg_doctor.go, dev/sg/sg_setup.go, dev/sg/sg_setup_test.go, dev/sg/sg_start.go, sg.config.yaml
=> sg: Allow checks to be built in Go

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/install/docker-compose/aws.md, doc/admin/install/docker-compose/digitalocean.md, doc/admin/install/docker-compose/google_cloud.md, doc/admin/install/docker-compose/operations.md, doc/admin/install/docker/aws.md, doc/admin/install/docker/digitalocean.md, doc/admin/install/docker/google_cloud.md, doc/admin/install/docker/index.md, doc/admin/install/docker/operations.md, doc/admin/install/kubernetes/configure.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/dev/how-to/testing.md, doc/index.md
Backporting the changes from https://github.com/sourcegraph/sourcegraph/pull/30641
=> release: sourcegraph@3.35.2

internal/search/streaming/stream_test.go
This caused a failure on `main` [here](https://buildkite.com/sourcegraph/sourcegraph/builds/129376)
=> fix batching stream test that didn't use goroutine safe operations

internal/search/query/visitor.go
A simplification of the main visit method from @keegancsmith's idea
See https://sourcegraph.slack.com/archives/C020S8AT3LN/p1643982145545779
=> search: remove visitor interface

doc/admin/observability/troubleshooting.md
These docs were lacking some discoverability
=> Include link to Prometheus cAdvisor scraping fix

doc/dev/setup/troubleshooting.md
I really enjoyed figuring this one out.
=> doc/dev: add note about Firefox certificate issues on macOS

.github/ISSUE_TEMPLATE/request_patch_release.md, dev/release/src/main.ts, dev/release/src/release.ts, dev/release/src/slack.ts, dev/release/src/util.ts
Quality of life improvement for the Release Captain
- sanity check to ensure `release cli` is always run on the `main` branch and it's up-to-date
- improve instruction for release captain in the patch release issue
- release captain can actually find the webhook URL for posting the announcement
=> dev: improve release process

dev/sg/main.go
bad code from me 😬 https://github.com/sourcegraph/sourcegraph/pull/30697/files#diff-c969fd220bfdc303a4c1cc94156276b261baf9bf5575619617b6ac4f11aaf4f8R121
=> dev/sg: fix update check

client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInput.tsx
=> notebooks: do not show suggestions on file URL paste

dev/sg/sg_version.go
=> dev/sg: do not show merges in sg version changelog

doc/cli/references/batch/apply.md, doc/cli/references/batch/exec.md, doc/cli/references/batch/preview.md, doc/cli/references/batch/repositories.md, doc/cli/references/batch/validate.md, doc/cli/references/validate.md, internal/src-cli/consts.go
Includes some fixes required for SSBC. Will upgrade our executors after this has landed on main.
=> Bump src-cli version to latest

client/browser/CHANGELOG.md
Follow-up on https://github.com/sourcegraph/sourcegraph/pull/30674.
=> bext: update changelog for #30674

cmd/frontend/graphqlbackend/search_results.go
This removes the lower-level limit and timeout wrapper jobs when and/or
jobs are enabled. With and/or jobs, these limits are set in
toEvaluateJob. Additionally, these limits make and jobs find fewer
results than it should since it limits each of the `and` subqueries rather
than just relying on the limit on number of results returned.
=> Search backend: remove lower-level limits when and/or jobs are enabled

client/vscode/package.json, client/vscode/src/file-system/FilesTreeDataProvider.ts, client/vscode/src/file-system/SourcegraphFileSystemProvider.ts, client/vscode/src/file-system/commands.ts, client/vscode/src/file-system/initialize.ts
=> Add button to remove repo from file tree

.tool-versions
This reverts commit db0c84ea3a3a8d66bcdeb67b543d5b66d017ffda.
Is a revert.
=> Revert "dev: Upgrade trivy and packer (#30852)"

doc/admin/install/docker-compose/operations.md, doc/admin/install/kubernetes/update.md
This PR updates kubernetes and compose docs to use new features of the migrator. Also updates the output of the migrator to be representative of what is seen.
=> migrations: Update upgrade docs

internal/search/run/combinators.go, internal/search/run/combinators_test.go, internal/search/run/expression_job.go, internal/search/run/expression_job_test.go
This adds some unit tests for our search jobs just as a "these are doing what we think they are, right?" check.
=> Search jobs: improve tests

doc/admin/organizations.md
Document workflow around user org -- I've created an issue around this since its not a great user experience 
https://github.com/sourcegraph/sourcegraph/issues/30665
=> Document hook in userOrgMap

client/shared/src/components/FileMatchChildren.tsx
This commit adds logic to handle middle click on links, and changes the
implementation to delegate the event to an actual anchor element so that
the standard browser behavior is better replicated (e.g. opening new tabs in
the background).
I tested the behavior in Chromium and Firefox on Linux.
=> search: Improve search result click behavior

dev/sg/sg_doctor.go, dev/sg/sg_setup.go
This is just the start, but I wanted to get the git check out now before
someone else runs into this.
=> sg: use some check funcs in sg doctor

dev/sg/sg_start.go
- I ran `sg start web-standalone` locally to confirm that it boots up again and fixes the issue as reported in slack.
=> sg: fix wrong running of checks when starting

shell.nix
Remove watchman as `sg` handles watches itself
N/a
=> nix: remove watchman

client/vscode/package.json
This PR is to fix the json format in our package.json that is including some of the configuration settings under a different object. More detail in https://github.com/sourcegraph/sourcegraph/issues/30906
=> VSCE: Fix json format for missing configurations

dev/release/src/github.ts, dev/release/src/util.ts
Fix https://github.com/sourcegraph/sourcegraph/issues/30758
=> dev: avoid dockerhub rate limiting in release-cli

.github/workflows/update-project-items.ps1
Slack doesn't use Slack apps (like the GitHub Slack integration) to unfurl links sent by other Slack apps/webhooks, so the unfurled link didn't contain issue details. But we have all the issue info, so this uses some manual Slack attachment to recreate it (or actually better, because we can include our project fields like "Size" and "Importance" as key/value lists which GitHub wouldn't inline)
=> Use Slack attachment for prettier issue post

.github/workflows/update-project-items.ps1
=> Fix variable name

doc/admin/how-to/troubleshoot-sg-extension.md
Add troubleshooting steps for VSCE as discussed [here](https://sourcegraph.slack.com/archives/C0W2E592M/p1644429485997449?thread_ts=1644364214.580019&cid=C0W2E592M).
=> Add VSCE troubleshooting steps

enterprise/internal/database/CODENOTIFY
=> CODENOTIFY: narrow down subscriptions for Joe Chen

doc/dev/how-to/index.md, doc/dev/how-to/testing_in_dogfood.md
I figured it would fit in better here with the other how-to guides.
=> Add short how-to for testing changes in dogfood.

client/web/src/org/invitations/OrgInvitationPage.module.scss, client/web/src/org/invitations/OrgInvitationPage.tsx, client/web/src/org/members/InviteMemberModal.tsx, cmd/frontend/graphqlbackend/org.go, cmd/frontend/graphqlbackend/org_invitation.go, cmd/frontend/graphqlbackend/org_invitations.go, cmd/frontend/graphqlbackend/org_invitations_test.go, cmd/frontend/graphqlbackend/schema.graphql, internal/database/mocks.go, internal/database/org_invitations.go, internal/database/org_invitations_test.go, migrations/frontend/1528395972_allow_org_invitation_user_id_to_be_nullable.down.sql, migrations/frontend/1528395972_allow_org_invitation_user_id_to_be_nullable.up.sql
Changes in this PR were done to support accepting organization invitation by email. 
https://sourcegraph.atlassian.net/browse/CLOUD-187
https://sourcegraph.atlassian.net/browse/CLOUD-226
Changes done in this PR are behind a feature flag `org-email-invites`.
TBD...
- tested manually
- unit tests TBD
=> [Cloud][CLOUD-226] Make email invites work

monitoring/definitions/executor.go
=> executors: fix template query for executor dashboard variable

enterprise/cmd/executor/config.go, enterprise/cmd/executor/internal/worker/handler.go, enterprise/cmd/executor/internal/worker/worker.go, internal/workerutil/worker.go, internal/workerutil/worker_test.go
Before this was an executor-only feature, but it should've been a worker native feature. Moved it over now :)
=> Add execution deadlines to worker util

.github/workflows/update-project-items.ps1
Fixes duplicate Slack posts for every label being added.
=> Only consider team label being added

internal/search/query_converter.go
Prep for optimizing Sourcegraph-to-Zoekt queries.
Semantics preserving, covered by unit tests.
=> search: factor out Zoekt query pattern conversion

doc/dev/how-to/index.md, doc/dev/how-to/profiling_continuous.md, doc/dev/how-to/profiling_one-off.md
Based on Slack discussion: https://sourcegraph.slack.com/archives/C07KZF47K/p1643981037493389
N/A as I'm adding development docs.
=> Add short how-tos for continuous and one-off profiling.

internal/database/org_invitations_test.go
adding more unit tests
This change is just unit tests, so that should pretty much be it...
=> [cloud][CLOUD-187] add unit tests for DB operations for email invitations

client/browser/src/end-to-end/shared.ts
Follow-up for https://github.com/sourcegraph/sourcegraph/pull/30170
- `sg test bext-build && sg test bext-e2e`
=> bext: update e2e tests

doc/admin/how-to/troubleshoot-sg-extension.md
Add known limitation for VSCE based on results found in this [docs](https://docs.google.com/document/d/1ocy4KcY8_U2S0Jl616g96qYZi1-7CMfJ92p56WY_an8/edit).
=> Add known limitations for VSCE

dev/sg/sg_tests.go
This fixes #27232
Ran `go run . test --help` in `dev/sg`
=> sg: list available testsuites in 'sg test --help' output

internal/search/run/expression_job_test.go
We've had some tests flaking because they relied on timings to determine if things were working right. Turns out, in CI, the time variability is much higher than locally, so these fail somewhat frequently. This rewrites those failing tests to synchronize with channels so we can inject ordering behavior. Yay for mockable things!
As a nice side effect, I think this also allows me to make it more clear what the tests are testing for. 
This just fixes some tests.
=> Search backend: use channels to synchronize tests so they are deterministic

doc/dev/background-information/continuous_integration.md, doc/dev/how-to/cache_ci_artefacts.md
Removes/refreshes outdated pipeline dev docs and refreshes it with snazzy new [embedded notebooks](https://github.com/sourcegraph/sourcegraph/pull/30669)! Most of this content are split out from [the notebook I've been sharing around](https://sourcegraph.com/notebooks/Tm90ZWJvb2s6MTE3), which I've split into a multi-part notebook for ease of embedding and sharing. The goal is to provide a look at the internals of the generator for potential contributors.
Left step options as a "coming soon" - I will circle back to this.
Closes https://github.com/sourcegraph/sourcegraph/issues/30557 
```
sg run docsite
```
Then navigate to http://localhost:5080/dev/background-information/continuous_integration#pipeline-development
=> doc/dev: refresh CI dev docs with search notebooks

client/shared/src/components/activation/ActivationChecklist.test.tsx, client/shared/src/components/activation/__snapshots__/ActivationChecklist.test.tsx.snap, client/web/src/site-admin/overview/__snapshots__/SiteAdminOverviewPage.test.tsx.snap, client/web/webpack.config.js, client/wildcard/src/components/Tabs/Tabs.tsx, package.json, yarn.lock
This reverts commit ea48af518d39cffbb3e962ff8b89318e368123a2 because it seemingly breaks e2e and QA test suites: https://buildkite.com/sourcegraph/sourcegraph/builds/131093
- No local testing. Reverting to previous state only.
=> Revert "Webapp: Update @reach-ui and react-focus packages versions (#30845)"

lib/codeintel/lsif/conversion/canonicalize.go, lib/codeintel/lsif/conversion/canonicalize_test.go
2 commits stacked on top of #31143.
n/a as it doesn't affect application code.
=> Minor cleanup for document canonicalization + test code

cmd/server/Dockerfile, cmd/server/build.sh
This is a follow-up from us converting p4-fusion into a multi-stage build for gitserver #31066. This now uses the same shared script for building.
Test Plan: CI with integration testing will exercise building and running the server image.
=> server: use p4-fusion multi-stage build

internal/repos/scheduler.go
The code in the else-if block is not related to the condition in the
if-block. As a result they can be separate if-blocks and also as a
positive effect allow us to return early from the function.
Co-authored-by: Ryan Slade <ryanslade@gmail.com>
No change in functionality. This PR includes some comments and a tiny reorganisation for better readability.
=> repos/scheduler: Add comments and simplify if-else in runUpdateLoop

doc/code_search/explanations/index.md
=> remove search scopes example

doc/code_insights/how-tos/Troubleshooting.md
Docs only change. I noticed a formatting issue when looking at our Troubleshooting doc. This fixes it!
Tested this locally:
Before:
After:
=> insights: Fix formatting in troubleshooting docs

cmd/frontend/graphqlbackend/search_results.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/31126.
This lets us avoid the `SearchInput` copy/mutation in `toSearchJob`. I'm busy trying to break the resolver dependency for the job creation stuff.
Semantics preserving, covered by tests
=> search: compute MaxResults directly from query

doc/dev/background-information/continuous_integration.md
That's just docs. The `sgquery`s where ran on sourcegraph.com first to make sure they're correct.
=> ci: document tracing and analytics

internal/search/job/job_test.go, internal/search/job/mapper_test.go, internal/search/job/printers.go, internal/search/job/printers_test.go
=> search: add s-expression job printer

internal/search/job/job_test.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/31199.
This adds tests to lock in job creation behavior when we stream and don't create `PRIORITY` jobs.
Unit tests.
=> search: tests for different types of search when streaming

enterprise/internal/insights/resolvers/insight_series_resolver.go, enterprise/internal/insights/resolvers/insight_view_resolvers.go
Fixes #30071 
This PR makes it so a dynamically generated series (capture group series) will always return at least one series resolver for the purposes of calculating the state. 
After the fix:
=> fix series status

client/web/src/search/notebook/fileBlock/SearchNotebookFileBlockInput.tsx
Fixes #30010
* Create a notebook with a file block
* Enter a repository name
* Select the highlighted suggestion by pressing the tab button
=> notebooks: select file block suggestion on tab

dev/gqltest/README.md, dev/gqltest/external_service_test.go, dev/gqltest/main_test.go
The code here shouldn't change. It runs locally but will probably fail here I still need
to find out how to add the correct environment variables in our CI environment.
=> gqltest: Add a test for connecting to a Perforce external service

internal/database/migration/store/store.go
Fixes #30996. This issue reported that users of 3.36.0 may write _unfinished_ or _failed_ migration logs which were since hand-resolved by a site-admin. This PR changes the store startup sequence when the database is non-dirty, has no _new-style_ migration logs (any logs written after this commit goes live), and the database schema version is between a set of known migration numbers for which only sequential migrations were defined.
If all those conditions are true, new migration logs from the minimum migration number up to the current database version are written and old ones are discarded.
If any condition is false, the site-admin needs to do something by hand (they already have a dirty database, have migrated successfully to the new version and can write _new-style_ migration logs, or …
=> migrations: Fix upgrade from 3.36.0 with failing migrations

client/browser/CHANGELOG.md
=> bext: update changelog after release

CHANGELOG.md
Appended the link to the advisory for INC-76
=> Added security advisory link

cmd/frontend/graphqlbackend/search_results.go
By guaranteeing that `stream` is non-nil, we can simplify the `results`
method quite a bit.
Stacked on #31286 
Semantics-preserving, covered by integration tests.
=> Search jobs: always pass stream to `results`

doc/dev/how-to/profiling_continuous.md, doc/dev/how-to/testing_in_dogfood.md
N/A since no application code is affected.
=> docs: Fix bullets in how-to docs.

docker-images/grafana/Dockerfile
To 7.5.15 to reflect changes to security advisory CVE-2022-21703
Tested on local machine.  Appears to work fine but may require more verification.
=> Update Grafana version

cmd/gitserver/p4-fusion-install-alpine.sh
I was hoping all the improvements made around this script would result in much faster build times. It does, but with a very high variance. As such I've instead uploaded the p4-fusion binary to the sourcegraph-artifacts bucket. I don't suspect we will often change versions here so this seems like a good approach. Additionally the build script is quite robust now, so when we do bump the version it will be easy to build the new version.
I believe this complexity and cache is justified by the build times introduced to our CI for this step.
Test Plan: Built image locally. Also pushing to main dry run branch to exercise image building on CI.
docker build -t p4-fusion --target=p4-fusion .
=> gitserver: pre-built p4-fusion artifacts

dev/pr-auditor/issue.go, dev/pr-auditor/issue_test.go
- Include title of the PR
- Include link to test plan docs
- Fix generated message
Unit tests expanded to include checks on the issue body
=> pr-auditor: tweak generated issues for clarity

enterprise/internal/batches/service/workspace_resolver.go, enterprise/internal/batches/service/workspace_resolver_test.go
There are two errors that we didn't catch:
- A search that would not return anything would silently select all user-visible repos (ugh)
- The search can return repos that aren't yet cloned. It doesn't make sense to error out in that case because for some instances that might always be the case (Cloud for example). Instead we treat them as if they didn't exist yet.
Added cases for the two edge-cases to our extensive tests and validated manually it doesn't break anything. Experimental feature, so risk is low.
=> ssbc: Fix resolution errors

doc/code_insights/index.md, doc/code_insights/references/index.md, doc/code_insights/references/license.md
@AlicjaSuska I think we should put up this basic page and not list the full limitations until we have aligned on them in [RFC 567](https://docs.google.com/document/d/1WIInNUMtgOPIeiIONGios2_y67CSkkZr0WtFtU4h_IY/edit#heading=h.qp2pvnk0jby). I will return to this page to list explicitly the limitations after the fact, but we need this page to link to in the modal. 
@unclejustin just fyi, getting this page up at the path we agreed upon listed here: https://github.com/sourcegraph/sourcegraph/pull/30783/files#diff-232c243d712011e9e62f63ccf14efdafdc4db10a0c6301d1ae6290591cc9dd10R65
=> basic license page v1

dev/release/release-config.jsonc
Updating release config for 3.37
=> update release config for 3.37 minor release

cmd/frontend/graphqlbackend/search_results.go
Previously, we were mutating SearchResultsResolver by adding elapsed to
when we call `logBatch`. This just modifies the call to add elapsed
before calling logBatch, which also has the benefit of simplifying
logBatch.
=> Search backend: simplify logBatch by not mutating SearchResultsResolver

internal/search/job/job_test.go
Adds a test to ensure we calculate limits based on protocol value (single source of truth--previously, a `DefaultLimit` value was a duplicative/diverging source of truth)
Yes, adds a test.
=> search: add job test for default limits computed from protocol

dev/gqltest/sub_repo_permissions_test.go, internal/gqltestutil/git.go
Part of https://github.com/sourcegraph/sourcegraph/issues/27448
=> gqltest: Add file list test for sub-repo permissions

client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx
Closes #31381. 
Please make sure I am updating the right button (believe so) – this is the one I want to update:
=> update button text to say "add or remove" rather than "add" 

CHANGELOG.md
N/A as no code/config changes.
=> codeintel: Add LSIF upload perf fix to changelog.

client/web/src/enterprise/insights/pages/CodeInsightsRootPage.test.tsx, client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx
Closes https://github.com/sourcegraph/customer/issues/655
- The free trial tag should be visible if you don't have the code insights license tag.
=> Code Insights: Add free trial badge

cmd/frontend/graphqlbackend/external_service_collaborators.go, cmd/frontend/graphqlbackend/external_service_collaborators_test.go
No change in behavior, this change refactors the collaborator discovery backend and adds tests.
Part of #31277  
This PR adds tests.
=> user invites: add tests for user invites collaborator discovery backend

doc/dev/background-information/sourcegraph_extensions.md
was incorrectly formatted, update to https://github.com/sourcegraph/sourcegraph-snyk
=> fix link to snyk extension

doc/admin/auth/index.md
This is a quick addition to the docs to highlight an unusual flow issue that has come up for some customers -- more here:
https://github.com/sourcegraph/sourcegraph/issues/31192
requesting review from other teams
=> note on OAuth flow

client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx, client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
=> batches: Omit changelog for 3.37

client/web/src/enterprise/insights/modals/GaConfirmationModal.tsx
We went back and forth on this but after playing with it live [we decided this was important](https://sourcegraph.slack.com/archives/C01RVEVPWLC/p1645081762620709)
cc @AlicjaSuska to close the loop!
Copy chage.
=> insights: update modal to bold free trial notice

doc/code_insights/references/common_use_cases.md
This completely refreshes the use cases page with templates. 
The page is a bit long and nonoptimal but I expect most people to use the templates that are on the landing page, and think being exhaustive and also linked 1:1 to in-product templates is good. 
You take the file https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/insights/pages/getting-started/components/code-insights-templates/constants.ts and then put it in an IDE, rip out all the typescript parts/comment them out so it's plain vanilla JS objects, then run the below script. 
Then copy the console output to this file (and remove any gross console things like line numbers from the console output) **below the introductory paragraphs**. 
```JS
for(var section = 0; section < …
```
=> insights: add templates from template library to use cases docs page

client/web/src/enterprise/batches/settings/AddCredentialModal.story.tsx, client/web/src/enterprise/batches/settings/AddCredentialModal.tsx, client/web/src/enterprise/batches/settings/BatchChangesSettingsArea.story.tsx, client/web/src/enterprise/batches/settings/BatchChangesSettingsArea.tsx, client/web/src/enterprise/batches/settings/BatchChangesSiteConfigSettingsArea.story.tsx, client/web/src/enterprise/batches/settings/BatchChangesSiteConfigSettingsArea.tsx, client/web/src/enterprise/batches/settings/CodeHostConnectionNode.tsx, client/web/src/enterprise/batches/settings/CodeHostConnections.tsx, client/web/src/enterprise/batches/settings/RemoveCredentialModal.tsx, client/web/src/enterprise/batches/settings/backend.ts
This PR converts the user and site credential UIs to use Apollo.
I've given this a workout locally, and we have these pages in our Storybook.
=> batches: convert user and site credential UI to use Apollo

doc/admin/how-to/dirty_database.md, doc/admin/how-to/manual_database_migrations.md, doc/admin/how-to/rollback_database.md, doc/admin/install/docker-compose/operations.md, doc/admin/install/kubernetes/update.md
=> migrations: Update docs

doc/code_insights/explanations/automatically_generated_data_series.md, doc/code_insights/explanations/current_limitations_of_code_insights.md, doc/code_insights/index.md, doc/code_insights/language_insight_quickstart.md
Reverts sourcegraph/sourcegraph#31470
=> Revert "insights: remove some beta labels in prep"

CHANGELOG.md
=> changelog: cut sourcegraph@3.37.0

doc/notebooks/index.md
- N/A just a small content fix
=> remove inapplicable "language insight" starter

client/web/src/repo/components/RepoHeaderActions/RepoHeaderActions.tsx
regression from https://github.com/sourcegraph/sourcegraph/pull/29582
Check this functionality works:
=> Fix MenuButton usage

client/shared/src/components/activation/ActivationDropdown.story.tsx
Trying to fix CI issue with Chromatic.
Run `yarn storybook` to see renamed Storybook stories.
=> web: rename stories to fix Chromatic

doc/admin/external_service/bitbucket_server.md, doc/admin/external_service/github.md, doc/admin/external_service/gitlab.md, internal/repos/bitbucketserver.go
Part of https://github.com/sourcegraph/customer/issues/707
=> doc: Document that changing repo order is safe

CHANGELOG.md
=> Add changelog for migrator service to 3.37 header

.tool-versions
Executor images built in CI to test it still works.
=> Upgrade packer to version that has ARM support

internal/search/job/mapper.go, internal/search/job/types_test.go
As in title
Added a unit test.
=> search: ensure mapper cases for all jobs

internal/search/query_converter.go
Follow up of https://github.com/sourcegraph/sourcegraph/pull/31527/files#r810840028. Let's just make `fold` side-effect free.
This is difficult to test because we assume the code is unreachable. Even the `err` generated by `parseRe` is very likely cannot be triggered, because we validate the input earlier during parsing.
=> search: fix potential err capture when building Zoekt expression

cmd/frontend/graphqlbackend/search_results.go
This was only used to calculate `LimitHit` and to limit the set of
matches in the resolver on query. However, both of these functions are
now fully performed by the `Limit` job.
Covered by integration tests.
=> Search backend: remove limit from SearchResultsResolver

CHANGELOG.md
Adds a few entries that were missed in other PRs.
Proofread.
=> changelog: Update a few entries

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/install/docker-compose/aws.md, doc/admin/install/docker-compose/digitalocean.md, doc/admin/install/docker-compose/google_cloud.md, doc/admin/install/docker-compose/operations.md, doc/admin/install/docker/aws.md, doc/admin/install/docker/digitalocean.md, doc/admin/install/docker/google_cloud.md, doc/admin/install/docker/index.md, doc/admin/install/docker/operations.md, doc/admin/install/kubernetes/configure.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/dev/background-information/ci/reference.md, doc/index.md, enterprise/dev/ci/internal/ci/pipeline.go
This pull request is part of the Sourcegraph 3.37.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.37.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30051)
=> release: sourcegraph@3.37.0

internal/search/job/job.go, internal/search/query/transformer.go, internal/search/query_converter.go, internal/search/query_converter_test.go
=> search: remove unused transform argument

internal/database/mocks.go
=> dev: Needed to re-run generate.sh

internal/search/job/job.go
Main change: previously, we mutated `args` to set `args.Mode` after doing some comparisons. This PR removes the mutation/comparison on `args.Mode` before creating jobs. Please go by commit.
For context, I'm doing this stuff so I can reuse parts for optimization. Anyway, it all tends to simplify/improve when working through things.
Semantics-preserving
=> search: simplify job mode logic

cmd/frontend/graphqlbackend/search_results.go, internal/search/predicate/substitute.go
This moves `(*searchResolver).expandPredicates()` out of graphqlbackend
and to `internal/search/predicate:Expand()`. Just continuing our
slimming down of `searchResolver`.
We're getting close to being able to run search _without any dependencies
on graphqlbackend_. I'm making a big push for this now because it seems 
achievable and it means that I can build repo-aware code monitors with extremely
minimal changes (maybe none?) to our actual search code. 
Semantics preserving reorganization.
=> Search backend: move predicate expansion to predicate package

doc/admin/how-to/troubleshoot-sg-extension.md, doc/integration/editor.md
1. Update VSCE troubleshooting docs to solve VPN issue using the `sourcegraph.requestHeaders` configuration option add in v2.0.9.
2. Added color theme-related Q&A.
=> Update VSCE troubleshooting VPN section

enterprise/dev/ci/internal/buildkite/agents.go, enterprise/dev/ci/internal/buildkite/buildkite.go, enterprise/dev/ci/internal/buildkite/cache.go, enterprise/dev/ci/internal/ci/operations.go, enterprise/dev/ci/internal/ci/pipeline.go
main-dry-run 1: https://buildkite.com/sourcegraph/sourcegraph/builds/133192 
main-dry-run 2: https://buildkite.com/sourcegraph/sourcegraph/builds/133205
=> dev/ci: only apply GOPROXY on non-baremetal agents

doc/admin/external_services/postgres.md
close https://github.com/sourcegraph/sourcegraph/issues/31414
A customer is having trouble configuring sourcegraph with pgbouncer and it does require some special config, so it's worth documenting
https://github.com/sourcegraph/delivery-scratch/tree/main/2022/pgbouncer-testbed
=> doc: add usage with pgbouncer

client/browser/src/shared/code-hosts/github/codeHost.module.scss, client/browser/src/shared/code-hosts/github/codeHost.tsx
Closes [#31359](https://github.com/sourcegraph/sourcegraph/issues/31359)
See steps to reproduce in the original issue
=> bext: make code intel popup buttons smaller on GitHub

doc/batch_changes/references/faq.md
=> FAQ: Batch Changes respects .gitignore

dev/ci/go-backcompat/flakefiles/v3.37.0.json
=> backcompat: Mark TestIndexStatus as flake in 3.37

internal/search/textsearch/textsearch.go
=> search: inline SearchFilesInRepos

dev/release/release-config.jsonc
Updating release config for 3.38
N/A
=> update release config for 3.38

internal/search/zoekt/indexed_search.go
Only comments have been changed
=> search: Fix a couple of doc comments

internal/codeintel/stores/dbstore/repos.go
Make this a single query rather than two, given we don't need to avoid running out of id space due to `bigint`.
Ref https://github.com/sourcegraph/sourcegraph/pull/31722/files#r813954264
Integration test.
=> codeintel: Upsert dependency repos

cmd/gitserver/server/vcs_syncer_npm_packages.go
=> gitserver: Fix panic in NPMPackagesSyncer.commitTgz

client/web/src/integration/blob-viewer.test.ts
See https://github.com/sourcegraph/sourcegraph/issues/31806 for more
details
=> Disable flaky client integration test

client/web/src/global/CoolCodeIntel.tsx, client/web/src/global/CoolCodeIntelQueries.tsx
This fixes #31641
- Tested locally and made sure that revisions in URL match revision selector
=> Experimental ref panel: use revision in references URLs

doc/dev/background-information/insights/backend.md
Closes https://github.com/sourcegraph/sourcegraph/issues/30195
I added a section for "Running Locally" that I think will be useful. Also fixed a few broken links. Is there any other scope we want to cover here?
Merging this into the existing PR with the bulk of the changes.
Docs only change.
=> insights: More backend dev doc updates

internal/search/symbol/symbol.go
In the process of `Job` creation we obsoleted this function 🤣 
=> search: delete unused symbol Search function

internal/gitserver/gitdomain/exec.go
This landed after my PR was first opened, so completely missed :slightly_smiling_face: 
N/A
=> add --points-at to allowlist for for-each-ref

internal/search/symbol/symbol.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/31776
So I need to do the same inlining for symbol search in order to uncork repo partitioning. A side effect of this change is that I can get rid of some todo's/redundant state and create a leaner global symbol search job.
Semantics-preserving
=> search: inline symbol search for jobs

client/vscode/CHANGELOG.md, client/vscode/README.md
To follow our discussion in https://github.com/sourcegraph/sourcegraph/issues/29706, this PR:
Add version number notes and changelog to README
Add version number notes to changelog
=> VSCE: Add version number and changelog to README

.github/workflows/label-notify.yml
No review required: config change
=> Add `@michaellzc` to delivery label notify

dev/Caddyfile
Newer versions of Caddy file to start when Caddyfiles are not formatted correctly 
None
=> Run 'caddy fmt Caddyfile'

internal/extsvc/github/common.go, internal/extsvc/github/v3.go
Patch related to #25904.
Pre-requisite to #31275.
In this commit, we change the internal API `doRequest` to return a new
custom type `httpResponseState` which contains both the
`http.Response.StatusCode` and the `http.Response.Header`.
:point_right: We want to support conditional requests[0] in the GitHub
client. To do this, we need access to the response status code, which
is a 304 if the resource has not been modified since the last time
this resource was accessed. Conditional requests do not count against
the API rate limits and will helps us alleviate stress on the GitHub
API for resources that do not change very frequently most of the
time. This helps us get away with not having to implement caching of
the corresponding GitHub resources on our end and instead rely on
these …
=>  internal/extsvc/github: Return httpResponseState from doRequest 

internal/conf/reposource/npm_packages.go, internal/conf/reposource/npm_packages_test.go
=> codeintel: Allow . in package scope names.

doc/batch_changes/references/batch_spec_cheat_sheet.md, doc/batch_changes/references/batch_spec_templating.md
=> fix iterating over paths

internal/codeintel/dependencies.go, internal/search/repos/repos.go
There you go, @tsenart.
Calm down I renamed a var :laff:
=> chore: Rename `GetOrCreateGlobalDependencyService` to `GetDependenciesService`

internal/codeintel/CODENOTIFY
=> chore: Add codenotify to internal/codeintel

internal/search/zoekt/indexed_search_test.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/31902
Simplifies some tests to not rely on PatternInfo type.
=> search: simplify Zoekt job test

client/web/src/tracking/util.test.ts, client/web/src/tracking/util.ts, internal/usagestats/event_handlers.go, internal/usagestats/event_handlers_test.go
Added new value to test cases to unit tests
=> usagestats: Add utm_cid to query param allowlist

internal/trace/traceutil.go
Get Datadog traceIDs as well
Part of https://github.com/sourcegraph/sourcegraph/issues/30699
n/a
=> Add Datadog traceID support

cmd/symbols/ctags-install-alpine.sh
Includes https://github.com/universal-ctags/ctags/pull/3300
Ran locally and verified it parsed correctly.
=> Fix ctags bug by resetting protobuf syntax

internal/database/batch/batch.go
Add defer where it should've been.
N/A.
=> database: Fix duration in batch insert traces

cmd/frontend/graphqlbackend/org.go, cmd/frontend/graphqlbackend/org_invitations.go, cmd/frontend/graphqlbackend/org_invitations_test.go, internal/database/org_invitations.go, internal/database/org_invitations_test.go, internal/database/schema.md, migrations/frontend/1645635177/down.sql, migrations/frontend/1645635177/metadata.yaml, migrations/frontend/1645635177/up.sql
🐛 Fixed problem when member could not access the organization if there was an
expired invitation in the DB
🐛 Fixed problem when username based invitation was stored with an email in
the DB instead
🐛 Fixed problem when username invitation cannot be created if there is a previous
expired invitation for the user
Phew! 😫 
Tested locally, added unit test coverage as well
=> [cloud] Fix invitation bugs

go.mod, go.sum, internal/profiler/profiler.go
Add Datadog profiler
Part of https://github.com/sourcegraph/sourcegraph/issues/30699
My main concerns here are the fact that we are dropping the `defer` so we don't catch panics. 
n/a
=> Add Datadog profiler

cmd/frontend/graphqlbackend/org.go, cmd/frontend/graphqlbackend/org_invitations.go, cmd/frontend/graphqlbackend/org_invitations_test.go, internal/database/org_invitations.go, internal/database/org_invitations_test.go, internal/database/schema.md, migrations/frontend/1645635177/down.sql, migrations/frontend/1645635177/metadata.yaml, migrations/frontend/1645635177/up.sql
This reverts commit 41c631e5b92e26c33bac388bbb913fcf9254fedc.
Unit tests, tested manually, tested in CI
=> Revert "Revert "[cloud] Fix invitation bugs" (#32017)"

cmd/gitserver/main.go
Reverts sourcegraph/sourcegraph#32056
=> Revert "gitserver: read HOSTNAME env var"

doc/dev/background-information/testing_principles.md
In order to skip review, the exact string `No review required:` must be included in the test plan.
N/A, docs change only
=> Clarify formatting on no review required

dev/gqltest/search_test.go, internal/conf/conf.go, internal/conf/server.go, internal/conf/store.go, internal/gqltestutil/search.go
This commit adds a backend integration test for dependencies search with NPM package repos.
Closes #32050
Integration test!
=> dev/gqltest: Test dependencies search

doc/dev/background-information/insights/backend.md
Part of #30195
Updating our backend dev docs to reflect reality a little better. Adding @felixfbecker and @Joelkw others for proofreading (ty!)
=> insights: update dev docs

enterprise/internal/codemonitors/background/graphql.go
This is a merge issue. It's currently breaking main. 
Covered by tests. Just fixing a bad merge.
=> Search backend: fix bad merge

dev/gqltest/search_test.go
=> dev/gqltest: Skip flaky repo:deps predicate test

cmd/gitserver/server/vcs_syncer_jvm_packages.go, cmd/gitserver/server/vcs_syncer_npm_packages.go, enterprise/internal/batches/store/batch_spec_workspaces.go, enterprise/internal/batches/store/changeset_jobs.go, enterprise/internal/batches/store/changeset_specs.go, enterprise/internal/batches/testing/batch_spec_workspace_execution_jobs.go, internal/codeintel/dependencies/service.go, internal/codeintel/dependencies/store/observability.go, internal/codeintel/dependencies/store/store.go, internal/codeintel/dependencies/store/store_test.go, internal/database/batch/batch.go, internal/database/batch/batch_test.go, internal/repos/jvm_packages.go, internal/repos/npm_packages.go
This reverts commit 075097f183a995d75a952a5e98953362e4ca2edc.
REVERT!
=> Revert "dependencies api: Batch database updates (#32034)"

cmd/gitserver/server/vcs_syncer_jvm_packages.go, cmd/gitserver/server/vcs_syncer_npm_packages.go, enterprise/internal/batches/store/batch_spec_workspaces.go, enterprise/internal/batches/store/changeset_jobs.go, enterprise/internal/batches/store/changeset_specs.go, enterprise/internal/batches/testing/batch_spec_workspace_execution_jobs.go, internal/codeintel/dependencies/service.go, internal/codeintel/dependencies/store/observability.go, internal/codeintel/dependencies/store/store.go, internal/codeintel/dependencies/store/store_test.go, internal/database/batch/batch.go, internal/database/batch/batch_test.go, internal/repos/jvm_packages.go, internal/repos/npm_packages.go
Fixes broken integration tests from #32034. Only commit de2a4313b6e0c671d6f491cacc87f2abcf41a913 is relevant.
Unit and integration tests: [main-dry-run](https://buildkite.com/sourcegraph/sourcegraph/builds/135054).
=> dependencies api: Batch database updates

enterprise/internal/database/perms_store.go
We don't store the raw bitmaps anymore, we just extract the integers so
there's no use optimising them.
=> authz: No need to optimise bitmaps

cmd/frontend/graphqlbackend/email_invitation.go
Closes #31778
Updates the email texts according to our discussions [here](https://docs.google.com/document/d/18FGG8nXFnmc1b2yXhQGXq2jUReHMTvOLMMLz-We-DfY/edit#).
=> user invites: Update email text

internal/codeintel/dependencies/service.go
This commit simplifies the `lockfileDependencies` method by leveraging a
sync.Mutex instead of a buffered channel, as well as ensuring we cancel
the existing context when returning from the method.
Existing tests.
=> codeintel/dependencies: Simplify lockfileDependencies

client/web/src/enterprise/code-monitoring/CodeMonitorList.module.scss, client/web/src/enterprise/code-monitoring/CodeMonitorList.tsx
I've equalized the vertical spacing between rows to always be 1rem/16px.
- Visual inspeciton
Fixes #32105
=> code monitoring: equalize row spacing in list

cmd/repo-updater/repoupdater/server.go, cmd/repo-updater/repoupdater/server_test.go
Quick fix. Was reading some code around permissions syncing and came across this.
Inspired from
https://www.morling.dev/blog/whats-in-a-good-error-message/.
Just a change in error message.
=> cmd/repo-updater: Update error message in handleSchedulePermsSync

client/web/src/site-admin/SiteAdminFeatureFlagsPage.tsx
On fetching feature flags, rather than unwrapping the `Observable` and then wrapping it
back into an observable in `queryFeatureFlags` with `of`, leave it as an `Observable`
and use piping stuffs inside `queryFeatureFlags`. This allows the `loading` state of
`FilteredConnection` work correctly - previously, when loading, feature flags will be
`undefined` and fall back to a list of empty nodes, and the list view will show "no results"
rather than "loading".
Related to https://github.com/sourcegraph/sourcegraph/issues/31182
```
sg start web-standalone
```
Spam reload the `/site-admin/feature-flags` page, see loading indicator
=> site-admin: fix loading state when loading feature flags

internal/search/zoekt/indexed_search.go
This commit fixes the search code to always find the correct Zoekt
branch rather than assuming HEAD is in the first position, which is no
longer true since https://github.com/sourcegraph/zoekt/commit/321d522863006f83e0bc0c8a86af3b009a2c826d
Existing tests.
=> search: Find correct Zoekt branch

client/web/src/user/settings/codeHosts/CodeHostItem.tsx, client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx, enterprise/cmd/frontend/internal/auth/oauth/middleware.go
This reverts commit b5cab0e4c26a29ebb7837cdabcfe1726ed86e95e.
I suspect that it broke main. Builds:
- https://buildkite.com/sourcegraph/sourcegraph/builds/135421 (build for PR that this is reverting)
- https://buildkite.com/sourcegraph/sourcegraph/builds/135427
- https://buildkite.com/sourcegraph/sourcegraph/builds/135431
- CI on this PR
- `main-dry-run` build: https://buildkite.com/sourcegraph/sourcegraph/builds/135442
=> Revert "Ask for GitHub App OAuth and login connection during Org Code Host Connection (#32058)

internal/extsvc/github/v3.go
It's quite common to have an error with a nil response.
Confirmed a few places in the code where we are returning nil responses.
=> github: Avoid potential panic

internal/vcs/git/refs_test.go
I stumbled across some of this code, and it seemed overly generalized for adding more test cases in the future. So I've removed a bunch of single-iteration loops and factored out the common logic for some tests.
N/A.
=> Simplify tests for comparing branches/tags

client/web/src/user/settings/codeHosts/CodeHostItem.tsx, client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx, enterprise/cmd/frontend/internal/auth/oauth/middleware.go
This reverts commit 5a9a429748e6e1e6f8e53427b6a474412922bd9d.
Turns out the 4 builds on `main` were flakes:
- https://buildkite.com/sourcegraph/sourcegraph/builds/135421#680e194f-bfc8-44aa-b52e-b8252eaad0f5
- https://buildkite.com/sourcegraph/sourcegraph/builds/135427#f625f9a8-435f-413e-9a0a-173b2c63c885
- https://buildkite.com/sourcegraph/sourcegraph/builds/135431#fc75bf4f-cafc-4f4d-91c0-6b3c5e461ec9
- https://buildkite.com/sourcegraph/sourcegraph/builds/135437#5f4a9ba4-1856-4bc4-922c-4c6fada3d68f
- Buildkite
=> Revert "Revert "Ask for GitHub App OAuth and login connection during Org Code Host Connection (#32058)" (#32252)"

client/codeintellify/src/hoverifier.test.ts, client/codeintellify/src/hoverifier.ts, client/common/src/util/hashCode.test.ts, client/shared/dev/jest-environment.js
A couple of unit tests are failing from the `client/codeintelify`, `client/common packages`. Explore tests on mentioned packages, to identify/resolve cause failing test
Unit tests all passing on mentioned packages
- Execute unit test to see all tests passed
[Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-31914)
[Sourcegraph Issue](https://github.com/sourcegraph/sourcegraph/issues/31914)
[Storybook](https://client-sourcegraph-storybook-pr-268.onrender.com/)
[Web](https://client-sourcegraph-frontend-pr-268.onrender.com/)
=> [SG-31914] Fix failing unit tests on `client/common`, `client/codeintellify` packages

enterprise/internal/batches/syncer/syncer_test.go
Only a test updated and still passes
=> batches: Remove use of database.Mocks.ExternalServices

cmd/symbols/internal/database/writer/writer.go, internal/diskcache/cache.go
Refactors a function for convenient use elsewhere, such as https://github.com/sourcegraph/sourcegraph/pull/32300
Automated tests.
=> diskcache: Refactor EncodeKeyComponents

doc/code_insights/explanations/current_limitations_of_code_insights.md
Docs update – this workaround helps unblock certain uses, but we're also working on further improvements. 
No tests needed - docs only.
=> update best practices for large repository insights

client/web/src/components/externalServices/AddExternalServicesPage.tsx, client/web/src/components/externalServices/ExternalServiceWebhook.tsx
BC link fixes for #32211.
These are just updating invalid link URLs.
=> batches: fix help links

client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx, client/web/src/enterprise/insights/components/insights-view-grid/components/built-in-insight/BuiltInInsight.tsx, client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/InsightContextMenu.module.scss, client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/InsightContextMenu.tsx, client/web/src/enterprise/insights/core/backend/code-insights-backend-context.ts, client/web/src/enterprise/insights/core/backend/code-insights-backend-types.ts, client/web/src/enterprise/insights/core/backend/code-insights-backend.ts, client/web/src/enterprise/insights/core/backend/gql-api/code-insights-gql-backend.ts, client/web/src/enterprise/insights/core/backend/gql-api/gql/RemoveInsightFromDashboard.ts, client/web/src/enterprise/insights/hooks/use-delete-insight.ts, client/web/src/enterprise/insights/hooks/use-remove-insight.ts, client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/DashboardsContent.tsx, client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboards-content/components/dashboard-inisghts/DashboardInsights.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/23065
- Check that the 'Remove from this dashboard' action actually removes insight from the dashboard
- Check that other context menu items haven't been affected 
@AlicjaSuska can you please check copies and the general flow for removing insight from the dashboard.
=> Code Insights: Add "Remove insight from dashboard" context menu action

client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
Updates copy used in notice message.
Review copy.
=> Update copy in notice

dev/sg/sg_lint.go
Classic case of a closure in a for loop capturing the wrong thing (cc @davejrt as this is a [common mistake](https://eli.thegreenplace.net/2019/go-internals-capturing-loop-variables-in-closures/) that isn't always easy to spot, you probably want to take a look). 
- Tested locally, was puzzled why `sg lint docker` was giving me shell errors.
=> sg: fix lint command subcommands

internal/database/gitserver_repos.go, internal/database/gitserver_repos_test.go, internal/database/mocks.go, internal/types/types.go
This adds the SetRepoSize method to the GitserverRepos store.
This is related to #32197
Added a unit test
=> gitserver-store: add SetRepoSize method

doc/dev/how-to/testing.md
Added docs to run Percy tests locally
Followed the instructions and successfully ran the Percy tests locally
=> Add docs on how to run Percy locally

enterprise/dev/ci/internal/ci/operations.go
Cluster QA only depends on the frontend image at the moment. This can cause the cluster test to run before all images are ready.
https://buildkite.com/sourcegraph/sourcegraph/builds/136025
=> dev/ci: cluster-qa depends on all DeploySourcegraphDockerImages

doc/docsite.json
Re-indexing docs for code insights
Tested locally with same configuration
=> insights: re-index docs

enterprise/cmd/precise-code-intel-worker/main.go
=> codeintel: moar events+data from precise-code-intel-worker into honeycomb

enterprise/internal/rockskip/search.go
In #32356 I forgot to lowercase the arguments.
Indexed a Java repo with capitalized filenames and make sure symbols appear in the sidebar.
=> rockskip: Fix lowercasing

CHANGELOG.md, internal/search/result/file.go, internal/search/streaming/stream.go, internal/search/streaming/stream_test.go
=> search: deduplicate paths when selecting file paths

internal/extsvc/npm/testdata/vcr/TestGetPackage.yaml
This gets generated for me every time I run tests
=> extsvc: Commit generated test data

.github/workflows/label-notify.yml
Does not need testing. Just removing myself from the label notifications.
=> Remove myself from label notifications

client/browser/CHANGELOG.md
Update browser extension changelog before release.
- run `sg run bext`
- ensure listed changes are working properly
=> bext: update changelog

internal/search/alert.go, internal/search/alert/observer.go, internal/search/repos/repos.go, internal/search/run/repository.go
This commit introduces search alerts related to dependencies search.
Fixes #32049
Manually tested. They look good.
=> search: Dependencies search alerts

internal/repos/scheduler.go
As seen in the [Datadog profiler](https://app.datadoghq.com/profiling/search?query=service%3Arepo-updater&agg_m=%40prof_go_cpu_cores_by_top_methods.value&agg_q=%40prof_go_cpu_cores_by_top_methods.attributes.method&agg_t=avg&viz=toplist&start=1646854762093&end=1647027562093&paused=false), this accounts for a large chunk of the CPU usage
over the last two days.
There's no reason to loop over all repo updates in the priority queue
which is a huge number compared to the set of uncloned repos.
Instead we loop over the uncloned repos, updating the priority of
existing updates in the queue and inserting a new update if one doesn't
yet exist.
Existing tests.
=> repos: Reduce CPU usage of Scheduler.PrioritiseUncloned

internal/search/job/job.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/32594.
Inlines the "force result types" computation in `computeResultTypes` but keeps the mutation of job args (`jargs`) out of it. This is an intermediate step.
=> search: don't mutate job args when computing result types

internal/search/job/job.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/32595.
Just a pass to simplify control flow by a human instead of compiler :-)
Semantics-preserving
=> search: simplify result type computation control flow

client/web/src/enterprise/code-monitoring/CodeMonitorList.tsx
Noticed TS build step failing due to this on another PR.
Just an unused import fix.
=> Remove unused import

cmd/frontend/Dockerfile, cmd/github-proxy/Dockerfile, cmd/gitserver/Dockerfile, cmd/loadtest/Dockerfile, cmd/migrator/Dockerfile, cmd/repo-updater/Dockerfile, cmd/searcher/Dockerfile, cmd/server/Dockerfile, cmd/symbols/Dockerfile, cmd/worker/Dockerfile, dev/sg/Dockerfile, dev/src-expose/Dockerfile, docker-images/grafana/Dockerfile, docker-images/jaeger-agent/Dockerfile, docker-images/jaeger-all-in-one/Dockerfile, docker-images/minio/build.sh, docker-images/postgres_exporter/Dockerfile, docker-images/prometheus/Dockerfile, docker-images/syntax-highlighter/Dockerfile, enterprise/cmd/frontend/Dockerfile, enterprise/cmd/precise-code-intel-worker/Dockerfile, enterprise/cmd/symbols/Dockerfile, enterprise/cmd/worker/Dockerfile, internal/cmd/progress-bot/Dockerfile, internal/cmd/resources-report/Dockerfile, internal/cmd/search-blitz/Dockerfile, internal/cmd/tracking-issue/Dockerfile
Closes: https://github.com/sourcegraph/customer/issues/763
Several iterations of CI. We also deploy a release candidate to our managed instances during the release process.
=> docker: update alpine base image

client/web/src/notebooks/blocks/compute/component/src/Main.elm
Stacked on https://github.com/sourcegraph/sourcegraph/pull/32636.
This just factors out a record so we can persist those options as-is:
```elm 
type alias DataFilter =
{ dataPoints : Int
, sortByCount : Bool
, reverse : Bool
, excludeStopWords : Bool
}
```
They correspond to these inputs in the UI:
These are super experimental options and tied to the current demo. The utility right now outweighs hashing out a more complete way to represent data processing for demo purposes.
After this PR I need just one more that actually persists this, then Sourcegraph users can try it out.
Two commits, to kind of demonstrate how the logic and data decomposes (mostly useful if you have a cursory idea of Elm, if not, don't worry, next week I'll do a walkthrough/workshop, probably emulating exactly this …
=> notebooks: factor out data filter logic

enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
Relates to: https://github.com/sourcegraph/sourcegraph/issues/30475 and  https://github.com/sourcegraph/sourcegraph/issues/28532
=> wrap the executor queue handler in actor http middleware

client/web/src/regression/codeintel.test.ts
Nothing to test, cause we're disabling a test
=> disable flaky test: 'Code intelligence regression test suite'

cmd/frontend/graphqlbackend/affiliated_repositories_connection.go, cmd/frontend/graphqlbackend/external_service.go, cmd/repo-updater/repoupdater/server.go, cmd/repo-updater/shared/main.go, internal/extsvc/versions/sync.go, internal/repos/gitolite.go, internal/repos/sources.go, internal/repos/sources_test.go, internal/repos/types.go, internal/repos/types_test.go
Preparing a DB connection which will be used in Gitserver client
Part of https://github.com/sourcegraph/sourcegraph/issues/32315
See that no existing tests are failing
=> gitserver: add db connections which are needed for future use in gitserver client

CHANGELOG.md
=> Add changelog entry for #32481

cmd/frontend/graphqlbackend/repository_comparison.go, cmd/frontend/graphqlbackend/repository_comparison_test.go, internal/vcs/git/diff.go
Fixes #31935.
- Added unit test.
- Q: Do we have tests which use git directly instead of going through mocks?
=> Support diffing for unrelated commits.

CHANGELOG.md
=> changelog: cut sourcegraph@3.38.0

doc/dev/how-to/add_support_for_a_language.md
=> docs: Add information for configuring highlighting

internal/search/query/types.go, internal/search/query_converter.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/32705.
As in title, setup for things.
=> search: expose IncludeExcludeValues method on basic query

internal/unpack/unpack.go
Small cosmetic change.
Integration test.
=> unpack: Reuse mode variable

enterprise/cmd/frontend/internal/compute/streaming/stream.go
Currently, compute queries can run indefinitely (we seem to have some issue cancelling Zoekt searches after max timeout and also not honoring `timeout:XYZ`, I will create an issue). This PR clamps the streaming HTTP request handler by 1 minute so that I can sleep easier at night if people decide to run some ridiculous thing on Sourcegraph.com. In time it would be nice to expose this as a configurable option, there's definitely some cool things you can do if you let things run longer than a minute (build up data sets or models of stuff, for example. more code mining than anything else).
Tested manually for compute in notebooks
=> compute: clamp requests to 1 minute at most

.github/workflows/update-project-items.ps1
Maintains the status for "In Progress" and "In Review".
Doesn't affect product and only easily testable in action
=> Maintain item status in project automation

client/web/src/notebooks/blocks/compute/component/src/Main.elm, enterprise/cmd/frontend/internal/compute/streaming/stream.go
Pops an alert so you know when results are incomplete if the query didn't finish in 1 minute.
Manually tested for experimental feature.
=> notebooks: surface alert in compute block for incomplete results

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/install/docker-compose/aws.md, doc/admin/install/docker-compose/digitalocean.md, doc/admin/install/docker-compose/google_cloud.md, doc/admin/install/docker-compose/operations.md, doc/admin/install/docker/aws.md, doc/admin/install/docker/digitalocean.md, doc/admin/install/docker/google_cloud.md, doc/admin/install/docker/index.md, doc/admin/install/docker/operations.md, doc/admin/install/kubernetes/configure.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/dev/background-information/ci/reference.md, doc/index.md, enterprise/dev/ci/internal/ci/pipeline.go
This pull request is part of the Sourcegraph 3.38.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.38.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/31768)
=> release: sourcegraph@3.38.0

internal/search/job/job.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/32800.
Same idea: compute features value and set directly from job args in job definitions.
=> search: set features directly based on job args

internal/search/job/job.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/32802.
Removes access to `UseFullDeadline` via `args`.
=> search: set useFullDeadline directly without args

internal/search/job/job.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/32805.
=> search: access query directly without args

internal/search/job/job.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/32808.
=> search: don't depend on args for any job creation except repo job

sg.config.yaml
I felt _very_ left out. It damaged me emotionally.
N/A.
=> sg: use enterprise-symbols for batches as well

doc/admin/install/docker-compose/index.md, doc/admin/install/kubernetes/index.md
=> ARM / ARM64 support

doc/admin/install/docker-compose/operations.md, doc/admin/observability/logs.md
=> Doc log lvl update

cmd/frontend/graphqlbackend/repository_comparison.go, cmd/frontend/graphqlbackend/repository_comparison_test.go, internal/vcs/git/diff.go, migrations/README.md
Running backend integration tests.
=> Reland "Support diffing for unrelated commits. (#32015)"

client/web/src/notebooks/blocks/compute/component/src/Main.elm
This persists the selected tab view. Basically the final PR I _need_ to have on main before being able to share notebooks/examples and make available to all.
Manually tested for experimental feature.
=> notebooks: persist compute block view tab

enterprise/internal/authz/perforce/protects.go
=> authz: Clarify the kind of Perforce wildcards we expect

.buildkite/hooks/pre-command, dev/check/go-lint.sh
=> ci: always create annotation folder

enterprise/dev/ci/internal/buildkite/buildkite.go
Just a tiny follow-up to https://github.com/sourcegraph/sourcegraph/pull/32840/files
n/a, just a comment change
=> dev/ci: update comment, fix typo

client/web/src/communitySearchContexts/HomepageConfig.ts, client/web/src/communitySearchContexts/Julia.tsx, client/web/src/communitySearchContexts/routes.tsx, client/web/src/search/panels/__snapshots__/CommunitySearchContextPanel.test.tsx.snap, cmd/frontend/internal/app/ui/router.go
Adds Julia community search context on Cloud.
* Manual testing by visiting the `/julia` route
=> Add Julia community search context

internal/database/sub_repo_perms_store.go
=> database: Simplify by using basestore.ScanFirstBool

cmd/searcher/search/filter.go, cmd/searcher/search/filter_test.go
Refactoring commit while working on something else. We also improve the test coverage so we test corner cases.
Test Plan: CI
=> searcher: inline newIgnoreMatcher

doc/admin/external_service/bitbucket_cloud.md, doc/admin/external_service/bitbucket_server.md, doc/admin/external_service/github.md, doc/admin/external_service/gitlab.md
Docs update for https://github.com/sourcegraph/sourcegraph/pull/32768
Pure doc update.
---
Jira: CLOUD-303
=> doc: update behavior changes of code host rate limiting

doc/admin/updates/docker_compose.md
- Adds note about docker-compose version minimum requirement to reflect the new service_completed_successfully dependency condition.
=> Add note about minimum docker-compose version required

internal/search/job/job.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/32926/files.
Directly computes `fileMatchLimit`. Note this is duplicating some logic in `query_converter.go` and putting it in job creation where it's better suited. When I'm done with the pass I can remove the redundancy in `query_converter.go`.
=> search: directly compute and access file match limit in job creation

enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go, enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go
Previously, there was no backend validation that slack webhooks for code
monitors actually pointed to Slack's API. This adds a check on code
monitor creation.
cc @andreeleuterio @deflncha @limitedmage 
Added test that creation fails with invalid URL as well as unit test for valid/invalid urls.
=> Code monitors: restrict slack webhooks to only https and slack host

client/web/src/enterprise/batches/create/yaml-util.test.ts, client/web/src/enterprise/batches/create/yaml-util.ts
Closes https://github.com/sourcegraph/sourcegraph/issues/32893
Added a test suite and checked manually as well.
=> batches: Properly quote name in YAML

client/web/src/notebooks/blocks/NotebookBlock.tsx, client/web/src/notebooks/notebook/useNotebookEventHandlers.ts
* Open notebook in firefox
* Create MD block
* Create new lines with Enter
* Cursor should not jump to the end
=> notebooks: ignore Monaco key events

doc/code_search/explanations/sourcegraph_cloud.md
Visually reviewing documentation. Automated testing of links and formatting from CI pipeline.
=> Removing outdated information on Sourcegraph Cloud offering

yarn.lock
=> yarn.lock: Commit generated changes from sg start

client/web/src/notebooks/blocks/compute/NotebookComputeBlock.tsx, client/web/src/notebooks/blocks/compute/component/src/Main.elm
As in title.
I will CSS-iffy things later, this is just a quick stopgap.
Test manually for experimental feature.
=> notebooks: compute block respects light/dark theme

doc/dev/setup/troubleshooting.md
Made few edits which I think are reasonable.
Pure doc edits.
=> doc: format edits of troubleshooting

dev/sg/main.go
I was running `sg run docsite `, then I am stuck in an infinite auto-update loop :(.
It probably had something to do with `fish` shell... I am not sure, maybe I'll take another look next week
Anyway, adding `-skip-auto-update` flag to all commands is annoying, why not just allow passing flags from env var?
```
⋊> ~/C/s/sourcegraph on 03-24-dev_sg_load_flags_from_env_var ⨯ sg run docsite                                                                          18:43:51
ℹ️ Auto updating sg ...
⌛ Stashing workspace...
⌛ Setting workspace up for update...
⌛ Updating to sg@666b1298ea3883bf3c6db209fe2f044cfedd5cde...
Compiling...
_____                    _____  
/\    \                  /\    \  
/::\    \                /::\    \  
/::::\    \              /::::\    \  
/::::::\    \ …
```
=> dev/sg: load flags from env var

enterprise/internal/authz/github/cache.go, enterprise/internal/authz/github/github.go
=> authz/github: Simplify cachedGroup.key

internal/database/schema.md
Previous merges conflicted in new schema.md. This PR regenerates the schema file.
N/A.
=> ci: Fix lint on main

client/web/src/enterprise/executors/ExecutorsListPage.tsx, doc/admin/deploy_executors.md, doc/admin/executors.md, doc/batch_changes/explanations/server_side.md, doc/batch_changes/explanations/server_side_debugging.md, doc/batch_changes/explanations/server_side_getting_started.md, doc/dev/background-information/batch_changes/index.md
=> Rename SSBC to running batch changes server-side

doc/dev/how-to/monitoring_local_dev.md
=> doc/dev: Add note to avoid pain from Linux + Firewall + Grafana

CHANGELOG.md
Added a brief explanation of how to add a changelog item in the changelog read me comment.
n/a this only updates comments
=> add explanation to changelog read me section

doc/admin/auth/index.md
CI testing for links and formatting.
Visual validation on a local instance.
=> Updating auth provider docs for openID

doc/admin/install/kubernetes/helm.md
=> docs(helm): using external object storage

doc/admin/install/kubernetes/helm.md
=> docs(helm): using external pg

internal/database/postgresdsn/schema.go
=> postgresdsn: Do not show password in error message

enterprise/dev/deployment-notifier/slack.go
Slack pings should be reserved for high-signal things that require immediate attention, which a deployment is usually not, unless the author explicitly wants to monitor a change as it goes live - in which case they can opt-in to a ping with `notify-on-deploy`.
n/a
=> dev/dn: only ping authors on opt-in via PR label

internal/workerutil/dbworker/store/store.go
Related to https://github.com/sourcegraph/sourcegraph/pull/33066#pullrequestreview-921694934
Only added a comment
=> dbworker: add forward-ref to update doc when columns are changed

doc/admin/install/kubernetes/helm.md
Include documentation on how to perform an upgrade and ways to review changes using helm.
Closes https://github.com/sourcegraph/sourcegraph/issues/32748
Confirm docs look ok
=> Add helm upgrade docs

dev/ci/asdf-install.sh, doc/dev/background-information/ci/index.md, enterprise/dev/ci/internal/buildkite/agents.go, enterprise/dev/ci/internal/buildkite/feature_flags.go, enterprise/dev/ci/internal/ci/cache_helpers.go, enterprise/dev/ci/internal/ci/pipeline.go
Reverts sourcegraph/sourcegraph#33186
Ait something's borked, stateless containers not starting
=> Revert "dev/ci: switch 100% to stateless agents"

.buildkite/pipeline.yml
follow-up https://github.com/sourcegraph/sourcegraph/pull/33226
n/a
=> dev/ci: set pipeline generate agent even more granularly

doc/batch_changes/references/batch_spec_cheat_sheet.md
=> Add cheatsheet how to list modified files

internal/search/job/job.go
This just reorganizes the blocks so that toplevel conditionals group jobs by the kind they create, so:
```go
if (text search) {
... Zoekt Global, normal Zoekt, Searcher job creations
}
if (symbol search) {
... Zoekt Global, normal Zoekt, symbol search creations
}
```
Previously, whether a search was global or not were a mix of the toplevel conditionals like `if repoUniverSearch { ... }` for creating text/search jobs. I.e., it was grouped by backend/optimization, not the kind of search (text vs symbol).
The new organization is going to make it easier to remove the confusing relations between `repoUniverseSearch`, `skipRepoSubsetSearch`, and `runZoektOverRepos` which came from trying to disentangle `mode`s.
=> search: group job creation by kind of search

dev/schemadoc/main.go, internal/database/schema.codeinsights.md
resolves #19115 
Add Code Insights database to schemadoc generator.
Documentation is generated
=> Add Code Insights DB Schema docs

doc/admin/install/managed.md
Part of https://github.com/sourcegraph/infrastructure/pull/3022
Manual review in editor
=> Add comments about public instances

client/web/src/org/openBeta/JoinOpenBetaPage.tsx, client/web/src/org/openBeta/NewOrganizationPage.tsx, client/web/src/user/settings/openBetaOrgs/OrganizationsList.tsx
This PR updates 3 links related to the new open beta experience.
- TOS link
- Beta limits link
- Redirect to Getting started after org creation (new open beta org page)
- Updated copy text on the new organization list page
- [Link](https://sg-web-piros-betalinks.onrender.com)
=> [Cloud SaaS - Open Beta] - updating Tos and beta limits link

enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_tree_info_resolver.go
Missed a conditional.
Validated by hand as part of https://github.com/sourcegraph/sourcegraph/pull/33153.
=> codeintel: Hide indexer hints if root does not match

CHANGELOG.md
Add missing changelog entry.
N/A.
=> chore: Add changelog entry

internal/cmd/git-combine/git-combine.go
Restores the `limit-remote` command line argument which was removed in https://github.com/sourcegraph/sourcegraph/pull/32038
From https://github.com/sourcegraph/sourcegraph/pull/32038#issuecomment-1087641282
Ran locally.
=> git-combine: Add commit limit arg

client/web/src/org/members/OrgMembersListPage.tsx
When leaving an org, the user is no longer a member of the organization
so it does not make sense to render the organization members list
to them anymore, as it will result with an error.
Instead we should redirect to user settings, which this change achieves.
Related:
https://sourcegraph.atlassian.net/browse/CLOUD-348
Tested locally. We do not have integration or E2E tests for this functionality, so testing manually is the only way.
This feature is behind a feature flag, so no impact expected to the customers.
- [Link](https://sg-web-cloud-348.onrender.com)
=> [cloud] Redirect the user when leaving organization

client/web/src/user/settings/codeHosts/CodeHostItem.tsx, client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
This is a small PR that just cleans up some left-over nonsense from previous iterations of solutions.
Manual visual testing
- [Link](https://sg-web-pjlast-cleanup.onrender.com)
=> Remove unused props and local storage checks

client/web/src/codeintel/ReferencesPanel.module.scss, client/web/src/codeintel/ReferencesPanel.tsx, client/web/src/codeintel/useCodeIntel.ts
This doesn't change behaviour at all.
* Fixes CSS of mini code view so there's no empty margin at bottom
* Renames props so they're more consistent
* Adds a constant that was repeated
- Tested manually locally to confirm that no behaviour was changed and that the CSS fix works as intended
- [Link](https://sg-web-mrn-minor-ref-panel-fixes.onrender.com)
=> New reference panel: some minor fixes and refactorings

client/web/src/enterprise/batches/create/library/LibraryPane.module.scss, client/web/src/enterprise/batches/create/library/LibraryPane.tsx
This is a non-functional addition
- [Link](https://sg-web-mm-add-link-to-example.onrender.com)
=> Link to batch changes library repo

doc/admin/install/kubernetes/helm.md
=> Update Helm menu buttons

dev/release/release-config.jsonc
As described [here](https://github.com/sourcegraph/sourcegraph/issues/33399)
Nothing to test.
=> Release: update release config for 3.38.1 patch

CHANGELOG.md
=> update changelog for v3.38.1

client/web/src/codeintel/RepositoryMenu.story.tsx, client/web/src/enterprise/codeintel/RepositoryMenu.story.tsx, client/web/src/enterprise/codeintel/RepositoryMenu.tsx, client/web/src/enterprise/codeintel/useCodeIntelStatus.ts
Add storybook stories for new repo badge.
N/A.
- [Link](https://sg-web-ef-storybook.onrender.com)
=> codeintel: Add storybook for repo badge

cmd/gitserver/server/cleanup.go
fixing overlooked comment from https://github.com/sourcegraph/sourcegraph/pull/33487
no functional changes
=> gitserver: add some grammar to log

client/web/src/enterprise/codeintel/RepositoryMenu.story.tsx, client/web/src/enterprise/codeintel/queries.ts, client/web/src/enterprise/codeintel/useCodeIntelStatus.ts
This PR exposes additional data in the return value of the `useCodeIntelStatus` hook.
N/A.
- [Link](https://sg-web-ef-expose-moar.onrender.com)
=> codeintel: Expose additional data in useCodeIntelStatus

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/install/docker-compose/aws.md, doc/admin/install/docker-compose/digitalocean.md, doc/admin/install/docker-compose/google_cloud.md, doc/admin/install/docker-compose/operations.md, doc/admin/install/docker/aws.md, doc/admin/install/docker/digitalocean.md, doc/admin/install/docker/google_cloud.md, doc/admin/install/docker/index.md, doc/admin/install/docker/operations.md, doc/admin/install/kubernetes/configure.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/server.md, doc/index.md
This pull request is part of the Sourcegraph 3.38.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.38.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/33457)
- [Link](https://sg-web-publish-3-38-1.onrender.com)
=> release: sourcegraph@3.38.1

doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md
Followup from https://github.com/sourcegraph/sourcegraph/pull/33472#discussion_r844406509
Just docs updates.
=> Release 3.38.1: add upgrade docs for k8s and docker_compose

dev/release/release-config.jsonc
=> Update release config for 3.39

doc/dev/how-to/zoekt_local_dev.md
I added a new section on how to install universal-ctags. I also took a
brief look at the rest of the document and updated it.
Only doc changes
=> doc: update zoekt how-to

internal/cmd/search-blitz/queries_dogfood.txt
=> search-blitz: gigarepo literal queries uniq names

enterprise/internal/codeintel/policies/matcher.go, enterprise/internal/codeintel/policies/matcher_common_test.go, enterprise/internal/codeintel/stores/dbstore/commits.go, enterprise/internal/codeintel/stores/dbstore/commits_test.go, internal/gitserver/gitdomain/common.go, internal/vcs/git/commits.go, internal/vcs/git/commits_test.go
Closes #33446 
Added test-case to `TestParseRefDescriptions`.
=> gitserver: allow missing date in for-each-refs tags output

go.mod, go.sum, internal/luasandbox/CODENOTIFY, internal/luasandbox/init.go, internal/luasandbox/observability.go, internal/luasandbox/service.go, internal/luasandbox/service_test.go
This PR introduces an internal package `luasandbox` as part of [RFC 624: Configurable auto-indexing recognizers](https://docs.google.com/document/d/1LOVI6xogkt4Iifl1F_8Gb_H9pXQ_MrynW8vmr6D05A0). A partial effort towards #33042. I do not want to include any additional callback choices in this PR yet as we may iterate on that choice later.
The additional unit tests in this PR.
=> luasandbox: Initial implementation

internal/database/migration/store/describe_test.go
Remove ALTER statements from test schema input.
=> migration: Remove ALTER ... OWNER TO postgres from test input

doc/admin/install/kubernetes/configure.md
https://docs.sourcegraph.com/admin/install/kubernetes/configure "Overlays" button should load
=> Fix broken overlays link

internal/extsvc/types_test.go
Not applicable.
Added a new test case.
=> internal/extsvc: Test edge case in ExtractRateLimitConfig

client/browser/CHANGELOG.md
=> Update client/browser/CHANGELOG.md after Browser Extension release

doc/admin/install/kubernetes/helm.md
Grammar and typo fixes
Look at it
=> Helm doc typos and grammar

dev/release/src/release.ts
Standardize on `release/x.y` as the release branch name for helm charts. We're also going to keep the version and appVersion in sync.
Ran a dry-run batch change and confirmed that both sourcegraph and sourcegraph-migrator Chart.yaml's were updated and the helm docs were re-generated (no more manual steps).
=> Update release tool to version helm chart the same as other deployment repos

doc/admin/install/kubernetes/helm.md
Modifications based on notes from doc walkthrough. I recommend looking at the diff on an individual commit basis to better understand what the intent of each change is - some of this was just rearranging existing content, or formatting updates.
Doc page should render
=> Update helm docs

internal/luasandbox/sandbox_test.go
Add specific unit test for RunScript distinct from module usage.
N/A.
=> luasandbox: Add unit test

internal/gitserver/mock_client.go
=> gitserver: go generate

dev/sg/checks.go, dev/sg/sg_setup_mac.go, dev/sg/sg_setup_ubuntu.go, internal/gitserver/mock_client.go
Fixes #33151.
Uninstalled rust from my system, ran the setup wizard, and it was there!!!
=> sg setup: Add rust to language dependencies

doc/admin/external_service/github.md
N/A - updating the documentation
=> Update Doc for adding webhook to External Service

cmd/searcher/internal/search/search_test.go
This adds support for FetchTarPaths in our store fake used in searcher
tests. This isn't called yet, but will be needed in an upcoming commit.
Also factored out fetchTimeoutForCI since I want to reuse it.
Depends on #33716
=> searcher: support FetchTarPaths in test infrastructure

docker-images/postgres-12-alpine/Dockerfile
this https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/792#discussion_r845298116
No
=> Add notes to watch for pg conf changes

internal/workerutil/worker_test.go
=> workerutil: Fix flaky TestWorkerConcurrent

internal/gitserver/client.go
Dead code removed, all tests still pass
=> Remove unused method

dev/sg/sg_install.go
Since `sg update` can no longer be used to globally install a custom build of `sg`, this PR makes a few improvements such that a one-liner like the following can easily be used to install `sg` globally (e.g. to test [autocompletions](https://github.com/sourcegraph/sourcegraph/pull/33817)):
```
go build -o ./sg ./dev/sg && ./sg install -f -p=false
```
- `--force, -f`: Delete any existing `sg` installation and proceed immediately to installation
- `--profile, -p`: When set to `false`, do not prompt for an update to profile files
Stacked on https://github.com/sourcegraph/sourcegraph/pull/33758
```
go build -o ./sg ./dev/sg && ./sg install -f -p=false
```
=> dev/sg: make 'sg install' nicer to use for local dev

dev/sg/sg_ci.go
I forgot to register the `--build` flag 😆 
n/a no review required: fixing regression
=> dev/sg: fix sg ci logs --build

dev/sg/sg_version.go
Ran into this:
```
➜  sourcegraph git:(fix-ci-logs) ✗ sg version changelog
⚠️ update check: error getting new commits since fc1e1b36e0aad85fc280d0d3e00db757f1db9606 in ./dev/sg: 'git rev-list fc1e1b36e0aad85fc280d0d3e00db757f1db9606..origin/main ./dev/sg' failed: fatal: Invalid revision range fc1e1b36e0aad85fc280d0d3e00db757f1db9606..origin/main: exit status 128 - try reinstalling sg with:
curl --proto '=https' --tlsv1.2 -sSLf https://install.sg.dev | sh
```
I'm pretty sure this just happened because I updated `sg` to a revision I don't yet have locally
`sg update`, `sg version c`
=> dev/ci: fetch before update/changelog check, remove debug print

internal/extsvc/bitbucketcloud/CODENOTIFY
This probably would have avoided an annoying rebase.
N/A
=> Add self to be notified of BB Cloud changes for now.

client/web/src/codeintel/ReferencesPanel.tsx
This fixes #33539 by using the links to the repository use the `externalHistory` and not the panel-internal memory history.
- Tested manually locally
- [Link](https://sg-web-mrn-fix-repo-links-ref-panel.onrender.com)
=> New reference panel: fix repository links not working

internal/database/migration/store/store_test.go
Increase the test timeout for when an index becomes initially available in Postgres system catalogs.
N/A.
=> ci: Increase TestIndexStatus timeout

enterprise/cmd/frontend/internal/app/app.go
Just removed some duplicated code
=> frontend: Remove duplicate external service creation

enterprise/dev/ci/internal/ci/operations.go
@bobheadxi, @valerybugakov I'm putting this up as a suggestion because those flakes are really frequent these days. 
n/a
=> Retry puppeteer temporarily

doc/batch_changes/how-tos/bulk_operations_on_changesets.md
=> Update documentation for bulk operations in Batch Changes

internal/luasandbox/util.go
Pulled from #33756 so that new libs can be reviewed independently.
These are empty utilities for now. #33756 will exercise these code paths in much more detail shortly.
=> luasandbox: Add additional utils

doc/admin/updates/docker_compose.md
=> Add unreleased docker release notes

cmd/frontend/graphqlbackend/search_results.go, cmd/frontend/graphqlbackend/search_results_test.go
Just removing dead code. Issues should be caught statically.
=> Search backend: remove unused isContextError

CHANGELOG.md
Changelog notes for contexts API changes
Just a changelog
=> insights: changelog for contexts API changes

CHANGELOG.md
Change log for insights indexer updates
N/A just a change log entry
=> change log entry for indexer batching

enterprise/dev/ci/internal/ci/operations.go
Flaky, hotfix to prevent blocking the pipeline. 
n/a
=> ci: retry vscext puppeteer tests

enterprise/dev/ci/internal/ci/operations.go
Client app PR preview should not fail CI builds.
=> ci: soft fail CI preview

internal/luasandbox/util.go
=> luasandbox: Export forEach

internal/codeintel/dependencies/lockfiles/service_test.go, internal/unpack/test_pack.go, internal/unpack/unpacktest/pack.go
I'll want to use this in upcoming tests dealing with git.Archive.
N/A.
=> unpack: Extract function to create zip archive in tests

.github/workflows/label-move.yml
Split growth & integrations teams into two separate teams and add the new issues to the corresponding boards
no test plan needed
=> Update label move logic

doc/dependency_decisions.yml, go.mod, go.sum, internal/luasandbox/libs.go, internal/luasandbox/libs/json.go, internal/luasandbox/libs/paths.go, internal/luasandbox/libs/paths_test.go, internal/luasandbox/sandbox_test.go, internal/luasandbox/util/util.go, third-party-licenses/ThirdPartyLicenses.csv
Adds a few initial importable libraries (filepath (**not disk**) and json operations) in the lua sandbox.
N/A (code currently unused).
=> luasandbox: Add initial libraries

client/web/src/notebooks/listPage/NotebooksGettingStartedTab.tsx
- [Link](https://sg-web-rn-notebooks-getting-started.onrender.com)
=> Notebook getting started tab tweaks

doc/admin/observability/alert_solutions.md, monitoring/definitions/repo_updater.go
=> monitoring: Update description for user added code alert

CHANGELOG.md
Non-code change
---
Part of CLOUD-222
=> [CLOUD-222] CHANGELOG: add entry for account lockout

doc/batch_changes/explanations/permissions_in_batch_changes.md
=> Making namespace permissions clearer

internal/luasandbox/libs/paths.go
Add `filepath.Join` to luasandbox.
N/A.
=> luasandbox: Add paths.join method

cmd/gitserver/main.go
We now sync rate limiters from config on stratup and periodically in the
background. This is consistent with what we do in repo updater and
ensures that we adhere to the rate limits set in config.
Same code is run in repo-updater. Also tested locally to confirm rate limits are
set during startup.
=> gitserver: Sync rate limiters

client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx, client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
Still pending wording / items.
Verified it shows and looks correct.
- [Link](https://sg-web-es-changelog-339-bc.onrender.com)
=> Add in-app changelog for Batch Changes for 3.39 release

internal/repos/syncer.go
Before we only logged when there was an error syncing in the background,
we now also log when doing a blocking sync. This should help us track
down spikes in errors syncing repos.
Only changes to logs
=> repos: Always log errors from SyncRepo

doc/cli/references/lsif/upload.md
This can be tested by running `sg run docsite` and navigating to the corrected page.
=> Update upload md

internal/vcs/git/blob.go
ReadFile has a bit more business logic since we introduced
FilterActorPath. Lets rather make it wrap NewFileReader so that it
doesn't need to duplicate that work and instead only handles what is
unique to it.
This also makes it much more clear that this is a convenience function
for future refactors.
The functional change here is we will now have an extra span in our
tracing for every ReadFile call. This seems fine and potentially useful
from the perspective of differentiating the time it takes to start
reading and the time it takes to read.
This is a random improvement I noticed. Feel free to not approve.
Test Plan: CI
=> git: ReadFile calls NewFileReader

client/browser/src/shared/code-hosts/gitlab/codeHost.ts, client/browser/src/shared/code-hosts/shared/codeHost.tsx, client/codeintellify/src/hoverifier.ts, client/codeintellify/src/overlayPosition.test.ts, client/codeintellify/src/overlayPosition.ts, client/codeintellify/src/types.ts, client/shared/src/hover/HoverOverlay.tsx
Fixes https://github.com/sourcegraph/sourcegraph/issues/33987
Existing tests and ran locally.
- [Link](https://sg-web-fix-hover-reposition-jank.onrender.com)
=> codeintellify: Fix hover reposition jank

enterprise/dev/deployment-notifier/slack.go
If I deploy a change to a particular service, I'd like to be able to only get notified when my change is deployed for that service (i.e. if I bump Prometheus, I do not want to know when frontend etc gets rolled out)
To enable this, add a check for labels `service/...` and only notify if the set of changed services includes the specified labels. If no such labels are specified, notify on all deployments
For example: https://github.com/sourcegraph/sourcegraph/pull/33927
n/a
=> dev/dn: allow 'service/...' labels to specify when to get notified

doc/admin/how-to/redis_configmap.md
=> docs: fix typo in redis configmap how-to

CHANGELOG.md
=> changelog: cut sourcegraph@3.39.0

internal/search/run/repo_has_file.go
We only construct newArgs in order to then refer to its fields later. We
can just reference the fields directly to avoid building a type where we
don't actually use all the fields later.
Also fixes some complaints in my editor.
Semantics-preserving, covered by tests.
=> Search backend: remove ephemeral object newArgs

client/web/src/codeintel/useSearchBasedCodeIntel.ts
Seen in [Slack](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1650386524227359).
TBD
- [Link](https://sg-web-fix-local-null.onrender.com)
=> New reference panel: check for null local payload

internal/database/external_services.go, internal/database/external_services_test.go
=> database: Allow listing external services based on ther update time

doc/admin/troubleshooting.md
Add > WARNING: Running Sourcegraph on ARM / ARM64 images is not supported for production deployments.
Yes
=> Update troubleshooting.md with Windows warning

doc/admin/troubleshooting.md
> WARNING: Running Sourcegraph on Docker Toolbox for Windows is not supported for production deployments.
=> Sourcegraph on Docker Toolbox for Windows

doc/cloud/cloud_ent_on-prem_comparison.md, doc/cloud/getting_started_on_cloud.md, doc/cloud/index.md, doc/cloud/organizations/adding_your_org_repos_to_cloud.md, doc/cloud/organizations/code_visibility_teams_sourcegraph_cloud.md, doc/cloud/organizations/creating_your_org_on_cloud.md, doc/cloud/organizations/deleting_org_on_cloud.md, doc/cloud/organizations/get_started_with_orgs_cloud.md, doc/cloud/organizations/inviting_users_to_org_on_sourcegraph_cloud.md, doc/cloud/organizations/searching_org_repo_sourcegraph_cloud.md, doc/code_search/explanations/code_visibility_on_sourcegraph_cloud.md, doc/code_search/explanations/sourcegraph_cloud.md
No test plan required; only documentation updates.
=> Remove cloud waitlist from docs

CHANGELOG.md
Context: https://github.com/sourcegraph/sourcegraph/pull/34134#issuecomment-1103478591
Test Plan: n/a
=> changelog: defaultRateLimit entry is for 3.39

dev/release/src/github.ts
The recent commit which added --reference-if-able assumed we always
cloned sourcegraph/sourcegraph. However, commands such as "yarn release
release:stage" clone the about repo. We didn't fail in those cases, but
by adjusting how we pick the reference we will often get the same
benefits.
Test Plan: dry run without main branch check then ran the release
command.
=> dev/release: support reference clones for other repos

.github/workflows/label-notify.yml
Removing myself to reduce notification noise.
=> Remove Maria from issue notifications

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/install/docker-compose/aws.md, doc/admin/install/docker-compose/digitalocean.md, doc/admin/install/docker-compose/google_cloud.md, doc/admin/install/docker-compose/operations.md, doc/admin/install/docker/aws.md, doc/admin/install/docker/digitalocean.md, doc/admin/install/docker/google_cloud.md, doc/admin/install/docker/index.md, doc/admin/install/docker/operations.md, doc/admin/install/kubernetes/configure.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/dev/background-information/ci/reference.md, doc/index.md, enterprise/dev/ci/internal/ci/pipeline.go
This pull request is part of the Sourcegraph 3.39.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.39.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/32836)
cc @keegancsmith
=> release: sourcegraph@3.39.0

dev/release/release-config.jsonc
=> dev/release: update config for v3.40.0

enterprise/dev/ci/internal/ci/operations.go
Publish storybook link only in PRs.
n/a
=> ci: post storybook link only in PRs

doc/admin/install/docker/operations.md
Link for Single Container Docker went to Pure Docker notes.
N/A
=> Fixed link to update/upgrade notes.

internal/gitserver/client.go, internal/gitserver/client_test.go
This PR is another step towards making it possible to run tests without gitserver server instance running, which is needed for further refactoring (https://github.com/sourcegraph/sourcegraph/issues/33280)
This allows using GitCommand interface implementation (LocalGitCommand) for tests which don't need a running Gitserver instance.
Closes https://github.com/sourcegraph/sourcegraph/issues/34258
New test case added
=> gitserver: add functionality to run git commands locally

internal/search/run/repo_has_file.go, internal/search/zoekt/indexed_search.go
Just a cleanup pass of the things that don't fit in other PRs. Details inline.
Semantics-preserving and minimal changes.
=> Search backend: minor tidying

enterprise/internal/codeintel/stores/dbstore/uploads.go
Addresses serious SQL query degradation where joins on lsif_packages, lsif_references and lsif_uploads would cause essentially non-terminating queries. Fixed by moving the join on `lsif_packages` outside the CTE.
The crux of the issue appears to be a missed optimization opportunity from Postgres on deferring the `JOIN` on `lsif_references` inside the `ranked_dependents` CTE. In the case of there being a very large number of rows from `lsif_references` that match the join predicate on `lsif_packages`, the rank+sort take a large amount of time due to the hugely inflated number of rows, which could've been avoided as `lsif_references` is not used in the rank+sort. 
In other terms, where `ƒ(RANK_SORT(A x B) x C) ≡ ƒ(RANK_SORT(A x B x C))` and `SIZE(A x B x C) >> SIZE(A x B)`, it makes no …
=> codeintel: improve LSIF dependents sql query CTE

internal/codeintel/policies/service.go
Appeases new linting rules for Go.
N/A.
=> chore: Fix unused variables

enterprise/cmd/frontend/internal/codeintel/httpapi/auth_middleware.go
See https://github.com/sourcegraph/src-cli/pull/729.
This is an error text change only.
=> codeintel: Match unsupported code host error with src-cli

internal/codeintel/dependencies/service.go
=> dependencies: Simplify errors

cmd/symbols/squirrel/hover_test.go, cmd/symbols/squirrel/languages.go, cmd/symbols/squirrel/local_code_intel_test.go
This reverts commit f9fadf486fd86d972b82bea14c9c2aabf97e47af.
[main-dry-run](https://buildkite.com/sourcegraph/sourcegraph/builds/143817)
=> Revert "Squirrel: Add more language support (#33689)"

cmd/symbols/shared/main.go
In every other package (except frontend) we initialize all
instrumentation before doing anything service specific. This makes
symbols consistent with that. It also likely removes subtle bugs like
the call to "log15.Root()" returning something different since
"logging.Init()" hasn't run yet.
Test Plan: CI
Depends on https://github.com/sourcegraph/sourcegraph/pull/34329
=> symbols: initialize instrumentation before service code

internal/gitserver/client_test.go, internal/gitserver/test_utils.go
Follow up to https://github.com/sourcegraph/sourcegraph/pull/34276 for further test writing convenience
No functional change, existing tests should pass
=> gitserver: extract creating and deleting of tmp directories for repo tests to separate function

monitoring/definitions/zoekt.go
@stefanhengl and I realized that the heat maps on the Zoekt dashboards were broken. They didn't include data-points (like lengthy indexing durations) that we knew existed (we could see them in the logs).  
It turns out that we weren't using the right Grafana incantations to inform it that the data source that we're using for the heatmap is already bucketed - it doesn't need to recreate its own buckets. We fixed that configuration, and also changed the heatmap to use a higher-contrast color scheme. 
Before:
After:
See [this blog post](https://grafana.com/blog/2020/06/23/how-to-visualize-prometheus-histograms-in-grafana/) for the guide that we followed. 
We used the local monitoring stack with sourcegraph.com's Prometheus instance to see that these changes fixed the issue.
=> monitoring: zoekt: fix heatmap configuration

dev/sg/internal/usershell/usershell.go
This caused problems before for oh-my-zsh users in the form of `sg
start` being stuck, because the checks it runs restarted ZSH under the
hood and oh-my-zsh was waiting for user input ("Do you want to update
oh-my-zsh?").
This fixes #33431.
Listen to this:
- Installed `oh-my-zsh`
- Changed its source to _always_ auto-update
- Ran `sg start`
- Saw the `checks` hanging
- Added the changes in this PR, reran `sg start`, everything passed 🎉
=> sg: disable oh-my-zsh auto-updates when reloading shell env

client/web/src/codeintel/ReferencesPanel.mocks.ts, client/web/src/codeintel/ReferencesPanel.test.tsx, client/web/src/codeintel/ReferencesPanel.tsx, client/web/src/repo/blob/Blob.tsx
Not many assertions yet, but this is the basic skeleton (that I also
want to clean up in follow-up PRs).
Assertions follow in other PRs.
@umpox added you so you can do a sanity check. Also: I changed the props for the `<Blob />` component to be a bit smaller (making them easier to mock). I tested this locally in the web app. Everything still works.
- Run this test locally
- [Web](https://sg-web-mrn-first-ref-panel-test.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-fozwbtdkbe.chromatic.com)
=> Add first high-level test for new reference panel

client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/ConfirmDeleteModal.tsx
removed stray $
resolves #34219
visual compare:
Before: 
After:
- [Link](https://sg-web-cw-fix-delete-title.onrender.com)
=> insights: remove stray characters

enterprise/cmd/worker/internal/codeintel/janitor/hard_delete.go, enterprise/internal/codeintel/stores/dbstore/helpers_test.go, enterprise/internal/codeintel/stores/dbstore/uploads.go, enterprise/internal/codeintel/stores/dbstore/uploads_test.go
I have no idea what happened but its this: https://github.com/sourcegraph/sourcegraph/pull/34354
see https://github.com/sourcegraph/sourcegraph/pull/34354
=> codeintel: fix hard deleter not deleting uploads from deleted repos

.github/workflows/update-project-items.ps1
Testing in production! Just affects tooling, not product.
=> Invert label check condition

internal/search/job/jobutil/combinators.go, internal/search/job/jobutil/combinators_test.go, internal/search/job/jobutil/mapper.go, internal/search/job/jobutil/printers.go, internal/search/job/jobutil/types.go
As in title/docstring.
Added unit tests.
=> search: add sequential job runner

lib/log/logger.go
I got the condition inverted 😬 
n/a
=> lib/log: fix safe-get condition in production

doc/admin/install/index.md
=> Fix deployment types table

cmd/symbols/squirrel/hover_test.go, cmd/symbols/squirrel/languages.go, cmd/symbols/squirrel/local_code_intel_test.go
- #33689 Original PR ❌ broke the Docker build because it needs g++ and there's no musl-g++ that I could find
- #34316 Reverted
- #34335 Fixed the underlying problem
- **This PR** 👈 reapplies the original PR
=> Squirrel: Add more language support 2

internal/search/job/jobutil/job.go, internal/search/job/jobutil/job_test.go
I'm expanding the GQL endpoint to return representations of a query. I want it to return:
- parse tree
- unoptimized (generic) job tree
- optimized job tree
It will make debugging and introspection easier, especially for optimizations--these are going to come up more often for commits, or-expressions over regexp/repos, etc.
Problem is, current job logic for optimization makes it difficult to get an unoptimized representation, because there's no control over whether we run that pass. This PR factors out optimization to be a function that gets passed in (and which can be the identity function) so it's easy to get an unoptimized tree.
This has a nice side effect, where it's easier to test the _end-to-end_ optimized vs unoptimized representation over the entire plan (previously, I just hooked …
=> search: factor out logic for job optimization

internal/repos/purge.go
Possible follow-up to https://github.com/sourcegraph/sourcegraph/pull/33276
Success log will spam a lot during initial run against 900k repos, but I'm not 100% sure that we want to miss repo names which were purged.
Another way is to add a label to success monitoring, but it is a less convenient way of looking for repo names which were purged.
No functional changes
=> repo-updater: remove log, cleanup comments in purge worker

cmd/gitserver/server/vcs_dependencies_syncer_test.go
Somehow this didn't trigger in PR CI, so broke main.
N/A
=> gitserver: Fix unparam lint error

internal/search/job/jobutil/job.go
=> search: fix unintended type alias definition

doc/getting-started/index.md
Improves the /getting_started page of the documentaiton to list additional major features.
Manually review added links to ensure the link to the correct location.
=> Improve major features

internal/search/job/observe.go
This reduces the number of logs added to search job traces. I'd
previously implemented a wrapper that logs every time a search event
came through, but that ended up being pretty verbose and not super
useful. Additionally, I started seeing logs about traces being too
large, and I have a feeling that may have been contributing.
Instead, each job logs an event to its trace on the first streamed
result, and adds a tag with the total number of results sent when the
trace finishes. This removes the "only do this if tracing is enabled"
logic since it reduces the overhead to an atomic add for each event.
FYI @tbliu98, this change is in the same domain as #34009, which 
I believe is slated to be one of your first issues to look at. No need 
to take a close look at this until then, but I figured …
=> Search backend: simplify search job traces

dev/release/release-config.jsonc
Updating release config for 3.39.1
N/A because its a patch
=> 3.39.1 release config

CHANGELOG.md
Just a changelog update for patch release.
=> add changelog entry for notebooks fix

CHANGELOG.md, client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/install/docker-compose/aws.md, doc/admin/install/docker-compose/digitalocean.md, doc/admin/install/docker-compose/google_cloud.md, doc/admin/install/docker-compose/operations.md, doc/admin/install/docker/aws.md, doc/admin/install/docker/digitalocean.md, doc/admin/install/docker/google_cloud.md, doc/admin/install/docker/index.md, doc/admin/install/docker/operations.md, doc/admin/install/kubernetes/configure.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/index.md
This pull request is part of the Sourcegraph 3.39.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.39.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34545)
=> release: sourcegraph@3.39.1

internal/repos/metrics.go
Count the number of deleted repos that are still cloned on disk.
Tested locally
=> repo-updater: Instrument the number of repos that can be purged

docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
Noah and I were reading through the code and while trying to understand
how it works we played around with some things and tried to refactor
them or move them around.
This is the result. Nothing here is "I need to get this merged, asap!",
it's all "eh, if you like it, cool, if not, I'll close this PR".
Existing tests
=> syntax-highligher: tiny refactors as we went along

cmd/frontend/internal/highlight/highlight.go
`highlightOp` was never initialized following https://github.com/sourcegraph/sourcegraph/pull/34456/files. I'm not sure if this is the best way to do this, but `main` is currently broken, so I'll leave it to others to clean it up if they have a better pattern for this.
Tested locally that panic does not occur.
=> fix panic in highlighting code from nil Operation

dev/sg/sg_db.go
Fixes #34579
Tested locally, was able to add a user after.
=> sg: fix db add-user incorrect flags

internal/search/job/jobutil/job.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/34552.
No clash on `zoekt` access now 🙌 . Will maybe destutter things later.
=> search: rename zoektutil -> zoekt in job logic

client/branded/src/components/__snapshots__/alerts.test.tsx.snap, client/shared/src/hover/__snapshots__/HoverOverlay.test.tsx.snap, client/web/src/enterprise/search/stats/__snapshots__/SearchStatsPage.test.tsx.snap, client/web/src/enterprise/user/productSubscriptions/__snapshots__/NewProductSubscriptionPaymentSection.test.tsx.snap, client/web/src/global/__snapshots__/Notices.test.tsx.snap, client/web/src/site/__snapshots__/LicenseExpirationAlert.test.tsx.snap, client/web/src/user/settings/emails/AddUserEmailForm.tsx, client/web/src/user/settings/emails/UserEmail.tsx, client/web/src/user/settings/privacy/UserSettingsPrivacyPage.tsx, client/wildcard/src/components/Alert/Alert.test.tsx, client/wildcard/src/components/Alert/Alert.tsx, client/wildcard/src/components/Alert/__snapshots__/Alert.test.tsx.snap, client/wildcard/src/components/Feedback/FeedbackPrompt/__snapshots__/FeedbackPrompt.test.tsx.snap, client/wildcard/src/index.ts, client/wildcard/src/utils/index.ts, client/wildcard/src/utils/screenReaderAnnounce.ts, doc/dev/background-information/web/accessibility/detailed-checklist.md, package.json, yarn.lock
Closes https://github.com/sourcegraph/sourcegraph/issues/34504
Closes https://github.com/sourcegraph/sourcegraph/issues/32376
We're predicting that we'll encounter a lot of accessibility issues due to important messages not being read out by screen readers, this PR aims to fix that for most cases, and make it simple to fix for other cases.
This PR does two things:
- Adds `role="alert"` to `<Alert />`
- Ensures any visual alerts are announced to screen readers
- Adds `screenReaderAnnounce` to Wildcard.
- Ensures we can still programmatically call out important messages to screen reader users. This helps in areas where we don't have a visual representation of a "success" or "error" state, and instead rely on that information being inferred somehow by the user.
To show how these are …
=> Accessibility: Support global announcements

enterprise/internal/authz/bitbucketserver/integration_test.go, enterprise/internal/authz/bitbucketserver/provider_test.go, internal/extsvc/bitbucketcloud/client_test.go, internal/extsvc/bitbucketcloud/main_test.go, internal/extsvc/bitbucketcloud/pull_requests_test.go, internal/extsvc/bitbucketcloud/repositories_test.go, internal/extsvc/bitbucketcloud/users_test.go, internal/extsvc/bitbucketserver/client_test.go, internal/extsvc/bitbucketserver/testing.go
=> bitbucket: Use t.Cleanup() for vcr tests

cmd/gitserver/server/repo_info.go, cmd/gitserver/server/server_test.go
=> gitserver: /delete should handle deleted repos

enterprise/dev/deployment-lag-notifier/Makefile, enterprise/dev/deployment-lag-notifier/github.go, enterprise/dev/deployment-lag-notifier/main.go, enterprise/dev/deployment-lag-notifier/slack.go
Small update. Noticed a little bit of spam that was causing unnecessary notifications. Add some additional logging.
Unit tests, manual verification.
=> notifier: clarify template a little, add logging

cmd/github-proxy/github-proxy.go
=> github-proxy: initialize and use lib/log

client/web/src/enterprise/codeintel/badge/components/IndexerSummary.module.scss, client/web/src/enterprise/codeintel/badge/components/IndexerSummary.tsx, client/web/src/enterprise/codeintel/badge/components/RequestLink.module.scss
Update badge styles to match target Figma.
N/A.
- [Web](https://sg-web-ef-badge-styles.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-jgsmwbnisa.chromatic.com)
=> codeintel: Fix badge styles

doc/dev/background-information/web/accessibility/how-to-audit.md
Using `tab` isn't always going to be the case, as need other keys to action items, navigate in menus etc
N/A - Docs only change
=> Accessibility docs: Update keyboard instructions

internal/workerutil/worker.go, internal/workerutil/worker_test.go
This PR fixes the `Stop()` method to be _properly_ graceful. We achieve this by using a different context for dequeue operations and handler operations. Stop now cancels the dequeue context but does not affect the root context that is passed into the handlers, so they can remain live while the worker waits for them to finish.
*Relevant behavior changes*: Currently, a signal will call `Stop` on the worker util, which cancels all contexts in the dequeue loop _and_ the handler. After this PR, `Stop` will no longer cancel already dequeued jobs, making this method graceful.
Product teams have likely assumed this was the case, but this may be a behavioral change for DevOps. See a related increase of graceful shutdown period [here](https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/1557 …
=> workerutil: Use correct contexts for handlers

internal/workerutil/worker.go
Forgot to update this comment.
N/A.
=> chore: Update comment

internal/repos/metrics.go
=> repos: Blocked repos should also be counted as purgeable

lib/log/logger.go
I notice that the debug lines we print to document information about logger scopes will point to `lib/log` instead of the line of scope creation, so we add a caller skip to correct this.
This doesn't remediate the issue for `observation.Context.Operation`'s usage of `.Scoped` but can address in a follow-up (https://sourcegraph.com/github.com/sourcegraph/sourcegraph@17100e5895c086e0387c0f5e7416ca5c6be8b24c/-/blob/internal/observation/observation.go?L144-152), it's a bit clunky ergonomics-wise
```
sg start --debug=enterprise-frontend
```
=> lib/log: add caller skip to point to line of Scope creation

doc/dev/background-information/web/web_app.md
Not never...always? Perhaps not. Probably just means never, or not ever. Never sounds less grrrrr and more heeeey.
n/a
=> not never -> never

doc/dev/background-information/web/accessibility/how-to-audit.md
Some aspects of keyboard navigation aren't obvious - this helps inform us before we do audits
N/A - Docs only
=> Accessibility docs: Add keyboard navigation guidance

cmd/frontend/internal/highlight/language.go
Enable C# for default highlighting with tree-sitter and enable other languages to be added easily
- Run tests w/ configuration and make sure it still updates for the languages
- C# should highlight w/ tree-sitter by default now (with no configuration)
=> syntax-highlighting: default C# to tree-sitter highlighting

client/search-ui/src/components/CommitSearchResultMatch.tsx, client/shared/src/components/Markdown.tsx
Part of #34237
- Verified no visual changes
- All tests pass
- [Web](https://sg-web-jp-commitsearchresultmatchfn.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-jmxmasvtiu.chromatic.com)
=> chore: refactor CommitSearchResultMatch into a functional component

dev/sg/sg_ci.go
The runtype branches are intentionally disposable, so we should force push by default.
Also bumps the timeout for build polling because I've seen it time out a few times
n/a
=> dev/sg: force push by default with runtype builds, increase timeout

enterprise/dev/ci/scripts/compare-hash.sh
When I bump the go version to go1.18 the executor step fails since when it does compare hash it doesn't correctly use the older go1.17. Running it fixes it.
Test Plan: CI main-dry-run will exercise compare-hash. When cherry-picked onto the go1.18 branch it turns the build green.
=> ci: run asdf in compare-hash

internal/search/types.go
Ignore return values in a consistent manner in this method.
N/A
=> Ignore fmt.Fprintf() return values in RepoOptions.String()

dev/sg/sg_setup.go, dev/sg/sg_setup_mac.go, dev/sg/sg_setup_shared.go, dev/sg/sg_setup_ubuntu.go
- Add gcloud setup via interactive installer
- Add gcloud auth setup and gcloud credentials setup
- "set up" is the verb, "setup" is the noun 😋 
Changed the check to intentionally fail and ran through the installation myself
=> dev/sg: add gcloud setup, fix 'setup' -> 'set up'

CHANGELOG.md, client/shared/src/search/query/filters.ts, client/shared/src/search/query/hover.test.ts, internal/search/query/fields.go, internal/search/query/transformer_test.go
Part of https://github.com/sourcegraph/sourcegraph/issues/34395
See [RFC 675 decision log](https://docs.google.com/document/d/1KebTihO_jrPcLblgeT4X428kfgs42NkFz_3kCr8bT0M/edit#heading=h.hbwoxn8m6e4u)
Added unit test.
=> search: alias 'path:' to 'file:'

cmd/worker/memo/memo.go, cmd/worker/workerdb/db.go, enterprise/cmd/worker/internal/batches/dbstore.go, enterprise/cmd/worker/internal/codeintel/clients.go, enterprise/cmd/worker/internal/codeintel/codeinteldb.go, enterprise/cmd/worker/internal/codeintel/dbstore.go, enterprise/cmd/worker/internal/codeintel/lsifstore.go, enterprise/cmd/worker/internal/executorqueue/config.go
🎉 the first generics PR to sourcegraph/sourcegraph
Should be caught by existing unit tests and the compiler
=> generics: make MemoizedConstructor generic

enterprise/internal/codemonitors/search.go
This just adds a small optimization that skips searching a repo if there
have been no new commits since the last search. The idea is just to cut
down on the number of network roundtrips in the default case.
Depending on existing tests.
=> Code monitors: small roundtrip optimization

CHANGELOG.md
Batch changes fix has been merged into the 3.39.1 docker-compose branch.
Doc change only
=> Add changelog entry for batch changes on docker compose

internal/codeintel/autoindexing/internal/inference/init.go, internal/codeintel/autoindexing/internal/inference/service.go
Address missing feedback in #35051 (automerge was on).
=> codeintel: Respond to missed inference service feedback

.github/workflows/batches-notify.yml
Add Randell, new engineer on Batch Changes, to batches-notify.yml
Such a small change does not need a test plan
=> Add Randell to batches-notify.yml

internal/errcode/code.go, internal/extsvc/github/v3.go, internal/repos/syncer.go
Closes https://github.com/sourcegraph/sourcegraph/issues/35046
Confirm that repos with this status are removed, for example:
[LagradOst/PaladinsHackPublic](https://github.com/LagradOst/PaladinsHackPublic)
=> repo-updater: Delete repos that are unavailable for legal reasons

enterprise/internal/database/perms_store.go
Only a refactor, all unit tests still pass
=> permissions: Remove some code duplication using generics

cmd/searcher/internal/search/search_structural.go
We previously had a pretty low value Info log whenever we did a structural search. Instead we now will have a span. Also removed is what I assume is a very rarely used Debug log. I could keep it, but don't think its worth wiring up to get access to a span/logger.
=> searcher: use opentracing for structural search

doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md
upgrade notes for https://github.com/sourcegraph/deploy-sourcegraph/pull/4126
docs change
=> docs: add cadvisor privileged upgrade notes

internal/database/basestore/rows.go
Use a generic.
Compilation errors should catch anything that's wrong.
=> generics: Update basestore scan functions

enterprise/internal/codeintel/stores/dbstore/uploads.go, internal/database/basestore/rows.go
This PR propose adding `NewSliceScanner` and `NewFirstScanner` as the primitives of basestore scanner factories. See the reduction of usage within the file, and also see a sample usage in `enterprise/internal/codeintel/stores/dbstore/uploads.go`, which we replicate incrementally through the rest of the codebase.
Compiler and existing unit tests.
=> basestore: Refactor scan primitives

dev/gqltest/search_test.go
=> test: delete stale comment

internal/search/result/commit.go
Prep for integrating Camden's diff parsing/result type.
=> search: simplify select on diff additions/removals

monitoring/monitoring/monitoring.go
This PR can stop rendering of alerts-related stuff on dashboard when no alert is defined in any one of the `Observable`
Setup kubectl context to dogfood
```sh
kubectl port-forward svc/prometheus 30090
```
```sh
cd monitoring && go generate ./...
```
```sh
sg run grafana
```
=> monitoring: hide alerts table

enterprise/dev/ci/internal/ci/cache_helpers.go
https://app.incident.io/incidents/101
main-dry-run: https://buildkite.com/sourcegraph/sourcegraph/builds/146612
=> dev/ci: disable yarn cache for now

cmd/gitserver/server/vcs_syncer_python_packages_test.go
The golden files were updated every time the test ran.
existing tests
=> gitserver: fix update of golden files

dev/sg/sg_ci.go
=> sg: fixes #35252

dev/sg/sg_lint.go
Allow `sg lint [lint] [lint] [lint]` - will be useful for https://github.com/sourcegraph/sourcegraph/issues/33363
Tab on first arg for full autocompletions:
Tab on second to continuously get autocompletions for other available checks:
Specify exactly the lint targets you want to run:
Default behaviour is still to run all:
=> dev/sg: allow providing list of lints to run

client/web/src/batches/icons.tsx, client/web/src/enterprise/batches/detail/changesets/ChangesetStatusCell.tsx, client/web/src/enterprise/batches/list/BatchChangeListPage.module.scss, client/web/src/enterprise/batches/list/BatchChangeListPage.tsx, client/web/src/enterprise/batches/list/BatchChangeNode.module.scss, client/web/src/enterprise/batches/list/BatchChangeNode.tsx, client/web/src/enterprise/batches/list/BatchChangeStatePill.tsx
Tested with screen reader to make sure the page is now more accessible.
Closes #34669, #34666
- [Web](https://sg-web-bo-fix-accessibility-issues.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-klwluksenr.chromatic.com)
=> Batches: fix accessibility issues

internal/gitserver/git_command.go
Only handling a previously ignored error
=> gitserver: Update comment and handle close error

internal/repos/syncer.go
We're seeing batching of errors due to our internal rate limiter and
want to confirm that only one in flight sync is happening.
We now log the error outside of the sync group and also indicate whether
the result was shared by more than one request.
Just logging changes
=> repos: Log more info from call to syncgroup

cmd/frontend/graphqlbackend/codeintel.go, cmd/frontend/graphqlbackend/codeintel.graphql, enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/documents_connection.go, enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/upload.go, enterprise/cmd/frontend/internal/codeintel/resolvers/iface.go, enterprise/cmd/frontend/internal/codeintel/resolvers/mock_iface_test.go, enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_resolver.go, enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go, enterprise/internal/codeintel/stores/lsifstore/documents.go, enterprise/internal/codeintel/stores/lsifstore/documents_test.go
Adds additional data for use in https://github.com/sourcegraph/sourcegraph/issues/31180
Tested by hand, more to do?
=> codeintel: expose documents contained in LSIF upload

client/web/src/batches/icons.tsx, client/web/src/enterprise/batches/list/GettingStarted.tsx
Tested with screen reader to ensure the icons are presentational 
- [Web](https://sg-web-bo-make-tutorial-icons.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-yxcxshhtwh.chromatic.com)
=> batches getting started: make tutorial icons presentational

dev/check/go-generate.sh, dev/generate.sh, doc/dev/background-information/dependencies_and_codegen.md, enterprise/dev/generate.sh, migrations/README.md
`sg generate` doesn't have everything yet, but it's got the go generate stuff :)
n/a
=> doc: note that go generate scripts are deprecated

dev/ci/asdf-install.sh, dev/ci/go-backcompat/test.sh, dev/ci/go-test.sh, enterprise/dev/ci/internal/ci/operations.go
use bsdtar for all cache extraction
A green build in this PR
=> dev/ci: use bsdtar in asdf-install

internal/repos/npm_packages_test.go, internal/repos/testdata/sources/TestNPMPackagesSource_ListRepos, internal/repos/testdata/sources/TestNPMPackagesSource_ListRepos.yaml
Verified fix by running:
```
go test ./internal/repos -run NPMPackagesSource_ListRepos -count=100
```
=> npm: Sort slice before comparison.

.github/PULL_REQUEST_TEMPLATE.md
Suggestion I missed in my last PR https://github.com/sourcegraph/sourcegraph/pull/35300
Test Plan: n/a
=> github: copy edit on test plan template

dev/pr-auditor/README.md, dev/pr-auditor/check.go, dev/pr-auditor/check_test.go, dev/pr-auditor/issue.go, dev/pr-auditor/issue_test.go, dev/pr-auditor/main.go
Fixes #33959 
CI + added unit tests.
=> dx: add -protected-branch to pr-auditor

internal/codeintel/dependencies/internal/store/store.go, internal/codeintel/dependencies/service.go
Misc drive-by updates.
God help us all if this causes problems.
=> codeintel: Small doc and errors updates

dev/ci/CODENOTIFY
Removed unused entry, and the file altogether as the only entry.
n/a
=> chore: remove unused CODENOTIFY

doc/admin/how-to/index.md
No review required: just a tiny doc correction
=> Removed duplicate how to

doc/dev/background-information/basestore.md, doc/dev/background-information/sql/batch_operations.md
descried -> described
None - it's a spelling fix
=> fix spelling of described in docs/dev

client/web/src/enterprise/repo/settings/RepoSettingsPermissionsPage.tsx, client/web/src/enterprise/repo/settings/backend.ts, cmd/frontend/graphqlbackend/authz.go, cmd/frontend/graphqlbackend/authz.graphql, enterprise/cmd/frontend/internal/authz/resolvers/resolver.go, enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
Part of https://github.com/sourcegraph/sourcegraph/issues/34631
Tests updated and manually tested locally.
=> permissions: Show an alert in the UI for unrestricted repos

CHANGELOG.md, doc/admin/repo/permissions.md
Closes https://github.com/sourcegraph/sourcegraph/issues/34631
Only docs changed
=> doc: Add documentation for setRepositoryPermissionsUnrestricted mutation

CHANGELOG.md, doc/admin/updates/kubernetes.md
Update Changelog and docs for https://github.com/sourcegraph/deploy-sourcegraph/pull/4128
N/A: Docs update
=> changelog: add note about ingress update in deploy-sourcegraph

CHANGELOG.md, doc/code_search/how-to/dependencies_search.md, doc/integration/python.md
It's docs, CI has link checks.
=> doc: Document Python dependency repos and search

doc/admin/external_service/index.md
=> Add small blurb about rate-limits & code host accts

internal/codeintel/dependencies/internal/store/store_test.go
=> dependencies: Fix flaky test

dev/gqltest/compute_test.go, internal/gqltestutil/compute.go
Adds integration test for compute endpoint.
Since it's a bigger change let's merge this independent of #35227 and rebase that PR on top of this. I want to test one more case but asking for review in this state so that merging is non-blocking.
See above.
=> compute: add integration test

client/web/src/components/diff/FileDiffNode.tsx, client/web/src/repo/compare/RepositoryCompareHeader.tsx
Related to https://github.com/sourcegraph/sourcegraph/issues/34426
Fixes some small issues found when doing the compare audit. Other issues will be raised in GH issues
Tested locally with a screen reader
- [Web](https://sg-web-tr-compare-page-fixes.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ewknpoeywk.chromatic.com)
=> Accessibility: Fix small issues on Compage page

internal/codeintel/autoindexing/internal/inference/service_generator_test.go
Follow-up on comments from #35452
N/A.
=> chore: Add test comments

doc/dev/how-to/add_observability.md
Just stumbled on this.
n/a, pure doc change.
=> docs: replect API change on observation howto

go.mod, go.sum
=> Update crypto lib for CVE

client/web/src/charts/components/line-chart/LineChart.tsx
Fixes https://github.com/sourcegraph/sourcegraph/issues/34182
- Make sure that you can hover all points on the line chart, even if they are placed at the very end of the chart (corners) 
For testing, you can use insight on this dashboard 
https://k8s.sgdev.org/insights/dashboards/ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3MjcyNTJ9
- [Web](https://sg-web-vk-fix-insight-chart-corner-point.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-myfggjcinv.chromatic.com)
=> Code Insights: Fix line chart point hover coords distribution

internal/search/searcher/search.go, internal/search/searcher/symbol_search_job.go
Part of #34009.
Add trace tags to `SearcherJob` and `SymbolSearcherJob`.
All existing tests pass. Example trace output:
`SearcherJob`:
`SymbolSearcherJob`:
=> Search backend: Add trace tags to jobs in package searcher

docker-images/postgres-12-alpine/Dockerfile
=> Fix postgres CVE

internal/search/structural/structural.go
Part of #34009
Add trace tags to `StructuralSearchJob`.
Visually verify trace output:
=> Search backend: Add trace tags to StructuralSearchJob

cmd/frontend/backend/repos.go
This feature should only be enabled on sourcegraph.com
Closes https://github.com/sourcegraph/customer/issues/928
Tested locally
=> frontend: Don't lazy clone missing repos on customer instances

internal/search/query/types.go
While playing around I noticed some panics in my printf debugging. The reason was that Pattern was nil. Instead of copy pasting the fix in both String and StringHuman, a helper function is created.
Test Plan: CI
Edit: hoping this kicks pr-auditor
=> search/query: check for nil Pattern in String and StringHuman

enterprise/internal/insights/resolvers/insight_series_resolver.go
just a PR to make things prettier as I was reading `handels` with a german accent in my head every time
compiles!
=> insights: prettier: update handler variable name

internal/types/types.go, internal/usagestats/batches.go, internal/usagestats/batches_test.go
Closes #26144 #23882
[BigQuery Schema Update](https://github.com/sourcegraph/analytics/pull/439)
=> batches: Add Pings for server-side batch changes

enterprise/internal/authz/gerrit/gerrit.go
Stub out necessary methods to implement the provider interface for Gerrit (and enable parallelization) 
No testing needed yet: no functional changes
=> stub out gerrit auth provider methods

enterprise/cmd/frontend/internal/compute/streaming/compute.go
This parallelizes execution of compute jobs using the new `group.OrderedParallel`,
which was introduced in #35572. 
This dramatically speeds up execution time for compute queries that require fetching
the file contents. See [comparison video](https://vimeo.com/710511004). 
Running backend integration tests. Also manually tested a few queries to validate that the results are the consistent. 
Edit to bump pr-auditor
=> Compute: parallelize execution

internal/gitserver/test_utils.go
Some tests that are checking commit IDs are consistently failing on my local macOS because I have GPG configured in my `~/.gitconfig`. This PR stops reading from system env vars altogether for tests.
Example failure execution of these tests:
```
→ go test
--- FAIL: TestRepository_BlameFile (1.14s)
commands_test.go:362: git cmd: hunks != wantHunks
hunks ==========
[
{
"StartLine": 1,
"EndLine": 2,
"StartByte": 0,
"EndByte": 6,
"CommitID": "ca46106c726e82468a64d527df8b5a762d88220b",
"Author": {
"Name": "a",
"Email": "a@a.com",
"Date": "2006-01-02T15:04:05Z"
},
"Message": "foo",
"Filename": "f"
},
{
"StartLine": 2,
"EndLine": 3,
"StartByte": 6,
"EndByte": 12,
"CommitID": "06d21bfafbedc6b8790e5f53acd88cdd6278c349",
"Author": {
"Name": "a",
"Email": "a@a.com",
"Date": "2006-01-02T15:04:05Z"
}, …
```
=> gitserver: stop reading system env vars in tests

cmd/frontend/graphqlbackend/repository_git_refs.go, internal/gitserver/commands.go, internal/gitserver/commands_test.go, internal/gitserver/gitdomain/common.go, internal/vcs/git/refs.go, internal/vcs/git/refs_test.go
Closes https://github.com/sourcegraph/sourcegraph/issues/35627
Small refactor, all unit tests still pass
=> git: Move git.ListTags onto gitserver client

doc/dev/background-information/web/accessibility/how-to-arc-toolkit.md
Unsure what happened here for this to be copied in!
N/A Docs only change
=> Accessibility docs: Fix ARC Toolkit tutorial link

CHANGELOG.md, client/web/src/site-admin/SiteAdminPingsPage.tsx, doc/admin/pings.md
* doc update
- [Web](https://sg-web-bo-update-docs-changelog-pings.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-cmicycyjol.chromatic.com)
=> Update docs for SSBC pings

internal/metrics/operation.go, internal/observation/observation.go
=> metrics: Fix somes typos

doc/admin/pings.md
Confirmed sub-bullet points are properly indented
=> batches: Update Markdown Indentation

CHANGELOG.md
=> changelog: cut sourcegraph@3.40.0

internal/database/migration/cliutil/drift.go, internal/database/migration/cliutil/drift_util.go, internal/database/migration/store/describe.go
Misc. updates to drift commands in `sg migration` and `migrator` service.
N/A.
=> migrator: Improve drift tooling

client/web/src/enterprise/insights/components/modals/ShareLinkModal/ShareLinkModal.tsx
Fixing a typo 
Viewing manually. 
- [Web](https://sg-web-patch-modal-typo.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-qepdazolqi.chromatic.com)
=> insights: fix typo in modal

doc/admin/deploy/docker-compose/index.md
Technical review by CE in PR, content editing by Product Education team members.
=> Update docker compose docs re private fork

internal/repos/github.go, internal/repos/github_test.go, internal/repos/types.go
@unknwon, this one's for you 😄 
Only a rename, all tests still pass
=> repos: Rename GithubSource to GitHubSource

.github/workflows/label-notify.yml
Will manually validate by creating a new issue.
=> Added rest of team to notification

.hadolint.yaml, cmd/searcher/Dockerfile, cmd/server/Dockerfile
finally made it pass
Running integration tests
=> bump comby version to 1.7.1

.github/workflows/label-notify.yml
Will test manually by creating a new ticket.
=> Consolidate search-core notification to github team

doc/admin/deploy/managed.md
part of https://github.com/sourcegraph/security-issues/issues/251
docs changes
=> Update MI backup schedule

cmd/frontend/internal/highlight/highlight.go
We're running into out-of-bounds indexing panics, which are meaningless
for an end-user. Instead of showing the unhighlighted text only for certain
errors, show it for all errors.
Not able to reproduce the panic locally yet, so I can't test the workaround.
=> frontend: Ignore all highlighting errors.

doc/code_insights/explanations/viewing_code_insights.md
For the 3.40 share updates 
Viewing manually deploy.
=> add share link docs

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/dev/background-information/ci/reference.md, doc/index.md, enterprise/dev/ci/internal/ci/pipeline.go
This pull request is part of the Sourcegraph 3.40.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.40.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34255)
cc @unknwon
=> release: sourcegraph@3.40.0

client/jetbrains/src/main/java/com/sourcegraph/browser/JSToJavaBridge.java, client/jetbrains/src/main/java/com/sourcegraph/browser/JSToJavaBridgeRequestHandler.java, client/jetbrains/webview/src/search/index.tsx, client/jetbrains/webview/src/search/jsToJavaBridgeUtil.ts
We had these housekeeping tasks on our list.
Just check the code. I've run the branch, it works as intended.
Btw I discovered a bunch of error messages in the JS console by these changes.
- [Web](https://sg-web-dv-jetbrains-js-to-java-bridge.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-bfqdgxkoyg.chromatic.com)
=> JetBrains: JS→Java bridge housekeeping

internal/database/migration/cliutil/drift_util.go, internal/database/migration/schemas/description.go
Add hints to drift detector. There are a lot of `TODO`s here because we can fill out additional hints incrementally in the future. Want to land this to get some of the goodies out the door.
Tested hints by hand. My database is a mess (NOT! I used the suggestions to fix it! 😎 )
=> drift: Add hints

doc/code_intelligence/explanations/features.md, doc/code_intelligence/references/indexers.md
N/a. This PR only changes docs.
=> Update docs for which languages support "Find implementations"

internal/codeintel/dependencies/internal/store/store.go
Noticed this while working on something else.
Existing tests
=> Fix wrong operation being used in method

lib/output/output.go
Add a method that renders a markdown code block without margins. I don't care about the API, but this unblocks the new migration drift detector from working well in a copy-and-paste scenario; currently copy and pasting function definitions contain additional indent that makes the drift detector complain in a way that needs to be fixed manually.
N/A.
=> lib/output: Add `WriteCode` method

internal/database/migration/cliutil/drift.go, internal/database/migration/cliutil/drift_util.go
=> sg migration drift: Update code output

client/web/src/codeintel/ReferencesPanel.module.scss, client/web/src/codeintel/ReferencesPanel.test.tsx, client/web/src/codeintel/ReferencesPanel.tsx
Ref #35725, #35721, #35723, #35726 
Update UI based on [figma file](https://www.figma.com/file/DZMyEJT3g2HT6HmJGNNOnW/%22Better%22-code-intel-panel?node-id=1384%3A10928).
New Reference Panel
Manually tested. Most changes are visual
- [Web](https://sg-web-cesar-update-ui-in-reference-panel.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-sazbrfsqzi.chromatic.com)
=> Update UI for new reference panel

client/branded/src/components/panel/TabbedPanelContent.tsx
Use parens correctly.
My 👁️ 👄 👁️ .
- [Web](https://sg-web-ef-gdi.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-mdpvatpaaw.chromatic.com)
=> codeintel: Show code intel reference panel redesign feedback CTA

doc/cli/references/code-intel.md, doc/cli/references/debug.md, doc/cli/references/index.md, doc/cli/references/lsif/upload.md, internal/src-cli/consts.go
Release notes https://github.com/sourcegraph/src-cli/releases/tag/3.40.1
N/A
=> Update to the latest src-cli release

client/vscode/CHANGELOG.md, client/vscode/CONTRIBUTING.md, client/vscode/src/backend/requestGraphQl.ts, client/vscode/src/common/links.ts, client/vscode/src/contract.ts, client/vscode/src/extension.ts, client/vscode/src/settings/accessTokenSetting.ts, client/vscode/src/settings/endpointSetting.ts, client/vscode/src/state.ts, client/vscode/src/webview/index.scss, client/vscode/src/webview/sidebars/auth/AuthSidebarView.tsx, client/vscode/src/webview/sidebars/help/HelpSidebarView.module.scss, client/vscode/src/webview/sidebars/help/HelpSidebarView.tsx
Close: https://github.com/sourcegraph/sourcegraph/issues/35955 & https://github.com/sourcegraph/sourcegraph/issues/35980
Issue summary: https://github.com/sourcegraph/sourcegraph/issues/35955
The integration test is currently failing for VSCE because of CORS issue caused by `credentials: include`
It was a leftover by mistake from my last PR when testing the streamlined auth flow.
Removing it has resolved the issue:
Issue summary: https://github.com/sourcegraph/sourcegraph/issues/35980
User is unable to login if  they have submitted a new instance URL in the UI while the extension has already connected to the old instance URL (we use [sourcegraph.com](http://sourcegraph.com/) by default). This is because updating instance URL via the UI does not trigger extension to reload currently …
=> vsce fix: remove credentials from graphQL & update endpoint

CHANGELOG.md
=> batches: update changelog for patch release

dev/sg/linters/gogenerate.go
This fixes the hanging issue mentioned https://github.com/sourcegraph/sourcegraph/issues/35918 
Expected https://buildkite.com/sourcegraph/sourcegraph/builds/149733#0180fc10-2872-4389-bb18-e0c4f044ee4f failed and it did 👍
=> ci: fix sg lint go hanging on generate failures

CHANGELOG.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/updates/server.md
=> chore: fix broken links and misplaced CHANGELOG entries

doc/code_intelligence/references/indexers.md
=> add scip-python

internal/database/migration/cliutil/drift_util.go
Adds suggestions when there's only one of the following wrong:
- type is different (stub for now)
- nullability flag is flipped
- missing or different default
- missing or different comment
=> sg migration drift: Add better suggestions for mismatched column properties

client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-select/DashboardSelect.tsx
interrupt key event if search box has focus
Closes https://github.com/sourcegraph/sourcegraph/issues/34782
- Confirm can now add spaces to dashboard fuzzy filter
- [Web](https://sg-web-insights-fix-space-bar-dashboard.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-eaibmvbwfc.chromatic.com)
=> fix space bar not working

dev/buildchecker/history.go, dev/buildchecker/main.go
Push weekly ci metrics to slack.
Follow up: update action with new flags and create webhook for appropriate channel
Running locally and pushing report to #jh-bot-test
=> ci: publish weekly metrics to slack

cmd/frontend/graphqlbackend/external_service_collaborators.go, doc/code_intelligence/how-to/index_other_languages.md, doc/code_search/how-to/dependencies_search.md, enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/indexers.go, internal/codeintel/stores/dbstore/commits_test.go, internal/codeintel/stores/dbstore/dumps_test.go
Makes progress towards https://github.com/sourcegraph/scip/issues/6.
Regenerated docs.
=> docs: Update lsif-py(thon)? → scip-python.

enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
Log the correct method name
Only changed a log line
=> repo-updater: Rename log for consistency

dev/release/release-config.jsonc
Preparing for the 3.40.1 patch release.
Just release config.
=> release: update release config for 3.40.1

cmd/gitserver/p4-fusion-install-alpine.sh
Docker files all build successfully.
Local testing using p4-fusion with version 1.9 done
=> gitserver: Upgrade p4-fusion to 1.9

internal/database/dbcache/cached_indexable_repos.go
I know this is a small change, but correct and my first contribution!
I talked with @keegancsmith and he said he could review it and see if it could be merged
Already tested, just refactoring from public to private
=> dbcache: unexport cachedRepos.Repos

CHANGELOG.md
=> Code Insights: Add share insight by link to the `CHANGELOG.md`

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/index.md
This pull request is part of the Sourcegraph 3.40.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.40.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/36218)
cc @unknwon
=> release: sourcegraph@3.40.1

doc/admin/auth/saml/index.md
=> doc/admin/auth/saml: Semantic improvements

enterprise/cmd/symbols/main.go, enterprise/internal/rockskip/server_test.go, internal/gitserver/commands.go, internal/vcs/git/refs.go
Refactoring in scope of https://github.com/sourcegraph/sourcegraph/issues/33280
Closes https://github.com/sourcegraph/sourcegraph/issues/36368
Existing tests should pass.
=> repo-updater: move git.RevList and git.RevListEach from vcs/git to gitserver/commands

client/web/src/enterprise/batches/batch-spec/execute/ExecuteBatchSpecPage.story.tsx
Verified that the timer no longer ticks in the storybook.
- [Web](https://sg-web-aharvey-fix-flaky-execute-story.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-fdftqampwl.chromatic.com)
=> batches: fix another flaky story by hardcoding a finish time

dev/ci/trivy/trivy-scan-high-critical.sh
Second attempt - the previous one was overwritten by the subsequent annotations.
Check an annotation in a build.
=> Add link to bottom of annotation

dev/ci/trivy/trivy-scan-high-critical.sh
Adding newlines to make the link more visible
Check the annotation.
=> Trivy annotation

client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.story.tsx, client/web/src/enterprise/insights/components/insights-view-grid/components/SmartInsight.tsx, client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.story.tsx, client/web/src/enterprise/insights/core/backend/gql-backend/code-insights-gql-backend.ts, client/web/src/enterprise/insights/core/backend/gql-backend/deserialization/create-insight-view.ts, client/web/src/enterprise/insights/core/backend/gql-backend/gql/GetInsights.ts, client/web/src/enterprise/insights/core/types/insight/common.ts, client/web/src/enterprise/insights/core/types/insight/index.ts, client/web/src/enterprise/insights/pages/insights/creation/capture-group/CaptureGroupCreationPage.tsx, client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/capture-group-insight-sanitizer.ts, client/web/src/enterprise/insights/pages/insights/creation/lang-stats/utils/insight-sanitizer.ts, client/web/src/enterprise/insights/pages/insights/creation/search-insight/utils/insight-sanitizer.ts, client/web/src/enterprise/insights/pages/insights/insight/CodeInsightIndependentPage.module.scss, client/web/src/enterprise/insights/pages/insights/insight/CodeInsightIndependentPage.tsx, client/web/src/enterprise/insights/pages/insights/insight/components/dashboard-pills/StandaloneInsightDashboardPills.module.scss, client/web/src/enterprise/insights/pages/insights/insight/components/dashboard-pills/StandaloneInsightDashboardPills.tsx, client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.tsx, client/web/src/integration/insights/create-insights.test.ts, client/web/src/integration/insights/fixtures/insights-metadata.ts
Closes https://github.com/sourcegraph/sourcegraph/issues/34760
- Make sure that dashboard pills work properly on the standalone insight page and match the design
- [Web](https://sg-web-vk-add-insight-dashboard-pills.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-bvzuhqrvsf.chromatic.com)
=> Code Insights: Add insight dashboard pills component

doc/admin/deploy/docker-compose/index.md
Any one PE team member to check for language errors.
=> Correct markdown around you/private example code

dev/sg/sg_setup.go, dev/sg/sg_setup_mac.go, dev/sg/sg_setup_shared.go, dev/sg/sg_setup_ubuntu.go
Applies review comments from https://github.com/sourcegraph/sourcegraph/pull/36335
=> dev/sg: fix interactive setup, simplify 1pass check

client/web/src/settings/DynamicallyImportedMonacoSettingsEditor.tsx, schema/schema.go, schema/settings.schema.json
Fixes #35890
Added a feature flag to test the home panels suggestions for repos and files.
Ran the local Sourcegraph successfully.
=> added a feature flag for homePanelsComputeSuggestions

cmd/symbols/fetcher/repository_fetcher.go, cmd/symbols/fetcher/repository_fetcher_test.go, cmd/symbols/internal/api/handler.go, cmd/symbols/internal/api/search_sqlite.go, cmd/symbols/internal/database/store/search.go, cmd/symbols/internal/database/store/store.go, cmd/symbols/internal/database/writer/cache.go, cmd/symbols/internal/database/writer/writer.go, cmd/symbols/parser/parser.go, cmd/symbols/types/types.go, enterprise/cmd/symbols/main.go, enterprise/internal/rockskip/search.go, enterprise/internal/rockskip/server_test.go
It looks like one struct was duplicated.
Go tests
=> symbols: Refactor params type

internal/search/searcher/search.go
This is just a small style change. At some point I'd implemented this as
a function that returns a closure over its arguments, but I think that
was before we had streaming for searcher so we weren't already creating
a closure here. In any case, when pairing with @tbliu98, he rightly asked
why we did it in this weird and convoluted way and I didn't have a real
answer, so I'm making it less confusing by just calling the function with
its full set of arguments every time. 
Stacked on #36432 
Should be semantics-preserving, but I'm depending on a quick manual smoke test and existing tests.
=> Search backend: simplify newToMatches

cmd/gitserver/server/server.go, cmd/gitserver/server/server_test.go
We want to always store the clone error, or clear it when there isn't
one, in the gitserver_repos table.
Part of https://github.com/sourcegraph/sourcegraph/issues/32628
Unit tests still pass
=> gitserver: Ensure we always record clone error

doc/admin/deploy/docker-compose/index.md
Updated deployment flow for docker compose based on demo and discussion with SMEs in test plan. Added contextualising information, made prerequisites clear, made outcome clear, created linear path through process. 
https://github.com/sourcegraph/product-education/issues/28 
Language check by @blvckcoffee or @dulanism
Technical accuracy check by @caugustus-sourcegraph or @kevinwojo or @briemcnally
=> Update deployment flow docker compose

doc/dev/setup/quickstart.md
=> doc/dev/setup: Fix typo

.github/workflows/label-notify.yml
=> Update DevX and FPT notifications

client/web/src/monitoring/datadog/datadogClient.ts
1. click repro link and observe no white-screen. The other crash will be fixed in a separate PR
Repro link: [https://sourcegraph.com/search?q=context:global+repo:^github\.com/sourcegraph/sourcegraph%24+file:^yarn\.lock+.*\n+index:no&patternType=regexp](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Eyarn%5C.lock+.*%5Cn+index:no&patternType=regexp)
- [Web](https://sg-web-jg-adderror-guard.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-bydafjhmei.chromatic.com)
=> fixes whitescreen crash with datadog

client/web/src/user/settings/repositories/RepositoryNode.tsx, client/web/src/user/settings/repositories/SelectAffiliatedRepos.tsx, client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.module.scss, client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx, client/web/src/user/settings/repositories/components/FilterInput/FilterInput.module.scss, client/web/src/user/settings/repositories/components/FilterInput/FilterInput.tsx
Resolves UI regressions from `<Input />` wildcard migrations
- visit routes: 
`/users/[USERNAME]/settings/repositories`
`/users/[USERNAME]/settings/repositories/manage`
- Compare with same route on `https://sourcegraph.com/`
- Confirm UI regressions has been resolved
- [Web](https://sg-web-input-regression-fix.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-xgyytopoeg.chromatic.com)
=> wildcard `<Input />` Migration: Fixed UI regressions on Input

doc/admin/deploy/docker-compose/index.md
@blvckcoffee or @dulanism to check formatting of code blocks and numbered lists please.
=> fix-markdown-numbered-lists

cmd/frontend/graphqlbackend/repository_git_refs.go, enterprise/cmd/frontend/internal/batches/resolvers/changeset_spec.go, enterprise/cmd/frontend/internal/batches/resolvers/changeset_spec_test.go, enterprise/internal/batches/reconciler/executor_test.go, enterprise/internal/batches/reconciler/main_test.go, enterprise/internal/batches/reconciler/reconciler_test.go, enterprise/internal/batches/sources/bitbucketcloud.go, enterprise/internal/batches/sources/bitbucketserver.go, enterprise/internal/batches/sources/common.go, enterprise/internal/batches/sources/github.go, enterprise/internal/batches/sources/gitlab.go, enterprise/internal/batches/testing/changeset.go, enterprise/internal/batches/types/changeset.go, internal/gitserver/commands.go, internal/gitserver/gitdomain/common.go, internal/gitserver/gitdomain/common_test.go, internal/search/repo_revs.go, internal/search/textsearch/textsearch_test.go, internal/vcs/git/refs.go, internal/vcs/git/refs_test.go
Part of https://github.com/sourcegraph/sourcegraph/issues/36535
Tests still pass, just a move refactor
=> vcs/git: Move some types into gitdomain

cmd/frontend/graphqlbackend/git_commit.go, internal/gitserver/commands.go, internal/vcs/git/refs.go
Part of https://github.com/sourcegraph/sourcegraph/issues/33280
Depends on https://github.com/sourcegraph/sourcegraph/pull/36539
Existing tests should pass
=> move GetBehindAhead function to gitserver package

dev/global-settings.json
YAY WE THERE! Let's get it to everyone at Sourcegraph in local dev, too :) 
Internal beta here we go 👀 
This is a dev-env only config change. It still starts and the flag is set, so all good.
=> SSBC: Enable by default in dev environment

CHANGELOG.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md
Updates CHANGELOGs for https://github.com/sourcegraph/deploy-sourcegraph/pull/4136
N/A
=> Add docs for new startup probes on Postgres containers

CHANGELOG.md, cmd/frontend/graphqlbackend/saved_searches.go, cmd/frontend/graphqlbackend/saved_searches_test.go
Fixes https://github.com/sourcegraph/security-issues/issues/274
Added tests to ensure errors are returned where expected.
=> Saved searches: fix update permissions

client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.tsx, package.json, yarn.lock
Why is English so hard I need a library for this :upside_down:
Closes https://github.com/sourcegraph/sourcegraph/issues/36596
Verified it looks correct now in the UI.
- [Web](https://sg-web-es-fix-ordinal.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ifenslxlfm.chromatic.com)
=> batches: fix ordinal representation of queue rank

dev/adr-docs/index.md.tmpl
Forgot to update the template :/ 
n/a
=> adr: fix template

dev/adr-docs/index.md.tmpl, dev/adr-docs/main.go, dev/sg/linters/linters.go, dev/sg/sg_lint.go, doc/dev/adr/index.md
Stop messing around and fix it.
n/a
=> ci: unblock main, disable docsite linterr

dev/sg/internal/run/run.go, sg.config.yaml
Kill some bash, to relax :D 
Tested locally
=> sg: add install func for Jaeger

cmd/repo-updater/shared/main.go, enterprise/cmd/repo-updater/internal/authz/integration_test.go, enterprise/cmd/repo-updater/internal/authz/perms_syncer.go, enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go, enterprise/cmd/repo-updater/main.go, lib/log/fields.go
Migrate logging from log15 to lib/log
Closes #34607
Unit tests and executed `sg run frontend gitserver repo-updater`
=> refactor(repo-updater): update authz/perm_syncer logging

client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.tsx, client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/filter-collapse-section/FilterCollapseSection.tsx, client/web/src/integration/insights/drill-down-filters.test.ts
Closes https://github.com/sourcegraph/sourcegraph/issues/34751
- Make sure that CI doesn't have any problems with the integration test
- [Web](https://sg-web-vk-add-search-context-integration.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-mllxxpxrad.chromatic.com)
=> Code Insights: Add integration test case for the search context filter

dev/release/release-config.jsonc
=> release: update `release-config.jsonc` for 3.40.2

.github/workflows/pr-auditor.yml
update PR auditor for https://github.com/sourcegraph/sourcegraph/issues/35635
a green run on this pr
=> ci: update pr auditor name

doc/admin/auth/saml/one_login.md
=> Fix `SAMl` to `SAML` in the heading

dev/release/release-config.jsonc
Updating release config as nothing has happened.
Config change, no tests needed
=> release: update release config for 3.41

internal/database/mocks.go, mockgen.yaml
Co-authored-by: Asdine El Hrychy <asdine.elhrychy@gmail.com>
Not applicable. Generated mocking code only.
=> internal/database: Generate mocks for BitbucketProjectPermissionsStore

cmd/symbols/squirrel/util.go
This is a more helpful error message.
N/A
=> squirrel: Improve parse error message

enterprise/cmd/executor/config.go
=> executor: Fix typo in config

sg.config.yaml
Reflecting team name change, though may break if someone from @sourcegraph/repo-management is using this?
Just dev config change.
=> sg: rename "core-app" to "iam"

cmd/frontend/backend/user_emails.go
Our code logic for calculating email sending cooldown consults the value of the `user_emails.last_verification_sent_at` column, however, if the email didn't get sent in the first place due to any reason, the column is NULL, and resend is impossible. The user would have to first remove and re-add the same email.
Fixes https://github.com/sourcegraph/sourcegraph/issues/36632
Manul e2e test and unit test.
1. Use a bad credential for the site config `"email.smtp"` (simulate email sending failures)
1. Add a new email under the user **Settings > Emails** (any random fake email, shouldn't be verified already by other users)
1. Refresh the page, click "Resend verification email"
1. Should see "Last verification email sent too recently" instead of "user email not found [...]"
=> backend: always update `last_verification_sent_at` column after trying to send email

doc/dev/background-information/sg/reference.md
Spotted in https://buildkite.com/sourcegraph/sourcegraph/builds/153650
CI
=> chore: make sg lint happy

internal/database/bitbucket_project_permissions.go, internal/database/mocks_temp.go
Add missing Done method for transactions.
Nothing
=> db: add missing done method

cmd/frontend/graphqlbackend/authz.go, cmd/frontend/graphqlbackend/authz.graphql, cmd/frontend/graphqlbackend/external_service.go, cmd/frontend/graphqlbackend/external_services.go, cmd/frontend/graphqlbackend/external_services_test.go, cmd/frontend/graphqlbackend/webhook_logs.go, enterprise/cmd/frontend/internal/authz/resolvers/resolver.go, enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
Closes #36454.
Added new tests.
=> Enqueue job in SetRepositoryPermissionsForBitbucketProject API

client/jetbrains/src/main/java/com/sourcegraph/find/SourcegraphWindow.java
Closes #36479
Another attempt at fixing #36479. This time it does not bring back the web view issues on macOS.
We now manually emit an action defined by the material UI theme to hide the overlay it opens whenever a popover is
created. This third-party plugin does not work with our approach of keeping the popover alive and thus, when the
Sourcegraph popover is closed, their custom overlay stays active.
Background on how we came up with the solution can be found here: https://github.com/mallowigi/material-theme-issues/issues/179#issuecomment-1151169850
_Note: This is not an ideal fix yet as the overlay does not re-appear when the window is re-opened. Given that this is not the only issue with the overlay and the fact that I was able to find more by using this theme myself for a bit, I am …
=> JetBrains: Force hide the material UI overlay when the Sourcegraph window is hidden

client/jetbrains/src/main/resources/META-INF/plugin.xml
This improves the action names for the context menu and action search (cmd+shfit+a). I'll describe the changes inline.
Terminology is loosely based on what we have [on VSCode](https://sourcegraph.slack.com/archives/C035WT8V856/p1654785021370309?thread_ts=1654779128.036769&cid=C035WT8V856),
Tested both the context menu and actions search manually:
- [Web](https://sg-web-ps-jetbrains-action-cleanup.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-jllzxrzwsi.chromatic.com)
=> JetBrains: Clean up action list

client/web/src/integration/utils.ts
I'm extracting Percy / general integration test stuff from #36044 into a separate (this) PR.
While working on integration tests for the search query input and trying
to figure out how to handle waiting on the editor if we want to be able
to test different editor implementations (Monaco/CodeMirror), I noticed
that the timeout for waiting on the editor gives other components time
to "settle".
This became evident after I removed one of the editor checks.
But that means that irrespectively of whether or not an editor is
rendered on the page, there are pages with components which need time to
settle. Using a generic timeout (instead of waiting for something that
doesn't exist anyway) expresses that intent better. And that generic
timeout also will leave enough time for the editor(s) to update. …
=> frontend: Use generic timeout in integration test

enterprise/cmd/frontend/internal/auth/githuboauth/session.go, enterprise/cmd/frontend/internal/auth/githuboauth/session_test.go, internal/extsvc/github/v3.go, internal/extsvc/github/v3_test.go
I decided to fix it sooner than later.
Fixes https://github.com/sourcegraph/sourcegraph/issues/36774
New test case added, existing ones should pass
=> auth: check all user github orgs instead of first page of 100 during verification

client/web/src/components/time/Duration.tsx, client/web/src/enterprise/batches/batch-spec/execute/ActionsMenu.tsx, client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspaceDetails.tsx, client/web/src/enterprise/batches/batch-spec/execute/workspaces/WorkspacesFilterRow.tsx, enterprise/cmd/frontend/internal/batches/resolvers/batch_spec.go, enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_test.go, enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace.go, enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace_resolution.go, enterprise/internal/batches/store/batch_spec_workspaces.go, enterprise/internal/batches/store/batch_spec_workspaces_test.go
This fixes various little things with cancelation, including that these two states were never exposed in the API (oops, lol).
Closes https://github.com/sourcegraph/sourcegraph/issues/36653
Manually tested UI fixes and wrote tests for store changes.
=> ssbc: Fix various quirks about cancelation in UI

doc/dev/how-to/add_logging.md
=> doc/dev: fix header level of traced sub-loggers

enterprise/cmd/executor/config.go
=> executor: Add clarification to `EXECUTOR_KEEP_WORKSPACES`

doc/dev/background-information/languages/testing_go_code.md, doc/dev/background-information/testing_principles.md
Following up on Slack convo.
n/a
=> docs: Mention -count for verifying flaky test fixes.

.github/teams.yml
Remove @rafax from IAM team group.
- still a valid YAML
=> Update teams.yml to remove rafalg

dev/release/src/release.ts
Sister PR of https://github.com/sourcegraph/sourcegraph/pull/36894
n/a
=> release: add "Test plan" to "deploy-sourcegraph-helm" PR

client/jetbrains/src/main/java/com/sourcegraph/find/PreviewContent.java, client/jetbrains/src/main/java/com/sourcegraph/find/PreviewPanel.java
Closes #36279
Part-of #36222
This was straight-forward to add. While working on this part I also simplified the validation code to use the least required statements. 
https://user-images.githubusercontent.com/458591/173076137-a6996713-d6f4-43cf-98cd-ab68feae38b3.mov
https://user-images.githubusercontent.com/458591/173080207-e45b2a80-cfce-4acb-9774-cc7fa2c96ba7.mov
- [Web](https://sg-web-ps-jetbrains-editor-scroll.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ecwmrbydob.chromatic.com)
=> JetBrains: Scroll to the first highlighted occurence inside code preview

enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
No need for it to be at Info level
No need
=> repo-updater: Reduce noisy log

client/web/src/notebooks/blocks/menu/NotebookBlockMenu.tsx, client/web/src/notebooks/listPage/NotebooksListPage.tsx, client/web/src/notebooks/notebook/NotebookCommandPaletteInput.tsx, client/web/src/notebooks/notebookPage/NotebookPage.tsx, client/wildcard/src/components/PageHeader/Breadcrumb/Breadcrumb.tsx, client/wildcard/src/components/PageHeader/__snapshots__/PageHeader.test.tsx.snap
[Sourcegraph issue](https://github.com/sourcegraph/sourcegraph/issues/35167)
[GitStart Ticket](https://app.gitstart.com/tasks/60127)
Notebooks Page 10a:
Headings:
Images:
- Two icons on Notebook page
Forms:
--- 
Notebooks Editing 10b:
Headings:
Images:
- Allo Icons on edit menu on the right needs
Links:
Button:
Forms:
I have added `aria` attributes to elements suggested, they can be inspected with dev tools and checked.
- [Web](https://sg-web-contractors-sg-35167.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ddcmaeubhl.chromatic.com)
=> [SG-35167] Accessibility: Search notebooks management ARC checklist issues

dev/sg/internal/analytics/actions.go, dev/sg/internal/analytics/context.go, dev/sg/internal/analytics/events.go
We seem to be getting some invalid events in OkayHQ. To avoid these, we add some simple validation
over events both pre-persistence and pre-submission.
no testing
=> dev/sg: improve validation of events

internal/database/bitbucket_project_permissions.go, internal/database/bitbucket_project_permissions_test.go
just a typo fix
part of https://github.com/sourcegraph/sourcegraph/issues/36453
amended tests should run
=> fix typo: status -> state

doc/adopt/index.md
Marketing request to add new bullets to adopt section with corresponding links.
Verify links and check langauge.
=> Added new bullets and links to Adopt section

doc/adopt/index.md
Added a space and question mark.
Review changes with requestor (@lcolston08)
=> Minor edits to adopt page

doc/batch_changes/how-tos/configuring_credentials.md
Closes #35071
Documentation update.
=> batches: update documentation for Github Org with SSO enabled

enterprise/cmd/executor/internal/worker/handler.go
- Only start a log group if something is actually happening
- Ensure directory structures exist
- Add some logs of which files are written where
Verified it looks as expected by hand.
=> executors: Improve setup.fs step

enterprise/cmd/worker/internal/permissions/bitbucket_projects.go, enterprise/cmd/worker/internal/permissions/bitbucket_projects_test.go, enterprise/cmd/worker/internal/permissions/testdata/vcr/client.yaml
This implements the handler of the Bitbucket Project Permissions worker.
Fixes https://github.com/sourcegraph/sourcegraph/issues/36450
Added a few unit tests
=> worker: implement handler

enterprise/cmd/frontend/internal/authz/resolvers/resolver.go, enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
Closes https://github.com/sourcegraph/sourcegraph/issues/37258
New unit test added
=> graphqlbackend: don't enqueue non-Bitbucket Server external services for Bitbucket Projects permission sync

enterprise/internal/database/external_services_test.go, internal/database/external_services.go
Ran an instance with just projectKeys locally to verify
=> Add projectKeys to the code host config constraint for bitbucket

dev/sg/internal/std/output.go, lib/go.mod, lib/go.sum, lib/output/output.go
Tested in https://github.com/sourcegraph/sourcegraph/pull/37033
=> output: add ReadPassword for securely reading password

internal/search/query/predicate.go
Left-over from #35374 that I just ran into. Apparently I didn't undo the
changes I made in that PR completely and ended up in a half-state.
=> Actually use RepoDependentsPredicate in predicate registry

client/web/src/charts/components/line-chart/LineChart.tsx, client/web/src/charts/components/line-chart/components/tooltip/TooltipContent.tsx, client/web/src/enterprise/insights/components/views/chart/series/SeriesChart.tsx, client/web/src/insights/utils/use-series-toggle.test.tsx, client/web/src/insights/utils/use-series-toggle.ts
Based on https://github.com/sourcegraph/sourcegraph/pull/37224
- Make sure that all series toggling logic works properly (see cases for this logic in the original PR)
- [Web](https://sg-web-vk-insights-fix-series-hover-v2.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-fsqbtnqlvg.chromatic.com)
=> Code Insights: Refactor line chart API

client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java, client/jetbrains/webview/src/search/input/JetBrainsSearchBox.tsx
Fixes https://github.com/sourcegraph/sourcegraph/issues/35919
Fixes 1/3 of https://github.com/sourcegraph/sourcegraph/issues/36704
Also a typo fix in a comment.
- Watch this [1-min Loom demo](https://www.loom.com/share/94873cc5be7040b59864a1ba4e9ea318) and check the code.
- [Web](https://sg-web-dv-jetbrains-fix-resize-by-adding.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-yecxjtavqd.chromatic.com)
=> JetBrains: Fix resize by adding padding

cmd/repo-updater/repoupdater/server.go
=> repo-updater: Include route name in http metrics

client/jetbrains/src/main/java/com/sourcegraph/browser/JSToJavaBridgeRequestHandler.java, client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java, client/jetbrains/src/main/java/com/sourcegraph/find/PreviewContent.java, client/jetbrains/src/main/java/com/sourcegraph/find/PreviewPanel.java, client/jetbrains/webview/src/bridge-mock/index.ts, client/jetbrains/webview/src/search/js-to-java-bridge.ts
Fixes https://github.com/sourcegraph/sourcegraph/issues/36704
Included a demo of the code changes because @taras-yemets is not very familiar with the code, especially the Java side code, and @philipp-spiess is not here today, so I wanted to make it as smooth as possible for Taras to do this PR review.
- Tested with fast and slow connections, [3-min Loom here](https://www.loom.com/share/656cb331972d447eb1a4123e0becf021)
- Demo of the code changes: [11-min Loom here](https://www.loom.com/share/7a6ee281f341480a8af593fd19e806de)
- [Web](https://sg-web-dv-jetbrains-add-preview-loading.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-excolxhsmj.chromatic.com)
=> JetBrains: Add preview loading state

doc/cli/references/batch/exec.md, internal/src-cli/consts.go
Mechanical change. Impact will be verified in executor release on k8s once built.
=> Bump src-cli for 3.41.0 release

client/web/src/fuzzyFinder/CaseInsensitiveFuzzySearch.test.ts, client/web/src/fuzzyFinder/CaseInsensitiveFuzzySearch.ts
See new unit test.
- [Web](https://sg-web-olafurpg-issue-36736.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-zymazwrwic.chromatic.com)
=> Fix #36736. Allow exact match for fuzzy file finder

dev/gqltest/README.md
while working on #34704 I got confused as to what steps were actually required to run integration tests locally so I've cleared up some things and updated outdated commands in the README. 
just a doc change
=> gqltest: update readme

client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.tsx
[Designs](https://www.figma.com/file/lYD20GUga7m3aZ49fYh1Vu/Charts-with-20%2B-matches-%7C-RFC-655-%7C-%2333930-%5BWIP%5D?node-id=2060%3A5275)
- Copy should match designs
- [Web](https://sg-web-jdb-update-filter-text.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-pzcfkozubo.chromatic.com)
=> update filter text

CHANGELOG.md
Changelog Cut for `sourcegraph@3.41.0`
=> changelog: cut sourcegraph@3.41.0

CHANGELOG.md
Updates changelog for https://github.com/sourcegraph/sourcegraph/pull/36341
- N/A
=> Add dashboard pills to the 3.41 CHANGELOG

client/web/src/tour/GettingStartedTour.tsx, client/web/src/tour/data/index.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/37402.
| BEFORE | AFTER |
| --: | :-- |
| <img width="379" alt="image" src="https://user-images.githubusercontent.com/6717049/174566929-b6367c45-421e-4650-8971-3fc3f513cdd8.png"> | <img width="379" alt="image" src="https://user-images.githubusercontent.com/6717049/174566842-65b00ce6-6eee-4452-93e9-5225bfc9fe17.png"> |
|<img width="379" alt="image" src="https://user-images.githubusercontent.com/6717049/174566988-504570f5-952d-4981-9950-0c7ef157a2d9.png"> | <img width="379" alt="image" src="https://user-images.githubusercontent.com/6717049/174566733-98ac7a50-46a8-4066-bfd7-3a40fa24fb97.png"> |
- Review code
- [Web](https://sg-web-erzhtor-fix-capitalization-in.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-qdllvtppth.chrom …
=> Fix capitalization in "Code search basics" list

doc/admin/observability/dashboards.md, monitoring/definitions/frontend.go, monitoring/definitions/shared/batches.go, monitoring/definitions/worker.go
No idea why we never added these, I've been missing them while doing some performance debugging, so adding them now.
Tested locally the dashboards work.
=> Add dashboards for batches workers

client/web/src/enterprise/searchContexts/SearchContextForm.tsx, client/web/src/integration/search-contexts.test.ts, client/web/src/integration/search.test.ts
This commit updates those tests (well, one of them), to also test the
CodeMirror implementation.
Integration test tests CodeMirror implementation and passes.
- [Web](https://sg-web-fkling-cm-search-context.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-pytxajgpyg.chromatic.com)
=> search: Update search context integration tests to test CM implementation

client/vscode/LICENSE
Adding the year and name of copyright owner for the VS Code licensing.
N/A
- [Web](https://sg-web-correct-vscode-licensing.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-afdikatnhf.chromatic.com)
=> Updating license for VS Code

.github/workflows/label-move.yml
=> Add executors board

dev/release/src/changelog.ts, dev/release/src/release.ts
Automate the helm changelog updates for each release, and fix a couple QoL issues seen when performing the latest patch release.
Closes https://github.com/sourcegraph/sourcegraph/issues/37430
Tested changelog update locally
=> Update release process to include helm steps

cmd/frontend/graphqlbackend/search_results.go, cmd/frontend/internal/search/search.go
Previously, `LogBackendEvent` spun up its own goroutine, and used the passed-in wait group to handle cleaning it up. It's generally preferable to leave the responsibility of spinning up goroutines to the caller, and this is complicating some refactors I've got queued, so this modifies it to be a synchronous function that can instead be backgrounded by the caller.
Unit tests and manual smoke tests.
=> Search backend: move concurrency handling to caller of LogBackendEvent

enterprise/internal/batches/store/batch_changes.go, enterprise/internal/batches/store/batch_spec_workspace_execution_jobs.go, enterprise/internal/batches/store/batch_specs.go, enterprise/internal/batches/store/changeset_events.go, enterprise/internal/batches/store/changesets.go
=> Fixup DB source comments in batches codebase

doc/admin/repo/permissions.md
Fixes #36456.
Doc changes only.
=> doc: Add bitbucket project perms explicit API usage docs

go.mod, go.sum, lib/go.mod, lib/go.sum
This includes a fix for the default log level.
Relying on test suite.
=> Use latest version of log library

cmd/gitserver/main.go, cmd/gitserver/server/server.go, cmd/gitserver/server/server_test.go, cmd/repo-updater/shared/main.go, enterprise/internal/insights/background/historical_enqueuer.go, enterprise/internal/insights/background/historical_enqueuer_test.go, enterprise/internal/insights/background/queryrunner/work_handler.go, enterprise/internal/insights/background/queryrunner/worker.go, enterprise/internal/insights/compression/worker.go, enterprise/internal/insights/compression/worker_test.go, internal/cmd/ghe-feeder/main.go, internal/cmd/ghe-feeder/worker.go, internal/codeintel/autoindexing/internal/inference/init.go, internal/codeintel/autoindexing/internal/inference/service.go, internal/codeintel/autoindexing/internal/inference/service_test.go, internal/database/gitserver_repos.go, internal/extsvc/github/v3.go, internal/ratelimit/rate_limit.go, internal/ratelimit/rate_limit_test.go, internal/repos/purge.go, internal/repos/sync_errored.go, internal/repos/syncer_test.go, internal/repos/types.go
Closes https://github.com/sourcegraph/customer/issues/880
Existing tests should pass
=> instrumentation: use instrumented version of rate limiter everywhere

client/web/src/search/results/DidYouMean.tsx
Addressing feedback https://github.com/sourcegraph/sourcegraph/pull/37588#discussion_r905263903
- [Web](https://sg-web-rvt-aria-hidden.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-hmhnosahcw.chromatic.com)
=> search: use aria-hidden for suggestion

doc/admin/deploy_executors.md
Found by a user here: https://github.com/sourcegraph/sourcegraph/issues/37559
Docs change.
=> Fixup some small issues in executor binary docs

internal/search/job/jobutil/feeling_lucky_search_job.go, internal/search/job/jobutil/feeling_lucky_search_job_test.go
lucky search currently notifies the user of alternative queries that ran, even when those queries return 0 results. This PR collects the count of results coming from each generated query and only sends the notification if we found results.
Pretty cool! Yes, this needs more bookkeeping overhead but it's so valuable I think it's worth it. The previous state is OK for a small number of suggestions, but as the query generation grows, this is going to get out of hand.
Aside: generated query job cancellation appears to not work, it's supposed to also not notify if we've already sent 500+ results total. I've never seen the context cancelled abort lucky search [in this code block locally](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/job/jobutil/feeling_lucky_se …
=> search: enrich lucky search suggestions

dev/pr-auditor/README.md, dev/pr-auditor/batch-changes/README.md, dev/pr-auditor/batch-changes/pr-auditor-patch.yml, dev/pr-auditor/batch-changes/pr-auditor-rollout.yml
Aligns the patch BC with what we currently use as a source of truth. Also document this batch change
This was used to create https://k8s.sgdev.org/users/robert/batch-changes/pr-auditor-patch-06-16 , e.g. https://github.com/sourcegraph/sourcegraph/pull/37367
=> dev/pr-auditor: update patch batch change

doc/batch_changes/tutorials/search_and_replace_specific_terms.md
This commit updates the example to use a prebuilt image. Additionally it includes a simplified spec for the common case.
I recently went through this tutorial, and was frustrated with it for two reasons:
- running cargo was very slow
- As a standard example, this should be very simple to do.
So I pushed an image which runs ruplacer so you don't have to run cargo. I also included an example where we don't try include/exclude specific files.
Question: Do we want somewhere an example of building a container locally to speed up the batch changes workflow? I'm not sure if this was documented elsewhere, even though here it is a side-effect of reading the old tutorial.
Future:
- We probably want to publish a ruplacer image under the sourcegraph dockerhub org.
- It feels like there is scope for a …
=> doc: use prebuilt container for ruplacer in batch changes

doc/adopt/index.md
=> Add Venn Diagram PDF

doc/code_intelligence/how-to/adding_lsif_to_many_repos.md, doc/code_intelligence/how-to/index.md
=> docs: Replace LSIF mentions with precise indexing.

client/web/src/enterprise/codeintel/indexes/components/EnqueueForm.tsx
I wasn't entirely sure how to create a `<Link to=CodeIntelConfigurationPage>` because that seems
to require passing a bunch of problems which I don't know if we have in context. So I've just mentioned
it textually for now.
How should I be testing this outside of manual checking? :clueless:
- [Web](https://sg-web-vg-fix-0-enqueued.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-unwsyxftqc.chromatic.com)
=> client: Don't treat 0 jobs enqueued as a success.

dev/codeintel-qa/cmd/clear/main.go, dev/codeintel-qa/cmd/query/main.go
=> ci(flake): Disable test properly.

.github/ISSUE_TEMPLATE/code-intel.md
Merge this PR and see the new template page  https://github.com/sourcegraph/sourcegraph/issues/new/choose
=> Add template for code intel issues

cmd/frontend/graphqlbackend/site_analytics.go, internal/adminanalytics/cache.go, internal/adminanalytics/fetcher.go, internal/adminanalytics/search.go
=> Add caching for admin analytics

doc/batch_changes/explanations/server_side.md
=> build images for the `linux/amd64` host

client/web/src/integration/insights/create-insights.test.ts
Skips failing flaky test in `create-insights.test.ts`
Issue to resolve this properly: https://github.com/sourcegraph/sourcegraph/issues/37701
N/A
- [Web](https://sg-web-insights-skip-flaky-test.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-leixkwvufe.chromatic.com)
=> Skip flaky test

client/vscode/CHANGELOG.md, client/vscode/README.md, client/vscode/package.json, doc/integration/editor.md, doc/integration/gitpod.md
Close:
This PR:
Updates docs for Gitpod support.
Updates logo in the sidebar as requested by the branding team:
See screenshots for logo update. 
- [Web](https://sg-web-bee-vsce-logo.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-sdpxnqwuup.chromatic.com)
=> VSCE: patch release v2.2.5 - update logo and add support for Gitpod

doc/dev/adr/1655963328-sunset-datadog.md, doc/dev/adr/how-to.md, doc/dev/adr/index.md
=> doc/dev: fix headers again

dev/sg/internal/db/db.go, dev/sg/sg_migration.go
=> migration: Reuse os.DirFS code

internal/database/migration/runner/options.go
List what's ambiguous, at the least.
N/A.
=> migration: Improve ambiguous revert message

dev/release/src/github.ts
=> update placeholder for release template

doc/dev/adr/1656412873-stop-using-bka-for-backend-tests.md, doc/dev/adr/index.md
Self-explanatory. Fixes https://github.com/sourcegraph/sourcegraph/issues/35638 
Discussion prior to the decision: https://docs.google.com/document/d/1n0WdwtvXXaB7bYtrXQav_-vvs6go21bcpoNDvvYyRRQ/edit# 
ADR so n/a
=> adr: stop using bka for backend tests

cmd/gitserver/server/server.go
While looking at https://sentry.io/organizations/sourcegraph/issues/3381789776/?project=5596888&query=is%3Aunresolved, I found that these errors have basically no scope outside the root one. Overall it seems that the scopes are a bit underutilized in Gitserver. 
This PR is a small suggestion to possibly get started on this as this would help. 
Two things to note:
- There is this PR https://github.com/sourcegraph/log/pull/13 to stop sending transient errors to Sentry 
- We could use scopes to gauge error rates, including on the transient ones, enabling to have a better use of the the errors signal. 
➡️ Thoughts? 
n/a logging changes and ci should cover it.
=> gs: add more logger scopes on a few handlers

internal/observation/observation.go
This is a stop-gap solution to get some degree of (local-ish) tracing using the Honeycomb Events API until we migrate to OpenTelemetry. The method is pretty self-explanatory based on the honeycomb docs on shipping the current span ID, parent span ID and trace ID.
There seems to be a mixed prior art between `trace.trace_id`, `trace_id` and (less commonly) `traceID`, so this PR consolidates at least code instrument with this package on `trace.trace_id`, based on the [Honeycomb docs](https://docs.honeycomb.io/getting-data-in/tracing/send-trace-data/#opentelemetry).
Tested by hand, just telemetry changes
=> honeycomb: stopgap partial traces in honeycomb

client/web/src/marketing/page/SurveyForm.tsx, client/web/src/marketing/toast/SurveyToast.test.tsx, client/web/src/marketing/toast/SurveyUseCaseToast.tsx
We missed this when reviewing https://github.com/sourcegraph/sourcegraph/pull/34589. This PR fixes the capitalisation!
N/A - Copy change
- [Web](https://sg-web-tr-survey-fix-type.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-pulrjutjwl.chromatic.com)
=> NPS Prompt: Fix typo

doc/admin/repo/permissions.md
=> docs: Clarify that setRepositoryPermissionsUnrestricted takes repo ids
