doc/admin/deploy/kubernetes/configure.md
Fix broken page
Docs, ran the docsite locally to review changes
=> doc: make kustomize configure page readable

internal/database/repos.go
Rather than complication allMatchingStrings with a last param, we should
instead move this logic into the only place it is used, for working out
what to do with a concat.
plz-review-url: https://plz.review/review/6590
=> database: inline .* check for allMatchingStrings

client/web/src/site-admin/SiteAdminArea.tsx, client/web/src/site-admin/analytics/index.tsx, client/web/src/site-admin/analytics/queries.ts, cmd/frontend/graphqlbackend/schema.graphql, cmd/frontend/graphqlbackend/site_analytics.go, internal/adminanalytics/notebooks.go, internal/adminanalytics/utils.go
=> Add notebooks stats to admin analytics

dev/buildchecker/slack.go, dev/buildchecker/slack_test.go
Removing the oof 😆 https://sourcegraph.slack.com/archives/C01N83PS4TU/p1656603021407609?thread_ts=1656589883.978399&cid=C01N83PS4TU
ran the unit tests
=> fix(buildchecker): remove okayhq mention

internal/search/streaming/stream.go
Streams will never be nil anymore, so we don't need any of the checks we
used to.
Unit tests.
=> Search backend: remove nil check

client/vscode/src/webview/search-panel/components/BrandHeader.tsx, client/web/src/search/home/SearchPage.tsx, client/web/src/search/home/SelfHostInstructions.tsx
- [Web](https://sg-web-rpp-dotcom-link-updates-winddown.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-wgaanaicup.chromatic.com)
=> More link updates for dotcom announcement

doc/admin/repo/perforce.md
=> docs: Add some basic docs for p4-fusion

client/jetbrains/README.md
As [discussed](https://docs.google.com/document/d/1ZvsSwc5oPi6Q4YVqy0DUcy-2FCGtswNxk5omxaIBld0/edit#heading=h.3ecr38rfbh7d) today.
(only doc change)
=> Add "yarn watch" to docs

enterprise/internal/rockskip/search.go
Removes a print statement.
N/A
=> rockskip: Remove print statement

enterprise/cmd/frontend/internal/codeintel/resolvers/resolver.go
I ran into the diagnostic warning while doing something else in this
file, thought I'd fix it.
=> codeintel resolvers: fix duplicate import of dbstore

enterprise/internal/authz/perforce/protects.go, enterprise/internal/authz/perforce/protects_test.go, internal/authz/sub_repo_perms.go
Specifically, test the case outline here:
https://www.perforce.com/manuals/p4sag/Content/P4SAG/protections-implementation.html
Closes https://github.com/sourcegraph/sourcegraph/issues/38107
Tests added
=> authz: Add more perforce permissions tests

cmd/gitserver/p4-fusion-install-alpine.sh
=> Upgrade p4 fusion

doc/code_insights/explanations/automatically_generated_data_series.md, doc/code_insights/explanations/current_limitations_of_code_insights.md, doc/code_insights/how-tos/filtering_an_insight.md
Small docs edits based on unify effort and an update on sort/filter.
resolves [35818](https://github.com/sourcegraph/sourcegraph/issues/35818)
docs only
=> insights: update insights docs

CHANGELOG.md
Add change log entry for new behavior for insights over some repos.
=> insights: update change log for just in time insight conversion

internal/search/job/jobutil/feeling_lucky_search_job.go, internal/search/job/jobutil/feeling_lucky_search_job_test.go
=> search: fix duplicate results in lucky search

cmd/frontend/graphqlbackend/schema.graphql, internal/search/run/run.go, internal/search/run/run_test.go
=> search: expose V3 for query interpretation

dev/gqltest/search_test.go
Flake [here](https://buildkite.com/sourcegraph/sourcegraph/builds/158839#0181d641-39a0-4e93-b243-f5054fabbab8). I've seen this one a few times.
N/A
=> Search: disable flaky integration test

cmd/gitserver/server/cleanup.go, cmd/gitserver/server/cleanup_test.go, cmd/gitserver/server/server.go
Closes https://github.com/sourcegraph/sourcegraph/issues/38065
Existing unit test updated
=> gitserver: update janitor, so it sets repo sizes not just once, but during every run

client/search-ui/src/CODENOTIFY, client/search/src/CODENOTIFY, client/shared/src/search/CODENOTIFY
n/a
- [Web](https://sg-web-fkling-search-code-codenotify.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-gfgvfsmmfe.chromatic.com)
=> Subscribe myself to search code file changes

internal/adminanalytics/cache.go
Forgot to revert local dev changes to cache interval.
- Check diff
=> Update admin-analytics background job cache interval

internal/search/job/jobutil/feeling_lucky_search_job.go, internal/search/result/deduper.go, internal/search/streaming/stream.go, internal/search/streaming/stream_test.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/38446.
As in title
Added test
=> search: add deduping stream constructor

internal/adminanalytics/users.go, internal/adminanalytics/utils.go
=> Fix admin-analytics chart SQL queries

internal/adminanalytics/users.go, internal/adminanalytics/utils.go
This PR refactors "analytics / users" / actitivities query to use `makeEventLogsQueries` utility function
- Check diff
=> Update "analytics / users" / actitivities query to use utility function

client/web/src/site-admin/SiteAdminArea.tsx, internal/adminanalytics/users.go
- Fix "analytics / users" chart
- Re-order "Notebook" sidebar link item
- Check diff
=> Fix "analytics / users" chart

internal/search/job/jobutil/feeling_lucky_search_job.go
Just a simplification I spotted. No reason to not allow individual rules to be a composition of rules.
Semantics preserving
=> search: simplify rule generator type

internal/search/job/jobutil/feeling_lucky_search_job.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/38492
Just simplifies some silliness in the logic because I wasn't focused on making that easy before.
=> search: simplify generator logic

dev/gqltest/search_test.go
=> gqltest: disable flakey test case

internal/search/job/jobutil/limit.go
This adds a log to our LimitJob when it cancels the child context so we
can see in the traces when thngs were canceled by the LimitJob.
=> Search backend: add trace log when the limit job cancels child context

internal/search/job/jobutil/feeling_lucky_search_job.go, internal/search/job/jobutil/testdata/TestCombinations/narrow_and_widen_rules.golden, internal/search/job/jobutil/testdata/TestCombinations/only_narrow_rules.golden, internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/pattern_as_type_multi_patterns.golden, internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/trigger_unquoted_rule.golden, internal/search/job/jobutil/testdata/TestNewFeelingLuckySearchJob/type_and_lang_multi_rule.golden
Stacked on https://github.com/sourcegraph/sourcegraph/pull/38515
It looks spiffy. Please let me have this until designers maybe complain that it's somehow confusing.
=> search: separate rule description with a little circle

internal/search/job/jobutil/feeling_lucky_search_job.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/38516.
Semantics-preserving
=> search: delete static lucky rules

dev/sg/internal/images/images.go
These changes enable to run `sg ops udate-images` on `sourcegraph/deploy-sourcegraph-cloud` repo. 
3 others engineers witnessed the local testing, this is soc-4 compliant 🐉
=> sg: ops update-images, only update our images

doc/cli/references/batch/apply.md, doc/cli/references/batch/preview.md, internal/src-cli/consts.go
Manual testing in executors once released.
=> Bump src-cli version to 3.41.1

doc/code_intelligence/explanations/writing_an_indexer.md
Locally generated and visually checked the docs
=> docs: Fix bugs in writing an indexer page.

doc/code_intelligence/explanations/writing_an_indexer.md
=> docs: Add blank lines before lists 🙄

client/jetbrains/src/main/java/com/sourcegraph/website/SearchActionBase.java
Fixes https://github.com/sourcegraph/sourcegraph/issues/38003
The neat thing about this change is that now the logic for checking whether we can search for the selection is the same as the logic that decides whether the related actions are enabled in the first place.
So there is no way anymore for the menu items to be enabled if we can't make a search!
- [short loom demo](https://www.loom.com/share/41475bd014f042d3a902d8f32cd832ff)
- At the end of the demo I said that the "Search selection in repository" feature didn't change—what I meant here was that the rest of its functionality didn't change. The "if there's no selection then search for the whole line" logic is applied for that feature as well.
- [Web](https://sg-web-dv-jetbrains-search-for-whole-line.onrender.com)
- …
=> Search for whole line in case of no selection

doc/dev/adr/1657287546-consolidate-redis-store-and-redis-cache-in-a-single-instance.md, doc/dev/adr/index.md
Follow-up to what has been discussed in the [Backend Crew meeting](https://docs.google.com/document/d/1Y51d863Nuqr9BzbTbwwSF9jes0ro71vB724oc2p8qsQ/edit#bookmark=kix.q3glfa62kub9)
How to review:
1. Check that the wording accurately reflect our decision
2. If you're against the decision, post a comment
n/a it's an adr
=> adr: consolidate redis

enterprise/cmd/worker/internal/permissions/bitbucket_projects.go, enterprise/cmd/worker/internal/permissions/bitbucket_projects_test.go
This includes using correct external service type and fixing an edge case when the Bitbucket project contains only users which are not yet added to Sourcegraph.
Closes https://github.com/sourcegraph/sourcegraph/issues/38569
New unit test added
=> worker: fix Bitbucket Projects permissions sync

internal/codeintel/dependencies/internal/lockfiles/dependency_graph.go, internal/codeintel/dependencies/shared/types.go
This addresses https://github.com/sourcegraph/sourcegraph/pull/37543#discussion_r913941594.
=> dependencies: use size for slices if known

internal/codeintel/dependencies/iface.go, internal/codeintel/dependencies/internal/lockfiles/service.go, internal/codeintel/dependencies/internal/lockfiles/service_test.go, internal/codeintel/dependencies/internal/store/store.go, internal/codeintel/dependencies/mocks_test.go, internal/codeintel/dependencies/service.go, internal/codeintel/dependencies/service_test.go
Addresses another 2-3 comments in https://github.com/sourcegraph/sourcegraph/pull/37543
=> dependencies: review follow-up to remove pointers and add comment

dev/release/release-config.jsonc
In preparation for 3.41.1 patch release
Part of https://github.com/sourcegraph/sourcegraph/issues/38614
None, config change only
=> dev: Update release-config

cmd/frontend/graphqlbackend/default_settings.go
=> Enable Starlark extension by default

client/web/src/integration/batches.test.ts
Appears still to be flaky, have reopened https://github.com/sourcegraph/sourcegraph/issues/37233
Failure on `main` [here](https://buildkite.com/sourcegraph/sourcegraph/builds/159986#0181f2dd-6959-4065-90d5-aaf8c6131b29/6-109)
N/A - CI only
- [Web](https://sg-web-tr-disable-batches-test.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-wczxdxqbld.chromatic.com)
=> Integration tests: Disable flaky batch changes test

doc/dev/background-information/ci/development.md
Add some information to the annotation and observability parts about grafana link use and generation
Ran `sg run docsite` and looked at my changes
=> docs(sg/ci): update pipeline with grafana link generation

enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/indexers.go, enterprise/cmd/worker/internal/codeintel/indexing/dependency_sync_scheduler.go, internal/codeintel/autoindexing/infer.go, internal/codeintel/autoindexing/internal/inference/lang_python_test.go, internal/codeintel/autoindexing/internal/inference/lua/.stylua.toml, internal/codeintel/autoindexing/internal/inference/lua/README.md, internal/codeintel/autoindexing/internal/inference/lua/clang.lua, internal/codeintel/autoindexing/internal/inference/lua/go.lua, internal/codeintel/autoindexing/internal/inference/lua/java.lua, internal/codeintel/autoindexing/internal/inference/lua/python.lua, internal/codeintel/autoindexing/internal/inference/lua/recognizers.lua, internal/codeintel/autoindexing/internal/inference/lua/rust.lua, internal/codeintel/autoindexing/internal/inference/lua/shared.lua, internal/codeintel/autoindexing/internal/inference/lua/test.lua, internal/codeintel/autoindexing/internal/inference/lua/typescript.lua, internal/codeintel/autoindexing/internal/inference/lua/util.lua
Don't merge yet, this dockerfile doesn't exist yet on docker hub. Just pushing to get feedback from @efritz
=> feat: Add autoindex for Python

dev/sg/internal/background/background.go, dev/sg/sg_update.go, dev/sg/sg_version.go
=> dev/sg: add pending spinner to manual 'sg update'

enterprise/internal/compute/CODENOTIFY
=> compute: codenotify @rvantonder

client/search-ui/src/input/toggles/Toggles.tsx
There are concerns about this toggle confusing users with lucky search:
I've decided to remove it and just default to our default toggles, this because:
- Lucky search is not about this UI change and I don't want people to fixate on it. It's easy to fixate on this silly thing when it's really really not the point.
- The toggle existed so that you can disable lucky search in the UI and fall back to literal/standard search. This so that I and others wouldn't have to go and change settings to change the default search as an only way to deactivate lucky search. I now have high confidence (lol) that lucky search works well so I'm comfortable just enabling it as the default for internal dog fooding. If someone wants to opt out they won't have the convenience of a toggle, they'll simply have to …
=> search: remove advanced toggle for lucky search

CHANGELOG.md, doc/admin/deploy/kubernetes/troubleshoot.md, doc/admin/deploy/resource_estimator.md
Docs update for https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/148 and https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/148
RE: https://github.com/sourcegraph/customer/issues/1094 & https://github.com/sourcegraph/customer/issues/385
Docs update
=> Add istio issue to troubleshooting docs

dev/codeintel-qa/README.md, doc/admin/external_service/aws_codecommit.md, doc/admin/external_service/bitbucket_cloud.md, doc/admin/external_service/bitbucket_server.md, doc/admin/external_service/github.md, doc/admin/external_service/gitlab.md, doc/admin/external_service/gitolite.md, doc/admin/external_service/non-git.md, doc/admin/external_service/other.md, doc/admin/external_service/phabricator.md, doc/admin/external_service/src_serve_git.md, doc/admin/repo/auth.md, doc/admin/repo/permissions.md, doc/code_intelligence/how-to/adding_lsif_to_many_repos.md, doc/code_search/how-to/adding_repositories_to_cloud.md
I tested locally and this is a docs-only change.
=> Update language for manage repos to manage code hosts

doc/code_intelligence/index.md
=> Bring back indexers shortcut button to main code intel doc

client/search-ui/src/input/CodeMirrorQueryInput.tsx
It's unsatisfying to find a solution to a problem and not understand
why the solution fixes the problem... this is the case here. I don't
know how the syntax highlighting extension could interfere with the
other extension or the editor focus, especially since it's only executed
when the query changes.
But alas, moving the extension after the current filter highlighting
extension fixes the issue. ¯\\_(ツ)_/¯
Before/after video: 
https://user-images.githubusercontent.com/179026/178593849-a2ebe610-4933-4372-827e-bca251a12eab.mp4
Fixes https://github.com/sourcegraph/sourcegraph/issues/38677 (but in an unsatisfying way...)
Enter filter into query. Tab out of the query input. Tabbing out is successful.
- [Web](https://sg-web-fkling-codemirror-focus-bug-2.onrender.com)
- …
=> search: Fix highlight filter focus bug

dev/release/release-config.jsonc
Changing release captain just in case any issue may arise (Ryan is OOO and I continue releasing the patch)
config change -- no tests needed
=> dev: update release config

CHANGELOG.md
Adding changelog entries for 3.41.1 patch
Documentation change, no tests needed
=> add changelog entries for 3.41.1

doc/dev/background-information/ci/index.md, doc/dev/how-to/ci_soft_failure_and_still_notify.md, doc/dev/how-to/index.md, doc/dev/how-to/receive_slack_notification_on_a_failed_ci_step.md, enterprise/dev/ci/internal/buildkite/step_notify.go
Follow-up of #38650, document the whole thing into how-tos
=> Document how to use the custom step slack notifs

enterprise/dev/ci/internal/ci/operations.go
does what it says on the tin
n/a, is doing test stuff
=> codeintel: soft-fail and alert on codeintel-qa failure

internal/codeintel/dependencies/CODENOTIFY
=> Add CODENOTIFY (and myself in it) to internal/codeintel/dependencies

dev/ci/integration/code-intel/test.sh, dev/codeintel-qa/cmd/query/main.go, dev/codeintel-qa/cmd/upload/state.go, dev/codeintel-qa/cmd/upload/upload.go
Adds more logging to codeintel-qa to debug flake
n/a, more debugging in tests
=> [debug] codeintel: print uploads IDs where possible

lib/errors/level_test.go, lib/errors/levels.go
Part of #38612.
Fixes #38615.
This error type is not used at the moment.
But it will be the next step.
New code that is not used anywhere yet. Also added some minimal tests to ensure this works for now. Will build upon it in future PRs.
=> lib/errors: Add new classifiedError type

doc/admin/external_services/postgres.md
=> add note about externalizing codeinsights-db

cmd/server/Dockerfile
This brings minio in line with the version in docker-images/minio/Dockerfile
CI checks
=> Update minio image in server Dockerfile

internal/codeintel/dependencies/internal/store/store.go
Noticed while working on something else.
=> dependencies observability: use correct operation in store

doc/admin/repo/permissions.md
=> doc: fix links to Setting Repository Permissions For Users

client/web/src/site-admin/analytics/AnalyticsBatchChangesPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsNotebooksPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsSearchPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsUsersPage/index.tsx, client/web/src/site-admin/analytics/components/AnalyticsPageTitle.tsx, client/web/src/site-admin/analytics/components/index.module.scss
* Removes information icon and tooltip from breader, moves tooltip to footer
* changes text weight on KPIs
* Small copy tweaks
Manual review of visual changes.   
- [Web](https://sg-web-rrhyne-aa-ui-tweaks.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-kzdapawpyf.chromatic.com)
=> admin analytics ui tweaks

dev/codeintel-qa/cmd/upload/state.go
=> codeintel-qa: Run `pg_dump` inside server image

CHANGELOG.md, cmd/symbols/squirrel/lang_java.go, cmd/symbols/squirrel/lang_python.go, cmd/symbols/squirrel/local_code_intel.go, cmd/symbols/squirrel/service.go, cmd/symbols/squirrel/service_test.go, cmd/symbols/squirrel/test_repos/python/example.py, cmd/symbols/squirrel/test_repos/python/example2.py, cmd/symbols/squirrel/test_repos/python/sub/example3.py, cmd/symbols/squirrel/util.go
Adds tree-sitter traversal logic for Python.
Go tests
=> squirrel: Add support for Python non-locals

client/web/src/site-admin/analytics/AnalyticsNotebooksPage/index.tsx
- visit https://sourcegraph.test:3443/site-admin/analytics/notebooks
- [Web](https://sg-web-naman-admin-analytics-update.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-octpfwlfbr.chromatic.com)
=> [Admin Analytics] update notebooks suggestion

cmd/searcher/internal/search/search_structural_test.go
Failure: https://buildkite.com/sourcegraph/sourcegraph/builds/160918
- N/A
=> Disable flaky StructuralLimits/exact_limit test

internal/services/executors/transport/graphql/validation.go
Pointed out by @efritz in https://github.com/sourcegraph/sourcegraph/pull/38815#discussion_r921328533 in another place (where I copy & pasted the code here).
This is safer.
=> From the shadow emerges: an error

enterprise/internal/batches/service/workspace_resolver.go, enterprise/internal/batches/service/workspace_resolver_test.go
Lost this somewhere in refactors.
Adjusted test suite.
=> Properly skip workspaces with no steps again

internal/repos/github.go, internal/repos/github_test.go
=> repos: remove unused exampleRepositoryQuerySplit

doc/batch_changes/index.md
=> clarifying monorepo support is experimental

dev/sg/main.go
This prevents updates from potentially being botched I think
=> dev/sg: wait for background jobs on interrupt

dev/sg/internal/images/compose.go
🤦 
same as https://github.com/sourcegraph/sourcegraph/pull/38827
=> dev/sg: fix compose file updating

cmd/frontend/graphqlbackend/commit_search_result.go, cmd/frontend/graphqlbackend/graphqlbackend_test.go, cmd/frontend/graphqlbackend/repository.go, cmd/frontend/graphqlbackend/repository_test.go, cmd/frontend/graphqlbackend/search_test.go, cmd/frontend/graphqlbackend/user.go, enterprise/cmd/frontend/internal/compute/resolvers/resolvers.go, go.mod, go.sum
Reverts sourcegraph/sourcegraph#38902 - merged too soon 😬 
Test plan: n/a
=> Revert "[SG-37398] - Migrate graphqlbackend.RepositoryResolver to use sourcegraph/log"

dev/sg/dependencies/shared.go
Rob ran into some issues with permissions of the generated completion script and sg home directory that was causing completions to not work with:
```
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]?
```
To work around this, we ensure the directory and the script have liberal permissions applied. 
Manually applying this fix fixed Rob's issue. To ensure it continues working for everyone else:
1. remove completions file
2. `go run ./dev/sg setup -f`
3. completions continue to work
=> dev/sg: set up sg home, autocomplete script with 0777

doc/dev/background-information/sg/reference.md, internal/database/migration/cliutil/up.go, internal/database/migration/cliutil/util.go, internal/database/migration/cliutil/validate.go
Applying @chrismwendt's suggestions from a prematurely merged #38917.
N/A.
=> migrator: Organize out of band migration runner construction

client/web/src/enterprise/batches/batch-spec/edit/DownloadSpecModal.story.tsx, client/web/src/enterprise/batches/batch-spec/edit/DownloadSpecModal.tsx, client/web/src/enterprise/batches/batch-spec/edit/EditBatchSpecPage.tsx
Closes #37360
checked to ensure the button functions the same as it did previously 
- [Web](https://sg-web-aa-restore-dontshow.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-vochffkxfr.chromatic.com)
=> batches: restore 'dont show again' button

internal/database/user_credentials.go
As spotted by @eseliger, rather embarrassingly for me.
This means I didn't even need to plumb the logger through `userCredentialsStore` in #38855, but I'm not going to revert that now. I assume this is the new best practice anyway.
We have test coverage here. No tests were ~~harmed~~ changed in the making of this PR.
=> database: remove unnecessary query

client/web/src/enterprise/batches/batch-spec/edit/DownloadSpecModal.tsx, client/web/src/enterprise/batches/batch-spec/edit/RunServerSideModal.module.scss, client/web/src/enterprise/batches/batch-spec/edit/RunServerSideModal.tsx
observed changes in storybook
- [Web](https://sg-web-aa-ssbc-video2.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-alnjijzktn.chromatic.com)
=> batches: enlarge video

client/web/src/regression/codeintel.test.ts
For less (┛ಠ_ಠ)┛彡┻━┻.
n/a
- [Web](https://sg-web-vg-disable-flake.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ndsaumagrs.chromatic.com)
=> ci(flake): Skip codeintel e2e test.

internal/gitserver/client.go
It's not used anywhere outside of the gitserver package
All tests still pass
=> gitserver: Client UserAgent can be private

internal/adminanalytics/fetcher.go
Fix admin analytics charts timezone issue. 
For the last 3 months, the loop to populate missing nodes starts from `from` date i.e 3 months back from now and adds 7 days in each iteration.  The DB aggregates data and returns Monday of the week as the date for the node, but the `from` date may not be Monday as it is just the current date minus 3 months. 
The fix is the start from `to` date which will be Monday of the current week and go back 7 days in each iteration to match the date value of nodes returned by the DB.
The last fix didn't work because it was built, tested and deployed on Monday so at that time it worked correctly. 
Check PR.
=> [Admin Analytics] fix admin analytics timezone issue

internal/adminanalytics/fetcher.go, internal/adminanalytics/notebooks.go, internal/adminanalytics/notebooks_test.go
Add tests for Admin Analytics Notebooks Creation metric to test out Admin Analytics Fetcher commonly used by all other metrics.
- go test ./internal/adminanalytics/
=> [Admin Analytics] add fetcher tests

internal/src-cli/consts.go
Will test executors with this version once they're deployed.
=> Bump src cli for release

dev/sg/internal/check/runner.go
Follow-up to #38878 - I didn't see that the categories themselves were
also executed concurrently.
Example failure here: https://buildkite.com/sourcegraph/sourcegraph/builds/161728#01821641-9c22-4e36-a8aa-419e7656521b
=> sg checks runner: fix data race

client/web/src/tree/Directory.tsx, client/web/src/tree/File.tsx, client/web/src/tree/SingleChildTreeLayer.tsx, client/web/src/tree/Tree.tsx, client/web/src/tree/TreeLayer.tsx, client/web/src/tree/TreeRoot.tsx, client/web/src/tree/util.tsx
As we're now [actively working on improving](https://github.com/sourcegraph/sourcegraph/issues/38667) the `Tree` component, this is one of a few small PRs introducing small changes to the code.
1. Check out the branch
2. Ensure tree works as before
3. Make sure tests pass
- [Web](https://sg-web-og-tree-simplify-props.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-zvjxquxxsz.chromatic.com)
=> Tree: simplify props and code a bit

client/web/src/charts/components/line-chart/LineChart.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/38919
- Open https://k8s.sgdev.org/insights/dashboards/ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3MjY0Nzl9 
- Make sure that the hover point does make sense based on the mouse cursor position 
- [Web](https://sg-web-vk-fix-line-chart-point.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-rcdcyxslay.chromatic.com)
=> Code Insights: Fix line chart hover areas distribution

doc/dev/background-information/ci/development.md
=> doc/dev: add some more details about generating annotations in ci

CHANGELOG.md, client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx
Changelog update.
- [Web](https://sg-web-update-changelog.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-qzcdgdvibi.chromatic.com)
=> batches: Update changelog

dev/release/src/release.ts
fixes the error of var name being < 3 chars
CI passing on this PR
=> fix var name too short

docker-images/postgres-12-alpine/Dockerfile
Updating busybox package version to patch awk vulnerability. Not relevant to our product, just hygiene.
Upgraded packaged busybox awk, local scan.
=> Fix busybox awk issue

client/web/src/enterprise/batches/workspaces-list/Descriptor.tsx
All credit to Kelli for finding and fixing this.
Closes https://github.com/sourcegraph/sourcegraph/issues/39091.
Verified on main it works correctly again.
- [Web](https://sg-web-es-kr-fix-scroll-overflow.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-bhfvxwangj.chromatic.com)
=> batches: fix scroll bar regression on batches execution page

CHANGELOG.md
Changelog Cut for `sourcegraph@3.42.0`
=> changelog: cut sourcegraph@3.42.0

doc/admin/repo/permissions.md
Additionally added a virtual-br so the NOTEs appear in there own boxes.
Test Plan: n/a
=> doc: fix link for Bitbucket Server in permissions.md

enterprise/cmd/precise-code-intel-worker/internal/worker/worker.go, enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go, enterprise/cmd/worker/internal/codeintel/indexing/dependency_sync_scheduler.go, enterprise/cmd/worker/internal/permissions/bitbucket_projects.go, enterprise/cmd/worker/internal/permissions/bitbucket_projects_test.go
Removing unused vars and making adding usages of `actor.WithInternalActor` function
Minor refactoring, existing tests should pass
=> chore: clean up unused input parameters in bitbucket_projects.go, use `actor.WithInternalActor` function

yarn.lock
Updates yarn.lock to be back in sycn
N/A Chore update
- [Web](https://sg-web-jdb-update-yarn-lock.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ylgyzfaxep.chromatic.com)
=> re-sync yarn lock file

client/search-ui/src/results/NoResultsPage.module.scss
Fixes https://sourcegraph.slack.com/archives/C03CSAER9LK/p1658340884753859
Verified manually and in visual tests
- [Web](https://sg-web-jp-noresultsvideopadding.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ujypcokfla.chromatic.com)
=> search ui: fix no results page spacing

enterprise/internal/compute/output_command.go
=> compute: simple return value for content output

enterprise/internal/compute/output_command.go, enterprise/internal/compute/output_command_test.go
Stacked on https://github.com/sourcegraph/sourcegraph/pull/39171.
Added test.
=> compute: ensure boundary assertions work on output

cmd/gitserver/server/cleanup.go
Minor cleanup in the cleanup code.
No functional change.
=> gitserver: Minor improvements to code readability in cleanup code

enterprise/dev/ci/internal/ci/changed/diff.go
Fixes #38754
One could argue that all shell scripts should end in `.sh` but it's actually quite common in the wild to just use the shebang, so we'd better address that case for the sake of correctness. 
Ran the generator locally, with a commit including changes to /dev/zoekt/update which is a shell script, but without the extension.
=> ci: detect bash scripts with shebang

doc/code_insights/references/common_use_cases.md
Add another common example 
Review manually, copy update.
=> add docker pinned images example

doc/dev/adr/1658418787-deprecate-raw-git-commands.md, doc/dev/adr/index.md
=> adr: Deprecate raw git commands in gitserver

doc/dev/adr/1657287546-consolidate-redis-store-and-redis-cache-in-a-single-instance.md
Fix the title of the ADR
`sg lint go`
=> fix adr case

internal/repos/sync_worker.go
This was never updated after we introduced the 'failed' state and made 'errored' transient.
As a result, on dotcom we currently have `1,167,159` external_service_sync_jobs, of which.. `1,121,444` should've been deleted, only 4% of that table size are required. This'll likely also yield some nice performance gains.
Validated that older failures I saw on my instance are now gone.
=> Fix external_service_sync_jobs cleanup job

client/web/src/components/Sidebar.tsx
1. Using only the `tab` and `enter` keys select an item in the sidebar.
2. Focus is lost, and users need to manually navigate back to the selected item.
Focus should stay on the currently selected item when clicked
[Sourcegraph issue](https://github.com/sourcegraph/sourcegraph/issues/35866)
[Gitstart ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-35866)
- Go to the site-admin of the web app.
- On the sidebar (on the right side), navigate through using `tab key` and press `Enter` to select an Item.
- Focus should stay on the currently selected item when clicked
- [Web](https://sg-web-contractors-sg-35866.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-wevacesach.chromatic.com)
Check out the [client app preview …
=> [SG-35866] Accessibility: Site admin sidebar: Focus lost when selecting item

client/web/src/search/suggestion/LuckySearch.tsx, internal/search/alert/observer.go
Helps to prepare client-side logging I will add soon.
Tested manually for experimental feature-flagged functionality.
=> search: use backend alert msg in lucky results

doc/admin/updates/pure_docker.md
PR for release
Just markdown, visual checking
=> 3.42 upgrade notes

enterprise/cmd/executor/vm-image/ignite-ubuntu/Dockerfile, enterprise/cmd/executor/vm-image/install.sh
Uses the same install process for both the VM and the ignite image, also some more clarity on what belongs to what.
Rolled this image out to k8s and verified things still work.
=> Some executors image enhancements

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/dev/background-information/ci/reference.md, doc/index.md, enterprise/dev/ci/internal/ci/pipeline.go
This pull request is part of the Sourcegraph 3.42.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/38119)
cc @mohammadualam
=> release: sourcegraph@3.42.0

doc/admin/admin_analytics.md, doc/admin/index.md, doc/admin/usage_statistics.md
Tested locally and only includes documentation updates.
=> Add admin analytics to docs

dev/release/release-config.jsonc
=> release config for 3.43

enterprise/cmd/executor/vm-image/ignite-ubuntu/Dockerfile, enterprise/cmd/executor/vm-image/install.sh
This reverts commit dad1c643b0f01e6cb3f1a4daf4e2d42e580daa9a. Hadolint somehow didn't catch stuff on the branch and it broke main. I don't feel like bash today so reverting.
Revert.
=> Revert "Some executors image enhancements (#39152)"

dev/sg/sg_db.go, doc/dev/background-information/sg/reference.md
Noticed that the description wasn't giving the correct flag name
extremely trivial change
=> sg: fix incorrect username in usage desc

dev/gqltest/external_service_test.go, dev/gqltest/sub_repo_permissions_test.go
Idiot me missed that there was other places to skip 😮‍💨 
Running the backend integration suite for real, so we don't merge that in main for nothing 😵‍💫
=> p4: skip integration tests for now

doc/dev/background-information/oobmigrations.md
=> doc: fix missing comma in the OOB migration example

internal/gitserver/client.go
Integration tests should prove it's ok.
=> gitserver: Remove fallback logic from BatchLog

cmd/frontend/graphqlbackend/repository_mirror.go, cmd/frontend/internal/httpapi/internal.go, cmd/repo-updater/repoupdater/server.go, internal/api/httpapi_schema.go, internal/repos/awscodecommit.go, internal/repos/gitolite.go, internal/repos/sources.go, internal/repoupdater/client.go, internal/repoupdater/protocol/repoupdater.go
Some various little things I found on my trail through the code.
CI will validate, also these are all things that will be statically checked by go.
=> Cleanup some repos code and complete deprecations

enterprise/cmd/executor/vm-image/ignite-ubuntu/Dockerfile, enterprise/cmd/executor/vm-image/install.sh
This reverts commit 40a4d4c24c056dc381ef9264fefb0a18e7adbd03.
Fixed lint errors, CI should tell.
=> Revert "Revert "Some executors image enhancements (#39152)" (#39332)"

internal/codeintel/dependencies/internal/store/observability.go, internal/codeintel/dependencies/internal/store/store.go
There should be a law against this.
- N/A
=> dependencies: use correct operation in store observability

cmd/gitserver/server/server.go, internal/gitserver/client.go, internal/gitserver/mocks_temp.go
It's not bein used anywhere since we can check this in gitserver_repos
now.
Existing tests should pass
=> gitserver: Remove IsRepoCloned

doc/dev/background-information/oobmigrations.md
Improve examples and add a missing entry in YAML.
Docs update
=> doc: minor updates to OOB migration

enterprise/dev/deployment-lag-notifier/slack.go
=> Sets tagged slack handle to devex support

dev/ci/trivy/trivy-artifact-html.tpl
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/aquasecurity/trivy$+type:diff+getCurrentTime&patternType=lucky indicates this was changed
this is a main dry run
=> ci/trivy: fix trivy template

internal/oobmigration/upgrade.go, internal/oobmigration/upgrade_test.go
Add a `from` and `to` parameter to `ScheduleMigrationInterrupts` so that we can filter out any irrelevant out of band migrations while calculating how to perform an instance upgrading.
New unit tests introduced in this PR.
=> oobmigration: Add bounds to `ScheduleMigrationInterrupts`

enterprise/cmd/worker/internal/codeintel/indexing/dependency_sync_scheduler.go, enterprise/cmd/worker/internal/codeintel/indexing/dependency_sync_scheduler_test.go, internal/conf/reposource/npm_packages.go
Fixes https://github.com/sourcegraph/sourcegraph/issues/33251, suggested by @mrnugget.
Added test case.
=> codeintel: Validate package names before insertion.

dev/codeintel-qa/cmd/upload/state.go
Dump lsif_configuration_policies on error
Changing codeintel-qa
=> dump lsif_configuration_policies

internal/oobmigration/runner.go, internal/oobmigration/upgrade.go, internal/oobmigration/version.go, internal/oobmigration/version_test.go
Export a function I'd like to use in another package.
N/A.
=> oobmigration: Export `CompareVersions`

client/web/src/codeintel/ReferencesPanel.tsx
This fixes the issue reported here: https://github.com/sourcegraph/sourcegraph/discussions/35668#discussioncomment-3047580
It fixes it differently than I described there, but I think it now works as expected:
https://user-images.githubusercontent.com/1185253/181267371-38d18bf9-53e3-4f7d-be88-8d238f7ab2e0.mp4
- Manual testing and existing tests, see video above
- [Web](https://sg-web-mrn-handle-click-in-peek-blob.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-gyazayiegg.chromatic.com)
=> ref panel: keep open if user clicks on def inside preview code view

client/web/src/enterprise/batches/batch-spec/edit/library/hello-world.batch.yaml
No test plan: template.
- [Web](https://sg-web-mm-clarify-helloworld.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-iuuujloxaw.chromatic.com)
=> Clarify hello world template

enterprise/internal/insights/resolvers/related_insights_resolvers.go
This prototype doesn't scale to hundreds of series, which is what we have on `k8s` and `demo`. This should have minimal impact on customers. This will allow the endpoint to return without timing out.
This returns the 50 most recently created series, to allow for a demo workflow of creating a new insight and then seeing it appear inline in search.
I tested this by printing to the console what series were being queried for based on the new limiting function, and in the right order. I set the limit to a high number to ensure it was handling out-of-bounds correctly, and a lower number to see it doing the limiting.
=> insights: Limit inline prototype queries to 50

dev/sg/sg_migration.go
=> chore: Rename duplicate aliased import

internal/database/migration/schemas/schemas.go
Add util function that filters a schema slice by name.
N/A.
=> migrations: Add `FilterSchemasByName`

internal/database/migration/stitch/stitch.go, internal/database/migration/stitch/stitch_test.go
This PR wraps two return values into a common struct type.
=> migrations: Add return type to `StitchDefinitions`

cmd/migrator/main.go
Remove a weird function layer that doesn't need to be there.
Tested manually.
=> migrator: Remove runner factory abstraction

internal/database/migration/schemas/schemas.go
Give a weird `fmt.Sprintf` call some context.
N/A.
=> migrations: Extract `MigrationsTableName`

internal/database/migration/stitch/stitch.go
This was just bugging me. Read really off-center.
N/A.
=> chore: Reflow a comment.

internal/database/migration/runner/errors.go
See description :smugcat:
N/A.
=> chore: Fix spelling in error text

doc/admin/deploy_executors.md, doc/admin/executors.md, doc/code_intelligence/explanations/auto_indexing.md, doc/code_intelligence/explanations/auto_indexing_inference.md, doc/code_intelligence/explanations/features.md, doc/code_intelligence/explanations/uploads.md, doc/code_intelligence/how-to/configure_auto_indexing.md, doc/code_intelligence/how-to/configure_data_retention.md, doc/code_intelligence/index.md, doc/code_intelligence/references/auto_indexing_configuration.md, doc/code_intelligence/references/indexers.md
=> Update language support and promote to beta

client/web/src/integration/CODENOTIFY, client/web/src/integration/batches.test.ts
Pending.
- [Web](https://sg-web-bo-fix-flaky-batch-change-details.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-bnjybytmrb.chromatic.com)
Closes #37233
=> batches: fix batch changes details integration test

monitoring/definitions/shared/codeintel.go
Sets the units for the executor runlock panels to milliseconds instead of none
Ran locally, all OK
=> executors: runlock panels with milliseconds units

internal/database/connections/test/store.go, internal/database/migration/runner/iface.go, internal/database/migration/runner/mocks_test.go, internal/database/migration/runner/runner.go, internal/database/migration/shared/types.go, internal/database/migration/store/store.go, internal/database/migration/store/store_test.go
=> database: Rename `migrations/storetypes` package

doc/admin/deploy/scale.md
Add link to worker jobs.
Docs update
=> Add link to worker services

internal/version/upgradestore/store.go, internal/version/upgradestore/store_test.go
Add `GetServiceVersion` method to the upgrade store.
Additional unit tests.
=> upgradestore: Add `GetServiceVersion`

internal/database/gitserver_repos_test.go
Some of the things I found yesterday while looking at the tests.
* Some assertions are made more stable (instead of using anonymous
counts it makes sure that the repos that we expect are iterated).
* Test helpers are reduced so the test doesn't include a lot of
redundant data that has nothing to do with the test.
* Instead of upserting `gitserver_repos` only the column we're
interested in is updated (since the DB trigger ensures a
`gitserver_repo` is inserted).
- These tests
=> db gitserver repos: remove redundant test data and clean up tests a bit

cmd/frontend/graphqlbackend/externallink/repository.go, cmd/frontend/graphqlbackend/externallink/repository_test.go, cmd/frontend/graphqlbackend/repository.go, cmd/frontend/graphqlbackend/search_results_stats_languages.go, enterprise/internal/batches/service/workspace_resolver.go, enterprise/internal/batches/service/workspace_resolver_test.go, internal/gitserver/client.go, internal/gitserver/commands.go, internal/gitserver/mocks.go, internal/gitserver/mocks_temp.go
We only need one and can choose whether it is short or not using a
parameter.
Existing tests pass
=> gitserver: Combine GetDefaultBranch and GetDefaultBranchShort

doc/admin/deploy/docker-single-container/index.md
fix typo
docs change, simple typo fix
=> docs: single docker container typo fix

cmd/frontend/graphqlbackend/site_alerts.go
from #23613
- download Sourcegraph
- verify banner link is correct
=> updated link for configuring https/ssl

doc/_resources/assets/redirects, doc/admin/how-to/site-admin-quickstart.md, doc/cloud/index.md, doc/dotcom/index.md, doc/index.md, doc/sidebar.md
- Update links
- Add Cloud to sidebar
None (docs only).
=> move Cloud managed instance docs to its own section at /cloud

doc/admin/admin_analytics.md, doc/adopt/trial/index.md, doc/sidebar.md
Quick Fix to:
- Adjust bullets on admin analytics page
- Add admin analytics to the sidebar
A docs-only update, tested locally.
=> Update admin analytics docs

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/index.md
This pull request is part of the Sourcegraph 3.42.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/39596)
cc @varsanojidan
=> release: sourcegraph@3.42.1

dev/release/release-config.jsonc
=> release: add instruction for getting slack username

internal/workerutil/worker_test.go
Ticket is here: https://github.com/sourcegraph/sourcegraph/issues/39749
- N/A
=> Disable flaky TestWorkerCancelJobs

cmd/gitserver/server/CODENOTIFY, cmd/repo-updater/CODENOTIFY, internal/gitserver/CODENOTIFY
=> add @sashaostrikov to CODENOTIFY files

.github/workflows/label-notify.yml
Updating GH workflow automation, so no testing
=> Add @ryphil to repo management notify

doc/dev/background-information/sg/reference.md, internal/database/migration/cliutil/upgrade.go, internal/database/migration/cliutil/upgrade_planner.go, internal/database/migration/cliutil/upgrade_runner.go
Fixes #39581. This PR issues a blocking error (which can be disabled via explicitly set user flag) that will ensure your instance is at the version you are upgrading _from_.
=> upgrade: Add bounds check

doc/cli/how-tos/creating_an_access_token.md, doc/code_search/explanations/features.md, doc/code_search/explanations/search_details.md, doc/code_search/how-to/exhaustive.md, doc/code_search/reference/language.md
Update pages for readability and fix some errors.
Documentation update only.
=> docs: Improve readability in code search docs pages

doc/cloud/index.md
Add a few more words to the "Backup and restore" section on the cloud page.
Documentation change: verify that it renders correctly.
=> Expand backup and restore section on cloud page

doc/code_intelligence/explanations/search_based_code_intelligence.md
Update to improve readability and clarity.
Documentation update. Verify that page renders correctly.
=> docs: Improvements to readability in search_based_code_intelligence.md

doc/admin/external_service/bitbucket_cloud.md
Update docs page for better readability and clarity, with some fixes.
Documentation update. Verify that the page renders correctly.
=> docs: Improve bitbucket_cloud.md, grammar fixes

doc/batch_changes/how-tos/index.md
=> Capitalization error correction

doc/adopt/index.md
Fixes link for code search product comparisons
manual test
=> fixes wrong link

client/web/src/components/FilteredConnection/FilteredConnection.tsx
Seems to have been commented out for a while - it already smells funny :)
- N/A
- [Web](https://sg-web-mrn-remove-commented-out-code.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-dyeiurxpth.chromatic.com)
=> Remove commented out code

doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md
Fixed broken links and added a few comments to some commands
=> docs update: fix broken links

internal/search/job/jobutil/repos.go, internal/search/job/jobutil/repos_test.go
This PR adds `DescriptionPatterns` as a field of type `[]*regexp.Regexp` on `RepoSearchJob`. Patterns passed to `repo:has.description` will be compiled to regex during job construction and populated in this field to avoid compiling regex during job execution.
This field is not yet used. Description pattern regex compilation will be added to the job construction step in the next PR when description match highlighting is added.
Unit tests pass
=> search: move compiled description pattern regex to a field on `RepoSearchJob`

doc/dev/how-to/index.md, doc/dev/how-to/sync_repositories_from_gitolite_sgdev_org.md, doc/dev/index.md
@mollylogue asked about this in Slack and I vaguely remembered how to do it, so I dug into it a bit and turns out: what I remembered still works, only the username had to be changed.
- CI
=> docs: document how to connect to gitolite.sgdev.org for dev

client/web/src/settings/DynamicallyImportedMonacoSettingsEditor.tsx
Forgot this one.
- N/A
- [Web](https://sg-web-mrn-remove-debug.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-juopflzmbv.chromatic.com)
=> Remove debug print statement

internal/database/migration/stitch/rewriter.go
Partial fix to #39863. This rewriter function incorrectly chose the parent of a renamed migration (an explicitly handled edge case) to be the wrong number on a number of patch versions (not tested by the stitch utility directly). This fixes the misnaming of that parent in this condition.
Existing unit tests (caught a bug on my first try of this!). Tested explicit patch version by hand.
=> migration: Fix identifier gap in rewriter

doc/admin/search.md
Adding to the docs the new functionality to check files skipped during indexing.
none, docs only update
=> adding changes to index status page

client/web/src/site-admin/analytics/AnalyticsBatchChangesPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsBatchChangesPage/queries.ts, client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/queries.ts, client/web/src/site-admin/analytics/AnalyticsNotebooksPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsNotebooksPage/queries.ts, client/web/src/site-admin/analytics/AnalyticsSearchPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsSearchPage/queries.ts, client/web/src/site-admin/analytics/AnalyticsUsersPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsUsersPage/queries.ts, client/web/src/site-admin/analytics/components/TimeSavedCalculatorGroup.tsx, client/web/src/site-admin/analytics/components/ValueLegendList.tsx, client/web/src/site-admin/analytics/components/index.module.scss, client/web/src/site-admin/analytics/useChartFilters.ts, cmd/frontend/graphqlbackend/schema.graphql, cmd/frontend/graphqlbackend/site_analytics.go, internal/adminanalytics/batchchanges.go, internal/adminanalytics/codeintel.go, internal/adminanalytics/fetcher.go, internal/adminanalytics/notebooks.go, internal/adminanalytics/search.go, internal/adminanalytics/users.go, internal/adminanalytics/utils.go
Closes https://github.com/sourcegraph/sourcegraph/issues/39310
Closes https://github.com/sourcegraph/sourcegraph/issues/39320
- Add 1 year hours saved projection 
- Add chart grouping dropdown, daily/weekly
- Update font colors
- visit admin analytics
=> [Admin Analytics] UI Improvements

dev/sg/internal/migration/squash.go
=> chore: Remove weird spacing

internal/database/migration/stitch/rewriter.go
🤦 
Tested expected output locally (was wrong, is now right)
=> chore: Iterate correctly

doc/code_intelligence/how-to/index.md
Previewed the markdown in GitHub
=> add link to python docs

enterprise/cmd/executor/internal/metrics/metrics.go
Simply combining them apparently doesn't yield valid metrics data. Oops.
Run in k8s to validate change.
=> Fix gathering metrics from multiple sources

internal/search/types.go
=> search: fix feature name typo

CHANGELOG.md, doc/code_insights/language_insight_quickstart.md
change log entry for streaming compute api fix
=> change log entry for streaming compute api fix

dev/sg/internal/background/background.go, dev/sg/main.go
=> dev/sg: better indicator when waiting for background jobs

client/web/src/search/home/QueryExamplesHomepage.module.scss, client/web/src/search/home/QueryExamplesHomepage.tsx
Review styles and interaction behavior visually.
- [Web](https://sg-web-qk-query-examples-refinements.onrender.com)
=> Refine styles for query chips

doc/dev/background-information/ci/development.md
Improved ["managing secrets" docs](https://docs.sourcegraph.com/dev/background-information/ci/development#managing-secrets).
[Slack thread context](https://sourcegraph.slack.com/archives/C01N83PS4TU/p1659348003203009?thread_ts=1659338762.182809&cid=C01N83PS4TU).
n/a
=> docs: improve managing secrets docs

dev/ci/asdf-install.sh
Follow-up to https://github.com/sourcegraph/cache-buildkite-plugin/pull/1/files as we have a copy and paste stuff here. 
manually tested
=> ci: silence aws s3 (asdf cache)

cmd/frontend/oneclickexport/export_test.go
=> oneclickexport: update cumulative test with DB query

cmd/frontend/oneclickexport/export_test.go
Fixing the build in main
existing tests
=> fix compilation error

schema/site.schema.json
another fix to heal the main
schema change, just CI
=> fix site.schema.json linter error

client/web/src/integration/search.test.ts
it failed during main CI run, example: https://buildkite.com/sourcegraph/sourcegraph/builds/165640#01826ece-27b0-4e6f-ae55-61e8ff92943b
CI, no functional changes made
- [Web](https://sg-web-ao-disable-flaky-ui-test.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-fmgvgnoxxb.chromatic.com)
=> disable flaky test

CHANGELOG.md, doc/code_insights/how-tos/creating_a_custom_dashboard_of_code_insights.md
move changelog entries for 3.42.2 patch release
doc change only
=> move changelog entries to 3.42.2

CHANGELOG.md, doc/code_insights/index.md
=> correct change log entry

cmd/server/Dockerfile
Forgot to update this since doing the same for the image we ship
CI checks
=> Update sg server minio

CHANGELOG.md
Add entry to changelog.
CI tests
=> Add password policy to changelog

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/index.md
This pull request is part of the Sourcegraph 3.42.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/40031)
cc @leonore
=> release: sourcegraph@3.42.2

dev/release/release-config.jsonc
changing release config post-3.42.2 patch
just a config change
=> release: 3.43 config

cmd/frontend/internal/app/app.go, cmd/frontend/internal/app/ping.go, cmd/frontend/internal/app/sign_out.go, cmd/frontend/internal/app/usage_stats.go, cmd/frontend/internal/app/verify_email.go, cmd/frontend/internal/auth/userpasswd/handlers.go, cmd/frontend/internal/auth/userpasswd/reset_password.go
Just a small improvement, inspired by @ryanslade [comment](https://github.com/sourcegraph/sourcegraph/pull/40078#discussion_r940170857)
No functional change, CI.
=> use http.HandlerFunc type where possible in frontend/internal/app

cmd/frontend/internal/app/app.go, cmd/frontend/internal/app/ping.go, cmd/frontend/internal/app/sign_out.go, cmd/frontend/internal/app/usage_stats.go, cmd/frontend/internal/app/verify_email.go, cmd/frontend/internal/auth/userpasswd/handlers.go, cmd/frontend/internal/auth/userpasswd/reset_password.go
=> [main-dry-run] use http.HandlerFunc type where possible in frontend/internal/app

enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go, enterprise/cmd/worker/internal/codeintel/indexing/dependency_sync_scheduler.go, internal/database/external_services.go
This reverts commit f21b0f678e39f3a72922dd17e986aa28032ee99a.
Is a revert.
=> Revert "database: Add ExcludeConfigField to extsvc.List (#40137)"

enterprise/cmd/executor/vm-image/ignite-ubuntu/Dockerfile
Somehow lost it in refactors :lolsob:
Verified git is there.
=> executors: Add git to ignite VM

doc/admin/user_data_deletion.md
This is to address some common concerns from admins attempting to clear seats on their Sourcegraph instances
Please see this [thread](https://sourcegraph.slack.com/archives/C01HW836940/p1659723245669479) for more context
Doc update -- this is tested and reviewed by relevant team
=> Doc Update: user deletion

dev/sg/sg_migration.go, doc/dev/background-information/sg/reference.md
=> chore: Fix typo

client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPolicyPage.tsx, client/web/src/enterprise/codeintel/configuration/pages/CodeIntelRepositoryIndexConfigurationPage.tsx
Renaming precise code intel to code graph data
No test needed, it's just a rename.
- [Web](https://sg-web-cesar-renaming-code-intel-2.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-gqxidebwbq.chromatic.com)
=> Renaming code intel titles

client/web/src/enterprise/codeintel/uploads/pages/CodeIntelUploadsPage.tsx
Remove container around alert message ref https://github.com/sourcegraph/sourcegraph/issues/36505
No test, its just visual.
- [Web](https://sg-web-cesar-36505-remove-alert-container.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-otgpyxyznl.chromatic.com)
=> Removing container around alert message

internal/database/external_services.go, internal/database/external_services_test.go, internal/oobmigration/migrations/extsvc_webhook_migrator_test.go
Closes #40219.
If everything still builds, we're good.
=> database: remove options no longer needed after #40113

doc/dev/background-information/ci/reference.md, enterprise/dev/ci/gen-pipeline.go
Removing this as it currently breaks any pipeline with no changes. 
CC @eseliger 
Generate a pipeline with no changes
=> remove pipeline version

doc/dev/background-information/ci/reference.md, enterprise/dev/ci/gen-pipeline.go
Reverts sourcegraph/sourcegraph#40229
this didn't work, back to the drawing board. 
CI Passing
=> Revert "remove pipeline version"

client/web/src/repo/blob/codemirror/sourcegraph-extensions.ts
Before: 
After: 
Enable CodeMirror file view. Go to a file, scroll to the bottom and verify that there is extra space for the status bar.
- [Web](https://sg-web-fkling-cm-bottom-spacer.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ctmbukawjy.chromatic.com)
=> codemirror file view: Add bottom spacer to prevent status bar from covering content

doc/admin/observability/alerts.md, doc/admin/observability/dashboards.md, enterprise/cmd/worker/internal/telemetry/telemetry_job.go, monitoring/definitions/shared/shared.go, monitoring/definitions/shared/usage_data_pipeline.go, monitoring/definitions/telemetry.go, monitoring/main.go, monitoring/monitoring/monitoring.go
Adds dashboard and (warning level) alerts for the usage data pipeline.
=> monitoring and alerts for usage data pipeline

enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
Add more debug logging to help when investigating customer issues.
None needed, only logs added
=> authz: Add more debug logging

internal/database/external_services.go, internal/database/external_services_test.go
A DB constraint was already added. (Thanks @miveronese!)
Closes https://github.com/sourcegraph/sourcegraph/issues/19878
Tests updated
=> database: Remove manual check for duplicate services

internal/database/external_services.go, internal/encryption/encryptable.go, internal/encryption/json_encryptable.go
=> chore: Remove dead code

enterprise/cmd/executor/docker-mirror/docker-mirror.json, enterprise/cmd/executor/vm-image/executor.json
=> executors: Don't pass SA file into build VM

client/web/src/enterprise/codeintel/repo/RepositoryCodeIntelArea.tsx, client/web/src/enterprise/codeintel/uploads/pages/CodeIntelUploadsPage.tsx, client/web/src/repo/tree/TabNavigation.tsx, client/web/src/repo/tree/TreeNavigation.tsx
Rename "Code graph" section to "Code graph data"
No test needed its just text.
- [Web](https://sg-web-cesar-40365-rename-code-graph.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-cegarwcvvx.chromatic.com)
=> rename code graph to code graph data

enterprise/internal/codeintel/CODENOTIFY
=> chore: Remove codenotify in empty directory

dev/build-tracker/build.go, dev/build-tracker/slack.go
Log some extra information about the author
Ran tests locally
=> better logging for teammate information

client/web/src/search/home/QueryExamplesHomepage.tsx, client/web/src/search/home/useQueryExamples.tsx
Fixes #40298
https://user-images.githubusercontent.com/6417322/184806778-37fa65c6-4eb3-44ac-a0ff-eb0454fc1698.mov
* Observe the new query examples on the homepage
- [Web](https://sg-web-rn-query-examples-update.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-gabdipvncp.chromatic.com)
=> homepage: query examples update

client/shared/src/settings/CoreWorkflowImprovementsEnabledProvider.tsx, client/shared/src/settings/useCoreWorkflowImprovementsEnabled.ts, client/web/src/SourcegraphWebApp.tsx
Fixes #39740
https://user-images.githubusercontent.com/6417322/184857371-ae7eaf61-297c-4349-be28-f057ebd5d351.mov
https://user-images.githubusercontent.com/6417322/184857410-9ab8e925-c4c2-4214-81f0-9585cfcd97a0.mov
* Enable Simple UI
* Do a search
* No old UI flash should happen
* Go to the file page
* Again, no old UI should flash
- [Web](https://sg-web-rn-fix-core-workflow-enabled.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-shlsgchimq.chromatic.com)
=> Fix Simple UI loading flashes

enterprise/cmd/executor/docker-mirror/docker-mirror.json, enterprise/cmd/executor/vm-image/executor.json
=> executors: Add eu-west-2 to AMI regions

enterprise/dev/ci/internal/ci/pipeline.go
Replace this with @burmudar's build tracker notifications!
n/a
=> dev/ci: remove custom notify step

doc/dev/background-information/ci/reference.md, enterprise/dev/ci/internal/ci/operations.go, enterprise/dev/ci/internal/ci/operations/operations.go
=> dev/ci: never merge empty sets

enterprise/cmd/frontend/internal/batches/init.go, enterprise/cmd/frontend/internal/batches/resolvers/batch_change_connection_test.go, enterprise/cmd/frontend/internal/batches/resolvers/batch_change_test.go, enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_test.go, enterprise/cmd/frontend/internal/batches/resolvers/bulk_operation_connection_test.go, enterprise/cmd/frontend/internal/batches/resolvers/bulk_operation_test.go, enterprise/cmd/frontend/internal/batches/resolvers/changeset_apply_preview_connection_test.go, enterprise/cmd/frontend/internal/batches/resolvers/changeset_apply_preview_test.go, enterprise/cmd/frontend/internal/batches/resolvers/changeset_connection_test.go, enterprise/cmd/frontend/internal/batches/resolvers/changeset_counts_test.go, enterprise/cmd/frontend/internal/batches/resolvers/changeset_event_connection_test.go, enterprise/cmd/frontend/internal/batches/resolvers/changeset_spec_connection_test.go, enterprise/cmd/frontend/internal/batches/resolvers/changeset_spec_test.go, enterprise/cmd/frontend/internal/batches/resolvers/changeset_test.go, enterprise/cmd/frontend/internal/batches/resolvers/code_host_connection_test.go, enterprise/cmd/frontend/internal/batches/resolvers/main_test.go, enterprise/cmd/frontend/internal/batches/resolvers/permissions_test.go, enterprise/cmd/frontend/internal/batches/resolvers/resolver_test.go, enterprise/cmd/worker/internal/batches/workers/reconciler_worker_test.go, enterprise/internal/batches/reconciler/executor_test.go, enterprise/internal/oobmigration/migrations/batches/ssh_migrator_test.go
Verified tests are still passing and everything works fine.
=> batches: rename aliases from campaign to batch changes

dev/release/release-config.jsonc
Fix semver in release config
N/A
=> fix semver

CHANGELOG.md
=> changelog: cut sourcegraph@3.43.0

enterprise/internal/oobmigration/migrations/batches/ssh_migrator.go, enterprise/internal/oobmigration/migrations/batches/ssh_migrator_test.go, enterprise/internal/oobmigration/migrations/iam/license_key_field_migrator.go, enterprise/internal/oobmigration/migrations/iam/license_key_field_migrator_test.go, enterprise/internal/oobmigration/migrations/iam/subscription_account_number_migrator.go, enterprise/internal/oobmigration/migrations/iam/subscription_account_number_migrator_test.go, enterprise/internal/oobmigration/migrations/register.go
Small refactor. Pulled from refactor work in #40395.
N/A.
=> oobmigration: Unify construction

internal/oobmigration/migrations/batches/extsvc_webhook_migrator.go, internal/oobmigration/migrations/batches/extsvc_webhook_migrator_test.go, internal/oobmigration/migrations/register.go
I liked the first one so much I did it again.
N/A.
=> oobmigration: Unify construction part 2

doc/code_insights/explanations/automatically_generated_data_series.md
Copy and run the query in Sourcegraph
=> Fixed pom.xml query

dev/build-tracker/README.md
This broke `main`. Fixed with `prettier`.
- CI
=> Fix formatting in build-tracker/README.md

enterprise/internal/oobmigration/migrations/batches/ssh_migrator.go, enterprise/internal/oobmigration/migrations/batches/ssh_migrator_test.go, enterprise/internal/oobmigration/migrations/codeintel/diagnostics_count_test.go, enterprise/internal/oobmigration/migrations/codeintel/document_column_split_test.go, enterprise/internal/oobmigration/migrations/codeintel/locations_count_test.go, enterprise/internal/oobmigration/migrations/codeintel/migrator_test.go, enterprise/internal/oobmigration/migrations/iam/license_key_field_migrator.go, enterprise/internal/oobmigration/migrations/iam/license_key_field_migrator_test.go, enterprise/internal/oobmigration/migrations/iam/subscription_account_number_migrator.go, enterprise/internal/oobmigration/migrations/iam/subscription_account_number_migrator_test.go, enterprise/internal/oobmigration/migrations/register.go, internal/oobmigration/migrations/batches/extsvc_webhook_migrator.go, internal/oobmigration/migrations/batches/extsvc_webhook_migrator_test.go, internal/oobmigration/migrations/register.go
Ensure test files are also isolated from changing code.
Updated unit tests.
=> oobmigration: Isolate tests

client/web/src/site-admin/analytics/AnalyticsExtensionsPage/index.tsx, cmd/frontend/graphqlbackend/schema.graphql
Follow up https://github.com/sourcegraph/sourcegraph/pull/40407#discussion_r947875792
- Check diff
=> admin-analytics: extensions page follow-up copy fix

doc/code_intelligence/explanations/auto_indexing.md, doc/code_intelligence/explanations/auto_indexing_inference.md, doc/code_intelligence/explanations/features.md, doc/code_intelligence/explanations/precise_code_intelligence.md, doc/code_intelligence/explanations/rockskip.md, doc/code_intelligence/how-to/configure_auto_indexing.md, doc/code_intelligence/how-to/enable_auto_indexing.md, doc/code_intelligence/index.md, doc/code_intelligence/references/auto_indexing_configuration.md
=> Tweak auto-indexing docs

cmd/worker/internal/migrations/init.go, cmd/worker/shared/main.go, enterprise/internal/oobmigration/migrations/register.go, internal/oobmigration/migrations/register.go, internal/oobmigration/registration.go
Added a type, get over it.
N/A.
=> oobmigration: Add function to clean up registration code

internal/oobmigration/runner.go
Do not log/block when the parent context is canceled.
N/A.
=> oobmigrations: Reduce runner log noise on context cancellation

doc/code_intelligence/references/indexers.md
=> Add Ruby Beta support

internal/oobmigration/runner.go, internal/oobmigration/runner_test.go, internal/oobmigration/validate.go
Update oobmigration logging practices
Updated unit tests.
=> oobmigration: Replace log15 with sg/log

enterprise/internal/authz/perforce/perforce.go
Before we were locking well before actually making any changes to the
map which would hold the lock for too long.
Also added some comments around why we lock in a couple of other places
as it wasn't obvious.
Existing tests pass
=> authz: Move locking of emailsCacheMutex

client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/components/Table.tsx, client/wildcard/src/components/Popover/components/PopoverTrigger.tsx, client/wildcard/src/components/Popover/components/popover-content/PopoverContent.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/40617.
- `sg start`
- Open http://localhost:3080/site-admin/users
- Choose user(s) and make any actions either using bulk actions dropdown or actions dropdown on user row
- Check that after clicking action dropdown closes
- [Web](https://sg-web-erzhtor-fix-user-management.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-qpjsvtkfvl.chromatic.com)
=> user-management: fix actions dropdown to dismiss on action click

lib/errors/warning_test.go
This PR: "I am the test plan".
=> lib/errors: Assert warning against nil error in tests

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/dev/background-information/ci/reference.md, doc/index.md, enterprise/dev/ci/internal/ci/pipeline.go
This pull request is part of the Sourcegraph 3.43.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/39333)
=> release: sourcegraph@3.43.0

internal/repos/clone_url_test.go, internal/repos/testdata/bitbucketserver-repos-username.golden, internal/repos/util.go, internal/repos/util_test.go
Based on original suggestion from @unknwon #40241
fixes: https://github.com/sourcegraph/customer/issues/1161
Tested with unit tests.
Tested locally against the bitbucket server instance https://bitbucket.sgdev.org/ and it worked with the default configuration there.
Tested locally against a bitbucket server instance with the same config as customer. Mentioned in this comment: https://github.com/sourcegraph/customer/issues/1161#issuecomment-1216217367
=> [iam] Fix incorrect username used on bitbucket

enterprise/internal/insights/aggregation/aggregation.go, enterprise/internal/insights/aggregation/aggregation_test.go
I updated the signature for the aggregation count functions and tried to make some test cases for you to work with
=> fix signature and make tests

enterprise/internal/insights/aggregation/aggregation.go, enterprise/internal/insights/aggregation/aggregation_test.go
This doesn't work in all the cases but I think it's close, aside from all query pattern parsing and case sensitivity stuff.
=> sample match

internal/oobmigration/oobmigrations.yaml
=> oobmigrations: Deprecate IAM migrations

internal/oobmigration/oobmigrations.yaml
=> oobmigrations: Deprecate batches migrations

internal/database/migration/cliutil/upgrade_runner.go, internal/version/upgradestore/store.go, internal/version/upgradestore/store_test.go
=> upgrade: Set new instance version on success

internal/metrics/metrics.go
Currently everytime we collect prometheus metrics we call statfs twice, once to calculate the available space and another to calculate the total space. However, we can reuse the statfs call. The pattern implemented here is the same used by the offical prometheus client to interact with go's stdlib metrics.
The motivation of this PR is not that statfs is a bottleneck, but rather to explore this pattern for a more complicated metric which will export many values from a single syscall.
Test Plan: the unit tests explicitly exercise metric collection for disk space.
=> metrics: call Statfs once per collection of disk metric

doc/dev/how-to/add_logging.md
=> doc/dev/how-to/add_logging.md: Fix typo in example

internal/database/migration/cliutil/upgrade_runner.go
=> migrator: Ensure we do not set version on upgrade dry run

internal/database/migration/shared/upgradedata/cmd/generator/consts.go, internal/database/migration/shared/upgradedata/stitched-migration-graph.json, internal/database/migration/stitch/stitch.go
Bump the max version so that we can gather the associated migration bounds for the recently released 3.43.
Existing CI pipelines should check go generate diff, if it exists.
=> oobmigration: Update MaxVersion

docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__.__markdown.md.snap
This started failing after the syntect change.
Re-ran tests.
=> syntax-highlighter: Update snapshot for Markdown test.

enterprise/internal/authz/perforce/cmd/scanprotects/README.md
Fixing [the failed build](https://buildkite.com/sourcegraph/sourcegraph/builds/169126#0182d468-d868-45d3-bd50-a48025885088) on `main`.
CI is green
=> web: prettier 🙏

docker-images/syntax-highlighter/crates/sg-syntax/src/sg_sciptect.rs, docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__.__scala.scala.snap, docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/syntect_files/scala.scala
See the updated snapshot tests.
=> CodeMirror blob: Tweak syntax highlighting for Scala

doc/code_navigation/references/indexers.md
=> Correct Ruby cell coloring

dev/build-tracker/build.go, dev/build-tracker/slack.go
* Add more logging to better diagnose failures
* Tiny refactor in failed job section creation for slack
Unit tests
=> build-tracker: add more logging wrt jobs

enterprise/cmd/repo-updater/internal/authz/perms_syncer_test.go
https://github.com/sourcegraph/sourcegraph/issues/40917
Test Plan: CI
=> authz: skip flaky PermsSyncer_syncPerms/max_concurrency

internal/users/stats.go
=> user-management: remove backend debug logs

internal/search/lucky/generator.go, internal/search/lucky/rules.go, internal/search/lucky/rules_test.go
Prep for factoring out some common code
Semantics-preserving, just a type change
=> search: rename lucky search transform type

internal/database/migration/cliutil/upgrade.go
Small usage update to be more correct.
N/A.
=> migrator: Small usage string update

cmd/frontend/internal/app/updatecheck/client.go, cmd/frontend/internal/app/updatecheck/handler.go, cmd/frontend/internal/cli/serve_cmd.go, cmd/frontend/internal/httpapi/httpapi.go
Migrate usage of  log15 to use sourcegraph/log
Unit tests
=> log15 migration: migrate updatecheck to use sourcegraph/log

dev/release/release-config.jsonc
=> release: update config for 3.43.1

CHANGELOG.md
=> release: cut CHANGELOG entries for 3.43.1

cmd/gitserver/server/gitservice.go
Loggers should not be initialized before package initialization, this change threads a logger through to log env configuration errors. It also updates some existing logging so that they are assigned to the correct scopes.
`sg start`
=> gitserver: propagate logger for egress variable parsing

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/index.md
This pull request is part of the Sourcegraph 3.43.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/40986)
cc @unknwon
=> release: sourcegraph@3.43.1

cmd/gitserver/server/gitservice.go
`env.Get` should not be called post-initialization, so we load it first and do the parsing later. This regression was introduced in https://github.com/sourcegraph/sourcegraph/pull/40966
`sg start` (though that didn't catch the issue before 😬 )
=> gitserver: fix gitServiceMaxEgressBytesPerSecond env loading

internal/codeintel/autoindexing/observability.go
@Numbers88s 
On cloud, The brain was panicing (if you know, you know). Now, brain no panic
=> fix: add op for last index scan

internal/search/job/jobutil/job.go, internal/search/job/jobutil/job_test.go, internal/search/structural/structural.go
=> search: remove unused structural search logic

internal/oobmigration/downgrade.go, internal/oobmigration/downgrade_test.go, internal/oobmigration/interrupts.go, internal/oobmigration/upgrade.go, internal/oobmigration/upgrade_test.go
Add logic to plan downgrades in the oobmigration package.
New unit tests.
=> oobmigration: Add downgrade scheduler logic

doc/admin/deploy/index.md, enterprise/internal/codeintel/CODENOTIFY
Doc Change - no testing needed.
=> Simplify Deployment page

cmd/repo-updater/CODENOTIFY, internal/cmd/progress-bot/CODENOTIFY, internal/httpcli/CODENOTIFY, internal/repos/CODENOTIFY
=> all: remove tsenart from CODENOTIFY

internal/httpcli/client_test.go
Adds a retroactive unit test for the failure fixed in https://github.com/sourcegraph/sourcegraph/pull/41059
unit tests pass
=> internal/httpcli: add unit test for logging middleware error scenario

doc/admin/how-to/troubleshoot-sg-extension.md
=> add resolution for access token error

internal/database/migration/cliutil/upgrade.go
Making this more uniform for upcoming `downgrade` command.
N/A.
=> upgrade: Make comment structure consistent

enterprise/internal/oobmigration/migrations/codeintel/document_column_split.go
=> oobmigrations: Fix copy-pasted docstring

internal/oobmigration/upgrade.go
Update comment to reflect reality.
N/A.
=> oobmigration: Update comment

cmd/migrator/shared/main.go, internal/database/migration/cliutil/downgrade.go, internal/oobmigration/downgrade.go
Implements `migrator downgrade`.
=> upgrades: But reverse!

cmd/frontend/graphqlbackend/schema.graphql, cmd/frontend/graphqlbackend/search_query_annotation.go, cmd/frontend/graphqlbackend/search_query_description.go
As in title, follow up of https://github.com/sourcegraph/sourcegraph/pull/41083
=> search: add annotations for proposed queries in GQL

client/jetbrains/CHANGELOG.md
This somehow made it to main.
docs change
=> Fix lint issue

enterprise/internal/licensing/features_test.go
Fixes broken test in main
Test updated
=> Rename business0 to PlanBusiness0

cmd/server/Dockerfile, docker-images/minio/build.sh
=> New minio version

cmd/frontend/graphqlbackend/insights_aggregations.graphql
linting change
`sg lint -fix client`
=> insights: prettier graphql

client/web/src/enterprise/batches/batch-spec/yaml-util.test.ts
Just removing useless log msg.
- [Web](https://sg-web-es-no-log.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-abfsbdymea.chromatic.com)
=> batches: Remove console log from test

client/web/src/nav/StatusMessagesNavItem.tsx
I asked in #analaytics whether I can remove it and they said yes. I also
suspect that the idea of "UserNotifications" doesn't exist anymore.
This again simplifies the code.
- existing tests
- [Web](https://sg-web-mrn-remove-user-notifications.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-frpuslmgkz.chromatic.com)
=> status messages: remove cloud-v1 user notification tracking

enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/util.go
The ConfigurationPolicy can be nil, but this logic didn't account for it, causing a panic.
Verified it no longer panics.
=> codeintel: Handle ConfigurationPolicy nil case

.github/teams.yml, .github/workflows/label-notify.yml
Minor changes, noticed from a few new issues
N/A - Automation tools only
=> Update FPT issue/PR automation

dev/sg/live.go, dev/sg/sg_live.go, doc/dev/background-information/sg/reference.md
=> dev/sg: only list commits if deployment is found in sg live

dev/sg/sg_live.go
merge conflict in main
build passes
=> dev/sg: remove unused import

.github/workflows/label-notify.yml
Not finding these as helpful as I had hoped.
N/A
=> Remove Justin from label notifications

dev/release/src/update.ts
Spotted in https://github.com/sourcegraph/sourcegraph/pull/41067
n/a
- [Web](https://sg-web-release-no-punc.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-qhjcptpwht.chromatic.com)
=> dev/release: remove random punctuation

doc/code_insights/explanations/search_results_aggregations.md, doc/code_insights/index.md
part of #40805
Manually reviewing the docs preview.
=> insights: add 4.0 docs scaffolding

doc/dev/background-information/sg/reference.md, internal/database/migration/cliutil/downgrade.go, internal/database/migration/cliutil/downto.go, internal/database/migration/cliutil/multiversion.go, internal/database/migration/cliutil/undo.go, internal/database/migration/cliutil/up.go, internal/database/migration/cliutil/upgrade.go, internal/database/migration/cliutil/upto.go
To match the documentation in #41067.
=> cliutil: Standardize privileged operation flags

doc/admin/how-to/manual_database_migrations.md
Confirm everything is working fine.
=> Update migrator doc

doc/dev/background-information/adding_ping_data.md
=> Adding info on how to add critical telemetry

go.mod, go.sum
Pulling in the changes from https://github.com/sourcegraph/zoekt/pull/418
Updated with `./dev/zoekt/update`
- https://github.com/sourcegraph/zoekt/commit/d749d80b21 webserver: do not wait until all shards loaded to be available
- https://github.com/sourcegraph/zoekt/commit/2478bf5713 go mod tidy
- https://github.com/sourcegraph/zoekt/commit/e97813e3ea deps: upgrade github.com/sourcegraph/log
- https://github.com/sourcegraph/zoekt/commit/d1964a317f Improve performance of List
Unit tests.
=> gomod: update zoekt for improved List performance

internal/authz/sub_repo_perms_test.go
A customer using sub-repo permissions reported an issue with LsFiles timing out. After some investigation I have ruled out git as the root cause, and as such the other major component is the call to FilterActorPaths.
This commit adds a benchmark for FilterActorPaths, but with a few include and exclude patterns and lots of files. This is to try and capture the code that will typically be involved. The intention is to investigate profiles and improve the benchmark results.
Here are the results on my desktop machine:
```
$ go test -bench=Filter -run=^$ -benchmem
goos: linux
goarch: amd64
pkg: github.com/sourcegraph/sourcegraph/internal/authz
cpu: AMD Ryzen 9 5950X 16-Core Processor
BenchmarkFilterActorPaths-32              27	  44682386 ns/op        111901 paths/s	 4233714 B/op	   72608 …
```
=> authz: introduce benchmark for FilterActorPaths

cmd/gitserver/server/server.go, enterprise/internal/insights/store/dashboard_store_test.go, enterprise/internal/insights/store/testdata/TestGetDashboard/test_user_4_in_org_1_can_see_both_dashboards_with_view.golden, enterprise/internal/insights/store/testdata/TestGetDashboard/test_user_4_in_org_1_can_see_both_global_and_org_private_dashboard.golden, internal/codeintel/stores/dbstore/configuration_policies_test.go, internal/trace/trace.go
Test plan:
Existing tests should successfully run.
=> gitserver: remove deprecated tracing functions usage.

doc/dev/how-to/add_logging.md
=> doc/dev: add warnings for common mistakes, update link to trace.Logger

CHANGELOG.md
=> changelog: Add note about multi-version upgrade

internal/authz/sub_repo_perms.go
I missed this in my previous commit, but we should also cache this metric. This provides another additional huge speedup of 58% on paths/s. Additionally I added a comment explaining why we cache WithLabelValues as well as providing a more useful help string for the metric.
```
name                 old time/op  new time/op  delta
FilterActorPaths-32  2.83ms ± 6%  1.78ms ± 3%  -36.97%  (p=0.000 n=10+9)
name                 old paths/s  new paths/s  delta
FilterActorPaths-32   1.77M ± 6%   2.80M ± 3%  +58.49%  (p=0.000 n=10+9)
```
=> authz: cache duration metric for subrepo perms

enterprise/internal/authz/perforce/cmd/scanprotects/README.md
None required, doc only change
=> scanprotects: Mention use of jq

doc/code_navigation/explanations/features.md
=> Update ref panel visual

internal/authz/sub_repo_perms.go
This bit of logic seems to always gate if we do checks for an actor, mainly via most functions calling ActorPermissions. It is currently copy pasted in two functions, but I intend on needing these checks in more places by avoiding always going via ActorPermissions.
=> authz: factor out actorSubRepoEnabled

client/web/src/enterprise/extensions/registry/RegistryNewExtensionPage.tsx
Fix broken link that breaks builds
If CI tests pass it should be fine.
- [Web](https://sg-web-dv-remove-broken-authoring-link.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-jxrepwoanz.chromatic.com)
=> Remove broken link

doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/observability/opentelemetry.md
Part of https://github.com/sourcegraph/sourcegraph/issues/39397.
=> docs: add OpenTelemetry configuration instructions for Helm

doc/code_insights/explanations/search_results_aggregations.md
=> insights: update aggregation docs for running explicit aggregations

CHANGELOG.md
feel free to suggest better wording, link is tracking issue
changelog change only
=> insights: add changelog entry for aggregations

doc/admin/observability/opentelemetry.md
=> doc/admin: add link to Kubernetes with Helm otelcol docs

client/web/src/enterprise/codeintel/repo/RepositoryCodeIntelArea.tsx, client/web/src/repo/tree/TabNavigation.tsx, client/web/src/repo/tree/TreeNavigation.tsx, doc/code_navigation/how-to/index_other_languages.md
Fixes #41410.
N/A.
- [Web](https://sg-web-ef-41410.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-jsczzqwrbg.chromatic.com)
=> codeintel: Fix "Code graph" casing

doc/code_insights/explanations/search_results_aggregations.md
=> Syntax-highlight queries in aggregation docs

doc/admin/faq.md
=> Add active user definition to admin docs

dev/release/release-config.jsonc
Patch release tracking issue: https://github.com/sourcegraph/sourcegraph/issues/41400
Patch release.
- [Web](https://sg-web-ig-patch-release-3-42-2.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ktxjjklsqk.chromatic.com)
=> dev/release: Update release-config.jsonc for 3.43.2

cmd/frontend/internal/cli/config.go
Previously we passed in the SITE_CONFIG_FILE override to watchUpdate without splitting the list. This meant that if you had multiple files, they would not be watched and required a process restart to take effect.
Additionally, we update the watchUpdate logger to always include the list of files in its logs.
=> frontend: watch multiple SITE_CONFIG_FILE overrides

client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/components/UsersList.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/41251.
- Check the diff
OR
- `sg start`
- Open http://localhost:3080/site-admin/users
- Check the "all billable events" link in the page bottom section redirects to the correct docs page
- [Web](https://sg-web-erzhtor-update-user-management.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ovthzlutpt.chromatic.com)
=> user-management: update "billable events" link URL

internal/authz/sub_repo_perms.go
This is a slight change in the behaviour of FilePermissionsFunc (and Permissions). Previously we never tried to get the rules if you passed in an empty Path. Now we do, but keep the empty path means Read behaviour. So the real change in behaviour is if the rules are invalid in a repo, previously permission check would work on empty path. Now it will also error like every path in the repo.
Note: I have not audited all the call sites of permissions code to see if this has potential to cause issue. It seems like if the rules are broken in a repo, lots of things break anyways. So this behaviour is a reasonable change.
=> authz: eagerly get compiled rules in FilePermissionsFunc

enterprise/cmd/executor/config.go, enterprise/cmd/frontend/internal/executorqueue/init.go
Resolves https://github.com/sourcegraph/sourcegraph/issues/41089
Tested Locally with `env EXECUTOR_QUEUE_NAME=prod-codeintel sg start codeintel`
=> add error validation to executors for executor_queue_name env var

CHANGELOG.md
Changelog changes for 3.43.2
Just changelog changes
=> 3.43.2 changelog

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/index.md
This pull request is part of the Sourcegraph 3.43.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/41485)
cc @indradhanush
=> release: sourcegraph@3.43.2

internal/search/job/jobutil/job_test.go, internal/search/job/jobutil/repos.go, internal/search/searcher/search.go, internal/search/zoekt/indexed_search.go
See title
Check that new trace field is present
=> search: Add regexps to job traces

.github/ISSUE_TEMPLATE/security-release-approval.md
Create security release approval issue template
Check if the issue works as expected
=> Security release approval issue template

.github/ISSUE_TEMPLATE/security-release-approval.md
Sorry stampers but it might take a couple of attempts
Create an issue
=> Fix security issue template

internal/search/backend/horizontal.go
We introduced this race yesterday in e07e7f52ce69231bd10dde68b7eb6809e00b0533 leading to a panic due to sending on a closed channel. We add a check with mutex to ensure the function is still running and will continue to run when we call FlushAll.
Additionally we now need to protect our final call to FlushAll.
Test Plan: go test. Hard to reproduce the race, so just ensuring correctness.
plz-review-url: https://plz.review/review/11438
=> search: prevent FlushAll call if zoekt horiz searches are done

doc/admin/how-to/remove-repo.md
=> doc: Describe how to trigger a manual repo purge

doc/code_navigation/explanations/auto_indexing.md, doc/code_navigation/how-to/enable_auto_indexing.md, doc/code_navigation/index.md, doc/code_navigation/references/indexers.md, doc/code_navigation/references/precise_examples.md
=> Update docs for Ruby and Rust support

cmd/frontend/registry/api/extension_connection_graphql.go, cmd/frontend/registry/api/gating.go
c.f. https://github.com/sourcegraph/sourcegraph/pull/41572#discussion_r966958018
Just a typo fix.
=> Fix typo in extension registry gating

client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/index.module.scss, client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/index.tsx
Resolves https://github.com/sourcegraph/sourcegraph/issues/41404
Ran locally
- [Web](https://sg-web-analytics-ui-tweaks.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ijtxvcyumr.chromatic.com)
=> Code intel analytics page UI tweaks

enterprise/internal/insights/resolvers/aggregates_resolvers.go
=> silence noisy log

client/web/src/search/results/sidebar/SearchFiltersSidebar.tsx
- Check that the aggregation UI is enabled by default 
- [Web](https://sg-web-vk-enable-aggregation-by-default.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-htpszcdsgi.chromatic.com)
=> Aggregation: Enable aggregation UI by default

doc/code_insights/explanations/search_results_aggregations.md
Updates docs regarding changes to proactive aggregation limits
docs only
=> insights: update docs regarding new aggregation limits

doc/admin/pricing.md
=> Bullets not rendering

.github/ISSUE_TEMPLATE/security-release-approval.md
=> Security issue template typo

internal/repos/syncer_test.go
This test has flaked on me a few times. The logs are really hard to read due to our use of parallel output and I think the implementation of logging with subtests. But it turns out the failing line is:
```
syncer_test.go:1170: expected 3 sync jobs, got 0
```
From reading the code we have very aggressive deadlines on polling. Essentially we need to have enqueued the jobs within `10ms * 10 = 100ms`. This change makes it so we wait 10s, which makes more sense on a busy CI system.
FYI to find the actual failure I searched for the line "left intact for inspection" in the CI logs.
=> repos: less aggressive polling in flakey Syncer/MultipleServices

client/branded/src/global-styles/dropdown.scss, client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/components/UsersList.tsx, client/wildcard/src/components/Combobox/Combobox.module.scss, client/wildcard/src/components/Combobox/Combobox.story.tsx, client/wildcard/src/components/Combobox/Combobox.tsx, client/wildcard/src/components/Combobox/README.md, client/wildcard/src/components/Combobox/index.ts, client/wildcard/src/hooks/useMeasure.ts
Closes https://github.com/sourcegraph/sourcegraph/issues/41631
This PR simply adds another wildcard component - Combobox UI 
Since this PR does change nothing about the product part of codebase it's safe to merge 
- Check Combobox storybook demos
- Check Combobox docs 
- Make sure that CI is green
- [Web](https://sg-web-vk-add-combobox-to-wildcard.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-xjapxsxhnq.chromatic.com)
=> Wildcard: Add combobox component

.github/ISSUE_TEMPLATE/security-release-approval.md
Minor change
It's an issue template
=> Update security issue template

cmd/searcher/internal/search/hybrid.go
This allows us to attach information to logger as we learn it, allowing
us to avoid repeating fields we want on each logger. This change was
motivated by wanting to log more and getting frustrated with
duplication.
plz-review-url: https://plz.review/review/11543
=> searcher: create a logger per hybrid try

doc/code_insights/explanations/search_results_aggregations.md
Small context tweaks + typos. 
Reviewing manually
=> small tweaks to 4.0 docs

enterprise/internal/authz/perforce/cmd/scanprotects/main.go
Also, output any errors syncing the logger
None needed, just updated some logs
=> scanprotects: Log correct environment variable

internal/database/phabricator.go, internal/database/phabricator_test.go
Closes https://github.com/sourcegraph/sourcegraph/issues/39494
This PR :)
=> Add tests for our Phabricator store

.github/workflows/push-schema.yml
**Context**: [Slack](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1663589662458399)
Can test when merged into `main`, ensure the schema is updated in [code-intel-extensions repo](https://github.com/sourcegraph/code-intel-extensions/blob/master/schema/schema.graphql).
=> update env variable for push-schema workflow

doc/code_insights/explanations/search_results_aggregations.md
adds suggestions for #41710, didn't realise auto merge was on 
checked docsite
=> docs: update to some aggregations wordings

dev/release/release-config.jsonc
As in description.
N/A
- [Web](https://sg-web-cc-release-config.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-kmetlugwyx.chromatic.com)
=> Update release config for 4.0

doc/admin/deploy/docker-compose/upgrade.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/deploy/kubernetes/update.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md
Make upgrade docs more explicit.
Docs update.
=> upgrades: Documentation improvements

dev/release/release-config.jsonc
I used the incorrect username for the github username.
N/A
- [Web](https://sg-web-cc-github-username.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-kjdnyagetn.chromatic.com)
=> Update release config with correct github username

CHANGELOG.md
=> Changelog: cut sourcegraph@4.0.0

doc/code_insights/explanations/index.md, doc/code_insights/explanations/search_results_aggregations.md, doc/code_insights/references/search_aggregations_use_cases.md
Add a number of common examples to get people started playing with search aggregations. Will keep up-to-date over time as we add more. 
=> insights 4.0: add recipes page of examples 

doc/admin/how-to/manual_database_migrations.md
No test plan required. 
Doc update
=> docs: fix minor typo

doc/dev/background-information/web/accessibility/how-to-audit.md
Add text to explain that Sourcegraph does not support mobile devices.
N/A Docs update
=> Update user journey section about mobile support

client/web/src/repo/blob/codemirror/blame-decorations.tsx
The original implementation was designed to dynamically add/remove gutters based on decoration information returned by the extension API.
The implementation was updated to make it special purpose for git blame information in #40615. Because of this there is no reason to keep the complex logic for managing dynamic gutters.
This also updates the implementation to not make assumptions about or access the editor's DOM structure directly and instead uses line and gutter decorations to highlight the hovered line.
Demo: 
https://user-images.githubusercontent.com/179026/191282349-e128e1aa-636e-4574-83d7-a6a2e93e5bae.mp4
Enable CodeMirror blob view, go to file, enable git blame view, hover over git blame information.
- [Web](https://sg-web-fkling-refactor-cm-blame-view.onrender.com)
- …
=> blob: Simplify CodeMirror blame view implementation

doc/code_insights/references/search_aggregations_use_cases.md
Updates query examples to standard search syntax for aggregations only
Visual check of markdown
=> insights: update aggregation examples to use standard search syntax

client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/components/UsersList.tsx
Simple wording change (no functionality changes). Tested locally. 
- [Web](https://sg-web-rpp-update-billing-language.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-lohpucyivp.chromatic.com)
=> Update events billing help text

internal/codeintel/autoindexing/internal/inference/lua/config.lua, internal/codeintel/autoindexing/internal/inference/lua/go.lua, internal/codeintel/autoindexing/internal/inference/lua/recognizers.lua, internal/codeintel/autoindexing/internal/inference/lua/typescript.lua, internal/codeintel/autoindexing/internal/inference/luatypes/recognizers.go, internal/codeintel/autoindexing/internal/inference/service_generator_test.go, internal/luasandbox/builtins.go, internal/luasandbox/lua/.stylua.toml, internal/luasandbox/lua/fun.lua, internal/luasandbox/util/util.go
Pulled from #36122 by @tjdevries. This PR adds additional typechecking to types created by the user in an inference sandbox. Fixes #34296. Additional efforts should convert existing go code bridges into pure lua, where possible.
Existing and new unit tests.
=> autoindexing: Add lua shims

doc/admin/deploy/docker-single-container/index.md, doc/admin/updates/docker_compose.md, doc/admin/updates/server.md
=> upgrade: Document single-server support

client/browser/CHANGELOG.md, client/browser/scripts/release-firefox.sh, client/web/src/extensions/components/ActionItemsBar.tsx, client/web/src/repo/actions/ToggleBlameAction.tsx, client/web/src/repo/blame/useBlameVisibility.tsx, client/web/src/repo/blob/BlameColumn.module.scss, client/web/src/repo/blob/BlameColumn.tsx, client/web/src/repo/blob/Blob.tsx, client/web/src/repo/blob/BlobPage.tsx, client/web/src/repo/blob/CodeMirrorBlob.tsx
Reverting PRs that blocked the main branch. 
CI should go green, this is a main dry run.
=> Revert "bext: fix firefox release script (#41655)"

internal/codeintel/stores/lsifuploadstore/config.go, internal/codeintel/stores/lsifuploadstore/store.go
=> S3: Allow configuration of UsePathStyle

internal/codeintel/autoindexing/background/scheduler/init.go
This caused a panic I saw while looking through logs.
=> chore: Fix nil logger

dev/sg/sg_monitoring.go, doc/dev/background-information/sg/reference.md, monitoring/monitoring/aggregations.go, monitoring/monitoring/internal/promql/promql.go
Lists all metrics used by each dashboard.
`go run ./dev/sg monitoring dashboards -metrics`
=> dev/sg: add 'sg monitoring dashboards -metrics'

.github/workflows/sg-binary-release.yml
`sg` imports a number of packages for which changes are important to rebuild `sg` with.
n/a
=> dev/sg: ensure rebuilds for dependency changes

internal/codeintel/autoindexing/internal/inference/lua/patterns.lua, internal/codeintel/autoindexing/internal/inference/lua/python.lua, internal/codeintel/autoindexing/internal/inference/lua/shared.lua, internal/codeintel/autoindexing/internal/inference/lua/test.lua, internal/codeintel/autoindexing/internal/inference/service_generator_test.go
Use new hotness.
Existing/modified unit tests.
=> inference: Update usages of `sg.autoindex.pattern`

doc/dev/background-information/sg/index.md
follows [slack convo](https://sourcegraph.slack.com/archives/C01N83PS4TU/p1663833882515709)
docs change only
=> docs: work with `OFFLINE`

internal/trace/httptrace.go
We generate unique labels for GraphQL routes in several places:
- `src_http_request_duration_seconds`
- `src_graphql_field_seconds`
- `src_graphql_request_duration_seconds`
It appears we do not leverage `route="graphql: ..." in any of our monitoring so it seems we can reduce the cardinality of this metric a bit by not recording the full route when handling GraphQL requests, and instead leveraging one of the existing metrics.
Highest-cardinality metrics currently: https://sourcegraph.sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22Prometheus%22,%7B%22exemplar%22:true,%22expr%22:%22topk(10,%20count%20by%20(__name__)(%7B__name__%3D~%5C%22.%2B%5C%22%7D))%22,%22requestId%22:%22Q-5320f47e-d7c6-4935-8cdf-ec62e15c351e-0A%22%7D%5D
`sg start` and `sg start …
=> httptrace: do not record full GraphQL route in src_http_request_duration_seconds

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, doc/dev/background-information/ci/reference.md, enterprise/dev/ci/internal/ci/operations.go, enterprise/dev/ci/internal/ci/pipeline.go
This pull request is part of the Sourcegraph 4.0.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.0.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/41759)
=> release: sourcegraph@4.0.0

internal/cmd/git-combine/default-branch.sh
Fixes https://sourcegraph.slack.com/archives/C023ELQLV7F/p1663681045232769
The gigarepo works by combining the commits from many upstream repos. However, if any of those repositories deletes/renames their default branch on github.com, then we'll need to our local configuration so that we're tracking the correct branch. 
git-combine solves this by running [a script](https://github.com/sourcegraph/sourcegraph/blob/git-combine-fix-null-case/internal/cmd/git-combine/default-branch.sh) on startup that discovers the name of the default branch for each of the upstreams that it's tracking. 
The script discovers the name of the default branch by parsing the output (via `sed`) of `git remote show $REMOTE`  for each remote:
https://github.com/sourcegraph/sourcegraph/blob/22666a33ee7109e39cb9a08988342 …
=> git-combine: fix error handling for print remote and default

doc/code_insights/how-tos/Troubleshooting.md
=> doc: fix typo in code-insights docs

internal/conf/validate_test.go
Two PRs landed at the same time which affected internal/conf. This created a bad merge since. This commit fixes it.
Test Plan: CI is green again. go test works locally now.
=> conf: fix build

internal/goroutine/periodic_test.go
See https://github.com/sourcegraph/sourcegraph/issues/42062
Disabled a test, n/a
=> flake: disable PeriodicGoroutineError

client/web/src/enterprise/codeintel/shared/components/CodeIntelUploadOrIndexerRepository.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/35329
Minor change from `"unknown"` -> `"Unknown repository"` for this copy. Makes it clearer to users and screen readers.
Tested journey with screen reader
- [Web](https://sg-web-tr-improve-code-intel-wording.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-blcroormrv.chromatic.com)
=> Accessibility: Better wording of unknown repo

internal/extsvc/github/v3.go, internal/repos/webhook_build_job.go
I was just looking through this code and mechanically fixed some nit stuff.
Existing CI
=> fix docs, remove unnecessary import aliases

dev/release/release-config.jsonc
N/A
- [Web](https://sg-web-cc-update-for-patch.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-hhsrcndbpo.chromatic.com)
=> Release: update config for patch release 4.0.1

internal/trace/httptrace.go
Prompted by https://sourcegraph.slack.com/archives/CHEKCRWKV/p1663949171300089?thread_ts=1663945117.373909&cid=CHEKCRWKV
n/a
=> httptrace: log whether shouldTrace was set

cmd/frontend/hubspot/hubspotutil/hubspotutil.go
This makes it easier to see where this data goes.
Comment only.
=> document link to trial submissions (self-hosted) on HubSpot

client/web/src/search/home/SelfHostInstructions.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/index.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md
This pull request is part of the Sourcegraph 4.0.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.0.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/42112)
- [Web](https://sg-web-publish-4-0-1.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-dzwyznivab.chromatic.com)
=> release: sourcegraph@4.0.1

doc/admin/analytics.md
Docs change only. Tested locally.
=> Remove experimental analytics docs badge

doc/admin/deploy/aws-ami.md
use text from AWS UI checkboxes and set auto-assign IP to "enable"
Test pass
=> doc: aws ami: use text from AWS UI checkboxes 

doc/admin/deploy/aws-ami.md
=> docs: fix typo

doc/getting-started/cloud-instance.md
Removes emojis (too noisy on the live page)
Fixes bullet point lists
na
=> Formatting fixes

internal/database/migration/cliutil/drift_schema.go
Addressing https://github.com/sourcegraph/sourcegraph/pull/41874#discussion_r979186484.
=> drift: Document regex pattern

cmd/frontend/graphqlbackend/git_tree_entry.go, cmd/frontend/graphqlbackend/graphqlbackend.go, cmd/frontend/internal/cli/serve_cmd.go, cmd/github-proxy/github-proxy.go, cmd/gitserver/main.go, cmd/gitserver/server/server.go, cmd/repo-updater/shared/main.go, cmd/searcher/main.go, cmd/symbols/shared/main.go, cmd/worker/shared/main.go, enterprise/cmd/executor/main.go, enterprise/cmd/precise-code-intel-worker/main.go, internal/repotrackutil/repouri.go, internal/repotrackutil/repouri_test.go, internal/trace/httptrace.go
Reverts sourcegraph/sourcegraph#42118
Test plan: CI passes
=> Revert "httptrace: remove unused repo and origin label"

doc/code_insights/references/license.md
Update insights license notes after new pricing was released. 
=> update with pricing page

client/web/src/search/results/SearchActionsMenu.tsx, client/web/src/search/results/createActions.ts
| Before  | After  |
| ------------- | ------------- |
| <img width="243" alt="Screenshot 2022-09-27 at 19 29 31" src="https://user-images.githubusercontent.com/18492575/192540321-083123cd-341f-4785-a3ad-701c6a34c5e3.png"> | <img width="225" alt="Screenshot 2022-09-27 at 19 32 59" src="https://user-images.githubusercontent.com/18492575/192540554-0cf04f1d-4f31-4c7c-9697-614b58536dcb.png">  |
- Make sure that the search result page context menu looks right
- [Web](https://sg-web-vk-fix-search-context-menu-copy.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-czyysbytti.chromatic.com)
=> Fix search context menu labels copy

dev/release/release-config.jsonc
N/A
- [Web](https://sg-web-cc-update-release-config.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ptcfdjroea.chromatic.com)
=> Release: update release config for 4.1.0

doc/dev/background-information/insights/backend.md
fix broken link by anchoring to commit
link change only, md preview verified
=> insights: docs: update broken link to oob migration

doc/code_insights/explanations/administration_and_security_of_code_insights.md
Add documentation for site config for insights.
Docs only - visual inspected
=> insights: document insights site config values

internal/services/executors/transport/graphql/executor_resolver.go, internal/services/executors/transport/graphql/executor_resolver_test.go
* Add more test cases
* Confirm existing functionality isn't broken
=> batches: adjust executor compatibility to work with insider versions

doc/admin/how-to/site-admin-quickstart.md, doc/admin/index.md, doc/admin/updates/docker_compose.md, doc/admin/updates/index.md, doc/admin/updates/kubernetes.md, doc/admin/updates/server.md
Misc. improvements on the flow of upgrade docs.
N/A.
=> upgrades: Make docs more focused

doc/admin/how-to/manual_database_migrations.md
Reorder commands by user relevance in this document.
N/A.
=> upgrade: Reorder migrator commands in docs

client/web/src/search/suggestion/QuerySuggestion.module.scss, client/web/src/search/suggestion/SmartSearch.story.tsx, client/web/src/search/suggestion/SmartSearch.tsx
Responsive UI for Smart Search box
https://user-images.githubusercontent.com/206864/193145225-d8bddad9-d0cf-4cf8-841e-a71291df4450.mp4
Added storybook at 480px width
- [Web](https://sg-web-jp-responsivesmartsearch.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-jooucegawn.chromatic.com)
=> search ui: smart search responsive ui

internal/database/CODENOTIFY, internal/repos/CODENOTIFY
=> chore: clean up some Codenotify for Joe

client/search-ui/src/components/CommitSearchResultMatch.tsx
Part of #42159
* No new functionality added, should be covered by tests
- [Web](https://sg-web-rn-simplify-commit-search-result.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-ieyswsrtvf.chromatic.com)
=> Simplify CommitSearchResultMatch component

doc/dev/background-information/telemetry.md
1. Removes Sourcegraph extensions mentions.
2. Updates logged events list.
3. Updates logged event arguments
Ran docsite locally and reviewed changes.
=> docs: update bext telemetry page

client/jetbrains/webview/src/bridge-mock/call-java-mock.ts, client/jetbrains/webview/src/search/App.tsx, client/jetbrains/webview/src/search/StatusBar.tsx, client/jetbrains/webview/src/search/java-to-js-bridge.ts, client/jetbrains/webview/src/search/js-to-java-bridge.ts, client/jetbrains/webview/src/sourcegraph-api-access/api-gateway.ts
I have some issues with my Prettier setting, and our common styles don't always get applied when they should.
So this is a fix for my wrong styles.
Only whitespace changes, no testing is needed besides the automated ones
- [Web](https://sg-web-dv-jetbrains-run-prettier.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-usjvmbjdft.chromatic.com)
=> JetBrains: Run `yarn format`

README.md
A new README for 4.0. It Fixes the missing logo, adds Discord, and more.
* Spell check
* Check links
=> New README for 4.0

doc/admin/deploy/docker-compose/index.md
Fixes https://github.com/sourcegraph/sourcegraph/issues/39668
I went through all links on the page, and found only one that was broken.
Only docs change
=> Docs: Fix link on Docker compose page

client/web/src/nav/GlobalNavbar.tsx, client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/components/Table.module.scss, client/web/src/site-admin/SiteAdminAllUsersPage/UserManagement/components/Table.tsx, client/web/src/site-admin/analytics/AnalyticsSearchPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsSearchPage/queries.ts, cmd/frontend/graphqlbackend/schema.graphql, internal/adminanalytics/search.go
Closes: https://github.com/sourcegraph/sourcegraph/issues/42386
Update User Management Actions dropdown style to match default except red icons and text
Added Copy/Paste events metric
Fix Analytics Link Font Weight
=> [In-Product Analytics] address UI feedback

doc/admin/observability/alerts.md
Fix build failure https://sourcegraph.slack.com/archives/C02FLQDD3TQ/p1664813708810539
This is from https://github.com/sourcegraph/sourcegraph/pull/42190, but I'm not sure why CI passed on that PR and failed when it got merged into main. 
- CI
=> monitoring: fix lint

doc/dev/background-information/web/graphql.md
This will help the next person who troubleshoots why types aren't being generated.
docs
=> docs: Clarify GraphQL type generation

client/vscode/tests/vsce.test.ts
Closes #40366
We felt that the information in #40366 is better preserved as a code comment.
This is just a code comment change
- [Web](https://sg-web-ps-cleanup-test-comments.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-gaiaombevg.chromatic.com)
=> Update comment about broken test cleanup

internal/codeintel/uploads/internal/store/store_uploads.go
#42266 forgot to coalesce a NULL value allowing it to cause a NULL to be inserted into a non-nullable column.
This an alternative to #42502, which reverts the original change.
=> codeintel: Fix NULL insert in `UpdateReferenceCounts`

doc/batch_changes/how-tos/configuring_credentials.md
=> clarify global access token summary

enterprise/internal/batches/sources/gitlab_test.go
This is supposed to be the last part of #42024, however, I didn't realize I had not pushed yet.
This doesn't affect functionality, it just makes the mocking of `GetVersions` clearer for cases where we have multiple external services.
* Tests are passing
=> batches: refactor mockGetVersions in `sources/gitlab`

client/web/src/site-admin/SiteAdminUpdatesPage.tsx
Tiny spacing changes.
Result:
View `Site admin` → `Updates` page to view changes.
- [Web](https://sg-web-qk-admin-updates-tweaks.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-dlpwkijfkp.chromatic.com)
=> Tiny tweaks to styling

cmd/gitserver/server/vcs_syncer_perforce.go, cmd/gitserver/server/vcs_syncer_perforce_test.go
Test plan:
New unit tests added.
Closes https://github.com/sourcegraph/sourcegraph/issues/42388
=> gitserver: include p4 command into logs in case of an error

internal/codeintel/policies/enterprise/README.md, internal/codeintel/uploads/internal/commitgraph/README.md
Remove outdated notes about "in-flight" refactors.
N/A
=> codeintel: Remove outdated package readmes

monitoring/monitoring/internal/promql/promql.go
The filtering we've applied on metrics is causing strange errors to be returned from Monarch (GCP monitoring): https://github.com/sourcegraph/customer/issues/1359
All the missing metrics happen to be histograms. I suspect we might need all three parts to a histogram (sum, count, buckets) for Monarch to accept the data, even if they are unused in our queries - this change makes sure all are present when one is found.
```
ts=2022-10-04T13:22:49.948Z caller=export.go:796 level=error component=gcm_exporter msg="send batch" size=2 err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric.: prometheus_target{namespace:,job:worker,instance:worker:6060,cluster …
```
=> monitoring: list all metrics in histogram sets

internal/tracer/should_trace.go, internal/tracer/switchable_otel.go, internal/tracer/watch.go, internal/tracer/watch_test.go
Sanity check for investigation of #42515 during hack hour with @jhchabran 
tests pass
=> internal/tracer: test switching tracing to sampling: none

dev/sg/sg_start.go
This steps is optional, and will continue with a warning if it fails.
https://sourcegraph.slack.com/archives/C01N83PS4TU/p1664904839499469
```
$ go run ./dev/sg start
⚠️ WARNING: failed to update dev-private:
exit status 128: error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
💡 Running 4 checks...
✅ Check "docker" success!
✅ Check "redis" success!
✅ Check "postgres" success!
✅ Check "git" success!
💡 Installing 15 commands...
```
=> dev/sg: try to update dev-private if used

doc/dev/background-information/goland.md
Add 'Colde Folding' section to the GoLand page.
Visually verified the page works.
=> Add 'Code Folding' section to the GoLand page.

schema/site.schema.json
Adding more examples for nameid-formats
No test plan required.
=> Additional SAML nameid formats

enterprise/internal/insights/pipeline/backfill.go, enterprise/internal/insights/pipeline/backfill_test.go, enterprise/internal/insights/pipeline/readme.md
Setup the initial steps for a backfill pipeline that runs over a single repo.
The test is mostly to ensure the steps are connected in the pipeline and give a sample of how to use.  I anticipate that most of the test work will be done against each individual step.
n/a currently this code is not used
Unit test added to ensure pipeline steps are connected.
=> insights: series based backfilling initial steps

sg.config.yaml
Fix bad syntax in bash install script in sg start.
Didn't work now does.
=> chore: Bash bad

cmd/frontend/graphqlbackend/commit_search_result.go, cmd/frontend/graphqlbackend/external_service.go, enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql.go, enterprise/cmd/frontend/internal/registry/extension_graphql.go
Reported by unused linter.
Test Plan: CI
=> all: remove unused loggers

cmd/frontend/internal/search/search.go
=> search: remove unused withDecoration

enterprise/internal/insights/scheduler/scheduler.go, enterprise/internal/insights/scheduler/scheduler_test.go, internal/database/schema.codeinsights.json, internal/database/schema.codeinsights.md, migrations/codeinsights/1664984848_insights_scheduler_table/down.sql, migrations/codeinsights/1664984848_insights_scheduler_table/metadata.yaml, migrations/codeinsights/1664984848_insights_scheduler_table/up.sql, migrations/codeinsights/squashed.sql
This is just a basic implementation of a new dbworker queue for the scheduler, with no custom logic or fields yet.
There is a test that verifies the routines start and stop successfully.
=> insights: skeleton queue for new scheduler

internal/codeintel/dependencies/internal/store/scan.go, internal/codeintel/policies/internal/store/scan.go, internal/codeintel/uploads/internal/store/scan.go, internal/codeintel/uploads/internal/store/store_uploads_test.go, internal/codeintel/uploads/transport/http/handler.go, internal/extsvc/gomodproxy/client.go, internal/extsvc/pypi/client.go, internal/search/alert/observer.go
All this code is reported by the unused linter.
Test Plan: CI
=> codeintel: remove unused code

internal/database/schema.json, internal/database/schema.md, migrations/frontend/1664988036_create_webhooks_table/down.sql, migrations/frontend/1664988036_create_webhooks_table/metadata.yaml, migrations/frontend/1664988036_create_webhooks_table/up.sql, migrations/frontend/squashed.sql
Closes https://github.com/sourcegraph/sourcegraph/issues/42572
- sg migrate up -> downto -> up
- CI
=> webhooks: add webhooks table

internal/database/mocks_temp.go, internal/database/webhooks.go, internal/types/types.go, mockgen.temp.yaml
Test plan:
Current CI, because nothing functional was added.
Closes https://github.com/sourcegraph/sourcegraph/issues/42621
=> webhooks: Add webhook store scaffolding

internal/database/webhook_logs.go
=> database: Remove unused context

doc/admin/deploy_executors_binary.md
=> doc: fix step numbering in the deploy executors doc

doc/batch_changes/references/requirements.md
I picked the simplest way :)
Docs change
=> podman not supported

enterprise/cmd/frontend/internal/codeintel/init.go, enterprise/cmd/frontend/internal/codeintel/services.go, enterprise/cmd/frontend/main.go
=> codeintel: Small refactor to simplify http init

README.md, client/branded/src/components/panel/views/FileLocations.tsx, client/jetbrains/webview/src/search/results/FileSearchResult.tsx, client/jetbrains/webview/src/search/results/utils.ts, client/search-ui/src/components/FileSearchResult.test.tsx, client/search/src/integration/streaming-search-mocks.ts, client/shared/src/components/ranking/LineRanking.ts, client/shared/src/components/ranking/PerFileResultRankingTestHelpers.ts, client/shared/src/testing/searchTestHelpers.ts, client/web/src/enterprise/batches/batch-spec/edit/library/LibraryPane.tsx, client/web/src/enterprise/batches/batch-spec/yaml-util.test.ts, client/web/src/enterprise/batches/batch-spec/yaml-util.ts, client/web/src/enterprise/batches/create/useSearchTemplate.ts
Related comment https://sourcegraph.slack.com/archives/C01C3NCGD40/p1665145913732369
- Check that CI is green
- [Web](https://sg-web-vk-run-yarn-format.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-akkzkvnkyg.chromatic.com)
=> Format files on the main branch

enterprise/internal/executor/client_types.go, enterprise/internal/executor/client_types_test.go
Part of #42722.
Support the different version structures.
Added Go tests.
=> batches: Add custom unmarshalling to support different versions.

internal/codeintel/policies/transport/graphql/utils.go
=> codeintel: Do not validate index values if indexing is disabled

client/web/src/enterprise/codeintel/indexes/components/CodeIntelIndexNode.tsx, client/web/src/enterprise/codeintel/indexes/hooks/useDeleteLsifIndexes.tsx, client/web/src/enterprise/codeintel/indexes/pages/CodeIntelIndexesPage.module.scss, client/web/src/enterprise/codeintel/indexes/pages/CodeIntelIndexesPage.tsx, client/web/src/enterprise/codeintel/uploads/hooks/useDeleteLsifUpload.tsx, cmd/frontend/graphqlbackend/codeintel.go, cmd/frontend/graphqlbackend/codeintel.graphql, enterprise/cmd/frontend/internal/codeintel/resolvers.go, internal/codeintel/autoindexing/internal/store/observability.go, internal/codeintel/autoindexing/internal/store/store.go, internal/codeintel/autoindexing/internal/store/store_indexes.go, internal/codeintel/autoindexing/internal/store/store_indexes_test.go, internal/codeintel/autoindexing/mocks_test.go, internal/codeintel/autoindexing/observability.go, internal/codeintel/autoindexing/service.go, internal/codeintel/autoindexing/shared/types.go, internal/codeintel/autoindexing/transport/graphql/iface.go, internal/codeintel/autoindexing/transport/graphql/mocks_temp.go, internal/codeintel/autoindexing/transport/graphql/observability.go, internal/codeintel/autoindexing/transport/graphql/root_resolver.go, internal/codeintel/autoindexing/transport/graphql/utils.go, internal/codeintel/types/types.go
Resolves https://github.com/sourcegraph/sourcegraph/issues/41196
Go tests, ran locally
=> codeintel: Support bulk deletion of LSIF indexes

doc/admin/external_service/index.md
=> Fix codehost compatibility page

enterprise/cmd/frontend/internal/codeintel/resolvers.go
=> chore: Remove outdated comments

cmd/frontend/auth/non_public_test.go, cmd/frontend/internal/app/ui/handlers_test.go, cmd/frontend/internal/app/ui/legacy_extensions_redirects_test.go, cmd/frontend/internal/app/ui/router.go, cmd/frontend/internal/app/ui/router_test.go, cmd/frontend/internal/cli/serve_cmd.go
=> chore: Remove unused param in frontend init

dev/release/release-config.jsonc
n/a
- [Web](https://sg-web-unknwon-patch-1.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-fykoydsbza.chromatic.com)
=> release: update Joe to be the 4.1 captain

client/web/src/enterprise/site-admin/sidebaritems.ts, cmd/frontend/graphqlbackend/batches.graphql, cmd/frontend/graphqlbackend/graphqlbackend.go, cmd/frontend/graphqlbackend/node.go, cmd/frontend/graphqlbackend/schema.graphql, cmd/frontend/graphqlbackend/webhooks.go, schema/site.schema.json
Minimal commit that just adds the schema and enough code so that it doesn't panic at runtime.
Closes https://github.com/sourcegraph/sourcegraph/issues/42747
None, this is just scaffolding
=> graphql: Add initial webhook schema

internal/database/mocks_temp.go, internal/database/webhooks.go, internal/database/webhooks_test.go
Test plan:
New database tests added.
Closes https://github.com/sourcegraph/sourcegraph/issues/42739
=> webhooks: implement GetByID and GetByUUID methods.

doc/batch_changes/index.md
=> Typo - ssbc is beta

dev/release/src/release.ts
N/A
- [Web](https://sg-web-cc-remove-optional-note.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-xqkhngesnt.chromatic.com)
=> Release: remove note about pure-docker steps being optional

internal/codeintel/stores/gitserver/client.go
Do not keep constructing new clients on every call.
Ran locally.
=> codeintel: Simplify gitserver layer

doc/admin/updates/pure_docker.md
=> Release: add link to upgrade commit for pure-docker deployment for 4.0.1

CHANGELOG.md
=> Add changelog entry for 4.0.1

client/web/src/user/settings/auth/UserSettingsSecurityPage.tsx, client/web/src/user/settings/backend.tsx
Title
Manual testing to confirm it still works as expected
- [Web](https://sg-web-pjlast-38195-connected-external.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-rwrhjkvyoy.chromatic.com)
=> Refactor class component to functional component and remove rxjs

doc/batch_changes/references/faq.md, doc/batch_changes/references/troubleshooting.md
Closes #41836.
Docs only, so reading.
=> doc: note that batch spec steps as different UIDs is unsupported

client/web/src/enterprise/batches/batch-spec/edit/workspaces-preview/WorkspacesPreview.tsx
Draft for now. The wording might be too jokey. cc: @malomarrec 
Addresses #42408. This will need a src-cli PR as well once we have some wording nailed down.
Tested in practice so far; will probably add a story for the new component.
- [Web](https://sg-web-aharvey-we-cant-repel-batch.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-gidsgarusm.chromatic.com)
=> batches: add warning message for large batch changes

CHANGELOG.md, client/web/src/auth/SignInPage.test.tsx
Changelog update and adjusted added test
Adjusted test
- [Web](https://sg-web-pjlast-fix-ts-build-tests.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-nddcelcimz.chromatic.com)
=> Update changelog and fix test

cmd/gitserver/server/server.go, internal/database/mocks_temp.go, internal/database/schema.json, internal/database/schema.md, internal/database/users.go, internal/database/users_test.go, internal/database/webhooks.go, internal/database/webhooks_test.go, internal/repos/github_webhook_handler.go, internal/types/types.go, migrations/frontend/1665488828_add_columns_to_webhooks_table/down.sql, migrations/frontend/1665488828_add_columns_to_webhooks_table/metadata.yaml, migrations/frontend/1665488828_add_columns_to_webhooks_table/up.sql, migrations/frontend/squashed.sql
Test plan:
Updated existing database tests.
SG migration up-down-up.
Closes https://github.com/sourcegraph/sourcegraph/issues/42798
Note to reviewers
_Updates_ of `updated_by` column will be implemented when [this code](https://github.com/sourcegraph/sourcegraph/pull/42774) is merged.
=> webhooks: add `created_by`, `updated_by` columns to `webhooks` table.

client/web/src/site-admin/analytics/AnalyticsCodeInsightsPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsCodeInsightsPage/queries.ts, client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/queries.ts, client/web/src/site-admin/analytics/AnalyticsExtensionsPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsExtensionsPage/queries.ts, client/web/src/site-admin/analytics/AnalyticsNotebooksPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsNotebooksPage/queries.ts, client/web/src/site-admin/analytics/AnalyticsOverviewPage/DevTimeSaved.tsx, client/web/src/site-admin/analytics/AnalyticsOverviewPage/queries.ts, client/web/src/site-admin/analytics/AnalyticsSearchPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsSearchPage/queries.ts, client/web/src/site-admin/analytics/AnalyticsUsersPage/AnalyticsUsersPage.module.scss, client/web/src/site-admin/analytics/AnalyticsUsersPage/AnalyticsUsersPage.story.tsx, client/web/src/site-admin/analytics/AnalyticsUsersPage/index.tsx, client/web/src/site-admin/analytics/AnalyticsUsersPage/queries.ts, client/web/src/site-admin/analytics/useChartFilters.ts, client/web/src/site-admin/analytics/utils.ts, cmd/frontend/graphqlbackend/schema.graphql, internal/adminanalytics/cache.go, internal/adminanalytics/users.go, internal/adminanalytics/users_test.go, internal/adminanalytics/utils.go
Closes: https://github.com/sourcegraph/sourcegraph/issues/42598
Added unit tests
https://www.loom.com/share/97ea71da839344b5b971bb9a442fda56
=> Fix In-Product Analytics Data Mismatch Issues

doc/admin/updates/index.md
=> grammar mistake

internal/codeintel/ranking/indexer_test.go
=> flake: Disable ranking service test

internal/database/users_test.go
Cause of several recent flakes:
- https://buildkite.com/sourcegraph/sourcegraph/builds/177459
- https://buildkite.com/sourcegraph/sourcegraph/builds/177533
- https://buildkite.com/sourcegraph/sourcegraph/builds/177469
N/A.
=> flake: Disable `Users_Delete` in `internal/database`

internal/codeintel/ranking/service.go
I missed to update the comments in an earlier PR.
just updated comments
=> ranking: fix comments

internal/codeintel/ranking/file_reference_graph.go
A small change I noticed when reviewing the PR which added buildFileReferenceGraph. We don't have to collect all paths before streaming, instead we can check if we have seen a path before and stream it out if we haven't.
I did this commit hastily, not sure if I am a fan of the name "gOut" and leaving the other group called "g".
This is a follow-up from this inline comment https://github.com/sourcegraph/sourcegraph/pull/42771#discussion_r993246945
Test Plan: CI
=> ranking: stream out as we receive an edge

schema/schema.go, schema/site.schema.json
Fix a missed site config renaming example.
Visually confirm the site config locally.
=> Fix audit log schema example

internal/codeintel/autoindexing/init.go, internal/codeintel/autoindexing/internal/background/background_jobs.go, internal/codeintel/autoindexing/internal/background/iface.go, internal/codeintel/autoindexing/internal/background/job_cleanup.go, internal/codeintel/autoindexing/internal/background/job_cleanup_test.go, internal/codeintel/autoindexing/internal/background/job_scheduler.go, internal/codeintel/autoindexing/internal/background/mocks_test.go, internal/codeintel/autoindexing/observability.go, internal/codeintel/autoindexing/service.go, mockgen.test.yaml
Remove store from background jobs
Update and run all the test.
=> [language-platform]: remove store from background jobs

enterprise/cmd/executor/internal/worker/workspace/clone.go, enterprise/cmd/executor/internal/worker/workspace_test.go
This is so that we never need to give git any credentials. It will also prevent the credential from ever landing in logs, so even if redaction fails this shall not cause any problem. It also makes sure that no further git remote operations are ever possible after the cloneRepo function returned.
Tested locally that cloning still works and isn't slower.
=> executor: Use git proxy service for cloning

dev/sg/internal/rfc/rfc.go
Helps inform relevance of RFCs, we have a lot of unused stuff lying around.
Only supports properly formatted RFCs to encourage everyone to name their RFCs correctly 🙃 
`go run ./dev/sg rfc list`
=> dev/sg: add last modified date to RFC listing

cmd/frontend/graphqlbackend/product_license_info.go, cmd/frontend/graphqlbackend/product_subscription_status.go, cmd/frontend/graphqlbackend/product_subscription_status_test.go, cmd/frontend/graphqlbackend/site_flags.go, cmd/frontend/graphqlbackend/site_flags_test.go, enterprise/cmd/frontend/internal/licensing/enforcement/users.go, enterprise/cmd/frontend/internal/licensing/init/init.go
When adding the Free Plan instead of checking for nil, I missed a few spots.
Added unit tests
=> Adjust free license user checks

shell.nix
=> nix: bump nixpkgs

cmd/gitserver/server/server.go
Use logging attributes, remove obsolete log during background repo update when `setHEAD` returns an error, because exactly the same message is logged as soon as `doBackgroundRepoUpdate` function returns.
After this change we won't have 3 Sentry events for a single `setHEAD` failure during a background repo update. Cannot make it down to 1, because log in `setHEAD` contains valuable command output and I cannot think about a way to propagate it so it won't look ugly in code or logs.
logging fixes, CI will be enough
=> gitserver: logging fixes.

internal/codeintel/codenav/transport/graphql/root_resolver.go
Add back auto indexing of rust package repo if they have not been yet indexed.
Ran all the test.
=> [language-platform] Add back auto indexing of rust package repo

internal/codeintel/policies/service.go
Adding missing service method in Policies Service
Ran all the test.
=> [language-platform]: Adding missing service method in policy service

.vscode/settings.json, CHANGELOG.md, client/jetbrains/webview/src/search/index.tsx, client/jetbrains/webview/src/search/results/FileSearchResult.tsx, client/jetbrains/webview/src/search/results/utils.ts, client/search-ui/src/components/FileSearchResult.tsx, client/vscode/src/backend/streamSearch.ts
Formatting change only
- [Web](https://sg-web-rs-yarn-format.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-pjlfavbuhq.chromatic.com)
=> chore: Run `yarn format`

client/jetbrains/CHANGELOG.md, client/jetbrains/README.md, client/jetbrains/gradle.properties
- Updated changelog with the changes since 2.0.1
- Ran the release process
- Extended the release process doc in the README
Read the updated docs to make sure it makes sense
- [Web](https://sg-web-dv-jetbrains-2-0-2.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-zlqbhxacyo.chromatic.com)
=> JetBrains 2.0.2

cmd/frontend/graphqlbackend/site.go, cmd/frontend/internal/cli/config.go, internal/database/conf.go, internal/database/conf_test.go, internal/database/mocks_temp.go, internal/database/settings.go, internal/database/settings_test.go
This reverts commit 43b8974b38545915bf7b83569dd97adc81c8f1b2.
Broken build: https://buildkite.com/sourcegraph/sourcegraph/builds/178185#0183e5b7-af5a-4f2c-b304-63ec733256be
Impossible to test, as this only fails in the CI... I want to 🔫 myself right now 😢
=> Revert "Revert "Revert "validate settings and site config in DB layer

internal/codeintel/policies/init.go, internal/codeintel/policies/internal/background/background_job.go, internal/codeintel/policies/service.go
Adding service to background job. Forgot to add it on previous PR
Ran all the test
=> [language-platform]: Adding service to background job

doc/admin/external_services/object_storage.md
Add more clarity on use of ec2 role credential environment variables.
No test plan. Doc update made.
=> doc: update on key id and role credential use

client/jetbrains/CHANGELOG.md, client/jetbrains/README.md, client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.story.tsx, client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx, client/web/src/extensions/components/ActionItemsBar.tsx, client/web/src/repo/RepoContainer.tsx
code formatting change
- [Web](https://sg-web-bo-run-format.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-pegjllcctq.chromatic.com)
=> run `yarn format`

internal/extsvc/gitlab/client.go
Followup of https://github.com/sourcegraph/sourcegraph/pull/39840#discussion_r951764015
CI
=> extsvc(gitlab): explicitly check and return errors

client/browser/CHANGELOG.md
:shipit: 
Just a changelog update.
=> Update browser extension changelog

doc/code_insights/explanations/automatically_generated_data_series.md
follow up on investigation into customer issue
docs change only
=> insights: docs: update capture group insights limitations

CHANGELOG.md
my branch from PR #42914 was having some issues so doing this separate from its PR sorry
changelog
=> batches: add fixed #42914 item to changelog

doc/code_insights/explanations/current_limitations_of_code_insights.md
=> insights: add revision limitation to docs

doc/batch_changes/references/requirements.md
ARM is technically in Beta
Feel free to merge after review
Docs
=> Beta for ARM

internal/database/migration/shared/upgradedata/cmd/generator/consts.go, internal/database/migration/shared/upgradedata/stitched-migration-graph.json
Bump the max version we support for multi-version upgrades.
N/A.
=> upgrades: Bump max supported version to support 4.1

internal/codeintel/uploads/service_worker_handler.go
Discussed this earlier with @eseliger. After we've moved the `committed_at` column from `lsif_uploads` to a new table, we expected lock contention on this particular query to go to nearly zero. We still see heavy contention and we were able to gain some intuition locally with two psql shells:
- In one session, start a txn and try to write to a table with a unique key
- In another session, try to write the same key to the table - it will block until the other session completes
In production we see this blocking behavior tank our throughput when there are multiple uploads (different roots or indexers) for the same (e.g., sg/sg, a **very** popular upload on our instance), as we basically force a serial order when processing such records.
The solution in this PR is to move the blocking query …
=> codeintel: Move `UpdateCommittedAt` outside of txn in pci-worker

internal/database/webhooks.go, internal/database/webhooks_test.go
Test plan:
Existing database tests should pass.
Closes https://github.com/sourcegraph/sourcegraph/issues/43101
=> webhooks: use dynamic query building where possible.

internal/gitserver/git_command.go
plz-review-url: https://plz.review/review/13314
=> gitserver: remove unread LocalGitCommand.command

client/web/src/communitySearchContexts/Backstage.tsx, client/web/src/communitySearchContexts/routes.tsx, cmd/frontend/internal/app/ui/router.go
1. Go to `/backstage`
2. Make sure it loads
3. Run an example query
=> Add community landing page for Backstage

cmd/frontend/backend/repos.go, doc/admin/observability/alerts.md, doc/admin/observability/dashboards.md, internal/database/repos.go, internal/repos/metrics.go, internal/repos/mocks_temp.go, internal/repos/observability.go, internal/repos/store.go, internal/repos/syncer.go, internal/repos/syncer_test.go, monitoring/definitions/repo_updater.go
Remove more code associated with user or org added code hosts.
This includes a bunch of test cases and metrics too.
All tests still pass
=> repos: Remove more code associated with user / org added code hosts

cmd/frontend/graphqlbackend/site.go, cmd/frontend/internal/cli/config.go, internal/database/conf.go, internal/database/conf_test.go, internal/database/mocks_temp.go, internal/database/settings.go, internal/database/settings_test.go
This is my yet another try to revive:
- #42039
After failing twice previously, this time I'm feeling lucky 🤞 
Tested the build with main-dry-run. The result can be seen here: https://buildkite.com/sourcegraph/sourcegraph/builds/178651
Hence why I'm confident it should pass the CI this time...
=> Revive #42039

dev/sg/sg_db.go, doc/dev/background-information/sg/reference.md, internal/database/dbtest/dbtest.go, internal/database/dbtest/dsn.go, internal/database/dbtest/dsn_test.go
Add a sg command to delete test databases created by the `dbtest` package.
Tested locally. I'm still here.
=> sg: Add `db delete-test-dbs`

.github/workflows/batches-notify.yml
Followup from https://github.com/sourcegraph/sourcegraph/pull/43207#discussion_r999980707
N/A
=> Fix parenthesis balancing

CHANGELOG.md
Forgot to link to the PR originally, fixed here.
just a changelog entry
=> Fix changelog entry to link to PR

client/web/src/enterprise/batches/batch-spec/batch-spec.mock.ts, client/web/src/enterprise/codeintel/indexes/pages/CodeIntelIndexPage.story.tsx, enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace.go, enterprise/cmd/frontend/internal/executorqueue/queues/batches/transform.go, enterprise/cmd/frontend/internal/executorqueue/queues/batches/transform_test.go, enterprise/cmd/frontend/internal/executorqueue/queues/codeintel/transform.go, enterprise/cmd/frontend/internal/executorqueue/queues/codeintel/transform_test.go, enterprise/internal/batches/store/worker_workspace_execution.go, enterprise/internal/batches/store/worker_workspace_execution_test.go, internal/codeintel/shared/resolvers/index_steps_resolver.go
Makes use of the new key property introduced in a previous PR.
Test suite and will test this on k8s.
=> executors: Use named keys for steps

README.md
=> README: Use preferred 4.0 banner in dark/light theme

doc/batch_changes/how-tos/index.md, doc/batch_changes/how-tos/server_side_file_mounts.md, doc/batch_changes/index.md, doc/batch_changes/references/batch_spec_yaml_reference.md
Also, any reason for this to be experimental?
Experimental features need to be feature flagged off by default, which doesn't make sense for this.
How about we make it GA, but add a note that we're iterating on this and feedback is very welcome? @Piszmog 
Just a docs change.
=> Clarify mount maturity and point to issue

cmd/symbols/shared/main.go, cmd/symbols/squirrel/breadcrumbs.go, cmd/symbols/squirrel/lang_java.go, cmd/symbols/squirrel/lang_python.go, cmd/symbols/squirrel/lang_starlark.go, cmd/symbols/squirrel/service.go
Most of the code is from:
- https://github.com/sourcegraph/sourcegraph/pull/43233
- https://github.com/sourcegraph/sourcegraph/pull/43234
- `env SRC_SQUIRREL_MAX_STACK_DEPTH=2 sg start codeintel`
- Hover over any Python symbol
- Notice the error
=> squirrel: Panic+recover on recursion limit exceeded

.buildkite/hooks/post-checkout, internal/database/event_logs_test.go
- Url added in db test tripped url lint
- Shell lint complained about a file
Test locally
=> sg: fix lint issues for urls and shell

cmd/symbols/squirrel/lang_python.go, cmd/symbols/squirrel/service_test.go, cmd/symbols/squirrel/test_repos/python/example.py
Fixes infinite recursion in python assignments.
- https://github.com/sourcegraph/sourcegraph/pull/43234 prevented stack overflow
Go tests
=> squirrel: Fix infinite loop in python assignments

internal/actor/http.go
None needed, only comment changed
=> actor: Fix typo in comment

client/web/src/components/fuzzyFinder/FuzzyModal.module.scss, client/web/src/components/fuzzyFinder/FuzzyModal.tsx
View in browser.
- [Web](https://sg-web-qk-style-tweaks-for-fuzzy-finder.onrender.com/search)
=> Fuzzy finder: tweaks to bring implementation closer to design

internal/codeintel/autoindexing/transport/graphql/root_resolver.go, internal/codeintel/shared/resolvers/index_resolver_connection.go, internal/codeintel/shared/resolvers/index_resolvers.go
Fixes https://github.com/sourcegraph/sourcegraph/issues/42434
Update error message in autoindexing page when tags fails
Run all the test.
=> [language-platform]: Update error message in autoindexing page when tags fails

client/web/src/components/fuzzyFinder/FuzzyFinder.story.tsx, client/web/src/components/fuzzyFinder/FuzzyModal.module.scss, client/web/src/components/fuzzyFinder/FuzzyModal.tsx, client/web/src/components/fuzzyFinder/FuzzyRepos.tsx
Co-Author: Quinn Keast <quinn@quinnkeast.com>
This is a copy of the PR https://github.com/sourcegraph/sourcegraph/pull/43291 but against the `main` branch.
See updated storybook.
- [Web](https://sg-web-olafurpg-fuzzy-styles.onrender.com/search)
=> Fuzzy finder: bring implementation closer to design

enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
From an API perspective, we treat executors as internal and the executor secret is an internal actor access token. This is no change to the before state, just makes sure that we don't forget to set the HTTP header (which actually was forgotten on some client calls). Eventually, this should be removed when we have more restrictive executor tokens.
Ran locally.
=> executors: Explicitly use internal actor for API

enterprise/internal/insights/scheduler/backfill_state_new_handler.go
Small fixes for transactionality around new backfiller.
Unit tests
=> insights: fix up new backfiller transaction

cmd/frontend/internal/app/ui/app.html
This adds Plausible to dot com and closes #43366.
- Ensure data is being tracked in Plausible
=> Adds Plausible to dot com

cmd/frontend/graphqlbackend/webhooks_test.go
These tests were missed on the out-of-date branch.
Tests pass now.
=> Fix webhook tests

dev/release/release-config.jsonc
n/a
- [Web](https://sg-web-unknwon-patch-1.onrender.com/search)
=> release: update config for 4.2.0

client/web/src/enterprise/codeintel/uploads/components/CodeIntelUploadNode.tsx
Fixes https://github.com/sourcegraph/sourcegraph/issues/33069
Updating icon to differentiate visually similar elements (>) so each icon can have different behavior.
No test needed.
- [Web](https://sg-web-cesar-33069-update-icons.onrender.com/search)
=> [language-platform] update icon to visually differentiate behavior

internal/search/job/jobutil/job.go
Semantics preserving, covered by existing tests
=> search: simplify search type filter logic

dev/release/release-config.jsonc
N/A
- [Web](https://sg-web-bo-update-config-patch-release.onrender.com/search)
=> update release config for patch request

.github/workflows/label-notify.yml
=> Update code notify for search product issues

internal/codeintel/policies/internal/store/store_repo_test.go, internal/codeintel/policies/internal/store/store_repos.go
#41064 removed a sort. Fixes #43472.
=> codeintel: Fix test nondeterminism

cmd/frontend/webhooks/github_webhooks.go, cmd/frontend/webhooks/github_webhooks_test.go
Uses `.Configuration` to unmarshal external service configs in the GitHub webhooks.
Tests still passing, investigating how to add extra tests.
=> Use .Configuration instead of .Config.Decrypt for GitHub Webhooks

cmd/frontend/graphqlbackend/repositories_test.go
See the [comment](https://github.com/sourcegraph/sourcegraph/pull/43071#discussion_r1003104844) on a PR for the webhooks test where I made this change for context
Unit tests pass
=> cleanup test to reduce code duplication

CHANGELOG.md
=> update changelog for patch release

internal/codeintel/codenav/init.go, internal/codeintel/codenav/ranking.go
Update the prefix of objects written to the GCS bucket.
Ran locally.
=> ranking: Make object names more hierarchical

client/web/src/enterprise/batches/list/GettingStarted.tsx, doc/batch_changes/index.md, doc/dev/background-information/batch_changes/index.md
closes #42412
update the batch changes demo video to include a flow for ssbc on the batch change index page as well as our docs
https://user-images.githubusercontent.com/67931373/196997252-487d845f-7b58-47a6-bd46-2061edaaf307.mp4
tested views of the video
- [Web](https://sg-web-aa-demo-video.onrender.com/search)
=> batches: replace video on index and leave notes on md files

go.sum
=> gomod: go mod tidy

doc/batch_changes/index.md
=> Monorepo is in beta

client/jetbrains/webview/src/search/index.tsx, client/shared/src/components/ranking/PerFileResultRankingTestHelpers.ts, client/shared/src/components/ranking/ZoektRanking.ts, client/web/src/search/home/TrySourcegraphCloudSection/TrySourcegraphCloudSection.module.scss, client/web/src/search/home/TrySourcegraphCloudSection/index.tsx, dev/scaletesting/bulkrepocreate/README.md, dev/scaletesting/codehostcopy/README.md
N/A
- [Web](https://sg-web-bo-prettier.onrender.com/search)
=> Run Prettier

cmd/gitserver/server/server.go
Minor change. This simplifies the call sites and makes it harder in the future to accidently use ensureRevision when DisableAutoGitUpdates is true.
=> gitserver: move DisableAutoGitUpdates check into ensureRevision

dev/scaletesting/README.md, dev/scaletesting/bulkrepocreate/README.md, dev/scaletesting/bulkreposettings/README.md, dev/scaletesting/bulkreposettings/main.go
This PR adds another script to the scaletesting collection, to update repositories in bulk on GitHub (enterprise). 
Manually tested, I used it to convert 200k repos to private in #43051
=> sct: add bulkreposettings

doc/admin/external_service/bitbucket_server.md, doc/admin/external_service/index.md
=> docs: Tweak bitbucket docs

cmd/frontend/internal/httpapi/search.go
=> Fix build by adding missing import

doc/api/graphql/managing-code-insights-with-api.md
Updates the insights api docs
docs only
=> insights: update api docs

internal/observation/observation.go
Updates `AddEvent` in `internal/observation` to send a Honeycomb Event marked as a `span_event` as per the OTel spec.
Could exhibit the issue I've mentioned in slack about not having tail-sampling for the raw honeycomb event aka this event may get sampled out while its "parent" does not. Not a problem I'm going to solve today though :rocket: 
Ran it locally and it worked as expected
=> observation: AddEvent sends honeycomb span-event

internal/codeintel/autoindexing/internal/background/iface.go, internal/codeintel/autoindexing/internal/background/job_scheduler.go, internal/codeintel/autoindexing/internal/background/mocks_test.go, internal/codeintel/policies/enterprise/matcher.go, internal/codeintel/policies/service.go
:hocho: 
Unit tests + compiler will cover this
=> codeintel: removed redundant method in policy matcher

doc/code_navigation/explanations/rockskip.md
=> rockskip: Add notes about when indexing is triggered

client/web/src/components/fuzzyFinder/FuzzyFiles.tsx, client/web/src/components/fuzzyFinder/FuzzyModal.module.scss, client/web/src/components/fuzzyFinder/FuzzyModal.tsx
Manually looked at the UI changes.
- [Web](https://sg-web-olafurpg-fuzzy-stuff.onrender.com/search)
=> Fuzzy finder: implement several suggestions

client/web/src/auth/CloudSignUpPage.tsx, client/web/src/auth/__snapshots__/SignUpPage.test.tsx.snap
Per design [spec](https://docs.google.com/document/d/1o2BVLvqwq3BPbj6jC7IXTbriu2SPadCe7wbeBsgjX3k/edit#) (2nd row)
- [Web](https://sg-web-becca-signup-copy-fix.onrender.com/search)
=> Signup copy adjustment

cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/deploy/machine-images/gce.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md
This pull request is part of the Sourcegraph 4.1.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.1.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43468)
=> release: sourcegraph@4.1.1

CHANGELOG.md
Changelog entries for https://github.com/sourcegraph/sourcegraph/pull/43591 as part of https://github.com/sourcegraph/sourcegraph/issues/43529
- N/A
=> Add changelog entry for removal of onboarding checklist

dev/release/release-config.jsonc
Release config update
- [Web](https://sg-web-bo-prepare-4-1-2-release.onrender.com/search)
=> update config for patch release 4.1.2

client/vscode/CHANGELOG.md, client/vscode/package.json
Requested by CE on [Slack](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1666973011485299?thread_ts=1660154184.480179&cid=C01LZKLRF0C)
Patch release to add new proxy support
This build passed the vs code integration test:
```
✓ works (19653ms)
1 passing (23s)
```
Unit tests are executed in the actual PRs that created the updates and fixes.
- [Web](https://sg-web-bee-release.onrender.com/search)
=> vsce: patch release v2.2.14

cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/deploy/machine-images/gce.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md
This pull request is part of the Sourcegraph 4.1.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.1.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43612)
=> release: sourcegraph@4.1.2

dev/release/release-config.jsonc
Release config
- [Web](https://sg-web-bo-update-releae-config.onrender.com/search)
=> release: update config for 4.2

internal/api/internalapi/client.go
Pretty terrible oopsie from #43280 , sorry 😬 
n/a for now, will find something robust to follow up with
=> internalapi: fix SendEmail arguments

CHANGELOG.md
Visually tested. Linter tests in CI.
=> Added fix mention to Changelog

internal/search/lucky/feeling_lucky_search_job.go
This makes incremental progress on shipping smart search on by default. We want to ship at least a minimally feature-complete version that works across the frontend and backend, which we can then optimize further. To do that I'm clamping some of the unoptimized/undesirable deduping behavior on the backend until I can iterate on that, see https://github.com/sourcegraph/sourcegraph/issues/43721 for more context.
Covered by existing tests, and not activated yet (will lock in with tests when enabled by default).
=> search: smart search activates on No Results only

doc/getting-started/index.md
Added sections for each feature and links to external learn.sourcegraph and youtube content for better self-service.
No review required: doc updates
=> additions and links to learn.sourcegraph

doc/getting-started/index.md
A couple small formatting fixes
No test plan required, minor formatting
=> small fixes

doc/admin/audit_log.md
Improve docs as per https://github.com/sourcegraph/sourcegraph/pull/43675#discussion_r1011371375
Run site manually.
=> Improve audit log docs.

internal/search/backend/metered_searcher.go
I want to investigate what happens for our new queries.
Test Plan: CI
=> search: log to honeycomb ranking options

cmd/gitserver/server/server.go
We seemed to have regressed on this and are spamming honeycomb with lots of events since no request is regarded as internal. I am not sure on the regression here, but this just stops the bleeding.
=> gitserver: UID 0 is treated as internal for honeycomb

internal/repos/github_test.go, internal/repos/testdata/golden/GithubSource_makeRepo_name-with-owner
New test case only. Builds pass.
=> internal/repos: Add test case for nameWithOwner

internal/database/schema.json, internal/database/schema.md, migrations/frontend/1667395984_remove_filter_from_lsif_references/down.sql, migrations/frontend/1667395984_remove_filter_from_lsif_references/metadata.yaml, migrations/frontend/1667395984_remove_filter_from_lsif_references/up.sql, migrations/frontend/squashed.sql
Is kinda big on dotcom (I know because I had to export a 23GB table lol).
This column has been unused for a while now.
=> codeintel: Remove unused filter column

doc/cloud/index.md
=> 15-day trials

dev/sg/sg_migration.go, internal/database/migration/cliutil/drift.go, internal/database/migration/cliutil/drift_schema.go, internal/database/migration/cliutil/multiversion.go
An alternative solution to #43694.
=> drift: Refactor expected schema factory to provide better output on error

internal/codeintel/ranking/loader.go, internal/codeintel/ranking/service.go, internal/codeintel/ranking/service_test.go
=> ranking: Ensure ranks are consistent (cheat sheet: 0=worse, 1=better)

client/web/src/search/home/QueryExamplesHomepage.tsx
Update Pro Tip copy for both auth'd and unauth'd visitors to .com.  This PR closes https://github.com/sourcegraph/sourcegraph/issues/43866.
=> Update protip language

internal/codeintel/codenav/internal/store/store.go, internal/codeintel/codenav/internal/store/store_test.go
Adds unit tests.
...new unit tests?
=> codeintel: Add missing codenav store unit tests

doc/dev/background-information/oobmigrations.md
Clarify how to deprecate an out of band migration
It's just docs, bruh
=> clarify oob migration deprecations

doc/dev/background-information/oobmigrations.md
Fix missing quotes in markdown
N/A
=> chore: fix missing quotes

monitoring/monitoring/internal/promql/promql.go, monitoring/monitoring/internal/promql/promql_test.go
Guards against https://github.com/sourcegraph/sourcegraph/pull/43865#discussion_r1012940874, returning an error like:
```
walk promql: unexpected sentinel value found in value of "job=~\"^frontend.*\"" - you may want to use ${variable:regex}
```
no diff or error from `go generate ./monitoring`, tests pass
=> monitoring/promql: guard against use of variables in regexp label match

client/jetbrains/CHANGELOG.md
I've submitted the new version to JetBrains. These are the changes made by the script.
(Only CHANGELOG changes)
=> JetBrains: 2.1.0 release

internal/codeintel/ranking/service.go
I think this is a more obvious way to write these ranking results.
Unit tests still pass!
=> ranking: Refactor generated/vendor/path tests

doc/admin/deploy/kubernetes/configure.md
Closes https://github.com/sourcegraph/sourcegraph/issues/43480
This PR adds instructions for configuring storageClass and Network in an RKE cluster, based on recent feedback from a customer. 
Check out this branch and run `yarn && yarn docsite:serve` to run the doc site locally:
Instructions are reported by customer.
=> docs/deploy add storage and network config for RKE

cmd/frontend/graphqlbackend/authz.go, cmd/frontend/graphqlbackend/authz.graphql, dev/gqltest/sub_repo_permissions_test.go, enterprise/cmd/frontend/internal/authz/resolvers/resolver.go, enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go, internal/gqltestutil/permissions.go
Reverts sourcegraph/sourcegraph#43964
But who will revert the reverts???
Turns out this wasn't the flake after all
N/A
=> Revert "Revert "Fix flaky Perforce integration tests""

client/browser/src/end-to-end/ghe.test.ts, client/web/src/enterprise/insights/components/views/card/InsightCard.tsx, client/web/src/enterprise/insights/pages/CodeInsightsRootPage.tsx, client/web/src/enterprise/insights/pages/dashboards/dashboard-page/DashboardsContentPage.tsx, client/web/src/enterprise/insights/pages/dashboards/dashboard-page/components/dashboard-menu/DashboardMenu.tsx, doc/admin/observability/dashboards.md, monitoring/definitions/codeintel_ranking.go, monitoring/definitions/dashboards.go, monitoring/definitions/shared/codeintel_ranking.go
=> ranking: Add basic dashboard

internal/database/github_app_helper.go
Was reading it and found it easier to read with the indentation. Decided to commit and create a PR. :) 
Cosmetic changes only.
=> internal/database/github_app_helper.go: Indent code

cmd/frontend/internal/httpapi/search.go, internal/codeintel/codenav/ranking.go
@sqs disabled ranking on dotcom in #43979. This re-enables it.
N/A.
=> ranking: Update conditions in which ranking runs

doc/cli/references/extsvc/create.md, doc/cli/references/extsvc/index.md, doc/cli/references/search.md, internal/src-cli/consts.go
- Updated minimum version to 4.1.1
- Ran `go generate` for docs
Just version + docs changes.
=> Bump src-cli minimum version

internal/database/schema.json, internal/database/schema.md, migrations/frontend/1667863757_drop_old_index/down.sql, migrations/frontend/1667863757_drop_old_index/metadata.yaml, migrations/frontend/1667863757_drop_old_index/up.sql, migrations/frontend/squashed.sql
=> ranking: Drop unused index

internal/extsvc/github/common.go
~I will investigate the build failures if this PR makes sense.~
Logging and error message change only. No functional change.
=> internal/extsvc/github: Log error from token.refreshFunc

client/web/src/search/home/QueryExamplesHomepage.constants.ts, client/web/src/search/home/QueryExamplesHomepage.tsx
Running `sg lint` failed locally on latest main.
Linter fix.
- [Web](https://sg-web-ig-sg-lint-fix-format.onrender.com/search)
=> client/web: Run sg lint -fix format

dev/release/release-config.jsonc
c.f https://github.com/sourcegraph/sourcegraph/issues/43840
Just a config change.
- [Web](https://sg-web-ps-prepare-4-1-3-release.onrender.com/search)
=> Update config for patch release 4.1.3

CHANGELOG.md
Add a change log entry for #43868
I want to include this in https://github.com/sourcegraph/sourcegraph/issues/43840 while we're at it (it's also very low risk).
Just a changelog change.
=> Add a changelog entry for #43868

CHANGELOG.md
It looks like we're going to create a patch release just for this fix: https://github.com/sourcegraph/sourcegraph/issues/43840. So let's at least have a change log entry ready for this.
Not needed, this is just a changelog entry.
=> Add a changelog entry for #43344

.github/workflows/progress.yml
update tag with image built on the correct architecture
n/a
=> update progress bot tag

internal/database/schema.json, internal/database/schema.md, migrations/frontend/1667917030_fix_codeintel_ranking_exports_index_order/down.sql, migrations/frontend/1667917030_fix_codeintel_ranking_exports_index_order/metadata.yaml, migrations/frontend/1667917030_fix_codeintel_ranking_exports_index_order/up.sql, migrations/frontend/squashed.sql
I think we get the same query plans, but this is more "correct" feeling, imo.
Tested on dotcom.
=> ranking: Improve `codeintel_ranking_exports` index

.github/workflows/progress.yml, internal/cmd/progress-bot/run.sh
Use the gcloud auth action and switch the service account
https://github.com/sourcegraph/sourcegraph/actions/runs/3420365877
=> progress_bot: use gcloud auth action

doc/getting-started/github-vs-sourcegraph.md
Review docs after they go live
=> Italicize note and update date

doc/getting-started/index.md
=> Add line before Code Search section

doc/getting-started/github-vs-sourcegraph.md
=> remove italics

cmd/frontend/graphqlbackend/webhook_logs.go, cmd/frontend/graphqlbackend/webhook_logs_test.go
See this PR discussion https://github.com/sourcegraph/sourcegraph/pull/44012#discussion_r1016381764
existing tests
=> gql: remove unnecessary webhook ID check

doc/getting-started/github-vs-sourcegraph.md
Update the Sourcegraph.com ranking algorithm on the docs.
No tests required: updating docs.
=> Update ranking details for Sourcegraph.com

internal/codeintel/codenav/internal/store/store.go
This change avoids second join to repo table. I don't think this helps on dotcom, where the query is consistently scanning through all relevant `lsif_uploads` and them being filtered out by an anti-join once they notice the work is already done.
Unit tests still pass.
=> ranking: (Possibly) optimize expensive periodic query

internal/codeintel/codenav/internal/store/store.go, internal/codeintel/codenav/internal/store/store_test.go, internal/codeintel/codenav/mocks_test.go, internal/codeintel/codenav/ranking.go
`Uplods`.
Existing CI pimpelimes.
=> chore: Me be an speelin chanp

client/web/src/search/helpers.tsx, cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/configure.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/deploy/machine-images/gce.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md
This pull request is part of the Sourcegraph 4.1.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.1.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/44078)
cc @philipp-spiess
=> release: sourcegraph@4.1.3

enterprise/dev/ci/scripts/app-token/main_test.go
Fix linting error for unused variable
https://buildkite.com/sourcegraph/sourcegraph/builds/182429
green tests on this build
=> apptoken: remove unused var

client/web/src/search/home/QueryExamplesHomepage.module.scss, dev/release/release-config.jsonc
Update release config to fix dates and new captain
N/A
- [Web](https://sg-web-cclark-release-config-4-3.onrender.com/search)
=> update release config for 4.2

internal/database/migration/runner/run.go
=> migrator: Fix missing logs for concurrent indexes that already exist

enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
In the previous [PR](https://github.com/sourcegraph/sourcegraph/pull/43736) `collectMetrics` was converted from a every 1 minute async collection to collecting metrics after every push to queue and doing perm sync. 
`collectMetrics` pull data from both DB and queue size from memory. Doing it with every sync/schedule is causing a lot of continuous load on DB. 
To fix it, this PR makes `collectMetrics` execute async and collect metrics from DB only every 15 seconds. Additionally, the queue size, which is collected from memory will still be collected with each sync and schedule.
=> [Permissions Syncs] fix collect metrics

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/question.md
=> correct typo in github templates

internal/repos/syncer.go
=> syncer: Fix typo

enterprise/cmd/executor/internal/worker/handler.go
This bugged me during your presentation, @eseliger.
No behavior changes.
=> executor: Weirdly verbose error handling

cmd/frontend/graphqlbackend/users_randomize_password.go, cmd/frontend/graphqlbackend/users_randomize_password_test.go
Currently, this only ever happens in dotcom mode. This updates the behaviour of `RandomizeUserPassword` to also send a password reset link on other Sourcegraph configurations if SMTP is enabled, while preserving the behaviour of the existing dotcom mode handling.
Updated tests pass
=> RandomizeUserPassword: send reset link in email if configured

client/web/src/enterprise/codeintel/indexes/components/CodeIntelIndexNode.tsx
Reloaded page, typo no longer existed.
- [Web](https://sg-web-aharvey-reindexeding.onrender.com/search)
=> codeintel: fix typo

cmd/gitserver/server/server.go
Is only 100 on dotcom which causes quite a bunch of queries. This bumps it to at least 500, which seems very reasonable.
Verified 500 is also performant.
=> Bump page size for gitserver repo iteration

dev/build-tracker/slack.go
Remove Grafana link that is posted in a build notification
Part of #43934
Unit tests
=> observability: remove grafana link gen from build-tracker

enterprise/internal/codeintel/autoindexing/internal/inference/libs/patterns.go
Remove unused code.
Unit tests.
=> inference: Remove unused go module code

internal/codeintel/dependencies/internal/background/job_cratesyncer.go
Part of https://github.com/sourcegraph/sourcegraph/issues/28532
Will look at dashboards after deployed
=> codeintel: Use an internal actor when syncing crates

client/web/src/Layout.tsx, client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx, client/web/src/nav/GlobalNavbar.tsx
Unblock PR testing
n/a
- [Web](https://sg-web-vg-fix-prettier.onrender.com/search)
=> chore: Reformat with prettier.

cmd/repo-updater/repoupdater/server.go
Also moved the helper below all the handlers.
Existing tests still pass
=> repo-updater: Use response helper in all handlers

client/web/src/site-admin/SiteAdminWebhooksPage.tsx
Test plan:
Existing storybook.
Closes https://github.com/sourcegraph/sourcegraph/issues/44291
- [Web](https://sg-web-ao-ui-fix-header.onrender.com/search)
=> web: fix SiteAdminWebhooksPage header.

client/web/src/Layout.tsx, client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx, client/web/src/nav/GlobalNavbar.tsx, internal/database/schema.json, internal/database/schema.md, migrations/frontend/1668179496_add_event_logs_name_timestamp/down.sql, migrations/frontend/1668179496_add_event_logs_name_timestamp/metadata.yaml, migrations/frontend/1668179496_add_event_logs_name_timestamp/up.sql, migrations/frontend/1668179619_drop_redundant_index/down.sql, migrations/frontend/1668179619_drop_redundant_index/metadata.yaml, migrations/frontend/1668179619_drop_redundant_index/up.sql, migrations/frontend/squashed.sql
This helps one of the dominating queries on DotCom.
Looked at query insights.
=> event_logs: Create better name/timestamp index

enterprise/internal/codeintel/autoindexing/internal/inference/infer.go, enterprise/internal/codeintel/autoindexing/internal/inference/lang_ruby_test.go, enterprise/internal/codeintel/autoindexing/internal/inference/libs/indexes.go, enterprise/internal/codeintel/autoindexing/internal/inference/libs/update-shas.sh, enterprise/internal/codeintel/autoindexing/internal/inference/lua/recognizers.lua, enterprise/internal/codeintel/autoindexing/internal/inference/lua/ruby.lua
Fixes https://github.com/sourcegraph/sourcegraph/issues/44122
TODO:
Added automated test. Also manually tested on Linux. Indexing did work, but there was some problem with Docker/src code-intel upload failing.
=> codeintel: Add support for Ruby auto-indexing.

.github/teams.yml
Update [team labeler config](https://github.com/JulienKode/team-labeler-action) based on the recent reorg. 
It works!
=> gh: update `team/code-exploration` labeler config

doc/admin/external_service/src_serve_git.md, doc/dev/background-information/web/styling.md, doc/getting-started/index.md, doc/index.md, doc/integration/gitlab.md, doc/sidebar.md
- add back description to docs homepage
- fix "GitLab" miscapitalization
- fix broken icons
Docs only
=> improve docs

enterprise/internal/codeintel/autoindexing/internal/inference/libs.go, enterprise/internal/codeintel/autoindexing/internal/inference/lua/clang.lua, enterprise/internal/codeintel/autoindexing/internal/inference/lua/go.lua, enterprise/internal/codeintel/autoindexing/internal/inference/lua/indexes.lua, enterprise/internal/codeintel/autoindexing/internal/inference/lua/java.lua, enterprise/internal/codeintel/autoindexing/internal/inference/lua/patterns.lua, enterprise/internal/codeintel/autoindexing/internal/inference/lua/python.lua, enterprise/internal/codeintel/autoindexing/internal/inference/lua/recognizer.lua, enterprise/internal/codeintel/autoindexing/internal/inference/lua/rust.lua, enterprise/internal/codeintel/autoindexing/internal/inference/lua/typescript.lua
Same effort as #44247, try not to use Go libs directly. Small effort in memory of #33040.
Existing tests.
=> inference: Prefer Lua over Go

enterprise/internal/codeintel/autoindexing/internal/inference/lua/ruby.lua
Handling https://github.com/sourcegraph/sourcegraph/pull/44249#pullrequestreview-1178259209.
=> codeintel: Fix ruby.lua import syntax

internal/search/backend/zoekt.go
=> search: remove unused StreamSearchEvent

dev/gqltest/external_service_test.go, dev/gqltest/sub_repo_permissions_test.go
Run this branch using `dry-run` to enable integration tests.
=> gqltest: Add a test that uses p4-fusion

doc/dev/background-information/oobmigrations.md
see title, follow-up after developing an oob migration
doc change only
=> docs: minor updates to developing an oob migration

dev/gqltest/external_service_test.go, dev/gqltest/sub_repo_permissions_test.go
This reverts commit 9333d30c6354fe5f2c43a87abce9bd2479f76e29.
Removes a flaky test
=> Revert "gqltest: Add a test that uses p4-fusion (#44346)"

doc/dev/background-information/workers.md
Given the number of changes around the worker API and underlying implementation, the docs were in need of a spring-cleaning :smugcat: (and ahead of https://github.com/sourcegraph/sourcegraph/pull/44294/)
Recommended reading with whitespace changes hidden
Ran docsite locally, tested link changes
=> worker: update 'Developing a worker' background-information doc

cmd/frontend/enterprise/enterprise.go, cmd/frontend/internal/httpapi/httpapi.go, cmd/frontend/internal/httpapi/webhookhandlers/handlers.go, cmd/frontend/webhooks/webhooks.go
Removed some dead code and simplified the signature of a method. Just a
few small things I spotted while thinking about how we can simply
webhook setup.
Existing tests
=> webhooks: Small cleanups

doc/admin/config/index.md
=> docs: link to global/user settings page

doc/admin/repo/webhooks.md
Requested by a partner, and documenting the answer. 
=> Add TTL expectations to webhooks doc page

doc/getting-started/index.md, doc/getting-started/oss-enterprise.md
=> Create Sourcegraph OSS vs Enterprise docs page

doc/getting-started/oss-enterprise.md
=> Fix bullets

.github/workflows/move-labled-issues-to-project.yml
=> Add insights issues to new project board

enterprise/cmd/frontend/internal/batches/webhooks/bitbucketcloud.go, enterprise/cmd/frontend/internal/batches/webhooks/bitbucketserver.go, enterprise/cmd/frontend/internal/batches/webhooks/github.go, enterprise/cmd/frontend/internal/batches/webhooks/gitlab.go, enterprise/cmd/frontend/internal/batches/webhooks/webhooks.go
* Improved a couple of error messages
* Made the `Webhook` internal
Existing tests still pass
=> webhooks: Small cleanups to batch changes webhooks

internal/src-cli/consts.go
=> batches: Update src-cli version

doc/admin/how-to/remove-repo.md
=> Adds note about "reclone" button introduced in 4.1

client/search-ui/src/input/toggles/SmartSearchToggle.tsx, client/search-ui/src/input/toggles/Toggles.tsx, client/vscode/src/webview/search-panel/SearchHomeView.tsx, client/vscode/src/webview/search-panel/SearchResultsView.tsx, client/web/src/integration/search.test.ts, client/web/src/search/home/SearchPageInput.tsx, client/web/src/search/results/StreamingSearchResults.test.tsx, client/web/src/search/results/StreamingSearchResults.tsx, client/web/src/stores/navbarSearchQueryState.ts, client/web/src/util/settings.ts, schema/schema.go, schema/settings.schema.json
This PR merges #44395 again after fixing tests. Just stamp because #44395 was already approved and needs to go in for branch cut.
Same as #44395
=> search: activate smart search by default

client/common/OWNERS, client/eslint-plugin-wildcard/OWNERS, client/http-client/OWNERS, client/observability-client/OWNERS, client/observability-server/OWNERS, client/wildcard/OWNERS
Switch the ping to the `@sourcegraph/code-exploration-devs` team instead.
N/A
- [Web](https://sg-web-lrh-update-fpt-owners-files.onrender.com/search)
=> Update FPT code owners ping

client/web/src/site-admin/analytics/AnalyticsUsersPage/index.tsx, client/wildcard/src/components/Charts/components/bar-chart/BarChart.tsx, client/wildcard/src/components/Charts/components/bar-chart/BarChartContent.tsx, client/wildcard/src/components/Charts/components/bar-chart/components/TooltipContent.tsx
Update label of frequency user char in user admin analytics. 
- [Web](https://sg-web-naman-update-labels-box.onrender.com/search)
=> [In-Product Analytics] update labels

doc/admin/search.md
(Taking into account feedback from https://sourcegraph.slack.com/archives/C023ELQLV7F/p1668533656534409 and https://sourcegraph.slack.com/archives/C07KZF47K/p1668614269300879?thread_ts=1668120346.452419&cid=C07KZF47K)
I've cleaned up and fleshed out some of the Zoekt scaling advice that I've written recently. 
N/A
=> docs: add scaling considerations for zoekt

CHANGELOG.md
=> changelog: cut sourcegraph@4.2.0

internal/database/migration/stitch/stitch.go
Adding a note to help users understand what to do if they encounter this (especially during release)
N/A
=> update error string to point users in the right direction

client/web/src/repo/RepoRevisionSidebarSymbols.tsx
Fixes e2e test regression from #44314
Tests should pass
=> symbols sidebar: fix e2e tests

doc/admin/executor_secrets.md
=> Link to encryption

client/web/src/featureFlags/featureFlags.ts, client/web/src/repo/blame/useBlameHunks.ts, client/web/src/repo/blob/codemirror/blame-decorations.tsx
=> Mrn+jh+ps/streaming git blame
