- client/web/src/components/FilteredConnection/ConnectionType.ts
- client/web/src/components/FilteredConnection/hooks/usePaginatedConnection.test.tsx
- client/web/src/components/FilteredConnection/hooks/usePaginatedConnection.ts
- client/web/src/search/backend.tsx
> Add usePaginatedConnection

- client/wildcard/OWNERS
I've been working on wildcard UI a lot recently so this mention will help me to track any wildcard changes that are happening in the wildcard components.
- N/A
- [Web](https://sg-web-vk-add-myself-to-wildcard-owners.onrender.com/search)
> Add @vovakulikov to wildcard OWNERS

- enterprise/internal/codeintel/uploads/internal/store/store_repositories.go
This PR removes the portion of a query that is conditionally executed via `WHERE` clause. It seems to be faster when the select query containing the clause does not exist at all in the query text.
**Before**:
We have a query performing a three-way union all. The first one has an `AND FALSE` condition, which translates (properly) into a one-time filter that throws all rows out of the selection. The first select in this union is disabled on the DotCom instance.
```sql
WITH repositories_matching_policy AS (
(
SELECT r.id
FROM repo r
WHERE
r.deleted_at IS NULL AND
r.blocked IS NULL AND
EXISTS (
SELECT 1
FROM lsif_configuration_policies p
WHERE
p.indexing_enabled AND
p.repository_id IS NULL AND
p.repository_patterns IS NULL
) AND FALSE
ORDER BY stars DESC NULLS LAST, id
LIMIT 100000
) UNION …
```
> codeintel: Speed up repository selection for auto-indexing

- client/browser/src/shared/code-hosts/shared/testHelpers.ts
- client/codeintellify/src/hoverifier.ts
- client/shared/src/platform/context.ts
- client/web/src/util/contributions.ts
- package.json
- yarn.lock
Thanks to @eseliger for starting this. I slightly simplified Erik's PR, it seems that yarn build-ts is passing so should be relatively safe to merge.
- Make sure that CI is passing
- [Web](https://sg-web-vk-upgrade-ts-4-9-3.onrender.com/search)
> Upgrade TypeScript to the 4.9.3

- doc/dev/adr/1669125523-do-not-adopt-git-fork-from-microsoft.md
- doc/dev/adr/index.md
@varsanojidan worked on this, I think it would be useful to record this decision and its results. 
@varsanojidan Perhaps you wanted to wait before sharing this, if yes, please close this PR. I was driving by the ADRs and it took me just 3m to get this done. 
ADR, nothing to test.
> adr: do not adopt git fork from microsoft

- client/jetbrains/README.md
- Alternative PR for https://github.com/sourcegraph/sourcegraph/pull/44707
Only docs change.
> JetBrains: Clarify instance type config

- .github/workflows/buildchecker-history.yml
- .github/workflows/buildchecker.yml
- .github/workflows/licenses-check.yml
- .github/workflows/pr-auditor.yml
- .github/workflows/sg-binary-release.yml
- go.mod
- internal/cmd/resources-report/go.mod
- lib/go.mod
Bump it.
Bop it.
Twist it.
Upgrade it.
THE CONTINUOUS INTEGRATION SERVER, **CONTINUUON**.
> go: Use Go 1.19

- cmd/frontend/backend/user_emails.go
- cmd/frontend/backend/user_emails_test.go
- cmd/frontend/graphqlbackend/user_emails.go
- cmd/frontend/graphqlbackend/user_emails_test.go
Move the "business logic" into the `backend` package and add some basic tests.
In preparation for adding some cleanup code as part of https://github.com/sourcegraph/sourcegraph/issues/44482
Extra tests added
> Move e-mail removal code into backend package

- enterprise/internal/authz/bitbucketserver/provider.go
- internal/encryption/json_encryptable.go
- internal/extsvc/gerrit/account.go
- internal/extsvc/github/common.go
- internal/extsvc/gitlab/user.go
- internal/extsvc/perforce/account.go
Instead of needing to pass a value in, we can supply the type we want
and return a new value of that type.
All tests still pass
> encryption: Simplify EncryptJSON

- enterprise/internal/codeintel/autoindexing/internal/background/job_dependency_indexing_scheduler.go
- enterprise/internal/codeintel/autoindexing/internal/background/job_dependency_indexing_scheduler_test.go
Previously, there was an unhandled case where if no external service was returned when listing external services for the kind associated with a package repo auto-indexing scheduling job, we would attempt to queue auto-index jobs anyways. This would cause a lot of error logging for repos not existing in the table but being requested for.
This PR makes us early-out if no external service was found, and also includes an improvement to handling package repos that dont exist (`len(repoNames)` >= `len(results)`, may be useful down the line if/when we dont add repo entries for non-existant packages. Do we want this in a separate PR perhaps?). 
Ran locally, and regressions should hopefully be handled by unit tests
> packages: dont queue auto-index job if no extsvc of given kind

- docker-images/opentelemetry-collector/Dockerfile
- docker-images/opentelemetry-collector/builder.template.yaml
Updated the config based on the recommendation here:
- https://github.com/open-telemetry/opentelemetry-collector/issues/6604#issuecomment-1325780273
Built the container locally
> otel: update otel build config

- doc/dev/background-information/workers.md
More tiny fixes I noticed while reading through docs.
- N/A
> docs: tiny fixes in worker docs

- internal/ratelimit/rate_limit.go
No longer high cardinality on dotcom. Let's remove it.
- N/A
> ratelimit: remove special case for Cloud v1

- cmd/searcher/internal/search/hybrid.go
When looking at dashboards we have a few errors across our different places we can fail. However, in everycase the logs seem to correlate with request cancellation (as well as a high volume of requests).
As such we ensure we always handle these conditions when recording metrics.
Test Plan: go test as well as monitoring grafana in prod.
> searcher: always handle request cancellation in hybrid metrics

- client/web/src/enterprise/batches/batch-spec/edit/workspaces-preview/useWorkspacesPreview.ts
For a new batch change, and when the current batch spec has been applied before, the workspace resolution would be trapped with an infinite loader. The initial empty spec has no workspace resolution. When submitted, we start fetching the status of the batch spec known prior saving. For ReplaceBatchSpecInput, that is not a problem, but when we go the CreateBatchSpecFromRaw path, we need to fetch the state of that NEW batch specs workspace resolution.
Verified the outlined scenario works now.
- [Web](https://sg-web-es-fix-resolution-fetch.onrender.com/search)
> Fix workspace resolution infinite loading

- go.mod
- go.sum
> chore: Update sg/scip dependency

- enterprise/internal/codeintel/ranking/internal/store/store.go
- internal/database/basestore/scan_collections.go
> chore: Remove unused generic parameter

- internal/database/schema.codeintel.json
- internal/database/schema.codeintel.md
- migrations/codeintel/1669075922_add_scip_tables/down.sql
- migrations/codeintel/1669075922_add_scip_tables/metadata.yaml
- migrations/codeintel/1669075922_add_scip_tables/up.sql
- migrations/codeintel/squashed.sql
Extracting the SCIP schema from #42850.
N/A.
> codeintel: Add tables to store SCIP data

- enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore_delete.go
- enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore_documents.go
- enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore_reconcile.go
- enterprise/internal/codeintel/uploads/internal/lsifstore/observability.go
- enterprise/internal/codeintel/uploads/internal/lsifstore/stream.go
Add observability wrappers to lsfistore methods.
N/A.
> codeintel: Fix observability on upload/lsifstore

- internal/adminanalytics/users.go
- internal/adminanalytics/utils.go
These vars should just be consts.
CI
> chore: change constant vars to const

- internal/src-cli/consts.go
This includes a fix for binary patches.
Has been tested and approved in implementation PRs.
> Bump src-cli version

- cmd/gitserver/server/list_gitolite.go
- cmd/gitserver/server/list_gitolite_test.go
- internal/security/security.go
- internal/security/security_test.go
> Fix gitoliteHost validation

- cmd/frontend/webhooks/webhooks_test.go
> fix lint issue w/ webhooks test

- client/web/src/nav/GlobalNavbar.tsx
This closes #44848 and changes the copy for the Try SG CTA.
Ensure the button says "Search private code"
- [Web](https://sg-web-brett-topnavcta.onrender.com/search)
> Search private code CTA

- cmd/frontend/internal/app/updatecheck/handler.go
- doc/admin/deploy/docker-compose/aws.md
- doc/admin/deploy/docker-compose/azure.md
- doc/admin/deploy/docker-compose/digitalocean.md
- doc/admin/deploy/docker-compose/google_cloud.md
- doc/admin/deploy/docker-compose/index.md
- doc/admin/deploy/docker-single-container/aws.md
- doc/admin/deploy/docker-single-container/digitalocean.md
- doc/admin/deploy/docker-single-container/google_cloud.md
- doc/admin/deploy/docker-single-container/index.md
- doc/admin/deploy/kubernetes/configure.md
- doc/admin/deploy/kubernetes/helm.md
- doc/admin/deploy/machine-images/gce.md
- doc/admin/external_services/postgres.md
- doc/admin/external_services/redis.md
- doc/admin/http_https_configuration.md
- doc/admin/ssl_https_self_signed_cert_nginx.md
- doc/admin/updates/docker_compose.md
- doc/admin/updates/kubernetes.md
- doc/admin/updates/pure_docker.md
- doc/admin/updates/server.md
- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/pipeline.go
This pull request is part of the Sourcegraph 4.2.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.2.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43423)
> release: sourcegraph@4.2.0

- dev/release/release-config.jsonc
4.3.0 release config
N/A
- [Web](https://sg-web-cclark-4-3-0-release-config.onrender.com/search)
> 4.3.0 release config

- doc/admin/audit_log.md
Audit log: add a FAQ section w/ "hydrate actors" steps.
Ran the docs manually.
> Audit log: add a FAQ section w/ "hydrate actors" steps.

- enterprise/internal/codeintel/shared/types/scip_canonicalize.go
- enterprise/internal/codeintel/shared/types/scip_sort.go
Add additional sort/canonicalization utils for SCIP structures.
N/A.
> codeintel: Add SCIP canonicalization utils

- internal/database/schema.codeintel.json
- internal/database/schema.codeintel.md
- migrations/codeintel/1669842405_add_additional_metadata_fields/down.sql
- migrations/codeintel/1669842405_add_additional_metadata_fields/metadata.yaml
- migrations/codeintel/1669842405_add_additional_metadata_fields/up.sql
- migrations/codeintel/squashed.sql
> codeintel: Add additional metadata fields to SCIP tables

- enterprise/internal/codeintel/shared/types/scip_sort.go
Just a consistency change.
N/A.
> chore: Change variable name

- doc/admin/how-to/postgres14-index-corruption.md
No test plan required. Fixing typo in documentation
> Fix typo and note section

- enterprise/internal/oobmigration/migrations/codeintel/types.go
- lib/codeintel/precise/types.go
We'll need access to this new field in the oobmigrator soon. Also drive-by added documentation to original field.
N/A.
> chore: Mirror Manager field in oobmigration package

- enterprise/cmd/frontend/internal/batches/resolvers/resolver.go
- enterprise/cmd/frontend/internal/batches/resolvers/resolver_test.go
Check for empty ID string when fetching batch workspace files by ID.
> batches: check for empty ID when fetching batch workspace file by ID

- doc/dev/background-information/sg/reference.md
- monitoring/command/generate.go
- monitoring/monitoring/generator.go
- monitoring/monitoring/multi_instance.go
Make `-multi-instance-groupings` behaviour mutually exclusive with the standard generate behaviour.
run locally, CI
> monitoring: make -multi-instance-groupings only generate multi-instance stuffs

- monitoring/monitoring/internal/grafana/board.go
- monitoring/monitoring/monitoring.go
- monitoring/monitoring/multi_instance.go
Makes sure we have no discrepancies, we're seeing Grafana still unhappy with our custom board config.
This PR will also make rank me above renovate bot in terms of commits
CI
> monitoring: unify board creation

- monitoring/monitoring/generator.go
- monitoring/monitoring/internal/grafana/home.go
- monitoring/monitoring/internal/grafana/home.json.tmpl
> monitoring: set tags, UID on home dashboard

- internal/database/schema.codeintel.json
- internal/database/schema.codeintel.md
- migrations/codeintel/1669075922_add_scip_tables/up.sql
- migrations/codeintel/1669934289_add_scip_document_schema_versions_table/down.sql
- migrations/codeintel/1669934289_add_scip_document_schema_versions_table/metadata.yaml
- migrations/codeintel/1669934289_add_scip_document_schema_versions_table/up.sql
- migrations/codeintel/squashed.sql
Confused myself with copy-and-paste.
Existing CI pipelines.
> codeintel: Fix migration comment and add missing function

- migrations/codeintel/1669075922_add_scip_tables/down.sql
Renamed this in the up migration but not in the down migration.
Existing pipelines.
> codeintel: Fix asymmetric down migration

- doc/admin/observability/dashboards.md
- monitoring/definitions/frontend.go
> monitoring: fix typo in email panel

- doc/dev/how-to/add_monitoring.md
See https://github.com/sourcegraph/customer/issues/1151
n/a
> doc/dev: document monitoring MultiInstance

- client/web/scripts/report-bundle-diff.ts
c.f. https://sourcegraph.slack.com/archives/C01N83PS4TU/p1669960214116879
This prevents crashes on forks.
Will test run on CI.
- [Web](https://sg-web-ps-fix-bundle-size-script-for.onrender.com/search)
> Handle missing BUILDKITE_PULL_REQUEST or BUILDKITE_PULL_REQUEST_REPO gracefully

- dev/codeintel-qa/scripts/clone-and-index.sh
- dev/codeintel-qa/scripts/clone.sh
- dev/codeintel-qa/scripts/download.sh
- dev/codeintel-qa/scripts/go-index.sh
- dev/codeintel-qa/scripts/upload.sh
`parallel_run.sh` didn't exist as expected.
Ran scripts by hand.
> codeintel-qa: Fix working directory in scripts

- doc/admin/postgres.md
> fix-typo-in-upgrade-doc

- dev/release/release-config.jsonc
Moving release day to 15th
N/A
- [Web](https://sg-web-cclark-move-release-date.onrender.com/search)
> moving release date to 15th

- client/web/src/enterprise/codeintel/badge/components/CodeIntelligenceBadgeMenu.story.tsx
- client/web/src/enterprise/codeintel/badge/components/IndexerSummary.tsx
- client/web/src/enterprise/codeintel/badge/components/UserFacingCodeIntelligenceBadgeContent.tsx
- client/web/src/enterprise/codeintel/badge/hooks/queries.ts
- client/web/src/enterprise/codeintel/badge/hooks/useCodeIntelStatus.ts
- cmd/frontend/graphqlbackend/codeintel.graphql
- enterprise/internal/codeintel/autoindexing/internal/jobselector/job_selector.go
- enterprise/internal/codeintel/autoindexing/transport/graphql/iface.go
- enterprise/internal/codeintel/autoindexing/transport/graphql/mocks_test.go
- enterprise/internal/codeintel/autoindexing/transport/graphql/root_resolver.go
- enterprise/internal/codeintel/autoindexing/transport/graphql/utils.go
- enterprise/internal/codeintel/shared/resolvers/summary.go
- enterprise/internal/codeintel/shared/types/indexers.go
- internal/codeintel/resolvers/all.go
- lib/codeintel/autoindex/config/types.go
- lib/codeintel/autoindex/config/types_test.go
Fixes #33793 
Fixes #34473 
A couple code intelligence badge updates:
- Show when additional coverage is available
- Do not request support for existing languages
Ran all the tests!
> [language-platform] Code intelligence badge updates

- doc/admin/how-to/site-admin-quickstart.md
Not anywhere in the docs I could find – customer/AE need here: https://sourcegraph.slack.com/archives/C015P61EXV1/p1670028915022519 .
> Docs: note how to add more admins

- cmd/symbols/shared/main.go
This is a small change that makes another refactor (that I will land soon) easier and have less of a merge conflict.
Minor code move, no manual test needed.
> extract sanityCheck

- cmd/frontend/graphqlbackend/git_commits.go
Add a helper and clean up the repetitive code.
Stumbled upon this while working on another PR.
No functional change. Existing tests should pass,
> graphqlbackend: Simplify pointer to value code

- enterprise/cmd/frontend/internal/auth/openidconnect/middleware.go
Addresses another issue in the OIDC login flow with TLS enabled. The user info call function as well as the token exchange need to use the external HTTP client as well.
Did a full login test with a reverse proxy that requires TLS. Managed to log in using Auth0 as an Open ID Connect provider.
> Use external http client for OIDC token exchange

- CONTRIBUTING.md
- doc/dev/setup/quickstart.md
- Fixes https://github.com/sourcegraph/sourcegraph/issues/45158
Only docs change.
> Docs: Add info about running PRs

- enterprise/internal/insights/query/streaming/decoder.go
We can reduce code duplication here since we have the same handler copy pasted 4 times. Motivated by https://github.com/sourcegraph/sourcegraph/pull/45069 which wanted to add a new condition to the handler.
> insights: factor out common OnProgress handler

- cmd/sitemap/main.go
migrate sitemap away from log15 
Some liberties are taken here when going from `error` to `warn` but as I understand it we only use error if we really want to see something in Sentry. 
part of https://github.com/sourcegraph/sourcegraph/issues/40896
CI
> logging: migrate to sglog

- cmd/frontend/globals/globals.go
The panic was unnecessary (and prevents us from running multiple services in the same process, which is an experimental goal of mine as part of creating a single Go static binary distribution of Sourcegraph).
n/a
> silently (without panics) enforce WatchPermissionsUserMapping called once

- enterprise/internal/codeintel/shared/types/scip_canonicalize.go
- enterprise/internal/codeintel/shared/types/scip_flatten.go
- enterprise/internal/codeintel/shared/types/scip_sort.go
- sg.config.yaml
This PR adds additional canonicalization steps to documents, symbols, and occurrences.
Used in another feature branch with additional tests.
> codeintel: Add additional canonicalization transformations

- dev/gqltest/search_test.go
> search contexts: fix backend integration test

- doc/dev/background-information/workers.md
While going through this guide, I've noticed some room for improvement.
Tried my best to assist future readers.
Changes:
- Added a step to add a store and a dummy handler function. With this, the example is much more complete.
- Clarified that the snippets can be copy&pasted to the same file, and it'll work.
- Fixed problems around aliased imports
- Fixed argument types for `dbworkerstore.New` (function signature probably changed since the time of writing)
- Made imports incremental to better assist the reader in assembling a dummy worker.
- Fixed typos
Docs change only. Go through the changed file and see if it makes sense.
- [Web](https://sg-web-dv-docs-improve-adding-new-worker.onrender.com/search)
Check out the [client app preview …
> Docs: Improve "Adding new worker" guide

- doc/admin/deploy/single-node/index.md
- doc/admin/deploy/single-node/script.md
Docs change to accompany
- https://github.com/sourcegraph/deploy/pull/18
This should not be merged until the above PR is merged
Test deployment, view docs for details/see above PR
> Add docs for generic install script to deploy a production Sourcegraph instance

- cmd/frontend/backend/webhooks.go
- cmd/frontend/backend/webhooks_test.go
- cmd/frontend/graphqlbackend/schema.graphql
- cmd/frontend/graphqlbackend/webhooks.go
- enterprise/cmd/frontend/internal/repos/webhooks/resolvers/resolver.go
- enterprise/cmd/frontend/internal/repos/webhooks/resolvers/resolver_test.go
- internal/database/mocks_temp.go
- internal/database/webhooks.go
- internal/database/webhooks_test.go
Follow-up comments from this PR: https://github.com/sourcegraph/sourcegraph/pull/44994#pullrequestreview-1204920653
Removes unnecessary nulls, which is nice :)
Tests adjusted where applicable.
> Follow-up comments on PR

- cmd/frontend/graphqlbackend/external_service.go
- cmd/frontend/graphqlbackend/external_services_test.go
- enterprise/internal/batches/sources/sources_test.go
- internal/database/external_services_test.go
- internal/database/repos_perm_test.go
- internal/repos/syncer.go
- internal/repos/syncer_test.go
- internal/repos/types.go
- internal/repos/types_test.go
Code removed in `sg hacking hour`
- 🤞 
> sg hacking hour offsite: removing cloud v1 code

- internal/database/helpers.go
- internal/database/users.go
- internal/database/users_test.go
A common pain point I have is finding the user for an ID that I come across in logs or honeycomb. This addition makes it possible to search for an ID or GraphQL ID in the site admin user panel and if it matches a user that user will be returned.
Test Plan: added a unit test for List
> database: UsersListOptions.Query searches for ID

- dev/scaletesting/codehostcopy/bitbucket.go
- moved some logs to debug level 
- removed an unusued context parameter
CI + build
> sct: fix error handling + logs in bitbucket

- package.json
- yarn.lock
CI
- [Web](https://sg-web-es-bump-chromatic.onrender.com/search)
> Bump chromatic CLI

- cmd/frontend/internal/cli/config.go
- internal/endpoint/endpoint.go
- internal/endpoint/endpoint_test.go
- internal/endpoint/k8s.go
- internal/endpoint/k8s_test.go
- internal/symbols/client.go
migrate endpoints to `sourecgraph/log`
CI
> endpoint: migrate to sg/log

- enterprise/cmd/frontend/internal/repos/webhooks/resolvers/resolver.go
> webhooks: fix setting webhook kind as its name

- dev/release/release-config.jsonc
4.2.1 patch
N/A
- [Web](https://sg-web-cclark-4-2-1-patch.onrender.com/search)
> 4.2.1 patch

- doc/admin/external_service/index.md
- doc/admin/repo/plasticscm.md
See this thread for context: https://twitter.com/SirSeanOfLoxley/status/1590400352960274434
Tested locally
> doc: add Plastic SCM

- cmd/frontend/internal/search/logs/logs.go
Just removing dead code.
Build passes.
> Search: remove unused MapToLog15Ctx

- enterprise/internal/insights/store/permissions.go
- enterprise/internal/insights/store/store.go
for work on #42128 to debug
Looked at the spans locally
> insights: experimental: add traces around fetching series points

- client/web/src/site-admin/SiteAdminWebhookCreatePage.story.tsx
- client/web/src/site-admin/SiteAdminWebhookPage.story.tsx
- client/web/src/site-admin/SiteAdminWebhookPage.tsx
- client/web/src/site-admin/SiteAdminWebhookUpdatePage.story.tsx
- client/web/src/site-admin/SiteAdminWebhookUpdatePage.tsx
- client/web/src/site-admin/WebhookCreateUpdatePage.tsx
- client/web/src/site-admin/WebhookNode.tsx
- client/web/src/site-admin/backend.ts
- client/web/src/site-admin/fixtures.ts
- client/web/src/site-admin/routes.tsx
Test plan:
Storybook and manual testing.
Closes https://github.com/sourcegraph/sourcegraph/issues/43490
- [Web](https://sg-web-ao-ui-webhooks-update-webhook.onrender.com/search)
> web: add SiteAdminWebhookUpdatePage.

- doc/dev/how-to/sourcegraph_ngrok.md
Often taken for granted but not a very new-comer-friendly step.
N/A
> doc: improve ngrok step

- internal/observation/observation.go
- internal/uploadhandler/observability.go
These errors are not actionable to use (codeintel) and just adds unnecessary noise to the internal channel
Does not impact any core logic, only telemetry. I added an if statement, a != expression, and an ^ expression :) Tested that `errors.As` correctly catches the error her
> codeintel: dont emit connrefused error to sentry

- doc/cloud/index.md
wrap up https://github.com/sourcegraph/sourcegraph/pull/39666
n/a docs changes
> docs: improve cloud docs

- enterprise/internal/insights/store/permissions.go
- enterprise/internal/insights/store/store.go
removal of experimental change only
> insights: remove experimental traces in points loading

- client/web/src/integration/insights/insight/dashboard-cards.test.ts
Wait for the bar chart content
- Integration test should pass
- [Web](https://sg-web-vk-fix-insight-integration-tests.onrender.com/search)
> Fix code insights integration test for compute insight card

- internal/database/schema.json
- internal/database/schema.md
- migrations/frontend/1670539388_create_roles_table/down.sql
- migrations/frontend/1670539388_create_roles_table/metadata.yaml
- migrations/frontend/1670539388_create_roles_table/up.sql
- migrations/frontend/1670539913_create_permissions_table/down.sql
- migrations/frontend/1670539913_create_permissions_table/metadata.yaml
- migrations/frontend/1670539913_create_permissions_table/up.sql
- migrations/frontend/squashed.sql
Closes #45436
Manually verified that two tables were created with the correct schema:
* roles
* permissions
> create roles and permissions table

- doc/admin/updates/kubernetes.md
> doc: update k8s release notes

- .vscode/settings.json
> use prettier for formatOnSave for consistency with ci

- doc/dev/adr/1669125523-do-not-adopt-git-fork-from-microsoft.md
Feedback after reviewing https://github.com/sourcegraph/sourcegraph/pull/44709
n/a
> adr: fix typos

- doc/admin/repo/permissions.md
> doc: fix list style rendering

- doc/code_insights/explanations/current_limitations_of_code_insights.md
Comes up 1-2 times a month, we should document it here!
> insights docs: update size and order limitation

- internal/search/env.go
From reading the call sites of this function it relies on full information (eg usagestats/etc).
Related to https://github.com/sourcegraph/sourcegraph/pull/45518
> search: fail ListAllIndexed if zoekt is partially available

- enterprise/cmd/symbols/shared/setup.go
I stumbled across this while re-enabling the linters. The `rockskipGoroutines` parameter is always nil. Still, I thought it'd be better to surface it in a small PR rather than in my upcoming PR with loads of fixes. 
CI
> rockskip: remove always nil return value

- doc/batch_changes/explanations/introduction_to_batch_changes.md
this is now supported 
doc update
> batches: doc update update fork known issues

- cmd/frontend/graphqlbackend/repository_text_search_index.go
Previously we may incorrectly report a repository as not indexed due to a rollout. Now we specifically handle the case when we fail to find an index during a rollout.
Note: This error only affects the admin page showing if a repository is indexed.
> search: display an error in index page during rollout

- internal/src-cli/consts.go
> bunp src-cli constant 4.3

- client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx
Verified the updated changelog is shown in the Batch Changes list page.
- [Web](https://sg-web-bo-batches-changelog-4-3.onrender.com/search)
> 4.3 in-app changelog for Batch Changes

- CHANGELOG.md
Part of https://github.com/sourcegraph/sourcegraph/issues/45566
Release, no review needed
> changelog: cut sourcegraph@4.3.0

- internal/database/migration/shared/upgradedata/cmd/generator/consts.go
- internal/database/migration/shared/upgradedata/stitched-migration-graph.json
- internal/database/migration/stitch/stitch.go
Update `maxVersionString`
Review
> Update maxVersion string

- enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
Speed up migrating LSIF -> SCIP when the number of result chunks can fit in the cache. Load all of them at once instead of over different queries.
> codeintel: Warm result chunk cache on small LSIF uploads

- internal/database/batch/batch.go
Add a new convenience function that collects the return values from `RETURNING id`-type batch inserts.
It's all glue that was used in another PR.
> database: Add `WithInserterForIdentifiers`

- internal/honey/event.go
Main purpose of this commit is to identify services in production which
are attempting to log to honeycomb but do not have the secrets setup. In
particular I'm interested in ensuring all uses of the zoekt-search
dataset are getting logged.
Maybe we don't need a counter since we could just check counters in
honeycomb, but this felt natural.
> honey: prometheus counter around NewEvent calls 

- internal/database/schema.json
- internal/database/schema.md
- migrations/frontend/1670870072_add_read_only_column_roles/down.sql
- migrations/frontend/1670870072_add_read_only_column_roles/metadata.yaml
- migrations/frontend/1670870072_add_read_only_column_roles/up.sql
- migrations/frontend/squashed.sql
Manually verified I could upgrade and downgrade the added migration.
> Add readonly column to `roles` table

- doc/admin/repo/metadata.md
Add more GraphQL examples and add src-cli command examples
Docs update
> docs: update repository metadata docs

- cmd/frontend/backend/user_emails.go
- cmd/frontend/backend/user_emails_test.go
- cmd/frontend/graphqlbackend/user_emails_test.go
Closes https://github.com/sourcegraph/sourcegraph/issues/44482
Test plan:
Tests added
> authz: Clear stale Perforce external accounts when email unverified

- doc/dev/background-information/web/graphql.md
First attempt to codify some of the pagination changes in our docs.
We'll want to add a good example implementation as well later.
Thoughts? Anything that we should add?
docs change
> Add section about pagination to GraphQL guide

- migrations/frontend/1669576792_make_batch_spec_of_batch_change_nullable/up.sql
Need to drop the constraint first and then delete the batch specs, otherwise violates the constraint.
Reviews.
> Fixup batch changes migration

- cmd/repo-updater/repoupdater/server.go
- enterprise/internal/authz/perforce/perforce.go
> otel: Remove some uses of deprecated LogFields

- doc/admin/external_service/index.md
Quick followup to https://github.com/sourcegraph/sourcegraph/pull/45579
Doc update
> Doc: quick follow up clarifications

- enterprise/internal/database/mocks_temp.go
- internal/database/database.go
- internal/database/mocks_temp.go
- internal/database/roles.go
- internal/database/roles_test.go
- internal/types/types.go
Part 1 #45456
Added unit tests for store methods
> rbac: Create store methods for roles and permissions (Part 1)

- client/web/src/nav/StatusMessagesNavItem.story.tsx
- client/web/src/nav/StatusMessagesNavItem.tsx
- internal/repos/status_messages_test.go
Follow up to #45619 for post merge review.
**Message on hover**
**Updated status message**
> ui: Fix bug and improve status message

- cmd/frontend/graphqlbackend/graphqlbackend.go
- cmd/frontend/graphqlbackend/slow_requests_tracer.go
- cmd/frontend/graphqlbackend/slow_requests_tracer_test.go
Forgot to rebase my branch without merging (typical, do what I say, not what I do 🤦) 
sg lint go should be green.
> Fix linting error about unused context

- doc/dev/background-information/sg/index.md
Follow up to #45161 to update the docs.
Docs only.
> doc/dev: Update offline mode usage instructions for sg

- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/integration/executors/config/repos.json
- enterprise/dev/ci/integration/executors/config/site-config.json
- enterprise/dev/ci/integration/executors/docker-compose.yml
- enterprise/dev/ci/integration/executors/run.sh
- enterprise/dev/ci/integration/executors/test.sh
- enterprise/dev/ci/integration/executors/tester/init.go
- enterprise/dev/ci/integration/executors/tester/main.go
- enterprise/dev/ci/integration/executors/tester/testinfra.go
- enterprise/dev/ci/internal/ci/operations.go
- enterprise/dev/ci/internal/ci/pipeline.go
- enterprise/internal/batches/store/batch_spec_execution_cache_entry.go
- enterprise/internal/batches/types/batch_spec_execution_cache_entry.go
- internal/gqltestutil/batch_specs.go
- internal/gqltestutil/repository.go
- lib/api/version_check.go
Ran locally and passed with the latest change.
> Reinstate executors e2e

- cmd/frontend/internal/httpapi/httpapi.go
- cmd/frontend/internal/httpapi/repo_shield.go
> httpapi: Remove unused param

- cmd/frontend/internal/cli/serve_cmd.go
- enterprise/cmd/frontend/internal/authz/init.go
- enterprise/cmd/frontend/internal/licensing/init/init.go
- enterprise/internal/authz/authz.go
- enterprise/internal/licensing/user_count.go
I had a few minutes of down time, so I removed some log15
CI.
> Remove some uses of log15

- enterprise/cmd/executor/internal/command/firecracker.go
Files in /tmp are not surviving the boot of the VM so they're gone by the time we run docker. This fixes it.
Tested on dogfood cluster.
> Make private container registries work in firecracker

- dev/gqltest/sub_repo_permissions_test.go
- internal/gqltestutil/git.go
Test plan:
New GraphQL test added.
Closes https://github.com/sourcegraph/sourcegraph/issues/39593
Int test build running in a [neighbour branch](https://github.com/sourcegraph/sourcegraph/tree/backend-integration/ao/symbols-sub-repo-perms-test): https://buildkite.com/sourcegraph/sourcegraph/builds/189770
> frontend: add a GraphQL test for sub-repo permissions for indexed symbols searches.

- dev/gqltest/sub_repo_permissions_test.go
Test plan:
gql test should not fail anymore.
> gqltest: make the error during waiting for repo to be cloned a reason to skip the test.

- dev/release/release-config.jsonc
Finalize https://github.com/sourcegraph/sourcegraph/issues/45566
n/a
- [Web](https://sg-web-dax-finish-release.onrender.com/search)
> update release config for 4.4.0

- enterprise/internal/insights/resolvers/insight_view_resolvers.go
Uncomment the repo query validation now that it's available to create/edit mutations
request
```graphql
mutation CreateSearchBasedInsight($input: LineChartSearchInsightInput!) {
createLineChartSearchInsight(input: $input) {
view {
id
}
}
}
```
bad input
```json
{
"input": {
"options": {
"title": "title"
},
"dataSeries": {
"query": "lang:go",
"options": {
"label": "insights",
"lineColor": "blue"
},
"repositoryScope": {
"repositories": [],
"repositoryCriteria": "lang:go bad query"
},
"timeScope": {
"stepInterval": {
"unit": "MONTH",
"value": 2
}
}
}
}
}
```
reponse
```json
{
"errors": [
{
"message": "the query cannot be used for scoping because it contains a pattern: `bad query`.",
"path": [
"createLineChartSearchInsight"
]
}
],
"data": null
}
```
good repo input
```json
{
"input": { …
```
> insights: strat scoped insights validation add repo query check

- client/web/src/site-admin/sidebaritems.ts
close https://github.com/sourcegraph/sourcegraph/issues/20249, https://github.com/sourcegraph/sourcegraph/issues/40852
related: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/889
INC-164
the menu item is shown all the time
- [Web](/search)
> feat: enable debug dashboard everywhere

- cmd/frontend/backend/user_emails.go
- internal/database/sub_repo_perms_store.go
> user_emails: Add comment and tweak casing

- doc/cloud/index.md
> **Warning** Merge after https://github.com/sourcegraph/handbook/pull/5832
n/a
---
Closes https://github.com/sourcegraph/customer/issues/1543
> doc(cloud): add description for Sourcegraph management access

- doc/admin/external_service/gitlab.md
> Updated gitlab code host configuration

- cmd/gitserver/server/vcs_syncer_perforce.go
Ran into this with @burmudar while looking at the code. It's easy for this to drift apart.
> p4-fusion: remove duplicated command building

- client/web/src/stores/experimentalFeatures.ts
- schema/schema.go
- schema/settings.schema.json
Preparation for https://github.com/sourcegraph/sourcegraph/pull/45687
- Make sure that CI is green
> Code Insights: Add new code insight repo UI experimental feature flag

- doc/admin/workers.md
- doc/dev/background-information/workers.md
> docs: update worker jobs information for code insights

- internal/metrics/operation.go
Some metrics are used by multiple services; in particular, worker and precise-code-intel-worker share a lot of metrics.
In the upcoming single-program distribution method, both of these services run in the same Go process. This means that their metrics registrations conflict and result in a panic. This change makes it so it does not panic and the metrics registrations are reused by both.
Automated tests cover it.
> do not panic on duplicate metrics collector registrations

- cmd/frontend/graphqlbackend/repository_git_refs.go
> remove unused field

- CODENOTIFY
> remove old CODENOTIFY file

- internal/oobmigration/oobmigrations.yaml
closes #45277 
local app startup ✅
> insights: mark end of recording times oob migration

- enterprise/internal/rockskip/server.go
Test plan:
Existing CI.
Part of https://github.com/sourcegraph/sourcegraph/issues/28532
> codeintel: use internal actor for rockskip.

- doc/admin/updates/pure_docker.md
Part of https://github.com/sourcegraph/sourcegraph/issues/45566
n/a
> Add missing pure-docker upgrade notes for 4.3

- doc/dev/background-information/insights/code_insights_pings.md
> Fix PR typo

- client/branded/.bazelignore
- client/browser/.bazelignore
- client/jetbrains/.bazelignore
- client/search-ui/.bazelignore
- client/search/.bazelignore
- client/shared/.bazelignore
- client/vscode/.bazelignore
- client/web/.bazelignore
We don't want bazel consuming any of these files built by the current build system. Any generated files will be generated by bazel.
manual bazel build
- [Web](https://sg-web-bazel-ignore-generated.onrender.com/search)
> bazel: ignore files generated into src

- doc/dev/background-information/web/graphql.md
> fix small spelling mistake

- docker-images/alpine-3.14/Dockerfile
> Bump up curl dependency

- .github/workflows/label-notify.yml
Workflow file, reviewed manually.
> Removing myself from label notifications

- doc/code_insights/explanations/viewing_code_insights.md
Add default visibility to the docs to clarify. 
Reviewing manually.
> insights: specify default visibility on creation

- client/jetbrains/BUILD.bazel
- client/search/BUILD.bazel
- client/shared/BUILD.bazel
- client/shared/dev/generate_graphql_operations.bzl
- client/web/BUILD.bazel
CI
- [Web](https://sg-web-bazel-rule-outs.onrender.com/search)
> bazel: rename generate_graphql_operations(output) to out

- enterprise/internal/codeintel/ranking/internal/background/indexer.go
Test plan:
CI.
part of https://github.com/sourcegraph/sourcegraph/issues/28532
> codeintel: use internal actor for gitserver calls.

- .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
- WORKSPACE
- pnpm-lock.yaml
Adds the new client package to the root Bazel `WORKSPACE`
`bazel build ...`
> bazel: add client/testing to workspace

- .github/teams.yml
- .github/workflows/label-notify.yml
> chore: update GitHub information for IAM and Repo Management teams.

- dev/scaletesting/codehostcopy/gitlab.go
- dev/scaletesting/codehostcopy/runner.go
1. Break out of the retry loop when a repo push terminates successfully
2. Check for server errors when creating repos on GitLab and retry a few times
None
> scaletesting: codehostcopy: retryable improvements

- go.mod
- go.sum
- schema/gen.sh
- schema/schema.go
Includes a minor change to the generated code (`interface{} -> any`).
Generated code diff only. Just check CI.
> update github.com/sourcegraph/go-jsonschema dep

- cmd/frontend/graphqlbackend/external_services.go
Follow up to #45986
Log change only.
> graphqlbackend: Fix log for repo exclusion

- go.mod
- go.sum
Only changes generated code. No test plan needed.
> update go-jsonschema dep

- dev/sg/internal/usershell/usershell.go
Port of #43302 (it's so old, build is faling with some unrelated issue in CI) 
Already tested and approved, follow-up to a PR from an external contributor I forgot to merge.
> fix(sg): Added ZDOTDIR to usershell guess

- CHANGELOG.md
> CHANGELOG: Add note about new test code host connection button 🎉

- doc/notebooks/blocks.md
Note that the block search will not inherit global or user setting defaults 
Doc
> Update block.md with note on default patterntype

- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/operations.go
Reverts sourcegraph/sourcegraph#46040 due to build failures ([example](https://buildkite.com/sourcegraph/sourcegraph/builds/191283#018574ad-7e0d-41e3-a073-76d543243b34)). 
cc @jhchabran 
N/A
> Revert "Remove the custom built gitserver using Microsoft fork of git"

- cmd/frontend/graphqlbackend/external_services.go
- cmd/frontend/graphqlbackend/external_services_test.go
Test plan:
Tests updated.
Part of https://github.com/sourcegraph/sourcegraph/issues/40504
> graphqlbackend: fix name of repo being added to code host config exclusion.

- client/web/src/repo/settings/RepoSettingsOptionsPage.tsx
- client/web/src/repo/settings/backend.ts
- client/web/src/repo/settings/components/ExternalServiceEntry.module.scss
- client/web/src/repo/settings/components/ExternalServiceEntry.tsx
Test plan:
Local sg run.
Depends on https://github.com/sourcegraph/sourcegraph/pull/46041
https://user-images.githubusercontent.com/94846361/210265621-9c78cb1b-d826-42c7-843d-a5d8290200f0.mov
- [Web](https://sg-web-ao-ui-add-exclude-repo-button.onrender.com/search)
> web: add exclude repo button.

- monitoring/monitoring/dashboards.go
- monitoring/monitoring/generator.go
- monitoring/monitoring/generator_test.go
- monitoring/monitoring/internal/grafana/uid.go
- monitoring/monitoring/monitoring.go
Adds improved up-front UID validation so we can get feedback faster about common invalid UIDs, and tests emulated Cloud use cases.
Unit tests
> monitoring: add more robust UID validation

- cmd/searcher/internal/search/search_structural.go
log.NamedError returns an error field. It does not actually generate a log message. This converts incorrect uses of log.NamedError to logger.Error calls.
Stacked on #46119
Manually tested that we generate logs for these. Will add unit tests for errors once we propagate errors nicely.
> Comby: use logger.Error instead of log.NamedError

- enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
Improvements to the SCIP migrator prior to its registration in #45106. This PR introduces configurable concurrency to the SCIP migrator. See https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/17560 for a related change we'll run for sourcegraph.com's migration.
> oobmigration: Run SCIP migrator concurrently

- enterprise/internal/oobmigration/migrations/codeintel/scip_migrator.go
Improvements to the SCIP migrator prior to its registration in https://github.com/sourcegraph/sourcegraph/pull/45106. This PR hoists scanning function factory calls into a common area so that we're not creating a bunch of short-lived functions.
> oobmigration: Hoist scanning functions in SCIP migrator

- cmd/frontend/graphqlbackend/external_services_test.go
Follow-up to @mrnugget's [comment](https://github.com/sourcegraph/sourcegraph/pull/45986#discussion_r1060027482) which (GitHub, and then) I lost
Test plan:
CI.
> chore: use mock history instead of custom variables.

- client/web/src/integration/codemirror-blob-view.test.ts
CI.
Flaked here https://buildkite.com/sourcegraph/sourcegraph/builds/191808#018581ea-9651-4f12-bead-dcd00bfd3d49
- [Web](https://sg-web-ao-disable-flaky-test.onrender.com/search)
> chore: disable flaky test

- dev/release/release-config.jsonc
https://github.com/sourcegraph/sourcegraph/issues/46134
CI
- [Web](https://sg-web-ggilmore-patch-3.onrender.com/search)
> Update release-config.jsonc for 4.3.1 patch release

- client/web/src/featureFlags/featureFlags.ts
Feature flag addition. Not much to test :) 
- [Web](https://sg-web-bo-create-feature-flag-for-rbac.onrender.com/search)
> add feature flag for rbac

- CHANGELOG.md
> Update CHANGELOG.md for 4.3.1 release

- doc/admin/updates/pure_docker.md
Part of https://github.com/sourcegraph/sourcegraph/issues/46161
CI
> docs: update pure_docker.md for 4.3.1 patch release

- enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore_documents.go
- enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore_documents_test.go
This should fix main.
Unit tests pass now
> codeintel: Fix test

- cmd/frontend/internal/app/updatecheck/handler.go
- doc/admin/deploy/docker-compose/aws.md
- doc/admin/deploy/docker-compose/azure.md
- doc/admin/deploy/docker-compose/digitalocean.md
- doc/admin/deploy/docker-compose/google_cloud.md
- doc/admin/deploy/docker-compose/index.md
- doc/admin/deploy/docker-single-container/aws.md
- doc/admin/deploy/docker-single-container/digitalocean.md
- doc/admin/deploy/docker-single-container/google_cloud.md
- doc/admin/deploy/docker-single-container/index.md
- doc/admin/deploy/kubernetes/configure.md
- doc/admin/deploy/kubernetes/helm.md
- doc/admin/deploy/machine-images/gce.md
- doc/admin/external_services/postgres.md
- doc/admin/external_services/redis.md
- doc/admin/http_https_configuration.md
- doc/admin/ssl_https_self_signed_cert_nginx.md
- doc/admin/updates/docker_compose.md
- doc/admin/updates/kubernetes.md
- doc/admin/updates/pure_docker.md
- doc/admin/updates/server.md
This pull request is part of the Sourcegraph 4.3.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.3.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/46161)
cc @ggilmore
> release: sourcegraph@4.3.1

- enterprise/internal/codeintel/uploads/internal/store/store_uploads.go
- enterprise/internal/codeintel/uploads/internal/store/store_uploads_test.go
We were incorrectly passing a raw pointer instead of wrapping it in a something that serializes nulls correctly.
> codeintel: Fix pointer <> nullable column issue

- lib/codeintel/upload/indexer_name.go
Modifies function to infer name and version from index whether it is SCIP or LSIF
LSIF unit tests continue to pass.
> [language-platform] infer name and version from scip index

- client/web/src/enterprise/insights/pages/insights/creation/InsightCreationPage.tsx
- client/web/src/enterprise/insights/pages/insights/creation/capture-group/CaptureGroupCreationPage.story.tsx
- client/web/src/enterprise/insights/pages/insights/creation/capture-group/CaptureGroupCreationPage.tsx
- client/web/src/enterprise/insights/pages/insights/creation/compute/ComputeInsightCreationPage.story.tsx
- client/web/src/enterprise/insights/pages/insights/creation/compute/ComputeInsightCreationPage.tsx
- client/web/src/enterprise/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.story.tsx
- client/web/src/enterprise/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.tsx
- client/web/src/enterprise/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.story.tsx
- client/web/src/enterprise/insights/pages/insights/creation/search-insight/SearchInsightCreationPage.tsx
- client/web/src/enterprise/insights/pages/insights/edit-insight/EditInsightPage.tsx
Prior to this PR all code insights creation UI pages had chaotic headers text with no structure, in this PR we add link breadcrumbs pattern for the insight creation UI pages
- Visit all code insight creation UI pages (track changes, detect and track, language insight)
- Check that all links in the page header work properly 
- [Web](https://sg-web-vk-improve-insight-creation.onrender.com/search)
> Code Insights: Fix code insights creation UI pages headers

- client/web/src/enterprise/insights/CodeInsightsAppRouter.tsx
- client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
- client/web/src/enterprise/insights/components/insights-view-grid/components/insight-context-menu/InsightContextMenu.tsx
- client/web/src/enterprise/insights/components/insights-view-grid/components/lang-stats-insight-card/LangStatsInsightCard.tsx
Fixes https://github.com/sourcegraph/sourcegraph/issues/45225
- Open code insight dashboard page (custom and all insight tabs)
- Open independent code insight page (click on the code insight card title)
- Open all code insight creation pages
- Make sure that all pages above are reachable 
- [Web](https://sg-web-vk-improve-insight-routes.onrender.com/search)
> Code Insights: Adjust insight routes

- doc/admin/validation.md
relates to: https://github.com/sourcegraph/src-cli/pull/912
N/A
> update use of validation script

- cmd/frontend/graphqlbackend/org_test.go
Tiny thing I bumped into while on other branch.
- This is the test
> graphqlbackend: remove duplicate import in test

- enterprise/internal/codeintel/shared/types/indexers.go
N/A there really isnt anything to do here besides OBSERVE
> codeintel: add scip-ruby to indexers list for graphql resolver

- internal/extsvc/github/common.go
This also fixes a panic if someone puts in a bad value for GITHUB_BASE_URL. If that happens the logs will be spammed with the parse error like before, but won't be followed by a panic.
Test Plan: go test and running single binary with an empty GITHUB_BASE_URL.
> extsvc: allow disabling github-proxy via empty GITHUB_BASE_URL

- client/wildcard/src/components/Card/Card.module.scss
Follow-up from this comment: https://github.com/sourcegraph/sourcegraph/pull/46274/files/dcf8246c42256f1235e07d724e6a5122061f415e#r1066067297
This just adds a comment, no code changes were made.
- [Web](https://sg-web-ps-explain-important-usage.onrender.com/search)
> Explain !important usage in Card

- client/web/src/repo/tree/TreePageContent.tsx
Fix https://github.com/sourcegraph/sourcegraph/issues/46308
Verified locally (appearance-only change)
- [Web](https://sg-web-bl-fix-spacing.onrender.com/search)
> fix spacing

- client/web/src/components/externalServices/AddExternalServicePage.tsx
- client/web/src/components/externalServices/AddExternalServicesPage.tsx
This will make the look of this page more uniform with other site admin pages, because all of them use Container component.
Test plan:
Local sg run and visual tests.
https://user-images.githubusercontent.com/94846361/212006704-8bee0eb5-cf0d-4e5e-a31d-58f3e49ad8cc.mp4
https://user-images.githubusercontent.com/94846361/212006765-50b74e3e-2286-4e87-9ece-ea74d947c108.mp4
- [Web](https://sg-web-ao-ui-add-container-to-add-ext.onrender.com/search)
> web: add Container component to AddExternalServicePage.

- client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
- client/web/src/site-admin/backend.ts
- cmd/frontend/graphqlbackend/outbound_requests.go
- cmd/frontend/graphqlbackend/schema.graphql
- internal/goroutine/background.go
- internal/types/types.go
- Extracted my unrelated changes from https://github.com/sourcegraph/sourcegraph/pull/44901
These are all trivial.
If CI is happy then I'm confident.
> Outbound requests and typo fixes

- doc/dev/background-information/build_p4_fusion.md
- doc/dev/background-information/index.md
- doc/dev/index.md
Instructions on how to build `p4-fusion` locally.
Closes https://github.com/sourcegraph/sourcegraph/issues/44762
Built locally
> doc: Instruction for building p4-fusion locally.

- doc/admin/deploy_executors.md
Closes #46224.
This information was an ask from the Feedback channel. I gathered this information by checking out how we configure GCP and AWS. I also tried to surface any additional information we have buried.
No tests needed. Just docs
> executors: Add information about resource recommendations

- doc/code_insights/quickstart.md
I was passing through and the insight quickstart was a bit too outdated so just took 5 minutes to update it
> insights: docs: update quickstart

- client/web/src/site-admin/SiteAdminWebhookPage.tsx
- client/web/src/site-admin/WebhookCreateUpdatePage.tsx
Small tweaks to make Webhook pages more uniform with new code host pages.
Test plan:
Local sg run and manual checks.
- [Web](https://sg-web-ao-ui-webhooks-page-tweak.onrender.com/search)
> web: add icons to buttons on SiteAdminWebhookPage, move buttons closer to each other on WebhookCreateUpdatePage.

- CHANGELOG.md
- doc/admin/how-to/clear_codeintel_data.md
- doc/admin/how-to/index.md
- doc/admin/how-to/lsif_scip_migration.md
- doc/admin/updates/docker_compose.md
- doc/admin/updates/kubernetes.md
- doc/admin/updates/pure_docker.md
- doc/admin/updates/server.md
Update changelog for LSIF -> SCIP migration.
> codeintel: Add SCIP notice to changelog and upgrade docs

- client/branded/src/components/panel/views/__snapshots__/HierarchicalLocationsView.test.tsx.snap
- client/shared/src/actions/__snapshots__/ActionItem.test.tsx.snap
- client/shared/src/hover/__snapshots__/HoverOverlay.test.tsx.snap
- client/web/src/auth/SignInSignUpCommon.tsx
- client/web/src/components/__snapshots__/LoaderButton.test.tsx.snap
- client/web/src/components/externalServices/__snapshots__/ExternalServiceForm.test.tsx.snap
- client/web/src/enterprise/insights/components/form/hooks/useField.ts
- client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-input/DrillDownInput.tsx
- client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/search-context/DrillDownSearchContextFilter.tsx
- client/wildcard/src/components/Combobox/Combobox.module.scss
- client/wildcard/src/components/Combobox/Combobox.tsx
- client/wildcard/src/components/Combobox/MultiCombobox.module.scss
- client/wildcard/src/components/Combobox/MultiCombobox.story.tsx
- client/wildcard/src/components/Combobox/MultiCombobox.tsx
- client/wildcard/src/components/Combobox/MultiComboboxStory.module.scss
- client/wildcard/src/components/Combobox/index.ts
- client/wildcard/src/components/Form/Input/Input.test.tsx
- client/wildcard/src/components/Form/Input/Input.tsx
- client/wildcard/src/components/Form/Input/__snapshots__/Input.test.tsx.snap
- client/wildcard/src/components/Form/LoaderInput/__snapshots__/LoaderInput.test.tsx.snap
- client/wildcard/src/components/LoadingSpinner/LoadingSpinner.tsx
- client/wildcard/src/components/Popover/components/floating-panel/FloatingPanel.tsx
- client/wildcard/src/components/Popover/components/popover-content/PopoverContent.tsx
- client/wildcard/src/components/Popover/tether/index.ts
- client/wildcard/src/components/Popover/tether/services/tether-registry.ts
- client/wildcard/src/components/index.ts
Preparation for https://github.com/sourcegraph/sourcegraph/issues/46291
This PR adds a first draft implementation of MultiCombobox UI in our wildcard components. Probably more changes will be required when we start using this component (but those changes will be addressed in follow up PRs)
- Check the storybook story with MultiCombobox
- [Web](https://sg-web-vk-add-multi-combobox-ui.onrender.com/search)
> Wildcard: Add MultiCombobox UI 

- dev/sg/dependencies/shared.go
Add `pnpm` description to `sg`.
CI and `sg setup`.
> sg: add `pnpm` description

- doc/admin/deploy/machine-images/aws-oneclick.md
> upgrades deadlink

- doc/admin/auth/index.md
> doc: missing comma breaks highlighting

- internal/src-cli/CODENOTIFY
- internal/src-cli/consts.go
Update src_cli constant. Branch cut is tomorrow so ensuring release chores are completed.
> batches: update src_cli constant

- client/web/src/enterprise/batches/CODENOTIFY
- client/web/src/enterprise/batches/list/BatchChangesListIntro.tsx
Hiding the Changelog alert for this release.
- [Web](https://sg-web-bo-batches-changelog-4-4.onrender.com/search)
> 4.4 changelog update for Batch Changes

- CHANGELOG.md
add changelog entry for #46480
doc
> add changelog entry for #46480

- CHANGELOG.md
See title
None, changelog entry update
> update changelog for the repo corruption features

- internal/authz/permssync/permssync.go
- internal/authz/permssync/permssync_test.go
Found a bug which I missed during code review :(
Added a couple of simple tests to catch anything similar.
Test plan:
Unit test added to cover previously untested code.
> permissions-center: fix a bug scheduling User syncs instead of Repo syncs.

- doc/admin/external_service/index.md
Just a doc update
Not applicable
> [docs] Change Bitbucket Cloud code host tier check marks

- client/web/package.json
- Check that you can run `pnpm storybook:web` and it actually opens the browser with compiled storybook UI 
- [Web](https://sg-web-vk-fix-web-storybook-script.onrender.com/search)
> Fix web storybook pnpm script

- enterprise/internal/insights/background/background.go
the retention enqueuer background job was using the main-db backed worker store, but the `insights_data_retention_jobs` table lives in the codeinsights-db
This cannot be tested locally as both databases live under the same name, which is a different setup than on our environments. However I am confident this will fix the issue.
> insights: fix: use codeinsights-db backed worker base store for retention enqueuer

- internal/database/conf.go
- internal/database/conf_test.go
- internal/database/helpers.go
- internal/database/mocks_temp.go
Part of #46031.
1. Updated tests
1. Builds should pass
> internal/database: Use PaginationArgs in ListSiteConfigs 

- internal/rcache/CODENOTIFY
- internal/redispool/CODENOTIFY
> internal: add keegan to CODENOTIFY for redis packages

- CHANGELOG.md
> changelog: cut sourcegraph@4.4.0

- internal/database/migration/shared/data/cmd/generator/consts.go
- internal/database/migration/shared/data/stitched-migration-graph.json
> update maxVersionString constant for migration

- internal/extsvc/azuredevops/client.go
- internal/extsvc/azuredevops/client_test.go
- internal/extsvc/azuredevops/testdata/golden/ListProjects.json
- internal/extsvc/azuredevops/testdata/vcr/ListRepositoriesByProjectOrOrg.yaml
- internal/extsvc/gerrit/client_test.go
Addresses: https://github.com/sourcegraph/sourcegraph/issues/46263
Implement the client for ADO.
Uses the following ADO API for fetching repos by project/org: https://learn.microsoft.com/en-us/rest/api/azure/devops/git/repositories/list?view=azure-devops-rest-7.0&tabs=HTTP
Unit test
> Implement ADO client

- internal/rcache/fifo_list.go
I can see things we can improve here now that this exists, but this
feels quite nice.
plz-review-url: https://plz.review/review/17427
> rcache: use KeyValue abstraction in FIFOList

- internal/database/mocks_temp.go
- internal/database/permission_sync_jobs.go
- internal/database/permission_sync_jobs_test.go
- internal/database/schema.json
- internal/database/schema.md
- migrations/frontend/1674041632_add_constraints_to_permission_sync_jobs_table/down.sql
- migrations/frontend/1674041632_add_constraints_to_permission_sync_jobs_table/metadata.yaml
- migrations/frontend/1674041632_add_constraints_to_permission_sync_jobs_table/up.sql
- migrations/frontend/squashed.sql
Test plan:
1) sg migration up -> down -> up.
2) Database tests added.
Closes https://github.com/sourcegraph/sourcegraph/issues/46321
> permissions-center: implement perms sync deduplication logic.

- doc/admin/how-to/blobstore_update_notes.md
also adds not about safely removing minio env variables.
Manual testing
> Add note about NO_PROXY

- internal/database/permission_sync_jobs_test.go
Small follow-up to [this comment](https://github.com/sourcegraph/sourcegraph/pull/46656#discussion_r1081464832).
Also make grammar consistent in test comments!
Test plan:
Tests should still pass.
> permissions-center: make tests fail-fast by changing `assert` to `require`.

- internal/database/CODENOTIFY
> update permission notify list

- client/vscode/README.md
- doc/getting-started/index.md
Removes deprecated learn links
- Test on related changed docs pages
> Remove deprecated learn links

- doc/dev/background-information/basestore.md
Wanted to do this for a long time now.
- N/A
> docs: document basestore scan helpers

- doc/admin/updates/pure_docker.md
add upgrade notes for pure docker
N/A
> add upgrade notes for pure docker

- cmd/frontend/internal/app/updatecheck/handler.go
- doc/admin/deploy/docker-compose/aws.md
- doc/admin/deploy/docker-compose/azure.md
- doc/admin/deploy/docker-compose/digitalocean.md
- doc/admin/deploy/docker-compose/google_cloud.md
- doc/admin/deploy/docker-compose/index.md
- doc/admin/deploy/docker-single-container/aws.md
- doc/admin/deploy/docker-single-container/digitalocean.md
- doc/admin/deploy/docker-single-container/google_cloud.md
- doc/admin/deploy/docker-single-container/index.md
- doc/admin/deploy/kubernetes/configure.md
- doc/admin/deploy/kubernetes/helm.md
- doc/admin/deploy/machine-images/gce.md
- doc/admin/external_services/postgres.md
- doc/admin/external_services/redis.md
- doc/admin/http_https_configuration.md
- doc/admin/ssl_https_self_signed_cert_nginx.md
- doc/admin/updates/docker_compose.md
- doc/admin/updates/kubernetes.md
- doc/admin/updates/pure_docker.md
- doc/admin/updates/server.md
- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/pipeline.go
This pull request is part of the Sourcegraph 4.4.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/45780)
> release: sourcegraph@4.4.0

- internal/database/mocks_temp.go
- internal/database/permission_sync_jobs.go
- internal/database/permission_sync_jobs_test.go
- internal/database/schema.json
- internal/database/schema.md
- migrations/frontend/1674455760_add_cancellation_reason_to_permission_sync_jobs_table/down.sql
- migrations/frontend/1674455760_add_cancellation_reason_to_permission_sync_jobs_table/metadata.yaml
- migrations/frontend/1674455760_add_cancellation_reason_to_permission_sync_jobs_table/up.sql
- migrations/frontend/squashed.sql
Test plan:
1) Sg migration up -> down -> up.
2) Unit tests updated.
Closes https://github.com/sourcegraph/sourcegraph/issues/46760
> permissions-center: add `cancellation_reason` column.

- internal/uploadhandler/upload_handler_multipart.go
Removing the transaction here because if we try to mark the record as failed we'll immediately rollback. We need to actually return a 500 while still committing the record state change.
> codeintel: Remove useless txn from upload handler

- enterprise/internal/codeintel/uploads/internal/lsifstore/scip_write.go
There (apparently) can be documents with duplicate hashes. In order to not hit the "unexpected number of document records inserted/retrieved" condition, we have to ensure the number of document identifiers we get back is the same as the number of *unique* document hashes, not the original number of documents.
Validated by hand.
> codeintel: Count inserted SCIP documents correctly

- enterprise/cmd/frontend/internal/auth/githuboauth/session.go
- enterprise/cmd/frontend/internal/auth/githuboauth/session_test.go
fixes https://github.com/sourcegraph/sourcegraph/issues/46802
- https://github.com/sourcegraph/sourcegraph/issues/46802
Previously, when github oauth provider had `allowSignup: true` configured, we returned the first error. However the code is written in a way, that it first tries to match existing user accounts to a list of verified email addresses from github. It only tries the signup flow when there is no match.
If for any reason the signup flow fails, e.g. a license is breached, the user got the first error saying there is no match on the email addresss, which is bogus.
Fixing this problem by returning the last error instead. Also added a regression unit test, so that this does not happen in the future.
```
Could not find existing user matching any of the verified emails: …
```
> Fix error handling when github oauth fails to create a user with signups allowed

- doc/admin/deploy/kubernetes/index.md
> grammar mistake fix

- client/web/src/components/externalServices/externalServices.tsx
- internal/extsvc/azuredevops/client.go
- internal/extsvc/azuredevops/testdata/golden/ListProjects.json
- internal/extsvc/azuredevops/testdata/vcr/ListRepositoriesByProjectOrOrg.yaml
- internal/repos/azuredevops.go
- internal/repos/azuredevops_test.go
- internal/repos/testdata/sources/AZUREDEVOPS/TestAzureDevOpsSource_ListRepos
- internal/repos/testdata/sources/TestAzureDevOpsSource_ListRepos.yaml
- schema/azuredevops.schema.json
- schema/schema.go
Closes https://github.com/sourcegraph/sourcegraph/issues/46267
Added the ability to exclude repo by name and pattern.
Added to unit test and verified manually.
> Implement exclude repo by name and pattern for ADO

- enterprise/cmd/frontend/worker/auth/perms_syncer_cleaner.go
- enterprise/cmd/frontend/worker/auth/perms_syncer_cleaner_test.go
- enterprise/cmd/repo-updater/internal/authz/perms_syncer_worker.go
- enterprise/cmd/repo-updater/internal/authz/perms_syncer_worker_test.go
- enterprise/cmd/repo-updater/shared/shared.go
- enterprise/cmd/worker/shared/shared.go
- internal/database/permission_sync_jobs_test.go
- schema/schema.go
- schema/site.schema.json
Test plan:
Local sg run and tests that only finished jobs are removed and site config setting is used. Unit tests added.
Closes https://github.com/sourcegraph/sourcegraph/issues/46322
> permissions-center: implement permissions sync jobs cleaner.

- dev/release/release-config.jsonc
Following the instructions here to get this out: https://github.com/sourcegraph/sourcegraph/issues/46923
- N/A
- [Web](https://sg-web-mrn-release-config-4-4-1.onrender.com/search)
> Update release config for 4.4.1

- CHANGELOG.md
This adds the changes in 4.4.1 (https://github.com/sourcegraph/sourcegraph/issues/46931) to the CHANGELOG
- NA
> Add 4.4.1 to CHANGELOG.md

- cmd/blobstore/internal/blobstore/blobstore.go
- cmd/frontend/graphqlbackend/slow_requests_tracer.go
- cmd/gitserver/server/vcs_syncer_ruby_packages.go
- dev/sg/internal/bk/bk.go
- enterprise/internal/codeintel/codenav/init.go
- enterprise/internal/codeintel/policies/init.go
- internal/authz/sub_repo_perms.go
- internal/codeintel/dependencies/init.go
- internal/extsvc/gitlab/client.go
- internal/oauthutil/oauth2.go
- internal/repos/syncer.go
- internal/search/repos/repos.go
- lib/batches/changeset_specs.go
- lib/codeintel/lsif/scip/document.go
> chore: remove some dead code found by linter.

- enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
- enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
- internal/auth/site_admin.go
Test plan:
Updated unit tests.
> permissions-center: fix triggeredByUserID for scheduled user permissions sync.

- cmd/frontend/internal/app/updatecheck/handler.go
- doc/admin/deploy/docker-compose/aws.md
- doc/admin/deploy/docker-compose/azure.md
- doc/admin/deploy/docker-compose/digitalocean.md
- doc/admin/deploy/docker-compose/google_cloud.md
- doc/admin/deploy/docker-compose/index.md
- doc/admin/deploy/docker-single-container/aws.md
- doc/admin/deploy/docker-single-container/digitalocean.md
- doc/admin/deploy/docker-single-container/google_cloud.md
- doc/admin/deploy/docker-single-container/index.md
- doc/admin/deploy/kubernetes/configure.md
- doc/admin/deploy/kubernetes/helm.md
- doc/admin/deploy/machine-images/gce.md
- doc/admin/external_services/postgres.md
- doc/admin/external_services/redis.md
- doc/admin/http_https_configuration.md
- doc/admin/ssl_https_self_signed_cert_nginx.md
- doc/admin/updates/docker_compose.md
- doc/admin/updates/kubernetes.md
- doc/admin/updates/pure_docker.md
- doc/admin/updates/server.md
This pull request is part of the Sourcegraph 4.4.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/46931)
cc @mrnugget
> release: sourcegraph@4.4.1

- enterprise/cmd/repo-updater/internal/authz/CODENOTIFY
- internal/database/CODENOTIFY
> chore: update Codenotify subscriptions for Joe

- service-catalog.yaml
> service-catalogue: fix gitserver entry

- client/web/src/site-admin/analytics/AnalyticsOverviewPage/index.tsx
Updated the link in In-Product Analytics based on [user feedback](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1674597163965429).
Only changed a link. Tested locally.
- [Web](https://sg-web-rpp-update-ipa-docs-link.onrender.com/search)
> Update the update link in IPA

- cmd/frontend/graphqlbackend/git_tree_entry.go
- cmd/frontend/graphqlbackend/repositories.go
- cmd/frontend/graphqlbackend/slow_requests_tracer.go
- cmd/frontend/internal/cli/config.go
- cmd/frontend/internal/cli/serve_cmd.go
- cmd/frontend/registry/api/extension_manifest.go
- cmd/frontend/registry/api/registry_graphql.go
- cmd/gitserver/server/vcs_syncer_jvm_packages.go
- cmd/searcher/internal/search/hybrid.go
- cmd/searcher/shared/shared.go
- dev/scaletesting/syntheticgithubdata/delete.go
- dev/scaletesting/syntheticgithubdata/state.go
- enterprise/cmd/frontend/internal/app/app.go
- enterprise/cmd/frontend/internal/auth/oauth/middleware.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/licenses_graphql.go
- enterprise/cmd/frontend/internal/registry/extension_graphql.go
- enterprise/cmd/repo-updater/internal/authz/metrics.go
- enterprise/internal/authz/syncjobs/records_store.go
- enterprise/internal/batches/sources/testing/fake.go
- enterprise/internal/codeintel/autoindexing/init.go
- enterprise/internal/codeintel/ranking/init.go
- enterprise/internal/codeintel/ranking/internal/store/observability.go
- enterprise/internal/codeintel/uploads/init.go
- enterprise/internal/insights/resolvers/insight_series_resolver.go
- enterprise/internal/insights/resolvers/insight_view_resolvers.go
- internal/database/webhooks.go
- internal/goroutine/periodic.go
- internal/own/codeowners/proto/find_owners.go
- internal/rcache/backwards.go
Removes all unused code as highlighted by `sg lint`
Unit tests and integration tests should still pass. My local `sg start` is still behaving as normal.
> Remove all unused code specified by linter warnings

- internal/database/basestore/store.go
- internal/database/database.go
This just moves the `WithTransact` logic down a level to the `basestore.Store` type. This allows us to use it on the store types rather than only on the `database.DB` type.
This is fully exercised by the tests added in #46796
> Database: move WithTransact logic to basestore

- doc/tutorials/index.md
Tested locally. Docs change only.
> Add tutorials page back

- doc/_resources/assets/docsite.css
Closes #46919
Don't ask me how this works but it works 🤷‍♀️
Verify visually
> docs: fix horizontal scrolling

- doc/dev/how-to/testing.md
Mention `sg run web-integration-build-prod` in docs.
N/a
> docs: update integration tests documentation

- lib/servicecatalog/CODENOTIFY
See https://github.com/sourcegraph/security-issues/issues/328#issuecomment-1406996126
n/a
> lib/servicecatalog: codenotify for cloud, security

- cmd/symbols/squirrel/lang_java.go
Fixes https://github.com/sourcegraph/sourcegraph/issues/46992
Fix in squirrel java where it was panicking when the path was not a subset of the root.
Validated by hand.
> [hotfix] squirrel fix for panic

- cmd/frontend/graphqlbackend/schema.graphql
- cmd/frontend/graphqlbackend/site_admin.go
- internal/database/mocks_temp.go
- internal/database/users.go
providing customers with an easier option for restoring user records after a deletion
manually tested by deleting a user in UI and restoring the user through graphql api
> create options to recover users

- cmd/frontend/backend/external_services.go
- cmd/frontend/backend/user_emails.go
- cmd/frontend/graphqlbackend/executors.go
- cmd/frontend/graphqlbackend/external_services_test.go
- cmd/frontend/graphqlbackend/user_emails_test.go
- cmd/frontend/internal/bg/update_permissions.go
- enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
- enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
- enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go
- enterprise/internal/database/mocks_temp.go
- internal/database/database.go
- internal/database/mocks_temp.go
- internal/database/webhook_logs_test.go
This PR replaces all uses of `(database.DB).Transact()` with the new `(database.DB).WithTransact()`. Each commit replaces one usage. 
Would recommend hiding whitespace for a more readable diff.
Unit tests. This should not change any behavior.
> Database: replace `DB.Transact()`/`DB.Done()` with `DB.WithTransact()`

- CHANGELOG.md
Tested locally 
- [Web](https://sg-web-mibali-bb-server-fix.onrender.com/search)
> CHANGELOG: Added note on bug fix for bitbucketserver repo description

- enterprise/cmd/frontend/worker/auth/perms_syncer_cleaner.go
- enterprise/cmd/frontend/worker/auth/perms_syncer_cleaner_test.go
> permissions-center: make `perms_syncer_cleaner` delete oldest jobs first.

- client/web/src/SourcegraphWebApp.tsx
Part of #33834 
- Relying on CI to be green as well
- [Web](https://sg-web-ps-root-level-switch.onrender.com/search)
> Migrate top-level <Switch/> in <SourcegraphWebApp/> to RR6

- doc/admin/observability/alerts.md
- doc/dev/background-information/sg/reference.md
Reverts some changes from https://github.com/sourcegraph/sourcegraph/pull/42367. I hope this fixes some errors in CI.
CI tests should pass
> Regenerate two md files

- internal/database/teams.go
Replaces uses of `(TeamStore).Transact()` with the new `(TeamStore).WithTransact()`. 
I recommend reviewing with hidden whitespace changes. 
Stacked on https://github.com/sourcegraph/sourcegraph/pull/47071
Unit tests.
> Database: convert TeamStore to use WithTransact

- internal/database/users.go
Followup from https://github.com/sourcegraph/sourcegraph/pull/46654
Unit tests.
> Database: use transaction during update

- CHANGELOG.md
> batches: add changelog for paginated log outputs

- doc/code_insights/explanations/current_limitations_of_code_insights.md
Perforce limitations weren't in the docs, surprisingly.
N/A
> update limitations for perforce

- client/web/src/org/OrgsArea.tsx
- client/web/src/org/area/OrgArea.tsx
- client/web/src/org/area/OrgHeader.tsx
- client/web/src/org/invitations/OrgInvitationPage.tsx
- client/web/src/org/new/NewOrganizationPage.tsx
Part of #33834 
This one did not spiral out of control thankfully. Lol
- CI
- [Web](https://sg-web-ps-migrate-orgs-area-switch.onrender.com/search)
> Migrate orgs area <Switch/> to RR6

- cmd/gitserver/server/CODENOTIFY
- cmd/repo-updater/CODENOTIFY
- internal/gitserver/CODENOTIFY
- internal/repos/CODENOTIFY
> chore: Remove myself from CODENOTIFY files

- dev/release/release-config.jsonc
Here we go again.
Request here: https://github.com/sourcegraph/sourcegraph/issues/47254
- NA
> Update release-config for 4.4.2 patch release

- CHANGELOG.md
See patch release here: https://github.com/sourcegraph/sourcegraph/issues/47256
NA
> Update CHANGELOG.md to add PR 47251 and add 4.4.2 release

- internal/database/users_test.go
unit test for recovering users 
1. Test reviving a user that does not exist
2. Test reviving a user that exists but hasn't been deleted
3. Test reviving a user that does exist and does not have additional resources deleted in the same timeframe
4. Test reviving a user that does exist and does have additional resources deleted in the same timeframe
Followup from https://github.com/sourcegraph/sourcegraph/pull/46654 
go test
> recover users unit tests

- client/web/src/enterprise/insights/CodeInsightsAppRouter.tsx
- Check that all tabs work properly on the code insight page
- [Web](https://sg-web-vk-fix-code-insights-routing.onrender.com/search)
> Fix typo in the code insights getting started page URL

- internal/database/schema.json
- internal/database/schema.md
- migrations/frontend/1675277218_add_lsif_uploads_uploaded_at_id/down.sql
- migrations/frontend/1675277218_add_lsif_uploads_uploaded_at_id/metadata.yaml
- migrations/frontend/1675277218_add_lsif_uploads_uploaded_at_id/up.sql
- migrations/frontend/1675277500_drop_lsif_uploads_uploaded_at/down.sql
- migrations/frontend/1675277500_drop_lsif_uploads_uploaded_at/metadata.yaml
- migrations/frontend/1675277500_drop_lsif_uploads_uploaded_at/up.sql
- migrations/frontend/1675277968_drop_lsif_indexes_queued_at/down.sql
- migrations/frontend/1675277968_drop_lsif_indexes_queued_at/metadata.yaml
- migrations/frontend/1675277968_drop_lsif_indexes_queued_at/up.sql
- migrations/frontend/squashed.sql
We should have these but don't 🤷 
Made one of these on sourcegraph.com already too check improvement.
> codeintel: Add useful indexes

- doc/dev/background-information/basestore.md
Forgot to document this one last time. It's super nice.
- N/A
> docs: document NewSliceScanner and how to use it

- internal/database/bitbucket_project_permissions.go
Saw this lint failure in builds.
Builds should pass.
> internal/database: Remove unused transact func

- cmd/frontend/graphqlbackend/graphqlbackend.go
- cmd/frontend/graphqlbackend/schema.graphql
- cmd/frontend/graphqlbackend/teams.go
- cmd/frontend/graphqlbackend/teams_test.go
This is used in src-cli.
Added a test.
> Add GraphQL endpoint to get a team by name

- internal/database/users.go
Included the Query for reviving Access Token deleted at the same time frame as the user deleted when reviving a deleted user.
Updated Query Syntax to PostgresSql Syntax because PostgreSQL doesn't use 'Inner JOIN' for Update queries.
Followup from https://github.com/sourcegraph/sourcegraph/pull/46654
sg start
add 5 access tokens for a user
Deleted 3 tokens first 
waited ... deleted User
Recovered Users
Only access tokens deleted at the same time as the user was recovered
> RecoverUsers: add missing query for access token

- enterprise/internal/insights/httpapi/export.go
closes #47311 
I added the check after the user auth check because my reasoning was that a "forbidden" status code made the most sense here but this is usually only returned if auth is possible.
Manually tested by generating a new license key as follows:
* Run `go run ./enterprise/internal/license/generate-license.go -private-key ../dev-private/enterprise/dev/test-license-generation-key.pem -tags=starter -users=10 -expires=8784h` in your sourcegraph folder
* Paste in the key in `dev-private` site config
* Start your sourcegraph instance (I don't think the type matters, mine was `sg start code-insights`
* Run your tests
Confirmed `403 Forbidden` status code and `invalid license for code insights` message
> insights: exporting is forbidden without valid code insights license

- cmd/frontend/graphqlbackend/permission_sync_jobs.go
- enterprise/cmd/frontend/internal/authz/resolvers/permission_sync_jobs.go
- enterprise/cmd/frontend/internal/authz/resolvers/permission_sync_jobs_test.go
- internal/database/mocks_temp.go
- internal/database/permission_sync_jobs.go
- internal/database/permission_sync_jobs_test.go
Test plan:
Tests added.
Closes https://github.com/sourcegraph/sourcegraph/issues/47301
> permissions-center: add basic permission sync jobs API.

- dev/gqltest/code_insights_test.go
- enterprise/cmd/worker/internal/batches/workers/batch_spec_workspace_creator_test.go
- enterprise/internal/batches/service/service_test.go
- enterprise/internal/batches/types/changeset_spec.go
Just build stuff. CI will find issues.
> Reduce amount of import from graphqlbackend from outside of cmd/frontend

- doc/admin/deploy/kubernetes/kustomize.md
> fix spelling mistake

- cmd/frontend/internal/highlight/language.go
- docker-images/syntax-highlighter/Cargo.lock
- docker-images/syntax-highlighter/crates/sg-syntax/Cargo.toml
- docker-images/syntax-highlighter/crates/sg-syntax/queries/scala/highlights.scm
- docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
- docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/files/plugins.scala
- docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/files/scala.scala
- docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__.__5billiondevices.scala.snap
- docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__.__5billiondevices.scala.snap
- docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__.__plugins.scala.snap
- docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__.__scala.scala.snap
- internal/gosyntect/gosyntect.go
- sg.config.yaml
> Highlighting: add tree-sitter highligher for Scala

- doc/admin/deploy/docker-compose/operations.md
[_Created by Sourcegraph batch change `sqs/fix-typos`._](https://sourcegraph.sourcegraph.com/users/sqs/batch-changes/fix-typos)
None needed - docs only
> Fix typo (sourecgraph -> sourcegraph)

- cmd/frontend/graphqlbackend/rbac.go
- cmd/frontend/graphqlbackend/rbac.graphql
- enterprise/cmd/frontend/internal/rbac/resolvers/apitest/types.go
- enterprise/cmd/frontend/internal/rbac/resolvers/permission.go
- enterprise/cmd/frontend/internal/rbac/resolvers/permission_test.go
- enterprise/cmd/frontend/internal/rbac/resolvers/role_test.go
- internal/types/types.go
* Manually tested
* Add unit tests
> rbac: add display name to permission fields

- schema/site.schema.json
change default value of experimental setting, leaving the setting just in case
Local deploy and checking retention procedure kicks in
> insights: enable data retention procedure by default

- internal/gitserver/proto/gitserver.pb.go
- internal/gitserver/proto/gitserver_grpc.pb.go
> gitserver: re-run sg generate buf

- cmd/frontend/graphqlbackend/CODENOTIFY
- doc/code_monitoring/CODENOTIFY
- enterprise/internal/compute/CODENOTIFY
- internal/extsvc/bitbucketcloud/CODENOTIFY
- internal/search/query/CODENOTIFY
Just a PR for removing people who've left from CODENOTIFY
manual review
> clean up CODENOTIFY sourcegrapher entries

- doc/admin/external_service/bitbucket_cloud.md
> Explained the term teams better

- doc/code_navigation/references/indexers.md
> docs: Update cross-repo for Rust & Ruby

- client/shared/src/codeintel/legacy-extensions/language-specs/languages.ts
- client/shared/src/languages.ts
- cmd/frontend/internal/highlight/language.go
- cmd/frontend/internal/highlight/syntect_language_map.go
- docker-images/syntax-highlighter/Cargo.lock
- docker-images/syntax-highlighter/crates/sg-syntax/Cargo.toml
- docker-images/syntax-highlighter/crates/sg-syntax/queries/xlsg/highlights.scm
- docker-images/syntax-highlighter/crates/sg-syntax/src/lib.rs
- docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
- internal/gosyntect/gosyntect.go
> Add xlsg support

- cmd/frontend/internal/app/ui/router.go
> Add setup wizard route to UI router

- dev/sg/linters/runner.go
> fix `sg lint` flag mention in CI help message

- cmd/frontend/backend/mocks_temp.go
- cmd/frontend/backend/repos.go
- cmd/frontend/backend/repos_test.go
It was never called outside of the backend package.
> backend: unexport Repo.Add

- internal/codeintel/dependencies/internal/store/store.go
- internal/codeintel/dependencies/internal/store/store_test.go
There was a bug in the SQL query where we were not sorting the package repo refs before performing ID pagination. This resulted in pagination windows becoming smaller than the limit amount in a technically undefined manner (based on however postgres decided to order things based on its mood), and entries never being surfaced entirely.
Ran the new query against production data, and updated existing unit test to stress pagination gone wrong
> packages: fix package ref listing missing order by for pagination

- enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
See https://github.com/sourcegraph/src-cli/pull/934.
Tested by hand. See test plan on linked PR.
> codeintel: Support SCIP detection for auto-indexing

- cmd/frontend/graphqlbackend/package_repos.go
Cursor pagination handling slipped through the cracks 😬 Schema was correct but somehow the backend wasnt
Ran locally, all OK 👍
> packages: fix packages pagination in graphql

- .eslintrc.js
- client/branded/src/search-ui/input/CodeMirrorQueryInput.tsx
- client/branded/src/search-ui/input/SearchBox.tsx
- client/branded/src/search-ui/input/SearchButton.tsx
- client/branded/src/search-ui/input/codemirror/completion.ts
- client/branded/src/search-ui/input/codemirror/index.ts
- client/jetbrains/webview/src/search/input/JetBrainsSearchBox.story.tsx
- client/web/src/codeintel/ReferencesPanel.tsx
- client/web/src/hooks/useScrollManager/useScrollManager.ts
- client/web/src/repo/blob/BlameColumn.tsx
- client/web/src/repo/blob/BlameDecoration.tsx
- client/web/src/repo/blob/BlobPage.tsx
- client/web/src/repo/blob/CodeMirrorBlob.tsx
- client/web/src/repo/blob/LegacyBlob.tsx
- client/web/src/repo/blob/codemirror/blame-decorations.tsx
- client/web/src/repo/blob/codemirror/hovercard.tsx
- client/web/src/repo/blob/codemirror/index.ts
- client/web/src/repo/blob/codemirror/navigate-to-any-line-on-click.ts
- client/web/src/repo/blob/codemirror/react-interop.tsx
- client/web/src/repo/blob/codemirror/search.tsx
- client/web/src/repo/blob/codemirror/token-selection/code-intel-tooltips.ts
- client/web/src/repo/blob/codemirror/token-selection/definition.ts
- client/web/src/repo/blob/codemirror/token-selection/keybindings.ts
- client/web/src/repo/blob/codemirror/token-selection/selections.ts
- client/web/src/search/helpers.tsx
- client/web/src/search/results/SearchResultsCacheProvider.tsx
- Part of #33834 
CI
- [Web](https://sg-web-vb-react-router-migration-8.onrender.com/search)
> web: remove `history` from the blob components

- cmd/frontend/graphqlbackend/codeintel.graphql
- enterprise/internal/codeintel/policies/internal/store/store_configuration.go
- enterprise/internal/codeintel/policies/internal/store/store_configuration_test.go
- enterprise/internal/codeintel/policies/shared/types.go
- enterprise/internal/codeintel/policies/transport/graphql/root_resolver.go
- internal/codeintel/resolvers/all.go
> codeintel: Allow filtering policies by protected flag

- enterprise/internal/codeintel/policies/internal/store/store_repos.go
See https://github.com/sourcegraph/sourcegraph/pull/47530#discussion_r1104692402.
Tested query by hand.
> codeintel: Improve repo count query

- enterprise/cmd/executor/internal/worker/workspace/firecracker.go
- enterprise/cmd/executor/internal/worker/workspace/util.go
Was broken in previous PR.
Main dry run passes now.
> Fix workspace mount paths for docker

- internal/codeintel/dependencies/internal/store/store.go
- internal/codeintel/dependencies/internal/store/store_test.go
Does what it says on the tin
Updated unit test
> packages: allow empty scheme to select all

- doc/dependency_decisions.yml
Fixes erroneous failing license check.
n/a
> pin license for library

- enterprise/dev/app/release.sh
Adopts the new Docker image built in response to https://github.com/goreleaser/goreleaser-cross/issues/28.
CI passes.
> fix libxar issue in app build

- doc/admin/how-to/index.md
- doc/admin/how-to/remove-repo.md
1. `sg start` or `sg run docsite`
1. http://localhost:5080/admin/how-to/remove-repo
> doc: Update remove repo page

- sg.config.yaml
I want that good stuff with @unknwon's changes: https://github.com/sourcegraph/docsite/releases/tag/v1.9.0
- Used it locally
> Update sg.config.yaml to pull in newest docsite version

- client/web/src/search/home/SearchPage.module.scss
- client/web/src/search/home/SearchPage.tsx
- schema/schema.go
- schema/settings.schema.json
This feature was removed, but the styles and settings weren't.
n/a
> SearchPage: remove unused styles (for old collaborators panel)

- client/web/src/enterprise/cody/GlobalCodyArea.tsx
n/a
- [Web](https://sg-web-sqs-fix-cody-enabled.onrender.com/search)
> fix cody enabled boolean

- cmd/searcher/internal/search/search_structural.go
- internal/comby/comby.go
Previously, the unmarshallers would just fail and return nil if it was invalid. Instead, now that we can actually handle the errors, we want to propagate and report them.
Unit tests. (yay we can start testing things now!)
> Comby: make unmarshalers fallible

- doc/admin/repo/metadata.md
> Document limitations of kvp

- doc/admin/observability/outbound-request-log.md
> Add troubleshooting note

- client/web/src/enterprise/organizations/routes.tsx
Fix the batch change execution routes.
1. sg start
2. go to the execution preview (e.g. https://sourcegraph.test:3443/organizations/sourcegraph/batch-changes/test-change-2/executions/QmF0Y2hTcGVjOiJiMmMzZGI2Ni0zZDI0LTQ3OTEtOWU1Ni01MThlOTdkNGI2MzYi/execution)
- [Web](https://sg-web-vb-fix-batch-changes-exec-route.onrender.com/search)
> web: fix batch-changes exec route

- CHANGELOG.md
Added changelog entries for the things I forgot to add them for before.
N/A just changelog entries.
> batches: add changelog entries

- doc/cli/quickstart.md
> Adds note about running src cli through an apache proxy

- client/web/src/enterprise/insights/pages/insights/creation/compute/components/ComputeInsightCreationContent.tsx
- client/web/src/enterprise/insights/pages/landing/getting-started/components/dynamic-code-insight-example/DynamicCodeInsightExample.tsx
closes https://github.com/sourcegraph/sourcegraph/issues/47687
- Check that getting started page example works properly 
- Check that compute powered insight creation UI validation works as expected
- [Web](https://sg-web-vk-fix-insight-repo-validation.onrender.com/search)
> Fix insight repositories validation check

- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/operations.go
- enterprise/dev/ci/internal/ci/pipeline.go
context: https://sourcegraph.slack.com/archives/C04MYFW01NV/p1676482700598499
preview pipeline
```sh
go run ./dev/sg ci preview -b docker-images-candidates-notest/publish-candiates-build        
```
```
If the current branch were to be pushed, the following pipeline would be run:
• Detected run type: Build all candidates without testing                                                                                                                                                                                                                                   
• Detected diffs: Go, Docs …
```
> dev/sg: candidate-notest now publishs images to docker hub

- CHANGELOG.md
Just adds the changelog entry for the rate limiter fix.
Changelog entry
> Add changelog entry for rate limiter fix

- doc/admin/free-tier.md
Not a native speaker, but the way it's been written read like SAML is an alternative to SSO, but actually is just an example of SSO.
n/a
> free-tier: improve SSO description

- .github/ISSUE_TEMPLATE/security-release-approval.md
> Update security release issue template

- docker-images/cadvisor/Dockerfile
- docker-images/jaeger-agent/build.sh
- docker-images/jaeger-all-in-one/build.sh
- docker-images/postgres-12-alpine/Dockerfile
- docker-images/prometheus/Dockerfile
> Resolve vulnerabilities in containers by updating dependencies

- internal/extsvc/azuredevops/client.go
- internal/extsvc/azuredevops/client_test.go
- internal/extsvc/azuredevops/users.go
- internal/extsvc/azuredevops/users_test.go
- internal/repos/azuredevops.go
Some improvements as first steps of #47163.
Updated tests.
> internal: Azure Dev Ops client improvements

- cmd/frontend/graphqlbackend/site.go
- internal/oobmigration/downgrade.go
- internal/oobmigration/downgrade_test.go
- internal/oobmigration/upgrade.go
- internal/oobmigration/upgrade_test.go
- internal/oobmigration/version.go
- internal/oobmigration/version_test.go
TBD
TBD
---
Stacked on https://github.com/sourcegraph/sourcegraph/pull/47672
> oobmigration: recognize dev version flag

- CHANGELOG.md
In response to: https://github.com/sourcegraph/sourcegraph/pull/47783#discussion_r1109445804
...
> fix change log grammar

- CHANGELOG.md
> changelog: announce shard merging

- CHANGELOG.md
> Add changelog entry for free license changes

- doc/sidebar.md
> doc: add "Getting started" to sidebar

- CHANGELOG.md
- enterprise/cmd/frontend/internal/licensing/enforcement/users.go
Changelog change.
But where is the changelog changelog?
> Add some details about the free license change

- CHANGELOG.md
Updates changelog.
N/A: changelog update.
> Add CodeMirror blob changes to the changelog

- CHANGELOG.md
Updates changelog.
N/A: changelog update
> Add blob view keyboard navigation to changelog

- .github/teams.yml
> chore: delete outdated team label automation

- dev/authtest/site_admin_test.go
> authtest: properly assert error

- enterprise/internal/codeintel/autoindexing/transport/graphql/observability.go
- enterprise/internal/codeintel/autoindexing/transport/graphql/root_resolver.go
Bye code.
Existing CI pipelines.
> codeintel: Remove unused resolvers

- doc/code_insights/explanations/administration_and_security_of_code_insights.md
- doc/code_insights/explanations/current_limitations_of_code_insights.md
Document new insights settings for controlling backfills
Update docs regarding limitations and scale.
n/a docs only
> insights: docs updates regarding scale/limitations

- CHANGELOG.md
> changelog: cut sourcegraph@4.5.0

- internal/database/migration/shared/data/cmd/generator/consts.go
- internal/database/migration/shared/data/stitched-migration-graph.json
Update the multi version upgrade constants
N/A
> 4.5.0 multi version upgrade constants

- cmd/frontend/graphqlbackend/site.go
It's wasteful to init twice for the exact same runner and parsed-version.
The `site > upgradeReadiness` endpoint still works.
---
Closes https://github.com/sourcegraph/sourcegraph/issues/47258, stacked on https://github.com/sourcegraph/sourcegraph/pull/47672
> graphqlbackend: only init once for upgrade readiness

- cmd/frontend/graphqlbackend/codeintel.graphql
- enterprise/internal/codeintel/shared/types/indexer_resolver.go
- internal/codeintel/resolvers/all.go
Expose language key in indexer resolver.
It builds don't it?
> codeintel: Add key to indexer resolver

- client/branded/src/search-ui/input/experimental/suggestionsExtension.ts
- client/web/src/search/input/suggestions.ts
This PR updates the suggestion logic to render predicate suggestions below value suggestions for the repo and file filters. For this I
- extended the suggestion extension to support "snippets", reusing CodeMirror's built-in snippet support
- made the number of suggested repo/file values depending on whether predicate results are present or not. This is to reduce the risk of having the predicate section be scrolled out of view and to keep keep the number of options manageable (we might want to limit the number of predicates in an empty state too, I don't know yet)
- introduces constants for how many options should be rendered to make them clearer and easier to change (we'll probably make this dynamic at some point).
https://user-images.githubusercontent.com/179026/219696300-81c1887c-80ff-4d …
> experimental search input: Add predicate support

- internal/gitserver/client.go
I merged an out-of-date PR that didn't merge cleanly, causing main to fail build.
This PR builds.
> Fix bad merge

- client/web/src/auth/SignInPage.tsx
- client/wildcard/src/components/Feedback/FeedbackPrompt/FeedbackPrompt.test.tsx
- client/wildcard/src/components/Feedback/FeedbackPrompt/FeedbackPrompt.tsx
- client/wildcard/src/components/Feedback/FeedbackPrompt/__snapshots__/FeedbackPrompt.test.tsx.snap
- simplify wording after user submits feedback: from "Thank you for your help." to just "Thank you."
- add period at end of sentence
n/a
- [Web](https://sg-web-sqs-fix-wording-minor.onrender.com/search)
> minor wording fixes

- enterprise/cmd/frontend/internal/auth/azureoauth/login.go
- enterprise/cmd/frontend/internal/auth/azureoauth/middleware.go
- enterprise/cmd/frontend/internal/auth/azureoauth/provider.go
- enterprise/cmd/frontend/internal/auth/azureoauth/provider_test.go
- enterprise/cmd/frontend/internal/auth/azureoauth/session.go
- enterprise/cmd/frontend/internal/auth/init.go
- enterprise/cmd/frontend/internal/auth/oauth/provider.go
- enterprise/cmd/frontend/internal/auth/oauth/utils.go
- internal/database/security_event_logs.go
- internal/extsvc/azuredevops/users.go
- schema/schema.go
- schema/site.schema.json
Major work on #47163.
This works and users are able to sign up / login. Frontend changes will follow in a separate PR as this PR is already quite big and I couldn't break this down to any smaller.
I've identified an extra list of things to be done in the issue including the frontend related changes which I will follow up on as improvements.
I've added some tests but not exhaustive, but I have a high degree of confidence on this working for a basic setup as a lot of the untested code is inspired from existing oauth provider implementations. I will add more tests as a follow up before this feature is ready for customer use. For now I want to move forward with implementing permissions syncing.
Let me know in reviews if that is acceptable.
- Added some tests
- Tested locally: …
> azureoauth: Add azure devops oauth provider

- cmd/gitserver/Dockerfile
- cmd/server/Dockerfile
- enterprise/cmd/batcheshelper/Dockerfile
- enterprise/cmd/executor/docker-image/Dockerfile
- enterprise/cmd/gitserver/Dockerfile
Update `git` binary to address discovered vulnerabilities. 
CI test build, run image and check `git` version.
> Bump up included git version

- cmd/frontend/graphqlbackend/permission_sync_jobs.go
- enterprise/cmd/frontend/internal/authz/resolvers/permission_sync_jobs.go
- enterprise/cmd/frontend/worker/auth/perms_syncer_cleaner_test.go
- enterprise/cmd/frontend/worker/auth/perms_syncer_scheduler_test.go
- enterprise/cmd/repo-updater/internal/authz/perms_syncer_worker_test.go
- internal/database/permission_sync_jobs.go
- internal/database/permission_sync_jobs_test.go
Test plan:
Part of https://github.com/sourcegraph/sourcegraph/issues/47731
> permissions-center: add types necessary for GraphQL layer.

- doc/admin/deploy/kubernetes/update.md
One of the problems without correct indentation is the auto-numbering list isn't working:
n/a
> doc: improve list indentation

- .github/workflows/batches-notify.yml
- .github/workflows/buildchecker-history.yml
- .github/workflows/buildchecker.yml
- .github/workflows/codenotify.yml
- .github/workflows/jetbrains-tests.yml
- .github/workflows/licenses-check.yml
- .github/workflows/licenses-update.yml
- .github/workflows/lighthouse-production.yml-disabled
- .github/workflows/lsif-go.yml
- .github/workflows/pr-auditor.yml
- .github/workflows/pr-preview.yml
- .github/workflows/resources-report.yml
- .github/workflows/scip-typescript.yml
- .github/workflows/sg-binary-release.yml
- .github/workflows/sg-setup.yml
Update to actions/checkout@v3 to avoid deprecation warning
Created as part of batch change: [_Created by Sourcegraph batch change `sourcegraph-operator-dax/Upgrade_actions_checkout_v2-v3`._](https://sourcegraph.sourcegraph.com/users/sourcegraph-operator-dax/batch-changes/Upgrade_actions_checkout_v2-v3)
> ci: update to actions/checkout@v3

- cmd/frontend/graphqlbackend/teams.go
- cmd/frontend/graphqlbackend/teams_test.go
- internal/database/fakedb/teams.go
Part of #47043
We introduce an operation to remove team members.
Unit test that verifies success scenario.
> Teams GraphQL - remove teams members op

- doc/code_search/CODENOTIFY
rg @rvantonder ./**/CODENOTIFY
> Remove from @rvantonder from CODENOTIFY files

- enterprise/internal/oobmigration/migrations/batches/external_fork_name_migrator_test.go
> Remove print statement

- internal/database/schema.json
- internal/database/schema.md
- migrations/frontend/1677005673_add_codeintel_rank_defintions_and_references/down.sql
- migrations/frontend/1677005673_add_codeintel_rank_defintions_and_references/metadata.yaml
- migrations/frontend/1677005673_add_codeintel_rank_defintions_and_references/up.sql
- migrations/frontend/squashed.sql
Adding definition and references tables that will be used in the ranking background jobs 
Test manually
> [rank] adding definition and references tables for ranking job

- doc/admin/deploy/kubernetes/helm.md
* Tested Doc changes by deploying and following steps, then troubleshooting issues and adding solutions to default suggestions/information on necessary changes
* Only Doc changes, no code change
> Update helm docs to be more clear for EKS

- internal/database/migration/shared/data/stitched-migration-graph.json
Adding missing generated change
> [hotfix] Adding missing generated change

- CHANGELOG.md
> fix CHANGELOG.md entry.

- .github/teams.yml
- .github/workflows/label-notify.yml
> add @mrnugget to IAM/repo management related gh automation.

- internal/database/migration/shared/data/stitched-migration-graph.json
Forgot to run `sg generate` for https://github.com/sourcegraph/sourcegraph/pull/48001. 🙈
Just a generated code change.
> Fix stitched migration

- internal/database/migration/shared/data/stitched-migration-graph.json
Updating migration graph for 4.5 branch
N/A
> updating migration graph for 4.5

- doc/admin/external_services/postgres.md
add docs for https://github.com/sourcegraph/sourcegraph/pull/47585
this feature was previously requested by a customer (fun fact: they're considering moving to cloud) https://docs.google.com/spreadsheets/d/1Mo9O-sARMdprPpFC_IZIM7AllDvSUzED-9X1fa5SkvI/edit?disco=AAAArZ57qxQ
it still requires more real-world testing, but it's worth having some minimal docs in case someone else want to give it a try.
N/A, docs only
> docs: add rds iam auth

- doc/admin/how-to/blobstore_debugging.md
- doc/admin/how-to/index.md
fix some broken links in our docs
docs change only.
> doc: fix broken admin how-to links

- cmd/worker/internal/migrations/init.go
- internal/oobmigration/runner.go
- internal/oobmigration/runner_test.go
This reverts commit 23d637a845e3693074fdb1a23dde950dca4bf4b1.
Currently breaking main, will investigate tomorrow.
Tis a revert.
> Revert "oobmigration: Do not run deprecated migrations in worker (#47964)

- cmd/frontend/internal/app/updatecheck/handler.go
- doc/admin/deploy/docker-compose/aws.md
- doc/admin/deploy/docker-compose/azure.md
- doc/admin/deploy/docker-compose/digitalocean.md
- doc/admin/deploy/docker-compose/google_cloud.md
- doc/admin/deploy/docker-compose/index.md
- doc/admin/deploy/docker-single-container/aws.md
- doc/admin/deploy/docker-single-container/digitalocean.md
- doc/admin/deploy/docker-single-container/google_cloud.md
- doc/admin/deploy/docker-single-container/index.md
- doc/admin/deploy/kubernetes/configure.md
- doc/admin/deploy/kubernetes/helm.md
- doc/admin/deploy/machine-images/gce.md
- doc/admin/deploy_executors_kubernetes.md
- doc/admin/external_services/postgres.md
- doc/admin/external_services/redis.md
- doc/admin/http_https_configuration.md
- doc/admin/ssl_https_self_signed_cert_nginx.md
- doc/admin/updates/docker_compose.md
- doc/admin/updates/kubernetes.md
- doc/admin/updates/pure_docker.md
- doc/admin/updates/server.md
- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/pipeline.go
This pull request is part of the Sourcegraph 4.5.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.5.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/47836)
> release: sourcegraph@4.5.0

- client/web/src/repo/RepoRevisionSidebarFileTree.tsx
This PR fixes two issues that were caused by recent infrastructure changes:
1. After the Apollo update, `onCompleted` is only called after the first time a query is resolved which caused the logic to load subtrees to be broken. To fix this, we set `notifyOnNetworkStatusChange` to true but that in turn also causes the `loading` flag to be set to true when the query is refetched, so we no longer use this information.
2. When I fixed the above issue, I noticed a sync issue between the controlled `expandedIds`. I'm not entirely sure why this was not noticeable before but it seems like I had a logic error in how I was syncing the controlled state value with the UI value. The single source of truth should the UI view which optimistically expands items when the user clicks on them anyway. This …
> Treeview: Fix directory expansion of file tree

- internal/search/job/jobutil/job.go
In the previous fix, I forgot that select:file.owners could also drop results entirely and not just potentially expand them to multiple results. So here we go, another fix for the same problem.
Verified result counts are now correct.
> Return correct result counts for select:file.owners

- client/web/src/enterprise/codeintel/configuration/components/CreatePolicyButtons.tsx
- client/web/src/enterprise/codeintel/indexes/pages/CodeIntelPreciseIndexesPage.tsx
Fixes some links that have caught out with the recent React Router changes
Tested locally
- [Web](https://sg-web-tr-fix-relative-link.onrender.com/search)
> Code Intel: Fix relative links

- dev/release/release-config.jsonc
Release config for 4.6, auto generated by release tool
N/A
> 4.6 release config

- doc/admin/observability/dashboards.md
> ci: Fix lint

- CHANGELOG.md
> changelog for 4.5.1

- CHANGELOG.md
Forgot to do this in the prior commit.
Test Plan: n/a
> repos: Changelog entry for other exclude setting

- .aspect/bazelrc/BUILD.bazel
- .aspect/bazelrc/ci.bazelrc
- .aspect/bazelrc/correctness.bazelrc
- WORKSPACE
Primarily to pickup https://github.com/aspect-build/bazel-lib/commit/91eeca7d40e22a9f96671444f792fa3bb2545d96
See: https://github.com/aspect-build/bazel-lib/issues/381
CI
> build: update aspect_bazel_lib to 1.27.2, update recommended CI bazelrc settings

- internal/search/keyword/keyword_search_job.go
I believe this filter was added to increase the relevance of keyword search results. However, in my tests I have seen that it is too aggresive and sometimes doesn't yield any results.
For example:
On .com this yields results:
```
zoekt query patternType:keyword r:sourcegraph$
```
but this doesn't
```
zoekt query asdf patternType:keyword r:sourcegraph$
```
This is not intuitive because we would expect the keyword search to be robust against non-matching terms, IE the result set should not decrease with more terms.
I propose to rely on our existing ranking (provided by Zoekt and document ranking) and to remove the logic in the job layer.
This will make it much easier to reason about relevance for keyword search.
- this feature is not public
- manual testing: I checked that a local instance …
> job: remove result filter from keywordSearchJob

- doc/admin/observability/alerts.md
- monitoring/definitions/zoekt.go
Shard merging reduces the number of mmapped files and is a good option to resolve this alert.
- just a copy change
> alert: mention shard merging in alert's next steps

- internal/database/permission_sync_jobs.go
- internal/database/permission_sync_jobs_test.go
Test plan:
Closes https://github.com/sourcegraph/sourcegraph/issues/47302
> permissions-center: introduce filtering by PermissionsSyncJobReasonGroup.

- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.story.tsx
- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTableItem.tsx
- client/web/src/site-admin/permissions-center/backend.ts
- cmd/frontend/graphqlbackend/authz.graphql
- cmd/frontend/graphqlbackend/permissions_sync_jobs.go
- enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
- enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
> permissions-center: add PermissionsSyncJobReason GraphQL type.

- cmd/frontend/internal/app/updatecheck/handler.go
- doc/admin/deploy/docker-compose/aws.md
- doc/admin/deploy/docker-compose/azure.md
- doc/admin/deploy/docker-compose/digitalocean.md
- doc/admin/deploy/docker-compose/google_cloud.md
- doc/admin/deploy/docker-compose/index.md
- doc/admin/deploy/docker-single-container/aws.md
- doc/admin/deploy/docker-single-container/digitalocean.md
- doc/admin/deploy/docker-single-container/google_cloud.md
- doc/admin/deploy/docker-single-container/index.md
- doc/admin/deploy/kubernetes/helm.md
- doc/admin/deploy/machine-images/gce.md
- doc/admin/deploy_executors_kubernetes.md
- doc/admin/external_services/postgres.md
- doc/admin/external_services/redis.md
- doc/admin/http_https_configuration.md
- doc/admin/ssl_https_self_signed_cert_nginx.md
- doc/admin/updates/docker_compose.md
- doc/admin/updates/kubernetes.md
- doc/admin/updates/pure_docker.md
- doc/admin/updates/server.md
This pull request is part of the Sourcegraph 4.5.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.5.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/48151)
> release: sourcegraph@4.5.1

- doc/admin/config/batch_changes.md
- schema/schema.go
- schema/site.schema.json
> docs: add specifics for when batch changes rollout window is applied

- doc/admin/updates/index.md
Sister PR of https://github.com/sourcegraph/sourcegraph/pull/48046 for documentation.
n/a
---
Closes https://github.com/sourcegraph/sourcegraph/issues/47259
> doc: check the upgrade readiness

- .github/test.CODEOWNERS
Equal rules need to be collapsed into a single one. 
Now matches more correctly.
> Fixup test codeowners file

- doc/code_insights/explanations/search_results_aggregations.md
Add timeout setting info and note about timeouts after adding repos.
n/a docs only
> insights: updated notes on aggregation timeouts

- doc/dev/background-information/basestore.md
[Old docs are here](https://docs.sourcegraph.com/dev/background-information/basestore#using-basestore-helpers-for-scanning)
[New docs are here](https://docs.sourcegraph.com/@milan_basestore_docs/dev/background-information/basestore#using-basestore-helpers-for-scanning)
New docs can be seen here:
since it's just docs changes, eyeballing 👀
> [doc] Add docs for basestore map scanner

- doc/admin/external_service/index.md
> docs: fix wrong header level

- enterprise/cmd/worker/internal/batches/workers/batch_spec_workspace_creator.go
Fixed an Issue that @BolajiOlajide found with mounting directories.
We would get the following error when trying to mount directories in `remote`.
```text
workspace resolution failed: could not find a matching mount entry
```
It seems when mounting directories, the workspace file cache would return an error since it could not find the specific file.
Updated to handle the case where the path is a directory.
All current tests pass and did functional testing.
For completeness, here is running a specific file
> batches: Fix issue with directory mounts

- doc/admin/deploy/kubernetes/configure.md
- doc/admin/deploy/kubernetes/index.md
- doc/admin/deploy/kubernetes/kustomize/migrate.md
- doc/admin/deploy/kubernetes/operations.md
- doc/admin/deploy/kubernetes/troubleshoot.md
Add new migration steps for kustomize docs
Docs update. Locally tested.
> docs: Add new migration steps for kustomize

- dev/release/src/release.ts
The formatting was all on a single line, this makes it a bit more readable.
- [Web](https://sg-web-cclark-fix-check-candidate.onrender.com/search)
> improve readability when printing rc tags

- cmd/frontend/internal/cli/serve_cmd.go
Minor commit, just noticing a slight cleanup while I was trying to understand how this code changed due to App.
> frontend: use MustGetBool for printLogo

- client/web/src/STORM.md
Start the living document where we can document our findings while we work on Storm. Let's define the guidelines together! 
Feel free to propose changes in this PR or create follow-ups.
N/a
> web: draft Storm guidelines

- client/web/src/site-admin/AccessRequestsPage/AccessRequestsGlobalNavItem.tsx
Follow up on https://github.com/sourcegraph/sourcegraph/pull/47741.
| --: | :-- |
| <img width="1727" alt="image" src="https://user-images.githubusercontent.com/6717049/221833564-01779673-74b8-42ce-9f39-f54e828656e7.png"> | <img width="1727" alt="Screen Shot 2023-02-28 at 13 51 33" src="https://user-images.githubusercontent.com/6717049/221833486-be338632-42e7-4e2c-8858-aa5a441b0bcd.png"> | 
- Check diff
- [Web](https://sg-web-erzhtor-fix-incorrect.onrender.com/search)
> [Request access] fix incorrect pluralization

- cmd/frontend/graphqlbackend/authz.graphql
- cmd/frontend/graphqlbackend/permissions_sync_jobs.go
- enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
- enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
- internal/database/permission_sync_jobs.go
- internal/database/permission_sync_jobs_test.go
Test plan:
GraphQL tests added.
Database layer unit tests added.
First part of https://github.com/sourcegraph/sourcegraph/issues/47303
> permissions-center: implement permissions sync job search by repo name.

- enterprise/internal/database/integration_test.go
- enterprise/internal/database/perms_store.go
- enterprise/internal/database/perms_store_test.go
- internal/database/repos.go
In response to feedback collected from PR: https://github.com/sourcegraph/sourcegraph/pull/48283
updated unit tests. and manually tests graphql api
> Improve list user permissions func on perms store

- enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
- internal/database/permission_sync_jobs.go
- internal/database/permission_sync_jobs_test.go
Test plan:
GraphQL tests added.
Database layer unit tests added.
Closes https://github.com/sourcegraph/sourcegraph/issues/47303
> permissions-center: support sync job search by user name/display name.

- doc/admin/deploy/kubernetes/configure.md
- doc/admin/deploy/kubernetes/index.md
- doc/admin/deploy/kubernetes/kustomize/index.md
- doc/admin/deploy/kubernetes/kustomize/migrate.md
Add more information on the Kustomize migration process
docs update.
> dcos: Update Kustomize migration process

- client/web/src/repo/RepoContainer.tsx
Repository pages update the current search input to contain the repo and file names. This PR updates that logic to also include the `context:` selector if the new quer input is enabled.
https://user-images.githubusercontent.com/179026/221905669-75203ec1-0bd6-4dad-8c02-8b4978f98828.mp4
Manual testing
- [Web](https://sg-web-fkling-search-input-context-repo.onrender.com/search)
> experimental search input: Preserve context: filter on repo pages

- doc/app/index.md
Can clean this up later, but wanted to make sure we got it in there. 
Passing CI
> add local repo tip

- .github/test.CODEOWNERS
They should be generally absolute, for both correctness and performance reasons.
Just a test file.
> Fix paths not absolute in test.CODEOWNERS

- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.story.tsx
Test plan:
CI.
- [Web](https://sg-web-ao-fix-stop-lying-in-storybook.onrender.com/search)
> fix name of the story in Storybook.

- client/web/BUILD.bazel
Manual bazel build
- [Web](https://sg-web-bazel-webpack-assets.onrender.com/search)
> web: add missing static assets to bazel bundle target

- .bazeliskrc
Are there any downsides to using the Aspect CLI by default? If we want to ask our engineers to rely on it, we should start testing it asap. 
1. Create an empty .ts file in the web package
2. Import this file into any of the existing .ts files
3. Run `bazel configure`
4. See the updated `BUILD.bazel` file
> bazel: add `.bazeliskrc` with Aspect-CLI

- internal/service/servegit/serve.go
The previous PR introduced fastwalk in a way which minimized change to make the PR easy to review. This PR restructures the code such that it makes more sense now that we have more concurrency control in place.
The main change is moving the walk code into its own function such that it is convenient to call it in its own goroutine and make it clear when the corresponding channel is closed.
Parent https://github.com/sourcegraph/sourcegraph/pull/48435
Part of https://github.com/sourcegraph/sourcegraph/issues/48176
> servegit: restructure Walk code to be more idiomatic

- WORKSPACE
- deps.bzl
I recently added a new dependency but forgot to regenerate these files :) This seems to have not been the only thing we missed lol, so this PR includes quite a bunch of modifications to the deps.bzl file.
Seems to still work? Help me vet this please 😬
> Update bazel dependencies file

- enterprise/internal/scim/user.go
- enterprise/internal/scim/user_patch.go
- enterprise/internal/scim/user_replace.go
- enterprise/internal/scim/user_replace_test.go
- Fixes https://github.com/sourcegraph/sourcegraph/issues/48428
Was a quick fix.
CI should pass, that's all. Tested it manually and with a new test case.
> SCIM: Add test for PUT, fix silly mistake around changes

- enterprise/cmd/frontend/internal/own/resolvers/resolvers.go
Forgot to check if a ruleset was actually found here! We do this check in search, though.
Works again!
> own: Fix error when no codeowners data is present

- doc/getting-started/oss-enterprise.md
Following the release of the updated free plan, updated table to match feature availability. 
Doc change only. Tested locally.
> Update free-plan table

- client/web/src/repo/blob/own/FileOwnershipEntry.tsx
- client/web/src/repo/blob/own/FileOwnershipPanel.story.tsx
- client/web/src/repo/blob/own/HistoryAndOwnBar.module.scss
- client/web/src/repo/blob/own/HistoryAndOwnBar.story.tsx
- client/web/src/repo/blob/own/HistoryAndOwnBar.tsx
[Fixes this](https://app.slack.com/client/T02FSM7DL/C04EM0VMAKZ/thread/C04EM0VMAKZ-1677638676.555479)
Updated storybook
- [Web](https://sg-web-jp-ownavatarsize.onrender.com/search)
> own: fix avatar size

- internal/database/basestore/scan_collections.go
Pulled from #47531. This PR introduces a new basestore scan helper that uses a scanner's boolean flag to include/exclude a result.
N/A.
> basestore: Add NewFilteredSliceScanner

- client/web/src/site-admin/AccessRequestsPage/index.tsx
- doc/admin/auth/index.md
Follow up on https://github.com/sourcegraph/sourcegraph/pull/47741. Closes https://github.com/sourcegraph/sourcegraph/issues/47445.
| --: | :-- |
| <img width="1728" alt="image" src="https://user-images.githubusercontent.com/6717049/222135484-fab84bfd-6fca-4eff-86ae-43b3bc1fe837.png"> | <img width="1728" alt="image" src="https://user-images.githubusercontent.com/6717049/222135332-be15fe59-6b86-4231-9bc1-e6226cb52443.png"> |
- `sg start`
- Disable built-in signup
- Open https://sourcegraph.test:3443/site-admin/access-requests 
- [Web](https://sg-web-erzhtor-add-request-access-empty.onrender.com/search)
> [Request access] Add empty list content + update docs

- internal/database/schema.json
- internal/database/schema.md
- migrations/frontend/1677694168_add_vulnerability_tables/down.sql
- migrations/frontend/1677694168_add_vulnerability_tables/metadata.yaml
- migrations/frontend/1677694168_add_vulnerability_tables/up.sql
- migrations/frontend/1677694170_add_vulnerability_match_tables/down.sql
- migrations/frontend/1677694170_add_vulnerability_match_tables/metadata.yaml
- migrations/frontend/1677694170_add_vulnerability_match_tables/up.sql
- migrations/frontend/squashed.sql
Pulled from #47531. Adds vulnerability and vulnerability match tables for future work.
CI tests.
> sentinel: Draft table schemas

- enterprise/internal/codeintel/autoindexing/internal/store/store_indexes.go
- enterprise/internal/codeintel/uploads/internal/store/store_uploads.go
Better index hygiene, in effort towards #48373 (not a significant perf boost).
> codeintel: Improve index usage for upload/index fetching

- doc/admin/deploy_executors.md
fix docs spacing and formatting
N/A
> fix: executor docs formatting

- enterprise/internal/codeintel/ranking/config.go
- enterprise/internal/codeintel/ranking/ranking.go
And lower the reducer batch size, seems to be dominating on dotcom and this might help.
N/A.
> ranking: Split map/reduce batch sizes

- enterprise/internal/codeintel/ranking/internal/store/ranking.go
Noticed in dotcom we have a ton of null graph keys because we simply aren't setting them!
Unit tests still pass.
> ranking: Ensure we write graph key

- client/web/src/search/input/suggestions.ts
I originally had symbol suggestions appear on customer instances if the query only contained `context:global`. However symbol queries are still too slow across multiple repos.
Now they only appear if the query contains a context != global, or a repo filter or a file filter, regardless of the environment.
Careful code inspection. TypeScript.
- [Web](https://sg-web-fkling-query-input-symbol.onrender.com/search)
> experimental search input: Don't show symbol suggestions in (only) global context

- schema/azuredevops.schema.json
- schema/schema.go
> schema: Fix typo in ADO doc string

- enterprise/cmd/frontend/internal/auth/azureoauth/login.go
- enterprise/cmd/frontend/internal/auth/azureoauth/provider.go
- enterprise/cmd/frontend/internal/auth/azureoauth/session.go
- enterprise/internal/authz/authz.go
- enterprise/internal/authz/authz_test.go
- enterprise/internal/authz/azuredevops/provider.go
- enterprise/internal/authz/azuredevops/provider_test.go
- internal/database/external_services.go
- internal/extsvc/azuredevops/client.go
- internal/extsvc/azuredevops/types.go
- internal/extsvc/azuredevops/users.go
- internal/oauthutil/oauth2.go
- internal/oauthutil/token.go
- internal/types/external_services.go
- schema/azuredevops.schema.json
- schema/schema.go
Originally created #48041 for early feedback. I've addressed those and created a new PR because it diverged a lot from the original branch.
Major progress on #47165. There's a little bit of follow up work required which would add more code to this PR - the implementation of `ValidationCheck` on the authz provider. I will follow up with a new PR, but the absence of it does not prevent a good configuration of ADO from working.
Not necessarily a big PR feature wise, ~500 lines is test code. But this does touch multiple modules that would make it hard to piece together for anyone not too familiar with the permissions syncing code. I've broken it down into sequential commits that should make sense when viewed in isolation for the most part. Each commit has a description describing the context …
> ADO: Implement user permissions sync

- enterprise/cmd/frontend/internal/auth/azureoauth/login.go
- enterprise/cmd/frontend/internal/auth/azureoauth/provider.go
- enterprise/cmd/frontend/internal/auth/azureoauth/session.go
- enterprise/internal/authz/azuredevops/provider.go
- enterprise/internal/authz/azuredevops/provider_test.go
- internal/extsvc/azuredevops/client.go
- internal/extsvc/azuredevops/users.go
Follow up on #48209. Part of #47165. 
- Builds should pass
- Added tests
> internal/authz/azuredevops: Implement ValidateConnection

- internal/database/permission_sync_jobs.go
Test plan:
Local sg run and GraphQL API queries.
> permissions-center: fix a bug with case difference between GQL and database layer.

- doc/dev/background-information/bazel.md
Extracted from https://github.com/sourcegraph/sourcegraph/pull/47856 PR description, to make sure we don't forget about this.
Test plan: doc change.
> doc: add a FAQ entry about updating bazelrc

- enterprise/internal/codeintel/autoindexing/internal/store/scan.go
- enterprise/internal/codeintel/sentinel/internal/store/observability.go
- enterprise/internal/codeintel/sentinel/observability.go
- enterprise/internal/codeintel/uploads/internal/store/scan.go
- enterprise/internal/codeintel/uploads/observability.go
> lint: Fix unused codeintel vars

- cmd/frontend/graphqlbackend/codeintel.graphql
- cmd/frontend/graphqlbackend/node.go
- enterprise/cmd/frontend/internal/codeintel/resolvers.go
- enterprise/internal/codeintel/sentinel/service.go
- enterprise/internal/codeintel/sentinel/transport/graphql/iface.go
- enterprise/internal/codeintel/sentinel/transport/graphql/observability.go
- enterprise/internal/codeintel/sentinel/transport/graphql/root_resolver.go
- internal/codeintel/resolvers/all.go
Adds resolver for Vulns and vuln matches.
It may only compile...
> sentinel: Add GraphQL layer for direct object access

- enterprise/internal/scim/init.go
- enterprise/internal/scim/mock_db.go
- enterprise/internal/scim/user.go
- enterprise/internal/scim/user_account_data.go
- enterprise/internal/scim/user_create.go
- enterprise/internal/scim/user_create_test.go
- enterprise/internal/scim/user_get.go
- enterprise/internal/scim/user_get_test.go
- enterprise/internal/scim/user_patch.go
- enterprise/internal/scim/user_patch_test.go
- enterprise/internal/scim/user_replace.go
- enterprise/internal/scim/user_replace_test.go
- enterprise/internal/scim/user_schema.go
- internal/database/external_accounts.go
- internal/database/mocks_temp.go
- Fixes https://github.com/sourcegraph/sourcegraph/issues/48353
- Fixes https://github.com/sourcegraph/sourcegraph/issues/48430
- Fixes https://github.com/sourcegraph/sourcegraph/issues/48424
And cleans up a bunch of other stuff.
**To the reviewer:** I didn't do a great job at using small PRs this time. If you feel like it, you can go commit by commit. The commits are pretty atomic, and the descriptions make sense. **But** it's a lot of commits, so to provide a more comfortable alternative, I left about two dozen explanatory comments in the diff. If you scroll through the final diff from top to bottom, I will tell you a story of the changes 📖, and my hope is that they will make sense to you.
With this PR, Microsoft's SCIM validator passes! 🎉 And the only known issue now is the attribute …
> SCIM: More fixes

- internal/database/permission_sync_jobs.go
- internal/database/permission_sync_jobs_test.go
Test plan:
Local sg run and GraphQL API test.
> permissions-center: fix counting jobs with search predicates.

- enterprise/internal/batches/sources/mocks_test.go
- internal/extsvc/azuredevops/client.go
- internal/extsvc/azuredevops/client_test.go
- internal/extsvc/azuredevops/testdata/golden/ListAuthorizedUserOrganizations.json
- internal/extsvc/azuredevops/testdata/vcr/ListAuthorizedUserOrganizations.yaml
- internal/extsvc/azuredevops/types.go
- internal/extsvc/azuredevops/users.go
- internal/extsvc/azuredevops/users_test.go
First part of #48555.
- Added tests
- Builds should pass
> azuredevops: Add client method ListAuthorizedUserOrganizations

- enterprise/internal/codeintel/sentinel/config.go
- enterprise/internal/codeintel/sentinel/init.go
- enterprise/internal/codeintel/sentinel/internal/background/cve_downloader.go
- enterprise/internal/codeintel/sentinel/internal/background/cve_source_github.go
- enterprise/internal/codeintel/sentinel/internal/background/cve_source_govulndb.go
- enterprise/internal/codeintel/sentinel/internal/background/cve_source_osv.go
- enterprise/internal/codeintel/sentinel/internal/background/metrics.go
- enterprise/internal/codeintel/sentinel/internal/store/matches_test.go
- enterprise/internal/codeintel/sentinel/internal/store/store.go
- enterprise/internal/codeintel/sentinel/internal/store/vulnerabilities.go
- enterprise/internal/codeintel/sentinel/internal/store/vulnerabilities_test.go
- go.mod
- go.sum
This PR implements the background routine that will periodically check for new vulnerabilities from the GitHub advisory database and upsert them into Postgres.
🥚
> sentinel: Vulnerability database syncer routine

- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.module.scss
- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
- client/web/src/site-admin/permissions-center/backend.ts
Test plan:
https://user-images.githubusercontent.com/94846361/222687156-4c90946b-e25b-49da-aa5d-c2c54e219940.mp4
- [Web](https://sg-web-ao-ui-pc-search-jobs-ui.onrender.com/search)
> permissions-center: add search form for permissions sync jobs.

- enterprise/cmd/frontend/internal/auth/azureoauth/login.go
- enterprise/cmd/frontend/internal/auth/azureoauth/provider.go
- enterprise/cmd/frontend/internal/auth/azureoauth/session.go
- enterprise/cmd/frontend/internal/auth/azureoauth/session_test.go
- schema/schema.go
- schema/site.schema.json
Fixes #48555.
- Added test
- Builds should pass
> azuredevops: Support allowOrgs in azure auth provider

- enterprise/internal/scim/mock_db.go
- Fixes stuff based on @kopancek's comments on https://github.com/sourcegraph/sourcegraph/pull/48577
Only affects tests
> SCIM: MockDB fixes: add comment, remove function, fix next ID

- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
Test plan:
Local sg run and test.
don't ask 😅 
- [Web](https://sg-web-ao-ui-fix-search-prompt-for-users.onrender.com/search)
> permissions-center: fix search prompt for users.

- WORKSPACE
- deps.bzl
- dev/linters/bodyclose/BUILD.bazel
- linter_deps.bzl
Some deps were missing an broke :gazelle-update-repos
fixed locally
> bzl: fix broken :gazelle-update-repos

- doc/admin/updates/kubernetes.md
* It's one character in a markdown page
> Update md syntax on note about hotfix

- doc/admin/deploy/kubernetes/helm.md
- doc/admin/updates/kubernetes.md
* Docs update only. Hotfix tested and confirmed from helm repo to work
> Backport 48644 to 4.5

- enterprise/internal/codeintel/ranking/internal/store/store_test.go
- internal/codeintel/types/ranking.go
- internal/database/schema.json
- migrations/frontend/1677878270_eric_is_bad_at_math/down.sql
- migrations/frontend/1677878270_eric_is_bad_at_math/metadata.yaml
- migrations/frontend/1677878270_eric_is_bad_at_math/up.sql
- migrations/frontend/squashed.sql
Transition to using a normalized sum over log(v+1) for each ref count.
> ranking: Fix log(0)

- enterprise/internal/codeintel/ranking/internal/store/ranking.go
I got bit by not dealing with hyphens in the graph key value again 😮‍💨.
> ranking: Fix cleanup SQL

- client/web/src/site-admin/SiteAdminPingsPage.tsx
- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
Test plan:
Local sg run and test.
- [Web](https://sg-web-ao-ui-chore-pings-containter.onrender.com/search)
> chore: add container to Pings page, use `PageHeader` component, add page title to `PermissionsSyncJobsTable`.

- client/web/src/enterprise/codeintel/indexes/pages/CodeIntelPreciseIndexPage.tsx
Updates wording
N/A - Copy change
- [Web](https://sg-web-tr-indexing-wording.onrender.com/search)
> Precise indexes: Fix wording

- dev/ci/go-backcompat/flakefiles/v4.5.0.json
- enterprise/internal/codeintel/ranking/internal/store/ranking.go
- enterprise/internal/codeintel/ranking/internal/store/ranking_test.go
- enterprise/internal/codeintel/ranking/internal/store/store.go
- enterprise/internal/codeintel/ranking/internal/store/store_test.go
- enterprise/internal/codeintel/ranking/mocks_test.go
- enterprise/internal/codeintel/ranking/service.go
- internal/database/repos_test.go
- internal/database/schema.json
- internal/database/schema.md
- migrations/frontend/1677958359_simplify_path_ranks_table/down.sql
- migrations/frontend/1677958359_simplify_path_ranks_table/metadata.yaml
- migrations/frontend/1677958359_simplify_path_ranks_table/up.sql
- migrations/frontend/squashed.sql
Remove precision from insertion/querying.
> ranking: Cleanup path ranks table

- doc/cli/index.md
> Add 1Password link

- doc/admin/auth/index.md
> Doc: fix typo that caused missing space

- client/web/src/enterprise/batches/settings/AddCredentialModal.tsx
- doc/batch_changes/how-tos/configuring_credentials.md
Closes https://github.com/sourcegraph/sourcegraph/issues/46731
- [Web](https://sg-web-iv-set-declared-scops.onrender.com/search)
> Document proper scopes for ADO Batch Changes

- enterprise/internal/codeintel/uploads/internal/store/store_uploads.go
Pretty self-explanatory diff.
Fixed codeintel-qa queries locally.
> chore: Fix nil deref

- client/web/src/LegacyLayout.tsx
- client/web/src/setup-wizard/SetupWizard.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-host-delete-modal/CodeHostDeleteModal.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-host-picker/CodeHostsPicker.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/common/CodeHostConnection.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/github/GithubConnectView.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/navigation/CodeHostsNavigation.module.scss
- client/web/src/setup-wizard/components/remote-repositories-step/components/navigation/CodeHostsNavigation.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/helpers.tsx
- client/web/src/setup-wizard/components/setup-steps/SetupSteps.module.scss
- client/web/src/setup-wizard/components/setup-steps/SetupSteps.tsx
- client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
- client/web/src/site-admin/analytics/components/ValueLegendList.tsx
- client/web/src/site-admin/analytics/components/index.module.scss
- client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
- client/wildcard/src/components/PageSwitcher/PageSwitcher.tsx
- client/wildcard/src/hooks/useStorageHook.ts
Part of https://github.com/sourcegraph/sourcegraph/issues/48648
- Make sure that all icons for the supported code host look good
- Check the light/dark theme for the JSON editor 
- Check spacings for remote and sync repositories step
- Check that skip functionality works as expected (if you haven't skipped wizard and you haven't setup your instance yet then on any route you should be redirected to `/setup/<last visited step>`, otherwise you should see the URL page that you typed in browser)
- [Web](https://sg-web-vk-wizard-paper-cuts.onrender.com/search)
> Setup Wizard: Fix some of paper cuts

- client/web/src/LegacyLayout.tsx
- client/web/src/setup-wizard/SetupWizard.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-host-delete-modal/CodeHostDeleteModal.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-host-picker/CodeHostsPicker.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/common/CodeHostConnection.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/github/GithubConnectView.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/navigation/CodeHostsNavigation.module.scss
- client/web/src/setup-wizard/components/remote-repositories-step/components/navigation/CodeHostsNavigation.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/helpers.ts
- client/web/src/setup-wizard/components/setup-steps/SetupSteps.module.scss
- client/web/src/setup-wizard/components/setup-steps/SetupSteps.tsx
- client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
- client/web/src/site-admin/analytics/components/ValueLegendList.tsx
- client/web/src/site-admin/analytics/components/index.module.scss
- client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
- client/wildcard/src/components/PageSwitcher/PageSwitcher.tsx
- client/wildcard/src/hooks/useStorageHook.ts
Reverts sourcegraph/sourcegraph#48699
To unblock main - failing build: https://buildkite.com/sourcegraph/sourcegraph/builds/204107 
- [Web](https://sg-web-revert-48699-vk-wizard-paper-cuts.onrender.com/search)
N/A - just reverting due to failing build
> Revert "Setup Wizard: Fix some of paper cuts"

- BUILD.bazel
- client/shared/dev/generate_graphql_operations.bzl
- client/shared/dev/generate_schema.bzl
- deps.bzl
- dev/babel.bzl
- dev/defs.bzl
- dev/sass.bzl
This resolves the buildifier failures we hit when running buildifier on Aspect Workflows for the demo.
Test plan: CI
- [Web](https://sg-web-aspect-buildifier-fixes.onrender.com/search)
> Buildifier fixes

- client/shared/src/testing/driver.ts
- client/web/src/LegacyLayout.tsx
- client/web/src/setup-wizard/SetupWizard.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-host-delete-modal/CodeHostDeleteModal.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-host-picker/CodeHostsPicker.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/common/CodeHostConnection.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/github/GithubConnectView.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/navigation/CodeHostsNavigation.module.scss
- client/web/src/setup-wizard/components/remote-repositories-step/components/navigation/CodeHostsNavigation.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/helpers.tsx
- client/web/src/setup-wizard/components/setup-steps/SetupSteps.module.scss
- client/web/src/setup-wizard/components/setup-steps/SetupSteps.tsx
- client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
- client/web/src/site-admin/analytics/components/ValueLegendList.tsx
- client/web/src/site-admin/analytics/components/index.module.scss
- client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
- client/wildcard/src/components/PageSwitcher/PageSwitcher.tsx
- client/wildcard/src/hooks/useStorageHook.ts
Original PR https://github.com/sourcegraph/sourcegraph/pull/48699
This PR is the second try to merge the original https://github.com/sourcegraph/sourcegraph/pull/48699 (after the first one was merged, a few e2e started to fail)
- Make sure that CI and e2e tests are fine
- [Web](https://sg-web-vk-wizard-paper-cuts-2.onrender.com/search)
> Setup Wizard: Fix wizard UI paper cuts 2

- client/web/src/site-admin/permissions-center/PermissionsSyncJobNode.tsx
Test plan:
Local sg run and test.
- [Web](https://sg-web-ao-ui-pc-change-wording.onrender.com/search)
> permissions-center: change wording for `REASON_REPO_OUTDATED_PERMS` and `REASON_USER_OUTDATED_PERMS` statuses.

- CHANGELOG.md
> CHANGELOG: Add note about fixed status message position

- client/web/src/nav/GlobalNavbar.tsx
- client/web/src/nav/NavBar/NavDropdown.tsx
Closes #48397
https://user-images.githubusercontent.com/458591/223126252-b2f6c14d-12f9-44e0-8665-268be766d624.mov
- [Web](https://sg-web-ps-app-feedback-tab.onrender.com/search)
> App: Add feedback tab

- enterprise/internal/batches/state/changeset_history.go
Manually tested it automatically turns to draft.
> Add initial state draft to ADO PRs in BC

- CHANGELOG.md
> Add changelog enrty for outbound request fix

- enterprise/internal/database/integration_test.go
- enterprise/internal/database/mocks_temp.go
- enterprise/internal/database/perms_store.go
- enterprise/internal/database/perms_store_test.go
- internal/database/repos_perm.go
Add repo permissions info api to list down users who has access to the repository and why. 
added unit tests.
> [Permissions] add store method for ListRepoPermissions

- dev/sg/sg_cloud.go
```sh
go run ./dev/sg cloud install         
👉 Removing existing installation at of "mi2" at "/Users/michael/.bin/mi2"
👉 Using GitHub CLI version "gh version 2.23.0 (2023-02-07)"
```
> dev/sg: log gh cli version

- doc/admin/observability/alerts.md
- doc/admin/observability/dashboards.md
- monitoring/definitions/dashboards.go
- monitoring/definitions/embeddings.go
- monitoring/monitoring/monitoring.go
Adds basic resource metrics for embeddings container.
* Manual testing.
> embeddings: container metrics

- .github/workflows/label-move.yml
Action fails with legacy IDs. This updates those to the V2 format.
Action succeeds
> chore: update project IDs for issue move Action

- client/web/src/site-admin/permissions-center/PermissionsSyncJobsPage.tsx
Make Permissions Sync Jobs Page enabled by default
- [Web](https://sg-web-thenamankumar-patch-1.onrender.com/search)
> Make Permissions Sync Jobs Page enabled by default

- doc/admin/deploy_executors_terraform.md
Weird line breaks were rendering the text with missing spaces.
None, doc change
> chore: fix executor terraform deployment docs formatting

- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/pipeline.go
Disable those until we fix database isolation + comby
`sg ci preview`
> Disable soft failing bazel jobs for now

- cmd/frontend/internal/bg/app_ready.go
Closes https://github.com/sourcegraph/sourcegraph/issues/48812
> app: print running address when ready

- cmd/frontend/internal/app/updatecheck/client.go
- cmd/frontend/internal/app/updatecheck/handler.go
- internal/usagestats/repositories.go
Whoops, I forgot this needs the analytics change first
Reverts sourcegraph/sourcegraph#48211
N/A
> Revert "capture bucketed repo sizes in pings"

- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/pipeline.go
Forgot to disable this earlier
sg ci preview (on the main branch this time)
> Disable bazel jobs on main

- doc/app/index.md
fix the brew install command; bump to the latest version
docs change only
> doc: app: update instructions to latest App version

- doc/dev/background-information/bazel_web.md
- doc/dev/background-information/index.md
(edit: @jhchabran: preview with `sg run docsite`)
> bazel: add bazel_web.md

- client/web/src/enterprise/repo/settings/RepoSettingsPermissionsPage.module.scss
- client/web/src/enterprise/repo/settings/RepoSettingsPermissionsPage.tsx
- client/web/src/enterprise/repo/settings/backend.ts
- client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
- cmd/frontend/graphqlbackend/authz.go
- cmd/frontend/graphqlbackend/authz.graphql
- enterprise/cmd/frontend/internal/authz/resolvers/permissions_info.go
- enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
- enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
- enterprise/internal/database/mocks_temp.go
- enterprise/internal/database/perms_store.go
closes: https://github.com/sourcegraph/sourcegraph/issues/48332
closes: https://github.com/sourcegraph/sourcegraph/issues/48331
- manual testing done.
- db store func covered with unit tests
> Naman/repo perms info UI

- doc/admin/external_service/azuredevops.md
> doc: Add steps to create a token for ADO with required scopes

- client/web/src/enterprise/code-monitoring/CodeMonitoringGettingStarted.tsx
- client/web/src/enterprise/code-monitoring/CodeMonitoringPage.story.tsx
- client/web/src/enterprise/code-monitoring/CodeMonitoringPage.test.tsx
- client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
- client/web/src/enterprise/code-monitoring/global/GlobalCodeMonitoringArea.tsx
Closes #48394
- [Web](https://sg-web-ps-add-app-header-to-code.onrender.com/search)
> App: Update Monitoring page

- enterprise/internal/database/integration_test.go
- enterprise/internal/database/perms_store.go
- enterprise/internal/database/perms_store_test.go
> [feat] use new data model in perms_store SetRepoPermissionsUnrestricted

- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
- client/web/src/site-admin/permissions-center/backend.ts
- enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
- enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
Test plan:
Local sg run and test.
> permissions-center: add cancel sync job action.

- cmd/frontend/internal/app/updatecheck/client.go
- cmd/frontend/internal/app/updatecheck/handler.go
- internal/usagestats/repositories.go
Revert the revert to restore the PR! 🎪 
Don't merge until analytics team has merged https://github.com/sourcegraph/analytics/pull/826
Reverts sourcegraph/sourcegraph#48211
see https://github.com/sourcegraph/sourcegraph/pull/48211
> Revert "Revert "capture bucketed repo sizes in pings""

- monitoring/monitoring/generator.go
Grafana's `GetFolderByUID` is proving frustratingly nondeterminstic, so this change allows us to skip that step and add retries/etc before calling the generator.
n/a, no behaviour changes if not providing `GrafanaFolderID`
> monitoring: allow providing folder ID to skip check/creation

- doc/dev/background-information/sg/index.md
it had some typos in  it, and some wrong info
Docs
> fix sg.config.override.yaml example

- doc/admin/scim.md
> docs: Fix tiny typo in SCIM doc

- enterprise/internal/database/perms_store_test.go
> [chore] fix bad predicate in sorting function for the test

- enterprise/internal/database/perms_store.go
- enterprise/internal/database/perms_store_test.go
bug https://sourcegraph.slack.com/archives/C03GMM0F2BA/p1678454844787959
updated unit tests.
> Fix list repo perms bug

- cmd/frontend/graphqlbackend/package_repos.go
> packages: fix handling of new cursor format in packageRepoReferences endpoint

- docker-images/grafana/Dockerfile
Updating the Wolfi grafana image
Building locally the image
> Update Wolfi grafana Dockerfile

- enterprise/internal/codeintel/autoindexing/internal/inference/libs/patterns.go
- enterprise/internal/codeintel/autoindexing/internal/inference/lua/patterns.lua
- enterprise/internal/codeintel/autoindexing/internal/inference/luatypes/path_patterns.go
- enterprise/internal/codeintel/autoindexing/internal/inference/util.go
I was testing previously and got fooled by bash expansion working where I thought it was git magic.
Tested locally on repos I saw weren't getting inferred correctly.
> codeintel: Fix pathspecs (again) for inference

- client/branded/src/search-ui/input/experimental/suggestionsExtension.ts
This PR updates the suggestions extension to throttle async suggestion requests. At the moment we are sending one or more search requests to the server for _every keypress_. While the data we get back is useful even if the input changed, it's not good for the server to overload it with requests.
While implementing this I ran into some race condition issues and so I also refactored the code to make the data flow and state transitions clearer.
- A `Query` (previously `RegisteredSource`) represents the suggestions query state (options available, pending server request, etc).
- In the beginning a query is _inactive_. It becomes activated (i.e. the suggestions are queried) due to various events (input changes, selection changes, etc). 
- If all suggestion sources provided static results, the …
> experimental search input: Throttle async suggestions

- client/web/src/integration/batches.test.ts
- client/web/src/integration/profile.test.ts
- client/web/src/integration/search-aggregation.test.ts
- client/web/src/integration/search.test.ts
- client/web/src/integration/settings.test.ts
- client/web/src/user/area/UserArea.tsx
- client/web/src/user/profile/UserProfile.story.tsx
- client/web/src/user/profile/UserProfile.tsx
- client/web/src/user/settings/UserSettingsArea.tsx
This PR enables the display of roles in the User Profile page.
* Manually tested
- [Web](https://sg-web-bo-display-roles-in-profile.onrender.com/search)
> rbac: display roles in profile

- client/web/src/nav/UserNavItem.tsx
👀 
- [Web](https://sg-web-fkling-search-input-beta.onrender.com/search)
> experimental search input: Update menu item

- internal/extsvc/jvmpackages/coursier/coursier.go
@Strum355 can you follow up on this next week with a more appropriate fix?
N/a
> Hotfix coursier cache dir creation on startup

- pnpm-lock.yaml
See [Slack](https://sourcegraph.slack.com/archives/C01C3NCGD40/p1678482384763389)
Ran `pnpm install` to update lock file
👀 
- [Web](https://sg-web-fkling-lock-file.onrender.com/search)
> pnpm: Update lock file

- internal/codeintel/dependencies/internal/store/store.go
nothing else to add
N/A, wrong metrics variable used resulting in wrong name in grafana
> packages: fix wrong metrics used in UpdateAllBlockedStatuses

- client/web/src/regression/core.test.ts
See https://github.com/sourcegraph/sourcegraph/issues/49161.
Two of the tests here were already disabled due to flakiness, now the third one was observed failing in Sourcegraph QA on `main` as well. It also turns out `beforeAll` and `afterAll` hooks still run on disabled tests, and they, too, were flaking... 🤔 Therefore I've disabled the whole `describe` suite (and "restored" the individual tests within it)
These tests [don't seem to have an owner ](https://github.com/sourcegraph/sourcegraph/issues/23049) and have not been resolved in 20 months. It might be worth removing them altogether if they're not serving us.
Check that CI passes.
- [Web](https://sg-web-kr-disable-flaky-regression-test.onrender.com/search)
Check out the [client app preview …
> flake: disable entire "core functionality" regression suite

- doc/admin/scim.md
- enterprise/internal/scim/mock_db.go
- enterprise/internal/scim/user.go
- enterprise/internal/scim/user_create_test.go
- enterprise/internal/scim/user_delete.go
- enterprise/internal/scim/user_get.go
- enterprise/internal/scim/user_patch.go
- enterprise/internal/scim/user_patch_test.go
- enterprise/internal/scim/user_replace.go
- enterprise/internal/scim/user_replace_test.go
- enterprise/internal/scim/user_schema.go
- Closes https://github.com/sourcegraph/sourcegraph/issues/49017
- Closes https://github.com/sourcegraph/sourcegraph/issues/49018
**For the reviewer:** it's easiest to review this PR **commit by commit**! I used descriptive comments and very small commits to guide you through the changes. I suggest you make use of it and follow my changes that way.
- Added tests for the new cases
- I'll test it with Okta's tests and they passed!
> SCIM: Do hard delete on soft delete request

- internal/database/event_logs.go
- internal/database/event_logs_test.go
- internal/types/types.go
- internal/usagestats/aggregated.go
- internal/usagestats/aggregated_test.go
Added RMAUs to event_logs unit tests.
> Add rolling monthly active users (prior 30 days) to site usage statistics ping

- client/web/src/enterprise/codeintel/admin/AdminCodeIntelArea.tsx
- client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPage.tsx
- client/web/src/enterprise/codeintel/dashboard/components/DataSummary.tsx
- client/web/src/enterprise/codeintel/dashboard/pages/GlobalDashboardPage.tsx
- client/web/src/enterprise/codeintel/dashboard/pages/RepoDashboardPage.tsx
- client/web/src/enterprise/codeintel/indexes/pages/CodeIntelPreciseIndexPage.tsx
- client/web/src/enterprise/codeintel/indexes/pages/CodeIntelPreciseIndexesPage.tsx
- client/web/src/enterprise/codeintel/repo/RepositoryCodeIntelArea.tsx
- client/web/src/enterprise/site-admin/sidebaritems.ts
Disabled some pages/routes that fail or effectively do nothing when auto-indexing is not enabled.
- [Web](https://sg-web-ef-autoindexing-disabled.onrender.com/search)
> codeintel: Improve UX when auto-indexing is disabled

- client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx
- client/web/src/enterprise/executors/instances/ExecutorCompatibilityAlert.tsx
- client/web/src/enterprise/executors/instances/ExecutorsListPage.tsx
- client/web/src/enterprise/executors/secrets/AddSecretModal.tsx
- client/web/src/enterprise/executors/secrets/UpdateSecretModal.tsx
- Fixes https://github.com/sourcegraph/sourcegraph/pull/49155
Tried to ensure tests pass with `sg test client` but getting Jest errors that I couldn't fix quickly.
Build is a-okay again
- [Web](https://sg-web-sginn-03-13-fix-update-url-paths.onrender.com/search)
> fix: update URL paths for moved docs

- CHANGELOG.md
changelog: cut sourcegraph@5.0.0
N/A
> changelog: cut sourcegraph@5.0.0

- .github/workflows/release-protector.yml
> release protector: remove unnecessary job

- doc/admin/deploy/kubernetes/configure.md
Add docs for new component added in https://github.com/sourcegraph/deploy-sourcegraph-k8s/pull/19
Run docs locally:
> docs: add imagepullsecrets kustomize guide

- doc/admin/observability/alerts.md
> add better description to blob_load_latency

- client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
**NOTE**: Enable ignore whitespace changes.
This commit cleans up the query input component a little bit by avoiding re-initializing the static extensions when the component gets re-rendered. Instead the only extension that depends on some dynamic value is moved directly into the component.
More importantly though: It avoids recreating the editor styles when navigating between the search home page and search results/repo pages (we should avoid that in all other CodeMirror instances too and I have made the necessary changes locally already, but that will be a separate PR).
Inspect CodeMirror input on search home page and search results page and verify that they both have the same CSS class names (i.e. the theme is not recreated). The `aria-*` attributes are set as well.
- …
> experimental search input: Simplify static extensions initialization

- doc/admin/observability/alerts.md
> Small correction on the blob_load_latency alert

- client/web/src/setup-wizard/components/SyncRepositoriesStep.tsx
- client/web/src/setup-wizard/components/local-repositories-step/LocalRepositoriesStep.tsx
Copy & grammar patches on Setup Wizard
- Review copy change, flag any clunky language
- [Web](https://sg-web-becca-setup-wizard-copy-patches.onrender.com/search)
> Setup Wizard copy patches

- go.mod
- go.sum
To include changes made in https://github.com/sourcegraph/embedded-postgres/commit/8f62b6947f2c0959c9b8d23911c7ad2dddfde0d8.
Close https://github.com/sourcegraph/sourcegraph/issues/48893
```
$ rm -rf ~/.embedded-postgres-go
$ rm -rf ~/Library/Application\ Support/sourcegraph-sp/postgresql/bin
$ sg start app
```
> app: bump version of github.com/sourcegraph/embedded-postgres

- internal/repos/syncer.go
Adds a comment based on this Slack thread: https://sourcegraph.slack.com/archives/C03D4H7UBEV/p1678686493434869
Just add a comment
> Add comment explaining case 2 of sync function

- doc/dev/background-information/testing_principles.md
Run `sg run docsite` and navigate to the relevant page.
> Update test type description to match the diagram

- .github/test.CODEOWNERS
Just some more dogfooding data 🤷 
n/a
> Add CODEOWNERS entries for Own team

- enterprise/internal/batches/sources/mocks_test.go
- internal/extsvc/azuredevops/client.go
- internal/extsvc/azuredevops/projects.go
- internal/extsvc/azuredevops/projects_test.go
- internal/extsvc/azuredevops/testdata/golden/ListAuthorizedUserProjects.json
- internal/extsvc/azuredevops/testdata/vcr/ListAuthorizedUserProjects.yaml
- internal/extsvc/azuredevops/types.go
- internal/extsvc/azuredevops/users_test.go
Part of #48574
Next step is to use this to list the projects during permissions sync.
1. Added tests
1. Build should passs
> azuredevops: Add client method ListAuthorizedUserProjects

- doc/dev/background-information/bazel.md
Add a FAQ entry about an issue that kept us very busy today. See the actual entry for more info.
CI.
> bzl: add a FAQ entry about cache busting

- client/shared/src/settings/settings.tsx
- client/web/src/LegacyLayout.tsx
- client/web/src/site/NeedsRepositoryConfigurationAlert.tsx
- client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
- schema/schema.go
- schema/settings.schema.json
We removed this flag before but apparently it's still with us, I think there was a bad merge and we haven't removed it completely from the code base, this PR does this
- Make sure that CI is green
> Remove setup wizard experimental feature flag

- internal/database/migration/shared/data/stitched-migration-graph.json
Main is failing because of this.
https://buildkite.com/sourcegraph/sourcegraph/builds/207007#annotation-0186e414-60fb-479c-9494-b06999c044ad-error
Lint fixes.
> lint: sg generate go

- doc/admin/observability/alerts.md
- doc/admin/observability/dashboards.md
- monitoring/definitions/frontend.go
Follow-up to adding a doc in this thread: https://sourcegraph.slack.com/archives/C03K05FCRFH/p1678737673863209.
Test plan:
CI.
> chore: add monitoring doc

- enterprise/internal/authz/azuredevops/provider.go
- enterprise/internal/authz/azuredevops/provider_test.go
In this commit we:
1. Collect a list of all orgs from the code host connections
2. Collect a list of all orgs from the specified projects in the code host connections
3. Iterate through those and only list repos of those orgs if the user already has access to it
4. Stop listing repos of the project because listing org repos already covers project repos (project is a sub-set of an org)
Fixes #48574.
👉 Checkout this loom video: https://www.loom.com/share/a7a2db7e87774fc595374cab8892460b
1. Tested locally
1. Updated tests
1. Builds should pass
> authz/azuredevops: List org repos only and skip project repos

- client/shared/src/util/url.ts
- client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
- client/web/src/enterprise/insights/components/code-insights-page/limit-access-banner/CodeInsightsLimitAccessAppBanner.tsx
- client/web/src/nav/GlobalNavbar.tsx
Closes https://github.com/orgs/sourcegraph/projects/306/views/1?pane=issue&itemId=22936209
C.f. https://github.com/sourcegraph/sourcegraph/pull/47858
- [Web](https://sg-web-ps-app-cloud-to-trial.onrender.com/search)
> App: Change Cloud language to Enterprise

- doc/admin/external_service/index.md
> Docs: fix gerrti/ado support list

- doc/admin/repo/update_frequency.md
How we configure rate-limiting needs some work 😛. But at least this should clarify things.
docs change
> Add more clarity to the rate-limiting docs

- doc/batch_changes/how-tos/configuring_credentials.md
- doc/batch_changes/references/faq.md
- doc/batch_changes/references/requirements.md
Clarifies several things that have come up through customer support channels recently.
N/A just docs changes.
> docs: misc clarifications to batches docs

- enterprise/cmd/repo-updater/internal/authz/perms_syncer_worker_test.go
@DaedalusG reported a [data race](https://buildkite.com/sourcegraph/sourcegraph/builds/206953) in this test. It's expected that a perms syncer [can be used concurrently](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3742563f711ca36e95fcc3733442a67aacfb66ac/-/blob/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go?L817-818), so this should be safe for the test constructs as well.
`go test -count 10 -race ./enterprise/cmd/repo-updater/internal/authz -run TestPermsSyncerWorker`
> Fix data race in test syncer

- internal/database/migration/shared/data/stitched-migration-graph.json
> go generate

- client/web/src/enterprise/repo/settings/RepoSettingsPermissionsPage.tsx
- client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
- client/web/src/site-admin/permissions-center/PermissionsSyncJobNode.tsx
- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.story.tsx
- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
- client/web/src/site-admin/permissions-center/backend.ts
- client/web/src/site-admin/permissions-center/styles.module.scss
- enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
Made a bunch of UI improvements to Permissions Center:
- Aligned headers for Added, Removed, Total to the right
- Added UserAvatar in place of mdiAccount icon in sync job row
- Increased size of subject icons to 24px in sync job row
- Fixed wrong calculation of ranFor when job is cancelled & startedAt is null
- Added job priority info in the details modal
- Improved details modal UI by adding colours, sections
https://www.loom.com/share/b3f7fa3f7b014a098d43f3f159316e4a
> Permissions Center UI Improvements

- .buildkite/hooks/pre-exit
Very small change, see code.
CI.
> ci: be more precise when tearing down test DBs

- client/web/src/setup-wizard/components/local-repositories-step/LocalRepositoriesStep.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-host-delete-modal/CodeHostDeleteModal.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/CodeHostCreation.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/CodeHostEdit.tsx
Follow up for https://github.com/sourcegraph/sourcegraph/pull/49348
- Check that the progress bar reacts immediately if you update local/remote repositories code hosts
- [Web](https://sg-web-vk-fix-wizard-refetch-queries.onrender.com/search)
> Fix setup wizard refetch queries API

- doc/admin/observability/dashboards.md
- enterprise/internal/codeintel/ranking/internal/store/ranking_test.go
- internal/database/migration/shared/data/stitched-migration-graph.json
Adds missing test for insert path counts
Added test
> [ranking] adding test for insert path counts

- client/web/src/components/FilteredConnection/FilterControl.module.scss
- client/web/src/setup-wizard/components/ProgressBar.module.scss
- client/web/src/setup-wizard/components/local-repositories-step/LocalRepositoriesStep.module.scss
- client/web/src/setup-wizard/components/local-repositories-step/LocalRepositoriesStep.tsx
- client/web/src/setup-wizard/components/remote-repositories-step/RemoteRepositoriesStep.module.scss
- client/web/src/setup-wizard/components/remote-repositories-step/components/navigation/CodeHostsNavigation.tsx
- client/web/src/setup-wizard/components/setup-steps/SetupSteps.module.scss
- client/web/src/site-admin/RepositoryNode.module.scss
- client/web/src/site-admin/RepositoryNode.tsx
- client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
- client/web/src/site-admin/analytics/components/index.module.scss
Manual backport based off failure [here](https://github.com/sourcegraph/sourcegraph/pull/49449#issuecomment-1472515204)
- Run from app to see all steps (sg start app)
- Test flow on all screen sizes (down to 320px screen width)
- Ensure no breaking UI
> [Backport] Setup Wizard: Mobile response styling

- internal/gitserver/addrs.go
> gRPC: add log message when we see new gitservers

- enterprise/internal/codeintel/codenav/transport/graphql/iface.go
- enterprise/internal/codeintel/codenav/transport/graphql/mocks_test.go
- enterprise/internal/codeintel/uploads/transport/graphql/iface.go
- enterprise/internal/codeintel/uploads/transport/graphql/mocks_test.go
> codeintel: Remove unused transport-layer iface methods

- doc/admin/permissions/syncing.md
Just noticed while reading docs.
- N/A
> docs: Make json look nicer by making it proper object

- client/web/src/repo/blob/codemirror/token-selection/definition.ts
Previously, triggering "go to definition" from a non-canonical revision (branch name or default/empty branch) always updated the URL to become canonical (URL gets commit SHA). Now, we try to preserve the non-canonical URL when navigating to the same commit within the same repo.
Start local server at
```
SOURCEGRAPHDOTCOM_MODE=true SOURCEGRAPH_API_URL=https://sourcegraph.com sg start web-standalone
```
* Visit URL with non-canonical branch and confirm that navigation within the revision (example: local variable) preserves the branch name. https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph@olafurpg/hl-color/-/blob/client/web/src/components/fuzzyFinder/FuzzyModal.tsx?L172:5-172:10
* Visit URL with default/empty branch and repeat. …
> Code navigation: preserve non-canonical revision when possible

- internal/singleprogram/postgresql.go
This should avoid quite a bit of logspam.
Test Plan: ran `.bin/sourcegraph` and did not see postgres log spam. Then ran the following and saw postgres logs
``` shell
SRC_LOG_LEVEL=debug .bin/sourcegraph 2>&1 | grep postgres
```
> singleprogram: log postgres binary output to logger Debug

- CHANGELOG.md
Change log entry for insight bug fix
n/a
> insights: Change log for detect & track bug fix

- enterprise/internal/codeintel/autoindexing/transport/graphql/root_resolver.go
Missed these in a previous pass.
If it compiles it's 👍
> codeintel: Remove unused autoindexing graphql resolvers

- enterprise/internal/codeintel/shared/resolvers/precise_indexes.go
Fix comment https://github.com/sourcegraph/sourcegraph/pull/49554#discussion_r1140781682
N/A.
> chore: Fix missing return

- doc/admin/config/webhooks/incoming.md
- doc/admin/external_service/azuredevops.md
This is what the section will look like:
Doc change only
> doc: Clarify batch changes doc and formatting

- internal/database/migration/shared/data/stitched-migration-graph.json
Re-generated stitched migrations after backporting migrations to 5.0 branch.
CI.
> chore: Regenerate stitched migrations (main)

- internal/database/teams.go
Amend the query in response to comment: https://github.com/sourcegraph/sourcegraph/pull/49556#discussion_r1140441398
Existing tests apply.
> Amend teams CTE query

- client/web/src/nav/StatusMessagesNavItem.mocks.ts
- client/web/src/nav/StatusMessagesNavItem.tsx
- client/web/src/nav/StatusMessagesNavItemQueries.ts
Follow up for https://github.com/sourcegraph/sourcegraph/pull/49348
- Make sure that CI is green
- [Web](https://sg-web-vk-fix-status-item-query.onrender.com/search)
> Fix status messages query

- cmd/frontend/backend/app.go
The repositories counts provided distinguish between local repositories and remote repositories (sourcegraph app only). These counts are needed so we recognize if no local repos or no remote repos are currently being sync'd (external service count is insufficient for our needs). Note that the count does not need to be accurate so long as it identifies whether the count is zero or positive.
We currently subtract local repos count from the total repos count, the latter being calculated by RepositoryStatistics. However, the local repositories count includes the same repository if it is sync'd by multiple external services. The total removes duplicates , and our check for localCount > totalCount means we return error and return `0` for each count.
In lieu of RepositoryStatistics total we now …
> Sourcegraph App Setup Experience: fix remote repositories count 

- enterprise/internal/codeintel/autoindexing/internal/background/job_dependency_indexing_scheduler.go
We suspect there might be a case where no packages are found, which would list all repos unnecessarily.
Existing test suite.
> Never list all repos in dependency indexing scheduler

- doc/admin/external_services/object_storage.md
https://sourcegraph.slack.com/archives/CHXHX7XAS/p1679423332891379
N/A
> Fix external object storage usage

- doc/admin/pings.md
Added a section on the data we're collecting for the app based on this [document](https://docs.google.com/document/d/11LueCWom986Ai0tOFs36lV_kqfJDgmqwP-NwncgKT8A/edit#). 
passing CI
> Add app telemetry to pings

- client/cody/vscode-codegen/src/completions/docprovider.ts
- client/cody/vscode-codegen/src/completions/index.ts
null
- [Web](https://sg-web-bl-cody-completion-context.onrender.com/search)
> Incorporate suffix into completions prompt

- internal/repos/github.go
Sanitizes both the repo description and the metadata description before converting a GitHub repository by removing all non-UTF-8 characters.
Verified locally by cloning github.com/Phr33d0m/NW-Profession-Bot , which has non-UTF-8 characters in the repo description.
> Add UTF-8 sanitization to both Repo description and metadata description

- doc/code_insights/explanations/administration_and_security_of_code_insights.md
Add docs for the admin section describing what is available
Previewed doc page
> insights: docs for admin section of code insights

- cmd/repo-updater/repoupdater/grpc_server.go
- cmd/repo-updater/repoupdater/server.go
Previously we synced the rate limits based on the configuration of the code host only after the code host config is validated, usually via an HTTP call to the code host API itself.
However if the rate limit is too strict, this call might fail. Applying the rate limit first fixes situations like
1. Apply too strict rate limit
2. All rate limit is consumed
3. Update the rate limit to higher value
4. the code host config is not applied, because rate limit is exceeded and the HTTP call to code host fails, hence we never get to applying the new rate limit
This genuinely happened to us when testing rate limits on rctest, we needed to restart the repo-updater service completely for the new rate limit config to be applied.
> [fix] code host rate limits must be synced first after config change

- internal/gitserver/search/match_tree.go
This reads it line by line, instead of keeping a copy of all the lines in memory. Small improvement probably, but something I saw while digging through some code and might be giving us _something_ back.
Small comparison of bufio.Scanner vs bytes.Split mem consumption over a larger file like our pnpm lock file. 
```go
func BenchmarkMemorySplit(b *testing.B) {
data, err := os.ReadFile("../../../pnpm-lock.yaml")
b.Fatal(err)
}
for i := 0; i < b.N; i++ {
for _, l := range bytes.Split(data, []byte("\n")) {
if len(l) > 10000 {
b.Fatal("long line")
}
}
}
}
func BenchmarkMemoryScan(b *testing.B) {
data, err := os.ReadFile("../../../pnpm-lock.yaml")
b.Fatal(err)
}
for i := 0; i < b.N; i++ {
sc := bufio.NewScanner(bytes.NewReader(data))
for sc.Scan() {
l := …
```
> diff search: Don't duplicate hunk body in memory

- enterprise/internal/codeintel/ranking/internal/store/ranking.go
Follow-up from #49763 where I forgot to apply these conditions consistently 🤦 
Unit tests.
> ranking: Apply conditions to hit index consistently

- cmd/frontend/internal/app/updatecheck/handler.go
- doc/admin/deploy/docker-compose/aws.md
- doc/admin/deploy/docker-compose/azure.md
- doc/admin/deploy/docker-compose/digitalocean.md
- doc/admin/deploy/docker-compose/google_cloud.md
- doc/admin/deploy/docker-compose/index.md
- doc/admin/deploy/docker-single-container/aws.md
- doc/admin/deploy/docker-single-container/digitalocean.md
- doc/admin/deploy/docker-single-container/google_cloud.md
- doc/admin/deploy/docker-single-container/index.md
- doc/admin/deploy/kubernetes/helm.md
- doc/admin/deploy/machine-images/gce.md
- doc/admin/executors/deploy_executors_kubernetes.md
- doc/admin/external_services/postgres.md
- doc/admin/external_services/redis.md
- doc/admin/http_https_configuration.md
- doc/admin/ssl_https_self_signed_cert_nginx.md
- doc/admin/updates/docker_compose.md
- doc/admin/updates/kubernetes.md
- doc/admin/updates/pure_docker.md
- doc/admin/updates/server.md
- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/operations.go
- enterprise/dev/ci/internal/ci/pipeline.go
This pull request is part of the Sourcegraph 5.0.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/48131)
> release: sourcegraph@5.0.0

- doc/app/index.md
Bump the app version on docs.sourcegraph.com/app
Also fix brew upgrade commands (just guarantee it works.)
Docs change only.
> doc: release Starship app version; fix brew upgrade commands

- internal/database/migration/definition/read.go
Saw this error locally today and `sg update` fixed the issue.
Not applicable.
> migration/definition: Suggest sg update for local dev

- internal/database/permission_sync_jobs_test.go
Follow-up to #49823 and this comment https://github.com/sourcegraph/sourcegraph/pull/49823#discussion_r1145853677
- N/A
> permission sync jobs: remove duplicated test helpers

- doc/app/index.md
Revamp app documentation & add uninstall instructions.
Docs change
> docs: app documentation revamp & uninstall instructions

- client/cody/README.md
with latest description and links.
n/a
> update cody readme

- cmd/frontend/graphqlbackend/app.go
- internal/service/servegit/service.go
We had some hardcoded coupling between implementations to ensure we initialized servegit in the same way in Init code as in the graphql handler. This makes us use the same instance of servegit.
I think this feels like a nice pattern to add onto our global service variable. Maybe instead of directly exposing Repos, it can expose some sort of struct like "Client". But I think we can evolve as we learn.
Test Plan: CI
> servegit: expose ServeGit repos function in service

- client/web/src/user/settings/emails/AddUserEmailForm.tsx
- client/web/src/user/settings/emails/UserSettingsEmailsPage.tsx
- internal/database/user_emails.go
- internal/database/user_emails_test.go
This change adds validation both in the UI while typing in the email and on the backend in a database layer.
Test plan:
https://user-images.githubusercontent.com/94846361/227489062-a26ddbce-787a-4f68-9ede-baa4902d4973.mp4
> web: fix ability to create duplicate email.

- internal/collections/set.go
- internal/collections/set_test.go
This is a thing I was long dreaming about, since our current code for dealing with permission sets is clunky to say the least.
Unit tests, it's not used anywhere yet, but plan on refactoring the perms_store as a next step.
> [feat] add set as a data structure

- doc/cody/index.md
Update Cody getting started for enterprise users
Docs only! Ran visual review
> Improve Cody getting started

- enterprise/cmd/embeddings/shared/main.go
* Tested locally with a private repo
> embeddings: use correct ctx when handling requests

- README.md
- doc/index.md
> update readme and docs index for 5.0

- client/web/dev/esbuild/server.ts
- client/web/src/enterprise/main.tsx
- package.json
- pnpm-lock.yaml
Now, after you save a file in your editor, the web browser will automatically perform a full-page reload so that your changes are reflected. See https://esbuild.github.io/api/#live-reload.
(Note: Unlike "hot module reloading", this performs a full-page reload, not an in-place reload. It's still a nice time-saver.)
n/a; dev only
- [Web](https://sg-web-sqs-esbuild-live-reload.onrender.com/search)
> use esbuild live reload

- doc/cody/index.md
docs-only
- [Web](https://sg-web-bl-cody-dotcom-docs.onrender.com/search)
> Add docs for installing Cody and enabling on sourcegraph.com

- client/cody/webviews/Chat.tsx
I found it pretty annoying that the cody UI keeps scrolling down while it's still producing new content. That makes it very hard to start reading longer messages before they're done, or reading previous ones / copying code from them. So I asked Cody for how to detect the scrolling position and made it so that it doesn't scroll anymore when the user scrolled up a bit.
Verified manually it feels better to me, lmk how it feels for others.
- [Web](https://sg-web-es-cody-less-scroll.onrender.com/search)
> cody: Don't scroll to bottom when scrolled up in transcript

- doc/admin/external_service/bitbucket_server.md
- doc/integration/bitbucket_server.md
> doc: fix typos and wrong links.

- internal/extsvc/gitlab/projects.go
- internal/repos/exclude.go
- internal/repos/gitlab.go
- internal/repos/gitlab_test.go
- internal/repos/testdata/golden/GitLabSource_makeRepo_path-pattern
- internal/repos/testdata/golden/GitLabSource_makeRepo_simple
- internal/repos/testdata/golden/GitLabSource_makeRepo_ssh
- internal/repos/testdata/sources/GITLAB/TestGitlabSource_ListRepos
- internal/repos/testdata/sources/TestGitlabSource_ListRepos.yaml
- schema/gitlab.schema.json
- schema/schema.go
[Slack thread](https://sourcegraph.slack.com/archives/C04M5M8GWCX/p1679683552428859)
Added a unit test to cover this scenario
> Add ability to exclude empty repositories in Gitlab

- client/cody/package.json
Rename, so N/A
- [Web](https://sg-web-bl-cody-rename.onrender.com/search)
> cody: rename "Sourcegraph Cody"

- enterprise/cmd/frontend/internal/codeintel/init.go
- enterprise/internal/codeintel/shared/resolvers/prefetcher.go
- enterprise/internal/codeintel/shared/resolvers/prefetcher_test.go
Remove unused struct field.
Build and tests.
> codeintel: Remove unused field

- doc/cody/index.md
> Clarify the two paths

- doc/dev/background-information/bazel.md
Document the weirdness @keegancsmith and I saw while trying to get bazel working on his nix environment
none - doc change
> bazel: document nix weirdness with CC variable

- internal/extsvc/azuredevops/client.go
- internal/extsvc/gitlab/client.go
This is the likely cause of a flake we saw in CI. It is in fact a real issue that can happen when the retry-at timestamp we get back is close to our current time. This leads to a race were the timestamp we get back from Azure or GitLab is in the past according to our clock. In the monitor API this would lead us to not retrying even though we can.
We attempted to improve the API of monitor to allow zero sleeps. But this likely breaks GitHub were we don't always get back rate limit headers. As such we updated the callsites in Azure DevOps and GitLab.
Co-authored-by: @pjlast
> extsvc: always retry if receiving a StatusTooManyRequests

- internal/extsvc/CODENOTIFY
> add myself to `extsvc` package CODENOTIFY file.

- internal/repos/exclude.go
- internal/repos/github.go
- internal/repos/gitlab.go
Added the ability to have a more generic exclude that takes a function as the exclude parameter.
Tests still pass
> Add ability to exclude repos more generically

- internal/repos/github.go
- internal/repos/github_test.go
Some code cleanup and unit test adding.
Added unit tests.
> Code cleanup for GitHub Search client

- enterprise/internal/database/perms_store_test.go
Test plan:
CI.
Follow-up to https://github.com/sourcegraph/sourcegraph/pull/50078/files in order to fix nits instead of writing nit comments on the PR.
> chore: cleanup `perms_store_test.go`.

- doc/admin/deploy/kubernetes/helm.md
This is a minor fix to the numbering that was present in this doc in certain sections and a tiny grammatical addition
No test plan required. Doc update only
> Numbered steps - minor fix

- .github/test.CODEOWNERS
- cmd/frontend/internal/search/CODENOTIFY
- internal/search/CODENOTIFY
> Set up code notifications for jtibs

- enterprise/internal/database/BUILD.bazel
> bazel: run configure

- .github/workflows/move-labled-issues-to-project.yml
> Move cody labeled issues to board

- client/branded/src/search-ui/components/RepoFileLink.tsx
- client/branded/src/search-ui/results/StreamingSearchResultsList.tsx
Tested locally, works fine.
Temp change
- [Web](https://sg-web-dv-results-nit.onrender.com/search)
> Results nit

- doc/cody/index.md
Minor docs update following user input.
Visual review of docs
> Add screenshot to .com instructions

- client/web/src/site-admin/permissions-center/PermissionsSyncJobNode.tsx
- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.story.tsx
- client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
- client/web/src/site-admin/permissions-center/backend.ts
- cmd/frontend/graphqlbackend/authz.graphql
- cmd/frontend/graphqlbackend/permissions_sync_jobs.go
- enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
- enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
Test plan:
Updated unit and GraphQL tests.
https://user-images.githubusercontent.com/94846361/228882541-3df00446-e9f6-46c2-9903-f6e0503d9aef.mp4
> permissions-center: add support for partial status in API and UI.

- cmd/frontend/graphqlbackend/schema.graphql
Verified locally on the VS Code debug console.
> Modify graphql schema with Cody event source

- enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
- enterprise/cmd/worker/internal/permissions/bitbucket_projects_test.go
- enterprise/internal/database/perms_store.go
- internal/authz/perms.go
- internal/collections/set_test.go
- internal/collections/slice_utils.go
The title says it all ✅ 
unit tests should cover this
> chore: use `Set[T]` instead of `map[T]struct{}` and remove dead code

- cmd/gitserver/server/cleanup.go
PR #38307 changed this behaviour, but this comment remained. Just ran into this and thought "that can't be right?" and well, let's fix it :)
- NA
> Update outdated code comment

- client/cody/CONTRIBUTING.md
- client/cody/package.json
- client/cody/scripts/release.ts
- dev/ci/runtype/runtype.go
- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/operations.go
- enterprise/dev/ci/internal/ci/pipeline.go
Inspired by out VS Code setup. This may need some trial and error as I figure out the exact CI steps so bear with me.
- Get the release tokens in properly => should work now but we might need to update the tokens on CI if they no longer work
- Changelog process? => Decided to skip this for now since we don't have a changelog
- We'll test with the 0.0.4 release
> Cody: Add release automation

- client/cody/package.json
Bumping the version number for the 0.0.4 release as discussed in [slack](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1680253929682909).
We'll use the automation from #50216 to publish.
- Tested the build locally
- [Web](https://sg-web-ps-cody-release-0-0-4.onrender.com/search)
> Cody: Release 0.0.4

- client/web/src/enterprise/site-admin/cody/backend.ts
* Inserted a bunch of jobs into the db, and tried out if pagination works in UI
- [Web](https://sg-web-rn-fix-embedding-jobs-pagination.onrender.com/search)
> embeddings ui: fix pagination

- enterprise/cmd/embeddings/shared/repo_embedding_index_cache.go
- enterprise/cmd/embeddings/shared/repo_embedding_index_cache_test.go
Acquire a mutex for the given repository to serialize access when downloading/getting the repo embedding index. This avoids multiple routines concurrently downloading the same embedding index when the cache is empty, which can lead to an out-of-memory error.
* Tested with a script creating multiple concurrent requests. (Found a deadlock in the original commit that way and fixed it.)
> embeddings: per repo mutex when getting/downloading an index

- enterprise/internal/embeddings/index_storage.go
- enterprise/internal/embeddings/index_storage_test.go
Implemented a couple of suggestions from my code review.
> embeddings: encode RepoEmbeddingIndex in chunks suggestions

- client/branded/src/search-ui/components/RepoFileLink.tsx
- client/branded/src/search-ui/results/StreamingSearchResultsList.tsx
(Just a revert)
- [Web](https://sg-web-dv-results-nit2.onrender.com/search)
> Revert PR#50153

- WORKSPACE
- deps.bzl
- enterprise/internal/codeintel/shared/types/BUILD.bazel
- enterprise/internal/codeintel/uploads/internal/background/BUILD.bazel
- enterprise/internal/codeintel/uploads/shared/BUILD.bazel
> Update buildfiles 03/04

- client/cody-ui/BUILD.bazel
- internal/database/event_logs.go
Visual check of built query, to be verified in BigQuery.
> Fix bug with current period usage statistics calculation

- cmd/frontend/graphqlbackend/external_account_data_resolver.go
- enterprise/cmd/frontend/internal/auth/saml/user.go
closes: https://github.com/sourcegraph/customer/issues/2029
https://github.com/sourcegraph/customer/issues/2029#issuecomment-1488038762
Visit the external accounts page.
> Fix external accounts data resolver

- cmd/blobstore/build.sh
- cmd/frontend/build.sh
- cmd/frontend/pre-build.sh
- cmd/github-proxy/build.sh
- cmd/gitserver/build.sh
- cmd/loadtest/build.sh
- cmd/migrator/build.sh
- cmd/repo-updater/build.sh
- cmd/searcher/build.sh
- cmd/worker/build.sh
- enterprise/cmd/frontend/build.sh
- enterprise/cmd/frontend/pre-build.sh
Adding a defauilt value for the Docker Bazel variable used in the build scripts
ran the script locally to see how it works with and without the variable set
> add default value for DOCKER_BAZEL

- enterprise/cmd/frontend/build.sh
Missed a dash for the default value 😑 
green ci
> fix bash default for frontend build

- .bazelrc
- BUILD.bazel
- client/cody-ui/BUILD.bazel
- client/web/BUILD.bazel
- cmd/frontend/BUILD.bazel
- cmd/frontend/build.sh
- cmd/frontend/pre-build.sh
- enterprise/cmd/frontend/BUILD.bazel
- enterprise/cmd/frontend/pre-build.sh
- ui/assets/BUILD.bazel
- ui/assets/assets_dist.go
- ui/assets/load_manifest_dist.go
My PR from 61876fbf561b860aa5db61401afca5f55d020a38 is failing to pass e2e tests, I must have missed something. 
CI
> Revert docker bazel frontend 

- enterprise/internal/codeintel/autoindexing/internal/store/store.go
- enterprise/internal/codeintel/codenav/internal/lsifstore/lsifstore.go
- enterprise/internal/codeintel/policies/internal/store/store.go
- enterprise/internal/codeintel/ranking/internal/store/store.go
- enterprise/internal/codeintel/uploads/internal/lsifstore/lsifstore.go
- enterprise/internal/codeintel/uploads/internal/store/store.go
Another pass at categorizing our store interfaces into behavior domains.
N/A.
> codeintel: Reorganize store interface categories

- doc/code_navigation/how-to/configure_data_retention.md
- doc/code_navigation/how-to/index.md
- doc/code_navigation/how-to/index_a_go_repository.md
- doc/code_navigation/how-to/index_a_typescript_and_javascript_repository.md
- doc/code_navigation/index.md
- doc/code_search/reference/language.md
- doc/code_search/reference/structural.md
Reopened https://github.com/sourcegraph/sourcegraph/pull/50302 rebased on main for bazel changes
N/A docs only
> Ritza editing march 2023

- client/web/src/enterprise/insights/pages/insights/insight/components/actions/CodeInsightIndependentPageActions.tsx
Fixing a typo
my eyes
- [Web](https://sg-web-cclark-fix-tooltip.onrender.com/search)
> fix typo in tooltip

- CHANGELOG.md
- dev/release/release-config.jsonc
> chore: prepare 5.0.1

- enterprise/internal/codeintel/ranking/internal/background/job_graph_exporter.go
🤦 
Note: 5.0 branch has this correct, this was a copy-and-paste error during a subsequent refactor.
N/A.
> ranking: Fix bad vacuum targets

- enterprise/internal/codeintel/autoindexing/service.go
- enterprise/internal/codeintel/codenav/transport/graphql/util_locations.go
- enterprise/internal/codeintel/services.go
- enterprise/internal/codeintel/uploads/transport/graphql/precise_index_resolver.go
- internal/codeintel/dependencies/internal/store/scan.go
- internal/codeintel/dependencies/internal/store/store.go
> lint: Remove unreferenced code

- client/web/src/integration/BUILD.bazel
green ci
- [Web](https://sg-web-wb-bazel-integration-tests-flaky.onrender.com/search)
> bazel: mark integration tests as flaky

- client/web/BUILD.bazel
- client/web/src/featureFlags/featureFlags.ts
- client/web/src/hooks/useUserExternalAccounts.ts
- client/web/src/site-admin/SiteAdminArea.tsx
- client/web/src/site-admin/sidebaritems.ts
Backport #45827 as part of a security vulnerability fix.
CI
> [Backport 5.0] cloud: hide o11y for non-operator users

- .github/workflows/sg-setup.yml
- .tool-versions
- WORKSPACE
- cmd/symbols/Dockerfile
- dev/build-tracker/Dockerfile
- dev/ci/integration/code-intel/install-src.sh
- dev/sg/checks.go
- docker-images/opentelemetry-collector/Dockerfile
- internal/cmd/git-combine/Dockerfile
- internal/cmd/progress-bot/Dockerfile
- internal/cmd/search-blitz/Dockerfile
- internal/cmd/tracking-issue/Dockerfile
Fixing accidentally missed backport
N/A
> backport 50341 to 5.0

- cmd/frontend/internal/app/updatecheck/handler.go
- doc/admin/deploy/docker-compose/aws.md
- doc/admin/deploy/docker-compose/azure.md
- doc/admin/deploy/docker-compose/digitalocean.md
- doc/admin/deploy/docker-compose/google_cloud.md
- doc/admin/deploy/docker-compose/index.md
- doc/admin/deploy/docker-single-container/aws.md
- doc/admin/deploy/docker-single-container/digitalocean.md
- doc/admin/deploy/docker-single-container/google_cloud.md
- doc/admin/deploy/docker-single-container/index.md
- doc/admin/deploy/kubernetes/helm.md
- doc/admin/deploy/machine-images/gce.md
- doc/admin/executors/deploy_executors_kubernetes.md
- doc/admin/external_services/postgres.md
- doc/admin/external_services/redis.md
- doc/admin/http_https_configuration.md
- doc/admin/ssl_https_self_signed_cert_nginx.md
- doc/admin/updates/docker_compose.md
- doc/admin/updates/kubernetes.md
- doc/admin/updates/pure_docker.md
- doc/admin/updates/server.md
This pull request is part of the Sourcegraph 5.0.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/50405)
> release: sourcegraph@5.0.1

- client/web/src/enterprise/cody/search/CodySearchPage.tsx
- client/web/src/repo/repoRevisionSidebar/cody/RepoRevisionSidebarCody.tsx
n/a
- [Web](https://sg-web-sqs-codysearch-logging.onrender.com/search)
> add telemetry for /cody/search and cody sidebar

- doc/cody/index.md
> cody: add docs on the excludedFilePathPatterns setting and how to enable codebase-aware answers

- doc/dev/background-information/bazel.md
Small entry in case somebody else runs into the same issue.
> docs: Bazel: Add FAQ entry about artifact exclusion in IDEs

- client/cody/package.json
follow https://github.com/sourcegraph/sourcegraph/blob/main/client/cody/CONTRIBUTING.md#release-steps
CI
- [Web](https://sg-web-04-06-client-cody-release-0-0-5.onrender.com/search)
> client/cody: release 0.0.5

- doc/cody/index.md
> Add link to the handbook

- doc/cody/index.md
> Move prerequisites to the doc

- doc/cody/index.md
Clarification to avoid confusion. We should not recommend this to prospects: this is just for individuals/community
Visual check
> Clarify sourcegraph.com is only for public code

- doc/cody/index.md
Users make their own decision based on our terms.
See https://sourcegraph.slack.com/archives/C04M7M2AHFY/p1681109756330319
Docs, no functional change
> Remove public code mentions except embeddings

- cmd/gitserver/server/cleanup.go
- cmd/gitserver/server/cleanup_test.go
- cmd/gitserver/server/repo_info.go
> cleanup: make logging consistent, clean up code.

- client/web/src/enterprise/cody/search/CodySearchPage.tsx
- client/web/src/enterprise/cody/search/translateToQuery.ts
- client/web/src/enterprise/routes.tsx
- Updated Cody Web Search Prompt Context to cover a lot more filters and use them in combination.
The following queries gave good results:
1. Find symbol translateToQuery in Sourcegraph repo\
2. Find translateToQuery in Sourcegraph repos excluding httpclient 
3. Find symbol translateToQuery in Sourcegraph repo excluding httpclient repo
4. Diff from branch naman/condition-cody-web on sourecegraph repository
5. find changes to RepositoryResolver under commit 0526edb for sourcegraph repo
6. changes to graphqlbackend in commit 0526edb on sourcegraph repo
7. files in frontend directory in sourcegraph repo
8. find graphql schema file which defined permissionsSyncJobs in graphqlbackend directory in sourcegraph repo
9. find changes to schema.graphql file in sourcegraph repo by @naman
10. find …
> Prompt engineering and updates for cody magical web search [no-bazel]

- client/web/BUILD.bazel
Ran `bazel configure` after [this PR](https://buildkite.com/sourcegraph/sourcegraph/builds/212514). 
CI passes
- [Web](https://sg-web-cc-fix-bazel.onrender.com/search)
> Bazel: fix client build

- client/cody/src/completions/index.ts
Wait a bit longer to trigger a completions-initiated request to the LLM. We estimate the LLM response latency to be 700ms, so subtract from the desired wait time to get the desired time to wait before sending the request so as to approximately attain the desired end user wait time.
Cody-only, tested locally
- [Web](https://sg-web-bl-completion-trigger.onrender.com/search)
> cody: trigger autocomplete less aggressively

- client/cody/src/completions/index.ts
Removing debug printf
- [Web](https://sg-web-bl-remove-printf.onrender.com/search)
> remove debug statement

- doc/dev/background-information/bazel.md
> docs: add a FAQ entry for "no-bazel"

- doc/cody/index.md
> Disabling Cody

- .github/workflows/sg-binary-release.yml
This should fix the issues with the glibc. 
CI
> sg: do not release with CGO enabled

- enterprise/cmd/executor/kubernetes/README.md
- enterprise/internal/codeintel/uploads/transport/graphql/index_steps_resolver.go
This PR fixes two types in the regex used in the step resolver.
> Fix k8s logkey regex

- doc/admin/executors/deploy_executors_kubernetes.md
Add additional docs about firewall rules.
No tests - just docs.
> Add docs about firewall rules for executors on K8s

- client/jetbrains/standalone/src/index.html
- client/jetbrains/webview/BUILD.bazel
- client/jetbrains/webview/src/bridge-mock/call-java-mock.ts
- client/jetbrains/webview/src/search/index.tsx
This PR fixes the JetBrains extension standalone build and an issue in the JavaScript resources caused by a missing top-level React router.
- [Web](https://sg-web-ps-fix-jetbrains-standalone.onrender.com/search)
> JetBrains: Fix standalone build

- enterprise/cmd/embeddings/shared/context_detection.go
- enterprise/cmd/embeddings/shared/context_detection_test.go
Add one more pattern that proved valuable.
New unit test, manual tests.
> Cody: more required context patterns

- doc/code_navigation/references/indexers.md
> Documentation: add row for C# status

- doc/cody/index.md
> Update cody doc index.md

- cmd/gitserver/Dockerfile
- cmd/server/Dockerfile
- docker-images/alpine-3.14/Dockerfile
- enterprise/cmd/batcheshelper/Dockerfile
- enterprise/cmd/bundled-executor/Dockerfile
- enterprise/cmd/executor-kubernetes/Dockerfile
- enterprise/cmd/executor/docker-image/Dockerfile
- enterprise/cmd/gitserver/Dockerfile
- Manually checked version locally
> Update to use curl from Alpine 3.17

- client/web/src/enterprise/cody/search/CodySearchPage.tsx
- client/web/src/enterprise/cody/search/translateToQuery.ts
- client/web/src/search/results/SearchResultsInfoBar.module.scss
- client/web/src/search/results/SearchResultsInfoBar.tsx
- client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
- Added Feedback loop
- Added Link to Magical Search on the default search page
- prompt improvements
- visit /search/cody
- [Web](https://sg-web-naman-cody-feedback.onrender.com/search)
> Add magical search feedback loop

- doc/admin/updates/kubernetes.md
Fixing formatting issues based on customer feedback
None required, formatting fix.
> fixed version formatting

- doc/dev/background-information/bazel.md
Test plan:
N/A.
Follow up to https://sourcegraph.slack.com/archives/C04MYFW01NV/p1681387676061919
> docs: add an FAQ entry about untracked files affecting `bazel configure`.

- client/cody/package.json
Release Cody v0.0.6
Version bump.
- [Web](https://sg-web-cody-v005.onrender.com/search)
> cody release v0.0.6

- client/web/src/enterprise/cody/search/CodySearchPage.tsx
- client/web/src/search/results/SearchResultsInfoBar.tsx
updates logging to also send data to BQ.
- [Web](https://sg-web-ak-send-events-to-bq.onrender.com/search)
> log events to both public_args and args so that it makes it to BQ

- enterprise/cmd/frontend/internal/completions/streaming/openai/openai.go
> cody: catch invalid param values for gpt-4

- client/cody-ui/BUILD.bazel
- client/cody-ui/package.json
- client/cody-ui/src/Chat.module.css
- client/cody-ui/src/Chat.tsx
- client/cody-ui/src/chat/ChatMessageLoading.module.css
- client/cody-ui/src/chat/ChatMessageLoading.tsx
- client/cody-ui/src/chat/ChatMessageRow.module.css
- client/cody-ui/src/chat/ChatMessageRow.tsx
- client/cody-ui/src/chat/ChatMessages.module.css
- client/cody-ui/src/chat/ChatMessages.story.tsx
- client/cody-ui/src/chat/ChatMessages.tsx
- client/cody/webviews/index.css
- client/storybook/src/main.ts
No behavior change.
- extract cody-ui ChatMessages and add storybook
- split apart cody-ui ChatMessages component
- remove duplicate cody vscode CSS vars
n/a; refactor only
- [Web](https://sg-web-sqs-cody-chat-ui-refactor.onrender.com/search)
> cody-ui chat refactors

- client/cody/webviews/Chat.tsx
This makes it faster to use Cody with just the keyboard. The user can immediately start typing to Cody after invoking `Cody: Focus on Chat View` with the keyboard.
Run extension in debug mode. Hit Opt+/ to open webview. The textarea should be focused. Click back to a file. Hit Opt+/ to focus the webview. The textarea should be focused again.
- [Web](https://sg-web-sqs-cody-focus.onrender.com/search)
> focus cody textarea when webview is opened and/or focused

- client/cody/src/chat/ChatViewProvider.ts
- client/cody/src/chat/protocol.ts
- client/cody/webviews/App.tsx
- client/cody/webviews/utils/VSCodeApi.ts
n/a; internal refactor only
- [Web](https://sg-web-sqs-cody-typed-protocol.onrender.com/search)
> use types for cody webview<->exthost protocol

- client/cody-ui/src/Chat.module.css
- client/cody-web/src/Chat.module.css
This was not actually taking effect anywhere due to overrides.
n/a; minor code cleanup
- [Web](https://sg-web-sqs-cody-tinyfix.onrender.com/search)
> remove big and ineffective cody message border-radius

- client/web/src/cody/CodyChat.module.scss
- client/web/src/cody/CodyChat.tsx
Closes #50676
Various UI fixes:
- Fixes the layout so that the input box is always shown, even when scrolled (and prevent double scrollbars)
- Increases list item paddings (otherwise it would barely work for numbers >9)
- Better align submit button
- [Web](https://sg-web-ps-cody-web-fixes.onrender.com/search)
> Cody web: Various UI fixes

- client/cody/package.json
Includes "fixup" and new README
- N/A
> Release Cody 0.0.7

- dev/sg/dependencies/shared.go
The command adds the plugin but the instructions are missing it.
- N/A
> sg: add pnpm plugin to instructions

- CHANGELOG.md
Add change log entry for insights over no repos fix.
> insights: Change log for insights over no repos

- client/cody-ui/src/chat/actions/TranscriptAction.tsx
> use common <Icon />

- CHANGELOG.md
just changelog change, no tests
> chore: add changelog entry for #50638

- CHANGELOG.md
> Add changelog entry for #50584

- CHANGELOG.md
> Add changelog entry for 50668

- CHANGELOG.md
> Changelog update for: Modify gitserverClient.ListFiles to speed up embeddings

- doc/_resources/assets/docsite.css
- doc/_resources/templates/root.html
- Updates to the latest version of the Markprompt web component. The latest version:
- Adds supports for CSS variables for more style configuration options
- Fixes the image width
- Adds support for custom prompt templates.
- Updates the CSS variables for light and dark mode.
- Uses a custom prompt template to inject base path for relative links.
Doc site only.
> Add CSS variables for UI configuration

- doc/code_navigation/references/indexers.md
> Documentation: use correct background color for C# row

- enterprise/internal/codeintel/uploads/internal/background/init.go
- internal/observation/context.go
Does what it says on the tin :chart_with_downwards_trend: :bee: 
N/A honeycomb specific stuff
> codeintel: dont emit codeintel-worker resetter events to honeycomb

- enterprise/internal/github_apps/store/store.go
- enterprise/internal/github_apps/store/store_test.go
> feat: add GetByAppID and GetBySlug to github apps store

- enterprise/dev/ci/internal/ci/bazel_operations.go
- enterprise/dev/ci/internal/ci/operations.go
- enterprise/dev/ci/internal/ci/pipeline.go
This argument is always false.
Test Plan: CI
> ci: remove bazel optional boolean

- doc/code_navigation/index.md
- doc/code_navigation/references/indexers.md
Two small changes:
* List C# as partially available for precise intelligence
* Update Ruby to GA for precise intelligence
Docs only
> Adding C# precise support, update Ruby precise status
