sourcegraph/sourcegraph-public-snapshot

client/web/BUILD.bazel
Decrease by 1 again. Follow-up to https://sourcegraph.slack.com/archives/C02FLQDD3TQ/p1682001328723939
CI
=> Reduce shard count for //client/web:test

dev/sg/sg_ci.go
I merged with this comment still in the PR
None - comment removal
=> remove left over debug comment

cmd/frontend/internal/app/updatecheck/handler.go, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/deploy/machine-images/gce.md, doc/admin/executors/deploy_executors_kubernetes.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md
This pull request is part of the Sourcegraph 5.0.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/50811)
=> release: sourcegraph@5.0.2

dev/release/release-config.jsonc
=> chore: close 5.0.2

client/branded/src/search-ui/components/SmartSearchPreview.tsx
`useMemo` optimization follow up to #50606
- Ensure CI builds successfully
=> #50606 follow up

doc/dev/setup/troubleshooting.md
Hopefully this saves someone some time in future. 
n/a doc update
=> add sg start tips for rosetta

enterprise/cmd/frontend/internal/completions/streaming/stream.go
This copies what we just did for code completions. It will be interesting to have this data.
=> completions: add honeycomb event for stream

.buildkite/pipeline.yml
Hopefully this makes this step much faster. Stole the command from @burmudar 
Test Plan: CI works for this PR
=> ci: use bazel for generate pipeline step

client/cody/package.json
=> Release Cody 0.0.8

doc/dev/background-information/build_p4_fusion.md
Tested it earlied this week. Quick fix to keep doc up to date.
Doc change only.
=> build_p4_fusion: Tested with nix 2.15.0

client/cody/src/chat/ChatViewProvider.ts
Continuing https://github.com/sourcegraph/sourcegraph/pull/50544
Cody is experimental. Verified locally.
- [Web](https://sg-web-bl-deepak2431-cody-file-links-fix.onrender.com/search)
=> Cody: Implemented cody to open file in Sourcegraph view

doc/cody/explanations/enabling_cody.md
Fixing broken link.
Docs only.
=> Update enabling_cody.md for broken link

client/cody/src/chat/ChatViewProvider.ts
Main is currently failing with this error https://buildkite.com/sourcegraph/sourcegraph/builds/214585#0187a4ef-a948-4be9-b7b7-d993e16b22ff
Green CI
=> cody: fix serverEndpoint access

client/cody/webviews/Login.module.css, client/cody/webviews/Login.tsx, client/cody/webviews/storybook/VSCodeStoryDecorator.module.css
Just some minor tweaks based on my personal opinion (100% open to pushback!).
- Remove icons (which just added visual noise IMO)
- Improve spacing
View login screen in Cody extension.
=> make the login form look nicer

CHANGELOG.md
just changelog change, no test needed
=> chore: modify changelog with link to the bitbucket server logs fix

enterprise/internal/codeintel/autoindexing/service.go
This pull request aims to remove unnecessary dependencies in the auto indexing service codebase. Upon reviewing the current code, it was found that some dependencies are no longer being used and only add unnecessary overhead to the application.
The following dependencies have been identified for removal:
- inference service
- logger
By removing these dependencies, we can improve the overall performance and maintainability of the auto indexing service. This change does not affect any of the existing functionalities of the service.
The changes in this pull request have been thoroughly tested and reviewed to ensure that they do not cause any unintended consequences or regressions. If there are any concerns or questions regarding this pull request, please do not hesitate to raise them in the …
=> [language-platform] Remove unnecessary dependencies in Autoindexing service

.github/workflows/batches-notify.yml
Updates who gets pinged on comment where batch changes team is mentioned:
- Removes Malo 😢
- Adds Ryan
- Adds Becca
N/A just a GH workflow change.
=> batches: update pings for batches notify

doc/admin/auth/saml/azure_ad.md
Reported by customer in ticket [13558](https://sourcegraph.zendesk.com/agent/tickets/13558)
Test in prod
=> Correcting email address claim name from customer feedback

enterprise/internal/licensing/features.go
Saw this in #51075 and decided that a small helper would, well, help.
- Existing
=> licensing: add helpers to reduce duplicated error message

client/cody-shared/src/chat/client.ts, client/cody-shared/src/chat/transcript/index.ts, client/cody-shared/src/chat/transcript/interaction.ts, client/cody-shared/src/codebase-context/index.ts, client/cody-ui/src/chat/Transcript.tsx, client/cody-web/src/App.tsx, client/web/BUILD.bazel, client/web/src/cody/ChatHistory.module.scss, client/web/src/cody/ChatHistory.tsx, client/web/src/cody/CodyChat.tsx, client/web/src/stores/codyChat.ts
Added UI for Cody web chat history. 
Demo: https://www.loom.com/share/1423f730385a4a189dc4fddcce96b452
- Open Ask Cody and visit history section.
=> Add cody web history ui

client/cody/src/chat/ChatViewProvider.ts
RE: https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1682434113130529
Log sign-in events (`CodyVSCodeExtension:login:clicked`) on all validated login sessions
All tests are passed.
=> cody: log login events

doc/admin/observability/dashboards.md, monitoring/definitions/frontend.go
Test Plan: copy-pasta the query into grafana query explorer.
=> monitoring: add dashboard for request rates to Cody REST endpoints

client/cody-shared/BUILD.bazel, client/cody-shared/src/telemetry/EventLogger.ts, client/cody/src/event-logger.ts
=> Move Cody version fetch to main Cody package

.bazeliskrc, client/shared/src/testing/BUILD.bazel
Upgrading `bazel-cli` to the latest version.
CI
=> bazel: upgrade bazel-cli

client/cody-shared/src/chat/client.ts, client/cody-ui/src/chat/Transcript.tsx, client/web/src/stores/codyChat.ts
Revert changes to Transcript Component regarding not showing last message if a message is in progress. Rather moved that logic to the Cody shared client.
- needs testing on vs code
=> Fix Transcript UI

client/cody/webviews/App.story.tsx, client/cody/webviews/Login.story.tsx
Fixes some errors in the storybook that prevented them from being run properly by Chromatic. Look at the diffs now 😎 
https://www.chromatic.com/pullrequest?appId=5f0f381c0e50750022dc6bf7&number=51145
=> Cody: Fix storybook

dev/sg/internal/sgconf/config.go
yep
ran locally, :eye: on output, all :heavy_check_mark:
=> sg: merge bazelCommands too

cmd/migrator/build.sh
This didn't get updated for 5.0.2
N/A
=> add 5.0.1 and 5.0.2

doc/dev/background-information/ci/reference.md, enterprise/dev/ci/internal/ci/operations.go, enterprise/dev/ci/internal/ci/pipeline.go
These got changed during the [migration to bazel](https://github.com/sourcegraph/sourcegraph/commit/5b198be1b47c52bb72d64c1afc3e54383def2358)
CI
=> ci: fix executor step keys

enterprise/internal/codeintel/ranking/internal/background/exporter/job.go, enterprise/internal/codeintel/ranking/internal/lsifstore/store.go, enterprise/internal/codeintel/ranking/internal/store/store.go, enterprise/internal/codeintel/ranking/mocks_test.go
=> ranking: Fix transaction safety when exporting uploads

CHANGELOG.md
No testing, just changelog update 🤷
=> chore: update changelog with fix for search contexts

client/cody-shared/src/chat/client.ts, client/cody-shared/src/sourcegraph-api/completions/browserClient.ts, client/web/src/cody/CodyChat.module.scss
=> Cody Web: Error handling, especially for rate limits

client/cody/CHANGELOG.md
Trying to document all the changes we have made since last Friday for v0.0.9. 
Feel free to make changes directly to this PR if i missed anything!
docs change, test plan not required
=> Cody: add changelog

client/cody/package.json
Preparing for a new release by pushing the version number.
Only a version number change.
=> Cody: Release 0.0.9

cmd/frontend/graphqlbackend/BUILD.bazel, cmd/frontend/graphqlbackend/user_usage_stats.go, cmd/frontend/hubspot/hubspotutil/hubspotutil.go
Run Sourcegraph locally to confirm no errors
=> Add hubspot event for Cody installation events

client/cody-shared/src/chat/transcript/messages.ts, client/cody/CHANGELOG.md, client/cody/package.json, client/cody/src/chat/ChatViewProvider.ts, client/cody/src/chat/protocol.ts, client/cody/src/command/LocalStorageProvider.ts, client/cody/src/main.ts, client/cody/webviews/App.tsx, client/cody/webviews/Chat.module.css, client/cody/webviews/Chat.tsx, client/cody/webviews/Settings.tsx, client/cody/webviews/UserHistory.css, client/cody/webviews/UserHistory.tsx
Closes #51101 
Tested all sorts of variations (empty and save, loading and saving different sessions over and over again, etc.) locally in VSCode and everything seems fine.
=> Fix history display/clear, add history load in VSCode

CHANGELOG.md
No test, only changelog change
=> chore: add change from #51255 to changelog

doc/cody/explanations/enabling_cody.md
Update Cody extension instructions (no longer need to request access in Discord or set the access token). 
N/A docs change
=> Update VS Code instructions

.bazelrc, .gitignore, WORKSPACE, dev/nix.bzl, dev/nix/001-rules-rust-cargo-bazel-env.patch, dev/nix/shell-hook.sh, shell.nix
Some sprinkling of special sauce for the NixOS (and nix shell) users in the house. Much care has been taken so that there should be no interference with anyone running bazel on a non-nixos machine, and that it also works as (mostly) expected for nix shell users on macos.
Ran main dry-run, all green, so it shouldnt interfere with anyone on a non-nixos machine
=> bazel: make work on nixos :sparkle: 

CHANGELOG.md
CHANGELOG update for #50353. Let me know if any language is clunky!
- CI/CD & language
=> CHANGELOG update for #50353

CHANGELOG.md
#50353 CHANGELOG copy update
- CI/CD & language
=> #50353 CHANGELOG copy update

doc/dev/how-to/testing.md
I was [only able to find this in an old Slack thread](https://sourcegraph.slack.com/archives/C01C3NCGD40/p1682719466691839?thread_ts=1682718804.031389&cid=C01C3NCGD40), there were no mentions of it anywhere in the docs that I could find, and the command previously documented no longer works :( 
this command works
=> testing: document how to update react snapshots

doc/cody/index.md
Update to docs for Cody start flow.
Docs only
=> Update index.md (cody docs)

doc/dev/background-information/index.md, doc/dev/background-information/sql/index.md, doc/dev/background-information/sql/migrations_overview.md
Ported the [Google Doc](https://docs.google.com/document/d/1iS9fbVYtWmTrrtz_Xs5HEhqpHNMKP5h16MitA-u7K3Y/edit#). 
n/a
=> doc: add "Migrations overview" page

dev/release/release-config.jsonc
=> release: activate 5.0.3

doc/cody/explanations/enabling_cody_enterprise.md
Closes https://github.com/sourcegraph/sourcegraph/issues/50632
docs
=> Selectively enabling Cody

doc/cody/explanations/code_graph_context.md
Doc update per 
https://sourcegraph.slack.com/archives/C03JR7S7KRP/p1682983762721699?thread_ts=1681503687.120539&cid=C03JR7S7KRP
n/a
=> Add mention for Sourcegraph Cloud customers

docker-images/prometheus/Dockerfile.bazel
Perms for some config files are incorrect with the new Dockerfile. This fixes it. 
Context: https://sourcegraph.slack.com/archives/C04MYFW01NV/p1682714634182829
- inspecting the files permissions in the newly built container.
=> containers: fix prometheus permissions 

enterprise/internal/codeintel/autoindexing/internal/background/job_summary_builder.go
(cherry picked from commit 3cc9006de32c922eb412b65349a6e0cc24208b87)
=> autoindexing: Guard summary builder with config flag (#51356)

client/wildcard/src/components/Button/story/Button.story.tsx, dev/ci/post-chromatic.sh, package.json, pnpm-lock.yaml
Fixing the script that posts Chromatic deployments links to the PR.
CI and comments in this PR
=> ci: fix chromatic preview script

client/wildcard/src/components/Button/story/Button.story.tsx, dev/ci/post-chromatic.sh
Change the Chromatic preview message
CI
=> ci: update the Chomatic preview message

.github/workflows/scip-go.yml
=> scip-go: nit ci fixups

src-tauri/README.md
Add Tauri readme
none - doc change
=> app: add Tauri readme

CHANGELOG.md
Just a quick update to the changelog before the patch cut.
N/A
=> Embeddings: update changelog with embeddings notes

CHANGELOG.md
Part of https://github.com/sourcegraph/sourcegraph/issues/51302
n/a
=> chore: cut CHANGELOG for 5.0.3

doc/app/index.md, doc/app/troubleshooting.md
This PR introduces a troubleshooting page for app with an installation troubleshoot and fix for an App binary install.
No test plan required. Doc update.
=> Create App troubleshooting guide

cmd/frontend/internal/app/updatecheck/handler.go, cmd/migrator/build.sh, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/deploy/machine-images/gce.md, doc/admin/executors/deploy_executors_kubernetes.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md
This pull request is part of the Sourcegraph 5.0.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/51302)
cc @unknwon
=> release: sourcegraph@5.0.3

dev/release/release-config.jsonc
=> release: wrap up 5.0.3 release

.github/workflows/scip-typescript.yml, client/wildcard/src/components/Button/Button.tsx
Requires the `pnpm` version bump too.
CI
=> ci: fix scip-typescript

enterprise/cmd/frontend/worker/auth/perms_syncer_scheduler.go, enterprise/cmd/frontend/worker/auth/perms_syncer_scheduler_test.go, enterprise/cmd/repo-updater/internal/authz/perms_syncer.go, schema/schema.go, schema/site.schema.json
backport of #51255
- #51255
just a site config schema change, tested locally
=> [Backport 5.0] feat: allow disabling of user centric or repo centric permission sync

client/cody-shared/src/chat/client.ts, client/cody-web/src/settings/useConfig.ts, client/web/src/stores/codyChat.ts
Opening up as draft because I'm not sure about the changes we (@eseliger and I) made here, but it fixed it locally.
- Manual testing of talking to Cody locally
=> cody web ui: fix cody in web not working locally

dev/nix/comby.nix, dev/nix/p4-fusion.nix
=> nix: run nix fmt

client/cody/CHANGELOG.md, client/cody/package.json
Just a changelog and version change
=> Cody: Release 0.0.10

client/cody-ui/src/Chat.tsx, client/cody/CHANGELOG.md, client/cody/src/chat/ChatViewProvider.ts, client/cody/src/chat/protocol.ts, client/cody/webviews/Chat.tsx
Adds logging to the chat prediction experimental feature.
https://user-images.githubusercontent.com/458591/236258186-697fcbfb-1ce8-45dd-8703-86a1e7b8dbee.mov
=> Cody: Log chat prediction usage

CODENOTIFY, shell.nix
Update pnpm checksum and add myself to codenotify so I dont miss it next time :grimacing: 
N/A nix stuff
=> nix: update pnpm hash

doc/dev/how-to/index.md, doc/dev/how-to/update_pnpm.md
Follow-up to @vovakulikov 's initiative, wrote a guide for the next person handling this update. 
previewed content with `sg run docsite`.
=> docs: add how-to for updating pnpm

docker-images/opentelemetry-collector/builder.template.yaml, docker-images/opentelemetry-collector/configs/group.yaml
Need to add more processors to aid in debugging our traces
built the collector locally
=> otel: add more processors and change filter ex to group ex.

internal/database/recent_view_signal.go, internal/database/recent_view_signal_test.go
Test plan:
Unit tests added.
Closes https://github.com/sourcegraph/sourcegraph/issues/51465
=> own: make view signal listing support options.

CHANGELOG.md
Changelog only. Forgot to add in the original PR.
=> CHANGELOG: Add src serve-git bug fix for 5.0.4

doc/code_navigation/how-to/configure_auto_indexing.md, doc/code_navigation/how-to/configure_data_retention.md, doc/code_navigation/how-to/index.md, doc/code_navigation/how-to/policies_best_practices.md, doc/code_navigation/index.md
=> codeintel: Provide guidance for indexing and retention policies

client/web/src/cody/chat/CodyChatPage.tsx
Add Download for VS Code CTA in the sidebar. 
- visit /cody
=> Add Download Cody for VS Code Ad to Cody Web Chat

cmd/migrator/shared/main.go, dev/sg/internal/migration/squash.go, dev/sg/sg_db.go, dev/sg/sg_migration.go, internal/database/connections/live/BUILD.bazel, internal/database/connections/live/runner.go, internal/database/migration/runner/runner.go
Logs the connection DSN strings used to connect to the databases for transparency. Closes #51177 
I ran it :slightly_smiling_face:
=> mvu: log connection DSNs on startup

cmd/server/Dockerfile
Supersedes https://github.com/sourcegraph/sourcegraph/pull/51616
See CI green.
=> Bump syntax-highlighter docker container for single-docker deployment

doc/sidebar.md
Update the TOC to label app as beta instead of experimental, for consistency with other artifacts. 
N/A minor copy change
=> Update docs TOC

CHANGELOG.md, enterprise/internal/codeintel/autoindexing/internal/background/job_cleanup.go, enterprise/internal/codeintel/autoindexing/internal/background/job_scheduler.go, enterprise/internal/codeintel/uploads/internal/background/job_backfill.go, enterprise/internal/codeintel/uploads/internal/background/job_cleanup.go, enterprise/internal/codeintel/uploads/internal/background/job_commitgraph.go, enterprise/internal/codeintel/uploads/internal/background/job_expirer.go, enterprise/internal/codeintel/uploads/internal/background/job_reconciler.go
=> Backport 51591 to 5.0

dev/gqltest/code_insights_test.go
Temporarily disabling some tests while I fix them to unblock main.
N/A
=> temporarily skip tests while I fix them

enterprise/cmd/frontend/internal/completions/resolvers/resolver.go, enterprise/internal/completions/streaming/llmproxy/llmproxy.go, enterprise/internal/completions/streaming/stream.go, schema/schema.go, schema/site.schema.json
=> llmproxy client: Switch to new dev url

client/cody/CHANGELOG.md, client/cody/package.json
Big one incoming 👀 
This is just a version bump
=> Cody: Release 0.1.0

enterprise/cmd/frontend/internal/own/resolvers/resolvers.go, enterprise/internal/own/background/recent_views_test.go, enterprise/internal/own/background/scheduler.go
=> own: rename feature flag for consistent naming.

internal/database/recent_view_signal.go, internal/database/recent_view_signal_test.go
=> own: fix a bug when not found repo broke building recent view signal.

client/web/src/components/gitHubApps/AddGitHubAppPage.tsx
Modifies the requested permissions for GitHub Apps.
Verified locally.
=> [github app] Update default GitHub App permissions

client/web/src/site-admin/SiteAdminFeatureFlagConfigurationPage.tsx, client/web/src/site-admin/SiteAdminFeatureFlagsPage.module.scss, client/web/src/site-admin/SiteAdminFeatureFlagsPage.tsx
Including page header button alignment, bringing headers/buttons into the container, adding breadcrumbs, and centering FilteredConnection summary.
Test plan:
https://github.com/sourcegraph/sourcegraph/assets/94846361/7c62c2e7-4556-4ca4-9d72-6b142e938ef1
=> chore: clean up feature flags page.

doc/batch_changes/references/batch_spec_cheat_sheet.md, doc/batch_changes/references/batch_spec_templating.md
Updating sed implementation in docs. 
Local
=> Updating sed implementation in docs

enterprise/cmd/llm-proxy/internal/auth/auth.go, enterprise/cmd/llm-proxy/internal/limiter/store.go, enterprise/internal/completions/streaming/anthropic/decoder.go
=> Light code formatting fixes

enterprise/cmd/llm-proxy/shared/main.go
This makes it easier to bulk expire all records and make more sense of what the records are for. Before, the key would simply be the actor ID which rn is the subscription graphql id.
WDYT about that?
Verified in redis that prefixing works.
=> llmproxy: Prefix rate limit entries in redis

cmd/frontend/internal/app/ui/handlers.go, cmd/frontend/internal/bg/app_ready.go, internal/singleprogram/postgresql.go, src-tauri/src/common.rs, src-tauri/src/main.rs, src-tauri/tauri.conf.json
* Updates some docstrings that I missed in a prior change
* Fixes an issue where dev mode couldn't sign in
* Gives Postgres more time to start (I was seeing timeouts in dev mode sometimes)
* Fix some dead code warnings in the Rust code
`sg start app` works as expected
=> app: various minor fixes

internal/database/feature_flags_test.go
=> chore: add forgotten test after updating the `UpdateFeatureFlag` function.

client/web/src/cody/components/ChatUI/ChatUi.module.scss, client/web/src/cody/components/ChatUI/ChatUi.tsx
Add VS Code like feedback button to Cody Chat on web.
- Visit /cody
=> [Cody Web] add feedback collection

client/cody/webviews/Login.module.css, client/cody/webviews/Login.tsx
**Changes**:
- Replaces the mention to request access on discord
- Changes alignment of elements
- Inserts divider between sections
- Removes custom labels and uses automatic labels from `<VSCodeTextField>` [component](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/text-field/README.md), which insures consistency with the design system of VSCode
Tested locally, handles resizes and different color themes
=> Cody VScode: Welcome screen UI Improvments 

client/web/src/components/externalServices/AddExternalServicesPage.tsx, client/web/src/components/externalServices/backend.ts, client/web/src/components/externalServices/externalServices.test.tsx, client/web/src/components/externalServices/externalServices.tsx, client/web/src/components/gitHubApps/backend.ts
=> feat: add link from code host connections to github apps

enterprise/internal/database/perms_store.go
=> chore: refactor to not use loop for adding to Set

client/cody/package.json
Changes:
- Adds descriptions to each setting options
- Reorders the options so that less important options come last
Tested locally
=> Update Cody VSCode Settings page

client/cody/CHANGELOG.md, client/cody/package.json
Changlog updated. 
Version bump
Changelog updated. eye checked :P
=> Cody release v0.1.2

dev/codeintel-qa/cmd/query/queries.go, enterprise/internal/codeintel/codenav/internal/lsifstore/document_metadata_test.go, enterprise/internal/codeintel/codenav/internal/lsifstore/locations_by_position.go, enterprise/internal/codeintel/codenav/internal/lsifstore/locations_by_position_test.go
This PR updates some missed QA tests.
Manually tested as well as updated QA tests.
=> [language platform] Updates failing QA tests

doc/admin/executors/firecracker.md
Closes #40935. 
Add some additional context around bare metal (what it is and cost and benefits).
To tests, just docs.
=> Add additional information about AWS bare metal

enterprise/internal/codeintel/ranking/internal/store/mapper.go
Pulled from #51681. See these query plans for a before/after difference: [15s](https://explain.dalibo.com/plan/7e22d1g3db7218c6) -> [203ms](https://explain.dalibo.com/plan/2c69eh51c6f32fcd).
=> ranking: Optimize mapper query

client/web/src/cody/chat/CodyChatPage.tsx
Add beta label to cody web chat.
- visit /cody
=> Add beta label to cody web chat

internal/repos/gitlab.go, schema/gitlab.schema.json, schema/schema.go
Closes https://github.com/sourcegraph/sourcegraph/issues/50882
Tested manually, works as expected.
Tests pass in CI.
=> Add exclude pattern support for GitLab

enterprise/internal/completions/streaming/codecompletion.go
This causes us to potentially use the wrong client. I've also done a general sweep to make them look more alike so as a next step we can hopefully unify them mostly.
CI.
=> Align implementation of HTTP handler for code and chat completions

doc/admin/observability/dashboards.md, enterprise/internal/codeintel/ranking/internal/background/exporter/job.go, enterprise/internal/codeintel/ranking/internal/background/janitor/job.go, enterprise/internal/codeintel/ranking/internal/background/mapper/job.go, enterprise/internal/codeintel/ranking/internal/background/reducer/job.go, enterprise/internal/codeintel/shared/background/janitor_job.go, enterprise/internal/codeintel/shared/background/pipeline_job.go, enterprise/internal/codeintel/uploads/internal/background/janitor/job_cleanup.go, enterprise/internal/codeintel/uploads/internal/background/janitor/job_cleanup2.go, enterprise/internal/codeintel/uploads/internal/background/janitor/job_reconciler.go, enterprise/internal/own/background/background.go, monitoring/definitions/shared/codeintel_ranking.go
Fixes #51832.
Looked at the dashboard.
=> ranking: Update dashboards

dev/sg/sg_db.go, doc/dev/background-information/sg/reference.md
Copy the user thing and change a few nouns, nbd.
Tested locally. It spits out a token!
=> sg db: Add add-access-token subcommand

client/cody-ui/src/Chat.tsx, client/cody-ui/src/chat/Transcript.tsx, client/cody-ui/src/chat/TranscriptItem.module.css, client/cody-ui/src/chat/TranscriptItem.tsx
Closes #51740
Tested web and VSCode locally.
=> Cody: Add submit button to edit dialog for parity with chat input box

client/web/src/cody/chat/CodyChatPage.tsx
Forgot checking for new feature flags on /cody.
- visit /cody
=> [Cody web chat] fix feature flagging

enterprise/cmd/frontend/internal/dotcom/productsubscription/llmproxyservice.go
Previously, we would return a very weird graph that shows usage only on days with usage, and no data points in between.
Looks better: <img width="947" alt="Screenshot 2023-05-15 at 19 07 06@2x" src="https://github.com/sourcegraph/sourcegraph/assets/19534377/4e62a029-1dda-41c5-9350-cfc2516c1026">
Verified the query works on my local instance. Screenshot attached.
=> llmproxy: Return one data point per day even if usage is zero

enterprise/internal/completions/client/anthropic/anthropic.go, enterprise/internal/completions/client/openai/openai.go
Piggyback tiny improvement to JSON error handling.
CI
=> completions: remain silent for request context cancellation

enterprise/internal/codeintel/policies/internal/background/repomatcher.go
Missed policies service when backporting #51591 - #51663.
CI
=> backport: Fix missing change from backport of #51591

client/cody/package.json
Just found two typos, fixed them
Only docs changes
=> Cody: Two tiny typo fixes

enterprise/internal/codeintel/autoindexing/internal/store/store_repositories.go
=> Backport 51947 to 5.0

dev/ci/integration/run-integration.sh
=> fix spelling

doc/dev/background-information/app/codesigning.md, doc/dev/background-information/app/index.md, doc/dev/background-information/index.md, doc/dev/index.md
=> docs: make link to app coddesigning

client/cody-jetbrains/build.gradle.kts, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatBubble.java
- Closes https://github.com/sourcegraph/sourcegraph/issues/52000
Screenshot:
- Tested it with some inputs
- Low stakes because this is not in production
=> Cody for JetBrains: Add markdown rendering

client/cody/CHANGELOG.md, client/cody/package.json
Release checklist:
Housekeeping items for cutting Cody VSCE release.
=> Cody: Release v0.1.3

dev/release/release-config.jsonc
Generated with `pnpm run release release:activate-release`
N/A
=> Release: update release config for 5.0.4 release

dev/sg/linters/linters.go
Run `lint:js:web` as part of `sg lint client` when not in CI
Issue: https://github.com/sourcegraph/devx-support/issues/16
CI
=> sg: add eslint to run locally with client lints

client/web/src/cody/components/ChatUI/ChatUi.tsx, client/web/src/cody/stores/sidebar.ts
Auto focus cody input on clicking ask cody button.
https://www.loom.com/share/0a5f1e2bacbd4e08a9801029360905e6
- visit repo page and click on ask cody.
=> Autofocus cody input on clicking ask cody

client/cody-shared/src/chat/transcript/index.ts, client/web/src/cody/sidebar/CodySidebar.tsx, client/web/src/cody/stores/chat.ts
Cody now persists the last opened chat and opens it on page reload.
https://www.loom.com/share/882f04d9c6c44e96bf8328ecb3cfd352
visit /cody
=> Persist last opened chat in Cody

internal/database/connections/live/BUILD.bazel, internal/database/connections/live/migration_test.go, internal/database/migration/cliutil/drift.go, internal/database/migration/schemas/description.go, internal/database/migration/stitch/rewriter.go, internal/database/migration/store/describe.go, migrations/codeinsights/1659572248_refresh_scoped_insights/down.sql, migrations/codeinsights/1672921606_data_retention_jobs_series_metadata/down.sql, migrations/codeinsights/1672921606_data_retention_jobs_series_metadata/up.sql, migrations/codeintel/1665531314_remove_api_docs_tables/down.sql, migrations/codeintel/1665531314_remove_api_docs_tables/up.sql, migrations/codeintel/1670365552_fix_scip_document_schema_counting/down.sql, migrations/frontend/1648628900_rename_localclone_worker_table/down.sql, migrations/frontend/1652707934_add_last_check_at_to_codeintel_lockfile_references/down.sql, migrations/frontend/1655157509_no_more_ssbc_access_tokens/down.sql, migrations/frontend/1667220626_rename_codeintel_path_ranks_key/down.sql, migrations/frontend/1670934184_add_gitserver_corruption_columns/down.sql, migrations/frontend/1674455760_add_cancellation_reason_to_permission_sync_jobs_table/down.sql, migrations/frontend/1675962678_remove_action_namespace_perms/down.sql, migrations/frontend/1676420496_frontend/down.sql, migrations/frontend/1677003167_package_repos_separate_versions_table_stage2/down.sql, migrations/frontend/1677944752_drop_unused_lockfiles_tables/down.sql, migrations/frontend/1678214530_fix_indexes_on_ranking_tables/down.sql, migrations/frontend/1678456448_make_role_name_citext/down.sql, migrations/frontend/1679058200_upsize_codeintel_ranking_references_processed_datatype/down.sql, migrations/frontend/1683670735_move_deleted_fields_for_ranking/down.sql, migrations/frontend/1683753933_move_upload_relation_in_ranking_export_data/down.sql
Fixes #52098.
The whole thing is a test plan, doofus.
=> migrations: Add CI check detecting drift on downgrade

wolfi-images/cadvisor.yaml, wolfi-packages/cadvisor.yaml
- Manually testing package locally
- Green CI
=> Bump cadvisor version to 0.47.1

client/cody-jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowFactory.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/completions/ChatUpdaterCallbacks.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/ApiAuthenticator.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/ApplicationSettingsConfigurable.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/CodyApplicationService.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/CodyProjectService.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/CodyService.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/ConfigUtil.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/NotificationActivity.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/OpenPluginSettingsAction.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/PluginSettingChangeActionNotifier.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/PluginSettingChangeContext.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/ProjectSettingsConfigurable.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/SettingsChangeListener.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/SettingsComponent.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/config/SettingsConfigurableHelper.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/telemetry/Event.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/telemetry/GraphQlLogger.java, client/cody-jetbrains/src/main/java/com/sourcegraph/cody/telemetry/PostStartupActivity.java, client/cody-jetbrains/src/main/resources/META-INF/plugin.xml
- Closes https://github.com/sourcegraph/sourcegraph/issues/51999
Added settings UI (99% of this PR)
Also:
- Added "synchronized" modifier at two places
- Commented out a debug log line
Comprehensive, [2.5-min Loom](https://www.loom.com/share/93692ba3459546608df5d90b533205f6)
Screenshot:
- Tested in Loom
- Low stakes, not in production yet
=> Cody for JetBrains: Add settings UI

internal/database/migration/cliutil/drift.go
=> drift: Fix which error we print

cmd/frontend/internal/app/updatecheck/handler.go, cmd/migrator/build.sh, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/deploy/machine-images/gce.md, doc/admin/executors/deploy_executors_kubernetes.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md
This pull request is part of the Sourcegraph 5.0.4 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/52092)
=> release: sourcegraph@5.0.4

enterprise/internal/own/ownref.go, enterprise/internal/own/ownref_test.go, internal/database/user_emails.go, internal/database/user_emails_test.go
Test plan:
Unit tests added.
Closes https://github.com/sourcegraph/sourcegraph/issues/52143
=> own: make bag match against any verified email.

doc/dev/background-information/app/index.md, doc/dev/background-information/app/troubleshooting.md, doc/dev/index.md
Add troubleshooting steps for app not loading
Docs-only change
=> docs: app troubleshooting

client/cody/webviews/Login.tsx
Follow-up to this comment: https://github.com/sourcegraph/sourcegraph/pull/52075#pullrequestreview-1431770387
- N/A
=> cody vs code: change "requires verified email" message to say "sourcegraph.com"

client/cody-ui/src/Chat.tsx, client/web/src/LegacyLayout.tsx, client/web/src/cody/components/ChatUI/ChatUi.module.scss, client/web/src/cody/components/ChatUI/ChatUi.tsx, client/web/src/cody/search/CodySearchPage.tsx, client/web/src/cody/stores/chat.ts, client/web/src/cody/useIsCodyEnabled.tsx, client/web/src/global/GlobalAlerts.tsx, client/web/src/global/Notices.tsx, client/web/src/marketing/toast/CodySurveyToast.tsx, client/web/src/storm/pages/LayoutPage/LayoutPage.tsx, client/web/src/user/settings/emails/UserEmail.tsx
Add alerts, notices, popups dotcom for restricting Cody access to logged-in users with verified emails only. 
https://www.loom.com/share/865d8621dbd440a3ae926a647ce4adca
design: https://www.figma.com/file/DIk3eGdgKszigQVec7Y8SD/Frictionless-cody?type=design&node-id=767-30229&t=ee1VyzmpjtZhgrNq-0
- sign up with a new account
=> Add Cody verify your email popup and notice for dotcom

client/web/src/storm/pages/SearchPage/TryCodyCtaSection.module.scss, client/web/src/storm/pages/SearchPage/TryCodyCtaSection.tsx
Manually test the links to determine if they work correctly.
=> Alter homepage copy to support the new /cody page

enterprise/cmd/sourcegraph/BUILD.bazel, enterprise/dev/app/app_stamp_vars.sh, enterprise/dev/app/app_version.sh
Take two!
I really did test it manually, swear.
=> app: fix local builds not starting

client/web/src/components/gitHubApps/CreateGitHubAppPage.tsx, client/web/src/components/gitHubApps/GitHubAppsPage.tsx, client/web/src/site-admin/SiteAdminExternalServicesArea.tsx, client/web/src/site-admin/SiteAdminGitHubAppsArea.tsx
Only UI changes, only adding page view events. I don't think tests are really applicable here.
=> [github apps] add missing page view events

enterprise/internal/own/ownref.go, enterprise/internal/own/ownref_test.go
Part of [#52133](https://github.com/sourcegraph/sourcegraph/issues/52133)
This pull request extends the Bag to take in many references at once. This is used for search (see #52219) where many ownership terms are given to include and exclude for search.
Small test to verify a multi-bag works.
=> ByTextReference accepts many references

.github/workflows/batches-notify.yml
Remove Ryan and add Malo to the batches notify ping.
=> add malo to batches notify

cmd/frontend/auth/providers/BUILD.bazel, cmd/frontend/auth/providers/mock_auth_provider.go, cmd/frontend/auth/providers/providers.go, cmd/frontend/auth/providers/providers_test.go, enterprise/internal/own/BUILD.bazel, enterprise/internal/own/ownref.go, enterprise/internal/own/ownref_test.go
Test plan:
Unit tests added.
Closes https://github.com/sourcegraph/sourcegraph/issues/52142
=> own: match linked code host handles.

client/cody/src/main.ts
Run sg start
Perform Cody actions
Verify events log to event_logs table in Postgres database
Verify events emit to dotcom
=> Fix Cody telemetry for VS Code Extension

client/web/src/enterprise/codeintel/ranking/pages/CodeIntelRankingPage.module.scss, client/web/src/enterprise/codeintel/ranking/pages/CodeIntelRankingPage.tsx
A few little alterations to make the page more readable.
N/A.
=> ranking: Tidy up frontend

enterprise/internal/own/ownref.go
Part of #52133
N/A - just String methods.
=> Bag.String for easier debugging

dev/nix/p4-fusion.nix, doc/dev/background-information/build_p4_fusion.md
Mostly just updating shasums and checking that it still builds.
Tested on Mac and Linux
=> nix: update p4 fusion openssl3

cmd/frontend/graphqlbackend/own.graphql, enterprise/cmd/frontend/internal/own/resolvers/resolvers.go, enterprise/cmd/frontend/internal/own/resolvers/resolvers_test.go, internal/database/BUILD.bazel, internal/database/recent_view_signal.go, internal/database/recent_view_signal_test.go
Test plan:
Unit tests added.
Closes https://github.com/sourcegraph/sourcegraph/issues/52209.
Depends on https://github.com/sourcegraph/sourcegraph/pull/52259.
=> own: respect repo exclusions in recent-views job.

client/cody/CHANGELOG.md
forgot to bump the changelog version
just a changelog change
=> Cody: Fix changelog

doc/admin/external_service/gitlab.md
Automated testing and visual check
=> Clarification to Project Query site config

client/cody/src/completions/provider.ts
Something really annoying with manually triggered completion is that it would include empty results (sometimes the response from the LLM are not great). This is fine for inline completions since those will be filtered out automatically but for manual ones, it would show an empty item in the sidebar which looked odd.
To smooth over some of these edges, this over-fetches the number of requested completions by two (ONLY for manual completions), filters out empty results, and caps the number to three (so it feels more reliable).
I think in the future we might want to rather stream those in and start additional requests only when some requests come back empty. This feature is not used much yet though so this seems reasonable to me.
=> Cody completions: Over-fetch manual completions but hide empty results

internal/gitserver/commands.go
This just removes an unnecessary layer of indirection over `gitCommand().StdoutReader()`. The added trace is not useful because both callers of the method and `StdoutReader()` each also define a span. 
Stacked on https://github.com/sourcegraph/sourcegraph/pull/52212
It builds.
=> Gitserver: remove unnecessary `execReader`

client/web/src/enterprise/codeintel/ranking/pages/CodeIntelRankingPage.tsx
=> ranking: Small UI tweak

cmd/frontend/graphqlbackend/user_emails.go
App checks if the current user has a verified email address for sg.com.  If the token is no longer valid this check fails, and causes the the JS Context to be built without a user object.  This puts the app into a not signed in state and the user can't resolve the issue. 
This change ensures that the check against sg.com will always return without an error and defaults to false if an error occurs.  While this may result in the user seeing message that they need to verify their email at least the user can correct the issue.
A follow up should be to allow the user to re-connect to dotcom if their token is no longer valid.
resolves https://github.com/sourcegraph/sourcegraph/issues/52421
Placed a bad token start app verify I am in a logged in state but Cody does not work.
=> App - Ensure verify email check always returns true or false 

internal/singleprogram/singleprogram.go
Effectively runs:
```
rm -rf $HOME/.cache/sourcegraph-sp
rm -rf $HOME/.config/sourcegraph-sp
rm -rf $HOME/Library/Application\ Support/sourcegraph-sp
rm -rf $HOME/Library/Caches/sourcegraph-sp
```
This deletes data from old Sourcegraph app directories, which came from before we switched to Tauri - so that users don't have to. In theory, these directories have no impact and can't conflict, but just for our own sanity we get rid of them. Any user running the new app version won't want these to stick around anyway.
Closes #52413
matches logically what is done in our docs today
=> app: delete old Sourcegraph app directories on startup

doc/cody/explanations/code_graph_context.md
=> docs: add section about incremental embeddings

doc/admin/executors/executor_secrets.md, doc/code_navigation/how-to/configure_auto_indexing.md, doc/code_navigation/how-to/enable_auto_indexing.md
- A bit of styling on the executor secrets page
- Add docs on configuring private repositories/secrets
Eyeballing
=> Docs on configuring secrets for auto-indexing

client/web/src/enterprise/codeintel/ranking/pages/CodeIntelRankingPage.tsx
=> ranking: Improve site-admin UI

doc/admin/how-to/repo-not-updated.md
for bug that has not existed since before 3.27.0
docs
=> remove troubleshooting section in docs

client/web/src/LegacyLayout.tsx, client/web/src/marketing/toast/CodySurveyToast.tsx, client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
- sign up for a new account on dotcom
=> Add event logging to signup Cody toast and email verification toast

enterprise/cmd/llm-proxy/internal/actor/source.go
Makes it easier to tell whether a span is _supposed_ to have no child spans, or if GCP is just a bit slow.
n/a
=> llm-proxy: annotate spans of sync jobs with whether they were skipped

wolfi-packages/p4cli.yaml
- Manual checking of updated package
=> Add license details for p4cli

enterprise/internal/codeintel/ranking/internal/store/mapper.go
#52502 introduced changes making this join unnecessary.
CI
=> ranking: Remove unnecessary join

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
- Updated the changelog
- Pushed the release
- Committed the post-release automatic changes
- Waited for JetBrains's approval
- Created this PR with auto-merge
- Submitted, got it approved, upgraded, tested, it works.
=> JetBrains: Release 2.1.4

wolfi-images/server.yaml
Add missing locale package to server base
CI + tested the newly built image
=> wolfi: add glibc-locale to server

client/web/src/enterprise/app/setup/steps/AppInstallExtensionsSetupStep.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/52559
- Check the other editor setup link (it should lead to the Cody doc page)
=> App: Fix other editors setup link

client/web/src/nav/UserNavItem.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/52517
- Check that app has only one item about settings which is "Settings" (it shouldn't have separate repositories or saved searches items)
=> App: Simplify user menu for the app

enterprise/cmd/frontend/internal/dotcom/productsubscription/llmproxy_graphql.go, enterprise/cmd/frontend/internal/dotcom/productsubscription/llmproxy_graphql_test.go, enterprise/internal/licensing/BUILD.bazel, enterprise/internal/licensing/codygateway.go, enterprise/internal/licensing/codygateway_test.go
Part of https://github.com/sourcegraph/sourcegraph/issues/52258 
CI
=> licensing: rename LLM-proxy to Cody Gateway

enterprise/internal/paths/match.go, enterprise/internal/paths/match_test.go
Just ensuring our workaround for a bug in our git show implementation works.
=> paths: add a test case for the embeddings dotdot workaround

client/web/src/enterprise/codeintel/ranking/pages/CodeIntelRankingPage.tsx
Fix two decimal points of precision 🥴 
=> ranking: Fix percentage in UI

client/cody/src/chat/fastFileFinder.ts, client/cody/src/chat/utils.ts
Address @valerybugakov's comments in https://github.com/sourcegraph/sourcegraph/pull/52541
Refactor verified by unit and integration test.
=> cody: clean up code following fast file finding change

CHANGELOG.app.md
add app-specific changelog we can all start keeping up-to-date. 
changelog only
=> app: add app-specific CHANGELOG

client/cody/test/fixtures/workspace/lib/batches/env/BUILD.bazel, client/cody/test/fixtures/workspace/lib/codeintel/tools/lsif-visualize/BUILD.bazel
Encountered this diff on main
`bazel configure`
=> bazel: run bazel configure

schema/site.schema.json
Apparently, during https://github.com/sourcegraph/sourcegraph/pull/50093 I missed to update examples section.
- Check the diff
=> (chore) fix "auth.accessRequest" site config schema example

wolfi-images/server.yaml
add missing locale package 
CI and tested in our rules_oci branch
=> wolfi: add locale package to server base

wolfi-images/jaeger-all-in-one.yaml
Replaces https://github.com/sourcegraph/sourcegraph/pull/52683 
manual testing
=> Tweak permissions on jaeger /tmp

client/shared/src/codeintel/legacy-extensions/language-specs/languages.ts
=> Enable "Find implementations" button for Dart

docker-images/syntax-highlighter/src/main.rs
=> syntax: small clippy change

.gitignore, dev/nix/comby.nix, dev/nix/ctags.nix, dev/nix/nodejs.nix, dev/nix/p4-fusion.nix, dev/nix/util.nix, flake.lock, flake.nix, shell.nix
Re-organizing a couple of things to make the individual files nicer, consolidated some things in ctags.nix, extracted forEachSystem stuff to flake.nix instead of the individual files, overlay for our specific nodejs requirements, some more comments to stuff
N/A, nix stuff
=> nix: reorganizing

doc/cody/explanations/code_graph_context.md
=> Embeddings: update docs for env vars

enterprise/internal/codeintel/ranking/internal/store/coordinator.go
=> ranking: Clean up old progress rows

enterprise/internal/codeintel/ranking/internal/store/mapper.go
Improve the mapper by de-materializing the exported uploads CTE.
[before](https://explain.dalibo.com/plan/52fe81ge964eaf9a) and [after](https://explain.dalibo.com/plan/dd5592bghf1f3e5c)
Unit tests.
=> ranking: Deduplicate use of `exported_uploads` CTE

client/web/src/marketing/toast/CodySurveyToast.tsx
Just noticed.
N/A - Copy change
=> Fix small Cody typo

doc/cody/explanations/index.md
First title was repeated
Tested locally
=> Fixes repeated links

internal/luasandbox/modules.go
The filepath package uses the host systems separator. However, embed.FS is ALWAYS a unix file system with `/` separators, so on windows, the luasandbox is currently not able to load the modules correctly. What a footgun :sadge:
Pulling this out into a separate PR so it's easier to revert if this is causing issues. I don't think it should cause any merge conflicts with https://github.com/sourcegraph/sourcegraph/pull/52384
We verified that this fixed an issue on windows.
=> luasandbox: Make modules load on windows

dev/release/release-config.jsonc
Test Plan: n/a
Fixes https://github.com/sourcegraph/sourcegraph/issues/52745
=> release: close 5.0.5

doc/dev/background-information/sg/reference.md, enterprise/cmd/executor/kubernetes/README.md, enterprise/cmd/executor/kubernetes/batches/executor-batches.Deployment.yml, enterprise/cmd/executor/kubernetes/codeintel/executor-codeintel.Deployment.yml, sg.config.yaml
Made it easier to develop K8s Executors by adding additional commands to `sg`.
=> executors: Easier K8s Local Development

client/web/src/cody/chat/CodyChatPage.tsx
See [this thread](https://sourcegraph.slack.com/archives/C054KJEF8DQ/p1685631464394469).
Tested locally, confirmed working.
=> cody/web: fix cody browser history loop

CHANGELOG.app.md
=> Add v2023.5.30

client/app-shell/static/error.html, src-tauri/Cargo.toml, src-tauri/src/common.rs, src-tauri/src/main.rs, src-tauri/src/tray.rs, src-tauri/tauri.conf.json
Add the ability to clear all data and reset everything in App to default settings.
Close #48940 
Co-authored/started by @chwarwick 
- Run app and set some settings
- Clear all data and observe that everything is reset to default state
=> app: Clear all data

enterprise/cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
=> [chore] unblock main with bazel configure

client/web/src/components/FilteredConnection/FilteredConnection.tsx
Deprecate `FilteredConnection` and add examples of how to use the recommended approach.
CI
=> web: deprecate `FilteredConnection`

tmp/redis.conf
A file was accidentally committed, removing it. 
CI
=> chore: remove accidental commit

doc/dependency_decisions.yml, third-party-licenses/ThirdPartyLicenses.csv
Update licenses and add `hashicorp/cronexpr` as approved with Apache 2.0 license
`LICENCE_CHECK=true ./dev/license.sh`
=> mark hashicorp/cronexpr as Apache 2.0

dev/nix/nodejs.nix
=> nix: bump pnpm hash

client/web/src/enterprise/codeintel/ranking/pages/CodeIntelRankingPage.module.scss, client/web/src/enterprise/codeintel/ranking/pages/CodeIntelRankingPage.tsx
Quick UI tweaks to the ranking page.
UI changes, tested locally
=> UI Enhancements for Ranking Page in Site Admin

doc/app/index.md, doc/app/release-pipeline.md
Document the Sourcegraph App release pipeline
doc change
=> app: describe the Sourcegraph App release pipeline

dev/release/templates/patch_release_issue_template.md, dev/release/templates/release_issue_template.md
These are a collection of changes I noted down while doing the 5.0.5 patch release. You can review commit by commit.
Test Plan: n/a
=> release: updates to patch issue template

dev/sg/sg_app.go, doc/dev/background-information/sg/reference.md
Description was a bit out of date for this command
Tested locally
=> sg: fix app command description

dev/mocha.bzl
Make Percy silent on success in Bazel.
CI
=> bazel: make percy silent on success

internal/gitserver/client_test.go
This fixes redundant code, a classic case of `if something then return true else false`. 
CI
=> gs: fix redundant code

dev/nix/nodejs.nix
=> nix: correct hash for pnpm 8.3.0

client/web/src/repo/blob/own/FileOwnershipEntry.tsx, client/web/src/repo/blob/own/FileOwnershipPanel.story.tsx, client/web/src/repo/blob/own/HistoryAndOwnBar.story.tsx, client/web/src/repo/blob/own/grapqlQueries.ts, cmd/frontend/graphqlbackend/schema.graphql, cmd/frontend/graphqlbackend/teams.go, enterprise/cmd/frontend/internal/own/resolvers/resolvers.go, enterprise/cmd/frontend/internal/own/resolvers/resolvers_test.go, enterprise/internal/own/BUILD.bazel, enterprise/internal/own/ownref.go, sg.config.yaml
Test plan:
Existing + new unit tests.
Closes https://github.com/sourcegraph/sourcegraph/issues/52504.
Closes https://github.com/sourcegraph/sourcegraph/issues/52576.
=> own: use bag in resolver. Guess GitHub team which doesn't exist in Sourcegraph.

doc/dev/background-information/bazel.md, doc/dev/background-information/bazel_containers.md, doc/dev/background-information/index.md
Add first batch of documentation around build images with `rules_oci` and `wolfi`
local docs preview
=> docs: building container images with bazel (oci/wolfi) 

dev/oci_deps.bzl
Update all base images, which in particular, `syntax-highlighter` as a follow-up to https://github.com/sourcegraph/sourcegraph/pull/52932 
CI
=> bzl: update all base images

CHANGELOG.md, enterprise/cmd/frontend/internal/auth/saml/BUILD.bazel, enterprise/cmd/frontend/internal/auth/saml/user.go, enterprise/cmd/frontend/internal/auth/saml/user_test.go
Also fixed a bug where we always returned an error from saml GetExternalAccountData function. We should only return an error there if the return value is nil.
Added a unit test.
=> [fix] SAML assertion case insensitive matching to get display name

dev/release/release-config.jsonc
=> release: update 5.0.6 captain

dev/release/release-config.jsonc
Reverts sourcegraph/sourcegraph#53004
n/a
=> Revert "release: update 5.0.6 captain"

internal/goroutine/periodic.go, internal/goroutine/periodic_test.go
Make this thing not suck.
...the unit test
=> goroutine: Improve unit test

enterprise/internal/codycontext/context.go
This adds early bailouts when we know we can't return any results. 
This fixes an issue where searching zero repositories would actually search all repositories. The problem was that `repo:^$` actually returns all repositories. This is a search bug that is unrelated to this endpoint and is not fixed by this PR.
Manually tested that zero repositories or zero code/text limits return zero results.
=> Embeddings: bailout early for zero results

.github/workflows/batches-notify.yml
=> batches: Remove Piszmog from Notify

internal/goroutine/periodic_test.go
Follow up to https://github.com/sourcegraph/sourcegraph/pull/53009.
Is comment.
=> chore: Make sure I finish writing my 

cmd/gitserver/server/server.go
readCloneProgress does not care about the call sites context since it runs in the background. Instead of the call sites encoding this knowledge we update the function to create its own background context.
Test Plan: CI
Co-authored-by: @indradhanush
=> gitserver: readCloneProgress does not take ctx

dev/build-tracker/main.go, enterprise/dev/ci/scripts/app-token/main.go, lib/batches/schema/stringdata.go
Fix usage of the deprecated ioutil package as described [here](https://golang.org/doc/go1.16#ioutil)
unit tests
=> fix: use of ioutil package

client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java, client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowFactory.java, client/jetbrains/src/main/java/com/sourcegraph/cody/UpdatableChat.java, client/jetbrains/src/main/java/com/sourcegraph/cody/UpdatableChatHolderService.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ResetCurrentConversationAction.java, client/jetbrains/src/main/resources/META-INF/plugin.xml
- Have a talk with cody to have some messages in the chat then then press new button placed next to gear icon in the toolbar, this should reset the current conversation with cody
https://github.com/sourcegraph/sourcegraph/assets/7345368/c096bb83-220e-43ca-a674-cc0bb84fb62e
=> JetBrains: button to reset current conversation with cody

enterprise/internal/codeintel/ranking/internal/store/reducer.go
Speed up the selection by moving all of the joins and the junk records after the lock/limit. This makes the set of join targets much smaller, and ensures that the proper index is used for item selection in the earlier CTE.
=> ranking: Speed up reducer record selection

doc/dev/how-to/cody_gateway.md
=> doc: add BigQuery playbook for Cody Gateway

doc/admin/how-to/clear_codeintel_data.md
Update to cascade deletes.
yes
=> docs: Update codeintel truncate commands

client/web/scripts/report-bundle-diff.ts
`gsutil` doesn't exit with a non-zero exit code when the file is not found, so we need to manually throw an error to switch to the next revision.
CI
=> ci: report bundlesize handle missing file

client/web/src/app/TauriNavigation.module.scss, client/web/src/app/TauriNavigation.tsx, client/web/src/nav/GlobalNavbar.tsx, client/web/src/nav/UserNavItem.tsx
Closes [#53113](https://github.com/sourcegraph/sourcegraph/issues/53113)
Closes [#53114](https://github.com/sourcegraph/sourcegraph/issues/53114)
=> app: hide unneeded navbar items

cmd/frontend/internal/bg/BUILD.bazel, cmd/frontend/internal/bg/update_permissions.go, cmd/frontend/internal/bg/update_permissions_test.go, internal/database/role_permissions.go, internal/rbac/schema.yaml, internal/rbac/types.go
Test plan:
Unit test added.
Local sg run and check.
Fixes https://github.com/sourcegraph/sourcegraph/issues/53065
=> rbac: don't include OWNERSHIP permissions to USER role by default.

cmd/gitserver/server/server_grpc.go
I split off the observability code in https://github.com/sourcegraph/sourcegraph/pull/47584 to make it easier to share with gRPC, but then failed to actually use it for gRPC. This was causing us to not trace gitserver search calls when gRPC was enabled. 
Tested that the server-side span is no longer missing.
=> Search: use observed method for gRPC

enterprise/cmd/executor/internal/worker/command/kubernetes.go, enterprise/cmd/executor/kubernetes/batches/executor-batches.Deployment.yml
Log the condition of the pod.
Local testing.
=> executors: Debug Log pod conditions

internal/conf/confdefaults/confdefaults.go
Opt app into incremental embeddings by default
na config change
=> App - default app to use incremental embeddings

enterprise/cmd/cody-gateway/internal/actor/actor.go, enterprise/cmd/cody-gateway/internal/events/events.go
A stub actor is set if we encounter an invalid token that belongs to a particular source, to avoid constantly attempting to fetching it from the source. We don't care about these actors since we can't assign them an identifier, and thus there is no point writing events about them, which may also avoid an abuse vector where an unknown actor can fill our BigQuery table with rubbish.
We leave a small hint of the discard happening on the trace span.
CI, lots of docstrings
=> cody-gateway: accept events without identifiers

doc/dev/background-information/bazel.md
When running queries locally on a machine that isn't authenticated to our internal registries, it may prevent the query to be run entirely. 
Adds a FAQ entry to explain how to go around this. 
CI
=> docs: add a FAQ entry for bazel queries and registries

client/web/BUILD.bazel, client/web/src/enterprise/own/AddOwnerModal.tsx, client/web/src/enterprise/own/RepositoryOwnPage.tsx, client/web/src/enterprise/own/RepositoryOwnPageContents.module.scss, client/web/src/enterprise/own/graphqlQueries.ts
Test plan:
Local sg run and test that the owner is created.
Part of https://github.com/sourcegraph/sourcegraph/issues/52931.
Will add team support as a follow-up.
https://github.com/sourcegraph/sourcegraph/assets/94846361/c779cb2f-17ce-4546-a0ec-6f76a6d7fcb7
=> own: add "Assign owner" modal window.

enterprise/internal/codeintel/autoindexing/internal/inference/lang_java_test.go, enterprise/internal/codeintel/autoindexing/internal/inference/libs/indexes.go
=> Update scip-java container SHA to latest

internal/oobmigration/BUILD.bazel, internal/oobmigration/store.go, internal/oobmigration/store_test.go
Will be used by https://github.com/sourcegraph/sourcegraph/pull/52242/files
Added unit test :+1:
=> oobmigrations: add GetByIDs

client/web/BUILD.bazel, client/web/package.json, client/web/src/enterprise/EnterpriseWebApp.tsx, client/web/src/enterprise/app/routes.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/53117
- Make sure that all links within Cody App work properly 
- Make sure that there are no "leaks" in UI that could lead you to pages that we don't have in Sourcegraph app.
=> Add app specific (simplified) routing schema

enterprise/cmd/cody-gateway/internal/actor/actor.go
Healthcheck panics in dev environment after https://github.com/sourcegraph/sourcegraph/commit/26de97cb777488c67839046c313c0586dc6f2f5e#diff-e65005ba54ef0cc3699a3b0854cdae9801354bb8395615ba994f9d72901ddac2R170 😞 
n/a, will follow up
=> cody-gateway/actor: don't panic on Logger

enterprise/cmd/cody-gateway/internal/httpapi/diagnostics.go
Right now every request generates a `diagnostics` trace 😅 There might be a better way to do this, will follow up again next week.
n/a
=> cody-gateway/httpapi: fixup /-/ endpoint handling

enterprise/cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go, enterprise/cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
This TODO is no longer valid as of https://github.com/sourcegraph/sourcegraph/pull/53265
n/a
=> cody-gateway/actor: remove outdated TODO

client/web/BUILD.bazel, client/web/src/enterprise/own/AddOwnerModal.tsx, client/web/src/enterprise/own/UserTeamSelect.tsx, client/web/src/enterprise/own/graphqlQueries.ts
Test plan:
Closes https://github.com/sourcegraph/sourcegraph/issues/52931.
https://github.com/sourcegraph/sourcegraph/assets/94846361/556741aa-0955-42d0-9131-cb5128737a6f
=> own: add teams support to "Add owner" button.

client/cody/CHANGELOG.md
Noticed a missing entry in the change log and some formatting inconsistencies
just changelog changes
=> Cody: Fix VS Code changelog

client/jetbrains/CHANGELOG.md, client/jetbrains/build.gradle.kts, client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java, client/jetbrains/src/main/java/com/sourcegraph/cody/UpdatableChat.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatBubble.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatMessage.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessageContentCreatorFromMarkdownNodes.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ExplainCodeDetailedPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ExplainCodeHighLevelPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/FindCodeSmellsPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/GenerateDocStringPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/GenerateUnitTestPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ImproveVariableNamesPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/Language.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/MessageBuilder.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/OptimizeCodePromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/PromptContext.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/PromptMessages.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/PromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/RecipeRunner.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SelectedText.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/TruncatedText.java
- Implements all but one recipes in #53235
This pr enables most of the basic recipes, which are:
- Explain code (high level)
- Generate unit test
- Generate a dcostring
- Improve variable names
- Smell code
- Optimize code
- All of the above recipes should give you a response with appropriate content if some of the code is selected
https://github.com/sourcegraph/sourcegraph/assets/7345368/299029c1-b7d1-4ce9-967e-0d74599e1fd1
=> JetBrains: cody basic recipes

internal/grpc/messagesize/BUILD.bazel
Not sure why this wasn't caught in the PR for #52036 
CI
=> grpc: bazel configure

docker-images/syntax-highlighter/Cargo.Bazel.lock, docker-images/syntax-highlighter/Cargo.lock, docker-images/syntax-highlighter/crates/scip-syntax/queries/scala/scip-tags.scm, docker-images/syntax-highlighter/crates/scip-syntax/src/lib.rs, docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.scala.snap, docker-images/syntax-highlighter/crates/scip-syntax/testdata/globals.scala, docker-images/syntax-highlighter/crates/scip-treesitter-languages/Cargo.toml, docker-images/syntax-highlighter/crates/scip-treesitter-languages/queries/scala/highlights.scm, docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__plugins.scala.snap, docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__scala.scala.snap, internal/ctags_config/ctags_config.go
=> scip-ctags: add scala support

enterprise/internal/codycontext/context.go
This makes context fetching a little more deterministic so tests are stable.
Ran the test 10 times to try to catch flakes.
=> Cody Context: make context resolution more deterministic

cmd/symbols/shared/main.go
whoops, we blew threw those limits
N/A, sample rate changes
=> codeintel: raise symbols honeycomb sample rate

enterprise/cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
=> cody-gateway: transform to have consistent token prefix for cache keys

enterprise/internal/codeintel/ranking/internal/background/exporter/job.go
=> ranking: Remove panic condition

enterprise/internal/own/BUILD.bazel, enterprise/internal/own/ownref.go, enterprise/internal/own/ownref_test.go
Test plan:
Closes https://github.com/sourcegraph/sourcegraph/issues/52718.
=> own: fix an error for SCIM external provider handle search.

doc/admin/licensing/index.md, doc/admin/pings.md, doc/dev/background-information/adding_ping_data.md, doc/sidebar.md
Closes #53145 
Doc updates
Just doc updates
=> Add documentation for new license verification

doc/admin/licensing/index.md
Small docs update to #53300 
Small docs update
=> [docs] Small update to licensing text

enterprise/internal/codeintel/ranking/internal/background/exporter/job.go
Ensure that we only emit symbols for definitions once per file to reduce the number of duplicate rows joined in the mapping phase.
Also clean up logic to match both def and ref export methods.
=> ranking: Refactor export to reduce definitions

enterprise/internal/codeintel/ranking/internal/store/coordinator.go
I got like "4000% complete" lol.
=> ranking: Fix estimation of reducer records

cmd/gitserver/server/BUILD.bazel, cmd/gitserver/server/common/BUILD.bazel, cmd/gitserver/server/common/queue.go, cmd/gitserver/server/common/queue_test.go, cmd/gitserver/server/perforce/BUILD.bazel, cmd/gitserver/server/perforce/perforce.go, cmd/gitserver/server/perforce/perforce_test.go, cmd/gitserver/server/server.go, cmd/gitserver/server/server_test.go, cmd/gitserver/shared/shared.go, internal/gitserver/BUILD.bazel, internal/gitserver/client_test.go
Part of #40330.
~Draft because I want to do some more testing. Code is more or less ready.~ 
- Updated test
- Did smoke tests for repo cloning, changelist mapping and metrics in Prometheus
For example:
=> cmd/gitserver: Add in-built metrics to common.Queue

internal/symbols/client.go
fixes https://sourcegraph.slack.com/archives/C04HCK4K3DL/p1686110895682199
CI
=> grpc: symbols: convert gRPC Cancelled/DeadlineExceeded errors to corresponding "context" errors

client/web/src/cody/chat/CodyChatPage.module.scss, client/web/src/cody/chat/CodyChatPage.tsx
Make mobile view of /cody on web match with cody sidebar.
Demo: https://www.loom.com/share/b0bcfbb4336b4bc1a773023d71cfce50
- Cody app: https://www.loom.com/share/c720a1385a984722a4505b7ad353e7d7
=> Fix mobile view for cody on web

client/web/src/end-to-end/code-intel/repository-component.test.ts, docker-images/syntax-highlighter/crates/scip-syntax/src/lib.rs, docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__tags_snapshot_go-diff.go.snap, docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__tags_snapshot_go-diff.go.snap.new
=> testing: does this fail in our CI

client/web/src/end-to-end/code-intel/repository-component.test.ts
=> lint: make repository-component.test.ts pretty again

client/cody/BUILD.bazel, client/cody/package.json, client/cody/src/completions/bestJaccardMatch.test.ts, client/cody/src/completions/bestJaccardMatch.ts, client/cody/src/completions/completion.test.ts, client/cody/src/completions/context.ts, client/cody/src/completions/index.ts, client/cody/src/completions/prompts.ts, client/cody/src/completions/provider.ts, client/cody/src/log.ts, client/cody/src/main.ts
- No functional changes. I only added comments, renamed a couple of properties and moved files around.
- Follow-up draft https://github.com/sourcegraph/sourcegraph/pull/53223 
CI
=> cody: add comments to completions modules

client/web/src/enterprise/own/RepositoryOwnPage.tsx
Test plan:
Local sg run and navigation checks.
https://github.com/sourcegraph/sourcegraph/assets/94846361/12e14b1d-f767-4543-9e82-21f11cf760c6
Closes https://github.com/sourcegraph/sourcegraph/issues/53369
=> own: make breadcrumbs include file path on drilldown page.

internal/trace/httptrace.go
This is an intentional panic which means we want to abort the http request. This is not an error that needs reporting.
Test Plan: CI
From https://console.cloud.google.com/errors/detail/CMbYzeaM1-aqVw;time=P30D?project=sourcegraph-dev
=> trace: handle http.ErrAbortHandler in loggingRecoverer

client/web/src/repo/stats/RepositoryStatsArea.tsx, client/web/src/repo/stats/RepositoryStatsContributorsPage.tsx
I picked the reviewers suggested by GitHub, and the change is minor, I think it should be fine :)
Test plan:
Local sg run and navigation checks.
https://github.com/sourcegraph/sourcegraph/assets/94846361/cf2f9481-9797-4726-8ffc-9c776fcb6fe8
=> chore: add file path breadcrumbs to repository contributors page.

client/jetbrains/CHANGELOG.md, client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java, client/jetbrains/src/main/java/com/sourcegraph/cody/prompts/SupportedLanguages.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/RecipeRunner.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/TranslateToLanguagePromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/ui/SelectOptionManager.java, client/jetbrains/src/main/java/com/sourcegraph/cody/ui/SelectOptionPopupUI.java, client/jetbrains/src/main/resources/META-INF/plugin.xml
- Closes #53235
Working "Translate to different language".
There are still some issues with the select option modal that need to be resolved before merging this. See some of the issues in the video. I'll also update the changelog.
- Select some code and request translation to another language recipe
https://github.com/sourcegraph/sourcegraph/assets/7345368/7a704ed3-92f5-4b67-a883-24b930063544
=> JetBrains: translate to different language recipe

doc/app/index.md
Update to a release that fixes a bug in Cody Chat. 
n/a docs change
=> 6.13 cody release

internal/conf/confdefaults/confdefaults.go
Adds new default cody enabled setting for app
sg start app starts successfully
=> App - add new cody enabled setting to app defaults

enterprise/internal/codeintel/ranking/internal/store/retrieval.go, enterprise/internal/codeintel/ranking/internal/store/retrieval_test.go, internal/database/repos.go
Use externally visible timestamp field.
Updated unit tests.
=> ranking: Fix timestamps in `LastUpdatedAt`

enterprise/internal/own/background/analytics.go
Part of #53438
Follow-up to a [comment](https://github.com/sourcegraph/sourcegraph/pull/53467#discussion_r1229509251) in #53467
TBD
=> Make HEAD resolution at analytics worker non-retryable

enterprise/cmd/frontend/internal/auth/saml/user.go
=> fix: incorrect error return

cmd/frontend/internal/cli/autoupgrade.go
If attempting to do an upgrade between patch versions with autoupgrade, we would fail with a schema out of date error. This happens because when checking whether we need to perform an upgrade, we only check major/minor versions. 
This PR does an additional check whether a patch version upgrade needs to be performed, if we don't need to perform a larger upgrade. We attempt to perform the larger upgrade flow for patch versions, as creating the upgrade range will error when major+minor versions are equal
Did local upgrade from 5.0.0 to 5.0.5
=> mvu: handle patch-only upgrade for autoupgrade

dev/ci/runtype/runtype.go, dev/oci_deps.bzl, doc/dev/background-information/bazel/faq.md, doc/dev/background-information/ci/reference.md, doc/dev/background-information/sg/reference.md, docker-images/codeinsights-db/BUILD.bazel, docker-images/codeinsights-db/README.md, docker-images/codeintel-db/BUILD.bazel, docker-images/codeintel-db/README.md, docker-images/jaeger-all-in-one/image_test.yaml, docker-images/postgres-12-alpine/BUILD.bazel, docker-images/postgres-12-alpine/README.md, enterprise/cmd/batcheshelper/BUILD.bazel, enterprise/cmd/batcheshelper/image_test.yaml, enterprise/cmd/executor/BUILD.bazel, enterprise/cmd/executor/image_test.yaml, enterprise/dev/ci/internal/ci/bazel_operations.go, enterprise/dev/ci/internal/ci/config.go, enterprise/dev/ci/internal/ci/operations.go, enterprise/dev/ci/internal/ci/pipeline.go, enterprise/dev/ci/push_all.sh
=> bzl: enact changes from  rfc 793

CHANGELOG.md
=> release: cut CHANGELOG for 5.0.6

client/cody/CHANGELOG.md, client/cody/package.json
=> Cody: Release 0.2.4

cmd/frontend/internal/app/updatecheck/handler.go, cmd/migrator/build.sh, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/deploy/machine-images/gce.md, doc/admin/executors/deploy_executors_kubernetes.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/kubernetes.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md
This pull request is part of the Sourcegraph 5.0.6 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/53491)
cc @unknwon
=> release: sourcegraph@5.0.6

client/jetbrains/CHANGELOG.md, client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ExplainCodeDetailedPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ExplainCodeHighLevelPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/FindCodeSmellsPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/GenerateDocStringPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/GenerateUnitTestPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ImproveVariableNamesPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/MessageBuilder.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/OptimizeCodePromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/OriginalText.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/PromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/RecipeRunner.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SummarizeRecentChangesPromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SummarizeRecentChangesRecipe.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/TranslateToLanguagePromptProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/vcs/CommitMetadataConsumer.java, client/jetbrains/src/main/java/com/sourcegraph/cody/vcs/Last5ItemsFromCurrentFileFilterOption.java, client/jetbrains/src/main/java/com/sourcegraph/cody/vcs/Last5ItemsLogFilterOption.java, client/jetbrains/src/main/java/com/sourcegraph/cody/vcs/LastNDaysFilterOption.java, client/jetbrains/src/main/java/com/sourcegraph/cody/vcs/VcsCommitsMetadataLoader.java, client/jetbrains/src/main/java/com/sourcegraph/cody/vcs/VcsCommitsMetadataProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/vcs/VcsFilter.java, client/jetbrains/src/main/java/com/sourcegraph/cody/vcs/VcsLogFilterOption.java, client/jetbrains/src/main/java/com/sourcegraph/cody/vcs/VcsLogFilterOptionsRegistry.java
Enabled summarize recent code changes recipe with available options: last 5 commits, commits from last day, commits from last week, last 5 commits from currently opened file in the editor. 
We're using any VcsLogProvider which is available in the project so it should work out of the box with all supported vcses in the JetBrains IDE (git, perforce, svn) but I tested it only with git. 
- All the options should display recent code changes. In case when nothing changed since last day or week, the message "No recent changes found." should be displayed. 
https://github.com/sourcegraph/sourcegraph/assets/7345368/7faeacc6-77eb-4ddc-9493-d98b847c2aad
=> JetBrains: enabled summarize recent code changes recipe

dev/release/release-config.jsonc, dev/release/templates/patch_release_issue_template.md, dev/release/templates/release_issue_template.md
=> relesae: finish 5.0.6 and minor template improvements

cmd/frontend/internal/cli/autoupgrade.go
Likely solves issue of dependent services picking up sentinel conf in local dev before frontend realizes it doesnt have anything to do
N/A trivial change : )
=> mvu: early-out autoupgrade if no work needed

client/web/src/nav/GlobalNavbar.tsx
[Figma discussion ](https://www.figma.com/file/ZkJFUvVzZW9TgFg7k9w9Oq/App-%5BMAIN%5D?type=design&node-id=1-222&t=TXq4Iih5PcKEHSQ2-0#469536099)
Enterprise button in the navbar is no longer shown
=> app: remove enterprise button in navbar

client/web/src/enterprise/own/RepositoryOwnEditPage.tsx, client/web/src/enterprise/own/RepositoryOwnPage.tsx
Closes #53457
Visual assessment and [Loom](https://www.loom.com/share/2fafbf18129a4c2686aa065479843dbc?sid=46661a68-fac6-4084-833e-78e4658bd758)
=> Change Edit ownership to Upload CODEOWNERS

CHANGELOG.md
changelog: cut sourcegraph@5.1.0
N/A
---
Part of https://github.com/sourcegraph/sourcegraph/issues/49918.
=> changelog: cut sourcegraph@5.1.0

enterprise/cmd/cody-gateway/internal/httpapi/diagnostics.go
=> cody-gateway: halt the response with invalid secret

enterprise/cmd/cody-gateway/internal/dotcom/BUILD.bazel, enterprise/cmd/cody-gateway/internal/dotcom/gen.go, enterprise/cmd/cody-gateway/internal/dotcom/genhelper/BUILD.bazel, enterprise/cmd/cody-gateway/internal/dotcom/genhelper/genhelper.go, enterprise/cmd/cody-gateway/internal/dotcom/genql.yaml, enterprise/cmd/cody-gateway/internal/dotcom/operations.go
Fixes https://github.com/sourcegraph/sourcegraph/issues/53007
CI
=> cody-gateway: re-enable GQL generate

CHANGELOG.md
=> Clarify cody feature flags changelog entry

client/web/src/cody/components/ChatUI/ChatUi.tsx
=> Cody web: fix tooltip for thumbs down

doc/dependency_decisions.yml
License check was failing with two new libraries that were added
ran the check locally
=> licenses: approve npm packages

client/web/src/enterprise/user/productSubscriptions/__snapshots__/UserSubscriptionsProductSubscriptionPage.test.tsx.snap
Didn't get caught in PR CI 🤔 Seems to be failing in main
CI
=> client/productSubscriptions: fix snapshot

shell.nix
Used by some frontend stuff
N/A nix stuff
=> nix: add sed to bazel path

client/web/src/repo/blob/CodeMirrorBlob.tsx, client/web/src/repo/blob/backend.ts, client/web/src/repo/blob/codemirror/scip-snapshot.ts, cmd/frontend/graphqlbackend/codeintel.codenav.graphql, enterprise/internal/codeintel/codenav/BUILD.bazel, enterprise/internal/codeintel/codenav/service.go, enterprise/internal/codeintel/codenav/shared/types.go, enterprise/internal/codeintel/codenav/transport/graphql/root_resolver_raw_scip.go, internal/codeintel/resolvers/codenav.go
Adds relationship data to scip snapshot UI in blob view
=> codeintel: add additional relationship data to snapshot view

enterprise/internal/embeddings/index_storage.go
If we encounter an error while gob encoding the index, we close the pipe without an error. This causes the upload store to store the index successfully rather than failing as it should.
This PR modifies the logic so it will close the pipe on error rather than allowing the upload to succeed. This is a possible explanation for some index corruption we were seeing. 
Embedded a repo to make sure it works. I can't actually find a way to trigger an error on this, so I can't write an automated test.
=> Embeddings: close pipe with error

doc/cody/explanations/policies.md
Follow-up based on a PR comment in #53603
Just a text change
=> docs: give examples for policy patterns

doc/dev/background-information/bazel/faq.md, doc/dev/background-information/bazel/index.md
Scratched my head for a while over this
No more head scratchies
=> bazel: update FAQ with networking

client/web/src/enterprise/EnterpriseWebApp.tsx, client/web/src/enterprise/app/setup/steps/AppAllSetSetupStep.module.scss, client/web/src/enterprise/app/setup/steps/AppAllSetSetupStep.tsx
Designs https://www.figma.com/file/ZkJFUvVzZW9TgFg7k9w9Oq/App-%5BMAIN%5D?type=design&node-id=62-661&t=PZMjaLVAmJdI4ZIx-0
- Check that the last step has the most recent copy and layout
=> Setup: Fix layout and copy for the last app setup screen

doc/app/index.md
Let users know which link to download depending on their operating system. 
n/a docs change
=> Update app download instructions

client/shared/src/testing/batches.ts, client/web/src/components/diff/FileDiffNode.story.tsx, client/web/src/enterprise/batches/close/BatchChangeClosePage.story.tsx, client/web/src/enterprise/batches/settings/RemoveCredentialModal.story.tsx, client/web/src/enterprise/batches/settings/ViewCredentialModal.story.tsx, client/web/src/enterprise/own/RepositoryOwnEditPage.tsx, client/web/src/site-admin/SiteAdminSidebar.story.tsx
`pnpm build-ts` runs successfully.
=> Fix a couple of Typescript errors (pnpm build-ts)

doc/cody/explanations/enabling_cody.md
Tiny change, but better get it out sooner than later.
- N/A
=> docs: remove outdated instruction on Cody+dotcom

doc/cody/explanations/cody_gateway.md
https://sourcegraph.slack.com/archives/C05497E9MDW/p1687292706080529
n/a
=> doc/cody: mention cody-gateway.sourcegraph.com domain

doc/app/index.md
Replace latest version in Cody App docs with 6-21-23 release. 
n/a docs update
=> Add cody app 6-21-23 release

doc/cody/explanations/code_graph_context.md, doc/cody/explanations/policies.md
Run sg run docsite and navigate to the relevant page.
=> Add additional information about embeddings

deps.bzl, internal/search/backend/zoekt.go
=> search: use new WithSearcher API for zoekt

enterprise/cmd/frontend/internal/own/resolvers/BUILD.bazel, enterprise/cmd/frontend/internal/rbac/resolvers/BUILD.bazel, enterprise/internal/codeintel/uploads/internal/store/BUILD.bazel, internal/oobmigration/migrations/batches/BUILD.bazel
Chore, adjust things to avoid failures 
CI
=> bzl: chore, adjust timeouts/flaky/size

enterprise/internal/licensing/check.go, enterprise/internal/licensing/check_test.go
=> [license-checks] use dotcom url from env

client/cody-shared/src/chat/recipes/find-code-smells.ts
This PR closes #53920.
Tested it manually for larger inputs, and it works fine.
=> Cody: Fix smell code recipe token length

client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.tsx, client/web/src/enterprise/own/admin-ui/query.ts, cmd/frontend/graphqlbackend/own.go, cmd/frontend/graphqlbackend/own.graphql, enterprise/cmd/frontend/internal/own/resolvers/resolvers.go, enterprise/cmd/frontend/internal/own/resolvers/resolvers_test.go, enterprise/internal/own/background/analytics_test.go, internal/database/ownership_stats.go, internal/database/ownership_stats_test.go, internal/database/repo_paths.go
Test plan:
GraphQL tests updated.
=> own: add information when Own statistics were last generated. (#53663)

client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.java
Leftover from https://github.com/sourcegraph/sourcegraph/pull/53370
Green CI.
=> JetBrains: Remove unintended println statement

doc/cody/faq.md
=> add FAQ about Cody API

client/web/src/repo/blob/own/FileOwnershipPanel.tsx, client/web/src/repo/blob/own/OwnerList.tsx, client/web/src/repo/blob/own/TreeOwnershipPanel.tsx
Test plan:
Closes https://github.com/sourcegraph/sourcegraph/issues/53929
=> own: fix "Add owner" button accidentally (not) showing.

client/cody-agent/BUILD.bazel
Bazel files on main are broken
N/A
=> bazel configure

client/web/src/repo/blob/own/FileOwnershipPanel.tsx, client/web/src/repo/blob/own/OwnerList.tsx, client/web/src/repo/blob/own/TreeOwnershipPanel.tsx
=> own: fix "Add owner" button accidentally (not) showing. (#53951)

cmd/frontend/graphqlbackend/slow_requests_tracer.go, dev/buildchecker/main.go
:canned_food: 
N/A tiny correctness fix for errors.Append
=> fix cases of err being discarded from errors.Append

doc/cody/explanations/code_graph_context.md
=> Removes redundant text

doc/cody/explanations/index.md
=> Change link to match an earlier rename

doc/cody/explanations/code_graph_context.md
=> Reduce the number of "NOTE" boxes

doc/cody/client_feature_availability.md, doc/cody/index.md
Docs change - rendered correctly
=> Add feature breakdown for clients

enterprise/cmd/frontend/internal/auth/githubappauth/middleware.go
GitHub's REST API is accessed at `http(s)://api.HOSTNAME.com` on Cloud but `http(s)://HOSTNAME/api/v3` for GHE server instances. The GitHub App creation workflow built up a URL to create an App from a manifest assuming the Cloud API URL schema, which caused the creation flow to fail partway with a TCP lookup error. This PR uses the common utility function `github.APIRoot` to look at the incoming (referer) URL and build the appropriate API URL based on it. The flow now completes successfully for both GHE and Cloud instances.
There's currently a separate issue when it comes to displaying the "identicon" of the App on GHE from within the Sourcegraph UI. As you can see in the screenshot above, we can't load the resource properly. The resource URL is correct, but it's locked behind a login …
=> github app: fix manifest endpoint URL for GHE instances

doc/admin/repo/perforce.md
5.1 introduces new Perforce features. Update the documentation to include those features.
docs
=> Update Perforce support documentation

enterprise/cmd/frontend/internal/own/resolvers/codeowners.go, enterprise/cmd/frontend/internal/own/resolvers/resolvers_test.go
=> Update uploaded CODEOWNRES file URL so that CODEOWNERS badge linking works

client/web/src/repo/blob/own/HistoryAndOwnBar.tsx, client/web/src/repo/blob/own/grapqlQueries.ts
Part of #53739 
To check it out:
1. Setup p4 locally, it's super easy LOL @indradhanush 
- enable `perforceChangelistMapping` feature
3. Go to recent CLs on a perforce depot.
4. Click one changelist number
5. Go to a modified file
Before:
After:
Visual assessment.
=> Fix history and own bar

src-tauri/tauri.conf.json
Sets a minimum window size
resolves https://github.com/sourcegraph/sourcegraph/issues/53960
`sg start app` resize ensure it stops at specified size
=> App - set a minimun window size

dev/backcompat/defs.bzl
OTEL stuff moved packages around, which messed our ability to build old code. This is happening because we're building the old code with our new `deps.bzl` (there isn't really an easy way around that for now). 
CI, backcompat test passed.
=> bzl: fix backcompat buildfiles breakage

client/web/src/enterprise/app/setup/steps/AppWelcomeSetupStep.module.scss
Fixes distortion of the image on first step of the App setup flow
resolves https://github.com/sourcegraph/sourcegraph/issues/53764
=> App - fix welcome image distortion

client/web/src/enterprise/app/setup/steps/AppAllSetSetupStep.module.scss
Fix the image distortion on the app app set page of the welcome flow
=> App - fix image distortion on app all set page

client/web/src/enterprise/app/settings/local-repositories/LocalRepositoriesTab.tsx
Fix regression after https://github.com/sourcegraph/sourcegraph/pull/53838
- Make sure that you can select local repositories and schedule them for the embeddings
=> Fix regression after new local repositores API changes

enterprise/cmd/executor/internal/worker/command/kubernetes.go, enterprise/cmd/executor/kubernetes/batches/executor-batches.Deployment.yml
A print statement snuck past me.
Also fixed the image that is being used for local development. It now matches what is configured in `sg.config.yml`
Manual testing
=> executors: Fix local testing issues

client/web/src/enterprise/codeintel/configuration/components/RepositoryPatternList.tsx
Fix #54057 
- Run app and test manually
=> App: Remove link in repository pattern list in App

client/web/src/site-admin/SiteAdminUpdatesPage.tsx
Add button to download drift as a json file if there is any.
=> upgrades: Add download drift button

client/jetbrains/CONTRIBUTING.md
=> JetBrains: add documentation on how to disable agent on local runs

client/cody/README.md
Updates the README to include GIF versions of our walkthrough videos.
Primary purpose is to improve our VS Code listing page.
N/A - Docs change
=> Cody: Update README to include example animations

doc/admin/repo/perforce.md
=> doc: Document behaviour of authz.enforceForSiteAdmins with p4 permissions

client/jetbrains/gradle.properties, client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java, client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowFactory.java, client/jetbrains/src/main/java/com/sourcegraph/cody/TruncationUtils.java, client/jetbrains/src/main/java/com/sourcegraph/cody/UpdatableChat.java, client/jetbrains/src/main/java/com/sourcegraph/cody/api/CompletionsInput.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/Chat.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatMessage.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ContextFilesMessage.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/Interaction.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/Transcript.java, client/jetbrains/src/main/java/com/sourcegraph/cody/context/ContextGetter.java, client/jetbrains/src/main/java/com/sourcegraph/cody/context/ContextMessage.java, client/jetbrains/src/main/java/com/sourcegraph/cody/context/embeddings/EmbeddingsSearcher.java, client/jetbrains/src/main/java/com/sourcegraph/cody/editor/EditorContext.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/RecipeRunner.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SummarizeRecentChangesRecipe.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/TruncatedText.java, client/jetbrains/src/main/java/com/sourcegraph/cody/ui/AccordionSection.java, client/jetbrains/src/main/java/com/sourcegraph/vcs/RepoUtil.java, client/jetbrains/src/main/resources/META-INF/plugin.xml
- Closes #53251 
This is WIP because some of the recipes don't work with these changes for some threading issues.
For reviewers: It probably makes the most sense to go **commit by commit** when reviewing the code. 90% of the commits are trivial, and I documented them in the commit messages. Then what remains is one meaty commit that's much easier to review with the rest out of your way.
Also in this PR:
- Fix for the inability to copy text from the chat because text input was focused all the time https://github.com/sourcegraph/sourcegraph/commit/6287965c157cb5f85d8c26369d3f6d4dd400ccd9 
- Added basic styling of the Read files output https://github.com/sourcegraph/sourcegraph/pull/53620/commits/0a14ab182077052966247fcf877ce1206df49138
=> JetBrains: enable embeddings-based context

internal/database/ownership_stats.go, internal/database/ownership_stats_test.go, internal/database/repo_paths.go, internal/database/repo_paths_test.go
Test plan:
Unit tests updated/added.
https://github.com/sourcegraph/sourcegraph/assets/94846361/cc81648d-ae24-4155-bc3c-310ffe0c439b
Closes https://github.com/sourcegraph/sourcegraph/issues/54031
=> own: don't count excluded paths in ownership analytics.

client/web/src/repo/blob/own/FileOwnershipEntry.tsx, client/web/src/repo/blob/own/FileOwnershipPanel.tsx, client/web/src/repo/blob/own/OwnerList.tsx, client/web/src/repo/blob/own/TreeOwnershipPanel.tsx
Test plan:
https://github.com/sourcegraph/sourcegraph/assets/94846361/a0f01363-3cbe-4f41-b155-5ec1bfa9ec0b
Closes https://github.com/sourcegraph/sourcegraph/issues/53942
=> own: show remove/add owner buttons only to the users with relevant rights.

client/web/src/repo/blob/own/FileOwnershipPanel.story.tsx, client/web/src/repo/blob/own/OwnerList.tsx, client/web/src/repo/tree/TreePageContent.tsx, enterprise/cmd/frontend/internal/own/resolvers/recent_contributors_signal.go, enterprise/cmd/frontend/internal/own/resolvers/recent_view_signal.go, enterprise/cmd/frontend/internal/own/resolvers/resolvers_test.go
Test plan:
| :-- | :-- |
| <img width="472" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/94846361/0e8ed99c-4448-4f00-b70d-0879b9ff5dc6"> | <img width="1000" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/94846361/065af549-a721-40b1-9a91-8ee0443d8b59"> |
| <img width="1155" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/94846361/e336600d-eea5-4ade-bc42-8215a18d2647"> | <img width="1155" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/94846361/d49fbca9-9795-4f28-91d6-1af9c391afd5"> | 
Closes https://github.com/sourcegraph/sourcegraph/issues/53949
=> own: update wording, remove owner count from tree page.

doc/admin/access_control/index.md, doc/admin/access_control/ownership.md, doc/own/assigned_ownership.md, doc/own/codeowners_format.md, doc/own/codeowners_ingestion.md, doc/own/index.md, doc/sidebar.md
Test plan:
Local sg run and check that docs are rendered adequately.
Part of https://github.com/sourcegraph/sourcegraph/issues/53654.
=> own: add docs about assigned ownership.

doc/batch_changes/explanations/introduction_to_batch_changes.md, doc/batch_changes/how-tos/configuring_credentials.md, doc/batch_changes/references/requirements.md
=> Gerrit BC docs

doc/cody/explanations/code_graph_context.md
=> Add note about embeddings creation

cmd/gitserver/server/patch.go
instead of using the patch commit hash, the base commit hash was being used to find the list of files affected by the patch, resulting in an empty list of files.
Run Perforce BC and see the publish.
=> fix bug in batch changes for perforce

CHANGELOG.md
fix to be included in correct release
CI
=> update 5.1 changelog

doc/cody/explanations/code_graph_context.md
=> add note for cloud customers about manually enabling embeddings

client/web/src/enterprise/app/components/zero-states/AppZeroStates.tsx, client/web/src/enterprise/app/setup/steps/AppAllSetSetupStep.module.scss, client/web/src/enterprise/app/setup/steps/AppAllSetSetupStep.tsx, client/web/src/enterprise/app/setup/steps/AppInstallExtensionsSetupStep.module.scss, client/web/src/enterprise/app/setup/steps/AppInstallExtensionsSetupStep.tsx, client/web/src/enterprise/app/setup/steps/AppLocalRepositoriesSetupStep.module.scss, client/web/src/enterprise/app/setup/steps/AppWelcomeSetupStep.module.scss, client/web/src/enterprise/app/setup/steps/AppWelcomeSetupStep.tsx
Copy updates to the App startup flow
Walk though startup and observer changes
=> App - copy updates to setup flow

doc/admin/external_services/object_storage.md
Clarifies which instances need ec2 role credentials.
Doc update
=> Update note about ec2 role credentials

client/cody-shared/src/chat/preamble.ts
=> Fix typo in Cody's preamble

cmd/gitserver/server/server_grpc.go
Using the generated getters protects against *proto.P4ExecRequest being nil (which is valid, since all fields are optional to send in protobuf). 
Existing unit tests
=> grpc: gitserver: use generated getters to access fields for p4exec

doc/code_navigation/how-to/combining_scip_uploads_from_ci_cd_and_auto_indexing.md, doc/code_navigation/how-to/index.md, doc/code_navigation/how-to/policies_best_practices.md, doc/code_navigation/how-to/policies_resource_usage_best_practices.md
=> docs: Update policies docs based on customer feedback

doc/code_navigation/how-to/configure_auto_indexing.md, doc/code_navigation/how-to/configure_data_retention.md, doc/code_navigation/index.md
Fixes [broken `main`](https://buildkite.com/sourcegraph/sourcegraph/builds/230882)
Docs update
=> docs: Fix broken links

internal/database/event_logs.go, internal/eventlogger/event_logger.go
Test locally to ensure pings are generated correctly
=> Exclude CodyVSCodeExtension:CodySavedLogin:executed event from pings

doc/cody/client_feature_availability.md
=> Add current availability note to cody clients

cmd/gitserver/server/patch.go
found a bug where untar was not overwriting the file, causing changelists with unchanged files to be shelved
run through the batch change process as described in [the original PR](https://github.com/sourcegraph/sourcegraph/pull/52127), then use P4V to confirm that the file(s) in the shelved changelist contain changes
more/better automated testing coming in separate PR
=> perforce batch changes bug fix

client/cody/README.md
Part of #53922
Just some minor tweaks to the autocomplete section.
wysiwyg
=> Cody: Tweak readme (call it autocomplete)

client/web/src/enterprise/app/setup/steps/AppAllSetSetupStep.tsx, client/web/src/enterprise/app/setup/steps/AppLocalRepositoriesSetupStep.tsx
Copy updates as per https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1687859827752239
👀
=> app: Copy updates

docker-images/syntax-highlighter/crates/scip-syntax/queries/go/scip-references.scm, docker-images/syntax-highlighter/crates/scip-syntax/src/languages.rs, docker-images/syntax-highlighter/crates/scip-syntax/src/lib.rs, docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__symbols__test__generates_go_symbols.snap, docker-images/syntax-highlighter/crates/scip-syntax/src/symbols.rs, docker-images/syntax-highlighter/crates/scip-syntax/testdata/symbols.go, docker-images/syntax-highlighter/src/main.rs
=> this one is for cesar

client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java, client/jetbrains/src/main/java/com/sourcegraph/cody/completions/AcceptCodyCompletionAction.java, client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java, client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SummarizeRecentChangesRecipe.java, client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
=> Fix JetBrains event logging

enterprise/cmd/cody-gateway/internal/events/buffered.go
The backlog filled up a few times this weekend. My hunch is GCP issues, but Cloud Trace querying is worse than I thought and I think the lack of a span here is causing the Sentry event's associated span to be invalid, so this change adds an explicit span that will help us locate traces that failed to buffer.
Hoping to revisit metrics sometime: https://github.com/sourcegraph/sourcegraph/issues/53775
CI
=> cody-gateway/events/buffered: add span

doc/app/index.md, doc/cody/explanations/installing_jetbrains.md, doc/cody/index.md
Quick, initial update to mention the Cody Jetbrains extension. 
docs update n/a
=> Add initial jetbrains docs

doc/app/index.md
Update app download links 
n/a docs change
=> Update app download links

doc/app/release-pipeline.md
Add a note about entitle bundle needed for updating the manifest.
docs
=> App - add note about entitle bundle for updating app manifest

client/cody/CHANGELOG.md, client/cody/package.json
=> Cody: Release 0.4.0

doc/admin/executors/deploy_executors_kubernetes.md, doc/admin/executors/deploy_executors_terraform.md
To be merged when 5.1 is released.
Nothing, doc changes
=> docs/executors: uncomment multiqueue 5.1 additions 

client/jetbrains/CHANGELOG.md, client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java, client/jetbrains/src/main/java/com/sourcegraph/cody/UpdatableChat.java, client/jetbrains/src/main/java/com/sourcegraph/cody/api/ChatUpdaterCallbacks.java
Just a tiny fix to avoid breaking `@NotNull` requirements.
Note: also fixed two warnings
`@NotNull` error messages should disappear
=> JetBrains: Handle null error messages

client/jetbrains/CHANGELOG.md, client/jetbrains/src/main/resources/META-INF/plugin.xml
=> JetBrains: fix sidebar refresh for non-internal builds

client/jetbrains/CHANGELOG.md, client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java, client/jetbrains/src/main/java/com/sourcegraph/vcs/RepoUtil.java
Index git repository without a remote in the Cody app and then ask something about the project in the Chat, Cody should respond with proper context
=> Repositories without configured git remotes are now available for Cody

client/cody/CHANGELOG.md, client/cody/package.json, client/cody/src/configuration.ts
Preparing a bugfix release PR in case we want to ship some fixes quickly 👀 
- just a release version bump
=> Cody: Release 0.4.1

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
- Updated version
- Updated changelog
Already published on marketplace, so this is just housekeeping/syncing.
No code changes
=> JetBrains: Release 3.0.2

enterprise/cmd/executor/internal/worker/command/kubernetes.go
Fix issue with where the command is ran.
=> executors: Run git command in specified directory

doc/admin/config/batch_changes.md
This PR documents #54324 in `docs.sourcegraph.com`, so customers are aware of the bug we recently found.
Doc update.
=> batches: document known commit signing bug

client/web/src/site-admin/analytics/AnalyticsNotebooksPage/index.tsx
Onboarding was misspelled in product. Corrected
This is a typo fix, no testing needed
=> Fixed a typo

internal/gitserver/client.go
https://github.com/sourcegraph/sourcegraph/pull/54395#discussion_r1245677785
CI
=> batchlog: add defensive err check

enterprise/internal/codeintel/codenav/commit_cache.go
Fixes a few issues:
- We previously would send duplicates to gitserver, so it was possible to get a large page of the same repo/commit pair which I think caused index rewrite issues of its own. We now deduplicate by inverting the index map so we can have multiple source indexes pointing to the same output index.
- When we can't resolve a repository name we `continue` the loop but later make the assertion that the slice we construct in that loop is a particular size. We should instead add a sentinel value so that we just keep the ouput `false` for those particular inputs.
=> commit cache: Fix bug in gitserver input reconstruction

client/cody/CHANGELOG.md, client/cody/package.json
0.4.2 Release version bump
Will merge this once https://github.com/sourcegraph/sourcegraph/pull/54405 is merged
version bump
=> Cody: Release 0.4.2

internal/database/connections/live/runner.go
Koow when an empty dsn
yes you do
=> upgrades: Quote dsn printing in log message

doc/admin/repo/perforce.md
=> doc: Add limitations of CL IDs in URLS for perforce depots

doc/admin/audit_log.md, doc/cloud/index.md
Finalize docs for audit logs
Part of https://github.com/sourcegraph/pr-faqs/issues/139
n/a, doc update
=> Add docs for Cloud audit logs

.github/test.CODEOWNERS, client/branded/src/search-ui/components/CODENOTIFY, client/web/src/enterprise/code-monitoring/CODENOTIFY, client/web/src/integration/CODENOTIFY, client/web/src/search/CODENOTIFY
=> chore: removing myself from codenotify/codeowners

CHANGELOG.md
Adding known issue for repo permission problem in 5.1
N/A just changelog
=> docs: known issues 5.1

CHANGELOG.app.md
Brings the app change log more up to date.
=> App - bring change log up to date

internal/repos/other.go, internal/repos/other_test.go
Fix explicit perms for srce expose for Other code host type
Manual
=> Fix explicit perms for src expose for Other code host type

dev/release/release-config.jsonc
=> 5.1.1 release config

CHANGELOG.md
=> 5.1.1 changelog

client/cody-agent/LICENSE
See https://sourcegraph.slack.com/archives/C05B7C6FBPX/p1687544789705619?thread_ts=1687455542.280179&cid=C05B7C6FBPX
N/A
=> Apache License Cody Agent

doc/admin/external_service/gitlab.md
Adds the correct access token scopes needed for syncing GitLab repos
N/A
=> Update access token scopes

client/cody/CONTRIBUTING.md
=> Cody: Improve release documentation

enterprise/dev/ci/internal/ci/bazel_operations.go
Follow-up to https://github.com/sourcegraph/sourcegraph/pull/54487
CI
=> bzl: also build bundle-enterprise first

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
Just submitted all of the past two days' changes to the JetBrains marketplace. This PR is only housekeeping to update the repo.
(Only docs changes)
=> JetBrains 3.0.3

doc/_resources/assets/docsite.css, doc/_resources/templates/root.html
=> Docs AI: Combine LLM prompt with instant search

cmd/searcher/internal/search/search_grpc.go, internal/grpc/internalerrs/common.go, internal/grpc/internalerrs/common_test.go
Slack link: https://sourcegraph.slack.com/archives/C04HCK4K3DL/p1687381299999559
>I'm getting this error running some searches using the internal search client
>
> 
> ```
> insightsSearchClient searcher/search.go:120 searchFilesInRepo failed {"error": "rpc error: code = Unknown desc = transport: received unexpected content-type \"application/octet-stream\"", "repo": "github.com/sourcegraph/sourcegraph"}
> ```
> 
The documentation for `grpc.ServerStream.SendMsg()` [states](https://github.com/grpc/grpc-go/blob/5b67e5ea449ef0686a0c0b6de48cd4cb63e3db2a/stream.go#L1509C1-L1515):
> 
>    // SendMsg sends a message. On error, SendMsg aborts the stream and the
>    // error is returned directly.
>    // ...
>    // It is safe to have a goroutine calling SendMsg and another goroutine
>    // …
=> grpc: searcher: fix race condition with server.send message

client/cody/CONTRIBUTING.md
Updates Cody Clients getting started markdown for commands & useful debugging tooling
N/A
=> Update cody client CONTRIBUTING.md doc

CHANGELOG.md
Updating the changelog in `main` to include the fixes in `5.1.2`
Chnagelog update
=> update changelog with 5.1.2 fixes

enterprise/internal/codeintel/autoindexing/internal/inference/libs/indexes.go
Le bump
N/A bumping already tested indexer shas
=> codeintel: bump indexer shas

doc/dev/how-to/wolfi/add_update_images.md
- Documentation - manually inspect docs site
=> Fix broken link in wolfi docs

enterprise/cmd/frontend/internal/insights/httpapi/export.go, enterprise/cmd/frontend/internal/insights/resolvers/dashboard_resolvers.go, enterprise/cmd/frontend/internal/insights/resolvers/insight_view_resolvers.go, enterprise/cmd/frontend/internal/insights/resolvers/validator.go, enterprise/internal/insights/store/dashboard_store.go, enterprise/internal/insights/store/dashboard_store_test.go, enterprise/internal/insights/store/insight_store.go, enterprise/internal/insights/store/insight_store_test.go
solves #33075 
Run diagnostics with telescope to find all instances where variable names need to change. Shipped with all tests passing.
=> pluralize variable names when representing slices/arrays

client/cody-shared/src/codebase-context/index.ts, client/cody-shared/src/sourcegraph-api/graphql/queries.ts, client/cody-shared/src/unified-context/client.ts, client/cody-shared/src/unified-context/index.ts
No logical changes. Updated & improved typing for unified context fetcher so it easily supports more context types in future. 
- validate if context files are passed correctly to the stream request.
=> Refactor unified context fetcher

client/cody/CHANGELOG.md
Realised I forgot to update as I clicked merge 😬 
N/A - Docs change
=> Cody: Update changelog

dev/release/src/batchChanges.ts
Update SRC endpoint for release Batch Change.
* Create a batch change with the release tool, the batch change should be created on `sourcegraph.sourcegraph.com`
=> release: update SRC endpoint for release Batch Change

enterprise/internal/own/ownref.go
Test plan:
Closes https://github.com/sourcegraph/sourcegraph/issues/52547
=> own: add an error in a weird case of a team not found by ID.

client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx
The cancel button did nothing, now it correctly goes back to the list view again.
Verified works.
=> Fix cancel button on token create form page

client/jetbrains/CHANGELOG.md, client/jetbrains/src/main/java/com/sourcegraph/cody/api/ChatUpdaterCallbacks.java, client/jetbrains/src/main/java/com/sourcegraph/cody/api/SSEClient.java, client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java, client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CompletionsProviderType.java, client/jetbrains/src/main/java/com/sourcegraph/cody/completions/UnstableCodegenLanguageUtil.java, client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/CodyCompletionItemProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/CompletionProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/SourcegraphNodeCompletionsClient.java, client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/UnstableCodegenEndOfLineCompletionProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/WebviewErrorMessenger.java, client/jetbrains/src/main/java/com/sourcegraph/cody/localapp/LocalAppManager.java, client/jetbrains/src/main/java/com/sourcegraph/cody/localapp/LocalAppPaths.java, client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/IntelliJTextDocument.java, client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/TextDocument.java, client/jetbrains/src/main/java/com/sourcegraph/vcs/RepoUtil.java, client/jetbrains/src/test/java/LocalAppManagerTest.java, client/jetbrains/src/test/java/com/sourcegraph/cody/completions/UnstableCodegenLanguageUtilTest.java, client/jetbrains/src/test/java/com/sourcegraph/cody/vscode/TestTextDocument.java
Follow-up refactor after #54435 
- switch logging to JetBrains api
- other misc refactorings based off https://github.com/sourcegraph/sourcegraph/pull/54435#pullrequestreview-1507103923
- Green CI
=> JetBrains: Refactor `unstable-codegen` completions

CHANGELOG.md
Also link to https://github.com/sourcegraph/sourcegraph/issues/53528#issuecomment-1594967818.
n/a
=> update relicense changelog entry with more info

doc/admin/subscriptions/index.md
Docs change only. Tested locally.
=> Update note on pricing page.

enterprise/cmd/frontend/internal/own/resolvers/resolvers.go
Clearing the own board might as well knock off some tiny tasks.
Test plan:
Closes https://github.com/sourcegraph/sourcegraph/issues/52895.
Closes https://github.com/sourcegraph/sourcegraph/issues/54569.
=> own: make Own resolver nil-safe by adding relevant checks.

doc/getting-started/index.md
This PR adds mentions Cody being open-source with GH repo links to our extensions.
* Check links
=> Improve open source messaging and add Cody

src-tauri/src/common.rs, src-tauri/src/tray.rs
Change verified by Sourcegraphers
=> App: use unwrap_or_else() with shell::open()

cmd/frontend/graphqlbackend/access_tokens.go, cmd/frontend/graphqlbackend/access_tokens_test.go
We rely on Sourcegraph Operator (SOAP) accounts to manage Cloud instances. Currently there are protections in place to prevent customer admins from seeing or deleting SOAP users, but in one case it seems a customer has managed to find our service account and delete its access tokens, breaking our automation.
This change ensures that if the actor is not a SOAP user, the owner of a token being deleted must not be a SOAP user.
Unit tests
=> accesstokens: only allow SOAP users to delete SOAP user access tokens

client/cody-shared/src/chat/typewriter.ts
Using a `MAX_CHAR_CHUNK_SIZE` works well right now, mainly because our targeted LLM's are still quite slow to return text. If we have much faster responses in the future we will want to ensure this chunk size scales appropriately, otherwise we will find that the typewriter will lag behind the text too much. ([mentioned](https://github.com/sourcegraph/sourcegraph/pull/54522#discussion_r1253369950) by @chrispine!)
Now, if we want that we need a typing interval less than 5ms, we work out the character chunk size that would be required for us to keep that interval of 5ms.
Example:
Lagging behind 200 chars
--> Calculated typing interval = 1ms per character
--> Actual typing interval = 5ms (default for some visible typing effect)
--> Calculated chunk size = 5 characters per interval
Lagging …
=> Cody Typewriter: Use a dynamic character chunk size

CHANGELOG.md, doc/admin/repo/auth.md
=> Add docs about support for rsa-sha signatures

.github/workflows/label-move.yml, .github/workflows/label-notify.yml, .github/workflows/move-labled-issues-to-project.yml
Test plan:
Try new actions as soon as this PR is merged.
=> chore: remove IAM/RM related GH actions in favour of Source.

dev/release/templates/release_issue_template.md
Things I found missing or can be improved during the 5.1.0 release.
n/a
=> release: improve minor release template

doc/_resources/assets/docsite.css, doc/_resources/templates/root.html
This PR bumps `@markprompt/web` to the latest version (0.10.0), which uses the new Markprompt search API endpoint. This addresses the following:
- Improved title formatting: in some situations, the kwic function was truncating too much text around the keyword. This is no longer the case.
- Improved ranking: the new API modifies the weight put on page title (highest), section heading, paragraph, improving the ranking of the results.
- Improved speed: we've updated the way content and metadata is indexed, which boosts query performance.
- Better handling of image/figure titles, such as [the Cody page](https://docs.sourcegraph.com/cody) which uses a figure as heading. Markprompt now grabs the `title` property in case of a figure, or the `alt` property in case of an image.
Manual testing
=> Markprompt v0.10.0

.github/workflows/label-notify.yml
=> chore: add label notify for `cody-gateway`

client/jetbrains/CHANGELOG.md, client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/AnthropicAutoCompleteProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/AutoCompleteProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/CodyAutoCompleteItemProvider.java, client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/PostProcess.java, client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/TextProcessing.java, client/jetbrains/src/test/java/PostProcessTest.java
Fixes #54269 
~Depends on: https://github.com/sourcegraph/sourcegraph/pull/54606, so that should be merged first~
I've no idea how to test if it works as expected, but it doesn't seem to break, either.
The frankencode 🧟  that is the `prompt_library` in its current state (with select pieces moved over from the VS Code plugin irregularly) makes me also wonder if efforts like this one even make sense at all, given that the agent migration is imminent.
Either way, here it is.
- green CI 🟢 
- if you know what should have changed in the autocomplete suggestions, feel free to check if they behave as expected 🤷‍♂️
=> JetBrains: Cody: improve prompt

enterprise/internal/batches/sources/mocks_test.go, internal/gitserver/client.go, internal/gitserver/commands.go, internal/gitserver/commands_test.go, internal/gitserver/mocks_temp.go, internal/gitserver/protocol/gitserver.go
Saw in one of my recent changes that ListFiles wasn't getting used anymore, so lets get rid of it.
Just removing a method.
=> chore: remove unused ListFiles in gitserver client

doc/dev/background-information/ci/reference.md
fixes a lint error after removing prometheus-gcp
CI
=> go: linting fix

CHANGELOG.app.md
Updates change log for July 11th release.
n/a change log
=> App - update changelog for release

doc/app/index.md
It would be great to get this in earlier, but I'd like to set better expectations on what "soon" means. 
n/a docs change
=> Add Windows ETA

cmd/frontend/graphqlbackend/settings.go, internal/api/api.go, internal/api/httpapi_schema.go
=> Chore: remove unused code

internal/codeintel/uploads/internal/background/processor/job_worker_handler.go
cc @varungandhi-src Re-commented the flow and refactored so that we favor early-exits over global state (buf/indexReader being nil-able was confusing to determine what states were valid). I think the only behavioral change is we hard-error on the creation of a temp file instead of logging+doing our best. We can preserve that old behavior if it was an intentional design decision.
=> refactor file writing

cmd/gitserver/server/patch.go
[Slack thread](https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1689124650296469)
manual
=> Redact command before logging  during create-commit-from-patch

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
Already published, this is just to add the change to the repo
(Only docs change and version bump)
=> JetBrains: 3.0.4 release

dev/sg/internal/background/background.go
https://github.com/sourcegraph/devx-support/issues/83 reported that the update mechanism appeared to be broken. After digging around, if `sg` completes after the jobs are done, which is where the auto-update is happening, the error was not displayed. 
So we don't know why it didn't work, but at least the next time, we'll see what error we encountered. 
CI + local tests
=> sg: print jobs output even if all done before exit

client/jetbrains/CHANGELOG.md, client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatBubble.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/CodeEditorFactory.java, client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessageContentCreatorFromMarkdownNodes.java, client/jetbrains/src/main/java/com/sourcegraph/cody/ui/TransparentButton.java
Added insert code at current position button to editor in the chat. With this button you can paste the code provided by the Cody directly to your editor
This pr and https://github.com/sourcegraph/sourcegraph/pull/54783 closes #54141  
- Talk to Cody so it will generate some code block for you, hover the code block and click on the new button, the code should appear at your current cursor position in the main editor
=> JetBrains: show insert code at current position button

doc/cody/troubleshooting.md
via https://github.com/sourcegraph/cody/issues/6
* Check link
=> Update link to Cody issues

internal/search/backend/metered_searcher.go
The code was incorrectly reporting uses of ReposMap as the slower List field.
=> search: metered searcher handles all list field types

enterprise/internal/oobmigration/migrations/codeintel/scip/migrator.go
Fix case where no columns are being updated (but we still want to bump the schema version because we've written external data).
=> scip: symbol migrator bugfix

dev/release/release-config.jsonc
=> Release: update release config for 5.1.3

cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel, cmd/cody-gateway/internal/httpapi/completions/upstream.go, cmd/cody-gateway/internal/httpapi/embeddings/BUILD.bazel, cmd/cody-gateway/internal/httpapi/embeddings/handler.go, cmd/cody-gateway/internal/httpapi/embeddings/models.go, cmd/cody-gateway/internal/httpapi/embeddings/openai.go, internal/completions/types/errors.go
Closes https://github.com/sourcegraph/sourcegraph/issues/54756
n/a
=> cody-gateway: report timeout error to client if deadline exceeded

CHANGELOG.md
=> Release: update changelog for 5.1.3

cmd/frontend/internal/httpapi/search.go, cmd/frontend/internal/httpapi/search_test.go, internal/search/backend/indexers.go, internal/search/backend/indexers_test.go, internal/search/env.go
Minimal is deprecated. This switches us to requesting a ReposMap and using it.
Test Plan: CI
=> search: reposAtEndpoint uses ReposMap

dev/release/release-config.jsonc
=> release: deactivate 5.1.3 release

.github/workflows/update-embeddings-list.yml, dev/update-embeddings-list/README.md
add README and fix the github actions working dir
N/A
=> fix: wrong execution dir

.github/workflows/update-embeddings-list.yml, dev/update-embeddings-list/README.md
pnpm install not working 😢 
N/A
=> add freeze lockfile when using pnpm install

.github/workflows/update-embeddings-list.yml, dev/update-embeddings-list/README.md, dev/update-embeddings-list/package.json, dev/update-embeddings-list/src/index.ts
gave up compiling the build, just using `ts-node` to run the script now
N/A
=> fix: remove build files and fix all working dirs

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
Already published, just adding change to repo.
Just docs changes and version bump
=> JetBrains: Release 3.0.5

dev/release/release-config.jsonc
=> Release: activate 5.1.4 release

.github/ISSUE_TEMPLATE/dev-infra.md
Just a little utility to create issues
N/A this is a github issue template
=> gh: add an issue template for dev-infra

doc/dependency_decisions.yml
add MPL license and approve hashiscorp/go-retryablehttp
tested locally
=> licenses: approve hashicorp/go-retryablehttp

doc/dev/background-information/bazel/faq.md
Add an entry about a gotcha one might experience while updating docs
doc update
=> bazel: faq entry about doc:test

CHANGELOG.md
=> Release 5.1.4: update changelog

doc/dev/background-information/gRPC_internal_api.md
=> doc(grpc): make notes actually appear as notes

enterprise/cmd/worker/internal/embeddings/repo/handler.go
Some of the logs are missing the repo identifieres which makes it difficult to track progress in the logs.
Test plan:
CI
=> embeddings: log repo name and id

enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
This commit also cleans up usages of `SetDefaultHook` vs. `SetDefaultReturn`, simplifying the code.
Test plan:
CI.
Closes https://github.com/sourcegraph/sourcegraph/issues/48336
=> permissions-center: add tests for `permissionsInfoResolver` and `permissionsInfoUserResolver`.

client/web/src/components/externalServices/externalServices.tsx
We agree that this list isn't great, but until we have more time to redo this page wholistically, I think these added descriptions help a lot. At least they help me.
Visual inspection.
=> Add descriptions for code hosts

dev/release/release-config.jsonc
=> Release: clean up release config

client/web/src/enterprise/batches/settings/BatchChangesSiteConfigSettingsPage.story.tsx, client/web/src/enterprise/batches/settings/backend.ts, client/web/src/integration/batches.test.ts
Based on a message from @Piszmog [here](https://sourcegraph.slack.com/archives/C01C3NCGD40/p1689696870755769)
- Check that batch change setting page works as expected
- Check that the storybook story also have proper mocks
=> Fix fetch strategy and storybook stories for the batch changes site config page

internal/database/perms_store_test.go
Ran into this when running tests.
- Ran the tests
=> perms store: remove debug printing from test

enterprise/dev/ci/images/images.go
This updates the embeddings image tag in the `deploy-sourcegraph-*` repos.
Running the release tool.
I'm not sure of the best way to manually test this.
=> release: update embeddings image tag

cmd/gitserver/server/cleanup.go, cmd/gitserver/server/cleanup_test.go, cmd/gitserver/server/server.go
Test plan:
Local sg run and check that janitor commands are stored in Redis.
Closes https://github.com/sourcegraph/sourcegraph/issues/55149
=> gitserver: record Git commands during janitor job.

.github/workflows/label-move.yml, .github/workflows/label-notify.yml
I renamed the labels on GitHub. Let's rename them here too.
N/A
=> github workflow: rename labels

doc/code_search/tutorials/examples.md, doc/getting-started/index.md
=> add search examples app link to docs

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
Published this version to the marketplace.
Only docs and version change
=> JetBrains: Release 3.0.7

CHANGELOG.md, doc/KNOWN-ISSUES.md
Introduces the initial version of the 'Known Issues' page. This new page aims to communicate known bugs, issues, and workarounds to our users and admins.
Doc update
=> Docs: Add known issues page

doc/app/index.md, doc/cody/explanations/installing_jetbrains.md, doc/cody/index.md
Quick, initial update to mention the Cody JetBrains extension.
---------
Co-authored-by: David Veszelovszki <veszelovszki@gmail.com>
(cherry picked from commit 6967b8435fb594e75ca64a5bd9ee400fc524bcf9)
CI
=> Add initial jetbrains docs (#54329)

CHANGELOG.md, client/web/src/enterprise/code-monitoring/CodeMonitorList.tsx, client/web/src/enterprise/code-monitoring/CodeMonitoringNode.tsx, client/web/src/enterprise/code-monitoring/CodeMonitoringPage.story.tsx, client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx, client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.test.tsx, client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.tsx, client/web/src/enterprise/code-monitoring/backend.ts, client/web/src/enterprise/code-monitoring/components/CodeMonitorForm.tsx, client/web/src/enterprise/code-monitoring/testing/util.ts, client/web/src/integration/code-monitoring.test.ts, cmd/frontend/graphqlbackend/code_monitors.go, cmd/frontend/graphqlbackend/code_monitors.graphql, cmd/frontend/graphqlbackend/user.go, enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers.go, enterprise/cmd/frontend/internal/codemonitors/resolvers/resolvers_test.go, internal/database/code_monitor_emails.go, internal/database/code_monitor_emails_test.go, internal/database/code_monitor_monitors.go, internal/database/code_monitor_queries.go, internal/database/code_monitor_slack_webhook.go, internal/database/code_monitor_slack_webhook_test.go, internal/database/code_monitor_webhook.go, internal/database/code_monitor_webhook_test.go, internal/database/code_monitors.go, internal/database/mocks_temp.go
Closes https://github.com/sourcegraph/sourcegraph/issues/50898
<details>
<summary>Screenshot from site-admin user view</summary>
</details>
Added storybook test & manual local testing
=> monitors: show every users' code monitors to admins

deps.bzl, go.mod, go.sum
We found it didn't make a difference, so we removed it.
Test Plan: tested in the zoekt repo.
=> gomod: update zoekt to revert posting list optimization

internal/siteid/siteid.go, internal/siteid/siteid_test.go
=> make Get safe to call concurrently

doc/cody/explanations/index.md, doc/cody/explanations/installing_jetbrains.md, doc/cody/quickstart.md
No review required: making minor doc updates.
=> adding jetbrains link to page

enterprise/dev/ci/push_all.sh
fixes https://github.com/sourcegraph/devx-support/issues/125
CI on this PR
=> ci: publish images to dockerhub on main-dry-run

internal/database/migration/shared/data/cmd/generator/consts.go, internal/database/migration/shared/data/stitched-migration-graph.json, internal/database/migration/stitch/stitch.go
Closes #55048 
Tested by generating stitched migrations with `cd internal/database/migration/shared && go run ./data/cmd/generator --write-frozen=false` and building `migrator` then attempting `upgrade`
https://github.com/sourcegraph/sourcegraph/issues/55048#issuecomment-1648356419
WIP
=> Handle database migrations for release

CHANGELOG.md
Backport PR https://github.com/sourcegraph/sourcegraph/pull/55252
n/a
=> Changelog: document PR #55064

CHANGELOG.md
=> Add 5.1.5 changelog entry for PR #55113

internal/collections/set.go, internal/collections/set_test.go, internal/gqltestutil/BUILD.bazel, internal/gqltestutil/repository.go, internal/gqltestutil/search.go
Test plan:
Integration tests should pass.
=> chore: use set difference operation instead of a map.

client/jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/AutoGrowingTextArea.kt
Set parameters as nullable to avoid exceptions from intellij type checks
- Should be possible to write text in the chat
=> JetBrains: fix types after migration

dev/release/release-config.jsonc
=> release: activate 5.1.5 release

dev/release/release-config.jsonc
=> release: update release-config.jsonc

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
=> JetBrains: release 3.0.8

dev/release/release-config.jsonc
=> release: close 5.1.5 release

internal/codeintel/context/service.go, internal/codeintel/context/text.go, internal/codeintel/context/text_test.go
=> context: Zero-allocation snippets

doc/integration/gitlab.md
review the changes in the browser and make sure the link works
=> Adding GitLab Solution Brief link to GitLab doc page

internal/gitserver/client.go
- CI 
- Local dev instance works
=> internal/gitserver: Remove unused clientImplementor.ConnForRepo

doc/cody/index.md
This PR ships some improvement to the main Cody intro.
- [Here](https://docs.sourcegraph.com/@fix-cody-intro/cody)
- [Slack Thread](https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1690572986358889?thread_ts=1690566601.403829&cid=C01DXLN3D0T)
- Check links
=> Reword details for StackOverflow explanation

doc/cody/faq.md
This PR adds a list of programming languages that Cody supports.
- [Here](https://docs.sourcegraph.com/@cody-languages/cody/faq#what-programming-languages-cody-supports)
- [Slack Thread](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1690212809229439)
- Check links
=> Add list of supporting programming languages for Cody

CHANGELOG.md
=> 5.1.5 known issues

doc/_resources/assets/docsite.css, doc/_resources/templates/root.html
This PR updates Markprompt to v0.14, which features a tab-based layout, and improves keyboard navigation.
Manual testing
=> Upgrade to Markprompt 0.14

internal/updatecheck/handler.go
We were reading from the site config which is the value of the dotcom instance, not the actual value reported by the Sourcegraph instances.
Piggybacked few other minor changes found while reading the code.
n/a
=> updatecheck: read `HasCodyEnabled` from ping request

deps.bzl, go.mod, go.sum, internal/embeddings/db/BUILD.bazel, internal/embeddings/db/chunk_point.go, internal/embeddings/db/chunk_point_test.go, internal/embeddings/db/db.go, internal/embeddings/db/migrate.go, internal/embeddings/db/qdrant.go
This implements a new `VectorDB` abstraction with a qdrant backend. It's not used yet. Stacked PRs will incorporate this into the existing stack.
Tested in my branch, but this is all unused code right now. There are a couple of small unit tests for the easily testable things.
=> Embeddings: implement db package

client/web/src/site-admin/RepositoryNode.tsx
Test plan:
Local sg run and visual check.
Spotted by @indradhanush [here](https://sourcegraph.slack.com/archives/C05HF5XGMFF/p1691052793147489)
=> web: don't disable "Settings" menu item for uncloned repos.

doc/cody/index.md
This PR adds small modifications to the main Cody intro with the mention of being "free and open source".
- [Here](https://docs.sourcegraph.com/@cody-intro-fix/cody)
- Check links
=> Add small tweaks to Cody intro

cmd/cody-gateway/shared/config.go
[BaseConfig validation is called as part of the service framework we have](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/service/svcmain/svcmain.go?L211:1-223:3), but right now we're not using it correctly, overriding it with our own `Validate` implementation and adding errors incorrectly.
After fixing how we're holding this by moving `AddError` to `Load()` and removing our custom `Validate()` implementation (which was overriding the BaseConfig implementation entirely), we now get a bunch of errors emitted from BaseConfig:
```
Running cody-gateway...
[   cody-gateway] FATAL sourcegraph svcmain/svcmain.go:220 invalid configuration {"service": "cody-gateway", "error": "3 errors occurred:\n\t* invalid value \"\" for CODY_GATEWAY_BIGQUERY_PROJECT_ID: no value …
```
=> cody-gateway: fix adding validation errors, remove custom Validate()

doc/_resources/templates/root.html
Reverts sourcegraph/sourcegraph#55569
- Check links
=> Revert "Make docs links open in a new tab by default"

doc/admin/deploy/machine-images/aws-ami.md, doc/admin/deploy/machine-images/aws-oneclick.md, doc/admin/deploy/machine-images/gce.md
Executor AMI instructions
doc change
=> AMI executor instructions

internal/gitserver/client_test.go
This test was never enabled since it was first added to the code base and upon inspection this test actually clones a repo and stuff, which should not happen in the client tests. I don't see a strong reason for it to exist, given there are few other tests like this in the clients package, so I'm removing this for now. If someone feels strongly about re-adding a similar less overloaded test, please go for it. I also cleaned up some other conf mocks that I first thought to maybe have been the culprit.
Closes https://github.com/sourcegraph/sourcegraph/issues/55393
Removal of a test.
=> gitserver: Removed test that was never enabled

internal/httpcli/client.go
Still trying to get nice querying in Cloud Trace (no negation why????)
n/a
=> httpcli: set httpcli.retried=false on first attempt

CHANGELOG.md
=> release: changelog update for 5.1.6

cmd/frontend/graphqlbackend/access_requests_test.go, internal/database/accessrequests/access_requests.go, internal/database/database.go, internal/database/database_test.go, internal/database/mockclient.go
=> Add concept of Raw executable

doc/_resources/templates/root.html
This PRs fixes the search links to match with the Web component API changes.
- Check links
=> Fix Markprompt search links

doc/cody/index.md
=> Update aside/beta section

CHANGELOG.md
- Docs update - requires CI only
=> Security updates in changelog for 5.1.6

doc/dev/background-information/test-plans/code-hosts/bitbucket_server.md, doc/dev/background-information/test-plans/code-hosts/index.md, doc/dev/background-information/test-plans/index.md, doc/dev/index.md
[Converted from a google doc](https://docs.google.com/document/d/16PHT7JIsLpIWm4mGq8FVMQ3oyjR-rUoHWZCCTvYC3B4/edit).
closes #54749 : 
- https://github.com/sourcegraph/sourcegraph/issues/54749
docs changes only, tested locally by running docsite.
Can be [viewed directly here](https://docs.sourcegraph.com/@docs_bitbucket_server_test_plan/dev/background-information/test-plans/code-hosts)
=> Docs bitbucket server test plan

.github/workflows/scip-go.yml, .github/workflows/scip-typescript.yml
=> codeintel: Upload sg/sg to codyintel

CHANGELOG.md
=> 5.1.6 patch: Update CHANGELOG.md for gRPC changes

cmd/gitserver/shared/BUILD.bazel, cmd/gitserver/shared/config.go, cmd/gitserver/shared/config_test.go, cmd/gitserver/shared/shared.go, cmd/gitserver/shared/shared_test.go
This moves all properties from this package into the config, and makes proper use of validation. Also added some tests.
Added tests for defaults, gitserver still starts.
=> gitserver: Cleanup config

internal/database/external_services_test.go, internal/database/org_members_db_test.go, internal/database/permission_sync_jobs_test.go, internal/database/user_emails_test.go, internal/database/users_test.go, internal/database/util_test.go
We have a nice pointers package now, so this PR just replaces some helper functions with that package.
It builds.
=> Chore: replace pointer helpers with pointers package

doc/cloud/index.md, doc/cody/capabilities.md, doc/cody/explanations/enabling_cody_enterprise.md, doc/cody/explanations/use_cases.md
N/A. This PR removes content from docs.
=> remove references to Recipes for Cody

internal/gitserver/gitdomain/common.go
=> cleanup: Remove unused function

migrations/frontend/1691043630_event_logs_indexing/metadata.yaml
=> backport: stitch migration change

cmd/repo-updater/shared/main.go, internal/repos/store.go, internal/repos/syncer.go, internal/repos/syncer_test.go
Cloud is now a different thing. It's confusing and took me 1min to rename.
- Existing
=> nitpick rename: rename IsCloud to IsDotCom

client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutoCompleteManager.java
Leftover from https://github.com/sourcegraph/sourcegraph/pull/55638
n/a
=> JetBrains: delete unused method

doc/dev/background-information/languages/testing_go_code.md
Update docs for mocking stores.
Documentation update.
=> [dbmocks] Minor docs update

.aspect/cli/config.yaml
Fixes #55731 
Env var added in https://github.com/sourcegraph/infrastructure/pull/5318
See https://buildkite.com/organizations/sourcegraph/analytics/suites/sourcegraph-bazel/runs/4b8a9e1a-8955-4871-94f5-6fefe999829e
=> Update buildkite aspect cli to latest version (which include BKA integration)

dev/sg/sg_ci.go
Fixes https://github.com/sourcegraph/devx-support/issues/154
The problem is that we never refresh the `build`. This PR does exactly this, it refreshes the build. 
Locally Tested + CI
=> sg: fix devx-support#154

.aspect/cli/config.yaml
Bump aspect-cli plugin for Buildkite to latest release. 
Tested over a test branch
=> ci: bump aspect-cli plugin for BK

dev/sg/sg_ci.go, doc/dev/background-information/sg/reference.md
we stopped using grafana cloud so removing the flag and code use to build the url
CI
=> sg: we don't use grafana cloud anymore

internal/search/backend/aggregate.go
We don't ever read these fields, so lets just avoid the work of aggregating them. It is likely we will remove them from the proto files.
These fields exist for the zoekt-webserver UI to generate URLs.
Test Plan: CI
=> search: remove aggregation of unread RepoURLs and LineFragments

doc/dev/background-information/languages/testing_go_code.md
=> fix broken go-cmp link

client/jetbrains/CHANGELOG.md, client/jetbrains/build.gradle.kts, client/jetbrains/gradle.properties, client/jetbrains/scripts/release.sh, client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.java
=> JetBrains: release 3.0.10-alpha

docker-images/cadvisor/BUILD.bazel
Just noticed this while browsing. Not sure if there are any followups that are needed.
N/A
=> Bazel: fix typo

cmd/frontend/graphqlbackend/repositories.go, internal/search/streaming/client/BUILD.bazel, internal/search/streaming/client/progress.go
Thanks to #55687 I learned about the `pointers` package. So here you go.
- N/A
=> chore: remove some more pointers

doc/dev/background-information/testing_principles.md
=> doc: add a small section about buildkite test analytics

cmd/frontend/graphqlbackend/cody_context.go, cmd/frontend/graphqlbackend/external_services_test.go, cmd/frontend/graphqlbackend/graphqlbackend_test.go, cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go, cmd/frontend/graphqlbackend/teams_test.go, internal/database/migration/cliutil/run_oobmigrations.go, internal/database/migration/cliutil/util.go, internal/database/migration/shared/data/cmd/generator/main.go, internal/database/perms_store_test.go, internal/database/repo_paths.go, internal/database/users_test.go
I noticed my linter complaining about a bunch of unused fields and methods, and also about unkeyed fields in struct.
Here's a PR to fix it.
* Confirm Sourcegraph works as normal
* Confirm unit tests are passing
=> code cleanup

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
=> JetBrains: release 3.0.10-alpha.3

.github/workflows/pull-request.yml
Updating template for docsite PRs
Tested manually.
=> [docsite] Update PR update template

enterprise/dev/ci/internal/ci/wolfi_operations.go, enterprise/dev/ci/scripts/wolfi/build-base-image.sh, enterprise/dev/ci/scripts/wolfi/build-package.sh, enterprise/dev/ci/scripts/wolfi/upload-package.sh, wolfi-packages/jaeger.yaml, wolfi-packages/jaegertemp.yaml
This is blocking buildkite on main.
This reverts commit 8e982b04bb7ff2574c3c681399c93cdc7d370c96.
Blocking CI, reverting to known good state. I will ensure CI run is green.
=> Revert "Additional Wolfi CI tweaks (#55929)"

client/jetbrains/src/main/java/com/sourcegraph/cody/CodyAgentFocusListener.java, client/jetbrains/src/main/java/com/sourcegraph/cody/CodyFileEditorListener.java
Adds agent connection checks to the File Open and Focus handlers.
- ./gradlew  -PenableAgent=true -PforceAgentBuild=true :runIde
- Ensure autocomplete works
=> JetBrains: add additional checks to ensure agent is connected before communicating

client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.java
Previously, the JB plugin skipped logging events if the agent process hadn't started yet. This commit fixes the problem by awaiting on the server connection before processing logs.
Co-Author: chwarwick <christopher.warwick@sourcegraph.com>
n/a
=> JetBrains: await on agent server before sending telemetry

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
=> JetBrains: release 3.1.0-alpha.1

schema/schema.go, schema/site.schema.json
Update typo in the site config. 
Tested locally. Only typo change.
=> Update typo in site config

client/jetbrains/build.gradle.kts
=> JetBrains: format build.gradle.kts with spotless

schema/schema.go, schema/site.schema.json
Making the description for FileFilters a bit better.
N/A
=> Improve description for fileFilters

client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.java
=> JetBrains: catch exception - fix #56032

WORKSPACE
Does this fix the build? https://buildkite.com/sourcegraph/sourcegraph/builds/239640#018a1cdb-c03c-4ed1-a99c-5c1bcb8d59e1
- Started `main-dry-run` build: https://buildkite.com/sourcegraph/sourcegraph/builds/239679
=> bazel: fix `patch_args`

dev/release/templates/patch_release_issue_template.md
Small formatting fix
None, markdown fix
=> release tool: fix formatting of patch release tracking issue template

wolfi-images/cloud-mi2.yaml
eventually replace https://github.com/sourcegraph/controller/blob/main/cmd/mi2/Dockerfile
CI
=> wolfi-images: add mi2 base image

.aspect/cli/config.yaml
=> ci: bump aspect-cli buildkite plugin

doc/cody/faq.md
* Check for typos
* are `<kbd>` elements ok?
[Preview Link](https://docs.sourcegraph.com/@jdorfman-cloud-ide-faq)
=> Add Cloud IDE entry to FAQs

client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
Fixes https://github.com/sourcegraph/sourcegraph/issues/55512
Try to reproduce the problem on Windows.
I'm blocked on testing it by https://github.com/sourcegraph/sourcegraph/issues/55916
=> JetBrains: Detect line separator

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
=> JetBrains: release 3.1.0-alpha.2

doc/cody/quickstart.md
This PR ships small improvements to Cody Quickstart tutorial.
Docs added
[Preview Link](https://docs.sourcegraph.com/@tweaks-cody-qs)
=> Add small tweaks to Cody Quickstart tutorial

doc/cody/explanations/code_graph_context.md, doc/cody/overview/enable-cody-enterprise.md
Add a note to the Azure OpenAI section that recommends not using it in a production setting. 
Docs change only. Tested locally. 
[Preview Link](https://docs.sourcegraph.com/@rpp/add-aoi-note)
=> Add AOI note about experimental

client/jetbrains/src/main/java/com/sourcegraph/cody/CodyAgentProjectListener.java
This should fix an exception that some users were seeing.
n/a
=> JetBrains: don't start/stop agent for disposed projects

client/jetbrains/gradle.properties
I will update the changelog for the next alpha release.
n/a
=> JetBrains: release 3.1.0-alpha.3

dev/release/templates/patch_release_issue_template.md
This PR updates the link for checking backported PRs to also include manual backports.
Template update.
=> release: check for auto and manually backported PRs during release

enterprise/cmd/frontend/internal/dotcom/productsubscription/codygateway_graphql_test.go, enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql.go, enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql_test.go, enterprise/cmd/frontend/internal/dotcom/productsubscription/tokens_graphql.go
Fix regression introduced in https://github.com/sourcegraph/sourcegraph/pull/56142
Context: https://sourcegraph.slack.com/archives/CMBA8F926/p1692894504864389
=> license: fix missing assignments of loggers

cmd/gitserver/server/cleanup.go
Little cleanup, reduces deduplicated code and makes the cleanup code a bit lighter.
Tests are still passing, and code review.
=> gitserver: Extract logic to list all repos on disk

dev/release/release-config.jsonc
=> Release 5.1.7 progress

cmd/pings/shared/main.go
Follow up of https://github.com/sourcegraph/sourcegraph/pull/56149#discussion_r1303889369. 
CI
=> pings: do not fail entire health check if HubSpot is not working

dev/release/release-config.jsonc
Update `release-config.jsonc` with changes from release process as outlined in release steps
N/A
=> release: update changes post release

CHANGELOG.md
Update `CHANGELOG.md` with release notes for 5.1.7
N/A
=> release: update CHANGELOG.md with release notes

internal/src-cli/consts.go
=> release: update src-cli version

client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
See https://github.com/sourcegraph/sourcegraph/pull/56240
=> JetBrains: Cody: Disabling autocomplete in readonly files

deps.bzl, enterprise/dev/ci/internal/ci/operations.go
Fix an issue with an edge case handling jetbrains only PR which turned out to be problematic when changes in the PRs aren't detected by the changes.Diff. 
ci
=> ci: fix pipeline

enterprise/cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go, enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql.go
=> productsubscription: add accessed entity to audit logs

doc/admin/licensing/index.md
Quick update to license key docs
No test plan required
=> Clarify license key information

doc/cody/troubleshooting.md
Adds a docs section for https://github.com/sourcegraph/cody/pull/851 to link to.
- Previewed locally
[Preview Link](https://docs.sourcegraph.com/@tl/add-cody-rate-limit)
=> Add info about Cody Autocomplete Rate Limits

client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx, cmd/cody-gateway/shared/config.go, internal/completions/httpapi/codecompletion.go
New day, new model 😎 
- Only adding a new code completion model string
=> Add Llama Code 7b model

dev/update-embeddings-list/src/index.ts
Removes token, uses env var.
N/A
=> Use env var for token

schema/schema.go
=> Regenerate schema.go

enterprise/cmd/frontend/internal/auth/githuboauth/session.go, enterprise/cmd/frontend/internal/auth/gitlaboauth/BUILD.bazel, enterprise/cmd/frontend/internal/auth/gitlaboauth/login.go, enterprise/cmd/frontend/internal/auth/gitlaboauth/session.go, enterprise/cmd/frontend/internal/auth/gitlaboauth/session_test.go, enterprise/cmd/frontend/internal/auth/gitlaboauth/user.go, internal/authz/providers/gitlab/common_test.go, internal/authz/providers/gitlab/sudo.go, internal/authz/providers/gitlab/sudo_test.go, internal/extsvc/gitlab/mock.go, internal/extsvc/gitlab/user.go, internal/extsvc/gitlab/users.go, schema/schema.go, schema/site.schema.json
This PR will disallow accounts signing up/in through GitLab or GitHub, that are newer than 14 days.
Tested changes locally with both GitHub and GitLab accounts.
=> auth: Check provider account creation date

enterprise/cmd/frontend/internal/auth/githuboauth/session.go, enterprise/cmd/frontend/internal/auth/gitlaboauth/session.go, schema/schema.go, schema/site.schema.json
Address comments from https://github.com/sourcegraph/sourcegraph/pull/56330. 
Tested locally, unit tests.
=> Fix up external creation date changes

internal/actor/http.go, internal/completions/client/client.go
=> actor: ID bugfix

internal/actor/http.go, internal/completions/client/client.go, internal/completions/client/codygateway/BUILD.bazel, internal/completions/client/codygateway/codygateway.go
Alternate take on https://github.com/sourcegraph/sourcegraph/pull/56352
CI passes
=> actor: alternative fix (revert #56352)

cmd/frontend/graphqlbackend/user.go, cmd/frontend/graphqlbackend/user_test.go
=> graphqlbackend: replicate validation to backend for post signup flow

doc/cody/overview/app/index.md
This PR ships major improvements to our Cody for desktop app docs, such as:
- Improved content templating and format
- New CTA design banners for installation link
- Improved docs page hierarchy
- Cards for "more resources" elements
Docs added
[Preview Link](https://docs.sourcegraph.com/@imp-cody-app)
=> Improve and update Cody desktop app setup guide

doc/cody/capabilities.md
This PR adds 3 demo GIFs to the Cody capabilities page:
- Context-based chat
- Hotkey commands
- Custom commands
Docs added.
[Preview Link](https://docs.sourcegraph.com/@cody-docs-capability-gifs)
=> Add 3 GIFs to Cody capabilities

CHANGELOG.md
=> changelog catchup

doc/batch_changes/how-tos/configuring_credentials.md
Clarified where "Add credentials" settings are located. Updated step 3 for clarity to reflect admin screen
=> Update add Global service account token instructions

dev/release/release-config.jsonc
=> close 5.1.8 release

CHANGELOG.md
=> add changelog section for 5.1.9

enterprise/cmd/worker/internal/search/exhaustive_search_test.go
Follow-up from this [PR comment](https://github.com/sourcegraph/sourcegraph/pull/56361#discussion_r1315999183)
- removing redundant checks in test
=> search job: remove redundant db checks in test

internal/search/exhaustive/store/exhaustive_search_jobs.go
Read through the code and realised that this doesn't use the [`basestore` helpers for
scanning](https://docs.sourcegraph.com/dev/background-information/basestore#using-basestore-helpers-for-scanning) so thought I'd drop by with a PR.
Also noticed that `ListSearchJobs` and `GetSearchJob` don't have tests -- I assume they're indirectly tested somewhere?
=> exhaustive search store: refactor scanning

doc/admin/observability/health_checks.md
=> Update health checks docs to include instance version in response

cmd/frontend/graphqlbackend/external_accounts.go
Adds a feature flag logic to disallow unlink external accounts.
=> feature-flag: support disallow unlink external accounts

.github/test.CODEOWNERS, client/web/src/enterprise/batches/CODENOTIFY, client/web/src/integration/CODENOTIFY, cmd/frontend/graphqlbackend/CODENOTIFY, doc/batch_changes/CODENOTIFY
=> Remove self from CODENOTIFY/OWNERS

enterprise/dev/ci/scripts/wolfi/build-base-image.sh
regression from https://github.com/sourcegraph/sourcegraph/pull/56439
after upgrading `apko`, image tag is now suffixed by arch
`sourcegraph-wolfi/cloud-mi2-base:latest` -> `sourcegraph-wolfi/cloud-mi2-base:latest-amd64`
https://buildkite.com/sourcegraph/sourcegraph/builds/241285#018a7208-d305-40ab-800e-8b25d036eb8d/30-364
```
* Loading built image into docker daemon...
  | 39dad30aed31: Loading layer  128.8MB/128.8MB
  | The image sourcegraph-wolfi/cloud-mi2-base:latest-amd64 already exists, renaming the old one with ID sha256:a4cfdd8636d67eb0fedd190880bbc58586e87f540dd4ff65a6ad73b1023f2524 to empty string
  | Loaded image: sourcegraph-wolfi/cloud-mi2-base:latest-amd64
  | * Pushing image to internal dev repo...
  | Error response from daemon: No such image: …
```
=> ci/wolfi: fix building base image

wolfi-images/cloud-mi2.yaml, wolfi-packages/gke-gcloud-auth-plugin.yaml, wolfi-packages/terraform.yaml
tested in Cloud control plane dev environment.
everything worked as expected
=> wolfi-images: update mi2 base image

enterprise/dev/ci/scripts/wolfi/build-base-image.sh
(cherry picked from commit 9f977fd637221b019d8185bfb6337a9266a20953)
CI
=> [Backport 5.1] ci/wolfi: fix building base image (#56448)

internal/extsvc/github/v4_test.go
Removes an unnecessary test case. Less confusing code == good.
Removes an unnecessary test case.
=> Remove unnecessary test for GET request in GH V4 client

client/jetbrains/gradle.properties
I will update the changelog before promoting a release to stable. For now, the list of recently merged PRs can be used as a changelog https://github.com/sourcegraph/sourcegraph/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+JetBrains%3A+is%3Aclosed
n/a
=> JetBrains: release 3.1.0-alpha.4

client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
=> JetBrains: Fix formatting

.vscode/cody.json
VSCode kept flashing a warning that this config needs to be migrated, this is the result of clicking that button.
Code review.
=> cody: Apply config fix

wolfi-images/batcheshelper.yaml, wolfi-images/blobstore.yaml, wolfi-images/bundled-executor.yaml, wolfi-images/cadvisor.yaml, wolfi-images/cloud-mi2.yaml, wolfi-images/executor-kubernetes.yaml, wolfi-images/executor.yaml, wolfi-images/gitserver.yaml, wolfi-images/jaeger-agent.yaml, wolfi-images/jaeger-all-in-one.yaml, wolfi-images/node-exporter.yaml, wolfi-images/opentelemetry-collector.yaml, wolfi-images/postgres-exporter.yaml, wolfi-images/postgresql-12-codeinsights.yaml, wolfi-images/postgresql-12.yaml, wolfi-images/prometheus-gcp.yaml, wolfi-images/prometheus.yaml, wolfi-images/qdrant.yaml, wolfi-images/redis-exporter.yaml, wolfi-images/redis.yaml, wolfi-images/repo-updater.yaml, wolfi-images/search-indexer.yaml, wolfi-images/searcher.yaml, wolfi-images/server.yaml, wolfi-images/sourcegraph-base.yaml, wolfi-images/sourcegraph-dev.yaml, wolfi-images/sourcegraph.yaml, wolfi-images/symbols.yaml, wolfi-images/syntax-highlighter.yaml, wolfi-packages/jaeger.yaml
Updating wolfi images
Manually test
=> updating wolfi images for realease 5.1.9

CHANGELOG.md
=> more changelog cleanup

client/web/src/get-cody/GetCodyPage.tsx
Would be even better to mention other JetBrains products.
Just a string change
=> Fix capitalization

client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/AccountSettingChangeListener.kt
Follow-up on #56579
- agent should get updated when account settings change
=> JetBrains: Cody: Hotfix: notify agent of configuration change on account settings change

client/web/package.json, pnpm-lock.yaml
In reference to:
- https://github.com/sourcegraph/cody/pull/1034
- https://github.com/sourcegraph/cody/pull/1043
- https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1694529000641279
- follow the test plan from the mentioned PRs.
=> Bump up cody-shared package version

dev/sg/sg_setup.go, doc/dev/background-information/sg/index.md, doc/dev/background-information/sg/reference.md
Document stuff from `sg setup` + fix a flag name. 
CI 
[Preview Link](https://docs.sourcegraph.com/@jh/doc-sg-setup-pre-commit)
=> doc: sg setup and pre-commit

client/jetbrains/gradle.properties
=> JetBrains: release 3.1.0-alpha.7

dev/oci_deps.bzl
=> updating hash for wolfi

client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
This PR updates the handler for autocomplete requests:
- Removes 20ms delay. This delay is already handled by the agent
- Refactors code to use only `if` statements with early returns
- Uses clearer `isTriggeredImplicitly` variable over `!isTriggeredManually`
This fixes some weird behaviors I was experiencing. For example, press backspace and confirm that we're sending autocomplete requests.
=> JetBrains: refine autocomplete trigger

CHANGELOG.md, doc/admin/repo/perforce.md, internal/authz/providers/perforce/BUILD.bazel, internal/authz/providers/perforce/authz.go, internal/authz/providers/perforce/cmd/scanprotects/main.go, internal/authz/providers/perforce/cmd/scanprotects/main_test.go, internal/authz/providers/perforce/perforce.go, internal/authz/providers/perforce/perforce_test.go, internal/authz/providers/perforce/protects.go, internal/authz/providers/perforce/protects_test.go, schema/perforce.schema.json, schema/schema.go
@sourcegraph/release-guild
Follow test plan from original PR #56450
=> Backport 56450 to 5.1

deps.bzl, go.mod, go.sum
Updates zoekt to https://github.com/sourcegraph/zoekt@2d1affd44cb72c6d4ee58c605f947f105c9150a5
CI
=> update zoekt to include fix from https://github.com/sourcegraph/zoekt@2d1affd44cb72c6d4ee58c605f947f105c9150a5

cmd/frontend/internal/search/resolvers/search_job.go, cmd/frontend/internal/search/resolvers/search_job_stats.go
This is fake and doesn't return actual data, but it unblocks Vova.
- N/A
=> search jobs: implement fake search job stats resolver

doc/cloud/private_connectivity_gcp.md
docs only
https://docs.sourcegraph.com/@michaellzc-patch-3/cloud/private_connectivity_gcp
=> docs: add cloud psc security faq

cmd/cody-gateway/CODENOTIFY, cmd/pings/CODENOTIFY, dev/managedservicesplatform/CODENOTIFY, dev/sg/msp/CODENOTIFY, internal/updatecheck/CODENOTIFY
=> chore: update CODENOTIFY for Joe

.vscode/cody.json, doc/cody/overview/cody-with-sourcegraph.md, doc/cody/overview/install-jetbrains.md
This PR ships major improvements to our Cody for Sourcegraph.com docs, such as:
- Improved content templating and format
- New CTA design banners for installation link
- Improved docs page hierarchy
- Cards for "more resources" elements
Docs added
[Preview Link](https://docs.sourcegraph.com/@imp-cody-sg)
=> Improve and update Cody with Sourcegraph.comn setup guide

cmd/cody-gateway/shared/config.go, dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go, sg.config.yaml
Based on feedback - makes it easier to reason with.
n/a
=> managedservicesplatform: remove service prefix from DIAGNOSTICS_SECRET

cmd/pings/shared/config.go, cmd/pings/shared/main.go, sg.config.yaml
Small things identified while trying using `sg msp` to deploy the service through Cloud Run.
Manually tested to have a service up and running in a test project.
=> pings: make it work with Cloud Run and `sg msp`

dev/managedservicesplatform/internal/stack/cloudrun/adapters.go
It's not optional in CDKTF
Manual edit by @unknwon
=> managedservicesplatform: add secret version explicitly

dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
🤦 
Manual edit by @unknwon (thanks!)
=> managedservicesplatform: fix diagnostics auth header

dev/managedservicesplatform/internal/stack/cloudrun/BUILD.bazel, dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
See docstrings, we have this for Cody Gateway as well.
Pings service :D
=> managedservicesplatform: add allUsers run.invoker

dev/managedservicesplatform/terraformcloud/terraformcloud.go, dev/sg/msp/sg_msp.go
=> managedservicesplatform: fix project deletion

cmd/frontend/internal/search/httpapi/export.go, cmd/frontend/internal/search/init.go, enterprise/cmd/worker/internal/search/exhaustive_search_test.go, internal/search/exhaustive/service/BUILD.bazel, internal/search/exhaustive/service/service.go, internal/search/exhaustive/service/service_test.go, internal/search/exhaustive/uploadstore/store.go
Relates to #56393 
This connects the http handler, that serves the csv, to the store that holds the csv blobs. Previously this endpoint just returned a mock csv.
=> search jobs: connect download handler to upload store

dev/sg/msp/sg_msp.go
```
sg msp tfc sync --delete services/pings/service.yaml
```
=> sg/msp: fixup workspace deletion

deps.bzl, go.mod, go.sum
https://github.com/sourcegraph/zoekt/pull/649
CI
=> zoekt: update to 19f03eed7c1047fa2949c66869eafec65bad1578

.github/workflows/label-notify.yml
=> label-notify: add eric and geoffrey for Cody Gateway

cmd/frontend/internal/search/resolvers/resolver.go, enterprise/cmd/worker/internal/search/BUILD.bazel, enterprise/cmd/worker/internal/search/exhaustive_search_test.go, internal/search/exhaustive/service/service.go, internal/search/exhaustive/store/exhaustive_search_jobs.go, internal/search/exhaustive/store/store.go
We first delete from the upload store and then from the db. This gives the user the opportunity to retry.
Test Plan:
=> search jobs: implement DeleteSearchJob resolver

internal/search/repos/repos.go
We want this behaviour for search jobs so we can only query the DB and
at a later stage query gitserver (which is slower). This also helps
break up that monster function a bit. This commit should not change any
behaviour.
Additionally we add some doc strings to explain behaviour.
=> search: split up repos resolver into DB part and gitserver part

cmd/pings/README.md, sg.config.yaml
=> pings: add README for local dev

doc/admin/deploy/docker-compose/index.md
Previewed locally
[Preview Link](https://docs.sourcegraph.com/@noah-berman/fix-docker-compose-install-anchor-1)
=> Fix anchor reference

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
=> JetBrains: release 3.1.0-alpha.10

cmd/frontend/internal/search/resolvers/resolver.go
=> search jobs: return EmptyResponse

cmd/frontend/graphqlbackend/search_jobs.graphql
Relates to [this comment](https://github.com/sourcegraph/sourcegraph/pull/56640#issuecomment-1723911957)
It seems that our connection resolver supports bidirectional paging out of the box. There should be no functinal change.
Test plan:
CI
=> search jobs: bidirectional pageInfo

doc/dev/how-to/wolfi/add_update_images.md, doc/dev/how-to/wolfi/add_update_packages.md
Update wolfi image update docs based on some questions raised about the process.
- Docs - checked locally
[Preview Link](https://docs.sourcegraph.com/@will/wolfi-package-docs-update)
=> Improve docs for updating images based on questions

cmd/frontend/hubspot/events.go, cmd/frontend/hubspot/hubspot.go, cmd/frontend/hubspot/hubspotutil/hubspotutil.go, cmd/pings/shared/main.go
=> pings: pass down request context to Ping methods

client/web/package.json, pnpm-lock.yaml
Bumps `cody-shared` version including
- https://github.com/sourcegraph/cody/pull/1107
CI passes
=> bump cody-shared package version

CHANGELOG.md
Closes https://github.com/sourcegraph/sourcegraph/issues/56763
Relates to https://github.com/sourcegraph/zoekt/pull/646
Test plan:
N/A
=> changelog: Zoekt deletes temp dir

internal/codeintel/autoindexing/internal/inference/lang_python_test.go, internal/codeintel/autoindexing/internal/inference/lua/python.lua, internal/codeintel/autoindexing/internal/inference/testdata/python_multiple_config_files_at_root.yaml, internal/codeintel/autoindexing/internal/inference/testdata/python_multiple_roots.yaml, internal/codeintel/autoindexing/internal/inference/testdata/python_package_with_pyproject.yaml, internal/codeintel/autoindexing/internal/inference/testdata/python_pyproject.yaml, internal/codeintel/autoindexing/internal/inference/testdata/python_requirements.txt.yaml, internal/codeintel/autoindexing/internal/inference/testdata/python_setup.py.yaml
Fixes https://github.com/sourcegraph/sourcegraph/issues/56336 with an out-of-the-box solution
Added snapshot tests
=> codeintel: Better auto-indexing for Python

wolfi-packages/p4-fusion.yaml
run `sg wolfi package p4-fusion`
=> update p4-fusion version to 1.13

CHANGELOG.md
=> add CHANGELOG.md entry for grpc

cmd/frontend/internal/search/CODENOTIFY, internal/search/CODENOTIFY
I am no longer working primarily on search backend work, and the notifications are getting a bit overwhelming. As always, feel free to ping me directly for a review
N/A
=> remove Camden from search codenotify

dev/release/release-config.jsonc
Part of https://github.com/sourcegraph/sourcegraph/issues/56794
n/a
=> release: activate 5.1.9 release process

dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go, dev/managedservicesplatform/spec/service.go
https://github.com/sourcegraph/managed-services/pull/7
=> managedservicesplatform: support http/2 services

CHANGELOG.md
Add CHANGELOG entry for #56697
CHANGELOG
=> Update CHANGELOG.md for PR 56697

client/web/src/enterprise/search-jobs/SearchJobModal/SearchJobModal.module.scss, client/web/src/enterprise/search-jobs/SearchJobModal/SearchJobModal.tsx, client/web/src/enterprise/search-jobs/SearchJobsPage.story.tsx, client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
Just simply fixes local cache logic for search jobs mutations
- Test that right after you delete search jobs you can't see it in the list UI
=> Search Jobs: Fix client cache updates for search jobs mutations

client/jetbrains/CHANGELOG.md, client/jetbrains/gradle.properties
I've cut the release but it can take a few hours until the version is available on the marketplace https://plugins.jetbrains.com/plugin/9682-sourcegraph-cody--code-search/versions
n/a
=> JetBrains: release 3.1.0 (stable)

.github/workflows/scip-go.yml, .github/workflows/scip-typescript.yml
This instance no longer exists.
Test Plan: CI
=> ci: remove scip actions for codyintel.sourcegraphcloud.com

cmd/cody-gateway/internal/httpapi/completions/upstream.go
This change tracks Sourcegraph actors in events. Nothing sensitive in here, but we do have to be a bit wary of how we use this data (actor identifiers are specific to the corresponding Sourcegraph instance, so it must always be used in conjunction with the actor source).
n/a
=> cody-gateway: track Sourcegraph actors in completion events

CHANGELOG.md
Part of https://github.com/sourcegraph/sourcegraph/issues/56794
n/a
=> release: cut changelog for 5.1.9

client/web/src/components/DownloadFileButton.tsx, client/web/src/components/LoaderButton.module.scss, client/web/src/components/LoaderButton.tsx, client/web/src/enterprise/search-jobs/SearchJobsPage.module.scss, client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
Small PR with quick paper cuts and download file fixes.
- Check that the file name of the downloaded file is set by content deposition filename value if the header is presented in the response headers
- Check that the search job page has a proper title value
=> [Search Jobs]: Fix download button logic and layout

cmd/cody-gateway/shared/metrics.go, cmd/telemetry-gateway/shared/config.go, cmd/telemetry-gateway/shared/main.go, cmd/telemetry-gateway/shared/metrics.go
=> telemetry-gateway: minor naming fixups

.github/ISSUE_TEMPLATE/security-release-approval.md
@shivasurya you won't escape so easily
=> Add Shiva to security issue template

doc/cloud/private_connectivity_aws.md, doc/cloud/private_connectivity_gcp.md
=> docs: update cloud private code hosts docs

dev/sg/msp/repo/root.go
=> use proper error lib
