- client/cody-shared/src/chat/recipes/non-stop.ts
- client/cody-shared/src/editor/index.ts
- client/cody/BUILD.bazel
- client/cody/package.json
- client/cody/src/chat/ChatViewProvider.ts
- client/cody/src/editor/vscode-editor.ts
- client/cody/src/extension.ts
- client/cody/src/main.ts
- client/cody/src/non-stop/FixupCodeLenses.ts
- client/cody/src/non-stop/FixupController.ts
- client/cody/src/non-stop/FixupTask.ts
- client/cody/src/non-stop/FixupTypingUI.ts
- client/cody/src/non-stop/TaskViewProvider.ts
- client/cody/src/non-stop/codelenses.ts
- client/cody/src/non-stop/diff.ts
- client/cody/src/non-stop/roles.ts
- client/cody/src/non-stop/utils.ts
- client/cody/src/test-support.ts
- client/cody/test/e2e/fixup-decorator.test.ts
- client/cody/test/e2e/task-controller.test.ts
- client/cody/test/integration/task-controller.test.ts
This does not *automatically* re-spin tasks, but the respin mechanism is working.
```
pnpm test:unit && pnpm test:integration && pnpm test:e2e
```
Manual test:
1. Create and save a file. Write a bunch of code in it.
2. Ask Cody to do something time consuming in chat, like list US states and their capitals.
3. While chat is busy, Cmd-Shift-P, Fixup (Experimental) and ask Cody to fix something. Note that the fixup task is paused while chat is busy, and gets picked up automatically when chat is not busy.
4. Edit in a blue rectangle to create a conflict with what Cody wants to write. Click Apply. Note that the task re-spins and Cody redoes its work including your changes.
5. Edit "in the zone" but outside blue rectangles so there's no conflict. Apply the change. Note that all the changes are …
> Cody: Re-spin tasks which have conflicts with local edits

- client/web/src/repo/blob/own/FileOwnershipEntry.tsx
Test plan:
Local sg run and visual check.
Closes https://github.com/sourcegraph/sourcegraph/issues/53456
> own: sort ownership reason badges.

- client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.tsx
- client/web/src/featureFlags/featureFlags.ts
- client/web/src/repo/blob/own/FileOwnershipPanel.tsx
- client/web/src/repo/blob/own/TreeOwnershipPanel.tsx
- client/web/src/repo/tree/TreePageContent.tsx
- client/web/src/site-admin/SiteAdminArea.tsx
- client/web/src/site-admin/SiteAdminSidebar.tsx
- client/web/src/site-admin/sidebaritems.ts
Test plan:
Local sg run and tests that Own views ˆstill show up.
Part of https://github.com/sourcegraph/sourcegraph/issues/53160
> own: remove redundant feature flags.

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessageContentCreatorFromMarkdownNodes.java
- Line breaks should be preserved in the chat messages
- Prompt input should be emptied after we click Send button
> JetBrains: fix line breaks in the chat and reset prompt input

- enterprise/internal/own/codeowners/file.go
- enterprise/internal/own/search/filter_job_test.go
- enterprise/internal/own/search/select_job.go
- enterprise/internal/own/search/select_job_test.go
- enterprise/internal/own/service.go
- enterprise/internal/own/service_test.go
Addresses: https://github.com/sourcegraph/sourcegraph/issues/52719
After change the search result is properly categorized as a team:
Manual, updated unit tests
> Fix visual bug that would not display Teams properly in search results

- client/web/src/repo/blob/own/grapqlQueries.ts
- enterprise/cmd/frontend/internal/own/resolvers/resolvers.go
- sg.config.yaml
Fixes the own API to filter on assigned owners.
History and ownership panel loads with the correct information still, and the API filters down.
> fix API to filter on assigned owner reason

- client/cody/src/completions/context-embeddings.ts
While playing around on other things, I noticed that embeddings are logged even when the repo has no embeddings:
As it turns out, in this case we automatically fall back to keyword search which I don't think are any better then the local context we have anyways so I suggest we bail out of it. We also call the event `embeddings` so we should only fire it when there are embeddings that are being used.
> Cody completions: Require an embeddings connection when using embeddings context

- internal/grpc/defaults/defaults.go
- internal/grpc/internalerrs/common.go
- internal/grpc/internalerrs/common_test.go
- internal/grpc/internalerrs/logging.go
This PR expands upon #52208 to also add _Server_-side interceptors that check for "internal" gRPC errors (which includes the [non utf-8 string issue](https://github.com/sourcegraph/sourcegraph/issues/52181)). 
After deploying #52208 to sourcegraph.com, I saw many [grpc error logs](https://cloudlogging.app.goo.gl/zykd4dbAFaMeHdHs8) that look like:
```jsonc
{
"jsonPayload": {
"InstrumentationScope": "gitserver.client.gRPC.internal.error.reporter",
"Body": "grpc: error while marshaling: string field contains invalid UTF-8",
"Attributes": {
"nonUTF8StringFields": [],
"grpcService": "gitserver.v1.GitserverService",
"messageJSON": "{\"Message\":null}", // ❗
"grpcMethod": "Search",
"grpcCode": "Internal"
},
"Resource": {
"service.name": "worker"
}
},
}
```
After a while, I realized that the …
> grpc: add server interceptors to catch "internal" utf-8 errors for streaming methods

- enterprise/internal/own/search/BUILD.bazel
- enterprise/internal/own/search/filter_job.go
- enterprise/internal/own/search/filter_job_test.go
- internal/search/job/jobutil/job.go
- internal/search/result/commit.go
Part of #53537
This change adds support for ownership filtering for commit results. And it was a request from a major customer.
- We include `ModifiedFiles` in `CommitMatch` for own (alongside sub-repo permissions case) see [#ask-iam](https://sourcegraph.slack.com/archives/C04ML7GFK5Y/p1686827762022219).
- We modify filter job to consider `[]string` for file paths rather than single string.
- This slice is a singleton for `FileMatch`.
- For `CommitMatch` in contains all `ModifiedFiles`. Here the filter will discard the `CommitMatch` if:
- Any of the files' owners match all excluded owners (if excluded owners are preset)
- None of the files' owners match all included owners (if included owners are present)
https://www.loom.com/share/591f13945b854c349c31e61a8096a6d8?sid=a71be5c4-b022-43d1-b3 …
> Support ownership search in diffs

- client/web/src/repo/commits/GitCommitNodeTableRow.tsx
Spotted the bug while testing in dogfood.
Tested manually.
And see:
https://github.com/sourcegraph/sourcegraph/assets/2682729/3fa4aaf9-f7cc-41e8-af90-ac4d214acddf
> ui: Use experimental flag for changelist or commit URL

- cmd/frontend/internal/cli/autoupgrade.go
- internal/version/upgradestore/store.go
In certain concurrent situations, it's possible for some frontends to block indefinitely if theyre trying to autoupgrade when it has already occurred and dependent services are already up and connected
Tested locally by first bringing up everything in docker-compose besides sourcegraph-frontend-0, and then bringing it up once everything is reasy
> mvu: check for upgrade completion during disconnect block checking

- src-tauri/src/tray.rs
- src-tauri/tauri.conf.json
Rename to Cody in:
- Application name when running (top left menu name)
- Title bar of the window
- In the system tray menu, "Open Sourcegraph" becomes "Open Cody"
Part of:
- #53120
The other part of the rename is the filenames of the releases. That's handled in a separate PR because it touches the build scripts:
- #53552 
- Check all updated places in App
> App: Rename to Cody

- internal/gitserver/observability.go
- internal/observation/observation.go
Fixes: https://github.com/sourcegraph/sourcegraph/issues/53455
Followup to https://github.com/sourcegraph/sourcegraph/pull/53565, @Strum355 made the great suggestion to use ErrorFilters directly.
This changes the gitserver client behavior, it will now **no longer log errors** as part of the end of observation.
Manual
> Filter out error logging from Gitserver client observability

- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
We aren't writing the error message here, so the result in the DB is not useful (doesn't actually say the problem). This PR just adds the error message to the error string.
N/A
> write git output with error in CommitLog

- client/web/src/site-admin/SiteAdminUpdatesPage.module.scss
- client/web/src/site-admin/SiteAdminUpdatesPage.tsx
_Second branch opened to address weird git merge snafu_
This PR introduced a copy button for suggested fixes for each individual schema drift logOutput, it also adds styling for dark mode users
Introduced drift to my local db `sg start`
> drift copy to clipboard - dark mode styling2

- internal/database/gitserver_repos.go
- internal/database/gitserver_repos_test.go
Not sure why I was using `dbutil.NewNullString` when the column is non-nullable. Too much copy pasta.
Thanks for [the alert](https://github.com/sourcegraph/sourcegraph/pull/51598#issuecomment-1593866227), @camdencheek 
unit tests added
re-clone a repository and verify that the last output shows up in the `Mirroring and cloning` page (click on the kebab menu on the repository and choose `Last sync log`
> don't use `dbutil.NewNullString` when inserting into `gitserver_repos_sync_output`

- doc/cody/completions.md
- doc/cody/explanations/code_graph_context.md
- doc/cody/explanations/cody_gateway.md
- doc/cody/explanations/enabling_cody_enterprise.md
- doc/cody/faq.md
- doc/cody/index.md
Adds customer/user-facing Cody Gateway docs, noting how access works, changing setup to use it as a default, and separating direct third-party LLM configuration into various sections. The docs focus primarily on Sourcegraph Enterprise since the story for that is a lot clearer, but I've included mentions of App to so that this page can be extended to accommodate App, which will talk to Cody Gateway directly.
The changes assume that customers are on 5.1, but given things are experimental and there are already a lot of 5.1-specific things in here I think that's fine?
There are also a few lightweight details about security/privacy here. Note that we do not yet have an SLA commitment for Cody Gateway due to a [lack of SLA from OpenAI](https://github.com/sourcegraph/sourcegraph/issues/52409#issu …
> doc/cody: customer-facing Cody Gateway docs

- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/InlineCompletionItem.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/Position.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/Range.java
- client/jetbrains/src/test/java/InlineCompletionsPostProcessingTest.java
Fixes #53239  (a follow up for #53476)
A rough-cut solution adjusting inline completion to not clash with the editor current line suffix.
- if the completion matches the suffix, the suffix is simply stripped.
- if the completion contains the suffix, its last occurence is cut.
- see: unit tests
- inline completions should not include the line suffix
> JetBrains: cut same line suffix when providing inline completions

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- limit prompt input height to 4 rows, for bigger input scroll appears
- break text by words instead of characters
- use standard label font
closes #53465 
- Height of the input should not grow
- text should break by words
- font should be the same as in the chat messages
> JetBrains: fix UI of the cody prompt input

- client/web/src/site-admin/RepositoryNode.module.scss
- client/web/src/site-admin/RepositoryNode.tsx
- client/web/src/site-admin/backend.ts
Relates to #52983 
We show a badge in site-admin > Repositories if an embedding exists. The badge links to the repo's embeddings jobs.
Visually inspected the change.
> site-admin: add badge for repos with embeddings

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- Closes https://github.com/sourcegraph/sourcegraph/issues/53465
Had to flip two lines because `promptInput.setUI(textUI);` apparently overwrites the font.
It uses the correct font now:
> JetBrains: Chat: Fix font in the prompt

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/CodyCompletionItemProvider.java
https://github.com/sourcegraph/sourcegraph/assets/18601388/b37ef1c0-ab3d-4f4f-95c6-5aed00811551
Autocomplete calls to Sourcegraph API should now be running in parallel.
Additionally, I reduced the debounce down to 20ms.
This should make response times a lot more reasonable.
- just check if I didn't make things slower on your machine for whatever reason
> JetBrains: snappier Cody autocomplete

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java
- client/jetbrains/src/test/java/InlineCompletionsPostProcessingTest.java
Fixes #53595 
Cody was returning completions with zero-width spaces for whatever reason.
I just filter them out.
Included a unit test.
Can double check if the bug is still replicable.
> JetBrains: Fixed: filter out zero-width spaces from inline autocomplete

- client/web/src/repo/blob/BlobPage.tsx
- client/web/src/repo/blob/own/HistoryAndOwnBar.module.scss
- client/web/src/repo/blob/own/HistoryAndOwnBar.story.tsx
- client/web/src/repo/blob/own/HistoryAndOwnBar.tsx
- client/web/src/repo/blob/own/grapqlQueries.ts
Main points:
- History can now live without own
- If own is off, one little GQL `@include(if: $includeOwn)` spares us the whole ownership query, leaving only the request for history
Test plan:
Closes https://github.com/sourcegraph/sourcegraph/issues/53556.
~Merge after https://github.com/sourcegraph/sourcegraph/pull/53558.~
https://github.com/sourcegraph/sourcegraph/assets/94846361/19070721-3253-4e21-945a-15e6695996fe
> own: separate History and Own so that turning off Own is not turning off History as well.

- enterprise/dev/app/create-github-release.sh
- enterprise/dev/app/create-update-manifest.sh
- enterprise/dev/app/tauri-build.sh
Rename to Cody in the build scripts that build the app. This should only affect the file names of the releases.
My editor automatically applied formatting to the shell files, so that's where the minor whitespace changes come from.
This PR only touches the build scripts. The other parts of the rebrand are in:
- #53518.
This is part of:
- #53120 
- Build app
- Verify that it works and that the releases are named "Cody" where they were previously named "Sourcegraph"
> App: Rename to Cody in app build scripts

- enterprise/internal/codeintel/ranking/internal/store/uploads.go
**Before**:
```
QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CTE Scan on candidates  (cost=83057.94..83057.96 rows=1 width=4) (actual time=10343.762..10344.180 rows=100 loops=1)
CTE candidates
->  Limit  (cost=83057.93..83057.94 rows=1 width=117) (actual time=10343.759..10344.145 rows=100 loops=1)
->  LockRows  (cost=83057.93..83057.94 rows=1 width=117) (actual time=10343.759..10344.137 rows=100 loops=1)
->  Sort  (cost=83057.93..83057.93 rows=1 width=117) (actual time=10343.731..10343.793 rows=101 loops=1)
Sort Key: u.id DESC
Sort Method: quicksort  Memory: 154005kB
-> …
```
> ranking: Improve export query performance

- client/web/src/cody/useCodyChat.tsx
- client/web/src/repo/components/TryCodyWidget/TryCodyWidget.tsx
- client/web/src/util/constants.ts
Rename event logs for recipe executed on web. 
- visit any file view page
- select code from the editor
- execute recipe
- check for event log request
> Rename cody recipe executed event logs

- doc/cody/explanations/code_graph_context.md
- doc/cody/explanations/index.md
- doc/cody/explanations/policies.md
- doc/cody/explanations/policy.md
This adds a doc page for embeddings policies to Sourcegraph docs > Cody > Explanations
I ran a local instance and verified that the screenshots are displayed correctly.
> cody: document embeddings policies

- client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.tsx
Test plan:
Closes https://github.com/sourcegraph/sourcegraph/issues/53587.
Closes https://github.com/sourcegraph/sourcegraph/issues/53590.
> own: show percentages of ownership on Own Analytics page.

- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/CodyServicesSection.tsx
With zero-config, the access token will now very rarely be explicitly needed. We retain the section just in case, but move it to the bottom of the Cody Services section so that it's less prominent.
> productsubscriptions: move access token to bottom of page

- cmd/frontend/graphqlbackend/batches.go
- cmd/frontend/graphqlbackend/batches.graphql
- cmd/frontend/graphqlbackend/file.go
- cmd/frontend/graphqlbackend/git_commit_test.go
- cmd/frontend/graphqlbackend/git_tree_entry.go
- cmd/frontend/graphqlbackend/perforce_changelist.go
- cmd/frontend/graphqlbackend/repository.go
- cmd/frontend/graphqlbackend/repository_comparison_test.go
- cmd/frontend/graphqlbackend/schema.graphql
- cmd/frontend/graphqlbackend/virtual_file.go
- enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace_file.go
- enterprise/cmd/frontend/internal/batches/resolvers/batch_spec_workspace_file_test.go
- internal/perforce/changelist.go
Part of #40330.
We want to be able to generate permalinks for files in a perforce depot
- Add the `changelistURL` property to the `File2` interface
- Add the `changelistURL` property to all the types that implement the `File2` interface
- Implement the `ChangelistURL` API and return a changelist URL for the `GitBlob` type
- Return nil for all the other types that implement `File2` (existing behaviour for these types, for example `url` is also not implemented on them)
Following existing conventions. Ideally we should have a top level `urls` node that embeds all the different type of urls instead of having them on the top level definition in the `File2` interface, but that is a major API change that we're not ready for
- Added tests
- Tested with UI code (another PR coming soon)
> graphqlbackend: Add changelistURL to GitBlob

- doc/batch_changes/references/batch_spec_templating.md
- doc/batch_changes/references/batch_spec_yaml_reference.md
Adds a note that `repository.search_result_paths` may be empty in certain circumstances.
N/A just a docs change.
> docs: note when `repository.search_result_paths` will be empty

- client/web/src/repo/blob/own/FileOwnershipEntry.tsx
- client/web/src/repo/blob/own/FileOwnershipPanel.tsx
- client/web/src/repo/blob/own/OwnerList.tsx
- client/web/src/repo/blob/own/TreeOwnershipPanel.tsx
Fixes: https://github.com/sourcegraph/sourcegraph/issues/53162
Ended up just refreshing the page instead of trying to link the OwnersList and HistoryAndOwnBar components, which would be a bit of a mess.
Manual
> Refresh page when making/removing owners

- client/cody/package.json
- client/cody/src/completions/providers/unstable-codegen.ts
This adds context in the expected format for the experimental codegen backend for. 
- Tested locally. The backend API is happy with this.
> Completions: Add context to codegen

- client/cody/CHANGELOG.md
- client/cody/src/completions/completion.test.ts
- client/cody/src/completions/multiline.ts
The title says it all. They're all c-like so the implementation doesn't need to change.
I also noticed that we currently do not support this style of syntax for else-block continuation. I don't think it's a big issue though since the single line `}` would end the selection so it's not as noticible as in the single line case. E.g. compare this cut-off behavior:
This:
```c
if ()
{
// foo
} 
```
With this:
```c
if ()
{
// foo
} else {
```
And it's clear as to why this is only an issue in the single line case
- Big test coverage this time
> Completions: Add multi-line heuristics for C, C++, C#, and Java

- client/cody-shared/src/configuration.ts
- client/cody/BUILD.bazel
- client/cody/package.json
- client/cody/src/completions/completion.test.ts
- client/cody/src/completions/context.ts
- client/cody/src/completions/index.ts
- client/cody/src/configuration-keys.ts
- client/cody/src/configuration.test.ts
- client/cody/src/configuration.ts
- client/cody/src/main.ts
- client/cody/src/testutils/cli/run-code-completions-on-dataset.ts
- Adds a setting to turn off code completions cache: `cody.completions.advanced.cache`. Needed to verify if the completions cache size is the issue for our customer. More context in [the Slack thread](https://sourcegraph.slack.com/archives/C05A7PPR07Q/p1686930187417899?thread_ts=1686841844.511079&cid=C05A7PPR07Q).
- Adds a setting to turn off embeddings context for code completions.: `cody.completions.advanced.embeddings`. Since embeddings also employ a cache, it should help debug the abovementioned issue.
- Change the `CodyCompletionItemProvider` constructor to be an object instead of a long list of arguments. READABILITY FTW.
- Implements a type-safe way to automatically generate a mapping of the VS Code extensions settings defined in the `package.json`. No more typos and updating keys …
> cody: add config properties for embeddings and completions cache

- src-tauri/src/main.rs
Saw a few log lines still referring to `Sourcegraph app`
none - log line change
> app: update log lines for Cody app

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
Closes #53504 
- In case of broken Cody chat state reset conversation button should re-enable "Send" button
> JetBrains: enable send button after conversation reset

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/UpdatableChat.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/api/ChatUpdaterCallbacks.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/AssistantMessageWithSettingsButton.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatBubble.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatUIConstants.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessageContentCreatorFromMarkdownNodes.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessagePanel.java
- client/jetbrains/src/main/java/com/sourcegraph/config/GoToPluginSettingsButtonFactory.java
- client/jetbrains/src/main/java/com/sourcegraph/find/HeaderPanel.java
Adds new "welcome" chat message when access token is not configured, and displays appropriate chat message when we get 401 Invalid access token from the server. 
closes #53460
- Chat message with instructions how to set up a token should appear when token is not configured or if is invalid and user tries to interact with cody
No access token defined
Getting 401 error from backend
> JetBrains: display message in the chat on invalid access token

- client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.tsx
- client/web/src/enterprise/own/admin-ui/query.ts
- cmd/frontend/graphqlbackend/own.go
- cmd/frontend/graphqlbackend/own.graphql
- enterprise/cmd/frontend/internal/own/resolvers/resolvers.go
- enterprise/cmd/frontend/internal/own/resolvers/resolvers_test.go
- enterprise/internal/own/background/analytics_test.go
- internal/database/ownership_stats.go
- internal/database/ownership_stats_test.go
- internal/database/repo_paths.go
Test plan:
GraphQL tests updated.
Closes https://github.com/sourcegraph/sourcegraph/issues/53658
> own: add information when Own statistics were last generated.

- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
- client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionPage.tsx
- client/web/src/enterprise/user/productSubscriptions/__snapshots__/UserSubscriptionsProductSubscriptionPage.test.tsx.snap
- client/web/src/featureFlags/featureFlags.ts
- doc/dev/how-to/cody_gateway.md
As we approach GA, this enables the Cody Gateway management UI by default for Sourcegraph.com so that teammates can begin to familiarize themselves with it before Enterprise GA (5.1 release). I'll be making an announcement tomorrow 😁 
Closes #52519
CI
> featureflags: remove cody-gateway-management-ui, enable by default

- enterprise/internal/completions/client/BUILD.bazel
- enterprise/internal/completions/client/client.go
- enterprise/internal/completions/client/observe.go
- internal/completions/types/BUILD.bazel
- internal/completions/types/types.go
This wraps our completions clients in an observability layer. The observability layer tracks metrics for completions durations as well as adds spans that capture both streaming and batch completion calls.
> Completions: add observability

- client/web/src/repo/blob/CodeMirrorBlob.tsx
- client/web/src/repo/blob/codemirror/scip-snapshot.ts
- enterprise/internal/codeintel/codenav/BUILD.bazel
- enterprise/internal/codeintel/codenav/service.go
- enterprise/internal/codeintel/codenav/service_snapshot_test.go
- enterprise/internal/codeintel/codenav/utils.go
Cases where theres an occurrence on the very last line (with no newline after it) would cause a panic. Fixes this :+1: 
Added unit test and tested in local environment as above ^
> codeintel: address out-of-range bugs in snapshot UI

- sg.config.yaml
- src-tauri/README.md
Improve the documentation for starting up App in dev mode and allow adding of repos by default.
`sg start app`  successful
> App - update sg start app to allow adding repos

- enterprise/cmd/cody-gateway/internal/httpapi/completions/anthropic.go
- enterprise/cmd/cody-gateway/internal/httpapi/completions/openai.go
- enterprise/cmd/cody-gateway/internal/httpapi/completions/upstream.go
- enterprise/cmd/cody-gateway/internal/httpapi/handler.go
- enterprise/cmd/cody-gateway/shared/config.go
- enterprise/cmd/cody-gateway/shared/main.go
See [Slack](https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1686881272805539) for context - this PR adds a limit for `maxTokensToSample` value Cody Gateway will forward to Anthropic.
Also slighly refactors signatures (to replace `any` with a named type) and adds a `validateRequest` hook.
Tested locally with values exceeding the limit and our regular 1000 limit.
Can be tested by running `CODY_GATEWAY_ANTHROPIC_MAX_TOKENS_TO_SAMPLE=50 sg start dotcom` (we use 1000 by default, so all requests will fail).
> Reject requests with MaxTokensToSample > 10000

- enterprise/internal/embeddings/embed/embed.go
- enterprise/internal/embeddings/embed/embed_test.go
We've had a few situations where we generate corrupt indexes because we trust that the embeddings service is returning the correct number of embeddings. In the past, this has failed when the model changes mid-embed (and changes the number of dimensions) and when the embeddings generation service/proxy is misbehaving and returning an empty response with a successful status code.
This moves the error to index time and makes it nice and clear rather than depending on the cryptic panics we get during search time.
Added a test
> Embeddings: check embeddings response length

- enterprise/internal/completions/httpapi/codecompletion.go
- enterprise/internal/completions/httpapi/stream.go
- internal/completions/types/BUILD.bazel
- internal/completions/types/errors.go
Sometimes, we'll get Sentry events indicating chat/completions failed, but it's hard to diagnose if this is something in Cody Gateway because we can't link it to a request on our end if the Sourcegraph request isn't traced. This change always adds an upstream trace if one looks like our internal standards to the log entry, so that it'll show up as a field in Sentry reports.
I think with this we should be good enough to close #53091, now there's always a way to get the corresponding request in Cody Gateway from all environments (logs and/or traces).
This must be added as log fields instead of in the error message to avoid breaking Sentry's error grouping.
CI
> completions/httpapi: log trace context from upstream

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionElementRenderer.java
Fixes #53530 
- verify that completions are rendered correctly on your machine
> JetBrains: Fix the `y` position at which autocomplete suggestions are rendered

- client/cody-ui/src/chat/TranscriptItem.module.css
- client/cody-ui/src/chat/actions/TranscriptAction.tsx
- client/cody/webviews/Chat.module.css
- client/cody/webviews/FileLink.tsx
- fix context files overflow issue:
|:-------------------------------------:|:-------------------------------------:|
| ![](https://github.com/sourcegraph/sourcegraph/assets/68532117/e0f505a3-e046-4212-b533-16a906aea97c) | ![](https://github.com/sourcegraph/sourcegraph/assets/68532117/113da009-1cc7-46c1-be49-fbf493675306) | 
~update feedback container spacing~ (will continue in a separate PR)
|:-------------------------------------:|:-------------------------------------:|
| ![](https://github.com/sourcegraph/sourcegraph/assets/68532117/ea744cbb-7300-4ded-bf05-e715c282b3c8) | ![](https://github.com/sourcegraph/sourcegraph/assets/68532117/4c8614a0-73ab-444a-b19d-c2a12d7ea695) | 
see screenshots above
> cody: fix context files overflow

- client/web/src/cody/chat/CodyChatPage.tsx
- client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.story.tsx
- client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
This PR adds a small additional link to the CTA that links to cody setup docs to reduce friction of setup.
Manually verified and added a storybook story.
> Add cody setup docs like for site-admins

- client/cody-ui/src/chat/TranscriptItem.module.css
- client/cody-ui/src/chat/TranscriptItem.tsx
close https://github.com/sourcegraph/sourcegraph/issues/53729
Add temporary padding to last message while message is in progress so that the `stop-generating` button does not block the response
Loom:
https://github.com/sourcegraph/sourcegraph/assets/68532117/0ee48380-854e-4bdf-91d8-7f1500a59614
> cody: add padding for stop-generating btn

- client/cody-ui/src/Chat.module.css
- client/cody/CHANGELOG.md
- client/cody/webviews/Chat.module.css
- client/cody/webviews/Chat.tsx
This makes the suggestion buttons a little more compact for now (saves 50px vertical height on average)
| - | - |
| <img width="322" alt="Screenshot 2023-06-20 at 10 46 07 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/65df0187-366b-429b-8ff2-7571a4040f61"> |<img width="322" alt="Screenshot 2023-06-20 at 10 46 57 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/15f88959-a2c6-492f-9325-d72e04ddd66a"> |
- Make the buttons appear
- Interact with them
> More compact Cody Chat Suggestions buttons

- src-tauri/README.md
Add documentation about Tauri icons to the App readme.
This explains how the icons work and how to generate the different size and format variants.
- Documentation change only
> App docs: Update readme with documentation about icons

- client/cody-shared/src/configuration.ts
- client/cody/BUILD.bazel
- client/cody/package.json
- client/cody/src/completions/providers/unstable-huggingface.ts
- client/cody/src/configuration.test.ts
- client/cody/src/configuration.ts
- client/cody/src/main.ts
This PR adds an experimental hugging face provider that we can use to test OSS models.
We currently have an instance with a deployed version for WizardCoder available, so this prompt is based on the StarCoder FIM prompt and seems to work great in my limited tests.
The biggest issue we have with this approach is latency. So we'll need to work on this next.
- Set the following settings:
```
"cody.completions.advanced.provider": "unstable-huggingface",
"cody.completions.advanced.serverEndpoint": "https://tjjgqj2ub71aikaq.us-east-1.aws.endpoints.huggingface.cloud",
"cody.completions.advanced.accessToken": "<TOKEN>",
```
- Start a completion request:
> Completions: Add hugging face provider

- CHANGELOG.md
- enterprise/internal/codeintel/uploads/internal/background/processor/scip.go
We're neglecting to add some packages to the `lsif_packages` table. Tracked this down to the `packageSet` map having false values when they should've been true.
Turns out that when processing documents in a particular order we can re-assign false over a true assignment in this map, counting definitions instead as references. This makes it unable to be the target of a jump-to-definition operation.
This PR fixes it so that we don't mark definitions as references once marked as definition.
Ran QA tests locally.
> codeintel: Fix package set construction

- internal/search/BUILD.bazel
- internal/search/env.go
I noticed in some places we use "len(repos.Minimal)" to indicate the number of indexed repos. However, in practice this should be the same as Stats.Repos. The only time Stats.Repos should be inaccurate is when rebalancing between zoekt shards.
I am going to collect data on sourcegraph.com via these metrics to see what happens in practice. I am recording two ways to calculate as well as if we have any crashes (which may also not be reported correctly in some places)
Test Plan: CI
> search: temporarily record stats values

- client/web/src/repo/blob/CodeMirrorBlob.tsx
- client/web/src/repo/blob/backend.ts
- client/web/src/repo/blob/codemirror/scip-snapshot.ts
- cmd/frontend/graphqlbackend/codeintel.codenav.graphql
- enterprise/internal/codeintel/codenav/BUILD.bazel
- enterprise/internal/codeintel/codenav/service.go
- enterprise/internal/codeintel/codenav/shared/types.go
- enterprise/internal/codeintel/codenav/transport/graphql/root_resolver_raw_scip.go
- internal/codeintel/resolvers/codenav.go
Adds relationship data to scip snapshot UI in blob view
Backport f6a16f4c from #53679
> [Backport 5.1] codeintel: add additional relationship data to snapshot view

- client/shared/src/search/stream.ts
We do not URL-encode paths, so special characters (`%`) break the links. This splits paths on `/`, encodes the components, then re-joins on `/` so that we still get nice looking URLs (we don't need to escape `/`). 
Fixes https://github.com/sourcegraph/sourcegraph/issues/40578
Tested that file paths containing `%` generate usable links.
> Search: URL encode path components

- client/web/src/enterprise/app/setup/AppSetupWizard.tsx
- client/web/src/setup-wizard/SetupWizard.tsx
- client/web/src/setup-wizard/components/setup-steps/SetupSteps.tsx
- src-tauri/Cargo.toml
- src-tauri/tauri.conf.json
[Desings ](https://www.figma.com/file/ZkJFUvVzZW9TgFg7k9w9Oq/App-%5BMAIN%5D?type=design&node-id=62-661&t=PZMjaLVAmJdI4ZIx-0)
Based on setup flow designs, we have to lock the window size when we are in the setup flow (the window should be fixed-sized and shouldn't be able to resize); right after the setup flow is finished, we should reset the setup flow to a fixed size and unlock resize. 
@danielmarquespt note that I used a bit increased height value here because the suggested 540 was too small for steps with the progress bar below. I can reevaluate the height value after we get the progress bar UI in place. 
- Check that in the setup flow, you can't resize the window, and it has a fixed 940x640 size
- Check that after setup flow window has standard 1024x768
> App setup: Lock window size in the setup flow

- client/web/src/cody/chat/CodyChatPage.tsx
- client/web/src/cody/components/ChatUI/ChatUi.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/53415
This PR makes links plain text in the Cody app chat, it will be improved later with IDE/editors deep link here https://github.com/sourcegraph/sourcegraph/issues/53776
- Check that links in chat are just plain text and not interactive links.
> Cody: Replace link with plain text in cody app chat

- docker-images/search-indexer/BUILD.bazel
- docker-images/search-indexer/Dockerfile.wolfi
I modified [the relevant Dockerfile in the Zoekt repo](https://github.com/sourcegraph/zoekt/blob/main/Dockerfile.indexserver) but just found this upstream Wolfi one and thought it might be responsible my changes not deploying properly, so I fixed it accordingly.
Generated search-indexer image contains scip-ctags in expected place.
> Copy scip-ctags in search-indexer Dockerfile

- client/web/src/components/gitHubApps/GitHubAppPage.tsx
@st0nebraker [pointed out](https://github.com/sourcegraph/sourcegraph/pull/53212#pullrequestreview-1475310777) in a previous PR that the "View on GitHub" link for GitHub App installations only works if you are able to administer that installation, e.g. that you are an org owner for the org where it's installed, if it's on an org, or that you are the user. If we had this information, we could just hide the button for installations the user can't actually view, but since we don't, we thought it could help to add a note instead.
Just an in-product docs change. Verified the text appears on the GitHub App page.
> github app: add note that only org owners can view org installations

- client/web/src/site-admin/sidebaritems.ts
Closes https://github.com/sourcegraph/sourcegraph/issues/53698
- Check that app doesn't have repositories setting tab in advanced settings
> Hide repositories from the Cody App advanced settings

- src-tauri/src/main.rs
Closes https://github.com/sourcegraph/sourcegraph/issues/53756
This allows clicking the dock icon to show the main window if it is closed but the app is still running.
This is a temporary solution that only works if the app has a single window. If we need to add more windows in the future, we need to wait until https://github.com/tauri-apps/tauri/issues/3084 is fixed.
1. Open app
2. Close with red button on top-left of window
3. Click on Cody icon in dock
App main window should be shown again.
> app: clicking on dock icon should open main window

- enterprise/dev/ci/push_all.sh
This should restore support for release branch preview builds of the format `5.0_227766_2023-06-14_5.0-87c77ce7f9ee` that is used in Cloud to CD builds from release branches: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/controller/-/blob/internal/version/branchimagetag/branch_image_tag.go?L43:1-59:46
Not sure how to test this, just cherry-pick into 5.1 maybe?
> dev/ci: push prod tags on all release branch builds

- internal/settings/BUILD.bazel
- internal/settings/settings.go
We're getting a [concurrent transaction error](https://sourcegraph.sentry.io/issues/4263654659/?project=6583153&referrer=slack) from settings because somewhere we're passing a transaction as the `database.DB` then using it concurrently in this method.
This updates the DB calls to run sequentially. This comes with a perf penalty, but I'd prefer a small perf impact to erroring/crashing/silently doing the wrong thing. As a followup, I will add a DB method that allows you to request settings for multiple subjects at once. That might not come until after 5.1 though, so I'd at least like to get this merged and backported.
Existing tests. Ran a few searches for a manual sanity check.
> Settings: make DB calls sequentially

- doc/admin/config/batch_changes.md
- enterprise/internal/authz/gerrit/mocks_test.go
- enterprise/internal/batches/sources/gerrit.go
- enterprise/internal/batches/sources/gerrit_test.go
- enterprise/internal/batches/sources/mocks_test.go
- internal/extsvc/gerrit/BUILD.bazel
- internal/extsvc/gerrit/changes.go
- internal/extsvc/gerrit/changes_test.go
- internal/extsvc/gerrit/client.go
- internal/extsvc/gerrit/testdata/vcr/DeleteChange.yaml
- migrations/BUILD.bazel
Closes https://github.com/sourcegraph/sourcegraph/issues/52386.
If the `batchChanges.autoDeleteBranch` site configuration option is enabled, Batch Changes will delete a Change on Gerrit after it is closed/abandoned. It is not possible to delete a Change once it has been merged.
https://github.com/sourcegraph/sourcegraph/assets/8942601/5d9f52cc-b34a-4ef1-a74f-2dc72d39b572
Client unit test coverage. Manual integration test, see video above.
> batches: auto-delete Gerrit Change on close

- cmd/frontend/graphqlbackend/dotcom.go
- cmd/frontend/graphqlbackend/dotcom.graphql
- enterprise/cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
In preparation to cut over to using the user id as the actor ID for the dotcom user actor, this adds the user id to the specific resolver that the cody gateway accesses.
`sg start dotcom`
```graphql
{
dotcom{
codyGatewayDotcomUserByToken(token:{TOKEN}){
username
id
codyGatewayAccess{
enabled        
}
}
}
}
```
```json
{
"data": {
"dotcom": {
"codyGatewayDotcomUserByToken": {
"username": "chrislocaldotcom",
"id": "VXNlcjo3",
"codyGatewayAccess": {
"enabled": true
}
}
}
}
}
```
> Cody-gateway - add user id to the dotcom user actor resolver

- doc/cody/explanations/enabling_cody.md
- doc/cody/index.md
Replaces instructions for Cody on dotcom with Cody app and streamlines the editor extension description a bit. We still need to articulate why a user should choose enterprise over app (or why they should upgrade from app to enterprise), but I'm guessing that might make more sense on about.sourcegraph.com than in the docs? Either way, it can be a separate update. 
n/a docs update
> Update Cody docs page

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java
- client/jetbrains/src/main/java/com/sourcegraph/common/EditorUtils.java
- client/jetbrains/src/test/java/InlineCompletionsPostProcessingTest.java
Fixes #53236 
Cody can possibly return suggestions prefixed with mixed whitespace indentation (tabs, spaces).
This makes sure tabs are converted to spaces in that case, according to the tab size configured in the relevant `IndentOptions`.
Note: any tabs after the indentation (leading whitespace string) are preserved in the suggestion. I believe it's the same in our VS Code implementation, correct me if I'm wrong.
I have included a unit test.
> JetBrains: convert `\t` to spaces in leading whitespace for autocomplete suggestions

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/config/PluginSettingChangeContext.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsChangeListener.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsConfigurable.java
Fixes #53748 
Should work as expected now.
https://github.com/sourcegraph/sourcegraph/assets/18601388/2eaab5ef-f2e3-4108-930b-bd788226c139
Make sure the following steps work on your local (as on the attached screen recording):
- enable completions
- have a suggestion rendered in an editor
- go back to settings, disable completions, save
- the previously rendered completion should disappear immediately
> JetBrains: Clear all rendered completions when they are disabled

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatBubble.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessageContentCreatorFromMarkdownNodes.java
Added some styles to distinguish inline code blocks in message from regular text
- Inline code blocks should get a different background color and the font should match current font from the main editor
> JetBrains: add background color to inline code blocks in chat message

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessageContentCreatorFromMarkdownNodes.java
Line highlight in code editor in Cody message is disabled, so the colors of the highlighted line in editor it doesn't blend with the background of the regular text
Before:
Now:
- Line highlighting of code inside code blocks is disabled
> JetBrains: disable line highlighting in Cody messages with code blocks

- enterprise/dev/app/tauri-build.sh
- src-tauri/src/main.rs
- fix script which uploads .deb
- add config for rust to only use the hide api on Mac
Pushed a release on `app-release/debug` and the app built successfully (previously it didn't)
- [Release](https://github.com/sourcegraph/sourcegraph/releases/tag/untagged-e8a2bdd5e13eadfc6b35)
- [Build](https://buildkite.com/sourcegraph/cody-app-release/builds/1319#0188dc45-dde0-4f98-90b4-1351e2671785)
> app: only use hide on mac otherwise use event window hide

- client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.story.tsx
- client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.tsx
Closes #53735
This change displays a zero-valued graph in own analytics rather than an empty page when zero-data is served.
Minor fixes drive-by:
- ensure `totalFiles` that values are divided by to compute percentages is non zero
- add space after colon in _Files owned through CODEOWNERS:_ tooltip
- in `lastUpdatedAt` use `x && y` instead of `x ? y : undefined` 
Before (graph absent):
After (graph present):
NEW STORYBOOK 🎉
> Fix empty own analytics in case zero-data is served

- client/cody-shared/src/chat/transcript/index.ts
- client/cody/src/chat/ChatViewProvider.ts
A temporary workaround for setting token limits in clients until appropriate configuration options are added to the backend.
Setting `cody.provider.limit.prompt` and `cody.provider.limit.solution` creates a replacement for [MAX_AVAILABLE_PROMPT_LENGTH](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody-shared/src/prompt/constants.ts?L7) to use in getPromptForLastInteraction, which truncates the list of messages to fit within a maximum prompt length defined by `MAX_AVAILABLE_PROMPT_LENGTH`.
From Cody:
```
MAX_AVAILABLE_PROMPT_LENGTH is being used to calculate the maximum length of the prompt that can be shown to the user.
It is calculated by subtracting the SOLUTION_TOKEN_LENGTH (which represents the length of the solution code) from the MAX_PROMPT_TOKEN_LENGTH …
```
> cody: config options for setting token limits

- client/cody-shared/src/chat/useClient.ts
- client/web/src/cody/components/ChatUI/ChatUi.tsx
- client/web/src/cody/isCodyEnabled.tsx
- Update notice in cody sidebar for logged-out users on dotcom
- Reset chat scope state on creating new chat. 
- Open cody sidebar on dotcom being logged out, it should say "sign in to get access to cody"
- Visit /cody, add repos to scope, create new chat, the scope should be reset.
> Fix cody gating & scope state reset

- cmd/frontend/graphqlbackend/search_results.go
- cmd/frontend/internal/search/BUILD.bazel
- cmd/frontend/internal/search/search.go
- internal/search/client/BUILD.bazel
- internal/search/client/telemetry.go
This was a weird dependency on graphqlbackend in the streaming endpoint. I chose client as the package for this to live in with the intention to move and unify search telemetry into the client. So this is a work in progress and will evolve quickly.
Test Plan: CI
> search: move DetermineStatusForLogs out of graphqlbackend

- cmd/gitserver/server/server.go
- internal/wrexec/recording_cmd.go
- internal/wrexec/recording_cmd_test.go
Minor issue I came across while reading code. Previously if a site-admin removed GitRecorder configuration that would be ignored until the next process restart. This explicitly handles that.
Additionally a test is added that we handle nil predicates. We already relied on this behaviour since if GitRecorder was not configured we would never call update => we had a nil predicate.
Test Plan: CI
> wrexec: handle unsetting GitRecorder config

- .vscode/launch.json
- dev/sg/internal/rfc/BUILD.bazel
- dev/sg/internal/rfc/rfc.go
- dev/sg/internal/rfc/rfc_test.go
Implements the new Google OAuth flow following [Obtaining OAuth 2.0 access tokens](https://developers.google.com/identity/protocols/oauth2/native-app?hl=en#step-2:-send-a-request-to-googles-oauth-2.0-server).
Closes #53522.
Added tests for the OAuth flow:
bazel test //dev/sg/internal/rfc:all
- All new code has a corresponding unit test
- Added unit test to existing code that was changed
> rfc/oauth: Implement new Google OAuth flow.

- doc/admin/executors/deploy_executors.md
- doc/admin/executors/deploy_executors_binary.md
- doc/admin/executors/deploy_executors_terraform.md
- doc/admin/executors/executor_secrets.md
- doc/admin/executors/index.md
- doc/admin/executors/native_execution.md
- doc/admin/index.md
Closes [#51734](https://github.com/sourcegraph/sourcegraph/issues/51734)
This just affects Binary and Terraform deployments.
No tests needed.
> executors: Update Documentation to remove Beta Tag

- enterprise/cmd/executor/internal/worker/command/kubernetes_test.go
Change to use `ElementsMatch` from `Equal`
Updated existing test
> executors: Fix flakey test

- enterprise/internal/own/ownref.go
Closes https://github.com/sourcegraph/sourcegraph/issues/53800
It isn't clear to me _why_, but there are userRefs with a nil user. This adds some simple guards to the user and team code to only dereference is we are sure we can.
N/A
> own: fix panic in bag resolver

- client/web/src/enterprise/batches/create/ConfigurationForm.module.scss
Closes https://github.com/sourcegraph/sourcegraph/issues/53111.
https://github.com/sourcegraph/sourcegraph/assets/8942601/4bf26845-0ac9-4868-b4f1-52f90a426854
The non-read-only version of the form has the description for the name input, which makes it expand to fill the whole `max-width`. The read-only form had shrunk because it doesn't have that description, so its contents didn't require it to be any wider. 
Visually verified the form width.
> batches: enforce min-width on configuration form

- client/web/src/enterprise/batches/create/ConfigurationForm.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/53318.
Fixes bug where the wrong namespace would be displayed in the read-only selector for namespace on a batch change's configuration tab. This was due to a mistaken assumption that the viewer would always have access to that namespace. If the viewer didn't, we'd default to the viewer's own namespace, hence the bug.
The namespace shown in the selector on the read-only form should *always* match the namespace shown in the page title breadcrumb:
And the viewer should continue to only be able to select from namespaces they can actually create batch changes in, when creating a new one:
Manually verified.
> batches: fix namespace displayed in readonly field of configuration form

- enterprise/cmd/cody-gateway/internal/httpapi/BUILD.bazel
- enterprise/cmd/cody-gateway/internal/httpapi/diagnostics.go
- enterprise/cmd/cody-gateway/internal/httpapi/handler.go
- enterprise/cmd/cody-gateway/internal/httpapi/requestlogger/BUILD.bazel
- enterprise/cmd/cody-gateway/internal/httpapi/requestlogger/requestlogger.go
- enterprise/cmd/cody-gateway/shared/BUILD.bazel
- enterprise/cmd/cody-gateway/shared/main.go
- internal/audit/BUILD.bazel
- internal/audit/audit.go
- internal/audit/audit_test.go
- internal/requestclient/BUILD.bazel
- internal/requestclient/client.go
- internal/requestclient/grpc.go
- internal/requestclient/http.go
Backport https://github.com/sourcegraph/sourcegraph/pull/53785
Clientside this is a pretty minimal diff - mostly tests and some diff in Cody Gateway which is not part of the Sourcegraph service
https://github.com/sourcegraph/sourcegraph/pull/53785
> [Backport 5.1] reqeuestclient, audit, cody-gateway: log user-agent as well (#53785)

- dev/oci_deps.bzl
- wolfi-images/blobstore.yaml
- wolfi-images/server.yaml
- wolfi-packages/s3proxy.yaml
Update s3proxy to latest release of our fork, which I've updated. Fixes ~44 vulns!
- s3proxy tests pass
- manual checking of final image
> Update s3proxy to latest custom release

- CHANGELOG.md
- doc/admin/observability/tracing.md
- internal/debugserver/BUILD.bazel
- internal/debugserver/debug.go
- internal/trace/BUILD.bazel
- internal/trace/trace.go
- internal/trace/tracer.go
Follow-up from https://github.com/sourcegraph/sourcegraph/pull/53435#issuecomment-1597050970 and INC-214 - this removes `net/trace` instrumentation entirely in the next release.
It seems [this gets low usage and may be difficult to use](https://github.com/sourcegraph/sourcegraph/pull/53795#pullrequestreview-1489890896), and it seems to introduce some risk and overhead. This will also make it easier to drop our internal trace wrapper entirely and/or integrate it as part of OpenTelemetry's APIs instead of having a proprietary way of doing traces.
Already tested in https://github.com/sourcegraph/sourcegraph/pull/53435
> internal/trace: remove net/trace integration

- dev/oci_deps.bzl
- wolfi-images/blobstore.yaml
- wolfi-images/server.yaml
- wolfi-packages/s3proxy.yaml
Reverts sourcegraph/sourcegraph#53872
This is blocking main. The change seems to have caused an issue with the backend_integration_test. Will investigate tomorrow.
- Manually checking main is green again
> Revert "Update s3proxy to latest custom release"

- cmd/symbols/Dockerfile
- cmd/symbols/build.sh
- cmd/symbols/ctags-install-alpine.sh
- enterprise/cmd/symbols/build.sh
Restore bash scripts for those building symbols locally outside bazel, primary with `sg start`
run `sg start` locally
> sg: restore symbols for sg

- cmd/gitserver/server/server_grpc.go
- internal/gitserver/client.go
This PR tweaks the gRPC gitserver.Archive and gitserver.Exec methods to translate some classes of well-known errors to particular gRPC status [codes](https://grpc.github.io/grpc/core/md_doc_statuscodes.html). 
In particular, the following errors get these [specific status codes](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) instead of codes.Unknown (previously)
- `context.Cancelled` -> `codes.Cancelled`
- `context.DeadlineExceeded` -> `codes.DeadlineExceeded`
- (if a `git` process is terminated via `SIGKILL`) -> `codes.Aborted`
When I was QA'ing the new gitserver.Archive implementation, I noticed that it has a fairly high error rate on sourcegraph.com: https://sourcegraph.com/-/debug/grafana/d/gitserver/git-server?viewPanel=100711&orgId=1&var-alert_level=&var-shard=&var-method= …
> grpc: gitserver: exec/archive: convert context errors to gRPC status codes, convert signal:killed to status.Aborted

- internal/trace/BUILD.bazel
- internal/trace/context.go
- internal/trace/context_test.go
Currently, if we have a raw OTel trace in the context but no active `trace.Trace`, we `TraceFromContext` will not use that, so we can lose some tracing information. This provides a temporary fix to make `TraceFromContext` create a new, ephemeral `*Trace` that contains the OTel span if it exists.
I think the real solution here is to just go all in on the OTel tooling and make our custom trace stuff conform to the OTel interfaces. I'll work on that in the background, but I want to get this out before 5.1.
Added unit tests.
> Tracing: inherit from raw OTel trace for TraceFromContext

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowFactory.java
Cody input prompt gets autofocus when Cody tool window is opened or when we switch between "Chat" and "Recipes" tabs inside the Cody
- Prompt input gets focus when Cody Chat window is opened
> JetBrains: autofocus prompt input in Cody chat

- WORKSPACE
Catch-up with latest release. 
CI
> bzl: bump hermetic-cc to 2.0 from 2.0.0-rc2

- client/web/src/components/FilteredConnection/hooks/useShowMorePagination.ts
- client/web/src/enterprise/site-admin/cody/SiteAdminCodyPage.tsx
When a user clicks on "Schedule Embedding", we schedule the repos for embedding and refetch the job list to update the view. However, the current refetch logic fetches only `n` results, where `n` is the number of jobs currently displayed. This leads to a confusing behavior (1 job visible, user schedules 3 more => 1 job visible), which the user can fix with a page refresh. Not ideal.
With this PR we always fetch a full page, i.e. 10 jobs, which makes more sense, because the number of jobs likely will have increased after the user clicked on "Schedule Embedding".
The root cause of the bug is that `refetchAll` closes over the current list of jobs, which I believe is the intention for the other call sites. I don't think it is a good idea to modify `refetchAll` during the code freeze. …
> cody site-admin: fix refetch for one-time jobs

- cmd/frontend/internal/app/updatecheck/app_update_check_test.go
- cmd/frontend/internal/app/updatecheck/app_update_checker.go
* Use semver constraints to prevent updates for clients on or before version `2023.6.13`
* Refactor tests
Unit tests
> app: prevent updates for clients on or before v2023.6.13

- shell.nix
Some stuff needed to build oci images with bazel on nix. Did you know `shasum` comes from the perl package? wild
N/A nix stuff
> nix: more bazel paths

- dev/oci_deps.bzl
- enterprise/dev/ci/scripts/wolfi/build-base-image.sh
- wolfi-images/batcheshelper.yaml
- wolfi-images/blobstore.yaml
- wolfi-images/bundled-executor.yaml
- wolfi-images/cadvisor.yaml
- wolfi-images/executor-kubernetes.yaml
- wolfi-images/executor.yaml
- wolfi-images/gitserver.yaml
- wolfi-images/jaeger-agent.yaml
- wolfi-images/jaeger-all-in-one.yaml
- wolfi-images/node-exporter.yaml
- wolfi-images/opentelemetry-collector.yaml
- wolfi-images/postgres-exporter.yaml
- wolfi-images/postgresql-12-codeinsights.yaml
- wolfi-images/postgresql-12.yaml
- wolfi-images/prometheus.yaml
- wolfi-images/redis-exporter.yaml
- wolfi-images/redis.yaml
- wolfi-images/repo-updater.yaml
- wolfi-images/search-indexer.yaml
- wolfi-images/searcher.yaml
- wolfi-images/server.yaml
- wolfi-images/sourcegraph-base.yaml
- wolfi-images/sourcegraph-dev.yaml
- wolfi-images/sourcegraph.yaml
- wolfi-images/symbols.yaml
- wolfi-images/syntax-highlighter.yaml
We need to push Wolfi base images to dockerhub to make them publicly accessible.
Once a first review pass has been made on this, we can push to a `wolfi/*` branch and check it works as expected.
I'll follow this with a second PR to switch `oci_deps.bzl` to point to dockerhub as well.
- Manually checking images are uploaded to dockerhub.
- Green `wolfi/` CI: https://buildkite.com/sourcegraph/sourcegraph/builds/229782
- Green main-dry-run: https://buildkite.com/sourcegraph/sourcegraph/builds/229784
> Push wolfi base images to Dockerhub

- cmd/gitserver/server/cleanup_test.go
- cmd/gitserver/server/list_gitolite_test.go
- cmd/gitserver/server/patch.go
- cmd/gitserver/server/server.go
- cmd/gitserver/server/server_test.go
- cmd/gitserver/server/vcs_syncer_git.go
- cmd/gitserver/shared/BUILD.bazel
- cmd/gitserver/shared/shared.go
- cmd/gitserver/shared/shared_test.go
- internal/gitserver/BUILD.bazel
- internal/gitserver/client_test.go
- internal/gitserver/integration_tests/BUILD.bazel
- internal/gitserver/integration_tests/test_utils.go
- internal/wrexec/recording_cmd.go
In this commit we wrap the fetch command in a RecordingCommandFactory similar to what is currently done at the call site of CloneCommand.
In order to make this cleaner - we add the RecordingCommandFactory on the GitRepoSyncer and introduce a constructor - NewGitRepoSyncer to ensure that the factory is always initialised and make GitRepoSyncer private.
The recording factory is initialised with a nil `shouldRecord` at the moment so this won't start recording fetch commands immediately. We update the factory similar to that in the server's handler and even then it should only affect those repos that are listed in the conf. So in addition to recording the clone path, now we will also record all fetches of those repos - which could be a source of more writes to redis (the backing store of the …
> gitserver: Add recordingfactory to Fetch of git vcs syncer

- client/web/src/enterprise/app/routes.tsx
- client/web/src/enterprise/app/setup/steps/AppLocalRepositoriesSetupStep.tsx
- client/web/src/enterprise/app/setup/steps/AppWelcomeSetupStep.module.scss
- client/web/src/enterprise/app/setup/steps/AppWelcomeSetupStep.tsx
[Design](https://www.figma.com/file/ZkJFUvVzZW9TgFg7k9w9Oq/App-%5BMAIN%5D?type=design&node-id=76-1782&mode=design&t=T4Ab2kSnq66kRtR9-0)
| State | UI |
| ------ | ------ | 
| Loading state | <img width="1008" alt="Screenshot 2023-06-21 at 17 06 28" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/15425842-de83-4317-ad22-490a405f756f"> |
| Verified state | <img width="1052" alt="Screenshot 2023-06-21 at 17 06 04" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/5c34d288-50ad-4571-bd97-5d34aea7fd8c"> |
@danielmarquespt I had to make a few changes to the original designs 
- This implementation doesn't have a re-send button. It turned out that we simply don't have this functionality in our API at the moment. We possible can do it later
- We do polling to get the …
> Setup: Add setup email verification state

- dev/oci_deps.bzl
We aren't pushing the grafana base image to dockerhub yet.
- CI
- Pull `us.gcr.io/sourcegraph-dev/wolfi-grafana@sha256:ec1049f35ff7e4ab6ff7b4cc6790996ad74d196b8dcee8ea5283fca759156637` manually
> Fix grafana base image

- cmd/blobstore/BUILD.bazel
- cmd/server/shared/blobstore.go
- dev/oci_deps.bzl
Backport this PR: https://github.com/sourcegraph/sourcegraph/pull/53921
Because some of the build pipeline has diverged, this couldn't be backported automatically so I've created this separate PR to backport the required changes.
This commit is not on main, but it implements the same changes as the above PR.
This is worth backporting as it fixes a number of CVEs in s3proxy.
- Green CI main-dry-run: https://buildkite.com/sourcegraph/sourcegraph/builds/229796
- Manually check final images
> [Backport] s3proxy vulnerability fixes

- dev/bazel_stamp_vars.sh
New way of handling version stamping was written with the idea that we'll move away from the pipeline generator. But I didn't follow-up with that impl on the tagged release versions stamping. 
So the best approach at this point is to revert to using the CI generated `VERSION`. 
Need to be backported so we can have a proper release tag and version in the binaries. 
CI + main-dry-run to inspect images
> [backport] bzl: use old method for getting VERSION stamping

- enterprise/cmd/cody-gateway/internal/actor/dotcomuser/BUILD.bazel
- enterprise/cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
- enterprise/cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser_test.go
- enterprise/cmd/cody-gateway/internal/dotcom/operations.go
- enterprise/cmd/cody-gateway/internal/dotcom/operations.graphql
This converts the dotcom user actor to use the userid as the actor id instead of the username.   
Updated and added tests
`sg start dotcom` with access token generated from a dotcom user  verified chat worked and was rate limited.
> Cody Gateway - switch dotcom actor id to userid instead of username

- client/web/src/enterprise/batches/list/BatchChangesChangelogAlert.tsx
- enterprise/internal/codeintel/autoindexing/internal/inference/libs/indexes.go
- internal/src-cli/consts.go
Retry of https://github.com/sourcegraph/sourcegraph/pull/53718, part of https://github.com/sourcegraph/sourcegraph/issues/49918
CI
> release: v5.1.0 bake constants and static content

- internal/conf/confdefaults/confdefaults.go
This removes default App settings that are not needed.
`incremental=true` the default currently
`excludedFilePathPatterns` has a better [default](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/embeddings/embed/files.go?L29:5&popover=pinned)
closes https://github.com/sourcegraph/sourcegraph/issues/53724
Made a local release build
Went though setup verified embeddings created 
Verified proper defaults
> App - remove embeddings settings that already have defaults

- internal/auth/userpasswd/app.go
- src-tauri/tauri.conf.json
Updates the name of the query param used to allow the tauri shell to open the UI
closes https://github.com/sourcegraph/sourcegraph/issues/53849
`sg start app` ui loaded
build local release version - opened app UI appeared checked logs to verify new query param name
> App - update the signin url query param name

- cmd/frontend/graphqlbackend/app.go
- cmd/frontend/graphqlbackend/app.graphql
- enterprise/cmd/frontend/internal/app/resolvers/progress.go
This adds another resolver to indicate when at least repo has completed embeddings.
Also add better support for failed/canceled jobs.  Now if a job fails it will advance the progress bar, it does this because that repo is done and it will not full complete otherwise.
**Check that when all jobs fail it still gets to 100%**
misconfigure embeddings with an invalid url 
`sg start app` and monitor progress
```
{embeddingsSetupProgress: {__typename: "EmbeddingsSetupProgress", overallPercentComplete: 100, oneRepositoryReady: false}}
```
Check for one repository ready
`sg start app` and monitor progress
```
{embeddingsSetupProgress: {__typename: "EmbeddingsSetupProgress", overallPercentComplete: 34, oneRepositoryReady: true}}
```
> App - setup progress add field to indicate 1 repo complete

- enterprise/cmd/cody-gateway/internal/httpapi/BUILD.bazel
- enterprise/cmd/cody-gateway/internal/httpapi/embeddings/BUILD.bazel
- enterprise/cmd/cody-gateway/internal/httpapi/embeddings/openai.go
- enterprise/cmd/cody-gateway/internal/httpapi/embeddings/openai_test.go
- enterprise/cmd/cody-gateway/internal/httpapi/handler.go
- enterprise/internal/embeddings/embed/BUILD.bazel
- enterprise/internal/embeddings/embed/client/openai/BUILD.bazel
- enterprise/internal/embeddings/embed/client/openai/client.go
- enterprise/internal/embeddings/embed/client/openai/client_test.go
- enterprise/internal/embeddings/embed/embed.go
The OpenAI embeddings API will nondeterministically return `null` for the `embedding:` field in the bulk embeddings API response payload. This is problematic because it causes our embeddings jobs to fail (previously, it would corrupt them, now we error). Retrying the whole request will sometimes help, but for some repos, there might be many duplicated chunks, so all of them need to succeed together for the full bulk request to succeed. 
This PR retries the failed chunks individually so that we don't need to depend on all the failing chunks to succeed in the same request. It's pretty hacky, and has a lot of duplication since we have two independent OpenAI clients, but refactoring that will need to be a followup. 
Added tests with a real HTTP server that repsonds with the invalid payloads …
> Embeddings: retry individually when OpenAI gives us back `null` fields

- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/CodyCompletionItemProvider.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/PostProcess.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/Completion.java
- client/jetbrains/src/test/java/PostProcessTest.java
Fixes #53645
This is mostly porting stuff from the VS Code plugin.
- I ported some of the tests from VS Code as well, so that we have a sanity check.
> JetBrains: port post-processing logic from VS Code

- client/cody/webviews/App.tsx
bug introduced by my last commit where I switched to using `isAuthenticated` instead of staying with `authStatus`, and did not `setisAuthenticated` when the config is first loaded, so it might cause some people unable to sign in automatically on restart.
Still passing all the current auth tests 🙏
> cody: unblock auth view

- enterprise/internal/github_apps/auth/auth_test.go
This was missing from a few of the uses of NewInstallationAccessToken, which for me lead to test failures locally.
Test Plan: go test passes locally
> auth: add rcache.SetupForTest for all NewInstallationAccessToken

- client/cody-shared/src/chat/preamble.ts
- client/cody-shared/src/chat/recipes/chat-question.ts
- client/cody-shared/src/chat/recipes/helpers.ts
- client/cody-shared/src/chat/recipes/next-questions.ts
- client/cody-shared/src/codebase-context/index.ts
- client/cody-shared/src/prompt/templates.ts
- client/web/src/cody/components/ChatUI/ChatUi.tsx
Improves Cody's context to clearly tell what repos are in the context and ask cody to suggestion the user add additional repos using the repo selector below the input box.
Also with each context files code snippet, include name of the repo the files belongs to. 
closes: #54002
- start a new chat
- Ask cody "explain sourcegraph/sourcegraph repo"
- Cody should apologise and ask to add additional repos to the context using the repo selector below the input box.
- Add sourcegraph/sourcegraph repo using the repo selector
- Again, ask cody to "explain sourcegraph/sourcegraph repo."
- Cody should reply correctly this time.
- Now, continue the same conversation by asking the same question for a different repo.
> Improve Cody's preamble to support multi-repo context

- internal/search/backend/cached_test.go
- internal/search/backend/fake.go
- internal/search/backend/horizontal.go
- internal/search/backend/horizontal_test.go
Not aggregating ReposMap was an oversight which luckily we do not use yet (but intend on migrating too). Stats.Repos is a field we want to start using to avoid the need of caching the full list in memory.
Test Plan: updated our fakes to populate Repos and ReposMap which then exercised the changed code paths.
> search: populate Stats.Repos and ReposMap from List

- cmd/blobstore/BUILD.bazel
- cmd/github-proxy/BUILD.bazel
- cmd/gitserver/BUILD.bazel
- cmd/loadtest/BUILD.bazel
- cmd/migrator/BUILD.bazel
- cmd/server/BUILD.bazel
- cmd/sourcegraph-oss/BUILD.bazel
- dev/sg/BUILD.bazel
- docker-images/prometheus/cmd/prom-wrapper/BUILD.bazel
- enterprise/cmd/batcheshelper/BUILD.bazel
- enterprise/cmd/cody-gateway/BUILD.bazel
- enterprise/cmd/embeddings/BUILD.bazel
- enterprise/cmd/executor/BUILD.bazel
- enterprise/cmd/frontend/BUILD.bazel
- enterprise/cmd/gitserver/BUILD.bazel
- enterprise/cmd/migrator/BUILD.bazel
- enterprise/cmd/precise-code-intel-worker/BUILD.bazel
- enterprise/cmd/repo-updater/BUILD.bazel
- enterprise/cmd/server/BUILD.bazel
- enterprise/cmd/sourcegraph/BUILD.bazel
- enterprise/cmd/symbols/BUILD.bazel
- enterprise/cmd/worker/BUILD.bazel
- internal/cmd/ghe-feeder/BUILD.bazel
- internal/cmd/search-blitz/BUILD.bazel
- internal/cmd/src-cli-version/BUILD.bazel
- internal/database/migration/shared/data/cmd/generator/BUILD.bazel
A few `x_defs` attributes were missing on binaries, which is now fixed. Also moved to stamping from `go_library` rules to `go_binaries` to ease caching. 
CI + main-dry-run + locally tested + `strings github-proxy | grep version` on `us.gcr.io/sourcegraph-dev/github-proxy:323c450504f8`
> bzl: set version on bins, not lib + add missing

- client/cody/src/services/AuthProvider.ts
Removes CTA from the "Signed in to (endpoint)" notification.
Reasoning: Pretty much all users will still have the Cody screen open - they've just been redirected back to VS Code. This CTA won't do appear to do anything if Cody is open, so remove the avoid confusion.
> Cody: Remove CTA from login notification

- client/web/BUILD.bazel
- client/web/src/components/gitHubApps/AppLogo.tsx
- client/web/src/components/gitHubApps/GitHubAppCard.tsx
- client/web/src/components/gitHubApps/GitHubAppPage.tsx
- client/web/src/enterprise/batches/settings/CommitSigningIntegrationNode.module.scss
- client/web/src/enterprise/batches/settings/CommitSigningIntegrationNode.tsx
1. GitHub App logo error fallback image
**BEFORE**
**AFTER**
2. GitHub App Edit screen mobile responsiveness (Down to 320px screenwidth)
**BEFORE**
**AFTER**
- Manual visual testing
> batches: UI papercut fixes

- client/web/src/site-admin/SiteAdminUpdatesPage.tsx
Fixes #52969 
- Before, update link in the Maintenance page routed to the about page
- Now, it routes to the update instructional docs
Test link manually.
> fix update link routed to the wrong page

- enterprise/cmd/cody-gateway/internal/notify/rate_limit.go
The actor ID of the dotcom user type [has changed to be the database ID](https://github.com/sourcegraph/sourcegraph/pull/53967), and because we currently don't have the ability to produce a direct link with database ID through URL hacking for that user, we downgrade to the pure-text version for the usage notifications.
CI
> cody-gateway: remove link in dotcomuser usage notify

- .buildkite/hooks/pre-command
We normally skip install of asdf images when GROUP_KEY is `Publish Images`, except for certains steps:
* Publish executor image in https://github.com/sourcegraph/sourcegraph/commit/bc0049c818fea6774d8aa7eb688f5b0cea7f7583
and now also Publish Docker registry image
BUILDKITE_GROUP_KEY="Publishimages" BUILDKITE_STEP_KEY="packerwhitecheckmarkPublishdockerregistrymirrorimage" .buildkite/hooks/pre-command
> ci: install asdf plugins on publish docker registery

- src-tauri/src/common.rs
- src-tauri/src/main.rs
Add validation for to the deep link handler in App to allow only paths that start with a slash. 
This makes sure that you can't use a deep link to open an unwanted URL in App.
- Added automated tests for `extract_path_from_scheme_url`
- Run `cargo test` in `src-tauri/`
> App: Add checks to validate paths in deep links

- client/web/src/enterprise/site-admin/cody/RepoEmbeddingJobNode.tsx
- client/web/src/enterprise/site-admin/cody/SiteAdminCodyPage.tsx
In App, removes the link from the repo names in "Embeddings jobs"
The repo name will no longer be a link, in App only.
Fix #53893
- Run App
- Test manually
> App: Remove link to repo when in App

- client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
Resolving: https://github.com/sourcegraph/sourcegraph/pull/54041#discussion_r1240170393
Forgot to render the link only for site admins.
- log in as site admin
- open the scope selector and click on the embeddings icon
- should redirect to site admin embeddings page
- login as non site admin
- open the scope selector and click on the embeddings icon
- should not redirect to site admin embeddings page
> [Cody] remove link for non site admins

- client/cody-shared/src/chat/markdown.ts
- client/common/src/util/markdown/markdown.test.ts
- client/common/src/util/markdown/markdown.ts
Add `target="_blank"` to all links in the markdown of Cody chat messages, which are rendered with `renderCodyMarkdown()`.
This opens all links within Cody chats in a new browser tab.
This is necessary (and the reason we're making this change) for the Cody UI specifically within App, because App needs to open all links in a browser instead of opening them inside of the App frame, which replaces the App's UI and it breaks it.
Add a new boolean option for `renderMarkdown` called `addTargetBlankToAllLinks`. 
It's used only in `renderCodyMarkdown` so this change only affects markdown rendered inside of Cody chat messages.
It adds `target="_blank"` and `rel="noopener"` to all `<a>` links that have a `href`, after converting from markdown, so this includes markdown-formatted links as well as …
> Add target=_blank to all links in Cody markdown

- doc/cody/explanations/enabling_cody_enterprise.md
Hyperlink not working inside the inline json comment -- removed as hyperlink below code block
doc
> Doc Update enabling_cody_enterprise.md

- client/cody/src/configuration.ts
changes the logged event name to follow our standard.
[More info on this doc](https://docs.google.com/document/d/1hHUsKWqDDHaB7mL5MgNLEdIWOPnbR-9KVBWSMQMSbO4/edit)
test locally
> refactor event name to comply with standards

- docker-images/postgres-12-alpine/Dockerfile
Fix vulnerability in postgres-12-alpine (postgres-12-alpine, codeintel-db, codeinsights-db) by updating ncurses-libs
- Green main-dry-run
- Scanning final images
> Update ncurses-libs in postgres-12-alpine images

- cmd/gitserver/server/server_test.go
- cmd/repo-updater/repoupdater/BUILD.bazel
- cmd/repo-updater/repoupdater/server.go
- cmd/repo-updater/repoupdater/server_test.go
- internal/grpc/contextconv/BUILD.bazel
- internal/grpc/contextconv/conversion.go
- internal/grpc/contextconv/conversion_test.go
- internal/grpc/contextconv/doc.go
- internal/grpc/defaults/BUILD.bazel
- internal/grpc/defaults/defaults.go
- internal/grpc/internalerrs/common.go
- internal/grpc/internalerrs/common_test.go
- internal/grpc/internalerrs/logging.go
- internal/grpc/internalerrs/prometheus.go
- internal/repoupdater/client.go
This PR adds interceptors that convert _raw_ `context.Cancelled/DeadlineExceeded` errors into [status.Cancelled / status.DeadlineExceeded](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) errors and vice versa.
For **clients**, this greatly simplifies error handling as we shouldn't need to sprinkle checks like "if status.Code(err)== Cancelled: return context.Cancelled" all over the place any more.
For **servers**, this is more of a defensive mechanism. These interceptors _only_ operate on errors that don't already have a status code associated with them, since it can't assume when it is or isn't appropriate to "override" a specific status code that a server author chose for any given method. (I am willing to revisit this after the code freeze if we find this restriction too …
> grpc: add interceptors that convert raw context.[Cancelled/DeadlineExceeded] errors into status errors and vice versa

- client/web/src/site-admin/sidebaritems.ts
The items in the repos group are not relevant to App since all repositories need to sit on the current computer.  Users can manage cloning via the tool of their choice and then add the local once they are local.
`sg start app` ensure section not shown
`sg start` ensure repos section is visible
> App - remove the repos settings group in advanced settings

- client/cody-shared/src/chat/useClient.ts
- client/cody-shared/src/sourcegraph-api/graphql/client.ts
- client/cody-shared/src/sourcegraph-api/graphql/queries.ts
- client/web/src/cody/chat/CodyChatPage.tsx
- client/web/src/cody/components/ChatUI/ChatUi.tsx
- client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
- client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
- client/web/src/cody/useCodyChat.tsx
closes: #54086
**Only for Cody App**, the first 10 repos on the instance are autoloaded into the chat context on initializing a new chat or resetting the chat scope.
Demo: https://www.loom.com/share/fc1289d2f32846348a8c51572293a909
- Open Cody App
- Modify the scope of the currently opened chat.
- Reset the scope, it should load up to 10 repos available on the instance.
- Modify the scope again.
- Create a new chat, it should load up to 10 repos available on the instance again.
> [Cody App] autoload repos into context on new chat and reset

- client/cody/CHANGELOG.md
- client/cody/package.json
- client/cody/src/editor/vscode-editor.ts
- client/cody/src/main.ts
- client/cody/src/services/StatusBar.ts
- client/cody/test/e2e/inline-assist-file-touch.test.ts
- client/cody/test/e2e/inline-assist.test.ts
- client/cody/walkthroughs/inline-assist.md
- doc/cody/client_feature_availability.md
As part of https://github.com/sourcegraph/sourcegraph/issues/53017 this renames "Inline Assist" to "Inline Chat"
- Run the automated tests
- Manually created inline chats, and tested fixups from chats
> Rename Cody Inline Assist to Cody Inline Chat

- .percy.yml
When running client integration tests, we create a new Percy build on a first `percySnapshot` call and upload snapshots as soon as they are taken. If a build fails because of a flake and an auto-retry is triggered, we create another Percy build and upload all snapshots again. This is the reason for the rising Percy costs since migrating to Bazel because the number of snapshots didn't change since then. See [this Slack thread](https://sourcegraph.slack.com/archives/C04931KQVRC/p1686911527274019) for more details. 
This PR defers Percy's build creation and snapshots upload until the test suite completion. No Percy build will be created if tests fail so that we can keep the auto-retry logic without changes.
CI
> ci: `percy` defer snapshots upload

- client/shared/src/testing/integration/context.ts
Our client integration tests are flaking quite a bit on the `driver.page.close()` call that's run after each test suite. After diving into Puppeteer's issues, it seems like this is a common hiccup. Apparently, Chrome is unreliable at consistently sending the page-close signal back to Puppeteer.
I dug around in the blame diffs, which slipped in the `page.close()` call, and didn't see any heavy-duty reasons for keeping it other than it being a good housekeeper — it leaves fewer tabs open, using less memory. So, I've removed the bit that throws when the `page.close()` call times out.
We're still shutting down the browser instance when a test suite wraps up, so we should be OK.
CI
> ci: do not error on `page.close()` timeout

- client/web/src/components/diff/FileDiffNode.tsx
- client/web/src/repo/commits/GitCommitNode.tsx
- client/web/src/repo/commits/GitCommitNodeTableRow.tsx
- client/web/src/repo/tree/TreePageContent.tsx
- client/web/src/repo/utils.tsx
Links to "Browse files @CID" will now directly go to the URL pointing to the CID instead of the Commit SHA.
- Tested manually
- Builds should pass
> client/web: Use perforce cid in tree URL

- client/cody/src/services/CodyMenus.ts
This removes the `ignoreFocusOut` for quick picks, which you really only want if you're supporting something that needs copy+pasting (i.e. an input in a multi-step flow). For everyone else, it just feels unnecessarily sticky/finicky. 
Before:
https://github.com/sourcegraph/sourcegraph/assets/153/6d225da3-3859-4762-867e-92a3ffeb61dc
After:
https://github.com/sourcegraph/sourcegraph/assets/153/d5a73260-767d-40cb-974f-fcb9d341dd95
- Open extension
- Click "Other Sign In Options…"
- Click outside the quickpick
> Cody for VS Code: Make signup quickpicks more easily dismissible

- client/cody/package.json
- client/cody/src/chat/ChatViewProvider.ts
- client/cody/src/services/FeedbackOptions.ts
- client/cody/src/services/StatusBar.ts
This removes the old Settings webview from being accessible, now that logout is done via the quickpick menu. This also improves some of the labelling and tooltips.
| - | - |
| <img width="242" alt="Screenshot 2023-06-24 at 12 29 05 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/b2070125-4747-42dc-962a-b7b473310542"> | <img width="236" alt="Screenshot 2023-06-24 at 12 43 14 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/0c1bc166-aa86-450f-822e-d6c18b851078"> |
| <img width="632" alt="Screenshot 2023-06-24 at 12 38 18 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/26aa0aa4-9f49-4613-881b-f26da38a4199"> | <img width="626" alt="Screenshot 2023-06-24 at 12 38 28 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/f7e6 …
> Cody for VS Code: Only show User Settings buttons in testing

- client/cody/src/chat/protocol.ts
- client/cody/src/services/CodyMenus.ts
Currently Cody App and Sourcegraph.com appear in the "previously used" list of sign in endpoints, but if you select them you are asked to enter an Access Token, which is confusing because that's not how you originally logged into these services. Logging into Cody App uses its own flow picking up the credentials from `app.json`, and Sourcegraph.com uses a callback style auth.
Given they already appear in other ways in the UI, this removes them from the previously used list.
Before:
https://github.com/sourcegraph/sourcegraph/assets/153/59e44283-4c72-4a2e-a733-d3a9aab57459
After:
https://github.com/sourcegraph/sourcegraph/assets/153/e0da267f-d4bc-4b86-b455-3fb381970692
- Open extension
- Login to sg dot com
- Logout
- See "Other Sign In Options…" menu
This doesn't fix people who have logged …
> Cody for VS Code: Remove Cody App and sourcegraph.com from previously used endpoints

- doc/cody/explanations/enabling_cody_enterprise.md
This makes some tiny changes to the docs for site-admins:
1. Use bullet points to make clear that there are 3 steps
2. Remove paragraph to say that embeddings can be configured, since they're enabled by default if `cody.enabled: true`
3. Make instructions consistent with others ("Go to", link style, ...)
4. Link to "Configuring embeddings" page
- Manual testing with `sg run docsite`
> cody docs: make setup process for admins clearer

- client/cody/src/services/FeedbackOptions.ts
- client/cody/src/services/StatusBar.ts
The statusbar quickpick menu is so tall that it doesn't fit on small screens, and it's so much text to parse. This simplifies it, so people can find what they need more quickly.
| Before | After | 
| - | - |
| <img width="618" alt="Screenshot 2023-06-26 at 5 01 03 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/481640e0-96b1-431a-820a-6bd026f377fc"> |  <img width="616" alt="Screenshot 2023-06-26 at 6 06 44 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/9c8a1560-901f-4690-afc9-c409ada885ce"> |
- Open extension
- Click Cody icon in statusbar
- Review quickpick items
> Cody for VS Code: Simplify the Cody status bar menu text

- enterprise/cmd/frontend/internal/guardrails/attribution/BUILD.bazel
- enterprise/cmd/frontend/internal/guardrails/attribution/attribution.go
- enterprise/cmd/frontend/internal/guardrails/attribution/attribution_test.go
- enterprise/cmd/frontend/internal/guardrails/attribution/observability.go
- enterprise/cmd/frontend/internal/guardrails/init.go
This adds traces, logs and metrics via the Operation abstraction. It is my first time using it, but I believe I am using it correctly. To use this we introduce a constructor which initializes the Operation for the attribution service.
Test Plan: go test and sg start and visiting the prometheus metrics.
Part of #53766 
Part of #52366
> guardrails: add observability for attribution

- dev/sg/internal/rfc/rfc.go
- dev/sg/internal/rfc/rfc_test.go
When running unit tests on my machine I would get an error dialog saying we can't open somewhere-far-away:11111.
Test Plan: go test -short ./... doesn't pop up a dialog anymore.
> sg: mock out open.URL

- internal/singleprogram/singleprogram.go
- sg.config.yaml
Code insights is not run in App so it can be safely disabled.  Improves initial startup time with fewer migrations to run.
`sg start app` app runs
build local release version - app runs
> App - disable code insights 

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/localapp/LocalAppInfo.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/localapp/LocalAppManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/localapp/LocalAppPaths.java
- client/jetbrains/src/main/java/com/sourcegraph/common/AuthorizationUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SourcegraphProjectService.java
- client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
- client/jetbrains/src/test/java/LocalAppManagerTest.java
~Fixes #53834~
Addresses most of #53834, the sidebar stuff + some other UX and other stuff will be added in a follow-up PR later.
This adds a third instance type for the local Cody App.
Only Macs are supported for now.
Make sure the app is running in the background when testing.
https://github.com/sourcegraph/sourcegraph/assets/18601388/88304210-d375-49d0-9c90-761efb844ff7
- some sanity-checks are included in the form of unit tests
- the local app setting should be greyed out if the app is not installed or if you're running on an unsupported platform (so not on Mac, for now)
- no access token should have to be set, the plugin should reuse the local app access token
- all API calls for Cody, including completions, chat and recipes should be done via the local app when enabled
> JetBrains: add basic integration with the local Cody app [WIP]

- client/web/src/enterprise/app/setup/steps/AppWelcomeSetupStep.module.scss
- client/web/src/enterprise/app/setup/steps/AppWelcomeSetupStep.tsx
This PR adds a special state to the welcome setup step right after connect to .com has been clicked. Previously users had to click the email verified button even if the email had been verified before. In this PR, you don't need to click anything and will be redirected automatically to the next setup step. 
https://github.com/sourcegraph/sourcegraph/assets/18492575/e5422a3b-ee5d-4f88-9068-e15f0907b6ad
- Check that the setup flow works properly if you have the email verified before you run the app
- Check that the setup flow works properly if you don't have your email verified before you run app
> Setup : Add auto-redirection UI to the welcome setup step

- doc/admin/deploy/docker-compose/upgrade.md
- doc/admin/deploy/docker-single-container/index.md
- doc/admin/deploy/kubernetes/helm.md
- doc/admin/deploy/kubernetes/upgrade.md
- doc/admin/updates/automatic.md
- doc/admin/updates/index.md
- doc/admin/updates/migrator/migrator-operations.md
Update docs related to MVU after Q2 work has completed. Fixes #51172 and #51170.
Docs update :)
> upgrades: Update docs

- dev/sg/sg_app.go
- doc/dev/background-information/sg/reference.md
Rename of the Sourcegraph App meant we had to update other places too
ran the command locally and it updated the `app.prod.update.manifest.json` in the `sourcegraph-app` bucket of the`sourcegraph` project
> sg / app: update command to use Cody App instead of Sourcegraph App

- lib/output/line.go
- lib/output/style.go
and make it a struct! Supersedes #54161.
Tested sg and stack locally.
> lib/output: Remove `Style` interface

- client/cody-shared/src/chat/recipes/explain-code-detailed.ts
- client/cody-shared/src/chat/recipes/explain-code-high-level.ts
- client/cody-shared/src/chat/recipes/file-touch.ts
- client/cody-shared/src/chat/recipes/find-code-smells.ts
- client/cody-shared/src/chat/recipes/generate-docstring.ts
- client/cody-shared/src/chat/recipes/generate-pr-description.ts
- client/cody-shared/src/chat/recipes/generate-release-notes.ts
- client/cody-shared/src/chat/recipes/generate-test.ts
- client/cody-shared/src/chat/recipes/git-log.ts
- client/cody-shared/src/chat/recipes/improve-variable-names.ts
- client/cody-shared/src/chat/recipes/next-questions.ts
- client/cody-shared/src/chat/recipes/optimize-code.ts
- client/cody-shared/src/chat/recipes/translate.ts
- client/cody-shared/src/prompt/truncation.ts
- client/cody/CHANGELOG.md
This PR closes #53920
Changes made:
1. Added warning message for each long truncated text
2. Fixed the args of token length for some of the recipes
Tested manually for long code snippets.
> Cody: Add warning message for recipes

- client/cody-shared/src/chat/recipes/generate-pr-description.ts
This PR is a minor fix for the PR description recipe. As I realised later, when you checkout from any other branch to a new branch, the `git log` command will carry all the commits not done by the current user and a long list of other user commits too. So, I updated the command to consider that.  I have tested these changes, and it works well now!
> Cody: PR description recipe fix

- cmd/gitserver/server/perforce/perforce.go
- enterprise/internal/batches/types/util.go
- internal/grpc/grpc.go
`ExperimentalFeatures` is not guaranteed to be non-nil. That can cause problems, especially in tests that don't mock the site config.
existing tests should still succeed
> Add nil checks on usages of ExperimentalFeatures

- enterprise/cmd/executor/internal/config/config.go
- enterprise/cmd/executor/internal/run/util.go
- enterprise/cmd/executor/internal/worker/command/kubernetes.go
Be able to load custom git certs when running with the single job option.
> executors: Use a custom git cert when cloning repos for the single job k8s option

- cmd/gitserver/server/server_grpc.go
Using the generated getters protects against the request itself being nil (which is possible since all fields are optional in protobuf 3).
Unit tests
> grpc: gitserver: use generated getters to access fields for archive

- cmd/gitserver/server/server_grpc.go
Using the generated getters protects against the request itself being nil (which is possible since all fields are optional in protobuf 3).
Unit tests
> grpc: gitserver: use generated getters to access fields for RepoCloneProgress

- cmd/gitserver/server/server_grpc.go
Using the generated getters protects against the request itself being nil (which is possible since all fields are optional in protobuf 3).
Unit tests
> grpc: gitserver: use generated getters to access fields for BatchLog

- client/cody/src/completions/logger.ts
- client/cody/src/testutils/mocks.ts
Closes #52687
This adds some logging to find enabled extension that match known completion providers so we can mark completions in these scenarios and exclude them from our top line metrics.
> Autocomplete: Log when another completion provider might be interfering

- client/cody-shared/src/hallucinations-detector/index.test.ts
- client/cody-shared/src/hallucinations-detector/index.ts
- client/cody/CHANGELOG.md
Fixes #54046
There was an issue in the regex because the first `fileRootPathCharacters` could pass as `/` which is obviously not a valid root directory name. This PR fixes that (although i think the whole regex could use some more love, I don't think they are encoding what I think they are doing very well?
Anyway, release coming up soon and this fixes the issue without regressing tests and seems relatively low risk. 🚢 
- added a test
- <img width="653" alt="Screenshot 2023-06-26 at 19 34 42" src="https://github.com/sourcegraph/sourcegraph/assets/458591/e5e15fe2-d48b-4419-9d51-6d95e6d04c1c">
> Cody: Ensure links are not matching hallucination detector logic

- enterprise/cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
Seems like chat can require instant: https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1687812777285669
n/a
> productsubscription/dotcomuser: allow users to use claude-instant for chat

- client/cody/CHANGELOG.md
- client/cody/package.json
- client/cody/src/configuration.test.ts
- client/cody/src/configuration.ts
- client/cody/src/main.ts
Closes #54132
Turn on autocomplete by default.
https://github.com/sourcegraph/sourcegraph/assets/458591/b6178fc0-c7a5-43e6-91f3-af89e00d95ec
> Autocomplete: Turn on by default

- client/cody/src/chat/ChatViewProvider.ts
- client/cody/src/chat/protocol.ts
- client/cody/src/services/AuthProvider.ts
- client/cody/webviews/App.tsx
- client/cody/webviews/Login.story.tsx
- client/cody/webviews/Login.tsx
Fix issue where cody would not sign users in with tokens returned from callback links due to the endpoint not being configured when token is returned.
Loom for fix: https://www.loom.com/share/27b874292c614f57b32142ec742fa069?sid=1ef5a8ef-9e89-427a-a225-845acf80693c
https://github.com/sourcegraph/sourcegraph/assets/68532117/5024a168-ca4a-4d1b-846b-03b9952bd850
> cody: fix callback redirect sign in

- client/cody/package.json
This feature is currently not on parity with the rest of the autocomplete logic so I thought it makes sense to mark it as experimental to make this clear. 
I've also removed it from the latest marketing video.
> Autocomplete: Mark panel view as experimental

- client/cody/src/completions/completion.test.ts
- client/cody/src/completions/shared-post-process.ts
- client/cody/src/completions/text-processing.ts
Closes #54145
This fixes a small regression from #53720 that we previously fixed by including the prefix in the comparison.
- Added a unit test
> Autocomplete: Fix truncation for matching next non-empty line

- client/web/src/integration/insights/create-insights.test.ts
This reverts commit 2390d5fa7a3a3d3d8121c0028c33fbbea89712ec.
- This root cause is addressed in https://github.com/sourcegraph/sourcegraph/pull/54117
- Closes https://github.com/sourcegraph/sourcegraph/issues/53767
CI
> Revert "flake: skip client integ test about codeinsights (#53768)"

- cmd/frontend/internal/httpapi/webhookhandlers/BUILD.bazel
- cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
- cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
- schema/schema.go
- schema/site.schema.json
Removes the checks for the `enablePermissionsWebhooks` flag so that the feature is enabled by default.
Just removes the checks that return nil if the feature is not enabled.
> Deprecate enablePermissionsWebhooks feature flag

- enterprise/internal/codeintel/policies/internal/store/configurations.go
I noticed that `lsif_configuration_policies_repository_pattern_lookup` has records of resolved repos for deleted policies
With this change we delete the resolved repos in `lsif_configuration_policies_repository_pattern_lookup` if the corresponding policy in 'lsif_configuration_policies' is deleted.
I considered adding a foreign key constraint to `lsif_configuration_policies_repository_pattern_lookup`, but the BackCompat tests failed because truncation (without CASCADE) doesn't work anymore.
- CI
- I created a policy and deleted it and verified that the entries for the resolved repos are deleted, too. I also verified that existing entries are not checked against the constraint.
> policies: clean up repository_pattern_lookup table

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessageContentCreatorFromMarkdownNodes.java
This fixes the issue when long text in the chat message wasn't wrapped and it was displayed somewhere outside of the view
closes #54125 
before:
now:
- Long words in the message are wrapped to new lines
> JetBrains: wrap long words in the chat message

- client/jetbrains/CONTRIBUTING.md
- client/jetbrains/build.gradle.kts
This disables the agent.
You can enable it with `-PenableAgent=true` when needed.
Some of our APIs were already using it, which caused some stability issues.
- green CI
- double check if the Cody chat isn't using the agent
> JetBrains: Disable the agent by default

- client/cody-shared/src/sourcegraph-api/completions/nodeClient.ts
- client/cody/CHANGELOG.md
- client/cody/src/chat/ChatViewProvider.ts
Closes #54256
Fix error handling when the client <> server connection is closed when sending chat messages.
https://github.com/sourcegraph/sourcegraph/assets/458591/c8852225-5c1f-41ec-bb0d-1e13c6c22db2
> Cody: Fix error handling in chat messages

- cmd/gitserver/server/run.go
io.Pipe provides a synchronous connection. So reading this commit we used to do io.Copy from r to progress. That means we can just replace any use of w with progress.
Test Plan: TestCloneRepo ensures we still write to progress. TestCloneRepoRecordsFailures ensures we still return summarized progress output.
Co-authored-by: @indradhanush
> gitserver: remove unnecessary Pipe in runRemoteGitCommand

- doc/cody/explanations/code_graph_context.md
- doc/cody/explanations/index.md
- doc/cody/explanations/indexing.md
- doc/cody/explanations/schedule_one_off_embeddings_jobs.md
- doc/cody/faq.md
This was missing from the docs. I also updated the parent page to clarify the difference between policies and one-off jobs.
Just a doc change
> cody docs: add page about one-off jobs

- client/web/src/cody/chat/CodyChatPage.tsx
We had a few reports that this link was appearing inside App. I can't see how `isCTADismissed` can be triggered from App but unsure if dated is shared from dotcom or if it can be preserved from older versions.
This change just guards to always ensure we don't show this link.
Related Slack discussion: https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1687861211915609
Tested locally
> App: Hide repetitive docs link

- doc/cody/explanations/code_graph_context.md
- doc/cody/faq.md
This adds a section to the FAQ and also documents some previously undocumented site config settings.
> cody docs: document why we skip files

- CHANGELOG.md
- enterprise/cmd/worker/internal/permissions/perms_syncer_scheduler_test.go
- enterprise/internal/database/perms_store.go
Previously, the `usersWithOldestPermsQuery` and `reposWithOldestPermsQuery` relied solely on the permission_sync_jobs table. If there was no row for the user or repo, this query would not return that user anymore.
This resulted in users/repos never being scheduled for a permission sync in cases when a job was not created previously (or jobs table was truncated).
Attempted to fix the queries by including those users/repos that do not have any record in the jobs table and putting these users/repos at the top of the queue.
unit test modified, tested locally
> [fix] perms jobs not being scheduled if there is not already a job

- client/cody-shared/src/chat/recipes/file-touch.ts
- client/cody/CHANGELOG.md
- client/cody/package.json
Closes #54254 
`cmd+shift+t` is used by VS Code to reopen the last file, we should use a different shortcut instead.
- also noticed that the recipe crashes when it tries to open non binary file (A `.DS_Store` in my example) so I fixed this too
> Cody: Change keyboard shortcut to avoid conflicts

- client/cody/walkthroughs/learn-more.md
Fixes #54231
https://github.com/sourcegraph/sourcegraph/assets/153/51141f30-3fa8-4cbc-8dfa-7d8dfd4dc700
- Opened the walkthrough
- Clicked "Learn More & Feedback"
- Verified video plays
> Cody VSCE: Add a demo of the pane header buttons to the walkthrough

- client/branded/src/search-ui/components/OwnerSearchResult.tsx
Part of #54209
Context:
- In Github all team names contain `/`
- So in case of github repo CODEOWNERS entries, if `@teamName/withForwardSlash` is seen, it's determined to be a team.
- But formerly in the front-end, all teams streamed from `select:file.owners` search were Sourcegraph teams
Bug:
- So all of these team names were linked to a teams page.
- Which in case of such a Github-repo CODEOWNERS entry that is determined to be a team, leads to linking to a team that does not exist on Code Search (so 404) 
Solution:
- Temporarily for 5.1 drop the link if the team name contains `/`
- This is safe because teams registered (so linked) do not contain `/` - it's not an allowed character
- All the other references from CODEOWNERS that are not resolved will be considered persons, and linking …
> Drop link from inferred github teams in select:file.owners

- enterprise/cmd/bundled-executor/README.md
- wolfi-images/bundled-executor.yaml
Requested by user to add `yq` to the bundled executor.
Checked the base image for yq.
> executors: Add yq to bundled executor

- enterprise/dev/ci/push_all.sh
The previous predicate to detect if our tag is a prod related one was failing to consider an ...-rc.X tag as being prod, leading to not pushing the tags to prod at all.
Test plan: used a regex tester to ensure it matches
Test script: 
```
BUILDKITE_TAG="v5.1.0-rc.5"
if [[ "$BUILDKITE_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(\-rc\.[0-9]+)?$ ]]; then
dev_tags+=("${BUILDKITE_TAG:1}")
prod_tags+=("${BUILDKITE_TAG:1}")
push_prod=true
echo $dev_tags
echo $prod_tags
else 
echo "NOPE"
fi
~ $ bash foo.sh 
5.1.0-rc.5
5.1.0-rc.5
```
> ci: detect rc releases as push-prod too

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/UpdatableChat.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ContentWithGradientBorder.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessageContentCreatorFromMarkdownNodes.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/RefreshCodyAppDetection.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyEditorFactoryListener.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/localapp/LocalAppManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/localapp/LocalAppPaths.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/ui/HtmlViewer.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
- client/jetbrains/src/main/resources/META-INF/plugin.xml
Show onboarding messages when cody app is not installed/running 
- When Cody app is not installed and user selected local app in the settings we should see information with the link to download Cody app
- When Cody app is installed but not running we should see the link to Open the Cody app
- Panel automatically changes when Cody app is closed/opened or installed
> JetBrains: Integrate plugin with Cody App

- client/web/src/components/gitHubApps/CreateGitHubAppPage.tsx
Closes [#54291](https://github.com/sourcegraph/sourcegraph/issues/54291)
While creating a GitHub app for Commit Signing, I noticed that clicking on the `Cancel` button redirects me to the GitHub Apps section for code host connections instead of the Batch Changes Admin settings page.
I've shared the walk through below.
I fixed that by introducing a `cancelUrl` variable to the `CreateGitHubAppPage` component, which depending on the GitHub app domain, switches where the cancel button should take the user to.
| Domain  | Cancel URL  |
|---|---|
| BATCHES   |   `/site-admin/batch-changes`  |
|  REPO |  `/site-admin/github-apps` |
* Navigate to the Batch Changes admin page `/site-admin/batch-changes`
* Create a commit signing integration for any code host
* Click on the `Cancel` button
* You …
> batches: update cancel url based on GitHub app domain

- enterprise/cmd/executor/internal/worker/command/kubernetes.go
Modify the repo's certs instead of the global. 
Test locally.
> executors: Set the ssl cert after repo creation and modify the repo's config

- client/web/src/enterprise/app/setup/steps/AppInstallExtensionsSetupStep.tsx
Removes the Beta label from VS Code extension and includes link to IntelliJ with experimental label
> App - update extension statuses

- client/cody-shared/src/chat/recipes/explain-code-detailed.ts
- client/cody-shared/src/chat/recipes/explain-code-high-level.ts
- client/cody-shared/src/chat/recipes/file-touch.ts
- client/cody-shared/src/chat/recipes/find-code-smells.ts
- client/cody-shared/src/chat/recipes/generate-docstring.ts
- client/cody-shared/src/chat/recipes/generate-pr-description.ts
- client/cody-shared/src/chat/recipes/generate-release-notes.ts
- client/cody-shared/src/chat/recipes/generate-test.ts
- client/cody-shared/src/chat/recipes/git-log.ts
- client/cody-shared/src/chat/recipes/improve-variable-names.ts
- client/cody-shared/src/chat/recipes/next-questions.ts
- client/cody-shared/src/chat/recipes/optimize-code.ts
- client/cody-shared/src/chat/recipes/translate.ts
- client/cody-shared/src/prompt/truncation.ts
This reverts commit e40e0d0f2c1336a039ca281c92a523a967596b46 (cc @deepak2431)
We noticed that there is some unexpected behavior in some recipes where this warning is shown even if only 5 lines of code are selected. It's probably because the context lines are truncated but we don't have time to look into this and fix it just yet (we were supposed to release a few hours ago 😓). We'll take a closer look after the release.
- It's a revert
> Revert "Cody: Add warning message for recipes (#54025)"

- enterprise/cmd/cody-gateway/internal/httpapi/BUILD.bazel
- enterprise/cmd/cody-gateway/internal/httpapi/diagnostics.go
- enterprise/cmd/cody-gateway/internal/httpapi/handler.go
- enterprise/cmd/cody-gateway/shared/config.go
Lately I've noticed many (most?) of our Sentry events come with `TraceId` that 404's on Cloud Trace, which kind of defeats the whole purpose of our tracing. I've spot-checked and see that all our traces in Cloud Trace have corresponding `Request` logs, but when attempting the inverse we often get a 404 in Cloud Trace.
I think the problem is that we are treating incoming traces as parents instead of linked traces. Treating the incoming request as a parent is cool because you get to see the whole thing end-to-end across projects, but it has the issue where half our traces are missing parents, and I think this is what causes logs to include traces that 404 when you query it on Cloud Trace
Was thinking of performing the parent/linking based on whether the request emits a ShouldTrace policy, …
> cody-gateway: treat incoming traces as links instead of parents

- internal/auth/userpasswd/handlers.go
Use new user ID for signup events instead of previous context ID
ensure tests pass
> Use new user ID for signup events instead of previous context ID

- client/cody-shared/src/codebase-context/index.ts
When an error happens during the local context, we need to handle it in the same way we do it for embeddings so we can bubble it up to the user.
https://github.com/sourcegraph/sourcegraph/assets/458591/52d4c13e-b1ce-4e65-aaf4-4f4146cf53f0
> Cody: Fix error handling for local context fetching

- cmd/frontend/codyapp/BUILD.bazel
- cmd/frontend/codyapp/latest_version.go
- cmd/frontend/codyapp/latest_version_test.go
Before, these two links (which are being added to marketing material, etc. as we speak):
* Mac (Apple Silicon): https://sourcegraph.com/.api/app/latest?arch=aarch64&target=darwin
* Mac (Intel): https://sourcegraph.com/.api/app/latest?arch=x86_64&target=darwin"
Would redirect to the `.tar.gz` download - not the `.dmg` Mac users will expect.
I'm positive this isn't the best way to implement this, I'm sure @burmudar will have a better idea later - I'll leave that to him :) But this works right now, and I've added test cases confirming it does so.. good enough?
Added tests
> app: fix download links not pointing to dmg

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
Fixes #54314 
Telemetry events should now be sent to both the current instance and to dotcom (unless the current instance is dotcom, or it's configured as an enterprise instance that's actually just dotcom).
- Green CI
- You can check the logs when a telemetry event should be sent to verify the behaviour.
> JetBrains: log telemetry events twice if not on dotcom instance

- client/web/src/auth/SignInPage.tsx
- client/web/src/auth/SignUpPage.tsx
- client/web/src/auth/components/ExternalsAuth.tsx
- client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
- client/web/src/get-cody/GetCodyPage.module.scss
Adds a `redirect` option to the `ExternalsAuth` component which can be used to specify a redirect page after a user signs-up successfully from specific locations.
> Add redirect option to external auth signup component

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
Internal error message is printed out to the logs instead of being displayed as a message
Steps to reproduce:
- Have Cody App selected as the server instance
- Have the Cody App running when you start the IDE
- Quit the Cody App
- Send another message in the chat
- Get these:
- I didn't find any context for your ask. I'll try to answer without further context.
- I'm sorry, I can't connect to the server. Please make sure that the server is running and try again.
No message with internal error should be shown to the user
> Don't display message with internal error when unable to load context

- internal/search/query/BUILD.bazel
- internal/search/query/helpers.go
- internal/search/query/helpers_test.go
This fixes a bug where we only match certain files, such as Dockerfile or BUILD.bazel, at root level when the user searches via the "lang:" filter EG "r:sourcegraph$ lang:bazel"
Background:
For some languages, linguist, and consequently go-enry, specifies files that don't match the language's extensions.
For example, for Starlark (alias of bazel), linguist lists the extensions .bzl and .star and a couple of special files such as `BUILD.bazel`. Note that ".bazel" is not listed as extension of Starlark.
However, our regexp pattern for the special files matches only files at root level.
This changes the regexp to be more permissive.
Cons:
- On the search page we now highlight a leading "/" for the new matches which is suboptimal. 
Test plan:
added unit test
> search: match lang specific files everywhere

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
Previous state:
- Inserts return char on ⏎
- Sends message on ⌃⏎ and ⌘⏎
New state:
- Sends message on ⏎
- Inserts a return char for ⌘⏎, ⇧⏎, ⌃⏎, and ⌥⏎.
Why change this?
- ChatGPT sends on ⏎
- Cody in VS Code sends on ⏎
- For me (@vdavid), a long-term IntelliJ user, sending on ⏎ comes naturally
- Other insiders were confused by this as well
Caveat:
- line breaks are not displayed in the sent messages. This was a pre-existing condition, not a regression. Created issue: https://github.com/sourcegraph/sourcegraph/issues/54330
Tested in this Loom: https://www.loom.com/share/9bd6fb2b5f7743dfa266cb74b76b1a7e
> JetBrains: Chat: Send on enter

- client/cody/CHANGELOG.md
- client/cody/src/services/AuthProvider.ts
This fixes `cody.customHeaders` so it's used instead of ignored. Reported by an Enterprise user who can no longer log into their instance, because the custom header isn't being passed.
After:
```
--> POST /.api/graphql?CurrentUser HTTP/1.1
--> Content-Type: application/json; charset=utf-8
--> Authorization: token a test token
--> Accept: */*
--> Content-Length: 89
--> User-Agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
--> Accept-Encoding: gzip,deflate
--> Connection: close
--> Host: localhost:3000
```
Before:
```
--> POST /.api/graphql?CurrentUser HTTP/1.1
--> x-test: test-test-test
--> Content-Type: application/json; charset=utf-8
--> Authorization: token a test token
--> Accept: */*
--> Content-Length: 89
--> User-Agent: node-fetch/1.0 …
```
> Cody VSCE: Fix customHeaders never being passed through

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ContextFilesMessage.java
Remove displayed duplicated file from "read" section in the chat
before: (duplicated readme.md entry)
now: no duplicates
- No duplicated entries should appear in the "Read" files section in chat
> remove displayed duplicated files from "read" section

- cmd/server/BUILD.bazel
- docker-images/prometheus/cmd/prom-wrapper/BUILD.bazel
- enterprise/cmd/server/BUILD.bazel
As a follow-up to https://sourcegraph.slack.com/archives/C04MYFW01NV/p1687904137730639 where @unknwon spotted a failure in the pure-docker test suite, I was ablet to root-cause the issues down to the prom-wrapper binary being built with `netgo` but with `cgo` enabled, which led to a weird case, where it still tried to nslookup with cgo and segfaulted. 
- 56c03276dd02f4873ec013f046d0453af456d816 fixes prom-wrapper 
- 7d6f928179d39bbed16f71bfa57b5a4d3e413100 conservatively disable cgo + enable netgo on the server, even if no issues have been observed so far. We might want to revisit this after the release. 
- Prom-wrapper QA: https://buildkite.com/sourcegraph/deploy-sourcegraph-docker/builds/13756
- CI (integration tests covered the server changes)
> bzl: fix build tags / disable cgo for server+prom 

- client/jetbrains/CHANGELOG.md
- client/jetbrains/README.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/localapp/LocalAppManager.java
- client/jetbrains/src/main/java/com/sourcegraph/config/CodyApplicationService.java
- client/jetbrains/src/main/java/com/sourcegraph/config/CodyProjectService.java
- client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
This removes the (hidden) overrides for the `instanceUrl` and `accessToken` with the `SRC_ENDPOINT` and `SRC_ACCESS_TOKEN` environment variables.
We had these to be able to quickly reuse the settings from [Sourcegraph CLI](https://docs.sourcegraph.com/cli) (as the CLI is configured with those).
I think we shouldn't rely on it anymore, since it may provide uneccessary complexity with debugging stuff for users who might have had the CLI on their machines before.
If we do want to reuse the values from these variables, it should probably be via another instance switch (next to the local app, dotcom and enterprise) instead of somewhat implicitly.
Note: I also removed some debug logs that don't seem necessary anymore.
- Having a configured Sourcegraph CLI locally shouldn't override the Cody …
> JetBrains: Remove Sourcegraph CLI's environment variable overrides

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/vcs/RepoUtil.java
This fixes the problem when user has git repository configured with https remote instead of ssh
This solves one of the problem why context was not available for some users https://github.com/sourcegraph/sourcegraph/issues/54353 
- Context from git repositories with different remotes than ssh should be correctly read from Cody app
> Read repository name form http/https remotes

- go.mod
- go.sum
Reverts sourcegraph/sourcegraph#54037
Test Plan: CI 
@keegancsmith @stefanhengl this broke `sg start` and only it because: 
- the automated PR doesn't bump deps.bzl, so bazel runs with the old version. 
- there is still code referencing the deleted funcs, see https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/search.go?L130
> Revert "zoekt: update to sourcegraph/zoekt@b9e6d9433e2e4438be6727ac3f1ae0a00e283220"

- cmd/frontend/internal/app/ui/router.go
The Go HTTP router needs to know that this page exists, or else it will return an HTTP 404, which will probably confuse search and OpenGraph clients and shows a brief 404 flicker in the browser tab title.
n/a
> fix HTTP 404 on /get-cody page

- client/web/src/enterprise/app/settings/local-repositories/LocalRepositoriesTab.module.scss
- client/web/src/enterprise/app/settings/local-repositories/LocalRepositoriesTab.tsx
- client/web/src/enterprise/app/setup/AppSetupWizard.module.scss
- client/web/src/enterprise/app/setup/steps/AppLocalRepositoriesSetupStep.module.scss
| Setting page | Setup flow |
| ---------- | ---------- |
| <img width="1041" alt="Screenshot 2023-06-28 at 12 15 43" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/3624b630-e6ba-4d79-ab4d-a33b9fd86a7a"> | <img width="1052" alt="Screenshot 2023-06-28 at 12 24 39" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/9e4a86e8-48aa-4ea4-a43c-15d7ec4c8c56"> |
- Check that local repositories UI works properly (shows wrapped names of repositories and their filenames) 
- Check local repositories UI in the setup flow and on the setting page
> Setup: Fix local repositories UI overflow problem

- client/web/src/get-cody/GetCodyPage.tsx
This page actually describes what you get. The demo page currently shows a Code Search video.
This page is pending merge at https://github.com/sourcegraph/about/pull/6344. The link does not currently work, but it will by the time this is deployed.
n/a
> link "Get Cody for Enterprise" to Cody pricing, not demo page

- client/web/dev/esbuild/build.ts
Follow up for https://github.com/sourcegraph/sourcegraph/pull/53962
In https://github.com/sourcegraph/sourcegraph/pull/53962 we added woff2 font, but we don't have any loader in esbuild for `.woff2` files. This pr simply adds it. 
CI is green
> Add file loader for woff2 fonts

- enterprise/cmd/cody-gateway/shared/tracing.go
In Sourcegraph we use debug-level for this error handler by default as well. Reduces error noise in local dev.
n/a
> cody-gateway: downgrade OTEL errors to debug

- enterprise/cmd/frontend/internal/dotcom/productsubscription/licenses_graphql.go
This is required for upcoming Cloud automation: https://github.com/sourcegraph/controller/pull/805
Currently we can't do the lookup:
```
ERROR mi2.instance.check.enforce.Enforce.cody mi2/instance.go:511 error encountered {"TraceId": "03e4d62c01a89c6a62e5d2e8f1cb6df6", "SpanId": "98bf6654fdf74de6", "environment": "prod", "instance": "src-96ed006bb45d673944e4", "error": "GetEmbeddingsIndexerToken: getSubscription: GetProductSubscriptionByLicense: input: dotcom.productLicenses must be site admin"}
```
unit tests on the `serviceAccountOrSiteAdmin` helper
> dotcom/productsubscription: allow SA to do license key lookup

- internal/gitserver/addrs.go
- internal/gitserver/client.go
Discovered locally when trying to request commits for multiple repos. In the gRPC branch of `ClientForRepo` we pass `repoName`, which was constructed with an explicit note that it's ONLY used for tracing (called in the `do` method). This messes up the calculation for an address and we end up not reaching out to any relevant shards.
This method is constructed in such a way that each set of repo names belong to the same gitserver shard, so we can take the first item from the set to calculate the repository name.
**Note**: This may cause partial code intelligence result sets when there are multiple repositories in the same shard per page of results.
> gitserver: Fix arguments to `ClientForRepo` in `BatchLog`

- enterprise/cmd/batcheshelper/main.go
- enterprise/cmd/batcheshelper/run/post.go
- enterprise/cmd/batcheshelper/run/post_test.go
- enterprise/cmd/executor/internal/worker/command/kubernetes.go
- enterprise/cmd/executor/internal/worker/command/kubernetes_test.go
- enterprise/cmd/executor/kubernetes/batches/executor-batches.Deployment.yml
When running a single job, do not need to add the directory as safe.
Updated tests and ran locally.
> executors: Handle single job and not needing to run the safe git command

- client/completions-review-tool/tsconfig.json
- client/web/src/integration/BUILD.bazel
- Re-enables client integration tests in Bazel
- Removes comment from the `tsconfig.json` file, which resulted in a warning when running `bazel configure`
CI
> ci: enable client integration tests

- client/jetbrains/CHANGELOG.md
- client/jetbrains/build.gradle.kts
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/HumanMessageToMarkdownTextTransformer.java
- client/jetbrains/src/test/java/URLBuilderTest.java
- client/jetbrains/src/test/java/com/sourcegraph/cody/chat/HumanMessageToMarkdownTextTransformerTest.java
When sending a message with new lines they're preserved in the chat message
Added AssertJ assertions to the unit tests to have better error messages on failed tests, and unit tests are now enabled on CI
- Send a message with new line and the message should be displayed with new line in the chat
before:
https://github.com/sourcegraph/sourcegraph/assets/7345368/b19bc261-5346-4567-9882-445495c41c96
after:
https://github.com/sourcegraph/sourcegraph/assets/7345368/8e8b2a53-457e-4355-8c19-cc5b149ed671
> JetBrains: preserve new lines in the human chat message

- client/cody-shared/src/chat/transcript/messages.ts
- client/cody-ui/src/Chat.tsx
- client/cody-ui/src/chat/Transcript.tsx
- client/cody-ui/src/chat/TranscriptItem.tsx
- client/cody/src/chat/ChatViewProvider.ts
- client/cody/src/chat/protocol.ts
- client/cody/webviews/Chat.module.css
- client/cody/webviews/Chat.tsx
This adds three recipes to the welcome chat message in VScode to help users get started. Fixes issue #54232 .
Open Cody. A new chat now has buttons. Clicking the buttons starts those recipes.
> Cody: Add some recipes buttons to the welcome message

- dev/backcompat/defs.bzl
- dev/backcompat/flakes.bzl
- dev/backcompat/patches/BUILD.bazel
- dev/backcompat/patches/ui_assets.patch
- dev/backcompat/test_release_version.bzl
- enterprise/dev/ci/internal/ci/bazel_operations.go
This PR moves the target release for back compat tests to 5.1 and fixes the various issues that arose. 
- We don't need to handle otel breaking updates, as 5.1 and HEAD are on the same version
- We now need to explicitly remove `/client/*` as we're properly targeting the `v5.1.0` tag and it doesn't contain my crude patches anymore 
- Bumped pinned back compat scip deps, as it frequently breaks due to having a lot of API changes across time 
- Added a new patch, to handle the consequences of having removed the client tree: previous release didn't have the refactored ui/assets explicit oss/enterprise targets and thus didn't explicitly depend on the client. Now we do, so it needed some patching to make the build working. 
- The buildkite command itself now substracts a few steps that are not …
> bzl: bump backcompat to target 5.1.0

- cmd/frontend/internal/httpapi/httpapi.go
- cmd/frontend/internal/httpapi/search.go
- deps.bzl
- dev/backcompat/defs.bzl
- go.mod
- go.sum
- internal/search/backend/metered_searcher.go
This endpoint was unused which was why it was removed in Zoekt. The changes from Zoekt included in this dep bump:
- https://github.com/sourcegraph/zoekt/commit/1686b50d50 indexserver: remove unused GetRepoRank
- https://github.com/sourcegraph/zoekt/commit/7078a585a9 shards: populate RepoList.Stats.Repos
- https://github.com/sourcegraph/zoekt/commit/b9e6d9433e zoekt-indexserver: Check stderr for git fetch
- https://github.com/sourcegraph/zoekt/commit/93f7b0c983 matchtree: capture Stats before pruning
- https://github.com/sourcegraph/zoekt/commit/7643f3b313 matchiter: capture metric NgramLookups
Test Plan: CI
> search: update zoekt with removal of RepositoryRankRequest

- enterprise/cmd/cody-gateway/internal/actor/source.go
- enterprise/cmd/cody-gateway/shared/config.go
- enterprise/cmd/cody-gateway/shared/main.go
- sg.config.yaml
These actor sources require additional setup to function (https://docs.sourcegraph.com/dev/how-to/cody_gateway) - if you don't care (dev-private points to the managed dev instance by default) this is just error noise on the dotcom run set, so unless a dotcom token is set we disable these sources entirely.
```
[   cody-gateway] ERROR cody-gateway.sourcesSync goroutine/periodic.go:395 operation.error {"TraceId": "f243edc2964770e6a886e4d95c09baa3", "SpanId": "fca7eb444071c1c0", "count": 1, "elapsed": 0.022313334, "error": "failed to sync dotcom-product-subscriptions: failed to list subscriptions from dotcom: returned error 401 Unauthorized: Invalid access token."}
```
With new defaults:
```
[   cody-gateway] WARN cody-gateway shared/main.go:96 CODY_GATEWAY_DOTCOM_ACCESS_TOKEN is not set, …
```
> cody-gateway: do not enable dotcom actor sources if no token is set

- enterprise/cmd/cody-gateway/internal/notify/BUILD.bazel
- enterprise/cmd/cody-gateway/internal/notify/rate_limit.go
- enterprise/cmd/cody-gateway/internal/notify/rate_limit_test.go
- enterprise/cmd/cody-gateway/shared/config.go
- enterprise/cmd/cody-gateway/shared/main.go
- internal/codygateway/types.go
As App usage of Gateway ramps up, we are expecting a _lot_ of actors to hit their rate limits. This is already causing a lot of noise in the channel. This change retains the previous notification thresholds for product subscriptions, but disables them entirely for other actor sources for now.
Env-based config is probably too brittle for this granularity so I think we should just hardcode it.
Thread: https://sourcegraph.slack.com/archives/C05BWKQB0R1/p1687904578368609
Unit tests
> cody-gateway: hardcode notification thresholds per actor source

- src-tauri/src/tray.rs
Adds a check for updates to the system tray so users can manually check for updates.  Tauri itself only checks during app start.
set dev version to `2023.6.25`  in tauri.dev.conf.json
`sg start app` no when prompted for update
Use the manual check option in system tray and see update prompt.
> App - add manual check for updates

- client/cody-shared/src/codebase-context/index.ts
- client/cody-shared/src/codebase-context/messages.ts
- client/cody/src/chat/ChatViewProvider.ts
This includes an additional field in the event payload when a user clicks on the thumbs up/thumbs down button. The field is a boolean "lastChatUsedEmbeddings" which is true if any of the context files came from embeddings.
I am unsure if this is the best approach to add this. I augmented the ContextFile interface to optionally specify a source. I then in the only place we directly use embeddings I set the source field. Other sources will not populate this field (yet). Note: things like the unified fetcher do not set this, which we may want to follow up on.
Note that the current implementation of feedback will just send the full latest transcript, no matter which message a user clicked on. As such we only base embeddings use on the last message. This is a limitation in the existing …
> cody: log if embeddings were used in feedback

- client/cody/CHANGELOG.md
- client/cody/src/chat/ChatViewProvider.ts
Closes #54427
During context fetching if we abort the request before we ever got a response from the server, we get a message with the text `socket hang up` in addition to the `aborted` error when responses are always streaming in.
With the recent changes from me to properly bubble up context fetching errors, these messages became visible in some unintended ways:
This PR fixes the issue by handling both `abort` and `socket hang up` messages.
- tested locally with both indexed and unindexed repos. Just send a message and press abort.
> Cody: Do not flicker error messages when aborting during context fetching

- client/cody/CHANGELOG.md
- client/cody/package.json
This pr adds "find code smells" recipe to editor context menu and to command pallette as it wasn't previously added when the recipe was added to the recipes section in the chat, according to the conversation with @vdavid 
- Find code smells recipe should be available in command pallette and in the editor context menu
> Cody: Add find code smells recipe to context menus

- .bazeliskrc
Suppresses the incorrect syntax error warning span when running `bazel configure`
https://github.com/aspect-build/aspect-cli/releases/tag/5.5.4
Ran `bazel configure` locally and observed no more spam from treesitter
> build: update to Aspect CLI 5.5.4

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ActionUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/BaseRecipeAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ExplainCodeDetailedAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ExplainCodeHighLevelAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/FindCodeSmellsAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/GenerateDocStringAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/GenerateUnitTestAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ImproveVariableNamesAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/OptimizeCodeAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SummarizeRecentChangesRecipe.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/TranslateToLanguageAction.java
- client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
- client/jetbrains/src/main/resources/META-INF/plugin.xml
Some recipes are now available as a context menu items in the editor
- Open editor, select some code and execute all the actions available under the "Cody" menu element
> JetBrains: Register some recipes as context menu actions in editor

- client/web/src/enterprise/codeintel/configuration/components/EmptyPoliciesList.module.scss
Fixing the Safari layout issue [reported](https://sourcegraph.slack.com/archives/C01NKL6V7E2/p1687980195563189) by the customer.
1. In Safari, navigate to [https://sourcegraph.test:3443/site-admin/code-graph/configuration](https://sourcegraph.test:3443/site-admin/code-graph/configuration) and ensure that UI is OK.
> web: fix code-intel layout in Safari

- client/web/BUILD.bazel
- cmd/frontend/internal/app/updatecheck/handler.go
- cmd/migrator/BUILD.bazel
- cmd/migrator/generate.sh
- doc/admin/deploy/docker-compose/aws.md
- doc/admin/deploy/docker-compose/azure.md
- doc/admin/deploy/docker-compose/digitalocean.md
- doc/admin/deploy/docker-compose/google_cloud.md
- doc/admin/deploy/docker-compose/index.md
- doc/admin/deploy/docker-single-container/aws.md
- doc/admin/deploy/docker-single-container/digitalocean.md
- doc/admin/deploy/docker-single-container/google_cloud.md
- doc/admin/deploy/docker-single-container/index.md
- doc/admin/deploy/kubernetes/helm.md
- doc/admin/deploy/machine-images/gce.md
- doc/admin/executors/deploy_executors_kubernetes.md
- doc/admin/external_services/postgres.md
- doc/admin/external_services/redis.md
- doc/admin/http_https_configuration.md
- doc/admin/ssl_https_self_signed_cert_nginx.md
- doc/admin/updates/docker_compose.md
- doc/admin/updates/pure_docker.md
- doc/admin/updates/server.md
This pull request is part of the Sourcegraph 5.1.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54459)
> release: sourcegraph@5.1.1

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/vcs/RepoUtil.java
Load first repository from the project when no file is opened in the editor
closes #54346 
- Open project with a git repository, close all files opened in the editor and ask Cody about the project, context should be provided because the repository should be selected from the first git repository available in the project
https://github.com/sourcegraph/sourcegraph/assets/7345368/f92d854e-b0c4-4ec9-9246-fce5a5669bd0
> JetBrains: load first repository from the project if no file open

- client/web/src/cody/sidebar/Provider.tsx
- client/web/src/repo/RepoContainer.tsx
Bug report: https://sourcegraph.slack.com/archives/C03CSAER9LK/p1687966684496949
The issue was the whole sidebar store getting updated due to resize. 
- resize cody sidebar
> Fix Cody Sidebar Resize Flicker

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/website/CopyAction.java
- client/jetbrains/src/main/java/com/sourcegraph/website/FileActionBase.java
closes: #54332 
- When Cody App is selected as the instance type link opening and sharing options on Sourcegraph should not be available to run
Uploading Screen Recording 2023-06-30 at 09.43.15.mov…
> JetBrains: disable link sharing when working with Cody app

- doc/admin/external_service/azuredevops.md
Add screenshots to make this obvious.
Doc page now looks like: 
(Note first screenshot is bit too large and needs another highlight around the icon in the menu bar, I'm reuploading the image to the assets bucket as soon as the current one is deletd by tech-ops, as I don't have permissions, but for the time being this should work)
Doc change only.
> doc/admin: Clarify importance of all accessible orgs for ADO

- BUILD.bazel
- dev/linters/go.mod
- dev/linters/go.sum
- dev/linters/gocheckcompilerdirectives/BUILD.bazel
- dev/linters/gocheckcompilerdirectives/gocheckcompilerdirectives.go
- dev/sg/internal/generate/golang/golang.go
- dev/sg/linters/go_checks.go
- dev/sg/linters/linters.go
- linter_deps.bzl
This removes the linter that checks for incorrectly formatted `go:generate` directives from `sg lint` and replace it with a proper linter handled by `nogo`. 
Locally tested + CI
> bzl: port go compiler directives linter from sg lint to nogo

- enterprise/dev/ci/internal/ci/bazel_operations.go
This moves the `//client/web:bundle` target to be built first, in isolation. Dependending on how Bazel schedules things, we've observed a few OOM crashes when building it since yesterday. 
This should bring more stability, until @valerybugakov modularizes the frontend and we can say goodbye to this huge target once for all :) 
It won't affect PRs with no client changes, because caching, PRs with client code might be a tad slower, but it's always better than crashing and retrying.
> bzl: build //client/web:bundle in isolation first

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/api/GraphQlClient.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CodyCompletionsManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/CompletionsProviderType.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/UnstableCodegenLanguageUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/CodyCompletionItemProvider.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/completions/prompt_library/UnstableCodegenEndOfLineCompletionProvider.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/localapp/LocalAppManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/IntelliJTextDocument.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/TextDocument.java
- client/jetbrains/src/main/java/com/sourcegraph/config/UserLevelConfig.java
- client/jetbrains/src/test/java/com/sourcegraph/cody/completions/UnstableCodegenLanguageUtilTest.java
Fixes #53973
given the following `~/sourcegraph-jetbrains.properties`:
```props
cody.completions.advanced.provider = unstable-codegen
cody.completions.advanced.serverEndpoint = http://localhost:3001/batch
```
when running a mock server with:
```bash
cd client/cody && pnpm ts-node ./scripts/mock-server.ts
```
You will be able to get the mock completion with the plugin (screenshot below).
- included some unit tests for `languageId` detection
- test against the mock server (as described)
- test against the live backend
> JetBrains: unstable codegen support

- client/web/src/repo/RepoContainer.tsx
- client/web/src/repo/RepoRevisionContainer.tsx
- client/web/src/repo/repoRevisionContainerRoutes.tsx
- Testing an alternative solution to https://github.com/sourcegraph/sourcegraph/issues/54389
- The `works with spaces in the repository name` client integration test failed when we tried this approach half a year ago. This problem was either fixed in react-router, or the removal of the compat router helped.
- Closes https://github.com/sourcegraph/sourcegraph/issues/54389
CI
> web: drop repo splat in favor of the repo name

- .gitignore
- BUILD.bazel
- dev/backcompat/patches/ui_assets.patch
- ui/assets/enterprise/BUILD.bazel
- ui/assets/oss/BUILD.bazel
Because we at least need one file to be present or the embed won't work, this replaces CHANGELOG.md by CONTRIBUTING.md as a placeholder. This will prevent PRs updating the changelog from invalidating the cache for nothing for these slow targets. 
Follow-up to https://github.com/sourcegraph/devx-support/issues/39
CI
> bzl: avoid ui/assets/* dep on CHANGELOG.md

- CHANGELOG.md
- internal/database/external_services_test.go
- schema/BUILD.bazel
- schema/bitbucket_cloud.schema.json
- schema/validation_test.go
The regular expression used in matching the exclusion by UUID in Bitbucket.org (Cloud) code host connection was unsupported by [AJV](https://ajv.js.org/), which was added for validation purposes in https://github.com/sourcegraph/sourcegraph/pull/52012.
The problem surfaced in an ugly way as an uncaught error that prevented the loading of create/edit code host UI for Bitbucket Cloud, which schema contained the invalid regex.
The issue was reported in Slack: https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1688132947851839.
Customers using Bitbucket.org (Cloud) are unable to create new or edit existing code host connections.
AJV JSON schema validator treated the escaped `-` sign as invalid. Removing the escaping from it fixed the problem.
Test plan:
Local sg run and verify that Bitbucket …
> fix Bitbucket Cloud exclude regex to make it work with AJV.

- doc/admin/config/batch_changes.md
Since we cannot reproduce and can't confirm if there was an issue with the PAT on S2, we can remove this.
N/A
> remove known commit signing bug

- client/jetbrains/src/main/java/com/sourcegraph/cody/context/embeddings/EmbeddingsSearcher.java
- Fixes https://github.com/sourcegraph/sourcegraph/issues/54472
Sourcegraph 5.0.5 responded with null data to this request, which we didn't expect, but we do now.
Tested it with 5.0.5 locally. [1-min Loom](https://www.loom.com/share/0d5d3b35ae6a48c7894e88d5a39a22ce?sid=d58d4f22-5eda-4a30-b850-41b9470707bc)
> JetBrains: Handle embedding checking response == null

- client/web/src/global/GlobalAlerts.tsx
When returning from dotcom connection the page would display a red warning regarding cody being enabled but without a global embeddings policy.
In app the policy gets auto created after the users adds repos.  This disables the warning on app.
resolves https://github.com/sourcegraph/sourcegraph/issues/54495
Made release build
verified no red flash
https://github.com/sourcegraph/sourcegraph/assets/6098507/7e526eea-b16a-4908-a94a-05075b868080
https://github.com/sourcegraph/sourcegraph/assets/6098507/784bbc90-8fac-4b8c-8030-dbcdbd2b85dd
> App - remove embeddings policy warning during setup

- client/web/src/enterprise/cody/configuration/pages/CodyConfigurationPage.tsx
- client/web/src/site-admin/SiteAdminConfigurationPage.tsx
Some docs links in the settings section navigated away from settings. It would be best to open these in a new window so the user can view them without losing their place in settings.  This also resolves an issue in app where allowing it to link out to the documentation.
resolves https://github.com/sourcegraph/app/issues/24
`sg start app` validated that links open to correct page in a new window.
`sg start` validated that links open in new tab
> App - open doc links in settings in new windows

- internal/singleprogram/singleprogram.go
Write the os and arch in addition to the version number at startup, this information is useful when debugging startup issues. 
`sg start app` view output
```
✱ Sourcegraph App version: 0.0.0+dev darwin arm64
```
> App - add os and arch info during startup log message

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
When no context found for user query we will display more informative message that can help user fix his problems with context
- Configure Cody to use dotcom but open project which is not indexed by dotcom and ask Cody something. Cody should respond with
>
> JetBrains: display more informative message when no context found

- WORKSPACE
- deps.bzl
In 2f7ae0988f5 @efritz updated `scip` in `go.mod`, but he forgot to run `bazel run :gazelle-update-repos`. This PR fixes this. 
@efritz it's really easy to miss this, I'll try finding a quick fix so it doesn't happen anymore 🙏 
CI
> bzl: update deps.bzl (go.mod update was not reflected)

- doc/own/index.md
Test plan:
N/A, only a doc change.
Closes https://github.com/sourcegraph/sourcegraph/issues/53655
> own: add an example of a query to find commits in given release for given owner.

- cmd/frontend/internal/app/ui/router.go
This has been bugging me for a while. The 404 errors come from the backend before the frontend takes over.
You could see `frontend` also logging errors:
```
[frontend] t=2023-07-03T08:50:34+0000 lvl=eror msg="ui HTTP handler error response" method=GET request_uri=/cody/MjAyMy0wNy0wM1QwNzo0MzowMS4xODNa status_code=404 error="repo not found: name=\"cody/MjAyMy0wNy0wM1QwNzo0MzowMS4xODNa\"" error_id=wt7u7W trace=
```
That means for every `/cody` requests we'd try to find a repository.
This here fixes the error by defining 2 routes:
- `/cody`
- `/cody/{chatID}`
And handling them correctly.
https://github.com/sourcegraph/sourcegraph/assets/1185253/468abf97-9ae5-47f2-9744-145b6bff3184
https://github.com/sourcegraph/sourcegraph/assets/1185253/ea2a62d8-8a31-41be-a88c-5cc788262296
- `sg start`
- …
> cody web: fix 404 errors when loading /cody

- dev/oci_deps.bzl
- wolfi-images/batcheshelper.yaml
- wolfi-images/bundled-executor.yaml
- wolfi-images/node-exporter.yaml
- wolfi-images/postgres-exporter.yaml
- wolfi-images/server.yaml
Update postgres-exporter and node-exporter to latest versions.
The current version of postgres-exporter seems to cause a [non-critical error](https://sourcegraph.slack.com/archives/C02E4HE42BX/p1688168678260469?thread_ts=1688063676.565389&cid=C02E4HE42BX) which is fixed in 0.12.1, so also backporting. 
TODO:
- CI
- Testing on S2
> Update prometheus tools

- deps.bzl
In 2f7ae0988f5 @efritz updated `scip` in `go.mod`, but he forgot to run `bazel run :gazelle-update-repos`. This PR fixes this.
@efritz it's really easy to miss this, I'll try finding a quick fix so it doesn't happen anymore 🙏
Backport 59a7bafd321cdd344f5954e0e22f12df10870bdd from https://github.com/sourcegraph/sourcegraph/pull/54521
CI
> [Backport 5.1] bzl: update deps.bzl (go.mod update was not reflected) (#54521)

- client/web/src/enterprise/own/OwnPage.tsx
- client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.tsx
- client/web/src/enterprise/own/admin-ui/OwnStatusPage.tsx
- client/web/src/nav/GlobalNavbar.tsx
- client/web/src/site-admin/sidebaritems.ts
- doc/own/codeowners_format.md
- doc/sidebar.md
Test plan:
| :-- | :-- |
| <img width="472" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/94846361/4570e5c3-a898-4b0a-b1a2-086cf4294301"> | <img width="472" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/94846361/15605998-e994-45b0-aec7-5a604620f17f"> |
| <img width="472" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/94846361/a61320d8-7323-4d10-9d0d-52c6aeca593d"> | <img width="472" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/94846361/0c4eb1eb-750f-43bb-9c7c-cf8ddf269500"> |
> own: remove forgotten "Own" references in favor of "Code ownership".

- cmd/gitserver/server/vcs_syncer_go_modules.go
- cmd/gitserver/server/vcs_syncer_jvm_packages.go
- cmd/gitserver/server/vcs_syncer_npm_packages.go
- cmd/gitserver/server/vcs_syncer_python_packages.go
Many dependency archives include duplicate files, we should set the flag to skip em to reduce some errors :fist_oncoming: 
N/A flipping a switch that is already tested and proven
> packages: skip duplicates when extracting

- enterprise/cmd/embeddings/shared/main.go
Just removing a redundant error check that my linter was complaining about.
It builds.
> Chore: remove redundant err check

- dev/sg/internal/run/run.go
This removes an extra `semaphore.Release` (it's already deferred in that function) that was causing a panic locally in `sg` and misleading me on the underlying cause.
This no longer panics on error.
> sg: remove extra semaphore release

- client/web/src/enterprise/insights/components/creation-ui/code-insight-time-step-picker/get-interval-descrtiption-text/get-interval-description-text.tsx
On some browsers Intl.ListFormat does not exist and causes the page to error.  This appears to be an issue on some linux versions and older macos versions.
resolves https://github.com/sourcegraph/sourcegraph/issues/54301
`sg start enterprise-codeinsights` - ensure that creation screen units display correctly
`sg start app` ensure embeddings jobs load
open dev tools and set int.ListFormat to null
verify app and code insights still loads and display a comma separated list such as `One year, two months`
> App/Insights: provide fallback for Intl.ListFormat

- dev/gqltest/bitbucket_projects_perms_sync_test.go
Let's see how CI behaves here.
Originally skipped in #52057. 
Closes #54475.
CI and main-dry-run.
> dev/gqltest: Unskip bitbucket project perms tests

- client/web/src/enterprise/site-admin/cody/RepoEmbeddingJobNode.tsx
With this change we update the estimate of "time to finish" on **Cody > Embeddings Jobs** without requiring the user to refresh the page.
The video runs 15x faster. Previously, the reported files changes, but not the "Expected time to finish"
https://github.com/sourcegraph/sourcegraph/assets/26413131/d0bca405-8a2d-4260-990b-202b8fb44fc4
Visual inspection
> cody admin: update estimated time to finish

- enterprise/dev/ci/internal/ci/bazel_operations.go
- enterprise/dev/ci/internal/ci/operations.go
- enterprise/dev/ci/internal/ci/pipeline.go
- testing/BUILD.bazel
Re-enable code-intel-qa, marked as flaky, on `main` branch only. 
CI
> bzl: re-enable code-intel-qa (only on main)

- cmd/repo-updater/repoupdater/server.go
- cmd/searcher/internal/search/search.go
- internal/search/client/BUILD.bazel
- internal/search/client/client.go
- internal/search/job/jobutil/limit.go
- internal/search/repos/repos.go
- internal/search/searchcontexts/BUILD.bazel
- internal/search/searchcontexts/search_contexts.go
- internal/search/searcher/client.go
- internal/search/zoekt/indexed_search.go
- internal/trace/trace.go
This removes the `LazyPrintf` method on `trace.Trace`. This method existed because of `x/net/trace`, but now we can just use `AddEvent` instead. It's not quite as ergonomic, but it provides more readable span events (they're not named `LazyPrintf`) and helps discourage adding massive payloads to a span.
This is another step towards standardization on OpenTelemetry.
Stacked on https://github.com/sourcegraph/sourcegraph/pull/54563
CI.
> Tracing: remove LazyPrintf

- enterprise/cmd/worker/internal/executors/BUILD.bazel
- enterprise/cmd/worker/internal/executors/multiqueue_cache_cleaner.go
When App was running and there were no executor queues there was a constant flow of errors being logged 
```
ERROR multiqueue-cache-cleaner.multiqueue.cachecleaner.metrics executors/multiqueue_cache_cleaner.go:95 Failed to get cache size {"queue": "codeintel", "error": "redigo: nil returned"}
ERROR executors.multiqueue-cache-cleaner goroutine/periodic.go:95 An error occurred in a background task {"handler": "executors.multiqueue-cache-cleaner", "error": "multiqueue.cachecleaner: redigo: nil returned"}
```
Redis reporting that the key does not exist should not throw an error but behave like the value is 0.
existing unit tests pass
`sg start app` errors no longer present
> silence errors when redis is reporting key does not exist

- dev/ci/runtype/runtype.go
- doc/dev/background-information/bazel/cookbook.md
- doc/dev/background-information/bazel/index.md
- doc/dev/background-information/ci/reference.md
- doc/dev/background-information/sg/reference.md
- enterprise/dev/ci/gen-pipeline.go
- enterprise/dev/ci/internal/ci/BUILD.bazel
- enterprise/dev/ci/internal/ci/bazel_operations.go
- enterprise/dev/ci/internal/ci/bazel_operations_test.go
- enterprise/dev/ci/internal/ci/pipeline.go
This introduces the `bazel-do` runtype, which provides a `bazel-do/[name]` branch scheme, where you can pass in the commit description a bazel command to be run. 
Diagnosing flaky tests, or simply testing something in CI can a bit cumbersome if you don't know your way around the pipeline. This PR fixes that by providing a way to set-up a build for your branch that will run a single bazel command and nothing else. 
Classic use cases can be: 
- diagnosing a flaky test
- just testing something and you want the faster builds from the CI 
- ensuring that your new code builds remotely without having to wait for the whole build. 
How to use: create a `bazel-do/my-thing` branch and put `!bazel test //something` in the last commit description. 
I plan to follow up with a `bazel ci bazel test …
> ci: introduce a bazel-do runtype to run user given bazel commands only

- enterprise/cmd/cody-gateway/internal/actor/limits.go
- enterprise/cmd/cody-gateway/internal/httpapi/BUILD.bazel
- enterprise/cmd/cody-gateway/internal/httpapi/completions/upstream.go
- enterprise/cmd/cody-gateway/internal/httpapi/embeddings/handler.go
- enterprise/cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
- enterprise/cmd/cody-gateway/internal/httpapi/handler.go
- enterprise/cmd/cody-gateway/internal/limiter/limiter.go
- internal/codygateway/types.go
This PR adds a basic endpoint that enumerates the configured limits and the current rate limit data. The main purpose of it is debugging, as we don't have direct read access to redis, but we may want to build some UI features off of this later, too.
Verified things work manually.
> gateway: Add endpoints to read limits

- doc/cody/explanations/code_graph_context.md
- doc/cody/explanations/cody_gateway.md
- doc/cody/explanations/enabling_cody_enterprise.md
Cody will be on by default for cloud from 5.1, and cody.enabled is the single source of truth. This fixes some confusing wording in our docs.
just docs
> Remove some outdated cody config disclaimers

- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/CodyGatewayRateLimitModal.tsx
- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/CodyServicesSection.tsx
- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/utils.ts
Large rate limits were hard to read, this formats numbers according to the machine locale as `1,000` or `1.000`.
Verified manually, see screenshot.
> gateway: Pretty print limit numbers

- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/CodyServicesSection.tsx
This adds a small UI confirmation for making sure cody gateway access is not toggled on/off accidentally, as if the timing is bad, it can cause a multi minute outage for the customer while changes still propagate.
Closes https://github.com/sourcegraph/sourcegraph/issues/54379
Verified manually.
> gateway: Add confirmation modal for toggling access

- cmd/blobstore/shared/BUILD.bazel
- cmd/blobstore/shared/shared.go
- cmd/server/shared/BUILD.bazel
- cmd/server/shared/blobstore.go
- enterprise/internal/codeintel/shared/lsifuploadstore/BUILD.bazel
- enterprise/internal/codeintel/shared/lsifuploadstore/config.go
- enterprise/internal/embeddings/BUILD.bazel
- enterprise/internal/embeddings/uploadstore.go
- internal/conf/deploy/BUILD.bazel
- internal/conf/deploy/endpoints.go
- internal/singleprogram/singleprogram.go
Apparently VS Code's Python support uses port 9000, so as long as we use it most VS Code Python devs can't run the app due to the port conflict with our services.
This PR switches the app's blobstore to listen on `:49000` instead of `:9000`. My thinking for now is that we can centralize all "default endpoint" and "what host/port should I listen on?" into the `deploy` package, and for now just change ports to have a `4` in front of them to reduce the change of conflicts.
Later, once we have them centralized in the `deploy` package we can easily modify that code to pick an unavailable port.
This also binds blobstore to `127.0.0.1` (more secure), previously it was bound to `localhost`.
To test this I did the following:
1. [x] Methodically searched our codebase for `9000` and vetted each …
> app: resolve port :9000 conflicts (change to :49000)

- .github/workflows/batches-notify.yml
Comment on an issue including `batch` or `team/batchers` in the text and look for a notification to @sourcegraph/code-search
> redirect batchers notifications to the Code Search team

- internal/conf/deploy/endpoints.go
We still use `sourcegraph/server` to run our integration tests in our CI pipelines (yuck) and in my change #54466 I failed to realize that `IsSingleBinary()` and `IsDeployTypeSingleDockerContainer(Type())` report different things.
This fixes the issue, and likely fixes `main` on our CI pipelines. If not, then both this change and the other should be reverted.
CI
> deploy: correct blobstore endpoint in sourcegraph/server image (fix 'main' CI)

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/BaseRecipeAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/DownloadCodyAppAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ExplainCodeDetailedAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ExplainCodeHighLevelAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/FindCodeSmellsAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/GenerateDocStringAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/GenerateUnitTestAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/ImproveVariableNamesAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/RunCodyAppAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SimpleRecipeAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/TranslateToLanguageAction.java
- client/jetbrains/src/main/resources/META-INF/plugin.xml
Enable editor context menu actions when configured to use Cody local app only when the cody app is up and running, otherwise show actions to download or run the cody app
- When the chat is not displayed because Cody app is not installed or not running and you're configured to use Cody app then recipe actions should be disabled and appropriate action should be shown
> JetBrains: show editor context recipe actions when cody app is available

- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/operations.go
- enterprise/dev/ci/internal/ci/pipeline.go
The metadata step is for the dev-infra team usage, but we don't use it much these days. Because it's still about 1m 1m30 per build, we're better without it.
CI
> ci: drop metadata step

- doc/admin/executors/deploy_executors_kubernetes.md
Makes it explicit to set this flag in the deployment docs for native Kubernetes executors.
> docs/executors: specify feature flag for native k8s deployment

- dev/sg/BUILD.bazel
- dev/sg/internal/bk/bk.go
- dev/sg/sg_ci.go
- doc/dev/background-information/sg/reference.md
- enterprise/dev/ci/internal/ci/pipeline.go
This is the companion PR to https://github.com/sourcegraph/sourcegraph/pull/54576 that streamline working with the `bazel-do/...` branches. 
It creates a new branch, with a unique name, adds an empty commit with the bazel command in the commit messages and pushes it. 
It support the `--wait` and `--web` flags, as usual. 
CI + https://buildkite.com/sourcegraph/sourcegraph/builds/232650#0189219a-4365-43eb-8035-6bce05d087b2
> sg: add ci bazel helper command to run bazel commands in CI 

- sg.config.yaml
Blobstore port for `sg start app` was incorrect because `SetDefaultEnv` does not overwrite existing values and `sg` set a default for blobstore to `9000`
`sg start app` - no errors about blobstore or code intel lsif uploads.
> App: fix blobstore port for sg start app

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/context/CurrentlyOpenFileListener.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/context/CurrentlyOpenedFileListener.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/context/EmbeddingStatusView.java
- client/jetbrains/src/main/java/com/sourcegraph/common/ProjectFileUtils.java
Shows currently opened file name in Cody footer
- Open some files in the editor and see that the file name is being displayed in the footer
> JetBrains: show currently opened file name in footer

- enterprise/cmd/embeddings/qa/embed_queries/main.go
- enterprise/cmd/embeddings/shared/main.go
- enterprise/internal/embeddings/embed/client/client.go
- enterprise/internal/embeddings/embed/client/openai/client.go
- enterprise/internal/embeddings/embed/client/openai/client_test.go
- enterprise/internal/embeddings/embed/client/sourcegraph/client.go
- enterprise/internal/embeddings/embed/embed.go
- enterprise/internal/embeddings/embed/embed_test.go
Retries are handled automatically by the underlying HTTP client. With this extra layer, we were retrying 5x more times, up to 1600 times. Let's leave retrying to the HTTP layer to reduce complexity in the embeddings clients.
Tested that retries were, in fact, handled in the HTTP layer for intermittent errors.
> Embeddings: remove extra retries

- client/jetbrains/webview/src/telemetry/EventLogger.ts
This change nests the `extensionDetails` object under a single `extensionDetails` property in `public_arguements`. This change makes it consistent with how we are storing it in VSCode.
Before:
```
{
"editor": "...",
"version": "...", 
"extensionID": "..." 
}
```
After:
```
{
"editor": "...",
"version": "...", 
"extensionDetails": { 
"ide": "..." 
}
}
```
This keeps the extensionDetails object nested under a single property, rather than merging all its properties at the top level.
No functionality is changed, this is just a minor syntax improvement to keep the public_argument object a bit more organized.
test locally
> Update `extensionDetails` in EventLogger.ts

- dev/backcompat/defs.bzl
- dev/backcompat/flakes.bzl
* Add a test to the sed command to only perform sed on files that exist
* Update the format args used - it had more args that formating place holders
* Set flakes path for ranking tests
Green CI
> backcompat: fixes to better handle file movement

- internal/conf/confdefaults/confdefaults.go
- internal/repos/BUILD.bazel
- internal/repos/conf.go
External services are only scanned for new repos at a set interval currently the minimum time between checks is 1 min.  This overrides that min for App and allows it to check every 15 seconds.   This allows new repos to be added more quickly during the setup flow instead of having a wait potentially for 1 min before they are discovered and synced.
`sg start app` add a local repo ensure repo is added and cloned.
> App - make App check for new repos faster

- internal/gosyntect/gosyntect.go
Pulled from #51690. This adds a new client method we'll use to provide precise Cody context.
> codeintel: Add symbols method to syntect client

- enterprise/cmd/cody-gateway/internal/events/buffered.go
We want to make sure we ~never drop anything, so let's just allow buffered events logger to work for longer to process all events.
n/a
> cody-gateway/events: do not let bufferedLogger.Stop time out

- enterprise/cmd/frontend/internal/auth/sourcegraphoperator/provider.go
regression from
https://github.com/sourcegraph/sourcegraph/pull/50586/files#diff-ee8e8b3d80266a31a0ea0102394d4434f42c692b4a787b9446d54846fd7167c4L237-R248
auth providers are populated from context.window
before
https://github.com/sourcegraph/sourcegraph/blob/bc2293827bcb6dda6c41ff1b24fadd2e92ede6dd/cmd/frontend/internal/app/jscontext/jscontext.go#L236-L251
after
https://github.com/sourcegraph/sourcegraph/blob/e2d4e003e0ddc51b8f103ee811a7387f5739a7b1/cmd/frontend/internal/app/jscontext/jscontext.go#L248-L265
it now gets the display name from common config, which relies on Provider.Config
https://github.com/sourcegraph/sourcegraph/blob/e2d4e003e0ddc51b8f103ee811a7387f5739a7b1/internal/auth/providers/providers.go#L192-L223
see above
before
after
> soap: fix missing display name

- client/cody/CHANGELOG.md
Preparing for a release and noticed that https://github.com/sourcegraph/sourcegraph/pull/54277 wasn't included in the changelog.
N/A - Docs change
> Cody: Update CHANGELOG.md

- client/web/src/repo/blob/own/HistoryAndOwnBar.story.tsx
Fixes this happening every build:
Chromatic passes with no changes to this story
> Web: Fix flaky storybook build due to React errors

- client/web-sveltekit/src/lib/utils.ts
- client/web-sveltekit/src/routes/[...repo]/(code)/+layout.svelte
- client/web-sveltekit/src/routes/[...repo]/(code)/+layout.ts
- client/web-sveltekit/src/routes/[...repo]/(code)/+page.svelte
- client/web-sveltekit/src/routes/[...repo]/(code)/+page.ts
- client/web-sveltekit/src/routes/[...repo]/(code)/-/blob/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo]/(code)/-/blob/[...path]/+page.ts
- client/web-sveltekit/src/routes/[...repo]/(code)/-/tree/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo]/(code)/-/tree/[...path]/+page.ts
- client/web-sveltekit/src/routes/[...repo]/-/branches/+page.svelte
- client/web-sveltekit/src/routes/[...repo]/-/branches/+page.ts
- client/web-sveltekit/src/routes/[...repo]/-/branches/all/+page.svelte
- client/web-sveltekit/src/routes/[...repo]/-/branches/all/+page.ts
- client/web-sveltekit/src/routes/[...repo]/-/commit/[...revspec]/+page.svelte
- client/web-sveltekit/src/routes/[...repo]/-/commit/[...revspec]/+page.ts
- client/web-sveltekit/src/routes/[...repo]/-/commits/+page.svelte
- client/web-sveltekit/src/routes/[...repo]/-/commits/+page.ts
- client/web-sveltekit/src/routes/[...repo]/-/tags/+page.svelte
- client/web-sveltekit/src/routes/[...repo]/-/tags/+page.ts
tl;dr: A little bit of housekeeping to (eventually) make use of streaming promises and to be less unconventional.
Context: Top-level promises returned by `load` functions are automatically resolved and the resolved values are passed to pages. This is not practical for big or slow-loading data. The workaround I've used so far was to return a store from the load functions instead. However this won't work if we ever decide to use server side rendering (can't serialize a store).
Recently SvelteKit has added support for streaming promises: https://kit.svelte.dev/docs/load#streaming-with-promises
To make (eventually) use of this and still get benefits from using a store we can simply return the (nested) promise from the load function and instantiate the store inside the component.
Note: …
> sveltekit-prototyp: Properly use kit's "streaming promises" feature

- sg.config.yaml
Supresses noisy outputs from `sg run docsite` 
Before 
After
> sg: silence most bazel output for docsite

- dev/sg/sg_run.go
- doc/dev/background-information/sg/reference.md
@efritz noticed that `sg run frontend` always pick the Bazel variant, which at the moment triggers a bundle build, which is really really slow. 
This was not how it was when we first introduced the Bazel variants of the commands, but I missed the consequences of refactoring how we handle the assets a while ago, which created this situation. 
This PR provides a bandage, which I hope will be ok with you @efritz while we fix the root cause for this. 
CI + locally tested.
> sg: add --legacy to run command

- client/cody/CHANGELOG.md
- client/cody/package.json
- client/cody/src/main.ts
https://github.com/sourcegraph/sourcegraph/assets/9516420/f2c2dd46-6afa-4c65-8daa-2fc286b1552d
Adds a "Collapse All Comments" option to the inline chat header
Tested locally in VS Code.
> Cody Inline Chat: Add "Collapse All Comments"

- dev/sg/generates.go
Title says it: when running `sg generate` the early-exit message didn't contain the newline at the end that every other `report.Output` has. I figured it's easier and more consistent to add it here now instead of checking whether `report.Output` has a trailing newline etc.
Also fixes a typo. Two P.
Tested manually, see screenshots
> sg generate: fix typo and add missing newline

- cmd/blobstore/internal/blobstore/blobstore_test.go
- internal/embeddings/BUILD.bazel
- internal/embeddings/index_storage_test.go
- internal/uploadstore/BUILD.bazel
- internal/uploadstore/gcs_client.go
- internal/uploadstore/gcs_client_test.go
- internal/uploadstore/lazy_client.go
- internal/uploadstore/mocks/BUILD.bazel
- internal/uploadstore/mocks/mocks_temp.go
- internal/uploadstore/observability.go
- internal/uploadstore/s3_client.go
- internal/uploadstore/store.go
This adds the method `Store.List(ctx context.Context) (iterator, err)` to the upload store.
**Why?**
Long-term we want to surface more information about the available embeddings to the user. Currently we rely on embeddings jobs which provide an indirect representation of the state of the embeddings store. As a first step we have to have a unified way (GCS, S3) to find out which embeddings we actually have (-> this PR)
Once we can list all keys, we can, for example, create a background job that keeps a db table up-to-date which we can use to:
- quickly filter repos by their embeddings in the site-admin UI.
- list embeddings (not just jobs) and their metadata.
- new unit tests
- I created a bucket on GCS and configured my local instance to use that bucket. Then I updated …
> uploadstore: add method to list all keys

- doc/cody/explanations/code_graph_context.md
- enterprise/cmd/embeddings/shared/config.go
- enterprise/cmd/embeddings/shared/repo_embedding_index_cache.go
- enterprise/cmd/embeddings/shared/repo_embedding_index_cache_test.go
- internal/embeddings/types.go
- internal/env/BUILD.bazel
- internal/env/env.go
This adds `env.MustGetBytes` that parses an environment variable with `go-humanize` and updates the `EMBEDDINGS_CACHE_SIZE` env var to use that. This is easier to read than a big blob of numbers, and easier to configure for admins. `go-humanize` supports numbers without a label and interprets it as bytes, just like we did before.
Check out the `go-humanize` tests for exactly what is accepted. Tested that a couple of env vars work as expected (in particular, just a plain number like this option used to use exclusively)
> env: add MustGetBytes

- dev/oci_deps.bzl
- wolfi-images/batcheshelper.yaml
- wolfi-images/node-exporter.yaml
- wolfi-images/postgres-exporter.yaml
- wolfi-images/server.yaml
Backport of https://github.com/sourcegraph/sourcegraph/pull/54533 to 5.1
Update postgres-exporter and node-exporter to latest versions.
The current version of postgres-exporter seems to cause a [non-critical error](https://sourcegraph.slack.com/archives/C02E4HE42BX/p1688168678260469?thread_ts=1688063676.565389&cid=C02E4HE42BX) which is fixed in 0.12.1, so also backporting. 
TODO:
- CI
- Testing on S2
> [Backport 5.1] Update prometheus tools

- client/cody/src/completions/logger.ts
Follow up to #54172 to check for additional completion providers when sending logs.
Logs should now show that another completion provider is enabled when AWS CodeWhisperer, Codeium, CodeComplete, Fauxpilot, or Tabby are enabled.
> Autocomplete: Check for additional completion providers when sending logs

- .gitattributes
The original idea that motivated the decision to hide bazel changes was that during the migration, we were really putting out a lot of these changes and it was really noisy in PRs. 
Now we've reached the point where we're using Bazel normally everyday, diffs on these files are much smaller. If you were making changes to a Makefile in your PR because you added a new file, you would want to see them them. 
Well it's the same thing here, stuff could go wrong if the Buildfiles are not updated, it's code exacly like your Makefile is. 
Which is why, I'm pushing for having those not collapsed by default. 
CI
> github: show bazel diff again

- src-tauri/src/main.rs
Disables the gitserver repo clean up by setting the env variable to 0 when spawning the sourcegraph process
Add a temporarly error log to print the variable value
Build release version
```SRC_REPOS_DESIRED_PERCENT_FREE	{"Resource": {"service.name": "sourcegraph-backend", "service.version": "2023.0.0+dev", "service.instance.id": "Chriss-MBP.warwick"}, "Attributes": {"value": 0}}```
> App - disable gitserver cleanup

- dev/sg/sg_app.go
- doc/dev/background-information/sg/reference.md
Adds a `sg app reset` command that removes all dev app data and clears the web cache 
`sg start app` - to create folders
`sg app reset --dry-run` verify that folders remain
`sg app reset` - verify that folders are gone
> App - add sg app reset command to clear local app dev data

- src-tauri/src/tray.rs
This adds a "Developer" menu in the system tray that is only available when running `sg start app`.  Currently the menu has two options:
1. Jump to repo setup in the setup flow
2. Jump to chat
These two options provide navigation that is not usually available but can be very helpful when doing dev work, by bypassing the connect to dotcom step,  skipping the setup flow or jumping back into the setup flow at the repo adding step
`sg start app` - verify menu is present and navigation works
build a release version - verify that developer menu is not present
> App - add a developer menu for dev mode 

- dev/release/src/google-calendar.ts
This marks everyone as optional when sending calendar events related to the release.
Run `pnpm run release tracking:timeline ` with `{dryRun.calendar}` set to `true` and the events generated should have an extra field of `optional: true`
> release: make release event attendees optional

- CHANGELOG.app.md
- src-tauri/src/main.rs
Passes an empty `SRC_PROF_HTTP` env variable when starting up the sourcegraph backend to disable the debug server in App.
resolves https://github.com/sourcegraph/sourcegraph/issues/54731
Build release version of app and check localhost:6060
> App - disable debug endpoints on port 6060

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
Prompt input displays 3 rows instead of 2
- Prompt input should display 3 rows instead of 2
before:
now:
> JetBrains: set minimum 3 rows for input text area

- doc/dev/background-information/bazel/go_generate.md
I think it would have been annoying to accept these suggestions in the actual PR
none - docs change
> bazel generate doc suggestions / fixes

- cmd/frontend/graphqlbackend/BUILD.bazel
- dev/BUILD.bazel
- dev/write_generated_to_source_files.bzl
- doc/dev/background-information/bazel/go.md
- doc/dev/background-information/bazel/go_generate.md
- doc/dev/background-information/bazel/index.md
- enterprise/cmd/cody-gateway/internal/dotcom/BUILD.bazel
- enterprise/cmd/cody-gateway/internal/dotcom/gen.go
- enterprise/cmd/frontend/internal/guardrails/dotcom/BUILD.bazel
- enterprise/cmd/frontend/internal/guardrails/dotcom/gen.go
This PR migrates the two go generate directives that generate some GQL client to Bazel. 
Because it was a good example on how to convert a `go:generate` directive, I also wrote a how-to to explain the migration process. 
CI + local
> bzl: migrate genqlient go:generate to Bazel

- dev/ci/runtype/runtype.go
- dev/sg/sg_ci.go
- doc/dev/background-information/ci/reference.md
- doc/dev/background-information/sg/reference.md
this also fixes the command so that we can push builds for external contributors
1. Created a fork
2. Made a [PR](https://github.com/sourcegraph/sourcegraph/pull/54711)
3. Submitted a [build](https://buildkite.com/sourcegraph/sourcegraph/builds/233315#0189308e-0634-465e-9d0d-47f73f164139)
```
go run ./dev/sg ci build --commit da6c539fd866d01cac56ab736091b7bb6c5acb7b
❗️ Commit "da6c539fd866d01cac56ab736091b7bb6c5acb7b" not found in in local 'origin/' branches - you might be triggering a build for a fork. Make sure all code has been reviewed before continuing.
Continue? (yes/no) yes
Pushing da6c539fd866d01cac56ab736091b7bb6c5acb7b to _manually_triggered_external/ext_da6c539fd866d01cac56ab736091b7bb6c5acb7b...
remote: 
remote: Create a pull request for …
```
> sg: add runtype manually triggered

- enterprise/cmd/cody-gateway/internal/httpapi/embeddings/openai.go
- enterprise/cmd/cody-gateway/internal/httpapi/embeddings/openai_test.go
- internal/embeddings/embed/client/client.go
- internal/embeddings/embed/client/openai/BUILD.bazel
- internal/embeddings/embed/client/openai/client.go
- internal/embeddings/embed/client/sourcegraph/BUILD.bazel
- internal/embeddings/embed/client/sourcegraph/client.go
- internal/embeddings/embed/client/sourcegraph/client_test.go
- internal/embeddings/embed/embed.go
- internal/embeddings/embed/embed_test.go
This adds the failing file name to the error message when OpenAI decides it doesn't want to process a file.
Tested that both the OpenAI client and the Cody Gateway client both show the error message containing the problematic file name.
> Embeddings: add file name to the error message from OpenAI weirdness

- dev/go_defs.bzl
We might need to turn off the race detector for a target, see https://sourcegraph.slack.com/archives/C04MYFW01NV/p1688741821325559
CI
> bzl: enable go_test to turn off race detector

- CHANGELOG.md
- enterprise/cmd/frontend/shared/shared.go
- internal/conf/init.go
See [this comment](https://github.com/sourcegraph/sourcegraph/pull/52242/files#r1254598066) for the source issue. Looks like #52242 introduced a condition where certain httpcli settings were not being configured in the frontend due to some cyclic package dependency-avoidance trickery in the `conf.Init` function.
This PR ensures that this setup code is hit in the frontend initialization process. No other service should need this (as they hit the `conf.Init` function directly from `SingleServiceMain` on startup), and no other feature should have been affected (as these are the only settings missing from that path).
> conf: Fix httpcli config

- enterprise/cmd/cody-gateway/internal/limiter/limiter.go
We should not rely on the call site to pass down a context that won't be cancelled by accident, and although our redis methods aren't taking a context right now, nothing prevent them from taking a context in the future (through a renovation/refactoring) by someone who absolutely has no "context" about it could cause we silently stop committing usage for rate limit of cancelled requests.
CI
> cody-gateway: commit usage with background context

- doc/dev/background-information/ci/reference.md
- internal/auth/providers/mock_auth_provider.go
- internal/auth/providers/providers.go
- internal/auth/providers/providers_test.go
Previously we used DisplayName from CachedInfo() function return. But refactoring to support displayPrefix and other common fields introduced a regression where we did not use it as a default, resulting in empty strings for DisplayName.
This commit brings back the old behavior, where we default to DisplayName from CachedInfo() and only overwrite it with a different value if there is one defined and it is not an empty string.
fixes #54740 
- #54740
Tested locally + unit test
> [fix] use sane default for auth provider display name

- deps.bzl
- go.mod
- go.sum
This PR bumps `sourcegraph/log` to https://github.com/sourcegraph/log/commit/40c57b632cca13ee3a4f6105d678de7902fc80e2 which will enable to get proper log severity parsing on both dotcom and s2. 
CI
> go: bump sourcegraph/log

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/api/ChatUpdaterCallbacks.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/api/CompletionsService.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/api/SSEClient.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/SourcegraphNodeCompletionsClient.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/Chat.java
Show stop generating button when response from Cody is being processed
- Talk to Cody and stop generating the response by clicking at the button
- Execute some recipes and stop generating by clicking at the button
- Reset current conversation while receiving the response should also stop generate response
> JetBrains: show stop generating button while receiving the response

- client/jetbrains/build.gradle.kts
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
This disables failing gradle tasks, It's going to be fixed later
- Green CI
> JetBrains: disable gradle copyAgentBinariesToPluginPath task

- doc/admin/observability/logs.md
Mentions the availability of `SRC_LOG_FORMAT=json_gcp` in the admin/observability/logging page.
CI.
> doc: mention json_gcp format for logs

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/UpdatableChatHolderService.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/api/ChatUpdaterCallbacks.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/Chat.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatBubble.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatMessage.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/MessageContentCreatorFromMarkdownNodes.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/RefreshCodyAppDetection.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ResetCurrentConversationAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SimpleRecipeAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/TranslateToLanguageAction.java
- Fixes https://github.com/sourcegraph/sourcegraph/issues/54592
There were some missing null annotations that allowed us to overlook this case. The main takeaway for me is to keep the habit of always using `@NotNull`/`@Nullable` annotations.
Also:
- Docs: Added some comments to clarify what some parts of the code do
- Cleanup: Fixed a deprecation warning
- Cleanup: Removed two commented code blocks
- Docs fix: Moved an unreleased changelog item
The above changes are all in separate commits for easier review.
I couldn't repro the original issue TBH, but based on the provided stack trace, I don't see how it could happen again after these changes.
> JetBrains: Fix NullPointerException if there's no chat component

- .buildkite/hooks/pre-exit
Only runs the docker clean up tasks if containers or volumes are found to stop the error messages at the end of jobs
Works on this feature branch in CI
> ci: surpress pre-exit hook warnings

- enterprise/internal/batches/reconciler/executor.go
- enterprise/internal/batches/reconciler/executor_test.go
We are seeing a user have an issue where GitHub is not able to open a Pull Request because the branch does not exist. No errors are occurring prior to the PR creation. While investigating _why_ the branch may not be created, I noticed that we do not handle if the error is not `pushCommitError`.
So hopefully this can help narrow down or catch _why_ the user is running into GitHub getting angry about no branch.
Added a new unit test
> codesearch: Handle error if not a pushCommitError

- dev/backcompat/defs.bzl
Minor improvements I noticed while updating this file. Not sure if this is in good style for bazel files, so interested in feedback.
Test Plan: rely on CI, didn't test locally.
> backcompat: use keyword args to format and generate build commands seds

- cmd/cody-gateway/internal/httpapi/completions/anthropic.go
- cmd/cody-gateway/internal/httpapi/completions/openai.go
- cmd/cody-gateway/internal/httpapi/completions/upstream.go
- cmd/cody-gateway/internal/httpapi/embeddings/openai.go
We've had TODOs for these in already, so I went ahead and implemented them. This adds some additional information for upstream on whos behalf we're doing a request. Both providers claim to use this to help us detect bad actors in case of abuse.
Tested that requests still work.
> gateway: Add actor tracking to upstream requests

- CHANGELOG.md
- internal/database/postgresdsn/postgresdsn.go
- internal/database/postgresdsn/postgresdsn_test.go
Fixes edge case where we construct a double-port postgres DSN.
Additional unit test case.
> postgresdsn: Fix double port

- internal/search/backend/cached_test.go
I am migrating us away from Minimal which is deprecated. This just ensures we correctly handle it in our caching. Luckily we did.
> search: test we correctly cache ReposMap field

- sonar-project.properties
Adding sonar project properties file to exclude few java, kotlin & c/cpp stuffs. (part of hackathon at BCN)
- Backup plan: revert this PR and `analysis method` as automatic on sonarcloud project setting
- Buildkite should automatically pickup this file for scanning
> Add Sonar Project Properties

- client/web/src/enterprise/site-admin/cody/RepoEmbeddingJobNode.tsx
- enterprise/cmd/frontend/internal/embeddings/resolvers/repo_embedding_jobs.go
This [PR](https://github.com/sourcegraph/sourcegraph/pull/54804) fixed an issue with job scheduling/execution in the backend. The interim fix of this PR relies on allowing for empty string `revision` values written with a repo embedding job when the repo is empty or some other issue occurs when fetching the repo's default branch (e.g. empty repo).
Empty revision value causes issues with graphql query repoEmbeddingJobs when [querying for Revision](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/site-admin/cody/backend.ts?L32-35) as our site admin jobs panel does.
`Panic occurred: runtime error: slice bounds out of range [:7] with length 0`
This PR updates the embedding job resolver to consider empty revision string acceptable and not call …
> Allow for null revision resolver when using repo embeddings job's empty revision string

- cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
- cmd/cody-gateway/internal/httpapi/completions/upstream.go
- cmd/cody-gateway/internal/httpapi/embeddings/BUILD.bazel
- cmd/cody-gateway/internal/httpapi/embeddings/handler.go
- cmd/cody-gateway/internal/httpapi/embeddings/openai.go
- cmd/cody-gateway/internal/response/response.go
Makes filtering much easier in Cloud Trace. Now, for example, to identify requests where we have been rate limited by upstream:
```
upstreamStatusCode: 429
matched_source: dotcom-product-subscriptions
```
If we've rate limited the caller ourselves:
```
resolvedStatusCode: 429
matched_source: dotcom-product-subscriptions
```
Note that I just realized we could've achieved this as well with root-span searches https://cloud.google.com/trace/docs/trace-filters#search-root-span , but this might come in handy regardless
CI
> cody-gateway: record custom upstreamStatusCode, resolvedStatusCode attributes

- client/web/src/enterprise/site-admin/cody/RepoEmbeddingJobNode.tsx
- enterprise/cmd/frontend/internal/embeddings/resolvers/repo_embedding_jobs.go
This [PR](https://github.com/sourcegraph/sourcegraph/pull/54804) fixed
an issue with job scheduling/execution in the backend. The interim fix
of this PR relies on allowing for empty string `revision` values written
with a repo embedding job when the repo is empty or some other issue
occurs when fetching the repo's default branch (e.g. empty repo).
Empty revision value causes issues with graphql query repoEmbeddingJobs
when [querying for
Revision](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/site-admin/cody/backend.ts?L32-35)
as our site admin jobs panel does.
`Panic occurred: runtime error: slice bounds out of range [:7] with
length 0`
This PR updates the embedding job resolver to consider empty revision
string acceptable and not call …
> [Backport 5.1]: Allow for null revision resolver when using repo embeddings job's empty revision string

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
Previously we depended on Tauri from a branch to pick up a change that was coming in Tauri 1.3 but not yet released.  This is now released and Tauri is now to v1.4.1 instead of depending on dev branch we now use named versions where possible
`sg start app` ✅ 
**build release version** 
- connect with dotcom ✅ 
- add repos ✅ 
- embeddedings generated ✅ 
- chat ✅
> App - Update Tauri dependencies to 1.4.1

- client/jetbrains/src/main/java/com/sourcegraph/telemetry/Event.java
We didn't convert an object to a string → our Go backend rejected it → got no logs on Dotcom :bang-head:
Currently, I'm getting back a bunch of 429 – Too Many Requests responses from Dotcom for some reason, but the problem should be solved.
I feel sorry about losing all those logs, it really sucks. We were too much in a rush and didn't test this properly. Totally my mistake.
Tested it with the built-in-debugger and by copying the requests to our GraphQL API console.
> JetBrains: Fix dotcom logging issue

- internal/search/backend/metered_searcher.go
We don't need to set opts.minimal, that is captured in the category name. Additionally we don't need a field per type since we can just add the size of each field to repos.
Test Plan: CI
> search: adjust honeycomb events for other List field types

- cmd/frontend/graphqlbackend/repository_stats.go
- internal/search/BUILD.bazel
- internal/search/env.go
We added a metric to ensure these values always agree, and they do. So we also remove that metric.
Test Plan: CI
> search: use zoekt RepoStats.Repos instead of length of map

- internal/singleprogram/postgresql.go
It seems like this error message was specifically added for NixOS users, which is a rather obscure subset of our overall users, and this error message phrasing is obfuscating the real issue when people read our logs on other platforms - so I am making it clearer.
Wording change only
> app: do not suggest running your own postgres

- enterprise/cmd/executor/internal/run/BUILD.bazel
- enterprise/cmd/executor/internal/run/util.go
- internal/conf/deploy/deploytype.go
- internal/singleprogram/singleprogram.go
Almost every user report I respond to has errors like this in their logs, which leads to users getting confused and thinking _that_ must be their issue (when in reality, it's some less verbose log line):
```
------------------------------------------------------------------------------|
Docker is unavailable                                                        |
------------------------------------------------------------------------------|
Sourcegraph is better when Docker is available; some features may not work:  
- Batch changes                                                              
- Symbol search                                                              
- Symbols overview tab (on repository pages) …
```
> app: prepare for a more minimal distribution & reduce red-herring errors

- cmd/frontend/graphqlbackend/repositories_test.go
- cmd/frontend/internal/httpapi/search.go
- cmd/frontend/internal/httpapi/search_test.go
- cmd/worker/internal/zoektrepos/zoektrepos.go
- internal/database/mocks_temp.go
- internal/database/repos_test.go
- internal/database/zoekt_repos.go
- internal/database/zoekt_repos_test.go
- internal/repos/status_messages_test.go
- internal/search/env.go
Minimal is deprecated since ReposMap has a more garbage collector friendly representation. This switches us over for ListAllIndexed calls. Additionally we update the return type to only have the fields that will be set by this call. This is to prevent accidental use of an unset field.
Test Plan: CI
Based on #54884
> search: use ReposMap for ListAllIndexed

- internal/search/repos/repos.go
- internal/search/repos/repos_test.go
- internal/search/zoekt/indexed_search.go
- internal/search/zoekt/indexed_search_test.go
This required updating pointers to MinimalRepoListEntry to be values which should be acceptable since they are small values. Minimal is deprecated.
Test Plan: CI
> search: use ReposMap in search path

- cmd/searcher/internal/search/hybrid.go
Minor change to move to non-deprecated ReposMap. The final change in the series.
Test Plan: CI
> searcher: use ReposMap

- internal/search/symbol/symbol.go
This makes it clearer that we should be using ReposMap instead of Minimal. Note: before we also would of gone via the cached searcher since the query was the const true.
Test Plan: CI
Based on #54886
> search: use ListAllIndexed for symbol search

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/vcs/VcsCommitsMetadataProvider.java
This pr add automatic disabling/enabling of the summarize recent code changes button in the recipes tab
Automatic disabling/enabling works only if we interact with the git repository through the IDE, it won't work if we manually modify our file system externally. 
closes sourcegraph/cody#118 
- Open project with git repository and button should be enabled
- Open project without git repository and button should be disabled
- Adding/removing the git repository through the IDE should enable/disable the button
> JetBrains: Disable git recipe button when vcs is not available

- client/web/src/codeintel/ReferencesPanel.tsx
This has been bugging me for a long time. Last time we talked about this in March there was consensus that right/down are common in dev tools and that the existing solution is confusing.
> ref panel: switch from chevron up/down to right/down for open/closed

- WORKSPACE
Bump rules_go to a newer version. I didn't go for `0.41.0` because it introduces a breaking change with how we deal with the googleapis and that will require some work to patch the back compat tests. So I'd rather bump this, update to go 1.20.5 and then deal with the 0.41.0 update :) 
CI
> bzl: bump rules_go to 0.40.1

- dev/release/src/batchChanges.ts
- dev/release/src/util.ts
- dev/release/templates/patch_release_issue_template.md
- dev/release/templates/release_issue_template.md
I noticed some of the release templates didn't have the `S2` instance as the release instance. This fixes that.
> release: update sourcegraph release instance

- doc/admin/user_data_deletion.md
- internal/database/users.go
Make it clear that deleting a user also removes their repository permissions.
N/A: Just a comment change and docs update.
> docs: update docs for user deletion

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/api/ChatUpdaterCallbacks.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/SourcegraphNodeCompletionsClient.java
Fixes https://github.com/sourcegraph/cody/issues/132 
(@vdavid can you update the ticket? I don't seem to have the right permissions to that board)
This is a temporary solution, I merely downgrade the errors to warnings.
What we should have is proper bubble notifications for error cases so that the user has feedback on what went wrong, why and how to fix it. 
We probably should change all the `logger.error` lines to an appropriate notification once we have the flows designed.
- check if the problem described in the issue is replicable
- green CI
> JetBrains: Cody: don't throw exceptions when the enterprise instance is down

- internal/observation/context.go
We have observation code paths that test if Tracer is set and optionally do work then. Outside of test environments Tracer should be set. So by setting Tracer in our test context we should start exercising more code paths during go test.
Test Plan: CI
> observation: set Tracer in TestContext

- client/branded/src/components/Timestamp/Timestamp.tsx
Previously, we would not re-render the label except on a timer. This updates it so that whenever the inputs change, we rerender immediately, then set a timer to update the label as time progresses.
Tested manually that the rendered label is correct and matches the tooltip, even on update and refresh.
> Embeddings: re-render the label every time the input changes

- doc/cody/explanations/policies.md
Refers to [slack convo](https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1689012250860489?thread_ts=1688638981.118639&cid=C04NPH6SZMW)
Test plan:
doc change only
> docs: recommend to embed active repos only

- enterprise/cmd/embeddings/shared/context_qa_test.go
- enterprise/cmd/embeddings/shared/main.go
- enterprise/cmd/embeddings/shared/main_test.go
- enterprise/cmd/embeddings/shared/repo_embedding_index_cache.go
- enterprise/cmd/embeddings/shared/repo_embedding_index_cache_test.go
- enterprise/cmd/embeddings/shared/search.go
- enterprise/cmd/worker/internal/embeddings/repo/handler.go
- internal/embeddings/index_name.go
- internal/embeddings/index_storage.go
- internal/embeddings/index_storage_test.go
With this PR we migrate embeddings to the new naming schema `<repo ID>.embeddingindex`. Old embeddings can still be read. New embeddings (full index and incremental) will follow the new naming schema.
Example: repo "qa-repo".
Old
```
qa_repo_d5e73055b0ac12179e03a9e6dc330d1c.embeddingindex
```
New
```
14.embeddingindex
```
*Why?*
- Our current naming schema makes it very inefficient to map embeddings to their repo. However, we need such a mapping, because we want to establish a representation of the existing embeddings in our database. So far we used the `repo_embeddings_jobs` table as a proxy, which is prone to diverge from the state of the store at some point. Using the new naming schema makes it trivial to map embeddings to their respective repos. 
-  Once we have embeddings represented …
> embeddings: name embeddings by id not by name

- enterprise/cmd/frontend/internal/authz/init.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/license_check_handler.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/license_check_handler_test.go
- internal/licensing/check.go
- internal/licensing/check_test.go
- internal/licensing/licensing.go
- internal/licensing/licensing_test.go
Added reason of why license is invalid. Changed the response for expired licenses not to return an error but return invalid state instead.
Tested locally by adding fields to Redis directly + unit tests.
> chore: improve licensing message when license is invalid

- enterprise/cmd/frontend/internal/dotcom/productsubscription/license_check_handler.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/license_check_handler_test.go
Rationale: https://docs.google.com/document/d/1o8fypurDxsukEbn9GaPQDv96PNyBPcoKlxpBQTW6l7U/edit
We do have customers who were broken because they use more than one instance with the same license key. We changed the v5.1 license key validation to only allow 1 license key per 1 instance. Until v5.1 it was a common setup to have multiple instances with the same key and it adds burden to customers and CE/TA teams to fix this.
This change is meant to switch from being reactive - mark the license on the instance as invalid when such a situation happens to be proactive - send a slack message to us instead and notify the customer that we need to change their license keys.
This change only needs releasing to dotcom, hence does not need backporting.
Tested locally via API calls + unit tests.
Slack …
> licensing: allow multiple instances with same license key

- .tool-versions
- WORKSPACE
- dev/backcompat/flakes.bzl
- dev/go_stringer.bzl
- dev/sg/checks.go
- internal/database/user_credentials_test.go
- bumps `rules_go` to `0.40.1` (didn't go for `0.41.0` yet, the breaking change with google apis is a bit messy to deal with, can be handled in a second time). 
- Because of an update to the crypto libs, we can't compare authenticators directly anymore. Instead I updated the test code to compare their `.Hash()`, which is semantically equivalent.
- Added that particular test to the flakes, to green the back compat tests.  
- Big thanks to @camdencheek for fixing the issues with the Go compiler and the `execabs` mess which requires absolute paths, which needed to be fixed, as Go 1.20.X doesn't ship with precompiled code for the stdlib anymore. 
CI
> bzl: update to Go 1.20.5 

- client/web/src/codeintel/ReferencesPanel.tsx
This treats the "Prototypes" list just like "Implementations":
It's open if `implementations_` is in the URL, otherwise it's closed by default.
> ref panel: only uncollapse prototypes if requested

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
When status of the Cody app changes while we are on the plugin settings, the links to run or install Cody app should automatically appear/disappear  
closes https://github.com/sourcegraph/cody/issues/124 
- Open Cody setting without the Cody app running, run it and the information to run the cody app should disappear
- Open Cody settings without the Cody app installed, install it and the information to install the cody app should disappear
> JetBrains: update visibility of helper links when Cody app status changes

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/InvalidAccessTokenException.java
If user has invalid token we will show only one informative message about invalid access token
closes https://github.com/sourcegraph/cody/issues/122 
Ask cody with invalid access token, only one message should appear in the chat
before:
now:
> JetBrains: show one informative message when user has invalid access token

- CHANGELOG.md
- client/web/src/auth/SignInPage.test.tsx
- client/web/src/auth/SignUpPage.test.tsx
- client/web/src/jscontext.ts
- client/web/src/user/settings/auth/ExternalAccountsSignIn.tsx
- client/web/src/user/settings/auth/UserSettingsSecurityPage.tsx
- client/web/src/user/settings/backend.tsx
- cmd/frontend/internal/app/jscontext/jscontext.go
- enterprise/cmd/frontend/internal/auth/azureoauth/BUILD.bazel
- enterprise/cmd/frontend/internal/auth/azureoauth/provider.go
- enterprise/cmd/frontend/internal/auth/azureoauth/provider_test.go
- enterprise/cmd/frontend/internal/auth/bitbucketcloudoauth/BUILD.bazel
- enterprise/cmd/frontend/internal/auth/bitbucketcloudoauth/config.go
- enterprise/cmd/frontend/internal/auth/bitbucketcloudoauth/config_test.go
- enterprise/cmd/frontend/internal/auth/gerrit/BUILD.bazel
- enterprise/cmd/frontend/internal/auth/gerrit/config.go
- enterprise/cmd/frontend/internal/auth/gerrit/config_test.go
- enterprise/cmd/frontend/internal/auth/githuboauth/BUILD.bazel
- enterprise/cmd/frontend/internal/auth/githuboauth/config.go
- enterprise/cmd/frontend/internal/auth/githuboauth/config_test.go
- enterprise/cmd/frontend/internal/auth/gitlaboauth/BUILD.bazel
- enterprise/cmd/frontend/internal/auth/gitlaboauth/config.go
- enterprise/cmd/frontend/internal/auth/gitlaboauth/config_test.go
- internal/auth/providers/providers.go
This PR removes the restrictions of having one Auth provider per URL, and instead allows one auth provider for each URL+ClientID combination.
The URL restriction came from the way our old permissions table worked, but with the `user_repo_permissions` table, this restriction no longer applies as permissions are stored against individual external accounts.
This has also become an increasingly common ask from customers, and it also eases the transitioning when switching from one auth provider to another, like switching from traditional GitHub OAuth to GitHub App Oauth.
One caveat that remains: Having multiple auth providers for the same URL does not play well with repo-centric permissions syncing, as we cannot from the repo token's perspective determine which user external account a …
> Allow multiple auth providers with the same URL, adjust UI

- enterprise/cmd/worker/internal/embeddings/repo/BUILD.bazel
- enterprise/cmd/worker/internal/embeddings/repo/handler.go
Right now we rely on the revision stored in `repo_embeddings_jobs` table for incremental updates. This hasn't led to problems yet, but it very well might.
For example, if the jobs table doesn't reflect the state of the store anymore, the diffs will be off (-> subtle bug) and we have to trigger a complete reindex to fix this.
In general, we shouldn't consider the job table as authorative when it comes to index metadata. Instead we should rely on the store or at least a db table that is eventually consistent with the store.
Note:
While I was anyway touching the code, I simplifed the logic around incremental updates a bit.
- CI, because this is mostly a refactor
- Manual testing: checked locally that incremental updates still work as expected
> embeddings: get rev from index instead of from job

- enterprise/cmd/embeddings/shared/search.go
- internal/embeddings/BUILD.bazel
- internal/embeddings/embed/embed.go
- internal/embeddings/index_storage.go
- internal/embeddings/index_storage_test.go
- internal/embeddings/quantize.go
- internal/embeddings/quantize_test.go
- internal/embeddings/types.go
This makes memory usage ~constant during the decode process. Previously, we were undersizing the large allocation (which caused it to reallocate ~10 extra times) for the index and making a bunch of additional smaller allocations per loop. This meant we were spiking memory usage during decoding, and even if the garbage collector could keep up (which I wouldn't expect it to), we'd still need 2x the index size at the peak for live memory. This was causing an OOM. 
Before:
```
BenchmarkCustomRepoEmbeddingIndexDownload-10                   1        1212576041 ns/op        1299284528 B/op    96393 allocs/op
```
After:
```
BenchmarkCustomRepoEmbeddingIndexDownload-10                   1        1193088500 ns/op        589103720 B/op     65660 allocs/op
```
That's a 2.2x reduction in allocated …
> Embeddings: optimize memory usage during decode

- enterprise/cmd/embeddings/shared/BUILD.bazel
- enterprise/cmd/embeddings/shared/repo_embedding_index_cache.go
If a query times out or a user navigates away while we are fetching an embeddings index, the fetch is canceled because it shares a context with the request. Instead, this PR updates the logic to spin up a detached background goroutine that will populate the cache 
Ran a query that was immediately canceled, then checked that a followup query did not miss the cache.
> Embeddings: populate cache in background

- client/branded/src/components/Timestamp/Timestamp.tsx
- enterprise/cmd/embeddings/shared/BUILD.bazel
- enterprise/cmd/embeddings/shared/context_qa_test.go
- enterprise/cmd/embeddings/shared/main.go
- enterprise/cmd/embeddings/shared/main_test.go
- enterprise/cmd/embeddings/shared/repo_embedding_index_cache.go
- enterprise/cmd/embeddings/shared/repo_embedding_index_cache_test.go
- enterprise/cmd/embeddings/shared/search.go
- enterprise/cmd/worker/internal/embeddings/repo/BUILD.bazel
- enterprise/cmd/worker/internal/embeddings/repo/handler.go
- internal/embeddings/BUILD.bazel
- internal/embeddings/embed/embed.go
- internal/embeddings/index_name.go
- internal/embeddings/index_storage.go
- internal/embeddings/index_storage_test.go
- internal/embeddings/quantize.go
- internal/embeddings/quantize_test.go
- internal/embeddings/types.go
This backports a set of recent embeddings-related PRs from `main`, including a fix that we want to include in an early patch release.
Tested in original PRs. Will test on the 5.1 branch before release.
> [Backport 5.1] Backport a few embeddings PRs

- enterprise/cmd/frontend/internal/dotcom/productsubscription/codygateway_service.go
Reverts sourcegraph/sourcegraph#54946. We need to sanitize the label values it seems
Test plan: n/a reverts to known state
> Revert "productsubscription: add labels to BigQuery queries"

- cmd/frontend/graphqlbackend/BUILD.bazel
- cmd/frontend/graphqlbackend/executor.go
- cmd/frontend/graphqlbackend/executor_test.go
- enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
- enterprise/cmd/frontend/internal/executorqueue/handler/handler_test.go
- enterprise/cmd/frontend/internal/executorqueue/handler/multihandler.go
- enterprise/cmd/frontend/internal/executorqueue/handler/multihandler_test.go
- lib/api/BUILD.bazel
- lib/api/version_check.go
- lib/api/version_check_test.go
The annoying error of `Invalid Semantic Version` tells us nothing and makes troubleshooting the issue difficult with lots of churn.
I have update Executor usage of `semvar.NewVersion` to wrap the error with a message that include the actual version that causes the error. This will help us understand the specific version string that is causing the error and more quickly determine _why_ the version is getting injected.
Update/add Go tests.
> executors: Provide more context when the semantic version is invalid

- client/web/src/enterprise/app/setup/steps/AppInstallExtensionsSetupStep.module.scss
- client/web/src/enterprise/app/setup/steps/AppInstallExtensionsSetupStep.tsx
Based on [this user test by @meglynst](https://sourcegraph.dovetailapp.com/data/HgYNJ7Hwipazu5LkkvtgA#v=ewAiAGMAIgA6ACIANQA0ADEAYgAyADgAMABhAC0AYgBhAGYAOQAtADQAYQAwAGQALQA5ADgAOABkAC0ANABiADQAOQA0ADkAMQA4ADAANQBlAGIAIgB9AA), the design of the App’s Extensions page can mislead people into thinking that the "Install" link is about installing the IDE itself. This PR:
* Updates the CTA label of each extension to make it clearer that you’re installing the Cody extension, not the IDE itself. This should also help them if something goes wrong with the deep link (as it did in that use test), as generally most IDE users know how to install an extension from their marketplace.
* Cleans up left side words (multiple editors, and they have different capabilities so I removed the feature list)
* …
> App: Clearer CTAs on the extension install page

- client/web/src/cody/chat/CodyChatPage.tsx
Closes https://github.com/sourcegraph/cody/issues/163
- Loaded the chat in App
- Verified link isn't rendered
> Hide the "Cody Settings" link in App

- schema/schema.go
- schema/site.schema.json
Removed the disclaimer that SCIM was not standards-compliant.
This has been the case for a long time, but we forgot to remove this disclaimer.
Only docs change
> SCIM: Remove disclaimer

- .github/workflows/pr-auditor.yml
Use pr-auditor from `sourcegraph/pr-auditor`
`gh workflow run pr-auditor --ref wb/pr-auditor` + `on: workflow_dispatch:`
> pr-auditor: use pr-auditor from new repo

- client/web/src/enterprise/repo/settings/RepoSettingsPermissionsPage.tsx
- client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
It was confusing what is full sync and incremental sync. Changed the text and added tooltip content to be more specific.
It now also aligns to what we say in the [permission docs](https://docs.sourcegraph.com/admin/permissions/syncing#permission-syncing).
Related issue:
- https://github.com/sourcegraph/sourcegraph/issues/55003
Tested locally
> chore: update text copy for permissions UI pages

- doc/cody/explanations/cody_clients.md
The purple badge wasn't there before this PR:
(Only docs change)
> JetBrains: Docs: Add "Experimental" badge

- CHANGELOG.md
- doc/admin/auth/index.md
- enterprise/cmd/frontend/internal/auth/gitlaboauth/BUILD.bazel
- enterprise/cmd/frontend/internal/auth/gitlaboauth/login.go
- enterprise/cmd/frontend/internal/auth/gitlaboauth/login_test.go
- enterprise/cmd/frontend/internal/auth/gitlaboauth/provider.go
- schema/schema.go
- schema/site.schema.json
Closes #50879 
Adds a new Auth provider configuration option for GitLab auth providers, `ssoURL`. This is an optional URL that points to a GitLab group's SSO sign-in page, and adds the regular OAuth URL as a `redirect` parameter. So users will first sign in to GitLab using their SSO, then it  will redirect them to the normal OAuth flow.
GitLab's normal OAuth flow for groups that have SSO enabled is broken, and users will be redirected to the normal GitLab sign-in page where they have to provide a username and password, which they don't have, because they use SSO.
Imagine the following scenario:
- You work for a company, SecretOrg
- Your code is stored on GitLab, and your SecretOrg group uses SAML/SSO for signing in
- SecretOrg uses Sourcegraph, because SecretOrg is awesome
- You try to …
> [gitlab] Support custom GitLab SSO sign-on URLs

- client/web/src/auth/__snapshots__/SignUpPage.test.tsx.snap
- client/web/src/site-admin/init/__snapshots__/SiteInitPage.test.tsx.snap
- client/web/src/user/index.ts
Closes #54702
I'm still trying to figure out when this started happening or why it started happening. However, according to the error message it looks like there's an invalid character within the character class (usually denoted by the [] brackets)
In the given regular expression `/^\w(?:\w|[.-](?=\w))*-?$/`, the invalid character class is [.-]. Escaping the hyphen character within the character class `[.\-]` fixes the error.
Spin up a fresh instance of Sourcegraph, entering the username and password shouldn't trigger the error in the console anymore.
> source: fix username input validation

- internal/cmd/search-blitz/.gitignore
- internal/cmd/search-blitz/Dockerfile
- internal/cmd/search-blitz/scripts/build.sh
At some point we started using the root go.mod, which made building the container image _very_ slow. So slow I wrote this before it had finished running.
Test Plan: built (without pushing) on my arm64 mac just to make sure the image still ran as linux/amd64 correctly.
> search-blitz: build outside of docker

- internal/cmd/search-blitz/config.go
- internal/cmd/search-blitz/config_test.go
- internal/cmd/search-blitz/main.go
- internal/cmd/search-blitz/prometheus.go
We have only ever had one group. I think this was introduced at a time when we thought we may have different groups of queries, but we ended up just relying on the query name for that.
Group was only used in local observability, but not in the metrics we record in the frontend. So this _might_ break the local grafana dashboard (which we can fix). But my main motivation was removing some of the log noise.
> search-blitz: remove group

- client/web/src/components/externalServices/ExternalServiceEditingDisabledAlert.tsx
- client/web/src/components/externalServices/ExternalServiceNode.tsx
- client/web/src/components/externalServices/ExternalServicePage.tsx
Closes #54974
Having a `View` label that leads to the `Edit` page (in a read-only mode) can be confusing to users. This PR ensures the label doesn't change and we toggle the button's disabled state instead.
* Start up your Sourcegraph instance.
* Ensure your code host connections are set via the `EXTSVC_CONFIG_FILE` environment variable.
* Navigate to the [code host connections](https://sourcegraph.test:3443/site-admin/external-services) page.
* The button label should be `Edit`, and it'll be disabled.
If the `EXTSVC_CONFIG_FILE` isn't set though, the button label will remain unchanged and will be enabled.
* Added a link to the docs in the Banner displayed when External Services can't be edited.
* Disabled the `Edit` and `Delete` button when editing is disabled for external services.
* …
> source: disable edit button for codehost connections when it's uneditable

- doc/integration/bitbucket_cloud.md
These were supported for a long time already, but we did not update this page in the past PRs.
tested locally, can also be [viewed here](https://docs.sourcegraph.com/@milan_bitbucket_cloud_docs/integration/bitbucket_cloud)
> docs: mark bitbucket cloud repo permissions as supported

- CHANGELOG.md
- client/web/src/components/externalServices/externalServices.tsx
- doc/integration/bitbucket_cloud.md
- internal/authz/providers/bitbucketcloud/provider.go
- internal/repos/bitbucketcloud.go
- internal/repos/bitbucketcloud_test.go
Closes #54968 
This PR does a few things to better the Bitbucket Cloud connection experience:
- Some docs have been updated to reflect the current Bitbucket Cloud setup experience
- Code host connections no longer automatically clone the repositories of the username the App Password belongs to
- Way-back-when, a user always had a personal workspace tied to their username. This is no longer the case, and newer Bitbucket Cloud accounts will always produce an error in the code host sync, because there is no workspace associated with their username
- Also removes the requirement for the `Account` scope on the App Password, and we use the List Repositories endpoint to verify a connection instead.
Update unit tests
> [bitbucket cloud] Code host connection updates

- cmd/gitserver/server/server.go
- cmd/gitserver/server/vcs_syncer_git.go
This commit fixes behaviour of `gitRepoSyncer.Fetch` function which previously always returned `nil` output and because of that no git command logs were stored into the DB.
Test plan:
Local sg run and test that the logs are stored in the DB and displayed on "Mirroring" page.
https://github.com/sourcegraph/sourcegraph/assets/94846361/8b87b98a-bf5b-480c-bfb2-2a8d9b7d94f0
> gitserver: return git command output when fetching a repo.

- BUILD.bazel
- dev/BUILD.bazel
- dev/write_generated_to_source_files.bzl
- doc/BUILD.bazel
- doc/admin/observability/BUILD.bazel
- monitoring/main.go
improve `write_generated_to_source_files` to:
- allow prefixes to be stripped from generated files
- specify a different destination
- handle being called from a different package than being next to the src target
This seemed like an easy change on the outset but it turned out to be quite involved. Some of the problems I encountered while doing this which required the above changes:
* monitoring-generator copies to a total different path in the repo route than what it normally outputs - ie. docs/alerts.md, docs/dashboard.md -> doc/admin/observability/
* `//monitoring:generate_config` outputs are local to it and AFAIK you can copy/move files to the parent package/dir
* The `//monitoring:generate_config` already does 90% of what we needed, but the outputs needed to be massaged a bit to fit …
> bazel: monitoring docs gen

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyOnboardingPanel.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/ui/Colors.java
Improved UI of the onboarding widget. closes https://github.com/sourcegraph/cody/issues/119
before:
now:
- No changes in the behaviour, green CI should be enough
> JetBrains: improve UI of the onboarding widget

- cmd/gitserver/shared/BUILD.bazel
- cmd/gitserver/shared/shared.go
- schema/schema.go
- schema/site.schema.json
Closes #55059
This PR makes the list of git commands that should be ignored for recording configurable via the site config setting.
* Add an entry to the `gitRecorder.ignoredGitCommand` array.
* Perform an operation that will execute that command inside of `gitServer`, check redis for the value associated with key `recording-cmd` and it shouldn't be part of the result.
> gitserver: make list of ignored git commands for recording configurable

- internal/repos/clone_url.go
- internal/repos/clone_url_test.go
We weren't including the `a/ `in the clone url for gerrit repos, which wasn't really a problem unless the gerrit repo's name started with an `a/`.
Manual
> fix bug for gerrit repos that have a/ at the start of their name

- client/web/BUILD.bazel
- cmd/frontend/BUILD.bazel
- enterprise/dev/ci/internal/ci/bazel_operations.go
Fixes #54819
The oss bundle is not used in any artifact we publish. I'm assuming if that if theres is any error, because the enterprise bundle is built on top of it, it would catch them. 
This shaves off having to build the bundle entirely, because any client code change means we're building two bundles in CI, just because we're running a few tests against those. 
So to make this happen, I tagged the relevant test targets to be manual, see the PR diff. 
In order to see what will ultimately be built in CI, I've used the following command
```
$ bazel query 'deps(tests(//...) except attr("tags", "manual", //...))' --output=label --keep_going | grep "client/web:bundle"
//client/web:bundle-enterprise
//client/web:bundle-enterprise.webpack.config.js
//client/web:bundlesize-report …
```
> ci: avoid building the oss bundle 

- cmd/frontend/graphqlbackend/completions.graphql
There was a bug in the graphql API backend for completions, where although the Go backend was set up to handle Fast completions the schema did not accurately reflect that.
I want to use this API with fast completions for various prototypes, so fixing this.
Logically matches the parameters [defined here](https://github.com/sourcegraph/sourcegraph/blob/429c6202041416d60daadc58cbadebbd578226e6/cmd/frontend/graphqlbackend/completions.go#L9-L12) and `sg start app` works. Existing CI tests will confirm it builds as expected.
> graphqlbackend: fix Fast completions parameter

- enterprise/cmd/frontend/internal/completions/resolvers/resolver.go
- internal/completions/httpapi/handler.go
- internal/completions/httpapi/observability.go
We need to fine tune model speed and right now, multi-line and single-line requests are logged without any way to distinguish them making it hard to reason about runtime performance.
This adds the `maxTokensToSample` config to the honeycomb logger so we can filter out only the ones for single-line (which will have this value set to `100`).
I need help with this. This change was not tested yet.
> Cody: Log max tokens to sample in Honeycomb

- cmd/gitserver/server/cleanup.go
- cmd/gitserver/server/cleanup_test.go
- internal/database/gitserver_repos.go
First, this is not a terribly huge problem, as this cleanup job is off by default. But while debugging something else, this struck me as potentially dangerous. In case of a DB outage or broken query, we would drain the entire gitserver disk here slowly because repo will be nil when general connectivity issues occur. To fix this, we add an error check and only do this for not found errors. I also dropped a duplicative log message. The cleanup function returning an error already logs all the relevant details.
Just a slight refactor to error checking, trusting CI and code review with this.
> gitserver: Don't delete repos when DB is down

- enterprise/cmd/embeddings/shared/BUILD.bazel
- enterprise/cmd/embeddings/shared/main.go
- enterprise/cmd/embeddings/shared/main_test.go
- enterprise/cmd/frontend/internal/embeddings/resolvers/resolvers.go
- internal/embeddings/BUILD.bazel
- internal/embeddings/client.go
- internal/embeddings/context_detection.go
- internal/embeddings/context_detection_test.go
- internal/embeddings/mocks_temp.go
We are making an RPC call to the embeddings service even though it's a stateless, importable function. This just calls the funtion directly from the resolver instead so we can skip all the surface area introduced by the RPC.
Existing tests, plus manual test that I can get the GraphQL call to return both true and false.
> Embeddings: make IsContextRequiredForChatQuery not an RPC call

- internal/database/repo_kvps.go
This just removes some leftover `fmt.Println` statements, presumably from debugging. However, now they're littering the logs whenever metadata is used.
Tested that the logs were clean when adding or reading metadata.
> Repo metadata: remove stray printlns

- cmd/gitserver/server/server.go
- cmd/gitserver/server/vcs_packages_syncer.go
- cmd/gitserver/server/vcs_packages_syncer_test.go
- cmd/gitserver/server/vcs_syncer.go
- cmd/gitserver/server/vcs_syncer_git.go
- cmd/gitserver/server/vcs_syncer_mock_test.go
- cmd/gitserver/server/vcs_syncer_perforce.go
- internal/wrexec/BUILD.bazel
- internal/wrexec/recording_cmd.go
Test plan:
Local sg run and test that one Redis list is created and filled for each repo.
Closes https://github.com/sourcegraph/sourcegraph/issues/55058
> gitserver: record git operations in separate Redis lists for each repo.

- client/web/BUILD.bazel
- client/web/src/components/fuzzyFinder/FuzzyActions.tsx
- client/web/src/components/fuzzyFinder/FuzzyFiles.test.ts
- client/web/src/components/fuzzyFinder/FuzzyFiles.tsx
- client/web/src/components/fuzzyFinder/FuzzyFinder.mocks.tsx
- client/web/src/components/fuzzyFinder/FuzzyFinder.story.tsx
- client/web/src/components/fuzzyFinder/FuzzyFsm.ts
- client/web/src/components/fuzzyFinder/FuzzyModal.tsx
- client/web/src/components/fuzzyFinder/FuzzyQuery.ts
- client/web/src/components/fuzzyFinder/FuzzyTabs.tsx
- client/web/src/fuzzyFinder/CaseInsensitiveFuzzySearch.ts
- client/web/src/fuzzyFinder/FuzzySearch.ts
- client/web/src/fuzzyFinder/WordSensitiveFuzzySearch.ts
Previously, it was not possible to navigate straight to a specific line number with the "Files" tab of the fuzzy finder. This commit adds the ability to specify a line number with a `:NUMBER` suffix. This feature makes it possible to copy-paste error messages that use the `FILE:LINE:COLUMN` format and quickly open the location with the fuzzy finder.
- New storybook test
- New unit tests for query parsing
> Fuzzy finder: allow line number at the end of a filename

- CHANGELOG.md
- deps.bzl
- go.mod
- go.sum
This update includes an optimization to avoid IO when looking up posting lists. The target is attribution search. The full list of commits is:
- 34f694c386 maximise distance between ngrams
- 1d71fd0226 ci: remove sync-zoekt step
- cbe083c969 remove ZOEKT_ENABLE_LAZY_DOC_SECTIONS
- 0aefb15ec4 rename ngrams to contentNgrams
- b7e5070bfb indexdata: read posting list iff all ng exist
Test Plan: CI
> zoekt: update with posting list IO optimization

- internal/extsvc/gerrit/account.go
Closes #55035
Fixes a minor display bug where the username and display name of gerrit accounts aren't properly handled.
Visual
> [gerrit] Fix account security page display bug

- internal/database/users_builtin_auth_test.go
This fixes #46510 by re-enabling the test and fixing its flakiness.
Test was flaky because it was `t.Parallel` but used `conf.Mock`, which writes to a global var.
So I removed `t.Parallel`, which fixes the data race.
But I also removed the `time.Sleep`, beacuse we don't need that. We can just reset the time.
- Ran the tests
> database: re-enable flaky test & remove sleep

- doc/admin/config/email.md
- internal/conf/computed.go
- internal/conf/computed_test.go
- schema/site.schema.json
This fixes #54984 by setting a default value for `email.senderName` and documenting the setting.
I also changed the docs to have valid syntax and changed from `domain.com` to `example.com`, which is the preferred way to refer to example emails.
- New unit test
> conf: add docs and default value for email.senderName

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowFactory.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/AssistantMessageWithSettingsButton.java
- client/jetbrains/src/main/java/com/sourcegraph/config/GoToPluginSettingsButtonFactory.java
- client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java
- client/jetbrains/src/main/java/com/sourcegraph/find/HeaderPanel.java
closes https://github.com/sourcegraph/cody/issues/141
- In the cody toolbar cogwheel menu new item should be displayed "Cody Settings..." which opens IntelliJ Cody settings window
> JetBrains: add go to settings from the cogwheel menu in the toolbar

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/CodyAutoCompleteItemProvider.java
- Decreased the parallel autocomplete request count from 3 to 1.
- Removed check for mid-word position to enable displaying completions mid-word.
Tested it, and it still works. Didn't do any benchmarking this time because we did it in VS Code, and it was significant, so I'm expecting the same speedup.
> JetBrains: Improve perceived autocomplete performance

- cmd/symbols/build-ctags.sh
- dev/ctags-install.sh
- dev/universal-ctags-dev
Fix a small typo that inverted a predicate and let to always build the docker container for ctags. 
Fixes https://github.com/sourcegraph/devx-support/issues/110
locally tested
> local: fix a bug that prevented using the native ctags binary

- internal/httpcli/client.go
Makes it easier to query, especially in Cloud Trace.
n/a
> httpcli: record retries on span

- internal/httpcli/client.go
Goofed this up, because this is called until retry is false the span always records false 🤦 
n/a
> httpcli: fix retry attribute

- internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
- internal/codeintel/codenav/internal/lsifstore/metadata_by_position.go
- internal/database/schema.codeintel.json
- internal/database/schema.codeintel.md
- internal/oobmigration/migrations/codeintel/scip/symbols_migrator.go
- internal/oobmigration/migrations/codeintel/scip/symbols_temp_tables.go
- migrations/codeintel/1689175157_update_scip_symbol_tables/up.sql
- migrations/codeintel/squashed.sql
Changes in this PR include:
- `codeintel_scip_symbols_lookup_leaves.fuzzy_descriptor_suffix_id` nullable, and making it so that we only write the value when it differs from the `descriptor_suffix_id`. These two values being equal is the common case so we save about 50% storage by effectively removing this column from the leaves table. This also allows us to only index non-null values in a partial index, so we're not also storing the same value in two indexes (another 50% savings - _wow 100% savings!_). This comes at the cost of requiring a second search condition when querying for `fuzzy_descriptor_suffix_id`.
- Replace the descriptor suffix indexes, which were overlapping, with an index that stores always-reversed values. This allows us to do efficient suffix searches, but storing it as …
> scip: optimize migrator, index size

- sg.config.yaml
This was excluded for historical reasons that no longer apply. This will reduce confusion when people try to start code insights locally.
Code Insights starts with `sg start enterprise`
> enable code insights in sg start enterprise

- cmd/cody-gateway/internal/httpapi/BUILD.bazel
- cmd/cody-gateway/internal/httpapi/handler.go
For the most part we're seeing lower-than-expected concurrent requests reported by the metric, I think we want to use UpDownCounter instead - concurrent bag items is explicitly listed as a use case: https://opentelemetry.io/docs/specs/otel/metrics/api/#updowncounter
Same as https://github.com/sourcegraph/sourcegraph/pull/55134
> cody-gateway: instrument upstream requests with UpDownCounter

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/api/ChatUpdaterCallbacks.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatBubble.java
Related to https://github.com/sourcegraph/cody/issues/231 and https://github.com/sourcegraph/cody/issues/256
Doesn't really fix either issue, but makes things somewhat better (?)
Before:
https://github.com/sourcegraph/sourcegraph/assets/18601388/5168116d-ec3d-44b0-b377-3598095605ba
After these changes:
https://github.com/sourcegraph/sourcegraph/assets/18601388/209f941d-e399-464a-b4b8-2e8dffe7d587
Notice how the bottom part of the scroll is no longer jumping (but the top still is).
What has been done here:
- streaming chat message updates now are discarded if they're shorter than the previous streaming message handled (to prevent messages being handled out-of-order, we were just doing fire-and-forget updates as they came before)
- the hacky scrolling to the bottom got replaced with a more …
> JetBrains: Cody: Partially improve the chat scroll panel flickering

- internal/txemail/txemail.go
This is a follow-up to #55139 and _actually_ uses the new value I added.
- N/A
> Use `conf.EmailSenderName` when rendering email

- internal/gitserver/addrs.go
- schema/schema.go
- schema/site.schema.json
Part of #54741 and follow up on #55001.
In this PR we make two changes:
1. Add a new site config `experimentalFeatures.useGitserverAddressLookupCache`
2. Use the site config to bypass the cache if it is explicitly set to `false
In #55001 we added DB reads to the repository address lookup code along with a cache to support git deduplication in the future. We want to test the impact on a production instance with and without the cache.
On the left we have the cache miss metric and on the right the cache hit metric. Notice how the cache hit metric starts trending down to 0 only after I set `false` in the config explicitly.
And again notice how the cache hits start showing up again and the cache miss has more or less stopped showing up after I removed the config after some time.
Simulated this …
> gitserver: Use address lookup cache conditionally 

- client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
- client/web/src/site-admin/backend.ts
- cmd/frontend/graphqlbackend/BUILD.bazel
- cmd/frontend/graphqlbackend/repositories.go
- cmd/frontend/graphqlbackend/repository_stats.go
- cmd/frontend/graphqlbackend/schema.graphql
- internal/database/repos.go
- internal/embeddings/background/repo/mocks_temp.go
- internal/embeddings/background/repo/store.go
We show the number of embedded repos in the top-right of **Site-Admin > Repositories** and make it possible to filter repositories based on whether they have been embedded or not (click on number or select from status dropdown).
With the new filter, admins can now, for the first time, get an overview of the available embeddings.
Test plan:
- the implementation follows closely that for "indexed"
- I verified locally that the behavior of the filter and the count of embedded repos matches the expectation (see video)
> site-admin: filter repos by embedding status

- enterprise/cmd/frontend/internal/authz/resolvers/resolver_test.go
- enterprise/cmd/frontend/internal/authz/resolvers/users.go
This fixes a nil panic reported in #39763.
When 0 users have access to a repository, this would panic in `(r *userConnectionResolver) compute(ctx context.Context)`.
The fix here is just moving the defensive check out of the condition so it applies regardless of whether an `after` is set or not.
I reworked the tests so I can inject how many users have access.
- New unit test
> authz resolvers: fix nil panic when 0 users are authorized

- cmd/gitserver/server/patch.go
- cmd/gitserver/server/server.go
- cmd/gitserver/server/server_grpc.go
- cmd/gitserver/server/server_test.go
- cmd/gitserver/server/serverutil.go
- cmd/gitserver/server/vcs_packages_syncer.go
- cmd/gitserver/server/vcs_syncer.go
- cmd/gitserver/server/vcs_syncer_git.go
- cmd/gitserver/server/vcs_syncer_mock_test.go
- cmd/gitserver/server/vcs_syncer_perforce.go
- dev/linters/unparam/BUILD.bazel
- internal/gitserver/adapters/BUILD.bazel
- internal/gitserver/adapters/git.go
- internal/gitserver/gitdomain/services_test.go
- internal/repos/perforce.go
Test plan:
CI.
Commands are wrapped in a same way as previously, so they will work.
Closes https://github.com/sourcegraph/sourcegraph/issues/55101
> gitserver: add recording for missed git commands.

- cmd/symbols/build-ctags.sh
This stuff is really messy, but this will at least unblock folks using ctags command. 
@davejrt is going to make this bunch of scripts completely irrelevant by getting Bazel to fetch the universal ctags binary as part of our Q3 effort to rework local env to use Bazel more. 
So, with that in mind, this PR is really the dumbest fix possible for the time being. Honnestly these scripts are messy, and should be deleted entirely anyway. 
> local: hotfix ctags mess with symbols

- internal/repos/store.go
This fixes #45776 by including the name of the repository in the error message. That would've saved us hours of debugging.
It's also fine to include this here, since these errors are only ever displayed to admins.
- N/A
> repos store: include name of repository in error message

- doc/admin/observability/dashboards.md
- monitoring/definitions/git_server.go
This fixes #44466 by removing a duplicate dashboard. As described in the ticket, this is already covered in the normal container dashboards.
Question: how do I regenerate the dashboards?
- N/A
> grafana: remove duplicated dashboard for gitserver

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatScrollPane.java
This cleans the errors I accidentally introduced in https://github.com/sourcegraph/sourcegraph/pull/55150
By fixing the auto-scrolling I broke the manual wheel scroll and mouse drag.
They should be working, an `AdjustmentEvent`'s `getValueIsAdjusting` is supposed to give you information whether an event is caused by the  user or the system. 
However, in the beautiful world of Swing, all data is suspect.
I did not find any by-design way of pairing adjustment events and mouse wheel scroll / mouse motion events.
It seems there just isn't one from a `JBScrollPane`'s perspective.
If anyone finds a better way, be welcome to override the changes from this PR.
What I'm doing instead is trying to guess that an adjustment event happening immediately after a mouse wheel event or a mouse drag event …
> JetBrains: Cody: Fix mouse wheel scrolling and manual mouse drag in the chat

- client/web/src/components/Breadcrumbs.tsx
- client/web/src/integration/repository.test.ts
- client/web/src/repo/FilePathBreadcrumbs.module.scss
- client/web/src/repo/FilePathBreadcrumbs.tsx
- client/web/src/repo/RepoHeader.module.scss
- client/web/src/repo/RepoHeader.story.tsx
- client/web/src/repo/RepoHeader.tsx
- client/web/src/repo/RepoRevisionContainer.tsx
- client/web/src/repo/blob/BlobPage.tsx
- client/web/src/repo/tree/TreePage.tsx
- client/wildcard/BUILD.bazel
- client/wildcard/src/components/Breadcrumbs/Breadcrumbs.module.scss
- client/wildcard/src/components/Breadcrumbs/Breadcrumbs.story.tsx
- client/wildcard/src/components/Breadcrumbs/Breadcrumbs.tsx
- client/wildcard/src/components/Breadcrumbs/index.ts
- client/wildcard/src/components/index.ts
Closes https://github.com/sourcegraph/sourcegraph/issues/54796
This PR adds a new smart file path breadcrumbs component. It works in a way that we render only a reasonable amount of filepaths and hide the part in the middle of the file path that doesn't fit in a given space width. The hidden items are still accessible through ... dropdown button.
Loom demo https://www.loom.com/embed/72a0ec19d0624ae4927a525294e08dc9?sid=7dc48532-943f-4eaa-8287-8aee3341dc79
| ------- | -------- |
| <img width="1095" alt="Screenshot 2023-07-13 at 20 41 34" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/97fdeff2-0be8-413b-ad92-a7aa43ed90dd"> | <img width="1095" alt="Screenshot 2023-07-13 at 20 36 01" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/fdbd0c28-7d …
> Blob UI: Improve file path breadcrumbs UI 

- internal/gitserver/addrs.go
- internal/grpc/defaults/defaults.go
See https://sourcegraph.slack.com/archives/C04HCK4K3DL/p1689969401765809 for more context.
This raises our global maximum message size that gRPC servers and clients are allowed to receive to 90 MB (up from 4MB). 4MB megabytes seems too restrictive for many of our use cases, and many projects (in the Slack message) seem to also increase their minimum. https://sourcegraph.com/search?q=context:global+MaxCallRecvMsgSize+-f:vendor+-r:grpc/grpc-go&patternType=standard&sm=1&groupBy=repo
However, at the same time we should strive to keep our message sizes as small as possible. I will prioritize adding additional Prometheus metrics to track this next week. 
Note: Our existing REST code effectively has no cap on message sizes, so we're still no worse off than we were before.
CI
> grpc: raise global default message size from 4MB to 90 MB

- internal/codeintel/uploads/internal/background/processor/BUILD.bazel
- internal/codeintel/uploads/internal/background/processor/job_worker_handler.go
- internal/codeintel/uploads/internal/background/processor/scip.go
- internal/codeintel/uploads/internal/background/processor/scip_test.go
- internal/codeintel/uploads/internal/lsifstore/BUILD.bazel
- internal/codeintel/uploads/internal/lsifstore/insert.go
- lib/codeintel/precise/types.go
Previously, we had a bunch of channels and goroutines, which
aren't necessary, since the invoking goroutine anyways processes
the documents one-by-one and writes them into the database
> uploads: Simplify code for streaming indexes

- client/web/src/storm/pages/SearchPage/TryCodySignUpCtaSection.module.scss
- client/web/src/storm/pages/SearchPage/TryCodySignUpCtaSection.tsx
Cody for JetBrains is actually out. Added it to the Cody landing.
Before:
After:
Waiting for reviews and CI
> Marked JetBrains "Coming soon" → experimental

- client/jetbrains/src/main/java/com/sourcegraph/cody/context/EmbeddingStatusView.java
A user was getting
<details>
<summary>this stack trace</summary>
com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=internal, containerState=DISPOSE_COMPLETED, componentStore=/Users/cptmo/Projects/internal) (disposed)
at com.intellij.serviceContainer.ComponentManagerImpl.checkState(ComponentManagerImpl.kt:201)
at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:593)
at com.intellij.openapi.fileEditor.FileEditorManager.getInstance(FileEditorManager.java:26)
**at com.sourcegraph.cody.editor.EditorUtil.getCurrentFile(EditorUtil.java:16)
at com.sourcegraph.cody.context.EmbeddingStatusView.updateEmbeddingStatusView(EmbeddingStatusView.java:88)**
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.j …
> JetBrains: Catch AlreadyDisposedException in EditorUtil

- client/wildcard/src/global-styles/highlight.scss
Previously, the dark syntax highlighthing theme didn't distinguish between string literals and string literal keys, or string literal escapes. For example, the object keys of a JSON or YAML file use the `StringLiteralKey` syntax kind, while string literal values use `StringLiteral`. By using the same color for both kinds, the dark theme made it difficult to read JSON/YAML files. This commit fixes the problem by using a different color, mirroring the behavior of the light theme, which also uses different colors for these kinds.
Manually tested with `SOURCEGRAPHDOTCOM_MODE=true SOURCEGRAPH_API_URL=https://sourcegraph.com sg start web-standalone`
**After**
**Before**
> Syntax highlighting: use different color for string escapes in dark theme

- CHANGELOG.md
Based on @csells feedback :)
- N/A
> changelog: update description for removed federation feature

- client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
This fixes an anoying behavior of the spinner on the **Site-Admin > Repositories** page.
**Current**
The spinner instantly shows up while we are fetching content. Ignoring that the other numbers don't show the spinner, this might be fine for very large instances, where fetching takes time, but on instances like s2 this just leads to a flickering repositories count in the top-left corner.
**Fix**
We move the spinner down to the top of the repositories list and only show it if loading takes longer than 300ms.
I visually inspected the change
> site-admin: fix spinner on repositories page

- internal/gitserver/addrs.go
- internal/grpc/defaults/defaults.go
(cherry picked from commit bce2029f622b1e652fe0624971d40f30943bd830)
This is a custom cherry-pick since https://github.com/sourcegraph/sourcegraph/pull/55209 's backport ran into merge conflicts: https://github.com/sourcegraph/sourcegraph/pull/55209#issuecomment-1646247112
CI
> grpc: raise global default message size from 4MB to 90 MB (#55209)

- cmd/frontend/graphqlbackend/recorded_commands.go
- cmd/frontend/graphqlbackend/recorded_commands_test.go
This PR fixes [a situation](https://github.com/sourcegraph/sourcegraph/pull/55210#issuecomment-1647804475) where the `gitRecorder` configuration isn't set on a Sourcegraph instance.
* Ensure `gitRecorder` isn't set in your site configuration
* Access any repository settings page and click on the `Logs` link
* You should be able to view the `Logs` page and a message saying there are no recorded commands for this repository.
> source: handle case when `gitRecorder` isn't configured on an instance

- client/shared/src/components/RepoLink.test.tsx
- client/shared/src/components/RepoLink.tsx
- client/vscode/src/webview/search-panel/alias/RepoFileLink.tsx
- client/web-sveltekit/src/lib/shared.ts
Closes [#54975](https://github.com/sourcegraph/sourcegraph/issues/54975)
I made an assumption here that the repository name will always be in the format `<hostname>/...`. That way we can assume that the repo name in the `displayRepoName` function will always contain at least one slash.
This P
| Before  | After  |
|---|---|
| <img width="954" alt="CleanShot 2023-07-20 at 13 58 30@2x" src="https://github.com/sourcegraph/sourcegraph/assets/25608335/79618455-cfee-48c2-9830-5dc6d68f104e">  | <img width="940" alt="CleanShot 2023-07-20 at 13 57 50@2x" src="https://github.com/sourcegraph/sourcegraph/assets/25608335/5e96750c-a3d5-4e26-a759-f89abe2ed277">  |
Add a mix of repos to external services with multiple amounts of slashes. In my case, I added Gerrit repos in the `gerrit.sgdev.org` …
> source: truncate hostname for repos regardless of how many slashes contained

- client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
- client/web/src/storm/pages/SearchPage/SimpleSearch.tsx
We truncate `argument` in dot-com, and only send public-argument. For the cloud pipeline, we get argument because it uses an allowlist of safe events.
Tested locally, events are sending both args.
> use public argument for simple search for dot-com

- internal/batches/state/BUILD.bazel
- internal/batches/state/state.go
- internal/batches/state/state_test.go
Found a slight bug. When an unknown perforce state occurs, it had "Gerrit" in the message. Fixed that and added tests.
Added Go tests.
> codesearch: Fix error message when unknown perforce change state

- CHANGELOG.md
This PR creates a section for `5.1.5` release and adds backported entries to the `5.1.5` section.
Changelog update
> changelog: Update Changelog for 5.1.5 release

- CHANGELOG.md
Forgot to add it in https://github.com/sourcegraph/sourcegraph/pull/53828
n/a
> changelog: Mention streaming ingestion of SCIP indexes

- BUILD.bazel
- dev/BUILD.bazel
- dev/sg/BUILD.bazel
- dev/sg/main.go
- dev/sg/root/root.go
- dev/sg/sg_help.go
- dev/sg/sg_start.go
- doc/BUILD.bazel
- doc/dev/background-information/sg/BUILD.bazel
- doc/dev/background-information/sg/reference.md
This removes the `go:generate` directive to generate `reference.md` to instead be generated with bazel ie. `bazel run //doc/dev/background-information/sg:write_cli_reference_doc` or `bazel run //dev:write_all_generated`
- Added flag `--no-dev-private` to disable checking for `dev-private` ... since in bazel we don't have access to it __easily__
- Added environment flag `SG_FORCE_REPO_ROOT` to set the repo root to a directory. This circumvents the auto repo detection since .. again ... in bazel there isn't an easy way to make the whole repo available. And for this command (generating help) it shouldn't be required, but a few commands determine the repo root at init time.
Executed locally + green ci
Closes #54834
> sg gen / bazel: port generation of reference from go to bazel

- client/shared/src/auth.ts
- client/shared/src/testing/integration/graphQlResults.ts
- client/web/BUILD.bazel
- client/web/src/LegacyLayout.tsx
- client/web/src/auth/CloudSignUpPage.tsx
- client/web/src/auth/PostSignUpPage.module.scss
- client/web/src/auth/PostSignUpPage.story.tsx
- client/web/src/auth/PostSignUpPage.test.tsx
- client/web/src/auth/PostSignUpPage.tsx
- client/web/src/auth/SignInPage.tsx
- client/web/src/auth/SignUpPage.tsx
- client/web/src/auth/__snapshots__/PostSignUpPage.test.tsx.snap
- client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
- client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
- client/web/src/communitySearchContexts/CommunitySearchContextPage.story.tsx
- client/web/src/enterprise/code-monitoring/testing/util.ts
- client/web/src/enterprise/searchContexts/SearchContextForm.story.tsx
- client/web/src/get-cody/GetCodyPage.tsx
- client/web/src/integration/insights/utils/override-insights-graphql-api.ts
- client/web/src/jscontext.ts
- client/web/src/marketing/toast/CodySurveyToast.module.scss
- client/web/src/marketing/toast/CodySurveyToast.tsx
- client/web/src/repo/components/TryCodyWidget/TryCodyWidget.tsx
- client/web/src/routes.constants.ts
- client/web/src/routes.tsx
- cmd/frontend/internal/app/jscontext/jscontext.go
- cmd/frontend/internal/app/verify_email.go
Implements `post-sign-up` flow on `sourcegraphDotCom`, mandating user to verify their email and fill up the cody survey before proceeding with using app.
  
[Figma](https://www.figma.com/file/DIk3eGdgKszigQVec7Y8SD/Frictionless-Cody?type=design&node-id=1617-37199&mode=design)
[Sourcegraph issue](https://github.com/sourcegraph/sourcegraph/issues/54465)
[Gitstart Ticket](https://clients.gitstart.com/sourcegraph/1/tickets/SGM-54465)
1. Run the sourcegraph app
2. Sign up for a sourcegraph account and it should redirect to the `/post-sign-up` page
3. In the `post-sign-up` page after validating email and filling the survey form it should take you to `/get-cody` page
4. Until the user has validated email and completed the survey form they are blocked in `/post-sign-up` page
> [SG-54465] : Simplify post signup flow SG-54465

- client/web/src/components/externalServices/ExternalServiceSyncJobNode.story.tsx
- client/web/src/components/externalServices/ExternalServiceSyncJobNode.tsx
The PR adds external service sync job state badge variants, so that different sync state statuses (failed, completed, etc) are visually quickly differentiated.
- Story added & screenshot test enabled
- `pnpm run storybook:web`
- Open http://localhost:9000/?path=/story/web-external-services-externalservicesyncjobnode--default
| --: | :-- |
| <img width="1297" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/6717049/eeaadd5e-b4d3-4b25-a71b-86529d9ce707">  | <img width="1297" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/6717049/20918b95-4f7c-44f7-8217-12d2aee449e1"> |
> feat(site-admin-ui): add extsvc sync job state badge variants

- internal/gitserver/search/diff_format.go
- internal/gitserver/search/diff_format_test.go
This fixes one of the invalid UTF8 errors by escaping invalid UTF8 bytes when we format the diff. This error accounts for roughly 80% of the reported instances of this error on sourcegraph.com (based on logs).
Added a unit test.
> gRPC: escape utf8 when formatting diff

- internal/database/migration/shared/data/cmd/generator/consts.go
- internal/database/migration/shared/data/stitched-migration-graph.json
- internal/database/migration/stitch/stitch.go
#55237 cleans up the database drift in `5.1`, while this PR does the same for the `main` branch.
Running the `cd internal/database/migration/shared && go run ./data/cmd/generator --write-frozen=false` should update the migration graph.
> cleanup database drifts

- cmd/symbols/squirrel/hover.go
- cmd/symbols/squirrel/local_code_intel.go
This sanitizes the two string fields we get from symbols, which are possible to be invalid utf8. We should likely skip symbols processing for non-utf8 files entirely since they are skipped in search, but that's a larger change.
I couldn't reproduce this locally because sg uses a weird configuration for symbols, but the change seems minimal and low risk, so the plan is to just make sure the errors go away.
> gRPC: sanitize symbols strings

- CHANGELOG.md
See https://github.com/sourcegraph/sourcegraph/pull/55292
N/A
> grpc: move localcodeintel changelog entry from unreleased to 5.1.5 section

- CHANGELOG.md
- doc/cody/explanations/code_graph_context.md
- doc/cody/explanations/enabling_cody_enterprise.md
- internal/completions/client/BUILD.bazel
- internal/completions/client/azureopenai/BUILD.bazel
- internal/completions/client/azureopenai/openai.go
- internal/completions/client/azureopenai/openai_test.go
- internal/completions/client/client.go
- internal/conf/computed.go
- internal/conf/computed_test.go
- internal/conf/conftypes/consts.go
- internal/embeddings/embed/BUILD.bazel
- internal/embeddings/embed/client/azureopenai/BUILD.bazel
- internal/embeddings/embed/client/azureopenai/client.go
- internal/embeddings/embed/client/azureopenai/client_test.go
- internal/embeddings/embed/embed.go
- schema/site.schema.json
This adds experimental support for Azure OpenAI as an embeddings and completions provider.
I added some experimental docs for it, and ran through it with a bunch of repos and queries, seems to be on-par with the OpenAI providers mostly. Only thing is that we make more requests for embeddings, because Azure doesn't yet support the batch API.
Test plan
Verified manually using our Azure deployment.
> [Backport 5.1] Implement experimental Azure OpenAI provider for completions and embeddings

- CHANGELOG.md
- client/web/src/components/gitHubApps/CreateGitHubAppPage.tsx
- enterprise/cmd/frontend/internal/auth/githubappauth/middleware.go
- enterprise/cmd/frontend/internal/auth/githubappauth/middleware_test.go
Firefox's default settings do not forward Referer headers for privacy reasons. This means that GitHub App setups fail when done using Firefox.
This PR adds the GitHub App's base url to the state we store in Redis, so that we no longer rely on the browser sending the Referer header.
Tests updated.
> [github app] Encode App baseURL in state instead of using Referer

- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/bazel_operations.go
- enterprise/dev/ci/internal/ci/pipeline.go
- enterprise/dev/ci/push_all.sh
Follows up from https://github.com/sourcegraph/sourcegraph/pull/55270 and pushes the images to dockerhub
Pushed image from this branch to docker hub https://hub.docker.com/layers/sourcegraph/frontend/docker-images-candidates-notest-dt-fix_regex_235989_2023-07-25_5.1-703c2e35f1dd/images/sha256-df53e963fc404d504d6da491ee5c634c49c2d6d18426a28948c3e737ce2016c4?context=explore
> ci: fix regex to push images to dockerhub

- client/web/src/repo/RepoRevisionSidebarFileTree.tsx
I was looking into #41750 and had to laugh out loud when I got to the last file in the sidebar, though "huh, why is that one a folder?", opened it and was greeted with an error message.
This here fixes the issue by not treating the error message as a child of the previous entry, which turns the previous entry into a folder.
- Add https://github.com/sourcegraph-testing/lotta-files to my instance
- Open repo
- Open file sidebar
> file sidebar: don't hide error by turning last file into folder

- dev/oci_deps.bzl
Update all base images to patch new vulnerabilities for the 5.1.5 release.
> Update all wolfi base images

- dev/BUILD.bazel
- dev/sg/BUILD.bazel
- lib/batches/schema/BUILD.bazel
- lib/batches/schema/batch_spec_stringdata.go
- lib/batches/schema/changeset_spec_stringdata.go
- lib/batches/schema/gen.go
- lib/batches/schema/gen/BUILD.bazel
- lib/batches/schema/gen/gen.go
Moved `stringdata.go` to `gen/gen.go` since that made it a whole lot easier to invoke it. Otherwise I would have had to [this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/go_stringer.bzl?L22-24)
Executed `bazel run //lib/batches/schema:write_generated_code` locally and `//dev/wrtite_all_generated`
Closes #54825
> bazel: replace go:generate with bazel target for schema changes

- doc/dev/index.md
This PR fixes the 404s in the ToC of our [Development docs](https://docs.sourcegraph.com/dev).
- [Preview Link Here](https://docs.sourcegraph.com/@fix-dev-docs-404/dev)
- [Background Context](https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1690327694999029)
* Check links
> Fix 404s in ToC Development docs

- client/web/src/site-admin/packages/components/MultiPackageForm.tsx
- client/web/src/site-admin/packages/components/SinglePackageForm.tsx
We currently limit packages to 1000. This PR fixes a bug that causes React to throw Minified React error #31 when trying to add 1000+ packages.
> Fix nextFetchLimit for packages exceeding 1000

- .gitignore
- client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
Reduce polling interval to 2s from 5s for embedding status indicator.
- sg start dotcom
- visit /cody
- add repos to context
- check network tab for repos embeddings status gql request every 2 seconds.
> Update polling interval for embeddings status indicator

- CHANGELOG.md
Added an entry that was supposed to be in 5.1.5 but was in 5.1.4
> release: 5.1.5 changelog update

- doc/_resources/assets/docsite.css
- doc/_resources/templates/document.html
- doc/_resources/templates/root.html
- doc/getting-started/index.md
- doc/index.md
- doc/sidebar.md
Our documentation site requires a significant design and structural overhaul. While I am diligently working on the progress toward achieving that goal, I am currently implementing some preliminary design and structural changes. These changes are aimed at rendering our documentation visually appealing, contemporary, clean, and well-organized in the interim period.
This PR ships the following design and structural changes to our docs website:
* Check links
> 🎨 Docs Design and Structure changes

- CHANGELOG.md
- internal/authz/providers/gitlab/BUILD.bazel
- internal/authz/providers/gitlab/oauth_test.go
- internal/authz/providers/gitlab/sudo.go
- internal/authz/providers/gitlab/sudo_test.go
- internal/extsvc/gitlab/projects.go
- internal/repos/gitlab_test.go
- internal/repos/testdata/gitlab-repos.json
- internal/repos/testdata/golden/GitLabSource_makeRepo_path-pattern
- internal/repos/testdata/golden/GitLabSource_makeRepo_simple
- internal/repos/testdata/golden/GitLabSource_makeRepo_ssh
- internal/repos/testdata/sources/GITLAB/TestGitlabSource_ListRepos
- internal/repos/testdata/sources/TestGitlabSource_ListRepos.yaml
Original Slack thread [here](https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1687969384430849)
We use a `min_access_level=20`  check on GitLab project queries, because `access_level` 10 is GUEST, and users with GUEST access cannot see repo contents, so we don't want to give access to those repos on Sourcegraph
HOWEVER, for Internal repos on GitLab, users can see the contents of the repo depending on how the repo is configured, regardless of their access level. So this puts us in a conundrum. If we have `min_access_level=20`, users can't see repos they should be able to see, but if we remove it, users can see repos they shouldn't be able to see
Adds a feature flag named "gitLabProjectVisibilityExperimental". When set to true:
@indradhanush  and I diffed some responses from the GitLab …
> [gitlab] Fix GitLab internal project visibility

- cmd/frontend/graphqlbackend/schema.graphql
- internal/database/event_logs.go
Follow on to https://github.com/sourcegraph/sourcegraph/pull/55126 to ensure events actually get logged in postgres, and that the LogEvent mutation accepts the new params (in addition to the LogEvents mutation, which for some reason has a different param list—something to update in the future)
tested locally
> Ensure new event parameters get logged in postgres

- CHANGELOG.md
- doc/admin/executors/deploy_executors_kubernetes.md
- enterprise/cmd/executor/internal/config/config.go
- enterprise/cmd/executor/internal/config/config_test.go
- enterprise/cmd/executor/internal/run/util.go
- enterprise/cmd/executor/internal/worker/command/kubernetes.go
- enterprise/cmd/executor/internal/worker/command/kubernetes_test.go
Be able to add annotations to Pods spawned by Jobs.
Unit tests and manual testing.
> executors: Be able to add annotations to job pods

- .buildkite/hooks/pre-exit
Fixes the error
```
/buildkite/builds/buildkite-agent-bazel-85dff99848-7lgqm-1/sourcegraph/sourcegraph/.buildkite/hooks/pre-exit: line 19: 0: command not found
--
  | /buildkite/builds/buildkite-agent-bazel-85dff99848-7lgqm-1/sourcegraph/sourcegraph/.buildkite/hooks/pre-exit: line 22: -gt: command not found
```
Check the pre-exit output on any bazel agent in this PR
> ci: fix pre-exit hook

- cmd/searcher/internal/search/hybrid.go
- cmd/searcher/internal/search/search_structural.go
- cmd/searcher/internal/search/search_test.go
This sanitizes sources of the `Content` field of `ChunkMatch` to ensure that it is always valid UTF-8. Example error [here](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-07-27T13:22:16.449412057Z;duration=P1D;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Aresource.labels.location%3D%22us-central1-f%22%0Aresource.labels.cluster_name%3D%22cloud%22%0Aresource.labels.namespace_name%3D%22prod%22%0AjsonPayload.InstrumentationScope%3D~%22gRPC.internal.error.reporter%22%0Atimestamp%3D%222023-07-27T13:22:16.449412057Z%22%0AinsertId%3D%22koc2gxbcll0u44uv%22?project=sourcegraph-dev). 
The underlying issue is that searcher does not exclude utf8 files when searching, so we can't guarantee that the contents are valid utf8. However, …
> gRPC: sanitize utf8 in searcher

- cmd/frontend/graphqlbackend/graphqlutil/BUILD.bazel
- cmd/frontend/graphqlbackend/graphqlutil/slice_connection_resolver.go
- cmd/frontend/graphqlbackend/graphqlutil/slice_connection_resolver_test.go
- cmd/frontend/graphqlbackend/recorded_commands.go
- cmd/frontend/graphqlbackend/recorded_commands_test.go
- cmd/frontend/graphqlbackend/schema.graphql
[Walkthrough](https://www.loom.com/share/8278ed0143af4f3d8734a69dafce91b8)
This PR introduces a slice connection resolver that can be used to paginate slices. I added this under the `graphqlutil` package because it fulfills an interface similar to that of the `ConnectionResolver`.
```graphql
type SliceConnectionResolver[T, any] interface {
Nodes(ctx context.Context) []T
TotalCount(ctx context.Context) int32
PageInfo(ctx context.Context) *PageInfo
}
```
This ensures we can adequately paginate the `RecordedCommands` field on the `RepositoryResolver`.
This is particularly useful because we get a slice of byte slice from redis and need to transform that into `RecordedCommandResolver`.
* Navigate to the API console
* Run a GraphQL query to fetch the recorded commands for any repository of your …
> git-debuggability: paginate recorded commands

- dev/sg/internal/run/run.go
Noticed while waiting for `symbols`:
- N/A
> sg: fix formatting errors in waitingMessages

- cmd/gitserver/shared/shared.go
- schema/schema.go
- schema/site.schema.json
I have pretty several repos on my local Sourcegraph instance, and I'll like to record commands on all of them instead of adding each of them one at a time to the site config.
* Update your site-config to include the `gitRecorder` configuration. 
* Update the `repos` array to include a wildcard
```json
"gitRecorder": {
"size": 200,
"repos": ["*"]
},
```
* Recorded commands will be stored on all repos.
> git-debuggability: allow site-admins configure recorded commands on all repositories

- dev/release/templates/patch_release_issue_template.md
Release template update.
* Removed the instruction to cherry-pick commits from `main` since we're now handling patch releases via backports.
* Added the full hyperlink for batch changes created so folks can click on it and go to the exact batch change for that release.
> release: update patch release template

- doc/admin/external_service/bitbucket_server.md
Verified locally that the docs render OK.
The docs changes [can be seen online here](https://docs.sourcegraph.com/@milan_update_bitbucket_docs/admin/external_service/bitbucket_server#repository-permissions).
> docs: update bitbucket server setup instructions for v7.20 and above

- internal/codeintel/autoindexing/internal/inference/service.go
- internal/codeintel/autoindexing/internal/store/BUILD.bazel
- internal/codeintel/autoindexing/internal/store/config_inference.go
- internal/codeintel/autoindexing/internal/store/config_inference_test.go
- internal/codeintel/autoindexing/service.go
- internal/luasandbox/sandbox.go
We recently had an issue where an invalid Lua script was put into the UI, causing knock off effects in several places.
This ensures that the script at least _parses_ before saving it. Not bulletproof, but should prevent some of the similar situations.
- unit tests
> Don't save inference scripts that fail to parse

- client/web/src/enterprise/codeintel/configuration/components/inference-form/CommandInput.tsx
- client/web/src/enterprise/codeintel/configuration/components/inference-form/InferenceForm.module.scss
Before (form stretches to the right into infinity)
After (if the field is read only, we wrap, if not read only, we _don't_ stretch the form anyways)
N/A
> Wrap CommandInput if the field is marked as read only

- internal/luasandbox/libs/paths.go
- internal/luasandbox/libs/paths_test.go
A simple `ancestorDirs("/")` causes an infinite loop and then a deadline error in the worker when inferring jobs.
Unit tests
> Fix ancestors calculation infinite loop

- doc/_resources/assets/docsite.css
- doc/cody/index.md
This PR ships improvement to the main Cody docs overview page with the following revamped changes:
- Improvements to the page information architecture
- Placement of callouts buttons and user-driven actions
- Simplify brand tone and overall grammar, vocab
- Remove fluff and inconsistent content structures
- [View here →](https://docs.sourcegraph.com/@cody-docs-pr1/cody)
https://sourcegraph.slack.com/files/U05EH1A6Y3F/F05JWJ0D75Z/sg.mp4
- Check links
> Docs improvements to the main Cody page

- doc/cody/index.md
Make section headings sentence case in Cody docs.
- [Slack thread](https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1690572986358889?thread_ts=1690566601.403829&cid=C01DXLN3D0T)
- Check links
> Fix headings in Cody docs — Make them sentence cased

- doc/_resources/assets/docsite.css
Increases padding on getting started sections of the documentation 
Manually review the new padding
> Docs: Improve padding on getting started buttons

- internal/gitserver/addrs.go
- internal/gitserver/client.go
It is not used.
Follow up to #55078.
- CI with main-dry-run
- Local testing
> internal/gitserver: Remove ConnForRepo from ClientSource interface

- client/web/src/repo/RepoContainer.tsx
While working on #55210 I noticed that the repo settings `{repo}/-/settings` route is accessible to non-site-admins (Also raised by Thorsten [here](https://github.com/sourcegraph/sourcegraph/pull/55210#discussion_r1272188597)). 
This PR adds some gating to the repo settings route to ensure they're only registered when the currently authenticated user is a site administrator.
| Before  | <img width="1499" alt="CleanShot 2023-07-31 at 14 16 59@2x" src="https://github.com/sourcegraph/sourcegraph/assets/25608335/348864b9-530d-49cc-9b66-6cba52da8ea1">  |
|---|---|
| After  | ![CleanShot 2023-07-31 at 14 15 44](https://github.com/sourcegraph/sourcegraph/assets/25608335/b6a61c44-0bcf-4a4e-9c28-62487d9043d7)  |
* Sign in to a Sourcegraph instance as a non site-admin
* Navigate to the …
> source: guard repo settings routes for admins

- cmd/frontend/graphqlbackend/external_services.go
- cmd/frontend/graphqlbackend/external_services_test.go
- cmd/frontend/graphqlbackend/schema.graphql
- internal/database/external_services.go
- internal/database/external_services_test.go
This is a prerequisite to https://github.com/sourcegraph/sourcegraph/pull/55392, where we decided that we need an `all external services for a Repo ID` query.
Test plan:
Database tests added.
GraphQL tests added.
Part of https://github.com/sourcegraph/sourcegraph/issues/45722.
> extsvc: add filtering by repository ID.

- client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
Fixes a bug where the search page content was getting affected by a disabled simple search flag. Note: this is not live in the 5.0 branch, so only made it to dotcom for a few days.
Flag disabled
Flag enabled, toggled off
Flag enabled, toggled on
> simple-search: fix the feature flag removing query examples when flag is disabled

- cmd/frontend/graphqlbackend/client_configuration.go
- cmd/frontend/internal/httpapi/BUILD.bazel
- cmd/frontend/internal/httpapi/httpapi.go
- cmd/frontend/internal/httpapi/internal.go
- internal/api/internalapi/BUILD.bazel
- internal/api/internalapi/client.go
- internal/conf/BUILD.bazel
- internal/conf/computed.go
This removes an unnecessary internal endpoint. Basically, `schema.ClientConfiguration` is the only consumer of `conf.*Configs()`, which are the only consumers of `internalClient.ExternalServiceConfigs`, which just hits the database and pulls the URL off the config.
So, rather than calling an internal API from `frontend`, which is just served by `frontend`, this PR updates `schema.ClientConfiguration` to just hit the database directly for this information, allowing us to get rid of one of the few remaining internal APIs.
This is an API that was slated to be converted to gRPC, so I'd rather not convert things we can just delete.
Tested locally that the API call worked as expected.
> Backend: remove unnecessary internal API for external services

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/context/EmbeddingStatusView.java
Stop generating button moved to controls panel from chat panel to avoid text jumping when finished generation of the message. Button is displayed always in the same place
- Text in the chat should not jump when stop generating button is hidden after finished message generation
> JetBrains: display stop generating button in controls panel to avoid text jumping in the chat

- internal/api/BUILD.bazel
- internal/api/api.go
- internal/api/api_test.go
- internal/gitserver/search/lazy_commit.go
- internal/gitserver/search/search.go
- internal/gitserver/search/search_test.go
This sanitizes the output of `git` for search so that invalid utf8 is converted to valid utf8. This fixes some more errors that were showing up on sourcegraph.com.
Tested that the two sources of the errors no longer error. Existing unit tests for regressions. Added a test for NewCommitID. Added an integration test.
> gRPC: sanitize utf8 for commit parsing

- internal/database/event_logs.go
The makeDateTruncExpression converter was truncating dates before converting to UTC. This introduced timezone shift errors for non-UTC dates.
This change updates the converter to first convert the date to UTC, then perform the truncation.
Verified on s2 that makeDateTruncExpression now behaves correctly.
> [Backport 5.1] internal/event_logs: fix timezone handling

- cmd/frontend/graphqlbackend/client_configuration.go
- cmd/frontend/internal/httpapi/BUILD.bazel
- cmd/frontend/internal/httpapi/httpapi.go
- cmd/frontend/internal/httpapi/internal.go
- internal/api/internalapi/BUILD.bazel
- internal/api/internalapi/client.go
- internal/conf/BUILD.bazel
- internal/conf/computed.go
This removes an unnecessary internal endpoint. Basically, `schema.ClientConfiguration` is the only consumer of `conf.*Configs()`, which are the only consumers of `internalClient.ExternalServiceConfigs`, which just hits the database and pulls the URL off the config.
So, rather than calling an internal API from `frontend`, which is just served by `frontend`, this PR updates `schema.ClientConfiguration` to just hit the database directly for this information, allowing us to get rid of one of the few remaining internal APIs.
This is an API that was slated to be converted to gRPC, so I'd rather not convert things we can just delete.
(cherry picked from commit 7265e0428e0854bb5ff41004a77c1d06dfac5efc)
Tested on merge to main
> [Backport 5.1]: remove unnecessary internal API for external services (#55450)

- client/BUILD.bazel
- client/web-sveltekit/package.json
- client/web-sveltekit/src/lib/featureflags/api.ts
- client/web-sveltekit/src/lib/featureflags/index.ts
- client/web-sveltekit/src/lib/featureflags/stores.test.ts
- client/web-sveltekit/src/lib/featureflags/stores.ts
- client/web-sveltekit/src/lib/stores.ts
- client/web-sveltekit/src/lib/utils/__snapshots__/time.test.ts.snap
- client/web-sveltekit/src/lib/utils/time.test.ts
- client/web-sveltekit/src/lib/web.ts
- client/web-sveltekit/src/routes/+layout.svelte
- client/web-sveltekit/src/routes/+layout.ts
- client/web-sveltekit/src/testing/mocks.ts
- client/web-sveltekit/src/testing/setup.ts
- client/web-sveltekit/svelte.config.js
- client/web-sveltekit/tsconfig.json
- client/web-sveltekit/vite.config.ts
- pnpm-lock.yaml
This PR adds a new store to make feature flags available throughout the app. Unlike the implementation in the web app, this implementation fetches all user flags when the page loads and updates them in intervals.
In the future we might have to add more functionality to force update the flags, but we can add those as needed.
Overriding feature flags via the URL is not supported yet (but I guess I will use the same approach as the web app).
This PR also updates the testing setup to make testing simpler and more deterministic:
- Faker is now automatically initialized with a fixed reference date.
- Functionality for mocking feature flags has been added
- Added helpers for using fake timers with a fixed reference/system date (it turned out that enabling fake timers by default doesn't work well …
> sveltekit: Add support for feature flags (and improve testing)

- client/web-sveltekit/src/lib/wildcard/Badge.module.scss
- client/web-sveltekit/src/lib/wildcard/Badge.svelte
- client/web-sveltekit/src/lib/wildcard/index.ts
- client/web-sveltekit/src/stories/Badge.stories.ts
- client/web-sveltekit/src/stories/BadgeExample.svelte
This PR adds the bade wildcard component to the prototype.
Whenever styles should be "shareable" it's easier to use CSS modules rather than Svelte `<style>` tags. This time I copied the module but I could also reuse the existing one from the wildcard library (still trying to figure out how to do that properly going forward).
Similar to Button, this component allows to customize the DOM structure via a "custom" slot which gets passed the generated class names. (whether or not that's a good approach remains to be seen)
Additionally customization could also be done by using `badgeClassName` directly.
Storybook
> sveltekit: Add badge wildcard component

- client/web/src/enterprise/repo/settings/RepoSettingsLogsPage.tsx
- client/web/src/enterprise/repo/settings/__snapshots__/RepoSettingsLogsPage.test.tsx.snap
Just a name change to the `Last repo commands` tab.
> source: rename "Last repo commands" tab

- doc/dev/how-to/wolfi/add_update_images.md
- doc/dev/how-to/wolfi/add_update_packages.md
Update documentation to reference the new `sg wolfi` commands
- Docs only - green CI build
> Update docs to reference `sg wolfi` commands

- client/web/src/enterprise/repo/settings/RepoSettingsLogsPage.tsx
- cmd/gitserver/server/server.go
[Context](https://sourcegraph.slack.com/archives/C05HF5XGMFF/p1690878610936729)
> If a repo syncs and there are no new commits, the last sync output updates to show No logs yet.  This can be misleading and gives a false impression to the user that the repo wasn’t synced at all. 
Right now, this PR updates the text displayed in the UI.
When the last sync doesn't produce an output, we display the text `Last sync command did not produce any output` in the UI.
> source: reword text displayed when there's no output from the last sync

- dev/ci/bazel-configure.sh
- dev/ci/bazel-prechecks.sh
- doc/dev/background-information/ci/reference.md
- enterprise/dev/ci/internal/ci/bazel_operations.go
I think this work will be superseded by https://github.com/sourcegraph/sourcegraph/issues/54822 but for now:
* Run `gofmt` via bazel to get the list of files that are not formatted and add it to the warning annotation 👇🏼 
* The step will soft fail if files are not formatted
Test locally and CI
> bazel: run gofmt as part of bazel configure step

- internal/eventlogger/event_logger.go
- internal/usagestats/BUILD.bazel
- internal/usagestats/event_handlers.go
Alternative to https://github.com/sourcegraph/cody/pull/455/files that would also prevent these events from being logged in dotcom's prod db
No errors running locally, but I didn't actually test with these specific events.
> Don't log certain high-volume events in local (postgres) databases

- cmd/frontend/internal/httpapi/httpapi.go
- cmd/frontend/internal/httpapi/router/router.go
- internal/api/internalapi/client.go
- internal/batches/reconciler/BUILD.bazel
- internal/batches/reconciler/executor_test.go
- internal/batches/reconciler/reconciler_test.go
- internal/batches/types/BUILD.bazel
- internal/batches/types/batch_change.go
- internal/batches/types/batch_change_test.go
- internal/codemonitors/background/BUILD.bazel
- internal/codemonitors/background/email.go
- internal/codemonitors/background/workers.go
This removes the `internalClient.ExternalURL` method, which can be replaced with a simple call to `conf.Get()`
Tested that the links in a code monitor still point to the right external URL
> Backend: remove internalClient.ExternalURL

- cmd/cody-gateway/internal/httpapi/completions/anthropic.go
- internal/completions/client/anthropic/anthropic.go
They recently introduced API versioning, so to be safe that we always get the correct API version that we currently support, we should set this header going forward.
Next up we can switch to the new API which allows incremental streaming, but that will take more engineering effort.
Verified Cody still works.
> Add API version header to Anthropic API requests

- monitoring/definitions/frontend.go
- monitoring/definitions/git_server.go
- monitoring/definitions/repo_updater.go
- monitoring/definitions/searcher.go
- monitoring/definitions/shared/grpc.go
- monitoring/definitions/symbols.go
In https://github.com/sourcegraph/sourcegraph/pull/55498, I removed the extra namespace from all the gRPC service metrics.
However, I missed that the method variable (which we use to be able to filter metrics for an individual method) definition was still referencing the old namespace. This had the inadvertent effect of breaking most of the gRPC dashboards on sourcegraph.com - since the metrics they were looking for didn't exist.
This PR fixes this by replacing the namespace in the definition with a grpc_service label filter.
Local testing
> grpc: monitoring: fix method label query

- deps.bzl
- go.mod
- go.sum
- internal/search/backend/metered_searcher.go
We introduced some new search stats we want to hook up to our observability. Additionally this bump includes the following changes:
- https://github.com/sourcegraph/zoekt/commit/9923324317 Create buf-breaking-check.yml
- https://github.com/sourcegraph/zoekt/commit/0f6564bdb9 trace: add service.instance.id
- https://github.com/sourcegraph/zoekt/commit/9c20a034e0 fix tracing
- https://github.com/sourcegraph/zoekt/commit/6a428ad677 SearchOptions: add MaxMatchDisplayCount
- https://github.com/sourcegraph/zoekt/commit/626c7d8f51 introduce DisplayTruncator
- https://github.com/sourcegraph/zoekt/commit/eede122967 gofmt -s -w .
- https://github.com/sourcegraph/zoekt/commit/9559422b7f DisplayTruncator: always apply both limits
- https://github.com/sourcegraph/zoekt/commit/63da184a02 stat: …
> zoekt: update and observe new timing Stats

- enterprise/cmd/embeddings/qa/embed_queries/main.go
- enterprise/cmd/embeddings/shared/main.go
- internal/embeddings/embed/client/azureopenai/BUILD.bazel
- internal/embeddings/embed/client/azureopenai/client.go
- internal/embeddings/embed/client/azureopenai/client_test.go
- internal/embeddings/embed/client/client.go
- internal/embeddings/embed/client/modeltransformations/BUILD.bazel
- internal/embeddings/embed/client/modeltransformations/model_transformations.go
- internal/embeddings/embed/client/modeltransformations/model_transformations_test.go
- internal/embeddings/embed/client/openai/BUILD.bazel
- internal/embeddings/embed/client/openai/client.go
- internal/embeddings/embed/client/openai/client_test.go
- internal/embeddings/embed/client/sourcegraph/BUILD.bazel
- internal/embeddings/embed/client/sourcegraph/client.go
- internal/embeddings/embed/client/sourcegraph/client_test.go
- internal/embeddings/embed/embed.go
- internal/embeddings/embed/embed_test.go
Add support for model-specific transformations. We have to:
* replace newlines with spaces for OpenAI (already implemented)
* add query-specific and document (code chunk)-specific prefixes for the E5 family of models.
* Embed with the OpenAI model and confirm the search still works.
* Embed with the Scout model and confirm the search still works.
(cherry picked from commit c022d9411cdb8953d3c9fc9613fd60b70c92c08d)
> embeddings: apply model transformations (backport #54302 to 5.1)

- enterprise/cmd/frontend/internal/guardrails/attribution/attribution.go
- enterprise/cmd/frontend/internal/guardrails/attribution/attribution_test.go
For the implementation of filtering we will always have a limit of 1 when searching attribution. This is an optimization so we can stop searching once we have a result from dotcom or the local instance.
Test Plan: added unit test
Part of https://github.com/sourcegraph/sourcegraph/issues/55451
> attribution: stop searching as soon as we hit our limit

- client/web/src/cody/useCodyChat.tsx
Closes https://github.com/sourcegraph/sourcegraph/issues/55553
Do not create empty chat if the current one is empty.
Tested manually. Video before is attached to the referenced issue.
https://github.com/sourcegraph/sourcegraph/assets/25318659/3f96fd82-759b-4898-af40-c07deac26c0f
> cody chat: do not recreate empty chat

- dev/nix/p4-fusion.nix
While setting up p4-fusion locally, I ran into the hash mismatch error. I updated the hash here.
Hash update.
> update hash for p4-fusion.nix

- doc/admin/deploy/machine-images/aws-ami.md
- doc/admin/deploy/machine-images/gce.md
Reverts sourcegraph/sourcegraph#55573
docs
> Revert "AMI executor docs"

- CHANGELOG.md
- client/web/src/repo/blob/codemirror/search.tsx
Resolves #54810
Browsers' built-in search input will select the input value when pressing Mod-f, even when the focus is already on the search input.
The default CodeMirror behavior will only select the input value when the input is not already focused. This PR changes the behavior to match the browser's behavior.
- Open file page
- Press `Mod-f` to open file search
- Type any input value
- Press `Mod-f` again -> input value is selected
> blob: Always select search input value when pressing Mod-f

- dev/oci_deps.bzl
Update all Wolfi base images to the latest release, to pick up new patches and fix vulns.
- Green CI
- Test on S2 prior to publishing
> Update wolfi base images for 5.1.6

- doc/dev/background-information/ci/reference.md
- docker-images/dind/Dockerfile
- enterprise/dev/ci/internal/ci/pipeline.go
Resolve vulnerabilities in dind image by updating to 23.0.6.
I also noticed that we no longer build the dind image (it's not a bazel image), so have added that back.
I haven't tested this locally yet, as I get an `ip: can't find device 'ip_tables'` error (both for the updated version and the 5.0.0 image.
> Update Docker-in-Docker image from 23.0.1 -> 23.0.6

- dev/oci_deps.bzl
Update all Wolfi base images to the latest release, to pick up new patches and fix vulns.
- Green CI
- Test on S2 prior to publishing
> [Backport 5.1] Update wolfi base images for 5.1.6

- doc/dev/background-information/ci/reference.md
- docker-images/dind/Dockerfile
- enterprise/dev/ci/internal/ci/pipeline.go
Resolve vulnerabilities in dind image by updating to 23.0.6.
I also noticed that we no longer build the dind image (it's not a bazel image), so have added that back.
> [Backport 5.1] Update Docker-in-Docker image from 23.0.1 -> 23.0.6 

- deps.bzl
- go.mod
- go.sum
Although we are not vulnerable to CVE-2023-26054, update github.com/moby/buildkit as a matter of course.
Resolves https://github.com/sourcegraph/sourcegraph/discussions/55412
* Update module version
* `go mod tidy`
* `bazel configure`
* `bazel run :gazelle-update-repos`
> Update moby/buildkit to v0.11.6

- doc/_resources/templates/root.html
This PR fixes the case of building a search link that doesn't have a section anchor.
> Fix title links

- doc/_resources/assets/docsite.css
- doc/_resources/templates/root.html
Fixes the search and breadcrumb link colors to match the rest of the doc, as well as fixing some colours and display issues with the markprompt button and overlay.
| - | - |
| <img width="1418" alt="Screenshot 2023-08-08 at 11 34 39 am" src="https://github.com/sourcegraph/sourcegraph/assets/153/fb1f3886-abff-4e9e-bd33-e7b0d509c2d0"> | <img width="1418" alt="Screenshot 2023-08-08 at 11 34 19 am" src="https://github.com/sourcegraph/sourcegraph/assets/153/22cc4bd5-6a61-4ae6-a29a-cd24083461b4"> |
| <img width="1418" alt="Screenshot 2023-08-08 at 11 34 30 am" src="https://github.com/sourcegraph/sourcegraph/assets/153/0906192b-fffd-4cfd-9130-43dfa9f9c88b"> | <img width="1418" alt="Screenshot 2023-08-08 at 11 34 14 am" …
> Docs: fix link colors

- client/shared/dev/generateGraphQlOperations.js
- client/web-sveltekit/package.json
- client/web-sveltekit/svelte.config.js
- client/web-sveltekit/vite.config.ts
- package.json
- pnpm-lock.yaml
This commit adds a couple of developer workflow improvements:
- GraphQL types are now generated automatically in dev and production mode. No need to run `pnpm generate` anymore (unless the changes happen outside of the SvelteKit app). To make this work I refactored the existing code to be able to reuse the config generation logic.
- Enabled Svelte's "inspect" mode to easily identify components. This also allows you to open the component in your configured editor.
- Enabled inspect mode for Vite plugins. I didn't need this but it's interesting to see how modules are transformed and might come in handy one day. 
Svelte inspect mode (screenshot tool didn't capture the cursor)
Vite inpsect
`pnpm dev`
> sveltekit: Enable graphql generation and inspect modes

- enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql.go
Was broken by https://github.com/sourcegraph/sourcegraph/pull/52811 where we switched from `l` to `activeLicense`, we accidentally only returned the most recent access token, causing older tokens to never get a new configuration synced.
Verified all tokens are returned again.
> codygateway: Always return all Sourcegraph access tokens

- cmd/frontend/internal/cli/config.go
- doc/dev/background-information/sg/reference.md
- enterprise/cmd/worker/internal/embeddings/repo/BUILD.bazel
- enterprise/cmd/worker/internal/embeddings/repo/handler.go
- enterprise/cmd/worker/internal/embeddings/repo/worker.go
- internal/conf/conftypes/conftypes.go
- internal/embeddings/db/BUILD.bazel
- internal/embeddings/db/qdrant.go
- sg.config.yaml
This is the minimal change to start ingesting into qdrant locally. Just `sg start qdrant` and all your background embeddings jobs will slowly fill up your qdrant db. Note that, right now, repos will only be ingested if they have changed (we do not schedule any jobs for repos that have not changed). I'll likely add some sort of "add a job for all embedded repos" lever soon. 
This does not yet use qdrant for the search side of things. 
Manual tests. Tested that embedding a new repo fills the vector db. Tested that incrementally updating a repo ingests the whole repo into the vector db.
> Embeddings: minimal local qdrant ingestion

- BUILD.bazel
- dev/linters/unused/BUILD.bazel
- dev/linters/unused/unused.go
This adds the `unused` lint to the set of linters supported by `nogo`. This PR leaves it disabled because we currently have a _lot_ of dead code lying around. 
For anyone who wants to work on sniping some unused code, just uncomment the line in `BUILD.bazel`
```bash
❯ bazel build //cmd/frontend/internal/httpapi
...
compilepkg: nogo: errors found by nogo during build-time code analysis:
internal/extsvc/types.go:319:87: bbsLower is unused (unused)
internal/extsvc/types.go:320:62: bbcLower is unused (unused)
internal/extsvc/types.go:321:24: jvmLower is unused (unused)
internal/extsvc/types.go:322:22: npmLower is unused (unused)
internal/extsvc/types.go:324:30: goLower is unused (unused)
internal/extsvc/types.go:324:89: pythonLower is unused (unused)
internal/extsvc/types.go:325:45: rustLower …
```
> Linting: add `unused` lint

- internal/extsvc/types.go
The linter in #55647 flagged these. They are unused and are a left-over after the migration to the "Variant" types in this file.
- Existing CI
> extsvc: remove unused vars

- internal/codeintel/autoindexing/internal/inference/libs/patterns.go
- internal/codeintel/autoindexing/internal/inference/luatypes/index_job.go
- internal/codeintel/autoindexing/internal/inference/luatypes/index_job_hint.go
- internal/codeintel/autoindexing/internal/inference/luatypes/path_patterns.go
- internal/codeintel/autoindexing/internal/inference/luatypes/recognizers.go
- internal/codeintel/autoindexing/internal/inference/service.go
- internal/luasandbox/util/util.go
There were some APIs which are unwieldy to use (perhaps because
of being written pre-generics), so I've simplified them before doing
more work here.
> cleanup: Simplify Lua sandbox code using generics

- client/browser/src/shared/code-hosts/gitlab/codeHost.test.ts
- client/browser/src/shared/code-hosts/gitlab/scrape.ts
closes https://github.com/sourcegraph/customer/issues/2189
We originally added support for `nameTransformations` in this PR: https://github.com/sourcegraph/sourcegraph/commit/39addfbfe2ef2002cb5ab550e03b5a9810209c19
That worked at the time, but made an assumption that all repositories have a host prefix on Sourcegraph (`e.g. 'gitlab.com/sourcegraph/jsonrpc2' -> 'sourcegraph/jsonrpc2'`). This is not necessarily the case if the Sourcegraph instance was set to use  `"repositoryPathPattern": "{pathWithNamespace}"`. If this was set, the repository would actually already be `sourcegraph/jsonrpc2`, so this code would remove the "sourcegraph" and try to build a repo name that didn't exist.
This PR updates the logic so that we always use the Sourcegraph resolved repo name for Sourcegraph API …
> GitLab extension: Fix for repositories with `repositoryPathPattern` set

- CHANGELOG.md
Just backported this: https://github.com/sourcegraph/sourcegraph/pull/55689
n/a
> changelog: disabled openai code completions in 5.1.6

- cmd/sitemap/graphql.go
- enterprise/cmd/cody-gateway/internal/httpapi/completions/anthropic.go
- enterprise/cmd/cody-gateway/internal/httpapi/completions/openai.go
- enterprise/cmd/cody-gateway/internal/httpapi/completions/upstream.go
- enterprise/cmd/cody-gateway/internal/httpapi/embeddings/handler.go
- enterprise/cmd/cody-gateway/internal/httpapi/embeddings/openai_test.go
- internal/httpcli/client.go
- internal/httpcli/client_test.go
Backports https://github.com/sourcegraph/sourcegraph/pull/55591 (manual PR because the automated one failed)
> [Backport 5.1] httpcli: respect retry-after on all error responses, set retry-after in Cody Gateway responses

- CHANGELOG.md
- enterprise/cmd/worker/internal/embeddings/repo/scheduler.go
We received [reports](https://sourcegraph.slack.com/archives/C03JR7S7KRP/p1691615072530409?thread_ts=1691445779.618029&cid=C03JR7S7KRP) in [slack](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1691505903644939) of repositories never getting scheduled for embedding jobs despite the filter / pattern preview showing repos that match.
In both cases linked private repos appear to be impacted. After fetching repo ids from `GetEmbeddableRepos` we then make another fetch for getting the repo names for those repo ids. This read operation is where we appear to end up missing out on some repos because we are not an internal actor and therefore [we must have permissions](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5.1/-/blob/internal/database/repos.go?L1242) to the repos that we …
> Fix: Repo embedding scheduler job routine as internal actor

- cmd/executor/build_binary.sh
- cmd/executor/docker-mirror/build.sh
- cmd/executor/release_binary.sh
- cmd/executor/vm-image/build.sh
- enterprise/dev/ci/internal/ci/operations.go
Those steps don't run on not-main so missed those when moving executor from enterprise/cmd to cmd.
main-dry-run.
> Fix main build due to broken paths in scripts

- CHANGELOG.md
- enterprise/cmd/worker/internal/embeddings/repo/scheduler.go
We received reports of repositories never getting scheduled for embedding jobs despite the filter / pattern preview showing repos that match.
In both cases linked private repos appear to be impacted. After fetching repo ids from `GetEmbeddableRepos` we then make another fetch for getting the repo names for those repo ids. This read operation is where we appear to end up missing out on some repos because we are not an internal actor and therefore we must have
permissions to the repos that we want `List`ed. When we aren't authorized for any repos then we end up never scheduling those repos since we never got the repo names.
(cherry picked from commit ef63a4f9ecd8913a191bc5e5d562b80d46da527b)
> [Backport 5.1] Fix: Repo embedding scheduler job routine as internal actor (#55698)

- client/web-sveltekit/src/lib/dom.ts
I assumed that faker wouldn't be included in production builds due to tree-shaking but I was wrong. It currently adds > 2MB to the production build files.
I confirmed that the `if` statement is removed in the production build (i.e. faker is not referenced) but the module is still included.
I thought maybe the dead code removal happens after dependencies are processed, so I removed the callsite completel but the module would still be included.
I tried various [`treeshake`](https://rollupjs.org/configuration-options/#treeshake) options, such as `moduleSideEffects: false`, but to no avail.
So for the time being, removing the import alltoghether is the best way to ensure that the module is not included in the production build.
`pnpm build` ... the output listing the generated files confirms …
> sveltekit: Remove faker from production build

- cmd/gitserver/server/BUILD.bazel
- cmd/gitserver/server/cleanup.go
- cmd/gitserver/server/cleanup_test.go
- cmd/gitserver/server/clone.go
- cmd/gitserver/server/patch.go
- cmd/gitserver/server/repo_info.go
- cmd/gitserver/server/server.go
- cmd/gitserver/server/server_grpc.go
- cmd/gitserver/server/server_test.go
- cmd/gitserver/server/servermetrics.go
- cmd/gitserver/server/serverutil.go
- cmd/gitserver/shared/BUILD.bazel
- cmd/gitserver/shared/config.go
- cmd/gitserver/shared/debug.go
- cmd/gitserver/shared/service.go
- cmd/gitserver/shared/shared.go
- cmd/gitserver/shared/shared_test.go
- enterprise/cmd/gitserver/shared/service.go
- internal/gitserver/client.go
This PR starts moving some things off of the server struct that don't actually need it. 
In tests, we don't need to construct the entire server each time, of which we have no clue what of the fields are actually required in a test. This makes the individual functions much easier to test. 
Also, the server struct with about 100 receiver methods smells like a huge anti-pattern. It's very hard to reason about what this monstrosity is all doing, or maybe also.. not doing. I'm hoping this is slowly becoming clearer as the individual subcomponents of the server become more obvious by such refactors.
As a side effect of some of these things becoming standalone routines vs being part of Server, we get:
- Them being goroutines they are tracked in the background routines in our site-admin area
- …
> gitserver: Start cleaning up server struct

- cmd/gitserver/server/run.go
This call does effectively nothing, luckily, because we set the Std buffers above, it errors out. Otherwise, this would panic. This does not cause trouble in this case, but is confusing and not needed, so removing it.
Verified that this was actually not required.
> gitserver: Remove unnecessary call to cmd.CombinedOutput

- internal/gitserver/gitdomain/exec_test.go
Ensure that file paths are not accepted as input.
follow up to #55657
CI test should exhibit that file paths are not accepted
> Add negative test for `git commit -F`

- internal/search/job/observe.go
The "first results" event got switched to an attribute at some point, but the timestamp is actually the interesting part of this event. This just switches it back from an attribute to an event.
N/A
> Search: fix tracing so "first results" is an event

- dev/release/src/release.ts
- The location of this file changed in https://github.com/sourcegraph/sourcegraph/pull/55466
The 5.1.6 release :grimacing:
> releasetool: update `updatecheck/handler` path in comby commands

- internal/codeintel/autoindexing/internal/inference/libs/indexes.go
A bunch of indexers published new releases with fixes,
in particular scip-go which includes a fix for repos using
stdlib packages newly introduced in Go 1.21
Covered by indexers' own tests
> chore: Bump autoindexing image SHAs

- client/jetbrains/CONTRIBUTING.md
Bumped into this for the second time in two days, so adding more docs.
Added two ways to install Java 11 (CLI and GUI) and run the plugin.
Not saying that it's perfect, and I didn't test it thoroughly (but we tested the CLI commands on @chwarwick's machine while screen sharing, and I used the GUI method earlier), but it should be 90% correct.
Only docs change.
> JetBrains: Add java install instructions

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AcceptCodyAutoCompleteAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutoCompleteTextAtCaret.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutocompleteTelemetry.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/Autocompletion.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutocompletionStatus.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutoCompleteManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyEditorFactoryListener.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/AutoCompleteProvider.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/prompt_library/CodyAutoCompleteItemProvider.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/recipes/SimpleRecipeAction.java
- client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
Closes https://github.com/sourcegraph/cody/issues/123
Changes:
- Added `latency` and `displayDuration` arguments for `CodyJetBrainsPlugin:completion:suggested` event logging
- Added comments to various places as I discovered the codebase.
The other two completion-related events (`completion:started` and `completion:accepted`) were already in place at the right locations. `completion:suggested` was triggered too early, I had to move it to a much later point where the timing information was available.
Caveats:
- Did not add any other arguments for now. I need to check the dashboard to make sure this is enough, but honestly, I didn't want to do a lot of changes before the Agent-related PRs are merged
Note for the reviewer: if the docs changes are too much, you can review this commit by …
> JetBrains: Add more comprehensive autocomplete telemetry

- CHANGELOG.md
- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
- cmd/cody-gateway/shared/config.go
https://www.anthropic.com/index/releasing-claude-instant-1-2
-  I connected the VS Code instant to the local instance and configured the dev server to use Claude instant 1.2 for code completions. It works
> Add support for Claude Instant 1.2

- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
This will allow us to measure the usefulness of our request caching
n/a
> metrics/RequestMeter: add label for X-From-Cache

- dev/release/src/util.ts
Locally tested and it formats the BAZEL file properly.
It is still hacky and in the long run we should probably research a bazel parser that can enable us load this and modify before saving but this works for now.
> release: fix improper formatting when generating migrator bazel build

- enterprise/cmd/bundled-executor/BUILD.bazel
- enterprise/cmd/executor/BUILD.bazel
- enterprise/cmd/executor/internal/util/BUILD.bazel
We seem to have lost this special build tag somewhere in migrations, causing the bundled-executor to no longer have the shell runtime code in it.
Manual backport of https://github.com/sourcegraph/sourcegraph/pull/55792.
Verified the image builds and has the correct build tag.
> Build bundled-executor with shell build tag again

- enterprise/cmd/bundled-executor/build-wolfi.sh
- enterprise/cmd/bundled-executor/build.sh
After changing paths, these seem to have been missed.
Made sure the scripts work again.
> Fix docker build scripts for bundled-executor

- go.mod
- go.sum
This updates our zoekt dependency to point to https://github.com/sourcegraph/zoekt/commit/956d775e32b369708c457dc612fd5b69ba85523e.
This is just updating the [github.com/sourcegraph/zoekt](github.com/sourcegraph/zoekt) dependency we have. All CI checks on the original repository are sufficient.
> chore: update zoekt to 956d775e32b369708c457dc612fd5b69ba85523e

- cmd/frontend/graphqlbackend/repository_mirror.go
- cmd/gitserver/server/server_test.go
- internal/database/gitserver_repos.go
- internal/database/gitserver_repos_test.go
- internal/database/mocks_temp.go
- internal/types/types.go
We recently added a left join on another table holding the gitserver sync logs, which added quite some overhead to the queries. Here's an example query plan from dotcom for the iterate gitserver repos query:
Before
```
SELECT
gr.repo_id, repo.name, gr.clone_status, gr.cloning_progress, gr.shard_id, gr.last_error, gr.last_fetched, gr.last_changed, gr.repo_size_bytes, gr.updated_at, gr.corrupted_at, gr.corruption_logs, gr.pool_repo_id, go.last_output 
FROM gitserver_repos gr 
JOIN repo ON gr.repo_id = repo.id 
LEFT OUTER JOIN gitserver_repos_sync_output go ON gr.repo_id = go.repo_id 
WHERE gr.repo_id > 0 AND repo.id > 0 
ORDER BY gr.repo_id ASC 
LIMIT 5000 
OFFSET 0;
```
```
QUERY PLAN
----------------------------------------------------------------------------------------------------------- …
```
> Improve performance of gitserver_repos store methods

- cmd/gitserver/shared/BUILD.bazel
- cmd/gitserver/shared/shared.go
This enables us to see gitserver routines in the background jobs page.
Verified locally that routines show up.
> gitserver: Register background routines with recorder

- client/jetbrains/build.gradle.kts
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutoCompleteManager.java
- client/jetbrains/src/main/java/com/sourcegraph/config/UserLevelConfig.java
- client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
- Adds more helpful debug logging
- Stop displaying autocomplete when built-in completions are visible
- Emit `null` instead of undefined fields
- Fixes https://github.com/sourcegraph/sourcegraph/issues/55796
Manually tested with `./gradlew -PplatformVersion=221.5080.210 -PenableAgent=true -PforceAgentBuild=true :runIde`. Make sure we autocomplete works as expected.
> JetBrains: fix miscellaneous issues

- client/web/src/site-admin/packages/PackagesModal.module.scss
- client/web/src/site-admin/packages/modal-content/ManagePackageFiltersModalContent.module.scss
The package repo filter list modal didnt enforce a max height, resulting in it growing beyond the top/bottom of the screen when too many filters were added.
Tested locally with 0-17 filters on 1440p and 1080p screens
> codeintel: limit package filter list modal height

- internal/codeintel/autoindexing/internal/inference/libs/recognizers.go
- internal/codeintel/autoindexing/internal/inference/luatypes/recognizers.go
The argument is first validated using `CheckTable`, which guarantees that
we'll have a table. So `new_fallback_recognizer` doesn't accept a `Recognizer` object,
which means that the singleton case in `MapSliceOrSingleton` is not triggered.
So directly use `MapSlice`.
> cleanup: Inline/Simplify function used only in one place

- internal/database/batch/observability.go
This may be indicative of a bigger problem in sourcegraph given the volume increase in events. I haven't investigated, but instead I am just getting ahead of us getting rate limited. 4x was chosen since my eyeballs make it look more like the event count from a while ago.
Test Plan: n/a
count of events
count of events by table. Seems to be an increase in usage of event logs
> database: sample 4x less events for honeycomb database-batch

- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentClient.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/ConnectionConfiguration.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/DebugMessage.java
- client/jetbrains/src/main/java/com/sourcegraph/config/CodyApplicationService.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/config/PluginSettingChangeContext.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsConfigurable.java
- client/jetbrains/src/main/java/com/sourcegraph/config/UserLevelConfig.java
Adds new settings to enable/disable cody agent debugging and adds a listener to capture debug messages and log them. Goes with Cody PR https://github.com/sourcegraph/cody/pull/668
Run extension with debug/verbose enabled ensure debug messages are added to logs
Run extension with debug/verbose disabled ensure no debugging message added to logs
> JetBrains: add settings for debugging agent 

- doc/cody/explanations/index.md
> chore: fix extra space that confused Markdown render

- dev/sg/internal/generate/generate.go
- dev/sg/internal/generate/golang/golang.go
- doc/admin/observability/alerts.md
- doc/admin/observability/dashboards.md
- monitoring/monitoring/documentation.go
- sg.config.yaml
Previous changes made it work, but in between the outdated PR description in https://github.com/sourcegraph/sourcegraph/pull/54965 and the fact that nothing really tells you about `bazel run //dev:write_all_generated`, this was very confusing. 
> sg: ease transition to bazel handled go:generate

- enterprise/dev/ci/scripts/wolfi/build-repo-index.sh
- enterprise/dev/ci/scripts/wolfi/upload-package.sh
- wolfi-images/sourcegraph-base.yaml
* Switch over from a GCS url to the new alias introduced [here](https://github.com/sourcegraph/infrastructure/pull/5304).
* Switch the root package repo path from `gs://package-repo/packages/` to `gs://package-repo/`
* Switch over to the new package signing keys introduced [here](https://github.com/sourcegraph/infrastructure/pull/5305).
Post-merge, this will require a rebuild of {repo index|all packages} with the new signing keys - currently the package repo is signed using the old `melange.rsa` key. Unsure whether this will require a full rebuild of all packages or just the index.
- Confirm base images still build locally
- Confirm package upload and reindex works on CI using new keys
> Switch package repo paths and use new signing keys

- dev/nix/start-redis.sh
Not sure when or why, but I just had the same issue as with postgres but with redis now :shrug: 
N/A nix stuff
> nix: fix direnv hanging when starting redis

- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsConfigurable.java
Fixes https://github.com/sourcegraph/sourcegraph/issues/55865
N/A. The field is now using `final @NotNull` making it impossible to get the same NPE.
> JetBrains: prevent null pointer exception

- client/jetbrains/build.gradle.kts
- client/jetbrains/gradle.properties
- client/jetbrains/scripts/release.sh
The 3.0.9 was a failure because the agent binaries were located in the `agent/agent/` directory instead of `agent/`. This code path was working correctly at one point but it was only manually tested. This commit fixes the issue and adds new assertions to the release script to prevent a regression like this in the future.
- Ran `./gradlew buildPlugin` and manually installed the zip file. Manually confirmed that autocomplete via agent works as expected. 
- Ran `./gradlew -PforceAgentBuild=true buildPluginAndAssertAgentBinariesExist` to confirm it runs successfully. Manually added a file that doesn't exist and confirmed the task fails.
> JetBrains: fix path of agent binaries in plugin zip

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyAgentProjectListener.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutoCompleteManager.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsChangeListener.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
- Clearer titles for sections: Authentication, Cody AI, Code Search
- Reorder groups to put Cody AI above Code Search
- Disabling Cody checkbox disables all checkboxes in the group
- Disabling Cody checkbox no longer sets autocomplete value to false. When you disable/enable Cody, the Cody-related setting values are the unchanged. Previously, all Cody values would be set to false.
- Automatically start/stop Agent based on Cody enabled setting
With `./gradlew -PenableAgent=true :runIde`:
- Cody + autocomplete is enabled, confirm autocomplete works.
- Disable Cody, confirm autocomplete checkbox is disabled but checked.
- Confirm autocomplete does not work.
- Enable Cody, disable autocomplete. Confirm autocomplete is still not working.
- Enable Cody, enable autocomplete, confirm autocomplete …
> JetBrains: improve settings UI

- CHANGELOG.md
Some features were released but not moved to the appropriate sections.
This also tweaks how the CHANGELOG is structured as discussed in [this thread](https://sourcegraph.slack.com/archives/C032Z79NZQC/p1691744143767099).
Not needed
> CHANGELOG: move released changes to appropriate section, add unreleased patch section + planned date

- doc/cody/quickstart.md
Updating the VS Code Quickstart page to reference Commands instead of Recipes.
Docs change only.
> Update quickstart.md for recipes -> commands

- cmd/frontend/internal/cli/BUILD.bazel
- cmd/frontend/internal/cli/serve_cmd.go
- go.mod
I'm still struggling to figure out why we are missing spans on sourcegraph.com, so this enables debug logging for the otel logging package. 
This can be removed in a couple of days or if we find what the cause of the missing spans is.
Tested locally that the logs work as expected. Note the `total_dropped`, which is of particular interest to me because we apparently also do batching in the service that is exporting to `otel-agent`, which is then exporting to `otel-collector`, which then exports to Jaeger and GCP 🤯 
```
[       frontend] 2023/08/15 21:44:57 internal_logging.go:63: "level"=8 "msg"="exporting spans" "count"=130 "total_dropped"=0
```
> Tracing: add logging for trace exporting

- internal/httpcli/client.go
Fix the `InternalClient` comment so Cody stops giving wrong answers in the test suite 😄 
* No tests, comment change.
> Fix InternalClient comment

- doc/code_navigation/references/inference_configuration.md
C++ auto-inference was removed in https://github.com/sourcegraph/sourcegraph/pull/55861
and hints were removed in https://github.com/sourcegraph/sourcegraph/pull/55863
n/a
> docs: Remove mentions of C++ and hints from auto-inference docs

- client/web/src/components/externalServices/externalServices.tsx
All other package hosts have this disclaimer, ruby should have it too, to my understanding of the packages architecture.
Verified it renders correctly.
> Add singleton message to Ruby package host

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyAgentFocusListener.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyFileEditorListener.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentClient.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentCodebase.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/ExtensionConfiguration.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/ClientInfo.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyEditorFactoryListener.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
This adds new logic to track the current codebase associated with the active editor/file and send the `extensionConfiguration/didChange`  notification to the agent with the codebase changes.
This also renames the ConnectionConfiguration to ExtensionConfiguration to match recent agent changes, since the configuration is inclusive of additional configuration beyond connection information.
I included the `textDocumentDidChange` event because I did not get `textDocumentDidOpen` or `textDocumentDidFocus`  events when the project opened to a specific file.
Opened editor to repo that has embeddings, verified that codebase was sent to agent and embeddings were fetched to use with autocomplete.
Opened editor to folder containing multiple repos observed that opening files updated the configuration …
> JetBrains: Send config changed event when codebase changes

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AcceptCodyAutoCompleteAction.java
Fixes https://github.com/sourcegraph/sourcegraph/issues/55917
Previously, when accepting multiline autocomplete, the caret could move outside of the visible window. This commit fixes the issue by scrolling the window to make the caret visible. When the caret is already visible, the editor doesn't scroll.
Trigger a multiline completion, scroll so the inlay hint appears at the bottom of the window, accept, confirm the window scrolls.
Trigger multiline completion so that the entire hint appears in the window, accept, confirm the editor doesn't scroll.
> JetBrains: make sure caret is visible after accepting autocomplete

- deps.bzl
This was updated in `go.mod` in #55812, but the corresponding entry in `deps.bzl` is still pointing to an older version. This was causing us to build an image without the intended fix.
CI.
> gRPC: update zoekt in deps.bzl

- cmd/frontend/graphqlbackend/site_alerts_test.go
- enterprise/cmd/frontend/internal/auth/BUILD.bazel
- enterprise/cmd/frontend/internal/auth/init.go
- enterprise/cmd/frontend/internal/auth/init_test.go
Closes https://github.com/sourcegraph/sourcegraph/issues/55433.
This PR adds a warning notification/alert if an enterprise license and no SSO providers are configured.
- Added new tests
> feat(setup-checklist): add configure SSO notification alert

- dev/ci/bazel-prechecks.sh
- enterprise/dev/ci/internal/ci/bazel_operations.go
This adds a check that `bazel run //:gazelle-update-repos` has been run. It should help catch the easy-to-miss step when updating dependencies. Quite a few unrelated changes, but all with explanatory comments.
[Slack context](https://sourcegraph.slack.com/archives/C05FDP58LRF/p1692197008211619)
An example failure [here](https://buildkite.com/sourcegraph/sourcegraph/builds/238821).
> Bazel: add precheck for `//:gazelle-update-repos`

- client/jetbrains/src/main/java/com/sourcegraph/cody/PluginUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
**Context:**
In VS Code, the `CodyVSCodeExtension:completion:suggested` events the extension emits, we have `"otherCompletionProviderEnabled": boolean`, which is set based on checking for [a hard-coded list](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/completions/logger.ts?L210) of known extensions being installed or not.
(This is not perfect because, for example, the GitHub Copilot extension could be installed, but the completions can be disabled, but it's still helpful to guess these cases.)
Before this PR, we didn't include this field in the events emitted in the JetBrains plugin.
**PR description:**
In this PR, I've added the same.
I went through the JetBrains Marketplace and searched for code completion plugins and added the IDs of the most …
> JetBrains: Detect other completion plugins

- internal/batches/reconciler/executor.go
- internal/batches/reconciler/executor_test.go
If we wrap the `pushCommitError`, it will not be displayed nicely in the UI. This returns the error if it is a `pushCommitError` without being wrapped, else we keep the error wrapped.
Covered by existing tests. Fixed failing test.
> batches: Fix regression the error message

- doc/code_navigation/index.md
Part of the Marketing team hackathon. 
There is a [table](https://docs.sourcegraph.com/code_navigation) on the main docs overview page of Code Navigation that should be aligned with the [new table styling](https://docs.sourcegraph.com/cody#main-features) that we have on the main Cody docs page.
For styling, refer to the CSS properties used [here](https://github.com/sourcegraph/sourcegraph/blob/main/doc/cody/index.md)
via: https://github.com/sourcegraph/documentation/issues/12
- Updating docs:
- "previewed locally" 
- share a screenshot if you want to be thorough
- Check links
> Replace HTML table with Markdown

- deps.bzl
- go.mod
- go.sum
- internal/search/backend/grpc.go
This PR updates our Zoekt dependency to https://github.com/sourcegraph/zoekt/commit/fcb279ae404c0aa102121b28257143ad16e77482.
This update includes changes to the Zoekt Search result protobuf definition. LineFragments and RepoURLs are no longer defined in the protobuf spec, and our go struct <-> protobuf struct conversion functions have been updated to reflect this. 
CI
> zoekt: update to fcb279ae404c0aa102121b28257143ad16e77482

- internal/api/internalapi/BUILD.bazel
- internal/api/internalapi/client.go
- internal/api/internalapi/client_test.go
Fixes https://sourcegraph.slack.com/archives/C039KBLH65V/p1692211398788339
-- 
This PR adds more robust URL parsing for the sourcegraph-frontend-internal URL that our configuration client uses. Notably, this logic:
- Will add a "http://" scheme if one isn't already specified in the URL
- Will add a default port of 80 to the URL if one isn't already defined 
So, under this new logic, a SOURCEGRAPH_FRONTEND-INTERNAL_URL value of `sourcegraph-frontend-internal` will now be transformed into `http://sourcegraph-frontend-internal:80`.
CI
> grpc: conf: add more robust URL parsing for SRC_FRONTEND_INTERNAL

- client/web/src/repo/blob/codemirror/linenumbers.ts
[Reported via Slack](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1692186686023639)
When determining whether to scroll a line into the view we are first validating whether the selected position (which includes line number and (optionally) character offset) is valid.
It's possible to get a position that refers to a valid line but an invalid character offset. Currently the selected line is not scrolled into view in that case.
This change ignores the character offset when validating the position. The character offset should have no impact on determining whether or not to scroll the line into view.
Opened a file link with an invalid character offset ([example](https://sourcegraph.test:3443/github.com/JetBrains/intellij-scala@ce4785e85496fe9d9d0c315b247ca75f0062188b/-/blob/scala/scala-im …
> blob: Scroll selected line into view even with invalid character offset

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AcceptCodyAutoCompleteAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutoCompleteActionHandler.kt
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutoCompleteManager.java
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/autocomplete/DisposeInlaysAction.kt
- client/jetbrains/src/main/resources/META-INF/plugin.xml
Closes [#55918](https://github.com/sourcegraph/sourcegraph/issues/55918)
Previously, pressing `Escape` had no effect when Cody autocomplete suggestions were visible. This PR fixes the issue by adding a new `Escape` keyboard shortcut to reject the completion. 
Note that the completion will appear again if the user moves the cursor around and back into the original position. We can consider changing the behavior in the future to never display autocomplete again in that position unless explicitly requested again, but we should rely on user feedback before making such a decision.
- Display inlay autocomplete suggestion and press ESC to hide the inlay
> JetBrains: hide autocomplete with ESC keyboard shortcut

- wolfi-packages/qdrant.yaml
This adds a wolfi package for qdrant so we can build it into a wolfi image.
Tested that it builds into a container correctly (will be followup PRs showing this)
> Qdrant: add wolfi package

- enterprise/cmd/worker/internal/search/BUILD.bazel
- enterprise/cmd/worker/internal/search/search.go
- enterprise/cmd/worker/internal/search/search_test.go
We introduce an interface for how we expect exhaustive search workers will interact with our search subsystem. Additionally we introduce a functional fake for this system which uses a fake search query language to make it easy to test how the parts interact.
I encourage reviewing this PR commit by commit since we start off with the current proposed interface from the issue and then improve it.
Note: The location of the code and names can all change. The purpose of this PR is so we have this code checked in so it can be incrementally improved / easier to track than comments on an issue. I also hope that the fake is useable today to unblock progress.
Fixes https://github.com/sourcegraph/sourcegraph/issues/55455
Test Plan: CI
> search: introduce backend interface for exhaustive search

- client/web/src/components/externalServices/AddExternalServicesPage.tsx
Notice the second paragraph, that's the only change suggested.
closes #55720 
- #55720
Tested locally, it's just a copy change in a React component.
> chore: add cody to the data privacy disclaimer

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutoCompleteManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyEditorFactoryListener.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/TriggerAutocompleteAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/InlineCompletionTriggerKind.java
- client/jetbrains/src/main/resources/META-INF/plugin.xml
Fixes https://github.com/sourcegraph/sourcegraph/issues/55910
Previously, it was not possible to explicitly request Cody autocomplete. This commit fixes the problem by registering an action that can be triggered through the alt-backslash shortcut.
Write code, get autocomplete suggestion, press `Escape` to hide completion, press alt-tab to trigger completion.
> JetBrains: add alt-backslash shortcut to trigger autocomplete

- client/shared/src/components/RepoLink.test.tsx
- client/shared/src/components/RepoLink.tsx
In the packages list view, we use the repolink component with the package name, which can be something like `org.scala-sbt:collections_2.12`. The current logic returned an empty string, so to be safe, we're not only stripping hostnames when the remainder of the name is more than length 0.
Added a test case!
> Fix empty package names

- wolfi-images/qdrant.yaml
This adds a wolfi image definition for qdrant. 
Ran `sg wolfi image qdrant` and it built a usable image.
> Qdrant: add wolfi image

- doc/code_search/tutorials/examples.md
Adds a few basic examples to answer the most immediate questions and avoid overwhelming users in their first visit to the page. 
Manually test the links to ensure they are correct.
> Add simple examples to the start of the page to help users begin

- dev/oci_deps.bzl
- docker-images/qdrant/BUILD.bazel
- docker-images/qdrant/qdrant_image_test.yaml
This creates a docker image from the wolfi base image and adds it to `docker-images`. 
Building the image passes and basic image tests pass.
> Qdrant: add docker image

- client/web/BUILD.bazel
- client/web/src/featureFlags/featureFlags.ts
- client/web/src/site-admin/SiteAdminArea.tsx
- client/web/src/site-admin/SiteAdminOnboardingTourPage.tsx
- client/web/src/site-admin/SiteAdminSidebar.tsx
- client/web/src/site-admin/routes.tsx
- client/web/src/site-admin/sidebaritems.ts
- schema/onboardingtour.schema.json
- schema/schema.go
I wanted to use CodeMirror but the plugin I found for schema validation doesn't seem to be complete yet. So I'm using the Monaco settings editor as it is used in other places.
I added a new schema for the onboarding tour based on the existing type definitions.
- Opened site-admin settings without feature flag set -> page not listed in menu and not accessible
- Overwrite flag with `?feature-flag-key=end-user-onboarding&feature-flag-value=true` -> menu entry is visible and page is accessible
- Change JSON -> save and and discard buttons are enbaled
- Click save button -> JSON is sent to the server
> onboarding: Initial version of experimental onboarding tour configuration page

- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.java
Previously, there was no clean way to ensure that the agent process would accept non-trusted certificates. This PR addresses the issue by setting the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0` based on the presence of the system property `-Dcody.accept-non-trusted-certificates-automatically=true`.
Ideally, we would infer the correct value of this property based on the "Server Certificates" settings in IntelliJ. Using a system property is a quick solution that solves our immediate problem.
n/a
> JetBrains: add options to accept non-trusted certificates

- dev/oci_deps.bzl
Followup to #55891 which updates the `p4-fusion` package that goes in `gitserver` and `server`.
run `sg wolfi image gitserver` and `sg wolfi images server`
> Update `gitserver` and `server` images

- dev/sg/internal/wolfi/base-image.go
to make copy/pasting command easier
after `sg wolfi image server`, see that the suggested command to run the image does not end with ellipses.
> Remove ellipses after docker command

- schema/site.schema.json
Removed setting because its unused, Perforce is always enabled.
> Deprecate unused perforce setting

- cmd/gitserver/server/patch.go
[Slack thread](https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1689124650296469)
Backport, manual test
> [Backport] Redact command before logging  during create-commit-from-patch (#54811)

- dev/nix/ctags.nix
add missing `ln` for `ctags` without version since it is referenced in shell.nix
tested locally
> nix: add ln to ctags without version

- cmd/gitserver/server/patch.go
There was already a url redactor declared higher up.
N/A
> Remove redundant url redactor

- client/web/src/components/externalServices/ExternalServiceEditPage.tsx
- client/web/src/components/externalServices/ExternalServicePage.tsx
- client/web/src/components/externalServices/externalServices.test.tsx
- client/web/src/components/externalServices/externalServices.tsx
Fixes a bug where GitHub and GitLab code hosts that aren't github.com or gitlab.com has their settings disappear.
This comes from a recent code change where we're no longer distinguishing between GitHub and GitHub enterprise connections (or GitLab and GitLab on-prem conns)
Confirmed locally. Function adjusted to no longer be able to return undefined, as it doesn't make sense. Tests that should have been failing updated as well.
> [fix] GHE and GitLab code host types not showing settings

- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.java
Part of https://github.com/sourcegraph/sourcegraph/issues/55916
We referenced the agent binary by `agent-windows-x64.exe`, but it should really be `agent-win-x64.exe`. This PR fixes this.
Got rid of the error message after this change.
> JetBrains: Fix agent binary name for Windows

- .buildkite/hooks/pre-exit
We've observed failures in e2e tests due to dangling containers. Despite the a `docker rm -f` being run in the pre-exit they aren't being removed. 
I suspect this is because for some reason, this is being read as one container name, and not as two separate containers. I've done some testing and you can observe in the output below
```
2023-08-21 09:17:47 CST | docker ps -a | 0s
-- | -- | --
  | 2023-08-21 09:17:47 CST | CONTAINER ID   IMAGE     COMMAND                  CREATED          STATUS          PORTS                  NAMES
  | 2023-08-21 09:17:47 CST | 54254a437fdc   nginx     "/docker-entrypoint.…"   35 seconds ago   Up 34 seconds   0.0.0.0:7081->80/tcp   pedantic_faraday
  | 2023-08-21 09:17:47 CST | 6acac2db587f   nginx     "/docker-entrypoint.…"   40 seconds ago   Up 38 seconds …
```
> ci: use array for running containers in preexit

- internal/service/svcmain/svcmain.go
Since executors currently do not assist the Cody App disable starting them to avoid docker issues.
Build release version `CODESIGNING=0 CI=false ./enterprise/dev/app/build.sh`
Verify app startup and no docker containers running
> App: disable executors for Cody App

- .buildkite/hooks/pre-command
Part of https://github.com/sourcegraph/sourcegraph/issues/55661
We've adding an echo command to see dangling containers, but because we don't monitor carefully all builds, we're surely missing them. 
This PR fixes that by opening a sentry ticket it it happens, so we won't miss those ever again. 
To be dropped commit, that triggers Sentry to ensure it's working as intended.
➡️ https://sourcegraph.sentry.io/issues/4410318138/?project=6110304&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
> ci: report dangling containers on Sentry

- cmd/frontend/internal/httpapi/httpapi.go
- cmd/frontend/internal/httpapi/search.go
- deps.bzl
- dev/backcompat/defs.bzl
- go.mod
- go.sum
- internal/search/backend/metered_searcher.go
Manual cherry pick of #54394 since there were many merge conflicts
---
This endpoint was unused which was why it was removed in Zoekt. The changes from Zoekt included in this dep bump:
- 1686b50d50 indexserver: remove unused GetRepoRank
- 7078a585a9 shards: populate RepoList.Stats.Repos
- b9e6d9433e zoekt-indexserver: Check stderr for git fetch
- 93f7b0c983 matchtree: capture Stats before pruning
- 7643f3b313 matchiter: capture metric NgramLookups
Test Plan: CI
(cherry picked from commit 49aff3d61c8479a296ba3379e7cabab97635be07)
> [backport 5.1] search: update zoekt with removal of RepositoryRankRequest (#54394)

- client/web/src/cody/components/ChatUI/ChatUi.tsx
- client/web/src/cody/widgets/CodyRecipesWidget.tsx
- client/web/src/cody/widgets/components/RecipeAction.tsx
- client/web/src/get-cody/GetCodyPage.tsx
- client/web/src/nav/GlobalNavbar.tsx
- client/web/src/util/constants.ts
Closes #[55848](https://github.com/sourcegraph/sourcegraph/issues/55848), adds a promo for Cody IDE extensions in the Cody tooltip & Cody chat response feedback footer:
- CI/CD
> Promo Cody IDE after every Cody Web interaction

- client/web/src/cody/chat/CodyChatPage.tsx
- client/web/src/cody/components/ChatUI/ChatUi.tsx
- client/web/src/cody/components/GettingStarted.tsx
- client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
- client/web/src/cody/useCodyChat.tsx
- client/web/src/repo/RepoContainer.tsx
#55846 follow up - Adds a utility function to transcription events logged to consolidate accounting for a nullable `transcript` in one place in the store
- CI/CD
> #55846 follow up - Transcript event logger refactor

- client/web/src/org/backend.ts
- client/web/src/org/settings/members/OrgSettingsMembersPage.tsx
This fixes #56104 by removing the "role" column from the members page and not querying `siteAdmin` for a given `user`.
Only site-admins can query `user.siteAdmin`, so instead of loosening that restriction we remove the column.
- Manual testing by opening an org page and listing the members on that page
> org members page: fix auth access when listing members as non-admin

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyAgentProjectListener.java
- client/jetbrains/src/main/java/com/sourcegraph/telemetry/PostStartupActivity.java
Fixes https://github.com/sourcegraph/sourcegraph/issues/56049
It's idempotent to start/stop the agent so it's safe run this more frequently.
n/a
> JetBrains: start/stop agent on install/unistall events

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/vscode/CancellationToken.java
Fixes https://github.com/sourcegraph/sourcegraph/issues/56042
Previously, we didn't correctly propagate autocomplete cancelation to the agent. This was problematic because we could end up queueing a lot of autocomplete requests making the experience lag. This PR fixes the problem by sending a `$/cancelRequest` notification to the agent as implemented in https://github.com/sourcegraph/cody/pull/787
While using the plugin, confirm that we're sending a lot of `$/cancelRequest` notifications. Also confirm that autocomplete still works as expected.
```
❯ tail -f build/sourcegraph/cody-agent-trace.json  | grep cancelRe
```
My anecdotal experience is that autocomplete feels somewhat snappier with this change, which makes sense if we're cancelling old requests more aggressively.
> JetBrains: add cancelation support

- enterprise/cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
- enterprise/cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user_test.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/service_account.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/service_account_test.go
Previously, headers and query strings could overwrite the feature flags, to prevent this, we're reading from the DB directly now.
cc #inc-234
Adjusted tests, got early feedback in slack.
> dotcom: Don't allow feature flag overrides for service account

- dev/release/src/release.ts
This was not bumped. Now it is.
Locally tested
> release tool: bump migrator tag in `deploy-sourcegraph-k8s` during releases

- dev/release/src/release.ts
- Closes #55790 
The existing `sed` pattern didn't catch the executor directories. The updated command targets all `Chart.yaml` files.
Locally tested
> release tool: bump chart versions of executor charts during release

- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
This fixes #56080 by truncating the output of the failing git command in case it failed.
When it _didn't_ fail, we don't want to truncate anything, but when it fails, 5000 bytes is probably enough output.
- I tested the helper function manually because I'm prone to off-by-one errors
- I do not know how to properly test this without pulling in a mock-lib from src-cli or overwriting `$PATH` in the test to put a different `git` in that'll fail. Suggestions welcome.
> gitserver: truncate output when ls-tree fails

- doc/dev/how-to/use_feature_flags.md
Previously this wasn't documented. The documentation in general is very much targetted from before we had a UI for this, but just adding this in.
Ideally I would want to document this better in the client libraries we use, but the API docs don't really document behaviour and instead rely on these docs.
Test Plan: n/a
[Preview Link](https://docs.sourcegraph.com/@k/ff-override-docs)
> doc: add documentation on per-request featureflag overrides

- doc/_resources/assets/docsite.css
- doc/_resources/assets/docsite.js
**Summary:**
This PR introduces a "Copy Code" button to all code snippets across the documentation site, enhancing user experience by allowing users to easily copy example code for their use.
Related Issue(s): [#15](https://github.com/sourcegraph/documentation/issues/15)
**Changes:**
- Added a new utility function, copyCode, to handle the clipboard action.
- Integrated the "Copy Code" button to our existing code snippet component.
- Updated styles and UX to ensure the button is unobtrusive but clear.
**Screenshots:**
Attached are screenshots highlighting the changes across various themes.
**Note:**
Feedback on the button's style or positioning is welcome. We aim for maximum user convenience with minimum distraction.
Kindly check and let me know if any changes are required. …
> Add "Copy Code" Button to Code Snippets

- deps.bzl
- go.mod
- go.sum
This PR updates zoekt to https://github.com/sourcegraph/zoekt/commit/f75df3d8a3f8de3003da19567bf13429563036cb, which include https://github.com/sourcegraph/zoekt/pull/640.
CI
> update zoekt to f75df3d8a3f8de3003da19567bf13429563036cb

- client/web/BUILD.bazel
- client/web/src/site-admin/site-config/SiteAdminConfigurationPage.tsx
- client/web/src/site-admin/site-config/forms/external-url/index.tsx
related #55431
- #55431
tested locally, UI changes only, see screenshots. behind a feature flag that is by default off
> feat: add external URL form

- client/jetbrains/src/main/resources/META-INF/plugin.xml
Previously, the plugin allowed dynamic loading, which could cause issues where the plugin was not working unless the user restarted IDEA. This PR fixes the problem by specifying that the plugin does not support dynamic loading and IDEA will therefore require the user to restart the IDE.
More details: https://plugins.jetbrains.com/docs/intellij/dynamic-plugins.html
n/a
> JetBrains: require restart after installation

- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.java
Previously, we would report "agent is not connected" even when we had a successful agent connection. The root problem was that a string variable `agentNotRunningExplanation` could be non-empty even when we were connected. This PR fixes the problem by ignoring the value of `agentNotRunningExplanation` when we are testing for a connection.
n/a
> JetBrains: fix `CodyAgent.isConnected` logic

- client/web/src/cody/chat/CodyChatPage.tsx
- client/web/src/cody/components/HistoryList/HistoryList.tsx
- client/web/src/cody/sidebar/CodySidebar.module.scss
- client/web/src/cody/sidebar/CodySidebar.tsx
Closes #55746 - Hides delete chat item or clear all chat history when there are no chat interactions. Updates chat history icon to match [VS Code's](https://github.com/sourcegraph/cody/pull/323)
- Manual test on cody sidebar & cody chat page: With chat history and without
> [cody/web] Papercuts: Hide delete & update history icon

- .vscode/cody.json
- doc/cody/capabilities.md
This PR adds a new section of **Cody Commands** in our [Capabilities](https://docs.sourcegraph.com/cody/capabilities) docs.
- [Slack thread](https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1692636946491599)
Docs added
[Preview Link](https://docs.sourcegraph.com/@cody-commands)
> Add Cody Commands docs in VS Code

- doc/_resources/assets/redirects
The PR adds redirects for our new Cody Quickstart tutorial.
Docs added
[Preview Link](https://docs.sourcegraph.com/@redirects-cody-quickstart)
> Add redirects for Cody QS

- sg.config.yaml
This updates the `sg start qdrant` config to use the qdrant image published by sourcegraph rather than the qdrant-published image. This just makes the local env a bit closer to what gets deployed.
Ran an embedding job locally and ran a search via qdrant.
> sg: use sourcegraph image for qdrant

- internal/embeddings/index_storage.go
- internal/embeddings/types.go
- internal/embeddings/types_test.go
We are seeing an out of bounds access on the Embeddings slice that implies corrupted data. This prevents us from trying to read the index after unmarshalling if it is corrupted in this way.
Test Plan: added unit test
> embeddings: validate unmarshalled EmbeddingIndex

- enterprise/cmd/frontend/internal/dotcom/init.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
- enterprise/cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user_test.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/graphql.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/licenses_graphql.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/service_account.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/service_account_test.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql_test.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/tokens_graphql.go
- enterprise/cmd/frontend/internal/dotcom/productsubscription/tokens_graphql_test.go
- internal/audit/audit.go
- internal/audit/audit_test.go
- internal/audit/audittest/BUILD.bazel
- internal/audit/audittest/audittest.go
- internal/audit/audittest/audittest_test.go
This change adds audit logging to successful access to product subscriptions, licenses, and Cody Gateway dotcom users, recording `grant_reason` and propagating `access` to indicate the use case the prompted the access.
Audit logs are recorded under 2 "entities":
- `dotcom-productsubscriptions`
- `dotcom-codygatewayuser`
Unit/integration test cases covering:
- return of `grant_reason` from our lowest-level `serviceAccountOrOwnerOrSiteAdmin` helper for checking access
- audit logging of access to Cody Gateway dotcom user
- audit logging of access to product subscription and active license
> productsubscription: add audit logs

- .github/teams.yml
- .github/test.CODEOWNERS
- cmd/gitserver/server/CODENOTIFY
- cmd/repo-updater/CODENOTIFY
- internal/extsvc/CODENOTIFY
- internal/gitserver/CODENOTIFY
- internal/repos/CODENOTIFY
To not spam their accounts indefinitely, removing them from codenotify.
Just some config files.
> Remove GitHub handles from notifications

- schema/site.schema.json
A very naive approach to allow the magic word `REDACTED` to be excempted from field validation using `pattern`. However, the error message for `pattern` isn't as user-friendly as builtin validation rules.
Alternatively, 
1. We can just change the `minLength` to be `1` (that just ensures it's not empty)
2. Update the field description to include the requirement (i.e. "the value must be at least 20 characters").
<table>
<tr><td><img width="587" alt="CleanShot 2023-08-23 at 23 02 09@2x" src="https://github.com/sourcegraph/sourcegraph/assets/2946214/486890ce-c858-4daf-819f-8d9fd52952c8">
<tr><td><img width="515" alt="CleanShot 2023-08-23 at 23 02 04@2x" src="https://github.com/sourcegraph/sourcegraph/assets/2946214/25dcc746-e302-4012-9ffe-e435e81fef71">
</table>
> site: use `pattern` to replace `minLength` for secret field validation

- internal/embeddings/db/migrate.go
This fixes the field type for the `repoID` index, which will make it an effective index (it's currently ignored by the planner). For some reason, I was thinking I was using a string for `repoID`. 
Manually tested that embedding a repo still works and that the index claims there are points in it.
> Qdrant: fix field type

- wolfi-packages/p4-fusion.yaml
- wolfi-packages/p4cli.yaml
We previously verified the Perforce-published hash so fetching over http isn't an issue. However, using https is best practice.
This is a holdover from fetching over HTTP in the old Dockerfiles, and wasn't picked up in the migration to packaging.
Well spotted @evict !
- Green CI - hash is verified as part of CI pipeline
- Manually check package works before merging
> Update p4 package to fetch over https

- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/CompletionEvent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AcceptCodyAutocompleteAction.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutocompleteTelemetry.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
- client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
This adds the remaining autocomplete telemetry data that the vs code extension currently sends.  This includes language, provider, lineCount, charCount and additional source information.
The suggestion's id is also included so it is possible to connect the suggested event to the accepted event.
`./gradlew -PforceAgentBuild=true :runIde`
Capture event data 
```json
{
"event": "CodyJetBrainsPlugin:completion:suggested",    
"source": "IDEEXTENSION",
"referrer": "JETBRAINS",    
"publicArgument": "{\"latency\":927,\"displayDuration\":520,\"isAnyKnownPluginEnabled\":false,\"contextSummary\":{\"embeddings\":null,\"local\":2,\"duration\":3.05745792388916},\"id\":\"o2rg1k8p1\",\"languageId\":\"go\",\"source\":\"Network\",\"charCount\":2,\"lineCount\":1,\"multilineMode\":null,\"providerIdentifier\ …
```
> JetBrains: Add remaining autocomplete telemetry parameters 

- deps.bzl
- dev/zoekt/update
- go.mod
- go.sum
This includes the changes from https://github.com/sourcegraph/zoekt/pull/641
CI
> zoekt: update to 40a9a23bb04b

- internal/conf/BUILD.bazel
- internal/conf/client.go
Fixes https://sourcegraph.slack.com/archives/C04HCK4K3DL/p1691782868033789
Our configuration package has logic to automatically retry requests if any of them fail. However, on startup, it's likely the case that any given client will start before the frontend configuration server fully initializes. In the HTTP path, we had logic to "ignore" logging connection errors that occur during this initialization peroid. 
We regressed on this behavior when we introduced gRPC powered site configuration in #55648. This PR adds similar logic for gRPC to reduce the logspam on startup. 
1) Before this change, run `sg start` from scratch with `SRC_GRPC_ENABLE_CONF: "true"` set in your `sg.config.yaml`. 
See errors like the following pop up in your terminal:
```
[    gitserver-1] ERROR …
```
> conf: grpc: support silent retries if frontend isn't ready yet

- internal/database/feature_flags.go
- internal/database/feature_flags_test.go
Clears Redis store with evaluated feature flag values when the feature flag value/rollout basis changes. 
Previously, the hash table storing the evaluated feature flag value for users has been deleted [only when the feature flag was deleted](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/feature_flags.go?L16:5-16:20#tab=references). Feature flag value change didn't clear the cache, resulting in incorrect rollout feature flags users split. 
For example (more details in [this thread](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1693220251878639?thread_ts=1692782949.435119&cid=C022SPMNR0W)):
- A feature flag is created with a rollout value of 1,000 basis points, leading to an expected split of 10/90.
- A certain number of users evaluate it, with …
> clear evaluated FF cache on FF value change

- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
- cmd/cody-gateway/shared/config.go
- deps.bzl
- internal/completions/httpapi/codecompletion.go
Fireworks have added llama code base model support for us.
- Only adding a new code completion model string
> Add llama-v2-13b-code support

- doc/_resources/templates/root.html
Adding GA tag on docs website to the root element of docs website.
Docs changes
[Preview Link](https://docs.sourcegraph.com/@add-ga)
> Add GA details to root doc

- client/jetbrains/README.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.java
- client/jetbrains/src/main/java/com/sourcegraph/common/BrowserErrorNotification.java
- client/jetbrains/src/main/java/com/sourcegraph/common/ErrorNotification.java
- client/jetbrains/src/main/java/com/sourcegraph/config/NotificationActivity.java
- client/jetbrains/src/main/java/com/sourcegraph/config/PluginSettingChangeActionNotifier.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsChangeListener.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsConfigurable.java
- client/jetbrains/src/main/java/com/sourcegraph/find/FindPopupPanel.java
- client/jetbrains/src/main/java/com/sourcegraph/find/browser/BrowserAndLoadingPanel.java
- client/jetbrains/src/main/java/com/sourcegraph/website/CopyAction.java
- client/jetbrains/src/main/resources/META-INF/plugin.xml
- Renamed the plugin to "Sourcegraph Cody + Code Search"
- Updated readme to emphasize the dual purpose of the plugin more.
Only string and docs changes, only the PR review is needed.
> JetBrains: Rename plugin

- client/browser/src/shared/code-hosts/gitlab/scrape.ts
Fixes the `getPageInfo` throwing a `Unable to determine project name` error when the new navigation is enabled.
- Enable new navigation in GitLab
- Have sourcegraph enabled in user preferences
- Visit a file
- Without this change sourcegraph will throw an error
> Fix GitLab project name with new navigation enabled

- internal/auth/userpasswd/BUILD.bazel
- internal/auth/userpasswd/handlers.go
- internal/security/BUILD.bazel
- internal/security/security.go
- internal/security/security_test.go
This PR adds functionalities to block certain email domains during registration. This allows us to create and maintain a configmap of disallowed email domains.
Tested locally, added test.
> Allow banning of email domains for DotCom registration

- cmd/cody-gateway/shared/config.go
Otherwise without this var set the service will not start properly.
Verified it starts up correctly again.
> codygateway: Make fireworks key optional

- cmd/gitserver/server/server_grpc.go
- cmd/gitserver/server/server_test.go
- internal/gitserver/client.go
- internal/gitserver/client_test.go
Our REST P4Exec implementation first checks to see if the provided credentials are valid before running streaming the p4 output. If it's invalid, the server returns a http.BadRequest response to the client:
https://github.com/sourcegraph/sourcegraph/blob/3e50ff1a904b8fb0e6d2eb010e33cab56503c91d/cmd/gitserver/server/server.go#L1731-L1739
Our client implementation is written in such a way where these errors are _immediately_ returned to the caller, without the need to consume the response body:
https://github.com/sourcegraph/sourcegraph/blob/457dc4813fc7614d84f91d0fb40404068ff1e362/internal/gitserver/client.go#L944-L956
The gRPC version of this function does the same credentials check, but it didn't maintain the invariant of _immediately_
returning credential errors to the caller. Instead, …
> grpc: p4exec: adjust client implementation to error immediately if a permission related error occurs

- internal/search/backend/BUILD.bazel
- internal/search/backend/grpc.go
- internal/search/backend/horizontal.go
grpc-zoekt webserver support has been running successfully on sourcegraph.com for a while now, so there is no need for two layers of feature flags here.
sourcegraph.com will speak zoekt-webserver via gRPC when the main conf.IsGRPCEnabled setting is set to true (like every other service).
CI
> grpc: remove zoekt-webserver specific feature flag

- internal/debugserver/grpcui.go
- sg.config.yaml
The [gRPCWebUI](https://github.com/fullstorydev/grpcui) debug page for each of or services will only be enabled if GRPC_WEB_UI_ENABLED is set to true (false by default). 
1. Run `env GRPC_WEB_UI_ENABLED=false sg start`, open https://sourcegraph.test:3443/-/debug/proxies/frontend-127.0.0.1/debug/grpcui/ and see the following:
1. Run `env GRPC_WEB_UI_ENABLED=true sg start`, open https://sourcegraph.test:3443/-/debug/proxies/frontend-127.0.0.1/debug/grpcui/ and see the following:
> grpc: put grpcwebui behind environment variable

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsChangeListener.java
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyDisableAutocompleteAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyEnableAutocompleteAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyStatusBarActionGroup.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyStatusBarWidget.kt
- client/jetbrains/src/main/resources/META-INF/plugin.xml
Fixes #56281 
https://github.com/sourcegraph/sourcegraph/assets/18601388/6d4d5628-a0d2-4c4a-9638-01aca872ce9c
Note: the toggle only enables/disables autocomplete on the application level for now. We should probably have a separate toggle to enable/disable on the project level as well.
- green CI
- the `enable` toggle only appears when autocomplete is disabled globally
- likewise, the `disable` toggle only appears when autocomplete is enabled globally
> JetBrains: Cody: Add a status bar toggle to enable/disable autocomplete

- dev/ci/bazel-prechecks-apply.sh
- dev/ci/bazel-prechecks.sh
- enterprise/dev/ci/internal/ci/bazel_operations.go
Persists & applies `bazel configure` and `bazel run //:gazelle-update-repos` changes in the precheck step which subsequent steps can apply in order to run even if the user forgot to run those commands. We apply these to the bazel test, async and build image candidates steps 
Many many `sg ci build main-dry-run`s
> bazel: run tests even if prechecks fail

- client/jetbrains/flake.lock
- client/jetbrains/flake.nix
The intellij client has different requirements than the main parts of the repo (given the dependency on sourcegraph/cody repo), so lets add a separate flake
N/A nix stuff
> nix: initial client/intellij nix flake

- dev/nix/shell-hook.sh
Not sure why we wouldnt do this, I had to set an action env in .bazelrc temporarily on the mac instead for this, so it makes sense to set it for non-nixos users too
N/A nix-shell specific
> nix: set bazel action env on non-nixos nix shell users too

- client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.tsx
- client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.tsx
See [this Slack thread](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1691502296112349) in which Daniel and Rob agree that we should be consistent and that the preferred variant is the one introduced in #54911.
- Storybook
See:
> batches: change chevrons from up/down to down/right
