- doc/code_navigation/explanations/writing_an_indexer.md
Useful gotcha + suggested fix in case someone else runs into this too.
n/a
[Preview Link](https://docs.sourcegraph.com/@vg/add-gotcha)
> docs: Cover gotcha for SCIP indexers implemented in C++

- enterprise/cmd/frontend/internal/search/resolvers/resolver.go
- enterprise/cmd/frontend/internal/search/resolvers/search_jobs_connection.go
- internal/search/exhaustive/service/service.go
- internal/search/exhaustive/store/BUILD.bazel
- internal/search/exhaustive/store/exhaustive_search_jobs.go
- internal/search/exhaustive/store/store.go
This ignores all arguments sent via graphql and always lists all search jobs created by a user. This should be something we can build on.
From reading the graphql schema we likely need a way to establish which users we are listing for, unless that is somehow part of the query field. In particular I am thinking of admins looking at search jobs.
Test Plan: manually ran the below graphql query locally
```graphql
query {
searchJobs {
nodes {
id
query
}
}
}
```
> searchjobs: PoC of listing search jobs

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
Resolve the warning that the method may return null. In response to the following reported stack trace.
```
java.lang.IllegalStateException: @NotNull method com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.inferLineSeparator must not return null
at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.$$$reportNull$$$0(CodyAutocompleteManager.java)
at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.inferLineSeparator(CodyAutocompleteManager.java:321)
at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.displayAgentAutocomplete(CodyAutocompleteManager.java:276)
at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.lambda$processAutocompleteResult$8(CodyAutocompleteManager.java:256)
...
```
Unable to recreate crash but updated code resolves warning that …
> JetBrains: ensure nonnull line separator method can't return a null 

- .github/workflows/trufflehog.yml
Bumping Trufflehog version o v3.54.3 to include my changes from https://github.com/trufflesecurity/trufflehog/pull/1742
CI 🟢  with trufflehog action 🟢
> bumped trufflehog version to v3.54.3

- doc/cloud/index.md
- doc/cloud/private_connectivity_aws.md
- doc/cloud/private_connectivity_gcp.md
also updated the comparision between private code hosts and public code hosts to get the terminology straight to avoid confusion
```sh
sg run docsite 
```
visit http://localhost:5080/cloud#private-code-host-support
> docs: add gcp private code host support

- internal/cmd/search-blitz/scripts/build.sh
This is to just help with showing the images that have been built and avoid the need to visit the webpage.
Test Plan: manually ran the command
> search-blitz: run list-tags in build help output

- client/web/src/user/settings/auth/ExternalAccount.tsx
- client/web/src/user/settings/auth/__snapshots__/ExternalAccount.test.tsx.snap
- internal/extsvc/github/common.go
[Slack Thread](https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1693616116217119)
The profile link for GitHub external account links to the API view for a user's profile instead of the actual link. This is fixed as I updated the component to concatenate the user's login with `https://github.com/`.
I considered changing this from the backend so the URL points to the actual user page; however, that information comes from GitHub, and it makes sense that we don't change it in the database as it'll affect old accounts also.
* Snapshot update
* Manually tested
> source: update profile link for github

- enterprise/cmd/worker/internal/search/exhaustive_search_repo.go
- enterprise/cmd/worker/internal/search/exhaustive_search_test.go
- enterprise/cmd/worker/internal/search/job.go
This implements the handler of the second worker of the seach jobs processing chain.
Test plan:
- Updated unit test
- I ran the following query locally
```
mutation {
createSearchJob(query:"1@rev1 1@rev2 2@rev3") {
id
}
}
```
and verified the contents of `exhaustive_search_jobs`, `exhaustive_search_repo_jobs` and `exhaustive_search_repo_revision_jobs`.
> search jobs: implement exhaustiveSearchRepoHandler

- client/web-sveltekit/src/routes/search/RepoSearchResult.svelte
PR #55542 added support for missing search results and refactored some code. Seems like I missed updating repo search results to use the new API.
- `pnpm dev`
- Open search page and search for `type:repo test`.
-> Search results are rendered without error
> sveltekit: Fix error when rendering repo search results

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/render/AutocompleteRenderUtils.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/render/CodyAutocompleteElementRenderer.java
- client/jetbrains/src/main/java/com/sourcegraph/config/CodyApplicationService.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/config/PluginSettingChangeContext.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsChangeListener.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
- client/jetbrains/src/main/java/com/sourcegraph/config/SettingsConfigurable.java
It resolves https://github.com/sourcegraph/sourcegraph/issues/56097
* Go to cody settings page
* Check Enable Cody autocomplete checkbox
* Check Enable custom autocomplete color checkbox
* Pick the color that you want to use for cody autocomplete hint
* Press OK
* Trigger autocompletion
Reopened https://github.com/sourcegraph/sourcegraph/pull/56236 PR to pass github checks.
> JetBrains: customize autocomplete color new branch

- internal/usagestats/code_monitoring.go
- internal/usagestats/code_monitoring_test.go
- internal/usagestats/code_monitoring_usage_stats.sql
- Before, `MonitorsEnabled` wouldn't populate, so it always returned 0.
- Now, `MonitorsEnabled` returns total monitors across webhooks, slack, and emails.
1. Adjusted unit test to account for new `monitors_enabled` field. 
2. Made sure test passes.
3. Manually tested: Ran dev environment, created code monitors, and made sure the next ping accounted for those code monitors, and that `MonitorsEnabled` no longer returned 0 when there are available code monitors.
> populate monitors_enabled field

- cmd/frontend/internal/httpapi/auth.go
Reduces logs related to bad user input to `warn`. We have started to generate a huge amount of these events in Sentry recently: https://sourcegraph.slack.com/archives/C05497E9MDW/p1694017736611569?thread_ts=1694017010.274539&cid=C05497E9MDW
n/a
> httpapi/auth: use audit logs for user errors

- enterprise/cmd/worker/internal/search/BUILD.bazel
- enterprise/cmd/worker/internal/search/exhaustive_search_repo.go
- enterprise/cmd/worker/internal/search/exhaustive_search_repo_revision.go
- enterprise/cmd/worker/internal/search/exhaustive_search_test.go
- enterprise/cmd/worker/internal/search/job.go
- internal/search/exhaustive/service/BUILD.bazel
- internal/search/exhaustive/service/search.go
- internal/search/exhaustive/service/service.go
- internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs.go
- internal/search/exhaustive/types/BUILD.bazel
- internal/search/exhaustive/types/exhaustive_search.go
This implements the worker that runs the user's query against 1 repo@rev.  For now we use a fake CSVWriter IE results are not yet persisted to a blobstore.
Test plan:
> search jobs: implement exhaustiveSearchRepoRevHandler

- cmd/frontend/enterprise/enterprise.go
- cmd/frontend/internal/cli/serve_cmd.go
- cmd/frontend/internal/httpapi/httpapi.go
- cmd/frontend/internal/httpapi/router/router.go
- enterprise/cmd/frontend/internal/search/BUILD.bazel
- enterprise/cmd/frontend/internal/search/httpapi/BUILD.bazel
- enterprise/cmd/frontend/internal/search/httpapi/export.go
- enterprise/cmd/frontend/internal/search/init.go
- enterprise/cmd/frontend/internal/search/resolvers/BUILD.bazel
- enterprise/cmd/frontend/internal/search/resolvers/resolver.go
- enterprise/cmd/frontend/internal/search/resolvers/search_job.go
- internal/search/exhaustive/service/service.go
This registers the handler to download the results of a search job in csv format. For now we only return dummy data.
Test plan:
I manually tested the following workflow
- Create search job in API Console
```graphql
mutation {
createSearchJob(query: "1@rev1 1@rev2 2@rev3 3@rev5") {
id
}
}
```
- Use the id to request the URL
```graphql
query {
node(id:"U2VhcmNoSm9iOjMy") {
... on SearchJob {
URL
}
}
}
```
- Download the file
```
curl -JO -H 'Authorization: token <TOKEN>' <URL>
```
- check the downloaded csv
> search jobs: add boilerplate to download results

- internal/search/exhaustive/store/BUILD.bazel
- internal/search/exhaustive/store/exhaustive_search_jobs_test.go
- internal/search/exhaustive/store/exhaustive_search_repo_jobs_test.go
- internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs_test.go
- internal/search/exhaustive/store/store_test.go
Three things in three commits:
- Added a unit test for `Get` and `List` - I think it's fine having them both in a single test right now. Just a sanity check really.
- Removed the `cleanup` stuff, since that's not necessary: `dbtest.New` creates a new database for every test, so state is not global and thus does not need to be cleaned up and THUS cleaning up is actually costing us time, you know
- Another `basestore.ScanAny` switch
- New and existing tests
> exhaustive search store: refactoring 2 - return of the scan helpers (and also: unit test & cleanup)

- dev/tool_deps.bzl
Follow-up to https://github.com/sourcegraph/devx-support/issues/217
For some reason, the universal ctags binary was rebuilt, and because the urls are the same, it broke when trying to run locally. 
This went unnoticed because the disk cache still have the old ref, and because the url didn't change, bazel made it work. 
We should add a buildnumber when we're creating the assets, to avoid this kind of issues. 
Locally tested + CI
> bzl: update sha256 for ctags

- client/web/src/site-admin/UserManagement/components/DateRangeSelect.tsx
Closes [#56380](https://github.com/sourcegraph/sourcegraph/issues/56380)
This PR adds improvements to the date selector component used in user management (`site-admin/users`) page.
1. When a user clicks the `Clear` button, they do not need to click the `Apply` button. The Clear action automatically resets the date range to `undefined` and the `isNegated` value to `false`.
2. The `Apply` button will be disabled when the date is required, `isNegated` is false and there's no date range selected.
3. The `Apply` button will be enabled when `isNegated` is true regardless of whether a date range is selected or not.
4. The `Apply` button will be enabled when `isNegated` is false, date is required and a date range is selected.
5. The `Apply` button will be disabled when a single date is selected. …
> source: improvement to user management date selector

- cmd/frontend/internal/httpapi/auth.go
- internal/authz/BUILD.bazel
- internal/authz/header.go
- internal/authz/header_test.go
This should help us identify traffic better.
Added a test to ensure the logs are actually how we expect them to look like.
> Add temporary logging to dotcom sudo handler

- internal/authz/header.go
- internal/authz/header_test.go
Previously if a header such as `Authorization: token` was passed, it would throw a sudo error on DotCom. We now make sure that we have the correct schema to ensure it's truly a sudo scheme.
Tested locally, added tests.
> Resolve sudo error for empty token header

- enterprise/dev/ci/scripts/wolfi/build-base-image.sh
- enterprise/dev/ci/scripts/wolfi/build-package.sh
older version of melange is breaking my build: https://buildkite.com/sourcegraph/sourcegraph/builds/241239 (it worked locally using the latest v0.4.0)
we might as well bump apko with it, the difference between local and CI is annoying https://sourcegraph.slack.com/archives/C04MYFW01NV/p1692288383092059?thread_ts=1692287435.835749&cid=C04MYFW01NV
CI
> ci/wolfi: upgrade packages and images build deps

- internal/codeintel/autoindexing/internal/inference/libs/update-shas.sh
This patch lets it be invoked from other directories,
as well as allows DOCKER_USER and DOCKER_PASS to be unset
(such as on a dev machine).
Manually ran the update script again.
> codeintel: Make update-sha script more flexible

- internal/search/exhaustive/service/BUILD.bazel
- internal/search/exhaustive/service/search_test.go
I am busy implementing the NewSearcher for real and this test logic is useful to reuse. This commit just refactors the existing test case to make the assertion part re-useable. It also has the nice side-effect of putting all the bits we assert on next to each other which makes the test easier to understand.
> searchjobs: factor out newSearcher test logic

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccount.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SourcegraphServerPath.kt
- client/jetbrains/src/test/kotlin/com/sourcegraph/cody/config/SourcegraphServerPathTest.kt
Previously user had to insert full url as a complete and valid url, now we're able to adjust the inserted text so it's easier for user to configure a server url
For server url without the schema we're adding the `https://` schema automatically.
For server url without `/` at the end we're adding the `/` automatically
- Configure new account with server url in a simplified form, we should be able to adjust the url so it's possible to connect to our backend.
> JetBrains: manually construct server url to fix any issues with it

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsConfigurable.kt
Accounts panel is now much smaller as we don't need to take as much space.
Previously
Now
- Accounts panel should display 3 and a half of accounts instead of taking so much space which can be used by other settings
> JetBrains: make accounts panel smaller

- enterprise/cmd/frontend/internal/search/resolvers/resolver.go
- enterprise/cmd/worker/internal/search/exhaustive_search_test.go
- internal/search/exhaustive/service/service.go
- internal/search/exhaustive/store/exhaustive_search_jobs.go
- internal/search/exhaustive/store/store.go
We cancel the search job and all jobs that derive from it.
Test plan:
- locally tested with
```graphql
mutation create {
createSearchJob(query: "1@rev1 1@rev2 2@rev3") {
id
}
}
mutation cancel  {
cancelSearchJob(id: "<id>") {
alwaysNil
}
}
```
> search jobs: implement Resolver.CancelSearchJob

- cmd/searcher/internal/search/hybrid_test.go
- cmd/searcher/internal/search/search.go
- cmd/searcher/internal/search/search_test.go
- cmd/searcher/protocol/searcher.go
This makes it so the server side of searcher will never read the FeatHybrid field in a request, and always treat it as true. This is the server side step of removing the hybrid search feature flag which has been rolled out successfully for many many months.
Test Plan: CI
> searcher: always do hybrid search

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
These events are not needed for our analytics and we're currently sending a very large volume of these events.
n/a
> JetBrains: stop logging `completion:started` events

- internal/database/dbconn/open.go
The errors.Errorf string dates back to sourcegraph being open sourced and likely was missed in a migration to using error wrapping.
I took a quick look to see if we have any references to the string mentioned here in docs/etc and found nothing. Also took a quick look at uses of errors.Is/etc and didn't see anything that would change behaviour. Nearly all code around here relies on strings.Contains because that is all we had back in the day when this code was written.
Test Plan: CI
> dbconn: wrap did not start error

- enterprise/cmd/frontend/internal/search/BUILD.bazel
- enterprise/cmd/frontend/internal/search/init.go
- enterprise/cmd/frontend/shared/service.go
- enterprise/cmd/worker/internal/search/BUILD.bazel
- enterprise/cmd/worker/internal/search/job.go
- internal/search/exhaustive/uploadstore/BUILD.bazel
- internal/search/exhaustive/uploadstore/store.go
- sg.config.yaml
This adds a blobstore for search job results to the worker and frontend. 
The worker will need the blobstore to upload results, frontend will need it to aggregate the CSV. 
This is mostly copy&paste from embeddings and codeintel.
Note:
- We should think about a central blobstore config instead of copy&pasting like I did here. I think for now this is ok to maintain speed for the sake of the first release but it feels wrong to copy&paste this in the future.
- CI
- We are not using the blobstore anywhere yet, so this should be save. Locally I confirmed that I can upload a blob.
> search jobs: add blobstore

- internal/database/dbtest/dbtest.go
We ran into this this week and I just saw Noah run into it. This likely would of saved time and should help in the future.
Test Plan: yolo
> dbtest: mention bazel tag needed when we don't connect to DB

- internal/repos/github.go
While reading the code and trying to understand whether state is modified somewhere, I noticed that `paginate` doesn't have to be a method.
I think as a function it's cleaner because it's easier to understand that it doesn't access `GitHubSource`.
> github source: tiny refactor to make `paginate` a function

- internal/codemonitors/background/workers.go
- internal/repos/syncer.go
Improve error logging at some common sources of logspam: https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1694018298564529 - at error level, this is causing us to get rate-limited in Sentry.
See self-review comments for details
No idea who to tag for reviews these days 😆 
CI
> repos, codemonitors: remove duplicate error logging

- doc/cody/capabilities.md
- doc/cody/use-cases.md
Changes /fix to /edit (to reflect the product change) in the Cody docs.
Docs only, local testing.
[Preview Link](https://docs.sourcegraph.com/@cody-docs-change-fix-to-edit)
> Update /fix command to /edit in Cody docs

- client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.module.scss
- client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.tsx
- client/branded/src/search-ui/results/progress/__snapshots__/StreamingProgressSkippedPopover.test.tsx.snap
- client/wildcard/src/components/Alert/Alert.module.scss
- client/wildcard/src/components/Alert/Alert.story.tsx
- client/wildcard/src/components/Alert/Alert.tsx
This PR adds yet another alert variation — "an alert block without alert icon within", This variation is needed for the newly added search job (exhaustive search creation banner UI on the search page); see screenshots below
| Light | Dark |
| ------ | ------ |
| <img width="381" alt="Screenshot 2023-09-06 at 19 39 41" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/970f1ec5-b0ea-41f7-8632-94d0601bde8a"> | <img width="375" alt="Screenshot 2023-09-06 at 19 39 53" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/dba69d26-c82a-4d0d-a8a9-1db9b6da0f92"> |
It also fixes a few corner cases in the layout when we have 0 results
- Check storybook alert UI story where a new alert block without icon is presented 
- Check the search jobs UI (you have to enable it first, …
> Wildcard Adjust exhaustive search creation alert banner styles

- cmd/gitserver/server/server_grpc.go
- cmd/gitserver/server/server_test.go
- internal/gitserver/client.go
- internal/gitserver/commands_test.go
- internal/gitserver/protocol/gitserver.go
- internal/gitserver/v1/gitserver.pb.go
- internal/gitserver/v1/gitserver.proto
Manual backport of https://github.com/sourcegraph/sourcegraph/pull/55990, which was accidentally not cherry-picked into the 5.1 branch.
Conflicts:
internal/gitserver/client.go
internal/gitserver/v1/gitserver.pb.go
CI
> [backport 5.1] gRPC: use byte slices for exec args (#55990)

- .gitignore
- client/web/BUILD.bazel
- client/web/package.json
- client/web/src/LegacyLayout.tsx
- client/web/src/cody/chat/CodyChatPage.tsx
- client/web/src/cody/components/ChatUI/ChatUi.tsx
- client/web/src/cody/components/CodeMirrorEditor.ts
- client/web/src/cody/components/FileContentEditor.ts
- client/web/src/cody/components/GettingStarted.module.scss
- client/web/src/cody/components/GettingStarted.tsx
- client/web/src/cody/components/RepoContainerEditor.ts
- client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
- client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
- client/web/src/cody/components/ScopeSelector/backend.ts
- client/web/src/cody/components/ScopeSelector/useRepoSuggestions.ts
- client/web/src/cody/sidebar/CodySidebar.tsx
- client/web/src/cody/sidebar/Provider.tsx
- client/web/src/cody/useCodyChat.tsx
- client/web/src/components/useUserHistory.ts
- client/web/src/repo/RepoContainer.tsx
- client/web/src/routes.tsx
- client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
- pnpm-lock.yaml
Closes https://github.com/sourcegraph/sourcegraph/issues/55363.
This PR provides suggestions to the context selector, so that it's less empty when you initially open the popover and it hopefully takes less work to find the repos you want to use Cody with.
| Scenario | | Note |
|-----:|:-----------:|----|
| Popover first opened | <img width="300" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/8942601/4dae8ec2-6794-4a39-ad42-c6f5d6a43058"> | The suggestions fill most of the popover window area and can be scrolled through. |
| When several suggestions have been added | <img width="300" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/8942601/9d789d75-74b5-4693-94ce-d3c8be2c895c"> | Any repos added from suggestions move to populate the "Repositories" …
> cody web: provide suggestions in context selector

- CHANGELOG.md
- internal/extsvc/github/v3.go
- internal/extsvc/github/v3_test.go
- internal/extsvc/github/v4.go
- internal/extsvc/github/v4_test.go
See [this comment](https://github.com/sourcegraph/customer/issues/2329#issuecomment-1711735942) and the issue it's in for full context.
Short version:
1. GitHub v3 and v4 clients execute this bit of code multiple times when retrying a request after it ran into rate limits: https://github.com/sourcegraph/sourcegraph/blob/16458d7e5c07ac69d00d32841a1a7dcd55a50ddb/internal/extsvc/github/common.go#L1589-L1590
2. When executed multiple times with the same `url.URL`, `req.URL.Path` ends up with invalid paths like `/api/v3/api/v3`
That lead to 404 errors showing up _sometimes_: when the client runs into rate limit and retries. And _sometimes_ these 404s were even ignored and lead to a "successful" end of the syncing process.
This changes the behaviour of the clients to keep a copy of the original …
> github: fix erratic 404s by keeping URL stable

- internal/repos/github.go
[Context](https://sourcegraph.slack.com/archives/C03K05FCRFH/p1694164347656019)
It seems when fetching GitHub repos, we return early before processing the last batch of repositories. This fixes that so we process every repository always.
* unit tests are passing
* testing fetching repos with ghe instance and nothing is broken
> source: return full repository when fetching public github repos

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/AddCodyAccountWithTokenAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/BaseLoginDialog.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccount.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountListModel.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyLoginRequest.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsConfigurable.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/AccountsPanelFactoryExtensions.kt
It's possible now to edit account from context menu (right click on account) 
- Right click on existing account and edit some fields, account should be updated after clicking "Apply" on dialog, reset and closing the dialog without applying the settings should not change account
- Add and remove should still work
> JetBrains: add ability to edit account from context menu

- cmd/sourcegraph/osscmd/BUILD.bazel
- cmd/sourcegraph/osscmd/osscmd.go
Since OSS apps don't exist anymore, and we now use this entrypoint for the previous enterprise services, we should get rid of this, it might cause weird behavior with authz providers being empty briefly after startup. Instead, we should rely on the services to properly fetch the providers.
sg start stack still works.
> Don't configure empty dummy authz providers in OSS apps

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt
It fixes #56122 
* Install IdeaVIM plugin
* Enter visual mode
* Navigate to closest whitespace to trigger autocomplete
* Autocomplete should not be triggered
> JetBrains: Cody: disable autocomplete with IdeaVIM visual mode

- client/web/src/util/size.test.ts
- client/web/src/util/size.ts
This slipped through the crack. I added a utility function to display size in a human-readable format. However, the logic for deriving the display value for sizes of over 1TB was wrong. 
This PR fixes that and ensures the human-readable size is correct.
* Updated the tests
* Manual testing on my local instance
> source: properly display size in terabytes

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
- Got a suggestion here: https://github.com/sourcegraph/sourcegraph/pull/56053#issuecomment-1714760515 that the line break inference didn't make sense. This is an attempt to remove some redundant code.
- Try to reproduce https://github.com/sourcegraph/sourcegraph/issues/55512 on Windows after this change.
> JetBrains: Just use \n

- client/jetbrains/CONTRIBUTING.md
The contributing docs had a lot of information that made it a bit overwhelming to read. This PR removes a lot of old and less useful instructions and adds a new table with an overview of the most useful commands to use for local development.
I'm hoping to replace the sdkman setup soon with Gradle toolchains.
n/a
> JetBrains: update contributing docs

- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AcceptCodyAutocompleteAction.java
Clears the last autocomplete candidate after acceptance so that new autocompletes will get a new ID 
closes https://github.com/sourcegraph/sourcegraph/issues/56469
Tested with https://github.com/sourcegraph/cody/pull/998
Accepted an autocomplete and then immediately removed it and triggered another
Got the same suggestion but verified the id was different.
```
[Trace - 09:00:18 AM] Sending request 'graphql/logEvent - (33)'
Params: {
"event": "CodyJetBrainsPlugin:completion:accepted",
"userCookieID": "4cbce745-e0bd-43d9-97ea-fc08be33ac0c",
"url": "",
"source": "IDEEXTENSION",
"referrer": "JETBRAINS",
"argument": {},
"publicArgument": {
"contextSummary": {
"local": 2.0,
"duration": 10.141000270843506
},
"id": "8rpyvgn2g",
"languageId": "go",
"source": "Network",
"charCount": 32, …
```
> JetBrains: clear last autocomplete candidate after acceptance

- sg.config.yaml
When running in debug mode, we disable Go optimizations / inlining with `export GCFLAGS='-N -l'`, but this causes the debugger to fail to access variables when stepping through files (error: `(unreadable could not find loclist entry at 0x13b3835 for address 0x1063d4aa4)`), likely due to the fact that our GCFLAGS value only disables optimizations in main package?
Context:
- https://github.com/go-delve/delve/issues/1320#issuecomment-415939417
- https://youtrack.jetbrains.com/issue/GO-5311
- Tested locally (as it only affects local debugging)
- Reproduction steps:
-- Run `DELVE=1 sg start dotcom`
-- Put a breakpoint [here](https://sourcegraph.sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph-inc239.git&branch=main&file=internal%2Fgitserver%2Fcommands.go&editor=V …
> Delve for all packages

- client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx
Previously, when using the JetBrains plugin with manual access token creation, the user had to type out the description of the access token. This PR adds the ability for the plugin to optionally include a default description value saving one manual step for the user. With this change, the user only needs to click "Generate token" instead of having to additionally type out a description value.
- Ran `SOURCEGRAPHDOTCOM_MODE=true SOURCEGRAPH_API_URL=https://sourcegraph.com sg start web-standalone`
- Visited URL https://sourcegraph.test:3443/users/olafurpg-testing/settings/tokens/new?description=foobar
- Confirmed that the default value is set
- Visited URL https://sourcegraph.test:3443/users/olafurpg-testing/settings/tokens/new
- Confirmed that the default value is empty, as usual
> Access tokens: add URL search parameter to control default description

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutocompleteProviderType.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/config/UserLevelConfig.java
Updates the list of available autocomplete providers to match what VS Code supports.  Also removes the default value, so that the default logic from the VS Code extension can be applied.  Currently a null value will result in a default to `anthropic` same as before however additional changes are being worked on so that the autocomplete provider will default based on the configuration of the sg instance the user is connected to. 
`./gradlew :runIde -PforceAgentBuild=true` - verify autocomplete works and defaults to anthropic
create `~/.sourcegraph-jetbrains.properties` and set `cody.autocomplete.advanced.provider=unstable-openai` 
restart plugin and verify it is using `unstable-openai` autocomplete provider.
> JetBrains: update autocomplete provider list and default to null

- client/jetbrains/src/main/java/com/sourcegraph/common/BrowserErrorNotification.java
- client/jetbrains/src/main/java/com/sourcegraph/common/BrowserOpener.java
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountListModel.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyLoginPanel.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyTokenCredentialsUi.kt
User can now click on the link that will redirect him to a page on which he can generate a new token
- Try to create/edit an account, link to generate a new token should appear and should redirect user to page on which he can generate new access token
> JetBrains: add link to generate new token

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/package.md
Added documentation to copied `auth` package with markdown as it is the default way of doing it in kotlin
- Green CI
> JetBrains: document `auth` package 

- .github/workflows/sg-setup.yml
- .tool-versions
- WORKSPACE
- dev/sg/checks.go
Upgrades go from 1.20.5 to 1.20.8 which includes
go1.20.6 (released 2023-07-11) includes a security fix to the net/http package, as well as bug fixes to the compiler, cgo, the cover tool, the go command, the runtime, and the crypto/ecdsa, go/build, go/printer, net/mail, and text/template packages. See the Go 1.20.6 milestone on our issue tracker for details.
go1.20.7 (released 2023-08-01) includes a security fix to the crypto/tls package, as well as bug fixes to the assembler and the compiler. See the Go 1.20.7 milestone on our issue tracker for details.
go1.20.8 (released 2023-09-06) includes two security fixes to the html/template package, as well as bug fixes to the compiler, the go command, the runtime, and the crypto/tls, go/types, net/http, and path/filepath packages. See the Go …
> go: Upgrade to 1.20.8

- deps.bzl
- doc/admin/observability/dashboards.md
- go.mod
- go.sum
- internal/search/backend/BUILD.bazel
- internal/search/backend/grpc.go
- internal/search/backend/zoekt.go
- monitoring/definitions/frontend.go
- monitoring/definitions/git_server.go
- monitoring/definitions/repo_updater.go
- monitoring/definitions/searcher.go
- monitoring/definitions/shared/grpc.go
- monitoring/definitions/symbols.go
- monitoring/definitions/zoekt.go
This bumps Zoekt to https://github.com/sourcegraph/zoekt/commit/3ce1f2b24c80b3dea89d237600d2b0879342ed1b
- bumps the version of zoekt we depend on: https://github.com/sourcegraph/sourcegraph/pull/56525/commits/4f25112a402f1376c668976876b90ceafc81a1f7
- using this new version of zoekt, implement a gRPC dashboard for zoekt-webserver: https://github.com/sourcegraph/sourcegraph/pull/56525/commits/e47723fa09cd95ec979e64546489d3cfe87807f5
See the screenshot below for what the new graphs look like:
CI
[Preview Link](https://docs.sourcegraph.com/@update-zoekt-prometheus-grpc-metrics)
> zoekt: update to 3ce1f2b24c80b3dea89d237600d2b0879342ed1b

- CHANGELOG.md
- doc/admin/repo/perforce.md
- internal/authz/providers/perforce/authz.go
- internal/authz/providers/perforce/cmd/scanprotects/main.go
- internal/authz/providers/perforce/cmd/scanprotects/main_test.go
- internal/authz/providers/perforce/perforce.go
- internal/authz/providers/perforce/perforce_test.go
- internal/authz/providers/perforce/protects.go
- internal/authz/providers/perforce/protects_test.go
- schema/perforce.schema.json
- schema/schema.go
User access to Perforce depots is sometimes denied unintentionally when using `"authorization"/"subRepoPermissions": true` in the code host config and the protects file contains exclusionary entries with the Host field filled out. Ignoring those rules (that use anything other than the wildcard (`*`) in the Host field) is now toggle-able by adding `"authorization"/"ignoreRulesWithHost"` to the code host config and setting the value to `true`. 
This will cause the protects parser to simply ignore all rules that specify a Host.
closes #53374
Added unit tests to verify correct behavior of the protects file parser.
> Add config to allow for ignoring Perforce protects rules that specify a Host

- client/web/src/components/CopyableText.tsx
- client/web/src/settings/tokens/AccessTokenCreatedAlert.tsx
[Context](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1694188323196199)
When a user creates an access token on Sourcegraph, we currently display the token by default in plain text. Sometimes the user is in a public place and this token could be captured by an attacker and used for malicious purposes.
This PR hides the token by default and the user can then click to see it or simply just copy it for use.
* I manually went through the flow of creating an access token by visiting my profile page [`/users/<USER>/settings/tokens`](https://sourcegraph.sourcegraph.com/users/bolaji.olajide-tkzij/settings/tokens)
* Then clicking on the `Generate new token` button
* This should display the newly created access token with the token hidden by default.
> hide access token by default after creation

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/api/CachingGraphQLQueryLoader.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/api/GraphQLFileNotFoundException.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/api/SourcegraphGQLQueryLoader.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/DeferredIconRepaintScheduler.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/ScaleContextCache.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/ScalingAsyncImageIcon.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/SimpleAccountsListCellRenderer.kt
More unstable API moved from IntelliJ to our sources because they broke the compatibility in new releases of Intellij IDEA
- Add account in new version of IntelliJ IDEA should work and should load the user avatar
> JetBrains: move caching graphql query loader to our sources from IntelliJ

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/config/NotificationActivity.java
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyApplicationSettings.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt
Closes #56096
- After installing the plugin the notification with code search onboarding appeared and now it is removed so when you install the plugin the notification on how to use code search is not going to be displayed
> JetBrains: removes code search onboarding

- cmd/frontend/graphqlbackend/BUILD.bazel
- cmd/frontend/graphqlbackend/site_test.go
- internal/database/repo_statistics_test.go
I was looking at existing usages of cmp.Diff and noticed these two
looked a bit unidiomatic, so I figured I'd simplify them.
n/a
> cleanup: More idiomatic cmp.Diff API usage

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.java
Fixes bug introduced in https://github.com/sourcegraph/sourcegraph/pull/56506
* Trigger autocomplete manually (by pressing alt + backslash)
> JetBrains: Cody: Fixing manual autocomplete trigger

- cmd/frontend/internal/httpapi/releasecache/config.go
Simply renames the URN for the release cache so that it's more identifiable.
N/A
> Rename release cache rate limiter urn

- cmd/gitserver/shared/shared.go
- cmd/worker/internal/ratelimit/job.go
- internal/extsvc/azuredevops/client.go
- internal/extsvc/bitbucketcloud/BUILD.bazel
- internal/extsvc/bitbucketcloud/client.go
- internal/extsvc/bitbucketserver/BUILD.bazel
- internal/extsvc/bitbucketserver/client.go
- internal/extsvc/crates/BUILD.bazel
- internal/extsvc/crates/client.go
- internal/extsvc/gerrit/BUILD.bazel
- internal/extsvc/gerrit/client.go
- internal/extsvc/github/v3.go
- internal/extsvc/github/v4.go
- internal/extsvc/gitlab/client.go
- internal/extsvc/gomodproxy/BUILD.bazel
- internal/extsvc/gomodproxy/client.go
- internal/extsvc/npm/npm.go
- internal/extsvc/pagure/BUILD.bazel
- internal/extsvc/pagure/client.go
- internal/extsvc/pypi/BUILD.bazel
- internal/extsvc/pypi/client.go
- internal/extsvc/rubygems/BUILD.bazel
- internal/extsvc/rubygems/client.go
- internal/ratelimit/BUILD.bazel
- internal/ratelimit/globallimiter.go
- internal/ratelimit/globallimiter_test.go
- schema/schema.go
- schema/site.schema.json
When redis-store goes down (during rollouts, for example) all upstream operations that request a rate limit token will fail immediately. This is not great.
Instead, we are trying an approach now that adds retries. We attempt to get the rate limit up to 8 times, and wait between 50 and 250ms for a total of 400ms to 2000ms of additional wait time before failing now. This number is just guesswork, and will not fully cover a rollout, but keep delays low. We will test this on dotcom and see what a good number would be.
In addition, instead of failing we are now falling back to an in-memory limiter instead. The limiter uses either 1/s as it's internal rate, or siteconfig.defaultRateLimit, if configured.
Tests still pass and we're trying this out on dotcom to see if this fixes issues while …
> globallimiter: Improve reliability

- client/jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt
It fixes #56511 
* Enable Cody autocomplete
* Navigate with arrows, autocomplete should not be triggered
* Autocomplete should be triggered after pressing spacebar
https://github.com/sourcegraph/sourcegraph/assets/9321940/2da1af24-140e-4b31-baa7-57b75596b5f4
> JetBrains: Cody: Disable autocomplete when navigating with arrow keys

- dev/sg/linters/gogenerate.go
Fixes https://github.com/sourcegraph/devx-support/issues/59
CI
> sg: avoid silently discarding files if lint go is ran locally

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentCodebase.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/ExtensionConfiguration.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/EmbeddingExistsParams.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/context/EmbeddingStatusView.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/java/com/sourcegraph/vcs/RepoUtil.java
Previously, the Cody sidebar always said that the git repo did not exist. This PR fixes the problem by correctly showing what repository got inferred, and it additionally shows whether the repository has embeddings enabled or not.
Tested with https://github.com/sourcegraph/cody/pull/1045 
* Open the sourcegraph/about repository
* Open any file in the repository
* Notice that the embedding status gets updated when the file is opened
> JetBrains: fix repo embedding status in chat sidebar

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyTokenCredentialsUi.kt
Previously, when creating an account, users had to manually type out the description for their access token. This PR fixes the problem by providing a default access token description, allowing the user to only click on "Generate token" without additional steps.
Manually test tested with sourcegraph.com token (where `?description` URL parameter is already respected).
> JetBrains: automatically generate access token description

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/java/com/sourcegraph/config/CodyAuthNotificationActivity.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/PersistentActiveAccountHolder.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/AccountsListModel.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/AccountsPanelFactoryExtensions.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/SignInWithSourcegraphAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/SimpleAccountsListCellRenderer.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/AddCodyAccountWithTokenAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/BaseLoginDialog.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountListModel.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountsHost.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyApplicationSettings.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyLoginPanel.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyLoginRequest.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyPersistentAccountsHost.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyProjectActiveAccountHolder.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/NotifyAboutNoActiveAccount.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ServerAuth.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsMigration.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsModel.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/AccountConfigurable.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/CodeSearchConfigurable.kt
- client/jetbrains/src/main/resources/META-INF/plugin.xml
Closes #56033 
Previously we displayed a notification that a user doesn't have an enterprise account and he can only access public repos. Now we removed all of the noisy notification and we have only one notification displayed per project if project doesn't have active account configured. There is a link in the notification to Open Cody which will open the Cody sidebar where user will be guided to create an account > https://github.com/sourcegraph/sourcegraph/issues/56024 
The notification can be dismissed for all of the projects with "Never Show Again" action
- Open new project where you don't have an active account and notifcation should be displayed where you can click on the "Open Cody" action, then Cody sidebar should appear
> JetBrains: unify onboarding notifications

- dev/check-tokens.sh
Detection isn't perfect, since the SA key file is json formatted, but matching on `service_account` and the GCP SA email structure should be sufficient.
- tested with a real GCP SA key file
- no false positives on current repo content
> Support detecting GCP SA keys

- cmd/gitserver/server/gitservice.go
- internal/service/servegit/serve.go
- lib/gitservice/BUILD.bazel
- lib/gitservice/gitservice.go
- lib/gitservice/gitservice_test.go
src-cli doesn't use logger, so this changes the pattern to instead make how we log injectable by the client. Currently the logger is just not set in src-cli leading to a nil pointer panic. After this is merged a follow up PR will go out for that.
Additionally this PR fixes a use for sourcegraph app which didn't set the logger as well.
Test Plan: CI
> gitservice: use an error hook instead of a logger

- .github/workflows/jetbrains-tests.yml
GitHub settings to enable a status check identifies it by the job name, not the workflow name (see https://stackoverflow.com/questions/68554735/github-action-status-check-missing-from-the-list-of-checks-in-protected-branch-s) 
CI
> gh: give a proper name to Jetbrains test job

- client/jetbrains/CHANGELOG.md
- client/jetbrains/src/main/resources/META-INF/plugin.xml
Partially addresses #56620
We still need to verify the compat on CI, so won't close the ticket after this is merged
- `since-build` JetBrains platform version declared in `plugin.xml` should match the backwards compat of API we use
- for the purpose of this PR, mostly the Kotlin UI DSL stuff was checked
> JetBrains: Cody: Bump Jetbrains platform compat to `221.5080.210`

- internal/database/external_services.go
- internal/database/external_services_test.go
- internal/repos/other.go
- internal/repos/other_test.go
- schema/other_external_service.schema.json
- schema/schema.go
Closes #56057 
Adds a config option for "Other" code host connections that only works on DotCom:
By adding
```json
"dotComPublic": true
```
to the code host config, repos added by that connection will be marked as public. This needs to be added explicitly, so it is on the configurator of that code host connection that all the repositories added by that connection is in fact public repositories.
https://github.com/sourcegraph/sourcegraph/assets/6427795/01cef46e-2814-43b2-b7be-3572622af2bd
When not on Sourcegraph.com, the config can't be saved at all:
Unit test as well as local test.
> Add dotComPublic config for Other gitrepo type

- internal/repos/sync_worker.go
We're currently keeping canceled jobs forever, this adds canceled jobs to the prune method.
Verified locally using sg start. This method needs refactoring to be programmatically testable, so saving that for another day.
> extsvc: Also delete old canceled jobs

- cmd/github-proxy/BUILD.bazel
- cmd/github-proxy/README.md
- cmd/github-proxy/github-proxy.go
- cmd/github-proxy/image_test.yaml
- cmd/github-proxy/shared/BUILD.bazel
- cmd/github-proxy/shared/service.go
- cmd/github-proxy/shared/shared.go
- cmd/github-proxy/shared/shared_test.go
- enterprise/dev/ci/images/images.go
- go.mod
- go.sum
Just to be safe and make rollbacks easier, we keep building `github-proxy` for a while.
N/a
> Restore github-proxy temporarily

- cmd/gitserver/server/BUILD.bazel
- cmd/gitserver/server/patch.go
- cmd/gitserver/server/server.go
- cmd/gitserver/server/server_test.go
- cmd/gitserver/server/urlredactor/BUILD.bazel
- cmd/gitserver/server/urlredactor/urlredactor.go
- cmd/gitserver/server/urlredactor/urlredactor_test.go
- cmd/gitserver/server/vcs_syncer_git.go
- cmd/gitserver/server/vcs_syncer_perforce.go
Self-contained code piece, so it can live in it's own package, decluttering the massive gitserver package.
Moved code, relying on CI.
> gitserver: Move urlredactor to separate package

- cmd/gitserver/server/vcs_syncer_perforce.go
This should give us more insight into what command is actually timing out when checking if a depot is cloneable.
n/a
> perforce: Improve error messages for timeouts

- dev/managedservicesplatform/terraformcloud/terraformcloud.go
On a VCS workspace:
```
sg msp tfc sync --workspace-run-mode=cli ./services/msp-testbed/service.yaml
```
Then, in a module:
```
terraform apply
```
> managedservicesplatform: fix enabling CLI mode on TFC workspace

- dev/managedservicesplatform/internal/stack/project/BUILD.bazel
- dev/managedservicesplatform/internal/stack/project/project.go
Validates generated project ID does not exceed GCP maximum (30 characters)
n/a
> sg/msp: add project ID validation

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
Previously, Cody chat reported a warning that there was no context when a chat message had no context files. This warning was not necessary since it's normal for some messages to have no context.
n/a
> JetBrains: don't warn about missing context with empty context files

- cmd/frontend/graphqlbackend/recorded_commands.go
- cmd/gitserver/server/patch.go
- cmd/gitserver/server/server.go
- cmd/gitserver/server/vcs_syncer_git.go
- internal/wrexec/recording_cmd.go
Closes [#56041](https://github.com/sourcegraph/sourcegraph/issues/56041)
This PR implements redaction for recorded commands. With this, we will be storing redacted command args and output.
> source: Implement redaction for recorded commands

- client/jetbrains/src/main/resources/META-INF/plugin.xml
> JetBrains: use "Sourcegraph & Cody" title in settings UI

- cmd/blobstore/internal/blobstore/BUILD.bazel
- cmd/blobstore/internal/blobstore/blobstore.go
- cmd/blobstore/internal/blobstore/blobstore_test.go
- cmd/blobstore/internal/blobstore/s3_routes.go
- internal/embeddings/index_storage_test.go
- internal/uploadstore/gcs_client.go
- internal/uploadstore/gcs_client_test.go
- internal/uploadstore/lazy_client.go
- internal/uploadstore/mocks/mocks_temp.go
- internal/uploadstore/s3_client.go
- internal/uploadstore/store.go
We extend `Store.List` and allow the caller to filter the objects by prefix. I need the prefix in a follow-up PR to iterate over all blobs associated with a search job.
`Store.List` isn't used anywhere, so it is fine to modify it instead of adding a dedicated new method.
Why isn't `Store.List` used anywhere?
I added this method a while ago to support the effort to create a single source of truth for embeddings. However, in the end I decided for a different approach. I left the method in place because I anticipated we might use it soon for other purposes.
updated unit tests
> uploadstore: list with prefix

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
Previously, the state of the chat transcript went out of sync between what was visible in the JetBrains UI and what the Cody worker (aka. agent) modeled internally. This PR fixes the problem by sending a `transcript/reset` notification when the user triggers the "Reset conversation with Cody" action.
This PR must be tested alongside the PR https://github.com/sourcegraph/cody/pull/1073
- Add `console.log({messages})` statement to Cody file `lib/shared/src/chat/chat.ts`
- Run `./gradlew -PforceAgentBuild=true :runIDE` 
- Send chat message "Hello", confirm transcript has one "Hello" message
- Send chat message "Goodbye", confirm transcript has one "Hello" message and one "Goodbye" message
- Switch active account, send new message "Hello 2" and confirm transcript  has three messages
- Reset …
> JetBrains: correctly manage chat transcript

- cmd/frontend/graphqlbackend/repository.go
- internal/database/BUILD.bazel
- internal/database/repo_commits_changelists.go
- internal/database/repo_commits_changelists_test.go
- internal/perforce/changelist.go
This produced an uncaught error when the commit SHA was an actual integer (`5123123`) and we parsed it correctly as an int and then tried to query.
- Manual testing by cloning `sourcegraph/cody` and accessing https://sourcegraph.test:3443/github.com/sourcegraph/cody@5816435/-/blob/vscode/src/completions/providers/unstable-azure-openai.ts (note the `5816435`)
> repository changelist resolver: correctly handle changelist id not found

- internal/testutil/BUILD.bazel
- internal/testutil/golden.go
Frustrated by your tests failing due to inconsequential whitespace? Fret no more! Introducing semantic comparison of JSON test results, using state-of-the art tools!
What tests the tests? Who watches the watchers?!
J/K - ran `bazel test //internal/batches/... //internal/extsvc/...` to ensure this change to the golden testing tool did not disrupt any existing tests. It didn't.
> Compare JSON test output semantically instead of as strings.

- dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
GCP validation apparently requires a dash here or something
> managedservicesplatform: add '-' to cloudrun SA

- cmd/cody-gateway/internal/httpapi/completions/anthropic.go
We are seeing requests flagged from App users, which we don't currently record out of an abundance of caution. Failure to record generates an error that is causing some noise in #alerts-cody-gateway.
[Question was raised about what to do here](https://sourcegraph.slack.com/archives/C05Q75F9ES3/p1694722458698469), but some of this usage seems fairly innocent, and the errors are not that high frequency (31 occurrences so far, from a small set of users). It doesn't seem to be a high priority right now, and I don't know if anyone is even using the recorded prompts, so let's just downgrade this log to a warning for now, and possibly remove the functionality entirely in the future.
n/a
> cody-gateway: downgrade recording errors to warn

- internal/updatecheck/client.go
- internal/updatecheck/client_test.go
Change the default Pings endpoint to be https://pings.sourcegraph.com.
Without a release, this is only realistically affecting dotcom.
Boot up locally
In request logs:
and in BQ:
> updatecheck: use new pings endpoint

- cmd/frontend/internal/httpapi/httpapi.go
- cmd/pings/shared/main.go
- internal/updatecheck/client.go
- internal/updatecheck/handler.go
Now we have pings.sourcegraph.com as the official pings service, dotcom would actually forward than consuming those pings directly (for backward compatibility for SG instances older than 5.2.0).
1. Grab the ping request body from https://sourcegraph.com/site-admin/pings and save it as a file named `dotcom-ping.json`
2. Boot up local instance in dotcom mode: `sg start dotcom`
3. `curl -X POST -H "Content-Type: application/json" -d @dotcom-ping.json https://sourcegraph.test:3443/.api/updates`
Then in BigQuery table:
> updatecheck: forward ping requests to pings.sourcegraph.com

- client/jetbrains/build.gradle.kts
- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentCodebase.kt
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentServer.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/GetRepoID.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/context/EmbeddingStatusView.kt
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/EditCodebaseContextAction.kt
- client/jetbrains/src/main/resources/META-INF/plugin.xml
Previously, there was no way for users to hard-code a specific repository that should be used for the embeddings context. This PR fixes the problem by making the repository name a button that opens a form to change the codebase when you click on it. The name of the codebase is validated with the API so help the user prevent writing a typo.
Test with this PR https://github.com/sourcegraph/cody/pull/1079
- Open a repository
- Open a file
- Open Cody sidebar
- Click on the repository name
- Try typing a repo that doesn't exist
- Update the text to be a repo that does exist
- Press OK confirm that the custom repo is selected
- Click on the repo again
- Make the input field empty
- Press OK
- Confirm that the repo name is inferred
> JetBrains: add button to change codebase context

- client/web/src/enterprise/search-jobs/SearchJobsPage.module.scss
- client/web/src/enterprise/search-jobs/SearchJobsPage.story.tsx
- client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
- cmd/frontend/graphqlbackend/search_jobs.go
- cmd/frontend/graphqlbackend/search_jobs.graphql
- cmd/frontend/internal/search/resolvers/BUILD.bazel
- cmd/frontend/internal/search/resolvers/resolver.go
- cmd/frontend/internal/search/resolvers/search_job.go
- enterprise/cmd/worker/internal/search/exhaustive_search_test.go
- internal/search/exhaustive/service/service.go
- internal/search/exhaustive/store/exhaustive_search_jobs.go
- internal/search/exhaustive/store/exhaustive_search_jobs_test.go
This updates the GraphQL schema for repo jobs and implements pagination and filtering for `searchJobs`.
- new unit test for list logic
- manual testing via API Console
I tested variations of this query
```graphql
query q {
searchJobs(first: 3, query: "rev3", userIDs: ["VXNlcjox"], states: [COMPLETED]) {
nodes {
id
query
startedAt
state
creator {
id
username
}
}
}
}
```
https://github.com/sourcegraph/sourcegraph/assets/26413131/52b8b91b-75ff-4c3f-a446-77c6de294cc8
> search jobs: fix pagination

- cmd/frontend/graphqlbackend/BUILD.bazel
- cmd/frontend/graphqlbackend/search_results_test.go
- cmd/frontend/graphqlbackend/search_test.go
- cmd/frontend/internal/guardrails/attribution/BUILD.bazel
- cmd/frontend/internal/guardrails/attribution/attribution_test.go
- dev/internal/cmd/search-plan/search-plan.go
- internal/search/client/BUILD.bazel
- internal/search/client/client.go
My goal is to mock gitserver client in another PR. This PR contains a few commits refactoring the search client to make this possible. It does this by storing inside of the search client the runtime clients and moving the creation of the gitserver client into that field.
Please review commit by commit, it contains motivation in the commit messages.
Test Plan: CI is sufficient for this change.
> search: make it possible to mock any RuntimeClients in client

- internal/search/alert/observer.go
This was a likely very rare to trigger bug. The more likely bug to
trigger was it asserted err was nil, but you can find a repo but have
some revs missing (which would result in an error). So this changes
behaviour, but looking at the call sites, function name and
documentation this is now the correct behaviour.
Note: I plan on adding an API which only communicates with the DB and
avoids slower gitserver calls. That may be useful to use here in the
future since this helper is only used for suggestions.
Test Plan: CI
> search: alert reposExist helper handles empty pages

- internal/search/alert/observer.go
- internal/search/repos/repos.go
- internal/search/repos/repos_test.go
We only use the iterator outside of this package. Additionally we don't
need to export Next from the Resolved struct since that is hidden by the
iterator.
> search: unexport repos.Resolver.Resolve

- dev/build-tracker/build/build.go
- dev/build-tracker/build/build_test.go
- dev/build-tracker/build/steps.go
- dev/build-tracker/integration_test.go
- dev/build-tracker/main.go
- dev/build-tracker/main_test.go
- dev/build-tracker/notify/slack.go
- dev/build-tracker/server_test.go
Previously, a notification could be sent **if**:
* the build finished
** OR **
* the job is finished or failed
Sometimes a notification can slip through, where a build is finished but not really failed. Now a notification  will only be sent once we recieve the `build.finished` event. We then determined whether the build is failed / fixed / passed and if it hasn't passed, we send a notification
* `go test //dev/build-tracker/...`
* `go test //dev/build-tracker/... -run TestSlackNotification -RunSlackIntegrationTest`
> build-tracker: only send notifications when a build is finished

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/SaveAccessTokenHttpService.java
- client/jetbrains/src/main/resources/META-INF/plugin.xml
- client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx
- Closes https://github.com/sourcegraph/sourcegraph/issues/56384
Three main changes:
- Hooked up the "Sign in free with Sourcegraph.com" button to open the correct remote URL. (It needed some iteration to reach a format that works well with the existing logic).
- Adjusted the "Authorize" page to accept our requests, display the correct text, and redirect to the right localhost URL. Generated URLs look like this, and they work: `http://localhost:63342/api/sourcegraph/token?token=sgp_67f78fdd4a115f580c40fd32523fb818f6b3abb5`
- Created a `RestService` to handle deep links to the plugin, and hooked it up with `plugin.xml`. It adds the account correctly.
Caveats:
- I haven't had time to figure out how to call [this function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/clie …
> JetBrains: Return to IDE after token generation

- internal/batches/service/service.go
- internal/batches/service/service_test.go
When calculating available bulk operations for changesets, we activate the `Close Changeset` operation on changesets that are in a failed state.
However, in this case, it shouldn't be because the changesets might not have been published, so it's impossible to close it.
* Updated unit tests
> batches: change condition for closable changesets

- client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx
- cmd/frontend/internal/app/ui/app.html
We used a temporary hack to set the `referrer` meta header to `strict-origin-when-cross-origin` rather than `origin-when-cross-origin` on a single page. But it looks like it's actually fine to use the former site-wide.
- Tested the JetBrains plugin auth process with dotcom; it still works.
- CI
> JetBrains: Move referrer setting to site-wide

- cmd/frontend/enterprise/enterprise.go
- cmd/frontend/graphqlbackend/search_jobs.go
- cmd/frontend/graphqlbackend/search_jobs.graphql
- cmd/frontend/internal/cli/serve_cmd.go
- cmd/frontend/internal/httpapi/httpapi.go
- cmd/frontend/internal/httpapi/router/router.go
- cmd/frontend/internal/search/httpapi/export.go
- cmd/frontend/internal/search/init.go
- cmd/frontend/internal/search/resolvers/search_job.go
- enterprise/cmd/worker/internal/search/exhaustive_search_test.go
- internal/search/exhaustive/service/service.go
- internal/search/exhaustive/store/exhaustive_search_jobs.go
- internal/search/exhaustive/types/exhaustive_search_repo_revision_job.go
We assemble logs in MEM and serve them as CSV on `/search/export/{id}/logs`.
Test plan:
```
mutation create {
createSearchJob(query: "1@rev1 2@rev5 3@rev6") {
id
}
}
query logURL {
node(id: "U2VhcmNoSm9iOjgy") {
... on SearchJob {
logURL
}
}
}
curl -X GET -H 'Authorization: token <SECRET>' <LOG URL>
repo,rev,start,end,status,failure_message
1,rev1,2023-09-18T13:25:58Z,2023-09-18T13:25:58Z,completed,
2,rev5,2023-09-18T13:25:58Z,2023-09-18T13:25:58Z,completed,
3,rev6,2023-09-18T13:25:58Z,2023-09-18T13:25:58Z,completed,
```
> search jobs: serve logs

- cmd/pings/shared/main.go
The initial write timeout was copied from Cody Gateway, but Pings service shouldn't be needing that much long timeout for writing responses.
CI
> pings: lower server write timeout

- cmd/pings/shared/BUILD.bazel
- cmd/pings/shared/main.go
Also need to set `GOOGLE_CLOUD_PROFILER_ENABLED=true` for the deployment.
CI
> pings: call Cloud Profiler init logic

- deps.bzl
- dev/zoekt/update
- doc/admin/observability/dashboards.md
- go.mod
- go.sum
- internal/grpc/defaults/BUILD.bazel
- internal/grpc/defaults/defaults.go
- monitoring/definitions/frontend.go
- monitoring/definitions/git_server.go
- monitoring/definitions/repo_updater.go
- monitoring/definitions/searcher.go
- monitoring/definitions/shared/grpc.go
- monitoring/definitions/symbols.go
- monitoring/definitions/zoekt.go
- schema/schema.go
This updates our zoekt dependency to https://github.com/sourcegraph/zoekt/commit/dfc14cb6a9744c038187a397528971f4012c2a01
This includes the following changes:
- https://github.com/sourcegraph/zoekt/commit/dfc14cb6a9744c038187a397528971f4012c2a01
- https://github.com/sourcegraph/zoekt/commit/2011bba55730f4a3b4e2ae06443b6353dda9009e
- https://github.com/sourcegraph/zoekt/commit/089709e4f3e3f0fd632d8cc07c610d1ecdc4b239
This PR also various grpc-related monitoring changes to accommodate:
-  the upgraded prometheus middleware package
- the inclusion of the message size interceptor with zoekt-webserver
CI
> update zoekt to include updated grpc prometheus 2.0.0 version

- doc/admin/how-to/blobstore_debugging.md
The command for entering a shell in k8s for blobstore don't work and likely never did; `-u` isnt a flag for kubectl and only `blobstore` doesnt work as the pod is suffixed with a random ID, requiring to either do `blobstore-<hash>-<id>` or `deployment/blobstore`
Tested by youngboi @jac
> docs: update kubectl command for blobstore debugging

- dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
- dev/managedservicesplatform/internal/stack/project/project.go
Has enabled and been working for [Pings service project](https://console.cloud.google.com/profiler;timespan=30m/pings;type=HEAP/inuse_space?project=pings-prod-2f4f73edf1db).
> msp: provision Cloud Profiler API access and roles

- client/wildcard/src/global-styles/base.scss
Fixes https://github.com/sourcegraph/sourcegraph/issues/51504.
The intent was to NOT include the @reach/menu-button styles (as evidenced by the comment right below in `base.css`). Omitting them does not cause any ill effects.
Previewed locally in Webpack and esbuild (checked that the UserNavItem dropdown has the correct color).
> fix incorrect theme colors in esbuild css output

- internal/search/repos/BUILD.bazel
- internal/search/repos/repos.go
- internal/search/repos/repos_test.go
This exports an API which allows search jobs to get the revisions that would be searched. This is currently unused but will be used in an upcoming commit.
Test Plan: added unit tests
> search: introduce repos.Resolver.IterateRepoRevs

- enterprise/cmd/worker/internal/search/exhaustive_search.go
- enterprise/cmd/worker/internal/search/exhaustive_search_repo.go
- internal/search/exhaustive/service/search.go
- internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs.go
- internal/search/exhaustive/types/exhaustive_search.go
Previously we would create a worker job per repo@refspec. However, we actually need the list of refspecs from a query to live together since they influence each other. For example the negated glob can remove refs from the final generated list of refs to search.
This commit keeps the string type and doesn't change anything in the DB. However, it updates naming and documentation to reflect that it is a list of refspecs.
I think there are database constraints around this, but I think once we have stuff working in a nice way we should revisit things like the schema and adjust it then.
Test Plan: CI
> search: exhaustive RepositoryRevSpec -> RepositoryRevSpecs

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/EditCodebaseContextAction.kt
Previously, we were sending a blocking network request on the IntelliJ event thread while validating that a repository name exists on the Sourcegraph instance in the dialog to select the Cody codebase context. If the validation didn't return then the IDE was completely frozen. The only wan to fix the problem was to force quit IntelliJ.
This PR fixes the problem by setting a timeout on the blocking requests so that the user at least regains control over their IntelliJ instance.
n/a
> JetBrains: don't block forever on event thread

- CHANGELOG.md
- docker-images/syntax-highlighter/crates/sg-syntax/src/sg_syntect.rs
- internal/highlight/highlight.go
- internal/highlight/language_test.go
- lib/codeintel/languages/BUILD.bazel
- lib/codeintel/languages/languages.go
> Let enry decide the filetype unconditionally for code highlighting

- doc/admin/updates/grpc/index.md
- doc/admin/updates/index.md
This is a more customer-facing version of the enablement page that I wrote in https://github.com/sourcegraph/handbook/pull/7779.
The main goal of this guide to inform customers what is changing and why, and under what circumstances they'll need to change some aspects of their network infra (firewall) before rolling out the 5.2.X. release. 
Just docs 
[Preview Link](https://docs.sourcegraph.com/@doc-grpc-release)
> doc: add grpc guide for 5.2.X release for firewall configuration

- dev/sg/internal/wolfi/update_hashes.go
- dev/sg/sg_wolfi.go
- doc/dev/background-information/sg/reference.md
Allows `update-hashes` to run against a single image. This is useful when you're updating a package and don't want to update everything.
Also improve the final summary message to better indicate what actions were performed and why.
```
> go run ./ wolfi update-hashes jaeger_agent
Checking for hash updates to 'wolfi_jaeger_agent_base'...
✅ Found new digest for index.docker.io/sourcegraph/wolfi-jaeger-agent-base
Updating file ...
✅ Succesfully updated digests in dev/oci_deps.bzl
> go run ./ wolfi update-hashes jaeger_agent_foobar
Checking for hash updates to 'wolfi_jaeger_agent_foobar_base'...
❌ Did not find any images matching 'wolfi_jaeger_agent_foobar_base' in dev/oci_deps.bzl
> go run ./ wolfi update-hashes
Checking for hash updates to all images...
✅ No digests needed to be updated in …
```
> Make `sg wolfi update-hashes` work on single images

- client/shared/src/settings/temporary/tourState.ts
- client/web/BUILD.bazel
- client/web/src/tour/components/Tour/SearchTask.tsx
- client/web/src/tour/components/Tour/Tour.test.tsx
- client/web/src/tour/components/Tour/Tour.tsx
- client/web/src/tour/components/Tour/TourNewTabLink.tsx
- client/web/src/tour/components/Tour/TourTask.tsx
- client/web/src/tour/components/Tour/context.tsx
- client/web/src/tour/components/Tour/useTour.test.tsx
- client/web/src/tour/components/Tour/useTour.ts
- client/web/src/tour/components/Tour/utils.tsx
- client/web/src/tour/data/index.tsx
- schema/onboardingtour.schema.json
Based on #56641 
This PR introduces a new "search query" step type to the onboarding tour. This type takes a query template and a list of code snippets. When the step is rendered it will make an "exploratory" query for each code snippet to find one that returns results. That query is then used in the onboarding tour.
The query template currently supports four variables: `$$userorg, `$$userrepo`, `$$userlang` and `$$snippet`.
The PR also removes the old logic for determining the user's language, which will be supplied by the user in a different way.
https://github.com/sourcegraph/sourcegraph/assets/179026/9d50aa1b-13b3-4ad9-baf0-acc20243d2d8
Existing tests. Run onboarding tour with hardcoded repo and language in browser.
> user onboarding: Add dynamic queries to user onboarding

- cmd/frontend/internal/search/resolvers/resolver.go
Fixes #56783
The accuracy of the cursor was less than the accuracy of the dates in the db. The rounding errors caused the pagination to behave oddly.
Test plan:
https://github.com/sourcegraph/sourcegraph/assets/26413131/0e7dfafa-0a32-49bc-9f9e-0cdc3c4482d1
> search jobs: fix bug in bidirectional pagination

- dev/managedservicesplatform/internal/stack/project/project.go
- dev/managedservicesplatform/managedservicesplatform.go
Makes it easier to identify the project
n/a
> managedservicesplatform: include env ID in display name

- cmd/frontend/graphqlbackend/external_service.go
- cmd/gitserver/server/vcs_syncer_perforce.go
- internal/repos/perforce.go
Enable the "Test connection" button in the code host page UI
Click the "Test connection" button in the code host connection UI. A message with an orange border will display, "Checking code host connection..." and then "Code host is reachable" should display with a green border.
> Enable "Test connection" for Perforce code hosts

- dev/oci_deps.bzl
Updated hashes for Wolfi base images.
Manually backported from https://github.com/sourcegraph/sourcegraph/pull/56554.
In addition to the hashes, I've also updated the repository to pull images from dockerhub to bring it inline with main. This shouldn't cause any issues, as it's how we've been building images on main. It'll also make future backports much simpler.
- Tested on DotCom and S2
> Backport 56554 to 5.1

- internal/updatecheck/build.go
In non-dotcom deployment, there is no frontend to respond to `conf.Get` and ~~seems to be~~is the cause of leaking goroutines/mem overtime:
CI
> updatecheck: call `conf.Get` only in running on dotcom

- dev/managedservicesplatform/internal/stack/project/project.go
- dev/managedservicesplatform/managedservicesplatform.go
- dev/managedservicesplatform/spec/service.go
This is rather finicky - we need to be careful not to change the defaults or existing projects
https://github.com/sourcegraph/managed-services/pull/7
> managedservicesplatform: fix project ID length detection, add config to shorten it

- deps.bzl
- doc/admin/observability/dashboards.md
- go.mod
- go.sum
- monitoring/definitions/frontend.go
- monitoring/definitions/git_server.go
- monitoring/definitions/repo_updater.go
- monitoring/definitions/searcher.go
- monitoring/definitions/shared/BUILD.bazel
- monitoring/definitions/shared/grpc.go
- monitoring/definitions/symbols.go
- monitoring/definitions/zoekt.go
- monitoring/go.mod
- monitoring/go.sum
- schema/schema.go
This PR adds a gRPC grafana dashboard for frontend's site configuration server. This required some refactoring to support multiple gRPC service dashboards on the same grafana page.
CI
Produced the above screenshot while connected to sourcegraph.com's prometheus instance:
[Preview Link](https://docs.sourcegraph.com/@grpc-frontend-2-servers)
> grpc: add dashboard for site-configuration service to frontend grafana page

- doc/admin/permissions/index.md
This adds a short section to "Permissions" so that users aren't completely lost. It links to the actual pages that tell the user how to configure things.
It's a first bandaid fix. We need to clean up this page.
|--------|------|
| <img width="1260" alt="screenshot_2023-09-19_12 32 23@2x" src="https://github.com/sourcegraph/sourcegraph/assets/1185253/73047536-625a-47a0-b744-c71ffd272e9f"> | <img width="1172" alt="screenshot_2023-09-19_12 32 54@2x" src="https://github.com/sourcegraph/sourcegraph/assets/1185253/fc98e36d-594f-4796-a805-0970e0fb4edf"> |
- Local testing
[Preview Link](https://docs.sourcegraph.com/@mrn/docs-permissions)
> docs: add "Getting started" section to Permissions docs

- internal/search/exhaustive/service/BUILD.bazel
- internal/search/exhaustive/service/searcher.go
- internal/search/exhaustive/service/searcher_test.go
Our DB enforces this field is non-empty. This is good from a debuggability point and an accidental use of a the default value of a string. So we update the code to convert empty revspecs from the search layer into explicit queries for HEAD.
Test Plan: updated unit tests
Fixes https://github.com/sourcegraph/sourcegraph/issues/56784
> search: explicitly use HEAD instead of empty string for exhaustive

- internal/search/exhaustive/store/exhaustive_search_jobs_test.go
We added support for this, the comment was just left behind.
Test Plan: n/a
> search: remove todo about recreating searches

- dev/tool_deps.bzl
Fixes the error `ERROR: /home/noah/Sourcegraph/sourcegraph/dev/tools/BUILD.bazel:21:10: no such package '@universal-ctags-darwin-amd64//file': The repository '@universal-ctags-darwin-amd64' could not be resolved: Repository '@universal-ctags-darwin-amd64' is not defined and referenced by '//dev/tools:universal-ctags` when running e.g. `bazel query`
Run a command such as `bazel query 'kind("go_binary", rdeps(//..., //internal/env/...))' --keep_going` and see the above error disappear after this PR
> bazel: fix @universal-ctags-darwin-x86_64 -> @universal-ctags-darwin-amd64

- enterprise/cmd/worker/internal/search/exhaustive_search.go
- enterprise/cmd/worker/internal/search/exhaustive_search_repo.go
- enterprise/cmd/worker/internal/search/exhaustive_search_repo_revision.go
- internal/search/exhaustive/service/BUILD.bazel
- internal/search/exhaustive/service/search.go
- internal/search/exhaustive/service/search_test.go
- internal/search/exhaustive/service/searcher.go
- internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs.go
This adjusts the search API for exhaustive to enforce explicit passing in of a userID to ensure we always run searches as the correct user. This is to prevent accidently running as another user and thus exposing results from repos a user is not allowed to see.
Test Plan: 
- CI
> search jobs: Enforce passing in a non-zero userID

- cmd/symbols/internal/api/handler_nocgo.go
This file is used to run with CGO_ENABLED=0 for faster recompilation during local dev. For local dev only.
CI
> fix nocgo stub file

- dev/managedservicesplatform/managedservicesplatform.go
```
│ Error: "Telemetry Gateway (dev)" name must be 4 to 30 characters with lowercase and uppercase letters, numbers, hyphen, single-quote, double-quote, space, and exclamation point.
```
> managedservicesplatform: fixup project display name

- cmd/pings/shared/main.go
@rafax - any take now the timeout values here? Reasonable or could/should be lower? I think one minute is pretty standard in general?
CI
> pings: lower server-side request timeouts

- dev/oci_deps.bzl
Update the hashes for the wolfi `server` and `gitserver` base images after #56780 got merged.
Run `sg wolfi image gitserver` locally.
After the image builds, launch a container with that image and check the version of `p4-fusion`:
```
% docker run -it --entrypoint /bin/sh sourcegraph-wolfi/gitserver-base:latest-amd64                  
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/ # p4-fusion-binary | head -3
[ PRINT @ Main:54 ] p4-fusion v1.13.0
[ PRINT @ Main:59 ] Usage:
--branch [Optional, Default is empty]
```
> Update oci_deps.bzl for new p4-fusion 1.13 package

- dev/sg/msp/repo/repo.go
- dev/sg/msp/repo/root.go
- dev/sg/msp/sg_msp.go
Previously, the command expected the full YAML path, which is a bit annoying to write. Now, we just codify the repo structure of https://github.com/sourcegraph/managed-services and allow users to just use the service ID from anywhere in the repository.
```sh
$ sg msp generate telemetry-gateway dev
Terraform assets generated in "services/telemetry-gateway/terraform/dev"!
$ cd services/telemetry-gateway/terraform/dev/stacks/project
$ sg msp generate telemetry-gateway dev
💡 Using repo root /Users/robert@sourcegraph.com/Projects/sourcegraph/managed-services as working directory
Terraform assets generated in "services/telemetry-gateway/terraform/dev"!
```
> sg/msp: improve DX by enforcing repo structure

- client/jetbrains/build.gradle.kts
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/SelectOptionPopupUI.kt
Unlocks indexing of the plugin with scip-java (see [here for example](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b71b22ef9584dc8441f9195f2decd52a53a9e2fb/-/blob/client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentCodebase.kt?L10:7&popover=pinned#tab=references)). 
`./gradlew compileKotlin` and (hopefully) covered by CI too
> JetBrains: bump kotlin to 1.9.10

- client/jetbrains/src/main/java/com/sourcegraph/cody/context/EmbeddingStatusView.kt
closes https://github.com/sourcegraph/sourcegraph/issues/56879 
Previously:
Now:
- Only icon should be displayed for embedding status
> JetBrains: display icon only instead of a button for embedding status

- client/jetbrains/flake.nix
Couldve done `LD_LIBRARY_PATH = libraries;` but didnt want it to mess with more stuff than needed (e.g. opening intellij from cli)
N/A nix stuff
> nix: wrap gradle with x11 libs for intellij plugin

- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/CodySettingChangeActionNotifier.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/CodyConfigurable.kt
- client/vscode/README.md
- client/web/src/cody/chat/CodyChatPage.tsx
- client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
- client/web/src/components/externalServices/AddExternalServicesPage.tsx
- client/web/src/nav/GlobalNavbar.tsx
- client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
- client/web/src/repo/components/TryCodyWidget/TryCodyWidget.tsx
- client/web/src/repo/tree/TreePage.test.tsx
- client/web/src/storm/pages/SearchPage/TryCodyCtaSection.tsx
- client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx
- doc/cody/explanations/cody_clients.md
- doc/cody/faq.md
- doc/cody/overview/index.md
- doc/cody/overview/install-vscode.md
- windows/installer/cody/package.en-us.wxl
"Cody AI" was one way we referred to Cody in its first couple months to make it clear that it's an
AI product. That is no longer needed, and it sounds stilted/hype-y.
The one place where we do need to say "Cody AI" is when referring to Cody's name on the VS Code
extension marketplace. There, the name `Cody` by itself is taken, so we need `Cody AI` (or something
else that is not just `Cody`, and we're sticking with `Cody AI` for now).
CI
[Preview Link](https://docs.sourcegraph.com/@sqs/cody-ai-naming)
> call it "Cody" not "Cody AI"

- client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx
Previously, the "Description" field got auto-populated with the name of the JetBrains IDE but the name wasn't correctly persisted after the user created the token. In the UI, it would say "No description".
This PR fixes the problem by passing the default description value as the initial value to the appropriate `setState` React hook.
Thank you @taylorsperry for reporting this issue!
- Used web-standalone with dotcom mode
- Created access token with default value "IDEA" from the URL parameter
- Validated that the access token had the description "IDEA" after creating the token
> JetBrains: fix bug for access token description

- dev/release/release-config.jsonc
Closes https://github.com/sourcegraph/sourcegraph/issues/56794
🤞
> release: close 5.1.9 and activate 5.2.0

- doc/sidebar.md
- doc/sla/index.md
This PR adds our Service Level Agreements page to docs. 
Docs added
[Preview Link](https://docs.sourcegraph.com/@sg-sla)
> Add SLA page to docs

- dev/release/templates/patch_release_issue_template.md
Docker image tags don't have `v` prefix.
🤞
> release: fixup patch release issue template

- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.tsx
- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/__snapshots__/SiteAdminGenerateProductLicenseForSubscriptionForm.test.tsx.snap
Per discussion here: https://sourcegraph.slack.com/archives/C012NU3PXA9/p1692739028032289
>Another request: the date picker defaults to 1 year out. This is _really_ easy to miss and I know multiple people have sent out accidental 1 year licenses that were supposed to be 30 day licenses (which is very bad!). Is there a chance someone can change the default picker?
Honestly, I have not tested this, I edited it in the GitHub editor... This is for internal/admin usage only, and it's a low risk change. If it passes CI, I assume it's okay? Defer to eng.
> Move new license default expiration date to today

- doc/index.md
There was a link to the /app page for downloading code search. Since the app doesn't run code search anymore, I've removed that CTA, and bumped up the CTA to deploy a Sourcegraph instance.
Docs only.
[Preview Link](https://docs.sourcegraph.com/@docs-cs-patch)
> Remove docs link for downloading code search app

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/AutoCompleteLanguageTableWrapper.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/AutocompleteLanguageTable.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/LanguageCheckboxColumn.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/LanguageEntryColumn.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/CodyConfigurable.kt
Fixes #56466
Some fixes for the languages table in Cody settings
- it should now have an increased height, so that it's easier to scroll
- the checkbox column gets disabled (can't enable/disable languages) when autocomplete is disabled
- I added a custom cell renderer for the language display name column, so that it now gets greyed out when autocomplete is disabled
https://github.com/sourcegraph/sourcegraph/assets/18601388/d94f08a9-7091-4419-a0bb-cc2ec312966e
- the table should work like in the screen recording
- enabling/disabling languages for autocomplete should work as expected
> JetBrains: Cody: Improve the languages table in Cody settings

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAuthenticationManager.kt
Fixes #56894 
Couldn't replicate the error, but I added some extra checks in place just in case.
- authentication flow should work as normal
- the error described in #56894 shouldn't be replicable
> JetBrains: Cody: Check if the project wasn't disposed when getting the active account

- dev/sg/msp/repo/BUILD.bazel
I'm not sure how this got into main but we're missing a bazel update on there.
CI passes fine
> bazel configure 

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/AutocompleteActionHandler.kt
Closes #https://github.com/sourcegraph/sourcegraph/issues/56895
But the root cause of the issue for the user was that the agent didn't start, that's why even when the editor is not supported we moved to the else branch and the exception appears because we will try to display inlays on not supported editor 
- I have no idea how to reproduce it...
> JetBrains: Fix: don't try to display inlays on not supported editor instances

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/SaveAccessTokenHttpService.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/SignInWithSourcegraphAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/AccountsHostProjectHolder.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/AddCodyAccountWithTokenAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyAccountListModel.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyPersistentAccountsHost.kt
- client/jetbrains/src/main/resources/META-INF/plugin.xml
Previously we displayed a dialog to configure server and access token manually to add sourcegraph.com account, now we start the web flow to authenticate user 
https://github.com/sourcegraph/sourcegraph/assets/7345368/7a15dd5e-8fe2-456c-9292-8e9253baca31
- Log in to Sourcegraph from settings page should start web authentication flow and should add account after successful authentication
> JetBrains: Sign in to sourcegraph.com with a webflow from action on settings page

- dev/ci/bazel-prechecks.sh
Fixes https://github.com/sourcegraph/devx-support/issues/251
This issue was happening because it's possible to end up with a clean diff, when `bazel configure` creates _new_ `BUILD.bazel` files. 
So instead, we add them with `--intent-to-add` which make them show up in `git diff`. 
Tested over a QA branch: `/reblochon/file.go` and `/camembert/file.go` were added without a buildfile, and this is the result:
> ci: fix bazel prechecks not detecting untracked changes

- .gitignore
Noticed this when I was searching for `bazel-prechecks.sh` in my editor and it wasn't showing up. 
CI
> chore: narrow gitignore glob for 'bazel-'

- .github/workflows/sg-binary-release.yml
Fixes https://github.com/sourcegraph/devx-support/issues/249
We didn't update the Go version in the GH Workflow that releases `sg`. This PR fixes it.
> ci: update Go version for sg binary releases

- dev/nix/nodejs.nix
- flake.lock
- flake.nix
We want to get newer stuff in the devshell, but keep a stabler pin for the static binaries (until darwin stdenv stabilizes, most notably the big brain work over at https://github.com/NixOS/nixpkgs/pull/256590)
N/A nix stuff :clueless:
> nix: separate nixpkgs-unstable pin from nixpkgs pin for static binaries

- dev/sg/msp/command.go
- dev/sg/msp/sg_msp.go
- doc/dev/background-information/sg/reference.md
This configures the stub `sg msp` command such that we now get a docstring with installation instructions in the `sg` reference.
As the tooling is still experimental, I'm opting to keep this in its own build variant for now, as it still represents a bit of a binary size increase to `sg`. Backlog issue: https://github.com/sourcegraph/sourcegraph/issues/56845
Rendered docs
[Preview Link](https://docs.sourcegraph.com/@sg-msp-install-instructions)
> sg/msp: set up command so that docs are rendered

- internal/pubsub/topic.go
Telemetry Gateway, which uses this in local dev, quickly becomes very noisy. I'll add a note about this in https://github.com/sourcegraph/sourcegraph/pull/56868 that if you want to see it, you have to configure a custom log level
telemetry-gateway no longer emits messages by default
> pubsub: downgrade logging client to debug

- cmd/pings/shared/main.go
GCP monitoring dashboard can't create graph and alert for a metric that is not visible.
```
$ sg run pings
$ curl -sS http://localhost:7011/metrics | grep "error_count"
pings_error_count_total{otel_scope_name="pings/shared",otel_scope_version=""} 0
```
> pings: always expose error count metric

- internal/telemetry/besteffort.go
- internal/telemetry/teestore/option.go
- internal/telemetry/teestore/teestore.go
- internal/telemetry/teestore/teestore_test.go
- internal/telemetry/telemetry.go
- internal/telemetry/telemetry_test.go
- internal/telemetry/telemetrygateway.go
- internal/telemetry/telemetrygateway_test.go
- Make `parameters` a pointer, so that you can just provide `nil` - a bit easier to manage at callsites
- Remove the `V2:` prefix on translated events, which were a bit confusing to look at - the V2 scheme does not matter to admins.
- Improved docstrings here and there on the new telemetry stuff
See https://github.com/sourcegraph/sourcegraph/pull/56924
> telemetry: make parameters optional, improve docstrings

- internal/database/event_logs.go
- internal/usagestats/event_handlers.go
Part of https://github.com/sourcegraph/sourcegraph/issues/56813 - see https://github.com/sourcegraph/sourcegraph/pull/56868 for docs!
n/a
> database, usagestats: mark deprecation of direct event_logs recording

- cmd/frontend/internal/app/BUILD.bazel
- cmd/frontend/internal/app/app.go
- cmd/frontend/internal/app/sign_out.go
Replaces the signout event logging with our new telemetry recorder, so we can start exporting some events in testing environments.
I intentionally left out `Attempted` events because in all cases we record either a success or a failure anyway.
Stacked on https://github.com/sourcegraph/sourcegraph/pull/56922
Part of https://github.com/sourcegraph/sourcegraph/issues/56815
See https://github.com/sourcegraph/sourcegraph/pull/56924
> signout: instrument with v2 events

- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/render/AutocompleteRenderUtils.java
- client/jetbrains/src/main/java/com/sourcegraph/cody/autocomplete/render/CodyAutocompleteElementRenderer.java
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/CodyConfigurable.kt
Some small fixes for autocomplete color:
- it's been possible to cause an NPE by enabling a custom color in the settings, but then not picking any particular color (which produced a null); there's now a fallback for this case
- we now explicitly set (the same) color for light & dark theme
- we could have a separate setting for either type of theme, or just only set for the current one in the future
- for now, we explicitly set the custom value for all themes
What should still be done later:
- #56996
https://github.com/sourcegraph/sourcegraph/assets/18601388/3da99531-4037-411d-bff6-73217046b22b
- when enabling custom autocomplete coloring, but not explicitly picking any color (effectively leaving it a null), no NullPointerExceptions or other errors should happen for now
> JetBrains: Cody: Improve autocomplete custom color setting

- cmd/frontend/graphqlbackend/user_usage_stats.go
- cmd/frontend/hubspot/contacts.go
- cmd/frontend/hubspot/hubspotutil/hubspotutil.go
closes part of https://github.com/sourcegraph/cody/issues/954
- Pass a new event `VSCodyInstalled` to HubSpot
- Pass a new bool property `VsCodyInstallEmailsEnabled` based on feature flag for AB testing. 
- enable the feature flag
- Install VS Code sign in should log event to hub spot with property true.
> Push VS Cody install events to HubSpot

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/CodyConfigurable.kt
https://github.com/sourcegraph/sourcegraph/assets/18601388/a62743ae-affb-405a-824b-614a050877aa
- debug settings work as expected
- verbose debug can only be enabled if regular debug is also enabled
> JetBrains: Cody: Only enable the verbose debug setting if regular debug is also enabled

- WORKSPACE
Reverts sourcegraph/sourcegraph#57002
CI
> Revert "bzl: bump oci_rules to 1.3.4"

- internal/codeintel/autoindexing/internal/inference/lua/python.lua
- internal/codeintel/autoindexing/internal/inference/testdata/python_multiple_config_files_at_root.yaml
- internal/codeintel/autoindexing/internal/inference/testdata/python_multiple_roots.yaml
- internal/codeintel/autoindexing/internal/inference/testdata/python_package_1.yaml
- internal/codeintel/autoindexing/internal/inference/testdata/python_package_2.yaml
- internal/codeintel/autoindexing/internal/inference/testdata/python_package_3.yaml
- internal/codeintel/autoindexing/internal/inference/testdata/python_package_with_pyproject.yaml
- internal/codeintel/autoindexing/internal/inference/testdata/python_pyproject.yaml
- internal/codeintel/autoindexing/internal/inference/testdata/python_requirements.txt.yaml
- internal/codeintel/autoindexing/internal/inference/testdata/python_setup.py.yaml
The default heap size for Node is 1400MB on 64-bit, which is
generally much less than the total memory available to an
auto-indexing VM. This can cause unnecessary OOMs, such
as when indexing django.
We already have the same local step in the scip-typescript
auto-indexing script, which also uses Node.
Updated snapshots
> codeintel: Increase Node heap size for scip-python

- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.kt
- client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/CodyApplicationSettings.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/SettingsModel.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/CodyConfigurable.kt
Fixes #56984
- the `Accept non-trusted certificates` setting should be respected
> JetBrains: Cody: Add a setting for accepting non-trusted certificates automatically

- enterprise/dev/ci/internal/ci/changed/diff.go
@burmudar the bitwise trickery for `diff.Only` has an edgecase, which is when no changes at all are detected. Because `d` is at `0`, the comparison will always return 0 regardless, essentially saying that "yes that diff is the only one present" whereas there are no diffs at all. 
> ci: fix diff.Only predicate wrongly returning true

- cmd/pings/shared/main.go
Since we are comparing a secret against user supplied input, we need to use constant time comparisons to make sure we aren't susceptible to timing attacks.
CI
> sec: use constant time comparison

- doc/cody/faq.md
Fix a typo error in Cody's FAQ docs.
Docs added
[Preview Link](https://docs.sourcegraph.com/@typo-fix)
> Typo fix in Cody FAQ docs

- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/protocol/Event.java
Telemetry events should include the client identifier.  
Added temporary logging in the agent to ensure client value is present
```
Logging event: {
event: 'CodyJetBrainsPlugin:completion:suggested', 
source: 'IDEEXTENSION',
referrer: 'JETBRAINS',
client: 'JETBRAINS_CODY_EXTENSION',
...
}
```
> JetBrains: add the client value to telemetry events

- WORKSPACE
- testing/tools/integration_runner.sh
I fixed a bug in the pipeline generation in between and this time the tests were run properly (and they're green). 
CI
> bzl: bump oci_rules to 1.3.4 

- client/jetbrains/flake.nix
- dev/nix/shell-hook.sh
Whoopsie in the shellhook that never came up coz we're not really using bazel yet locally :clueless:
N/A nix
> nix: fix shellhook and add extra libs for jetbrains plugin

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentManager.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/CodySettingChangeContext.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/notification/CodySettingChangeListener.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/config/ui/CodyConfigurable.kt
A followup to https://github.com/sourcegraph/sourcegraph/pull/56999#pullrequestreview-1642248534
- Cody agent should restart after changing the `Accept non-trusted certificates automatically` setting
- The setting should thus be respected without restarting one's IDE
> JetBrains: Cody: Restart agent when certificate setting changes

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
Fixes #57022 
https://github.com/sourcegraph/sourcegraph/assets/18601388/d33414e8-1b18-423d-8a2a-627f2801cf69
- commands panel should be loaded after logging in an account on a clean setup
> JetBrains: Cody: Refresh commands panel on first login

- client/jetbrains/src/main/java/com/sourcegraph/telemetry/GraphQlLogger.java
@kelsey-brown wrote: "I’m still not seeing any JetBrains values for extensionDetails.ide on the CodyInstalled event"
I've found no problem with the logging format, but the condition deciding whether we do the logging in the first place seemed wrong.
The condition was added on 2023-08-14 by @olafurpg.
Not sure if it's possible that we were not only missing the `extensionDetails` in the event details, but the whole logging was not triggered since mid-August?
Ran it in debug mode and saw that the condition was successfully triggered.
> JetBrains: Fix CodyInstalled event logging

- internal/telemetry/teestore/teestore.go
- internal/telemetry/teestore/teestore_test.go
Inject a clear marker to argument if a v2 event tee'd into `event_logs` can be exported, until we have a more robust system for revealing `telemetry_events_export_queue` to site admins.
This is not robust, as it does not work for usages of `teestore.WithoutV1` - https://github.com/sourcegraph/sourcegraph/issues/57027 tracks implementing a way to get a "real" list of exported events.
Golden tests
> telemetry/teestore: add marker for if event can be exported

- cmd/frontend/internal/app/app.go
- internal/auth/userpasswd/handlers.go
- internal/auth/userpasswd/handlers_test.go
- internal/telemetry/events.go
- internal/telemetry/telemetry.go
Uses the updated approach I've been taking so far for now, which is to retain the legacy events, using `teestore.WithoutV1` to avoid changing the shape of the legacy events.
CI
> userpasswd: add v2 events for signup

- doc/admin/observability/alerts.md
- doc/admin/observability/dashboards.md
- monitoring/definitions/frontend.go
This changes the threshold to critical-alert on 10% failure rate, and warn on any non-zero failure rate (as all email delivery failures impact user experience).
Test query (dotcom): https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22Prometheus%22,%7B%22exemplar%22:true,%22expr%22:%22sum(increase(src_email_send%7Bsuccess%3D%5C%22false%5C%22%7D%5B30m%5D))%20%2F%20sum(increase(src_email_send%5B30m%5D))%20*%20100%22,%22requestId%22:%22Q-c1441862-6745-442a-9745-ba1bf9d80a4e-0A%22%7D%5D&right=%5B%22now-2d%22,%22now%22,%22Prometheus%22,%7B%22exemplar%22:true,%22expr%22:%22sum(increase(src_email_send%7Bsuccess%3D%5C%22false%5C%22%7D%5B30m%5D))%22,%22requestId%22:%22Q-4b1e1c07-aa04-4f9b-ab5d-fef8100a5b24-0Q-c8739f02-df38-476b-8cb0-fc9ddc0fd71c-1A%22%7D,%7B%22e …
> monitoring: make email_delivery_failures on percentage, not count

- flake.lock
This seems to be missing from the recent nix change. My nix develop keeps autoupdating it.
Test Plan: nix develop doesn't change the working copy
> nix: update flake.lock

- enterprise/cmd/worker/internal/search/exhaustive_search.go
- internal/search/exhaustive/service/search.go
- internal/search/exhaustive/service/searcher.go
- internal/search/exhaustive/service/searcher_test.go
This can be a very large list and the underlying repos resolver relies on an iterator to avoid the large list appearing in memory. So this commit adjusts the interface to also use an iterator reducing memory usage the first step of exhaustive search.
Test Plan: go test should be sufficient
> search: RepositoryRevSpecs returns an iterator

- migrations/frontend/1695747321_remove_drift/down.sql
- migrations/frontend/1695747321_remove_drift/metadata.yaml
- migrations/frontend/1695747321_remove_drift/up.sql
See [slack context](https://sourcegraph.slack.com/archives/C05MS02FW81/p1692216344341539?thread_ts=1692126487.083519&cid=C05MS02FW81) and the [release blocking thread](https://sourcegraph.slack.com/archives/C032Z79NZQC/p1695747244024459).
For permanence, #55893 was merged, then reverted, and merged into the 5.1 branch and reverted. For some instances the original index ran, but is no longer in the "squashed" form of the schema. This clears out any indexes that have hit this path so there's no drift.
> chore: Remove indexes that existed for a short time

- .github/test.CODEOWNERS
- .github/workflows/label-notify.yml
- doc/CODENOTIFY
- docker-images/postgres-12-alpine/CODENOTIFY
- monitoring/CODENOTIFY
The GitHub team has been deleted. If you think other teams want to get notified, feel free to suggest edits!
CI
[Preview Link](https://docs.sourcegraph.com/@jc/codenotify-delivery)
> chore: clean up CODENOTIFY for @sourcegraph/delivery

- internal/actor/actor.go
- internal/actor/http.go
- internal/actor/http_test.go
Cookie anonymous UID continues to take precedence, but this is helpful for clients that don't use cookies to track anonymous UID (i.e. VSCode), and especially relevant in the context of our new telemetry mutations, which now use real actors to determine the user, instead of asking clients to tell us who the user is.
Unit test
> actor: propagate anonymous UID from 'X-Sourcegraph-Actor-Anonymous-UID'

- cmd/frontend/globals/globals.go
- cmd/frontend/internal/auth/saml/BUILD.bazel
- cmd/frontend/internal/auth/saml/config.go
- cmd/frontend/internal/auth/saml/middleware_test.go
- cmd/frontend/internal/auth/saml/provider.go
- cmd/frontend/internal/cli/http.go
- cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
- cmd/frontend/internal/dotcom/productsubscription/license_anomaly.go
- cmd/frontend/internal/dotcom/productsubscription/license_anomaly_test.go
- cmd/frontend/internal/dotcom/productsubscription/license_check_handler.go
- cmd/frontend/internal/repos/webhooks/resolvers/BUILD.bazel
- cmd/frontend/internal/repos/webhooks/resolvers/resolver.go
- cmd/frontend/internal/repos/webhooks/resolvers/resolver_test.go
- cmd/frontend/internal/search/resolvers/BUILD.bazel
- cmd/frontend/internal/search/resolvers/search_job.go
- internal/batches/reconciler/BUILD.bazel
- internal/batches/reconciler/executor_test.go
- internal/batches/types/BUILD.bazel
- internal/batches/types/batch_change.go
- internal/batches/types/batch_change_test.go
- internal/codemonitors/background/BUILD.bazel
- internal/codemonitors/background/email.go
- internal/codemonitors/background/email_test.go
- internal/codemonitors/background/workers.go
- internal/codemonitors/background/workers_test.go
In light of recent failures, this Pull Request reverts the changes made to the external URL in a [previous PR](https://github.com/sourcegraph/sourcegraph/pull/56916), ensuring stability and functionality. This PR is a proactive measure to unblock the system by reverting to a stable state, with a follow-up PR planned to address the reference to the global external URL variable. Additionally, an unnecessary `sync.Once` has been removed, a likely culprit in needing to restart the server when externalURL is updated.
1. **Reversion of External URL Update**:
- The external URL has been reverted to its prior state by undoing changes from the previous PR. This change stabilizes the system and unblocks current failures.
2. **Removal of Unnecessary sync.Once**:
- Removed an extraneous `sync.Once`, …
> [config]: Reverting External URL Update and Removal of sync.Once

- client/jetbrains/src/main/java/com/sourcegraph/cody/CodyToolWindowContent.java
Removed old onboarding as we don't support this in the new onboarding flow
- Green CI
> JetBrains: remove old onboarding about cody app

- schema/site.schema.json
This fixes #56980
- `sg start`, open site-config, add `repoPurgeWorker`, see defaults
> site-config: fix invalid default values for repo purge worker

- cmd/frontend/internal/search/resolvers/resolver.go
- cmd/frontend/internal/search/resolvers/search_job.go
- enterprise/cmd/worker/internal/search/exhaustive_search_test.go
- internal/search/exhaustive/service/service.go
- internal/search/exhaustive/store/exhaustive_search_jobs.go
- internal/search/exhaustive/store/exhaustive_search_jobs_test.go
- internal/search/exhaustive/types/exhaustive_search_job.go
Closes #56937
Closes #56935
This PR moves the logic for computing the aggregate state from the resolver to the store.
Why?
To filter and sort by the aggregate state and make use of the paging helpers, we have to return the aggregate state from db instead of computing it in the resolver. 
Note:
There is a bit of awkwardness because only `ListSearchJobs` computes the aggregate state, but not `GetSearchJob`. I don't want to set `AggState` in `GetSearchJob` because it is fairly expensive to calculate, and we call `GetSearchJob` a lot as part of the security checks, so I wanted to keep it as lean as possible. 
In the future we should have a dedicated call to the db for security checks and use `GetSearchJob` only when we create a search job. Then we can calculate the aggregate state on …
> search jobs: compute aggregate state in db

- cmd/frontend/internal/dotcom/productsubscription/licenses_graphql.go
- internal/license/generate-license.go
- internal/license/license.go
- internal/licensing/licensing.go
This change introduces a license version 3, which now records `CreatedAt` marking the creation of the license. This will apply to all licenses created when this change rolls out.
Recording this allows us to gate capabilities based on the time a license was created, namely for [telemetry export configuration](https://sourcegraph.slack.com/archives/C05BGNBEPKL/p1695750396124609?thread_ts=1695683252.874339&cid=C05BGNBEPKL).
I'm marking this as needing backport so that we can extract and use this new attribute.
CI
> license: record CreatedAt in license info

- CHANGELOG.md
This PR adds a changelog entry for all the features added by the git debuggability job fair project.
Changelog update.
> source: add changelog entry for git debuggability

- internal/telemetry/teestore/BUILD.bazel
- internal/telemetry/teestore/teestore.go
- internal/telemetry/teestore/teestore_test.go
The `event_logs` table requires that either the user or an anonymous user ID is provided, so some events can fail to insert when translated by `telemetry/teestore`. This change makes sure we always have either the user ID or anonymous ID.
I added an integration test to make sure translated events will always insert successfully without being caught by constraints. Existing unit tests + autogold show the new generated anonymous ID.
> telemetry/teestore: generate anonymous ID if user and anonymous ID are empty

- lib/go.mod
- lib/go.sum
Version 1.11 of cockroachdb/errors added support for the stdlib multierror pattern, which is necessary for cross compatibility with 3rd party libraries that use multierrors.
CI
> Chore: bump cockroachdb/errors

- cmd/searcher/internal/search/BUILD.bazel
- cmd/searcher/internal/search/search_grpc.go
- cmd/searcher/internal/search/search_grpc_test.go
Errors like the following are popping up in searcher.Search error logs (https://cloudlogging.app.goo.gl/TMkmbxYSQth6qN2E8):
- "rpc error: code = Unknown desc = Write: write |1: broken pipe"
- "rpc error: code = Unknown desc = failed to wait for executing comby command: signal: killed"
- "rpc error: code = Unknown desc = WriteHeader: write |1: broken pipe"
I believe a lot of these can be given proper grpc error codes (not just codes.Unknown) by special casing some special errors:
1. If an error occurred and the context also expired, just return a context error (codes.DeadlineExceeded or codes.Cancelled) (there is an implicit assumption here that an expired context is the cause of the error)
1. If an error occurred and the error contains "signal: killed", return codes.Aborted
See …
> grpc: searcher: convert well-known errors to proper grpc status codes

- internal/embeddings/db/conf.go
This fixes a case that can trigger a nil panic when qdrant is enabled in config, but no endpoint is configured. This should be a very rare situation.
Manually tested that the situation that was panicking locally no longer panics.
> Bug: fix nil panic

- enterprise/cmd/worker/internal/auth/sourcegraph_operator_cleaner.go
- enterprise/cmd/worker/internal/auth/sourcegraph_operator_cleaner_test.go
- internal/database/external_accounts.go
External account deletion soft-deletes accounts. This means that on subsequent SOAP logins, SOAP users with more than 1 external account are more or less instantly demoted, because the cleanup job detects their expired - but deleted - SOAP external accounts.
This change updates the cleaner to ignore deleted external accounts, and also to hard-delete SOAP external accounts using a new option so that we don't have endless cruft building up.
No backport needed as https://github.com/sourcegraph/sourcegraph/pull/56866, which introduced this bug, did not make it into the 5.2 branch cut.
Updated integration test
> soap-cleaner: do not pick up soft-deleted external accounts

- wolfi-packages/p4-fusion.yaml
Occasional core dumps with 1.13, most of them SIGSEGV
core dumps do not happen all of the time, but this command run on `gitserver` reliably reproduces them:
```shell
P4USER=<perforce user>
P4PASSWD=<user ticket>
P4PORT=<perforce host>
DEPOT=<depot name>
export P4USER P4PASSWD P4PORT
for x in 1 2 3 4 5
do
tmpdir=/data/repos/.tmp/test_p4-fusion-${RANDOM}
rm -rf "${tmpdir}"
mkdir -p "${tmpdir}"
echo "attempt ${x}"
p4-fusion-binary \
--path ${DEPOT}... \
--client "" \
--user ${P4USER} \
--src "${tmpdir}/.git" \
--networkThreads 16 \
--printBatch 10 \
--port ${P4PORT} \
--lookAhead 16 \
--maxChanges 32 \
--retries 100 \
--refresh 100000 \
--includeBinaries false \
--fsyncEnable true \
--noColor true 2>&1 | { grep "core dumped" || true; }
rc=$?
echo "return code: ${rc}"
rm -rf "${tmpdir}"
done …
```
> revert p4-fusion to 1.12

- internal/extsvc/github/globallock.go
- internal/ratelimit/globallimitergettokens.lua
- internal/ratelimit/globallimitersettokenbucket.lua
Changes as described in #55290 and #56548
- Check if a lock failure error is an `ErrTaken` error and if so, it logs a warning instead of an error.
- Add key expirations to redis rate limiter keys. If keys aren't refreshed in 1 day, they are deleted.
- The rate limiter retry func now randomises between 200 and 300 ms, instead of 50 and 250 ms
- This brings the average wait time up to 8 seconds, which is the same amount of time it takes for a lock to expire. So if a lock failed to unlock, there is a greater chance that a new lock will be successfully grabbed.
Some local tests for now
> Distributed Rate Limiter updates

- enterprise/cmd/worker/internal/search/BUILD.bazel
- enterprise/cmd/worker/internal/search/exhaustive_search_test.go
- internal/search/exhaustive/service/service.go
Previously we would always write a header line before actually checking if we can view a job. This automatically lead to status 200 and us ignoring the later error. This adjusts the service call to return before any writes.
Test Plan: a test was added which ensures we don't write anything in case of auth failure.
Fixes https://github.com/sourcegraph/sourcegraph/issues/57087
> search: return status forbidden on download exhaustive logs

- cmd/frontend/internal/search/httpapi/BUILD.bazel
- cmd/frontend/internal/search/httpapi/export.go
- cmd/frontend/internal/search/httpapi/export_test.go
- internal/search/exhaustive/service/search.go
- internal/search/exhaustive/service/search_test.go
- internal/search/exhaustive/service/service.go
- internal/search/exhaustive/service/service_test.go
Closes #57032 
We already don't write CSV headers if we don't find matches, so all we have to do is skip the upload.
Test plan:
- new and updated unit test
- ran a "needle in the haystack" query locally and confirmed that now we upload 1 CSV (for the needle) instead of 1 per revision.
> search jobs: don't upload emtpy blobs

- wolfi-images/gitserver.yaml
- wolfi-images/server.yaml
Previously we didn't set the epoch, this makes sure we are on latest 1.12 for p4-fusion.
Tested the version is correct and p4-fusion-binary and wrapper script are available.
> Set epoch for p4-fusion 1.12

- client/branded/src/search-ui/results/progress/exhaustive-search/exhaustive-search-validation.test.ts
- client/branded/src/search-ui/results/progress/exhaustive-search/exhaustive-search-validation.ts
Closes #57131 
We only allow flat queries in the backend, which implies no AND or OR.
Test plan:
- updated test
- checked locally that it is not possible to create a search job from a query with "AND" operator.
> search-jobs: add AND to query validation

- dev/oci_deps.bzl
This will put the right image hashes in place so we can build `gitserver` and `server` with the version 1.12.0 of `p4-fusion`. 
Follow up from:
- https://github.com/sourcegraph/sourcegraph/pull/57113
- https://github.com/sourcegraph/sourcegraph/pull/57129
Pulled and tested the p4-fusion version is 1.12.0 in the docker images.
> wolfi: update server / gitserver base images for p4-fusion revert

- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/protocol/ClientInfo.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/config/ConfigUtil.kt
does what it says on the tin
Tested that agent accepts the uri that we send and it does: `2023-09-28 13:22:47,242 [   4056]   WARN - #c.s.c.a.CodyAgent - Cody Agent: handshake with client 'JetBrains' (version '3.4.0-alpha.1') at workspace root path 'file:///home/noah/Sourcegraph/lsif-kotlin'`
> JetBrains: migrate from deprecated workspaceRootPath to workspaceRootUri

- dev/oci_deps.bzl
This change should be backported as the current version of p4-fusion, 1.13, segfaults under some conditions. See https://github.com/sourcegraph/sourcegraph/pull/57113 for more details.
This will put the right image hashes in place so we can build `gitserver` and `server` with the version 1.12.0 of `p4-fusion`. 
Follow up from:
- https://github.com/sourcegraph/sourcegraph/pull/57113
- https://github.com/sourcegraph/sourcegraph/pull/57129
Pulled and tested the p4-fusion version is 1.12.0 in the docker images.
> Backport 57133 to 5.2: wolfi: update server / gitserver base images for p4-fusion revert

- doc/dev/how-to/wolfi/add_update_packages.md
Add instructions for downgrading packages in our images.
Related: https://github.com/sourcegraph/security/issues/965
- Docs - will manually check and verify
[Preview Link](https://docs.sourcegraph.com/@will/docs-wolfi-package-downgrade)
> Docs: Add wolfi package downgrade instructions

- .editorconfig
My intellij wont default to 2 indent without setting this :shrug: 
N/A setting style in .editorconfig
> JetBrains: set .editorconfig indent size for java + kotlin

- wolfi-images/gitserver.yaml
- wolfi-images/server.yaml
- wolfi-packages/jaeger.yaml
This change should be backported as the current version of p4-fusion, 1.13, segfaults under some conditions. See https://github.com/sourcegraph/sourcegraph/pull/57113 for more details.
This PR pins the older package for p4-fusion, to make sure we don't hit any SEGFAULTs.
Follow up of PR: https://github.com/sourcegraph/sourcegraph/pull/57113. This PR will be followed up with another PR, to update the image hashes for server and gitserver.
- Manually inspecting packages
> Backport 57134 to 5.2: Set epoch for p4-fusion 1.12

- internal/completions/client/azureopenai/openai.go
When using the completions endpoint instead of the chat/completions the streaming data needs to be accumulated from the Text field as there is no delta sent.
`sg start`  with completions configured for azure-openai
use VS Code extension to get autocomplete 
verify autocompletes are returned.
> Azure OpenAI: Fix autocomplete streaming 

- wolfi-packages/qdrant.yaml
This updates the wolfi package version to 1.5.1, which includes some bugfixes and stability improvements, as well as proper healthz endpoints for k8s.
N/A. Will test new images before updating.
> Qdrant: bump version

- cmd/frontend/graphqlbackend/embeddings.go
- cmd/frontend/graphqlbackend/embeddings.graphql
- cmd/frontend/internal/embeddings/resolvers/resolvers.go
- internal/embeddings/background/repo/mocks_temp.go
- internal/embeddings/background/repo/store.go
- internal/embeddings/background/repo/store_test.go
When qdrant is enabled, an embeddings job will upload the embeddings to both blobstore and qdrant. This means that, after qdrant is enabled, we will naturally migrate the data if a policy is configured for a repo. However, there may be repos that were only embedded with a one-off job. This PR adds a GraphQL endpoint that just reschedules all repos that have a completed embeddings job, which will cause them to be uploaded to qdrant.
Added a test for the DB layer. Manual end-to-end test.
> Qdrant: add endpoint to move all embeddings to qdrant

- internal/types/types.go
- internal/usagestats/code_monitoring.go
- internal/usagestats/code_monitoring_test.go
- internal/usagestats/code_monitoring_usage_stats.sql
Before, `monitors_enabled_unique_users` and `monitors_enabled_last_run_errored` returned null values every time. This commit makes it so that they populate with the correct data. 
1. Adjust unit tests to account for newly populated monitor fields. 
2. Shipped with all tests passing.
> populate monitors_enabled_unique_users and last_run_errored

- cmd/frontend/graphqlbackend/embeddings.graphql
I accidentally put `migrateToQdrant` in the `Query` block rather than the `Mutation` block. Whoops.
N/A
> Qdrant: make migrateToQdrant a mutation

- enterprise/cmd/worker/internal/search/exhaustive_search.go
- enterprise/cmd/worker/internal/search/exhaustive_search_repo.go
- enterprise/cmd/worker/internal/search/exhaustive_search_repo_revision.go
- enterprise/cmd/worker/internal/search/job.go
- internal/search/exhaustive/store/exhaustive_search_jobs.go
- internal/search/exhaustive/store/exhaustive_search_repo_jobs.go
- internal/search/exhaustive/store/exhaustive_search_repo_revision_jobs.go
- internal/workerutil/dbworker/store/store.go
This adds a resetter for each of our 3 search job workers and enables resets and retries.
Test plan:
manual testing
- I set an old, completed job to "processing" and verified that the resetter reset it to "failed".
- I set a recent, completed job to "processing" and verified that the resetter reset it to "queued".
> search jobs: add resetter workers

- cmd/frontend/internal/search/httpapi/BUILD.bazel
- cmd/frontend/internal/search/httpapi/export.go
- cmd/frontend/internal/search/httpapi/export_test.go
- cmd/frontend/internal/search/init.go
- enterprise/cmd/worker/internal/search/exhaustive_search_test.go
- internal/search/exhaustive/service/service.go
This commit makes it such that both CSV handlers for exhaustive search validate the job ID before setting any CSV headers or writing data. This makes it possible to distingiush between errors that happen before we write out CSVs and during.
Another benefit is we now call WriteHeader, which avoids long delays between clicking the download button and the download starting. Before until go decides to flush there may be several seconds before the headers are sent.
To achieve this change we adjust the service interface to instead return an io.WriterTo. A more generic API would return an io.Reader (involving the use of an io.Pipe). However, we can specialize to io.WriterTo since that is exactly the interface we want to use (and is an underlying optimization used by io.Copy)
Additionally we add …
> search: exhaustive handlers validate input before writing CSV

- internal/search/job/jobutil/exhaustive_job.go
- internal/search/job/jobutil/exhaustive_job_test.go
This improves our test coverage for `NewExhaustive`. The goal is to make sure we won't process unsupported or extremely expensive queries.
CI
> search jobs: add more tests for query validation

- internal/search/exhaustive/service/BUILD.bazel
- internal/search/exhaustive/service/searcher.go
- internal/search/exhaustive/service/searcher_test.go
When searching HEAD we don't validate the revision exists until search time. This means for empty repositories it is possible to attempt to search them, leading to a revision not found error in the logs.
Non-exhaustive search would present an error as an alert. But for exhaustive we work around this by just not writing any CSV and treating the job as success. To build trust we likely need to think how to communicate empty repos in the logs, but for now this is a relatively easy thing to trigger so this is good enough for EAP.
Test Plan: updated tests to simulate an empty repo
Fixes https://github.com/sourcegraph/sourcegraph/issues/57179
> search: ignore empty repositories in exhaustive search

- cmd/frontend/internal/search/httpapi/export_test.go
- cmd/frontend/internal/search/init.go
- enterprise/cmd/worker/internal/search/exhaustive_search_test.go
- internal/search/exhaustive/service/service.go
Right now we don't have a good way to give feedback if a worker fails due to the query not being passed. Right now we validate in the frontend, but the validation isn't always aligned so it is possible to hit this path. This commits adds a step in the job creation service which first sees if the query parses.
Test Plan: go test should be sufficient.
Fixes https://github.com/sourcegraph/sourcegraph/issues/57181
> search: validate query before creating exhaustive job

- client/branded/src/search-ui/results/progress/exhaustive-search/exhaustive-search-validation.test.ts
- client/branded/src/search-ui/results/progress/exhaustive-search/exhaustive-search-validation.ts
The backend only supports queries with `type:file` filters. Here I add a check to the client, so that users cannot create search jobs for queries with other `type:` filters.
Test plan:
updated unit test
> search jobs: check query for explicit type filters

- deps.bzl
- go.mod
- go.sum
There was a minor contribution for scala classes which are final. That is the only change for both zoekt and go-ctags here.
Test Plan: CI
> gomod: update go-ctags

- dev/oci_deps.bzl
This fixes vulnerability affecting 5.2 release. so, updating hashes of images CVE-2023-5156
- Green 🟢  CI Build
- Manual inspection of images
> Backport 5.2 : Wolfi update hash for Images 5.2 Release

- client/web/src/auth/SignInPage.tsx
- client/web/src/auth/__snapshots__/SignInPage.test.tsx.snap
The dotcom sign-in page now asks you to contact your site admin, which needs to make more sense in the dotcom context. This is because we disabled sign-ups for INC-239. Instead, we tell users to try App or Enterprise, which is what we did before
Start up your SG instance in dotcom mode. Ensure `allowSignups` is set to `false` in your Site Configuration.
> dotcom: adjust sign-in CTAs when signup is disabled

- cmd/frontend/backend/repos.go
- cmd/frontend/backend/repos_test.go
I've run into this function while investigating things so often and fell for it not actually running on non-dotcom instances each time - so making it extra clear here.
CI, only a rename.
> Make clearer that Repos.add is only called on dotcom

- cmd/gitserver/server/server.go
We have a code path for dotcom where we try to see if a repo is cloneable if it doesn't exist in the DB yet. However, we assume that any error from the getRemoteURL means that the repo is not existing and we should try to clone the repo without auth from a madeup URL. This could cause unauthed clone attempts to repos that actually DO exist in the instance, so added an additional check here if the error is actually a "repo isn't found" error.
CI and integration tests.
> gitserver: Don't attempt to clone repos without auth when DB fails

- client/browser/config/webpack/development.config.ts
- client/browser/config/webpack/production.config.bazel.ts
- client/browser/config/webpack/production.config.ts
This was used for the deprecated and removed Sourcegraph extension API support.
CI
> remove old USE_EXTENSIONS env var

- cmd/executor/internal/run/util.go
- cmd/frontend/graphqlbackend/site_alerts.go
- cmd/frontend/internal/app/app.go
- cmd/frontend/internal/app/ui/help.go
- cmd/frontend/internal/cli/serve_cmd.go
- cmd/frontend/internal/executorqueue/init.go
- cmd/sourcegraph/README.md
- cmd/worker/internal/migrations/init.go
- doc/dev/background-information/sg/reference.md
- internal/api/internalapi/client.go
- internal/conf/computed.go
- internal/conf/conf.go
- internal/conf/confdefaults/confdefaults.go
- internal/conf/deploy/deploytype.go
- internal/conf/deploy/endpoints.go
- internal/highlight/highlight.go
- internal/ratelimit/globallimiter.go
- internal/repoupdater/client.go
- internal/service/svcmain/svcmain.go
- internal/singleprogram/singleprogram.go
- sg.config.yaml
Now, `sg start single-program` starts a single-binary local dev server. This is similar to Cody app, but instead of using a Tauri desktop app UI and limiting to only Cody-related functionality, it runs a full Sourcegraph instance and lets you access it through your web browser. It is useful for local dev because it's less resource-intensive and has faster recompile/relink times than `sg start` (which runs many processes).
For local dev only.
Run `sg start single-program` and confirm that it starts up. CI covers other entrypoints.
> support single-program execution for local dev

- client/branded/src/search-ui/components/QueryExamples.tsx
- client/web/src/notebooks/notebook/NotebookComponent.tsx
- client/web/src/notebooks/notebookPage/NotebookContent.tsx
- client/web/src/notebooks/notebookPage/NotebookPage.tsx
This feature flag was removed in 8d7310a817d5aca6bc9be5962b8319d3055ed9cd 4 months ago, but a few references remained.
CI
> remove unused feature flag enableOwnershipSearch

- CHANGELOG.md
- client/branded/src/search-ui/input/CodeMirrorQueryInput.tsx
- client/branded/src/search-ui/input/SearchBox.tsx
- client/branded/src/search-ui/input/codemirror/completion.test.ts
- client/branded/src/search-ui/input/codemirror/completion.ts
- client/branded/src/search-ui/input/codemirror/index.ts
- client/shared/src/settings/settings.tsx
- client/web/src/enterprise/code-monitoring/components/FormTriggerArea.tsx
- client/web/src/enterprise/insights/components/form/monaco-field/MonacoField.tsx
- client/web/src/enterprise/searchContexts/SearchContextForm.tsx
- client/web/src/notebooks/blocks/file/NotebookFileBlockInputs.tsx
- client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
- client/web/src/notebooks/blocks/symbol/NotebookSymbolBlockInput.tsx
- client/web/src/savedSearches/SavedSearchForm.tsx
- client/web/src/search/SearchConsolePage.tsx
- client/web/src/search/input/SearchNavbarItem.tsx
- client/web/src/storm/pages/SearchPage/SearchPageInput.tsx
- schema/settings.schema.json
This makes it so that the previously on-by-default behavior is now the only behavior. This only affects the old query input, not the new query input. The behavior is confusing to describe, but it basically means that as you type in the old query input, there is no autocomplete item selected until you press the down arrow, so pressing <kbd>Enter</kbd> does not confusingly accept an autocomplete item that you did not intend.
This was set to on by default on https://sourcegraph.com 9 months ago at https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/17546, and has been on by default in all other instances for 1 year.
With the old query input enabled, ensure that the 1st autocomplete item is not selected until you press the down arrow.
> always enable applySearchQuerySuggestionOnEnter

- client/branded/src/search-ui/components/QueryExamples.constants.ts
- client/branded/src/search-ui/components/QueryExamples.module.scss
- client/branded/src/search-ui/components/QueryExamples.tsx
- client/branded/src/search-ui/components/useQueryExamples.tsx
- client/branded/src/search-ui/results/NoResultsPage.tsx
- client/shared/src/settings/temporary/TemporarySettings.ts
- client/web-sveltekit/src/lib/search/queryExamples.ts
- client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
- Fix typos and other imperfections (eg in `repo:foo/.*`, the `.*` is unnecessary)
- Regroup and re-label the examples
- Make diff search examples more prominent
- Remove the diff search pre-populated author because it is unlikely to return results (given that diff search is slow and non-deterministic with respect to order)
- Make queries clickable as links instead of adding to query input
Run with dotcom mode on and off and confirm that the queries make sense and are clickable.
> improve search query examples on homepage

- enterprise/cmd/worker/internal/embeddings/repo/handler.go
- internal/embeddings/embed/embed.go
- internal/embeddings/embed/embed_test.go
We regularly run into a problem where a customer with a large repo tries to embed that repo, gets part way, but then flakiness from OpenAI, their network, or whatever else causes the whole embeddings job to fail. This is very frustrating on the side of the customer, and is the source of a lot of delays when getting customers up and running with Cody. We already retry in the HTTP layer, but sometimes this isn't enough, especially since failures seem to be correlated with the content being sent.
Instead, this PR allows some requests to fail. We already allow some _chunks_ to fail (which is the most common failure case where openAI just returns a null vector), but this extends that setting to now also include full request failures. 
To avoid jobs succeeding when there is a configuration …
> Embeddings: tolerate some failure when generating embeddings

- cmd/frontend/internal/search/httpapi/BUILD.bazel
- cmd/frontend/internal/search/httpapi/export_test.go
- enterprise/cmd/worker/internal/search/BUILD.bazel
- enterprise/cmd/worker/internal/search/exhaustive_search_test.go
- internal/search/exhaustive/service/service.go
This checks `ExperimentalFeatures.SearchJobs` before kicking off a search job.
Test plan:
I unset `experimentalFeatures.searchJobs` locally and verified that the GraphQL API returns an error.
> search jobs: check feature flag in CreateSearchJob

- docker-images/dind/Dockerfile
Update docker dind image to 24.0.6 to patch [CVE-2022-48174](https://access.redhat.com/security/cve/CVE-2022-48174)
- Scan for vulns in updated image
- Confirm new image is compatible
> Update docker dind image to 24.0.6 to fix vulns

- doc/admin/observability/alerts.md
- doc/admin/observability/dashboards.md
- monitoring/definitions/telemetry.go
This includes 1 critical alert - if the export queue grows without decreasing for a very long time (36h). This is a real problem as it can mean there is a very large amount of data accumulating in the DB.
Against Sourcegraph.com data:
[Preview Link](https://docs.sourcegraph.com/@telemetry-export-critical-alert)
> monitoring: add queue growth panel and alert

- wolfi-packages/ctags.yaml
This PR is switching Ctags packages from hash versions to tagged versions
CI Build Checks
> switching ctags to tagged versions

- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/auth/ui/EditCodebaseContextAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/ui/LoadingLayerUI.kt
closes https://github.com/sourcegraph/sourcegraph/issues/56949
This PR fixes the issue that when changing the codebase git url the EDT thread was blocked on every validation. Now the EDT thread is not blocked and user can easily edit the input field while validation happens in background. We also display loading icon in the input field to indicate that validation is in progress
https://github.com/sourcegraph/sourcegraph/assets/7345368/2f121247-c92f-4c8c-8782-37031259cb70
- Edit codebase url and see that validation works and it doesn't block the EDT thread
> JetBrains: validate git url in codebase selection asynchronously without blocking the EDT

- client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgentManager.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/initialization/PostStartupActivity.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyAutocompleteStatus.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyAutocompleteStatusService.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyDisableAutocompleteAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyEnableAutocompleteAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyManageAccountsAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyOpenSettingsAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/CodyStatusBarActionGroup.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/OpenLogAction.kt
- client/jetbrains/src/main/kotlin/com/sourcegraph/cody/statusbar/ReportCodyBugAction.kt
- client/jetbrains/src/main/resources/META-INF/plugin.xml
Adds status bar state for when the agent binary cant be run or crashes while running, as well as a menu option to open idea.log (like in the Help dropdown) in the editor
Tested cases:
- Binary cant be executed (arm64 bin on amd64 machine)
- Process gets terminated externally (SIGTERM)
> JetBrains: show icon when agent doesnt start/crashes

- schema/schema.go
Got out of date, JH is working on a permanent fix. For now, applying this fix manually so that I don't have to revert this change all the time when I run sg generate to keep diffs clean.
CI.
> Regenerate schema.go file

- .editorconfig
The default my editor uses is 4 spaces, which always throws formatting errors in CI. This makes my life easier :)
VSCode no longer uses 4 spaces which makes the linter angry.
> proto: Add editorconfig to ident using two spaces

- client/browser/src/browser-extension/pages/background.html
Followup (fix) to #57229.
Run Chrome extension from unpacked local build and confirm that the background page loads successfully.
> fix background page bundle name

- dev/tool_deps.bzl
The following action updated the arm64 darwin ctags binary, which means it has a new hash
https://github.com/sourcegraph/sourcegraph/actions/runs/6384355462/job/17326849491
Related to: https://github.com/sourcegraph/devx-support/issues/274
Executed locally and CI
> ctags: update darwin ctags sha256

- client/web/src/user/settings/accessTokens/UserSettingsTokensArea.tsx
- pnpm-lock.yaml
Closes [#1267](https://github.com/sourcegraph/cody/issues/1267)
Fixes an issue where the Token creation routes don't have the logic to check if the user has completed the post-signup survey, leading to scenarios where, when signing into Sourcegraph for the first time to create a token, the user wouldn't be asked to complete the quick survey.
Local verification by redirecting to the token creation page on sign-in
> Add redirect to post-signup survey on token routes

- internal/search/exhaustive/service/service.go
If we fail to get from the upload store it would result in a panic due to trying to close the reader. However, the only practical way to trigger this path is to cancel the download request, which means the user luckily wouldn't see this panic.
Test Plan: go test to ensure nothing regresses further. Otherwise I am relying on just code review.
> search: exhaustive panic on uploadstore error

- deps.bzl
- go.mod
- go.sum
The mentioned PR has been merged upstream and is available in 0.8.1, thus ditching the fork.
CI.
> Remove replace directive for graphql-go/graphql

- dev/tool_deps.bzl
The universal-ctags for arm darwin isn't stable, and a new binary has been uploaded replacing the old one which caused the sha to be updated. This is being fixed in #57296.
Part of https://github.com/sourcegraph/devx-support/issues/274
```
curl -L -o universal_ctags https://storage.googleapis.com/universal_ctags/aarch64-darwin/bin/universal-ctags-5.9.20220403.0
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 2612k    0 2612k    0     0  1090k      0 --:--:--  0:00:02 --:--:-- 1093k
sourcegraph on  wb/update-ctags-sha [$?] via 🐹 v1.20.8 took 2s
❯ sha256sum universal_ctags
6631f0bbd65cdedc155fcd9e17c8c31102aeffc78e2438799d4fb43297c5d473  universal_ctags
```
> ctags: update universal-ctags sha

- dev/sg/dependencies/mac.go
- dev/sg/dependencies/ubuntu.go
Since we are working with perforce a bunch and have test suites that need the CLI that are currently skipped locally, I think it makes sense to add the p4 CLI here. 
The installation for ubuntu seems more involved and requires adding package sources and so forth, which I'm not sure we want to do. If you have a good idea on how to best implement this for linux as well, let me know.
Ran `go run ./dev/sg setup` locally and verified things work.
> sg: Install p4 cli for local dev

- cmd/frontend/internal/httpapi/auth.go
In our current setup, when a request with incorrect authentication headers reaches DotCom, it's mistakenly treated with a 429 status code due to how we handle rate limits for anonymous requests. DotCom mode-specific behaviour was identified: the system keeps forwarding the wrong header until it reaches the [middleware that checks if we allow anonymous access](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/auth/non_public.go?L23-37).
This middleware passes the check as it's configured to identify if we are operating in [DotCom mode](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/conf/auth.go?L28-33).
I propose to check if we are in DotCom mode when we have an invalid header, to prevent us from treating users that supply (invalid) …
> auth: return 401 for invalid auth headers on DotCom

- internal/gitserver/BUILD.bazel
- internal/gitserver/client.go
This change switches to conc for the pooling, to prevent multiple go routines potentially writing to the same errs slice.
Manually checked the endpoint still works.
> gitserver: Prevent concurrent writes to errs

- doc/cody/custom-commands.md
This adds docs for the new `mode` custom commands property, which was introduced in sourcegraph/cody#1116.
- Updated doc
- Verified preview link
[Preview Link](https://docs.sourcegraph.com/@add-custom-command-mode-property)
> Add docs for the new custom commands mode property

- internal/gitserver/client.go
- internal/gitserver/gitolite.go
- internal/gitserver/grpc_test.go
We don't actually do anything in the constructor, so we can remove the sync.Once and the helper.
> gitserver: remove lazy constructor for atomicGitServerConns

- .github/workflows/universal-ctags.yml
- dev/nix/ctags.nix
Small improvements:
* have the platform in the job name
* print out the hashes of the binaries
* only upload a new binary if a commit it pushed to main
A bit hard to test but:
* make a small change to `dev/nix/ctags.nix` and see:
** it shouldn't upload anything
** print out the hashes
> ctags actions: only upload when a change to ctags nix is pushed to main

- client/web/BUILD.bazel
- client/web/src/user/settings/auth/ExternalAccount.test.tsx
- client/web/src/user/settings/auth/ExternalAccount.tsx
- client/web/src/user/settings/auth/ExternalAccountsSignIn.test.tsx
- client/web/src/user/settings/auth/ExternalAccountsSignIn.tsx
- client/web/src/user/settings/auth/UserSettingsSecurityPage.tsx
- client/web/src/user/settings/auth/__snapshots__/ExternalAccountsSignIn.test.tsx.snap
As a follow-up to https://github.com/sourcegraph/cody/issues/1267 , this PR displays all connected external accounts for each auth provider.
Under normal circumstances, a user shouldn't have more than one external account per auth provider. But there are ways in which it could happen, such as linking directly to an Auth Provider sign-in page like VS Code does, or possibly when auth providers get removed and added and edited etc.
Regardless, I think it's a good change that changes nothing about the regular behaviour, and alleviates confusion in the unlikely scenario that something wonky happened (and allows users to disconnect those extra external accounts).
Before:
After:
Added snapshot test that confirms that both accounts are shown for a single auth provider.
> Display all external accounts for each auth provider

- cmd/gitserver/internal/gitserverfs/fs.go
- cmd/gitserver/internal/patch.go
- cmd/gitserver/internal/perforce/cloneable.go
- cmd/gitserver/internal/perforce/depots.go
- cmd/gitserver/internal/perforce/login.go
- cmd/gitserver/internal/server.go
- cmd/gitserver/internal/server_grpc.go
- cmd/gitserver/internal/server_test.go
- cmd/gitserver/internal/vcssyncer/vcs_syncer_perforce.go
When running perforce commands, we should set HOME to the .p4home dir in our data directory. All other directories aren't writable in our default helm deployment, and writing a p4trust file to the actual users $HOME will break.
Closes https://github.com/sourcegraph/sourcegraph/issues/53268
Closes https://github.com/sourcegraph/sourcegraph/issues/56261
To test, I spun up a helm-based k8s deployment in the docker for mac k8s environment. First with the latest insiders images off main, and the issue from #53268 showed up for connecting to my locally hosted SSL enabled perforce server.
Then, built a new image with these fixes in, and the connection to the Perforce server no longer fails.
Also verified that the trust file is written at the expected path.
> gitserver: Consistently set HOME to .p4home for perforce

- doc/code_search/how-to/search-jobs.md
To enable search jobs, the user needs to configure a storage bucket first.
Test plan:
CI
[Preview Link](https://docs.sourcegraph.com/@sh/search-jobs-update-docs)
> search jobs: mention bucket config in the docs

- internal/gitserver/BUILD.bazel
- internal/gitserver/client.go
- internal/gitserver/client_test.go
Depends on #57316 
When I run go test -race on this, I get the following (expected) race condition that @eseliger 's #57316 PR will fix. 
```
=== RUN   TestClient_SystemsInfo/GRPC
==================
WARNING: DATA RACE
Write at 0x00c000e40e9f by goroutine 112:
github.com/sourcegraph/sourcegraph/internal/gitserver_test.TestClient_SystemsInfo.func3.2.1.1()
/Users/ggilmore/dev/sourcegraph/internal/gitserver/client_test.go:1585 +0xe4
github.com/sourcegraph/sourcegraph/internal/gitserver_test.(*mockClient).DiskInfo()
/Users/ggilmore/dev/sourcegraph/internal/gitserver/client_test.go:1776 +0x74
github.com/sourcegraph/sourcegraph/internal/gitserver.(*clientImplementor).getDiskInfo()
/Users/ggilmore/dev/sourcegraph/internal/gitserver/client.go:519 +0xe0 …
```
> gitserver: disk-info: make test hit two separate gitserver addresses

- internal/database/external_services.go
In case we ever don't set the created_at field, this makes sure that it's set to a time other than `time.Time{}`.
Closes https://github.com/sourcegraph/sourcegraph/issues/36224
CI and checked references of this function.
> extsvc: Ensure created_at is set

- internal/database/repos.go
- internal/search/zoekt/BUILD.bazel
- internal/search/zoekt/indexed_search.go
In cloud v1 we would automically include all user added private repos. However, we no longer have user added external services so this code is a noop. In fact on cloud we have no private repos, so effectively this should always return an empty list on dotcom.
This commits doesn't yet do the TODO around using repos.Resolve, since I'm worried about changing too much at once. Feels like a good follow-up.
Additionally there are a few more uses of UserID and OrgID on the repo listing API. It wasn't obvious to me how to update those call sites, so I just added a comment noting the deprecation and would rather follow-up with other PRs.
Test Plan: just relying on unit tests. The only possible functional change is on dotcom, but in that case it was always empty since we have no private repos on …
> search: remove UserID logic for dotcom repo resolution

- monitoring/BUILD.bazel
While debugging builds running against Aspect Workflows, we stumbled across this issue: 
```
=== RUN: File Existence Test: Dashboard config
--- FAIL
duration: 0s
Error: /sg_config_grafana/provisioning/dashboards/sourcegraph/gitserver.json has incorrect user ownership. Expected: 0, Actual: 501
```
This is happening because we're creating the monitoring config tarball manually with a `genrule` instead of using `pkg_tar` (for convenience). Because the commands for that rule are not explicitly set the ownership on these files, it just end up being whatever user the agent is running the build with.
This works against normal Bazel CI agent, because they're running everything as root (yes bad, that's why we're happy to switch for AW). But when running it on the upcoming agents, it will instead …
> bzl: fix ownership of generated monitoring config

- CHANGELOG.md
- client/web/src/components/FilteredConnection/hooks/usePageSwitcherPagination.ts
- client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
- cmd/frontend/graphqlbackend/authz.go
- cmd/frontend/internal/authz/resolvers/permissions_info.go
- internal/database/perms_store.go
- internal/database/perms_store_test.go
Fixes an issue where admins can't view a user's permissions if they don't have access to all of the repos a user has access to.
Previously the page would just load forever, now admins are told they can't see the repo:
Manual tests
> [bug] Display user permissions even if the GQL resolver has errors

- cmd/worker/shared/BUILD.bazel
- cmd/worker/shared/main.go
- cmd/worker/shared/service.go
Now that everything is enterprise, we can simplify the initialization a bit. This PR mostly just inlines the `enterpriseInit` logic so that it always runs.
Ran `sg start` and saw worker do its thing.
> Chore: simplify enterprise init in `worker`

- dev/ci/integration/executors/run.sh
Was moved out of enterprise/, so this is no longer correct.
CI
> Fixup script path after move

- internal/telemetry/BUILD.bazel
- internal/telemetry/besteffort.go
- internal/telemetry/telemetrytest/BUILD.bazel
- internal/telemetry/telemetrytest/telemetrytest_test.go
This fixes a [nil panic](https://files.slack.com/files-pri/T02FSM7DL-F0601EYB25S/new_error_in_sourcegraph-dev_sourcegraph-frontend_sourcegraph-frontend-5c688b9445-frtdq) that was showing up when recording with nil parameters, which is documented as an okay thing to do. 
Added a test that this no longer panics when recording fails.
> Telemetry: fix nil panic 

- dev/release/release-config.jsonc
This updates the release date to being 10am in my working hours, rather than 7pm.
Test Plan: Ran "pnpm run release tracking:timeline" in dryRun mode. Once in main will run for real. Given the cal event already exists, might require Bolaji to update the event time.
> release: update 5.2.1 release to 10am SAST

- sg.config.yaml
I often want to quickly test a config change to a code host config, but then realize I forgot to set this env var manually again and then need to restart the entire stack. I don't think disallowing edits is a great default, so instead of adding it to my override file I'm proposing to add it to the general configuration.
What do people think?
Tested in local dev that it is respected properly.
> Allow to edit code host config temporarily in local dev by default

- cmd/frontend/internal/search/httpapi/export.go
- cmd/frontend/internal/search/resolvers/search_job.go
- cmd/worker/internal/search/exhaustive_search_test.go
- internal/search/exhaustive/service/service.go
- internal/search/exhaustive/store/exhaustive_search_jobs.go
- internal/search/exhaustive/store/store.go
This removes the awkwardness introduced [here](#56957) between `Get` and `List` for exhaustive search. The problem was that we used `Get` to retrieve the job AND for security checks. This PR decouples these two concerns.
- We add a dedicated method to the store for security checks and update all call sites
- The remaining calls to Get are legit calls to retrieve the job
- We update `Get` to include the aggregated state, just like `List`.
Note:
This doesn't mean we shouldn't investigate a more elegant solution for state aggregation long term, but at least the complexity is now confined to the store and doesn't leak to the API anymore.
This is a refactor, so relying on CI
> search jobs: add state aggregation to GetSearchJob

- dev/sg/internal/images/dockerhub.go
- dev/sg/internal/images/gcr.go
- dev/sg/internal/images/helm.go
- dev/sg/internal/images/registry.go
Fixes https://github.com/sourcegraph/devx-support/issues/285
Ran the updating command against the repo, with a `sg` built with the code from this PR. It went fine as expected.
> sg: fix sg ops issue with dogfood-k8s

- cmd/frontend/graphqlbackend/repositories.go
This resolver is not actually used. I think it could of been removed a while ago as per Naman's comment about it being unused. The interface for it needs to remain, but the actual implementation here can be removed.
Test Plan: go test. If that is happy we know the code is unused.
> graphqlbackend: remove unused repositoryConnectionResolver

- BUILD.bazel
- client/branded/src/search-ui/components/QueryExamples.module.scss
- client/branded/src/search-ui/components/RepoMetadata.module.scss
- client/branded/src/search-ui/input/SearchContextDropdown.module.scss
- client/jetbrains/webview/src/search/input/JetBrainsToggles.module.scss
- client/web/src/enterprise/insights/components/views/card/InsightCard.module.scss
- client/web/src/setup-wizard/components/remote-repositories-step/components/navigation/CodeHostsNavigation.module.scss
- client/wildcard/src/components/Button/Button.module.scss
- client/wildcard/src/global-styles/base.scss
- client/wildcard/src/global-styles/custom-forms.scss
- client/wildcard/src/global-styles/forms.scss
Resolves part of https://github.com/sourcegraph/sourcegraph/issues/44878
- `:focus` is unconditional selector, every time when element is focused (regardless of what caused this focus) this selector will match
- `:focus-visible` is conditional, and browser decides when this selector will match, for example clicks on button shouldn't trigger focus-ring style, so focus-visible won't be triggered/matched.
In our styles we're heavily using `:focus` selector, and therefore we have a lot of controls which always have focus-ring styles, sometimes this also causes having double focus-ring UI (our custom ring from `base.scss` and browser standard ring)
So this PR replaces `:focus` to `:focus-visible` in some places where it makes sense, we still need to use :focus somewhere where it should be use …
> Use focus-visible instead of focus pseudo selector

- cmd/frontend/internal/app/ui/handlers.go
- cmd/frontend/internal/app/ui/tmpl.go
- cmd/frontend/main.go
- cmd/sourcegraph/main.go
- dev/sg/sg.config.example.yaml
- sg.config.yaml
- ui/assets/doc.go
This env var was already used when running either Webpack or esbuild. In the future Webpack will no longer be used, so a more general name not tied to the specific bundler is best.
(Command: `fastmod -e yaml,go,md WEBPACK_DEV_SERVER WEB_BUILDER_DEV_SERVER`)
This was only used for local dev. Run a local dev server with `sg start` and confirm that frontend assets are built.
> rename env var WEBPACK_DEV_SERVER to WEB_BUILDER_DEV_SERVER

- deps.bzl
- go.mod
- go.sum
This just includes one commit which is a convenience for our dev environments.
- https://github.com/sourcegraph/zoekt/commit/cc1b5cda70 ctags: allow binary to be anything with validation
Test Plan: see test plan in that commit. Otherwise go test
Fixes https://github.com/sourcegraph/sourcegraph/issues/57336
> gomod: update zoekt to allow CTAGS_COMMAND=ctags

- shell.nix
It has been broken for me since the nix changes a few weeks ago. I've mostly been devving on linux so I've been ignoring it.
Test Plan: nix develop on my mbp
> nix: do not manage bazel on MacOS

- client/web/dev/esbuild/build.ts
- package.json
- pnpm-lock.yaml
Webpack builds already use the Webpack Sentry plugin to automatically inject code to send errors to Sentry. This adds the same to the esbuild build config.
esbuild is dev only, so CI suffices.
> add sentry esbuild plugin

- client/browser/src/end-to-end/github.test.ts
- client/browser/src/end-to-end/gitlab.test.ts
Skipping GitHub e2e tests for the extension because the extension no longer works in the file view after the GitHub redesign. 
E2E tests pass.
> bext: skip github e2e tests

- internal/search/repos/repos.go
We don't have repos associated with user or org anymore. I was thinking stuff would go wrong since we were setting these values, but if you read the database code if SearchContextID is set we ignore the UserID and OrgID.
This change is part of removing UserID and OrgID from the repos API.
Test Plan: go test. Additionally manually inspected some tables on dotcom to understand what data we had for these fields.
> search: do not specify user or org id from search contexts

- BUILD.bazel
This was erroneously removed in https://github.com/sourcegraph/sourcegraph/pull/57387/files#r1349473876.
CI
> add back bazel dep for postcss-focus-visible

- client/web/src/components/ErrorBoundary.test.tsx
- client/web/src/components/ErrorBoundary.tsx
- client/web/src/components/__snapshots__/ErrorBoundary.test.tsx.snap
- client/web/src/monitoring/index.ts
- client/web/src/monitoring/shouldErrorBeReported.ts
If a frontend chunk fails to load with Webpack, the user sees a message telling them to reload. This change makes it so that users also see this when esbuild is used as the bundler. Esbuild surfaces this error slightly differently.
Use esbuild locally. Set a Chrome devtools network blocker for a chunk file. Confirm the reload page is shown.
> show "Reload" for esbuild dynamic import errors

- .gitignore
- client/observability-server/src/webBundleSize/getBundleSizeStats.test.ts
- client/observability-server/src/webBundleSize/getBundleSizeStats.ts
- client/observability-server/src/webBundleSize/index.ts
- client/web/dev/esbuild/manifestPlugin.ts
- client/web/dev/server/bazel.server.ts
- client/web/dev/server/development.server.ts
- client/web/dev/server/production.server.ts
- client/web/dev/utils/get-index-html.ts
- client/web/src/integration/context.ts
- client/web/webpack.bazel.config.js
- client/web/webpack.config.js
- cmd/frontend/internal/app/ui/handlers.go
- cmd/frontend/internal/app/ui/handlers_test.go
- dev/Caddyfile
- dev/sg/linters/linters.go
- doc/dev/setup/troubleshooting.md
- ui/assets/assets.go
- ui/assets/dev.go
- ui/assets/doc.go
- ui/assets/enterprise/assets.go
- ui/assets/manifest.go
This file is produced by both Webpack and esbuild. It is not Webpack-specific.
```
fastmod -e yaml,ts,js,md,tsx WEBPACK_MANIFEST WEB_BUILD_MANIFEST
fastmod -e yaml,ts,js,md,tsx,go webpack.manifest.json web.manifest.json
fastmod -e yaml,ts,js,md,tsx,go webpackManifestPath webBuildManifestPath
fastmod -e yaml,ts,js,md,tsx,go 'webpack manifest' 'web build manifest'
fastmod -e go,ts,tsx webpackManifest webBuildManifest
fastmod -e go,ts,tsx WebpackManifest WebBuildManifest # not all accepted
```
CI
[Preview Link](https://docs.sourcegraph.com/@sqs/esbuild-etc/webpack-names2)
> rename {webpack => web}.manifest.json

- client/web/README.md
- client/web/dev/server/production.server.ts
- client/web/dev/utils/create-js-context.ts
- client/web/dev/utils/environment-config.ts
- client/web/webpack.bazel.config.js
- client/web/webpack.config.js
- sg.config.yaml
This is not Webpack-specific, and now many/most people would actually use this with esbuild.
fastmod -e yaml,ts,js,md,tsx WEBPACK_SERVE_INDEX WEB_BUILDER_SERVE_INDEX
CI
> rename {WEBPACK => WEB_BUILDER}_SERVE_INDEX env var

- .eslintrc.js
- client/branded/src/components/ToggleBig.story.tsx
- client/branded/src/search-ui/input/codemirror/active-filter.ts
- client/branded/src/search-ui/input/experimental/suggestionsExtension.ts
- client/branded/src/search-ui/results/AnnotatedSearchExample.tsx
- client/shared/src/search/query/patternMatcher.test.ts
- client/web/src/repo/blob/codemirror/blame-decorations.tsx
- client/wildcard/src/components/Typography/Heading/H1.tsx
- client/wildcard/src/components/Typography/Heading/H2.tsx
- client/wildcard/src/components/Typography/Heading/H3.tsx
- client/wildcard/src/components/Typography/Heading/H4.tsx
- client/wildcard/src/components/Typography/Heading/H5.tsx
- client/wildcard/src/components/Typography/Heading/H6.tsx
- dev/release/src/release.ts
The `id-length` eslint rule forbids short variable names (3 chars or less). This is a bad rule IMO because it leads to needlessly long var names (`index` instead of `i`). It's also really annoying, and I know I'm not alone in feeling that (https://registerspill.thorstenball.com/p/who-removes-rules).
CI
> globally disable the id-length rule (long live vars named `i`)

- client/branded/BUILD.bazel
- client/branded/src/search-ui/input/BaseCodeMirrorQueryInput.story.tsx
- client/branded/src/search-ui/input/BaseCodeMirrorQueryInput.tsx
- client/branded/src/search-ui/input/CodeMirrorQueryInput.module.scss
- client/branded/src/search-ui/input/CodeMirrorQueryInput.tsx
- client/branded/src/search-ui/input/codemirror/active-filter.ts
- client/branded/src/search-ui/input/codemirror/parsedQuery.ts
- client/branded/src/search-ui/input/codemirror/token-info.ts
- client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
- client/branded/src/search-ui/input/experimental/codemirror/history.ts
- client/branded/src/search-ui/input/experimental/codemirror/syntax-highlighting.ts
- client/shared/src/components/CodeMirrorEditor.tsx
- client/web/src/nav/GlobalNavbar.tsx
- client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
- client/web/src/notebooks/blocks/suggestions/SearchTypeSuggestionsInput.tsx
- client/web/src/search/SearchConsolePage.tsx
- client/web/src/search/input/ExperimentalSearchInput.tsx
- client/web/src/search/input/SearchNavbarItem.tsx
- client/web/src/storm/pages/SearchPage/SearchPageInput.tsx
First part of `N` to clean up the CodeMirror query input implementation.
We currently have to "main" query input implementations, the "old" one in `client/branded/src/search-ui/input/CodeMirrorQueryInput.tsx` and the experimental/new one in `client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx`. They share quite a bit of code but not as much as they could.
There are also two "configurations" of the old query input, `CodeMirrorMonacoFacade` and `CodeMirrorQueryInput`.
All these differ from each other in two ways: 
1. which (CodeMirror) extensions configured
2. how they integrate with other UI elements "around" them
My plan is to simplify at least the first one by rearranging the logic inside these components into reusable/configurable extensions that can be …
> search: Cleanup CodeMirror query input (part 1)

- CHANGELOG.md
Moves the backport changes to the 5.2.1 heading.
Changelog update
> Update changelog for 5.2.1 backports

- .github/workflows/sg-setup.yml
- .tool-versions
- WORKSPACE
- dev/sg/checks.go
Update go to 1.20.9 which fixes https://github.com/sourcegraph/devx-support/issues/241
CI
> update go to 1.20.9

- client/web/src/auth/CloudSignUpPage.story.tsx
- client/web/src/auth/PostSignUpPage.story.tsx
- client/web/src/auth/RequestAccessPage.story.tsx
- client/web/src/auth/ResetPasswordPage.story.tsx
- client/web/src/auth/SignInPage.story.tsx
- client/web/src/auth/SignUpPage.story.tsx
- client/web/src/auth/UnlockAccount.story.tsx
- client/web/src/auth/VsCodeSignUpPage.story.tsx
- client/web/src/site-admin/init/SiteInitPage.story.tsx
Just adding these stories to chromatic. That was the reason we didn't get the diff last time.
I think login and signup are important enough to spend a few snapshots on.
Check chromatic diff.
> Verify signup and login pages in chromatic

- client/storybook/BUILD.bazel
- client/storybook/src/main.ts
- dev/ci/internal/ci/operations.go
- package.json
- pnpm-lock.yaml
This fixes a few project metadata detection issues, makes it easier to run chromatic locally for testing, and potentially fixes TurboSnap with vite.
Tested locally that this new configuration correctly emits build metadata and that project and addons are correctly identified now.
> chromatic: Fixup project detection and emit TurboSnap metadata with vite

- client/browser/src/end-to-end/gitlab.test.ts
It looks like our tests are failing because we added an alias for the sourcegraph org.
This just fixes a test
> e2e tests: update sourcegraph group name

- client/storybook/src/main.ts
- client/storybook/src/preview.ts
- client/web-sveltekit/.storybook/main.ts
- package.json
- pnpm-lock.yaml
This was not being used. It was there previously, but for some reason the upgrade to Storybook 7 made it more prominent.
CI
> remove storybook addon-docs

- .bazelignore
These sometimes contain BUILD.bazel files that confuse local working copies.
CI
> bazelignore storybook static files

- doc/admin/pings.md
This code path moved
Doc
[Preview Link](https://docs.sourcegraph.com/@wg/fix-ping-channel-link)
> Doc: update doc link for release.channel and pings

- dev/app/app-version.sh
- dev/app/build-backend.sh
- dev/app/build.sh
- dev/app/create-github-release.sh
- dev/app/create-update-manifest.sh
- dev/app/tauri-build.sh
With the move of the scripts from `enterprise` to `dev` the scripts had the wrong cwd. This fixes it
* Pushing this branch to `app-release/debug`
* https://buildkite.com/sourcegraph/cody-app-release/builds/1401#018b18f3-5542-4f18-9da5-fe6b44968afa
> app: fix script paths

- CHANGELOG.md
- internal/conf/computed.go
- internal/search/backend/aggregate.go
- internal/search/backend/horizontal.go
- internal/search/backend/horizontal_test.go
- internal/search/backend/metered_searcher.go
- internal/search/client/client.go
- internal/search/types.go
- internal/search/types_test.go
- schema/schema.go
- schema/site.schema.json
The enhanced ranking logic is GA since 5.1. So far we haven't had any issue so we should remove the old code path with 5.3.
Test plan:
CI
> ranking: remove old code path

- dev/codehost_testing/BUILD.bazel
- dev/codehost_testing/org.go
- dev/codehost_testing/repo.go
Add actions to create github reposa and also to delete them. The added
actions are able to:
- fork repos
- push local repos
- make repos public / private
tested in wb/e2e/poc
> e2e tst: add actions to create repos

- cmd/frontend/auth/user.go
- cmd/frontend/auth/user_test.go
- cmd/frontend/backend/user_emails_test.go
- cmd/frontend/graphqlbackend/external_accounts_test.go
- cmd/frontend/internal/auth/sourcegraphoperator/associate.go
- cmd/frontend/internal/auth/sourcegraphoperator/associate_test.go
- cmd/frontend/internal/authz/webhooks/github_test.go
- cmd/repo-updater/internal/authz/perms_syncer.go
- cmd/repo-updater/internal/authz/perms_syncer_test.go
- cmd/worker/internal/auth/sourcegraph_operator_cleaner_test.go
- cmd/worker/internal/permissions/perms_syncer_scheduler_test.go
- dev/sg/sg_db.go
- internal/database/authz_test.go
- internal/database/dbmocks/mocks_temp.go
- internal/database/external_accounts.go
- internal/database/external_accounts_test.go
- internal/database/repos_perm_test.go
- internal/database/users_test.go
- internal/extsvc/gerrit/externalaccount/externalaccount.go
- internal/own/ownref_test.go
- internal/sourcegraphoperator/associate.go
Closes #57418 
UserExternalAccountsStore operations that add a user external account now returns the created external account.
This fixes an issue in the permissions syncer where, for providers that implement `FetchAccount`, the created external account is used without an external account ID in the first sync, which leads to entries in the `user_repo_permissions` table where the external account ID is `NULL`.
Unit test adjusted to assert that the user repo permissions inserted does not have an external account ID of 0.
> [bug] Fix syncUserPerms creating user repo permissions with NULL external account IDs

- dev/codehost_testing/BUILD.bazel
- dev/codehost_testing/README.md
- dev/codehost_testing/example/BUILD.bazel
- dev/codehost_testing/example/example_test.go
- dev/codehost_testing/github_client.go
- dev/codehost_testing/org.go
- dev/codehost_testing/repo.go
- dev/codehost_testing/scenario.go
- dev/codehost_testing/scenario_test.go
- dev/codehost_testing/team.go
- dev/codehost_testing/user.go
add actions to create github users and also remove created users.
note: we cannot create admins so instead of search and map a user to the
Admin user
tested in wb/e2e/poc
> e2e tst: add actions to create github users

- internal/gitserver/BUILD.bazel
- internal/gitserver/client.go
- internal/gitserver/client_test.go
Manual backport of #57318 since there were merge conflicts. 
CI
> [backport 5.2] gitserver: disk-info: make test hit two separate gitserver addresses

- .github/teams.yml
- .github/workflows/label-move.yml
- .github/workflows/label-notify.yml
- .github/workflows/move-labled-issues-to-project.yml
We added an [automated workflow](https://github.com/orgs/sourcegraph/projects/209/workflows/12532815) that adds team/source tickets to our triage inbox. We will check this column regularly instead of creating massive email spam for each of us each time an issue is labeled with team/source. This also allows us to retire some old GitHub actions workflows.
GH actions logs will tell.
> source: Use automated project board workflows

- doc/dev/background-information/telemetry/protocol.md
- internal/telemetrygateway/identifier.go
- internal/telemetrygateway/v1/telemetrygateway.pb.go
- internal/telemetrygateway/v1/telemetrygateway.proto
Fixes a typo in the type name. This will not break the protocol, as proto type names are not used during encoding.
CI
[Preview Link](https://docs.sourcegraph.com/@telemetry-gateway-typo)
> telemetry-gateway: fix typo in proto type name

- dev/ci/images/images.go
This service is in the process of being removed, so we're dropping it from this list.
CI.
> Remove GitHub Proxy from dev/ci/images list

- client/app-shell/static/index.html
In recent user testing of sourcegraph/cody#1275 all the users mentioned App’s loading time, and many showed some discomfort as to whether it was loading correctly. Loading also stalled for one of the users.
This updates the App’s loading screen to:
- After 5 seconds, start showing some messages (ala Slack & Discord) to give people a bit more confidence that things are happening
- After 30s says "Initializing" and includes a link to show the logs and to email support
https://github.com/sourcegraph/sourcegraph/assets/153/13ffa3c5-7679-4ca6-b77f-56b4c1113229
- Tested in browser
- Test links in Tauri wrapper
> Adding loading messages and buttons to Cody App loading screen

- cmd/frontend/globals/BUILD.bazel
- cmd/frontend/globals/globals.go
Asking for a stamp because this is blocking main.
For some reason, changing this file was causing backend integration tests to fail. I have not figured out why. I assume it's something like the global logger isn't being initialized on some startup paths, and these are being called during init time, but I also didn't see a panic message in the test logs, so I have no idea. In any case, these are causing test failures, so I'm partially reverting the change.
Ran the `backend-integration` tests on this PR.
> Fix build: revert globals change

- doc/dev/background-information/sg/reference.md
- sg.config.yaml
This wraps the necessary secrets to run the e2e tests locally, exactly like it's done in CI. 
Eases working on https://github.com/sourcegraph/devx-support/issues/300 
> sg: add a test target that wraps bazel e2e tests

- CHANGELOG.md
- dev/oci_deps.bzl
We ran `sg wolfi update-hashes`. This makes sure we are using the latest version of `curl` and other dependencies that have been updated.
Related to: https://github.com/sourcegraph/sourcegraph/pull/57529.
CI tests will verify the builds. Verified versions locally, see [comment below](https://github.com/sourcegraph/sourcegraph/pull/57533#issuecomment-1757439310).
> wolfi: update base-images (CVE-2023-38545)

- internal/cmd/tracking-issue/Dockerfile
The dockerfile was using an old version of the Go base images, which weren't compatible with the time format I used to patch this code. 
Locally built.
> tracking-issue: update Dockerfile

- .github/workflows/tracking-issue.yml
We're triggering that workflow on a ton of events, and each run crawls a ton of issues for nothing, very often soft-failing because it triggers the limits for making requests. 
Nobody needs the tracking issues to be updated instantly, every 15m is perfectly fine. 
CI
> tracking-issue: only trigger periodically

- dev/ci/internal/ci/config.go
- dev/ci/internal/ci/operations.go
- dev/ci/internal/ci/pipeline.go
- dev/ci/internal/ci/wolfi_operations.go
- dev/ci/runtype/runtype.go
- dev/ci/runtype/runtype_test.go
- doc/dev/how-to/wolfi/add_update_images.md
Allow us to automatically rebuild Wolfi base images periodically. This can be triggered using a Buildkite scheduled build.
Implements https://github.com/sourcegraph/security/issues/986 to rebuild Wolfi base images automatically, speeding up dependency upgrades.
When run against a branch, newly built images will be pushed to GCR. When run against `main`, they will be pushed to Dockerhub.
- Tested locally with `WOLFI_BASE_REBUILD=true sg ci preview --format yaml`
- Scheduled run against `will/wolfi-base-rebuild-auto` branch: https://buildkite.com/sourcegraph/sourcegraph/builds/246765#018b1f59-2f46-469d-89da-e73a19b999da
> wolfi: Rebuild wolfi base images when env WOLFI_BASE_REBUILD=true

- cmd/frontend/internal/app/ui/router.go
This fixes #56624 by implementing the solution described in this comment: https://github.com/sourcegraph/sourcegraph/issues/56624#issuecomment-1720266424
Before the copy&paste allegations: I independently arrived at the same thing after trying to figure out where the loop comes from.
- Manual testing locally as described in the ticket.
> Allow HEAD requests on non-dotcom instances

- internal/database/BUILD.bazel
- internal/database/event_logs.go
- internal/database/telemetry_export_store.go
- internal/trace/context.go
When a request context is cancelled, the [corresponding event database insert can fail on context cancellation](https://sourcegraph.slack.com/archives/C03V51C8K53/p1697072391851359) - but this is highly unlikely to be desirable behaviour, since we probably want to proceed with persisting the event regardless.
This change introduces a new helper in `internal/trace`, `BackgroundContext`, which aliases `CopyContext(context.Background(), from)` with some more docstrings on when to use it and how to use it correctly. We use this new background context in the most inner part of `(TelemetryEventsExportQueueStore).QueueForExport` and `(EventLogStore).BulkInsert` to ensure we don't interrupt database inserts.
CI
> event_logs, telemetry_export: do not interrupt insert on context cancel

- internal/codemonitors/search_test.go
This fixes a build failure on main from a bad merge.
It builds.
> Chore: fix build from bad merge

- doc/dev/how-to/debug_executor.md
- doc/dev/how-to/index.md
Eric and Bolaji put together some nice notes on debugging executors, and I wanted to capture it in a place that's more permanent than a slack message.
CI
[Preview Link](https://docs.sourcegraph.com/@cc/document-executor-debugging)
> Add dev docs for debugging firecracker executors

- dev/buildchecker/branch.go
- dev/buildchecker/branch_test.go
- dev/buildchecker/testdata/TestRepoBranchLocker/lock.yaml
- dev/buildchecker/testdata/TestRepoBranchLocker/unlock.yaml
The lock / unlock operation of buildchecker has been broken for quite a while due to an API change.
By default, GetRequiredStatusChecks returns with Contexts and Checks populated but the API docs specify that Contexts is deprecated and one should prefer check. Additionally only ONE of them should be set. See https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection
Tested it out locally against a branch on `sourcegraph/infrastructure`
> buildchecker: update lock/unlock api for buildchecker

- client/web/src/components/FilteredConnection/hooks/useShowMorePagination.ts
- client/web/src/repo/commit/RepositoryCommitPage.tsx
- client/web/src/repo/commits/RepositoryCommitsPage.tsx
- client/web/src/repo/tree/TreePageContent.tsx
(partially) Closes #57324 
This PR makes some Apollo query changes, setting error policies to 'all'. This allows changelists/commits to render even when the GraphQL resolvers have errors.
This at least makes the pages functional, but I created a follow-up ticket to review our GraphQL resolvers [here](https://github.com/sourcegraph/sourcegraph/issues/57556). We're very error happy in the resolvers, and it brings down the whole page, even when not having access to something is completely expected.
Manual tests
> Display commits/changelists even if graphql error occurs

- client/web-sveltekit/src/lib/branded.ts
- client/web-sveltekit/src/lib/search/CodeMirrorQueryInput.svelte
Because the prototype (intentionally) isn't "verified" when changes to other packages are made, it's possible that it breaks when code in other packages changes.
This commit brings the prototype up-to-date. The `singleLine` extension was recently refactored and the `applyOnEnter` option was removed.
`pnpm build` builds the app successfully
> sveltekit: Fix prototype due to external package changes

- dev/ci/scripts/wolfi/update-base-image-hashes.sh
- doc/dev/how-to/wolfi/add_update_images.md
- Update docs: improve instructions; fix URL as branch name has changed
- Include buildkite build # in PR, and update on rebuilds
- Docs change - green CI
- Run CI pipeline manually with `WOLFI_BASE_REBUILD=true` https://buildkite.com/sourcegraph/sourcegraph/builds/247084#018b2933-639c-458c-ba20-f35b4cf9a62c
- Confirm PR body is updated with link: https://github.com/sourcegraph/sourcegraph/pull/57570
[Preview Link](https://docs.sourcegraph.com/@will/wolfi-auto-update-docfix)
> wolfi: Improve auto-update image docs and PR body

- cmd/frontend/graphqlbackend/git_commit.go
- cmd/frontend/graphqlbackend/perforce_changelist.go
- cmd/frontend/graphqlbackend/perforce_changelist_test.go
The `FetchCommits` query is used to list the commit history of a file. That particular operation is quite slow, so we spent some time digging into why. 
Traces indicated that there were a _ton_ of followup requests to gitserver after resolving initial list of commits. We tracked this down to two sources:
1) Do not do a followup request to resolve the root tree of a commit. We can just assume this exists.
2) Do not resolve the parent commits for the sake of Perforce when we are not in a perforce repo.
Updated existing test and manually compared the results of a few queries.
> Perf: improve speed of `FetchCommits`

- sg.config.yaml
Handling a missing edge case where the user could be running the command from Linux.
> sg: handle running test bazel-e2e on Linux

- cmd/repo-updater/image_test.yaml
- wolfi-images/repo-updater.yaml
Reverts #57120
Update: ah, this needs to be a two-step process, one to revert the image and the next to add the test.
After https://github.com/sourcegraph/sourcegraph/pull/57119 we no longer require the `p4cli` package on `main`. However, we use images built from `main` on the 5.2 release branch rather than building a separate set of images, and the 5.2 branch requires this package to be present.
So far building-from-main has been a simple solution that hasn't caused problems, but does mean that changes which are backwards-incompatible with the release branch break things.
My preferred solution would be to [investigate rules_apko](https://github.com/sourcegraph/security/issues/998) as this will simplify the build process and should solve this problem.
A quicker, but conceptually more …
> Add p4 binary back to repo-updater image

- client/web/src/enterprise/repo/settings/RepoSettingsPermissionsPage.tsx
- internal/database/perms_store.go
- internal/database/perms_store_test.go
Fixes an issue I encountered while confirming something else on the repo permissions page.
Explicit permissions aren't represented on the repo permissions pages at all. They're represented as "permission syncs" which isn't true.
This PR fixes that.
Before:
After:
Updated unit test to test for these cases
> Fix explicit perms label being missing on repo permissions page

- internal/gitserver/client_test.go
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
I was hopeful that I could improve commit parsing speed because I saw a span that took 600ms to run a git command compared to the 200ms I was getting when I ran the command in the terminal. However, after going through the trouble of cleaning this all up, it turns out my baseline number was very skewed and now I'm measuring ~200ms with the code in `main`. So this doesn't actually seem to improve performance much (though it does reduce allocations).
_However_, this dramatically simplifies our parsing logic for streaming commits, so I think it's still worth merging even without a measurable perf improvement. See inline comments and diffs.
Existing tests cover the parsing quite well. Manual sanity checks of the areas of our UI which use commit history.
> Cleanup: simplify commit parsing

- cmd/cody-gateway/internal/httpapi/embeddings/handler.go
- cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
This fixes a regression from https://github.com/sourcegraph/sourcegraph/pull/53346, where the original consumption calculation for embeddings usage was as follows:
```go
// If response is healthy, consume the rate limit
if responseRecorder.StatusCode >= 200 && responseRecorder.StatusCode < 300 {
uh := w.Header().Get(usageHeaderName)
if uh == "" {
logger.Error("no usage header set on response")
}
usage, err := strconv.Atoi(uh)
logger.Error("failed to parse usage header as number", log.Error(err))
}
if err := commit(usage); err != nil {
logger.Error("failed to commit rate limit consumption", log.Error(err))
}
}
```
The equivalent of the above is now implemented in a callback provided to the `HandleFeature` constructor which handles usage-based-rate-limiting.
The `usedTokens` …
> cody-gateway: fix embeddings rate-limiting to be consumption-based

- doc/cody/overview/index.md
Add the Neovim extension link to the main Cody overview page. 
Docs Added
[Preview Link](https://docs.sourcegraph.com/@add-neovim)
> Add Neovim extension link to main Cody overview page

- cmd/executor/internal/run/install.go
- cmd/executor/internal/run/run.go
- cmd/executor/internal/run/validate.go
- cmd/executor/internal/util/srccli.go
- cmd/executor/internal/util/srccli_test.go
- cmd/executor/internal/util/validate.go
- cmd/executor/internal/util/validate_test.go
Use client for auth in HTTP request not options apiclient.EndpointOptions
Correctly adds auth header to request
internal context: [https://sourcegraph.slack.com/archives/C01JR51JR5J/p1697050361943039](https://sourcegraph.slack.com/archives/C01JR51JR5J/p1697050361943039)
Tested the request construction locally against `sgdev`:
```
λ ~/sourcegraph/ wg/fix-executor-installSrc EXECUTOR_FRONTEND_URL=https://k8s.sgdev.org EXECUTOR_FRONTEND_PASSWORD=REDACTED go run ./cmd/executor install src-cli --bin-dir ~
λ ~/sourcegraph/ wg/fix-executor-installSrc ~/src version
Current version: 5.2.0
Recommended version: 5.2.0 or later
```
Printing the new request
```
λ ~/sourcegraph/ wg/fix-executor-installSrc EXECUTOR_FRONTEND_URL=https://k8s.sgdev.org/ EXECUTOR_FRONTEND_PASSWORD=REDACTED go run …
```
> fix `installSrc` in executors

- internal/codeintel/codenav/internal/lsifstore/metadata_by_position.go
- internal/codeintel/codenav/internal/lsifstore/metadata_by_position_test.go
Fixes #56904 
We should use `LIKE` instead of `=` because the query fragment passed in
has the form `path + "%"` for [pattern matching](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-LIKE).
That said, it seems a bit weird that the path used here is used as a pattern, not as a literal path. When requesting other subfields like hovers, the path is treated literally. 😕 Keeping that as-is for backwards compatibility, and since nobody around has strong opinions on this.
Manually tested this against a fake index generated from scip-go modified
to emit diagnostics. I don't think it's a good idea to create more tech debt
by adding a large SQL file with a bunch of binary strings without clear
reproduction steps, which is what one of the other tests does for hovers.
> codeintel: Fix path-matching query fragment for diagnostics in GraphQL

- internal/search/client/client.go
- internal/search/job/jobutil/job_test.go
- internal/search/types.go
- internal/search/zoekt/query.go
This change is behind a feature flag.
We use Zoekt's query parser when we send a query to Zoekt, bypassing Sourcegraph's current logic for interpreting patterns. Filters should keep working as expected. The most notable difference is probably that Zoekt interprets "foo bar" with an implicit "AND" while Sourcegraph concatenates the two terms.
The intend is to experiment with different
ways of parsing the user query.
Test plan:
CI
> search: use Zoekt parser in frontend

- .buildkite/hooks/pre-exit
The #discuss-dev-experience channel showed up in the logs for a build I was looking at on Buildkite.
n/a
> update reference to #discuss-dev-experience channel

- dev/oci_deps.bzl
Automatically generated PR to update Wolfi base images to the latest hashes.
Built from Buildkite run [#247387](https://buildkite.com/sourcegraph/sourcegraph/builds/247387).
- CI build verifies image functionality
> Auto-update Wolfi base images to latest

- dev/oci_deps.bzl
Automatically generated PR to update Wolfi base images to the latest hashes.
Built from Buildkite run [#247242](https://buildkite.com/sourcegraph/sourcegraph/builds/247242).
CI build verifies image functionality
> Backport - Auto-update Wolfi base images to latest

- cmd/frontend/webhooks/gitlab_webhooks.go
This PR resolves an issue where a timing attack would be possible to retrieve webhook secrets. 
By using a constant-time comparison, regardless of whether the client-provided secret (in the form of a request header `X-Gitlab-Token` is correct or not, the comparison takes the same amount of time.
* Confirm webhooks work as normal.
* CI tests
> use time-safe comparison for gitlab webhook secret

- CHANGELOG.md
- deps.bzl
- go.mod
- go.sum
This updates zoekt to include a fix in ranking.
- https://github.com/sourcegraph/zoekt/commit/8c5bd7de94 Use Go 1.21.2
- https://github.com/sourcegraph/zoekt/commit/659eac980e all: remove deprecated RepoList.Minimal
- https://github.com/sourcegraph/zoekt/commit/f17ff0bac9 scoring: handle scip-ctags kinds
Test Plan: CI
Part of https://github.com/sourcegraph/sourcegraph/issues/57659
> gomod: update zoekt for ranking regression fix

- CHANGELOG.md
We take all the sections except the unreleased new version. This is to help prevent conflicts.
Test Plan: CI
> CHANGELOG: copy-paste from main

- client/web/BUILD.bazel
- client/web/src/repo/RepoContainer.tsx
- client/web/src/repo/RepoLinkPicker.module.scss
- client/web/src/repo/RepoLinkPicker.tsx
This PR simply extends existing UI about repository button/breadcrumb. With new repository picker it should be very easy to switch between different repositories. 
https://github.com/sourcegraph/sourcegraph/assets/18492575/c4f18276-77a2-487c-ab43-0976d9dacd6d
- Check that main repository button is still a link and steal leads to the repository root page
- Check that you can quickly switch repositories with newly added picker UI
> Repo page: Add new repo link picker UI

- dev/ci/internal/ci/changed/diff.go
- dev/ci/internal/ci/operations.go
Follow-up to #57505, remove code that skipped a lot of testing if we detected changes in the jetbrains code. 
CI
> ci: clean edge-case handling code for JB

- CHANGELOG.md
- internal/insights/query/querybuilder/builder_test.go
- internal/search/query/transformer.go
We have some logic that annotates a `content:` node as regex if `patterntype:regex` is set. This allows us to do things like `content:^a:b`, since escaping colons used to be a significant part of how `content:` was used.
However, another significant way `content:` is used is to just search for string literals that would otherwise be interpreted as search syntax. Like `content:"a and b"`. It's a pretty solid heuristic to not treat a quoted string as regex, especially since we now have `/.../`-delimited regex literals, which makes using `content:` for regex patterns largely unnecessary. 
This was causing an issue where a parsing roundtrip for code insights would mangle a query like `content:"TEST" patterntype:regex` to `content:/"TEST"/`, which is obviously not ideal.
Fixes #57323 
Added a …
> Search: do not interpret `content:` as regex if it is quoted

- CHANGELOG.md
- deps.bzl
- go.mod
- go.sum
This updates zoekt to include a fix in ranking.
- 8c5bd7de94 Use Go 1.21.2
- 659eac980e all: remove deprecated RepoList.Minimal
- f17ff0bac9 scoring: handle scip-ctags kinds
Test Plan: CI
Cherry-picked from #57665
> [Backport 5.2] gomod: update zoekt for ranking regression fix

- internal/search/client/client.go
- internal/search/types.go
- internal/search/zoekt/query.go
This change is behind a feature flag.
Our experiments showed that often we miss the top results especially if the keywords are very common. Increasing the limits for `ShardMaxMatchCount` and `TotalMaxMatchCount` improves the results. We use the same limits as we do for "keyword scoring",  which are also identical to Zoekt's default limits. 
I also renamed the internal feature flag from `Keyword` to `UseZoektParser` to avoid confusion with `KeywordScoring`. 
Test plan:
- local testing: ran a couple of searches with `feat=search-new-keyword` and confirmed results are looking promising
- the new limits are identical to [Zoekt's default limits](https://github.com/sourcegraph/zoekt/blob/f17ff0bac96acb444f554e9cf13e04e92bbf1b67/eval.go#L140-L149) and we already use the same limits for keyword …
> search: use 10x defaults if using Zoekt parser

- dev/oci_deps.bzl
This resolves a number of issues due to CVE-2023-4911.
Ran `trivy` on the new image:
```
$ trivy image us.gcr.io/sourcegraph-dev/wolfi-grafana@sha256:1334165966d67b676d0765fb59a732e8ba3f5b03365cd6026a6b42c133de48c6
2023-10-18T14:28:36.722+0200	INFO	Vulnerability scanning is enabled
2023-10-18T14:28:36.722+0200	INFO	Secret scanning is enabled
2023-10-18T14:28:36.722+0200	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-10-18T14:28:36.722+0200	INFO	Please see also https://aquasecurity.github.io/trivy/v0.46/docs/scanner/secret/#recommendation for faster secret detection
2023-10-18T14:28:38.635+0200	INFO	Detected OS: chainguard
2023-10-18T14:28:38.635+0200	INFO	Detecting Chainguard vulnerabilities...
2023-10-18T14:28:38.636+0200	INFO	Number of …
```
> deps: update grafana base image

- internal/database/telemetry_export_store.go
Mistake I caught while testing #57681 (backport of https://github.com/sourcegraph/sourcegraph/pull/57605) - I've updated the backport with the same fix.
Ran various cases locally with `?trace=1` and found the trace attributes
> database/telemetryexport: fixup for metric and trace attribute

- doc/dev/how-to/wolfi/add_update_images.md
Turns out the previous instructions didn't work, as buildkite will rebuild the original commit. "Rebuild this branch" exists but there seems to be a bug and it doesn't pick up the custom envars.
- Docs - check preview
> docs: update instructions for rerunning wolfi buildkite pipeline

- renovate.json
We don't seem to regularly address any of these PRs that are currently open, but Renovate force pushes to the PRs it currently has open. For some of the current branches, we ran what looks like >2500 builds so far. That seems quite wasteful to me.
This makes the workflow explicit: You go to the dashboard, check the checkbox, and get the PR you want to merge in a moment. No more crazy amount of CI jobs generated from pretty much stale PRs.
Also, most of the package specific rules felt outdated so removed them.
Once this is merged, I will close the current stale PRs (can be reopened using the dashboard) and we should ideally see less CI jobs.
Verify that Renovate still works after this PR.
> Require approval to run Renovate

- doc/admin/observability/alerts.md
- doc/admin/observability/dashboards.md
- internal/conf/BUILD.bazel
- internal/conf/client.go
- internal/conf/conf.go
- monitoring/definitions/embeddings.go
- monitoring/definitions/frontend.go
- monitoring/definitions/git_server.go
- monitoring/definitions/repo_updater.go
- monitoring/definitions/searcher.go
- monitoring/definitions/shared/BUILD.bazel
- monitoring/definitions/shared/site_configuration.go
- monitoring/definitions/symbols.go
- monitoring/definitions/worker.go
Preparation for https://docs.google.com/document/d/1rZaH10vJbk5z-8XyIuH9ib3zy5QTJTwire68wXA4Zyg/edit?usp=sharing
This change consists of two parts:
- The configuration client now updates a new metric, metricDurationSinceLastSuccessfulUpdateSeconds. This metric keeps track of the elapsed time since the configuration client was able to last successfully fetch the site configuration. This metric gets updated at various points throughout the continuouslyUpdate loop.
- Various dashboards have been added to the frontend Grafana page under the "Site configuration client update latency" section. One of the dashboards triggers an alert if any configuration client (across all services) hasn't been able to get the site configuration over a 5-minute interval.
I ran the monitoring stack locally to …
> conf: add metric and associated alert if clients fail to update site configuration within 5 minutes

- internal/licensing/BUILD.bazel
- internal/licensing/telemetryexport.go
#57605 disables the new telemetry export in dotcom because it has an older license and does not fulfill any of the other conditions for default enablement. This adds a hardcoded env check on good old `envvar.SourcegraphDotComMode()`, since we already use this to e.g. determine if we can export sensitive metadata.
n/a
> licensing: export events in dotcom mode

- cmd/frontend/graphqlbackend/BUILD.bazel
- cmd/frontend/graphqlbackend/telemetry.go
- cmd/frontend/graphqlbackend/telemetry_test.go
- cmd/frontend/internal/telemetry/resolvers/BUILD.bazel
- cmd/frontend/internal/telemetry/resolvers/telemetrygateway.go
- cmd/frontend/internal/telemetry/resolvers/telemetrygateway_test.go
The `privateMetadata` field, which accepts arbitrary values, was using the wrong JSON type in the backend - it should be `JSONValue`, not `json.RawMessage`, which is another thing entirely. This causes the field to currently be unusable, as the backend type does not match with the GraphQL schema.
This bug does not affect any existing features - the new telemetry export is enabled, but no clients currently use the GraphQL mutation yet (WIP: https://github.com/sourcegraph/cody/pull/1192 - developing this is what caught this). However, it's important that this bug be fixed so that we can start using the new mutation in clients. In the meantime, we can do a clientside check to filter out this broken field (which is optional) until 5.2.2
> graphqlbackend/telemetry: fix privateMetadata type

- cmd/gitserver/internal/vcssyncer/perforce.go
- schema/perforce.schema.json
- schema/schema.go
Closes #57638 
Makes `lookAhead` optional in the Perforce config and default to 2000 if unset.
No real changes here, tests should still pass and such.
> Make lookAhead optional in Perforce connection config

- cmd/frontend/backend/user_emails.go
- cmd/frontend/graphqlbackend/user_emails_test.go
- internal/database/authz.go
Closes #57582 
Fixes an issue where a user's email address could not be deleted while sub-repo permissions are enabled.
Same unit test still asserts that the account was deleted.
> [fix] User email deletion when sub-repo permissions are enabled

- client/browser/src/end-to-end/github.test.ts
- client/browser/src/end-to-end/shared.ts
- client/browser/src/shared/code-hosts/github/codeHost.tsx
- dev/ci/internal/ci/changed/diff.go
- dev/ci/internal/ci/pipeline.go
For reasons unknown I looked at the browser extension. This seems to fix the issues of showing the "open in sourcegraph" button in the file header.
I modified the E2E test to make hovercard testing optional so that we can at least test the toolbar button.
Addendum: I also updated the pipline generate to run browser extension tests when code inside `client/browser/` changes.
Manual testing and reenabling the E2E test for the button specifically.
> bext: Fix SG button in file page header

- internal/uploadstore/config.go
- internal/uploadstore/config_test.go
- internal/uploadstore/s3_client.go
Before this change, we would try to read AWS config files on disk and talk to the metadata server to get a role assumption. That was super unnecessary and meant that Sourcegraph wouldn't start up properly when AWS was misconfigured locally, although we never actually needed to talk to AWS.
Closes https://github.com/sourcegraph/sourcegraph/issues/56599
Verified that embedding jobs which talk to blobstore still work and upload an index properly. Also adjusted tests. Is there something else I could try?
> uploadstore: Don't read AWS config for blobstore backend

- internal/goroutine/periodic.go
- internal/goroutine/periodic_test.go
If the handler function of a periodic goroutine panics, the handler silently dies. I don't see a panic error log, and it is never invoked again.
After discussing this on Slack, we concluded that periodic routines are most often part of a background job and that they shouldn't take down entire services when a single component misbehaves. Instead we treat them as an error in that component, which will surface in logs and the background jobs UI.
See https://sourcegraph.slack.com/archives/C02UC4WUX1Q/p1696960510011339 for the discussion to go with this behavior.
Closes https://github.com/sourcegraph/sourcegraph/issues/56427
Added a test to verify the behavior.
> goroutine: Don't silently stop after panic

- internal/conf/BUILD.bazel
- internal/conf/client.go
- internal/conf/conf.go
In the previous iteration of this functionality (#57682), the lastUpdateTime metric only updated:
1. Prior to the update thread sleeping
2. Immediately after it wakes up from sleep
3. In the small window of time immediately between the lastUpdateTime was set to time.Now (after a successful fetch) and the next instruction (to set the new value of the metric).
All of this means that metric was only infrequently updated. It successfully handles the case where site configuration is unavailable for a bit (e.g repeated fetch failures over a long period of time). However, this also meant that in the happy path case, the last update times were consistently too low (e.x. ~500 nanoseconds) since the metric is never updated during the most time consuming part of the process: actually reaching out …
> conf: enable Prometheus to sample the lastUpdateTime metric concurrently with the actual config update process

- doc/admin/observability/alerts.md
- doc/admin/observability/dashboards.md
- monitoring/definitions/shared/usage_data_pipeline.go
- monitoring/definitions/telemetry.go
Some gentle doc writing during ship coffee break - this adds a bit more detail to the telemetry panel help text, unhides them as they are now available by default, and puts them above the Cloud-specific exporter.
Not that important so not backporting.
n/a
[Preview Link](https://docs.sourcegraph.com/@telemetry-monitoring-improvements)
> monitoring/telemetry: un-hide panels, improve docstrings

- cmd/frontend/graphqlbackend/BUILD.bazel
- cmd/frontend/graphqlbackend/telemetry_test.go
- cmd/frontend/internal/telemetry/resolvers/telemetrygateway.go
- cmd/frontend/internal/telemetry/resolvers/telemetrygateway_test.go
The bug fix in #57719 (backported in #57720) fixed support for the common case, a JSON object `privateMetadata`, but the GraphQL schema describes that any valid JSON should be accepted, and GraphQL validation permits primitives like `string`:
This change improves on #57719 with support for arbitrary types in case they get submitted. Similar to #57719, this is not a customer-affecting bug today as there are no usages, but it is important we land this fix to minimize the impact of this bug as we introduce usages like https://github.com/sourcegraph/cody/pull/1192.
The diff is mostly tests, as the fix is fairly minimal.
> telemetrygateway: support arbitrary privateMetadata types from graphqlbackend

- doc/code_navigation/explanations/uploads.md
- doc/cody/core-concepts/context/context-selection.md
- doc/cody/core-concepts/context/usage-and-limits.md
- doc/cody/core-concepts/embeddings/configure-embeddings.md
- doc/cody/core-concepts/embeddings/embedding-index.md
- doc/cody/core-concepts/embeddings/index.md
- doc/cody/core-concepts/keyword-search.md
There was some post-follow-up feedback on the original [Core Concepts PR](https://github.com/sourcegraph/sourcegraph/pull/57592/) we shipped yesterday. This PR adds the suggested changes.
Docs added
[Preview Link](https://docs.sourcegraph.com/@imp-core-concepts)
> Add follow-up feedback to Core Concepts

- cmd/frontend/internal/httpapi/auth.go
- internal/authz/BUILD.bazel
- internal/authz/header.go
- internal/authz/header_test.go
This reverts commit aa8c53f43b19eb381d5301f0a06104a06d6a0118.
No longer needed.
CI.
> Revert "Add temporary logging to dotcom sudo handler (#56429)"

- wolfi-images/gitserver.yaml
- wolfi-packages/p4-fusion.yaml
We've forked the tool and are now ready to try some of the fixes out in a more production enviroment, so bundling this temporarily from a specific commit from the fork repo.
Next up, I'll open a PR to use the newly generated base image in bazel and add the new `--noBaseCommit` flag to the perforce syncer.
Ran `sg wolfi package p4-fusion locally and it passed`.
> Bump p4-fusion to version of our fork

- dev/sg/internal/sgconf/config.go
When running `sg test <target> extra-arg1 extra-arg2 ...`, the extra args are generally appended to the `<target>` command on a new line, which means the extra args are interpreted by the shell as their own command. The user's intent is for them to be appended to the last command in the `<target>` command string, which this commit achieves by trimming trailing whitespace.
n/a
> fix extra args handling in `sg`

- .pre-commit-config.yaml
Fixes https://github.com/sourcegraph/devx-support/issues/324
Locally tested by adding spaces in those files manually and checking that the new regexp ignores them.
> local: exclude generated files from pre-commit

- dev/sg/internal/wolfi/base-image.go
A recent update to the apko image changed the default workdir, which breaks our `include: ./sourcegraph-base.yaml`. This PR explicitly sets the workdir.
- Tested locally - fixes issue
> sg: fix `sg wolfi image` builds

- dev/gqltest/sub_repo_permissions_test.go
- internal/gqltestutil/repository.go
- testing/BUILD.bazel
This PR makes the sub-repo permissions tests actually functional. This test basically had no chance of ever passing.
Firstly, the user email was completely wrong.
These tests would always auto-skip since the actual time it waits for repos to clone is 5 seconds, not 45 seconds.
Then, the tests themselves are extremely flaky while waiting for a repo to be indexed. I simplified that part and took out the dependence on waiting for a repo to be indexed.
I don't think permissions should depend on whether a repo is indexed or not anyways. But I left that part commented out for now and we can revisit it.
CI actually runs the test and passes
> Make sub-repo permissions integration test functional

- cmd/gitserver/internal/vcssyncer/go_modules.go
- cmd/gitserver/internal/vcssyncer/go_modules_test.go
- cmd/gitserver/internal/vcssyncer/jvm_packages.go
- cmd/gitserver/internal/vcssyncer/jvm_packages_test.go
- cmd/gitserver/internal/vcssyncer/npm_packages.go
- cmd/gitserver/internal/vcssyncer/npm_packages_test.go
- cmd/gitserver/internal/vcssyncer/packages_syncer.go
- cmd/gitserver/internal/vcssyncer/packages_syncer_test.go
- cmd/gitserver/internal/vcssyncer/python_packages.go
- cmd/gitserver/internal/vcssyncer/python_packages_test.go
- cmd/gitserver/internal/vcssyncer/ruby_packages.go
- cmd/gitserver/internal/vcssyncer/rust_packages.go
- cmd/gitserver/internal/vcssyncer/syncer.go
- internal/extsvc/gomodproxy/client.go
- internal/extsvc/gomodproxy/client_test.go
This aligns what we do for Go with what we do for python, writing a zip file to disk. This should prevent big memory spikes when large go modules are downloaded.
Adjusted tests and checked locally that both python and go modules are still cloned correctly.
> gopackages: Don't keep zip file in memory

- CHANGELOG.md
- dev/release/release-config.jsonc
Part of https://github.com/sourcegraph/sourcegraph/issues/57319
Test Plan: n/a
> release: 5.2.2 config and CHANGELOG for 5.2.1

- client/web/src/repo/RepoContainer.tsx
Fixes layout regression from https://github.com/sourcegraph/sourcegraph/pull/57609
https://github.com/sourcegraph/sourcegraph/pull/57609 changed the routes and the layout structure around the root repo page wrapper, it caused that Cody chat UI was rendered inside the nested block with flex-column layout and therefore it grew to 100% height and shrink the blob UI block with content. 
This PR doesn't revert changes from https://github.com/sourcegraph/sourcegraph/pull/57609 but adds repo container render point that we could render something on the top level from nested react routes component. 
| Broken layout | Fixed layout |
| ------ | ------ |
| <img width="1149" alt="Screenshot 2023-10-20 at 14 35 39" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/96824d08-8b8c-4b2d-b41d-3 …
> [Repository Pages]: Fix Cody chat sidebar layout

- .aspect/bazelrc/ci.sourcegraph.bazelrc
- dev/mocha.bzl
- sg.config.yaml
This makes it possible to run e2e tests locally on Linux and use the current $DISPLAY for the non-headless browser.
CI
> un-hardcode $DISPLAY for e2e tests to support non-headless local e2e test running

- client/browser/package.json
- client/web/package.json
- dev/ci/internal/ci/operations.go
- package.json
- sg.config.yaml
To pass multiple ignore patterns to Jest, you need to use `--testPathIgnorePatterns pattern1 --testPathIgnorePatterns pattern2 ...`. Otherwise, `--testPathIgnorePatterns pattern1 pattern2` treats `pattern2` as a test pattern to run, not to ignore.
The consequence of this is that some npm scripts and CI steps were running tests that they didn't need to run.
CI
> fix passing multiple args to jest --testPathIgnorePatterns

- .eslintrc.js
- client/shared/src/codeintel/legacy-extensions/lsif/definition-hover.test.ts
- client/shared/src/codeintel/legacy-extensions/lsif/providers.test.ts
- client/shared/src/codeintel/legacy-extensions/lsif/references.test.ts
- client/shared/src/codeintel/legacy-extensions/search/providers.test.ts
With this rule enabled, saving a file in VS Code often takes 2-5 seconds or longer. With it disabled, saving a file is usually instant.
This rule can be useful, but it's not worth the massive slowdown it causes.
This rule is identified as the biggest culprit in slow eslint analysis by running `TIMING=1 pnpm exec eslint --fix client/web/dev/server/development.server.ts`.
CI
> disable eslint rule etc/no-deprecated for massive file save speedup

- doc/admin/observability/alerts.md
- doc/admin/observability/dashboards.md
- internal/conf/BUILD.bazel
- internal/conf/client.go
- internal/conf/conf.go
- monitoring/definitions/embeddings.go
- monitoring/definitions/frontend.go
- monitoring/definitions/git_server.go
- monitoring/definitions/repo_updater.go
- monitoring/definitions/searcher.go
- monitoring/definitions/shared/BUILD.bazel
- monitoring/definitions/shared/site_configuration.go
- monitoring/definitions/symbols.go
- monitoring/definitions/worker.go
- wolfi-packages/p4-fusion.yaml
This PR cherry picks https://github.com/sourcegraph/sourcegraph/pull/57682 and https://github.com/sourcegraph/sourcegraph/pull/57747 into the 5.2 base branch. These are monitoring improvements that add alerts if our site config fetching process fails. 
CI
> [backport 5.2] conf: add metric and associated alert if clients fail to update site configuration within 5 minutes (#57682)

- client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPolicyPage.tsx
> client: Link to glob syntax for tags/branches/repos

- client/web/src/enterprise/batches/detail/BatchChangeDetailsPage.story.tsx
- client/web/src/enterprise/batches/detail/changesets/ChangesetCheckStatusCell.story.tsx
- client/web/src/enterprise/batches/detail/changesets/ChangesetReviewStatusCell.story.tsx
- client/web/src/enterprise/batches/detail/changesets/ChangesetStatusCell.story.tsx
- client/web/src/enterprise/batches/list/BatchChangeNode.story.tsx
- client/web/src/enterprise/batches/list/BatchChangesListIntro.story.tsx
- client/web/src/enterprise/batches/preview/list/HiddenChangesetApplyPreviewNode.story.tsx
- client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.story.tsx
- client/web/src/enterprise/insights/components/form/field/Field.story.tsx
- client/web/src/enterprise/insights/components/views/card/InsightCard.story.tsx
- client/web/src/enterprise/insights/pages/insights/creation/capture-group/CaptureGroupCreationPage.story.tsx
- client/web/src/enterprise/insights/pages/insights/creation/intro/cards/InsightCards.story.tsx
- client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.story.tsx
- client/web/src/enterprise/insights/pages/landing/dot-com-get-started/components/code-insights-examples-picker/code-insights-examples-slider/CodeInsightsExamplesSlider.story.tsx
- client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-examples/CodeInsightsExamples.story.tsx
- client/web/src/nav/GlobalNavbar.story.tsx
- client/web/src/search/Notepad.story.tsx
- client/web/src/search/results/sidebar/Revisions.story.tsx
- client/wildcard/src/components/Charts/core/components/scroll-box/ScrollBox.story.tsx
- client/wildcard/src/components/Form/TextArea/TextArea.story.tsx
Fixes `tsc --build` errors of the form:
```
error TS2742: The inferred type of 'default' cannot be named without a reference to '.pnpm/@storybook+types@7.4.6/node_modules/@storybook/types'. This is likely not portable. A type annotation is necessary.
```
CI
> fix storybook inferred default export types

- dev/ci/internal/ci/pipeline.go
If the runtype is `ManuallyTriggered` run the same build as if it is a PR
Should it also not do any wolfi stuff? Since that also pushes images 🤔 
* `go build -o pipeline ./dev/ci/gen-pipeline.go`
* `git co _manually_triggered_external/ext_e951611910c8c24c65cabb19c90d25f035f25af9`
```
./pipeline| jq '.steps[] | if has("label") then .label else .steps[] | .label end'
":bazel: Perform bazel prechecks"
":bazel: Tests"
":bazel::snail: Async BackCompat Tests"
":pineapple::lint-roller: Run sg lint"
"Sonarcloud Scan"
```
> ci: let runtype.ManuallyTriggered execute the same build as PR

- sg.config.yaml
Quick follow-up on an issue with docsite being a bit too slow to shut down and causing issues. 
See https://github.com/sourcegraph/devx-support/issues/245 
CI + locally tested.
> sg: disable docsite from default start target

- cmd/frontend/backend/mocks_temp.go
- cmd/frontend/backend/repos.go
- cmd/frontend/backend/repos_vcs_test.go
- cmd/frontend/graphqlbackend/repository_git_refs.go
- cmd/frontend/internal/httpapi/stream_blame.go
- internal/gitserver/commands.go
Attempting to understand when we schedule repo updates, I found a lot of places where we didn't explicitly say that we don't need to ensure the revision, but based on assumptions about data above we can safely do so.
CI still passes.
> gitserver: Reduce instances of EnsureRevision

- cmd/frontend/graphqlbackend/git_commit.go
- cmd/frontend/graphqlbackend/git_ref.go
- cmd/frontend/graphqlbackend/git_tree.go
- cmd/frontend/graphqlbackend/git_tree_entry.go
- cmd/frontend/graphqlbackend/git_tree_entry_test.go
- cmd/frontend/graphqlbackend/git_tree_test.go
- cmd/frontend/graphqlbackend/schema.graphql
I wanted to look into this resolver because it seemed to cause a lot of load on S2 and dotcom. Looking at it, I realize that there are zero tests so I didn't even know what's expected to be returned here. This PR adds a baseline for what should be returned and fixed a bunch of bugs:
- Improper argument validation that could cause panics
- Improperly counted results for `first` argument (still weird with `ancestors: true` but changing that might break things)
- Removed arguments from GraphQL schema that weren't actually respected
- Fix line ending handling in content pagination to return indication if file ended with no newline
- Fix TotalLines for files without a final newline
- Improves performance of line parsing
- Fix ancestors option creating too many results by recursively including …
> Add tests to cover GitTree resolver

- dev/gqltest/sub_repo_permissions_test.go
This still causes delays of up to 45s without adding any value, so let's skip it entirely until we fix it.
CI should tell that it's disabled.
> Fully disable sub repo perms test

- internal/database/access_tokens.go
- internal/licensing/licensing.go
Some instances such as S2 sets the `dev` tag, so it's not a good signal for identifying whether an instance is a local dev instance.
Instead, check whether the license signing private key has been overridden via the env `SOURCEGRAPH_LICENSE_GENERATION_KEY`. If the associated public key matches the hardcoded license signing public key, we can determine that the instance is a real, correctly-licensed instance. If not, it's a dev instance.
- CI
- Manual testing locally
> access tokens: Improve identification of dev instances

- client/web/src/storm/pages/SearchPage/SearchPageFooter.tsx
Updates the footer for the search homepage specific to Sourcegraph.com:
- Removes the 'App' link, which pointed to the app download page.
- Adds a 'Security' link pointing to our Security page on the marketing site.
All links in footer for the SearchPage component were tested with the storybook live preview.
> Update dotcom footer links

- dev/gqltest/sub_repo_permissions_test.go
Those add a lot of additional run time to CI, so disabling them temporarily.
```
2023/10/23 21:31:41 Site admin has been created: gqltest-admin
2023/10/23 21:31:41 License key added and verified
--- FAIL: TestSubRepoPermissionsSymbols (32.90s)
sub_repo_permissions_test.go:93: Creating Alice
sub_repo_permissions_test.go:93: Waiting for user permissions to be synced: Retry timed out in 30s
FAIL
^^^ +++
```
cc @pjlast
CI.
> Skip more perforce tests that regularly time out

- client/web/src/cody/components/ChatUI/ChatUi.module.scss
- client/web/src/cody/components/ChatUI/ChatUi.tsx
- client/web/src/cody/useCodyChat.tsx
- visit the browser and run the following code to fill up the localStorage in the console.
```
var exception;
var repeat = function(str, x) { return new Array(x+1).join(str); };
var too_big = repeat("x", 5*1024*1024/2); // each JS character is 2 bytes
localStorage.clear();
try {
localStorage.setItem("test", too_big);
} catch (e) {
exception = e;
}
```
> [Cody Web] handle localStorage limit exceeded

- doc/dev/background-information/bazel/faq.md
Follow up to https://github.com/sourcegraph/devx-support/issues/339
None - this is a doc change
[Preview Link](https://docs.sourcegraph.com/@wb/bazel/faq-entry)
> bazel: add entry about `--macos_sdk_version`

- client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx
Previously, the JetBrains plugin used two query parameters during onboarding
- `requestFrom=JETBRAINS` to inform the user that they are authenticating for a JetBrains IDE.
- `port=NUMBER`: to indicate which `http://localhost:NUMBER` URL to redirect to after authorization. Without the port number, we don't know how to send the access token to the local IDE.
This PR adds support to encode both parameters together as `requestFrom=JETBRAINS-PORT_NUMBER`. The motivation for this change is to solve https://github.com/sourcegraph/jetbrains/issues/19. We hit on an issue that GitHub SSO was not working when linking directly from the IDE, and we suspect that the root issue is related to the two parameter encoding. If this change does not work as intended, then we plan to revert the diff.
We have …
> JetBrains: Cody: Encoding port in requestFrom param

- dev/check-tokens.sh
- doc/dev/background-information/sg/index.md
- internal/accesstoken/cody_access_token_test.go
Follow-up to https://github.com/sourcegraph/devx-support/issues/338 
This PR introduces a mechanism to tell pre-commit to simply skip a file if it legitimately contains what looks like a token but shouldn't raise an error. 
It also fixes a very dumb bug, previously the list of files returned by `git diff` included files that got deleted, which made the script fail because `grep` obviously couldn't read them.
Typically, this happens when doing a large rebase/merge where one of those legitimate files gets added to the diff. 
For the exception bit: 
- Changed a file containing false positives 
- Staged the changes
- Tried to commit
- Observed the failure because a token is detected 
- Added the comment to signal the exception
- Staged the changes again
- Tried to commit 
- Observed that it …
> local: handle exceptions for token checking pre-commit hook

- internal/licensing/codygateway.go
- internal/licensing/codygateway_test.go
When GPT tag is added, append GPT models to the list of allowed models instead of removing Anthropic ones.
- unit tests updated
- local testing
> Append GPT instead of overriding

- cmd/symbols/ctags-install-alpine.sh
- dev/nix/ctags.nix
- dev/tool_deps.bzl
- wolfi-packages/ctags.yaml
This is the latest release from December 2022. I see important bug fixes between our tagged version and this release.
Test Plan: CI
> all: use universal-ctags v6.0.0

- cmd/symbols/ctags-install-alpine.sh
The format of the archive is slightly different for tags vs commits.
Fix for https://github.com/sourcegraph/sourcegraph/pull/57725
Test Plan: used this version of the script in the docker build for the zoekt repo.
> symbols: use correct directory in ctags-install-alpine.sh

- wolfi-packages/ctags.yaml
I recently bumped the version and did not realise I needed to update the epoch back to 0.
Test Plan: CI
> wolfi-packages: set epoch to 0 for ctags

- doc/dev/how-to/wolfi/add_update_packages.md
- wolfi-packages/ctags.yaml
- Fix epoch for ctags package
- Improve docs for epochs
- CI
[Preview Link](https://docs.sourcegraph.com/@will/ctags-epoch-update)
> Update ctags epoch

- client/web/jest.config.js
- package.json
- pnpm-lock.yaml
The jest-canvas-mock lib is no longer needed. It was erroring because it assumes that `global.jest` is defined, but we can just remove it.
CI
> fix client/web jest tests

- deps.bzl
- go.mod
- go.sum
This has a bunch of ranking tweaks such as upranking markdown files (hence the go-ctags bump). A side effect of this change is that markdown headings will appear in symbol search results. I have a suspicion this won't be that bad in practice and in fact may be useful (eg the symbol sidebar when viewing a markdown file).
If this is a problem, we will likely revert that change in go-ctags and then work on how to only have that information for search ranking.
https://github.com/sourcegraph/zoekt/compare/16e2ff8c98ee...0f21f325cc5d
- https://github.com/sourcegraph/zoekt/commit/f39e6eb573 zoekt: add debug flag to show DebugScore output
- https://github.com/sourcegraph/zoekt/commit/081cd037fd boost graphql types in results
- https://github.com/sourcegraph/zoekt/commit/70f5dd3fcc score: always …
> gomod: update zoekt and go-ctags

- dev/tool_deps.bzl
Landed a PR which updated ctags for everything but bazel, now that CI has built the artifacts this updates it for bazel. Used the output from https://github.com/sourcegraph/sourcegraph/actions/runs/6628151191
Test Plan: copy pasted sha from the CI run above, did not validate other than double check so that may go wrong. Also double checked the artifact name via the listing at https://storage.googleapis.com/universal_ctags
> dev: update ctags in bazel to 6.0.0

- doc/admin/external_service/github.md
This commit adds an expanded explanation on what GitHub Enterprise visibility options represent and what they do.
Doc update. Previewed locally.
[Preview Link](https://docs.sourcegraph.com/@doc/ghe-visibility-explanation)
> Add note on visibility options on GHE

- internal/insights/query/querybuilder/builder_test.go
- internal/insights/query/querybuilder/regexp.go
- internal/insights/query/querybuilder/regexp_test.go
- internal/search/query/parser.go
- internal/search/query/parser_test.go
- internal/search/query/printer.go
- internal/search/query/testdata/TestStringHuman/printer#08.golden
For code insights, we wrap regex regex patterns with slashes when we're rebuilding the query string from the parsed query. However, we cannot just wrap a regex pattern in `/.../` because the query scanning logic respects escape sequences, so anything that would be interpreted as an escape sequence by the query scanner would break the intent of the original regex.
This PR fixes the `StringHuman` method by correctly escaping regex patterns when delimiting them with `/.../`.
[Slack thread](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1698164126691289)
Added a roundtrip test for the roundtrip we can guarantee to be stable. Updated tests that already demonstrated this incorrect behavior. Also manually tested that the bad insights behavior was fixed.
> Search: fix delimiting escape sequences

- doc/dev/background-information/telemetry/index.md
This change moves up the clients section (since most events are created in clients), and adds a link to the VSCode docs being added in https://github.com/sourcegraph/cody/pull/1192 (preview: https://github.com/sourcegraph/cody/blob/vscode-telemetry-v2/vscode/CONTRIBUTING.md#telemetry-events)
Part of https://github.com/sourcegraph/sourcegraph/issues/56813
n/a
[Preview Link](https://docs.sourcegraph.com/@dev-telemetry-recording-docs)
> doc/dev: update event-recording docs for clients

- internal/database/repos.go
- internal/database/schema.json
- internal/database/schema.md
- migrations/frontend/1697750425_topic_column/down.sql
- migrations/frontend/1697750425_topic_column/metadata.yaml
- migrations/frontend/1697750425_topic_column/up.sql
- migrations/frontend/1697752805_index_topics_column/down.sql
- migrations/frontend/1697752805_index_topics_column/metadata.yaml
- migrations/frontend/1697752805_index_topics_column/up.sql
- migrations/frontend/1697754648_drop_old_repo_topic_indexes/down.sql
- migrations/frontend/1697754648_drop_old_repo_topic_indexes/metadata.yaml
- migrations/frontend/1697754648_drop_old_repo_topic_indexes/up.sql
- migrations/frontend/squashed.sql
Previously, querying repos by topic was pretty messy, especially after we added support for gitlab topics. We had to dig down into the metadata, which not particularly nicely structured JSON for github, and we had to do this both for the index and for queries. 
This adds a generated column `topics` which isolates the complexity of extracting the topics from the metadata while maintaining normalization. It replaces the codehost-specific indexes with a single GIN index on that column so that querying for repos with a specific topic is both fast and easy.
@jasonhawkharris updated all the tests for gitlab topics in https://github.com/sourcegraph/sourcegraph/pull/57649, and all the tests pass.
> Clean up querying of repository topics

- internal/completions/client/openai/openai.go
- internal/conf/computed.go
- internal/conf/computed_test.go
Adds experimental OpenAI autocomplete support **_only for BYOK configurations_**.  This brings the changes from the Azure OpenAI provider to OpenAI provider.  Additional it updates the default autocomplete model for OpenAI to be `gpt-3.5-turbo-instruct`  as this model continues to support the non-chat based completions api.  
part of https://github.com/sourcegraph/sourcegraph/issues/57724
Verified Chat & autocomplete work in VS Code
Verified Cody web works
Ran client completions and benchmark tooling.
> Cody: Experimental OpenAI autocomplete support

- client/wildcard/src/components/Card/Card.module.scss
- client/wildcard/src/components/Combobox/MultiCombobox.module.scss
- client/wildcard/src/components/Combobox/MultiCombobox.story.tsx
Similar to the infamous https://github.com/sourcegraph/sourcegraph/issues/42217 CSS order problem in webpack. 
Recent migration to esbuild by default caused/revealed the old problem with CSS order over global and module styles. In this particular case CSS global class `.form-control` overrided some local MultiCombox input styles. This PR simply increases cascade speciality but I think general solution here would be wrap global styles with CSS `@layers` and this would give us more control over CSS cascade order (meaning we don't need to control order of files and operate order of cascade instead) 
| -------- | -------- |
| <img width="1149" alt="Screenshot 2023-10-25 at 16 10 22" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/2aa40df3-4581-4aaa-995f-1f844 …
> [Wildcard]: Fix MultiCombobox Input UI

- client/web/src/featureFlags/featureFlags.ts
- internal/search/client/client.go
With the recent changes in how feature flags work in the web app we now need the flags listed in the allow list for per request (via feat=) overrides.
Test Plan: CI
> web: add all search feature flags to client side

- .github/workflows/scip-typescript.yml
Fixes the scip-typescript workflow in GitHub Actions
CI
> bump pnpm version in scip-typescript workflow

- cmd/gitserver/internal/cleanup.go
Two reasons:
- The janitor process on dotcom takes a very long time so that we often don't get to this critical stage before gitserver restarts for the next rollout
- The repos we're about to delete are first optimized, which is wasted effort
CI, just swapped a job order for dotcom.
> dotcom: Run disk janitor before repo cleanup

- client/web/src/repo/settings/RepoSettingsIndexPage.tsx
During a recent support issue, some engineers were confused by the wording, and thought the commit SHA and skipped files related to the in-progress indexing job. In reality, they are describing the last successful job run. This change tries to clarify the wording a bit.
Visual inspection.
Before (screenshot from customer instance):
After (from local testing):
If an index job is running it will say "indexing in progress" instead of "up to date".
> Search: clarify wording for indexing job progress

- dev/managedservicesplatform/internal/stack/cloudrun/adapters.go
- dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
- dev/managedservicesplatform/spec/environment.go
Support variable substitution from terraform runtime information, see test plan for use cases.
> I know we already have `GOOGLE_CLOUD_PROJECT`, but this can unlock more use cases
spec
```
env:
CAPI_PROJECT: "{{ .ProjectID }}"
CAPI_DASHBOARD_EXTERNAL_URL: "https://{{ .ServiceDnsName }}"
```
`terraform plan`
```
Terraform will perform the following actions:
~ resource "google_cloud_run_v2_service" "cloudrun" {
id                      = "projects/cloud-ops-dashboard-prod-245f/locations/us-central1/services/cloud-ops-dashboard"
name                    = "cloud-ops-dashboard"
~ template {
~ containers {
name    = "cloud-ops-dashboard"
~ env {
name  = "CAPI_PROJECT"
~ value = "cloud-ops-dashboard-prod-245f" -> "ABC_cloud-ops-dashboard-prod-245f"
}
}
}
}
```
> msp: support templating in service env var

- .github/workflows/sg-binary-release.yml
`sg msp` is hidden behind the build tag `msp`.
I would like to start using `sg msp` in CD pipeline. Being able to download the release from the internet would make my life easier.
merged and 👀 
tested commands locally, `/sg-msp_darwin_arm64 msp -h` works
> ci: release sg msp build

- client/web/dev/esbuild/config.ts
- client/web/dev/utils/environment-config.ts
For local dev, you can set the env var `DEV_WEB_BUILDER_NO_SPLITTING` to disable code splitting in the esbuild web build. This produces a large single bundle, but it is ~25% faster to produce and means that page navigations need not fetch additional chunks (which incurs an esbuild full rebuild). The downside is that the bundle is quite large (~20MB), but parsing does not seem to be noticeably slow on my machine. So, this is an overall speedup for local dev.
CI
> env var DEV_WEB_BUILDER_NO_SPLITTING to disable code splitting

- .tool-versions
- BUILD.bazel
- WORKSPACE
- client/browser/BUILD.bazel
- client/browser/config/BUILD.bazel
- client/build-config/BUILD.bazel
- client/web/src/org/settings/profile/OrgSettingsProfilePage.tsx
- package.json
- pnpm-lock.yaml
- wolfi-images/cloud-mi2.yaml
Going from version 18 to 20 means we get better perf and the built-in WebCrypto API, which makes a crypto test polyfill no longer needed.
CI
> upgrade nodejs to 20.8

- .github/workflows/licenses-check.yml
Update all the versions in license_check workflow, especially pnpm otherwise license_finder fails
Fixed https://github.com/sourcegraph/devx-support/issues/348
Check that the action runs without quiting
> license check: update versions used by workflow

- cmd/frontend/graphqlbackend/user.go
- cmd/frontend/graphqlbackend/users_test.go
This makes sure we can only call `CreatePassword` from an actual user session. Now we prevent it from being set using an access token.
Closes https://github.com/sourcegraph/security-issues/issues/353.
- Added unittests
- Confirmed in GraphQL console it works with session cookie
- Use `curl` command below to verify
```
curl \     
-H 'Authorization: token [your_test_token]' \
-d '{"query":"mutation { createPassword(newPassword:\"foobazbar123!\") { alwaysNil } }"}' \
https://sourcegraph.test:3443/.api/graphql
{"errors":[{"message":"only allowed from user session","path":["createPassword"]}],"data":{"createPassword":null}
```
> graphql: only allow CreatePassword from session cookie

- dev/sg/internal/run/helpers.go
- dev/sg/internal/run/run.go
- dev/sg/sg_start_test.go
This irritated me and I also think it's confusing to see the output twice, once in red and once in default color.
The "easy" fix would be to change the underlying error and don't include the output, but it turns out that `run.InRoot` is used in quite a few things: `sg ci` helpers, migration helpers, etc. And I don't want to suddenly stop output from appearing where it previously did.
So I special-case the case where we *do* have the output easily available, which is where we check for the `installErr`.
It's a bit of a band-aid and ideally we'd fix the underlying issue, but I also like errors having the output included by default because it's helpful.
- Uninstall nodejs version, run `go run ./dev/sg start --only web`
> sg: don't print output twice if build fails

- cmd/frontend/graphqlbackend/preview_repository_comparison.go
- cmd/frontend/graphqlbackend/repository_comparison.go
This is a small perf improvement for a commit's diff view. There is more we should do here, but this improved the speed of the example I was looking at. 
Contributes to fixing https://github.com/sourcegraph/sourcegraph/issues/57833
Existing tests and manual test.
> Commit view: speed up repository comparison

- client/web/src/featureFlags/FeatureFlagsProvider.tsx
I've changed this code a couple of times between returning an object and a map and it seems I left it in a bad state (`overrideFeatureFlags` returns a map).
Performing a search that includes `feat=search-debug` shows debug information.
> web: Fix syncing feature flag overrides from URL

- client/web/src/repo/blob/own/HistoryAndOwnBar.tsx
This removes the `Show history` link on the latest commit line, which is a duplicate of the toggle button in the actions bar. https://github.com/sourcegraph/sourcegraph/issues/57702 will make it easier to find the history toggle, but I don't think we need to block on that PR to merge this change.
Fixes https://github.com/sourcegraph/sourcegraph/issues/57568
See screenshot.
> Blob view: remove duplicate show history

- client/web/src/repo/tree/TreePageContent.tsx
Loading the contributors for a repo can take quite a bit of time. Turns out, most of this time was spent fetching the first commit for each contributor. We don't actually use that data, so this removes that from the GraphQL query, which cuts the example I was looking at from 900ms to 300ms. 
Fixes [#57826](https://github.com/sourcegraph/sourcegraph/issues/57826)
It builds without that info. And it speeds it up. Manually checked that there is no visible change.
> Tree view: speed up contributors query

- cmd/frontend/internal/completions/resolvers/BUILD.bazel
- cmd/frontend/internal/completions/resolvers/resolver.go
- internal/completions/client/BUILD.bazel
- internal/completions/client/client.go
- internal/completions/client/observe.go
- internal/completions/httpapi/BUILD.bazel
- internal/completions/httpapi/chat.go
- internal/completions/httpapi/codecompletion.go
- internal/completions/httpapi/handler.go
- internal/completions/types/types.go
This change adds backend telemetry events, using the new telemetry system, on completions clients. In conjunction with https://github.com/sourcegraph/sourcegraph/pull/57774 and Telemetry Export rollout in 5.2.1, this can get us some initial events to start tying completions events to individual interactions as discussed in [Gateway to eventlogger mapping](https://docs.google.com/document/d/1V5MK_SI7OnvzVSi1AnhuX5RzvIZTNIZ3MdHACTBz0tE/edit).
(cherry picked from commit 1a7b408c4317b8839481fbdd3a0f1d58767d61e3 from https://github.com/sourcegraph/sourcegraph/pull/57775)
CI
> [Backport 5.2] completions: add backend events on clients and handlers (#57775)

- .prettierignore
- client/shared/dev/BUILD.bazel
- client/shared/dev/generateGraphQlOperations.ts
- client/web/src/enterprise/insights/admin-ui/components/job-actions/CodeInsightsJobsActions.tsx
Overall, this cuts the time to generate `graphql-operations.ts` files by 50% (from ~4.6s to ~2.3s).
- skip graphql-codegen step for files that lack "gql`": Also fixes an issue in a tsx file that started to throw an error with this filtering step.
- do not run prettier for graphql-operations.ts files: It is not needed because they are not checked in and they can be prettierignored, which can save a lot of time when rebuilding these graphql-operations.ts files.
CI, and manually confirmed that the graphql-operations.ts files that are emitted do not differ after these changes (except for the file mentioned in the bugfix above)
> faster graphql-operations codegen step

- internal/completions/client/fireworks/fireworks.go
- internal/completions/types/types.go
- schema/site.schema.json
Forward the log probabilities from the Fireworks API to the client. This will enable us to use the log probabilities as a signal for completions.
```
-    "provider": "sourcegraph",
+    "provider": "fireworks",
-    "accessToken": "<CODE GATEAWY TOKEN>",
+    "accessToken": "<FIREWORKS API TOKEN",
-    "endpoint": "https://cody-gateway.sgdev.org"
+    "endpoint": "https://api.fireworks.ai/inference/v1/completions",
```
> Pass through logprobs from completions model

- client/browser/BUILD.bazel
While working on https://github.com/sourcegraph/devx-support/issues/351 which relates to https://github.com/sourcegraph/sourcegraph/pull/57886 we ended up with @burmudar finding out the following: 
- `bazel test //client/browser:test` is not sandboxed and doesn't have the `patch_node_fs` set to True, on both @sqs's branch and on `main`. 
- Because how NodeJS ecosystem works, the [rules behind this](https://docs.aspect.build/rulesets/aspect_rules_js/docs/js_binary/#copy_data_to_bin-1) are copying files in the output tree to account for peculiarities with the load mechanism that NodeJS uses. 
- Bazel output tree is not cleaned across builds, which is normal, that's where you store the outputs, rules are not supposed to read from here. 
- Because both the new and old implementations of the …
> bzl: re-enable sandbox for browser tests

- cmd/frontend/graphqlbackend/user_usage_stats.go
- cmd/frontend/hubspot/events.go
- cmd/frontend/hubspot/hubspot.go
- cmd/frontend/hubspot/hubspotutil/hubspotutil.go
Send a custom behavioural CodyInstall event to HubSpot using the V3 API.
The previous attempt tried to send the new event using the same old API which doesn't work.
Tested locally using API Key.
```graphql
mutation {
logEvents(
events: [{event: "CodyInstalled", url: "https://sourcegraph.com/cody", source: WEB, userCookieID: "71dc375b-c5bb-408e-b1b9-0e6383b3b2b8", publicArgument: "{\"extensionDetails\": { \"ide\": \"vscode\"}}"}]
) {
alwaysNil
__typename
}
}
```
> Sent custom CodyInstall event to HubSpot

- cmd/searcher/internal/search/hybrid.go
- cmd/searcher/internal/search/search.go
Some of the calls done by this code returns very obtuse errors, so lets mix in some more context. Additionally we add in an extra error/debug log at the end of execution which includes the finalState, which will likely be very helpful when debugging errors.
Test Plan: CI
> searcher: wrap all errors returned in hybrid search path

- testing/BUILD.bazel
In the `//testing:codeintel_integration_test_local` target.
Run test target locally as this target is not meant to be run on CI
> build: fixup typo in BUILD file no-sandbox tag

- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
- cmd/cody-gateway/shared/config.go
- internal/completions/httpapi/codecompletion.go
Adds a few new supported model strings:
- `anthropic/claude-instant-1.2-cyan` c.f. https://sourcegraph.slack.com/archives/C04D0GRD1GB/p1698458381224209?thread_ts=1698383238.134869&cid=C04D0GRD1GB
- `fireworks/accounts/fireworks/models/llama-v2-34b-code-instruct` and `fireworks/accounts/fireworks/models/mistral-7b-instruct-4k` c.f. https://app.fireworks.ai/models/fireworks/mistral-7b-instruct-4k and https://app.fireworks.ai/models/fireworks/llama-v2-34b-code-instruct
- Only adding a new code completion model string
> Add support for new Fireworks and Anthropic models

- internal/completions/client/openai/openai.go
- internal/conf/computed.go
- internal/conf/computed_test.go
Adds experimental OpenAI autocomplete support **_only for BYOK configurations_**.  This brings the changes from the Azure OpenAI provider to OpenAI provider.  Additional it updates the default autocomplete model for OpenAI to be `gpt-3.5-turbo-instruct`  as this model continues to support the non-chat based completions api.  
part of https://github.com/sourcegraph/sourcegraph/issues/57724
Verified Chat & autocomplete work in VS Code
Verified Cody web works
Ran client completions and benchmark tooling.
> [Backport 5.2] Cody: Experimental OpenAI autocomplete support (#57872)

- docker-images/syntax-highlighter/crates/scip-syntax/queries/javascript/scip-tags.scm
- docker-images/syntax-highlighter/crates/scip-syntax/queries/rust/scip-tags.scm
- docker-images/syntax-highlighter/crates/scip-syntax/queries/typescript/scip-tags.scm
- docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__ctags__test__ctags_runner_basic.snap
- docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_ctags-empty-scope.rs.snap
- docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.js.snap
- docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.ts.snap
- docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_javascript-object.js.snap
- docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_scopes.rs.snap
- docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__tags_snapshot_ctags-empty-scope.rs.snap
- docker-images/syntax-highlighter/crates/scip-syntax/src/ts_scip.rs
- docker-images/syntax-highlighter/crates/scip-syntax/testdata/ctags-empty-scope.rs
Add scip-ctags kinds for js, ts, and rust; I can improve Zig another time (it would require a lot of new query work).
Snapshot tests.
> Add scip-ctags kinds for js, ts, and rust

- client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts
When go marshals a `nil` slice to JSON, it marshals as `null`. However, unlike in go, null is not treated as an empty slice in javascript. This was causing type errors that showed up in the UI.
Rather than fixing this on the backend side of things (which would be fragile, since it's very conventional to use a nil slice to mean empty slice in go), this makes the field nullable in the typescript type.
Fixes #57902 
No longer seeing the type error in the UI. New tests feel unnecessary since this is just making a type match what the backend actually returns.
> References pane: fix typing on symbols return type

- internal/database/migration/multiversion/drift.go
Quick fix to correct the doc string in the drift output
> 3)Doc link  for resolving schema diffs output to the logs is incorrect i.e https://docs.sourcegraph.com/admin/how-to/manual_database_migrations#drift
The correct link is https://docs.sourcegraph.com/admin/updates/migrator/schema-drift
Minor change CI
> change string to correct doc link

- cmd/frontend/internal/cli/http.go
- cmd/frontend/internal/httpapi/BUILD.bazel
- cmd/frontend/internal/httpapi/api_test.go
- cmd/frontend/internal/httpapi/httpapi.go
- cmd/frontend/internal/httpapi/repo_shield_test.go
- cmd/frontend/internal/httpapi/router/BUILD.bazel
- cmd/frontend/internal/httpapi/router/router.go
This does the same thing that I did for the UI router:
1. Move the route definitions to the place where the handlers are defined.
2. Keep the naming of some endpoints around when they're referenced.
Once I also do this for the internal handler, I can clean up more routes.
- Tested locally by booting up `sg start` and clicking around and using API
- Kicked-off `sg ci main-dry-run`: https://buildkite.com/sourcegraph/sourcegraph/builds/249248
> httpapi: put router for external API in same place as handler

- dev/tool_deps.bzl
- doc/cli/references/code-intel/upload.md
We bumped src-cli in `internal/src-cli/consts.go` but not in the Bazel defs. This PR corrects it.
> bzl: bump src-cli to 5.2.0

- deps.bzl
- go.mod
- go.sum
This version contains a fix for a ranking regression we experienced using SCIP
ctags:
* https://github.com/sourcegraph/zoekt/pull/674
It replaces our earlier workaround (https://github.com/sourcegraph/zoekt/pull/655) with a more robust fix.
Relates to sourcegraph/sourcegraph#57659
Sourcegraph and Zoekt CI
> Bump Zoekt for ctags ranking fix

- dev/nix/nodejs.nix
- flake.lock
- flake.nix
- shell.nix
Upgrade nodejs and pnpm to match what the rest of the repo is using.
We don't fetch typescript from npm registry since 5.2.2 has a missing `package-lock.json`. Fortunately `nixpkgs-unstable` has 5.2.2.
Tested locally
```
bash-5.2$ pnpm --version
8.9.2
bash-5.2$ node --version
v20.8.0
bash-5.2$ tsc --version
Version 5.2.2
bash-5.2$ exit
```
> nix: upgrade node and pnpm

- doc/code_search/explanations/features.md
The PR fixes the experimental label badge in the heading. 
- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1698768999710409
Docs added
[Preview Link](https://docs.sourcegraph.com/@fix-exp-badge)
> Fix experimental badge in Code Search Features docs

- dev/managedservicesplatform/spec/environment.go
follow up https://github.com/sourcegraph/sourcegraph/pull/57953
introduce a new deployment type `subscription` to subscribe for image tags from container registry
https://github.com/sourcegraph/managed-services/pull/29
> msp: add subscription deploy type

- client/shared/src/search/query/scanner.ts
- client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
`SyntaxHighlightedSearchQuery` does not render regexp ranges, such as `[a-z]`, correctly. 
input query: `context:global ghp_[A-Za-z0-9]{36} r:.* rev:*refs/heads/* patterntype:regexp`
Search jobs page:
I couldn't find a simple fix so I decided to replace it with a read-only CodeMirror editor.
I want to get this into the upcoming patch. However, we use `SyntaxHighlightedSearchQuery` in a lot of places and it seems risky to replace the component without baking it a bit on s2. Hence I only fix this bug for Search Jobs.
- This is how it looks locally after the fix:
> search jobs: fix query highlighting

- internal/completions/client/awsbedrock/bedrock.go
GA documentation for AWS Bedrock lists [a different endpoint](https://docs.aws.amazon.com/general/latest/gr/bedrock.html) for InvokeModel & InvokeModelWithResponseStream this updates the endpoint building logic to match the documentation.
Manually tested Autocomplete & chat against internal Bedrock instance
> Cody: Update Bedrock endpoint to match documentation

- deps.bzl
- go.mod
- go.sum
We create a new release branch in zoekt called "sourcegraph-5.2". It is based off the version in the sourcegraph 5.2 release branch. We then cherry-picked 3 commits from main into it. This is to avoid the large number of changes we are making, but including the fixes we want.
https://github.com/sourcegraph/zoekt/compare/f17ff0bac96a...379ed5a0bb34
- https://github.com/sourcegraph/zoekt/commit/39e647cabf C-tags: use type def instead of type alias
- https://github.com/sourcegraph/zoekt/commit/ebf3aedaee Ranking: standardize ctags kind names before scoring
- https://github.com/sourcegraph/zoekt/commit/379ed5a0bb Debug: make indexing timeout configurable
This update was done by running "./dev/zoekt/update sourcegraph-5.2"
Note: we can't do a normal backport due to wanting to run a different …
> gomod: update zoekt to 5.2 release branch

- internal/workerutil/dbworker/store/store.go
Not sure why go's format string linter isn't picking this up.
Test Plan: n/a
> dbworker: include recordID in fetchDebugInformationForJob error

- internal/authz/providers/github/BUILD.bazel
- internal/authz/providers/github/github_test.go
I've observed a few times but ultimately this is diffcult to catch in the act but here is one data point where the sorting order isn't stable like in this [build](https://buildkite.com/sourcegraph/sourcegraph/builds/249376#018b89e8-b855-4663-939a-dc8c39847dfb) for this [test](https://buildkiteartifacts.com/ce5a7366-33fc-414f-aff4-ac5542f2233f/1c544f6a-e12e-42d5-bfff-b3c95f10496d/018b89e6-f28c-44e7-9372-1e5289ef101a/018b89e8-b855-4663-939a-dc8c39847dfb/_bk_artefacts_2974006606/test.log?response-content-type=text%2Fplain&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQPCP3C7L3ZLZ2PFG%2F20231101%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231101T084636Z&X-Amz-Expires=600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjENf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIC6ktEz1Ia0hxBZsrZ7jLG …
> github test: make the sorting more stable in test

- doc/api/stream_api/index.md
`--data-urlencode` was listed twice in example.
Docs: see change in page
[Preview Link](https://docs.sourcegraph.com/@peterguy/docs-fix-stream-api-example)
> remove duplicate option in streams API example

- client/web/BUILD.bazel
- client/web/src/repo/RepoLinkPicker.tsx
- client/web/src/repo/constants.ts
- client/web/src/repo/utils.test.ts
- client/web/src/repo/utils.tsx
Before, the RepoLinkPicker was initializing the first set of results by running a query with a value of `""`. While this doesn't affect small instances much, large instances, like dotcom, are affected by very slow initial loading times.  
Now, it's faster. 
This also fixes a bug where users without site-admin privileges were unable to use the feature due to getting a bunch of errors when clicking the dropdown instead of repo names. 
- Tested performance on local dev environment - **Negligible/No observable improvement**
- Tested performance on `k8s.sgdev.org` - **Negligible improvement**
- Tested performance on `dotcom` - **Markedly faster than before**
- Add unit test
> Code Navigation: optimize repo link picker

- .prettierignore
This line was removed in #57365 but it seems it causes `sg lint --fix format` to format all the generated JS and JSON files inside ui/assets/ and is thus rather slow. I believe this folder can be safely ignored.
👀
> Add back 'ui/assets/' to .prettierignore

- cmd/cody-gateway/internal/httpapi/embeddings/handler.go
Records the raw character count of embeddings input, similar to how we record raw character counts for the completions handler.
n/a
> cody-gateway/embeddings: record input_character_count

- cmd/frontend/graphqlbackend/git_commits.go
When fetching the information about the commit that modified a file, we use an `ancestors` query that is filtered to the file name. This is a paginated interface, so we always request n+1 items so we know whether there is a next page. 
However, the extra requested commit can actually be quite expensive to fetch, particularly in the relatively common case that a file has only been modified in one commit: the one that created it. In that case, we have to iterate over the entire history of the repository to look for a commit that doesn't exist to produce information about a next page that will never be fetched. 
The ideal solution here would be to only fetch n+1 if the `hasNextPage` field of the resolver is requested. Unfortunately, our GraphQL package [still doesn't support querying for …
> Perf: optimize fetching last file commit

- cmd/gitserver/internal/BUILD.bazel
- cmd/gitserver/internal/ensurerevision.go
- cmd/gitserver/internal/server.go
I would like to know how many calls we actually make, and with what outcome this function returns so added a prom metric for it. This is for research purposes on how gitserver is used today, we can remove the metric later, or add it to a dashboard if it turns out to be super valuable for debugging.
Existing tests should discover when the metric broke something.
> gitserver: Add observability around ensureRevision

- dev/ci/internal/ci/BUILD.bazel
- dev/ci/internal/ci/bazel_operations.go
- dev/linters/depguard/depguard.go
- dev/sg/ci/BUILD.bazel
- dev/sg/ci/subcommands.go
- dev/sg/internal/wolfi/BUILD.bazel
- dev/sg/internal/wolfi/update_hashes.go
- dev/sg/sg_app.go
- internal/codycontext/BUILD.bazel
- internal/codycontext/context.go
- internal/database/migration/drift/BUILD.bazel
- internal/database/migration/drift/util_search.go
I was randomly browsing this file and saw this mistake
CI
> bazel: fix depgard regexp typo

- dev/ci/images/images.go
Qdrant was missing, causing some incorrect behavior when updating images.
It got me another step closer to a clean release.
> Release: add qdrant to images list

- client/shared/src/components/CodeMirrorEditor.tsx
- client/web/BUILD.bazel
- client/web/src/repo/blob/CodeMirrorBlob.tsx
- client/web/src/repo/blob/codemirror/eof.ts
- client/web/src/repo/blob/codemirror/links.ts
- Move the end-of-file decoration extension into its own module
- Remove blobInfo dependency of `buildLinks` extension (renamed to `linkify`)
- Use `useCompartment` for blobProps and wrap settings to simplify component structure.
- Remove theme extension. We are using our own CSS rules for dark/light theme styling.
Manual testing:
- Last line is hidden when empty
- Links are clickable
> blob: Simplify/cleanup some extension usage

- client/shared/dev/generateGraphQlOperations.ts
- client/web-sveltekit/src/routes/UserMenu.svelte
- client/web-sveltekit/vite.config.ts
PR #57963 moved files from JS to TS, which breaks this projects build process. I tried to use `ts-node` as well but couldn't get it to work. Inlining the configuration seems to be the easiest way atm.
`pnpm dev` runs without error.
> svelte: Fix build process

- cmd/symbols/squirrel/language-file-extensions.json
- cmd/symbols/squirrel/util.go
While investigating https://github.com/sourcegraph/sourcegraph/issues/57974, I noticed
that the list of file extensions in the Squirrel code for C and C++ is partly wrong
and partly incomplete. So this PR fixes that. Specifically:
There are a bunch of uppercase extensions in use:
- `.C`, `.CC` and so on -- confirmed via Sourcegraph.com using a `count:all` query.
- The `.pc` and `.pcc` files are just wrong. `pc` is most common for pkg-config files,
and `pcc` is for PCGen files.
~We don't add a general lower-casing step before comparing the extension as it is
not common in other languages to have uppercase file extensions.~
~However, we could do that, since the current list of extensions is all lower-case.~
Ideally, https://github.com/sourcegraph/sourcegraph/issues/56379 would've been
fixed …
> squirrel: Do case-insensitive comparison of file extensions

- client/web/src/codeintel/ReferencesPanel.tsx
Following up from Slack thread: https://sourcegraph.slack.com/archives/C01C3NCGD40/p1698900105171149
n/a
> client: Remove needless useMemo calls in ref panel code

- sg.config.yaml
Following-up on Dogfood decommissioning, this swaps the target for `sg start web-standalone` to S2. 
Ran the command locally, it worked.
> sg: web-standalone now points at S2

- internal/cmd/search-blitz/main.go
This increases the poll interval of Search Blitz from 1m to 5m. We are currently running about 80 queries per minute, which is a non-insignificant amount of load on sourcegraph.com. This should cut down the load significantly while keeping a decent granularity for our charts.
[Slack thread](https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1698962313071229)
N/A
> Search blitz: increase poll interval to 5m

- docker-images/syntax-highlighter/Cargo.Bazel.lock
- docker-images/syntax-highlighter/Cargo.lock
- docker-images/syntax-highlighter/Cargo.toml
This pulls in https://github.com/sourcegraph/scip/pull/217 which I need for https://github.com/sourcegraph/sourcegraph/pull/58082 but I wanted to keep that one focused on the change.
- N/A
> syntax-highlighter: update scip to version 0.3.2

- cmd/frontend/graphqlbackend/BUILD.bazel
- cmd/frontend/graphqlbackend/git_commit.go
- cmd/frontend/graphqlbackend/git_tree_history.go
- cmd/frontend/graphqlbackend/git_tree_test.go
- cmd/frontend/graphqlbackend/schema.graphql
- cmd/gitserver/internal/integration_tests/archivereader_test.go
This adds a new `history` method to the `TreeEntry` GraphQL object. It returns the history of that entry as a set of `TreeEntry` nodes. This is to suport #57827. Previously, fetching the history would take a separate GraphQL request entry.
A sticky design choice was whether to make `history` return a connection of `TreeEntry` or `Commit` objects. I think that the choice to return `TreeEntry` is slightly more correct even though it requires another layer of querying to get to the underlying commit for two reasons:
1) If we just return the commits that modified the tree, if we wanted to fetch the content at the historical revision (say, to fetch a diff), we'd have to make a followup query for the path at the returned commit instead of just adding a field to the first query.
2) It makes it …
> GraphQL: add history to TreeEntry

- client/web/src/repo/commits/GitCommitNode.module.scss
- client/web/src/repo/commits/GitCommitNodeTableRow.tsx
This improves the UI when expanding commit messages by replacing the expand button with a toggleable caret icon. It cleans up the expanded view by adding padding and other styles.
Before: 
https://github.com/sourcegraph/sourcegraph/assets/62355966/00635e6a-66fe-4f2b-973a-5f51fb090163
After: 
https://github.com/sourcegraph/sourcegraph/assets/62355966/12c65d05-bf63-421c-8378-ababc11c97b3
Manual testing on small, medium and large instances
> Code Navigation: Commit expand clean up

- client/browser/src/shared/code-hosts/gitlab/codeHost.test.ts
Giving a little more context where this test fails with a fake error. Instead of
CI
> codehost tests: improve error description

- .prettierignore
Found prettier was linting files from `package/` which contains node_modules like js files
Local and CI
> prettier: add package to prettier ignore

- client/shared/src/codeintel/legacy-extensions/util/api.ts
- cmd/symbols/internal/api/handler_cgo.go
- cmd/symbols/squirrel/http_handlers.go
- cmd/symbols/squirrel/util.go
Cherry-pick #58030 to release branch.
Fixes https://github.com/sourcegraph/sourcegraph/issues/57974
Same as #58030
> [Backport 5.2] fix: Check for known Squirrel errors inside GraphQL responses (#58030)

- client/web/src/repo/blob/codemirror/blame-decorations.tsx
The hunks should be compared by identity, not revision. I think I was exploring comparing by revision in order to avoid showing the same decoration for consecutive hunks, but that had other UI issues.
> blob: Fix missing blame decoration

- WORKSPACE
This bumps the version of `hermetic_cc_toolchain` to v2.1.2 to fix a build issue I ran into when running `sg start otel` after upgrading to Sonoma.
`sg start otel` no longer fails.
> Bump hermetic_cc_toolchain to v2.1.2

- cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
This adds the set of allowed models to the `GET /v1/limits` API endpoint for feature detection.
Verified locally that the endpoint still works and that model names are returned correctly.
> codygateway: Expose allowed models in limiter status endpoint

- cmd/symbols/squirrel/BUILD.bazel
@varungandhi-src's [PR](https://github.com/sourcegraph/sourcegraph/pull/58143) fixes the `go test` part of the issues with Starlark test data, and this PR makes it so Bazel properly sees those files.
The problem was happening exactly as diagnosed by @burmudar over [slack](https://sourcegraph.slack.com/archives/C04MYFW01NV/p1699344515274959?thread_ts=1699334502.046179&cid=C04MYFW01NV). 
```
//cmd/symbols/squirrel:squirrel_test                                     PASSED in 3.5s
```
```
~/work/other S jh/fix-squirrel-build $ bazel cquery '//cmd/symbols/squirrel:*' --output=files
INFO: Analyzed 28 targets (1 packages loaded, 29 targets configured).
INFO: Found 28 targets...
cmd/symbols/squirrel/test_repos/starlark/BUILD
cmd/symbols/squirrel/test_repos/starlark/BUILD.bazel …
```
> bzl: add missing test data for squirrel test 

- dev/codeintel-qa/cmd/clear/BUILD.bazel
- dev/codeintel-qa/cmd/clone-and-index/BUILD.bazel
- dev/codeintel-qa/cmd/download/BUILD.bazel
- dev/codeintel-qa/cmd/query/BUILD.bazel
- dev/codeintel-qa/cmd/upload-gcs/BUILD.bazel
- dev/codeintel-qa/cmd/upload/BUILD.bazel
- internal/cmd/init-sg/BUILD.bazel
I was unhappy with https://github.com/sourcegraph/sourcegraph/pull/58151 and wondered if the targets weren't pulled in because nothing actually tells Bazel to not build them when using `...`. Turned out that's right, that's how they got picked up. 
So tagging them with `manual` doesn't affect the original case, which is when you want to run e2e tests locally, because in that case you are explictly calling those targets (transitively). 
CI
> bzl: add manual tags to a `go_cross_binary` rules that are used with local e2e testing

- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
- cmd/cody-gateway/shared/config.go
- internal/completions/httpapi/codecompletion.go
- internal/conf/computed.go
- internal/licensing/codygateway_test.go
Adds supports for new model identifiers:
- `gpt-4-1106-preview` as the preview for gpt-4-turbo
- `accounts/sourcegraph/models/starcoder-7b` and `accounts/sourcegraph/models/starcoder-16b` as new StarCoder deployments
- Tests green on CI
> Add gpt-4-turbo and new Fireworks model support

- doc/cody/troubleshooting.md
This doc update adds the step to take when a user hits a local storage exceed error on their Sourcegaph instance when using Cody chat
Doc update previewed locally. 
[Preview Link](https://docs.sourcegraph.com/@doc/add-localstorage-troubleshooting-section)
> Add troubleshooting for localStorage in Cody Web

- client/web/src/repo/blob/codemirror/blame-decorations.tsx
Fixes a layout bug that was causing EOF message in the blob view to align with git blame decorations instead of with code mirror content. Before and After video: 
https://github.com/sourcegraph/sourcegraph/assets/62355966/79dd6673-6f05-448d-a24c-7d08ce779fe0
Manual testing on files with and without the EOF decoration
> Code Navigation: align EOF message with code mirror content

- internal/gitserver/git_command.go
A long time ago in a galaxy far, far away we included stderr in the error messages returned from git. From reading our codepaths nearly everything goes via DividedOutput which throws the message away since CommandStatusError.Message is always set to a message like "exit status 128". This makes it really hard to understand why something isn't working.
A risk here is we intentionally got rid of stderr output due to security concerns? However, I think the more likely reason was accidental from when the whole RemoteGitCommand vs LocalGitCommand abstraction was introduced.
I noticed this when trying to debug why hybrid search was failing.
Test Plan: CI
> gitserver: include stderr in output error message

- cmd/frontend/graphqlbackend/graphqlbackend.go
- cmd/frontend/graphqlbackend/rate_limit.go
- cmd/frontend/graphqlbackend/search_test.go
- cmd/frontend/graphqlbackend/testing.go
- cmd/frontend/internal/httpapi/graphql.go
This sets a maximum GraphQL query depth of 20 and sets a maximum number of aliases. This helps prevent queries that consume too many resources and lead to a Denial-of-Service.
For more information, or discussion on the change please refer to: 
- https://github.com/sourcegraph/security-issues/issues/359 for the the maxdepth definition;
- https://github.com/sourcegraph/security-issues/issues/358 for the max field count check;
- Tested on local instance
- CI tests
> sec: Define GraphQL cost limits

- CHANGELOG.md
- cmd/frontend/graphqlbackend/git_blob.go
- cmd/frontend/graphqlbackend/schema.graphql
- internal/gitserver/commands.go
Currently, our `git blame` API endpoint adds the `-w` flag to `git blame`, which causes whitespace-only changes to be ignored when blaming a line. This is different than GitHub's behavior, and a confusing default.
This makes the ignoring whitespace configurable in the GraphQL enpdoint, and disables it by default.
Git blame for [this file](https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/cody/search/CodySearchPage.tsx?L122-129&trace=1) now matches what GitHub shows.
> Git blame: make ignoring whitespace configurable

- CHANGELOG.md
- client/web/src/components/diff/DiffHunk.module.scss
- client/web/src/components/diff/DiffHunk.tsx
- client/web/src/components/diff/__snapshots__/DiffHunk.test.tsx.snap
This fixes line wrapping behavior in diff view. Previously, if a line didn't fit in the view, it would jump to a new line before properly wrapping. This made it look like the diff added a newline.
The problem was that we're adding a diff marker (the plus/minus) in the gutter, but outside the div with `inline-block`, so the whole div was being pushed to the next line. Instead, if we move the `::before` selector to target the div with the content, the issue goes away. Because we cannot use a data attribute from a parent element in CSS, I also had to move `data-diff-marker` to the div that's being targeted.
Fixes https://github.com/sourcegraph/sourcegraph/issues/57834
See the before in the [issue report](https://github.com/sourcegraph/sourcegraph/issues/57834). Here's the after: …
> Diff view: fix line wrapping

- client/web/src/components/diff/DiffHunk.module.scss
- client/web/src/components/diff/DiffHunk.tsx
- client/web/src/components/diff/__snapshots__/DiffHunk.test.tsx.snap
- client/web/src/repo/blob/codemirror/eof.ts
This adds the `user-select: none` attribute to text in two places. The first is the `no newline at end of file` notice. It's really easy to accidentally copy that instead of the code, so this just makes it non-selectable. The second is the hidden text describing the types of diff lines. Previously, this would make text copied from diffs unusable, so this makes that text not show up when copied. 
Ensured that not copying the text succeeds in both firefox and safari.
> Web client: fix copyability of text

- dev/managedservicesplatform/internal/stack/BUILD.bazel
- dev/managedservicesplatform/internal/stack/README.md
- dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
- dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/builder.go
- dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/job/job.go
- dev/managedservicesplatform/internal/stack/cloudrun/internal/builder/service/service.go
- dev/managedservicesplatform/internal/stack/project/project.go
- dev/managedservicesplatform/internal/stack/stacks.go
This change allows Stacks to add outputs explicitly, rather than requiring them to be referenced by another stack. We mark everything as non-sensitive as the only values exposed here are for human reference.
https://github.com/sourcegraph/managed-services/pull/48
> dev/msp: add explicit outputs to stack workspaces

- dev/managedservicesplatform/internal/resource/redis/redis.go
We need to declare this explicitly to avoid infinite drift in Terraform:
```
~ resource "google_redis_instance" "redis-instance" {
id                       = "projects/cloud-ops-dashboard-prod-245f/locations/us-central1/instances/redis"
name                     = "redis"
~ persistence_config {
- rdb_snapshot_period     = "TWENTY_FOUR_HOURS" -> null
}
}
```
n/a
> dev/msp: fix redis configuration drift

- doc/cody/overview/install-jetbrains.md
The PR adds DataGrip as the supported IDE in JetBrains docs.
Docs Added
[Preview Link](https://docs.sourcegraph.com/@add-datagrip)
> [Cody GA Docs] Add DatGrip to list of supported JetBrains IDEs

- dev/managedservicesplatform/BUILD.bazel
- dev/managedservicesplatform/cdktf.go
- dev/sg/msp/repo/repo.go
- dev/sg/msp/sg_msp.go
```sh
sg msp generate -all # generate all envs across all services
sg msp generate -all <service> # generate all envs for a single service
sg msp generate # error, needs service
sg msp generate <service> # error, needs env
sg msp generate <service> <env> # same as before
```
https://github.com/sourcegraph/managed-services/pull/48
> dev/msp: 'generate -all' to generate all services and all envs

- cmd/symbols/squirrel/BUILD.bazel
- cmd/symbols/squirrel/util.go
One of the bugs in https://github.com/sourcegraph/sourcegraph/pull/58069
Run `go test ./cmd/symbols/squirrel/...`. It wasn't caught by CI: https://sourcegraph.slack.com/archives/C04MYFW01NV/p1699334502046179
> squirrel: Do a lowercase check only if the case-sensitive check fails

- dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
This is an oversight, as we configure this in Cody Gateway.
n/a
> dev/msp: add SSL_CERT_DIR when configuring Redis

- lib/batches/changeset_spec.go
- lib/batches/changeset_spec_test.go
- lib/batches/schema/changeset_spec_stringdata.go
- schema/changeset_spec.schema.json
- schema/schema.go
Part 1 of [#58150](https://github.com/sourcegraph/sourcegraph/issues/58150)
#51572 added the `fork` attribute to the changeset template. This allowed per-batch-change control for pushing to a fork of the upstream repository. However, this was only supported by SSBC, and the field was ignored by batch changes created via the `src-cli` tool.
This PR adds the attributes to the `/lib` so that `src-cli` can properly parse the fork attribute whenever it's specified in a batch spec.
* I did a couple of manual tests to ensure this change didn't introduce any regression.
* Added a test for fork support to the `ParseChangesetSpec` function.
* Batch changes created via `src-cli` with the fork attribute now have the proper `fork_namespace` set.
> code-search: handle changeset fork when creating a batch change via src-cli

- cmd/frontend/internal/httpapi/graphql.go
We want to log query violations, as this could indicate client code that uses the GraphQL API in a non-standard way. 
CI tests.
> Temporarily log costly queries

- cmd/symbols/squirrel/BUILD.bazel
- cmd/symbols/squirrel/language-file-extensions.json
- cmd/symbols/squirrel/languages.go
Fixes one of the bugs in https://github.com/sourcegraph/sourcegraph/pull/58069
n/a
> squirrel: Re-enable code nav for .pcc/.pc files

- docker-images/syntax-highlighter/crates/scip-syntax/src/ts_scip.rs
This change adds a comment explaining how the 'kind' names don't always match
the universal-ctags output exactly.
Comment-only change
> SCIP ctags: explain the 'kind' naming

- client/web/src/repo/blob/codemirror/search.tsx
- client/wildcard/src/global-styles/code.scss
This PR cleans up the blob view search bar, which was obfuscated in a number of ways, especially in dark mode. 
Before: 
After: 
Some other changes: 
- Remove superfluous 'previous' and 'next' labels since carat up and down will suffice. 
- previous, next buttons, and results will show up dynamically based on matches. Matches must be greater than 1 for next and previous buttons to become visible.
- Remove superfluous label describing command on right side of search container.
- Lighten any items that were not easily visible in dark mode.
- Fix strange looking key icons
Manual testing
> Code Navigation: cleans up blob view search

- doc/cody/overview/install-vscode.md
The PR adds info about configuring Code Graph Context for Cody via VS Code extension settings.
Docs added.
[Preview Link](https://docs.sourcegraph.com/@cody-vs-cg)
> [Cody GA Docs] Add info for enabling Code Graph with VS Code extension

- dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
- dev/managedservicesplatform/internal/stack/project/project.go
- dev/managedservicesplatform/internal/stack/stacks.go
This change renders any explicit outputs that are added as locals as well. This allows us to just add custom Terraform inside the same directory, and everything just works nicely OOTB, allowing us to add adjacent resources we'd like (e.g. permissions)
`sg msp generate` and place custom `terraform.tf` referencing the new locals. Running generate again doesn't blow the custom TF away either
> dev/msp: render explicit outputs as locals

- dev/managedservicesplatform/BUILD.bazel
- dev/managedservicesplatform/internal/stack/cloudrun/BUILD.bazel
- dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
- dev/managedservicesplatform/internal/stack/iam/BUILD.bazel
- dev/managedservicesplatform/internal/stack/iam/iam.go
- dev/managedservicesplatform/internal/stack/iam/iam_test.go
- dev/managedservicesplatform/internal/stack/project/BUILD.bazel
- dev/managedservicesplatform/internal/stack/project/project.go
- dev/managedservicesplatform/managedservicesplatform.go
- dev/managedservicesplatform/terraformcloud/BUILD.bazel
- dev/managedservicesplatform/terraformcloud/terraformcloud.go
This change moves service accounts etc to a new `iam` module that can be configured and applied before deploying any Cloud Run resources. MSP services will frequently need the workload service account to have access to other resources outside the project - this will resolve the chicken-and-egg problem with provisioning new services that we frequently run into.
However, to do this safely, we must avoid recreating the service account entirely, so that existing permission grants are preserved. See test plan for manual migration process, which does some surgery on the Terraform state to avoid any destructive changes.
```sh
export SERVICE_ID=telemetry-gateway
export ENV_ID=dev
export SERVICE_ACCOUNT=telemetry-gateway-sa@telemetry-gateway-dev-0050.iam.gserviceaccount.com
```
Generate:
```sh
sg …
```
> dev/msp: migrate service accounts, IAM to 'iam' module

- deps.bzl
- go.mod
- go.sum
This update contains one commit from the zoekt repo:
db067d1294 matchtree: call prepare on symbolRegexpMatchTree subtree
Test Plan: tested in the zoekt repo
> gomod: update zoekt with symbol perf fix

- client/wildcard/src/components/Combobox/MultiCombobox.module.scss
Simply removes focus ring from input UI in the multi combobox UI 
| ------- | ------- |
| <img width="591" alt="Screenshot 2023-11-08 at 16 34 02" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/f7e18cbe-1ac0-4bb2-9965-2f2b6e963263"> | <img width="586" alt="Screenshot 2023-11-08 at 16 34 32" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/06100663-bb05-424a-82c3-295f74b5fd52"> |
- Check multi combobox with valid/invalid states (I checked code insight creation form for it)
> Fix input focus ring styles in MultiCombobox UI

- cmd/frontend/internal/httpapi/graphql.go
Previously we returned an error, which resulted in a 500 error. This will return 400 with a clear message indicating a cost violation.
Backport from: https://github.com/sourcegraph/sourcegraph/pull/58230
Manually backported to include change: https://github.com/sourcegraph/sourcegraph/pull/58192. 
Tested locally, CI.
> [Backport 5.2 (manual)] Return better error for GQL cost violations

- client/web/src/repo/RepoLinkPicker.tsx
- client/web/src/repo/utils.tsx
Follow up from this convo https://github.com/sourcegraph/sourcegraph/pull/58025#discussion_r1379139554
This PR improves a bit behaviour of the repository picker makes it a bit more explicit about what value exactly we use to fetch list of repositories in the suggestion panel. Prior this PR we fetch list by repository name but input doesn't have any value. This PR include initial value in the input so user can see why they see what they see in the suggestion panel. 
- Check that when you open repository picker it has initial value with repository name
> [Repository page]: Show initial repository query value in initial picker state

- client/web/src/repo/blob/codemirror/search.tsx
Before, the regex filter on blobview search was crashing the application when selected with an undefined or empty value. 
This commit adds conditionals that check for valid regular expressions so that the feature is now useable, and no longer crashing the application.
There are still other improvements that need to be made regarding the regex filter, but this commit makes the core feature useable.
Manual testing
> Code Navigation: fix borked regex filter

- dev/managedservicesplatform/internal/resource/cloudflare/cloudflare.go
- dev/managedservicesplatform/internal/resource/cloudflareorigincert/cloudflareorigincert.go
- dev/managedservicesplatform/internal/resource/gsmsecret/gsmsecret.go
- dev/managedservicesplatform/internal/resource/loadbalancer/loadbalancer.go
- dev/managedservicesplatform/internal/resource/managedcert/managedcert.go
- dev/managedservicesplatform/internal/resource/random/random.go
- dev/managedservicesplatform/internal/resource/redis/redis.go
- dev/managedservicesplatform/internal/resource/serviceaccount/serviceaccount.go
- dev/managedservicesplatform/internal/resource/tfvar/tfvar.go
- dev/managedservicesplatform/internal/resourceid/resourceid.go
- dev/managedservicesplatform/internal/stack/iam/iam.go
- dev/managedservicesplatform/internal/stack/project/project.go
- dev/managedservicesplatform/internal/stack/stacks.go
Fix a regression from #58216 where I changed a resource ID from a static string to a CDKTF variable, breaking generation for the cloud-ops-dashboard service. CDKTF variables cannot be used as resource IDs.
This changes the role ID to the `resourceid` type to guard against misuse, and also adds some docstring warnings on various `resourceid.ID` constructors.
https://github.com/sourcegraph/managed-services/pull/65
> dev/msp: fix custom role ID, update resourceid with warnings

- client/web/src/repo/blob/codemirror/codeintel/extension.ts
This PR fixes a CSS bug where there were white corners overlapping the border radius of tooltip containers in dark mode. 
manual testing
> Code Navigation: remove white corners from tooltips in dark mode

- client/web/src/cody/chat/CodyChatPage.tsx
- client/web/src/cody/components/ChatUI/ChatUi.tsx
- client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
- client/web/src/cody/widgets/CodyRecipesWidget.tsx
- client/web/src/get-cody/GetCodyPage.tsx
- client/web/src/site-admin/analytics/AnalyticsExtensionsPage/index.tsx
- client/web/src/site-admin/analytics/AnalyticsSearchPage/index.tsx
- client/web/src/storm/pages/SearchPage/TryCodyCtaSection.tsx
- client/web/src/util/constants.ts
A "get Cody in your editor" CTA was showing in the bottom right of every single chat message. This was obtrusive. There is already a CTA at the top of the page to get Cody in your editor. Here is the CTA that was removed:
Also generally prefers the term "editor" to "IDE" except in the specific context of JetBrains IDEs.
CI
> tweak wording and remove obtrusive CTA from cody chat messages

- go.mod
- internal/tracer/BUILD.bazel
- internal/tracer/tracer.go
- internal/tracer/watch_test.go
We see the OpenTelemetry debug logs emit a lot of output in Cloud - it's not all that important, and we already register an error handler, so this sets the default OpenTelemetry output to discard.
I'm still not sure what caused this to start happening but this should fix the problem.
CI
> internal/tracer: silence opentelemetry debug logs

- dev/managedservicesplatform/internal/resourceid/resourceid.go
- dev/managedservicesplatform/internal/stack/iam/iam.go
Regression from #58239 - added a `Stringer` implementation that panics to guard against this in the future.
```
sg msp generate -all -stable
```
https://github.com/sourcegraph/managed-services/pull/68
> dev/msp: fixup resource IDs

- client/branded/src/search-ui/input/SearchBox.story.tsx
- client/branded/src/search-ui/input/SearchBox.tsx
- client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.module.scss
- client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
- client/branded/src/search-ui/input/toggles/Toggles.test.tsx
- client/branded/src/search-ui/input/toggles/Toggles.tsx
- client/web/BUILD.bazel
- client/web/src/LegacyLayout.tsx
- client/web/src/components/externalServices/ExternalServiceEditPage.story.tsx
- client/web/src/components/externalServices/ExternalServicePage.story.tsx
- client/web/src/devsettings/DeveloperSettingsGlobalNavItem.tsx
- client/web/src/nav/GlobalNavbar.module.scss
- client/web/src/nav/GlobalNavbar.tsx
- client/web/src/nav/NavBar/NavBar.tsx
- client/web/src/nav/NavBar/NavItem.module.scss
- client/web/src/nav/UserNavItem.story.tsx
- client/web/src/nav/UserNavItem.tsx
- client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
- client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.module.scss
- client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.story.tsx
- client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
- client/web/src/search/input/LazyV2SearchInput.module.scss
- client/web/src/search/input/LazyV2SearchInput.tsx
- client/web/src/search/input/SearchNavbarItem.tsx
- client/web/src/search/input/V2SearchInput.tsx
- client/web/src/site-admin/AccessRequestsPage/AccessRequestsGlobalNavItem.tsx
- client/web/src/storm/pages/SearchPage/SearchPageInput.tsx
- schema/schema.go
- schema/settings.schema.json
Closes https://github.com/sourcegraph/sourcegraph/issues/54794
The problem this PR is trying to solve is optimising/freeing vertical space (free it for actual content that matters but still manage our global navigation in a way that this is still visible and accessible). Vertical space becomes a bigger problem in places where we have a lot of sticky content on top (like blob UI page or even search result page), users who don't use big external monitors can't use Sourcegraph efficiently. 
The solution is to merge search box UI and global navigation UI, similar how our code search product have it (see Google Code Search and Github navigation). 
Note: that we still not sure about some decisions about this navigation, this might affect our feature visibility in unexpected way, so on pages …
> [Search UI]: Add new experimental search UI navigation

- dev/managedservicesplatform/internal/stack/iam/iam.go
- dev/sg/msp/sg_msp.go
The iam stack was mutating the shared `serviceAccountRoles` variable, which affects the output of other services.
```
sg msp generate -all
```
> dev/msp: do not mutate package variable

- docker-images/syntax-highlighter/Cargo.Bazel.lock
- docker-images/syntax-highlighter/Cargo.lock
- docker-images/syntax-highlighter/Cargo.toml
- docker-images/syntax-highlighter/crates/scip-treesitter-cli/Cargo.toml
- docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/evaluate.rs
- docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/index.rs
- docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/main.rs
- docker-images/syntax-highlighter/crates/scip-treesitter/src/types.rs
Major changes:
1. Use proper iteration structures like `into_iter()`/`iter()` in a bunch of places to
avoid cloning `HashMap`/`Vec` structures (as those will be deep clones).
2. Uses string interning to avoid cloning `String`s and avoiding complicating
lifetimes by passing `&str` everywhere. This allows marking all the interesting
types as `Copy` so that `*` can perform a copy with needing `clone()`.
3. Introduces newtype wrappers to avoid confusing different kinds of symbols.
4. Uses more methods instead of free functions for better auto-complete and
and code organization.
n/a
> cleanup: Make evaluator code more idiomatic

- client/web/src/nav/StatusMessagesNavItem.tsx
The "!" is unnecessary and strikes the wrong tone.
CI
> remove "!" from global navbar site admin status messages

- docker-images/syntax-highlighter/Cargo.Bazel.lock
- docker-images/syntax-highlighter/crates/scip-treesitter-cli/BUILD.bazel
- docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/lib.rs
- docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/main.rs
- docker-images/syntax-highlighter/crates/scip-treesitter-cli/tests/integration_test.rs
- docker-images/syntax-highlighter/crates/scip-treesitter-cli/tests/snapshots/integration_test__globals.java.snap
So earlier, I removed the library part from the Bazel build configuration.
However, the correct build configuration actually involves moving the
integration test (which utilizes the `scip-treesitter-cli`) binary into
a separate integration test directory, since integration tests have
an implicit dependency on the binary, whereas unit tests don't.
https://users.rust-lang.org/t/cargo-how-do-i-make-a-integration-test-a-depend-on-binary-b/9821/4
So previously, `cargo test` wouldn't have worked anyways because
of this missed dependency. However `bazel test` was working
because Bazel allows customizing the dependency graph by
adding a dependency on the binary in a way that cargo doesn't.
Moreover, because the integration test utilizes a function
`read_index_from_file` from the code, we need …
> build: Separate out integration test and re-add library target for scip-treesitter-cli

- dev/sg/dependencies/mac.go
- dev/sg/dependencies/shared.go
- dev/sg/dependencies/ubuntu.go
The "is Sourcegraph teammate" check was removed from `sg`, but we need to skip those same steps as before in CI.
CI
> fix sg in CI

- dev/universal-ctags-dev
Fixes https://github.com/sourcegraph/devx-support/issues/376
Locally ran `sg start` and the big block of output from universal-ctags-dev is not there anymore.
> bzl: do not show full commmand line for ctags in dev

- deps.bzl
- go.mod
- go.sum
This update contains one commit from the Zoekt repo:
- 2355607d5f Indexing: respect indexing buffer limit
> Zoekt: bump version for index memory fix

- cmd/frontend/graphqlbackend/git_tree_entry.go
When `len(in) == 0`, this code panics because `in` will be indexed with a negative value. 
The file I was trying to view no longer panics.
> Fix panic for empty blobs

- client/web/src/repo/blob/RenderedFile.module.scss
This commit introduces a minor enhancement by incorporating background colors for code snippets, both inline and block, during the rendering of markdown. This addition enhances the clarity of code sections, contributing to an improved overall viewing experience.
Loom video of changes: 
https://www.loom.com/share/d9228c8e4ae444e1ace5c13ad9bcda45?sid=57c09212-ab48-4dec-b0dd-54b83fa39c88
Manual testing in light and dark mode on many different repos.
> Code Navigation: add background inline code and code blocks

- cmd/frontend/graphqlbackend/git_tree.go
- cmd/frontend/graphqlbackend/git_tree_test.go
- cmd/frontend/graphqlbackend/schema.graphql
There were two issues with that PR that introduced the test suite:
- When switching recursive on, we accidentally added more entries than expected, because git would also output parents of the requested subtree to list.
- I misunderstood what recursiveSingleChild is supposed to do. As a result, the code is a bunch simpler.
Closes https://github.com/sourcegraph/sourcegraph/issues/57999 Closes https://github.com/sourcegraph/sourcegraph/issues/57936
Added tests for both of these cases.
> Fixup GitTree behavior after adding test suite

- CHANGELOG.md
- internal/conf/computed.go
- internal/conf/computed_test.go
This fixes a bug where the default size limit for files was set to 0 if `FileFilters`  were defined.
Until this fix is released, a workaround is to always define `MaxFileSizeBytes` if `FileFilters` are defined.
Test plan:
> embeddings: fix default size limit

- client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.test.tsx
- client/web/src/enterprise/code-monitoring/components/FormTriggerArea.test.tsx
- client/web/vitest.config.ts
- package.json
- pnpm-lock.yaml
- vitest.shared.ts
So, ultimately: 
- Bumping to `vitest-1.0.0-beta.4` seemed to improved things a bit, but we're not entirely sure about this, as @burmudar 
- Lowering the max threads from 16 to 8 fixed the very strange errors about workers not qutting in time. 
- All the `vitest_test` rules are now properly sandboxed. 
- A few dependencies were missing, it previously worked because everything was happening without any sandbox, and stuff was there because the output tree was already populated with the non explicitly declared dependencies. 
CI + local
> bazel: fix vitest_test in Bazel in sandbox mode

- tools/release/README.md
- tools/release/schema_deps.bzl
Update the database schema tarball so `main` includes 5.2.2 
CI 
`tar tf $(bazel cquery //cmd/migrator:tar_schema_descriptions --output=files)`
Spotted a missing file while doing the above, BRB fixing this.
> bzl: bump db schemas to 5.2.2

- deps.bzl
- go.mod
- go.sum
This update contains these commits from the Zoekt repo:
- e068116194 Indexing: improve skipped doc handling
- 5e2620e0cf Indexing: properly block on shard building
> Zoekt: bump version for more indexing fixes

- client/web/src/repo/blob/codemirror/search.module.scss
- client/web/src/repo/blob/codemirror/search.tsx
Better looking previous and next buttons for blob view search. Now more closely resembles safari's find feature.
Before: 
After:
Manual testing in light and dark mode.
> Code Navigation: clean up prev next buttons

- client/shared/src/backend/repo.ts
- client/web-sveltekit/src/lib/repo/api/tree.ts
- client/web/src/integration/graphQlResponseHelpers.ts
- client/web/src/integration/repository.test.ts
- client/web/src/repo/RepoRevisionSidebarFileTree.tsx
- client/web/src/repo/tree/TreePagePanels.tsx
This PR removes the ability to collapse single-child directories. This feature has been pretty unstable and has been the source of quite a few bugs lately. Additionally, it's surprisingly expensive to implement, requiring fetching ton of extra data (the _entire_ recursive git tree) from gitserver, which adds significant latency to interactions with the file tree. Between the complexity, bugginess, and fundamental perf issues, I don't think it's worth keeping around. Especially since it's pretty rare for directories to contain only a single subdirectory. 
Before:
After:
There is a lot of very complex backend code that I will clean up as a followup. 
Tested that single-file directories now get rendered consistently.
> File tree: get rid of single child logic

- cmd/frontend/graphqlbackend/git_tree.go
- cmd/frontend/graphqlbackend/git_tree_test.go
- cmd/frontend/graphqlbackend/schema.graphql
This is the backend half of [this PR](https://github.com/sourcegraph/sourcegraph/pull/58272). It removes the `recursiveSingleChild` logic from the tree resolver. All consumers of this field have been removed from the client already, and it's unlikely this would be something that customers would use (or even be able to use correctly) so I think it's safe to make what is technically a breaking change. 
Poked around in the file tree and everything looked fine. All consumers of this API have already been removed.
> GraphQL: remove recursiveSingleChild option from backend

- internal/telemetry/sensitivemetadataallowlist/BUILD.bazel
- internal/telemetry/sensitivemetadataallowlist/sensitivemetadataallowlist.go
- internal/telemetry/sensitivemetadataallowlist/sensitivemetadataallowlist_test.go
In case we need more metadata from Cloud instances or a particular customer, an env var override could come in handy. It must be proactively configured.
This change also fixes a misspelling in the file name.
unit test on the parser
> telemetry: allow env-var allowlisting of sensitive metadata export

- doc/admin/telemetry/index.md
- doc/dev/background-information/telemetry/architecture.md
- doc/dev/background-information/telemetry/index.md
- doc/dev/background-information/telemetry/protocol.md
- internal/telemetrygateway/v1/protoc-gen-doc.tmpl
In 5.2.1, we've rolled out a new telemetry export framework and associated docs, but not all events use it yet - this change adds disclaimers that the new content does not apply to a lot of existing events. Migrations are being tracked by the analytics team. In most cases, there isn't an equivalent reference for the existing events, particularly Cody extension events, so I haven't added any links. There's a discussion about this in [this thread](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1699627360154729).
I also made a few misc updates to other sections to hopefully improve the wording and clarity a bit.
n/a
[Preview Link](https://docs.sourcegraph.com/@telemetry-doc-update)
> doc: add notes that new telemetry docs only apply to some events

- client/web/src/codeintel/ReferencesPanel.mocks.ts
- client/web/src/codeintel/ReferencesPanel.tsx
- client/web/src/codeintel/location.ts
- client/web/src/codeintel/useCodeIntel.ts
- client/web/src/enterprise/codeintel/useCodeIntel.ts
The current ref panel code scatters calls for grouping and uniquing in a bunch of different places.
This makes the code hard to understand (which invariants hold and why?) and makes it harder
to propagate information easily at per-file or per-repo granularity.
In the future, we want to attach one SCIP Document per file for https://github.com/sourcegraph/sourcegraph/issues/58182
So I've attempted to centralize the grouping and uniquing logic here, and made
liberal use of assertions and comments to make it clear which invariants hold.
My coding style + naming is probably somewhat unidiomatic, open to suggestions for improvements.
TODO, not sure what kinds of tests I should add. Unit tests for the new `LocationGroup` class?
Is there any easy way to add fuzz tests to make sure that no …
> client: Centralize ref panel logic for Location grouping & uniquing

- cmd/frontend/graphqlbackend/user_usage_stats.go
IDE can be in a capital case. 
-
> [Cody] fix cody install event typo

- CHANGELOG.md
- client/branded/src/search-ui/input/experimental/suggestionsExtension.ts
Fixes #57848 
This issue occurred when a suggestion was applied while the extension was waiting for additional suggestions from the server.
There are various ways to fix this but the most robust one is to identify when a state update pertains to the current completion request and when it does not.
This commit adds a new field to the `Query` object to make this possible. Whenever a new request is issues this field is assigned a new value, making it easy to identify when we should preserve the current suggestion selection.
A relatively reliable way to test this seems to be the following:
- Prime file cache with some values, e.g. by typing `file:foo`
- Add another file filter with a single letter which is different from the first letter used in the previous step (to ensure a server request …
> search: Fix suggestion being selected after applying one

- internal/repos/sources_test.go
This test requires Redis under the hood.
I do have Redis running, but since `redis-cache` and `redis-store` aren't valid hostnames on my local machine, the tests couldn't connect and would timeout, leading to a long test run time.
Before:
$ time go test -run 'TestSources_ListRepos$' ./internal/repos -count=1
[...]
5.90s user 2.04s system 19% cpu 39.877 total
After:
$ time go test -run 'TestSources_ListRepos$' ./internal/repos -count=1
[...]
3.78s user 1.64s system 135% cpu 3.993 total
- Running this test
> repos: fix slow TestSources_ListRepos test

- cmd/gitserver/server/server.go
- cmd/gitserver/server/server_grpc.go
- cmd/gitserver/server/vcs_syncer_perforce.go
- internal/repos/perforce.go
Since there were a lot of changes around this code base including new gitserver RPC endpoints, I decided to implement a minimal fix here from scratch vs trying to backport maybe 5000 loc or going through rebase hell.
This PR fixes the integration test for perforce since we switched to SSL. This fixes a real issue, not just CI. 
CI passes now, was red before.
> Reimplement fix for setting p4trust consistently in 5.2

- dev/oci_deps.bzl
Updates the wolfi base-images to resolve detected CVEs. It adds 2 new images from our private repository, this is to prevent shipping an experimental p4-fusion-binary into the patch release.
- Check if p4-fusion-binary is the correct version
- Check if there's no unexpected CVE
- CI tests
> [5.2] Add updated base images

- internal/completions/client/client.go
- internal/embeddings/embed/embed.go
- internal/httpcli/client.go
Switched the completions & embeddings clients to use an uncached client, as the requests should be unique and caching would not be helpful.
CI 
Chatted with Cody web successfully, embedded a repo successfully
> Replace default httpclient for cody requests 

- CHANGELOG.md
- cmd/frontend/graphqlbackend/graphqlbackend.go
- cmd/frontend/graphqlbackend/rate_limit.go
- cmd/frontend/graphqlbackend/search_test.go
- cmd/frontend/graphqlbackend/testing.go
- cmd/frontend/internal/httpapi/graphql.go
- internal/conf/computed.go
- schema/schema.go
- schema/site.schema.json
This makes it easier for customer site-admin to change the GraphQL limits. It adds a `RateLimits` function to fetch the structure and makes sure we have default values.
CI tests, test locally.
> sec: Make GraphQL cost limits configurable

- CHANGELOG.md
- cmd/frontend/graphqlbackend/graphqlbackend.go
- cmd/frontend/graphqlbackend/rate_limit.go
- cmd/frontend/graphqlbackend/search_test.go
- cmd/frontend/graphqlbackend/testing.go
- cmd/frontend/internal/httpapi/graphql.go
- internal/conf/computed.go
- schema/schema.go
- schema/site.schema.json
This makes it easier for customer site-admin to change the GraphQL limits. It adds a `RateLimits` function to fetch the structure and makes sure we have default values.
@sourcegraph/release-guild 
CI tests, test locally.
> [Backport 5.2] sec: Make GraphQL cost limits configurable

- doc/api/graphql/index.md
Adds a section on docs.sourcegraph.com about the new costs limitations.
Review
[Preview Link](https://docs.sourcegraph.com/@vincent/graphql-cost-doc)
> docs: Add section about GraphQL cost limts

- dev/build-tracker/notify/slack.go
The loom referenced in "Is this a flake?" is not relevant anymore and by adding this to the notification we can get more people to look at the test analytics.
> [!NOTE]
> We can't (more like it's too much effort now ...) provide a direct link to the builds test analytics run as the test analytics run ID is not exposed anywhere in the build events that we get from buildkite 
None - only a text change for the link
> buildtracker: replace "Is this a flake" with "View test analytics"

- dev/sg/dependencies/helpers.go
Improve the error message from:
To
The first error message makes you think you only have to define `PG_UTILS_PATH=...`, but you actually need to know that you need to do `build --action_env`. Granted auto fix should also fix this in the correct way.
Tested locally
> sg: improve PG_UTILS_PATH error msg

- internal/repos/BUILD.bazel
- internal/repos/sources_test.go
Here's some `stop-the-bleeding` for you.
I ran into these tests yesterday and really, _really_ struggled adding a new test for the `Exclude` functionality on the GitHub code host connection. Turns out that the test's `assert` method basically re-implements the implementation and is prone to false negatives and false positives.
The rest of the `testCases` also struck me as "someone added them here because this was easy" and then they've grown over the past few years.
So what I did here was to
- Split up that huge test function into separate smaller functions that can be run independently and also allow easier updating of VCR fixtures
- **Keep the VCR fixtures the same!**
- Make fixture names more visible
- Add simple but clear test assertions that assure that the `Source` yields the repos …
> repos: refactor and clean-up the `Source.ListRepos` tests

- cmd/frontend/internal/embeddings/resolvers/BUILD.bazel
- cmd/frontend/internal/embeddings/resolvers/repo_embedding_jobs.go
- cmd/frontend/internal/embeddings/resolvers/repo_embedding_jobs_test.go
Fixes #58313
Order by column for a connection resolver needs to have table name prefix, rather than default `id`. This is because when using a repo name filter, the `repo` table is `JOIN`ed to the query. Now there are two tables - repos and jobs that both have the `id` column and filtering by unqualified `id` is ambiguous SQL.
Add a test case reproducing the problem. Without the explicit order by column:
```
--- FAIL: TestDBPaginationWithRepoFilter (1.39s)
/Users/cbart/sourcegraph/cmd/frontend/internal/embeddings/resolvers/dbtest.go:150: testdb: postgres://sourcegraph:sourcegraph@127.0.0.1:5432/sourcegraph-test-3696020003995722875?sslmode=disable&timezone=UTC
/Users/cbart/sourcegraph/cmd/frontend/internal/embeddings/resolvers/core.go:57: [33mWARN[0m TestDBPaginationWithRepoFilter …
```
> Repo embedding jobs ordered by a qualified column

- client/web/src/repo/blob/codemirror/codeintel/README.md
- client/web/src/repo/blob/codemirror/codeintel/decorations.ts
- client/web/src/repo/blob/codemirror/linenumbers.ts
- client/web/src/repo/blob/codemirror/utils.ts
Fixes a bug that caused double line highlighting when using Code Search in Firefox. 
1. Manually test in firefox at different zoom levels
2. Manually test in chrome and safari at different zoom levels
> Code Navigation: fix double line highlight in Firefox

- client/web/src/codeintel/ReferencesPanel.tsx
- client/web/src/enterprise/codeintel/useCodeIntel.ts
Instead of having calls to `setCodeIntelData` scattered in different places,
this patch makes things a bit simpler -- we only call it at the end of having
processed the result of a query.
Stacked on top of #58183, to be merged after that.
Manually tested with `sg start web-standalone`
> client: Simplify some code in useCodeIntel.ts

- BUILD.bazel
- dev/sg/BUILD.bazel
```sh
bazel build //dev/sg:sg --//:sg_msp=True
```
```sh
bazel run //dev/sg:sg --//:sg_msp=True -- msp help                                                            14:56:46
INFO: Analyzed target //dev/sg:sg (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //dev/sg:sg up-to-date:
bazel-bin/dev/sg/sg_/sg
Aspect @rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of //dev/sg:sg up-to-date (nothing to build)
INFO: Elapsed time: 0.317s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/dev/sg/sg_/sg msp help
NAME:
sg managed-services-platform - EXPERIMENTAL: Generate and manage services deployed on the Sourcegraph Managed Services Platform
USAGE:
sg msp init $SERVICE
sg msp …
```
> dev/sg: build sg-msp with bazel

- client/web/src/repo/blob/codemirror/search.module.scss
- client/web/src/repo/blob/codemirror/search.tsx
Add a close button to the blobview search component. 
Inactive: 
hover:
Manual testing in light and dark mode.
> Code Navigation: add close button to blobview search

- client/branded/src/search-ui/input/codemirror/token-info.ts
- client/wildcard/src/global-styles/highlight.scss
Before, when a user hovered over a token with a tooltip, the immediate lack of highlighting created a state of uncertainty. No indication precedes the appearance of a tooltip, as they take several seconds to fully load upon the initial page load, and highlighting will not appear until they are fully loaded. This behavior contributed to a sluggish and somewhat frustrating user experience. 
Video of behavior before: 
https://github.com/sourcegraph/sourcegraph/assets/62355966/1824c361-2a9f-4762-a3fe-c51aa3057b71
Now, highlighting occurs instantly upon hover, signaling to the user that an interaction is imminent.
1. Test manually on various file types:
- go
- javascript
- typescript
- cpp
- C
- ruby
- python
- java
- rust
> Code Navigation: tokens highlight immediately on hover

- client/web/dev/esbuild/server.ts
Recently, the plain URL became the marketing site, so the previous message:
```
[web-standal...p] ===================================================
[web-standal...p]
[web-standal...p]         ✱ Sourcegraph is really ready now!
[web-standal...p]
[web-standal...p]      Click here: https://sourcegraph.test:3443
[web-standal...p]
[web-standal...p] ===================================================
```
Would take you to an empty page, potentially leading one to the incorrect
conclusion that something was wrong.
Run `SOURCEGRAPH_API_URL=https://sourcegraph.com sg start web-standalone`
> build: Point to /search URL in help text

- vitest.workspace.ts
It appears that the workspace configuration is somehow broken because it doesn't include any tests defined in `client/web/src/`. This can be tested by filtering for a test inside this subtree, for example
pnpm exec vitest RepoRevisionSidebar
vitest will error saying it didn't find any tests. The list of projects it prints also doesn't include `web`.
I don't know what exactly it is that makes it exclude `client/web/` but with the simpler version in this PR `client/web/` will be included.
**NOTE:** Or is it intentional that `client/web/` is excluded? If so it's not obvious from the code.
I removed `client/web/dev/` from the list because it will be included by `client/web/` too and seems to "just work" even though it has it's own configuration file.
Before: 
After: 
`pnpm exec vitest …
> vitest: Fix workspace config wrt client/web/

- docker-images/syntax-highlighter/README.md
- docker-images/syntax-highlighter/crates/sg-syntax/src/lib.rs
- docker-images/syntax-highlighter/crates/sg-syntax/src/sg_sciptect.rs
- docker-images/syntax-highlighter/crates/sg-syntax/src/sg_syntect.rs
- docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
- docker-images/syntax-highlighter/docs/api.md
- docker-images/syntax-highlighter/src/bin/scip-dump-response.rs
- internal/gosyntect/gosyntect.go
- internal/highlight/highlight.go
In the code, the [CSS field was always set to be true](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/internal/highlight/highlight.go?L420), which meant that the Theme field would
be ignored in the query to syntect server. This patch removes both fields, keeping only
the `q.css == true` code path, and deleting all the mentions of themes.
Run `cargo run --bin syntect_server` followed by `SRC_SYNTECT_SERVER=http://127.0.0.1:8000 sg start enterprise-codeintel` and check highlighting is still working fine.
> syntax-highlighter: Delete Theme and CSS fields

- cmd/frontend/internal/auth/openidconnect/middleware.go
- cmd/frontend/internal/auth/openidconnect/middleware_test.go
> oidc: redirect to `/search` page after auth flow by default

- doc/cody/overview/enable-cody-enterprise.md
Add note requiring version 5.2.2 to use AWS Bedrock. 
Docs change only. 
[Preview Link](https://docs.sourcegraph.com/@rpp/update-min-version-bedrock)
> Add required Sourcegraph version for Bedrock

- sg.config.yaml
This isn't much, but while I was taking a look again at Bazel + local env, noticed this got in the way. It's not the best way to solve this, but at least, it won't make folks squint their eyes to notice this in the middle of the logs. 
Locally tested + CI
> sg: ease scip-ctags-dev installation

- cmd/worker/internal/codemonitors/BUILD.bazel
- cmd/worker/internal/codemonitors/codemonitor_job.go
This executes on the deprecation plan of monitors on dotcom. See Slack here: https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1698878170295189
This only stops them from running, but doesn't hide them from the UI and prunes the DBs yet, which is scheduled for November 29.
Code review, CI.
> Stop running deprecated code monitors on dotcom

- cmd/gitserver/internal/server.go
In a recent change, I accidentally broke this logic, which is causing a bunch of errors on sourcegraph.com. The stray filepath.Dir I forgot to remove around tmpDir made it so that all repos are renamed to the same path, and never actually deleted, causing ErrExists errors.
Verified fix by hand.
> gitserver: Fix removal of old clone during reclones

- cmd/frontend/internal/app/ui/BUILD.bazel
- cmd/frontend/internal/app/ui/router.go
We log a ton of events to Sentry about 404 routes and the likes. I don't think 4xx errors should cause error logs, so I'm downgrading these to warning level instead.
Code review.
> Prevent error log and sentry spam from HTTP client errors

- client/web/src/repo/blob/codemirror/linenumbers.ts
Don't remove the line selection (and URL fragment) when a user clicks on a line again - Slack discussion, other Code Editor / browsing systems (Github / Gitlab / Google Code Search) don't remove it.
> Don't remove the URL number / line selection when user clicks again

- .tool-versions
- WORKSPACE
- cmd/symbols/Dockerfile
- docker-images/syntax-highlighter/.cargo/config.toml
- docker-images/syntax-highlighter/Cargo.Bazel.lock
- docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
- docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/index.rs
- docker-images/syntax-highlighter/crates/scip-treesitter-languages/src/parsers.rs
- docker-images/syntax-highlighter/crates/scip-treesitter/src/types.rs
- docker-images/syntax-highlighter/crates/sg-syntax/src/sg_treesitter.rs
- src-tauri/README.md
There are a bunch of improvements since Rust 1.68.0
such as nicer panic messages, and sparse-by-default
crates.io usage when using cargo directly.
TODO:
To be merged after #57894
Should be covered by CI, right?
> bzl: Bump Rust version

- docker-images/syntax-highlighter/BUILD.bazel
Fixes https://github.com/sourcegraph/sourcegraph/issues/58333 
I created a repo for `scip-ctags` in our Docker org accordingly. 
CI + ran the container locally 
```
~/work/sourcegraph U main $ docker load --input=bazel-bin/docker-images/syntax-highlighter/scip-ctags_image_tarball/tarball.tar
7bd31829c240: Loading layer [==================================================>]  8.535MB/8.535MB
Loaded image: scip-ctags:candidate
~/work/sourcegraph U main $ docker run scip-ctags:candidate -- -h
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
{"_type":"program","name":"SCIP Ctags","version":"5.9.0"}
```
> bzl: containerize scip-ctags

- internal/repos/awscodecommit.go
- internal/repos/azuredevops.go
- internal/repos/bitbucketcloud.go
- internal/repos/bitbucketserver.go
- internal/repos/exclude.go
- internal/repos/exclude_test.go
- internal/repos/github.go
- internal/repos/gitlab.go
- internal/repos/gitolite.go
- internal/repos/other.go
- internal/repos/sources_test.go
This is a follow-up to https://github.com/sourcegraph/sourcegraph/pull/58377 and changes how `exclude` works by AND'ing all conditions in a single rule together.
It does this mostly by refactoring the code and turning things upside down (inside out?):
- instead of each `[]exclude` entry in a code host connection config being turned into a separate condition, one of which had to be true
- each entry is turned into a `*rule` that can have multiple conditions and all of them have to be true for a repo to be excluded.
Best explained with an example.
Old code:
```go
var eb excludeBuilder
for _, r := range c.Exclude {
eb.Exact(r.Name)
eb.Exact(r.Id)
}
exclude, err := eb.Build()
return nil, err
}
// then:
exclude(r.Id) || exclude(r.Name) || exclude(r)
```
New code:
```go
var ex …
```
> repo exclusion: switch to dynamic rule builder

- doc/dev/background-information/observability/cadvisor.md
Adding a known issue where cAdvisor doesn't scrape metrics in a non-privileged overlay Kustomize deployment
Doc update. Tested locally
[Preview Link](https://docs.sourcegraph.com/@doc/add-non-privileged-section)
> Update cAdvisor documentation

- dev/ci/push_all.sh
- docker-images/syntax-highlighter/BUILD.bazel
Add `oci_push` rule so new `scip-ctags` container for test purposes in Zoekt gets published. 
```
~/work/sourcegraph  main $ bazel query 'kind("oci_push rule", //...)' | grep scip
Loading: 0 packages loaded
//docker-images/syntax-highlighter:scip-ctags_candidate_push
```
```
~/work/sourcegraph  main-dry-run/jh/scip-ctags $ docker run us.gcr.io/sourcegraph-dev/scip-ctags@sha256:259f2435d5af95fc14e787b08c530b400259c8e6b1ce72bb163dba5b3320887e -- -h
Unable to find image 'us.gcr.io/sourcegraph-dev/scip-ctags@sha256:259f2435d5af95fc14e787b08c530b400259c8e6b1ce72bb163dba5b3320887e' locally
us.gcr.io/sourcegraph-dev/scip-ctags@sha256:259f2435d5af95fc14e787b08c530b400259c8e6b1ce72bb163dba5b3320887e: Pulling from sourcegraph-dev/scip-ctags
13b374ce116e: Pull complete
fedaafe1220e: Pull complete …
```
> bzl: add missing oci_push rule for scip-ctags

- doc/admin/deploy/kubernetes/configure.md
Update docsite for Kubernetes configs to fix random grammar errors and dead links.
Ran `sg run docsite` locally.
[Preview Link](https://docs.sourcegraph.com/@jdp/ssh-docs-fix)
> docs: update grammar and fix broken links

- deps.bzl
- go.mod
- go.sum
This change bumps the Zoekt version to include important fixes to prevent OOMs
during search indexing. Zoekt has a dedicated release branch called
`sourcegraph-5.2`, so we just bump the dependency on that branch to pull in new
commits.
Command: `./dev/zoekt/update sourcegraph-5.2`
https://github.com/sourcegraph/zoekt/compare/379ed5a0bb34...61edc95ba097
- https://github.com/sourcegraph/zoekt/commit/943fc74746 Indexing: respect indexing buffer limit
- https://github.com/sourcegraph/zoekt/commit/61edc95ba0 Indexing: properly block on shard building
Zoekt and Sourcegraph CI, also these changes have been running on S2 and dot
com for around a week.
> gomod: bump Zoekt version for 5.2

- internal/database/dbmocks/mocks_temp.go
- internal/database/gitserver_repos.go
- internal/database/gitserver_repos_test.go
- internal/repos/purge.go
We noticed this while investigating DB performance issues on dotcom.
This code would do the following:
1. Send query to database
2. Read first row of response
3. Delete repository on disk
4. Possibly wait for rate limiter
5. If more rows, repeat 2-4
Means the connection was held while the repositories were being deleted. With large repositories this can be a substantial amount of time.
Since we already have a `Limit` option and load & purge repositories in batches of 5000, we can instead load all repo names into memory at once and hand the DB connection back to the pool and _then_ delete them on disk.
A repository name might have 50 bytes, which means we'd load 5000*50 bytes into memory, which is 500kb, which is _fine_, I think, in cases where we have 5000+ repos to delete. It's …
> gitserver: do not hold connection when reading repos for purging

- client/web/src/enterprise/batches/DropdownButton.module.scss
- client/web/src/enterprise/batches/DropdownButton.tsx
Closes #58447
A UI regression was introduced some time ago that caused disabled buttons in the DropDownButton to not be styled differently. This PR fixes that by adding styles for disabled state for a MenuItem.
Manual testing
> code-search: properly display disabled bulk operations

- deps.bzl
- go.mod
- go.sum
This bumps the Zoekt version to pull in a fix to limit shard parallelism when
`SRC_INDEX_CONCURRENCY` is set. It's super are to set this environment
variable, so this should only really affect dot com once we roll it out there.
This commit was generated by running `./dev/zoekt/update`. Notable changes:
https://github.com/sourcegraph/zoekt/compare/137eb8f22610...0959170c1623
- https://github.com/sourcegraph/zoekt/commit/c02b6e0f52 matchtree: always use evalMatchTree
- https://github.com/sourcegraph/zoekt/commit/7c14b93bdf ctags: require scip-ctags to be present
- https://github.com/sourcegraph/zoekt/commit/ef907c2371 Indexing: limit shard parallelism when index concurrency is set
- https://github.com/sourcegraph/zoekt/commit/2a4f4a4265 Indexing: improve doc content checks
Zoekt and …
> gomod: bump Zoekt for index concurrency change

- cmd/gitserver/internal/integration_tests/mocks.go
- cmd/gitserver/internal/lock.go
- cmd/gitserver/shared/debug.go
- cmd/gitserver/shared/service.go
- cmd/gitserver/shared/shared.go
There's little insight into what's currently being done by the syncer, so adding this endpoint as a stopgap until we have a DB backed queue and more insight for free through that.
Tested manually locally.
> gitserver: Add debug endpoint to inspect repository locker

- internal/highlight/language.go
Lets us detect local references using the tree-sitter grammar for Java
Locally tested with the following patch:
```patch
diff --git a/client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts b/client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts
index 7c45907c51..84c9594549 100644
--- a/client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts
+++ b/client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts
@@ -141,6 +141,7 @@ export async function searchBasedReferences({
occurrence.symbol?.startsWith('local ') &&
occurrence.range.contains(new ScipPosition(position.line, position.character))
) {
+                debugger;
return occurrences
.filter(reference => reference.symbol === occurrence.symbol)
.map(reference => ({
```
Steps:
1. Add …
> enables tree-sitter based references for Java

- client/branded/src/search-ui/results/progress/exhaustive-search/exhaustive-search-validation.test.ts
- client/branded/src/search-ui/results/progress/exhaustive-search/exhaustive-search-validation.ts
- doc/code_search/how-to/search-jobs.md
- internal/search/job/jobutil/exhaustive_job.go
- internal/search/job/jobutil/exhaustive_job_test.go
We allow repo predicates for Search Jobs by removing the corresponding validation checks. At the same time we improve the checks against file predicates.
We now support the following **repo** predicates:
- .has.meta
- .has.file
- .has.content
- .has.path
- .has.commit.after
- .has.description
Notes:
- Why don't we allow file predicates? `file:has.content()` is translated to an AND query in our (query parsing) job layer. In Search Jobs we don't call this code path. A quick copy&paste hack let to Search Jobs breaking in unexpected ways. Hence I want to leave file predicates to a separate investigation and PR.
- The validation in the client and backend are not 100% identical which is a trade-off we accepted for the EAP. The plan is to remove the client validation soon and instead call out to …
> search jobs: allow repo: predicates

- internal/codeintel/uploads/internal/store/summary.go
- internal/database/schema.json
- internal/database/schema.md
- migrations/frontend/1695152835_add_index_for_upload_indexers/down.sql
- migrations/frontend/1695152835_add_index_for_upload_indexers/metadata.yaml
- migrations/frontend/1695152835_add_index_for_upload_indexers/up.sql
- migrations/frontend/1695152902_add_index_for_index_indexers/down.sql
- migrations/frontend/1695152902_add_index_for_index_indexers/metadata.yaml
- migrations/frontend/1695152902_add_index_for_index_indexers/up.sql
- migrations/frontend/squashed.sql
Fix the slow "list indexers" GraphQL endpoint, which is especially problematic on the upload/index list view when not scoped to a particular repository.
Created indexes in dotcom and hand-tested that new queries use the proper index.
> codeintel: Improve GetIndexers method

- client/web/src/cody/chat/CodyChatPage.tsx
- client/web/src/featureFlags/featureFlags.ts
Adds and evaluates a mock feature flag for the Cody chat A/A test. This will help us construct metrics to evaluate chat performance and verify that results are consistent between both groups.
- Logged the feature flag with different users to verify it evaluated to different values (for a 50/50 rollout feature flag)
> cody web: evaluate the mock feature flag

- client/web/src/nav/GlobalNavbar.tsx
- client/web/src/nav/UserNavItem.tsx
- client/web/src/storm/pages/SearchPage/SearchPageFooter.tsx
Updates the most prominent marketing links (on sourcegraph.com/search) from about.sourcegraph.com to sourcegraph.com.
Link changes only.
> Update marketing homepage links from PCS

- deps.bzl
- go.mod
- go.sum
- internal/requestclient/BUILD.bazel
- internal/requestclient/client.go
- internal/requestclient/client_test.go
- internal/requestclient/geolocation/BUILD.bazel
- internal/requestclient/geolocation/data/README.md
- internal/requestclient/geolocation/geolocation.go
- internal/requestclient/geolocation/geolocation_test.go
- internal/requestclient/grpc_test.go
- internal/requestclient/http.go
This change adds country-level geolocation data to `requestclient` as discussed [here](https://sourcegraph.slack.com/archives/C01PQEVJ5A9/p1700078374822459?thread_ts=1694717740.084639&cid=C01PQEVJ5A9), provided as a 2- or 3-character ISO 3166-1 country code that seems pretty widely used. The inference strategy goes:
1. If we are behind Cloudflare, we trust [Cloudflare's originating country data](https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#cf-ipcountry) and use it as-is
2. If a `Forwarded-For` exists, we look up the first `(*requestclient.Client).Forwarded-For` address in the embedded IP geolocation database
3. Otherwise, we look up `(*requestclient.Client).IP` in the embedded IP geolocation database
WE use [DB-IP.com](https://db-ip.com/)'s ["IP to …
> [Backport 5.2] requestclient: add country-level geolocation data (#58386)

- cmd/frontend/graphqlbackend/user.go
- cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
- cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
- internal/conf/computed.go
- internal/conf/conftypes/consts.go
- schema/schema.go
- schema/site.schema.json
Adds four new config items ({chat, code completions} x {Community, Pro} = 4).
Using `user.CodyProEnabledAt` to determine the user's plan.
Returns the matching limit and interval based on this.
The requirement for the interval is "from the Nth day of this month until the Nth day of the next month", which the current architecture doesn't support, so I'm just using a 30-day interval to indicate "1 month", and the Cody Gateway side will need to recognize this and apply the "Nth-to-Nth" logic.
Currently, it's feature-flagged with `cody-pro-dec-ga`, which is off, so we're good to test this later.
> SSC: Rate limit based on the user's plan

- .eslintrc.js
Spotted another file section of client code that should be ignored by eslint
CI and should not see `Eslint Oops` message
> eslint: ignore client/web/dev and friends

- internal/licensing/data.go
Follow-up to #58326
Removes the now-unused `ExpiredFeatures`.
Unused code.
> Remove ExpiredFeatures from licenses since they're now unused

- client/shared/dev/BUILD.bazel
- client/web/src/integration/BUILD.bazel
Causes failure as this build https://buildkite.com/sourcegraph/sourcegraph/builds/252077. More context [here](https://sourcegraph.slack.com/archives/C05EVRLQEUR/p1700737212337599) 
[main-dry-run](https://buildkite.com/sourcegraph/sourcegraph/builds/252089#_) and ci
> ci: add @percy/puppeteer explicity to `run_percy_with_mocha` target

- cmd/frontend/graphqlbackend/outbound_webhooks.go
This PR brings back previously removed code from the frontend, to show the user a nice error message. 
Tested locally, no longer creates the webhook.
> sec: Show error message to user before creating webhook

- dev/managedservicesplatform/terraformcloud/terraformcloud.go
- dev/sg/msp/sg_msp.go
Provisioned by https://github.com/sourcegraph/infrastructure/pull/5631
The idea is to have operators request membership to the new team via Entitle to get access to MSP workspaces. Will document in a follow-up.
This change also adds a `-all` guard for syncing all environment TFC workspaces, similar to the one for `sg msp generate`.
n/a
> msp: add artificial operators team to generated workspaces

- client/web/src/enterprise/codeintel/searchBased.ts
- client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts
The separation of the logic into different functions makes it clearer
what the order of searches is. It also makes it clearer that for some
reason, we're only using the locals information from the SCIP
Document for 'Find references', and not for 'Go to definition'.
Using the SCIP Document for for 'Go to definition' too could avoid
a network request.
TODO:
> client: Minor cleanup for search-based code intel

- cmd/gitserver/internal/cleanup.go
The janitor process is currently very very silent and it's hard to know if it's even doing anything. Until we make it a proper worker with proper reporting, I suggest we add a bit more logs here to understand what it does.
Manually verified that the logs look good.
> gitserver: More logging in janitor

- dev/global-settings.json
- schema/settings.schema.json
We add "newStandardRC1" to the list of allowed values for pattern types in the settings schema. At the same time we set the default for the local dev environment.
Once this is merged we can update the global settings for S2 as well.
The new behavior for S2 and local will be like this:
- All searches will be made in the "precise (NEW)" mode
- Users can quickly switch between different modes (smart, precise (legacy), precice (NEW)) by using the smart search toggle
- The choice is only persisted for the current session
- Users can permanently opt out in their user settings
Why?
Currently, "smart search" is hardcoded as default. However it can be overwritten by settings. The idea is to set "precise (NEW)" as new default for Sourcegraph instances (local and s2) in global settings. Users can …
> search: add new pattern type to settings schema

- CHANGELOG.md
- cmd/frontend/backend/external_services_test.go
- cmd/gitserver/internal/cloneurl/clone_url.go
- doc/admin/external_service/bitbucket_cloud.md
- internal/authz/providers/authz_test.go
- internal/batches/sources/bitbucketcloud.go
- internal/extsvc/bitbucketcloud/client.go
- internal/repos/bitbucketcloud.go
- internal/repos/bitbucketcloud_test.go
- internal/repos/testdata/sources/BITBUCKETCLOUD-LIST-REPOS/with-access-token.yaml
- internal/types/secret.go
- schema/bitbucket_cloud.schema.json
- schema/schema.go
Closes #58321 
This PR adds support for Bitbucket Cloud Premium Workspace access tokens.
A new code host config option is added: `accessToken`, and when set instead of `username` and `appPassword`, will be used to sync and clone repositories.
VCR test added.
[Preview Link](https://docs.sourcegraph.com/@pjlast/58321-support-bitbucket-cloud-access-tokens)
> [bitbucket cloud] Support workspace access tokens

- .aspect/bazelrc/ci.sourcegraph.bazelrc
Bazel 6.3.0 introduced a change where `common` could be set in bazelrc and Bazel applies the flag to all commands the flag is valid for. This change uses that feature in the CI bazelrc so that all flags apply to both `bazel test` and `bazel build`. Warming calls `bazel build` and it is [broken on main](https://buildkite.com/sourcegraph/warming-aspect-workflow-sourcegraph/builds/82) since 3 required env vars set in the CI bazelrc are scoped to just the `bazel test` command:
```
test --define=E2E_HEADLESS=false
test --define=E2E_SOURCEGRAPH_BASE_URL="http://127.0.0.1:7080"
test --define=DISPLAY=:99
```
CI & run warming on this commit manually https://buildkite.com/sourcegraph/warming-aspect-workflow-sourcegraph/builds/83
> build: fix CI bazelrc settings for Aspect Workflows warming

- dev/ci/internal/ci/bazel_operations.go
`//client/web:bundle` is marked exclusive so it will be built on it's own if required
CI
> bazel: build client web is exclusive so not required to prebuild

- cmd/repo-updater/shared/main.go
Realistically, in the past it never got to a steady state because it just waits for too long. Trying to sync at most one a second seems fine to me, let's try it.
Will monitor grafana after rollout.
> dotcom: Make repo with last errors syncer faster

- internal/httpcli/client.go
For local development we require localhost, for instance for Cody Gateway. We now add a check to make sure we don't block localhost access from when `INSECURE_DEV` is set to `true`. 
> sec: Allow localdev to connect to localhost

- .gitignore
- client/shared/dev/generateCssModulesTypes.ts
Sometimes you just want to make a `.module.css` file not a `.module.scss` file. Sometimes you just want to style it old-school.
CI
> generate .css.d.ts for non-SCSS (plain .css) files as well

- cmd/gitserver/internal/gitservice.go
We tested this forever on dotcom and no issue with it. Let's bump it here.
Was tested on dotcom for a while.
> Backport setting for gitserver bandwidth from sourcegraph.com

- client/web/src/components/externalServices/ExternalServiceNode.tsx
In the list of external services, for services that are overdue on scheduling, or are currently syncing but haven't finished yet we show things like "Next sync scheduled 30 minutes ago". This makes it a little less confusing as to what that means by saying "Next sync scheduled now" instead.
Manually tested.
> Don't show time in the past for next sync at

- internal/repos/syncer.go
In the code host syncing stats, repos that were "undeleted" from our soft-deletion state on sync showed up as modified which feels weird. This fixes it and makes it so that they get counted as added repos instead.
CI and manually verified that they now show in the UI correctly.
> Fix soft deleted repos revived appearing as modifed

- internal/database/dbmocks/mocks_temp.go
- internal/database/external_services.go
- internal/database/external_services_test.go
- internal/repos/sync_worker.go
Before we deleted anything completed older than a day. That doesn't give a good amount of insight into what's happening and keeping a few hundred records around isn't very costly. 
So now instead of just deleting everything older than a day, we delete everything older than 30d. 
To protect against table bloat, we also additionally only keep up to the 100 most recent records per external service.
Added unit tests.
> Improve retention logic for code host sync jobs

- dev/tool_deps.bzl
- dev/tools/BUILD.bazel
As I was looking at migrating to bazel some scripts involving packer, we also need `gcloud` in there, which ultimately is also needed for local tooling. 
CI + local:
Running `gsutil` exactly like I would normally yields the same output: 
```
~/work/other U jh/bzl-gcloud $ bazel run //dev/tools:gsutil -- ls gs://schemas-migrations/dist/schemas-v5.2.1.tar.gz
INFO: Analyzed target //dev/tools:gsutil (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //dev/tools:gsutil up-to-date:
bazel-bin/dev/tools/gsutil
Aspect @rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of //dev/tools:gsutil up-to-date (nothing to build)
INFO: Elapsed time: 0.119s, Critical Path: 0.02s
INFO: 5 processes: 5 internal.
INFO: Build completed successfully, 5 total actions
INFO: Running …
```
> bzl: add gcloud/gsutil to //dev/tools

- cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
- internal/conf/computed.go
- internal/conf/conftypes/consts.go
- schema/schema.go
- schema/site.schema.json
- Added two new config items for the embeddings limit for Community+Pro users.
- We're now passing the values to Gateway instead of the hard-coded values on Dotcom with the `cody-pro` feature flag _on_, otherwise falling back to the old hard-coded values.
- Clarified the descriptions for rate limiting-related config items.
I've set the limits in the site config. I've verified that when I run [this GraphQL query](https://sourcegraph.test:3443/api/console#%7B%22query%22%3A%22query%20CodyGatewayAccess(%24token%3AString!)%20%7B%5Cn%20%20dotcom%20%7B%5Cn%20%20%20%20codyGatewayDotcomUserByToken(token%3A%20%24token)%20%7B%5Cn%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20username%5Cn%20%20%20%20%20%20codyGatewayAccess%20%7B%5Cn%20%20%20%20%20%20%20%20enabled%5Cn%20%20%20%20%20%20%20%20embeddingsRat …
> PLG: Add embeddings rate limits

- deps.bzl
- dev/sg/ci/subcommands.go
- dev/sg/msp/repo/repo.go
- dev/sg/msp/sg_msp.go
- dev/sg/sg_generate.go
- dev/sg/sg_lint.go
- dev/sg/sg_live.go
- dev/sg/sg_run.go
- dev/sg/sg_secret.go
- dev/sg/sg_start.go
- dev/sg/sg_tests.go
- go.mod
- go.sum
- lib/cliutil/completions/options.go
- monitoring/command/generate.go
Improves positional completions added for `sg msp` in #58538 by checking for partial flag input (`-` and `--`), which now complete flags correctly, and also improving the way we build positional argument completions with a more robust helper, `completions.CompletePositionalArgs`.
I found a bug as well upstream, https://github.com/urfave/cli/issues/1822, but I won't be investigating that further
Playing around with various completions combos locally
> sg: improve positional completions

- lib/managedservicesplatform/runtime/contract.go
Adds the Redis endpoint provisioned by MSP. In MSP, this is just a simple string, with networking/TLS/etc already provisioned on the instance, so the configuration is just a string (unlike Cloud SQL, where we use IAM auth in #58420).
n/a
> msp/runtime: add Redis address

- cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
Add code completion models to App / PLG user allowlist.
Only add models that account for [>0.1% of total traffic](https://redash.sgdev.org/queries/217/source).
> Add code completion models used by PLG

- dev/ci/gen-pipeline.go
It's quite useful to see what will be the `$VERSION` when previewing a pipeline, and it's a really easy change.
Locally tested + CI 
```
~/work/other U main $ sg ci preview
If the current branch were to be pushed, the following pipeline would be run:
• Detected run type: Main branch                                                                                                                                                            
• Detected diffs: None                                                                                                                                                                      
• Computed variables: …
```
> ci: preview commands show computed VERSION

- cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
- internal/conf/computed.go
- internal/conf/conftypes/consts.go
- schema/schema.go
- schema/site.schema.json
- Renamed the existing four config items to make it more explicit that they pertain to LLM requests
- Added four new config items that limit interactions.
The new set of constants is not used yet.
Not much to test on this: the old ones are covered by CI, and the new constants are not used yet.
> PLG: Add config items for interaction-based limits

- internal/completions/httpapi/BUILD.bazel
- internal/completions/httpapi/handler.go
The logic I introduced is:
- IF the `cody-pro` feature flag is enabled
- AND we're on dotcom
- AND the completions provider is Cody Gateway
- THEN pass the user's access token to Gateway instead of the default access token in the site config.
- ELSE just do what we did before this PR
I logged the access token on the Cody Gateway side; it was the correct one with the feature flag on and off, and Gateway gave me correct responses.
> SSC: Use the user's access token for Gateway on dotcom

- client/shared/src/settings/settings.tsx
- client/web/src/repo/RepoRevisionSidebar.tsx
Before, if a user refreshed the blobview after navigating to a file from the file tree, the full tree context would disappear, leading to a frustrating experience for some users. 
Now, users can choose if they'd like to show the full context of the file tree or not. See video: 
https://www.loom.com/share/afdea775679945fd9b42a4cfc817edb0
1. Manual testing
> Code Navigation: show full tree context

- client/shared/src/codeintel/legacy-extensions/lsif/providers.ts
- client/shared/src/codeintel/legacy-extensions/lsif/stencil.ts
- client/shared/src/codeintel/legacy-extensions/search/providers.test.ts
- client/shared/src/codeintel/legacy-extensions/util/api.ts
- client/web/src/integration/codemirror-blob-view.test.ts
These introspection queries are leftover from a time when this code was in extensions and we didn't know what version of the server was running. Now that it is part of the bundled javascript, we can remove the GraphQL introspection since we can guarantee we've got the version as the server. 
CI and some clicking/hovering around
> Code intel: remove introspection queries

- client/web/src/cody/management/CodyManagementPage.tsx
- client/web/src/cody/subscription/queries.tsx
- cmd/frontend/graphqlbackend/schema.graphql
- cmd/frontend/graphqlbackend/user.go
This PR links the Cody Manage page UI with the usage metrics API merged previously. It additionally adds an API exposing limits as well. 
- chat with cody on any client connected to sg instance running in dotcom mode
- check /cody/manage for counters
> Add Cody Usage Metrics

- internal/completions/client/codygateway/codygateway.go
Some discussion around transport misuse in https://github.com/sourcegraph/sourcegraph/pull/58016#discussion_r1397367483 caused me to preemptively add `req.Clone` calls in our transport implementations to adhere by Go documentation to not mutate requests in RoundTripper. This broke the actor propagation to Cody Gateway because so far, it has only worked by _accidentally_ using a mutated request, and with cloning, the original request is not mutated to include the appropriate headers.
This change correctly uses the parameterized request in the Cody Gateway client, which has been cloned and mutated by the actor transport.
There is an outstanding TODO here that I never addressed for why we are using this hack - will revisit after https://github.com/sourcegraph/sourcegraph/pull/58279
There are …
> completions/codygateway: fix actor propagation

- dev/oci_deps.bzl
Auto-update Wolfi base image hashes at 2023-11-28 03:10:20 UTC
Co-authored-by: Buildkite <buildkite@sourcegraph.com>
Co-authored-by: Mohammad Alam <mohammad.alam@sourcegraph.com>
(cherry picked from commit 411e0b7cb5a4ac1a3be4f589a06aedd211436b5c)
This PR updates wolfi base images but keeps the 2 images that are using a stable version of p4-fusion
CI checks pass
CVE check to resolve any pending CVEs
> Auto-update Wolfi base images to latest (#58322)

- .github/workflows/licenses-check.yml
- .github/workflows/pr-auditor.yml
- .github/workflows/sg-binary-release.yml
- .github/workflows/sg-setup.yml
closes https://github.com/sourcegraph/devx-support/issues/414
it started breaking since https://github.com/sourcegraph/sourcegraph/pull/58617
```
../../internal/authz/perms.go:4:2: package cmp is not in GOROOT (/opt/hostedtoolcache/go/1.20.8/x64/src/cmp)
```
n/a
> ci: bump go to 1.21 in gitub actions

- doc/code_search/reference/language.md
- internal/search/query/predicate.go
The language reference listed [deprecated tags](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dd29aab51d64de31fa265ac04c0536af47f4451c/-/blob/client/shared/src/search/query/hover.ts?L225-232), such as `has` and `has.key`, but missed the `has.meta` predicate which replaces both.
Test plan:
- I verified that both links for the examples work
[Preview Link](https://docs.sourcegraph.com/@sh/update-predicate-docs)
> docs: update docs for repo predicates

- dev/ci/internal/buildkite/buildkite.go
- dev/ci/internal/ci/bazel_operations.go
- dev/ci/internal/ci/operations.go
- dev/ci/internal/ci/pipeline.go
- dev/ci/internal/ci/wolfi_operations.go
In addition to the normal aspect workflow steps, we aslo want to run our normal pipeline steps so that it is siimilar to our main pipeline.
Poor out one for my homies ... Aspect steps done in under 3 mins and then our steps came 📈 
Altered the steps of the Aspect pipeline as per the following
```yaml
steps:
- key: aspect-workflows-setup
label: ":aspect: Setup Aspect Workflows"
commands:
- "rosetta steps | buildkite-agent pipeline upload"
agents:
queue: aspect-default
- key: sg-gen-pipeline
label: ":pipeline: Generate pipeline"
if: build.branch == "wb/bazel-aspect/gen-pipeline"
commands:
- "./dev/ci/gen-pipeline.sh"
agents:
queue: bazel
env:
ASPECT_WORKFLOWS_BUILD: "1"
```
> aspect+ci: omit bazel tests when running as part of the aspect workflow pipeline

- deps.bzl
- go.mod
- go.sum
Contains the following changes:
https://github.com/sourcegraph/zoekt/compare/d982320abe7b...0d03621d45a3
- https://github.com/sourcegraph/zoekt/commit/5c51794c39 Indexing: use one ctags process per shard
- https://github.com/sourcegraph/zoekt/commit/8abf874fe1 gomod: require go1.21
- https://github.com/sourcegraph/zoekt/commit/0d03621d45 revert use of mmap-go
Test Plan: tested on zoekt CI and this one
> gomod: update zoekt to include go.mod 1.21 requirement

- sg.config.yaml
Looks like when we got rid of the enterprise dir, it left a duplicate entry in `watch` for symbols.
N/A
> sg: remove duplicate watch target

- client/web/src/repo/RepoRevisionSidebarFileTree.module.scss
- client/web/src/repo/RepoRevisionSidebarFileTree.tsx
- client/web/src/repo/tree/TreePagePanels.tsx
- client/web/src/repo/utils.test.ts
- client/web/src/repo/utils.tsx
This PR fixes two bugs.
1) Before, the test indicator caused some strange positioning behavior with the actual file names. Now, it behaves as expected.
2) Before, folder names that happened to be named the same as a valid file extension (nix, js, ts, etc.) appeared with language icons instead of the directory icon. This has been fixed.  
Manual testing
> Code Navigation: fix test indicator positioning

- .eslintrc.js
It seems the correct config is actually `EXPERIMENTAL_useProjectService`, as documented in https://typescript-eslint.io/blog/parser-options-project-true#project-services. The former was "working" because of the `process.env.TYPESCRIPT_ESLINT_EXPERIMENTAL_TSSERVER = 'true'` line.
CI
> fix useProjectService TypeScript ESLint config

- CHANGELOG.md
- cmd/gitserver/internal/cloneurl/clone_url.go
- cmd/gitserver/internal/cloneurl/clone_url_test.go
- internal/batches/sources/azuredevops_test.go
- internal/extsvc/azuredevops/types.go
- internal/repos/azuredevops.go
- schema/azuredevops.schema.json
- schema/schema.go
In line with other code hosts, adding SSH clone support here via gitURLType.
Verified locally by configuring it and seeing a repo clone successfully via ssh.
> azuredevops: Add support for SSH cloning

- dev/ci/bazel-prechecks-apply.sh
- dev/ci/internal/ci/bazel_operations.go
- dev/ci/internal/ci/pipeline.go
Need to update the dependent keys otherwise you run into this scenario where steps wait indefinitely
CI + main-dry-run
> aspect: use different dep step key if running as part of aspect

- .aspect/workflows/bazelrc
- .aspect/workflows/config.yaml
There is a Workflows issue with `--bazelrc=.aspect/workflows/bazelrc` not being applied to all bazel invocations. This will work-around that issue. Will be fixed in Workflows in a future release.
Check that these bazel flags are applied on all bazel invocations.
> aspect: work-around flags issue with .aspect/workflows/bazelrc

- client/web/src/repo/RepoRevisionSidebarFileTree.tsx
This makes a couple of changes to minimize the number of requests we make for the file sidebar.
Previously, we would make an initial request to populate the root level of the file tree. However, we would immediately make a followup `ancestors` request to fully-populate the tree down to the level that we've selected. I think this might be a recent regresion. For reasons I don't quite understand, this also caused us to re-run the initial query in `useQuery`. I expect it has to do with the second request busting the cache so that when we re-render, the initial response isn't in apollo's cache. 
This modifies the initial data loading query to 1) target `filePath` rather than `initialFilePath` so that we get everything we need to render the full file tree and 2) set `ancestors` when we're …
> File sidebar: minimize fetches

- client/web/src/routes.tsx
- cmd/frontend/internal/codemonitors/resolvers/BUILD.bazel
- cmd/frontend/internal/codemonitors/resolvers/resolvers.go
This removes the code monitors page from sourcegraph.com and adds a check to all code monitor mutations. It still allows code monitor queries because it's cheap to keep read access active via the API, and it lets people still export their monitors if needed.
Part of https://github.com/sourcegraph/sourcegraph/issues/57539
As a followup, I plan to truncate the code monitor execution tables. I will maintain the code monitor definition tables so people can continue to export via the API and they are cheap to keep around.
Tested that `/code-monitors` 404s in dotcom mode, and behaves normally in normal mode.
> Chore: disable monitors on dotcom

- dev/tool_deps.bzl
While working on executors + bazel, stumbled across this which has not been updated for a while. 
CI + `bazel query` all arch variants to validate the checksums.
> bzl: bump src-cli to 5.2.1

- dev/nix/nodejs.nix
- flake.lock
Update flake so that we can use clang 16 on darwin
* nix develop
```
clang --version
clang version 16.0.6
Target: arm64-apple-darwin
Thread model: posix
InstalledDir: /nix/store/a5v30qll5i02vr9y97bk1rdx3mm6kvlm-clang-16.0.6/bin
```
> nix: update flake for clang 16 and assert typescript 5.3.2

- docker-images/executor-vm/BUILD.bazel
We spotted a typo with @burmudar that was real hard to catch during a review. It has no incidence on the final image name that gets pushed, but during the build, it's incorrect. 
CI
> bzl: fix repo name for executor-vm

- cmd/worker/internal/repostatistics/BUILD.bazel
- cmd/worker/internal/repostatistics/compactor.go
- cmd/worker/internal/repostatistics/resetter.go
- cmd/worker/shared/main.go
- doc/admin/workers.md
- internal/database/dbmocks/mocks_temp.go
- internal/database/repo_statistics.go
- internal/database/repo_statistics_test.go
We've noticed over the past year that sometimes there can be drift in the `repo_statistics` and `gitserver_repo_statistics` tables. We still don't know why, our strongest hypothesis is that it's because someone hand-modifies the `repo` table.
In any case: it doesn't hurt to make the statistics self-repairing.
The only downside is that the worker requires an exclusive lock on the `repo` and `gitserver_repos` tables, which are some of our busiest tables.
That's why we only run it when the instance is presumably _not_ busy and we also use a 5min timeout.
- Unit tests
- Manually ran the worker every 1s to make sure it doesn't run
[Preview Link](https://docs.sourcegraph.com/@mrn/recreate-repo-statistics)
> Recreate repo statistics every Sunday morning

- internal/database/repo_statistics.go
- internal/database/repo_statistics_test.go
This is an edge case, because we should always have `0` values in the table, but maybe sometimes we don't due to manual editing or something. So let's be on the safe side.
- Manual testing of both queries in SQL console
- Unit tests
> repo statistics: coalesce when compacting table

- docker-images/dind/Dockerfile
Potential fix for security vulnerability - uses the very recently published https://hub.docker.com/layers/library/docker/24.0.7-dind/images/sha256-4c92bd9328191f76e8eec6592ceb2e248aa7406dfc9505870812cf8ebee9326a?context=explore
CI
> docker-images/dind: upgrade to 24.0.7

- internal/completions/httpapi/chat.go
- internal/completions/httpapi/codecompletion.go
- internal/completions/httpapi/handler.go
Closes https://github.com/sourcegraph/sourcegraph/issues/58283
The new header is only added in case of dotcom when `cody-pro` is on.
Clients can recognize this and can show the Upgrade button accordingly.
I haven't been able to test TBH because of the issues with hanging requests on my local instance. @thenamankumar, could you execute this test plan for me?
1. Run `sg start dotcom`, set the `cody-pro` feature flag to `false` for your user
2. Run this curl in another terminal and get a response successfully:
```
curl --location 'https://sourcegraph.test:3443/.api/completions/code' \
--header 'Authorization: token {TODO ADD A VALID TOKEN HERE FOR YOUR USER}' \
--header 'Content-Type: application/json; charset=utf-8' \
--header 'X-Sourcegraph-Should-Trace: false' \
--header 'Cookie: …
```
> SSC: Add x-is-cody-pro-user header

- cmd/frontend/graphqlbackend/user.go
- cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
- internal/completions/httpapi/limiter.go
This PR creates the `rate-limits-exceeded-for-testing` feature flag and applies a limit=1 with interval=max(int32) for users that have the FF. This override takes precedence over all other types of limits, and applies both on dotcom and Cody Gateway.
@thenamankumar, please test this or let's test it together—again I'm not sure why, but my cURL requests to Gateway hang.
My test plan would be this:
- Enable feature flag
- Make sure the rate limit errors get triggered consistently. Test code completions, chat, and embeddings
- Disable feature flag
- Make sure rate limit errors don't get triggered
Note that Gateway-side caching might mess things up during this testing.
> SSC: Add "rate limits exceeded" feature flag to aid client testing

- deps.bzl
- go.mod
- go.sum
- lib/go.mod
This PR bumps up go grpc to 1.57.1 
CI Tests
> bumping go grpc to 1.57.1

- dev/sg/generates.go
Previously it would always report 0s for Bazel, even though it takes way longer than that (and many more cores :P).
This change returns the report as-is which means the duration reporting is correct.
- Run `go run ./dev/sg generate` and see `✅ Target "bazel" done (116s)`
> sg generate: report duration for bazel step

- internal/search/exhaustive/service/searcher.go
- internal/search/exhaustive/service/searcher_test.go
This fixes a bug which caused search jobs validation to return an error if a user specified an explicit `type:file` filter in the query.
Test plan:
new unit test
> search jobs: allow explicit type:file

- cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
- cmd/cody-gateway/internal/actor/source.go
- cmd/cody-gateway/internal/actor/source_test.go
- cmd/cody-gateway/internal/httpapi/featurelimiter/BUILD.bazel
- cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
- cmd/cody-gateway/internal/httpapi/handler.go
- cmd/cody-gateway/shared/main.go
This PR adds a `/v1/limits/refresh` API endpoint to Cody Gateway, allowing an authenticated user to trigger a refresh of their limit (bypassing the Cody Gateway cache), [context](https://sourcegraph.slack.com/archives/C05SZB829D0/p1701364254661389?thread_ts=1701187278.753019&cid=C05SZB829D0). This endpoint:
- doesn't accept any parameters or return any values
- blocks until the refresh is complete
- replaces a cached value with a newly read value 
-- in case of errors, the cached value is not updated
This is currently only implemented for sourcegraph.com users using a `dotcom-user` Source (i.e. not Product Subscriptions). 
As a [follow-up](https://github.com/sourcegraph/sourcegraph/issues/58734) we should make sure people don't use it to refresh the token "too often" (making …
> Allow refreshing usage limits for dotcom users

- dev/release/src/release.ts
- dev/release/src/util.ts
Since the introduction of [#57591](https://github.com/sourcegraph/sourcegraph/pull/57591) we do not need to manually populate the bazel output anymore.
If the `5.2.4` release goes on fine. We should be good.
> release: remove manual migration bazel output generation func

- internal/authz/providers/perforce/protects.go
A tiny change to use the new `clear` function in go 1.21 instead of deleting
each entry manually. This was the only place I saw where we could use it.
> Use clear map function from go 1.21

- cmd/frontend/internal/auth/githuboauth/session.go
- cmd/frontend/internal/auth/gitlaboauth/session.go
- schema/schema.go
- schema/site.schema.json
Needed for PLG QA, see https://docs.google.com/document/d/1all3z8dPs52amhNs3m4O1Lu7V6VsCaU7jXovprte-EE/edit?disco=AAABAHybed8
1. Setting `dotcom.minimumExternalAccountAge` to `36500`
1. Adding my primary email on both GitHub.com and GitLab.com to `dotocm.minimumExternalAccountAgeExemptList`, authenticated successfully.
> auth: allow exempted list from the minimumExternalAccountAge

- dev/oci_deps.bzl
Ran `sg wolfi update-hashes` to get this.
CI should find any issues this version bump could cause.
> Bump wolfi images to make use of latest p4-fusion
