doc/sla/index.md
[Preview Link](https://docs.sourcegraph.com/@eg-sla)
=> remove on-call opsgenie section on SLA page

client/jetbrains/CODENOTIFY
Removed myself from notifications.
No functional changes
=> JetBrains: Remove codenotify file

WORKSPACE
See title, maintenance update. Previous release was not working against AW agents. 
CI
=> bzl: bump oci_rules to 1.3.4

CHANGELOG.md
changelog: cut sourcegraph@5.2.0
N/A
=> changelog: add sub-sections

client/web/src/enterprise/search-jobs/SearchJobModal/SearchJobModal.tsx, client/web/src/enterprise/search-jobs/SearchJobsPage.tsx, cmd/frontend/internal/app/ui/router.go
Fixes https://github.com/sourcegraph/sourcegraph/issues/57008
Closes https://github.com/sourcegraph/sourcegraph/issues/56934
Closes some feedback about download button https://sourcegraph.slack.com/archives/C05KARB1F33/p1695321364406309
- Check that download button is always available but disabled if not results are available
- Check that you don't have any errors in the search-jobs route in the console
=> [Search Jobs] Paper cuts

cmd/telemetry-gateway/CODENOTIFY
=> chore: update mention of Core Services team handle

client/jetbrains/CHANGELOG.md, client/jetbrains/build.gradle.kts, client/jetbrains/gradle.properties
=> JetBrains: release 3.3.0

internal/database/telemetry_export_store.go
This change makes it so that the contents of `telemetry_events_export_queue` are exactly what we export, by having sensitive field redaction occur up-front as we insert the events into the database queue.
This has benefits for https://github.com/sourcegraph/sourcegraph/issues/57027 as what you see in the `telemetry_events_export_queue` is now the exact payload that leaves a Sourcegraph instance.
This is not yet GA or enabled outside of internal instances, so there is no concern for any already-queued events.
CI
=> database/telemetryexport: store messages exactly as it will be exported

doc/api/graphql/search.md
=> Added text indicating no GraphQL limitations

doc/cody/overview/enable-cody-enterprise.md
This PR adds AWS Bedrock to the list of third-party LLM providers.
Docs added.
[Preview Link](https://docs.sourcegraph.com/@add-aws-bedrock)
=> [OCT Launch] Add AWS Bedrock to LLM provider list

doc/sidebar.md, doc/sla/index.md
[Preview Link](https://docs.sourcegraph.com/@eg-prem-support)
=> add premium support doc to docs

cmd/gitserver/shared/shared.go
This code path was required for cloud v1 because we would have private repos alongside public repos, and cloud default services would usually not be able to pull those. Since we don't have private repos anymore, we can skip this check. Worst case, we will have a repo marked as private in the DB and we won't attempt to update it - which would fail anyways. But now with a no sources for X error instead.
CI.
=> gitserver: Simplify getRemoteURLFunc

wolfi-packages/qdrant.yaml
Fixes https://buildkite.com/sourcegraph/sourcegraph/builds/244641
CI
=> Qdrant: fix CI "Package dependency" check

internal/embeddings/background/repo/store.go, internal/embeddings/background/repo/store_test.go
This fixes the query for `RescheduleAllRepos` so that it correctly skips repos that have never been successfully embedded.
Added a case to existing test.
=> Qdrant: fix "RescheduleAll" query

dev/sg/internal/images/k8s.go
I overlooked an edge case, which I found while running the update command on components/executors in sourcegraph/deploy-sourcegraph-k8s. This fixes it. 
CI + `~/work/other/sgd ops update-images --kind k8s --docker-username=$DOCKER_USERNAME --docker-password=$DOCKER_PASSWORD --pin-tag 5.1.7 components/executors/`
=> sg: fix missing edge case in sg ops update-images

doc/cody/feature-reference.md, doc/sidebar.md
This document compares Cody's features and capabilities across different clients.
Docs Added
[Preview Link](https://docs.sourcegraph.com/@cody-ide-features/cody/feature-reference)
=> Add Feature Parity Reference for Cody Clients

doc/getting-started/github-vs-sourcegraph.md
[Preview Link](https://docs.sourcegraph.com/@morgangauth-patch-2)
=> Including Maedah's fix

wolfi-images/batcheshelper.yaml, wolfi-images/blobstore.yaml, wolfi-images/bundled-executor.yaml, wolfi-images/cadvisor.yaml, wolfi-images/cloud-mi2.yaml, wolfi-images/executor-kubernetes.yaml, wolfi-images/executor.yaml, wolfi-images/gitserver.yaml, wolfi-images/jaeger-agent.yaml, wolfi-images/jaeger-all-in-one.yaml, wolfi-images/node-exporter.yaml, wolfi-images/opentelemetry-collector.yaml, wolfi-images/postgres-exporter.yaml, wolfi-images/postgresql-12-codeinsights.yaml, wolfi-images/postgresql-12.yaml, wolfi-images/prometheus-gcp.yaml, wolfi-images/prometheus.yaml, wolfi-images/qdrant.yaml, wolfi-images/redis-exporter.yaml, wolfi-images/redis.yaml, wolfi-images/repo-updater.yaml, wolfi-images/search-indexer.yaml, wolfi-images/searcher.yaml, wolfi-images/server.yaml, wolfi-images/sourcegraph-base.yaml, wolfi-images/sourcegraph-dev.yaml, wolfi-images/sourcegraph.yaml, wolfi-images/symbols.yaml, wolfi-images/syntax-highlighter.yaml
Rebuilding Wolfi Image
make sure rebuilds wolfi base image
=> Rebuilding wolfi base images 5.2

dev/oci_deps.bzl
Updating hashes of images
- Green 🟢  CI Build
- Manual inspection of images
=> Wolfi update hash for Images 5.2 Release

doc/admin/updates/index.md
Local 
[Preview Link](https://docs.sourcegraph.com/@galindo-j-patch-1)
=> Update index.md to include additiona upgrade scenario

doc/cody/overview/install-jetbrains.md
Adds beta label to JB docs.
Docs added
[Preview Link](https://docs.sourcegraph.com/@maedahbatool-patch-1)
=> Remove experimental label

CHANGELOG.md
This PR adds a changelog entry for all the features added in the admin onboarding updates.
Changelog update.
=> [changelog]: adding changelog update for admin onboarding

client/branded/src/search-ui/input/LazyQueryInput.tsx, client/branded/src/search-ui/input/QueryInput.ts, client/shared/src/components/MonacoEditor.tsx, client/web/src/enterprise/insights/components/creation-ui/insight-repo-section/InsightRepoSection.tsx
=> fix misc. doc and type inconsistencies in query inputs

enterprise/cmd/worker/internal/telemetrygatewayexporter/telemetrygatewayexporter.go
Updates the defaults based on ballpark estimates originally proposed by @nathan-downs in https://docs.google.com/document/d/1qZqtacGELLa6LXqZAs7oD7XOSRCEnucUHKB8YUu6XMI/edit.
n/a
=> telemetrygatewayexporter: increase default export reate

client/web/src/site-admin/SiteAdminOnboardingTourPage.tsx, client/web/src/tour/components/Tour/TourContent.tsx
=> onboarding: Add 'Experimental' badge to tour and site admin page

enterprise/cmd/worker/internal/telemetrygatewayexporter/telemetrygatewayexporter.go
Backports default changes from https://github.com/sourcegraph/sourcegraph/pull/57221, as the [backport failed](https://github.com/sourcegraph/sourcegraph/pull/57221#issuecomment-1741582331) because a previous backport had not yet been merged yet.
cc @sourcegraph/release-guild 
n/a
=> [Backport 5.2] telemetrygatewayexporter: increase default export rates

doc/cody/overview/install-jetbrains.md
This PR adds list of IDEs Cody support with JetBrains.
Docs added
[Preview Link](https://docs.sourcegraph.com/@jb-ides)
=> [OCT Launch] Add JetBrains supported IDEs for Cody

cmd/cody-gateway/internal/httpapi/completions/anthropic.go, cmd/cody-gateway/internal/httpapi/completions/fireworks.go, cmd/cody-gateway/internal/httpapi/completions/openai.go, cmd/cody-gateway/internal/httpapi/completions/upstream.go
The current identifiers are not granular enough to pinpoint a specific user
CI
=> cody-gateway: forward identifier that includes actor ID to upstreams

doc/cody/feature-reference.md
The PR adds improvements to the feature parity docs.
Docs added
[Preview Link](https://docs.sourcegraph.com/@imp-feature-parity/cody/feature-reference)
=> [OCT Launch] Improvements to Cody Clients Feature Parity docs

CHANGELOG.md
Part of https://github.com/sourcegraph/sourcegraph/issues/56907
n/a
=> release: formalize 5.2.0 CHANGELOG

.github/test.CODEOWNERS, .github/workflows/label-notify.yml
Until next time, dear fella :)
n/a
=> Stop pinging efritz

CHANGELOG.md
linking to the new doc page
Test plan:
N/A
=> search jobs: add changelog entry

.github/workflows/universal-ctags.yml, dev/nix/ctags.nix
Fix push branch target
This workflow should run once the branch is merged to main
=> ctags: fix push branch target

doc/cody/overview/install-neovim.md, doc/sidebar.md
This PR adds docs updates for the Cody Client — Neovim extension. It adds a new section called "Cody for Neovim" and explains the entire setup, installation and configuration.
Docs added
[Preview Link](https://docs.sourcegraph.com/@cody-neovim/cody/overview/install-neovim)
=> [OCT Launch] Cody Client: Docs updates for Neovim

docker-images/syntax-highlighter/crates/sg-syntax/src/sg_sciptect.rs, docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__off-by-one.yaml.snap, docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/syntect_files/off-by-one.yaml
Closes #57043 I believe
Snapshot tests passing locally.
=> Fix syntect scip off-by-one

doc/cody/feature-reference.md
Updated the feature parity matrix to align with JB updates coming in today's release. 
n/a docs update 
[Preview Link](https://docs.sourcegraph.com/@taylorsperry-patch-3)
=> Docs: Update feature parity matrix

dev/codeintel-qa/cmd/clone-and-index/main.go
=> chore: Delete commented out code

flake.lock, shell.nix
=> nix: use go1.21

client/extension-api/BUILD.bazel, client/extension-api/package.json, client/extension-api/src/index.js, client/extension-api/tsconfig.json
=> remove client/extension-api stub

dev/ci/internal/ci/operations.go, doc/dev/background-information/ci/reference.md
Failure example: https://buildkite.com/sourcegraph/sourcegraph/builds/246235#018b0c9a-38be-43ed-af9e-d8cf04ab7305
CI
=> temporarily disable Chromatic upload that is failing on main

client/storybook/src/main.ts, dev/ci/internal/ci/operations.go, doc/dev/background-information/ci/reference.md
This reverts commit 4c23391014ecbc0159e5c64f55e95f8de9cef718 and adds a workaround to the Storybook Vite configuration to make it work.
CI
[Preview Link](https://docs.sourcegraph.com/@sqs/fix-chromatic-build)
=> Revert "temporarily disable Chromatic upload that is failing on main (#57455)"

cmd/embeddings/shared/main.go, cmd/frontend/internal/authz/BUILD.bazel, cmd/frontend/internal/authz/init.go, cmd/gitserver/internal/integration_tests/tree_test.go, cmd/gitserver/shared/shared.go, cmd/precise-code-intel-worker/shared/shared.go, cmd/repo-updater/shared/main.go, cmd/worker/shared/main.go, internal/authz/providers/authz.go, internal/authz/providers/authz_test.go, internal/authz/providers/bitbucketcloud/provider_test.go, internal/authz/providers/perforce/protects_test.go, internal/authz/subrepoperms/sub_repo_perms.go, internal/authz/subrepoperms/sub_repo_perms_test.go, internal/search/symbol/symbol_test.go
See inline comment, there's no good reason to make this so complicated. So simplifying here.
CI.
=> authz: Don't return error for subrepoperm constructor

dev/codehost_testing/BUILD.bazel, dev/codehost_testing/README.md, dev/codehost_testing/example/BUILD.bazel, dev/codehost_testing/example/example_test.go, dev/codehost_testing/github_client.go, dev/codehost_testing/org.go, dev/codehost_testing/repo.go, dev/codehost_testing/scenario.go, dev/codehost_testing/scenario_test.go, dev/codehost_testing/team.go
add actions to create github teams and assign users to those teams. Also
added actions to remove added teams.
tested in wb/e2e/poc
=> e2e tst: add actions to create github teams

dev/codehost_testing/BUILD.bazel, dev/codehost_testing/README.md, dev/codehost_testing/config/config.go, dev/codehost_testing/example/BUILD.bazel, dev/codehost_testing/example/example_test.go, dev/codehost_testing/github_client.go, dev/codehost_testing/org.go, dev/codehost_testing/repo.go, dev/codehost_testing/scenario.go, dev/codehost_testing/scenario_test.go, dev/codehost_testing/team.go, dev/codehost_testing/user.go
Add actions to create github org and also to tear it down
tested in wb/e2e/poc
=> e2e tst: add actions to create github org

CHANGELOG.md
https://github.com/sourcegraph/sourcegraph/pull/57318
cc @keegancsmith https://github.com/sourcegraph/sourcegraph/pull/57346#pullrequestreview-1658950679
Changelog
=> Update 5.2.1 CHANGELOG for #57318

dev/backcompat/bazel-backcompat.sh
Print out the patches that are applied
copied the portion of changed bash locally and ran it ... also ci
=> backcompat: print patches being applied

client/branded/src/search-ui/input/SearchBox.tsx, client/jetbrains/webview/src/search/input/JetBrainsSearchBox.tsx, client/web/dev/utils/create-js-context.ts, client/web/src/integration/jscontext.ts, client/web/src/jscontext.ts, client/web/src/search/input/SearchNavbarItem.tsx, client/web/src/storm/pages/SearchPage/SearchPageInput.tsx, cmd/frontend/internal/app/jscontext/jscontext.go, internal/conf/computed.go
Those services are no longer supported, just removing some more leftovers of that.
CI.
=> Remove externalServiceUserMode configuration

.github/workflows/sg-setup.yml, .tool-versions, WORKSPACE, dev/sg/checks.go
Update to latest version for security fixes
CI
=> go: update to 1.20.10

cmd/frontend/internal/codemonitors/resolvers/BUILD.bazel, cmd/frontend/internal/codemonitors/resolvers/resolvers.go, internal/codemonitors/BUILD.bazel, internal/codemonitors/search.go, internal/codemonitors/search_test.go, internal/search/commit/commit.go, internal/search/job/jobutil/job.go
I apologize for the multi-focused PR, but a few of these fixes bled into each other. 
- Fixes https://github.com/sourcegraph/sourcegraph/issues/56238
- Fixes https://github.com/sourcegraph/sourcegraph/issues/54700 
- Removes some dead code
- Removes some old feature flag code
Comments inline.
Manually tested that monitors still work. Existing tests cover standard cases, and I updated the test that checks that a failure logs a message.
=> Code monitors: fix a bunch of stuff

doc/cody/overview/enable-cody-enterprise.md, doc/cody/overview/install-jetbrains.md, doc/cody/overview/install-neovim.md
This PR fixes and removes Beta and Experimental badges from our headings. 
- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1697052664480639
Docs added
[Preview Link](https://docs.sourcegraph.com/@fix-link)
=> Fix experimental and beta badges in headings

CHANGELOG.md
=> Changelog: update with code monitors fixes

cmd/cody-gateway/internal/events/BUILD.bazel, cmd/cody-gateway/internal/events/buffered.go, cmd/cody-gateway/internal/events/events.go, cmd/cody-gateway/internal/events/instrumented.go
Replaces some the custom helper we have with the new shared one used in https://github.com/sourcegraph/sourcegraph/pull/57552
CI
=> cody-gateway: use xcontext.Detach

internal/wrexec/recording_cmd.go
Saw a panic on S2 caused by this.
CI.
=> wrexec: Don't panic when process state is nil

cmd/symbols/parser/config.go, internal/ctags_config/ctags_config.go, schema/README.md, schema/schema.go, schema/site.schema.json
See https://sourcegraph.slack.com/archives/CHXHX7XAS/p1696264864218959.
CI
=> site-config: Make symbols not required in syntaxHighlighting

client/shared/dev/runMochaTestsWithPercy.js
If an arg is passed to runMochaTestsWithPercy that contains a space, it is split into 2 args when the underlying command is run. This causes problems with (eg) `-f 'some test'`, which is used to filter Mocha tests to run, where only `some` is used and `test` is treated as a separate command-line arg.
This does not cause any known problems today, but it is a bug and makes it hard to run a subset of integration tests through this runner in local dev.
CI
=> runMochaTestsWithPercy: preserve args

internal/src-cli/CODENOTIFY, monitoring/CODENOTIFY
=> chore: Remove old CODENOTIFY entries

doc/cody/overview/enable-cody-enterprise.md
Fixes one link to a header anchor that wasn't working.
Docs only.
[Preview Link](https://docs.sourcegraph.com/@iskyos-docs-link-header-fix)
=> Update link on enable-cody-enterprise.md

doc/cody/troubleshooting.md
This doc update covers a workaround for VS Code on Linux where a user has issues logging in and the suggested steps to remediate.
[Preview Link](https://docs.sourcegraph.com/@docs/cody-vscode-linux-workaroud)
=> Add workaround steps for VS Code on Linux

doc/cli/how-tos/index.md, doc/cli/how-tos/revoking_an_access_token.md, doc/cli/index.md
- Docs change - confirm by checking doc and testing instructions
[Preview Link](https://docs.sourcegraph.com/@will/docs-revoke-access-token)
=> docs: add how-to for revoking access tokens

schema/schema.go, schema/site.schema.json
This has been removed long ago, but seems like we forgot to remove this field from site config.
CI.
=> Remove unused field in site config

wolfi-images/gitserver.yaml, wolfi-images/server.yaml, wolfi-packages/p4-fusion-sg.yaml, wolfi-packages/p4-fusion.yaml
Combine https://github.com/sourcegraph/sourcegraph/pull/57751 and https://github.com/sourcegraph/sourcegraph/pull/57756 to fork p4-fusion into a separate package, and update relevant images.
> We've forked the tool and are now ready to try some of the fixes out in a more production enviroment, so bundling this temporarily from a specific commit from the fork repo.
> 
> Next up, I'll open a PR to use the newly generated base image in bazel and add the new --noBaseCommit flag to the perforce syncer.
> 
- Build package + image locally
- Test using CI
=> Fork p4-fusion package and update in server + gitserver

dev/gqltest/sub_repo_permissions_test.go, internal/gqltestutil/repository.go, testing/BUILD.bazel
This reverts commit 7f3e4755bd3202d631b61d88090ae2935bd45b77.
It seems to time out.
cc @pjlast 
CI
=> Revert "Make sub-repo permissions integration test functional (#57764)"

doc/dev/background-information/sg/reference.md, sg.config.yaml
n/a; dev only
[Preview Link](https://docs.sourcegraph.com/@sqs/sg-web-integ)
=> add `sg test bazel-web-integration`

client/browser/src/shared/components/HoverOverlay.story.tsx, client/web/src/components/Timeline.story.tsx, client/web/src/enterprise/batches/batch-spec/TabBar.story.tsx, client/web/src/enterprise/batches/batch-spec/edit/workspaces-preview/WorkspacesPreview.story.tsx, client/web/src/enterprise/batches/batch-spec/edit/workspaces-preview/WorkspacesPreviewList.story.tsx, client/web/src/enterprise/batches/batch-spec/execute/ReadOnlyBatchSpecForm.story.tsx, client/web/src/enterprise/batches/close/BatchChangeClosePage.story.tsx, client/web/src/enterprise/batches/settings/AddCredentialModal.story.tsx, client/web/src/repo/commits/GitCommitNode.story.tsx, client/web/src/site-admin/webhooks/MessagePanel.story.tsx, client/wildcard/src/components/Button/story/Button.story.tsx, client/wildcard/src/components/Card/Card.story.tsx, client/wildcard/src/components/PageSelector/PageSelector.story.tsx, client/wildcard/src/components/Panel/story/Panel.story.tsx, client/wildcard/src/components/Popover/story/Popover.story.tsx, client/wildcard/src/components/Typography/Typography.story.tsx, client/wildcard/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx
Use StoryFn instead of Story (which is deprecated and unresolvable, causing a type error).
CI
=> fix storybook types

CHANGELOG.md, doc/admin/updates/kubernetes.md
Closes https://github.com/sourcegraph/sourcegraph/issues/55290
docs only. 
[Preview Link](https://docs.sourcegraph.com/@es/proxy-changelog)
=> Add changelog entries about removal of GitHub proxy

cmd/gitserver/internal/sg_maintenance.sh, cmd/gitserver/internal/vcssyncer/perforce.go
=> Fixup a few code comments

docker-images/syntax-highlighter/crates/scip-syntax/queries/java/scip-tags.scm, docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__test__scip_snapshot_globals.java.snap, docker-images/syntax-highlighter/crates/scip-syntax/testdata/globals.java
Noticed that we're missing it.
Added definition in globals.java and updated snapshot
=> Emit symbols for Java records and record fields

client/branded/src/search-ui/results/sidebar/SearchFilterSection.tsx, client/browser/src/shared/code-hosts/gitlab/codeHost.test.ts, client/browser/src/shared/code-hosts/gitlab/codeHost.ts, client/browser/src/shared/code-hosts/shared/codeHostTestUtils.ts, client/observability-server/BUILD.bazel, client/web/src/search/results/sidebar/Revisions.tsx, dev/update-embeddings-list/src/index.test.ts, dev/update-embeddings-list/src/index.ts
- fix client/observability-server test
- clean up dev/update-embeddings-list
- don't complain if no tests
- avoid window.location modification (which jsdom forbids)
- eliminate cross-package SCSS import
CI
=> misc test cleanups

deps.bzl, go.mod, go.sum
Only includes some changes to ranking.
https://github.com/sourcegraph/zoekt/compare/0f21f325cc5d...b5a5fdc86e83
- https://github.com/sourcegraph/zoekt/commit/1a3dddce84 score: experimental extension novelty in sorting
- https://github.com/sourcegraph/zoekt/commit/b5a5fdc86e score: boost exported go ident and downrank _test.go
Test Plan: CI
=> gomod: update zoekt with ranking tweaks

client/build-config/OWNERS
The only team/owner no longer exists
n/a
=> chore: delete client/build-config/OWNERS

cmd/frontend/internal/cli/http.go
This is just a rename, but I'm telling you: I need this. Reading through a file with `newInternalHTTPHandler` and `newExternalHTTPHandler` and mentions of internal/external APIs left and right, the fact that `httpapi` is imported as `internalhttpapi` does NOT help.
It's like naming your backend frontend or something.
- Ran `sg start` to make sure everything still boots up correctly
=> http routers: rename package import for more clarity

CHANGELOG.md
change log entry for OpenAI autocomplete
n/a change log entry only
=> Cody: change log for OpenAI autocomplete

cmd/gitserver/internal/vcssyncer/perforce.go
The initial "clone" of a p4-fusion depot will only contain loose objects, since it doesn't care about repacking for simplicity. This is good to keep p4-fusion non-complex, but bad for performance and disk usage, so instead we are now verifying the repos integrity (to make sure that if there's issues, we'll know they came from repack or p4-fusion) and then repack all the objects into a single pack.
Closes https://github.com/sourcegraph/sourcegraph/issues/57626.
Multiple manual test runs, checked repos remained valid, and that the progress report correctly renders. This will also be covered by the E2E tests for Perforce.
=> perforce: Run fsck and repack after clone

doc/integration/jetbrains/index.md
=> Update links to point to jetbrains repo

.github/workflows/sg-binary-release.yml
https://github.com/sourcegraph/sourcegraph/commit/813644d5e1f1f38c5ab38e6f0aeaaf48fe905c43#diff-e70d050939925f9327f8896f7548a4d70d407d2e1c2edbbaf0f74a7137039e47
my patch was never released
n/a
=> ci: fix sg msp is not release

cmd/cody-gateway/internal/limiter/BUILD.bazel, cmd/cody-gateway/internal/limiter/limiter.go
Follow-up to https://github.com/sourcegraph/sourcegraph/pull/57553/files
=> Remove more on-off context manipulation

.github/workflows/label-notify.yml
=> chore: update label-notify.yml for Cody Gateway

doc/admin/deploy/index.md
Docs added.
[Preview Link](https://docs.sourcegraph.com/@creativefisher-patch-1)
=> Updated the link to the enterprise trial form

lib/go.mod
=> chore: Run go mod tidy

WORKSPACE
This reverts commit 144e4d9be3523d6a9d4a91b3ee1e48c2b4224aaf.
I pused a commit to main without a PR
None - this is a revert
=> Revert "bazel: upgrade to rules_rust 0.30"

internal/search/query/CODENOTIFY
=> Add Camden to codenotify for search queries

CHANGELOG.md
Changelog entry for AWS Bedrock endpoint update
N/A changelog only
=> Changelog entry for AWS Bedrock endpoint update

dev/nix/nodejs.nix
=> nix: assert typescript version and reduce repetition in nodejs.nix

dev/release/src/release.ts, dev/release/src/util.ts
This fixes a few issues I hit during the 5.2.2 patch release.
I used these changes to make the release.
=> Release tool: fix a few issues

WORKSPACE
Lets try this again but instead from a PR
CI
=> bazel: upgrade rules rust

cmd/migrator/BUILD.bazel, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/deploy/machine-images/gce.md, doc/admin/executors/deploy_executors_kubernetes.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, internal/updatecheck/handler.go
This pull request is part of the Sourcegraph 5.2.2 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58049)
[Preview Link](https://docs.sourcegraph.com/@publish-5.2.2)
=> release: sourcegraph@5.2.2

CHANGELOG.md, dev/release/release-config.jsonc
=> Release: deactivate 5.2.2 release

.pre-commit-config.yaml
Fixes https://github.com/sourcegraph/devx-support/issues/361
CI
=> local: don't let pre-commit run no DB md files

cmd/searcher/internal/search/hybrid.go, internal/gitserver/commands.go
We improve DiffSymbols to first check the commits exist. This is to provide a better error message. Additionally we wrap the returned error to include context of the command run.
We also improve hybrid search to fall back in the case a commit doesn't exist. The most likely explanation is that there is some sort of race and the indexed commit no longer exists in the repository. In that case we should fall back to normal searcher.
Test Plan: CI. We do not explicitly test the error path here. However, the happy path is covered by integration tests.
=> gitserver: more robust DiffSymbols

testing/tools/integration_runner.sh
We accidentally brought back some of the local development logic in the e2e tests helpers, i.e. mount data volumes, which ultimately we never use in CI because we always discard them. 
This proved to create problems for Aspect Workflows agents, and this PR might solve it. Regardless of what we do for those agents, this is still code that provides no value so we're better off without it. 
CI
=> bzl: do not mount data volumes for e2e tests

client/web/src/components/diff/DiffBoundary.tsx, client/web/src/components/diff/__snapshots__/DiffHunk.test.tsx.snap
Small commit to align offset diff header with the rest of the page.
Before:
After:
Test manually
=> Code Navigation: fix offset diff header

doc/dev/security/csrf_security_model.md
n/a
[Preview Link](https://docs.sourcegraph.com/@unknwon-patch-1)
=> chore: fix typo in csrf_security_model

cmd/frontend/internal/httpapi/graphql.go
Will allow us to investigate how the API is used.
Verified locally using sg start monitoring.
=> Add histogram for GraphQL cost

doc/dev/how-to/cody_gateway.md
Clarifies ambiguous bits from https://sourcegraph.slack.com/archives/C05SZB829D0/p1699280143605309
n/a
[Preview Link](https://docs.sourcegraph.com/@cody-gateway-dev-docs)
=> doc/dev: improve cody-gateway setup docs

dev/managedservicesplatform/internal/resource/redis/redis.go
`sg msp generate` on https://github.com/sourcegraph/managed-services/pull/47
=> dev/msp: fix redis endpoint

client/web/src/repo/tree/TreePageContent.tsx
=> Code Navigation: edit tooltip to reflect new RBAC permissions paradigm

doc/getting-started/index.md
PR fixes the broken link.
- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1698944287998579
Docs added
[Preview Link](https://docs.sourcegraph.com/@link-fix)
=> Fix broken link on the main docs landing page

doc/cody/overview/cody-with-sourcegraph.md, doc/cody/overview/index.md, doc/sidebar.md
This PR removes Cody App from the main docs nav to encourage the adoption of IDE extensions and app maintenance issues. 
- [Asana task
](https://app.asana.com/0/1205845687915332/1205901009682191/f)
- [Slack thread](https://sourcegraph.slack.com/archives/C0379USFD7E/p1699296351784209)
Docs added
[Preview Link](https://docs.sourcegraph.com/@rmv-cody-app)
=> [Cody GA Docs] Remove Cody App from main docs navigation

cmd/frontend/internal/httpapi/graphql.go
cost can be nil, so we have to guard against that.
Code review.
=> Fix nil panic in cost prom metric when estimation failed

cmd/frontend/internal/httpapi/graphql.go
The new enforcement logic doesn't consider cost being nil, so wrapped this in a conditional block now.
Code review.
=> Fix another nil panic with cost estimation

doc/cody/overview/cody-with-sourcegraph.md, doc/cody/overview/index.md, doc/sidebar.md
Reverts sourcegraph/sourcegraph#58178
- https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1699553868780979
Docs added
[Preview Link](https://docs.sourcegraph.com/@revert-58178-rmv-cody-app)
=> Revert "[Cody GA Docs] Remove Cody App from main docs navigation"

client/web/src/repo/blob/codemirror/tooltips/CodyTooltip.tsx
This is a quick refactor of the cody widget extension to make derive the tooltip position from the current selection rather than from mouse/keyboard events. This allows us to ignore certain selection events, which is the primary motiviaton for this change: I find it surprising that the widget appears when the selection changes due to navigating search results, since this selection change is not something that I've done explicitly (it's an implementation detail).
Now this does have the effect that the widget is shown immediately when any text is selected, not just after the mouse was released, but I think that's an OK tradeoff.
https://github.com/sourcegraph/sourcegraph/assets/179026/4a73c459-1408-4094-9dfd-b3a8f8a591c7
- Select text with mouse: cody widget appears
- Select text with …
=> file/cody: Refactor cody widget extension

dev/sg/msp/sg_msp.go
As titled. The main one I added here was pending spinners for various parts of workspace sync, which takes a few seconds.
```
sg msp tfc sync
```
=> dev/msp: add cute pending spinners for slower commands

doc/cloud/private_connectivity_aws.md
=> doc: update aws private code host docs

dev/release/templates/release_issue_template.md
=> release: instruct release_issue_template to update RC instance

doc/integration/vscode/index.md
=> Update broken links

internal/updatecheck/client.go
I'm not super familiar with `sync.WaitGroups` ... Let me know if I need to change anything with the simple logic here!
Ran Sourcegraph locally with no errors
=> Don't do expensive ping queries for dotcom; these are causing timeouts

wolfi-images/batcheshelper.yaml, wolfi-images/blobstore.yaml, wolfi-images/bundled-executor.yaml, wolfi-images/cadvisor.yaml, wolfi-images/cloud-mi2.yaml, wolfi-images/executor-kubernetes.yaml, wolfi-images/executor.yaml, wolfi-images/gitserver.yaml, wolfi-images/jaeger-agent.yaml, wolfi-images/jaeger-all-in-one.yaml, wolfi-images/node-exporter.yaml, wolfi-images/opentelemetry-collector.yaml, wolfi-images/postgres-exporter.yaml, wolfi-images/postgresql-12-codeinsights.yaml, wolfi-images/postgresql-12.yaml, wolfi-images/prometheus-gcp.yaml, wolfi-images/prometheus.yaml, wolfi-images/qdrant.yaml, wolfi-images/redis-exporter.yaml, wolfi-images/redis.yaml, wolfi-images/repo-updater.yaml, wolfi-images/search-indexer.yaml, wolfi-images/searcher.yaml, wolfi-images/server.yaml, wolfi-images/sourcegraph-base.yaml, wolfi-images/sourcegraph-dev.yaml, wolfi-images/sourcegraph.yaml, wolfi-images/symbols.yaml, wolfi-images/syntax-highlighter.yaml
We need to build these images on the 5.2 branch, due to an experimental `p4-fusion-binary` being used by the images we normally build from main.
- Scan the images for CVEs
- Check if the p4-fusion-binary is not the sg version.
=> Trigger Wolfi Image build on 5.2 branch

cmd/searcher/internal/search/search_regex_test.go
Without this benchmarks panic.
Test Plan: go test -bench .
=> searcher: set Log on test githubStore

doc/cody/overview/enable-cody-enterprise.md
=> doc: update cody on cloud instruction

deps.bzl, go.mod, go.sum
https://github.com/sourcegraph/zoekt/compare/5e2620e0cf64...137eb8f22610
- https://github.com/sourcegraph/zoekt/commit/334e30f230 client: Allow custom Doer
- https://github.com/sourcegraph/zoekt/commit/137eb8f226 build: ignore out of bound lines from ctags
Test Plan: CI
=> gomod: update zoekt to allow custom doer

dev/gqltest/external_service_test.go, dev/gqltest/sub_repo_permissions_test.go
Disabling to unblock - context https://sourcegraph.slack.com/archives/C04MYFW01NV/p1699972152542289
CI
=> perforce: disable tests 5.2 pending p4 trust fix

internal/repos/github.go
Seems like this was a debug leftover.
- N/A
=> github repos: do not log "exclude forks"

dev/gqltest/external_service_test.go, dev/gqltest/sub_repo_permissions_test.go
This reverts commit 553d81ba84362c7d765cb5017a113da010d2f435.
CI.
=> Revert "perforce: disable tests 5.2 pending p4 trust fix (#58336)"

dev/release/release-config.jsonc
=> release 5.2.3 in progress

doc/cody/feature-reference.md
The PR removes duplicated table item from the Feature Reference docs.
Docs added
[Preview Link](https://docs.sourcegraph.com/@rmv-dup)
=> Remove duplicated table item from Feature Reference

doc/dev/background-information/bazel/faq.md
Covers https://github.com/sourcegraph/devx-support/issues/393
CI
[Preview Link](https://docs.sourcegraph.com/@jh/bzl-faq/tsconfig)
=> dev: add FAQ entry about `bazel configure` warning

shell.nix
Aint nobody got time to work in frontend without the language server :D
`nix develop` and opening up a typescript file
=> nix: add typescript language server

internal/completions/client/fireworks/fireworks.go
This fixes JSON unmarshalling of a reported linter issue.
CI.
=> fireworks: Fix struct tag

internal/bytesize/BUILD.bazel, internal/bytesize/bytesize.go, internal/bytesize/bytesize_test.go, internal/repos/exclude.go, internal/repos/exclude_test.go, schema/github.schema.json, schema/schema.go
This is a follow-up to the review in https://github.com/sourcegraph/sourcegraph/pull/58377 and addresses all comments.
- Unit tests
=> github star/size exclusion: incorporate feedback from code review

CHANGELOG.md, dev/release/release-config.jsonc
=> finalizing release 5.2.3

doc/cody/faq.md
Add a short note about Cody's response to non-code questions. 
Docs change only, tested locally. 
[Preview Link](https://docs.sourcegraph.com/@rpp/add-non-code-note)
=> Add note about non-programming questions

CHANGELOG.md
Changelog for mentioned PRs.
- N/A
=> changelog: document exclude rules and size/stars rules

cmd/frontend/graphqlbackend/external_accounts.go
Follow-up of https://github.com/sourcegraph/sourcegraph/pull/56442#pullrequestreview-1616553005
CI
=> graphqlbackend: better disallow unlinking account feature flag check

doc/batch_changes/explanations/permissions_in_batch_changes.md
Doc update.
[Preview Link](https://docs.sourcegraph.com/@bo/update-batch-changes-permissions-docs)
=> code-search: update batch changes permissions doc

dev/sg/internal/run/command.go, dev/sg/sg_start.go
Crude hack in preparation of tomorrow's demo day. 
CI + local tests.
=> sg: add --sgtail to start command

internal/fileutil/BUILD.bazel, internal/fileutil/fileutil_posix.go
To investigate an issue on dotcom.
CI.
=> Add additional logging for rename failures

doc/batch_changes/references/faq.md
This change explains how to create and use a team namespace in a batch change.
[Preview Link](https://docs.sourcegraph.com/@doc/batch-team-namespace)
=> Update FAQ with team namespaces

doc/cody/quickstart.md
Remove SS in Cody Quickstart.
Docs added
[Preview Link](https://docs.sourcegraph.com/@fix-ss)
=> Remove broken screenshot in Cody Quickstart

cmd/frontend/internal/context/resolvers/context_test.go
Had this test flake on me recently where the result was actually correct but the ordering was different. 
_Can't find the build where this happene_ 😢
Test locally + CI
=> gitserver tests: sort results before comparing

internal/database/sub_repo_perms_store.go
There is another error message with the same wording, so debugging can be confusing.
CI tests should all pass
=> clarify wording for error message

internal/database/gitserver_repos.go
Unstable ordering here could mean that we run into deadlocks when two of these queries run at the same time. Ordering them and selecting them for update in that order fixes it for most conditions.
Using a local repro, I've no longer been able to reproduce the issue we saw on dotcom. I will mark the sentry issues as resolved, to be informed about regressions, and all the existing tests still pass so I'm confident the query behaves the same as before.
=> gitserver: Use stable ordering for DB updates to prevent deadlocks

testing/BUILD.bazel
Pre-factored out of https://github.com/sourcegraph/sourcegraph/pull/56569
CI
=> build(bazel): mark integration tests that must run in isolation as exclusive

dev/sg/sg_src.go
Shell expansion breaks usage like `sg src search c.Run()`. (You'd need to do `sg src search "'c.Run()'"`, which is unwieldy.)
n/a
=> do not perform shell expansion on `sg src` invocations

client/web/src/enterprise/batches/batch-spec/header/BatchChangeHeader.tsx, client/web/src/enterprise/batches/list/BatchChangeListPage.tsx, client/web/src/enterprise/code-monitoring/CodeMonitorList.tsx, client/web/src/enterprise/code-monitoring/CodeMonitoringLogs.tsx, client/web/src/nav/NavBar/NavDropdown.tsx, dev/sg/sg_src.go
- improve batch change description in header
- CodeMonitoringLogs: clean up text
- remove awkward dangling feedback link on code monitor list page
- fix sg error message for `sg src-instance register`
- fix jsdoc
CI
=> misc fixes to text and error message copy

cmd/gitserver/internal/statesyncer.go
Turns out that this can error and when it does a restart is the only way to really recover from it. That doesn't feel great. So I made an error trigger another full sync.
=> gitserver: Run full sync after errors

cmd/frontend/BUILD.bazel, internal/settings/settings_test.go, schema/schema.go, schema/settings.schema.json
Found while cleaning up sourcegraph.com
CI.
=> Remove unused settings and env vars

doc/admin/config/batch_changes.md
Doc update
[Preview Link](https://docs.sourcegraph.com/@bo/doc-rejecting-unverified-commits)
=> code-search: add documentation for rejecting unverified commits

doc/integration/bitbucket_server.md
* Update the installation steps to point to the Atlassian marketplace and the manual steps
* Remove the link to the Github repository in the overview section to reduce confusion
See details in [this Slack thread](https://sourcegraph.slack.com/archives/C89KCDK5J/p1696565997219209)
previewed the changes locally
[Preview Link](https://docs.sourcegraph.com/@mike-r-mclaughlin-patch-3)
=> Update Bitbucket Server page to link to the marketplace

doc/code_search/explanations/search_details.md
Closes https://github.com/sourcegraph/sourcegraph/issues/58621
Ran the snippet locally to ensure it does what's expected.
[Preview Link](https://docs.sourcegraph.com/@cc/re2-docs)
=> Docs: add details about RE2

CHANGELOG.md
Add a change log entry for Azure OpenAI updates now that they will be included in 5.2.4
Change log only.
=> Cody: Changelog entry for additional Azure OpenAI authentication methods.

dev/sg/sg_start.go, doc/dev/background-information/sg/reference.md
Just a small typo I came across while devving.
N/A
[Preview Link](https://docs.sourcegraph.com/@cc/fix-typo)
=> sg: fix typo

dev/release/release-config.jsonc, dev/release/src/release.ts
=> Activate 5.2.4 release

doc/index.md
Just updating links to marketing site
[Preview Link](https://docs.sourcegraph.com/@creativefisher-patch-6)
=> Updating links to marketing site

doc/code_search/index.md
Just updating links to marketing pages.
[Preview Link](https://docs.sourcegraph.com/@creativefisher-patch-5)
=> Updating links to marketing pages

doc/_resources/templates/root.html
Just updating links to marketing site
[Preview Link](https://docs.sourcegraph.com/@creativefisher-patch-4)
=> Updated links to marketing site

doc/getting-started/index.md
Just link change
[Preview Link](https://docs.sourcegraph.com/@creativefisher-patch-3)
=> Update link to marketing page

internal/licensing/data.go
Adding them to the list of available features.
We still need to implement gating and enforcement. For now, since all current plans have no enforcement, all plans get this feature set.
CI.
=> licensing: Add features for search, monitors and notebooks

client/web/BUILD.bazel, client/web/src/cody/subscription/CancelProModal.tsx, client/web/src/cody/subscription/CodySubscriptionPage.module.scss, client/web/src/cody/subscription/CodySubscriptionPage.tsx
Closes https://github.com/sourcegraph/cody/issues/1960.
https://www.loom.com/share/b2ab2ba854ee4920adc7a3b4bc822257
Local dotcom run.
=> Redesign and add are you sure to Cody pricing

sg.config.yaml
Automerged and had to fix this as part of ther review
CI
=> sg+docsite: remove outdated comment

cmd/worker/internal/repostatistics/resetter.go
I killed all of the queries that have been running on dotcom for >10hrs. I don't know where they come from. Let's try again.
- NA
=> statistics resetter: try again on Tuesday

cmd/migrator/BUILD.bazel, doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/deploy/machine-images/gce.md, doc/admin/executors/deploy_executors_kubernetes.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, internal/updatecheck/handler.go
This pull request is part of the Sourcegraph 5.2.4 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58662)
[Preview Link](https://docs.sourcegraph.com/@publish-5.2.4)
=> release: sourcegraph@5.2.4

CHANGELOG.md
=> 5.2.4 changelog update

dev/release/release-config.jsonc
=> deactivate release

internal/httpcli/client.go
Instead of using the test transport option, we now have a separate deny list for local development. This makes it easier to change the deny list and separates test from local development.
https://github.com/sourcegraph/sourcegraph/pull/58558#pullrequestreview-1748789265
Tested locally, ci tests.
=> add localDevDenyList for denylists

dev/oci_deps.bzl
After we had to revert this today because a faulty version of sg downgraded postgres, trying again.
CI found issues last time, so hoping it's gonna go green this time.
=> Bump base images again

internal/completions/httpapi/codecompletion.go
We don't give any details right in this error message - providing the model in the response is useful feedback. See: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1701802444496609
n/a
=> completions: include model in 'unsupported model' error

WORKSPACE
Newer version of rules that we use
CI
=> bazel: update rules_ts, rules_js and bazel-lib

cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go, cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user_test.go
Found an oversight in my code that might've caused me a bunch of headaches when testing Cody Gateway locally.
After fixing the bug, my requests don't hang anymore.
Also added a set of tests for the completions limiting functionality to make sure it works correctly.
Added the tests.
=> SSC: Fix Gateway bug and add tests

client/web/src/cody/onboarding/CodyOnboarding.tsx, client/web/src/cody/subscription/CancelProModal.tsx, client/web/src/cody/subscription/CodySubscriptionPage.tsx, client/web/src/cody/subscription/UpgradeToProModal.tsx, client/web/src/util/constants.ts
Add telemetry for Cody PLG onboarding flow and more. 
closes: https://github.com/sourcegraph/cody/issues/1935
closes: https://github.com/sourcegraph/cody/issues/1959
follow: https://docs.google.com/spreadsheets/d/1QXnrHkgGLXdbfHEhI_VjtDTy-mCtnK1qri3IMQu7rNk/edit#gid=1704312181
=> Add Cody PLG Telemetry

client/web/src/PageError.tsx, dev/ci/internal/ci/operations.go
chromatic was disabled since it was blocking main
CI + change to frontend files to trigger build
=> Revert - disable chromatic

cmd/gitserver/internal/server_grpc.go, cmd/repo-updater/shared/main.go, internal/repos/purge.go
=> purge worker: fix bug in gRPC handler and bump log level

cmd/gitserver/internal/cleanup.go
There was a bug where when a repo is on a wrong shard we would delete it, and return done: false. Then, the next check is for repo corruption. The repo has been removed, so the HEAD doesn't exist and the corruption is logged.
This PR also splits the two concerns into two workers, to make reasoning about it easier. The reason they were coupled was because of a prom metric that wasn't even exposed in Grafana, so I just removed it.
CI and prayer.
=> Don't run janitor after removing wrong shard repo

dev/build-tracker/build/build.go, dev/build-tracker/build/build_test.go, dev/build-tracker/build/steps.go, dev/build-tracker/integration_test.go, dev/build-tracker/main.go, dev/build-tracker/main_test.go, dev/build-tracker/notify/slack.go, dev/build-tracker/server_test.go
=> build-tracker: only account for terminal job states

internal/database/BUILD.bazel, internal/database/perms_store_test.go
This test is the slowest one in the whole package and it's not worth it.
- NA
=> internal/database: remove test that takes 10s and is not worth it

dev/ci/internal/ci/bazel_operations.go
Use the correct emoji as listed here https://github.com/buildkite/emojis#emoji-reference
CI
=> ci: fix legacy image build emoji

client/browser/src/shared/code-hosts/shared/codeHost.tsx
Includes fix for css colliding https://github.com/sourcegraph/sourcegraph/pull/58809
This PR branch was checkout from the bext/release and cherry picked commit with a fix from the main branch
- CI is passing
=> Use document element for class theme in code hosts integrations (#58809)

dev/ci/internal/ci/operations.go
This reverts commit 648843768e6c3a037dcb98d8160f37b9c7fb0bea.
CI
=> Enable Chromatic - Revert "Disable chromatic again (#58846)"

.github/workflows/pr-auditor.yml
Use new token secret for PR Auditor
Tested on Infrastructure repo
=> pr-auditor: use token secret

cmd/msp-example/internal/example/diagnostics.go, cmd/telemetry-gateway/service/service.go, lib/managedservicesplatform/runtime/contract.go
As requested in https://github.com/sourcegraph/accounts.sourcegraph.com/pull/146#discussion_r1419251152
n/a
=> msp/runtime: provide query params to healthcheck

client/web/src/cody/management/CodyManagementPage.module.scss, client/web/src/cody/management/CodyManagementPage.tsx, client/web/src/cody/onboarding/CodyOnboarding.module.scss, client/web/src/cody/onboarding/CodyOnboarding.tsx, client/web/src/cody/subscription/CodySubscriptionPage.module.scss, client/web/src/cody/subscription/UpgradeToProModal.tsx
Links to new videos with better animation
Changes copy in the Dashboard and success modal
Tested local in Light and Dark mode
=> Copy changes and new video

cmd/frontend/graphqlbackend/user.go
IDEs including VS Code and JetBrains, are sending double the number of event logs, with similar event names but different sources. This PR updates the usage stats logic to count intercations based on event logs only from Cody agent. It also now covers event logs from cody web. 
use this query: https://sourcegraph.com/api/console#%7B%22query%22%3A%22%7B%5Cn%20%20currentUser%20%7B%5Cn%20%20%20%20id%5Cn%20%20%20%20codyCurrentPeriodChatUsage%5Cn%20%20%20%20codyCurrentPeriodChatLimit%5Cn%20%20%20%20eventLogs(first%3A%2050)%20%7B%5Cn%20%20%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20source%5Cn%20%20%20%20%20%20%20%20user%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20timestamp%5Cn%20%20%20%20%20%20%7D%5Cn% …
=> Fix Cody Usage Metrics SQL Query

client/web/src/cody/management/CodyManagementPage.module.scss, client/web/src/cody/management/CodyManagementPage.tsx, client/web/src/cody/subscription/CodySubscriptionPage.tsx, client/web/src/cody/subscription/UpgradeToProModal.tsx, client/web/src/cody/subscription/queries.tsx, client/web/src/marketing/components/HubSpotForm.module.scss, internal/database/users.go
closes: https://github.com/sourcegraph/cody/issues/2310
closes: https://github.com/sourcegraph/cody/issues/1931
closes: https://github.com/sourcegraph/cody/issues/2230
closes: https://github.com/sourcegraph/cody/issues/2309
closes: https://github.com/sourcegraph/cody/issues/2276
=> [Cody] fix limit reached UI

internal/completions/httpapi/handler.go
Disable dotcom level user-based rate limiting for Cody GA. We need to only rely on Cody gateway which performs user-level rate limiting now. 
.
=> [Cody] disable dotcom level rate limitting for Cody GA

client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx
=> feat: add neovim to cody redirects, instead of re-using jetbrains

CHANGELOG.md
Change log entry for azure auth proxy for cody provider.
=> Change log entry for azure auth proxy for cody provider

dev/release/release-config.jsonc
=> release 5.2.5 in progress

CHANGELOG.md
=> 5.2.5 changelog update

doc/admin/deploy/docker-compose/aws.md, doc/admin/deploy/docker-compose/azure.md, doc/admin/deploy/docker-compose/digitalocean.md, doc/admin/deploy/docker-compose/google_cloud.md, doc/admin/deploy/docker-compose/index.md, doc/admin/deploy/docker-single-container/aws.md, doc/admin/deploy/docker-single-container/digitalocean.md, doc/admin/deploy/docker-single-container/google_cloud.md, doc/admin/deploy/docker-single-container/index.md, doc/admin/deploy/kubernetes/helm.md, doc/admin/deploy/machine-images/gce.md, doc/admin/executors/deploy_executors_kubernetes.md, doc/admin/external_services/postgres.md, doc/admin/external_services/redis.md, doc/admin/http_https_configuration.md, doc/admin/ssl_https_self_signed_cert_nginx.md, doc/admin/updates/docker_compose.md, doc/admin/updates/pure_docker.md, doc/admin/updates/server.md, internal/updatecheck/handler.go
This pull request is part of the Sourcegraph 5.2.5 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58967)
cc @jdpleiness
[Preview Link](https://docs.sourcegraph.com/@publish-5.2.5)
=> release: sourcegraph@5.2.5

dev/release/release-config.jsonc
=> release: close release 5.2.5

client/web/src/cody/onboarding/CodyOnboarding.tsx
Changing existing install documentation to the new docs URL.
New installation url parameters will be `sourcegraph.com/docs/cody/clients/install-<editor>`
N/A
=> Update Cody installation URLs

client/web/src/cody/onboarding/CodyOnboarding.tsx
=> editor names (FSF -> GNU, fix capitalization of JetBrains)

client/web/src/cody/management/CodyManagementPage.tsx, client/web/src/cody/onboarding/instructions/JetBrains.tsx, client/web/src/cody/onboarding/instructions/NeoVim.tsx, client/web/src/cody/onboarding/instructions/VsCode.tsx, client/web/src/cody/subscription/UpgradeToProModal.tsx
Adhere to https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/style_and_mechanics/.
CI
=> use consistent "Sentence case" capitalization

cmd/cody-gateway/shared/config.go
Add the other variant of model name
- config only
- works locally
=> Add claude instant 1.2 (no v)

client/web/src/search/results/StreamingSearchResults.tsx, pnpm-lock.yaml, schema/schema.go, schema/settings.schema.json
- Check that new search results page layout available by `newSearchResultsUI` feature flag
=> [Search Results]: Add new feature flag for the new search results page

dev/bkstats/OWNERS, dev/bkstats/README.md, dev/buildchecker/OWNERS, dev/buildchecker/README.md, dev/ci/OWNERS, dev/deployment-notifier/OWNERS, dev/scaletesting/OWNERS, dev/sg/OWNERS, internal/observation/CODENOTIFY, internal/trace/CODENOTIFY, internal/tracer/CODENOTIFY, lib/errors/CODENOTIFY, third-party-licenses/CODEOWNERS
Spotted this while waiting for some builds. There are some occurrences in the docs as well, but I need to double check things before changing stuff over there. 
CI
=> chore: links/ownership devx->dev-infra

client/jetbrains/CHANGELOG.md, client/web/src/cody/onboarding/CodyOnboarding.tsx, client/web/src/cody/onboarding/instructions/JetBrains.tsx, client/web/src/cody/onboarding/instructions/NeoVim.tsx, client/web/src/cody/onboarding/instructions/VsCode.tsx, client/web/src/cody/subscription/CodySubscriptionPage.tsx, client/web/src/cody/subscription/UpgradeToProModal.tsx, client/web/src/tour/data/index.tsx, doc/cody/capabilities/commands.md, doc/cody/capabilities/index.md, doc/cody/overview/install-jetbrains.md, doc/cody/overview/install-vscode.md, doc/getting-started/index.md
Adhere to https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/style_and_mechanics/.
CI
[Preview Link](https://docs.sourcegraph.com/@sqs/more-edit-fixes)
=> more style fixes in text

internal/completions/httpapi/handler.go, internal/completions/types/errors.go, internal/completions/types/errors_test.go
Manual testing with Philipp and David, code review.
=> Attempt to fix 429 error reporting for Cody Pro

cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
edit: trivial change, CI will cover it.
=> Add GPT4 to Pro User Allowlist

cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
=> Allow instant models for free users

cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
Here is a [4-min Loom](https://www.loom.com/share/587832673f554047a5b2aaf1cee5dead?sid=f53dd3a6-c905-4462-a9a2-7e54c4b5876a) where I show the rationale behind this change.
I'll have auto-merge enabled, so please only approve if you feel this is good enough. I'll also try to be around for fixes.
Tested it with cURL, and I saw it fixes the problem in my test case.
=> SSC: Ugly hack to fix the user data caching in gateway

cmd/frontend/graphqlbackend/git_tree_entry.go
=> dotcom: render known lock files as plaintext

cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go, internal/completions/httpapi/chat.go, internal/completions/httpapi/codecompletion.go
This should fix some issue that we're seeing with symf. I hope.
Check after rollout. It doesn't repro locally.
=> More leniently allow claude instant v1 models

dev/release/templates/patch_release_issue_template.md
=> Add the step to create the release tracking issue

client/web/src/repo/blob/codemirror/search.tsx
Follow up for https://github.com/sourcegraph/sourcegraph/pull/58218#discussion_r1388343328
- Check that regex document search still works properly
=> [Blob UI]: Re-use cursor iterator in file match search calculations

dev/managedservicesplatform/spec/spec.go
=> msp/spec: check length of final project name

client/web/src/cody/subscription/CodySubscriptionPage.tsx
As reqeusted by @chenkc805
- No "Coming soon" badge
- No price or team limit - replace with "Coming soon"
- Change CTA to "Request Info"
It looks like this:
=> SSC: Enterprise copy tweaks

dev/buildchecker/README.md, dev/buildchecker/slack.go, dev/buildchecker/slack_test.go
=> dev: remove deadlink from buildchecker

doc/index.md
Docs added
[Preview Link](https://docs.sourcegraph.com/@fix-typo)
=> Fix typo on main docs page

internal/ratelimit/globallimiter.go
=> globallimiter: Make enum values const

cmd/cody-gateway/internal/httpapi/featurelimiter/BUILD.bazel, cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
I think I landed a change with some bad bazel
CI
=> cody-gateway: bazel configure

.github/teams.yml, .github/test.CODEOWNERS, .github/workflows/label-notify.yml
Hope you appreciate less emails from new tickets in our repo 😬 
n/a
=> Stop tagging @mrnugget

.aspect/workflows/config.yaml
Performance on warm small runners for gazelle & buildifier tasks on e2-medium machines looks good: https://buildkite.com/sourcegraph/aspect-experimental/builds/3371
CI
=> build: use small low-cost Aspect Workflows runners for buildifier, gazelle & finalization steps

CHANGELOG.md
Relates to #58927
just a doc change
=> changelog: display GitHub/GitLab topics

doc/cloud/index.md
=> docs: update cloud limitation

doc/cloud/index.md
https://sourcegraph.slack.com/archives/C03JR7S7KRP/p1703268636194889
n/a
=> docs: update cloud api rate limit

lib/managedservicesplatform/runtime/sanitycheck.go, lib/managedservicesplatform/runtime/service.go
Useful for checking the build version
n/a
=> lib/msp: dump service metadata on SANITY_CHECK

cmd/frontend/auth/user.go, internal/security/security.go
Thought it might be easier to do feedback like this :)
=> Minor refactoring and remove redundant checks

.bazeliskrc, client/browser/BUILD.bazel, client/shared/BUILD.bazel, client/shared/src/testing/BUILD.bazel, client/web/src/regression/BUILD.bazel
Cleans up the spam:
```
2023/12/22 01:53:17 finding module path for import slices: finding module path for import slices: template: main:1:9: executing "main" at <.Module.Path>: nil pointer evaluating *modinfo.ModulePublic.Path
2023/12/22 01:53:17 finding module path for import slices: finding module path for import slices: template: main:1:9: executing "main" at <.Module.Path>: nil pointer evaluating *modinfo.ModulePublic.Path
2023/12/22 01:53:17 finding module path for import slices: finding module path for import slices: template: main:1:9: executing "main" at <.Module.Path>: nil pointer evaluating *modinfo.ModulePublic.Path
2023/12/22 01:53:17 finding module path for import slices: finding module path for import slices: template: main:1:9: executing "main" at <.Module.Path>: nil …
```
=> chore: upgrade to Aspect CLI 5.8.19

dev/sg/dependencies/mac.go, dev/sg/dependencies/ubuntu.go
Original message was confusing, see [slack](https://sourcegraph.slack.com/archives/C04MYFW01NV/p1703817143818289). This clarifies what's going on exactly. 
CI
=> sg: clarify setup restart message

lib/managedservicesplatform/runtime/contract_bigquery.go, lib/managedservicesplatform/runtime/contract_postgresql.go
=> msp/runtime: add checks to detect capabilities

flake.lock, shell.nix
Now that its landed on nixpkgs-unstable https://nixpk.gs/pr-tracker.html?pr=262152
`bazel version` shows 7.0.0
=> nix: bump to bazel 7

cmd/cody-gateway/internal/events/events.go, cmd/cody-gateway/internal/httpapi/completions/upstream.go, cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
Add information about limit that was hit and retry_after period.
=> Add rate limit information to RateLimited events

doc/admin/observability/alerts.md, doc/admin/observability/dashboards.md, monitoring/go.mod, monitoring/monitoring/BUILD.bazel, monitoring/monitoring/owners.go, monitoring/monitoring/owners_test.go
This updates ownership for search, code insights, and batch changes. 
N/A
=> Monitoring: update owners for code insights and batches

dev/managedservicesplatform/spec/environment.go, dev/sg/msp/example/example_test.go, dev/sg/msp/example/testdata/TestNewJob/dev/insert_environment.golden, dev/sg/msp/example/testdata/TestNewJob/dev/spec.golden, dev/sg/msp/example/testdata/TestNewJob/prod/insert_environment.golden, dev/sg/msp/example/testdata/TestNewJob/prod/spec.golden, dev/sg/msp/example/testdata/TestNewService/dev.golden, dev/sg/msp/example/testdata/TestNewService/dev/insert_environment.golden, dev/sg/msp/example/testdata/TestNewService/dev/spec.golden, dev/sg/msp/example/testdata/TestNewService/prod.golden, dev/sg/msp/example/testdata/TestNewService/prod/insert_environment.golden, dev/sg/msp/example/testdata/TestNewService/prod/spec.golden
Visual inspection of new golden files. Before the template fix, we would also get an error ("env ID not in project ID")
=> sg/msp: improve test coverage on examples, fix project ID generation

client/web/src/util/permission.ts, internal/rbac/gen/yamldata.go
Due to auto-merge, I missed out on some comments @camdencheek shared on #59236.
This PR implements them.
CI tests should be passing.
=> code-search: nitpitck for rbac refactor

client/web-sveltekit/src/lib/fileIcons.ts, client/web-sveltekit/src/lib/search/utils.ts, client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
Fixes TS/format issues introduced by recent commits.
`pnpm check` doesn't report any issues with files inside `client/web-sveltekit`.
=> svelte: Fix issues reported by svelte-check

deps.bzl, go.mod, go.sum, lib/go.mod, lib/go.sum, lib/managedservicesplatform/go.mod, lib/managedservicesplatform/go.sum
To include [this fix](https://github.com/sourcegraph/conc/pull/132)
CI
=> Chore: bump conc

internal/database/external_services.go, internal/database/external_services_test.go
Closes #59412 
Refactors the calcUnrestricted function so that the logic is a bit more clear.
Unit tests added to ensure refactor is safe
=> Refactor calcUnrestricted function

internal/accesstoken/personal_access_token_test.go, internal/database/access_tokens_test.go
pre-commit flags  these tokens but the tokens are for testing
tested locally
=> pre-commit: add pre-commit directives to token tests

cmd/frontend/graphqlbackend/schema.graphql, internal/database/users.go
Just minor update to the PR. Thought it might be easier to do it like this rather than go back and forth in the comments.
=> Minor PR feedback

.github/workflows/universal-ctags.yml
Fixed bad copy-paste job :clown_face: 
Manually invoked workflow https://github.com/sourcegraph/sourcegraph/actions/runs/7476990901/job/20348648403
=> chore: fix universal-ctags darwin GHA workflow

CHANGELOG.md
Minimal mentions of things I know of in v5.2.6 release
Docs
=> add a few changes for v5.2.6 release

dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go, dev/managedservicesplatform/stacks/monitoring/monitoring.go
Part of https://github.com/sourcegraph/managed-services/issues/328
https://github.com/sourcegraph/managed-services/actions/runs/7496449586
=> msp/alertpolicy: generate links to generated handbook docs

docker-images/opentelemetry-collector/builder.template.yaml
Part of https://github.com/sourcegraph/sourcegraph/pull/59561#issuecomment-1890116710
CI
=> otel-collector: add k8sattributesprocessor

dev/sg/sg_ops.go
=> sg: allow one to specify custom registries

dev/ci/internal/ci/misc_operations.go, dev/sg/linters/BUILD.bazel, dev/sg/linters/linters.go, dev/sg/linters/misc.go
Temporarily emit telemetry on sg-lint steps to honeycomb to determine timings
https://ui.honeycomb.io/sourcegraph/datasets/sg-lint-buildkite/result/FeP9mXgMxzB
=> ci: emit sg lint honeycomb timings in CI (temporary)

dev/managedservicesplatform/spec/spec.go
Made the mistake of forgetting to change the domain when setting up a new test environment in `msp-testbed`
n/a
=> msp: validate that domains are unique across environments

dev/ci/internal/ci/client_operations.go
We're hitting an internal server error with too many files uploaded. This disables the step until we can figure out how to deal with that
None - this disables a step
=> ci: disable chromatic

cmd/cody-gateway/internal/httpapi/completions/upstream.go
When proxying upstream requests, we shouldn't be forwarding hop-by-hop headers as defined in [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html) and redefined later. 
- tested locally with a fake backend
=> Do not forward hop-by-hop headers

lib/managedservicesplatform/bigquerywriter/bigquerywriter.go, lib/managedservicesplatform/runtime/contract_bigquery.go
Error from https://github.com/sourcegraph/sourcegraph/pull/59604
Deploy to msp-testbed
=> lib/msp: fixup bigquerywriter creation

doc/cloud/private_connectivity_sourcegraph_connect.md
This came up with a thread with customer. let's write this down for future references.
CI
[Preview Link](https://docs.sourcegraph.com/@michaellzc-patch-4)
=> docs: update src connect security faq

client/web/src/repo/actions/CopyPermalinkAction.tsx
Fixes the copy link that was copying the url without a base url. 
CI/CD
=> Code Navigation: fix broken `copy` link

.github/workflows/scip-typescript.yml, cmd/frontend/internal/executorqueue/queues/codeintel/transform.go, cmd/frontend/internal/executorqueue/queues/codeintel/transform_test.go
Missed these the first time around
CI
[Preview Link](https://docs.sourcegraph.com/@christoph/lsif-to-code-intel)
=> More updates for deprecated src-cli command

cmd/frontend/internal/search/search.go
This updates the search stream to properly calculate the source for honeycomb events. Currently, our sentinel metrics in Honeycomb only represent GraphQL requests because we do not properly set the source string. This means that we're not getting any good metrics on latency (which we don't measure for GraphQL since it doesn't make sense), only duration.
Attached a debugger and saw that the string was correctly set.
=> Search: fix source for honeycomb logging

client/web/BUILD.bazel, client/web/src/repo/actions/CopyPermalinkAction.tsx, client/web/src/repo/actions/actions.test.ts
Adds a test to ensure the correct url is being copied to the keyboard by the "copy link" button
The code itself is a unit test. Shipped as passing.
=> Code Navigation: Add test to prevent URL bug

cmd/frontend/graphqlbackend/search_results.go, cmd/frontend/internal/search/event_writer.go, internal/search/streaming/filters.go, internal/search/streaming/filters_test.go, internal/search/streaming/search_filters.go, internal/search/streaming/search_filters_test.go
Just a small cleanup to make FilterKind a typed string and put all the possible values in one place.
CI. No change in behavior.
=> Search: make FilterKind typed

internal/vcs/url.go, internal/vcs/url_test.go
See inline comment for reasoning.
Added a test.
=> hack: Add support for iap:// URLs

shell.nix
Host clang for bazel reason:
```
ERROR: /Users/noah/Sourcegraph/sourcegraph/BUILD.bazel:305:5: GoLink sg_nogo_actual_/sg_nogo_actual [for tool] failed: (Exit 1): builder failed: error executing GoLink command (from target //:sg_nogo_actual) bazel-out/darwin_arm64-opt-exec-ST-1a88b5d644a4/bin/external/go_sdk/builder_reset/builder '-param=bazel-out/darwin_arm64-opt-exec-ST-1a88b5d644a4/bin/sg_nogo_actual_/sg_nogo_actual-0.params' -- -extld ... (remaining 6 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/go_sdk/pkg/tool/darwin_arm64/link: running external/local_config_cc/cc_wrapper.sh failed: exit status 1
ld: framework not found CoreFoundation
clang: error: linker command failed with exit code 1 (use -v …
```
=> nix: use clang11Stdenv for shell and host clang for bazel on macos

dev/release/release-config.jsonc
=> release: activate 5.2.7 release

CHANGELOG.md
=> release: 5.2.7 changelog update

cmd/frontend/auth/auth.go, cmd/frontend/auth/user.go, cmd/frontend/auth/user_test.go
Make the users' life a little bit better.
CI
=> auth: retry user creation once with random suffix when in collision

internal/updatecheck/handler.go
=> updatecheck: remove error logging for client side errors

internal/search/job/jobutil/job_test.go, internal/search/types.go
This was only referenced in tests.
=> search: remove unused GlobalSearchMode

internal/search/job/jobutil/job_test.go
This captures an inefficent job plan we came across when investigating global queries against zoekt with ors and ands in them. It is a noop change.
=> search: test case for global zoekt query translation failing

internal/updatecheck/handler.go
This pull request is part of the Sourcegraph 5.2.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59830)
=> release: sourcegraph@5.2.7

dev/release/release-config.jsonc, dev/release/src/release.ts
=> release: deactivate 5.2.7 release

CHANGELOG.md
=> docs: Add CHANGELOG entries related to graph/code nav

client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss, client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
Fixes https://github.com/sourcegraph/sourcegraph/issues/59897
- Check that footer action UI is sticky but footer doc link is not
=> Search Filters: Fix filters action sticky layout

doc/cloud/index.md
copy from https://docs.google.com/document/d/1c4OKkUEt_RGiDJUJoWElBx1heat3hNkXMLfnmGUHYDs/edit#task=hqLZPYKQBHcV-GRq
DO NOT MERGE until https://github.com/sourcegraph/controller/pull/1316 is deployed
docs only 
[Preview Link](https://docs.sourcegraph.com/@michaellzc-patch-4)
=> docs: add cloud security faq

client/web/src/site-admin/analytics/AnalyticsCodeIntelPage/index.tsx, internal/codeintel/autoindexing/internal/inference/libs/update-shas.sh, internal/codeintel/uploads/shared/indexers2.go
We should not be recommending the old LSIF indexers
n/a
=> client: Update lsif-{clang,dart,php}->scip-{clang,dart,php}

internal/gitserver/protocol/gitserver.go
Seems to be a flipped condition, fixing here.
Test suite and code review.
=> gitserver: Fixup error conversion to RepoNotExistError in search

cmd/frontend/internal/search/search.go
We recently forced gzip compression on responses from the streaming endpoint. However, we have noticed a significant performance regression in search blitz which is likely due to it. Search blitz runs in the same data-center as dotcom, so the compression didn't help download speed but did vastly increase response time.
Camden pointed out using gzip.BestSpeed on the original PR and in my testing it is a significant improvement on CPU use with an acceptable decrease in compression ratio. Here is the table from my testing on a real life example:
| encoding   |      size | time  |
|------------|-----------|-------|
| none       | 287728396 | 0.1s  |
| zstd       |  64662426 | 0.9s  |
| gzip-speed | 102231337 | 2.4s  |
| br         |  61296159 | 9.1s  |
| gzip       |  86795072 | 10.7s |
| …
=> search: use gzip.BestSpeed for streaming endpoint

cmd/frontend/graphqlbackend/BUILD.bazel, cmd/frontend/graphqlbackend/site.go, cmd/frontend/graphqlbackend/site_test.go, internal/cloud/site_config.go, internal/conf/diff.go
(cherry picked from commit 736af892a39306ed0f23b7605af7a39a30ab62e1) https://github.com/sourcegraph/sourcegraph/pull/59884
CI
=> soap: add support for site config allowlist (#59884)

internal/trace/url.go
This showed up in some profiles as being an area of ~high contention, 99% of which is coming from parsing the template string every time. This PR adds some caching to it.
n/a - code review
=> trace: Memoize template for trace URL

dev/managedservicesplatform/managedservicesplatform.go
Fixup for https://github.com/sourcegraph/sourcegraph/commit/7a05a723e59947f5f2519c8c2b1b09874d481c53
Applied to sams-dev
=> msp/monitoring: fixup alerting config drilling

doc/admin/observability/logs.md
n/a
[Preview Link](https://docs.sourcegraph.com/@bobheadxi-patch-1)
=> doc: update log levels

dev/managedservicesplatform/spec/environment.go
=> msp/cloudrun: fixup configuration YAML

client/web/src/cody/onboarding/instructions/JetBrains.tsx
closes: https://github.com/sourcegraph/accounts.sourcegraph.com/issues/384
Update JetBrains Marketplace Link
- visit cody/mange
- click on any jet brains ide
=> Update JetBrains Marketplace Link

dev/managedservicesplatform/stacks/monitoring/cloudsql.go
Adjust alerts to have more durations, and add a sustained/spike variant for the per-query lock times.
n/a
=> msp/monitoring: adjust cloudsql alerts

dev/release/release-config.jsonc
=> release: activate 5.3 release

docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
=> highlighter: Simplify OffsetManager::new a bit

dev/managedservicesplatform/stacks/monitoring/service.go
Closes https://github.com/sourcegraph/managed-services/issues/470
Click-ops the same metric
https://github.com/sourcegraph/managed-services/actions/runs/7744233533
=> msp/monitoring: add pending requests alert

dev/managedservicesplatform/managedservicesplatform.go, dev/managedservicesplatform/stacks/monitoring/cloudsql.go, dev/managedservicesplatform/stacks/monitoring/monitoring.go
Closes https://github.com/sourcegraph/managed-services/issues/471
Clicks-ops new metrics
=> msp/monitoring: add CloudSQL connections alert, prefix all

dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go, dev/managedservicesplatform/internal/resource/logcountmetric/BUILD.bazel, dev/managedservicesplatform/internal/resource/logcountmetric/logcountmetric.go, dev/managedservicesplatform/stacks/monitoring/BUILD.bazel, dev/managedservicesplatform/stacks/monitoring/monitoring.go, dev/managedservicesplatform/stacks/monitoring/service.go
Closes https://github.com/sourcegraph/managed-services/issues/374. I think I may have spent a bit too much time making this clever... let's keep it simple 😅 
Tested briefly on sams-dev:
Also https://github.com/sourcegraph/managed-services/actions/runs/7744222455
=> msp/monitoring: alert on Cloud Run status logs indicating service failure

dev/sg/sg_bazel.go
After going through our docs, it appears `aspect configure` can behave differently in a subdir of the repo root, so we shouldn't set the subcommand dir to be the repo root when invoking through `sg bazel configure`.
Also improving some help messages that were missed
Various (sub)commands of `sg bazel`
=> sg: remove repo root detection and improve help messages

client/web/src/enterprise/site-admin/dotcom/productSubscriptions/plandata.ts
Oops, inconsistency. 
Manual verification.
=> Fixup tag of cody enterprise plan

client/branded/BUILD.bazel, client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss, client/branded/src/search-ui/results/filters/NewSearchFilters.story.tsx, client/branded/src/search-ui/results/filters/NewSearchFilters.tsx, client/branded/src/search-ui/results/filters/components/DynamicFilterBadge.tsx, client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss, client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx, client/branded/src/search-ui/results/filters/components/filter-skeleton/SearchFilterSkeleton.module.scss, client/branded/src/search-ui/results/filters/components/filter-skeleton/SearchFilterSkeleton.tsx, client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.tsx, client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.module.scss, client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.tsx, client/branded/src/search-ui/results/filters/types.ts, client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.module.scss, client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx, client/web/src/search/results/components/filters-panel/SearchFiltersPanel.tsx, client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
Original PR https://github.com/sourcegraph/sourcegraph/pull/60073
(cherry picked from commit c32dba7b5cecfe067c4166bb78807f03ebdeec98)
Short description, this original PR contains small design tweeks around hover and loading states
- CI passes
=> Search results design tweaks (#60073)

client/web/src/storm/pages/SearchPage/KeywordSearchCtaSection.module.scss
Adjusts spacing according to the specifications in #60196
Before: 
After:
CI/CD passing
=> Keyword Search: re-space keyword search cta

client/web/src/nav/GlobalNavbar.module.scss, client/web/src/search/results/components/new-search-content/NewSearchContent.module.scss
Tweak colors on search results. Reference #60072 
CI/CD... just color changes
=> tweet colors on search results

cmd/gitserver/internal/patch.go
This PR refactors all the "p4" invocations in cmd/gitserver/internal/patch.go to use the new `perforce.NewBaseCommand` API introduced in https://github.com/sourcegraph/sourcegraph/pull/59997. 
As a note,  I think the flow of original code is a bit odd  (a lot of bespoke functions with only one usage), but I believe it's best to keep this change as minimal as possible. 
CI
=> gitserver: fix cmd/gitserver/internal/patch.go to use new perforce.NewBaseCommand utility

client/web/src/search/results/components/search-results-info-bar/SearchResultsInfoBar.tsx, client/web/src/storm/pages/SearchPage/KeywordSearchCtaSection.tsx
Make sure to vertically center the beta badge.
Follow up to #60189
Manual testing
=> Keyword search: center beta badge

CHANGELOG.md
=> changelog: cut sourcegraph@5.3.0

sg.doctor.yaml
Add diagnostics to show:
- size of `client/web/dist`
- size of `~/.sourcegraph`
- content of `~/.sourcegraph/repos`, `~/.sourcegraph/repos_1`, `~/.sourcegraph/repos_2`
Executed locally
```
Command:  du -sh ~/.sourcegraph/
Output:
8.6G  /Users/william/.sourcegraph/
Error:
<nil>
Command:  du -sh client/web/dist
Output:
285M  client/web/dist
Error:
<nil>
Command:  find ~/.sourcegraph/repos -type d -maxdepth 2 -type d find ~/.sourcegraph/repos_1 -type d -maxdepth 2 -type d find
~/.sourcegraph/repos_2 -type d -maxdepth 2 -type d
Output:
/Users/william/.sourcegraph/repos
/Users/william/.sourcegraph/repos/devx-scratch
/Users/william/.sourcegraph/repos/devx-scratch/.git
/Users/william/.sourcegraph/repos/embeddings-api
/Users/william/.sourcegraph/repos/embeddings-api/.git …
```
=> sg doctor: add disk category to sg doctor

client/web/src/featureFlags/featureFlags.ts
Searched for hits in this codebase and all those removed only had hits in this file.
Test Plan: CI
=> client: remove unread FEATURE_FLAGS

cmd/cody-gateway/internal/httpapi/completions/fireworks.go, cmd/cody-gateway/shared/config/config.go
Stop rewriting ST models strings now that we support ST Starcoder.
- e2e tests pass
=> Remove code for rewriting st models

CHANGELOG.md, client/web/BUILD.bazel, client/web/src/site-admin/analytics/AnalyticsCodyPage/index.tsx, client/web/src/site-admin/routes.tsx, client/web/src/site-admin/sidebaritems.ts
Adds a link to Cody Analytics service.
[Figma](https://www.figma.com/file/pMaNBzIz3to8ujUsRX4f7I/Cody-analytics?type=design&node-id=8-32&mode=design&t=QqFheUIS2zNQYY28-0)
- CI
- Tested manually
=> site admin: add link to Cody Analytics

client/web/src/cody/useCodyChat.tsx
=> repo -> file in cody chat

sg.config.yaml
Searched codebase, no usages. Ran locally, nothing broke.
=> sg: Remove unused old env var

dev/sg/sg_bazel.go
=> sg bazel: add completions for 'configure'

dev/sg/sg_bazel.go
Pretty please? 😄 
```
sg bz configure
```
=> sg bazel: add 'bz' alias

cmd/gitserver/internal/server.go, cmd/gitserver/internal/server_grpc.go, cmd/gitserver/internal/server_grpc_test.go
Now that we know how often this is going to be copied, I decided to make a helper function.
Existing tests verify that the behavior hasn't been changed (except for the error string)
=> gitserver: Make helper function for maybeStartClone

cmd/gitserver/internal/clone.go, cmd/gitserver/internal/mocks_test.go, cmd/gitserver/internal/patch.go, cmd/gitserver/internal/perforce/command.go, cmd/gitserver/internal/server.go, cmd/gitserver/internal/server_grpc.go, cmd/gitserver/internal/server_grpc_test.go, internal/gitserver/client_test.go, internal/gitserver/protocol/gitserver.go
- The logger was unused
- The CloneRepo function does exactly the same check as MaybeStartClone did, so this can be simplified.
Existing tests, and integration test suite.
=> gitserver: Minor cleanups

deps.bzl, go.mod, go.sum
https://github.com/sourcegraph/zoekt/compare/245e0cebf761...1c158f9b8661
- https://github.com/sourcegraph/zoekt/commit/b227501acf all: gofumpt -l -w .
- https://github.com/sourcegraph/zoekt/commit/1c158f9b86 Don't truncate file before detecting language
=> gomod: Bump Zoekt for better lang detection

internal/conf/validate.go
Solves https://github.com/sourcegraph/sourcegraph/issues/60045 
Run in admin and try to save access token and you shall get this.
=> Redacting attribution Gateway access token

dev/release/src/github.ts
We now run bazel in the release tool, but it depends on configuration created by sg setup or our nix flake. The work directory will only contain files committed to the repository, so we copy over the bazel specific configuration which is git ignored.
Test Plan: get a little further when running "pnpm run release release:bake-content"
=> release: copy over bazel user rc files to sg workdir

CHANGELOG.md
This adds changelog entries for the big items we shipped this quarter. Feel free to suggest any additional items.
N/A
=> Search: add changelog entries for 5.3

dev/ci/internal/ci/pipeline.go, internal/updatecheck/handler.go
This pull request is part of the Sourcegraph 5.3.0 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60032)
cc @keegancsmith
=> release: sourcegraph@5.3.0

dev/release/src/release.ts
=> release: ignore executors_kubernetes.mdx during release

cmd/cody-gateway/internal/httpapi/BUILD.bazel, cmd/cody-gateway/internal/httpapi/handler.go, deps.bzl, go.mod, go.sum
This reverts commit cafef3509dac607416e8f7d65cdcaf6c7badced4.
So far, it has increased CPU usage slightly [(~10%)](https://console.cloud.google.com/monitoring/metrics-explorer;duration=PT1H?pageState=%7B%22domainObjectDeprecationId%22:%22A7EE4707-B929-44F4-9FB3-817BDF2150FD%22,%22xyChart%22:%7B%22constantLines%22:%5B%5D,%22dataSets%22:%5B%7B%22legendTemplate%22:%2299%25%22,%22plotType%22:%22LINE%22,%22targetAxis%22:%22Y1%22,%22timeSeriesFilter%22:%7B%22aggregations%22:%5B%7B%22crossSeriesReducer%22:%22REDUCE_PERCENTILE_99%22,%22groupByFields%22:%5B%22resource.label.%5C%22service_name%5C%22%22%5D,%22perSeriesAligner%22:%22ALIGN_SUM%22%7D%5D,%22apiSource%22:%22DEFAULT_CLOUD%22,%22crossSeriesReducer%22:%22REDUCE_PERCENTILE_99%22,%22filter%22:%22metric.type%3D%5C%22run.googleapis.com%2Fcontain …
=> Revert "Support compression for embedding endpoint (#60459)"

dev/gqltest/sub_repo_permissions_test.go
Fixed in https://github.com/sourcegraph/sourcegraph/pull/57854
Closes https://github.com/sourcegraph/sourcegraph/issues/40883
n/a removed a comment only
=> Remove outdated comment on flakiness

dev/release/release-config.jsonc
=> release: config update

cmd/frontend/internal/guardrails/BUILD.bazel, cmd/frontend/internal/guardrails/init.go
=> [dotcom] log.NoOp passed into attribution search client

cmd/frontend/internal/app/ui/raw_test.go, internal/gitserver/client.go
Just removed some mock code, CI should find any issues.
=> gitserver: Small mocks cleanup

dev/sg/sg_ops.go
This adds a new flag that allows us to run `sg ops update-images --only='gitserver'` to update only the image of a specific service.
Code review.
=> sg: Support only flag in sg ops update-images

dev/sg/sg_ops.go
=> sg: Fix only flag

client/web/src/cody/subscription/CodySubscriptionPage.tsx
Updates the Cody subscription page for changes to the Enterprise plan.
@thenamankumar will run `sg start dotcom` locally and then manually QA https://sourcegraph.test:3443/cody/subscription.
=> Update Cody Enterprise plan

cmd/repo-updater/shared/main.go, internal/database/orgs.go
These query paths weren't tested so didn't find them initially, although I tried to go over all search results for external_services and external_service_repos.
Went over the results again, these were the only two remnants I found.
=> Remove references to dropped columns

internal/search/backend/metered_searcher.go
Before this commit we only logged it searching actual instances. However, we only send to honeycomb the aggregator. In practice this will lead us to logging the time for the very first zoekt to respond.
=> search: log stream.latency for zoekt aggregator

dev/release/release-config.jsonc
=> release: activate 5.3.1 release

CHANGELOG.md
=> release: prep changelog for 5.3.1 and beyond

internal/codeintel/uploads/transport/http/BUILD.bazel, internal/codeintel/uploads/transport/http/auth/BUILD.bazel, internal/codeintel/uploads/transport/http/auth/middleware.go, internal/codeintel/uploads/transport/http/auth/middleware_test.go, internal/codeintel/uploads/transport/http/handler.go, internal/codeintel/uploads/transport/http/handler_test.go, internal/codeintel/uploads/transport/http/init.go, internal/uploadhandler/upload_handler.go, internal/uploadhandler/upload_handler_state.go
Also does some refactorings
CI, locally tested
=> Adds tests for upload middleware

client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx
Run locally to make sure nothing broke.
=> enable auth token redirects to Cursor

dev/release/release-config.jsonc
=> release: deactivate 5.3.1 release

cmd/frontend/graphqlbackend/repository_text_search_index.go
Came across this since I was checking we always set ChunkMatches: true. I additionally listed a few more options to ensure we don't bother sending back all the matches since we only rely on the stat. Additionally I raise the limits just to make sure we give accurate counts.
Test Plan: check not indexed count didn't change in dev server
=> search: set options for NOT-INDEXED search

internal/search/backend/metered_searcher.go
When inspecting honeycomb there are lots of very noisy errors which are due to timeouts or cancellations. It is noisy since it is a combined error of all the backends that didn't finish. Additionally these are not errors, but rather expected behaviour due to how we use context to implement match limits and timeouts.
This commit instead does not record the error field in that case, but instead expands the "code" field to do record this. So we now have a more useful prometheus metric as well as the code field in honeycomb.
=> search: do not record full error for cancel or timeout

client/web/src/enterprise/rbac/SiteAdminRolesPage.tsx
Roles isn't exclusively available to Batch Changes anymore.  A number of services/products have since adopted RBAC so I'm updating the UI here.
UI update.
=> update roles page description

internal/search/zoekt/query.go
I think this was a leftover when we where experimenting with keyword search.
=> search: remove unused toZoektPatternNew

dev/sg/ci/subcommands.go
Instead of having to make a commit, just take the staged files (if using the --staged flag)
I ran it locally! : ) https://buildkite.com/sourcegraph/sourcegraph/builds/263512#018df461-13a2-4dd3-8c2c-164024720745
=> sg: add flag to allow running sg ci bazel with current staged files

internal/conf/conf.go
See the inline comments, this PR will allow to add standalone commands to `sg` where we can run e.g. gitserver without requiring a frontend to be running. This can be useful to test services without the full stack, which reduces load and recompile times, and doesn't trigger any requests to the services that you don't want.
Wrote a standalone config for gitserver and it can start up and run properly.
=> conf: Allow a local stub file

cmd/gitserver/internal/vcssyncer/BUILD.bazel, cmd/gitserver/internal/vcssyncer/packages_syncer.go
Merge conflict with https://github.com/sourcegraph/sourcegraph/pull/60810
CI
=> vcssyncer: fix dotcommode check

cmd/gitserver/internal/server.go
These values were left empty, which meant that right after a clone the
scheduler thinks a repo is in dire need of a git fetch, even when the
newly cloned repo hasn't been active in ages.
Verified correct data using gRPC UI.
=> gitserver: Populate last_changed and last_fetched fields for clone

client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.tsx
I introduced a new typo while fixing another one in #60822 :-(
Test plan:
N/A
=> search-jobs: fix typo (part 2)

cmd/gitserver/internal/vcssyncer/BUILD.bazel, cmd/gitserver/internal/vcssyncer/packages_syncer.go
A merge conflict reintroduced a use of a package that no longer exists.
`main` builds
=> Chore: fix bad merge

internal/search/result/BUILD.bazel, internal/search/result/file.go, internal/search/result/file_test.go
This is a band-aid in response to https://github.com/sourcegraph/sourcegraph/issues/60605. I still plan to follow up with a more complete fix, but wanted to fix the immediate problem so we 1) have a solution for customers who hit this, and 2) can get a patch release out since there is not another planned for 2 more weeks. 
Added unit test.
=> Search: protect against panic

internal/codeintel/autoindexing/internal/inference/iface.go
=> Fix small typo in gitserver scope

dev/tool_deps.bzl
Update src-cli to 5.3.0 for executors.
CI + inspect docker container to check the resulting version.
=> Bump src-cli to 5.3.0 for executors (#60705)

.aspect/workflows/config.yaml, dev/ci/internal/ci/aspect_workflows.go, dev/ci/internal/ci/images_operations.go, dev/ci/internal/ci/wolfi_operations.go
before: 
after:
CI + see above
=> ci: label the integration tests properly

internal/auth/userpasswd/handlers_test.go, internal/search/casetransform/lower_regexp_test.go, internal/search/job/jobutil/job_test.go
=> Fix tests for go 1.22

internal/cody/subscription.go, internal/cody/subscription_test.go
As part of [#inc-284-plg-users-paying-for-and-being-billed-for-pro-without-being-upgrade](https://sourcegraph.slack.com/archives/C06N8ELPKNH/p1709796118502059) it is noted that users have multiple SAMS accounts associated with their dotcom account.
Originally we only fetched subscription data from the first SAMS account associated with the user. As part of this PR, we are now fetching subscription data from all SAMS accounts associated with the user, and using the one with an active subscription. This is only a TEMPORARY solution to mitigate the incident. If there is no active subscription, we default to the first subscription fetched. 
MUST be removed/fixed once we have a proper solution in place as part of [#60912](https://github.com/sourcegraph/sourcegraph/issues/60912).
unit tests …
=> Merge cody subscription details from multiple associated SAMS accounts

internal/search/backend/horizontal.go
Follow-up to #60878. Now that we've updated to Go 1.22, we don't need to copy
loop variables before using them in goroutines.
Just a warm-up before I open a bigger PR to fix this in other places.
Covered by existing tests like `horizontal_test.go`.
=> Search: simplify goroutine params

dev/release/release-config.jsonc
`pnpm release release:prepare`
N/A
=> Release: prepare 5.3.2 release

dev/release/release-config.jsonc
`pnpm run release release:activate-release`
N/A
=> Release: activate 5.3.2 release

dev/managedservicesplatform/stacks/project/project.go
Adds bigquery connection API to allow for connecting big query to cloudsql
CI, local generated TF, applied to testbed
=> sg/msp: add `bigqueryconnection.googleapis.com` api

CHANGELOG.md
=> Release: update changelog for v5.3.2

internal/updatecheck/handler.go
This pull request is part of the Sourcegraph 5.3.2 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60972)
=> release: sourcegraph@5.3.2

cmd/frontend/graphqlbackend/roles_test.go, cmd/frontend/graphqlbackend/user.go
Currently, listing roles associated with a user on dotcom fails with the error `roles are not available on sourcegraph.com`. However, roles _are_ available on dotcom and you can configure them for users (e.g. Entitler, #60795), but there's no way to check what roles a user has with  the current guard.
This relaxes the restriction to allow site admins to view a user's roles.
Test case
=> graphqlbackend: allow siteadmins to view roles on dotcom

gen.go
=> chore: fixup go-mockgen run statement

dev/ci/images/images.go
Remove the safeguard from `main` branch that I left in #60962  
CI
=> fix: ci: remove safeguard for prod registry

cmd/gitserver/internal/cleanup.go, cmd/gitserver/internal/search.go, cmd/gitserver/internal/server_test.go, cmd/gitserver/internal/vcssyncer/jvm_packages.go, cmd/gitserver/internal/vcssyncer/npm_packages_test.go
Trusting CI that it'll find things.
=> gitserver: Fix some lint warnings

.buildkite/pipeline.backcompat.yml, dev/backcompat/bazel-backcompat.sh
@jamesmcnamara and I paired on this. Does what it says in the title
Closes https://github.com/sourcegraph/sourcegraph/issues/60249
https://buildkite.com/sourcegraph/sourcegraph-backcompat/builds/26257
=> ci: let backcompat tests run on aspect workflow agents

cmd/frontend/auth/user_test.go
Follow up on https://github.com/sourcegraph/sourcegraph/pull/61119#discussion_r1523821235
CI
=> auth: fix ineffective test

client/web/src/open-in-editor/OpenInEditorPopover.tsx
Some updates to the editor button copy to make it more obvious what is meant by the "Default projects path"
[Requesting Slack thread](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1710333723801189)
=> Web app: open in editor copy updates

internal/conf/validate.go, internal/conf/validate_test.go
=> conf: redact `dotcom.sams.clientSecret` site config

dev/backcompat/bazel-backcompat.sh
=> ci: Fetch tag before checkout in backcompat test

.gitignore
Just a quick cleanup while I was taking a look at the .gitignore file to figure out why some files were unintentionally being ignored.
Removing these did not uncover any ignored files.
=> Chore: clean up .gitignore

CHANGELOG.md
To be merged after landing https://github.com/sourcegraph/sourcegraph/pull/60989
n/a
=> docs: Update CHANGELOG for bug-fixes

CHANGELOG.md
Updates the changelog to reflect this backport: https://github.com/sourcegraph/sourcegraph/pull/61212
Changelog update
=> Update changelog for 5.3 backport

release.yaml, tools/release/slack.sh
=> Update manifests to post Slack messages on internal releases and public promotions

cmd/cody-gateway/internal/httpapi/completions/fireworks.go, cmd/cody-gateway/internal/httpapi/completions/fireworks_test.go, cmd/cody-gateway/shared/config/config.go
No longer needed after https://github.com/sourcegraph/infrastructure/commit/1208f60dabe419a316761c2b968d7629b6e97221
- e2e tests pass
- unit tests pass
=> Remove quantized Starcoder support

client/web-sveltekit/src/routes/search/+page.ts
This just updates a couple of constants to match the react webapp so the experience is more directly comparable. 
Closes #60732
N/A
=> Svelte: update search params

CHANGELOG.md
=> Add changelog entry for GitHub App auth fix

internal/rockskip/search.go
migrate from log15 to `sourcegraph/log`
CI
=> logging: migate rockskip search away from log15

internal/rockskip/BUILD.bazel
Fix main
CI and executed locally
=> ci: sg bazel configure

dev/managedservicesplatform/spec/environment.go, dev/managedservicesplatform/stacks/cloudrun/cloudrun.go
Fix up https://github.com/sourcegraph/sourcegraph/pull/61185
https://sourcegraph.slack.com/archives/C05GJPTSZCZ/p1710969384771769
https://github.com/sourcegraph/managed-services/pull/655 is deployed
=> msp: fix secret volume mounts

CHANGELOG.md
=> chore(changelog): update changelog to say 5.3.3

internal/updatecheck/handler.go
This pull request is part of the Sourcegraph 5.3.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/61302)
=> release: sourcegraph@5.3.3

dev/release/release-config.jsonc
=> release: close 5.3.3 patch

CHANGELOG.md
Forgot about that in https://github.com/sourcegraph/sourcegraph/pull/60953
- Trivial changelog change
=> Add Claude 3 changelog

cmd/msp-example/BUILD.bazel, cmd/telemetry-gateway/BUILD.bazel, dev/ci/msp_deploy.sh, dev/msp_delivery.bzl
Update `msp_delivery` bazel macro arguments to make it simpler to use
CI
=> msp_delivery: infer pipeline id from service_id and region

deps.bzl, go.mod, go.sum
https://github.com/sourcegraph/zoekt/compare/f2577c25dc61...931974dd953e
- https://github.com/sourcegraph/zoekt/commit/06de7adb72 shards: use selectRepoSet in List
- https://github.com/sourcegraph/zoekt/commit/931974dd95 shards: respect scheduler and use smarter synchronization for List
Test Plan: tested in zoekt repo and this CI
=> gomod: update zoekt for List performance improvements

cmd/cody-gateway/shared/config/BUILD.bazel, cmd/cody-gateway/shared/config/config.go, cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel, cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go, internal/completions/client/anthropic/anthropic.go, internal/completions/httpapi/BUILD.bazel, internal/completions/httpapi/chat.go, internal/conf/BUILD.bazel, internal/conf/computed.go
- Trivial change (just adding a model to the allowlist) CI will test
=> Add Sonnet for free users

cmd/msp-example/internal/example/example.go
Want to start poking at https://github.com/sourcegraph/managed-services/issues/660 - since you can't exec into a Cloud Run container, this might be an easy way to check what is reachable from the container without writing code and shipping it every time.
It requires the generated diagnostics secret so is not accessible to users.
```
curl -v -H 'Authorization: bearer sekret' 'localhost:9080/proxy?host=https://sourcegraph.com&path=__version'
```
=> msp-example: add proxy util for testing networking stuff

cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go, cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser_test.go
context: https://sourcegraph.slack.com/archives/C06R89KF3AB/p1711569914628259
We have noticed a huge uptick in Claude 3 usage which was tracked down to one abusing user. The user has the correct quota of 1 but has over 2k API keys. The current theory is that they are reusing API keys and abusing the 1 quota.
Root cause:
If the user uses a new access token to make a request to cody gateway and the actor is not saved in the cache against that new token, we would reset the usage. This allowed users to use Cody without limits by keep generating new tokens. 
The fix is to check the cache for actor against the user id while `fetchAndCache` and not reset the usage if actor is found in the cache aginst the user id. 
https://www.loom.com/share/724bb4383d864805a7b61a4ccb46303c
=> Fix INC 290

cmd/msp-example/internal/example/example.go
Similar to #61394 - cant exec into Cloud Run, so this is a jank way to allow for some testing. In particular I want to check Private Service Connect properties before deciding how we want to proceed here.
n/a
=> msp-example: add 'insecure' as option to proxy test endpoint

cmd/gitserver/internal/vcssyncer/perforce.go
Our git logic determines the last fetch date by looking at the mtime of the FETCH_HEAD or HEAD file. Since for perforce we don't have a FETCH_HEAD, and HEAD is not touched because we don't do an actual git fetch, just run p4-fusion, this is not actually set correctly.
Thus, the search will show a red icon saying this repo is _severely_ out of date, incorrectly.
This fixes the issue by adjusting the mtime of HEAD after a successful p4-fusion fetch.
Replicated the setup locally and verified that after this change the repo is now correctly showing as fresh.
=> gitserver: Mark perforce repos correctly as recently fetched

cmd/telemetry-gateway/BUILD.bazel
Investigating some potential weird behaviour with @akalia25 
n/a
=> telemetry-gateway: pause MSP rollouts

client/web/BUILD.bazel, client/web/src/cody/management/CodyManagementPage.tsx, client/web/src/cody/onboarding/CodyOnboarding.tsx, client/web/src/cody/onboarding/instructions/CodyFeatures.tsx, client/web/src/cody/onboarding/instructions/JetBrains.tsx, client/web/src/cody/onboarding/instructions/NeoVim.tsx, client/web/src/cody/onboarding/instructions/VsCode.tsx, client/web/src/util/constants.ts
- Fixes https://github.com/sourcegraph/cody/issues/2361
Added the three new event types and triggering them when needed.
Caveats/questions:
- Wasn't sure what to use for the exact name of the editors, I used "JetBrains", "VS Code", and "NeoVim".
- About the naming for the newer telemetryRecorder thing, I just came up with the feature names (e.g. `cody.onboarding.openMarketplace` and the metadata format, not sure if that's needed/right)
Ran the site locally and checked if each of the events get triggered.
I couldn't actually find a way to trigger the "Cody Features" view 🤔 but the logging is there the same way as for the setup instructions page, so it should work the same way.
=> PLG: Add missing events

doc/cloud/index.md
we don't do monthly upgrade but "regular"
n/a
=> docs: update cloud upgrade cadence

client/web/src/cody/onboarding/instructions/JetBrains.tsx, client/web/src/cody/onboarding/instructions/NeoVim.tsx, client/web/src/cody/onboarding/instructions/VsCode.tsx
Updated names as a follow-up to https://github.com/sourcegraph/sourcegraph/pull/61467/, based on @bobheadxi's feedback [here](https://github.com/sourcegraph/sourcegraph/pull/61467/files#r1544075021).
No testing needed here, the PR review is enough.
=> PLG: Fix event feature names

dev/build-tracker/config/config.go
:sadge: 
to be tested again in CloudRun testing environment
=> build-tracker: fix BUILDTRACKER_DEBUG_PASSWORD env var key

dev/build-tracker/BUILD.bazel
My merge commented this which it should not have
CI
=> build-tracker: uncomment that which was commented

cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
This PR changes our WIP Embeddings model name to the actual model we plan to use. 
This change is separated from Cody Gateway changes so it can be deployed to sourcegraph.com (which is deployed M-F, not ad-hoc) before we deploy Cody Gateway changes.
- not used for live traffic
=> Rename allowlisted PLG model

CHANGELOG.md
Changelog entry for https://github.com/sourcegraph/sourcegraph/pull/61431
no test plan
=> Add code insight alert fix to the 5.4 CHANGELOG.md

CHANGELOG.md
=> release: changelog update

CHANGELOG.md
=> changelog: add header for april patch release

CHANGELOG.md
Updated the change log for the Pkl highlighting update
- No testing needed for updating the changelog
=> Update changelog to add Pkl highlighting update

lib/managedservicesplatform/runtime/internal/opentelemetry/metrics.go
#61619 's metrics export instrumentation doesn't work - unlike the tracing side, we have to do this when we create each export mechanism, the point where we provide a reader to the meter provider setup doesn't seem to work. Only the OTEL exporter gives us an actual `metric.Exporter` implementation so we only instrument that - Prometheus is for local dev and Prometheus service provides useful diagnostics, so this is ok
```
OTEL_GCP_PROJECT_ID=msp-testbed-test-77589aae45d0 sg run msp-example 
```
=> msp/opentelemetry: fix metrics export instrumentation

internal/search/job/jobutil/job.go
We refactored this code as part of #59038, and moved this comment elsewhere,
but forgot to delete it here.
Comment-only change
=> Searcher: remove stray comment

internal/database/dbconn/dynamic_metadata.go
We have a suspicion that this might help fix query insights aggregations. If it doesn't, we can revert this PR safely.
All DB related tests are still passing.
=> database: Format metadata as multiline string

client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx, cmd/cody-gateway/shared/config/config.go, cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go, internal/completions/httpapi/chat.go, internal/conf/computed.go, internal/licensing/codygateway.go, internal/licensing/codygateway_test.go
Adds the new public gpt 4 turbo version strings and removes the now unused `openai/gpt-4-1106-preview` (this was only used by PLG and we've upgraded it a couple of weeks ago already).
```
curl 'https://sourcegraph.test:3443/.api/completions/stream' -i \
-X POST \
-H 'authorization: token TOKEN' \
--data-raw '{"messages":[{"speaker":"human","text":"What is your name?"}],"maxTokensToSample":30,"temperature":0,"stopSequences":[],"timeoutMs":5000,"stream":true,"model":"openai/gpt-4-turbo"}'
HTTP/2 200
access-control-allow-credentials: true
access-control-allow-origin:
alt-svc: h3=":3443"; ma=2592000
cache-control: no-cache
content-type: text/event-stream
date: Wed, 10 Apr 2024 11:44:08 GMT
server: Caddy
server: Caddy
set-cookie: sourcegraphDeviceId=568d4ff9-1507-49aa-909e-73961c4f59d3; …
```
=> Cody PLG: Add GPT 4 Turbo GA version identifiers

.buildkite/pipeline.backcompat.yml
Whille we investigate the error - we're making backcompat soft fail
CI
=> ci: temporary mitigation - make backcompat soft fail on exit code 1

dev/ci/internal/ci/config.go
=> IGNORE ME: debug screaming

dev/BUILD.bazel, dev/migrations.bzl, dev/sg/dependencies/BUILD.bazel, dev/sg/dependencies/helpers.go, dev/sg/dependencies/mac.go, dev/sg/internal/migration/squash.go, dev/sg/internal/run/helpers.go, dev/tool_deps.bzl, dev/tools/BUILD.bazel, shell.nix
Following on from https://github.com/sourcegraph/sourcegraph/pull/61658, here we complete the picture
CI doesn't complain about a diff
=> bazel: use pgutil binaries from GCS instead of from the host

client/web-sveltekit/src/lib/Avatar.stories.svelte, client/web-sveltekit/src/lib/Avatar.svelte
This adjusts the design parameters for the Avatar component when no avatarURL is available. 
[Figma](https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/Code-Search?type=design&node-id=326-3404&mode=design&t=AJLHXqlTLf95fMdd-0)
Dark
Light
Manual testing with stories on both light and dark mode.
=> Sveltekit: implement new avatar design

dev/ci/images/images.go, dev/ci/internal/ci/images_operations.go, dev/ci/push_all.sh
Reverts sourcegraph/sourcegraph#61789
we should be unblock now https://github.com/sourcegraph/infra-aspect-dev/pull/119
waiting for runner image deployment
CI
=> Revert "Revert "ci: publish release images to public artifact registry""

.github/workflows/sg-setup.yml, dev/sg/dependencies/mac.go
CI and tested commands manually
=> sg: brew link postgresql@12

dev/ci/push_all.sh
Fix for now that we're doing one row per registry
CI when on main, purely cosmetic
=> ci: fix push_all annotation

client/web-sveltekit/README.md
Updating the Readme based on some things I had to figure out.
Not applicable, because it's only changes to the readme
=> chore: update readme for svelte dev

dev/sg/dependencies/ubuntu.go
Followup from https://github.com/sourcegraph/sourcegraph/pull/61802
Tested in an ubuntu container
=> sg: install postgres 12 instead of 15 [ubuntu edition]

CHANGELOG.md
=> release: add headers for changelog entry for next patch release

CHANGELOG.md
=> release: move #61513 out of the 5.3.9104 release section

doc/dev/how-to/wolfi/add_update_images.md
Provide an example pull request that shows how to add a new base image
- Docs - read through
- CI
=> Add a worked example pull request to wolfi image docs

wolfi-packages/.yam.yaml, wolfi-packages/qdrant.yaml
A [Yam](https://github.com/chainguard-dev/yam) configuration file is required by `wolfictl`, so adding it is a dependency for running wolfictl in github actions (https://github.com/sourcegraph/sourcegraph/pull/61933).
This will only affect package configuration files in the wolfi-packages/ directory.
- CI
=> Add yam.yaml configuration file to wolfi-packages/

CHANGELOG.md
Add a changelog entry for #61984
N/A
=> Add changelog entry for #61984

CHANGELOG.md
=> release: 5.3.11625 changelog update

dev/sg/sg_teammate.go, dev/team/team.go
Some local state was staged but not commited
Local and CI
=> sg: teammate details - fix field ordering in sg teammate printing

release.yaml
Will test during patch release 5.3.12303 today.
=> release: plug release registry to release

CHANGELOG.md
=> release: 5.3.12303 changelog update

CHANGELOG.md
=> release: fix changelog header

.aspect/bazelrc/ci.sourcegraph.bazelrc, .aspect/workflows/config.yaml, .gitignore, dev/ci/internal/ci/images_operations.go
Needed for ci-obs metrics pipeline
See buildkite build for this PR
=> ci: emit Bazel BEP file 

release.yaml
=> release: fix yaml indentation

CHANGELOG.md
Add jsx fix to changelog
- check change log
=> Add JSX fix to changelog

client/web/src/repo/blob/codemirror/codeintel/hover.ts
Fixes https://github.com/sourcegraph/sourcegraph/issues/61942
There are currently two situations where the popover isn't properly closed:
1. The popover extends outside of the file view boundaries and the mouse leaves the file view via the popover.
2. The hovered symbol is at the edge of the file view and the mouse leaves the file view moving over the symbol.
The first case is annoying becaues the popover might cover important information and it's not possible to close the popover by moving outside of it.
The second case is annoying because it can cause the popover to appear when moving outside of the file view (towards the top or bottom), which is just surprising at the best case, but can hide important information in the worst case.
This affects both the React and SvelteKit versions. …
=> blob: Properly hide popovers when the mouse leaves the file area

cmd/symbols/shared/setup.go
We are getting "fatal error: concurrent map writes" in production when enabling rockskip at large customers. The root cause is the repoToSize map which is read for every search request (and written every "cache miss").
This was the easiest change to make. We should probably also be single flighting this request, but that can be changed at another time.
Additionally fixed another bug where in the cache miss case we would do `size :=` and therefore not update size from 0, which then does a sqliteSearch. This means on the very first request to a rockskip repo we would always do sqliteSearch which is also a waste of resources.
Test Plan: Stefan manually testing :)
=> symbols: use concurrency safe map for repoToSize in rockskip

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/Picker.svelte
Fixes https://github.com/sourcegraph/sourcegraph/issues/57704
- Check that rev picker has a proper zero loading, error, and no data states layout
=> Fix zero, error, loading states for rev picker UI

CHANGELOG.md
=> Code insights: add changelog entry for drilldown change

internal/search/codycontext/job.go
In #62162, we pushed some Cody context logic down into the 'search job'. The
tests I added assume that the results are returned in a consistent order. This
is nice behavior and makes testing and debugging easier.
I mistakenly thought that `pool.NewWithResults` would return results in the
behavior goroutines were originally submitted. Oops! Now we use two separate
wait groups and ensure we return results in a consistent order.
Test are currently flaking ([example](https://buildkite.com/sourcegraph/sourcegraph/builds/270930#018f1761-0549-4b0d-91af-bc91242506a5)), this PR fixes them.
=> Context: always return code results first

wolfi-images/cloud-mi2-base/BUILD.bazel
We no longer publish this image either, and it's used by the cloud team for several of their containers.
- CI
=> Publish a cloud-mi2 base image for use in the cloud repo

dev/sg/internal/release/config.go, dev/sg/internal/release/release.go, release.yaml
Closes #62144
Manual testing. Will cut an internal release also.
=> release: allow creation of development releases

dev/managedservicesplatform/spec/spec.go
=> msp/spec: exclude populated README from YAML

cmd/frontend/internal/auth/openidconnect/session.go, cmd/telemetry-gateway/service/config.go, cmd/telemetry-gateway/service/service.go, deps.bzl, go.mod, go.sum
Sister PR of https://github.com/sourcegraph/sourcegraph-accounts-sdk-go/pull/16
CI
=> chore: update SAMS SDK

dev/sg/internal/backport/BUILD.bazel, dev/sg/internal/backport/backport.go, dev/sg/internal/execute/BUILD.bazel, dev/sg/internal/execute/exec.go, dev/sg/internal/release/BUILD.bazel, dev/sg/internal/release/cut.go, dev/sg/internal/release/release.go, dev/sg/internal/repo/git_repo.go
This command will be used for cutting a branch. 
```sg release cut -v <release_version>```
This will create a new branch and push it, it'll also create the relevant backport label for the release.
=> release: sg release cut

client/web/src/org/OrgsArea.tsx, client/web/src/org/area/OrgArea.tsx, client/web/src/org/area/OrgInvitationPageLegacy.tsx, client/web/src/org/backend.ts, client/web/src/org/invitations/OrgInvitationPage.tsx, client/web/src/org/new/NewOrganizationPage.tsx, client/web/src/org/settings/DeleteOrg.tsx, client/web/src/org/settings/DeleteOrgModal.tsx, client/web/src/org/settings/members/InviteForm.tsx, client/web/src/org/settings/members/OrgSettingsMembersPage.tsx, client/web/src/org/settings/profile/OrgSettingsProfilePage.tsx
=> v2t: Add v2t to src/org

client/web/src/cody/management/CodyManagementPage.tsx
addressing review comment: https://github.com/sourcegraph/sourcegraph/pull/62039#discussion_r1576520858
manually tested
=> Add comment regarding switch account screen

deps.bzl, dev/managedservicesplatform/stacks/cloudrun/internal/builder/service/service.go, go.mod, go.sum
Upgrades the google & google_beta terraform providers to 5.26.0
https://github.com/sourcegraph/managed-services-platform-cdktf/pull/7
tested locally
=> sg/msp: upgrade google/google_beta to v5.26.0

client/web-sveltekit/src/lib/Hotkey.test.ts, client/web-sveltekit/src/lib/Hotkey.ts
=> chore: add tests

release.yaml
Resolves [Michael's request](https://sourcegraph.slack.com/archives/C05DWT4ANHH/p1714420855027439)
Assumed valid since copy pasted
=> Misc: Add #team-cloud-ops slack webhook to release.yaml

client/web/src/cody/management/CodyManagementPage.tsx, client/web/src/cody/switch-account/CodySwitchAccountPage.tsx
Small suggested change by @unknwon that slipped through in #62039. Also an update the comment about the URL param now that support for it has been merged to Jetbrains too.
- CI
=> Update wording on account mismatch for Cody PLG Manage page

cmd/frontend/graphqlbackend/BUILD.bazel
Having the empty file doesn't add anything.
=> chore: Remove empty graphql file

internal/appliance/BUILD.bazel, internal/appliance/blobstore.go, internal/appliance/config/config.go, internal/appliance/defaults.go, internal/appliance/reconcile.go, internal/appliance/spec.go, internal/appliance/symbols.go, internal/appliance/testdata/golden-fixtures/blobstore-default.yaml, internal/appliance/testdata/golden-fixtures/blobstore-subsequent-disable.yaml, internal/appliance/testdata/golden-fixtures/repo-updater-default.yaml, internal/appliance/testdata/golden-fixtures/repo-updater-with-no-resources.yaml, internal/appliance/testdata/golden-fixtures/repo-updater-with-pod-template-config.yaml, internal/appliance/testdata/golden-fixtures/repo-updater-with-resources.yaml, internal/appliance/testdata/golden-fixtures/repo-updater-with-sa-annotations.yaml, internal/appliance/testdata/golden-fixtures/symbols-default.yaml, internal/appliance/testdata/golden-fixtures/symbols-with-storage.yaml, internal/k8s/resource/service/service.go
This is a refactor: golden test fixtures have not changed (well, except config hashes, due to the changed structure of the defaults).
=> appliance: default config

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
PR #62187 introduced a regression that causes the code and blame views for Markdown files to not show.
This commit fixes this. I renamed the variables to be a bit more clear and removed the check for `showCodeView`. Instead this relies on the template handling all other cases (binary, formatted, etc) first. Showing the file contents is now basically the fallback mode.
Manual testing. Verified that hover cards show up.
=> svelte: Fix code/blame view for rich HTML files

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte, client/web-sveltekit/src/routes/svelte-overrides.scss
Fixes with shadows rendering on the file view (specifically on the file tree sidebar, the bottom panel and the file header).
=> Svelte: Fixes shadows on file view

client/web-sveltekit/src/lib/blame/BlameDecoration.svelte
| ------ | ------ |
| <img src="https://github.com/sourcegraph/sourcegraph/assets/18492575/93bc7580-f188-412e-892c-b3098c1d4bb5"> | <img alt="Screenshot 2024-05-02 at 15 03 34" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/87e068fa-10cc-4026-9c98-9bbac0cbd5bb"> |
- Manual testing (here is the localhost link from the screenshot - [link](http://localhost:5173/github.com/sourcegraph/sourcegraph@362cc80c4d004eedf37df341d7de743ea324c90d/-/blob/cmd/frontend/graphqlbackend/testing.go?L79-80&view=blame))
=> Svelte: Fix blame decoration line layout

client/web/src/auth/SignInPage.test.tsx
Multiple PRs were merged, and so this build will no longer pass.
Adds `requiredForAuthz` field to the auth provider.
Build passes again
=> Fix test for SignInPage

.github/ISSUE_TEMPLATE/feature_request.md
Alternative to https://github.com/sourcegraph/sourcegraph/pull/62192, based on [this feedback](https://sourcegraph.slack.com/archives/C0EPTDE9L/p1714158741117939?thread_ts=1714157803.660119&cid=C0EPTDE9L) which I strongly agree with. 
CI
=> chore(gh): FR template tells where to submit them

.buildkite/pipeline.backcompat.yml
This reverts commit 3e441fd647443efc7781a056dda5bca456a67952.
Backcompat issue is back
CI
=> Revert "ci: remove softfail backcompat mitigation (#62230)"

dev/sg/internal/run/sgconfig_command.go
Part of https://github.com/sourcegraph/devx-support/issues/922
_I think it might be failing here_ but can't reproduce locally - so I am just sprinkling some error descriptions
Ci and @fkling trying this out
=> sg: improve error message when watching files

internal/appliance/BUILD.bazel, internal/appliance/defaults.go, internal/appliance/gitserver.go, internal/appliance/gitserver_test.go, internal/appliance/golden_test.go, internal/appliance/reconcile.go, internal/appliance/spec.go, internal/appliance/testdata/golden-fixtures/gitserver-default.yaml, internal/appliance/testdata/golden-fixtures/gitserver-with-no-resources.yaml, internal/appliance/testdata/golden-fixtures/gitserver-with-resources.yaml, internal/appliance/testdata/golden-fixtures/gitserver-with-storage.yaml, internal/appliance/testdata/golden-fixtures/symbols-default.yaml, internal/appliance/testdata/golden-fixtures/symbols-with-storage.yaml, internal/appliance/testdata/sg/gitserver-default.yaml, internal/appliance/testdata/sg/gitserver-with-no-resources.yaml, internal/appliance/testdata/sg/gitserver-with-resources.yaml, internal/appliance/testdata/sg/gitserver-with-storage.yaml, internal/k8s/resource/container/container.go
Add GitServer service definition and golden tests to the appliance.
Golden files for testing.
=> appliance: gitserver service definition

internal/codeintel/codenav/commit_cache.go, internal/codeintel/codenav/service.go
Not 100% sure if this is perfectly behavior-preserving but fixes ENG-23752
Covered by existing tests?
=> chore: Remove duplicate code for upload filtering

dev/sg/msp/sg_msp.go
This makes integration easier in CI - see failure in https://github.com/sourcegraph/managed-services/actions/runs/8945233608/job/24573806590
n/a
=> msp: prefer env token before setting up GSM client

LICENSE.enterprise
As suggested by Legal
No code changes
=> Update Enterprise license copyright notice

README.md
As discussed with our legal counsel
No code changes
=> Add copyright to README

client/web-sveltekit/src/lib/repo/FileHeader.svelte
| Type | Before | After |
| ----- | ------- | ------ |
| Short path | <img width="712" alt="Screenshot 2024-05-06 at 20 41 48" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/05477217-81b1-4fc9-83c3-cc31f01f0af8"> | <img width="709" alt="Screenshot 2024-05-06 at 20 41 07" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/9fc9dc50-85a6-477e-8f53-bd1ad592a42c"> |
| Long file path | <img width="712" alt="Screenshot 2024-05-06 at 20 41 41" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/fcdd12c3-bc47-46a9-a7b4-96fe56855d3a"> | <img width="710" alt="Screenshot 2024-05-06 at 20 41 28" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/1e60ebc3-ed54-495e-90a1-92db5d8c9ade"> |
- Check breadcrumbs row with different file paths (short one …
=> Svelte: Fix breadcrumbs layout

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
Regression after https://github.com/sourcegraph/sourcegraph/pull/62478
In https://github.com/sourcegraph/sourcegraph/pull/62478 I changed id but forgot about CSS selectors, they are crucial due to panel layout rules there 
=> [Svelte]: Fix blob content panels css selectors

WORKSPACE, dev/schema_migrations.bzl, internal/database/migration/shared/data/cmd/generator/consts.go, internal/database/migration/shared/data/stitched-migration-graph.json
Port of https://github.com/sourcegraph/sourcegraph/pull/62490
* chore(bzl): allow to invalidate migrations repo rule
* chore(bzl): gen stitch graph for 5.4
CI + see original PR
=> chore(rel): bump minor for stitch graph + add support invalidating migrations repo rule

internal/codeintel/uploads/service.go
=> chore: Fix function name in comment

cmd/worker/internal/githubapps/job.go, doc/dev/background-information/insights/backend.md, internal/insights/background/background.go
Just a few typos.
Anything that could break should be covered by existing CI.
=> chore: fix typos

internal/codeintel/codenav/service.go
Confused as to why this was left as a TODO but whatever
=> chore: Inline method at single usage site

internal/codeintel/resolvers/root_resolver.go
These provide helpful type errors when making changes.
Covered by build
=> chore: Add missing interface assertion for codenav Resolver

release.yaml
Will test during release promotion
=> release: execute gh via bazel

internal/rockskip/server.go, internal/rockskip/server_test.go
Another tiny warm-up for Rockskip tests. This commit adds a test for getHops
and simplifies the method. 
Added new test
=> Rockskip: test getHops function

release.yaml
=> release: remove slack webhook requirement

dev/authtest/BUILD.bazel, dev/authtest/code_intel_test.go, internal/codeintel/uploads/transport/http/auth/middleware.go, internal/codeintel/uploads/transport/http/auth/middleware_test.go, internal/gqltestutil/client.go
Fixes GRAPH-570
Adds new tests and updates existing tests
=> chore: Refactor codeintel middleware code

cmd/searcher/internal/search/hybrid.go, cmd/symbols/internal/database/writer/writer.go, cmd/worker/internal/embeddings/repo/handler.go, internal/rockskip/index.go
I accidentally pushed my PR feedback commit to a different branch before merging https://github.com/sourcegraph/sourcegraph/pull/62548 🤦 This is just followup on a couple of pieces of feedback from that PR
N/A, no change in behavior, just style.
=> PR feedback followup

dev/managedservicesplatform/terraformcloud/terraformcloud.go
Not even being able to view MSP workspaces in the event of e.g. CI failures is quite annoying - this makes MSP workspaces visible to everyone. This is part of addressing feedback from Michael today about the number of Entitle requests required to get a MSP service set up
Also see CORE-37:
> We can probably save some time here off the bat by making MSP TFC workspaces at least viewable by anyone in Sourcegraph, so that you can copy-paste the error over to #discuss-core-services without the time wasted on getting an Entitle request.
Using https://github.com/sourcegraph/sourcegraph/pull/62565, I applied this change successfully to all MSP workspaces.
=> msp/terraformcloud: grant 'sso' team read access to MSP workspaces

dev/sg/msp/sg_msp.go
For ease of applying Terraform Cloud workspaces changes fleet-wide, e.g. #62559 
Using `-all` updates all workspaces:
```
sg msp tfc sync -all
```
=> sg msp tfc sync: support applying to all services

dev/managedservicesplatform/terraformcloud/terraformcloud.go, dev/sg/msp/sg_msp.go
When using https://github.com/sourcegraph/sourcegraph/pull/62565, we override test environments that are in CLI mode, which can cause infra to be rolled out by surprise via VCS mode on switch - this change adds an option to respect the existing run mode configuration via `-workspace-run-mode=ignore`.
Thread: https://sourcegraph.slack.com/archives/C06JENN2QBF/p1715256898022469?thread_ts=1715251558.736709&cid=C06JENN2QBF
```
sg msp tfc sync -all
👉 Syncing all environments for all services, including setting ALL workspaces to use run mode "vcs" (use '-workspace-run-mode=ignore' to respect the existing run mode) - are you sure? (y/N)  N
❌ aborting
Projects/sourcegraph/managed-services 1 » sg msp tfc sync -all -workspace-run-mode=ignore
👉 Syncing all environments for all services - are you …
```
=> msp/terraformcloud: add option to respect existing run mode

internal/gitserver/commands_test.go
This PR adds more tests for the gitserver client GetObject method.
New unit tests
=> gitserver: client: grpc: add tests for GetObject

.github/workflows/scip-go.yml
AFAIK we're no longer using it.
- N/A
=> Remove SCIP upload to dogfood host

client/web/src/external-account-modal/ExternalAccountsModal.tsx
Check for a user external account's client ID as well when matching it to an external auth provider.
Unit tests pass and manual local test
=> Check for ClientID when matching auth provider to user external account

dev/linearhooks/internal/service/service.go
=> dev/linearhooks: add /-/healthz endpoint

cmd/frontend/internal/httpapi/completions/handler.go, cmd/frontend/internal/httpapi/completions/handler_test.go
=> Cody Ignore: update version constraint mismatch error text

deps.bzl, go.mod, go.sum
https://github.com/sourcegraph/zoekt/compare/4e674a49795c...fe8f2a3d9cab
- https://github.com/sourcegraph/zoekt/commit/fe8f2a3d9c Avoid overlapping trigrams in distanceHitIterator
=> Bump zoekt for iterator optimization

dev/managedservicesplatform/internal/resource/deliverypipeline/deliverypipeline.go, dev/managedservicesplatform/stacks/cloudrun/cloudrun.go
PR feedback from: https://github.com/sourcegraph/sourcegraph/pull/62702
ci
=> sg/msp: clarify `repository` annotation meaning in delivery pipeline

WORKSPACE
=> chore(ci): rules_buf 1.31

CHANGELOG.md
Related PRs:
- #62573
- https://github.com/sourcegraph/sourcegraph/pull/62593
- https://github.com/sourcegraph/src-cli/pull/1079
n/a
=> docs: Add CHANGELOG entry for SRC_ACCESS_TOKEN

internal/src-cli/consts.go
Now that 5.4.0 has been released.
Following https://github.com/sourcegraph/src-cli/blob/main/DEVELOPMENT.md#releasing, then run a src-cli command after the release is done.
=> Bump minimum src-cli version required

cmd/frontend/internal/cody/subscription.go
There was a minor error in the the logic we use to disambiguate fetching the Cody Pro subscription for a Sourcegraph user with multiple SAMS identities.
The SSC backend assigns a Cody Pro subscription to a SAMS user account. However, a single Sourcegraph.com user account can have _multiple_ SAMS identities. This leads to problems...
So as a workaround until we can fix https://github.com/sourcegraph/sourcegraph/issues/60912 more generally (e.g. remove all instances where a dotcom user has multiple SAMS accounts), we have some logic to "pick the right Cody Pro subscription". (e.g. if a user has 2x canceled Cody Pro subscriptions, but one that is active. Select the active one.)
The problem we have in the code is that we should consider the subscription status of `trialing` as being one of …
=> Fix issue in SAMS account disambiguation

CHANGELOG.md
Just adds a couple of changelog entries for recently-merged features.
N/A
=> Chore: add changelog entries

internal/appliance/config/BUILD.bazel, internal/appliance/config/dev_mode.go, internal/appliance/config/dev_mode_test.go, internal/appliance/config/spec.go, internal/appliance/dev/integrationtest/BUILD.bazel, internal/appliance/dev/integrationtest/integration_test.go
Early work for https://linear.app/sourcegraph/issue/REL-23/developer-smoke-testing-setup-with-a-real-kubernetes. It doesn't finish the issue. I suspect the output of that issue will actually be to split more sub-issues for the TODOs in here.
This PR adds tests, although these are early WIP and are not run in CI yet. This is basically just adding a harness.
=> appliance: initial smoke testing harness

client/web/BUILD.bazel, client/web/src/cody/management/api/teamInvites.ts, client/web/src/cody/management/api/teamMembers.ts, client/web/src/cody/management/api/teamSubscriptions.ts, client/web/src/cody/management/api/types.ts
Adds the REST API types for the Team Invites and Team Members sections. This isn't used by anything yet, but will be part of updating the Mange `AuthenticatedCodyManageTeamPage` page to use the API client hook.
NOTE: I didn't add this in this PR because I'm trying to tease out my local branch into separate PRs. But here's the relevant update to the `Client` type, so that you can call the endpoints that read/write these data types.
```ts
...
export module Client {
// Invites
export function getTeamInvites(): Call<types.ListTeamInvitesResponse> {
return { method: 'GET', urlSuffix: '/team/current/invites' }
}
export function createTeamInvite(requestBody: types.CreateTeamInviteRequest): Call<types.TeamInvite> {
return { method: 'POST', urlSuffix: '/team/current/invites', requestBody }
}
// …
```
=> Add missing API types

CHANGELOG.md
=> Update changelog for 5.4.2198

CHANGELOG.md
Adds a changelog entry for the backported fix to batch changes scheduling in #62597 
N/A
=> Chore: add changelog entry for #62597

dev/gqltest/search_test.go, dev/gqltest/site_config_test.go
=> ci: fix test issues on main

cmd/gitserver/internal/server.go
Running RefHash on repos with a few hundred thousand refs (nixpkgs) can run into a deadline exeeded issue, so we add a separate timeout for the `postRepoFetchActions`.
Test plan:
The repo clones correctly after this change.
=> gitserver: Fix postrepoactions for repos with many refs

dev/sg/internal/cloud/common.go, dev/sg/internal/cloud/deploy_command.go, dev/sg/internal/cloud/instance.go, dev/sg/internal/cloud/lease_command.go, dev/sg/internal/cloud/list_versions_command.go, dev/sg/internal/cloud/printers.go, dev/sg/internal/cloud/upgrade_command.go
* check that the instance has `completed` status before trying to extend the lease or upgrading it
* fix output of list-versions to print to stdout and information messages to stderr so that the output can be piped into another tool
* update list output to show action url and expiry time instead of status since it is usually "unspecified" which is not informative
CI and local testing
=> sg: cloud ephemeral - various small fixes

CHANGELOG.md
https://linear.app/sourcegraph/issue/REL-68/update-changelog-website-when-all-changes-are-accounted-for
n/a
=> Update missing changelog element for 5.4.2198

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/RepositoryRevPicker.svelte, client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/RepositoryRevPickerItem.svelte
Fixes https://github.com/sourcegraph/sourcegraph/issues/62655
=> Svelte: add default badge to default branch

dev/ci/internal/ci/release_operations.go
Problem ⬇️ 
```
VERSION=v5.3.6666 BUILDKITE_COMMIT=3507614937a086847868d5e8128af7c965c50e50 RELEASE_INTERNAL=true sg ci preview -b main --format=yaml
If the current branch were to be pushed, the following pipeline would be run:
Parsed diff:                                                                                                                                                                                                
changed files: [dev/ci/internal/ci/release_operations.go]                                                                                                                                                   
diff changes: "Go" …
```
=> chore(rel): fix tests not waiting for push prod

dev/sg/internal/cloud/instance.go, dev/sg/internal/cloud/instance_test.go, dev/sg/internal/cloud/printers.go
The reason format changed in the latest release of the API. This updates  SG to handle the new format
CI + bazel test
=> sg: cloud use new status reason format

tools/release/config/calendar.jsonc
This PR updates the calendar config to match the [Notion handbook](https://www.notion.so/sourcegraph/Sourcegraph-releases-eee2a5384b0a4555adb51b439ddde35f?pvs=4) source of truth
No test plan necessary, config change
=> Update release calendar

doc/dev/how-to/add_support_for_a_language.md
Clarify standards for tests and queries in docs.
n/a
=> docs: Add tips for highlighter queries and test cases

internal/updatecheck/handler.go
quick fix latest version after release
- Bump latest version reported by dotcom
no test required
=> chore(release): quick fix latest version after release

cmd/frontend/internal/httpapi/completions/handler.go, internal/completions/client/azureopenai/openai.go, internal/completions/types/types.go, internal/conf/computed.go, internal/conf/conftypes/consts.go, schema/schema.go, schema/site.schema.json
[See what the field Does
](https://learn.microsoft.com/en-us/answers/questions/1607830/how-does-the-user-parameter-work-in-azure-openai-s)
Tested locally by setting up extra variable in siteadmin with azure config and it worked perfectly.
=>  Adding the User param to the site config so that it can be supported by Azure as an extra param

deps.bzl, go.mod, go.sum
https://github.com/sourcegraph/zoekt/compare/fe8f2a3d9cab...640102a4a30e
- https://github.com/sourcegraph/zoekt/commit/df7a7e7162 Simplify trigram selection in distanceHitIterator
- https://github.com/sourcegraph/zoekt/commit/640102a4a3 Increase filename boost
Covered by Zoekt and Sourcegraph CI
=> gomod: bump Zoekt for filename boost

.github/PULL_REQUEST_TEMPLATE.md
Fixes https://github.com/sourcegraph/devx-support/issues/990
- Test plan has been in place for a long time, so we can get rid of the detailed instructions.
Irrelevant, just a PR template update. CI.
=> chore(dev): shorten test plan in PR template

dev/sg/internal/release/cut.go
Previously, the version number had to be specified explicitly during the `sg release cut` command. Now we can optionally pass `--version=auto` to query release-registry for the next version. 
We need this in both places, since on main cut releases, this is the first step that happens, but during patch releases, the first step is `sg release create` which also has `--version=auto`.
- Add `--version=auto` to `sg release cut`
=> feat(sg): add version=auto for `sg release cut`

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
=> Svelte: remove go to repository root button

client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx, cmd/frontend/internal/httpapi/completions/chat.go
This change adds support for the Google Gemini 1.5 Flash and Pro models in the ModelBadges component and the isAllowedCustomChatModel function. This allows these models to be displayed and used in the Sourcegraph product subscriptions UI and chat functionality.
In your sg local instant, look for the gemini models in the license page.
Verify you are not seeing the following error when running the curl command listed in https://sourcegraph.slack.com/archives/C05AGQYD528/p1717105626504719?thread_ts=1717011825.198899&cid=C05AGQYD528: `{"error":"model \"google/gemini-1.5-flash-latest\" is not allowed, allowed: []"}`
=> Cody PLG: add support for Google Gemini models

.github/workflows/bazel-test-ownership-check.yml, dev/check-test-ownership.sh
This PR adds a non-blocking GHA check to report when a branch's Bazel test ownership drops below 70%. See example messaging below to see how it looks like: https://github.com/sourcegraph/sourcegraph/pull/62985#issuecomment-2139439084. The message will be updated if the threshold is reached/breached whenever the branch changes.
Extensive iteration in this PR, see below message https://github.com/sourcegraph/sourcegraph/pull/62985#issuecomment-2139439084
=> feat(ci): add GHA to report when Bazel test ownership drops below 70% threshold

.github/PULL_REQUEST_TEMPLATE.md
See: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/devx-service@main/-/blob/cmd/changelog/main.go?L30
N/A updating PR tempalte
=> chore(ci): fix PR template's changelog type list

cmd/enterprise-portal/BUILD.bazel
Enables MSP rollouts for enterprise portal.
n/a
=> chore/enterprise-portal: enable MSP rollouts

internal/updatecheck/handler.go
Bump version consts to latest post release
No test required
=> bug(release): update version strings in upgradeReadiness

lib/codeintel/precise/util.go
Just noticed some dead code.
Covered by existing tests?
=> chore: Remove unused codeintel utils code

internal/codeintel/codenav/service_new.go
This was previously added in https://github.com/sourcegraph/sourcegraph/pull/54628,
we need a somewhat different implementation for precise usages which handles
all of definitions/references etc.
Deleting dead code which has no tests
=> chore: Remove unused code for precise defs by symbol

wolfi-images/sourcegraph-dev.lock.json, wolfi-images/sourcegraph-dev.yaml, wolfi-images/sourcegraph-dev/BUILD.bazel
Publish the sourcegraph-dev image, which is identical to our sourcegraph base image but includes apk tools. This is not recommend for prod images, but it very useful for building internal tooling on top of, rather than publishing a separate image for every single tool.
- CI
=> Publish sourcegraph-dev image

cmd/worker/shared/BUILD.bazel, cmd/worker/shared/main.go
It looks like this job is running much more than expected. Fixes GRAPH-648.
Temporarily commenting out the job to fix this.
n/a
=> chore: Temporarily disable syntactic indexing worker job

internal/codeintel/codenav/service_new.go
For ease of understanding.
n/a
=> chore(codeintel): Document prepareCandidateUploads function

internal/appliance/config/defaults.go, internal/appliance/config/spec.go, internal/appliance/reconciler/BUILD.bazel, internal/appliance/reconciler/reconcile.go, internal/appliance/reconciler/testdata/golden-fixtures/worker/default.yaml, internal/appliance/reconciler/testdata/golden-fixtures/worker/with-blobstore-and-embeddings.yaml, internal/appliance/reconciler/testdata/golden-fixtures/worker/with-blobstore.yaml, internal/appliance/reconciler/testdata/golden-fixtures/worker/with-replicas.yaml, internal/appliance/reconciler/testdata/sg/worker/default.yaml, internal/appliance/reconciler/testdata/sg/worker/with-blobstore-and-embeddings.yaml, internal/appliance/reconciler/testdata/sg/worker/with-blobstore.yaml, internal/appliance/reconciler/testdata/sg/worker/with-replicas.yaml, internal/appliance/reconciler/worker.go, internal/appliance/reconciler/worker_test.go
Closes https://linear.app/sourcegraph/issue/REL-83/service-definition-worker
- Deploys the Worker service.
=> feat(appliance): deploy worker

pnpm-lock.yaml
Main is failing without this
CI
- Add missing telemetry package to pnpm lock file
=> chore(pnpm): add telemetry package

cmd/frontend/graphqlbackend/codeintel.codenav.graphql
Fixes https://linear.app/sourcegraph/issue/GRAPH-634/add-guidance-for-pagination-in-occurrences-api
n/a
=> schema: Document perf scaling for occurrences(...)

internal/appliance/config/BUILD.bazel, internal/appliance/config/defaults.go, internal/appliance/config/embed.go, internal/appliance/config/postgres/codeinsights.conf, internal/appliance/config/spec.go, internal/appliance/dev/compare-helm/compare-helm.go, internal/appliance/reconciler/BUILD.bazel, internal/appliance/reconciler/codeinsights.go, internal/appliance/reconciler/codeinsights_test.go, internal/appliance/reconciler/reconcile.go, internal/appliance/reconciler/testdata/golden-fixtures/codeinsights/default.yaml, internal/appliance/reconciler/testdata/sg/codeinsights/default.yaml
Closes https://linear.app/sourcegraph/issue/REL-3/service-definition-codeinsights
**Add optional diff extra args to compare-helm**
I wanted this to do `diff --side-by-side`, may as well commit it as a
feature.
**feat(appliance): deploy codeinsights-db**
---
Ready for review, but draft until base branch merged.
- Appliance can deploy codeinsights-db.
=> feat(appliance): deploy codeinsights-db

cmd/gitserver/internal/gitserverfs/fs.go
I thought it might be nice to save on a few IOPS from the Stat calls to check if a repo is cloned by caching it for a bit. But turns out that the mutex locking and unlocking is more expensive than the stat operation.
We can come back here later and see if we can optimize it, we never had this in the past so this will be no regression.
Some background on mutex performance: https://stackoverflow.com/questions/57562606/why-does-sync-mutex-largely-drop-performance-when-goroutine-contention-is-more-t
Closes SRC-322
Test plan:
Without the cache, the tests still pass.
=> gitserver(fs): Remove caching of cloned state

internal/repos/syncer.go, internal/repos/syncer_test.go
My local instance has few repos enough that this doesn't happen, but on larger instances this preloading fights with the new preloading.
They are both best effort, and are meant to achieve the same thing.
Thus, this one is not required anymore, and we can delete it, after we added another one in https://github.com/sourcegraph/sourcegraph/pull/62891.
Test plan:
Verified with sleeps and logs locally that repos are correctly upserted in the schedule now.
=> repoupdater(scheduler): Prevent race condition of schedule preloading

wolfi-images/batcheshelper.lock.json, wolfi-images/blobstore.lock.json, wolfi-images/bundled-executor.lock.json, wolfi-images/caddy.lock.json, wolfi-images/cadvisor.lock.json, wolfi-images/cloud-mi2.lock.json, wolfi-images/executor-kubernetes.lock.json, wolfi-images/executor.lock.json, wolfi-images/gitserver.lock.json, wolfi-images/grafana.lock.json, wolfi-images/jaeger-agent.lock.json, wolfi-images/jaeger-all-in-one.lock.json, wolfi-images/node-exporter.lock.json, wolfi-images/opentelemetry-collector.lock.json, wolfi-images/postgres-exporter.lock.json, wolfi-images/postgresql-12-codeinsights.lock.json, wolfi-images/postgresql-12.lock.json, wolfi-images/prometheus.lock.json, wolfi-images/redis-exporter.lock.json, wolfi-images/redis.lock.json, wolfi-images/repo-updater.lock.json, wolfi-images/search-indexer.lock.json, wolfi-images/searcher.lock.json, wolfi-images/server.lock.json, wolfi-images/sourcegraph-base.lock.json, wolfi-images/sourcegraph-dev.lock.json, wolfi-images/sourcegraph-template.lock.json, wolfi-images/symbols.lock.json, wolfi-images/syntax-highlighter.lock.json
This reverts commit 3fc155dc4ddae4af8ebaf0cb5e39b6fd5fb8e849.
- CI
=> Revert "security: Auto-update package lockfiles for Sourcegraph base images (#63067)"

cmd/frontend/internal/httpapi/completions/chat.go
Fix: Add missing `/` to provider name for google models in Cody Gateway allowlist.
I was getting the following error from Cody Gateway:
```
event: error
data: {"error":"Sourcegraph Cody Gateway: unexpected status code 400: {\"error\":\"model \\\"google/\\\" is not allowed, allowed: [google/gemini-1.5-pro-latest, google/gemini-1.5-flash-latest]\"}\n"}
```
Changes:
- prepend "google/" to the Google model names to match the expected format
The issue doesn't affect instances that set `google` as the `provider`, and their requests should work as expected.
This change only affect Cody Gateway users with the following setting:
```
"completions": {
"provider": "sourcegraph"
"chatModel": "google/gemini-1.5-pro-latest",
"fastChatModel": "google/gemini-1.5-flash-latest",
},
```
=> fix(gateway): update Google model names in allowed custom chat models

dev/ci/msp_deploy.sh
Add 'author' and 'commit_message' annotations on release
Part of CORE-163
CI
=> msp/deploy: add 'author' and 'commit_message' annotations

dev/managedservicesplatform/spec/environment.go, dev/managedservicesplatform/spec/service.go
Lessons learned from https://sourcegraph.slack.com/archives/C05E2LHPQLX/p1717703306405529
n/a
=> chore/msp: document gRPC notes in spec docstrings

dev/sg/sg_cody_gateway.go
Add some messaging around generating a token as well as when arguments are missing
Tested locally
=> sg: add some messaging around generating a token

cmd/frontend/internal/cli/sysreq.go
It looks like this is broken on main; got a CI error: https://buildkite.com/sourcegraph/sourcegraph/builds/277526
=> chore: Fix lint error (unparam)

release.yaml
n/a
- Remind releasers of tag pipeline as final step.
=> chore(release): remind releasers of tag pipeline

dev/sg/internal/cloud/delete_command.go, dev/sg/internal/cloud/deploy_command.go, dev/sg/internal/cloud/printers.go, dev/sg/internal/cloud/upgrade_command.go
- suggested commands didn't have the `ephemeral` subcommand
- update expiry time to show in duration till expiry
Tested locally + CI
- fix suggested cloud ephemeral commands
- show duration till expiry for cloud ephemeral
=> fix(sg): fix cloud eph suggested commands 

internal/codeintel/codenav/transport/graphql/BUILD.bazel, internal/codeintel/codenav/transport/graphql/root_resolver_usages.go, internal/codeintel/resolvers/codenav.go
Adds stubs that @varungandhi-src and I will be sharing as we work on the new Codegraph APIs
just stubs, no code to test
=> Adds stubs for usage connection resolver

internal/highlight/language_test.go
Adds test case to cover the content based behavior for the Hack language 
- Ensure unit test passes 
- Add test case for coverage hack lang detection
=> chore(search): Add test case covering hack lang detection behavior

cmd/cody-gateway/shared/config/config.go, cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go, cmd/frontend/internal/httpapi/completions/chat.go, internal/conf/computed.go
This change adds the stable versions of the Google Gemini 1.5 Flash, Gemini 1.5 Pro, and Gemini Pro models to the list of allowed models in the Cody Gateway configuration and API endpoints.
The changes are made in the following files:
- `cmd/cody-gateway/shared/config/config.go`
- `cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go`
- `cmd/frontend/internal/httpapi/completions/chat.go`
- `internal/conf/computed.go`
The new models are added to the allowed model lists and also set as the default chat, fast chat, and completion models when the configuration is not explicitly set.
This change ensures that users are defaulted to use the stable versions of the Google Gemini models with the latest versions are still being available for use in the Cody Gateway …
=> feat(cody-gateway): add Google Gemini stable models to allowed models

cmd/frontend/graphqlbackend/BUILD.bazel, cmd/frontend/graphqlbackend/person.go, cmd/frontend/graphqlbackend/person_test.go
Refer to https://github.com/sourcegraph/security-issues/issues/392#issuecomment-2158160741 for more information about this dotcom specific change.
CI tests
=> dotcom: fix issue with dotcom emails

internal/database/dbconn/open.go
Previously, you'd get an error during `Open` instead of during driver construction.
=> chore: Validate driver type immediately

WORKSPACE, doc/dev/background-information/bazel/containers.md, doc/dev/background-information/bazel/faq.md, doc/dev/background-information/sg/index.md, docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel, sg.config.yaml
Reverts sourcegraph/sourcegraph#63111
Issue with jobs only run on main
:wat:
=> Revert "refactor: upgrade to rules_oci 2.0"

cmd/frontend/graphqlbackend/person_test.go
I forgot to clean up the mocks after the test, this causes issues with other tests that use the same backend.
CI tests, ran tests locally no unexpected failures.
=> fix(tests): Clean up mocks after test

cmd/frontend/graphqlbackend/codeintel.codenav.graphql
Based on Slack discussion: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1718147284720739
n/a
=> chore(schema): Add implementation status for codeGraphData

CHANGELOG.md
n/a
- Advise contributors of new changelog process.
=> chore(changelog): advise contributors of new process

README.md
=> chore: remove broken link in README

lib/codeintel/languages/BUILD.bazel, lib/codeintel/languages/languages.go, lib/codeintel/languages/languages_test.go
Addresses questions in https://github.com/sourcegraph/sourcegraph/pull/63254
Added tests
=> chore: Add more tests for GetLanguages API

cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
Add a stable version of the Gemini 1.5 Flash model to the allowed list for Code Completion.
1. Start a local Cody Gateway instance
2. In your local sg instance set "google/gemini-1.5-flash" as your completionModel
3. curl to the completion endpoint to confirm you are getting a completion response instead of streaming response (starts with data:):
```
{"completion":"I am a large language model, trained by Google. \n\nHere's what that means:\n\n* **Large Language Model:** I'm","stopReason":"STOP"}%
```
=> Cody Gateway: add gemini model to code completion list

cmd/cody-gateway/internal/httpapi/completions/google.go
- Fixes https://github.com/sourcegraph/sourcegraph/issues/63294
This PR turns off flagging for all Google models entirely.
Not tested yet.
=> fix(cody-gateway): Disable flagging Google requests

cmd/frontend/graphqlbackend/codeintel.codenav.graphql
Based on discussion here: https://github.com/sourcegraph/sourcegraph/pull/63217
n/a
=> chore: Add more docs for occurrences GraphQL API

cmd/frontend/graphqlbackend/codeintel.codenav.graphql, cmd/frontend/graphqlbackend/node.go, internal/codeintel/codenav/transport/graphql/BUILD.bazel, internal/codeintel/codenav/transport/graphql/root_resolver.go, internal/codeintel/resolvers/codenav.go, internal/codeintel/resolvers/root_resolver.go
Fixes https://linear.app/sourcegraph/issue/GRAPH-692/provide-id-field-on-codegraphdata
Here's a screenshot of it in action:
Manually tested against API console. Will follow-up with automated tests later.
=> feat: Add id for CodeGraphData

client/web/src/cody/invites/InviteUsers.tsx, client/web/src/cody/management/CodyManagementPage.tsx, client/web/src/cody/team/CodyManageTeamPage.tsx
Based on @taras-yemets's [feedback](https://github.com/sourcegraph/sourcegraph/pull/63375#discussion_r1647346730) on https://github.com/sourcegraph/sourcegraph/pull/63375
Just a refactor
=> Improve InviteUsers interface

cmd/cody-gateway-config/dotcom_models.go, cmd/cody-gateway/shared/config/config.go, cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go, cmd/frontend/internal/httpapi/completions/get_model.go, internal/completions/client/anthropic/anthropic.go, internal/conf/computed.go, internal/modelconfig/embedded/models.json
CONTEXT: https://sourcegraph.slack.com/archives/C05AGQYD528/p1718898110684289?thread_ts=1718896254.676939&cid=C05AGQYD528
CLOSE https://linear.app/sourcegraph/issue/CODY-2177
Adding new Claude 3.5 Sonnet (`claude-3.5-sonnet-20240620`) to the Cody Gateway allow list.
Model ID based on Anthropic Console:
Claude 3.5 Sonnet is Live on [s0.dev](http://s0.dev/) to confirm this is the correct model ID
Verify you can use the new model through Cody Gateway
feature(plg): new Claude 3.5 Sonnet model support for Cody Pro users
=> Cody Gateway: New Claude 3.5 Sonnet model

cmd/cody-gateway-config/dotcom_models.go, internal/completions/client/anthropic/anthropic.go, internal/modelconfig/embedded/models.json
Update Claude 3.5 model id to claude-3-5-sonnet-20240620
NA
=> fix(cody-gateway): model id for claude 3.5 sonnet

dev/sg/internal/release/BUILD.bazel, dev/sg/internal/release/list_release.go, internal/releaseregistry/BUILD.bazel, internal/releaseregistry/README.md, internal/releaseregistry/client.go
In preparation for reuse elsewhere.
I ran:
```
❯ go run ./dev/sg release list | head -n 5
Fetching versions from the release registry......
✅ Fetched 41 versions from release registry
ID  Product             Version     Created                SHA
52  docker              v5.4.5099   2024-06-05T21:23:18Z   3e196005b8afefb8e302c02b0bd1523768b7c111
51  deploy-sourcegraph  v5.4.5099   2024-06-05T21:15:02Z   47c861ac692583925b8154479cd39915f6ed7b26
50  helm                v5.4.5099   2024-06-05T21:13:30Z   8e8919bcc9334a6bfad316234c556f3c69d44407
49  k8s                 v5.4.5099   2024-06-05T21:08:46Z   8f3676865121c8d4ea2ffc5f6e356d1fb7393bcc
```
=> chore(sg): extract releaseregistry client package

cmd/frontend/internal/httpapi/completions/get_model.go
related: https://linear.app/sourcegraph/issue/CODY-2553/update-cody-free-tier-to-make-it-more-appealing
related: https://github.com/sourcegraph/cody/pull/4665
related: https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/18638
test manually
=> allow more models to be used in Cody Free

internal/collections/BUILD.bazel, internal/collections/ordered_set.go, internal/collections/ordered_set_test.go
Missing from stdlib and the orderedmap library we're using.
Added tests
=> chore: Add collection type - OrderedSet

.github/PULL_REQUEST_TEMPLATE.md
It takes up precious seconds of my time on this planet to delete all of the boilerplate text here.
n/a
=> shorter PR template

client/web/src/cody/chat/CodyChatPage.tsx
Added this during testing and forgot to remove it before merging.
n/a
=> oops, fix Cody Web enablement

client/web/src/enterprise/searchContexts/CreateSearchContextPage.tsx, client/web/src/enterprise/searchContexts/SearchContextsList.tsx
Visit search contexts page and ensure it renders as expected.
=> misc wording and UI tweaks to search contexts pages

client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.tsx
=> feat: remove experimental label from batches merge changesets action

client/web-sveltekit/BUILD.bazel, cmd/frontend/internal/auth/azureoauth/provider.go, cmd/frontend/internal/httpapi/completions/handler.go, deps.bzl, go.mod, go.sum, internal/completions/client/azureopenai/BUILD.bazel, internal/completions/client/azureopenai/openai.go, internal/completions/tokenusage/BUILD.bazel, internal/completions/tokenusage/tokenusage.go, internal/completions/tokenusage/tokenusage_test.go, internal/completions/types/types.go, internal/conf/computed.go, internal/conf/conftypes/consts.go, schema/schema.go, schema/site.schema.json
Description:
This PR introduces support for counting tokens within the Azure code and updating these counts in Redis. The token counting logic is embedded directly in the Azure code rather than using a standardized point for all token counting logic.
Reasoning:
•	Azure does not currently support obtaining token usage from their streaming endpoint, unlike OpenAI.
•	To enable immediate functionality, the token counting logic is placed within the Azure code itself.
•	The implementation supports GPT-4o.
Future Considerations:
•	When Azure eventually adds support for token usage from the streaming endpoint, we will migrate to using Azure’s built-in capabilities.
•	This will ensure full utilization of Azure OpenAI features as they achieve parity with OpenAI.
Changes:
•	Added token counting …
=> Add Support for Counting Tokens for Azure Code and Update in Redis

internal/appliance/reconciler/prometheus.go, internal/appliance/reconciler/testdata/golden-fixtures/prometheus/default.yaml, internal/appliance/reconciler/testdata/golden-fixtures/prometheus/privileged.yaml, internal/appliance/reconciler/testdata/golden-fixtures/prometheus/subsequent-disable.yaml, internal/appliance/reconciler/testdata/golden-fixtures/prometheus/with-existing-configmap.yaml
=> fix(appliance): fix typo in prometheus RBAC

client/web/src/cody/subscription/CodySubscriptionPage.tsx
Updating the Free tier limits. Context: https://linear.app/sourcegraph/issue/CODY-2553/update-cody-free-tier-to-make-it-more-appealing
manual review
=> Update free tier limits

client/web/src/namespaces/NamespaceArea.tsx, client/web/src/namespaces/index.ts, client/web/src/org/area/OrgArea.tsx, client/web/src/savedSearches/SavedSearchCreateForm.tsx, client/web/src/savedSearches/SavedSearchForm.story.tsx, client/web/src/savedSearches/SavedSearchForm.test.tsx, client/web/src/savedSearches/SavedSearchListPage.tsx, client/web/src/savedSearches/SavedSearchUpdateForm.tsx, client/web/src/user/area/UserArea.tsx
Also reduce dependency on the GraphQL result types.
CI
=> narrow NamespaceProps type

.aspect/workflows/config.yaml
Required change for new workflows
CI
=> update config for workflows 5.10

client/vscode/CHANGELOG.md, client/vscode/README.md
Update the README and CHANGELOG after recent changes.
Read the README and CHANGELOG
=> chore(search) VSCode Search extension: Update README and CHANGELOG

dev/linearhooks/BUILD.bazel
See https://github.com/sourcegraph/managed-services/pull/1686
n/a
=> chore/linearhooks: use MSP rollouts

dev/sg/internal/release/calendar.go, tools/release/config/calendar.jsonc
Updated events to match [Release Calendar](https://www.notion.so/sourcegraph/Sourcegraph-Releases-eee2a5384b0a4555adb51b439ddde35f?pvs=4) for September and August. Manually updated July events (and updated the `jsonc` file). 
Also removed branch cut events and associated automation, since we don't do that anymore. 
- chore(release): Update calendar events until September
- chore(release): Remove branch cut automation from `calendar.go`
=> Chore(release): Calendar Updates

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
=> fix(svelte): Remove rogue console.log statement

dev/sg/main.go
As I just reviewed a PR for `sg` about analytics, I've wasted 10m wondering why I wasn't seeing anything (thought I might be on the wrong branch, that type of things). Turned out, we obviously flip certain default value for flags (such as disabling analytics) when running a dev build. 
`sg` now prints out a warning at the beginning stating which of those are flipped out. 
CI + local run 
Warning sign is missing, but it's there, something wrong with my font.
=> chore(local): sg warns about opposite default value on dev builds

client/web-sveltekit/src/lib/repo/FileDiff.svelte
Small change to make browsing large diffs more ergonomic.
=> feat(svelte): Make diff headers on commit page sticky

client/web-sveltekit/src/lib/dom.ts
Previously, this only listened for resize events. However, shrink/grow might also be required if the contents of the element _change_. This adds a `MutationObserver` to `sizeToFit` to recalculate the sizing when the element (or its children) is mutated.
Fixes SRCH-679
https://share.cleanshot.com/Xdz6g16m
=> Svelte: add mutation observer to `sizeToFit`

.github/workflows/licenses-check.yml
Update the pinned SHA for `pnpm/action-setup`
License checker for this PR passing.
=> fix(actions): update pinned SHA for `pnpm/action-setup` action

internal/codeintel/codenav/service.go, internal/codeintel/codenav/transport/graphql/iface.go, internal/codeintel/codenav/transport/graphql/mocks_test.go, internal/codeintel/codenav/transport/graphql/root_resolver.go, internal/codeintel/core/BUILD.bazel, internal/codeintel/core/option.go, internal/codeintel/core/option_test.go
Adds an `Option[A any]` type for codeintel
Added Unit and PB tests
=> Adds Option for codeintel

client/web-sveltekit/src/lib/repo/OpenCodyAction.svelte
Fixes srch-686
Manual testing, trivial change.
=> fix(svelte): Use 'pointer' pointer for cody button

CHANGELOG.md
Closes SPLF-125
Test plan:
N/A
=> update changelog: Keyword search GA

client/web-sveltekit/package.json, client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte, pnpm-lock.yaml
Yet another PR to get cody web up-to-date in the new web app.
=> chore(svelte): Update to latest cody web version

cmd/symbols/shared/setup.go, internal/symbols/BUILD.bazel, internal/symbols/client.go
Was reading through the service, found these things and figured why not commit them.
Test plan:
CI.
=> symbols: Minor code cleanup

cmd/frontend/graphqlbackend/codeintel.codenav.graphql
Based on feedback from @camdencheek [in Slack](https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1719938010642799?thread_ts=1719915800.655399&cid=C05EA9KQUTA).
n/a
=> docs: Fix inaccuracies in RangeInput GraphQL docs

dev/sg/internal/cloud/deploy_command.go
Currently if a cloud ephemeral build is trigger it is triggered on the `main` sourcegraph pipeline. Once a build a triggered and a commit is subsequently pushed the previous build is cancelled - which means the Cloud Ephemeral build is cancelled leading to a failed deployment.
In this PR, we instead trigger a build on the Cloud Ephemeral pipeline. Which is the _exact_ pipeline as `sourcegraph` main but:
- sets the pipeline env to always have `CLOUD_EPHEMERAL=true`
- does not cancel previous builds
https://buildkite.com/sourcegraph/cloud-ephemeral/builds/1
* `sg cloud eph` will now trigger builds on the `cloud-ephemeral` pipeline
=> feat(sg/cloud): trigger build on cloud-ephemeral pipeline

CHANGELOG.md
Changelog update
N/A
* Batch Changes: GitHub apps can now be added as a credential for authentication and interacting with changesets. [#31533](https://github.com/sourcegraph/sourcegraph/issues/31533)
=> chore: add changelog entry for Batch Changes <> GitHub apps integration

cmd/frontend/graphqlbackend/access_tokens.go
Closes https://linear.app/sourcegraph/issue/SRC-463/error-handling-for-smtp-config-issues
Before, when someone created or deleted an access token, we'd block on sending the email before we'd return to the user. 
However, if an error occurred when sending an email - the error was only logged - **not** returned to the caller. 
This PR makes three changes:
1. We now sending the email in a background goroutine. This makes it so that the caller doesn't have to wait for the email to be sent before getting the access token back. This isn't a behavior change since we only logged any SMTP errors and **deliberatly avoided** forwarding that error to the caller. That behavior doesn't change here.
1. If an error occurs while sending the access token email, we now have a specialized log message …
=> feat/graphql/access_tokens: send access token creation/deletion emails in background and create special message for dial errors

WORKSPACE
Missing bit for the minor release version bump
CI
=> chore(release): bump stitch graph generation

client/web-sveltekit/src/lib/repo/FileDiffHunks.svelte
Fixes srch-717
This commit fixes the line numbers for unified diff views, which are used on the commit page and for inline diffs.
| ![2024-07-11_10-40](https://github.com/sourcegraph/sourcegraph/assets/179026/170ac815-d038-4239-80fe-7d35cecfa832) | ![2024-07-11_10-38](https://github.com/sourcegraph/sourcegraph/assets/179026/3606cb34-ad87-43bf-9664-414bf9250fa4) |
=> fix(svelte): Show correct line numbers in unified diff

client/web/src/cody/chat/new-chat/NewCodyChatPage.tsx, client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.tsx
Closes https://linear.app/sourcegraph/issue/CODY-2847/change-experimental-labels-to-beta
- Check that cody web page and cody web side panel have beta badges
=> Move Cody Web to beta

cmd/cody-gateway-config/dotcom_models.go, cmd/frontend/internal/httpapi/completions/get_model.go, cmd/frontend/internal/httpapi/completions/get_model_test.go, cmd/frontend/internal/modelconfig/BUILD.bazel, cmd/frontend/internal/modelconfig/builder.go, cmd/frontend/internal/modelconfig/builder_test.go, internal/completions/client/codygateway/codygateway.go, internal/conf/computed.go, internal/modelconfig/embedded/models.json
While testing the modelconfig system working end-to-end with the data coming from the site configuration, I ran into a handful of minor issues.
They are all kinda subtle so I'll just leave comments to explain the what and why.
Added new unit tests.
NA
=> Several fixes around merging modelconfig, and the current Cody Gateway data

dev/sg/cloudsqlproxy/cloudsqlproxy.go, dev/sg/msp/sg_msp.go
Ported from https://github.com/sourcegraph/controller/pull/1622 :) 
n/a
=> feat/sg/msp: helpful error on cloudsqlproxy port conflict

client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx
Fixes CODY-2661
Previously, only the JetBrains and Neovim Cody plugins had dedicated pages to authorize access token redirects to a localhost port. Other clients like the Cody CLI and Eclipse plugin reused the JetBrains page, which technically works but is problematic because the UI says the user is authorizing "JetBrains" when in reality they're authorizing other clients. This PR fixes the problem by adding dedicated pages for the Cody CLI, Eclipse plugin and Visual Studio extension.
Didn't test this locally because it takes me a long time to setup Docker access. The diff is small and should be low-risk to merge. I manually searched for 'JETBRAINS' in this directory and confirmed there are no remaining special cases for JetBrains.
=> Cody: add access token callback pages for CLI, Eclipse and VS

lib/telemetrygateway/v1/dial.go
Makes it a little easier to use
n/a
=> chore/lib/telemetrygateway: fixup Dial helper

dev/sg/enterprise/sg_enterprise.go
Testing for display-name setting which we recently added, and this is useful in the interim to set display names on the go for subscriptions EP already tracks.
note: I don't anticipate doing this for every field we make update-able, especially since the next step(s) will be updating the UI
```
sg enterprise subscription set-name es_4dae04ba-5f5b-431a-b90b-e8e3dd449181 "robert's test subscription"
```
=> feat/sg/enterprise: add 'sg enterprise set-name'

tools/release/promote_images.sh
Misc fixes to the `promote_images.sh` script that are known.  Notably, create the annotations directory if it doesn't exist
=> fix(release): misc fixes to private promote images script

package.json, pnpm-lock.yaml
=> upgrade vitest to latest

client/web-sveltekit/BUILD.bazel, client/web-sveltekit/playwright.config.ts, client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte, client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts, client/web/src/repo/blame/hooks.ts, client/web/src/repo/blame/shared.ts
Contributes to SRCH-738
Notably, this does not yet identify the root cause of SRCH-738, but it does identify and fix some confounding bugs. It's possible that these actually also _cause_ some of the issues in SRCH-738, but I wanted to at least push these to dotcom, where we can reproduce some of the weirdness. At the very least, it doesn't explain the auth errors being reported.
(cherry picked from commit d91fab39e287d57d00f35fb8952f5b7daabfa1d2)
CI
=> Backport: Blame: fix some issues with the stream (#63865)

internal/codeintel/codenav/service.go
A bunch of logic was constructing "visibleUpload" values but
it just needed to pass around CompletedUpload. Simplify that.
- Stacked on top of https://github.com/sourcegraph/sourcegraph/pull/63986
=> chore(codeintel): Simplify code using upload filtering

internal/codeintel/codenav/transport/graphql/root_resolver.go
Separating out the logic into a different function so it can be reused
later for precise usagesForSymbol.
- This PR is stacked on top of https://github.com/sourcegraph/sourcegraph/pull/63997
- Above PR is further stacked on top of https://github.com/sourcegraph/sourcegraph/pull/63986
n/a
=> chore(codeintel): Move RequestState construction to separate func

internal/appliance/reconciler/testdata/golden-fixtures/frontend/adopt-service.yaml
Semantic merge conflict in a test fixture, not caught by actual merge conflict though.
Tests all pass.
=> chore(appliance): fix a failing test

cmd/enterprise-portal/internal/subscriptionsservice/v1_test.go
As we start adding more stuff here, we need a bit more flexibility to add tests without it becoming overwhelming. The current copy-pasta is quite difficult to read, this standardizes the expected behaviour for the Update and List tests.
CI
=> chore/enterpriseportal: rewrite subscriptions API tests to be table-driven

client/web/src/enterprise/codeintel/configuration/hooks/queryPolicies.tsx, client/web/src/enterprise/codeintel/configuration/hooks/types.tsx, client/web/src/enterprise/codeintel/configuration/hooks/usePolicyConfigurationById.tsx, client/web/src/enterprise/codeintel/configuration/hooks/useSavePolicyConfiguration.tsx, client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPage.tsx, client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPolicyPage.tsx, client/web/src/enterprise/codeintel/configuration/shared.ts, cmd/frontend/graphqlbackend/codeintel.policies.graphql, internal/codeintel/policies/internal/store/configurations.go, internal/codeintel/policies/internal/store/configurations_test.go, internal/codeintel/policies/internal/store/repository_matches.go, internal/codeintel/policies/shared/types.go, internal/codeintel/policies/transport/graphql/configuration_policy_resolver.go, internal/codeintel/policies/transport/graphql/root_resolver_policy_mutations.go, internal/codeintel/policies/transport/graphql/root_resolver_policy_queries.go, internal/codeintel/resolvers/policies.go
Reverts sourcegraph/sourcegraph#63876 https://sourcegraph.slack.com/archives/CHXHX7XAS/p1721835847010889
CI
=> Revert "Syntactic indexing policy toggle: UI and supporting APIs"

dev/ci/internal/ci/images_operations.go, dev/ci/push_all.sh
Reverts sourcegraph/sourcegraph#64044
Dockerhub cant handle it and keeps ratelimiting us
CI
=> Revert "chore(bazel): rework push_all to improve concurrency by avoiding bazel server lock"

docker-images/appliance-frontend/BUILD.bazel, docker-images/appliance-frontend/image_test.yaml, docker-images/appliance-frontend/init.sh, docker-images/appliance-frontend/nginx.conf, internal/appliance/frontend/maintenance/BUILD.bazel, internal/appliance/frontend/maintenance/README.md, internal/appliance/frontend/maintenance/image_test.yaml, internal/appliance/frontend/maintenance/maintenance.conf.template, wolfi-images/appliance-frontend.lock.json, wolfi-images/appliance-frontend.yaml
Creates the Wolfi image for the Appliance Maintenance UI
```
bazel test \
//internal/appliance/frontend/maintenance:image_test \
//docker-images/appliance-frontend:image_test
```
=> Wolfi image for Sourcegraph Frontend

dev/ci/push_all.sh
=> fix(ci): reduce push_all concurrency due to ratelimits

dev/ci/push_all.sh
=> fix(ci): reduce push_all concurrency even further due to ratelimits

internal/gosyntect/gosyntect.go
This might help with debugging in the future.
N/A
=> observability: Adds useful data to traces from gosyntect.Highlight

dev/ci/internal/ci/images_operations.go, dev/ci/push_all.sh
So we can dig into why stuff is being built
CI
=> chore(ci): emit execlog for image push jobs

client/web-sveltekit/src/lib/repo/filePopover/FilePopover.svelte
=> Svelte: do not show path section if empty

dev/ci/internal/ci/images_operations.go
=> ci: automatic retry push images job at least 1

internal/database/sub_repo_perms_store.go
This takes less hoops to find what we support, and we don't extend this any time soon.
Test plan: CI passes.
=> subrepo: More explicitly define supported hosts

cmd/frontend/graphqlbackend/product_subscription_status.go, cmd/frontend/graphqlbackend/site.go, cmd/worker/internal/licensecheck/BUILD.bazel, cmd/worker/internal/licensecheck/check.go, cmd/worker/internal/licensecheck/check_test.go, cmd/worker/internal/licensecheck/job.go, cmd/worker/internal/licensecheck/usercount.go, internal/database/sub_repo_perms_store.go, internal/diskcache/cache.go, internal/licensing/BUILD.bazel, internal/licensing/user_count.go
This code was using a strange pattern that isn't actually observed or controlled by our worker mechanisms, so switching it to return proper goroutines.
Test plan: CI passes, would like a thorough review on the licensecheck code.
=> licensecheck: Make proper goroutine

cmd/frontend/graphqlbackend/git_commit_test.go
=> chore: Replace calls to deprecated ioutil.TempFile

internal/codeintel/codenav/transport/graphql/BUILD.bazel, internal/codeintel/codenav/transport/graphql/root_resolver_code_graph.go, internal/codeintel/codenav/transport/graphql/root_resolver_hover.go, internal/codeintel/codenav/transport/graphql/root_resolver_ranges.go, internal/codeintel/codenav/transport/graphql/root_resolver_stencil.go, internal/codeintel/codenav/transport/graphql/root_resolver_usages.go, internal/codeintel/codenav/transport/graphql/util_locations.go
Collecting some red-line brownie points
Existing tests continue to pass
=> chore(codeintel): replaces lsp.Range uses with scip.Range

dev/ci/internal/ci/images_operations.go, dev/ci/push_all.sh
For more insights into whats happening during those damn build commands
Also removes emitting to honeycomb, that was my experiment that has concluded.
CI
=> chore(bazel): emit json profile for image push jobs

cmd/customer-2315/BUILD.bazel, cmd/customer-2315/image_test.yaml, cmd/customer-2315/main.go, cmd/customer-4512/BUILD.bazel, cmd/customer-4512/image_test.yaml, cmd/customer-4512/main.go, internal/completions/client/azureopenai/openai.go
This is a backport PR to add changes from https://github.com/sourcegraph/sourcegraph/pull/64116 to v5.5.x to main to create a release of the frontend.
=> Backport 5ce2eea to 5.5.x

client/web/dev/esbuild/chunkCleaner.ts
This comment is no longer relevant
CI
=> chunk cleaner: remove comment

client/web-sveltekit/src/routes/+layout.svelte, client/web-sveltekit/src/routes/WelcomeOverlay.svelte, client/web-sveltekit/src/testing/integration.ts, client/web/src/sveltekit/SvelteKitNavItem.tsx
A few followups from #64163. Comments inline.
Manual local testing
=> Svelte: welcome banner followups

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts, schema/schema.go, schema/settings.schema.json
Just removes a redundant feature flag.
Fixes SRCH-644 
N/A
=> Chore: remove enablePreciseOccurrences feature flag

internal/codeintel/uploads/internal/store/uploads.go
Follow-up to https://github.com/sourcegraph/sourcegraph/pull/64210. It looks
like the visible uploads detection was copied in yet another place.
=> chore: De-duplicate CTE for visible uploads

client/web-sveltekit/src/lib/TabsHeader.svelte, client/web-sveltekit/src/lib/codenav/ExplorePanel.svelte, client/web-sveltekit/src/lib/navigation/FeedbackDialog.svelte, client/web-sveltekit/src/lib/repo/HistoryPanel.svelte, client/web-sveltekit/src/lib/repo/LastCommit.svelte, client/web-sveltekit/src/lib/repo/OpenCodyAction.svelte, client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.svelte, client/web-sveltekit/src/lib/repo/filePopover/FilePopover.svelte, client/web-sveltekit/src/lib/search/dynamicFilters/HelpFooter.svelte, client/web-sveltekit/src/lib/search/dynamicFilters/SectionItem.svelte, client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte, client/web-sveltekit/src/lib/search/input/SearchInput.svelte, client/web-sveltekit/src/lib/search/resultsIndicator/SuggestedAction.svelte, client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte, client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/DiffView.svelte, client/web-sveltekit/src/routes/svelte-overrides.scss
Resurrection of https://github.com/sourcegraph/sourcegraph/pull/64080 -- full details are there.
Manually tested locally.
=> Styling updates throughout

client/web-sveltekit/src/lib/codenav/ExplorePanel.svelte, client/web-sveltekit/src/lib/codenav/ExplorePanelFileUsages.svelte
Fixes SRCH-835 after https://github.com/sourcegraph/sourcegraph/pull/64236#issuecomment-2265515068
CI
=> Chore: remove non-null assertions

internal/codeintel/codenav/transport/graphql/root_resolver_code_graph.go, internal/codeintel/codenav/transport/graphql/root_resolver_test.go, internal/codeintel/resolvers/codenav.go
Reported in Slack: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1722847794289709
n/a
=> fix: Handle potential nil reference properly

internal/workerutil/dbworker/store/store.go
Under high contention, the updating of execution logs query:
```
UPDATE
lsif_indexes
SET
execution_logs = execution_logs || $1::json
WHERE
id = $2
AND worker_hostname = $3
AND state = $4 RETURNING ARRAY_LENGTH(execution_logs, $5)
```
Was taking multiple seconds due to lock contention on the lsif_indexes_state index.
Running `EXPLAIN ANALYZE` on Sourcegraph.com under lower contention uses
the primary key index on id, so we don't have an easy way to test the high contention
scenario. Try this alternate query form to see if that fixes the issue.
Existing tests continue to pass.
Slowly increase executor count back to 160 and see if lock contention comes up again.
=> fix: Try workaround for bad index choice when updating execution logs

client/web-sveltekit/package.json, client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte, client/web/src/cody/chat/new-chat/NewCodyChatPage.module.scss, client/web/src/cody/chat/new-chat/components/chat-ui/ChatUI.module.scss, client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.tsx, package.json, pnpm-lock.yaml
Incorporates https://github.com/sourcegraph/cody/pull/5129
Run in SvelteKit and non-SvelteKit. Ensure that the Cody standalone chat and Cody sidebar chats work.
=> upgrade Cody Web, always create a new chat

cmd/frontend/internal/app/ui/sveltekit/sveltekit.go
=> Svelte: enable toggle by default

WORKSPACE, internal/database/migration/shared/data/cmd/generator/consts.go, internal/database/migration/shared/data/stitched-migration-graph.json
The only manual action for bumping a minor but we'll get there :) 
CI
=> chore(rel): prepare stitch graph for 5.6 

deps.bzl, go.mod, go.sum
https://github.com/sourcegraph/zoekt/compare/acacc5eda188...20c496e3680f
- https://github.com/sourcegraph/zoekt/commit/b4193c29e7 Remove redundant phrase boost logic
- https://github.com/sourcegraph/zoekt/commit/801a704725 inline ctags alpine script
- https://github.com/sourcegraph/zoekt/commit/e77b32d6f1 docker: remove scip-ctags from Dockerfile
- https://github.com/sourcegraph/zoekt/commit/e372e97c88 Fix rare failures in ngram selection tests
- https://github.com/sourcegraph/zoekt/commit/20c496e368 Add metric for indexing delay
Covered by CI
=> Search: update Zoekt for telemetry improvement

internal/database/basestore/handle.go
Currently, this uses context.Background, because the initial context might've been canceled.
However, that causes us to lose any context involved here, so traces won't include this query and tenant information would be lost.
This uses the new-ish context.WithoutCancel to avoid this issue and stores the context used to create the transaction to close it later.
Test plan: Ran a local instance and didn't see errors, also integration and E2E tests pass.
=> db: Don't lose context when marking savepoints as done

cmd/worker/internal/authz/BUILD.bazel
Similar to https://github.com/sourcegraph/sourcegraph/pull/64412 
CI
=> chore(ci): shard authz test

cmd/frontend/graphqlbackend/external_account_data_resolver_test.go, cmd/frontend/internal/auth/azureoauth/middleware.go, cmd/frontend/internal/auth/bitbucketcloudoauth/middleware.go, cmd/frontend/internal/auth/bitbucketserveroauth/middleware.go, cmd/frontend/internal/auth/gerrit/config.go, cmd/frontend/internal/auth/githuboauth/middleware.go, cmd/frontend/internal/auth/gitlaboauth/middleware.go, cmd/frontend/internal/auth/httpheader/provider.go, cmd/frontend/internal/auth/oauth/middleware.go, cmd/frontend/internal/auth/oauth/provider.go, cmd/frontend/internal/auth/openidconnect/provider.go, cmd/frontend/internal/auth/providers/mock_auth_provider.go, cmd/frontend/internal/auth/providers/providers.go, cmd/frontend/internal/auth/saml/middleware.go, cmd/frontend/internal/auth/saml/provider.go, cmd/frontend/internal/auth/sourcegraphoperator/provider.go, cmd/frontend/internal/auth/userpasswd/provider.go
=> Refactor the weird isOAuth pattern

internal/database/connections/test/store.go
When we added a migration that actually relies on the promised property of migrations always running inside a transaction, we noticed that the memoryStore implementation we use in the dbtest package does not actually start a transaction. This implements transactions for the memorystore as well, to make it pass.
Test plan: Our migration now passes, and dbtest performance with and without this change is the same.
=> migrationtests: Actually run in a transaction when in test mode

client/web-sveltekit/src/routes/search/QueryExamples.svelte
=> fix(svelte): Show focus style when tabbing through search query examples

cmd/frontend/internal/httpapi/httpapi.go
=> dotcom: request write scopes for EP prod proxy

internal/database/connections/live/migration_test.go
This test ensures that newly added tables also have the tenant_id column. We will later extend this test to also check that RLS policies exist, once we created them.
Test plan: Test passes, when I modify the new migration that adds tenant_id everywhere to skip a table it fails with a nice error message.
=> tenant: Add test to verify that we don't regress on tables without tenant

internal/codeintel/autoindexing/internal/inference/libs/indexes.go, internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Gradle.yaml, internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Maven.yaml, internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_SBT.yaml, internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_lsif-java.json.yaml, internal/codeintel/autoindexing/internal/inference/testdata/Nested_JVM_project_WITHOUT_top-level_build_file.yaml, internal/codeintel/autoindexing/internal/inference/testdata/Nested_JVM_project_with_top-level_build_file.yaml, internal/codeintel/autoindexing/internal/inference/testdata/go_files_in_root.yaml, internal/codeintel/autoindexing/internal/inference/testdata/go_modules.yaml, internal/codeintel/autoindexing/internal/inference/testdata/scip-ruby.yaml
=> chore: Bump autoindexing image SHAs

client/web-sveltekit/README.md, dev/tool_deps.bzl
This PR updates the docs for when we want to upgrade playwright and its browsers.
No testing required, because it's just docs.
=> chore: improve docs for playwright upgrades

cmd/frontend/graphqlbackend/package_repo_filters.go, cmd/frontend/graphqlbackend/repository.go
Adds some additional site-admin checks. :lock: 
CI tests, local testing
=> sec: Add extra admin checks

cmd/worker/internal/codeintel/autoindexing_scheduler.go, internal/codeintel/autoindexing/init.go
Code continues to build & tests pass
=> chore: Remove unused parameter

client/web-sveltekit/src/routes/[...repo=reporev]/-/stats/contributors/+page.svelte
Replace 'commits' with 'changelists' on contributors page
Visual/Manual testing
=> [Sveltekit]: perforce - replace 'commits' with 'changelists' on contributors page

cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go, cmd/enterprise-portal/internal/database/subscriptions/subscriptions_test.go
At some point, I introduced a fast-path for subscription upsert where if no conditions are provided, we fail to check for constraint errors and wrap them with `ErrInvalidArgument`.
This change makes it so that we correctly check for constraint errors in both paths.
Fixes https://sourcegraph.sentry.io/issues/5717030715/?referrer=slack&alert_rule_id=15230143&alert_type=issue
DB tests
=> fix/enterpriseportal: fix invalid argument errors

cmd/frontend/internal/context/resolvers/context.go
This PR adds a seperate check how ChatIntent api should be enabled. For now the chatIntent api is enabled for all the enterprise instances.
ToDo:
1. Check if we should only enable the end point on `dotcom` and `S2` instance.
tested locally, need to add test cases here
=> enable chat intent on enterprise instances

internal/cmd/git-combine/README.md
=> chore(docs): update git-combine README

dev/ci/images/images.go
Relates to https://linear.app/sourcegraph/issue/REL-322/appliance-helm-chart-should-be-versioned but does not close it.
See test plan in https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/534
=> feat(sg): update appliance images

CHANGELOG.md, client/browser/CHANGELOG.md, client/jetbrains/CHANGELOG.md, client/vscode/CHANGELOG.md
Closes DINF-175
Update changelog files, with no broken links.
=> update changelog links

README.md
=> Add a visible notice in the README 
