cmd/worker/internal/repostatistics/resetter.go

Final test was successful: resetter ran on sourcegraph.com and took 1min.
Logging was also helpful.
So this is the production-ready version.
- N/A

statistics resetter: run on Sunday, between 2 and 2:30am

---

dev/oci_deps.bzl

This reverts commit af97dce23d5434dbdb412ea7cafcc1da2fe7db6c.
Broke images, somehow postgres got downgraded.
CI.

Revert "Bump wolfi images to make use of latest p4-fusion (#58752)"

---

.github/workflows/buildchecker-history.yml
.github/workflows/buildchecker.yml

buildchecker now requires Go 1.21 due to changes in a dependency, but this was never reflected in the Go version used by the workflow file, hence it has been failing for some time now
Tested using `act workflow_dispatch -W .github/workflows/buildchecker.yml`

bump go version in buildchecker

---

CHANGELOG.md
internal/database/external_services.go
internal/database/external_services_test.go

Closes #58772
Fixes an issue where the logic that determines whether or not a code host connection is unrestricted differs between the code host connection creation and update code.
Tests updated

[fix] Updating an code host config maintains the correct unrestricted state

---

dev/build-tracker/main.go
dev/build-tracker/main_test.go
dev/build-tracker/notify/slack.go

The build can be finished and have failing jobs but a late job can come in and make the build "not be finished", which is a problem since we don't get a notification for the late job finishing, which leads to the job perpetually being in in-progress.
We do not count in-progress jobs anymore because this can lead to invalid build states even though the build is finished
Added unit tests
Reproduce the problem
```
go test ./...
?       github.com/sourcegraph/sourcegraph/dev/build-tracker/config     [no test files]
?       github.com/sourcegraph/sourcegraph/dev/build-tracker/util       [no test files]
--- FAIL: TestToBuildNotification (0.00s)
--- FAIL: TestToBuildNotification/Finished_build,_with_2_failed_jobs_and_then_a_late_in_progress_job (0.00s)
main_test.go:156: got 2, wanted 3 for …
```

buildtracker: ignore inprogress jobs when determining final status

---

internal/database/gitserver_repos.go
internal/database/gitserver_repos_test.go

This syncer tries to sync repos that have an error, but it also tries to sync *blocked* repos which would always fail to sync. Unnecessary work.
- Unit tests
- Confirmation in production by looking at logs

errored repos syncer: do not try to sync blocked repos

---

cmd/frontend/auth/user.go
cmd/frontend/internal/auth/oauth/BUILD.bazel
cmd/frontend/internal/auth/oauth/session.go

We have a few test users whom we want to make Cody PLG users automatically. This PR does that.
Tested this:
- ✅ Created a new user through OpenID Connect. If the user was on `MinimumExternalAccountAgeExemptList` then they got `cody-pro` as a feature flag.
- ✅ Otherwise, they didn't get the feature flag.
- ✅ If the `MinimumExternalAccountAgeExemptList` config item doesn't exist, it still works

SSC: Hook up exempted users with cody-pro FF

---

wolfi-images/redis.yaml
wolfi-images/server.yaml

`redis-cli` package was missing from image
`sg wolfi image server` + ` docker run -it --entrypoint /bin/sh sourcegraph-wolfi/server-base:latest-amd64 redis-cli -h`

wolfi: add redis cli to server image

---

client/web/src/repo/RepoRevisionSidebarFileTree.module.scss
client/web/src/repo/constants.ts

This commit adds icons for `.toml`, and `.vue` file types. It also adds a less-dated icon for Java. 
Visual/manual testing in local environment

Code Navigation: change Java icon and add vue icon

---

internal/accesstoken/personal_access_token.go
internal/completions/httpapi/BUILD.bazel
internal/completions/httpapi/chat.go
internal/completions/httpapi/codecompletion.go
internal/completions/httpapi/handler.go
internal/database/access_tokens.go
internal/database/access_tokens_test.go
internal/database/dbmocks/mocks_temp.go

- Closes https://github.com/sourcegraph/sourcegraph/issues/58572
Our plan to use internal access tokens worked!
I found no way to get the SHA256-hashed token value from the DB, so I created a new function to get it.
I tested the new function to make sure it works. 
Tested it in two ways:
1. With Cody Web locally: I could repro the problem before this change, and not after. 🎉 
2. In the API console with the query
```
query CodyGatewayAccess {
completions(input: {messages: [{speaker:HUMAN, text:"hi\n\nAssistant:"}], temperature:1,maxTokensToSample: 2, topK: 1, topP: 1}) {}
}
```
Btw, it's an additional win that the API console works again!

SSC: Fix Cody Web

---

cmd/frontend/internal/app/resolvers/app.go
cmd/frontend/internal/embeddings/resolvers/resolvers.go
cmd/worker/internal/embeddings/repo/scheduler.go
internal/embeddings/background/repo/types.go
internal/embeddings/schedule.go
internal/embeddings/schedule_test.go

Refactors the repository scheduling logic into two separate methods, one used
by the GraphQL API, and the other by the policy framework. This makes the code
easier to read and lets us make some improvements:
* For policy scheduling, stop translating back-and-forth between repo IDs and
names
* Make sure to fail entire GraphQL request if there is an error fetching repos,
instead of silently ignoring it
Added new unit test

Embeddings: refactor job scheduling code

---

doc/cloud/index.md

you can't have CAA on `src.acme.com`, cuz it already has a CNAME to cloud-managed domain `acme.sourcegraphcloud.com`. It has to be on the apex domain
docs only

docs: fix up caa records requirement

---

cmd/frontend/internal/auth/openidconnect/BUILD.bazel
cmd/frontend/internal/auth/openidconnect/middleware.go
cmd/frontend/internal/auth/openidconnect/user.go
cmd/frontend/internal/auth/openidconnect/user_test.go

We haven't been storing token info into the `user_external_accounts.auth_data` column, which might be an oversight. We need to store the token info for SAMS (and Cody Gateway later on), so need to fix it now.
CI and tested e2e (local credentials):

oidc: store access token into auth_data

---

client/web/BUILD.bazel
client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
client/web/src/cody/components/GettingStarted.tsx
client/web/src/cody/management/CodyManagementPage.tsx
client/web/src/cody/onboarding/CodyOnboarding.module.scss
client/web/src/cody/onboarding/CodyOnboarding.tsx
client/web/src/cody/onboarding/instructions/JetBrains.tsx
client/web/src/cody/onboarding/instructions/VsCode.tsx
client/web/src/enterprise/cody/configuration/pages/CodyConfigurationPage.tsx
client/web/src/get-cody/GetCodyPage.tsx
docsite_run.sh

1. Adds Video to first step
2. Adds fade-in animation to first step
3. Adds coloured stroke to the modal
4. Makes the overaly bg more opaque
5. Converts all IDE icons to SVGs of the same size
6. Include Release Label on IDE list
7. Adds illustrations to VSCode step
8. Adds illustrations to feature step
9. Adds vertical support for modals with long content
This loom goes over all the changes
https://www.loom.com/share/f81613aecf874d0a9faca779f7d77cc0?sid=ff13e5e0-5aec-4b85-ab72-92e3f4979bdf
Previewed all locally
Mostly CSS and HTML changes

Onboarding UI Fixes

---

cmd/cody-gateway/internal/httpapi/completions/fireworks.go
cmd/cody-gateway/internal/httpapi/handler.go
cmd/cody-gateway/shared/config.go
cmd/cody-gateway/shared/main.go

Some [traffic is still hitting](https://redash.sgdev.org/queries/226/source#445) the ST environment, despite the relevant [feature flag](https://sourcegraph.com/site-admin/feature-flags/configuration/cody-autocomplete-default-starcoder-hybrid-sourcegraph) being ramped down to 0 (likely due to a delay in feature flag propagation on the client side) - this PR adds a mechanism that forwards requests sent to ST models to hit the MT ones. 
Off by default, so should be safe to roll out.

Rewrite ST models to MT equivalents

---

dev/nix/shell-hook.sh

Currently on non-nixos hosts we will append to .bazelrc-nix everytime the shell hook runs. This leads to the file growing quite large, I am unsure on the impact on bazel. This was an accidental regression when we removed bazel from the nix darwin environment.
Test Plan: ran nix develop and I didn't have duplicated lines.

nix: empty out before writing to it .bazelrc-nix

---

client/browser/src/shared/code-hosts/shared/codeHost.tsx

Fixes https://github.com/sourcegraph/sourcegraph/issues/23251
I think this problem has been with us since the very beginning of native code integration and browser extension development. This may became even worse since we switched from Webpack to esbuild where we include all possible code host styles in one bundle (meaning that we still load GitHub-related styles even if we're in GitLab integration). 
Overall, the current state is 
- In this PR we use just a hot fix way and use the most top level HTML element to assign css tokens and colors (this gives us ability to not native styles and keep cascade specificity lower than native styles)
- Possible we could use here `@layer` cascade at-rule, but at the moment our CSS token system structure just ins't ready for this change and this could …

Use document element for class theme in code hosts integrations

---

client/web/src/repo/settings/RepoSettingsIndexPage.tsx

Previously, when an index is not up-to-date, we'd always claim that we're
actively indexing the repo. This is misleading, because indexing indexing could
be stuck or failing.
Now, we remove the loading spinner and just say the repo is "queued for
indexing". If the index is out-of-date and it's been more than 8 hours since
the last successful job, then we also show a warning tooltip.
Addresses #57337
Lots of manual testing.

Admin: avoid false impression that Zoekt is indexing

---

cmd/telemetry-gateway/internal/events/BUILD.bazel
cmd/telemetry-gateway/internal/events/events.go
cmd/telemetry-gateway/internal/events/events_test.go
internal/pubsub/pubsubtest/pubsubtest.go
internal/pubsub/topic.go

This might make it easier to the team to work with the incoming data, and could be useful for some degree of tagging.
Unit tests

telemetry-gateway: add attributes to pubsub events

---

dev/ci/internal/ci/operations.go

Revert "Revert - disable chromatic (#58841)"
This reverts commit 53bcd31b1ffea2b4ca9b2c04424b5dc486877052.
None - Disabling a step

Disable chromatic again

---

internal/database/gitserver_repos.go
internal/database/gitserver_repos_test.go
internal/database/repos_test.go

So previously this would log corruption errors even if the repo was on a different shard than the one this method is called on.
This change makes it only log if the repo is on the local shard.
- NA

gitserver repos: do not log corruption from wrong shard

---

internal/database/gitserver_repos_test.go
internal/database/zoekt_repos_test.go

We bumped into this earlier. Turns out this helper was a "would be nice" approach that didn't pan out. Instead of changing all of the tests to follow this approach, I decided to simplify and reduce the things that aren't needed because it makes maintenance easier.
NA

database: simplify test helper

---

sg.config.yaml
testing/tools/integration_runner.sh

Additionally, when generating unique ids in integration tests fallback to hexdump if openssl is not available
Tested locally
```
<snip>
if [[ $(uname) == "Darwin" ]]; then
BAZEL_FLAGS=("--config darwin-docker")
else
BAZEL_FLAGS=()
fi
bazel test //testing:backend_integration_test ${BAZEL_FLAGS[*]} --verbose_failures --sandbox_debug  in "/Users/william/code/sourcegraph"...
INFO: Analyzed target //testing:backend_integration_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
[1 / 2] Testing //testing:backend_integration_test; 662s darwin-sandbox

sg: add config to run backend-integration tests locally

---

client/web/src/cody/onboarding/CodyOnboarding.tsx

- Closes https://github.com/sourcegraph/cody/issues/2054
It was a small change, after all.
Watch me test it in this [3-min Loom](https://www.loom.com/share/66611ce7d82043669ef06d597876784f?sid=6be701b9-23ac-4a6e-b20d-e5d47255aeda)
I tested:
- If `/cody/manage` gets a `returnTo` parameter, it correctly goes through the onboarding process, then redirects to the desired page
- If it doesn't get the new param, it won't do a redirect

SSC: Handle returnTo params on /cody/manage

---

client/web/src/repo/blob/codemirror/codeintel/api.ts
client/web/src/repo/blob/codemirror/codeintel/extension.ts

While I was reading the code, this was a little bit confusing,
as `CodeIntelAPIAdapter` contains a `CodeIntelAPIConfig`,
which contains an `api` field of type `CodeIntelAPI`.
So I've renamed the local variables and functions to line
up with the type name.
n/a

client: Rename api -> apiAdapter for clarity

---

client/web/src/repo/settings/RepoSettingsIndexPage.tsx
client/web/src/site-admin/RepositoryNode.tsx

This PR backports these changes related to the search indexing admin experience:
* https://github.com/sourcegraph/sourcegraph/pull/58061
* https://github.com/sourcegraph/sourcegraph/pull/58415
* https://github.com/sourcegraph/sourcegraph/pull/57903
* https://github.com/sourcegraph/sourcegraph/pull/58793
CI and manual testing

[Backport 5.2] Admin: improve search indexing page

---

internal/codeintel/autoindexing/transport/graphql/BUILD.bazel
internal/codeintel/autoindexing/transport/graphql/root_resolver_configuration_repository.go

Fixes #58453
Add the `vitejs/vite` repo to your local sg instance, and view the autoindex configuration page.
After this PR you should see the real error: 
`Error fetching index configuration: Inference limit: requested content for more than 100 (100) files`
instead of a nil pointer exception.
I added two commits, but the first is completely overridden by the second. In 67ed1c33e3c589b0a067a5f08be05116eb98a180 I tried to 'interpret' what the code was trying to do in the first place, and return a 'succesful' result even if the evaluation ran into a limit error. That produces very confusing UX though, because now it looks like everything is fine on the configuration page, but there are no build jobs. I think it's better to surface the error in the UI here.
This change leaves things in a bit …

Surfaces errors in autoindex configuration

---

cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
cmd/cody-gateway/internal/httpapi/completions/anthropic.go
cmd/cody-gateway/internal/httpapi/completions/fireworks.go
cmd/cody-gateway/internal/httpapi/completions/openai.go
cmd/cody-gateway/internal/httpapi/completions/upstream.go
cmd/cody-gateway/internal/httpapi/handler.go
cmd/cody-gateway/internal/response/BUILD.bazel
cmd/cody-gateway/internal/response/response.go
cmd/cody-gateway/internal/response/response_test.go
cmd/cody-gateway/shared/config.go
cmd/cody-gateway/shared/main.go
internal/completions/client/fireworks/fireworks.go

For streaming requests, we don't want to buffer responses, but instead send the data to the client as soon as possible - see [Slack](https://sourcegraph.slack.com/archives/C05AGQYD528/p1701791953787829) and this issue https://github.com/sourcegraph/cody/issues/2180. This PR detects streaming requests (from all providers) and automatically flushes the response after every write.
Improvement can be observed using this https://sourcegraph.slack.com/archives/C05AGQYD528/p1702287275092429?thread_ts=1701791953.787829&cid=C05AGQYD528.
From local tests, this cuts time-to-first-event from ~1s to ~300ms (Fireworks Starcoder, measured client side). 
- unit tests

cody-gateway: For streaming requests, flush response after every write

---

doc/cody/core-concepts/embeddings/index.md
doc/cody/overview/enable-cody-enterprise.md
internal/completions/client/azureopenai/openai.go
internal/embeddings/embed/client/azureopenai/BUILD.bazel
internal/embeddings/embed/client/azureopenai/client.go

Because Azure get token requests are sent to `login.microsoftonline.com` sometimes it is required to direct the request through a proxy, however if not all outgoing requests can be directed though the proxy it is not possible to use standard proxy environment variables.
This adds the `CODY_AZURE_OPENAI_IDENTITY_HTTP_PROXY` environment variable for this specific purpose.  If set the credential requests will use a separate http.Client with the proxy specified.
resolves https://github.com/sourcegraph/sourcegraph/issues/58827
Created an Azure SPN with cert
Created a local proxy 
az logout -- to ensure that i'm not getting credentials from az
export CODY_AZURE_OPENAI_IDENTITY_HTTP_PROXY=localhost:29100
set azure environment credential env variables
start proxy
sg start
```
2023/12/08 14:32:41 …
```

Cody: Azure OpenAI allow authentication requests to use a proxy

---

doc/admin/external_service/azuredevops.md

This change adds more context to each scope option in ADO token creation page. Previously, this wasn't clear to users creating tokens and confused them.
Doc update. Previewed locally.
[Preview Link](https://docs.sourcegraph.com/@doc/ado-scope-update)

Additional scope information for each ADO scope section

---

cmd/gitserver/README.md
dev/p4-fusion-dev
dev/tool_deps.bzl
dev/tools/BUILD.bazel

The only place where we currently use p4-fusion appears to be in integration tests, where the binary is already in the image via Wolfi. All other unit tests just test for expected args/env to p4-fusion if we _were_ to call it\
`./dev/p4-fusion-dev` successfully runs the binary

bazel: provide p4-fusion via bazel

---

cmd/worker/internal/embeddings/repo/scheduler.go
doc/cody/core-concepts/embeddings/configure-embeddings.md
internal/embeddings/embed/embed.go
internal/embeddings/embed/embed_test.go

Usually, during an embeddings job we allow 10% of embedding requests to fail,
simply skipping over failed chunks. If a customer has hit their rate limits,
this means we might continually send a huge number of embedding requests that
we know will immediately fail. With this change, we immediately fail a job if
the rate limit is exceeded.
It also increases the amount of time between attempting to run a job to 15
minutes. This won't make a big difference to user experience, since by default
embeddings jobs aren't allowed to be scheduled within 24h of the last run. But
it helps prevent jobs from continuously being scheduled then failing.
This change is unlikely to have a user-facing impact, but just helps cut down
on noise in logs and excessive requests to Cody Gateway.
Added new unit test …

Embeddings: fail job immediately if rate limited exceeded

---

client/web/src/LegacyLayout.tsx
client/web/src/auth/PostSignUpPage.tsx
client/web/src/user/settings/accessTokens/UserSettingsTokensArea.tsx

- This PR accompanies https://github.com/sourcegraph/sourcegraph/pull/58854 in solving https://github.com/sourcegraph/cody/issues/2054
I did two things:
- Add an "IF cody-pro feature flag is on THEN redirect /post-sign-up to /cody/manage"
- IF cody-pro feature flag is on THEN don't redirect other pages to /post-sign-up.
I recommend [this Loom recording](https://www.loom.com/share/eaa6c32fa0114321a482846676664bef) to
- @chenkc805 to verify if the behavior is as expected
- the reviewer because I also go though the code
Tested it in the [Loom](https://www.loom.com/share/eaa6c32fa0114321a482846676664bef)

SSC: Add redirect from /post-sign-up to /cody/manage for users with the cody-pro feature flag

---

internal/cmd/tracking-issue/Dockerfile

It didn't build on the previous Go version, now we use the `slices` package (it trips up `go get`). 
Built it locally.

dev: issue tracker, bump Go version

---

client/web/src/cody/management/CodyManagementPage.tsx

Remove emacs documentation link text from cody management page

Remove emacs documentation link text from cody management page

---

cmd/gitserver/internal/cleanup.go
internal/database/dbmocks/BUILD.bazel
internal/database/dbmocks/mocks_temp.go
internal/database/gitserver_repos.go
internal/database/gitserver_repos_test.go

Noticed as part of #wg-cheaper-sourcegraph that the calls to UpdateRepoSizes on sourcegraph.com would never, ever return. Instead the goroutine would get stuck, somehow connection between client and DB would get lost, DB would think client is still there, and the whole thing might have locked rows, and it all became a big disaster.
Digging into this I found that even locally, I could never get the test to update, say, 100k repos with the given batch size. It would time out after 10min.
So what I was to
1. Remove the transaction and the locking -- we update two fields anywhere, that aren't updated by anything else (and in the case of `updated_at` it doesn't matter)
2. Reduce the batch size drastically
3. Add a test to play around with large repo sizes
4. Add a logger
When running the test …

database: speed up UpdateRepoSizes

---

cmd/cody-gateway/internal/httpapi/completions/upstream.go

This PR changes the new autoflushing code to only perform our aggressive flushing for code-completions, which:
- have far lower latency (lower chance of interrupts)
- return smaller responses
- have lower cost of retries (if we get an error)
- make it easier to gracefully handle errors (are used to populate cache, not directly returned to the user)
This code is off-by-default, I intend to enable it later today and watch https://cloudlogging.app.goo.gl/ozyEAoy1PsmBAPU19 for errors.
- locally tested

Flush for code completions only

---

dev/pr-auditor/main.go

Noticed a minor mistake in `pr-auditor`, we were using the repo name instead of the repo owner to create labels. 
Because the error is ignored in the code, to avoid messing things up, we never noticed it. 
CI

dev: fix pr-auditor label owner

---

client/browser/src/shared/code-hosts/gitlab/domFunctions.ts

Thanks to @taras-yemets this PR fixes code target selector since Gitlab changed their markup about code blocks recently. 
- Check that code intel tooltip shows up in Gitlab code view

Gitlab Native integration: Fix code element target selector

---

internal/search/query/transformer.go

Some tiny typos I noticed while getting up to speed with this code.
Comment-only change

Search: correct comments in query planning

---

cmd/frontend/graphqlbackend/telemetry.go
cmd/frontend/graphqlbackend/telemetry.graphql
cmd/frontend/graphqlbackend/telemetry_test.go
cmd/frontend/internal/telemetry/resolvers/BUILD.bazel
cmd/frontend/internal/telemetry/resolvers/telemetrygateway.go
cmd/frontend/internal/telemetry/resolvers/telemetrygateway_test.go

Generating the timestamp serverside can cause client-generated events to appear out-of-order, and in general will have a gap between when an event actually occurred and the timestamp that gets persisted.
This change only fixes it for V2 telemetry - the V1 `logEvent` mutation doesn't accept a timestamp, and while the V1 `logEvents` GraphQL schema does accept a timestamp, [the resolver input implementation does not use it](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/user_usage_stats.go?L85:1-109:2).
I will update https://github.com/sourcegraph/telemetry after this PR, and add handling to VSCode.
Unit tests

graphqlbackend/telemetry: allow client-provided timestamp in events

---

internal/search/searcher/search.go

This block duplicates the logic further down. It doesn't cause any problems because it makes the `IsGRPCEnabled` check below it redundant, but it's just unnecessary duplication.
CI.

gRPC: remove duplicate implementation

---

doc/batch_changes/explanations/permissions_in_batch_changes.md

Just a couple of settings that were [cased incorrectly](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4df3edf5ae0f17c702485455a7bf71fb86f0c9be/-/blob/schema/site.schema.json?L594-594).
N/A
[Preview Link](https://docs.sourcegraph.com/@cc/fix-batch-changes-docs)

Docs: fix batch changes settings names

---

WORKSPACE
testing/tools/upgradetest/BUILD.bazel

@DaedalusG this PR turns the `sh_binary` into  a `sh_test` and properly fixes the `select` block so we can use this locally (assuming you use your arm laptop). 
I tested it locally, if ran fine, though it failed because of the timeout, which you can adjust on your side. 
I also cherry-picked an update to `hermetic_cc` as the rebase wasn't that trivial and I'll leave you handle that on your side. If you're blocked, please reach out. 
```
bazel test //testing/tools/upgradetest:sh_upgradetest --config darwin-docker
```
Locally tested

Turns the `sh_binary` into a `sh_test`

---

dev/pr-auditor/README.md
dev/pr-auditor/main.go

See https://sourcegraph.slack.com/archives/C05EVRLQEUR/p1702391975683659?thread_ts=1702384926.937979&cid=C05EVRLQEUR for context. 
Basically, in order to re-use the pr-auditor binary to perform manual runs, we need to be able to skip the status checks POST, because it makes no sense on old runs. 
Locally tested, CI

dev: add a --skip-status flag to pr auditor

---

internal/database/gitserver_repos.go

While inspecting this query in production we noticed that it didn't use the `repo.name` index. Changing the cast from `::text` to `::citext` makes it use the index.
With a representative query on sourcegraph.com, we go from
before: 5.5sec with batch size 100
to
after: 194ms with batch size 100
Run the following on the production DB:
```sql
WITH update_data AS (
SELECT * FROM (VALUES
-- (<repo_name>, <repo_size_bytes>),
('github.com/jawah/niquests'::citext, 13812962::bigint),
('github.com/calebyhan/population_cities'::citext, 31575::bigint),
('github.com/jeroenouw/AngularIonic'::citext, 2208211::bigint),
('github.com/elysium-suite/sarpedon'::citext, 384235::bigint),
('github.com/zhangtaii/douban.fm'::citext, 951327::bigint),
('github.com/lildinti/pygubu-examples'::citext, 0::bigint), …
```

janitor: improve repo size update perf from 5.5sec to 200ms

---

client/branded/src/search-ui/components/FileContentSearchResult.tsx
client/shared/src/components/ranking/PerFileResultRanking.ts
client/shared/src/search/stream.ts
client/web-sveltekit/src/lib/search/utils.ts

This removes a field that is never set on `ChunkMatch` and `LineMatch`. These types should match the definitions on the backend. Looking at the git history, it looks like this hasn't been functional in a long time. `AggregableBadge` _is_ still used in some code intel hover code because it used to be an extension point.
The type system will catch most obvious errors here. I also did a bit of manual clicking to make sure nothing unexpected broke.

Web: remove aggregableBadge from `ChunkMatch` and `LineMatch`

---

cmd/searcher/internal/search/BUILD.bazel
cmd/searcher/internal/search/search_test.go

I've got a separate PR I'm about to open that updates searcher to respect `NumContextLines` and I want to add some tests for that. Updating these tests is super obnoxious because we marshal to a custom format, and the formatting of the tests is pretty messy.
This PR just updates the test to use autogold so tests will fail if there is a change, but can be updated with `go test ./cmd/searcher/internal/search/ -update`. 
The tests still pass.

Search: convert searcher tests to autogold

---

cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
internal/completions/httpapi/chat.go

Problem: I forgot to update one of the model lists in https://github.com/sourcegraph/sourcegraph/pull/58817. As a result, we got mistakenly limited with some of the models.
Note: I know it's not great to have these lists duplicated (see the changes to see what I'm talking about), but I wanted to minimize this change, so just left a reminder to don't forget to update the other list when making changes.
Tested it with a Free and a Pro user, and it returned the right models.

SSC: Handle model permissions correctly

---

client/web/src/tracking/eventLogger.ts

Currently we only [log post-auth events from the frontend](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fe5f100efdb631a53c0ea104af72224ec718ff88/-/blob/client/web/src/tracking/eventLogger.ts?L240-253) when a view event is called. However, we recently discovered that some pages have been added that don't call view events (e.g. [here's an example of "fixing" one](https://github.com/sourcegraph/sourcegraph/pull/57957)).
This PR makes it so that any logged events trigger the appropriate checks.
Tested locally

Add URL param checking to all event types, not just page view events

---

cmd/searcher/internal/search/search.go
cmd/searcher/internal/search/search_regex_test.go
cmd/searcher/internal/search/store.go
cmd/searcher/internal/search/store_test.go
cmd/searcher/internal/search/zipcache_test.go

Searcher's entrypoint method handles delegating to standard unindexed search
vs. structural search. This change consolidates the structural search logic to
make this method easier to follow
Specific changes:
* Create new function `Service.getZipFile`
* Consolidate structural search logic
* Remove redundant method `Store.PrepareZip`
Refactor is covered by existing unit tests

Searcher: factor out structural search logic

---

internal/insights/query/querybuilder/builder_test.go
internal/insights/query/querybuilder/regexp.go
internal/insights/query/querybuilder/regexp_test.go
internal/search/query/parser.go
internal/search/query/parser_test.go
internal/search/query/printer.go
internal/search/query/testdata/TestStringHuman/printer#08.golden

For code insights, we wrap regex regex patterns with slashes when we're rebuilding the query string from the parsed query. However, we cannot just wrap a regex pattern in /.../ because the query scanning logic respects escape sequences, so anything that would be interpreted as an escape sequence by the query scanner would break the intent of the original regex.
This PR fixes the StringHuman method by correctly escaping regex patterns when delimiting them with /.../.
[Slack thread](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1698164126691289)
Backport of #57877
Added a roundtrip test for the roundtrip we can guarantee to be stable. Updated tests that already demonstrated this incorrect behavior. Also manually tested that the bad insights behavior was fixed.

[Backport 5.2] Search: fix delimiting escape sequences

---

enterprise/cmd/worker/internal/embeddings/repo/scheduler.go
internal/embeddings/embed/embed.go
internal/embeddings/embed/embed_test.go

Usually, during an embeddings job we allow 10% of embedding requests to fail,
simply skipping over failed chunks. If a customer has hit their rate limits,
this means we might continually send a huge number of embedding requests that
we know will immediately fail. With this change, we immediately fail a job if
the rate limit is exceeded.
It also increases the amount of time between attempting to run a job to 15
minutes. This won't make a big difference to user experience, since by default
embeddings jobs aren't allowed to be scheduled within 24h of the last run. But
it helps prevent jobs from continuously being scheduled then failing.
This change is unlikely to have a user-facing impact, but just helps cut down
on noise in logs and excessive requests to Cody Gateway.
Backport for …

[Backport 5.2] Embeddings: fail job immediately if rate limited exceeded

---

dev/managedservicesplatform/internal/resource/monitoringalertpolicy/BUILD.bazel
dev/managedservicesplatform/internal/resource/monitoringalertpolicy/monitoringalertpolicy.go
dev/managedservicesplatform/internal/resource/monitoringalertpolicy/monitoringalertpolicy_test.go
dev/managedservicesplatform/internal/resource/redis/redis.go
dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
dev/managedservicesplatform/internal/stack/monitoring/monitoring.go
dev/managedservicesplatform/managedservicesplatform.go
dev/managedservicesplatform/spec/monitoring.go
lib/pointers/ptr.go
lib/pointers/ptr_test.go

Part of 
- https://github.com/sourcegraph/sourcegraph/pull/58816
Adds monitoring alert policies for Redis based on [alerts_redis.tf](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/infrastructure/-/blob/cody-gateway/modules/monitoring/alerts_redis.tf) from Cody Gateway
Redis ID is referenced using a cross stack output. Example here from the generated output `resource.labels.redis_instance_id = \"${data.terraform_remote_state.cross-stack-reference-input-cloudrun.outputs.cross-stack-output-google_redis_instanceredis-instanceid}\"`
CI + viewing generated terraform cdtkf - has not been tested live

msp: Add alerts if Redis is configured

---

dev/managedservicesplatform/BUILD.bazel
dev/managedservicesplatform/internal/resource/monitoringalertpolicy/BUILD.bazel
dev/managedservicesplatform/internal/resource/monitoringalertpolicy/monitoringalertpolicy.go
dev/managedservicesplatform/internal/resource/monitoringalertpolicy/monitoringalertpolicy_test.go
dev/managedservicesplatform/internal/resource/redis/redis.go
dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
dev/managedservicesplatform/internal/stack/monitoring/BUILD.bazel
dev/managedservicesplatform/internal/stack/monitoring/monitoring.go
dev/managedservicesplatform/managedservicesplatform.go
dev/managedservicesplatform/spec/BUILD.bazel
dev/managedservicesplatform/spec/monitoring.go
dev/managedservicesplatform/spec/spec.go
dev/sg/msp/sg_msp.go
lib/pointers/ptr.go
lib/pointers/ptr_test.go

Add monitoring stack to MSP
Includes alerts based on those defined in cody gateway [alerts_cloudrun.tf](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/infrastructure/-/blob/cody-gateway/modules/monitoring/alerts_cloudrun.tf)
Closes https://github.com/sourcegraph/sourcegraph/issues/56876
- Deployed to a msp-testbed GCP project observed alert policies in place
- eyeballed the cdktf matches alerts in [alerts_cloudrun.tf](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/infrastructure/-/blob/cody-gateway/modules/monitoring/alerts_cloudrun.tf)

msp: add monitoring stack

---

internal/database/gitserver_repos.go

On sourcegraph.com it took 5min to update 780k repos with batch size of
200. Batches took between 50ms and 200ms. So I think it's fine to increase to 1000.
- N/A

janitor: bump batch size again

---

client/web-sveltekit/src/lib/Timestamp.svelte
client/web-sveltekit/src/lib/Timestamp.test.ts
client/web-sveltekit/src/lib/__snapshots__/Timestamp.test.ts.snap
client/web-sveltekit/src/lib/graphql/apollo.ts
client/web-sveltekit/src/lib/repo/FileTable.gql
client/web-sveltekit/src/lib/repo/FileTable.svelte
client/web-sveltekit/src/lib/repo/HistoryPanel.svelte
client/web-sveltekit/src/lib/repo/api/tree.ts
client/web-sveltekit/src/lib/repo/tree.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/page.gql
client/web-sveltekit/src/stories/TimestampExample.svelte

This commit builds on #58847 (which enables a new way of working with GraphQL). I initially also changed the loader to query for the list of files directly instead of using `fetchTreeEntries`, but the same function is used by the file tree sidebar, which, thanks to caching, ensures that we have to fetch this data only once. I'd still like to refactor this at some point and make it so that data dependencies are declared next to the components that need them, but that should be done in a separate PR/commit.
This commit also changes the prop of the Timestamp component, because props that default to `false` are easier to work with. This also uncovered an issue with the test setup.
Manual testing

svelte: Show commit info next to tree entries on tree page

---

client/web/src/codeintel/ReferencesPanel.tsx

As I was changing the code to use the code intel API,
figured that I might as well simplify a few small things
that I noticed were off.
Does not affect any functionality
Tested with `sg start web-standalone`

cleanup: Simplify some of the ref panel code

---

client/web/src/cody/management/CodyManagementPage.tsx

Previously, (1) the underlines showed up in the space between the icon and the text and (2) the underline was blue for Documentation and gray for the other one.
CI

fix underlines on link hover

---

client/shared/src/codeintel/legacy-extensions/language-specs/languages.ts
client/shared/src/languages.ts
client/web/src/codeintel/ReferencesPanel.tsx
client/web/src/codeintel/token.ts
client/web/src/codeintel/useCodeIntel.ts
client/web/src/enterprise/codeintel/searchBased.ts
client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts

Previously, we relied on detecting the language from file paths,
then using various regexes associated with the language to identify
token boundaries. However, the code mirror blob view always provides
a full token range, which can be used directly, instead of attempting
to recompute the token boundaries.
For older URLs, we fallback to simple identifiers, which should
work for the vast majority of languages and identifiers.
We cannot yet remove the language detection here because the file
extensions associated with the language are later used for search-based
code navigation.
This patch also makes the language spec optional for search-based
code intel, as we do not have a solution to #56376 which would
guarantee that we always have a language available. If a language
is not available, …

client: Avoid complex tokenization in ref panel code

---

.github/teams.yml

This team doesn't exist anymore
Trivial change, not touching any app code.

Do not add code-exploration team label to PRs

---

dev/ci/internal/ci/operations.go

disable chromatic again (https://github.com/sourcegraph/devx-support/issues/470) 
CI

ci: temporarily disable chromatic tests

---

cmd/frontend/backend/external_services.go
cmd/frontend/backend/external_services_test.go
internal/database/external_services.go
internal/database/external_services_test.go
nogo_config.json

Regex vs glob shenanigans
`bazel build $(bazel query 'kind("go_binary", //...)'`

bazel: fix nogo matchers and ensuing violations

---

cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go

For users with quota overrides, we should still use their Cody-pro limits
- curl correctly refreshes limits

Apply model list for users with overrides

---

.vscode/settings.json

Nice to have, prevents search results in VS Code from being clogged with Bazel generated files 
Tested in VS code UI

chore: Ignore bazel in search and quick-open vscode

---

client/web/src/cody/onboarding/CodyOnboarding.tsx
client/web/src/cody/subscription/CancelProModal.tsx
client/web/src/cody/subscription/CodySubscriptionPage.tsx
client/web/src/cody/subscription/UpgradeToProModal.tsx

For Cody GA some web events have been added and they are only logging metadata to `event_properties` and not `public_arguments`. This PR fixes that and ensures the analytics team is able to receive the event metadata.
simple change, not touching any logic.
ensure `sg start` runs

update logging to include public_args

---

cmd/cody-gateway/internal/events/events.go

Could be useful for deriving retry information from specific events.
n/a

cody-gateway: add trace_id to metadata

---

cmd/telemetry-gateway/internal/events/events.go

Just in case we can get more details from error reports like https://sourcegraph.slack.com/archives/C05V6JS7QKB/p1702496634429589
CI

telemetry-gateway: try to record cancel cause if one is provided

---

cmd/telemetry-gateway/internal/events/events.go
cmd/telemetry-gateway/internal/server/server.go
cmd/telemetry-gateway/service/service.go
internal/pubsub/topic.go
internal/updatecheck/handler.go

We currently don't call `Stop` on the pub/sub client, which is pretty important because I think it actually does buffering by default: https://sourcegraph.com/github.com/googleapis/google-cloud-go@6eb769621618a965abeabf11e6315bdb8be9b050/-/blob/pubsub/topic.go?L122-137
This change adds a `TopicPublisher` interface with write-only methods so that we don't accidentally Stop the client at callsites, and adds a Stop to telemetry-gateway. I'll follow up with another change to update Pings to the MSP runtime and apply a Stop there as well
CI

pubsub: add narrower TopicPublisher interface, ensure Stop in telemetry-gateway

---

client/branded/src/search-ui/components/FileContentSearchResult.tsx

Thanks to @camdencheek for the catch. I forgot to update preview button UI with new feature flag for the search results page
- Check that you can't see preview button when your newSearchResultsUI feature flag is off

Search Results: Use new flag for file preview feature

---

deps.bzl
go.mod
go.sum
internal/telemetrygateway/v1/event.go
internal/telemetrygateway/v1/event_test.go

This change upgrades `github.com/google/uuid` to use their new implementation of UUID v7, which is a new time-ordered UUID format. This might have benefits because we do potentially large updates/deletes based on the ID (export ack and queue cleanup respectively).
Sanity check test on the new default generator, and monitor post-deploy.

telemetrygateway: use time-ordered UUID v7 for events

---

cmd/frontend/internal/httpapi/BUILD.bazel
cmd/frontend/internal/httpapi/auth.go
cmd/frontend/internal/httpapi/auth_test.go

#57160 introduced a regression where requests to `/.api/license/check` all started failing with `401 Unauthorized`. License checks have been failing since 4 October. We never noticed because we disabled any consequences of license checks failing, but we would like these checks to succeed so that we can use the events produced by the checks to detect when licenses are used by multiple instances.
This PR adds a bypass to this handler, similar to the bypass for `/.api/scim/v2`, so that the license check handler checks the authentication instead.
Added unit test

Bypass the access token auth handler for license checks

---

cmd/telemetry-gateway/internal/events/events.go
cmd/telemetry-gateway/internal/events/events_test.go
cmd/telemetry-gateway/internal/server/server.go
cmd/telemetry-gateway/service/BUILD.bazel
cmd/telemetry-gateway/service/config.go
cmd/telemetry-gateway/service/service.go

In dotcom, each export job is now taking a pretty long time (https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/18312), and part of that might be because we are not very fast at doing these exports in Telemetry Gateway, with a concurrent publish limit of 100, when payloads in a stream are regularly several times that.
This change increases the default from 100 to 250, and also makes it configurable via env var so we can change it more easily. Resource utilization on Telemetry Gateway is _very_ low, so this should be safe on our end - if it causes issues with Pub/Sub (unlikely) we'll get Sentry alerts.
CI

telemetry-gateway: bump default stream publish concurrency to 250, make configurable

---

lib/managedservicesplatform/runtime/contract.go

Update docstring to try to guide how Healthy should be implemented
n/a

msp/runtime: clarify what Healthy should indicate

---

WORKSPACE

While updating it in devx-service I noticed there was a newer version
CI

bazel: update rules_oci to 1.4.3

---

cmd/frontend/internal/dotcom/productsubscription/license_check_handler.go

Just updates the duplicate license keys check so that it doesn't spam the #licenses Slack channel
N/A webhook endpoint update

Update the webhook endpoint for the multiple license keys check

---

client/web-sveltekit/BUILD.bazel

In the prototype "external" links are marked with a React logo to make it clear that these links makes you leave the prototype. This currently doesn't work on S2 because the React logo wasn't included in the list of source files for bazel.
I don't have a good way to test this locally, but it's safe because it's a non-code change.

svelte: Fix bazel build to include React logo

---

dev/sg/dependencies/shared.go
dev/sg/internal/usershell/autocomplete/README.md
dev/sg/internal/usershell/autocomplete/bash_autocomplete
dev/sg/internal/usershell/autocomplete/zsh_autocomplete

Still trying to figure out if https://github.com/urfave/cli/issues/1822 is caused by us, I notice our completion script has fallen out of sync with upstream.
```
sg setup
```
play around with new completions
```
sg setup # should show completions up-to-date
```

dev/sg/autocomplete: sync completion scripts from upstream

---

dev/managedservicesplatform/spec/monitoring.go
dev/managedservicesplatform/spec/spec.go
dev/sg/msp/sg_msp.go

The top-level spec works if zero value and does not need to be explicitly provided, but right now this causes a JSON schema error if you don't provide `monitoring`. This change makes it optional for the purposes of JSON schema validation.
```
sg msp schema -output='../managed-services/schema/service.schema.json'
```

msp: make monitoring spec optional

---

dev/managedservicesplatform/internal/stack/iam/iam.go

Looks like the one that needs it is the SA, not the Cloud Run identity:
```
Error: Error waiting to create Service: Error waiting for Creating Service: Error code 13, message: Revision 'sams-00001-8m6' is not ready and cannot serve traffic. spec.template.spec.containers[0].env[12].value_from.secret_key_ref.name: Permission denied on secret: projects/sourcegraph-dev/secrets/SAMS_GITHUB_CLIENT_SECRET/versions/latest for Revision service account sams-sa@sams-dev-bfec.iam.gserviceaccount.com.
```
Was able to successfully start revision with https://github.com/sourcegraph/managed-services/commit/56af2255a5928c60cd8a24aa7cfd3f42ed120c7f

msp/iam: grant external secret to workload SA, not Cloud Run identity

---

deps.bzl
go.mod
go.sum
internal/telemetrygateway/v1/event.go
internal/telemetrygateway/v1/event_test.go

This change upgrades github.com/google/uuid to use their new implementation of UUID v7, which is a new time-ordered UUID format. This might have benefits because we do potentially large updates/deletes based on the ID (export ack and queue cleanup respectively).
(cherry picked from commit da5694f6974794432047819eeb77d8c74bff2e50 #59016)
CI, and I've seen some non-scientifically-visible improvements corresponding to when this was rolled out to dotcom, with a slight drop in export durations, queue cleanup times, and time to collect metrics about the backlog:

[Backport 5.2] telemetrygateway: use time-ordered UUID v7 for events (#59016)

---

client/shared/src/api/contract.ts
client/shared/src/api/extension/extensionHost.ts
client/shared/src/codeintel/api.ts

This is some setup for getting rid of all the cruft from extensions. The first step is to make the browser extension use the codeintel packages directly rather than requiring codeintel extensions running in a web worker. This extracts and simplifies few functions to prepare for that.
Existing tests. Everything here should be semantics-preserving. I'll do more careful tests of the browser extension before making another release, but I'd like to move as fast as I can on the removal of the extensions cruft because it's causing pain. This should not break anything in the webapp because the webapp does not use extensions.

Extensions: some prep work for removal

---

cmd/frontend/auth/user.go
cmd/frontend/auth/user_test.go

Follow-up to https://github.com/sourcegraph/sourcegraph/pull/59036 , expanding the new `externalAuthSignup` event coverage for the purposes of a potential SAMS + telemetry V2 demo.
Details in docstrings.
CI

externalAuthSignup: update v2 events to capture all cases

---

client/web-sveltekit/src/routes/search/SearchResults.svelte

I had changed the border from bottom to top but forgot to update this rule.
Manual testing

svelte: Fix repo sidebar border style

---

client/branded/src/search-ui/components/RepoMetadata.tsx
client/branded/src/search-ui/components/RepoSearchResult.tsx
client/shared/src/search/stream.ts
client/web/src/integration/commit-page.test.ts
client/web/src/integration/graphQlResponseHelpers.ts
client/web/src/repo/backend.ts
client/web/src/repo/tree/TreePage.test.tsx
client/web/src/repo/tree/TreePage.tsx
client/web/src/repo/tree/TreePageContent.tsx
cmd/frontend/graphqlbackend/BUILD.bazel
cmd/frontend/graphqlbackend/graphqlbackend_test.go
cmd/frontend/graphqlbackend/repository.go
cmd/frontend/graphqlbackend/repository_test.go
cmd/frontend/graphqlbackend/schema.graphql
cmd/frontend/internal/search/search.go
internal/database/repos.go
internal/database/repos_test.go
internal/search/streaming/http/events.go
internal/types/types.go

Currently, we sync topics from GitHub and GitLab and it is possible to
filter repositories by their topics with the `repo:has.topic` filter.
However, unlike user-added metadata, the synced topics are not visible in the UI,
neither for repo matches nor on the repo tree page. This means it is impossible 
for users to figure out which topics they can filter by.
With this PR we display topics, such as "language" or "golang", in addition to 
metadata (EG `fruit:banana`) for repo matches and on the repo tree page (see screenshots).
**Search results**
**Repository tree page (right panel)**
Note: Our search language distinguishes between user provided metadata (has.meta) and automatically synced metadata (has.topic). 
- I checked that clicking on a "topic" badge adds a …

search: expose GitHub/GitLab topics in UI

---

cmd/cody-gateway/internal/actor/actor.go
cmd/cody-gateway/internal/actor/actor_test.go
cmd/cody-gateway/internal/actor/source.go
cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
cmd/cody-gateway/internal/httpapi/completions/anthropic_test.go

Historically, we never saw meaningful abuse from Cody App users, but now that PLG users use `dotcom-user` by default, we need abuse tooling to work for this too.
- also unit tests

Treat dotcom-user as dotcom user (duh)

---

client/web-sveltekit/src/routes/search/SymbolSearchResult.svelte

Just like file matches, symbol matches should be clickable and open to the respective file.

svelte: Link symbol search results

---

.aspect/bazelrc/ci.bazelrc
.aspect/bazelrc/ci.sourcegraph.bazelrc

This is more a change for Aspect Workflows, considering we auto retry steps on Buildkite in our normal pipeline - we increase the flake retry attempts so that Aspect (but really Bazel) also retries a little bit more 
CI

bazel: set retry flakes to 3

---

client/web-sveltekit/src/lib/fileIcons.ts
client/web-sveltekit/src/lib/web.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte

This adds file icons to the tree view in the svelte kit prototype.
Manual, visual testing

Sveltekit Prototype: add file icons to svelte prototype

---

dev/linters/forbidigo/forbidigo.go

New output: `dev/linters/dbconn/dbconn.go:83:16: use of fmt.Errorf forbidden because “errors.Newf should be used instead” (forbidigo)`
Previous output: `dev/linters/dbconn/dbconn.go:83:16: use of fmt.Errorf forbidden by pattern ^fmt\.Errorf$ (forbidigo)`
Used `fmt.Errorf` in //dev/linters/dbconn` and ran bazel build on it

bazel: nicer error message for forbidigo patterns

---

client/web-sveltekit/src/routes/+layout.svelte

Before this commit the theme was always initialized as 'system'. This loads the configured theme from temporary settings. There will be a flash of the wrong theme on load, but that's not avoidable atm.

svelte: Initialize theme with user configured value

---

client/branded/src/search-ui/components/FilePathSearchResult.tsx
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx

So there are a few problems with new search results UI and global navigation UI feature flags
- In new navigation the new search mode picker is missing (this PR fixes)
- When we released file preview feature behind navigation flag we had to change it to newSearchResultUI feature flag, when I updated it I forgot about one place, so I fixed it here too
- Check that new navigation search box has new search modes picker
- Check that file preview feature is available only when `newSearchResultsUI` is enabled

Fix new flag for file preview feature/global navigation search box

---

client/branded/src/search-ui/input/codemirror/token-info.ts
client/wildcard/src/global-styles/highlight.scss

Reverts sourcegraph/sourcegraph#58384
This caused some drastic UI issues with search results and certain file types.
Tested that the behavior has been returned to the original state, where tokens are only highlighted when the info for the hovercards is populated.

Revert "Code Navigation: tokens highlight immediately on hover"

---

client/web-sveltekit/src/lib/theme.ts
client/web-sveltekit/src/routes/+layout.svelte

#59086 didn't work properly. Turns out the theme values stored in temporary setting are different from what the prototype expected. It only accidentally worked when I tested it.
This commit introduces a helper method that accepts an arbitrary string value and updates the theme state accordingly, instead of using an arbitrary string value as theme state (ideally TS would have complained about this before but it looks like it didn't).
Go to dotcom, change theme to the different values (system, light, dark). Refresh local dev build (proxies to dotcom) after every change and verify that it applies the set theme.

svelte: Fix setting theme from temporary settings

---

dev/managedservicesplatform/internal/resource/cloudflare/cloudflare.go

There are a _lot_ of records and stuff in Cloudflare - this makes it easier to identify which ones are managed by MSP.
n/a

msp/cloudflare: add comment and tags for identifiability

---

dev/run-server-image.sh
testing/BUILD.bazel

Some of the suites weren't yet using gRPC - this PR turns it on so we gain some more confidence before we start dropping HTTP entirely.
See if CI passes.

Make sure we test gRPC in CI suites

---

dev/linters/forbidigo/BUILD.bazel
dev/linters/forbidigo/forbidigo.go
dev/linters/go.mod
dev/sg/linters/linters.go

Closes https://github.com/sourcegraph/sourcegraph/issues/54847
Sample deliberate error:
```
$ bazel build //dev/sg
INFO: Analyzed target //dev/sg:sg (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/noah/Sourcegraph/sourcegraph/dev/sg/BUILD.bazel:128:10: GoCompilePkg dev/sg/sg.a failed: (Exit 1): builder failed: error executing command (from target //dev/sg:sg) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src dev/sg/analytics.go -src dev/sg/checks.go -src ... (remaining 245 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: nogo: errors found by nogo during build-time code analysis: …
```

bazel: add sgexit lint to nogo

---

client/web-sveltekit/vite.config.ts

I don't know if this is only an issue for me, but I'm not able to run `pnpm build` locally anymore. The build fails with the error mentioned in the comment. Hover seeing that CI is green for other PRs and SvelteKit is deployed to S2 successfully, I don't really know why this is happening.
This change fixes it though.
`pnpm build` runs locally without issue.

svelte: Fix local build

---

dev/managedservicesplatform/internal/stack/project/project.go

The default is from Cloud, and is way too long for the usual MSP use case - almost all services set a custom suffix length today to avoid hitting project name limits. https://github.com/sourcegraph/managed-services/pull/214 pins anything using the default today.
n/a

msp: reduce default project suffix length

---

dev/caddy.sh

This MR addresses #58926.  
The changes ensure the Caddy admin server is running before calling another `caddy [command]`.
I also replaced `exec` with `eval`, as that allowed using `trap` while staying in the current shell session.
<details><summary>Before</summary>
Commit [`57166ea80caa7e2eb7d9c8134b35c47997a0835c`](https://github.com/bevzzz/sourcegraph/commit/57166ea80caa7e2eb7d9c8134b35c47997a0835c)
</details>
<details><summary>After</summary>
</details>
Manually, since most of the logic is still in `caddy.sh` and, as far as I can tell, the script is not used in production.
1. Configure the "initial" state for anyone running `sg setup` for the first time:
- Run  `caddy untrust` to remove the root certificate from your local trust store
- Run ` caddy stop` to make sure the  Caddy admin …

fix(sg): start Caddy admin server before `caddy trust`

---

internal/search/query/labels.go
internal/search/query/parser.go
internal/search/query/parser_test.go
internal/search/query/transformer_test.go

Relates to https://github.com/sourcegraph/sourcegraph/issues/58815
Ported directly from https://github.com/sourcegraph/sourcegraph/pull/58849/
We add support for glob syntax to file and repo filters.
Notes:
- `f:` matches nothing. I think this is less surprising than our [current behavior](https://sourcegraph.com/search?q=context:global+f:&patternType=standard&sm=1)
- `*` matches any sequence of characters, including `/`
- No other special characters are supported
Test plan:
- new unit tests

search: support glob syntax for repo and file filters

---

client/web-sveltekit/src/lib/search/input/SearchInput.svelte
client/web/src/search/input/V2SearchInput.tsx
client/web/src/search/input/suggestions.ts

This updates suggestions to insert literals instead of regex-escaped values for repo and file filters.
CI

search: use literal suggestions for keyword search

---

dev/global-settings.json

This reverts the default from loveable search to smart search for the local dev environment. This is mainly to disentangle our protoype running on S2 from everyone's dev experience.
Devs who want to use loveable search locally, can set the feature flag "search-new-keyword".
- ran a local instance and confirmed that the default is now "smart search".

dev: revert to old search mode for local dev environment

---

internal/database/event_logs_test.go
internal/database/external_accounts_test.go
internal/database/external_services_test.go
internal/database/feature_flags_test.go
internal/database/outbound_webhook_logs_test.go
internal/database/outbound_webhooks_test.go
internal/database/recent_view_signal.go
internal/database/recent_view_signal_test.go

Found this package frustratingly slow, so looked at the worst offenders.
Top 5 before:
```
TestOutboundWebhookJobs,3.61
TestRecentViewSignalStore_InsertPaths_OverBatchSize,4.9
TestFeatureFlagStore,6.28
TestEventLogs_OwnershipFeatureActivity,7.05
TestExternalServicesStore_Upsert,9.72
```
Top 5 after:
```
TestPermsStore_GrantPendingPermissions,2.28
TestExternalServicesStore_DeleteExtServiceWithManyRepos,2.43
TestAccessTokens,2.47
TestWebhookUpdate,2.67
TestFeatureFlagStore,4.95
```
CI still passes.

Speed up some slow DB tests

---

dev/managedservicesplatform/managedservicesplatform.go
dev/managedservicesplatform/terraformcloud/BUILD.bazel
dev/managedservicesplatform/terraformcloud/runs.go
dev/managedservicesplatform/terraformcloud/terraformcloud.go
dev/sg/cloudsqlproxy/BUILD.bazel
dev/sg/cloudsqlproxy/binary.go
dev/sg/cloudsqlproxy/cloudsqlproxy.go
dev/sg/msp/BUILD.bazel
dev/sg/msp/helpers.go
dev/sg/msp/sg_msp.go

This change introduces an `mi2`-like experience for interacting with MSP databases. By default we use the new readonly-SA introduced in https://github.com/sourcegraph/sourcegraph/pull/59105, otherwise with the `--write-access` flag you can connect as the same user as the Cloud Run workload, which gives a lot more permissions.
An alias, `sg msp pg connect`, is available for those less inclined to type out the entire `postgresql` subcommand name.
Closes https://github.com/sourcegraph/managed-services/issues/207
Applied to `msp-testbed`, which has a PG instance and provisioned tables.
Try both service accounts:
```
sg msp pg connect --write-access msp-testbed test
sg msp pg connect msp-testbed test 
```
With both of the above:
```
primary=> select * from users;
id | created_at | updated_at | …
```

sg: add 'sg msp postgresql connect'

---

dev/managedservicesplatform/terraformcloud/terraformcloud.go
dev/sg/msp/BUILD.bazel
dev/sg/msp/sg_msp.go

Convenience helper for opening workspaces in browser. I'm hoping to expand `sg msp` with more commands to view resources in GCP console and stuff.
```
sg msp tfc view  
sg msp tfc view msp-testbed
sg msp tfc view msp-testbed test
```

sg msp: add 'sg msp tfc view'

---

.github/workflows/pr-auditor.yml
.github/workflows/report-job-failure.yml

Without the repo name the message is a bit vague
[forced a failure in pr-auditor and ran the action manually](https://github.com/sourcegraph/sourcegraph/actions/runs/7287530980/job/19858354317)

sentry action reporter: set the repo name in the event message

---

dev/ci/internal/ci/executor_operations.go

I renamed the script for conditional build, after doing QA, as it's rather inconsequential and made a typo along the way 🙈  
CI + double checked the path

ci: fix a typo in conditional executor rebuild

---

BUILD.bazel
cmd/server/shared/shared.go
dev/check/no-localhost-guard.sh
dev/linters/nolocalhost/BUILD.bazel
dev/linters/nolocalhost/nolocalhost.go
dev/sg/internal/rfc/rfc.go
dev/sg/internal/rfc/rfc_test.go
dev/sg/linters/linters.go
dev/sg/msp/sg_msp.go
dev/sg/sg_embeddings_qa.go
internal/grpc/example/client/main.go
internal/webhooks/outbound/outbound.go

Also fixes all the violations that snuck past due to https://github.com/sourcegraph/sourcegraph/pull/46202 confusingly breaking the `git grep` call :thinking: 
Tested with various combinations of [the following line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/internal/conf/computed.go?L300)

bazel: add no-localhost-guard lint to nogo

---

client/branded/src/search-ui/input/toggles/SmartSearchToggleExtended.tsx

This updates the extended picker to mention the new glob syntax.
Note that this just visible internally. 
Test plan:
- tested locally.

search: mention glob syntax in search mode picker

---

internal/search/query/parser.go
internal/search/query/parser_test.go

Relates to #58815 
This fixes a bug I found during manual testing. We didn't split off the revision before converting glob to regex.
Test plan:
New unit tests

search: don't convert rev to regex for kw search

---

cmd/cody-gateway/internal/actor/actor.go
cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
cmd/cody-gateway/internal/actor/limits.go
cmd/cody-gateway/internal/actor/limits_test.go
cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
cmd/cody-gateway/internal/actor/source.go
cmd/cody-gateway/internal/actor/source_test.go
cmd/cody-gateway/internal/httpapi/featurelimiter/BUILD.bazel
cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
cmd/cody-gateway/internal/httpapi/handler.go
cmd/cody-gateway/shared/main.go

Follow-up on https://github.com/sourcegraph/sourcegraph/pull/58732#discussion_r1414348506 as I was reading the code again this morning after looking at some discussions - this change removes the SyncOnce interface and uses our existing SourceUpdater.
There is some more nuance here than I remember, however: `Actor.Update` is also called when a user hits their rate limit. This could be a good thing (poll for update if a user is rate-limited) - if we increase a user's rate limit it will get updated quickly. Because of the above  if the actor was recently updated we no-op and return an error. This could be useful in the general refresh endpoint use case as well, to avoid something repeatedly hitting dotcom in quick succession.
Updated tests assert same behaviour as existing implementation

cody-gateway: remove SyncOnce, use existing SourceUpdater

---

client/web/src/repo/tree/TreePagePanels.tsx
cmd/cody-gateway/internal/httpapi/featurelimiter/BUILD.bazel

Adds 'ago' back to timestamps in the 'last updated' column of the TreePanel. 
Manual testing/CI passing

Code Navigation: add 'ago' back to timestamps

---

dev/managedservicesplatform/internal/stack/iam/BUILD.bazel
dev/managedservicesplatform/internal/stack/iam/iam.go
dev/managedservicesplatform/spec/service.go

Using service name in the account ID results in IDs that are too long for the operator access SA added in #59105 - this change uses a randomized name with fixed length. This fits the use case as well, since these operator accounts should only be used by MSP tooling.
To prevent future issues, there is now a check restricting the service ID length. We have 1 service exceeding this length - I am working to migrate that first.
n/a

msp: fixed-length operator access account ID, restrict service ID lengths

---

dev/sg/linters/doc_changes.go
doc/cloud/index.md

In https://github.com/sourcegraph/sourcegraph/pull/59114, we started blocking all changes to docs v1.
After discussing with @MaedahBatool @eshamow, we decided to permit changes to Cloud docs until docs v1 can be sunset to avoid showing outdated content to Cloud customers.
CI should pass

ci: permit changes to doc/cloud/*

---

client/web-sveltekit/.prettierignore
client/web-sveltekit/src/lib/dom.ts
client/web-sveltekit/src/lib/wildcard/menu/Menu.svelte
client/web-sveltekit/src/routes/Header.svelte
client/web-sveltekit/src/routes/HeaderNavLink.svelte
client/web-sveltekit/src/routes/UserMenu.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
client/web-sveltekit/src/routes/styles.scss

Closes #59149
This PR adds more entries to the repo nav bar, all leading to the current web app. I basically copied the same list of links we are showing on the repo page in the current app plus some additional entries (Commits and Contributors; I assume those have been removed because the repo page shows/showed a panel for them? idk)
The navbar felt really crowded, so I put the additional items into a menu. This menu will also hold the navbar items if there is not enough space. We need to make a decision about which items we want to show.
I know the "selected entry" style in the menu is not ideal. While I think in general Svelte's way of handling style is better (it prevents issues with style ordering, which we have right now), it also makes it more difficult to build somewhat styleable …

svelte: Add more repo navigation entries and make navigation somewhat response

---

internal/conf/computed.go
internal/conf/computed_test.go

There have been several reports of Azure OpenAI chat requests exceeding the token limit, this lowers the default for Azure and OpenAI GPT-4 to allow for a little more margin of error with token estimation.
unit tests updated

OpenAI: lower max chat token defaults

---

client/web-sveltekit/package.json
client/web-sveltekit/src/lib/search/state.ts
client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/RepoSearchInput.svelte
pnpm-lock.yaml

Closes #59162
This PR adds the search query input to the repo page header. I used a similar solution as GitHub, which renders a button that looks a bit like an input and opens a dialog with the real input.
The input is prepopulated with a `repo:` filter for the current input. It has a tab/focus trap and closes on escape.
Before settling on this solution I tried various other approaches:
- Directly render the input in the header and make it expand on focus. That caused strange text selection because mousdown would expand the input and mouseup would happen at a different place in the input, causing text selection.
- Using the `<dialog>` element. It has some default styles/behavior that interfered with what I wanted to do.
- I wanted to use the newly added `openFocus` option in …

svelte: Add search query input to repo pages

---

client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
cmd/frontend/internal/search/resolvers/BUILD.bazel
cmd/frontend/internal/search/resolvers/search_job.go

This fixes a bug where the search jobs page wouldn't render if a user was missing. The reason was that we returned an error if a user was missing, instead of nil, so we rendered that error instead.
Test plan:
I ran a search job locally, deleted the user afterwards and verified that the page renders as exepected.

search jobs: handle unknown users

---

client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte

I forgot to add that to https://github.com/sourcegraph/sourcegraph/pull/59158 . Right now the selected nav entry doesn't update because `$page.url` is accessed directly in the function and not passed as dependency.
Manual testing

svelte: Fix updating active repo nav entry

---

dev/sg/msp/helpers.go

We generate all stacks to get a list of stacks for which we need TFC workspaces - we need to do this in "stable mode" to avoid image access on subscription types (same thing we do for CI)
n/a

msp: fix tfc workspace sync on services with private images

---

deps.bzl
dev/managedservicesplatform/managedservicesplatform.go
dev/sg/msp/BUILD.bazel
dev/sg/msp/helpers.go
dev/sg/msp/sg_msp.go
go.mod
go.sum

Jump to a tidy view of service logs (assuming `sourcegraph/log`) in browser quickly.
```
sg msp logs sams dev
```

msp: add 'sg msp logs'

---

go.mod
internal/grpc/defaults/BUILD.bazel
internal/grpc/defaults/defaults.go
internal/grpc/defaults/retry.go
internal/grpc/defaults/retry_test.go

This PR adds a basic configuration for enabling retries with gRPC  for certain RPC types. 
The description for `defaults.RetryPolicy` is probably the most important thing to read:
```go
// RetryPolicy is the default retry policy for internal GRPC requests.
//
// The retry policy will trigger on Unavailable and ResourceExhausted status errors, and will retry up to 20 times using an
// exponential backoff policy with a maximum duration of 3s in between retries.
//
// Only Unary (1:1) and ServerStreaming (1:N) requests are retried. All other types of requests will immediately
// return an Unimplemented status error. It's up to the caller to manually retry these requests.
//
// These defaults can be overridden with the following environment variables:
// - SRC_GRPC_RETRY_DELAY_BASE: Base …
```

grpc: create stub retry utilities

---

internal/grpc/retry/BUILD.bazel
internal/grpc/retry/backoff.go
internal/grpc/retry/doc.go
internal/grpc/retry/examples_test.go
internal/grpc/retry/options.go
internal/grpc/retry/retry.go
internal/grpc/retry/retry_test.go

The package has some issues (the retry logic for client stream is flawed). I'm adding a copy of this to our repository for future edits.
See the discussion in https://github.com/sourcegraph/sourcegraph/pull/59145
The existing test suite from the copied project is now running in CI.

grpc: retry: fork retry package grpc: import fork of go-grpc-middlware/retry package

---

internal/grpc/retry/retry.go
internal/grpc/retry/retry_test.go

When retrying a client stream, we must ensure that we haven't received any data from the server yet before retrying. Otherwise, we can't know if the client has already consumed part of the stream. Blindly retrying the stream could produce duplicate messages or inconsistent messages. The only safe generic behavior that we can implement is to only retry if an error occurs _before_ the server successfully sends the first message. After that, any encounters that we see on the stream will be directly returned to the caller - no retries will occur. Only the caller knows the retry semantics that it wants.
This matches the built-in grpc retry behavior (that we can't use, see https://github.com/sourcegraph/sourcegraph/issues/51060) as documented on …

grpc: forked retry package: force streaming retries to fail if we have already recieved a message on the stream

---

dev/managedservicesplatform/internal/stack/options/googleprovider/google.go
dev/managedservicesplatform/internal/stack/stacks.go

Custom TF might depend on this, and it could also make it easier to collect TF outputs for automation, since now every stack with GCP resources will automatically expose the project ID in `locals.project_id`
https://github.com/sourcegraph/managed-services/actions/runs/7302712634

msp: make project_id available in TF variables

---

dev/managedservicesplatform/internal/resource/bigquery/bigquery.go
dev/managedservicesplatform/spec/environment.go

Dashes are not allowed in dataset ID, since we use it in service IDs we cannot use it as-is for dataset IDs. We had a fix for this in Cody Gateway TF but I forgot to port it
https://github.com/sourcegraph/managed-services/commit/c761f01422b7e3b90d2f5a615a904085bd6c0dad fixed my workspace

msp: fixup default bigquery dataset ID

---

internal/grpc/defaults/BUILD.bazel
internal/grpc/defaults/retry.go
internal/grpc/defaults/retry_test.go

This just swaps the grpc/defaults package to use our new internal grpc retries package instead of the [upstream one](https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/retry). 
CI

grpc: defaults: switch defaults package to use custom retry fork

---

internal/grpc/defaults/BUILD.bazel
internal/grpc/defaults/defaults.go
internal/grpc/retry/BUILD.bazel
internal/grpc/retry/examples_test.go
internal/grpc/retry/options.go
internal/grpc/retry/retry.go
internal/grpc/retry/retry_test.go

This tweaks our forked [grpc retry](https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/retry) package to support traces in a similar manner to our internal httpcli logic. 
When reviewing this PR, I'd recommend comparing this against the logic in `internal/httpcli` to see if it's to your liking: https://github.com/sourcegraph/sourcegraph/blob/023e96c2fc25ced65c528be2474b5fd1f9a34792/internal/httpcli/client.go#L582-L631
1. (pre-requisite) I checked out https://github.com/sourcegraph/sourcegraph/pull/59136 (`12-20-grpc_frontend_configuration_support_automatic_retries_GetConfig_is_idempotent_`) that is the PR that has retries hooked up for all services.
2.  In `sg.config.yaml`, I commented out the entry that starts one of the gitserver instances when running `sg start`.
```patch …
```

grpc: retry: add sourcegraph tracing support

---

internal/search/backend/BUILD.bazel
internal/search/backend/retry.go
internal/search/backend/zoekt.go

This PR adds support for automatic retries in the `zoekt-webserver` grpc client that `searcher` uses.
---
I wrapped the basic zoekt-webserver grpc client with an "automaticRetryClient" that uses the default retry policy that was defined in https://github.com/sourcegraph/sourcegraph/pull/59095. See that PR for more details. All the methods don't have any side effects, so they're all capable of being retried. 
Note that for ServerStreaming methods like StreamSearch and List, the retry logic will only automatically retry if we haven't received any messages back from the server yet. 
After we receive a single message, we can't know whether or not the caller has consumed the message yet (e.x: started consuming the search results from `StreamSearch` and displaying them in the WebUI) and can …

grpc: searcher: zoekt-webserver support automatic retries

---

dev/sg/sg_telemetry.go

Show a warning on the telemetry command (for adding to/removing from the `event_logs` exporter that runs in Cloud) that the mechanism is deprecated, and point users towards the appropriate documentation page.
See https://sourcegraph.slack.com/archives/C0EPTDE9L/p1702596065088999 (archive: https://docs.google.com/document/d/1W17w8YSOnW9vZDZfT72zYETjlyMLqCJbQf5WXtmLbrI/edit#heading=h.jydzavzbp1e0)
(copy in screenshot is not final, see diff)

sg telemetry: show deprecation warning

---

dev/managedservicesplatform/internal/stack/project/BUILD.bazel
dev/managedservicesplatform/internal/stack/project/project.go

I forgot to push this change to my previous PR, https://github.com/sourcegraph/sourcegraph/pull/59220
n/a

sg msp: add workaround to retain stable resourceid

---

dev/managedservicesplatform/internal/resource/monitoringalertpolicy/monitoringalertpolicy.go

Quick fix to the redis monitoring
CI
Checked the generated output is updated
Clickops in GCP to see the generated output matches GCP code

msp: fix incorrect redis filter resource descriptor

---

client/web/src/enterprise/codeintel/repo/RepositoryCodeIntelArea.tsx
internal/codeintel/uploads/transport/graphql/root_resolver_coverage.go

[Slack Thread](https://sourcegraph.slack.com/archives/C07KZF47K/p1703102588008859)
* Start your sourcegraph instance with Dotcom configuration. `sg start dotcom`
* Navigate to the code intel dashboard of any repo: `https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/code-graph/dashboard`
* You should get a 404 page.
* Before adding the guard on the client side and added the backend guard.
* With both guards (Client & Backend)

Guard repo code-intel page on Dotcom

---

cmd/frontend/graphqlbackend/rate_limit.go
cmd/frontend/graphqlbackend/rate_limit_test.go
cmd/frontend/internal/httpapi/graphql.go
doc/api/graphql/index.md
internal/conf/computed.go
schema/schema.go
schema/site.schema.json

This will allow us to tweak our GraphQL rate limiting in more detail for overly large queries. We've added more restrictions for duplicate and unique field count. In addition to these restriction we now calculate the query cost before validating the query against the schema. The validation is quit heavy and could still lead to resource exhaustion.
See https://github.com/sourcegraph/security-issues/issues/375 for more context.
Changes: 
- Calculates QueryCost before validating the schema
- Extended QueryCost struct with new metrics
- Updated fragment cost tracking
- Added tracking of duplicate/unique fields
- Updated tests
CI tests, local tests.

Improve GQL ratelimits

---

dev/sg/msp/example/example_test.go
dev/sg/msp/example/job.template.yaml
dev/sg/msp/example/service.template.yaml
dev/sg/msp/sg_msp.go

Fix path generation and arguments from https://github.com/sourcegraph/sourcegraph/pull/59220 for the `sg msp init-env` command.
Also updates the initial example service spec to match the one generated from writing the YAML back to disk - there's not too much control over the indentation offered by the library.
```
sg msp init-env pings dev
```

sg msp: 'init-env' fixes

---

cmd/frontend/auth/BUILD.bazel
cmd/frontend/auth/user.go
internal/security/BUILD.bazel
internal/security/security.go
internal/telemetry/events.go
schema/schema.go
schema/site.schema.json

1. Add logic to auto-disable Google signups from non-Gmail domains during a 24-hour window if too many (> 30) signups from the same domain.
2. Check if is email domain is banned based on SRC_EMAIL_DOMAIN_DENY_LIST for social logins as well. Currently only used for user password signup.
.

Add logic to auto disable google signups from non-gmail domain for 24hrs if too many signups from same domain.

---

client/branded/src/components/Timestamp/Timestamp.test.tsx

Mocks current time for snapshot tests stability.
Reported in [this](https://sourcegraph.slack.com/archives/C07KZF47K/p1704194857934479) Slack thread.
- CI passes

Mock current time for stability

---

client/web/src/notebooks/blocks/file/NotebookFileBlock.tsx
client/web/src/notebooks/blocks/symbol/NotebookSymbolBlock.tsx

The changes to `CodeExcerpt` rendering broke notebooks rendering of code for file blocks and symbol blocks. This fixes the rendering of highlighted code in notebooks by passing in the highlighted code as `highlightedLines` rather than `plaintextLines`.
Fixes https://github.com/sourcegraph/sourcegraph/issues/59252

Notebooks: fix highlighted code

---

dev/nix/nodejs.nix
flake.lock
shell.nix

standard bash is a non-interactive shell meant for a build environment instead of an interactive environment.
Also bumping nixpkgs while we're here
run `bash` in `nix develop`

nix: use interactive bash instead of non-interactive in shell

---

dev/managedservicesplatform/internal/stack/monitoring/monitoring.go

Extracted from https://github.com/sourcegraph/sourcegraph/pull/59257 - I want to fix this first so that when we roll out https://github.com/sourcegraph/sourcegraph/pull/59257, we don't get hit with a swarm of alerts.
tested in https://github.com/sourcegraph/sourcegraph/pull/59257

msp/monitoring: fix redis alert

---

monitoring/monitoring/owners.go
monitoring/monitoring/owners_test.go

Probably good to improve the docstrings here in light of https://sourcegraph.slack.com/archives/C03L2R35ENL/p1704240126855279, since hopefully folks will be reading this.
```sh
go test -run TestOwners github.com/sourcegraph/sourcegraph/monitoring/monitoring -update -online
```

monitoring: improve registerObservableOwner and TestOwner docstrings

---

cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
cmd/frontend/internal/dotcom/productsubscription/licenses_db_test.go

Fixes a panic when rendering a notification introduced in https://github.com/sourcegraph/sourcegraph/pull/59214 when an optional field is referenced. This change dereferences those fields safely as "unknown" and adds a test over zero values of various inputs to do a simple sanity-check that it doesn't blow up.
I also spotted a stray `log.Error` without a logger - fixed that while I was in here.
Unit test panicked without change, no longer panics with change

productsubscription: fix panic on license creation

---

dev/ci/internal/ci/executor_operations.go

Dumb typo I missed before EOY PTO :/ 
CI + double checked

ci: fix typo in executor op

---

docker-images/syntax-highlighter/Cargo.Bazel.lock
docker-images/syntax-highlighter/Cargo.lock
docker-images/syntax-highlighter/Cargo.toml

Originally had to pin to an older serde version due to https://stackoverflow.com/questions/76905691/bazel-unable-to-build-external-rust-dependency-with-feature-serde1, but according to [this comment](https://github.com/bazelbuild/rules_rust/issues/2071#issuecomment-1686022916), this issue is resolved in newer released versions now
`bazel build //docker-images/syntax-highlighter:scip-ctags` works

syntax-highlighter: bump serde to version that works with bazel

---

cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
cmd/frontend/internal/dotcom/productsubscription/licenses_db_test.go

Previously this test depended on `time.Until` - instead, we inject a stable `time.Time` as `now` and evaluate the difference based on that.
Autogold assertion shows the expected time diff (3 days) - this should be stable now

productsubscription: stabilize license notification test

---

cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
cmd/frontend/internal/dotcom/productsubscription/subscriptions_db.go

The error returned from the security event log was not handled appropriately in a few places. this PR fixes those issues.
Thanks to @bobheadxi for catching this.
Locally tested

fixing error handling

---

internal/gitserver/client.go
internal/gitserver/commands.go

Previously, the doc comment referred to a non-existent `maxBytes` parameter.
In the modified `commands.go`, you can see these two lines:
```
r := io.Reader(br)
data, err := io.ReadAll(r)
```
slightly below the modified doc comment, indicating that the full contents are read.
n/a

gitserver: Update out-of-date doc comment for ReadFile

---

cmd/frontend/graphqlbackend/git_tree_entry.go

It's not a lockfile, so it usually doesn't grow large enough to cause trouble for syntax highlighting
This was ignored for syntax highlighting in #59010, but I think `package.json` was included by accident.
Tested locally
`sg start` -> search for `package.json` -> see highlighted file

Syntax highlight package.json files

---

cmd/frontend/internal/dotcom/productsubscription/license_anomaly.go
cmd/frontend/internal/dotcom/productsubscription/license_anomaly_test.go
cmd/frontend/internal/dotcom/productsubscription/license_check_handler.go
cmd/frontend/internal/dotcom/productsubscription/license_check_handler_test.go
cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
cmd/frontend/internal/dotcom/productsubscription/licenses_db_test.go
cmd/frontend/internal/dotcom/productsubscription/subscriptions_db.go
internal/types/types.go

This PR reworks the way we do our license checks a bit with the following goals:
- Have license checks be less noisy
- Ensure license alerts are actionable
Originally, once a site ID was assigned to a license key, it would be permanently assigned and any pings from a new license key would trigger alerts. However, there are valid reasons under which a customer's site ID could change, such as them redeploying Sourcegraph.
In cases where customers are using the same license key on their dev and prod instances, the only way to fix this would be for someone to issue **two** new license keys for the customer: one for each instance. This is because the license key would be claimed by the dev instance, and then be rendered useless to any other instance without some SQL magic.
**AFTER THIS PR**
We …

Adjust license anomalies checks

---

client/web-sveltekit/src/lib/search/results.ts
client/web-sveltekit/src/routes/search/RepoSearchResult.svelte

We already had metadata badges. This just adds additional badges for topics to match the behavior of the react webapp. I think we can upgrade repo metadata out of experimental as well and show it by default, but I'll do that in a followup PR.
Manually tested that the links work as expected.

Svelte: add topic badges to repo search results

---

cmd/searcher/internal/search/hybrid_test.go
cmd/searcher/internal/search/matcher.go
cmd/searcher/internal/search/search.go
cmd/searcher/internal/search/search_regex.go
cmd/searcher/internal/search/search_regex_test.go
cmd/searcher/internal/search/search_structural.go
cmd/searcher/internal/search/search_test.go

This refactors the searcher logic to handle negated patterns within `matcher`, instead of the main file processing loop. This will be really helpful when adding support for 'and' and 'or' matchers to searcher, since now negation is handled at the level of a query atom.
The refactor uncovered two bugs in the negation logic, which are now fixed:
* When the pattern was negated, in some cases we ignored file include/ exclude patterns
* Hybrid search was totally ignoring pattern negation
Relates to #59038
New unit tests to cover the bug fixes

Searcher: fix issues with negated patterns

---

cmd/pings/service/BUILD.bazel
cmd/pings/service/service.go
deps.bzl
go.mod
go.sum
lib/managedservicesplatform/go.mod
lib/managedservicesplatform/go.sum
lib/managedservicesplatform/runtime/BUILD.bazel
lib/managedservicesplatform/runtime/service.go

[It's free](https://cloud.google.com/stackdriver/pricing#profiler-costs) and useful when problems arise. In MSP services alone we've used this twice already (`pings` and `cloud-ops`).
The prerequisite infra (API and IAM access) is already provisioned.
n/a, this is more or less the same setup as in pings

msp/runtime: always enable Cloud Profiler

---

dev/managedservicesplatform/googlesecretsmanager/googlesecretsmanager.go
dev/managedservicesplatform/internal/resource/cloudflareorigincert/cloudflareorigincert.go
dev/managedservicesplatform/internal/stack/BUILD.bazel
dev/managedservicesplatform/internal/stack/cloudrun/cloudrun.go
dev/managedservicesplatform/internal/stack/monitoring/monitoring.go
dev/managedservicesplatform/internal/stack/options/googleprovider/google.go
dev/managedservicesplatform/internal/stack/project/project.go
dev/managedservicesplatform/internal/stack/stacks.go
dev/managedservicesplatform/internal/stack/tfcworkspaces/tfcworkspaces.go
dev/sg/msp/helpers.go
dev/sg/msp/sg_msp.go

Right now, commands like `sg msp db connect` need to access TFC workspace outputs. This is clunky because it requires another Entitle roundtrip to get credentials and access to TFC.
Now that we configure project ID up-front, `sg msp` can just reach out to the service environment's project ID for secrets - by adding all local variables/TF outputs to GSM as well, we can now get access to everything with just one Entitle request on the environment project or folder.
This change only emits StackLocals as GSM secrets - I'll make the actual tooling changes in a follow-up.

msp: emit StackLocals as GSM secrets

---

cmd/frontend/internal/dotcom/productsubscription/tokens_db.go
cmd/frontend/internal/dotcom/productsubscription/tokens_db_test.go
internal/database/access_tokens.go
internal/database/access_tokens_test.go

It appears that we update a token's `last_used_at` value every time `AccessTokenStore.Lookup` is called. However, this causes far more writes than are useful.
This PR updates `Lookup()` to just have a read-only query, and only update the token's `last_used_at` if it is been greater than five minutes. The tradeoff being the common case of token access will be much faster, but once every five minutes -- or first lookup in a while -- will require 2x database queries. And moving forward the `last_used_at` value may be up to 5m stale.
Added unit tests for the new functionality.

Allow last_used_at to be semi-stale

---

client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.tsx

- Changed the "Code" icon to curly braces so we didn't have so many vaguely-rectangular icons
- Changed the "Repositories" icon to a fork icon because the normal "Source Repository" icon stands out much more than the other icons and it looked out of place. 
- Changed the "Symbols" icon to the function icon, which is widely used to represent generic "symbols" elsewhere.
Before:
After:
See screenshots. We'll let design have a pass at this too once Taiyab is back.

Filters panel: refine type icons

---

dev/managedservicesplatform/internal/resource/bigquery/bigquery.go
dev/managedservicesplatform/managedservicesplatform.go
dev/managedservicesplatform/operationdocs/BUILD.bazel
dev/managedservicesplatform/operationdocs/internal/markdown/BUILD.bazel
dev/managedservicesplatform/operationdocs/internal/markdown/inline.go
dev/managedservicesplatform/operationdocs/internal/markdown/inline_test.go
dev/managedservicesplatform/operationdocs/internal/markdown/markdown.go
dev/managedservicesplatform/operationdocs/links.go
dev/managedservicesplatform/operationdocs/operationdocs.go
dev/managedservicesplatform/operationdocs/operationdocs_test.go
dev/managedservicesplatform/operationdocs/testdata/TestRender/basic.golden
dev/managedservicesplatform/operationdocs/testdata/TestRender/resources.golden
dev/managedservicesplatform/spec/environment.go
dev/managedservicesplatform/spec/service.go
dev/managedservicesplatform/spec/spec.go
dev/managedservicesplatform/stacks/cloudrun/internal/builder/job/job.go
dev/managedservicesplatform/stacks/iam/iam.go
dev/managedservicesplatform/stacks/monitoring/monitoring.go
dev/sg/msp/BUILD.bazel
dev/sg/msp/sg_msp.go
go.mod

This is a start to https://github.com/sourcegraph/managed-services/issues/328 and not meant to be complete - it creates some Markdown that can be read in terminal for now. Eventually we may want to persist this somewhere.
Aiming to land this roughly as-is since this is a large initial diff with a lot of copy-pasta from `sourcegraph/controller`.
```
sg msp operations sams
```

sg/msp: add prototype 'sg msp docs'

---

doc/admin/observability/alerts.md
doc/admin/observability/dashboards.md
monitoring/definitions/frontend.go
monitoring/monitoring/monitoring.go

Spotted this alert the other day, we have dedicated fields for extended descriptions, and some parts (like "5s") is redundant because the alerting rules already provide that in the template message
n/a
[Preview Link](https://docs.sourcegraph.com/@remove-paragraph-description)

monitoring: remove very long description

---

client/web/src/enterprise/codeintel/dashboard/components/BrainDot.module.scss
client/web/src/enterprise/codeintel/dashboard/components/BrainDot.tsx
client/web/src/repo/RepoHeader.tsx

I did a bunch of testing on S2 and Dotcom, and I noticed several bugs introduced by #58122 - this PR takes an attempt to fix them.
The lack of a `max-height` attribute on the container for the context menu causes the list to grow abnormally long. 
Also, in a case where there are no items in the context menu (e.g the revision comparison page), the context menu renders nothing - we should hide it in this case instead of showing an empty context menu.
Navigating to a repository root page that has been indexed and contains a lot of visible indexes, the context menu shouldn't be abnormally long.
The radio button for indices shouldn't be hidden when the context menu is open.

code-search: fix for regression introduced by actions discoverability

---

cmd/cody-gateway/internal/events/events.go
cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
cmd/cody-gateway/internal/httpapi/completions/anthropic.go
cmd/cody-gateway/internal/httpapi/completions/anthropic_test.go
cmd/cody-gateway/internal/httpapi/completions/fireworks.go
cmd/cody-gateway/internal/httpapi/completions/openai.go
cmd/cody-gateway/internal/httpapi/completions/upstream.go

Use explicit interfaces instead of a struct with inline methods to improve type safety - [context](https://sourcegraph.slack.com/archives/C05497E9MDW/p1702048403168149). 
- all existing tests pass

Use interfaces instead of using structs with methods

---

client/shared/src/search/query/decoratedToken.test.ts
client/shared/src/search/query/scanner.test.ts
client/shared/src/search/query/scanner.ts

Relates to: #58815 
This PR fixes a bug in keyword search, where 'OR', 'AND', and 'NOT' were highlighted within quoted patterns, such as `"foo and bar"`. In keyword search, however, we want to treat quoted patterns as literals and the operators shouldn't be highlighted.
before:
after:
Test plan:
new unit tests

search: don't highlight operators inside "..."

---

cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
cmd/cody-gateway/internal/httpapi/completions/fireworks.go
cmd/cody-gateway/internal/httpapi/completions/fireworks_test.go
cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go

Extract token counts from streaming Fireworks requests - [context](https://sourcegraph.slack.com/archives/C060RPB9H1T/p1704283962290259?thread_ts=1704213101.928429&cid=C060RPB9H1T). 
Non-streaming requests already set token counts correctly.
Closes https://github.com/sourcegraph/sourcegraph/issues/56704
- unit tests added

Extract token count from streaming Fireworks requests

---

cmd/frontend/internal/context/resolvers/context_test.go
internal/codycontext/context.go

Currently when embeddings are disabled the unified cody context will continue to try to use embeddings because they were previously generated.  This results in errors for each repo, stating that embeddings are disabled.
This updates the repo partitioning to only use search if embeddings are disabled. 
Disabled embeddings
Used cody web client - verified additional context added to the request

Update unified cody context to only use search when embeddings are disabled

---

client/wildcard/src/global-styles/code.scss

e9b0ce5c3d42 changed the styles of the `<kbd>` tag. Presumably the assumption was that content of this tag will always be a single character, but that's not the case. It's used in various places and the content can differ between platforms.
This PR reverts this particular change.
Before: 
After: 
Looked at various places where we use this tag, e.g. search input suggestions.

web: Revert <kbd> tag styling

---

docker-images/syntax-highlighter/crates/scip-syntax/docs/locals-query-dsl.md
docker-images/syntax-highlighter/crates/scip-syntax/queries/go/scip-locals.scm
docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs

This shows up in the Java queries, where we're not just skipping definition matches, but also reference ones.
See https://github.com/sourcegraph/sourcegraph/pull/59376#discussion_r1444434483
Check that none of the snapshots changed as a result of this PR

Update locals DSL to @occurrences.skip for skipping defs and refs

---

docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs

While this signifies a programming error, it's not a valid reason to crash the program at runtime. Sorry I missed this one earlier. There are now no `assert!` macros left in here.
Tests run succesfully in CI

Uses a debug_assert over assert for non-critical locals error

---

cmd/frontend/internal/search/search.go
internal/search/streaming/search_filters.go

This modifies the search streaming code to only send filters when they've changed (plus a final flush at the end of the search just in case). Previously, we would send every filter on every flush tick, which is once ever 100ms. For a 10 second search, this comes out to 100 filters events. After this change, the same search only sends 4 filters events.
This makes debugging easier (fewer events to sift through) and improves performance (only need to compute/parse/send/render the filters a few times).
@fkling [pointed this out](https://sourcegraph.slack.com/archives/C05R619V4F8/p1702635431363339) a while ago, and I was working in this code today, so I went ahead and fixed it while I was here.
Tested a few searches and ensured that the filters events that come through are all unique and …

Streaming search: only flush filters when dirty

---

wolfi-packages/p4-fusion.yaml

Occasionally hashes for p4-fusion images can change, even when there's no
version change. This bumps the hash for the API dependency to match the
latest.
Covered by CI

Build: bump hash for perforce API

---

client/web/src/site-admin/SiteAdminTokensPage.tsx
client/web/src/user/settings/accessTokens/UserSettingsTokensPage.tsx

The previous logic didn't account for the allow-site-admin state so we never displayed the button in that case. This PR fixes that.
I want to reconsider these three options in the future and see if we couldn't replace it with RBAC instead, but for now this seems like the most straightforward way to improvement.
Manually tested all the states.

Fix logic for when to show add access token button

---

cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
cmd/cody-gateway/internal/httpapi/completions/fireworks_test.go
cmd/cody-gateway/internal/httpapi/completions/openai.go
cmd/cody-gateway/internal/httpapi/completions/openai_test.go

OpenAI has enabled usage data on streaming requests for our org, this extracts the usage data.
closes https://github.com/sourcegraph/sourcegraph/issues/59297
Unit test added
Manual testing running gateway.

Extract token count from streaming OpenAI responses

---

client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/search-query-checks/SearchQueryChecks.tsx
client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.test.ts
client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.ts

Based on this slack thread https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1704741483847149
**TL;DR** 
We basically don't want to restrict multi line query in the capture group insight query field since we don't have restriction about capture group being single-line anymore. 
- Check multi-line capture group query passes client validation in the creation UI form

Code Insights: Remove no new line check from capture group insight

---

cmd/frontend/graphqlbackend/schema.graphql
cmd/frontend/graphqlbackend/site.go
internal/conf/computed.go
internal/conf/computed_test.go
internal/conf/conftypes/consts.go
schema/schema.go
schema/site.schema.json

Main Issue https://github.com/sourcegraph/sourcegraph/issues/58631
Related PR https://github.com/sourcegraph/dev-private/pull/82
Run in Dev mode and test the GQL by tweaking the site admin config.

Adding Config options for Siteadmins to configure whether clients can use Chat/autocomplete/commands

---

client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx

Just a small change to make the search functionality in the filters panel case-insensitive.
Manually tested that case-insensitive search works for languages and repos

Filters panel: make search case-insensitive

---

doc/admin/observability/alerts.md
doc/admin/observability/dashboards.md
monitoring/definitions/frontend.go

The >5s blobstore latency alert triggers _very_ eagerly, and it's also self-resolving. I don't think the current threshold works very well as an alert system, as it turns into a boy-who-cried-wolf scenario.
This PR requires that the blobstore latency be >5s for 10 minutes before an alert is triggered.
Alert update

Adjust blobstore latency alert

---

shell.nix

Due to a newly enabled (in bazel 7) `--incompatible_sandbox_hermetic_tmp`, and nix setting TMP/TMPDIR to something below /tmp, we encounter https://github.com/bazelbuild/bazel/issues/5900
`nix develop --command bazel build //dev/sg` is successfull

nix: unset TMP and TMPDIR for bazel

---

dev/sg/dependencies/mac.go
dev/sg/dependencies/ubuntu.go

On older versions like 2.39.2, the no-locahost-guard script would incorrectly report false positives.
Note: https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.39.3.txt specifically fixes the issue with the script. 
locally testd

sg: bump git version requirement

---

client/web/src/cody/components/GettingStarted.tsx
client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
client/web/src/cody/components/ScopeSelector/backend.ts
client/web/src/cody/components/ScopeSelector/useRepoSuggestions.ts

Removes icon indicators and warnings from Cody web chat regarding presence or absence for embeddings. 
This also removes the repo status polling because there is no longer a status change. 
part of https://github.com/sourcegraph/sourcegraph/issues/59309
Opened webclient, selected repos ensured context was requested from those repos.
before 
after

Remove embeddings indicators from cody web chat

---

cmd/frontend/graphqlbackend/git_commit.go
cmd/frontend/graphqlbackend/perforce_changelist.go
cmd/frontend/graphqlbackend/repository.go
cmd/frontend/graphqlbackend/repository_test.go
cmd/frontend/graphqlbackend/search_results.go
cmd/frontend/graphqlbackend/symbols.go
cmd/frontend/internal/compute/resolvers/resolvers.go
internal/cmd/search-blitz/search.graphql

For reasons I don't fully understand even though it's probably my doing, `RepositoryResolver` depends on the search result type `RepoMatch`. There was some really convoluted logic about how only the `name` and `id` fields of `RepoMatch` were set, which is particularly confusing because a `RepoMatch` isn't even required to construct the `RepositoryResolver`. The only information being provided by `RepoMatch` was `rev`, which it really shouldn't be since a repository domain object should not even have a rev (that should be relegated to the `GitCommitResolver` or `GitRefResolver`, which contain a `RepositoryResolver`). 
Anyways, this removes the dependency on the search result type.
CI.

Chore: clean up `RepositoryResolver`

---

client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/search-query-checks/SearchQueryChecks.tsx
client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.test.ts
client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.ts

Based on this slack thread https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1704741483847149
**TL;DR** 
We basically don't want to restrict multi line query in the capture group insight query field since we don't have restriction about capture group being single-line anymore. 
- Check multi-line capture group query passes client validation in the creation UI form
Backport [af1c6ce](https://github.com/sourcegraph/sourcegraph/commit/af1c6ceb9167f31771f562f60097eca7e9a4b830) from https://github.com/sourcegraph/sourcegraph/pull/59395

[Backport 5.2] Code Insights: Remove no new line check from capture group insight

---

internal/version/version.go
internal/version/version_test.go

We were initially about to move some constants from `internal/database/migration/shared/data/cmd/generator/consts.go` so we can group all constants that needs to be stamped on a release in the same place, but decided to go against it, as it would trigger rebuilding targets that depends on `internal/version`. 
Still found out a small chore along the way, so here it is. 
CI

chore: unexport version.MockTimestamp as it's only used in tests

---

cmd/frontend/internal/app/resolvers/app.go
cmd/frontend/internal/embeddings/resolvers/resolvers.go
enterprise/cmd/worker/internal/embeddings/repo/scheduler.go
internal/embeddings/background/repo/types.go
internal/embeddings/schedule.go
internal/embeddings/schedule_test.go

This PR backports a fix to embeddings, plus an earlier refactor that it's based on:
* https://github.com/sourcegraph/sourcegraph/pull/58980
* https://github.com/sourcegraph/sourcegraph/pull/58787
Modified unit tests

[Backport 5.2] Embeddings: avoid constantly rerunning job if it failed

---

internal/search/streaming/search_filters.go

This just fixes the string label for commit date filters. It didn't match what we expected in the client, so that panel wasn't showing.
Quick manual test

Filters panel: fix label for commit dates

---

internal/search/streaming/search_filters.go

There seem to be situations where we get back symbols with kinds that are not enumerated by our symbol kinds list. I'm not sure where these come from yet, but in any case, it's not possible to run a query to search for only that kind of symbol, so I skip them for the purpose of calculating filter groups.
Manual test that seasrch which previously returned an empty symbol kind now doesn't.

Filters panel: skip unknown symbol kinds

---

cmd/executor/_binary.push.sh

Just noticed I had my "test/dev" branch/branch for releases here that was dropping many binaries from `main` here https://buildkite.com/sourcegraph/sourcegraph/builds/257179#018cef14-5cbf-4c4c-837b-008fa62e6660/27-4550 
This adds a failsafe so we don't accidentaly reproduce the same mistake. 
CI

ci: avoid dropping ALL executors binary if BUILDKITE_TAG is empty

---

client/common/BUILD.bazel
client/common/src/util/deviceDetection.ts
client/common/src/util/index.ts
client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx

Closes [#361](https://github.com/sourcegraph/security-issues/issues/361)
Details in the above issue.
I followed the recommendation from the issue I've attached.
I tested it on an Android device. The `Authorize` button is disabled.

token: disable Authorize button on mobile device

---

internal/search/streaming/BUILD.bazel
internal/search/streaming/search_filters.go
internal/search/streaming/search_filters_test.go

The label for symbol kind is being returned from the backend as all lower-case. This title-cases the label. We could do this in the client too, but IMO labels should be returned from the API as "intended-case".
Before:
After:
Manual. See screenshots

Filters panel: title-case symbol kind

---

client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx

This updates the filters panel to show only the `org/name` from the repo, removing the code host from the text by default and replacing it with a representative icon if it is a known codehost. Additionally, it adds a hover tooltip that shows the full repo name (including code host) so that a user can still see what repo it is even if it's a long repo name. 
In an ideal world, we would fetch the code host kind from the backend and use that to render the icon. However, it's non-trivial to add followup requests and caching here, so I'm just copying what we do elsewhere in the UI. So this [only renders special icons](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6b1979f7b6267b67d72a744ca8048bdc06e1c3e3/-/blob/client/branded/src/search-ui/components/CodeHostIcon.tsx?L8-10) for …

Filters: update repo rendering

---

dev/pr-auditor/check-pr.sh
dev/pr-auditor/check.go
dev/pr-auditor/check_test.go
dev/pr-auditor/issue.go
dev/pr-auditor/issue_test.go
dev/pr-auditor/main.go

Adds two new environment variables to the pr-auditor workflow that allow opting out of test plans or review requirements at a repo level. Flips some of the polarities of flags so that the zero-value of options structs are the defaults.
Includes unit tests and github actions will be manually tested

Allow repo wide pr-auditor opt-out of test plans and reviews

---

client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx

In my last PR, there was an issue with rendering non-standard code host icons. This fixes that.
See screenshot.

Filters: fix icon for nonstandard codehosts

---

internal/search/streaming/search_filters.go

Values for before/after were reading as search terms instead of as values for before and after filters.
Used to be: `after:1 week ago`
Now is: `before:"1 week ago"`
Otherwise, we would be returning results for 'week ago'.
CI/CD

New Filters Panel: encase before/after values in double quotes where necessary

---

deps.bzl
go.mod
go.sum

This bump only includes one commit from zoekt which is a performance fix. See the commit in the zoekt repo for details.
- https://github.com/sourcegraph/zoekt/commit/7487a0d53131a188fcf769ed64ceee07f8acdfd2 chunkmatches: reuse last calculated column when filling
Test Plan: tested in zoekt repo and this CI

gomod: update zoekt to include chunkmatch perf fix

---

dev/ci/semgrep-scan.sh

This PR attempts to add non-blocking error handling for semgrep findings. Semgrep binary returns 1 for high severity issue report and then fails the buildkite job. Rather than blocking CI, code scanning feature will automatically block for high severity issues. (Currently disabled but can be enabled from `code scanning` settings.

Add non-blocking error handling for semgrep findings

---

client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss
client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.module.scss

Before, when dark mode is enabled, filters in the new filters panel had no hover behavior. Now, the background changes when the user hovers over individual filters in both light, and dark mode. 
CI/CD & manual/visual testing

New Filters Panel: change background on hover

---

client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx

Before, filters with many results would show either all, or no filters. Now, the `show more [filter]s` button adds 5 at a time until `allFiltersAreDisplayed`, at which point the button will change to a `Show less [filter]s`, collapsing back to 5 when clicked. 
https://github.com/sourcegraph/sourcegraph/assets/62355966/5a2cce74-1707-470d-b171-006cddaee081
CI/CD should be enough.

New Filters Panel: replace 'show all' logic with 'show more/less' logic

---

dev/managedservicesplatform/spec/environment.go
dev/managedservicesplatform/terraformcloud/terraformcloud.go
dev/sg/msp/helpers.go

Adds `allowDestroys` checks to:
1. Workspaces via `AllowDestroyPlan`
2. `sg msp tfc sync -delete`
n/a

sg msp: expand destroy protection to more features

---

WORKSPACE

Not relevant outside of nixos users, zig-cc only used for darwin cross-compile or nixos users

nixos: add zig-cc platform sha for nixos

---

CHANGELOG.md

This PR adds entries for these changes related to the search backend:
* https://github.com/sourcegraph/sourcegraph/pull/58651
* https://github.com/sourcegraph/sourcegraph/pull/58866
* https://github.com/sourcegraph/sourcegraph/pull/58869
* https://github.com/sourcegraph/sourcegraph/pull/58980
Docs-only change

Search: add missing changelog entries for 5.2

---

internal/grpc/retry/options.go
internal/grpc/retry/retry.go

```
callOpts := reuseOrNewWithCallOptions(intOpts, retryOpts) // callOpts are recycled here if no call opts given
doTrace := makeTracingCallback(parentCtx, logger, service, method)
originalCallback := callOpts.onRetryCallback
callOpts.onRetryCallback = func(ctx context.Context, attempt uint, err error) { // and is overwritten here, potentially by multiple callers at the same time.
doTrace(attempt, err)
if originalCallback != nil {
originalCallback(ctx, attempt, err)
}
}
```
`go test ./cmd/gitserver/internal/integration_tests -race -count=5` consistently fails before this change on branch `es/grpc-cleanup` where we switched the integration test suite from HTTP to gRPC (the default option). With this patch applied, it no longer fails.

Fix data access race condition in gRPC retry logic

---

deps.bzl
go.mod
go.sum

Has been merged, no longer needed.
CI, the new exposed constructor will cause a build failure if we didn't get the right version.

go: Remove override for go-tiktoken

---

internal/grpc/retry/retry_test.go

During https://github.com/sourcegraph/sourcegraph/pull/59487, we discovered that the existing test suite for the retry package doesn't execute any requests in parallel due to https://github.com/stretchr/testify/issues/187. 
This PR explicit adds some basic tests that execute Unary / Streaming requests to see if they trip the race detector.
CI
I also opened this example PR to show how these tests would catch the issue in https://github.com/sourcegraph/sourcegraph/pull/59487: https://github.com/sourcegraph/sourcegraph/pull/59491

grpc: retry: add test that exectures parallel requests

---

internal/database/teams.go
internal/database/teams_test.go

While fetching members of a team, we currently don't check if the user is deleted which leads to an error on S2 when fetching the member's information.
```graphql
query ListTeamMembers($first: Int, $after: String, $search: String, $teamName: String!) {
team(name: $teamName) {
id
members(first: $first, after: $after, search: $search) {
totalCount
pageInfo {
endCursor
hasNextPage
}
nodes {
...ListTeamMemberFields
}
}
}
}
fragment ListTeamMemberFields on TeamMember {
__typename
... on User {
__typename
id
url
username
displayName
avatarURL
}
}
```
* Navigate to S2
* Access the [`everyone` team on S2](https://sourcegraph.sourcegraph.com/teams/everyone/members)
* You should see the list of team members instead of the current error page on S2.

handle deleted users when listing team members

---

doc/admin/observability/alerts.md
monitoring/definitions/shared/dbconns.go

https://github.com/sourcegraph/sourcegraph/pull/59284 dramatically reduced the `mean_blocked_seconds_per_conn_request` issues we've been seeing, but overall delays are still higher, even with generally healthy Cloud SQL resource utilization.
Spot-checking the spikes in load in Cloud SQL, it seems that there is a variety of causes for each spike (analytics workloads, Cody Gateway syncs, code intel workloads, gitserver things, `ListSourcegraphDotComIndexableRepos` etc) so I'm chalking this up to "expected". Since this alert is seen firing on a Cloud instance, let's just relax it for now so that it only fires a critical alert on very significant delays.
n/a
[Preview Link](https://docs.sourcegraph.com/@increase-blocked-seconds-per-con-alert)

monitoring: relax mean_blocked_seconds_per_conn_request alerts

---

internal/database/dbconn/open.go

We sometimes pass huge data here, and this can cause a very large attribute to be rendered. This PR limits it to at most 128 characters, which was chosen arbitrarily.
Verified with go playground that this syntax works.

otel: Log at most 128 characters for generic pq Arrays

---

internal/highlight/language.go

Locally tested with the following patch:
```patch
diff --git a/client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts b/client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts
index 7c45907c51..84c9594549 100644
--- a/client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts
+++ b/client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts
@@ -141,6 +141,7 @@ export async function searchBasedReferences({
occurrence.symbol?.startsWith('local ') &&
occurrence.range.contains(new ScipPosition(position.line, position.character))
) {
+                debugger;
return occurrences
.filter(reference => reference.symbol === occurrence.symbol)
.map(reference => ({
```
Steps:
1. Open a Go file in the sourcegraph/sourcegraph repo
2. Hover over a local variable
3. a) Before this …

Enables tree-sitter based locals references for Go

---

cmd/worker/internal/search/exhaustive_search_repo_revision.go
cmd/worker/internal/search/exhaustive_search_test.go
internal/search/exhaustive/service/matchcsv.go
internal/search/exhaustive/service/search.go
internal/search/exhaustive/service/search_test.go
internal/search/exhaustive/service/searcher.go
internal/search/exhaustive/service/searcher_test.go

Relates to #59329 
This is mostly a refactor to prepare for a JSON writer that replaces our CSV writer.
The high-level plan is to switch the internal (object storage) AND the external (download) format from CSV to JSON.
Test plan:
- CI
- Note: I had to update `SearcherFake`, hence some of the test data changed. It only affects a few tests and the character of the tests remains the same.

search jobs: refactor SearchQuery interface

---

internal/completions/httpapi/codecompletion.go

This feature flag was only used while we were evaluating the single tenant instance. 
Going forward, we will add support for Cody Gateway to resolve the virtual model strings, but for now we translate to our current MT defaults.
- Trivial change, CI will test

Remove no longer used cody-autocomplete-default-starcoder-hybrid-sourcegraph feature flag

---

cmd/cody-gateway/internal/httpapi/completions/upstream.go

Flush streaming responses for chat, not only code completions.
- tested locally (events are returned immediately, without buffering)

Flush chat responses

---

cmd/frontend/internal/search/BUILD.bazel
cmd/frontend/internal/search/search.go
internal/search/alert.go
internal/search/job/jobutil/job.go
internal/search/job/jobutil/job_test.go
internal/search/query/types.go
internal/search/searcher/symbol_search_job.go

The search planning code uses the same `TextPatternInfo` struct for unindexed
search, structural search, and symbol search. However, most of the parameters
don't make sense for symbol search. This PR pulls out a dedicated
`SymbolSearchRequest` struct for symbol search to use instead.
This uncovered an error with symbol search where negation was allowed, but gave
the wrong results. With this change, we just return an error.
Relates to https://github.com/sourcegraph/sourcegraph/issues/59038
Existing tests for symbol search, as well as manual testing

Symbol search: clean up job logic

---

dev/managedservicesplatform/internal/resource/cloudflare/cloudflare.go
dev/managedservicesplatform/operationdocs/operationdocs.go
dev/managedservicesplatform/spec/environment.go
dev/managedservicesplatform/stacks/cloudrun/internal/builder/service/service.go

For most use cases, services should be behind the default Cloudflare proxy. Addresses https://github.com/sourcegraph/managed-services/pull/334#discussion_r1446496498
The only services that should not be proxied, pings and telemetry-gateway, both specify `proxied: false` explicitly already (these services should have static IPs available)
https://github.com/sourcegraph/managed-services/actions/runs/7482506337

msp/cloudflare: proxy by default

---

.aspect/workflows/config.yaml
dev/ci/internal/ci/bazel_operations.go

Renamed this job when we got rid of HTTP because that's the only version we need to run now.
CI will fail if the new name is still wrong.

Fix bazel config for backend integration tests

---

client/web/src/open-in-editor/OpenInEditorActionItem.module.scss
client/web/src/opencodegraph/global/ToggleOpenCodeGraphVisibility.module.scss
client/web/src/opencodegraph/global/ToggleOpenCodeGraphVisibility.tsx
client/web/src/repo/actions/GoToCodeHostAction.tsx

[Thread](https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1704903083081249)
This fixes the color mismatch in the repo actions navbar.
Navigate to a file view `/github.com/sourcegraph/code-intel-extensions@525da1bc7a1dd5c068091f881c38b6b8210d3351/-/blob/schema/schema.graphql`

fix code actions color mismatch

---

dev/managedservicesplatform/operationdocs/operationdocs.go
dev/managedservicesplatform/operationdocs/testdata/TestRender/basic.golden
dev/managedservicesplatform/operationdocs/testdata/TestRender/resources.golden

Makes some additions to the docs aimed at clarifying [some confusion we saw recently](https://sourcegraph.slack.com/archives/C05GJPTSZCZ/p1704979291858529?thread_ts=1704733470.477189&cid=C05GJPTSZCZ), where it might not be immediately obvious where to go to find your service for those who are unfamiliar.
Golden tests

msp/operationdocs: talk more about TFC and Cloud Run

---

dev/managedservicesplatform/operationdocs/index.go
dev/managedservicesplatform/operationdocs/testdata/TestRenderIndexPage.golden

🤦
While here, I also fixed up some of the wording. 
n/a

msp/operationdocs: fix typo

---

internal/database/dbconn/open.go

This reverts commit 24fc9f5923328233c3257e72b10f74fb7682d658.
It doesn't have the intended effect on []int, and instead prints even longer values. 
CI.

otel: Only log type for unknown arguments in sql

---

client/web/src/repo/blob/codemirror/search.tsx

Fixes #57897 
This adds an effect on `findNext` that scrolls the newly-selected item into the middle third of the view rather than just scrolling the minimum amount for it to show up in the view. If it is already visible in the view, no scrolling happens.
https://github.com/sourcegraph/sourcegraph/assets/12631702/121ec818-4eb4-4dd9-9351-c36c375d253b
Manually tested that the scrolling feels right.

Blob view: scroll search results to center of view

---

cmd/frontend/graphqlbackend/site.go

While working on support for StarCoder for Enterprise I noticed the GQL API was reporting the wrong model. This was probably a typo.
- Setting a custom completions model works as expected

Expose the right model name when querying the completions model via GQL

---

dev/managedservicesplatform/spec/spec.go
dev/sg/msp/helpers.go
dev/sg/msp/sg_msp.go

Addresses some feedback from [this thread](https://sourcegraph.slack.com/archives/C05GJPTSZCZ/p1705074439174099):
1. `init-env` might be easily confused for `init`, this change adds an up-front check that all arguments are present and returns an error message suggesting `init` just in case you haven't created a service yet
2. If a service spec can't be opened, we now return an error message `service does not exist`
3. All callsites of `spec.Open` now wrap the error with the ID of the service they are expecting to open
```
$ sg msp init-env dev               
❌ exactly 2 arguments required, '<service ID>' and '<env ID>' -  this command is for adding an environment to an existing service, did you mean to use 'sg msp init' instead?
$ sg msp init-env asdfasdf dev
❌ load service "asdfasdf": …
```

sg msp: improve error messaging

---

client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
client/branded/src/search-ui/results/filters/hooks.ts
client/web/BUILD.bazel
client/web/src/search/results/SearchResultsCacheProvider.tsx
client/web/src/search/results/StreamingSearchResults.tsx
client/web/src/search/results/components/filters-panel/SearchFiltersPanel.module.scss
client/web/src/search/results/components/filters-panel/SearchFiltersPanel.tsx
client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
client/wildcard/src/components/Tooltip/Tooltip.tsx

Resolves part of https://github.com/sourcegraph/sourcegraph/issues/59385
This PR adds 
- Tablet/mobile layout for the new search filters panel
- Fixes problem with code host color in selected filter state
- Tooltip size if filter panel width is less than tooltip content 
| Tablet | Mobile |
| -------- | -------- |
| <img width="967" alt="Screenshot 2024-01-11 at 23 37 02" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/a9395bb8-5787-42fc-b37f-1a4633cd2275"> | <img width="1218" alt="Screenshot 2024-01-11 at 23 39 00" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/5220cc52-ebf2-48a4-b42f-90a06c277a6b"> |
- Check that the new search results panel looks good (good enough) on tablet and mobile screens

Search Results: Support tablet/mobile layout for the new search filters panel

---

dev/sg/linters/prettier.go
package.json

`sg lint`'s `format` target runs `./dev/ci/pnpm-run.sh format:check`, which runs prettier against _every_ file. We can do better than that in CI by only running it against files that have been modified between the current branch and the base branch of the PR.
~**TODO:** this probably breaks when run on `main`, so we need to fix that first.~ Format step isnt run on main, so I _think_ this is safe
Before (left) After (right)
Tested on a branch based off https://github.com/sourcegraph/sourcegraph/tree/vk/add-mobile-layout-for-new-filters (https://github.com/sourcegraph/sourcegraph/tree/nsc-vk/lint-test_add-mobile-layout-for-new-filters
https://buildkite.com/sourcegraph/sourcegraph/builds/257779#_

ci: only run prettier on files changed between <commit> and <PR base branch>

---

cmd/worker/internal/telemetrygatewayexporter/queue_metrics.go
internal/database/dbmocks/mocks_temp.go
internal/database/telemetry_export_store.go
internal/database/telemetry_export_store_test.go

As titled. The plan is to measure this in dotcom and devise a dashboard panel + alert to ensure the freshness of data exports.
Integration tests against DB

telemetrygatewayexporter: add gauge indicating the age of the oldest unexported event

---

docker-images/opentelemetry-collector/builder.template.yaml

Part of https://github.com/sourcegraph/customer/issues/2673
CI, `sg ci build docker-images-candidates-notest`: https://buildkite.com/sourcegraph/sourcegraph/builds/257840

otel-collector: add prometheusreceiver

---

dev/ci/internal/ci/bazel_operations.go

Alternative to #59567 where we include bazel prechecks
CI change

Include bazel prechecks on aspect

---

internal/codeintel/autoindexing/internal/inference/lua/java.lua
internal/codeintel/autoindexing/internal/inference/lua/patterns.lua
internal/codeintel/autoindexing/internal/inference/lua/python.lua
internal/codeintel/autoindexing/internal/inference/lua/typescript.lua

According to the `README.md` and the `.stylua.toml` file in this directory, this is how things ought to be formatted. Doing this in a separate PR to not clutter my follow-up one.
Using `stylua 0.19.1` I ran the command `stylua *.lua` inside `internal/codeintel/autoindexing/internal/inference/lua`, which produced this changeset.
Just formatting, so nothing should've changed here

Formats our autoindexing scripts according to stylua

---

doc/admin/observability/alerts.md
doc/admin/observability/dashboards.md
monitoring/definitions/frontend.go
monitoring/monitoring/documentation.go
monitoring/monitoring/generator.go

Removing owner from monitoring definition we don't alert on. [Context](https://sourcegraph.slack.com/archives/C03L2R35ENL/p1704240126855279)
- CI
[Preview Link](https://docs.sourcegraph.com/@rg/remove_no_alert_owner)

Remove owner of NoAlert observable

---

sonar-project.properties

This reverts commit bf077013507d830e754f6d52fb6869260c4468c0.
With this PR the agents got updated to use a newer version of sonar scan and also use the newer JVM
- https://github.com/sourcegraph/infrastructure/pull/5745
Tested here https://buildkite.com/sourcegraph/sourcegraph/builds/257912#018d0dd2-9bc6-4949-8639-897bdc65b6d0

Revert "sonarscan: add property to allow old java version (#59575)"

---

client/web/src/components/externalServices/AddExternalServicesPage.story.tsx
client/web/src/integration/jscontext.ts
client/web/src/jscontext.ts
cmd/frontend/hooks/hooks.go
cmd/frontend/internal/licensing/init/init.go

Similar to #59528, this surfaces the cody feature status.
`features.cody` should be available in the JSContext.

licensing: surface cody feature status

---

dev/managedservicesplatform/spec/environment.go

Old code tried to check `s.Subscription.Tag`  even if `s.Subscription` was `nil`. It also did not verify whether the provided `s.Subscription` or `s.Manual` was actually expected based on `s.Type`
- CI

msp: check matching EnvironmentDeploySpec is provided

---

cmd/msp-example/internal/example/redis.go

@jac spotted a profile indicating we might have a resource leak on the clients created here. The client implements a closer, so we should use it.
n/a

msp-example: close redis client

---

dev/managedservicesplatform/spec/environment.go

Valdiation was added in #59535 , but it was not called.
```
managed-services git:(main) ✗ sg msp generate -all releaseregistry
❌ load service "releaseregistry": spec.parse: resources.memory must be >= 512Mi
```

sg msp: trigger resources validation

---

cmd/msp-example/internal/example/bigquery.go
lib/managedservicesplatform/bigquerywriter/bigquerywriter.go
lib/managedservicesplatform/runtime/contract_bigquery.go

Similar to #59598, I think this is another leak in the example service. This is less of an issue in services that create the `Writer` once, but in general things should be shut down cleanly.
n/a

msp-example: close BigQuery client

---

WORKSPACE
client/web-sveltekit/BUILD.bazel
third_party/rules_go/package_main.patch

upgrade rules_go and use newer go compiler version
CI + `bazel build //dev/sg:sg`

bazel: use rules_go 0.45

---

dev/ci/internal/ci/changed/diff.go
dev/ci/internal/ci/changed/diff_test.go
dev/ci/internal/ci/changed/files.go
dev/sg/linters/linters.go

Eliminate running `pnpm dedupe --check` if no (p)npm files are changed
No `pnpm` check being run https://buildkite.com/sourcegraph/sourcegraph/builds/258158#018d1274-b292-4e66-8865-7ab8426149ff

ci: run pnpm-dedupe only if pnpm files changed

---

internal/licensing/codygateway.go
internal/licensing/codygateway_test.go

Depends on https://github.com/sourcegraph/sourcegraph/pull/59522
This PR changes the default allowed model list for all cody gateway licenses that do not have an overwrite yet. On it's own, nothing will change yet. However, with access to fireworks models, an enterprise admin will be able to set the model as the default for the whole instance. 
This change is then going to be picked up by the clients as per https://github.com/sourcegraph/cody/pull/2714 allowing admins to opt-in to using Starcoder.
- Reset the license key overwrites for the Cody Gateway license, e.g.: 
- Observe that requests to starcoder works:
```
curl 'https://sourcegraph.test:3443/.api/completions/code' \
-X POST \
-i \
-H 'authorization: token TOKEN' \
--data-raw '{"messages":[{"speaker":"human","text":"function …
```

Add Starcoder  to all non-overwritten enterprise configurations

---

.bazelignore

Directories deleted upstream may remain locally due to (gitingored) node_modules folders, resulting in bazel errors. Instilling the discipline, widespread understanding and documentation to avoid this is a tough problem, so we can suppress the error from happening by having bazel ignore them
https://github.com/sourcegraph/sourcegraph/issues/59155#issuecomment-1883544374
`bazel query //...`

bazel: reintroduce bazelignore entries for deleted directories

---

cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
cmd/frontend/internal/dotcom/productsubscription/tokens_db.go
cmd/frontend/internal/dotcom/productsubscription/tokens_db_test.go
cmd/frontend/internal/httpapi/auth.go
cmd/frontend/internal/httpapi/auth_test.go
internal/apptoken/apptoken.go
internal/database/access_tokens.go
internal/database/access_tokens_test.go
internal/database/dbmocks/mocks_temp.go

This backports #59284, which changes the `last_used_at` column of access tokens to only be updated after a period of time so that we avoid significant database contention in periods of high token-auth'd API traffic that we've been observing in Sourcegraph.com due to the Cody PLG launch.
I'm backporting this because it turns out we are seeing similar problems placing significant database load on Cloud instances that have adopted Cody as they start increasing their API access traffic in a way that probably never happened before as most Code Search usage happens via UI - I've seen this alert fire many times on multiple Cloud instances. On a spot-check, at least several of the spikes in Cloud `pgsql` database (equivalent to the dotcom `sg` database) are entirely attributable to access token …

[Backport 5.2] accesstokens: allow last_used_at to be semi-stale (#59284)

---

dev/nix/bazel.nix
flake.nix

bazel (and its community of rules) is a bit of a mess when it comes to passing around env values, including $PATH, resulting in some actions not receiving the $PATH value set via `--action_path=PATH=...` that we rely on. Bazel 6 in nixpkgs had [the following patch](https://sourcegraph.com/github.com/NixOS/nixpkgs/-/blob/pkgs/development/tools/build-managers/bazel/bazel_6/actions_path.patch) that hardcodes a set of packages to include in that case, which is currently missing from Bazel 7 in nixpkgs, so we (temporarily, hopefully) reintroduce that patch locally. 
See: https://github.com/NixOS/nixpkgs/pull/262152#issuecomment-1879053113 and https://github.com/NixOS/nixpkgs/issues/94222 for some reading
I plan to move more bazel stuff out of shell.nix perhaps, into bazel.nix, as its a tad …

nix: patch bazel_7 with hardcoded bin paths

---

dev/managedservicesplatform/spec/environment.go

If `/-/healthz` is not implemented, services _must_ respond on `/` for external healthchecks (the Cloud Run default only does a TCP connect, which is why it generally works OOTB while the recently launched external healthchecks #59461 do not).
n/a

msp/spec: document requirements for healthzProbes: false

---

package.json

The order for git-diff is from-commit to-commit, so we just had them flipped. This isn't a problem for 95% of cases, but it breaks when a file is deleted in your branch because the flipped filter will think of it as added.
Tested locally on branch with deleted files

Fix format:ci arg ordering

---

internal/cmd/search-blitz/queries.txt

When originally added, these queries were intending to test unindexed search
(searcher). But we'll now use Zoekt when searching recent revisions. So we
update the queries to use `index:no` to make sure they're hitting searcher.
I also removed the `patterntype:structural` queries, since structural search is
now disabled on dot com by default.
Tested these on dot com, and made sure they were not hitting Zoekt

Search blitz: make sure to test searcher

---

dev/managedservicesplatform/internal/terraform/terraform.go

Eyeing potentially upgrading our Terraform version to the latest ones eventually, as we started pretty far behind because I copy-pasta'd some old configs from elsewhere. The release notes of the latest one https://github.com/hashicorp/terraform/releases/tag/v1.7.0-rc2 mentions that upgraders should be on the latest patch of their `major.minor` release, which for us means 1.3.10. This should be safe to do as it's just patches.
n/a

msp: upgrade to Terraform 1.3.10

---

WORKSPACE

This bumps the version of hermetic_cc_toolchain to v2.1.2 to fix a build issue I ran into when running sg start otel after upgrading to Sonoma.
(cherry picked from commit a465ffc0887093ad6ec6df27aee06e649ce36264)
Cherry-picking to 5.2 for verifying that a patch works, and I've already upgraded the macOS version on my dev machine.
Run `sg start enterprise-codeintel` locally and see that it works instead of running into https://github.com/sourcegraph/devx-support/issues/366

[Backport 5.2] Bump hermetic_cc_toolchain to v2.1.2 (#58132)

---

cmd/gitserver/internal/BUILD.bazel
internal/extsvc/rubygems/BUILD.bazel

Investigating at why some caching is not kicking in for the gitserver internal package tests, stumbled across a useless `data` attr. Found along the way, a duplicated target which I dropped. 
CI

bzl: drop unused target and data glob

---

dev/ci/bazel-build-sg.sh
dev/ci/bazel-configure.sh
dev/ci/bazel-gomodtidy.sh
dev/ci/gen-pipeline.sh
dev/ci/integration/executors/test.sh
dev/ci/push_all.sh
dev/ci/scripts/wolfi/update-base-image-hashes.sh

Differences in flags are causing a lot of analysis cache discarding in CI due to differences.
We mightnt see the results for this until every branch has these changes, as bazel only keeps one analysis cache around.
But also sometimes builds are very fast even when analysis cache is busted :upside_down_face: so who knows
:eye: Observing sourcegraph & aspect pipelines :eye:

ci: use ci bazelrc flags everywhere

---

dev/Caddyfile
internal/completions/client/client.go
internal/httpcli/client.go

Add a way to disable HTTP2 for sourcegraph.com -> Cody Gateway communication. This should unblock experimentation with features that require low time-to-first-event for streaming requests (currently affected by GOAWAY errors, see https://github.com/sourcegraph/cody/issues/2180 and [Slack](https://sourcegraph.slack.com/archives/C05497E9MDW/p1704734964553649) for context).
This is unlikely to be the real/permanent fix, but should unblock us for now (until we find a way to reproduce and fix the issue). 
- tested locally 
- off-by-default

Add an option for disabling HTTP/2 when communicating with Cody Gateway

---

.aspect/workflows/config.yaml
dev/ci/internal/ci/bazel_operations.go

they are executed automatically by bazel as part of //...
CI

bazel: remove explicit running of backend_integration_test

---

dev/managedservicesplatform/stacks/cloudrun/cloudrun.go

https://registry.terraform.io/providers/jianyuan/sentry/latest/docs/resources/project#default_rules
n/a

msp/cloudrun: do not provision default rules for Sentry

---

client/branded/src/components/panel/TabbedPanelContent.tsx
client/wildcard/src/components/Tabs/Tabs.tsx
client/wildcard/src/components/Tabs/useShouldPanelRender.ts

https://github.com/sourcegraph/sourcegraph/assets/18492575/a98c6394-98eb-4097-9cc1-0623d94514e3
- Check that you load only data that you need for open tab on the initial rendering
- Check that as you switch to the new tab (if it's first render of the panel you should see loading) if it's second render you should see tab content UI immediately with no loaders
@jasonhawkharris I didn't link any issue here but if we have some can you add it to this PR description

Blob UI: Use memoize rendering behavior for the tabbed panels

---

internal/cmd/search-blitz/queries.txt

This adds and 'AND' query to search blitz. The performance of 'AND' queries
will be important going forward, since we're changing the default search
strategy to interpret spaces as AND instead of performing an exact match.
It adds both an indexed search (hitting Zoekt) and unindexed search (hitting
searcher).
Tested these queries on dot com.

Search: add 'AND' queries to search blitz

---

doc/admin/observability/dashboards.md
monitoring/definitions/shared/grpc.go

Follow up to #59680. I accidentally forgot to only display retried requests on the dashboards that shows the request counts. 
Ran locally, saw that the "Client retry count per-method over 2m" dashboards now have the proper is_retried label:

grpc: fix retry count dashboard (forgot to add label to filter only retried requests)

---

doc/admin/observability/alerts.md
doc/admin/observability/dashboards.md
monitoring/definitions/embeddings.go
monitoring/definitions/frontend.go
monitoring/definitions/git_server.go
monitoring/definitions/repo_updater.go
monitoring/definitions/searcher.go
monitoring/definitions/shared/site_configuration.go
monitoring/definitions/symbols.go
monitoring/definitions/worker.go

We discovered recently that the definition for the alert that fires if the site configuration hasn't been fetched within 5 minutes strips out the regex that targets individual services (since it uses a grafana variable). This means that every instance of this alert will fire if any individual service trips over this threshold.
This PR fixes the issue by adding a new `job` filter for this alert that targets only the services that have that Prometheus scrape target name. This works around the previous issue by using a fixed value for the `job` value instead of a dynamic grafana value.
The value of the job filter generally looks like `job=~.*$container_name` (following the strategy from https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9a780f2e694238b5326e3e121d6a1828463001b9/-/blob/ …

monitoring: fix alert definition for site configuration by adding scrape job label

---

doc/admin/observability/alerts.md
doc/admin/observability/dashboards.md
monitoring/definitions/frontend.go

This alert does not seem to be useful at all and only leads to anxiety and waking up at night.
Removed alert.

Remove blobstore latency alert

---

cmd/cody-gateway/internal/actor/actor.go
cmd/cody-gateway/internal/actor/dotcomuser/BUILD.bazel
cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser_test.go
cmd/cody-gateway/internal/limiter/BUILD.bazel
cmd/cody-gateway/internal/limiter/limiter.go
cmd/cody-gateway/internal/limiter/prefix.go
cmd/cody-gateway/shared/main.go

Addressing feedback from PR: https://github.com/sourcegraph/sourcegraph/pull/59330
The rate limiting fix merged last week, need a bit of refactoring. We wanted to revert the change which exposed the BaseLimiter from actor and simply the creation of dotcom user. 
@bobheadxi and I paired on reviewing and making the changes in this PR. 
- Unit tests are present for the dotcomuser covering all the code touched by these changes. 
- For in-depth manual testing, follow the test plan from here: https://github.com/sourcegraph/sourcegraph/pull/59330

[Cody Gateway] refactor rate limiting fix

---

dev/ci/internal/ci/bazel_helpers.go

Noticed this op wasn't used anywhere anymore. 
CI

ci: drop unused operation

---

cmd/cody-gateway/internal/httpapi/attribution/handler.go

Slack [conversation](https://sourcegraph.slack.com/archives/C05497E9MDW/p1705574718346319) - this PR improves the error message (to indicate the error came from Sourcegraph.com) and changes the status code.
- CI

Add context to the error returned from dotcom

---

client/web/src/end-to-end/code-intel/repository-component.test.ts
client/web/src/repo/blob/codemirror/blame-decorations.tsx
client/web/src/repo/blob/codemirror/linenumbers.ts

Closes #59096
It's been reported multiple times that text selection conflicts with line selection, i.e. the selected line background color would be rendered on top of text selection background color and thus it seemed that no text was selected.
I remembered that this was fixed at some point so I was curious why it didn't work anymore.
The original fix was made in #47378. The `selected-line` CSS class was removed from the selected line decoration (effectively removing the background color) and instead the selected line(s) background was drawn with [CodeMirror's layer feature](https://codemirror.net/docs/ref/#view.layer). Layers are drawn *behind* the text and therefore not conflicting with the text selection color.
#47378 added *back* the `selected-line` CSS class to the selected line …

blob: Fix text selection visibility over selected lines and line number alignment

---

dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
dev/managedservicesplatform/managedservicesplatform.go
dev/managedservicesplatform/stacks/cloudrun/cloudrun.go
dev/managedservicesplatform/stacks/monitoring/BUILD.bazel
dev/managedservicesplatform/stacks/monitoring/cloudsql.go
dev/managedservicesplatform/stacks/monitoring/monitoring.go

Adds a suite of default Cloud SQL alerts on obvious things like resource utilization, and also on lock waits, which just happen to be on my mind because of recent issues in dotcom.
Closes https://github.com/sourcegraph/managed-services/issues/403
See https://github.com/sourcegraph/managed-services/pull/416

msp/monitoring: add Cloud SQL alerts

---

internal/grpc/retry/retry.go
internal/grpc/retry/retry_test.go

The `retry` package's WithOnRetryCallback functionality should only run a user defined callback if the library is about to retry a request. Howevever, there was a a pre-existing bug in the library that ran the callback whenever any sort of error occurred - regardless of whether the error was actually a retriable one. (Example: the callback would fire even if the error was a context cancellation error that can never be retried). 
This had some unintended side-effects, including inaccurate Prometheus / tracing metrics (which relied on this functioanity). 
This PR fixes the issue - now the callback only fires when there is a retriable error. 
CI (new tests)

grpc: fix retry callback logic

---

client/web/src/nav/GlobalNavbar.test.tsx
client/web/src/nav/GlobalNavbar.tsx
client/web/src/nav/NavBar/NavBar.tsx
client/web/src/nav/UserNavItem.test.tsx
client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
client/web/src/routes.tsx

Closes #59662
| Cody Only  | 
|---|
| ![CleanShot 2024-01-19 at 12 15 26@2x](https://github.com/sourcegraph/sourcegraph/assets/25608335/37f2f6d9-7134-4034-8d17-118c9810d7f4)  |  
| Code Search Only  | 
|---|
| ![CleanShot 2024-01-17 at 11 34 04@2x](https://github.com/sourcegraph/sourcegraph/assets/25608335/61907434-3166-4c94-95e1-9fc35531b42a) |  
| Code Search + Cody  | 
|---|
| ![CleanShot 2024-01-17 at 11 34 04@2x](https://github.com/sourcegraph/sourcegraph/assets/25608335/61907434-3166-4c94-95e1-9fc35531b42a) |  
* CI checks.

licensing: hide code-search related links when on Global Navbar Cody-only license

---

internal/conf/computed.go
internal/search/client/client.go

This removes the check for structural search from the backend.  This means, even if the `[ ]`-toggle is hidden in the UI (default from 5.3 on), our backend will still support structural search for the time being.
The intend is to give customers a few releases to either explicitly enable structural search or to migrate their links, code insights and scripts to regexp.
Test plan:
I tested manually that structural search queries work if the pattern type is specified explicitly in the search bar.

search: remove check for structural search from backend

---

client/branded/src/search-ui/components/QueryExamples.constants.ts
client/branded/src/search-ui/components/QueryExamples.tsx
client/branded/src/search-ui/components/useQueryExamples.tsx
client/branded/src/search-ui/results/NoResultsPage.tsx
client/branded/src/search-ui/results/StreamingSearchResultsList.tsx
client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
client/web/src/storm/pages/SearchPage/SearchPageContent.tsx

This updates the examples on the homepage depending on whether keyword search is activated or not.
Test plan:
manual testing

search: update query examples on homepage

---

schema/settings.schema.json

Fixes a typo introduced in #59686
Test plan:
Verified locally that the default "keyword" is now respected

search: fix typo in defaultPatternType

---

lib/managedservicesplatform/runtime/contract.go
lib/managedservicesplatform/runtime/service.go

As titled. Also downgrades healthz failures to `warn` - we have additional alerting for if this fails persistently at an infrastructure level.
n/a

msp/runtime: use scoped loggers for healthz, expose EnvironmentID in contract

---

CHANGELOG.md
client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.tsx
client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
client/web/src/nav/GlobalNavbar.tsx
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
client/web/src/search-jobs/utility.ts
client/web/src/search/results/StreamingSearchResults.test.tsx
internal/search/exhaustive/service/service.go

Relates to #59352 
This updates the badges from "experimental" to "beta" and enables search jobs by default.
Just a change of defaults. I checked the badges in the Navbar and on the Search Jobs page manually

search jobs: graduate from EAP to beta

---

client/branded/BUILD.bazel
client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
client/branded/src/search-ui/results/filters/components/Icons.tsx
client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss
client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.module.scss
client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.tsx
client/web/src/search/results/components/filters-panel/SearchFiltersPanel.module.scss
client/web/src/search/results/components/filters-panel/SearchFiltersPanel.tsx

Fixes https://github.com/sourcegraph/sourcegraph/issues/59440
Fixes https://github.com/sourcegraph/sourcegraph/issues/59385
Note: That `count:all` filter will be added on the backend (probably under utility section), after this FE logic will use them as other filters without changes. 
- Check that filters panel has close button on the mobile
- Check that filters has right show/hide more filters logic 
- Check that filters section has zero state if your inline search produces zero matches
- Check that icons in the footer are right

Search filters: Polish filters panel

---

cmd/frontend/graphqlbackend/search_results_test.go
internal/authz/subrepoperms/BUILD.bazel
internal/authz/subrepoperms/sub_repo_perms.go
internal/authz/subrepoperms/sub_repo_perms_test.go
internal/database/sub_repo_perms_store.go
internal/own/background/BUILD.bazel
internal/own/background/analytics.go
internal/own/background/analytics_test.go
internal/own/background/background.go
internal/own/background/recent_contributors.go
internal/own/background/recent_contributors_test.go
internal/search/job/jobutil/sub_repo_perms_job.go
internal/search/job/jobutil/sub_repo_perms_job_test.go

Currently, in the `SubRepoPermsJob`, we filter each search event in the stream serially. This is problematic because these checks require a database call, which means we're making a serial database call for each unique repo in our search results. We pay this cost whether or not the repo is a perforce repo because we're making the DB call specifically to check whether the repo is a perforce repo. This is currently adding ~2ms per unique repo in a set of search results when subrepo permissions are enabled (such as on S2).
Example trace: 
We had various layers of caching of this information that I consolidated into a cache on the checker itself so the caller doesn't need to worry about cache logic and so the cache can be shared between dependents of a client. Whether a repo is a perforce …

Perf: cache whether subrepo perms are enabled for a repo

---

CHANGELOG.md
internal/conf/computed.go
internal/database/access_tokens.go
internal/database/access_tokens_test.go
schema/schema.go
schema/site.schema.json

Add a setting to limit the number of active access tokens a user can have at a one time, the default value is 25 tokens.  Internal access tokens do not count towards the active limit.  Override of this default is available using the `maxTokensPerUser` setting in the `auth.AccessTokens` section of the site config.
This change does not effect existing tokens, if a user is over the limit no tokens are invalidated however they will not be able to create new tokens without first removing enough to get below the limit. 
closes https://github.com/sourcegraph/sourcegraph/issues/59544
tests add
manual test of access token page and call back page

New setting to specify the maximum number of active access tokens a user is allowed

---

client/branded/src/search-ui/results/filters/components/Icons.tsx

Originally, new icons were added in this PR https://github.com/sourcegraph/sourcegraph, this PR simply adds some attribution comment for the CC 4.0 license of these icons. 
- None

Icons: Add attribution license comment for the core-line icon set

---

cmd/frontend/graphqlbackend/access_tokens.go

The error from creation of access tokens was unchecked with caused emails to be sent when creation of the access token failed.  This becomes a more common situation after https://github.com/sourcegraph/sourcegraph/pull/59731 which adds a limit to the number of access tokens a user may have.
manually tested

Don't send users access token created email when creation fails

---

CHANGELOG.md
cmd/frontend/graphqlbackend/embeddings.graphql
cmd/frontend/internal/context/resolvers/BUILD.bazel
cmd/frontend/internal/context/resolvers/context_test.go
cmd/frontend/internal/embeddings/resolvers/BUILD.bazel
cmd/frontend/internal/embeddings/resolvers/repo_embedding_jobs_test.go
cmd/frontend/internal/embeddings/resolvers/resolvers_test.go
cmd/worker/internal/embeddings/repo/handler.go
internal/codygateway/client.go
internal/conf/computed.go
internal/conf/computed_test.go
internal/embeddings/background/repo/BUILD.bazel
internal/embeddings/background/repo/store_test.go
internal/embeddings/db/BUILD.bazel
internal/embeddings/db/conf_test.go
schema/site.schema.json

Overrides the embeddings config to default embeddings to disabled unless the site is running in dotcom mode.  This is a first minimal step to removing embeddings, dotcom is still dependent on the embeddings config to supply PLG rate limits for local generated embeddings and the current extension versions still use remote embeddings from dotcom as an additional context source.  
When embeddings are no longer need for dotcom the code related to embeddings can be removed. 
closes https://github.com/sourcegraph/sourcegraph/issues/59308
unit tests updated
manual test using `sg start` - extension didn't attempt to search embeddings because they are disabled.
manual test using `sg start dotcom` - extension saw embeddings enabled for repo and searched successfully

Disables embeddings for all instances that are not dotcom

---

dev/managedservicesplatform/spec/monitoring.go
dev/managedservicesplatform/spec/spec.go
dev/managedservicesplatform/stacks/monitoring/response_codes.go

Adding response code ratio alerts to the service spec was not generating the cdktf. The code was always setting the monitoring spec to empty struct.
The fix is to only set to empty struct if it parsed as nil (was not provided)
Noticed when experimenting for https://github.com/sourcegraph/accounts.sourcegraph.com/issues/291
- CI
- locally-tested

sg/msp: fix monitoring config struct always being zero value

---

client/web/src/enterprise/searchContexts/SearchContextForm.tsx
client/web/src/enterprise/searchContexts/backend.ts
client/web/src/integration/search-contexts.test.ts

This solves [#57932](https://github.com/sourcegraph/sourcegraph/issues/57932). 
A customer reported that search contexts with over a thousand repos were failing when trying to create them. 
The root cause is that the webapp was fetching repositories to validate them, but was not using pagination, and instead tried to get them all in one go. The backend limits the number of results in a page to 1000, even if the client requests more. Now, the web app pages through results.
Create search context exceeding the max number of results. 
Check network responses for the correct output.

alter function using apollo client to achieve pagination

---

client/web/src/cody/subscription/queries.tsx
cmd/frontend/graphqlbackend/schema.graphql
cmd/frontend/graphqlbackend/user.go
cmd/frontend/graphqlbackend/user_test.go
internal/cody/BUILD.bazel
internal/cody/subscription.go
internal/cody/subscription_test.go
internal/cody/utils.go
internal/cody/utils_test.go
internal/ssc/BUILD.bazel
internal/ssc/ssc.go
internal/ssc/types.go
schema/schema.go
schema/site.schema.json

This PR is the first of many to fetch Cody's subscription data from SSC (Self-Serve Cody) into dotcom and integrate at the required places. This PR only takes care of the "fetching" part. 
Right now, we know if the user has opted for a pro trial by looking at the `users.cody_pro_enabled_at` column in the dotcom database. 
From Feb 1st, tentatively, we will be allowing users to put in their credit cards on SSC, which will create a `trialling` subscription for them on SSC. We will need the combined info of dotcom and SSC to support the UI.
After the Feb 15th release, SSC will be the only source of truth for the user's Cody subscription. Part of the code, added as part of this PR, will be removed after the release.
Cody Clients and Cody Management page on dotcom uses dotcom's API to know …

Add Self Serve Cody API client to dotcom

---

cmd/worker/internal/codygateway/usageworker.go

This PR fixes a nil access panic on shutdown of worker that I saw locally:
```
[         worker] 2024/01/24 13:08:53 goroutine panic: runtime error: invalid memory address or nil pointer dereference
[         worker] goroutine 980 [running]:
[         worker] runtime/debug.Stack()
[         worker]       /Users/erik/.asdf/installs/golang/1.21.4/go/src/runtime/debug/stack.go:24 +0x64
[         worker] github.com/sourcegraph/sourcegraph/lib/background.Go.func1.1()
[         worker]       /Users/erik/Code/sourcegraph/sourcegraph/lib/background/goroutine.go:19 +0x38
[         worker] panic({0x105c12fa0?, 0x1089dc620?})
[         worker]       /Users/erik/.asdf/installs/golang/1.21.4/go/src/runtime/panic.go:914 +0x218
[         worker] …
```

worker: Fix potential panic on exit

---

client/shared/src/search/stream.ts

This reduces the default display limit from 1500 to 500. Note: this is _not_ the same as the default `count:`, so we will still collect and aggregate up to the default `count:` on the backend for the purpose of calculating more exhaustive filters, but we will only send up to 500 results to the client for display. 
Now that our default `count:` is higher and we're streaming larger chunk matches, stream sizes can get unacceptably large. For the purpose of searching code, 500 results should be enough to get an idea of whether your search is refined enough, and our new filters panel will help gently suggest ways to refine it better, so I think reducing the default display limit is an acceptable tradeoff here.
Another option would be to have a separate cutoff where we stream the matched ranges …

Search: reduce display limit to 500

---

client/web/src/global/GlobalAlerts.tsx

Removes the alert about embeddings policies from the UI 
manually tested.

Remove embeddings alert from ui

---

client/web/src/cody/management/CodyManagementPage.tsx
client/web/src/cody/subscription/CancelProModal.tsx
client/web/src/cody/subscription/CodySubscriptionPage.tsx
client/web/src/cody/subscription/UpgradeToProModal.tsx
client/web/src/cody/subscription/queries.tsx
client/web/src/featureFlags/featureFlags.ts
cmd/frontend/graphqlbackend/BUILD.bazel
cmd/frontend/graphqlbackend/schema.graphql
cmd/frontend/graphqlbackend/user.go
cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
internal/cody/subscription.go
internal/cody/subscription_test.go
internal/cody/utils.go
internal/cody/utils_test.go
internal/completions/httpapi/chat.go
internal/completions/httpapi/handler.go
internal/ssc/ssc.go
internal/ssc/types.go

Follow-up PR of https://github.com/sourcegraph/sourcegraph/pull/59763
closes: https://github.com/sourcegraph/sourcegraph/issues/58123
closes: https://github.com/sourcegraph/sourcegraph/issues/59622
closes: https://github.com/sourcegraph/sourcegraph/issues/59620
closes: https://github.com/sourcegraph/sourcegraph/issues/59623
The previous PR:
- added a new SSC API client in dotcom to fetch user's subscription info
- added a func `cody.SubscriptionForUser` to be used to find cody subscription info for the user. 
- added unit tests
This PR:
- updates all the graphql resolvers wherever applicable to use the `cody.SubscriptionForUser` function rather than directly checking dotcom's DB for `users.cody_pro_enabled_at` column.
- updated the rate limits logic in `dotcom_user_resolver` to use …

Expose new Cody Subscriptions API & integrate rate limits with SSC subscription data

---

client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss
client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
client/branded/src/search-ui/results/filters/components/Icons.tsx
client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.module.scss
client/branded/src/search-ui/results/filters/hooks.ts
client/web/src/search/results/SearchResultsCacheProvider.tsx
client/web/src/search/results/components/filters-panel/SearchFiltersPanel.module.scss
client/web/src/search/results/components/filters-panel/SearchFiltersPanel.tsx

Closes https://github.com/sourcegraph/sourcegraph/issues/59804
Adds "Apply filters to the query" button. 
- You can see it only when you have some selected filters
- As you click it we move all selected filters from the panel to the query and we reset the selected filters in the filter panel (since these filters will be handled by search box query)
- You can go back to prev state with browser history 
| Desktop | Mobile |
| -------- | -------- |
| <img width="1171" alt="Screenshot 2024-01-23 at 13 22 36" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/2d53d05b-61f9-4e64-85d9-18bdfff780cd"> | <img width="1014" alt="Screenshot 2024-01-23 at 13 26 33" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/de5add8d-bd46-423c-8d1c-760c56e7dea3"> |
- Check that this …

Search Filters: Add apply filters button to the new search filters

---

client/web/src/codeintel/ReferencesPanel.tsx
client/web/src/codeintel/token.ts
client/web/src/codeintel/useCodeIntel.ts
client/web/src/enterprise/codeintel/searchBased.ts
client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts

Cherry-pick fix for https://github.com/sourcegraph/sourcegraph/issues/58548 to 5.2 branch

[Backport 5.2] client: Avoid complex tokenization in ref panel code (#58954)

---

doc/admin/observability/alerts.md
monitoring/definitions/shared/dbconns.go

https://github.com/sourcegraph/sourcegraph/pull/59284 dramatically reduced the `mean_blocked_seconds_per_conn_request` issues we've been seeing, but overall delays are still higher, even with generally healthy Cloud SQL resource utilization.
Spot-checking the spikes in load in Cloud SQL, it seems that there is a variety of causes for each spike (analytics workloads, Cody Gateway syncs, code intel workloads, gitserver things, `ListSourcegraphDotComIndexableRepos` etc) so I'm chalking this up to "expected". Since this alert is seen firing on a Cloud instance, let's just relax it for now so that it only fires a critical alert on very significant delays.
(cherry picked from commit fc37f748654133d80199f306330207f6fc704825, https://github.com/sourcegraph/sourcegraph/pull/59507)
n/a
[Preview …

[Backport 5.2] monitoring: relax mean_blocked_seconds_per_conn_request alerts (#59507)

---

cmd/frontend/internal/app/jscontext/jscontext.go

This PR disables Features in JSContext if the license the Sourcegraph instance is running on doesn't support them. 
For example, features like Embeddings and Cody depends on the license supporting `FeatureCody`, however if this isn't the case, we can hardcode false for the context variables. 
This makes checks on the frontend easy to do.
* Manual testing on my local instance.

licensing: disable features in JSContext based on license

---

.aspect/bazelrc/ci.sourcegraph.bazelrc
.buildkite/hooks/post-checkout
WORKSPACE
dev/mocha.bzl
sg.config.yaml
testing/BUILD.bazel
testing/e2e_test.sh
third_party/bazel_lib/BUILD.bazel
third_party/bazel_lib/use_default_shell_env.patch
third_party/rules_js/BUILD.bazel
third_party/rules_js/use_default_shell_env.patch

Another step towards https://github.com/sourcegraph/sourcegraph/issues/59155, previously `bazel test //...` would error at analysis time on `//client/web/src/end-to-end:e2e` due to it attempting to perform variable substitution for env vars e.g. `"HEADLESS": "$(E2E_HEADLESS)"`, for values not defined via `--define` (we only set these explicitly in .aspect/bazelrc/ci.sourcegraph.bazelrc and some `sg` targets).
By leveraging https://bazel.build/rules/lib/builtins/actions#run.use_default_shell_env, we can allow the test to read values from `--action_env` while _also_ having explicit values set via `env` macro parameter. Previously, setting `env` macro parameter would completely shadow any `--action_env` values. 
Unfortunately, we cant use `--test_env` for this, as `js_run_binary` is an …

bazel: patches to allow use_default_shell_env for e2e testing

---

WORKSPACE
client/browser/BUILD.bazel
client/browser/scripts/build-inline-extensions.js
client/shared/dev/buildCodeIntelExtensions.js
client/shared/dev/build_code_intel_extensions.bzl
shell.nix

Reimplement fetching & building code-intel-extension bundle as a bazel `http_archive` repository & refactored `js_run_binary`. This should allow the extensions bundle to be cached in the repository cache, instead of being affected by changing action environments
`bazel build //client/browser:code-intel-extensions` and `cd client/browser && pnpm run create-source-zip` run without error

bazel: fetch code-intel-extensions bundle as bazel repository

---

internal/database/security_event_logs.go
internal/database/security_event_logs_test.go

When we pass `nil` to `LogSecurityEvent` `json.Marshal`  turns it into `"null"`, that's why before we edit it with `jsonc.Edit` we need to make sure it's a valid JSON object string instead. We added an additional condition that checks if the argument is `"null"` and return `"{}"` instead.
CI tests, local test.

Fix: ensure event.Argument is json

---

internal/guardrails/attribution_filter_test.go

Part of https://github.com/sourcegraph/sourcegraph/issues/59863
Raised in https://sourcegraph.slack.com/archives/C04MYFW01NV/p1706186104544169
One test is still flaky, but I can't put a finger on it, so I'll skip it for now, and see to it tomorrow.
`bazel test //internal/guardrails:guardrails_test --runs_per_test=100 --jobs=100`

De-flake guardrails_test

---

.aspect/workflows/config.yaml

Resolves the following warning in Aspect Workflows 5.9 for the deprecated non-list task style in the `.aspect/workflows/config.yaml`:
```
(02:52:02) [ASPECT] [WARN]
--
  | • tasks: Deprecated configuration: Tasks are migrating to a list, see documentation for details
```
Also, white space was inconsistent in the file so I ran it through a formatter.
CI

build: resolved deprecation warning for aspect config.yaml tasks style

---

client/web/src/repo/commits/GitCommitNode.tsx

Before, we showed the full commit message on the commit view. Now, we give the user the option to see more, or less of the commit message.
Previewed locally. Passing CI/CD.

truncate commit message in commit view if necessary

---

client/branded/src/search-ui/components/CommitSearchResultMatch.module.scss
client/branded/src/search-ui/components/CopyPathAction.module.scss
client/branded/src/search-ui/components/FileMatchChildren.module.scss
client/branded/src/search-ui/components/FilePathSearchResult.tsx
client/branded/src/search-ui/components/RepoSearchResult.tsx
client/branded/src/search-ui/components/ResultContainer.module.scss
client/branded/src/search-ui/components/ResultContainer.tsx
client/branded/src/search-ui/components/SearchResult.module.scss
client/branded/src/search-ui/components/SearchResultPreviewButton.tsx
client/branded/src/search-ui/components/SymbolSearchResult.module.scss
client/branded/src/search-ui/results/StreamingSearchResultsList.tsx
client/web/src/search/results/components/new-search-content/NewSearchContent.module.scss
client/wildcard/src/global-styles/colors.scss

This updates the styling of the search results to match the designs. As it turns out, there wasn't a ton to do other than styling and spacing tweaks that we needed to do anyways.
<table>
<th>
<td>Light</td>
<td>Dark</td>
</th>
<tr>
<td>Content</td>
<td>
</td>
<td>
</td>
</td>
</tr>
<tr>
<td>Repo</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Path</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Symbol</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<tr>
<td>Commit</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Diff</td>
<td>
</td>
<td>
</td>
</tr>
</table>
A video of scroll behavior. Notice that the first header does not move when scrolled.
https://github.com/sourcegraph/sourcegraph/assets/12631702/feb598cc-6ba9-4a72-9602-bb19a4fadaa2
@taiyab The header color for dark mode looks nice, but does not contrast well …

Search Results: new styling

---

dev/sg/msp/BUILD.bazel
dev/sg/msp/sg_msp.go

Saves some time for #progress posts so that I'm not constantly counting these by hand 😁 
Note that a lot of soon-to-be-prod environments are actually still in the `test` category for convenience

sg msp: add 'fleet' command for summaries

---

dev/sg/sg_monitoring.go

Allows you to list metrics from multiple dashboards, e.g. `sg monitoring metrics frontend gitserver`. Previously, we only used the first argument (incorrectly)
```sh
sg monitoring metrics frontend
Found 160 metrics in use.  
sg monitoring metrics frontend gitserver
Found 216 metrics in use.
```

sg monitoring: fix dashboard arguments

---

dev/managedservicesplatform/stacks/monitoring/service.go

Regression from #59848 - I'm not sure how this didn't caught in my testbed testing, but once rolled out it caused the monitoring stacks to fail to apply
Applied in `msp-testbed-robert`

msp/monitoring: fixup external healthcheck alert

---

client/web/src/repo/commits/GitCommitNode.tsx

Reverts sourcegraph/sourcegraph#59766 since it inadvertantly expanded the commit message at the top of the blob view
N/A

Revert "truncate commit message in commit view if necessary"

---

cmd/frontend/internal/handlerutil/repo.go

When a repo is renamed, we redirect to the new name so old links still work. However, we currently strip any query params or fragments from the request on redirect. This makes the redirect only update the path, maintaining the original query params.
This should fix an issue reported where "open in sourcegraph" links stopped working.
Renamed a repo, tested that the redirect kept `?trace=1`. I'd write an automated test, but the way we set up routing would make that really finnicky and not very valuable

Misc: retain URL params on redirect

---

cmd/syntactic-code-intel-worker/shared/config.go
dev/scip-treesitter-dev
docker-images/syntax-highlighter/crates/scip-treesitter-cli/BUILD.bazel
docker-images/syntax-highlighter/crates/scip-treesitter-cli/tests/integration_test.rs
sg.config.yaml

Use the same environment variable name, and make sure
we use the new binary name for tests.

build: Use scip-treesitter binary consistently

---

client/branded/src/search-ui/results/filters/NewSearchFilters.story.tsx
client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
client/branded/src/search-ui/results/filters/hooks.ts
client/branded/src/search-ui/results/filters/types.ts
client/shared/src/search/searchQueryState.tsx
client/web/src/search/helpers.tsx
client/web/src/search/results/StreamingSearchResults.tsx
client/web/src/search/results/components/aggregation/hooks.ts
client/web/src/search/results/components/filters-panel/SearchFiltersPanel.tsx
client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
client/web/src/stores/navbarSearchQueryState.ts
client/wildcard/src/hooks/useSyncedWithUrlState.ts

Support behaviour from https://github.com/sourcegraph/sourcegraph/issues/59593
Quick facts about `count:all` filter
- It isn't supported on the backend, so client should extend backend generated filters with new count kind
- `Count:all` filter should change the original query, we do not store anything in filters query param about count:all filters
- Since `count:all` will change the query we should support filter preservation as we change the query (prior to this PR any changes about the query reset filters completely) 
- Filter preservation tries to be a bit smart and resets filters if they no longer makes sense with new query, for example if you're picked Paths type in the filter panel and then select `Exclude go vendor` filter and then switch to the repository type, this filter will be …

Search Filters: Add count:all client filter

---

internal/completions/httpapi/handler.go

Context: https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1706116514736789
Work with https://github.com/sourcegraph/cody/pull/2902
- Increased the maximum request duration for HTTP API calls in the `internal/completions/httpapi` handler from 1 minute to 2 minutes to accommodate longer processing times for slower chat model.
Connect instance. to Cody and try using Chat GPT 4 model that has a slower response time, and confirm any streaming response did not get cut off at 1 minute.

change(httpapi): extend max request duration

---

cmd/frontend/graphqlbackend/repository_git_refs.go

Accidentally broke this, forgot to initialize the map here.
Verified manually the panic is no longer happening.

branches: Fix nil map assignment

---

cmd/frontend/internal/search/BUILD.bazel
cmd/frontend/internal/search/display.go
cmd/frontend/internal/search/search.go

We are going to make this logic more complicated. This is a first step to better document and isolate the logic from the core http streaming logic.
The intention is to add limiter (or possibly mutators) based on ChunkMatch.Content sizes.

search: factor out display limit logic into displayFilter struct

---

cmd/frontend/internal/search/BUILD.bazel
cmd/frontend/internal/search/search.go
cmd/frontend/internal/search/search_test.go

We have noticed large response payloads on dotcom which are not gzipped compressed. This should help make a dent in the amount of data a client needs to download over the wire.
Alternatively I considered upgrading all uses of StreamWriter to support gzip. I was surprised but happy to see StreamWriter now has multiple consumers outside of search (completions and blame). However, this was relatively complicated so targetting just our main streaming endpoint.
Test Plan: Added unit tests. Additionally debugged why the middleware wasn't working before and how to make it work with https://gist.github.com/keegancsmith/4e133d976f7042f0b56b6f1f062dae7b

search: encode streaming SSE with gzip

---

client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.tsx
cmd/frontend/internal/httpapi/httpapi.go
cmd/frontend/internal/search/httpapi/export.go
cmd/frontend/internal/search/resolvers/search_job.go

Search Jobs returns results as line separated JSON, but with a .json extension. This can cause confusion because users might exepect a well formated json file.
This changes the extension to [.jsonl](https://jsonlines.org/) and updates content-type to `application/jsonlines`.
Test plan:
manual testing

search jobs: change extension to .jsonl

---

internal/codeintel/autoindexing/internal/inference/libs/indexes.go
internal/codeintel/autoindexing/internal/inference/libs/update-shas.sh
internal/codeintel/autoindexing/internal/store/enqueuer_test.go

We're not actually using this anywhere, as the default autoindexing config for Rust uses `scip-rust` instead.
n/a

Stops updating lsif-rust docker image

---

deps.bzl
go.mod
go.sum

This update brings in the following commits:
https://github.com/sourcegraph/zoekt/compare/b82a981f8240...340c5f85f0b7
- https://github.com/sourcegraph/zoekt/commit/fdc6ba2262 gomod: bump go-git/go-git/v5 to v5.11.0 for CVE-2023-49569
- https://github.com/sourcegraph/zoekt/commit/92cb8852b4 score: remove unused contentProvider.matchScore
- https://github.com/sourcegraph/zoekt/commit/cdb1665266 eval: prefer longer candidateMatch when removing overlaps
- https://github.com/sourcegraph/zoekt/commit/b08be72e4c shards: always aggregate stats for tracing
- https://github.com/sourcegraph/zoekt/commit/340c5f85f0 score: introduce query.Boost to scale score
Test Plan: tested on zoekt CI and this CI

gomod: update zoekt for new query.Boost

---

cmd/gitserver/internal/git/gitcli/mergebase.go
cmd/gitserver/internal/git/gitcli/mergebase_test.go
cmd/gitserver/internal/server_grpc_test.go
internal/gitserver/commands_test.go

After implementing two other endpoints, the testing strategy is clearer to me now and I've backported the same strategy to merge base here.
Just adding tests.

gitserver: Add test suite for MergeBase

---

wolfi-images/server.yaml

In the latest release Chainguard are now using `grafana-7` rather than `grafana`.
- CI
- Manual testing of CI-built image

Match chainguard's updated grafana versioning

---

cmd/frontend/internal/httpapi/stream_blame.go
internal/gitserver/BUILD.bazel
internal/gitserver/commands.go
internal/gitserver/commands_test.go

Just to streamline a bit.
Existing test suites for Blame.

gitserver: Consistently return os.ErrNotExist on subrepo error

---

internal/search/searcher/symbol_search_job.go

This is in line with other jobs, and makes more sense IMO wrt. the comment right above.
Let me know if this assessment is wrong.
CI.

search: Don't trigger git fetch in symbol search job

---

client/branded/src/search-ui/components/ResultContainer.module.scss
client/branded/src/search-ui/components/ResultContainer.tsx

This fixes an issue with z-index leakage that I introduced in the search results styling update. I didn't really understand what a stacking context was, so I deleted something I thought was no longer relevant.
Fixes https://github.com/sourcegraph/sourcegraph/issues/59903
See screenshot. Would be nice to add some snapshot tests for this view. Will look into how to do that.

Search results: isolate z-index

---

CHANGELOG.md
client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
client/web/src/search/input/V2SearchInput.tsx
client/web/src/storm/pages/SearchPage/SearchPageInput.tsx

Closes https://github.com/sourcegraph/sourcegraph/issues/59174
This PR adds autofocus to the search page but doesn't show suggestions until the user interacts with the input (either by moving the cursor or changing the input).
- Opened the search home page -> search input is focused
- Moved cursor with keyboard, moved cursor with mouse, entered text -> suggestion show up
- Opened search results page and repo page -> search input is not focused

search: Auto focus search input on homepage without showing suggestions

---

client/branded/src/search-ui/components/ResultContainer.module.scss
client/branded/src/search-ui/components/SymbolSearchResult.module.scss

Fixes https://github.com/sourcegraph/sourcegraph/issues/59882
This just updates the borders on the search results headers to be `--border-color-2` for higher contrast. The borders separating the file chunks and individual symbol matches stay at `--border-color` because those have darker backgrounds, so the higher contrast is not needed. Additionally, I think it helps with visual hierarchy.
<table>
<tr><th>Light</th><th>Dark</th></tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</table>
Visual testing.

Search results: use `--border-color-2` on header

---

internal/cody/subscription.go
internal/cody/subscription_test.go
internal/ssc/BUILD.bazel
internal/ssc/ssc.go

Update the `ssc.Client` code to use SAMS access tokens for authentication rather than a shared secret. (Having SSC use the shared secret for auth was only going to be a temporary solution, and SAMS apparently supports OAuth clients and issuing tokens well enough to use this now(*).)
(*) Using the SSC client is behind a feature flag while the system is under development, but also because I do not believe the dotcom instance actually has the SAMS-prod identity provider wired up. (So if this were enabled, I don't think it would actually work on Sourcegraph.com as-is.)
This PR also performs some minor stylistic cleanups, adds some comments, and fixes a bug in the unit tests that should have been caught by the linter in CI (❗❓) .
> Re: bugs, the issue was that since …

Update SSC client to use SAMS access tokens

---

cmd/gitserver/internal/git/gitcli/clibackend.go

No idea how this snuck in, but we've accidentally accumulated the whole stdout in memory for no good reason? I'm not sure why this is in here tbh, but it was me.
Thanks GCloud Profiler!
None of the tests break.

gitserver: Don't buffer stdout

---

dev/managedservicesplatform/stacks/monitoring/common.go

This is only really a critical problem if we are pegged at high usage for a long time.
n/a

msp/monitoring: relax CPU alerts

---

cmd/frontend/graphqlbackend/BUILD.bazel
cmd/frontend/graphqlbackend/site.go
cmd/frontend/graphqlbackend/site_test.go
internal/cloud/site_config.go
internal/conf/diff.go

Part of https://github.com/sourcegraph/customer/issues/2747
Closes https://github.com/sourcegraph/customer/issues/2750
On Cloud, site config is a mixed of Cloud-managed and customer-managed fields. Sometime customer may touch things that they're not supposed to. Either it broke the instance or they're surprised these values are overridden by Cloud later on.
@unknwon proposed the idea of reusing SOAP to implement an allowlist approach to solve this problem.
Follow https://handbook.sourcegraph.com/departments/cloud/technical-docs/oidc_site_admin/#how-to-enable-soap-locally to set up dev environment
```
{
"authProviders": {
"sourcegraphOperator": {
"clientID": "<>",
"clientSecret": "<>",
"issuer": "<>",
"lifecycleDuration": 60
}
},
"siteConfigAllowlist": {
"paths": ["externalURL"]
}
}
``` …

soap: add support for site config allowlist

---

cmd/frontend/internal/auth/openidconnect/middleware.go

Client-side/sister PR of https://github.com/sourcegraph/accounts.sourcegraph.com/pull/375. This allows SG clients (e.g. Cody clients) to instruct which authentication provider to use when gets redirected to SAMS.
Dotcom accounts are migrating to SAMS but in order to make SAMS as the only sign-in option, we need to remove all other options but VSCode clients hardcodes the URL that blindly assumes those options will still exist, which results in a dead-end page for users.
But we do want to keep the benefit of "Sign in with [provider]" initiated from the clients, so with this PR, the VSCode client only need to update its link to something like (line break for readability):
```
https://sourcegraph.com/.auth/openidconnect/login?
prompt_auth={google,github,gitlab}&
pc=xSZLq_V7qzT9tU0-lHh98w& …
```

oidc: support pass along "prompt_auth" to IdP

---

internal/search/client/client.go
internal/search/client/client_test.go

We don't need V4 for the next release. We always send the pattern type if keyword search is active. 
Test plan:
CI

search: remove V4

---

client/branded/src/search-ui/input/SearchBox.tsx
client/web/src/communitySearchContexts/CommunitySearchContextPage.tsx
client/web/src/featureFlags/featureFlags.ts
client/web/src/featureFlags/useFeatureFlag.ts
client/web/src/nav/GlobalNavbar.tsx
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
client/web/src/search/input/SearchNavbarItem.tsx
client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
client/web/src/storm/pages/SearchPage/SearchPageInput.tsx

In #59779 we cleaned up the config for keyword search, removing the feature
flag in favor of a user setting. This PR temporarily re-introduces the feature
flag to make it easier to run users tests.
Now, the feature can be enabled simply by adding the URL parameter
`&feat=search-keyword`.
Manual testing

Keyword search: temporarily add feature flag

---

dev/managedservicesplatform/spec/environment.go
dev/managedservicesplatform/stacks/monitoring/monitoring.go

Previously these were universally suppressed as we were in development only.
Applied on sams-dev

msp/monitoring: add alerting spec for environment Opsgenie enablement

---

dev/managedservicesplatform/spec/environment.go
dev/managedservicesplatform/stacks/cloudrun/internal/builder/service/service.go

SAMS is _very_ compute-heavy it turns out, so we want to be able to use the 2nd-generation Cloud Run environment: https://cloud.google.com/run/docs/about-execution-environments
n/a

msp/cloudrun: expose execution environment

---

dev/managedservicesplatform/internal/resource/cloudsql/cloudsql.go
dev/managedservicesplatform/spec/environment.go

In SAMS we are exploring horizontal scaling options, and naturally this requires higher database connections. In the future maybe we can intelligently configure this based on Cloud Run scaling configurations.
Click-ops the increase

msp/cloudsql: make max_connections configurable

---

dev/nix/shell-hook.sh
shell.nix

As detailed in the shell hook:
Without this, zig cc is forced to rebuild on every sandboxed GoLink action, which adds ~1m of time to GoLink actions. The reason it's on _every_ GoLink action is because sandboxes are ephemeral and don't persist non-mounted paths between actions.
We're already doing this for `darwin-docker` config, so this only affects us nixos users
--- 
Smuggling in a libtool fix for macos that would otherwise yield the following error when building rust with bazel:
<details>
<summary>Details</summary>
```
cargo:rerun-if-env-changed=AR_aarch64-apple-darwin
AR_aarch64-apple-darwin = None
cargo:rerun-if-env-changed=AR_aarch64_apple_darwin
AR_aarch64_apple_darwin = None
cargo:rerun-if-env-changed=HOST_AR
HOST_AR = None
cargo:rerun-if-env-changed=AR
AR = …
```

nix: mount /tmp/zig-cache in sandbox actions

---

cmd/frontend/internal/auth/oauth/middleware.go
cmd/frontend/internal/auth/openidconnect/config.go
cmd/frontend/internal/auth/openidconnect/middleware.go

When there is no matching auth provider, there is almost always something more fucky going on. Although this PR is made specifically for VSCode Cody client, i.e. when users click on the "Sign in with X" button that links to a non-existent auth provider, it is generally more helpful to the end user to get back to the `/sign-in` page then a raw screen with a opaque error message.
```zsh
→ curl https://sourcegraph.test:3443/.auth/openidconnect/login?pc=404&returnTo=%2Fsearch
<a href="/sign-in?returnTo=/search">Found</a>.
→ curl https://sourcegraph.test:3443/.auth/github/login?pc=404&returnTo=%2Fsearch
<a href="/sign-in?returnTo=/search">Found</a>.
```

auth: redirect to "/sign-in" when auth provider not found

---

cmd/gitserver/internal/server.go
cmd/gitserver/internal/server_test.go
doc/admin/observability/alerts.md
doc/admin/observability/dashboards.md
monitoring/definitions/git_server.go

IMO, this is an unnecessary optimization that increases complexity and in the current implementation locks for longer than it needs to, because the lock in Blocking clone mode is only returned when the clone has completed, limiting the concurrency more than desired. There are also the clone limiter AND RPS limiter still in place, so we got more than enough rate limiters in place here, IMO.
Please prove me wrong :) 
Existing test suites and code reviews.
[Preview Link](https://docs.sourcegraph.com/@es/cloneablelimiter-rm)

gitserver: Remove CloneableLimiter

---

docker-images/syntax-highlighter/crates/scip-treesitter-cli/BUILD.bazel
docker-images/syntax-highlighter/crates/scip-treesitter-cli/testdata/scip-index.sh

1. Fix an issue where `index.scip` symlink was creating issues in... the process that is supposed to produce the destination file for the symlink
2. Remove the container after running, to avoid having lots of lingering containers
Extensive details are added in the script
existing tests cover this

Fix chicken-and-egg problem in scip-index.sh

---

internal/cody/subscription.go
internal/cody/subscription_test.go
internal/ssc/ssc.go
schema/schema.go
schema/site.schema.json

closes: https://github.com/sourcegraph/sourcegraph/issues/60012
To enable testing, we need to make the SAMS hostname configuration via site config, so that we can connect dotcom staging to sams dev. 
unit tests cover the changes.

Make SSC SAMS host name configurable

---

internal/search/client/client.go
internal/search/job/jobutil/job.go
internal/search/query/BUILD.bazel
internal/search/query/transformer.go
internal/search/query/transformer_test.go

Terms in phrases might be separated by more than one whitespace. With this change we respect the original query when we construct the phrase query. Before, we always joined terms with " ".  
Additionally we couple this feature to keyword search instead of having it as a feature flag.
Note: The transformation now happens during the planning stage instead of the executing stage. I think this is a more obvious spot as it happens next to other transformations on the query plan.
Test plan:
updated unit test

search: respect whitespace for phrase boost

---

client/web/src/LegacyLayout.tsx
client/web/src/nav/GlobalNavbar.tsx
client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.story.tsx
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx

This PR updates the NewGlobalNavigationBar so that it conforms to some of the updates we've been making to the NavBar as regards the licensing work.

code-search: update new global navigation bar to conform to navbar update

---

client/branded/src/search-ui/input/SearchBox.tsx
client/branded/src/search-ui/input/toggles/Toggles.test.tsx
client/branded/src/search-ui/input/toggles/Toggles.tsx
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
client/web/src/search/input/SearchNavbarItem.tsx
client/web/src/search/results/components/search-results-info-bar/SearchResultsInfoBar.tsx
client/web/src/storm/pages/SearchPage/SearchPageInput.tsx

This adds a telemetry event to track if users hit the keyword search and regexp
toggles. This will help us understand
1. If users are often frustrated/ surprised with the new search syntax
2. Whether we could potentially remove the regexp toggle in a future release
Manual testing with the `eventLogDebug` setting

Search: Add telemetry for keyword and regexp toggles

---

internal/database/batch/BUILD.bazel
internal/database/batch/observability.go

Doesn't appear to be used by anyone anymore, so we can save some quota
N/A

honeycomb: remove database-batch from emitting to honeycomb

---

dev/nix/shell-hook.sh

Non-hermetic /tmp disabled until we're on bazel 7.0.1
https://github.com/bazelbuild/bazel/issues/20527
`bazel build //:gazelle-buf`

nix: mount /tmp/zig-cache RW in sandbox actions

---

client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.module.scss
client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.module.scss
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx

So this PR does two things 
- Fixing type filter change callback (Apparently I broke it in my last PR about telemetry)
- Small fix for the search box slim navigation (removing background and use border since highlighted tokens overlap visually/blend with search box background)
- Check that you can change filter type by clicking on different types in the filter panel 
- Check that highlighted tokens don't overlap with background color of the search box UI

Search Results: Fix search box look and filter type change logic

---

internal/search/query/transformer.go
internal/search/query/transformer_test.go

Relates to #59974
We revert the logic to a much simpler join by " ".
During manual testing we noticed that queries that include reserved keywords, such as `(foo and bar) and bas` led to undesired phrase queries. For the case of `(foo and bar) and bas` we would search the phrase `foo and bar) and bas`. In hindsight this is an obvious flaw of using the character range of the terms from the original query. 
I also fix another bug which was caused by missing parser flags. Essentially, the missing flags led to parser errors if specials characters were used in the phrase.
Test plan:
- I tested manually queries such "* func = Function" or "(foo and bar) and bas" and confirmed the results are as expected.

search: revert to single space phrase boosting

---

cmd/frontend/internal/context/BUILD.bazel
cmd/frontend/internal/context/init.go
cmd/frontend/internal/context/resolvers/BUILD.bazel
cmd/frontend/internal/context/resolvers/context_test.go
internal/codycontext/BUILD.bazel
internal/codycontext/context.go
internal/codycontext/filter.go
internal/codycontext/filter_test.go
schema/schema.go
schema/site.schema.json

Updates the getCodyContext resolver to filter out context if a `.cody/ignore` file is present and it matches an ignore rule. The behavior is behind an experimental feature in the site config. 
closes https://github.com/sourcegraph/sourcegraph/issues/59682
closes https://github.com/sourcegraph/sourcegraph/issues/59976
updated existing context resolver tests
add new tests for filtering logic
Manual testing 
- Created a test repo with a main.go file and printed hello world
- Asked Cody what it printed
- Added a .cody/ignore file with main.go in it
- waiting for repo sync
- Asked Cody what the program prints - it did not read the file anymore.

Add .cody/ignore support to remote context 

---

cmd/msp-example/internal/example/BUILD.bazel
cmd/msp-example/internal/example/example.go

Otherwise, it seems all our images are the same. Having a diff makes it easier to test deploying changes, e.g. #59956 
Builds locally

msp-example: use version.Version for more interesting images

---

internal/ssc/BUILD.bazel
internal/ssc/ssc.go

When we wrote the code for `ssc.client`, we wanted to use an existing OAuth library to automate reissuing access tokens when they expire. So we would only need to generate a new SAMS access token every hour or so, rather than on every request.
I had thought that the `*http.Client` returned from `clientcredentials.Config::Client(...)` would do just that. However, in practice that did not appear to be the case. (The HTTP client was returning tokens that had long expired, i.e. not refreshing them when needed.)
After looking closer at the source code, a few things stood out. For example, by having the `*http.Client` be long lived, it runs afoul of the doc comment on top of `oauth2.NewClient` (which `client credentials.Config::Client` calls).
> The returned client is not valid beyond the …

Use long lived oauth2.TokenSource, not http.Client

---

lib/managedservicesplatform/runtime/contract.go
lib/managedservicesplatform/runtime/internal/opentelemetry/opentelemetry.go

This change implements the [SDK env var configuration for disabling OpenTelemetry](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#general-sdk-configuration) - this can be useful locally when no collector is set up.
n/a

lib/msp: implement OTEL_SDK_DISABLED

---

dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
dev/managedservicesplatform/spec/environment.go
dev/managedservicesplatform/stacks/monitoring/cloudsql.go
dev/managedservicesplatform/stacks/monitoring/common.go
dev/managedservicesplatform/stacks/monitoring/job.go
dev/managedservicesplatform/stacks/monitoring/monitoring.go
dev/managedservicesplatform/stacks/monitoring/redis.go
dev/managedservicesplatform/stacks/monitoring/response_codes.go
dev/managedservicesplatform/stacks/monitoring/service.go

Closes https://github.com/sourcegraph/managed-services/issues/469 - allow us to subscribe to pages without unintentionally being paged by potentially flakey alerts. At launch we'll have close eyes on things so this is fine - as we gain confidence in alerts we make promote them to critical ones.
Related: https://github.com/sourcegraph/managed-services/issues/385
On sams-prod:
```
"display_name": "External Uptime Check",
"documentation": {
"content": "Service is failing to repond on https://accounts.sourcegraph.com - this may be expected if the service was recently provisioned or if its external domain has changed.\n\nSee https://handbook.sourcegraph.com/departments/engineering/managed-services/sams#prod for service and infrastructure access details.\nIf you need additional assistance, …
```

msp/monitoring: only use Opsgenie for critical alerts, make external_health_check the only critical alert

---

cmd/frontend/internal/auth/openidconnect/middleware.go

This is the client/sister PR of the https://github.com/sourcegraph/accounts.sourcegraph.com/pull/388
Have you ever encounter a scenario that... you thought (and you did) signed out of a service to switch accounts, but clicking on sign in never again prompt to choose which GitHub/GitLab/Google to continue. Only to realize you need to manually sign out of the IdP as well?
This PR is for this exact UX improvement. Because there is no safe to automatically signs out users from IdP when signing out of a service (and in general it just shouldn't), force re-authentication it a nice way to have an illusion of integrated UX that now the user can the exact same sign-in options as if the user had never signed in.
1. If their IdP/SSO support `prompt=login` per standard, the improved UX still hold.
2. …

oidc: add prompt login option

---

client/shared/src/search/stream.ts

This helps alleviate an issue where we often do not show enough results on the first page due to a single file containing lots of matches. However, there are some searches which match files which contain long lines. That we are tackling right now. In the mean time though I think its better to solve the single file issue over the specific searches being slow.
Test Plan: CI

search: up display limit to 1500

---

client/web/src/cody/management/CodyManagementPage.tsx

closes: https://sourcegraph.slack.com/archives/C05PC7AKFQV/p1706755128948399
Silly mistake from the previous PR. 
I override the `cancelAtPeriodEnd` property on the frontend to test that state and take a screenshot. I forgot to remove the code. 
- Set `use-ssc-for-cody-subscription` and `cody-pro-trial-ended` feature flags to true
- Upgrade to pro
- No subscription end date should be visible on /cody/manage
- Cancel the subscription
- Subscription end date should be visible now

Fix Cody subscription ends at display logic in UI

---

client/web/src/search/results/components/search-results-info-bar/SearchResultsInfoBar.module.scss
client/web/src/search/results/components/search-results-info-bar/SearchResultsInfoBar.tsx

This PR adds a "Send feedback" button to the keyword search popover that pulls
up our feedback modal. It prefixes the feedback with "[Source: keyword search]"
so we know it's about keyword search.
Manual testing

Keyword search: add feedback modal

---

docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/evaluate.rs
docker-images/syntax-highlighter/crates/syntax-analysis/src/globals.rs
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
docker-images/syntax-highlighter/crates/syntax-analysis/src/range.rs
docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshot.rs

`Packed` doesn't make sense as a prefix as the value is actually unpacked
(we'll duplicate the line number in the common case)
n/a

highlighter: Rename PackedRange -> Range

---

dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go

Resolves discrepancy: https://sourcegraph.slack.com/archives/C06BYLJJN6N/p1706802823149289?thread_ts=1706780468.256149&cid=C06BYLJJN6N
Adding the service/env makes notifications more readable in various feeds.
https://github.com/sourcegraph/managed-services/actions/runs/7744213169

msp/monitoring: make alertpolicy subjects consistent

---

dev/sg/internal/wolfi/base-image.go

Part of https://github.com/sourcegraph/sourcegraph/issues/60069
CI 
`sg wolfi image opentelemetry-collector` works

Allow sg wolfi image opentelemetry-collector to work

---

cmd/symbols/image_test.yaml
docker-images/search-indexer/image_test.yaml

Our image tests looked for the presence of a libarchive file. This isn't present in newer versions of the package - presumably as it isn't required at runtime so has been stripped. Replace the test with the actual shared library file.
- CI build

Test for jansson shared library rather than .la file

---

tools/release/schema_deps.bzl

@keegancsmith the release is still running the previous iteration of how we handle database schemas in the migrator. I'll make sure it's correct for when you start running the legacy release tooling, as this part isn't automated over there, as I initially thought we'd be done by then (but in the meantime we found a better way of doing it). 
If for some reason, you were the one to handle this manually and I'm not there (and also because the way to use this the _old way_ is slightly different that what the README explains, which is made for RFC795, so it has a notion of schemas being avail but not yet published).   
```
bazel run //tools/release:upload_current_schemas -- v5.3.0 
bazel run //tools/release:generate_schemas_archive -- v5.3.0 fetch-current-schemas $(pwd)/
```

Update migrator schemas to 5.2.7

---

internal/search/job/jobutil/exhaustive_job.go
internal/search/job/jobutil/exhaustive_job_test.go

This PR adds support for boolean patterns to search jobs. It should be okay in
terms of performance, since we recently updated searcher to handle AND/ OR
patterns natively (https://github.com/sourcegraph/sourcegraph/issues/59038).
This also makes the integration with keyword search a lot nicer. Now when you
have a keyword search with multiple terms and you go to create a search job, it
succeeds. Previously it showed this confusing error:
AM](https://github.com/sourcegraph/sourcegraph/assets/7461306/f21a6b0b-e1a3-42bd-8415-cbc1f3346ac0)
Updated unit tests, light manual testing

Search jobs: support boolean patterns

---

internal/search/codycontext/job.go
internal/search/codycontext/query_transformer.go
internal/search/codycontext/query_transformer_test.go
internal/search/job/jobutil/job.go

If a cody context query contains only stopwords, then query processing returns
a list of empty terms, causing a panic. Now, we just return an empty query
which matches no files.
Fixes #60090
Added new unit test

Cody context: handle empty queries

---

client/web/src/repo/tree/TreePage.tsx

Now that we don't show a commits panel anymore there is no link to navigating to the commits page. This PR adds back the link to the "repo header".
Visual testing

repo: Add back link to commits page

---

client/web/src/cody/management/CodyManagementPage.tsx

You can be in a situation where the `/cody/management` page is showing you inconsistent/confusing data. Unfortunately there are several reasons for this, and some we won't be able to fix for another few weeks.
This PR introduces some new local variables to tease apart different uses of the `cancelAtPeriodEnd` field. And adds a boat load of comments to clarify what things need to change and how, as we iterate on this page and the larger SSC integration.
> @thenamankumar , as always I reserve the right to be totally wrong. Feel free to make any changes to the comments if they are factually incorrect. Otherwise, if things look good please go ahead and merge it so we can get this deployed ASAP. 🙏 
Fixes #60071 
I did no testing for this. We definitely should have unit tests for the …

Correct discrepancy between "subscription end" and "trial end" on Cody Management Page

---

client/web/src/LegacyRouteContext.tsx
client/web/src/LegacySourcegraphWebApp.tsx
client/web/src/components/legacyLayoutRouteContext.mock.ts
client/web/src/routes.tsx
client/web/src/search/upsell/SearchUpsellPage.tsx

Closes #60105
The previous implementaiton had lots of ternaries - I discovered recently that the `<LegacyRoute>` component had a `condition` prop that uses a boolean logic to mount a route or display a 404, so I'm moving the logic to use that instead as it's cleaner and easier to understand.
On a full license, all routes will work as is.
On a Code Search only license, only code-search features will show up.
On a Cody only license, only cody related features will show up.

licensing: cleanup logic for conditonally mounting route

---

'
client/branded/src/search-ui/input/experimental/codemirror/syntax-highlighting.ts
client/wildcard/src/global-styles/colors.scss

This PR adds a violet background color to keywords. I chose violet-01 for light mode and violet-05 for dark mode.
I also cleaned this up a bit to avoid repeating color values and moved the colors into CSS variables and applied transparency via SCSS. Maybe the alpha value needs to be tweaked.
Light mode: 
Dark mode:
Visual testing

search input: Add background color to operators/keywords

---

cmd/frontend/internal/auth/oauth/middleware.go
cmd/frontend/internal/auth/openidconnect/middleware.go

https://github.com/sourcegraph/sourcegraph/pull/59986 does not _fully_ work, so here is the follow-up.
```zsh
→ curl https://sourcegraph.test:3443/.auth/openidconnect/login?pc=404&returnTo=%2Fsearch
<a href="/sign-in?returnTo=/search">Found</a>.
→ curl https://sourcegraph.test:3443/.auth/github/login?pc=404&returnTo=%2Fsearch
<a href="/sign-in?returnTo=/search">Found</a>.
→ curl https://sourcegraph.test:3443/.auth/openidconnect/login?pc=404&redirect=%2Fsearch
<a href="/sign-in?returnTo=/search">Found</a>.
→ curl https://sourcegraph.test:3443/.auth/github/login?pc=404&redirect=%2Fsearch
<a href="/sign-in?returnTo=/search">Found</a>.
```

auth: be fully compatible with our creative redirect params

---

cmd/frontend/internal/app/ui/handlers.go

Ran `sg start dotcom` and confirmed after login, a user is redirected to the `/search` route.

licensing: ignore redirect check on dotcom

---

internal/rockskip/postgres.go

Closes #60110
Changed the DELETE statement for the rockskip_symbols table to use the `repoId` variable directly instead of wrapping it in a PostgreSQL array. Using an int array caused an error because [repo_id is an integer in the schema](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e0a774243cf61a83063eb8eea13d37b1764b4483/-/blob/internal/database/schema.codeintel.json?L1320-1323).
` t=2024-02-01T21:05:07+0000 lvl=eror msg="Failed to delete old repos" error="ERROR: invalid input syntax for type integer: \"{11}\" (SQLSTATE 22P02)"`
tryDeleteOldestRepo deletes repos to stay under max_repos: 2.
https://github.com/sourcegraph/sourcegraph/assets/69164745/303075ba-f6c1-462e-a91a-c7c089af9cfc

fix: Use repoId instead of array for rockskip_symbols delete

---

internal/search/job/jobutil/job.go
internal/search/job/jobutil/job_test.go

This fixes an issue we introduced recently where empty symbol searches could
panic. The bug is unreleased.
Added new unit test

Symbol search: fix panic on empty query

---

cmd/symbols/image_test.yaml
docker-images/search-indexer/image_test.yaml

Confimed that this test validates that ctags was both built with jansson and that the runtime environment has the correct libs:
```
$ universal-ctags --list-features
#NAME             DESCRIPTION
iconv             can convert input/output encodings
interactive       accepts source code from stdin
json              supports json format output
option-directory  TO BE WRITTEN
optscript         can use the interpreter
packcc            has peg based parser(s)
regex             can use regular expression based pattern matching
wildcards         can use glob matching
rm /usr/lib/libjansson.*
$ universal-ctags --list-features
universal-ctags: error while loading shared libraries: libjansson.so.4: cannot open shared object file: No such file or directory
```
- Local testing
- CI

ctags: ensure that binary has correct featureset

---

docker-images/syntax-highlighter/BUILD.bazel
docker-images/syntax-highlighter/Cargo.Bazel.lock
docker-images/syntax-highlighter/Cargo.lock
docker-images/syntax-highlighter/Cargo.toml
docker-images/syntax-highlighter/crates/syntax-analysis/Cargo.toml
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/syntect_html.rs
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/syntect_scip.rs
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
docker-images/syntax-highlighter/src/bin/scip-dump-response.rs
docker-images/syntax-highlighter/src/lib.rs
docker-images/syntax-highlighter/src/main.rs

Makes partial progress towards https://github.com/sourcegraph/sourcegraph/issues/59792
Addresses feedback from https://github.com/sourcegraph/sourcegraph/pull/59890
- `*Query` types are now moved to the server code.
- syntax-analysis crate no longer depends on Rocket (web server).
Instead, it just takes a FileInfo struct for highlighting,
and the server code converts a query into a FileInfo value.
- syntax-analysis crate doesn't depend on JSON for highlighting.
There is still JSON usage in the ctags bit, but we can
separate that out in a different PR as this is already quite big.
As part of this, I've introduced different types for the different
grammar names (Syntect/Sublime vs Tree-sitter) so that the code is
easier to follow. For simplicity, we do not eagerly validate
the grammar names …

highlighter: De-couple server code from highlighting

---

dev/sg/internal/rfc/rfc.go

The Google Drive API fails with a 403 if a search specifies both `fullText` and `orderBy` because the results are always ordered by relevance. This breaks `sg rfc search`. Fix the command by not trying to sort these results.
Manually tested:
```
bazel run //dev/sg:sg -- rfc search foo  # does not fail with 403
```

Fix `sg rfc search` 403 failures

---

dev/ci/internal/ci/images_operations.go
dev/ci/internal/ci/pipeline.go

This removes the constraint on candidate images requiring tests to have run. I tested this with a dependency on the test step, then without, then with again, to see if caching was having an impact, but it seems like no, they all took about the same amount of time, and running it without the constraint saved about 3 minutes.
Ran it in CI

Build and push candidate images in parallel

---

dev/check-tokens.sh

As title. This doesn't actually allow us to remove the pragma from any files because every file that contains a local token also contains a real looking token. 
However, weren't actually catching any files that contained new tokens because the regex we had would only catch old-style tokens, so this is actually necessary
Manually tried to commit various local, old style and new style tokens to verify pre-commit caught them.

Updated pre-commit regex for new token format

---

client/web/src/featureFlags/useFeatureFlag.ts
client/web/src/integration/search.test.ts
client/web/src/stores/navbarSearchQueryState.test.ts
client/web/src/util/settings.ts
schema/settings.schema.json

This switches the default from off to on. To disable keyword search completely, customers have to set
`experimentalFeatures.keywordSearch: false` in site settings.

search: default keyword search to on

---

docker-images/syntax-highlighter/crates/scip-syntax/src/evaluate.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/io.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
docker-images/syntax-highlighter/crates/scip-syntax/tests/integration_test.rs

`anyhow` allows us to use Result instead of panics in most places, and lets us attach more context to errors. This way we can eg. print file paths we failed to read, rather than just "Failed to read"
Code continues to compile

Uses Result over panics in scip evaluation

---

doc/admin/observability/alerts.md
monitoring/definitions/shared/codeintel.go

We've been running into spurious alerts on-and-off.
We should add observability here to better narrow down why
we're getting backlogs that are getting cleared later.
In the meantime, it doesn't make sense for this to
be a critical alert.
n/a

codeintel: Downgrade queue size critical alert to warning

---

client/web-sveltekit/src/lib/shared.ts
client/web-sveltekit/src/routes/[...repo=reporev]/RepoSearchInput.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/layout.spec.ts

This properly escapes the repository name when opening the search input on a repository name, so that it can be used as a `repo:` filter value.
Manual testing, updated integration test

svelte: Escape repository name in repo search input

---

client/branded/src/search-ui/results/filters/NewSearchFilters.tsx

Just a tiny change to change the copy from `By repositories` to the singular `By repository` to be more consistent with the other filter types and so that it correctly completes the sentence "Filter results by repository"
N/A, just a tiny copy edit.

Search filters: make repository singular

---

client/branded/src/search-ui/input/BaseCodeMirrorQueryInput.tsx
client/web/src/repo/blob/CodeMirrorBlob.tsx

Closes #60118
It appears that the recent update included changes to CodeMirror's base theme which depend on light/dark mode settings. This makes it important to communicate the current mode to CodeMirror.
In our case we don't use a specific "dark mode theme". All light/dark mode differences are handled via CSS variables. We tell CodeMirror to apply dark mode rules by setting `EditorView.darkTheme.of(true)`.
Visual testing.

codemirror: Fix text selection color in search input and blob

---

dev/managedservicesplatform/stacks/project/project.go

Adds the `collect-security-audit-logs` label to production projects 
- CI
- Locally checked label gets added to correct projects when running `sg msp gen`

sg/msp: enable security audit logging for production projects

---

cmd/frontend/internal/search/search.go
internal/search/streaming/search_filters.go

This dramatically increases the limits on the number of dynamic filters sent back to the client. Right now, we send a maximum of 40 filters back, which is problematic when a user wants to search for a repository in the sidebar to filter down their results. Since these are small payloads, I've increased the max number to 1000. It should be rare that we get more filters than that given that we generate at most one filter per result.
I've also increased the flush interval from 100ms to 200ms to offset the small potential payload size increase. It's practically not useful to get that many updates per second anyways, and we can probably push this even further since this also forces a re-render of a bunch of things for each event, but for now I'm happy with just doubling it.
I tested that the …

Search filters: increase backend limits on dynamic filters

---

internal/search/client/client.go
internal/search/types.go

This is no longer used, since we always phrase boost when
`experimentalFeatures.keywordSearch` is enabled.
Covered by CI

Search: remove search-phrase-boost feature flag

---

client/shared/src/search/query/filters.ts
client/web/src/enterprise/code-monitoring/components/FormTriggerArea.tsx
client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/search-query-checks/SearchQueryChecks.tsx
client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.ts
cmd/frontend/graphqlbackend/saved_searches.go

This PR fixes several issues when you perform a keyword search, then select Actions -> ...
* Code monitoring now allows `patterntype:keyword`
* Saved searches now accept `keyword`
* Insights already allowed `keyword` for "Track changes", now it correctly rejects it for "Detect and track patterns"
* The keyword patterntype no longer has these red squiggly lines in various search inputs:
Manual testing. Also tested searches within Notebooks and Batch changes, and `keyword` is already allowed.

Keyword search: support patterntype in other features

---

client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.tsx

As pointed out by Aimee, this is just confusing and not adding any value. So we're hiding them, but keep them around for tag validity checks otherwise.
Verified manually, see screenshot.

licensing: Don't offer disabled deprecated plans

---

internal/search/client/client.go

While looking at our traces I noticed that the name "NewSearchInputs" is probably a remnant from earlier code.
"Plan" is the better name, given that we also use "Execute" for the next stage.
Test plan:
local testing

dev: rename trace to Plan

---

client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.module.scss
client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx

@rrhyne mentioned to remove the dropshadow when the input is autofocused. Personally it feels weird to me that the shadow suddenly appears after user interaction.
https://github.com/sourcegraph/sourcegraph/assets/179026/b06a1026-8c45-46be-95b6-8808b754cd1c
https://github.com/sourcegraph/sourcegraph/assets/179026/cf1aa98d-5829-4d05-89b6-ec05c1e065a8
Manual testing

search: Don't show drop shadow for when autofocused

---

internal/completions/httpapi/handler.go

I noticed a missing return here, which led to a double `http.Error` write which is obviously illegal (and reported by `net/http` when we hit this case.)
CI

completions: fix HTTP double error-write bug

---

internal/search/query/parser.go
internal/search/query/parser_test.go
internal/search/query/query.go
internal/search/query/testdata/TestConcat/#12.golden
internal/search/query/testdata/TestConcat/#13.golden
internal/search/query/transformer.go

We change the behavior of the parser for **keyword search** to support the
following:
- parse parenthesis as groups instead of as literals
- allow mixing of implicit and explicit boolean operators
|query | parser (before) | parser (now) |
|:-----|:-------|:-------|
(a b)| "(a b)" | (and a b) | 
(a or b) c | ERROR | (and (or a b) c)
func(a int)*| "func(a int)" | "func(a int)"
*To support searching for function signatures without escaping the query,
we heuristically parse parenthesis inside patterns as literals. 
We already supported this behavior with "standard" search.
However this heuristic causes **inconsistencies** which may or may not be acceptable, 
depending on how much we want to support queries such as "func(a int)" without quotation.
(foo bar)bas -> (and "foo" "bar" "bas") …

keyword search: implicit operators and parens as groups

---

cmd/frontend/graphqlbackend/site.go
cmd/frontend/internal/app/jscontext/jscontext.go
cmd/frontend/internal/completions/resolvers/resolver.go
cmd/frontend/internal/embeddings/resolvers/resolvers.go
internal/cody/BUILD.bazel
internal/cody/feature_flag.go
internal/cody/feature_flag_test.go
internal/codycontext/context.go
internal/completions/httpapi/handler.go

These messages still referred to an "experimental" feature state, which is no longer true!
So this PR does just a minimal change, it adds some more flavor to the error message and gets rid of the "experimental" wording.
Adjusted existing and wrote new tests.

cody: Improve error messages for isCodyEnabled

---

cmd/frontend/internal/httpapi/ssc.go

forgot to remove fmt.Printf
locally tested

chore: Remove accidental debugging leftovers

---

client/branded/src/search-ui/results/filters/components/DynamicFilterBadge.tsx
client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx

We'd talked about this at some point, but I don't remember where we landed on it. It was trivial to implement so I figured we'd just discuss it on a PR to save some time. I am also simultaneously [increasing the default limit](https://github.com/sourcegraph/sourcegraph/pull/60114) so we should hopefully see this even less. 
It might be a little verbose, would appreciate feedback on the copy. 
Hovered over an approximate count and viewed the tooltip.

Search filters: add approximate count tooltip

---

dev/ci/push_all.sh

Fixes https://github.com/sourcegraph/devx-support/issues/597
Will fire a `main-dry-run` build in a minute and report back
report: 
```
bazel     --bazelrc=.bazelrc --bazelrc=.aspect/bazelrc/ci.bazelrc --bazelrc=.aspect/bazelrc/ci.sourcegraph.bazelrc     run     //cmd/searcher:candidate_push     --stamp     --workspace_status_command=./dev/bazel_stamp_vars.sh --  --tag 78208ef98d5b --tag 78208ef98d5b_2024-02-06 --tag 78208ef98d5b_260954 --tag insiders  --repository us.gcr.io/sourcegraph-dev/searcher
```
we're good

ci: do not push to prod on main-dry-run builds

---

client/web/src/search/index.ts
client/web/src/search/results/components/search-results-info-bar/SearchResultsInfoBar.tsx
client/web/src/stores/navbarSearchQueryState.test.ts
client/web/src/storm/pages/SearchPage/KeywordSearchCtaSection.tsx

This PR adds 'Beta' labels to the keyword search banner and popover, as we've
decided to ship the feature as 'beta'.
It also sneaks in a bug fix: before, if the URL did not contain a `patterntype`
parameter, we always defaulted to `standard`. Now, we use the correct default
based on the settings. This is important because users often configure a custom
search engine to search Sourcegraph (so for example they can type
`sg "some query"` in the chrome search bar). Now, these searches use `keyword`
search when the feature is enabled, whereas before they always used `standard`.
Added new unit test for bug fix

Keyword search: add 'beta' labels and fix URL parsing

---

client/web/BUILD.bazel
client/web/src/cody/featureFlags.ts
client/web/src/cody/management/CodyManagementPage.tsx
client/web/src/cody/subscription/CodySubscriptionPage.tsx
client/web/src/featureFlags/featureFlags.ts

closes: https://github.com/sourcegraph/sourcegraph/issues/60212
We are blocked from testing complete SSC integration on https://cody-services-dev.sgdev.dev/cody/manage due to hard-coded sams URL in the code. 
For a quick fix, this PR makes the URL origin toggle between `accounts.sourcegraph.com` and `accounts.sgdev.org` using feature flag `cody-payments-testing-mode`
Ideally yes, it should be configurable through site config. But that will take a bit longer to implement and unblock testing. 
tested locally.

[Cody Manage] make ssc url configurable for testing

---

cmd/gitserver/internal/perforce/BUILD.bazel
cmd/gitserver/internal/perforce/command.go
cmd/gitserver/internal/perforce/command_test.go

This PR introduces an abstraction in the `cmd/gitserver/internal/perforce` package that controls how perforce commands are instructed. A new API, `perforce.NewBaseCommand` encapsulates the construction of the `exec.Cmd` for the `p4` cli so that people are generally prevented from accessing the underlying `exec.Cmd` fields.
See https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1706747362767739?thread_ts=1705621787.809159&cid=C05EMJM2SLR for more context on this change.
Some rote CI tests

gitserver: introduce abstraction around p4 exec

---

cmd/gitserver/internal/p4exec.go
cmd/gitserver/internal/patch.go
cmd/gitserver/internal/perforce/BUILD.bazel
cmd/gitserver/internal/perforce/changelist.go
cmd/gitserver/internal/perforce/cloneable.go
cmd/gitserver/internal/perforce/depots.go
cmd/gitserver/internal/perforce/groups.go
cmd/gitserver/internal/perforce/login.go
cmd/gitserver/internal/perforce/protects.go
cmd/gitserver/internal/perforce/users.go
cmd/gitserver/internal/server_grpc.go
cmd/gitserver/internal/vcssyncer/perforce.go
cmd/gitserver/internal/vcssyncer/syncer.go

This PR uses the `perforce.NewBaseCommand` utility introduced https://github.com/sourcegraph/sourcegraph/pull/59997 throughout the rest of the `internal/perforce` package.
Existing tests in CI

gitsever: use NewBaseCommand utility in internal/perforce package

---

cmd/gitserver/internal/p4exec.go
cmd/gitserver/internal/patch.go
cmd/gitserver/internal/perforce/changelist.go
cmd/gitserver/internal/perforce/cloneable.go
cmd/gitserver/internal/perforce/depots.go
cmd/gitserver/internal/perforce/groups.go
cmd/gitserver/internal/perforce/login.go
cmd/gitserver/internal/perforce/protects.go
cmd/gitserver/internal/perforce/users.go
cmd/gitserver/internal/server_grpc.go
cmd/gitserver/internal/vcssyncer/perforce.go

While reviewing my refactor of https://github.com/sourcegraph/sourcegraph/pull/59998 given https://github.com/sourcegraph/sourcegraph/pull/59998/files#diff-9c050a0ff56a8416d8dcf8c4fceb82883eb7cc5f2b1a30b288b93722f985f1ec, I found it quite difficult to review since each function had so many back to back `string` arguments with the addition of `reposDir`. It was hard to convince myself that I never made a typo.
Example: 
```go
func IsDepotPathCloneable(ctx context.Context, reposDir, p4home, p4port, p4user, p4passwd, depotPath string) error
```
This PR is a shot at trying to fix this by extracting all these string arguments into a separate arguments struct. Now, I can see at each call-site the names of each argument that I'm using. 
Example:
```go
// IsDepotPathCloneableArguments are the …
```

gitserver: perforce: refactor functions to use argument structs

---

cmd/gitserver/internal/vcssyncer/perforce.go
cmd/gitserver/internal/vcssyncer/perforce_test.go

This PR sets the P4CLIENTPATH environment variable for `git p4` invocations. Since we should be soon switching to p4-fusion anyway, I decided to not expand the `perforce.NewBaseCommand` command to add a `git p4` equivalent. 
See https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1706747362767739?thread_ts=1705621787.809159&cid=C05EMJM2SLR for more context.
CI

cmd/gitserver/internal/vcssyncer/perforce.go: set P4CLIENTPATH environment variable for git p4 invocations

---

client/branded/src/search-ui/components/FileContentSearchResult.tsx
client/shared/src/search/stream.ts
client/web/src/search/results/StreamingSearchResults.test.tsx
client/web/src/search/results/StreamingSearchResults.tsx
client/web/src/search/results/export/searchResultsExport.ts
cmd/frontend/internal/search/search.go
internal/search/BUILD.bazel
internal/search/exhaustive/service/matchjson.go
internal/search/streaming/http/events.go
internal/search/truncate.go
internal/search/truncate_test.go
internal/search/type_converters.go

max-line-len is a new parameter which when set will truncate the Content field of ChunkMatch such that no line is longer than max-line-len. Currently we only set it for interactive queries in the webapp with the conservative number 5kb.
A new field is introduced to ChunkMatch when its content has been truncated. The webapp detects this and will skip syntax highlighting files which contain truncated ChunkMatches. The webapp will still highlight the non-truncated ranges.
We have noticed that some documents are close to our max index size (about 1mb), and are all 1 line. This can lead to response sizes in the 100s of megabytes. This both is slow for the browser to receive and parse, as well as causing locking up/freezing of the browser.
The name max-line-len was chosen as a trade-off between …

search: introduce max-line-len streaming parameter

---

client/web/src/cody/management/CodyManagementPage.tsx

closes: https://github.com/sourcegraph/accounts.sourcegraph.com/issues/452
removes this banner: 
- for free trial period but ssc connected
- put in your credit card
- the banner should not be visible on returning to /cody/manage

[Cody Manage] remove revert to trial banner

---

cmd/gitserver/internal/git/gitcli/clibackend.go
cmd/gitserver/internal/git/gitcli/odb.go
cmd/gitserver/internal/git/gitcli/odb_test.go

When not all messages are read from a reader (for example, if an archive operation times out, or if a ReadFile request is canceled, or the reader is only interested in the first X lines), we didn't properly Wait() on the command.
The added test case proves that before the code changes to the reader, there is 1 goroutine too much still active in the runtime. After this change, it's equal, across a few hundred runs.
Added test case.

gitserver: Fix goroutine leak when reader is not drained

---

client/web/src/cody/management/CodyManagementPage.tsx
client/web/src/cody/subscription/CodySubscriptionPage.tsx
client/web/src/util/constants.ts

closes: https://github.com/sourcegraph/accounts.sourcegraph.com/issues/465
closes: https://github.com/sourcegraph/accounts.sourcegraph.com/issues/442
Rather than redirecting users to accounts.sourcegraph.com directly from cody/manage, always send them to /cody/subscription page.
Test all flows by going through this locally: https://docs.google.com/drawings/d/1zFen6ut00ljsaJ8kjHVP7FRTeeWN-vcm5S0GGUVB_Ak/edit

[Cody Manage] update redirection URLs

---

internal/ssc/ssc.go

Add default value for ssc.apiBaseURL site config param. The default value was mentioned in the JSON schema but not applied. 
fixing this under https://github.com/sourcegraph/sourcegraph/issues/60218
verified locally.

Add default value for ssc.apiBaseURL

---

client/web/src/cody/management/CodyManagementPage.tsx
client/web/src/cody/subscription/CodySubscriptionPage.tsx

closes: https://github.com/sourcegraph/accounts.sourcegraph.com/issues/444
Right now, the tile should go away once the trial period ends. 
But this PR also hides it for the users who put in their CC even before the trial ends.
- sign up for pro trial
- add credit card
- the free trial tile should not be visible

Hide free trial tile if cc added

---

CHANGELOG.md

Update changelog after packport as suggested in https://github.com/sourcegraph/sourcegraph/pull/60173#issuecomment-1931812885
N/A

Update changelog after backport

---

client/web/src/repo/RepoRevisionSidebarCommits.tsx
client/web/src/repo/blob/panel/BlobPanel.tsx
client/web/src/repo/commits/GitCommitNode.tsx
client/web/src/repo/tree/TreePagePanels.module.scss
client/web/src/repo/tree/TreePagePanels.tsx

Closes #51209
This commit changes the logic in the file list panel to respect the `history.preferAbsoluteTimestamps` setting. The issue originally referenced the commits panel but that was removed in favor of the combined file/commit panel.
I also noted that `GitCommitNode` is used in most places but the callsites do not provide the value from the setting. Rather than make every callsite read the user settings the component itself uses settings as a fallback when the prop is not explicitly set.

code nav: Respect history.preferAbsoluteTimestamps user setting

---

dev/oci_deps.bzl

Switch over from the Chainguard Grafana base iamge to one that we build ourselves (from https://github.com/sourcegraph/sourcegraph/pull/60097)
- Will validate on S2

Use internally-built grafana base image

---

client/web/src/repo/RepoRevisionContainer.module.scss
client/web/src/repo/RepoRevisionContainer.tsx

Closes #47884
Instead of just truncating it we let CSS handle the overflow rendering and show a tooltip when it overflows.
https://github.com/sourcegraph/sourcegraph/assets/179026/9c76e23c-bf89-40a9-86bf-2184d836c7f1
Manual testing

code nav: Better truncation of revision names in revision selector

---

client/web/src/cody/featureFlags.ts
client/web/src/featureFlags/featureFlags.ts
internal/cody/subscription.go

closes: https://github.com/sourcegraph/sourcegraph/issues/60270
Change feature flag name `use-ssc-for-cody-subscription` to `use-ssc-for-cody-subscription-on-web`, so it is different from the one used on clients and we can control the two releases separately.
unit tests covers it.

Update SSC release feature flag name

---

dev/sg/internal/images/images_test.go
dev/sg/internal/images/registry.go

When getting the rawImg value from the yaml, the `"` quotes do not get removed leading to the parsing of the image value faliing.
Unit tests

sg ops: sanitize raw image values more

---

doc/_resources/assets/docsite.css
doc/_resources/templates/root.html

The PR adds inline CSS styling in markdown since the CSS is not getting fetched by docsite.css file.
Docs CSS added.
[Preview Link](https://docs.sourcegraph.com/@fix-banner-css)

Add inline styling in old docs banner

---

CHANGELOG.md

Add a changelog entry for the keyword search feature.
Closes #58815
Docs-only change

Keyword search: add a changelog entry

---

client/web/src/repo/RepoContainer.tsx

When an instance doesn't have the Cody feature enabled on it's license, we want to hide the `AskCody` button shown on the blob view.

licensing: hide ask cody button when cody feature isn't enabled

---

cmd/frontend/internal/app/ui/help.go
cmd/frontend/internal/app/ui/help_test.go

This updates the `/help` redirect to point to the new docs site. This is used within the product to link to the docs for the version being run. When 5.3 is released, the docs for it will be found at `sourcegraph.com/docs/v/5.3` instead of the current `docs.sourcegraph.com/@5.3`.
Fixes #59597
Updated automated tests and manually tested that previously-broken links now work as intended. We wrote a script to check that all the `/help/.*` paths in the `sourcegraph/sourcegraph` repository can be redirected to `sourcegraph.com/docs` without a 404

Docs: update `/help` redirect to point to new docs site

---

dev/sg/internal/run/sgconfig_command.go
sg.config.yaml

The [file watching notification library](https://github.com/rjeczalik/notify) we use defaults to making all watches shallow, but our convention was always that they should be recursive. A simple fix.
Manually tested locally with changes to deep files

Made all file watches in `sg start` recursive

---

client/web/src/cody/management/CodyManagementPage.tsx
client/web/src/cody/subscription/CodySubscriptionPage.tsx

We pushed the PLG launch date back from 2/15 to 2/21. This means that Cody Pro free trials will continue to run a little bit longer.
This PR updates the places in the frontend where we mention the specific date. However, in reality the "free trial end" will be managed via flag flip. On that day we will need to roll set the `cody-pro-trial-ended` to `true` globally. (As that is what will change the frontend's behavior.)
Part of https://github.com/sourcegraph/accounts.sourcegraph.com/issues/475.
NA. String changes only.

Update PLG launch dates hard coded in frontend

---

cmd/executor/internal/config/config.go
cmd/executor/internal/config/config_test.go
cmd/executor/internal/run/util.go
cmd/executor/internal/worker/BUILD.bazel
cmd/executor/internal/worker/cmdlogger/logger.go
cmd/executor/internal/worker/cmdlogger/logger_test.go
cmd/executor/internal/worker/command/command.go
cmd/executor/internal/worker/handler.go
cmd/executor/internal/worker/worker.go

Adds a mode on request of a customer that logs ALL the things the executor does. Essentially, we're dumping the whole job payload, which contains all the relevant information to be able to replicate what users did.
We're attempting to redact any secret values, but there's no 100% guarantee (especially if a user uses a non-redacted secret directly). 
Here's an example:
```
[batches-exe...r] WARN executor_processor.Handle worker/handler.go:151 Received new job to process {
"handle": {
"jobID": 7,
"repositoryName": "github.com/k3s-io/k3s",
"commit": "6d77b7a9204ebe40c53425ce4bc82c1df456e911",
"job": {
"id": 7,
"version": 2,
"queueName": "",
"repositoryName": "github.com/k3s-io/k3s",
"repositoryDirectory": "repository",
"commit": "6d77b7a9204ebe40c53425ce4bc82c1df456e911",
"fetchTags": false, …
```

executor: Add audit log mode

---

client/branded/src/search-ui/results/StreamingSearchResultsFooter.tsx
cmd/frontend/internal/search/search_test.go
internal/search/streaming/api/progress.go

The display limit is a separate limit from the result limit. In cases where we don't hit a result limit (which will be more frequent now that `count:` has been increased by default), we might still hit a display limit. This adds a message to the bottom of the search results that indicates that the results being shown are not exhaustive.
Fixes https://github.com/sourcegraph/sourcegraph/issues/60181
When the display limit has been hit:
When the display limit has been hit and the result limit has been hit:
Manual visual testing

Search results: add a message for when the display limit is hit

---

dev/ci/scripts/wolfi/update-base-image-hashes.sh

The wolfi automatic update PRs include a `backport-<branch>` label so that they will be backported to the latest release.
Update this from 5.2 -> 5.3
e.g. of auto PR: https://github.com/sourcegraph/sourcegraph/pull/60143
- CI

Set wolfi auto-update backport target branch to 5.3

---

client/web/src/search/home/SearchPage.tsx
client/web/src/storm/pages/SearchPage/CodyUpsell.module.scss
client/web/src/storm/pages/SearchPage/CodyUpsell.tsx
client/web/src/storm/pages/SearchPage/SearchPage.tsx
client/web/src/storm/pages/SearchPage/SearchPageContent.story.tsx
client/web/src/storm/pages/SearchPage/SearchPageContent.tsx

After doing some testing on DotCom, I noticed the new cody banner was unresponsive on mobile. This PR fixes that.
I also noticed the `Explore Cody` link wasn't linking to the marketing page on Dotcom. @taiyab I'm not sure if this is better or we should link to the PLG dashboard instead, however, we'll still need to handle when a user isn't authenticated on DotCom - linking to the marketing page `sourcegraph.com/cody` was the easiest of all options, however, I'm happy to change to something else.
https://github.com/sourcegraph/sourcegraph/assets/25608335/9c050e69-de16-4a85-a4ba-0ec4a5cc96af
https://github.com/sourcegraph/sourcegraph/assets/25608335/248aecea-7699-4a24-aee8-03e50b2962d6
* Manual testing based on the description above.

code-search: handle mobile responsiveness for cody banner on search page

---

client/web/src/cody/management/CodyManagementPage.tsx

closes: https://github.com/sourcegraph/accounts.sourcegraph.com/issues/465
Update the Add Credit Card button link to redirect to accounts.sourcegraph.com. 
tested locally.
- opt pro trial without turning on feature flag
- turn on `use-ssc-for-subscriptions-on-web` feature flag
- check that add to credit card button redirects to SAMS.

Update Add CC Link

---

dev/sg/sg_start_test.go

Make the slices order stable.
Without fix ❌ 
```
//dev/sg:sg_test                                                         FAILED in 19 out of 50 in 11.4s
```
With fix ✅ 
```
//dev/sg:sg_test                                                         FAILED in 3 out of 50 in 5.2s
```
The three failures were (which is unrelated)
```
WARNING: DATA RACE
Write at 0x00c0020433b0 by goroutine 229:
github.com/sourcegraph/sourcegraph/lib/output/outputtest.(*Buffer).writeToCurrentLine()
lib/output/outputtest/buffer.go:111 +0x57c
github.com/sourcegraph/sourcegraph/lib/output/outputtest.(*Buffer).Write()
lib/output/outputtest/buffer.go:100 +0x490
fmt.Fprintf()
GOROOT/src/fmt/print.go:225 +0x94
--- FAIL: TestStartCommandSet (0.03s)
sg_start_test.go:39: wrong output:
[]string{
... // 8 identical elements …
```

sg: ensure sg expected output is sorted before compare

---

internal/database/telemetry_export_store.go
internal/database/telemetry_export_store_test.go

According to the comment the feature flag should be removed by now. I double checked in slack and we can.
Test Plan: CI

database: remove telemetry-export feature flag

---

client/branded/src/search-ui/components/QueryExamples.tsx
client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss
client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx

This implements the changes in https://github.com/sourcegraph/sourcegraph/issues/60195, with a couple of small tweaks described below.
First, I modified the copy because "all repositories" is not accurate since we will be limiting to only the repository they entered.
Before: "Try searching all repositories explicitly by adding `repo:hand` to your original search query" 
After: "Try adding `repo:hand` to your original search query narrow results to that repo."
Second, I modified the text in the button to only link `search bar` because text cannot wrap within a button, so it was making the alignment weird if the linked text was larger.
[Loom walkthrough](https://www.loom.com/share/fce0b1d138774f2b8b305f3419bbba75?sid=e6a4865c-e394-4bb6-845a-118abadc45f5)
Fixes #60195 
Fixes …

Search filters: update empty state for dynamic filter searches

---

client/branded/src/search-ui/components/ResultContainer.module.scss
client/branded/src/search-ui/components/ResultContainer.tsx
client/branded/src/search-ui/results/StreamingSearchResultsList.tsx
client/web/src/search/results/components/aggregation/SearchAggregationResult.module.scss
client/web/src/search/results/components/new-search-content/NewSearchContent.module.scss
client/web/src/search/results/components/new-search-content/NewSearchContent.tsx

- Check the search result matches UI got no regressions in the layout 
- Check that the search aggregation UI has proper paddings 
- Check that zero state UI has proper paddings

Search Result: Fix search result padding problem

---

internal/search/job/jobutil/job_test.go
internal/search/query/parser.go
internal/search/query/parser_test.go
internal/search/query/testdata/TestConcat/#13.golden
internal/search/query/testdata/TestParseKeywordPattern/parens_around_slash...slash.golden
internal/search/query/testdata/TestParseStandard/parens_around_slash...slash.golden
internal/search/query/transformer.go

With the recent changes in the client, the client now sends us queries wrapped in parentheses which our hoisting heuristics don't handle well.
There are 2 issues.
1. The leaf parser incorrectly marks some queries as "disambiguated"
2. `Hoist` doesn't deal well with common nested queries such as `(and parameter (or (and parameter pattern ) pattern))`
This PR addresses both issues like follows:
1. We don't mark queries as disambiguated if we encounter a boolean operator inside parenthesis
2. We add a recursion to `Hoist` that deals with the simplest case of `(and parameter expression)`
Note:
This is also fixes a bug we recently documented with a test case, see `job_test.go`
The question is, are we hoisting anything now that we shouldn't but we haven't documented it in tests?
Test plan:
- …

search: fix hoisting heuristic for nested queries

---

client/web-sveltekit/src/app.html
client/web-sveltekit/src/lib/dom.ts
client/web-sveltekit/src/routes/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte

This fixes an issue that had been bugging for quite a while: When you scrolled within a file and navigated to a new file, we would open the new file at the same scroll position instead of at the top of the file.
SvelteKit has native support for restoring and resetting the scroll position, but that only works when the whole page is scrollable. In our case we made an "app" wrapper `<div>` scrollable, so that wouldn't work with SvelteKit.
I made the necessary HTML changes so that we can leverage SvelteKit's default behavior but that was problematic too: After clicking on an entry in the file tree the whole file tree would be moved down because now the whole page would be scrolled to the top, revealing the page navigation bar and repo header again.
So what we really want is to scroll to the …

svelte: Improve scroll behavior on repo pages

---

client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss
client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.module.scss
client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.module.scss
client/branded/src/search-ui/results/filters/components/filter-type-list/FilterTypeList.tsx
client/branded/src/search-ui/results/filters/components/filters-doc-footer/FiltersDocFooter.module.scss

This is my last planned set of design fixes for the filters panel. It's somewhat of a monolithic PR since it's the result of pairing with @taiyab and we just fixed things while we were looking at it together.
In summary:
- Fixes the issue where we would show `0` count even though a limit was hit
- Hides the entire "By type" section when a `type:` filter is entered explicitly by the user
- Fixes various spacing issues that became more apparent when the "By type" section is gone
- Fixes various small consistency issues where the "By type" section is rendered differently than the other sections
- Fixes some overlap issues that were caused by negative margins
Depends on and includes https://github.com/sourcegraph/sourcegraph/pull/60216
Stacked on …

Search filters: final design tweaks

---

cmd/frontend/auth/BUILD.bazel
cmd/frontend/auth/auth.go
cmd/frontend/auth/auth_test.go
cmd/frontend/auth/user.go
cmd/frontend/auth/user_test.go
cmd/frontend/internal/auth/httpheader/BUILD.bazel
cmd/frontend/internal/auth/httpheader/middleware_test.go
internal/auth/userpasswd/handlers.go
internal/scim/BUILD.bazel
internal/scim/user.go
internal/scim/user_create_test.go

We are seeing many email-derived usernames to be rejected as suspicious, or high chance of collisions. This would be a common theme when using custom domain emails to sign in to Sourcegraph.com. Thus this PR updates the logic to append random 5-char suffix when the username is derived from email.
Not sure if this is something we want to do only in dotcom mode (i.e. hurts Enterprise users, tho SCIM is doing the same thing when turned on), up to the Source team.
CI and tested locally e2e

auth: append random suffix when derive username from email

---

client/web/src/enterprise/site-admin/dotcom/productSubscriptions/plandata.ts
internal/licensing/data.go
internal/licensing/tags_test.go

These are the final names.
Verified manually that both on the admin side and on the instance side the license name shows correctly.

licensing: Rename new plans

---

internal/completions/httpapi/handler.go

Closes #59824
Attribution for autocomplete is implemented in the back-end and can currently be enabled by using `attribution.enabled: true` site config. However for safety we allow disabling attribution just for autocomoplete by setting `autocomplete-attribution` feature flag to `false`.

Autocomplete attribution requires site config setting but can be individually disabled with feature flag

---

client/branded/src/search-ui/input/BaseCodeMirrorQueryInput.tsx
client/web-sveltekit/src/lib/search/BaseQueryInput.svelte
client/web/src/repo/blob/codemirror/codeintel/keybindings.ts

Codemirror applies its own styling for selections, and when the blob view is focused, that styling is higher precedence than the overrides we provide. More confusingly, sometimes (it's not deterministic) the codemirror styling does not respect the light/dark theme settings, which makes selection look very broken. It's still not clear to me why the theme variable is not being respected, but given our proximity to code freeze, this just adds an `!important` to our theme overrides to make it not feel super broken.
[Slack thread](https://sourcegraph.slack.com/archives/C05MHAP318B/p1707329576741979)
Before:
A capture of the CSS selector that was problematic:
Visually checked that there are no more dark backgrounds and opened the console to double check that the `!important` was showing up and …

Blob view: bandaid selection coloring

---

client/web/src/enterprise/site-admin/dotcom/productSubscriptions/plandata.ts
internal/licensing/data.go
internal/licensing/tags_test.go

These are the final names.
Verified manually that both on the admin side and on the instance side the license name shows correctly.
Test Plan: manual
(cherry picked from commit c657b314710b38831cbe883cb37b96c95646bc95)

licensing: Rename new plans (#60345)

---

.aspect/workflows/config.yaml

As per the feedback given over https://sourcegraph.slack.com/archives/C07KZF47K/p1707468139054549?thread_ts=1707435487.087259&cid=C07KZF47K this would be really helpful.
CI

aw: use two different jobs for e2e and normal testing

---

cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
internal/completions/httpapi/codecompletion.go

Two things going on here:
1. We add Llama Code 13b to all PLG users. c.f. https://sourcegraph.slack.com/archives/C05AGQYD528/p1707411649398769?thread_ts=1706882079.259169&cid=C05AGQYD528
2. Removed some no longer needed model translation. CG can handle the virtual `fireworks/starcoder-16b` model names for a while now.
- Trivial change, CI will test it

Add Llama Code 13b to all PLG users and remove unused model conversation

---

internal/database/migration/cliutil/util.go

Migrator was incorrectly returning that it needs an update if the migrator is newer than the latest release at the minor level. 
CI

mig: fix out-of-date-detection

---

docker-images/redis-cache/BUILD.bazel
docker-images/redis-cache/image_test.yaml
docker-images/redis-cache/readiness.sh
docker-images/redis-store/BUILD.bazel
docker-images/redis-store/image_test.yaml
docker-images/redis-store/readiness.sh

Readiness check testing:
```
$ /usr/local/bin/readiness.sh 
Could not connect to Redis at 127.0.0.1:6379: Connection refused
/redis-data $ echo $?
1
redis-server &
/redis-data $ /usr/local/bin/readiness.sh 
/redis-data $ echo $?
0
```
- CI tests
- Tested readiness check locally

Improve redis image readiness checks

---

tools/release/schema_deps.bzl

Follow-up to https://github.com/sourcegraph/sourcegraph/pull/60087 for 5.3.0 
Release tooling: tooling affecting internal/database/migration/shared/data/cmd/generator/consts.go is still required to be run before the final release.
CI

Update database schemas for migrator to 5.3.0

---

shell.nix

`sg start otel` works since it runs wolfi and wolfi wants to access the osx keychain to load the image into docker

nix: add docker-credential-helpers package

---

client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss
client/wildcard/src/global-styles/code.scss

Adjusts default styling for the `<kbd>` element.
Before: 
After:
Test manually. CI/CD passing.

Code Navigation: adjust global styling for kbd element

---

cmd/cody-gateway/internal/httpapi/completions/anthropic.go
cmd/cody-gateway/internal/httpapi/completions/fireworks.go
cmd/cody-gateway/internal/httpapi/completions/openai.go
cmd/cody-gateway/internal/httpapi/completions/upstream.go
cmd/cody-gateway/shared/config/config.go

Removes code for logging Fireworks code completion requests (no longer needed). 
Also, simplifies `upstreamHandlerMethods.getRequestMetadata` signature for all implementations.
- unit tests
- e2e tests locally

Remove code for logging completions

---

client/branded/src/search-ui/results/StreamingSearchResultsFooter.module.scss
client/branded/src/search-ui/results/StreamingSearchResultsFooter.tsx
client/branded/src/search-ui/results/StreamingSearchResultsList.tsx
client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
client/web/src/search/results/components/new-search-content/NewSearchContent.module.scss
client/web/src/search/results/components/new-search-content/NewSearchContent.tsx
client/web/src/search/suggestion/DidYouMean.tsx
client/web/src/search/suggestion/SmartSearch.tsx

[Original Slack report message](https://sourcegraph.slack.com/archives/C05D629GWJK/p1707480193201689) 
Fixes https://github.com/sourcegraph/sourcegraph/issues/60119
Prior to this PR we used negative margins to have paddings for all child content in the content area but made an exception for actual search result matches block (which should have 0 spacing between parent border). This layout doesn't work in case we render content and some other elements on the same level, because of exactly negative margins of the content block. See the image below. 
So this PR adds manual wrappings for spacing and handles content children spacing manually as well.  
Also, this PR fixes some regression after #60220, now we render no zero-state content again. This is probably was just a mistake there but if …

Search-results page: Fix search result layout block spacings

---

internal/search/zoekt/query.go
internal/search/zoekt/query_test.go

For the 'search-content-based-lang-detection' feature, this PR improves how filters are converted to Zoekt queries:
* Only convert filters to Zoekt lang filters, instead of also including file filters
* Handle excluded filters as well, for example `-lang:go`
* Use 'and' instead of 'or' to combine multiple filters
Relates to https://github.com/sourcegraph/sourcegraph/issues/60341
Added new unit tests, manual testing

Search: solidify conversion to Zoekt queries

---

client/web/src/cody/dashboard/CodyDashboardPage.tsx

All links to the old docs page `docs.sourcegraph.com` should be updated to their `sourcegraph.com/docs` equivalent.

licensing: update doc links to the new doc website

---

internal/conf/computed.go
internal/conf/computed_test.go

Lowers the default context window size for GPT-4 models that have 8k windows to account for the 1k token response size.
Updated unit test

Lower context window size for gpt-4 down to account for chat responses

---

cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go
cmd/cody-gateway/shared/config/config.go
cmd/cody-gateway/shared/main.go

Make dotcom actor refresh cooldown configurable - see [Slack](https://sourcegraph.slack.com/archives/C05SZB829D0/p1707552838650569)
- e2e tests

Make dotcom actor refresh cooldown configurable

---

cmd/searcher/internal/search/search_regex.go
cmd/searcher/internal/search/search_regex_test.go
cmd/searcher/internal/search/search_structural.go

This PR refactors `regexSearchBatch` to remove duplicating the work of
constructing the matcher objects. It will be helpful for the searcher work in
https://github.com/sourcegraph/sourcegraph/issues/60341.
Adapted unit tests

Searcher: refactor batch search method

---

client/web/src/site-admin/routes.tsx

Follow-up on https://github.com/sourcegraph/sourcegraph/pull/60371 ([comment](https://github.com/sourcegraph/sourcegraph/pull/60371/files#r1485710297)).
**Cody feature enabled in license**
**Cody feature disabled in license**
- CI
- Tested manually: Cody analytics page is not available in the site admin sidebar and via URL  "site-admin/analytics/cody"

Render Cody analytics site admin route if Cody is enabled in license

---

cmd/cody-gateway/qa/fireworks.go
cmd/cody-gateway/shared/config/BUILD.bazel
cmd/cody-gateway/shared/config/config.go

Fix bad Fireworks model list. 
Update end-to-end tests to use the virtual model string.
- manual test
- e2e test

Fix model allowlist for fireworks + use virtual model string in e2e

---

cmd/worker/internal/embeddings/repo/worker.go
internal/codycontext/BUILD.bazel
internal/codycontext/context.go

Fully removing our use of qdrant is quite a large change. Instead this does a minimal change by just removing the part of our code which optionally searches via qdrant, and additionally the part which uses a real qdrant client. This effectively makes it so qdrant is always disabled.
In practice, the "GetEmbeddingsConfig" will only return a configuration for dotcom. Currently qdrant is disabled on dotcom, so operationally this is a noop change.
Test Plan: CI and investigating that live environments this is a noop.

all: update code paths as if qdrant is disabled

---

CHANGELOG.md
internal/authz/providers/perforce/perforce.go
internal/authz/providers/perforce/perforce_test.go

Closes #58757 
Makes perforce email matching case insensitive.
Adjust and add unit test.

Make perforce email matching case insensitive

---

cmd/gitserver/internal/mocks_test.go
cmd/gitserver/internal/patch.go
cmd/gitserver/internal/server.go
cmd/gitserver/internal/server_grpc.go
cmd/gitserver/internal/server_grpc_test.go
internal/gitserver/client_test.go
internal/gitserver/protocol/gitserver.go

This makes it so that we don't have to buffer the entire patch in memory, which has been seen to be 100MB+ in the past.
Existing test suites cover that this didn't break anything.

gitserver: Make patch reader for CreateCommitFromPatch streaming

---

cmd/gitserver/internal/mocks_test.go
cmd/gitserver/internal/patch.go
cmd/gitserver/internal/server.go
cmd/gitserver/internal/server_grpc.go
cmd/gitserver/internal/server_grpc_test.go
internal/gitserver/client_test.go
internal/gitserver/protocol/gitserver.go

Just a simple change, we don't need to explicitly reimplement this.
This endpoint is unused, so as long as Go is happy, it will be fine.

gitserver: Default to unimplemented handler of P4Exec

---

internal/extsvc/types.go
schema/azuredevops.schema.json
schema/schema.go

We already had a rate limiter in the code, it was just not configurable, so we used Inf always. This was a quick win.
Closes https://github.com/sourcegraph/sourcegraph/issues/46956
Manually set a very low limit locally, ran again, saw requests getting queued. Also the rate limiter state in the UI correctly reflects the configuration.

ratelimiter: Add configuration options for ADO

---

cmd/cody-gateway/internal/actor/dotcomuser/dotcomuser.go

Log when rate-limit refresh is blocked (so we can create a log-based metric).
- e2e tests pass

Log when refresh is blocked by cooldown

---

client/web/src/cody/management/CodyManagementPage.tsx
client/web/src/cody/subscription/CodySubscriptionPage.tsx
client/web/src/util/constants.ts

closes: https://github.com/sourcegraph/accounts.sourcegraph.com/issues/491
Change the colour of the Manage Subscription Button on `/cody/manage` to blue and add cc icon.
For Pro users add a primary Manage Subscription button on the right side of the header on `cody/subscription` and add a link back to the dashboard below the header. 
Take care of all the feature flags and states while doing the above changes.
- Turn on use-ssc-for-subscription-on-web feature flag
- Upgrade to pro and add credit card
- Verify that the above buttons and links are working as expected.

Update Manage Subscription buttons

---

client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss

Using a more appropriate color variable for the background of the filter panel.
Manually tested.

Search results: Modified filter panel background color

---

cmd/worker/internal/githubapps/worker/installation_backfill_test.go
internal/extsvc/github/v3.go
internal/github_apps/store/BUILD.bazel
internal/github_apps/store/store.go
internal/github_apps/store/store_test.go
internal/github_apps/types/types.go

Because we were not paginating, we would end up deleting all installations when there were more than 30 (default page size).
Added a unit test and @BolajiOlajide manually tested the fix.
[Walkthrough of Bolaji running a dead simple test](https://www.loom.com/share/4d1254e072db4973b1f17645b13b5654?sid=d392589a-bd31-48e2-a3a1-071a1d3bf678)

Batch changes: paginate when listing github apps

---

client/web/src/auth/CloudSignUpPage.story.tsx
client/web/src/auth/CloudSignUpPage.tsx
client/web/src/auth/RequestAccessPage.story.tsx
client/web/src/auth/RequestAccessPage.test.tsx
client/web/src/auth/RequestAccessPage.tsx
client/web/src/auth/ResetPasswordPage.story.tsx
client/web/src/auth/ResetPasswordPage.tsx
client/web/src/auth/SignInPage.story.tsx
client/web/src/auth/SignInPage.test.tsx
client/web/src/auth/SignInPage.tsx
client/web/src/auth/SignUpForm.tsx
client/web/src/auth/SignUpPage.story.tsx
client/web/src/auth/SignUpPage.test.tsx
client/web/src/auth/SignUpPage.tsx
client/web/src/auth/UnlockAccount.story.tsx
client/web/src/auth/UnlockAccount.tsx
client/web/src/auth/UsernamePasswordSignInForm.tsx
client/web/src/auth/VsCodeSignUpPage.story.tsx
client/web/src/auth/VsCodeSignUpPage.tsx
client/web/src/auth/components/ExternalsAuth.tsx
client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
client/web/src/get-cody/GetCodyPage.tsx
client/web/src/repo/components/TryCodyWidget/TryCodyWidget.tsx
client/web/src/routes.tsx
client/web/src/site-admin/init/SiteInitPage.tsx
client/web/src/util/constants.ts

Context:
`sg start`
visit page
(This is actually harder with this commit given some of these pages are hard to reach, so more testing would be helpful)

v2 telemetry: add v2 telemetry to src/auth

---

cmd/telemetry-gateway/internal/server/BUILD.bazel
cmd/telemetry-gateway/internal/server/publish_events.go

Currently, failures don't get marked as a failed span. This is mostly a visibility improvement.
n/a

telemetry-gateway: mark handlePublishEvents spans as failed on error

---

cmd/frontend/internal/guardrails/init.go
internal/codygateway/client.go

Part of https://github.com/sourcegraph/sourcegraph/issues/60439
- Return error in case `http.Doer` is not set. Not sure how that can be but the error indicates it's nil sometimes.
- Return uninitialized attribution client, if HTTP client was not created.

Quickfix for attribution panics

---

dev/release/src/release.ts

The part that generates the stitch graph is now handled fully by Bazel, so we don't need to explicitly call the generator when running the legacy tooling.
TODO

rel: remove call to generate stitch from legacy tooling

---

dev/release/src/release.ts

Legacy release tooling wasn't using the new bazel target for generating that file, which this PR fixes. 
Ran locally (had to comment other changesets, but that bit ran fine).

Fix legacy release tooling, use bazel to generate stitch graph

---

dev/release/src/static-updates.ts

Even though this code was added a year ago, it clearly has never actually been run. The first fix is correctly specifying the name of the terraform-aws-executors repository. It had the name and owner mixed up, causing the clone to fail.
The second fix is to fetch the history so that prepare-release.sh actually runs.
Note: this will still just fail. But it gets far along enough in my release now that I can pick up the pieces and manually create PRs. Then I can comment out these steps and run the tool again.
Test Plan: blood, sweat and tears
Part of https://github.com/sourcegraph/sourcegraph/issues/60032

release: half fix bake*ExecutorsSteps

---

internal/completions/httpapi/handler.go
internal/guardrails/attribution_filter.go

Closes #60439
2 issues:
- if no attribution search is triggered it can wait forever
- if the attribution search returns a result while we stream other stuff, we might concurrently flush, causing panics (the panic message is not 100% the one from the ticket, but very close, and we were able to repro that, and not anymore after the fix)

Fix panics in streaming completions handler

---

cmd/frontend/internal/guardrails/init.go

This reverts commit bc599bb8f0e40957d5f711e10636bf3ef5c030d0.
Part of https://github.com/sourcegraph/sourcegraph/issues/60439
This is not needed after a proper fix from @keegancsmith https://github.com/sourcegraph/sourcegraph/pull/60471

Revert "Return uninitialized gateway if client is nil"

---

dev/release/src/static-updates.ts

I am running the 5.3 release but this is all borked. We used to run a src-cli reference doc generator, but we now have a docs repo which uses mdx files. So the reference generator needs to be updated. So for now I am just skipping this and will follow up later.
Test Plan: progress in running bake-content for release

release: skip updating src-cli docs reference

---

WORKSPACE
sg.config.yaml

There was an issue with the Rust rules, that caused failures with `bazel query ...` which is now fixed by using the latest `rule_rust`, enabling us to use the bazel command for `syntax-highlighter`. 
Ran locally + CI

Re-enables syntax highlighter in bazel commandset + bump rules_rust

---

dev/release/src/release.ts

We should be ignoring updating `sourcegraph/server` in the changelog for `docs`, this is because we have some entries that specifies changes at a certain version.
We'll find out lol.

release: ignore CHANGELOG.mdx in docs repo when updating server tags

---

cmd/frontend/internal/auth/openidconnect/middleware.go

This reverts commit 4c5a558d5c4cc234f8d0e4edd448b09e892c6554.
After [some discussions](https://sourcegraph.slack.com/archives/C06HHK23QR4/p1707419775776459), asking users to "sign out twice" may end up with less trouble than "always sign in".
CI

Revert "oidc: add prompt login option (#60036)"

---

client/web/src/cody/components/GettingStarted.module.scss
client/web/src/cody/components/GettingStarted.tsx

Issue: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1707499933575329
As reported, the text comes out of the bubble for Cody Web.
After testing, I found that the bug is on Firefox because the browsers treat Grids differently. 
I have replaced grid-based CSS with a basic flex model with position absolute to fit text nicely into the bubble. 
Tested on all browsers at various zoom levels.
- Open Cody Web in the sidebar on file view. 
- Create new chat
- The bubble should cover the whole "Hi I'm Cody" text.
- Test on all the browsers.

Get Stevey a bigger bubble

---

cmd/msp-example/internal/example/example.go
cmd/pings/service/service.go
cmd/telemetry-gateway/service/service.go
lib/background/BUILD.bazel
lib/background/background.go
lib/background/background_test.go
lib/managedservicesplatform/runtime/service.go

Possible alleviation to recent errors like https://sourcegraph.slack.com/archives/C06CCJR4K9R/p1707434020627279 and https://sourcegraph.slack.com/archives/C06CCJR4K9R/p1707772710344069 - it's possible that server stops before the pub/sub client, cancelling the context of ongoing requests and causing them to be interrupted. This could possibly be fixed by ensuring the pub/sub client clears its backlog before we stop the server.
Unit tests on the new LIFOStopRoutine:
```
go test -race -count=100 -run ^TestLIFOStopRoutine$ github.com/sourcegraph/sourcegraph/lib/background
```

pings, telemetry-gateway: stop pubsub client before stopping server

---

dev/managedservicesplatform/internal/resource/loadbalancer/loadbalancer.go
dev/managedservicesplatform/spec/environment.go
dev/managedservicesplatform/stacks/cloudrun/internal/builder/service/service.go

These can be pretty high-volume, so I think it might be best to leave it opt-in for now
click-ops the equivalent change

msp/loadbalancer: add config to enable logging

---

internal/search/query/parser.go
internal/search/query/parser_test.go

This fixes a bug in the backend parser to recognise "AND" and "OR" even if they aren't preceded by whitespace. Previously, a query such as "(a or b)and c" was not parsed correctly, because "and" was preceded by ")", which resulted in surprising results.
They key idea of the fix is to recognise parenthesis as proper boundaries and to not advance the parser immediately once we encounter a right parenthesis, but instead to let the caller advance. This way, the caller can construct an operator (`(or a b)` in this case) before continuing with the parsing. This mirrors the behavior of the other keywords that can break the loop in the leaf parser.
The handling of whitespace in our parser is very fragile. A more thorough fix would be to introduce a lexer to eliminate the significance of …

search: better handling of keyword boundaries

---

dev/managedservicesplatform/internal/resource/alertpolicy/BUILD.bazel
dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
dev/managedservicesplatform/internal/resource/alertpolicy/responsecode.go
dev/managedservicesplatform/internal/resource/alertpolicy/responsecode_test.go
dev/managedservicesplatform/internal/resource/alertpolicy/thresholdaggregation.go
dev/managedservicesplatform/internal/resource/alertpolicy/thresholdaggregation_test.go
dev/managedservicesplatform/stacks/monitoring/cloudsql.go
dev/managedservicesplatform/stacks/monitoring/common.go
dev/managedservicesplatform/stacks/monitoring/job.go
dev/managedservicesplatform/stacks/monitoring/redis.go
dev/managedservicesplatform/stacks/monitoring/response_codes.go
dev/managedservicesplatform/stacks/monitoring/service.go

Previously, different conditions would have completely different code paths for generating the policy, which lead to some drift in the ones we pay less attention to (like response code) and a lot of copy-pasta.
This change adjusts our internal abstraction to center around condition builders, and switch on the type of the alert to generate the condition that then goes into the a unified alert policy format. This will make it easier for us to build more alerts on different condition types.
In doing this I notice that `ResourceKind`, `ResourceName` are threshold-aggregation-specific, so I've moved those downwards as well.
`sg msp generate -all` changes only the response code alerts to have additional labels, and also updates the severity level for the external uptime alert to match the …

msp/alertpolicy: unify on generalized policy builder, with custom condition builders

---

dev/managedservicesplatform/spec/monitoring.go
dev/managedservicesplatform/stacks/monitoring/monitoring.go

Change Nobl9 to a pointer type to make it optional
- locally tested

sg/msp: make nobl9 key optional in spec

---

cmd/gitserver/internal/git/gitcli/mergebase.go
cmd/gitserver/internal/git/gitcli/mergebase_test.go
cmd/gitserver/internal/git/iface.go
cmd/gitserver/internal/server_grpc.go
cmd/gitserver/internal/server_grpc_test.go
internal/gitserver/commands_test.go

Aligning with other functions, we now return a RevisionNotFoundError instead of an unwrapped command error.
Added tests.

gitserver: Normalize revisionnotfound errors

---

cmd/gitserver/internal/cleanup.go
cmd/gitserver/internal/cleanup_test.go

In the janitor, we calculate the repo size. That is quite IO heavy and expensive, and every fetch (basically the only writing operation) runs this, too. So janitor is mostly doing that to ensure that things don't get terribly out of sync, if some issues occur.
Given that, we don't need to run this every time. Instead, we can run it only once a day. In reality, probably less often. We can adjust as needed.
Also moves it to the end of the janitor operations, to collect a size that's not outdated immediately when the next janitor step runs.
Verified the setting works locally.

gitserver: Calculate repo size less frequently in janitor

---

internal/database/schema.json
internal/database/schema.md
migrations/frontend/1707759188_drop_user_searchable/down.sql
migrations/frontend/1707759188_drop_user_searchable/metadata.yaml
migrations/frontend/1707759188_drop_user_searchable/up.sql
migrations/frontend/squashed.sql

We stopped using this over a release ago, so we can now safely drop it from the schema.
Closes https://github.com/sourcegraph/sourcegraph/issues/60141
Backcompat tests.

Drop unused users.searchable DB column

---

cmd/gitserver/internal/integration_tests/BUILD.bazel
cmd/gitserver/internal/integration_tests/resolverevisions_test.go
internal/batches/sources/mocks_test.go
internal/codemonitors/search.go
internal/codemonitors/search_test.go
internal/gitserver/client.go
internal/gitserver/commands.go
internal/gitserver/internal_test.go
internal/gitserver/mocks_temp.go
internal/gitserver/observability.go
internal/gitserver/protocol/gitserver.go
internal/gitserver/protocol/gitserver_test.go
internal/gitserver/search/search.go
internal/gitserver/search/search_test.go
internal/search/commit/BUILD.bazel
internal/search/commit/commit.go

To migrate ResolveRevision to gRPC, I'm removing this endpoint in favor of individual calls
for now.
This will simplify the migration. If someone was requesting hundreds of revs here, this will
actually give us better metrics about that, and we'll be able to fix it again.
Adjusted existing tests.

gitserver: Remove ResolveRevisions from client

---

CHANGELOG.md
internal/github_apps/store/BUILD.bazel
internal/github_apps/store/store.go
internal/github_apps/store/store_test.go

Closes #54066
In the past, when we get an error fetching a GitHub app, we assume the app has been deleted and delete all it's installations from the database. This caused issues for one of our customers.
Manual testing. 
I added a GitHub app for Commit Signing, manually triggered the worker to ensure it refreshes it's installations. Then I faked an error in the code, to see if the installations got deleted when a refresh occurred (they didn't). They only got deleted when the client returns a 404.

batches: change criteria for deleting GitHub apps from the database

---

WORKSPACE
dev/schema_migrations.bzl
dev/tool_deps.bzl
internal/database/migration/shared/BUILD.bazel
internal/database/migration/stitch/archives.go

Does what it says on the tin
Caveat:
As this doesn't use the built-in downloaders, this probably cant make use of the repository cache. While it won't refetch it every single time (there is _some_ degree of caching), I'm not sure what will cause it to not use the cached one and refresh it. Its a very fast operation though.
See https://github.com/bazelbuild/bazel/issues/19267
`bazel build //internal/database/migration/shared:generate_stitched_migration_graph`

bazel: move schema migrations fetching from GCS to bazel repository

---

CHANGELOG.md
client/web/src/enterprise/batches/settings/CommitSigningIntegrationNode.tsx
client/web/src/enterprise/batches/settings/CommitSigningIntegrations.tsx
client/web/src/enterprise/batches/settings/backend.ts
cmd/frontend/graphqlbackend/githubapps.go
cmd/frontend/graphqlbackend/githubapps.graphql
cmd/frontend/internal/githubapp/resolver.go

This gives site admins the ability to refresh a commit signing app, instead of waiting for the periodic worker (which runs every 24 hours) to kick of the installation sync.
Add a GitHub app on Sourcegraph for Commit Signing.
There should be a `Refresh` button to refresh installations on the app.
If the app is installed on any new org or account, the installations will be added to the database after the `Refresh` operation is done.

batches: allow refreshing commit signing apps installation

---

client/web/src/auth/SignInPage.tsx

- Fixes https://github.com/sourcegraph/accounts.sourcegraph.com/issues/520
Add the `returnTo` URL param if we have a return URL.
- Tested the logic locally with several test URLs with their query string empty and not.
- Couldn't test it end-to-end because I have issues with my local env I haven't resolved.

Set returnTo when redirecting to a third-party auth provider on dotcom

---

dev/managedservicesplatform/internal/resource/alertpolicy/BUILD.bazel
dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
dev/managedservicesplatform/internal/resource/alertpolicy/conditionbuilder.go
dev/managedservicesplatform/internal/resource/alertpolicy/conditionbuilder_test.go
dev/managedservicesplatform/internal/resource/alertpolicy/metricabsence.go
dev/managedservicesplatform/internal/resource/alertpolicy/thresholdaggregation.go
dev/managedservicesplatform/managedservicesplatform.go
dev/managedservicesplatform/spec/BUILD.bazel
dev/managedservicesplatform/spec/environment.go
dev/managedservicesplatform/spec/environment_test.go
dev/managedservicesplatform/stacks/monitoring/cloudsql.go
dev/managedservicesplatform/stacks/monitoring/common.go
dev/managedservicesplatform/stacks/monitoring/job.go
dev/managedservicesplatform/stacks/monitoring/monitoring.go
dev/managedservicesplatform/stacks/monitoring/redis.go
dev/managedservicesplatform/stacks/monitoring/service.go

Prevents the issue we ran into in https://sourcegraph.slack.com/archives/C05GJPTSZCZ/p1707907271464879 from going unnoticed again:
1. Adds a `MetricAbsence` condition type for us to use internally
a. In doing so, I realized we can shape our abstraction around the GCP UI with the new `ConditionBuilder` type. This is basically what you see in the UI when you create a policy by hand. This is now shared between `MetricAbsence` and `ThresholdAggregation`
2. Adds `FindMaxCronInterval()` on the job schedule spec, which validates cron specs, tries to ensure they are of a certain window, and provides the "maximum interval" it detects.
3. Use `FindMaxCronInterval()` to define an alert where if no executions are detected within that interval + 10 minutes, the alert will fire.
`sg msp generate -all` …

msp/monitoring: add MetricAbsence condition type, add missing executions alert

---

internal/search/query/parser_test.go

This is the first PR in a series to replace autogold with simpler table based tests where it makes sense.
Why?
Autogold is great for regression tests or when the expected result is tedious to write out, but it is more difficult to parse visually and it is not as convenient during debugging.
Test plan:
all tests pass

search: replace autogold with table based test

---

cmd/telemetry-gateway/internal/events/BUILD.bazel
cmd/telemetry-gateway/internal/events/events.go
cmd/telemetry-gateway/internal/server/server.go

Telemetry Gateway recently received an event that, when composed as JSON with license key and everything, seems to be exceeding 10MB in size, which is the Pub/Sub limit: https://sourcegraph.slack.com/archives/C06CCJR4K9R/p1707986358501489?thread_ts=1707984656.886109&cid=C06CCJR4K9R
Pending a decision from the team (https://sourcegraph.slack.com/archives/CN4FC7XT4/p1707986514302069), let's record some details here for now:
1. Return special annotate error with additional details on clearly oversized events, and don't both trying to send it to pub/sub, as that may cause problems if this continues
2. Improve our logger such that all events in a stream are annotated with the instance ID
Note the TODO:
```go
// TODO: We can't error forever, as the instance will keep trying to
// deliver this …
```

telemetry-gateway: fast-error on oversized event, improve logging

---

.buildkite/pipeline.yml

This change mostly affects the Aspect Pipeline, moving the initial steps being defined in the UI to having them in the `buildkite.yml` file.
Once this is merged the UI steps will be updated to prefer uploading the pipeline rather than raw steps
- [sourcegraph pipeline](https://buildkite.com/sourcegraph/sourcegraph/builds/262493)
- [aspect pipeline](https://buildkite.com/sourcegraph/aspect-experimental/builds/8813) on this branch - notice that the pipeline is uploaded
- [aspect pipeline](https://buildkite.com/sourcegraph/aspect-experimental/builds/8814) not on this branch - notice different steps being used

ci: generate different steps depending on what pipeline we're in

---

cmd/telemetry-gateway/internal/events/events.go

🤦 wrapping nil error always returns nil - fixup for #60546 
n/a

telemetry-gateway: fixup error initialization

---

cmd/frontend/graphqlbackend/product_license_info.go
cmd/frontend/graphqlbackend/product_subscription_status.go
cmd/frontend/graphqlbackend/site_flags.go
cmd/frontend/internal/licensing/enforcement/users.go
cmd/worker/internal/licensecheck/check.go
cmd/worker/internal/licensecheck/check_test.go
internal/licensing/plans.go

Closes #60359 
The free license should not be doing license verification checks.
Add unit test

Don't verify license on free plan

---

cmd/gitserver/internal/cleanup.go
internal/database/gitserver_repos.go
internal/database/gitserver_repos_test.go

I was looking at some logs and noticed the gitserver janitor job constantly logging that it failed to lookup a repo. I checked and it correctly said these repos no longer existed, but this was logging when things go wrong. Turns out in a refactor from August 2022 (cd1131217d73) we wrapped the error type in scanGitserverRepos, but didn't update the call sites of it to take into account wrapped errors.
This means since then lookups of missing repos via the normal GetBy methods have not been returning missing repo errors! This likely has a bunch of ramifications that I haven't explored yet.
In the case of gitserver janitor, I believe we would never delete missing repositories now. There is a decent chance this will free up a bunch of disk space for all sourcegraph instances. Atleast for the …

database: return not found error for repos.GetBy{ID,Name}

---

cmd/telemetry-gateway/internal/events/BUILD.bazel
cmd/telemetry-gateway/internal/events/events.go
cmd/telemetry-gateway/service/BUILD.bazel
cmd/telemetry-gateway/service/service.go

Follow-up to https://sourcegraph.slack.com/archives/C06CCJR4K9R/p1707987648387399
`sg run telemetry-gateway`, metric initialization works (the main potential failure point)

telemetry-gateway: add metric for published message sizes

---

internal/workerutil/worker.go

This seems quite noisy and clearly like a debug signal, so moving it to debug level instead.
```
[         worker] INFO worker.repo-perms-syncer workerutil/worker.go:329 Dequeued record for processing {"TraceId": "fdcacc27c3b381f2746ff76e8573eaed", "SpanId": "b98a6da2a9121465", "name": "user_permissions_sync_job_worker", "id": "208561"}
```
No noise in my terminal anymore.

Reduce info logspam from logging in worker

---

cmd/cody-gateway/internal/httpapi/completions/upstream.go

Follow-up for https://github.com/sourcegraph/sourcegraph/pull/60547:
- lower case comparison
- log the actual patterns on start-up
- early exit

Follow-up fixes for detection

---

internal/completions/client/awsbedrock/BUILD.bazel
internal/completions/client/awsbedrock/bedrock.go
internal/completions/client/awsbedrock/bedrock_test.go

This allows a full endpoint to provided to the completions configuration instead of a aws region.  The reason for this change is to support scenarios where the default bedrock endpoints are not reachable from the frontend deployment.  When specifying the endpoint it is necessary to set the AWS_REGION environment variable to the region that the Bedrock models are in.
These commits manually were tested in a reference environment with a tunnel between GCP and AWS that approximated the type of environment this is intended to support

Allow Bedrock completions provider to accept a full endpoint url

---

cmd/server/BUILD.bazel
cmd/server/image_tests/test_services.sh
cmd/server/shared/shared.go

I noticed this comment that we remap the binary name in bazel for server. Well we can just update server and make it consistent with everything else.
Test Plan: CI

server: use syntect_server binary

---

cmd/gitserver/internal/git/gitcli/exec.go
cmd/gitserver/internal/git/gitcli/object.go
cmd/gitserver/internal/git/gitcli/object_test.go
cmd/gitserver/internal/git/gitcli/resolverevision.go

- Makes it use the getCommand helper which runs proper command args validation and is embedded in observability
- Makes the test suite simpler and more aligned
Added/modified tests, existing other tests still pass.

gitserver: Modernize GetObject

---

cmd/telemetry-gateway/internal/server/server.go

Discussed [here](https://sourcegraph.slack.com/archives/CN4FC7XT4/p1707990139798159) - this helps with identifying the impact of issues and diagnostics, as it can be tricky to link and instance ID back to a customer, and not all licenses have a Salesforce ID yet it seems.
We only log the URL once, instead of attaching it to the logger, to avoid having this sent to Sentry for now (out of an abundance of precaution)
n/a

telemetry-gateway: log reported instance URL in request start log

---

internal/codeintel/autoindexing/internal/inference/libs/indexes.go
internal/codeintel/autoindexing/internal/inference/libs/update-shas.sh
internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Gradle.yaml
internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_Maven.yaml
internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_SBT.yaml
internal/codeintel/autoindexing/internal/inference/testdata/JVM_project_with_lsif-java.json.yaml
internal/codeintel/autoindexing/internal/inference/testdata/Nested_JVM_project_WITHOUT_top-level_build_file.yaml
internal/codeintel/autoindexing/internal/inference/testdata/Nested_JVM_project_with_top-level_build_file.yaml

Previously, I changed the code to use YAML snapshots instead of
hard-coded structs, so replacing the SHAs in tests just involves
running the test with the `-update` flag documented in the code
instead of tweaking Go code.
n/a

build: Update snapshot outputs when updating SHAs

---

dev/backcompat/bazel-backcompat.sh
dev/backcompat/patch_flakes.sh
dev/ci/internal/ci/misc_operations.go

Missed a series of failures on https://buildkite.com/sourcegraph/sourcegraph-backcompat/builds/23295
Primary build should wait for this step to complete

backcompat: make step non-async

---

dev/release/src/release.ts
dev/release/src/static-updates.ts

The Graph team can handle updating the SHAs on an as-needed
basis, similar to how it is done on the main branch.
Discussed here: https://github.com/sourcegraph/sourcegraph/pull/60542
n/a

release: Remove indexer updates from release process

---

doc/dev/background-information/scim_postman_collection.json

Removed a comma that prevents Postman from importing the collection as valid.
- Download Postman
- Attempt to import new collection JSON (copy and paste the text into the import window)
- Collection should be imported as valid (previously it would not be)
[Preview Link](https://docs.sourcegraph.com/@nb/remove-errant-comma-from-scim-postman)

Remove errant comma from scim_postman_collection.json

---

dev/managedservicesplatform/stacks/cloudrun/internal/builder/service/service.go

context: https://sourcegraph.slack.com/archives/C05GJPTSZCZ/p1708009262460989
https://cloud.google.com/run/docs/rollouts-rollbacks-traffic-migration#send-to-latest
per GCP docs
it rendered:
```diff
--- a/services/cloud-ops/terraform/prod/stacks/cloudrun/cdk.tf.json
+++ b/services/cloud-ops/terraform/prod/stacks/cloudrun/cdk.tf.json
@@ -379,7 +379,13 @@
"connector": "${google_vpc_access_connector.cloudrun-connector.self_link}",
"egress": "PRIVATE_RANGES_ONLY"
}
-        }
+        },
+        "traffic": [
+          {
+            "percent": 100,
+            "type": "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
+          }
+        ]
}
},
"google_cloud_run_v2_service_iam_member": {
```
Then, we can test it manually by:
- clickops and pin to an older revision
- run terraform apply, it should …

msp: always route traffic to the latest revision on deploment

---

docker-images/syntax-highlighter/BUILD.bazel
docker-images/syntax-highlighter/syntect_server_entrypoint.sh

All our containers should be using tini as PID 1 to cleanup zombies. In the case of syntax-highlighter we did not. Additionally we did some janky inline shell script so we could inject the $WORKERS envvar as an argument.
This commits moves the janky script into an entrypoint script and calls it via tini. Additionally it uses exec so we don't have a parent shell messing with signals.
I picked the name syntect_server_entrypoint since I had some concerns this file would end up in the server docker image, so wanted to give it a unique name. This may make it possible for us to use this script as well in server if we choose to.
Test Plan: built the image and ran it. Then checked we had the process running with child workers correctly.
``` shell
bazel build …
```

syntax-highlighter: use tini and entrypoint script

---

cmd/frontend/internal/httpapi/httpapi.go
cmd/frontend/internal/httpapi/internal.go
internal/api/BUILD.bazel
internal/api/httpapi_schema.go
internal/api/internalapi/client.go
internal/codemonitors/background/email.go
internal/conf/client.go
internal/env/env.go
internal/txemail/txemail.go
internal/txemail/txtypes/types.go

We no longer need this endpoint. Also found a few other things related to internalapi on the way that could use a cleanup.
Integration tests should verify that conf works just as before.

Cleanup internalapi after gRPC migration

---

cmd/executor/vm-image/_ami.push.sh

Causing error to not cause the script to fail if the file was missing
https://stackoverflow.com/questions/44014857/function-invocation-in-for-loop-does-not-fail-even-with-set-e

executors: fix AMI push script for when aws_regions.json missing

---

client/web/src/cody/subscription/CodySubscriptionPage.module.scss
client/web/src/cody/subscription/CodySubscriptionPage.tsx
client/web/src/cody/subscription/UpgradeToProModal.tsx

closes: https://github.com/sourcegraph/accounts.sourcegraph.com/issues/560
Remove Strikethrough from $9.
Ran locally

Remove strikethrough

---

cmd/executor/docker-mirror/_ami.push.sh
dev/db/drop-test-databases.sh
docker-images/alpine-3.14/update-all-dockerfiles.sh

For same reason as https://github.com/sourcegraph/sourcegraph/pull/60610, cleaning up the remaining scripts
https://stackoverflow.com/questions/44014857/function-invocation-in-for-loop-does-not-fail-even-with-set-e

scripts: dont run subshell in for loop

---

cmd/executor/docker-mirror/BUILD.bazel
cmd/executor/docker-mirror/_ami.push.sh
cmd/executor/vm-image/BUILD.bazel
cmd/executor/vm-image/_ami.push.sh

Bazel ami.push targets were missing the file and pointing at wrong location
Tested manually on buildkite agent by @jhchabran

executors: fix path to aws_regions.json in ami.push targets

---

client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss

The background color behind the "Move filters to query" button is too prominent and has been updated to match the rest of the panel.
(Remains unchanged, `code-bg` and `color-bg-1` both output white in light mode)
(Remains unchanged, `code-bg` and `color-bg-1` both output white in light mode)
- Locally tested

Search results: Update filter actions background

---

cmd/gitserver/internal/cleanup.go
cmd/gitserver/internal/integration_tests/tree_test.go
cmd/gitserver/shared/shared.go

- App is no longer, and janitor really has to run, we shouldn't comment it out
- Tree test double-initialized the gitserver
- Removed duplicate reponame variable
Small code style changes, CI will find issues.

gitserver: Small code cleanup

---

cmd/frontend/graphqlbackend/user.go
cmd/frontend/internal/httpapi/ssc.go
internal/cody/rate_limits.go

The refresh rate limits API on dotcom always returns 500 when it fails to update rate limits on dotcom.
Related Issue: https://github.com/sourcegraph/accounts.sourcegraph.com/issues/562
This PR updates the API to return a better error message and status.
This will also propagate the 429 error it receives from the gateway to the caller SSC. 
This will allow SSC to retry at a later time and do better error logging in sentry. 
SSC side of PR: https://github.com/sourcegraph/accounts.sourcegraph.com/pull/579
ran locally

Return better error and status code from dotcom refresh limits api

---

cmd/gitserver/internal/perforce/changelist.go

This seems to have been accidentally misnamed in the recent refactor to the p4 command pattern.
Unfortunately this has also made it into the 5.3 release, so we'll have to backport it.
Code review, we currently cannot write perforce "unit" tests.

perforce: Fix changelist host setting

---

internal/grpc/streamio/BUILD.bazel
internal/grpc/streamio/streamio.go
internal/grpc/streamio/streamio_test.go

As I dug into why we're allocating a ton of memory in io.Copy when forwarding the stdout from exec calls to the writer, I found that we allocate 128kb every time, while many calls actually only write 40 bytes (a commit SHA).
I then looked at gitaly and noticed that we use a very old version of their implementation and that they saw the same on their end and fixed it.
So here we go, updating it to the latest.
Note that we currently don't need the NewSyncWriter, but I kept it anyways, maybe it reminds us of the importance if we ever need it.
List of commits from gitaly: https://gitlab.com/gitlab-org/gitaly/-/commits/master/streamio/stream.go?ref_type=heads
---
streamio: Implement synchronized writer
Writing to gRPC streams concurrently isn't allowed, which is why we need to synchronize …

grpc: Bump streamio code to latest version

---

client/web-sveltekit/src/routes/search/+page.ts
client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte

This adds a display limit (currently unlimited) and a line length limit (currently unlimited) to the search requests from the Svelte webapp. Currently, we're trying to stream the entire result set back to the client, which can be quite large. Additionally, rendering and highlighting long lines can be expensive.
Clicked around, testing that the webapp no longer seized up on large result sets.

Svelte: add display limit and content length limit

---

client/web/src/storm/pages/SearchPage/CodyUpsell.tsx

Hope you're the right person Bolaji, GitHub suggested you. Should just be a stamp.
See discussion at https://sourcegraph.slack.com/archives/C0678ATBXCG/p1708381486675609
CI

remove ?utm_source=server for dotcom -> dotcom CTA link

---

dev/sg/internal/std/BUILD.bazel
dev/sg/internal/std/output.go
lib/output/capabilities.go
lib/output/output.go
lib/output/outputtest/BUILD.bazel
lib/output/outputtest/buffer_test.go

For tests we do not want to use the detection on os.Stdout to change what output we capture and assert against. In particular when running the sg tests for me under emacs's compilation-mode I get failures due to extra escape codes.
This is a different take on ensuring tests do not have Isatty enabled. The previous attempt used the passed in writer to determine this. However, on further inspection of call sites we somewhat regularly captures the output and then only show it if something went wrong. In those cases we should preserve Isatty of stdout so the errors look prettier.
Test Plan: go test -short ./...

lib/output: ForceTTY can be used to disable Isatty

---

dev/sg/internal/check/common.go
dev/sg/internal/check/helpers.go
shell.nix

If using nix develop we can defer to our nix environment correctly installing bazel. In particular on linux nix directly installs the correct version of nix and we do not use bazelisk.
Test Plan: "sg start enterprise-bazel" on nixos

sg: bazelisk check skipped on nix develop

---

client/shared/src/codeintel/legacy-extensions/language-specs/cpp.ts
client/shared/src/languages.ts
cmd/symbols/squirrel/language-file-extensions.json
internal/codeintel/uploads/shared/indexers2.go

Fixes https://github.com/sourcegraph/sourcegraph/issues/60661
Hovers start showing up on my local instance
You can test that they currently don't work on Sourcegraph.com
https://sourcegraph.com/github.com/Fytch/ProgramOptions.hxx@cafa8436dd96a65f1f4c1b921eef90dd85b58197/-/blob/include/ProgramOptions.hxx?L272

squirrel: Allow .hxx extension for C++

---

docker-images/syntax-highlighter/src/main.rs

With this change, we can remove the extra shell layer around the highlighter.
`cd docker-images/syntax-highlighter` and compare output of `cargo run --bin syntect_server` and `QUIET=true cargo run --bin syntect_server`. The latter should not have any logging as requested in https://github.com/sourcegraph/sourcegraph/issues/60407#issuecomment-1952248780

syntax-highlighter: Turn off Rocket logging with QUIET=true

---

cmd/cody-gateway/internal/httpapi/completions/upstream.go

When we detect NSFW content / session control phrases, include information about what was detected.
- local testing 
- e2e tests

Store data about profanities and session control phrases

---

docker-images/syntax-highlighter/src/main.rs

This reverts commit c19a432ab777335573aa4e6ffcf4668f1cb7be8a.
Run the following locally:
```
bazel build //docker-images/syntax-highlighter:image_tarball
docker load --input $(bazel cquery //docker-images/syntax-highlighter:image_tarball --output=files)
docker run --detach --name=syntax-highlighter -p 9238:9238 syntect-server:candidate
curl http://localhost:9238/health
```
This prints OK after this revert, but not before.

Revert "syntax-highlighter: Turn off Rocket logging with QUIET=true (#60660)"

---

client/web/src/cody/chat/CodyChatPage.tsx
client/web/src/cody/widgets/CodyRecipesWidget.tsx
client/web/src/marketing/toast/CodySurveyToast.tsx

`/get-cody` is just a redirect to `/cody/manage`.
Cody clients probably contain a lot of links to `/get-cody` so we still need that redirect (and will need it for a year plus) but within the web app, we can go to the management page directly.
Not tested yet!

Replace /get-cody links with /cody/manage

---

cmd/searcher/internal/search/search_regex.go

In #59331, we refactored the searcher logic to support AND/ OR patterns in
searcher. While doing so, we accidentally regressed on an optimization that
avoids loading file content when the pattern is empty.
We now have a benchmark for empty patterns, but this benchmark was added
recently and wasn't run during that refactor.
Note: this will be backported to 5.3.
Ran new benchmarks (see below commment)

Searcher: fix optimization for empty patterns

---

cmd/searcher/internal/search/search_regex.go

In #59331, we refactored the searcher logic to support AND/ OR patterns in
searcher. While doing so, we accidentally regressed on an optimization that
avoids loading file content when the pattern is empty.
We now have a benchmark for empty patterns, but this benchmark was added
recently and wasn't run during that refactor.
CI and benchmarks

[Backport 5.3] Searcher: fix optimization for empty patterns

---

cmd/frontend/internal/dotcom/productsubscription/tokens_db.go
internal/database/migration/shared/data/stitched-migration-graph.json
internal/database/schema.json
internal/database/schema.md
migrations/frontend/1708596613_access_tokens_double_hash_index/down.sql
migrations/frontend/1708596613_access_tokens_double_hash_index/metadata.yaml
migrations/frontend/1708596613_access_tokens_double_hash_index/up.sql
migrations/frontend/squashed.sql

This adds an index that can be used to reduce the number of SHA256 hashes computed by CodyGatewayDotcomUserByToken, reducing query latency and CPU usage.
Slack [conversation](https://sourcegraph.slack.com/archives/C05497E9MDW/p1708526972279079).
Query plan after:
```
Nested Loop  (cost=6006.56..9238.90 rows=1248 width=20) (actual time=0.719..0.961 rows=0 loops=1)
->  HashAggregate  (cost=6006.14..6018.62 rows=1248 width=8) (actual time=0.719..0.960 rows=0 loops=1)
Group Key: t2.id
->  Gather  (cost=1023.02..6003.02 rows=1248 width=8) (actual time=0.710..0.951 rows=0 loops=1)
Workers Planned: 1
Workers Launched: 0
->  Nested Loop  (cost=23.02..4878.22 rows=734 width=8) (actual time=0.329..0.330 rows=0 loops=1)
->  Nested Loop  (cost=22.59..3246.99 rows=735 width=12) (actual …
```

Add double hash index for CodyGatewayDotcomUserByToken

---

internal/search/result/symbol.go
internal/search/zoekt/indexed_search.go
internal/search/zoekt/indexed_search_test.go

A query like `type:symbol repo link picker` is translated into zoekt as
```
(and sym:substr:"repo" sym:substr:"link" sym:substr:"picker")
```
If you have a symbol `RepoLinkPicker` Zoekt's result type will model this as 3 matches (which is correct) but all with the same `SymbolInfo.` When we convert this into Sourcegraph's symbol information we only want to have a match per symbol. Before this change we would translate this into 3 results, internally each having a different Column the match appears at. By the time it would reach the user via the streaming API the column is gone and we just have symbol information, which means effectively we had 3 duplicate results.
This commit makes what Zoekt returns match the expectations of Sourcegraph's symbol results. Note: we have to use a slight …

search: deduplicate symbol results from zoekt

---

client/web/src/cody/management/CodyManagementPage.tsx

Issue: https://sourcegraph.slack.com/archives/C05SZB829D0/p1708613278533909
Now that the trial has ended the users who opted Pro earlier but have not put in their credit cards yet are still shown having Pro tier along with the usage limits counter. This is confusing. 
This PR updates the subscription status text to "Your Cody Pro trial has ended" and changes the trier to "Free".
**Before**
**After** 
Ran locally

Fix trial ended text

---

internal/tracer/oteldefaults/exporters/otlp.go

Using the `http/proto` protocol caused a panic because the client was nil after this switch. This just modifies the switch to return an error instead.
N/A

Chore: error on unknown protocol rather than panic

---

dev/tool_deps.bzl

Update src-cli to 5.3.0 for executors. 
While we already tagged 5.3.1, it hasn't been staged yet, meaning the deployments methods are not yet updated and we have time to rebuild the executors images, so it includes that commit. 
5.3.1 is tagged on the latest commit on branch `5.3`, so no other changes will go in.  
CI + inspect docker container to check the resulting version.

Bump src-cli to 5.3.0 for executors

---

BUILD.bazel
dev/ci/bazel-configure.sh
dev/ci/internal/ci/config.go

I've been unable to reproduce why `sg lint` appears to be running more lints than expected for a given diff, so lets add some friendly debug logging so we can investigate 😊 
:eye: CI :eye:

ci: debug logging for sg lint changed files

---

doc/_resources/assets/docsite.css
doc/_resources/templates/root.html

This PR makes the docs banner fixed as you scroll. Also, fix the margin for breadcrumbs with the banner notice. 
- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1708634123363059?thread_ts=1708093272.257949&cid=C01DXLN3D0T
Docs banner fixed
[Preview Link](https://docs.sourcegraph.com/@fix-banner)

Fix the docs banner

---

internal/honey/event.go
internal/honey/honey.go

I found this very useful in my dev environment to debug some searches. Initially I added in a new event type. However, we do some transformations in our eventWrapper which I wanted to preserve. So instead at time of Send we decide if we should send to honeycomb or just log to stderr.
Note: this produces a lot of log output due to background processes running commands against git/etc.
Test Plan: "HONEYCOMB_LOCAL=true sg start enterprise" and see events in console when I do searches.

honey: HONEYCOMB_LOCAL which logs events to stderr

---

internal/licensing/codygateway.go
internal/licensing/codygateway_test.go

Increase default Code Completions limit for Enterprise Cody customers to 1000/user/day.
- existing unit tests were updated
- tested manually

Increase Enteprise Code Completions limit to 1000

---

client/web/src/cody/management/CodyManagementPage.tsx

Fixes the problem mentioned [here](https://sourcegraph.slack.com/archives/C06HHK23QR4/p1708082073088569), that this button:
should link the SSC site, not dotcom's /subscription page.
I've also fixed a few linter warnings.
Didn't test this because my dev env is still in ruins. I'll want to get it confirmed first that we need this, and then I can test it better.

Link to SSC

---

internal/insights/scheduler/backfill_state_inprogress_handler.go
internal/insights/scheduler/backfill_state_inprogress_handler_test.go

The computed state is so cheap that we might as well just compute it each time we want to access it. The main difference is we won't log insights backfiller changing. However, the old code just always logged at startup and whenever any site config changed. It also feels somewhat low value, so I think its fine just not to log.
Additionally the old code protected writes to task.config via a mutex, but never used that mutex for reads. So it was in fact racey.
FYI I came across this because I was looking into reducing the logspam in our product.

insights: remove config watcher

---

internal/search/backend/metered_searcher.go
internal/trace/trace.go

This commit has a few changes to how we do telemetry for zoekt.
- SearchOption attributes are part of span creation.
- SearchOption and Stats attributes are filtered to remove default values. This mirrors how we log in net/trace which I find useful when reading options.
- SearchOption add missing fields.
- EndWithErrIfNotContext helper introduced and used for Search and List.
- List uses same pattern for telemetry as Search
- List logs actor
- List correctly logs repos count and always logs stats.crashes.
Test Plan: go test and "HONEYCOMB_LOCAL=true sg start" followed by a search. I then visually eyeballed the log output for events.
See details for the events logged in my devserver
<details>
```
EVENT search-zoekt
actor: 1
category: ListAll
duration_ms: 2
query: TRUE
repos: 12 …
```

search: consistent telemetry between honeycomb and tracing for zoekt

---

internal/search/symbol/symbol.go
internal/search/zoekt/indexed_search.go

We only ever ask for ChunkMatches and we more than likely will evolve the Zoekt API so it is the default and possible remove support for LineMatches.

search: remove support for reading LineMatches

---

internal/completions/client/observe.go

Discussion at https://sourcegraph.slack.com/archives/C05BGNBEPKL/p1708975582881559
>Since the start of the month, we recorded 29.6m cody.completions : stream events as of Friday from the Sourcegraph backend ([see here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ee9199762853c10e6a737f341ceb0808ceca20ea/-/blob/internal/completions/client/observe.go?L45-52)).  
>
>This single event represents 24% of all rows in our table. 
CI, and ran Sourcegraph locally to confirm no errors

Remove high volume event that isn't used

---

client/web/src/LegacySourcegraphWebApp.tsx

There was a typo in the context building that caused the Code Graph Data button on the repo page to be disabled. This just fixes that typo.

Chore: fix typo causing code intel to be disabled

---

client/web/src/cody/management/CodyManagementPage.tsx

Fixes [this](https://sourcegraph.slack.com/archives/C05PC7AKFQV/p1709108448338019) problem where the "manage subscription" button on `/cody/manage` didn't link to the right page.
The problem was a missing `event.preventDefault()` call but I also noticed that on hovering the button, the wrong URL was displayed as the target, so fixed that, too.
Tested it locally.

Fix Cody PLG "Manage subscription" button

---

cmd/frontend/internal/app/ui/help.go
cmd/frontend/internal/app/ui/help_test.go

It was hardcoded to 5080 because the docs were included in the monorepo. Now that docs are in their own repo with their own web app, they use a different port.
Currently, that is the default Next.js port 3000.
That might change, depending on what developers do in the docs repo. Note that this change means that in order to use the new docs, you will need to clone the sourcegraph/docs repo, and follow its README to run it in dev mode.
- clone docs repo (https://github.com/sourcegraph/docs)
- build and run docs site according to its README
- `asdf install`
- `pnpm install`
- `pnpm run dev`
- run `sg start`
- click on help link (I used https://sourcegraph.test:3443/help/api/graphql)
- verify that it loads the new docs site

Update help router for dev to use new docs repo

---

internal/compute/query.go
internal/search/job/jobutil/job.go
internal/search/query/labels.go
internal/search/query/printer.go
internal/search/query/transformer.go
internal/search/query/transformer_test.go
internal/search/smartsearch/rules.go

It seems we lazily used IsAlias as the annotation before since we had the invariant that for Patterns the only time that happens is for content. However, this was really confusing to work out and its easy to add in a new annotation.
Follow up from https://github.com/sourcegraph/sourcegraph/pull/60782

search: use annotation IsContent for "content:" patterns

---

client/web/src/components/SelfHostedCta/SelfHostedCta.story.tsx
client/web/src/components/SelfHostedCta/SelfHostedCta.tsx
client/web/src/components/WebStory.tsx
client/web/src/user/settings/aboutOrganization/AboutOrganizationPage.story.tsx
client/web/src/user/settings/aboutOrganization/AboutOrganizationPage.tsx
client/web/src/user/settings/routes.tsx

Context:
`sg start`
visit page

v2t: add v2t to the rest of src/components

---

client/web/src/enterprise/codeintel/admin/AdminCodeIntelArea.tsx
client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPage.tsx
client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPolicyPage.tsx
client/web/src/enterprise/codeintel/configuration/pages/CodeIntelInferenceConfigurationPage.tsx
client/web/src/enterprise/codeintel/configuration/pages/CodeIntelRepositoryIndexConfigurationPage.tsx
client/web/src/enterprise/codeintel/dashboard/pages/GlobalDashboardPage.tsx
client/web/src/enterprise/codeintel/dashboard/pages/RepoDashboardPage.tsx
client/web/src/enterprise/codeintel/indexes/pages/CodeIntelPreciseIndexPage.tsx
client/web/src/enterprise/codeintel/indexes/pages/CodeIntelPreciseIndexesPage.tsx
client/web/src/enterprise/codeintel/ranking/pages/CodeIntelRankingPage.tsx
client/web/src/enterprise/cody/repo/CodyRepoArea.tsx
client/web/src/enterprise/repo/enterpriseRepoContainerRoutes.tsx

Note that this PR builds on top of https://github.com/sourcegraph/sourcegraph/pull/60382/files#diff-a354ffdebcc1d98d0e3632043847fe31b6b4a09ac8586b777538ebf182218a6a because that PR hasn't been merged yet and included edits to a number of files in this folder.
Context:
* …

Add v2t to src/enterprise/codeintel

---

client/web/src/enterprise/code-monitoring/CodeMonitorList.tsx
client/web/src/enterprise/code-monitoring/CodeMonitoringGettingStarted.tsx
client/web/src/enterprise/code-monitoring/CodeMonitoringPage.story.tsx
client/web/src/enterprise/code-monitoring/CodeMonitoringPage.test.tsx
client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.story.tsx
client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.test.tsx
client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.story.tsx
client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.test.tsx
client/web/src/enterprise/code-monitoring/ManageCodeMonitorPage.tsx
client/web/src/enterprise/code-monitoring/global/GlobalCodeMonitoringArea.tsx

Context:
`sg start`
visit page

V2t src/enterprise code monitoring

---

client/web/src/LegacyLayout.tsx
client/web/src/components/fuzzyFinder/FuzzyFinder.mocks.tsx
client/web/src/components/fuzzyFinder/FuzzyFinder.tsx
client/web/src/components/fuzzyFinder/FuzzyModal.tsx
client/web/src/storm/pages/LayoutPage/LayoutPage.tsx

Context:
`sg start`
visit page

v2 telemetry: add v2 telemetry to src/components/fuzzyFinder

---

client/web/src/components/gitHubApps/CreateGitHubAppPage.tsx
client/web/src/components/gitHubApps/GitHubAppPage.tsx
client/web/src/components/gitHubApps/GitHubAppsPage.tsx
client/web/src/enterprise/batches/settings/BatchChangesCreateGitHubAppPage.tsx
client/web/src/site-admin/SiteAdminGitHubAppsArea.tsx
client/web/src/site-admin/routes.tsx

Context:
`sg start`
visit page

v2t: add v2t to src/components/gitHubApps

---

cmd/gitserver/internal/git/observability.go

We started logging these, but RevisionNotFound is actually a well-expected case so let's not log it. NotFound errors from os are also expected for some methods, so skipping over those as well.
Closes https://github.com/sourcegraph/sourcegraph/issues/60598
Ran the stack and checked for logspam.

gitserver: Reduce logspam from expected errors

---

client/web/src/end-to-end/code-intel/repository-component.test.ts

This test seemed to have caused a lot of failures since March 1st (2024).  I looked at a couple of test failures since then and they were all related to that test. `//testing:e2e_test` had been quite reliable until then.
I wasn't able to identify what the issue is.
[Test analytics](https://buildkite.com/organizations/sourcegraph/analytics/suites/sourcegraph-bazel/tests/0189f3a8-28d8-7392-be6a-e1ab56d20fab?branch=all+branches)
CI

ci: Disable flaky 'highlights correct line for Go' test

---

internal/usagestats/aggregated_cody.go

Fixes: https://github.com/sourcegraph/sourcegraph/issues/60825
If there are no entries in the cody stats table (as is the case if it hasn't been used yet), events will be nil:
https://github.com/sourcegraph/sourcegraph/blob/33b92afbc955f613ff4b9f1d099747b60fdf6564/internal/database/event_logs.go#L1444-L1449
If this is the case, then we simply return the default value of the aggregated cody stats type:
```
events, err := db.EventLogs().AggregatedCodyUsage(ctx, time.Now().UTC())
return nil, err
}
stats := &types.CodyUsageStatistics{
Daily:   newCodyEventPeriod(),
Weekly:  newCodyEventPeriod(),
Monthly: newCodyEventPeriod(),
}
if events == nil {
// If there are no events, return the empty stats.
return stats, nil
}
```
It seems like these stats are only used for bigquery …

frontend: GetAggregatedCodyStats: add nil guard for events

---

client/web/src/end-to-end/code-intel/repository-component.test.ts

See #60823. Looking at [test analytics](https://buildkite.com/organizations/sourcegraph/analytics/suites/sourcegraph-bazel/tests/0189f3a8-28d8-7392-be6a-e1ab56d20fab?branch=all+branches) it appears that now the other symbol sidebar test causes issues. This PR disabled it too (I think we can keep the existing issue to track both).
CI

ci: Disable typescript symbol sidebar test

---

cmd/gitserver/internal/vcssyncer/BUILD.bazel
cmd/gitserver/internal/vcssyncer/packages_syncer.go

Since we don't validate versions, we have about 170k packages on dotcom that constantly fail cloning. This is putting unnecessary load at it, so until we fix this, let's accept that some packages will have a few missing versions, in favor of having the package cloned at all, and a calmer system.
Will monitor dotcom.

packages: Temporarily disable failing for invalid versions on dotcom

---

cmd/gitserver/internal/ensurerevision.go
cmd/gitserver/internal/mocks_test.go
cmd/gitserver/internal/repo_info_test.go
cmd/gitserver/internal/server.go
cmd/gitserver/internal/server_grpc.go
cmd/gitserver/internal/server_test.go

This PR started as a "oh let me wrap the context error in a nice message".
Then, as I dug in, I noticed that we did very messy things with context along the way, ultimately causing clones to be canceled while a request loses interest, making us have to start over, and those nicely wrapped errors just not bubbling up. Instead, we would get cryptic "signal: killed" errors now.
I want to come back at this again and check if we could rewrite these errors in the presentation layer only, but for now I think this is a fix that's workable. We should be coming back at this when we look at scheduler.
I'll include inline comments to explain the changes in detail.
Closes https://github.com/sourcegraph/sourcegraph/issues/56915
Test suites still pass, the integration test suite will cover it E2e, and …

gitserver: Improve error reporting for context deadlines for clones and updates

---

internal/search/result/file.go
internal/search/result/file_test.go

After adding context lines to chunk matches, we are now returning line matches that don't contain any of the actual matches. They have an empty `OffsetAndLengths` field, which means no part of that line actually matched, but we are still returning the unmatched line when splitting a chunk match into line matches.
This PR is a small change to skip any lines in the chunk that have no matched ranges when converting to line matches.
Added a unit test.

Search: skip context lines when converting to line matches

---

internal/tracer/oteldefaults/exporters/BUILD.bazel
internal/tracer/oteldefaults/exporters/otlp.go

In dotcom, the OTEL SDK reports:
```
traces export: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
```
This isn't super helpful for narrowing down where these invalid attributes are coming from.
Luckily, we have some middleware providing some slightly more detailed diagnostics in `grpc/internalerrs`, including detailed logging for this exact problem - this hooks that middleware into the OTEL SDK to help us pin down the source of this issue.
```
sg start
```
Tried a `trace=1` search, nothing bad happened. This middleware is already used extensively elsewhere, and we have an escape hatch via `SRC_GRPC_INTERNAL_ERROR_LOGGING_ENABLED`. Confirmed there's no logspam from failed export due to lack of an active collector in local dev.

tracer/exporters: use internalerrs loggers on OTEL gRPC exporter

---

docker-images/syntax-highlighter/README.md
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__syntect_scip__test__groovy.groovy.snap
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntect_files/groovy.groovy
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/syntect_scip.rs

There was a Groovy issue reported recently.
https://github.com/sourcegraph/customer/issues/2858
The client code attempts to trigger code navigation based on syntax kinds set
by the syntax highlighter, but I noticed we didn't have any tests for the
syntax kinds for Groovy.
So let's at least add a test before fixing this. The fix is tracked in:
- https://github.com/sourcegraph/sourcegraph/issues/60820
This PR just adds a test to make the issue clear.
Snapshot tests

syntax-highlighter: Add snapshot test for Groovy

---

internal/database/dbconn/dynamic_metadata.go
internal/database/dbconn/open.go

Combat issues we're seeing with non-UTF8 values in trace attributes breaking trace exports - at least [one sample](https://sourcegraph.slack.com/archives/C04MYFW01NV/p1709584216722099?thread_ts=1706107280.411819&cid=C04MYFW01NV) indicates that otelsql attributes are the likely issue. This _may_ be a regression from https://github.com/sourcegraph/sourcegraph/pull/4981. This change:
1. Runs all SQL args that get converted to strings through `strings.ToValidUTF8`
2. Customize how the query gets added as an attribute (to make sure it's also valid UTF8, and doesn't have a crazy length)
1. Because queries now get truncated, this change also ensures that the inferred caller context (visible in Cloud SQL) also gets added to the span
3. Makes the truncation thresholds configurable and bumps the …

dbconn/otelsql: run all string attributes through strings.ToValidUTF8

---

client/web-sveltekit/src/lib/navigation.ts
client/web-sveltekit/src/params/reporev.ts
client/web-sveltekit/src/routes/+layout.svelte
client/web/src/featureFlags/featureFlags.ts
cmd/frontend/internal/app/ui/sveltekit.go

Related: #60735
This commit adds a new feature flag, `web-next-enabled`, to have more control over the Svelte rollout. The plan is to enable the Svelte prototype by default on S2 as quickly as possible. However, not all pages are fully converted and we don't to roll out pages that lack features people are using (e.g. the refernece panel). A separate feature flag allows us to enable some pages by default while having the rest be opt-in.
On the Svelte side this is handled the following ways:
1. Non existing routes already trigger a page refresh. I.e. if the user follows a link that is not handled by SvelteKit they'll get the React app automatically. However, the repo route is very "greedy" because it basically matches any path and treats it as repository name. This commit restricts the …

svelte: Introduce new feature flag for incremental rollout of Svelte on S2

---

client/branded/src/components/Timestamp/Timestamp.tsx
client/branded/src/search-ui/components/LastSyncedIcon.tsx
client/web-sveltekit/src/lib/Timestamp.svelte
client/web/src/enterprise/codeintel/configuration/components/Duration.tsx
client/web/src/enterprise/codeintel/configuration/components/DurationSelect.tsx
client/web/src/enterprise/insights/components/creation-ui/code-insight-time-step-picker/get-interval-descrtiption-text/get-interval-description-text.tsx
client/web/src/enterprise/productSubscription/ExpirationDate.tsx
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.tsx
client/web/src/global/GlobalAlerts.tsx
client/web/src/integration/batches.test.ts
client/web/src/productSubscription/helpers.ts
client/web/src/repo/blob/blameRecency.tsx
client/web/src/site-admin/SiteAdminBackgroundJobsPage.tsx
client/web/src/site-admin/SiteAdminUpdatesPage.tsx
client/web/src/site-admin/analytics/AnalyticsOverviewPage/index.tsx
client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
client/web/src/site/LicenseExpirationAlert.tsx
package.json
pnpm-lock.yaml

This PR bumps our https://date-fns.org/ package to v3 which was just released in December: https://blog.date-fns.org/v3-is-out/. We need this for its new integration with UTCDate (see https://github.com/sourcegraph/sourcegraph/pull/60532) - which is required for the license key expiration fix (see https://github.com/sourcegraph/sourcegraph/pull/60533)
CI was also complaining about some build issues after upgrading the package, so this PR also adjusts some import statements to resolve them.
```
Type 'typeof import("/tmp/bazel-working-directory/__main__/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/date-fns@3.3.1/node_modules/date-fns/formatDistanceStrict")' has no call signatures.
client/branded/src/components/Timestamp/Timestamp.tsx(101,17): error TS2349: This expression is not …
```

web: upgrade date-fns to v3

---

package.json
pnpm-lock.yaml

This PR adds the https://github.com/date-fns/utc package, which when used in conjunction with date-fns@v3, allows you to perform calculations in the UTC time zone. 
--- 
Stacked on: 
- https://github.com/sourcegraph/sourcegraph/pull/60531
CI

web: add date-fns/utc package

---

cmd/frontend/graphqlbackend/event_logs.go
cmd/frontend/graphqlbackend/event_logs_test.go

This feature was introduced in 2021 when we still had private code on Dotcom. We no longer have private code on Dotcom and it can be useful to view user events when investigating an incident.
CI tests.

Allow site-admins to view user events on Dotcom

---

cmd/frontend/auth/BUILD.bazel
cmd/frontend/auth/user.go
internal/auth/userpasswd/BUILD.bazel
internal/auth/userpasswd/handlers.go
internal/security/BUILD.bazel
internal/security/security.go
internal/security/security_test.go
internal/telemetry/events.go
schema/schema.go
schema/site.schema.json

This is being handled by accounts now so we can remove the code from Dotcom.
CI tests

Remove dotcom specific gmail abuse check

---

dev/ci/internal/ci/executor_operations.go

Accidental left-over while QA'ing the original PR.
Fixes https://github.com/sourcegraph/devx-support/issues/658 
CI

ci: fix executors image family for nightly builds

---

client/branded/BUILD.bazel
client/branded/src/components/Timestamp/Timestamp.tsx
client/web/BUILD.bazel
client/web/src/enterprise/dotcom/productSubscriptions/ProductLicenseValidity.tsx
client/web/src/enterprise/productSubscription/ExpirationDate.tsx
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.tsx
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionNode.tsx
client/web/src/enterprise/user/productSubscriptions/__snapshots__/UserProductSubscriptionStatus.test.tsx.snap

Fixes https://github.com/sourcegraph/sourcegraph/issues/60409
[Native Javascript Date objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) have an epoch based internal representation. However, any method calculations are done using the browser's local timezone. This also includes the utility functions that `date-fns` provides (such as `endOfDay`). This lead to confusing behavior, such as license expiration dates accidentally being 9 hours earlier or later than expected (since it depends on the location of the CE creating the key). 
However, this PR fixes the problem by using date-fns v3 (https://github.com/sourcegraph/sourcegraph/pull/60531) along side UTCDate(https://github.com/sourcegraph/sourcegraph/pull/60532). The new `date-fns` major …

 web: subscriptions: fix: make all license expiration calculations use utc instead of the browser's local timezone

---

.aspect/workflows/bazelrc
.aspect/workflows/config.yaml

Workflows now looks for a `.aspect/workflows/bazelrc` by convention and uses it if found. This simplifies the config.yaml file.
CI

ci: use .aspect/workflows/bazelrc for Aspect Workflows flags

---

client/shared/src/util/url.ts
client/web-sveltekit/src/lib/search/state.ts
client/web-sveltekit/src/routes/search/+page.ts

This propagates the `trace=1` from the URL query to the search stream request.
I also looked into maintaining the `trace=1` when submitting a query (new navigation), but I wasn't sure what the best way to do that is. The React webapp maintains that query param across navigations, but it's not clear to me whether that's actually a good pattern. If I understand correctly, we would need to check and forward the `&trace=1` at every place we navigate, which would be pretty overwhelming. 
The trace setting is independent of search query params. Is there a good pattern for storing/fetching/forwarding pieces of state in the URL?
Contributes to [#60732](https://github.com/sourcegraph/sourcegraph/issues/60732)
Added `&trace=1` to a search URL and checked that the returned trace URL works.

Svelte: respect trace=1 query param

---

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.gql

Fixes #60430 
Unhighlighted code is now correctly highlighted.

Svelte: use JSON_SCIP format for highlighting

---

client/web/src/enterprise/own/RepositoryOwnEditPage.story.tsx
client/web/src/enterprise/own/RepositoryOwnEditPage.tsx
client/web/src/enterprise/own/RepositoryOwnPageContents.tsx
client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.story.tsx
client/web/src/enterprise/own/admin-ui/OwnAnalyticsPage.tsx
client/web/src/enterprise/own/admin-ui/OwnStatusPage.tsx
client/web/src/enterprise/repo/enterpriseRepoContainerRoutes.tsx
client/web/src/site-admin/routes.tsx

v2t: add v2t to src/enterprise/own

---

client/web-sveltekit/src/lib/search/state.ts

I introduced a bug in #60871 that was causing submitting a search to fail. TIL that `new URL` does not work with a relative URL by default!
Submitting a search on the home page now works. I think we actually have a playwright test for this, but apparently it's not hooked up to CI yet.

Svelte: fix code submission

---

doc/cloud/index.md

Per [discussion](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1709661124763989) in #discuss-engineering, aligned on language and examples for discussing why latency is not an effective measure for our cloud services.
Docs change, no code changes. Previewed locally
[Preview Link](https://docs.sourcegraph.com/@ejs/add_cloud_latency)

Add latency section to Cloud FAQ

---

dev/sg/sg_backport.go

Replace the use of `master` with `main` in the `sg backport` description.
Just a text update

update description for sg backport

---

.aspect/cli/config.yaml

Disables the following annotations:
See https://github.com/sourcegraph/aspect-cli-plugin-buildkite/pull/4 for config option
Build should not have empty failure annotation

ci: disable posting of annotations by aspect buildkite plugin

---

cmd/cody-gateway/internal/httpapi/completions/anthropic.go
cmd/cody-gateway/internal/httpapi/completions/upstream.go

Follow-up to https://github.com/sourcegraph/sourcegraph/pull/60835 recording the pattern that we blocked
- e2e tests

Record pattern that was blocked

---

.aspect/workflows/config.yaml

We the slow agent health check post-task happen at one other deployment and have not tracked down the root cause yet but it does seem to be related to the observability code that runs at that time.
CI

ci: disable Workflows runner observabilty to resolve slow post-task agent health check

---

WORKSPACE
dev/oci_defs.bzl

with_cfg.bzl is a lot of complicated starlark which we can avoid having to try understand when debugging needs arise by doing what it does by-hand and specific to what we need (aka super cut down and simplified).
Extracted from https://github.com/sourcegraph/sourcegraph/compare/jcjh/msp-bazel-delivery#diff-1a8a445b4ce2a72080eca8ae2a3ae24bc904175e9d9aa2dd1938a29746ae86a3 while we were debugging why AW delivery was being problematic (this wasnt the reason, but I did this change in case it _was_ causing issues and itd be more understandable to read)
`bazel run //cmd/batcheshelper:image_tarball && docker run batcheshelper:candidate --help`

bazel: transition oci_image ourselves instead of via with_cfg.bzl

---

cmd/frontend/graphqlbackend/code_hosts.go
cmd/frontend/graphqlbackend/code_hosts_test.go

Make sure we match the same requirements as for listing the codehosts. Updated test cases to prevent future regressions.
See  https://github.com/sourcegraph/security-issues/issues/384 for more information!
CI tests

Enforce authz check for individual codehosts

---

client/web-sveltekit/src/lib/search/BaseQueryInput.svelte

This div had a different background color than both its parent divs and child divs, which was causing there to be a weird dark spot in the query input where there was a margin.
Before:
After:

Svelte: remove weird background color

---

cmd/frontend/internal/compute/streaming/BUILD.bazel
cmd/frontend/internal/compute/streaming/compute.go
internal/search/backend/BUILD.bazel
internal/search/backend/aggregate.go
internal/search/backend/horizontal.go

Because of a recent regression, frontend could panic when streaming back search
matches. These panics occur in a raw goroutine, which we didn't manually
propagate. So the panics caused frontend to crash.
This PR updates the relevant places to use `conc` objects, which properly
propagate panics. I did a "best effort" based on the original issue and didn't
audit all frontend search code.
Related to INC-258
Related to #60605
Happy path is covered by existing tests like `aggregate_test.go` and
`horizontal_test.go`. Manually repro'd the original issue #60605 with the
search `repo:sourcegraph/sourcegraph camden cheek file:contains.content(>\n)`
and checked frontend no longer crashes. Also manually tested code insights.

Search: avoid crashing on frontend panic

---

client/web-sveltekit/src/lib/search/dynamicFilters/index.ts
client/web-sveltekit/src/lib/shared.ts
client/web-sveltekit/src/routes/search/+page.ts
client/web-sveltekit/src/routes/search/SearchResults.svelte

This PR comes in three commits:
1) Add the URL parameter to force use of the cache to navigations from the filters panel. These are not forward/back so we don't use the cache automatically, but toggling them on and off is a very common pattern that we don't want to re-run the query for.
2) Make the stream always defined. Previously, we were using a `BehaviorSubject` with a default value of `undefined`, but we actually have a meaningful value for "a stream that has had no events yet". This simplifies a bunch of signatures and consumers of the stream. This seems unrelated, but it made it easier to reason about the initial state of the observable.
3) Remove the request cancellation logic. I had previously asked for us to cancel in-flight requests when we make a new request to reduce the load …

Svelte: fixup caching

---

cmd/frontend/graphqlbackend/git_blob.go
cmd/frontend/graphqlbackend/schema.graphql

This allows to get blame for the entire file without specifying `1` and `100000` as the range.
Verified manually in my local instance.

Allow to get Blame information for a whole file

---

internal/codeintel/codenav/service_new_test.go

test: Remove wrong dot in local symbol names

---

client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionsPage.tsx
client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
client/web/src/site-admin/sidebaritems.ts
client/web/src/user/settings/sidebaritems.ts

Some users have gotten Sourcegraph Enterprise license keys confused with Cody Pro subscriptions because the former was also called "Subscriptions" in the user settings area ([example](https://discord.com/channels/969688426372825169/1212987159791800351/1213121019397546024)). This renames "Subscriptions" to "Enterprise licenses" in the UI. The API and URLs remain unchanged for compatibility.
Docs PR: https://github.com/sourcegraph/docs/pull/125
Run `sg start dotcom` and confirm that the sidebar labels and page titles are updated.

rename "Subscriptions" to "Enterprise licenses" to avoid confusion with Cody Pro

---

cmd/frontend/graphqlbackend/external_account.go
cmd/frontend/graphqlbackend/schema.graphql
internal/cody/subscription.go

As part of [#inc-284-plg-users-paying-for-and-being-billed-for-pro-without-being-upgrade](https://sourcegraph.slack.com/archives/C06N8ELPKNH/p1709796118502059) it is noted that users have multiple SAMS accounts associated with their dot-com account which is unexpected.
This PR exposes graphql API to allow us to fetch cody subscription associated with the SAMS external account identity.
Comparing `user.codySubscription` with `user.externalAccounts.nodes.codySubscription` will allow us to debug the mismatch between the SAMS identity using which the user paid for cody pro vs the one they are signed in on dotcom or cody clients.
Run query:
```graphql
{
user(username: "hereisnaman") {
codySubscription {
plan
status
currentPeriodStartAt
currentPeriodEndAt
}
externalAccounts {
nodes {
serviceID …
```

Expose API to fetch cody subscription associated with SAMS identity

---

cmd/gitserver/internal/executil/BUILD.bazel
cmd/gitserver/internal/executil/executil.go
cmd/gitserver/internal/executil/executil_test.go
cmd/gitserver/internal/patch.go
cmd/gitserver/internal/server.go
cmd/gitserver/internal/vcssyncer/git.go

This change feeds git the HTTPS URL user:password part via env vars through an inline shell script. Before, the password would be part of the command args, which is viewable in ps, top and so forth. Now, the secret can no longer be copied from the output of top.
Thanks to Keegan for the suggestion to use an inline script and an env var!
Closes https://github.com/sourcegraph/security-issues/issues/244
Closes https://github.com/sourcegraph/sourcegraph/issues/56810
CI integration tests, manually verified that clones, conn checks and so forth still work locally. Also verified that in `top` the credentials no longer show up, and no local credential helper is invoked. We believe now is the best time to merge such a change, so we have the longest possible period of us dogfooding this before a …

gitserver: Pass HTTPS remote URL password as env var

---

.aspect/workflows/config.yaml
dev/sg/internal/images/BUILD.bazel

`include_eternal_tests` is now deprecated and Workflows no longer filters eternal tests out by default as of 5.9.18.
CI

ci: remove include_eternal_tests as it is no longer needed in Aspect Workflows 5.9.18

---

cmd/frontend/graphqlbackend/external_account.go

Fix for the [PR](https://github.com/sourcegraph/sourcegraph/pull/60914). We should fetch subscription info only for openidconnect sams external account. But it was implemented otherwise. 
```
{
user(username: "hereisnaman") {
codySubscription {
plan
status
currentPeriodStartAt
currentPeriodEndAt
}
externalAccounts {
nodes {
serviceID
serviceType
accountID
codySubscription {
plan
status
currentPeriodStartAt
currentPeriodEndAt
}
}
}
}
}
```

Fix external_account.cody_subscription logic

---

client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte

Tiny issue I noticed: when activating a filter, the appearance of the "Reset all" button causes everything in the filters panel to shift slightly.
Before:
https://github.com/sourcegraph/sourcegraph/assets/12631702/8c54dff6-1112-4501-b78e-edcbeb7f4acf
After:
https://github.com/sourcegraph/sourcegraph/assets/12631702/c32b21df-ca76-4706-a563-ad1ebb8dd811

Svelte: fix jumpy filters panel

---

client/web-sveltekit/src/routes/search/SearchResults.svelte

This moves the action bar outside of the scrollable element in search results. We want the actions (and result count) to always be visible.
Before:
https://github.com/sourcegraph/sourcegraph/assets/12631702/766199b0-c396-459a-b2f5-74486457bae8
After:
https://github.com/sourcegraph/sourcegraph/assets/12631702/c19253f9-565e-4c2a-93be-0d501945dd68

Svelte: scroll result list without actions

---

client/web-sveltekit/BUILD.bazel
dev/defs.bzl

Makes the vitest macro more generic to support web-svelte use cases
Ran target locally and it is included in CI

Updates vitest macro

---

client/web-sveltekit/BUILD.bazel
client/web-sveltekit/package.json
dev/defs.bzl
pnpm-lock.yaml

Closes #60882 
This commit adds a new target to run the unit tests inside client/web-sveltekit with vitest.
We have an existing vitest rule (macro?) but that expects the existence of a vitest.config.ts file, which client/web-sveltekit doesn't have. The test config is defined in `vite.config.ts`. Therefore I'm using the vitest binary directly.
CI

svelte/ci: Add vitest target for client/web-sveltekit

---

client/web-sveltekit/src/routes/[...repo=reporev]/layout.spec.ts

A recent change to the top navigation caused two buttons containing the word "search" to be present on the page. This change narrows down the selection to the desired button.
```
cd client/web-sveltekit
pnpm test
```
(playwright tests don't run in CI yet)

svelte: Fix repo playwright test

---

internal/types/types.go
internal/usagestats/aggregated_cody.go

Avoid sending a bunch of empty/zero fields to data warehouse. Fixes https://sourcegraph.slack.com/archives/C01PQEVJ5A9/p1709742734184889?thread_ts=1705069745.537519&cid=C01PQEVJ5A9
CI. Also tested output locally. 
Original json value (from local testing):
```
{
"Daily": {
"StartTime": "2024-03-07T00:00:00Z",
"TotalCodyUsers": {
"UserCount": 1,
"EventsCount": 2
},
"TotalProductUsers": {
"UserCount": 0,
"EventsCount": null
},
"TotalVSCodeProductUsers": {
"UserCount": null,
"EventsCount": null
},
"TotalJetBrainsProductUsers": {
"UserCount": null,
"EventsCount": null
},
"TotalNeovimProductUsers": {
"UserCount": null,
"EventsCount": null
},
"TotalEmacsProductUsers": {
"UserCount": null,
"EventsCount": null
},
"TotalWebProductUsers": {
"UserCount": null,
"EventsCount": null
}
},
"Weekly": { …
```

Limit empty/zero data in json output from aggregate Cody ping data

---

client/web/src/cody/chat/CodyChatPage.tsx
client/web/src/cody/components/ChatUI/ChatUi.tsx
client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.story.tsx
client/web/src/cody/components/CodyMarketingPage/CodyMarketingPage.tsx
client/web/src/cody/components/ScopeSelector/ScopeSelector.tsx
client/web/src/cody/dashboard/CodyDashboardPage.tsx
client/web/src/cody/management/CodyManagementPage.tsx
client/web/src/cody/onboarding/CodyOnboarding.tsx
client/web/src/cody/search/CodySearchPage.tsx
client/web/src/cody/sidebar/CodySidebar.tsx
client/web/src/cody/sidebar/Provider.tsx
client/web/src/cody/subscription/CancelProModal.tsx
client/web/src/cody/subscription/CodySubscriptionPage.tsx
client/web/src/cody/subscription/UpgradeToProModal.tsx
client/web/src/cody/useCodyChat.tsx
client/web/src/cody/widgets/CodyRecipesWidget.tsx
client/web/src/repo/RepoContainer.tsx
client/web/src/repo/blob/CodeMirrorBlob.tsx
client/web/src/repo/blob/codemirror/tooltips/CodyTooltip.tsx
client/web/src/routes.tsx

Context:
`sg start`
visit page

v2 telemetry: add v2 telemetry to src/cody

---

cmd/frontend/internal/httpapi/graphql.go

This code was breaking the GraphQL API when a client sends invalid parameters. It is also redundant because `schema.Exec` validates the parameters are part of executing a GraphQL query. The validation errors will still be returned to the client.
[This query](https://sourcegraph.sourcegraph.com/api/console#%7B%22query%22%3A%22query%20BlobPageQuery(%24repoName%3A%20String!%2C%20%24revspec%3A%20String!%2C%20%24path%3A%20String!)%20%7B%5Cn%20%20repository(name%3A%20%24repoName)%20%7B%5Cn%20%20%20%20id%5Cn%20%20%20%20commit(rev%3A%20%24revspec)%20%7B%5Cn%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20oid%5Cn%20%20%20%20%20%20blob(path%3A%20%24path)%20%7B%5Cn%20%20%20%20%20%20%20%20...BlobPage_Blob%5Cn%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20__typename%5Cn%20%20 …

Bug: remove extra GraphQL validation

---

client/web-sveltekit/src/lib/search/dynamicFilters/Section.svelte

Tiny fix for when to show conditional messages. Previously, we would not show the "no matches" message if the user had activated "Show more". This just modifies the conditional so that we always show that message if no results match their filter.
Before:
After:

Svelte: fix no matches messages with show more

---

internal/search/job/jobutil/exhaustive_job.go
internal/search/job/jobutil/exhaustive_job_test.go

It is currently possible to create search jobs based on `select:` queries although we don't support them. This adds a check to fail validation.

search jobs: fail validation for select: queries

---

sg.config.yaml

Fixes https://github.com/sourcegraph/devx-support/issues/693
It seems we may have broken the mecanism that restart a command if the compilation failed when we rewrote in #60687. Rather than fixing old code, I added a `cody-gateway-bazel` command set until we fully switch to `bazel` as the default for everyone. 
I tested it and I can mess up the compilation, then fix it and it correctly picks it up without having to restart `sg`. 

sg: add a cody-gateway-bazel commandset

---

cmd/frontend/auth/user.go
cmd/frontend/auth/user_test.go
cmd/frontend/internal/auth/openidconnect/user.go
schema/schema.go
schema/site.schema.json

When using an external identity provider, Sourcegraph by default doesn't care how many external identities you're adding to your account. In some cases, this can be undesirable though, for example when trying to map a Sourcegraph user to a single identity in the outside world.
Since we cannot change the behavior here silently as people might rely on it, I decided to add a new option for this.
When enabled, the following scenario will no longer be allowed:
- I sign in to Sourcegraph for the first time using an Okta account called supererik@sourcegraph.com.
- I then go to the auth provider flow a second time (accounts tab, or through a redirect) and this time I choose my Okta account erik@sourcegraph.com
- Since I am already authenticated to Sourcegraph and it appears to Sourcegraph as if I …

oidc: Add option to allow only a single identity per provider

---

client/web/src/enterprise/rbac/SiteAdminRolesPage.tsx

Roles isn't exclusively available to Batch Changes anymore.  A number of services/products have since adopted RBAC so I'm updating the UI here.
UI update.
Backport 1833f32 from #60756

[Backport 5.3] update roles page description

---

client/web/src/repo/blob/CodeMirrorBlob.tsx
client/web/src/repo/blob/codemirror/tooltips/HovercardView.tsx

Original problem [thread](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1709913968661159) 
The problem was simple, since we started checking feature flags within the link component and in the case of hovercard we render links outside of the main react call tree, the feature flag check within the link component didn't have access to the Apollo context. This PR just adds the client providers manually in the hover card.
- Go to the blob UI view and check that you can see code intel hover tooltip over symbols

Fix link feature flag check within code intel card

---

tools/release/schema_deps.bzl

```
git co 5.3
git pull
bazel run //tools/release:upload_current_schemas -- v5.3.2
bazel run //tools/release:generate_schemas_archive -- v5.3.2 fetch-current-schemas $(pwd)/
```
CI + 
```
INFO: Running command line: bazel-bin/tools/release/generate_schemas_archive v5.3.2 fetch-current-schemas /Users/tech/work/other/
Generating an archive of all released database schemas for v5.3
--- Downloading all schemas from gs://schemas-migrations/schemas
/var/folders/pc/p4c29gw17jz3vqdkgrfnnvdr0000gn/T/tmp.5c7gV2icdT /private/var/tmp/_bazel_tech/0812c8e6e121162f0d18a505d289a8d2/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/tools/release/generate_schemas_archive.runfiles/__main__
--- Filtering out migrations after 5.3
/private/var/tmp/_bazel_tech/0812c8e6e121162f0d18a505d289a8d2/execroot/__mai …
```

backport: update schema descriptions for 5.3.2

---

client/web/src/enterprise/codeintel/searchBased.ts

Language names can contain spaces, and because we don't have a typed API,
I made the mistake of directly concatenating the language name string to `lang:`,
which caused an incorrect search query to be sent for code nav for `Protocol Buffers`,
resulting in 0 code nav results.
Fixes https://github.com/sourcegraph/customer/issues/2882
Manually confirmed that quoting fixes the issue.

client: Quote language name in code nav search queries

---

.github/workflows/buildchecker-history.yml
.github/workflows/buildchecker.yml
.github/workflows/licenses-check.yml
.github/workflows/pr-auditor.yml
.github/workflows/sg-binary-release.yml
.github/workflows/sg-setup.yml

Let Github workflows use the new go version
Github Actions

Github Acionts: update workflows to use go 1.22

---

client/build-config/BUILD.bazel
dev/defs.bzl
sg.config.yaml

The `npm_package` macro had an unused argument that it was silently dropping before passing on, making any call site that used very misleading. Also fixed a small bug with running blobstore through bazel.
Ran `bazel test //...`

Removed unused bazel macro arg

---

WORKSPACE
dev/BUILD.bazel
dev/go-mockgen-gazelle/go-mockgen.go

`//dev:go_mockgen` had `suggested_update_target` set to `//dev:write_all_generated` without it actually being part of that list. Theres two options here: updated `suggested_update_target` to `//dev:go_mockgen` for go_mockgen targets, or add the former to the latter. We're going with the latter here (we could also do both, but want to direct people towards write_all_generated even though it does more work in the worst case)
CI and `bazel run //dev:write_all_generated`

bazel: include //dev:go_mockgen in //dev:write_all_generated

---

dev/managedservicesplatform/operationdocs/operationdocs.go
dev/managedservicesplatform/operationdocs/testdata/TestRender/basic.golden
dev/managedservicesplatform/operationdocs/testdata/TestRender/resources.golden

Link to more explicit setup docs in https://github.com/sourcegraph/managed-services/pull/745 for first-time users so that subsequent steps make sense
https://github.com/sourcegraph/handbook/pull/8693

msp/operationdocs: link to msp repo setup

---

dev/sg/cloudsqlproxy/binary.go
dev/sg/msp/repo/root.go

Previously, we'd ask users to run the command again with the `-download` flag. This is kind of annoying especially because of flag positioning quirks. Instead, let's just ask the user if they'd actually like us to install it for them, in case we don't find the binary in the cache.
```sh
$ sg msp pg connect sams dev  
⚠️ cloud-sql-proxy binary not found at "/Users/robert@sourcegraph.com/Library/Caches/sourcegraph/bin/cloud-sql-proxy/2.8.1/cloud-sql-proxy"
👉 Would you like me to install cloud-sql-proxy for you? n
❌ failed to find cloud-sql-proxy: stat /Users/robert@sourcegraph.com/Library/Caches/sourcegraph/bin/cloud-sql-proxy/2.8.1/cloud-sql-proxy: no such file or directory
$ sg msp pg connect sams dev
⚠️ cloud-sql-proxy binary not found at …
```

sg msp: improve cloudsqlproxy installation UX

---

WORKSPACE
third_party/rules_oci/BUILD.bazel
third_party/rules_oci/no_xattr.patch

Workaround for https://github.com/sourcegraph/devx-support/issues/622. This is portable between both bsdtar and gnutar. On gnutar, this is the default, so this changes nothing for CI builds. This only changes behaviour in macOS with bsdtar.
It is unclear to me where a final solution will exist:
- An issue was opened upstream in docker/moby, but the latest opinion is that this is an issue with rules_oci _technically_ emitting docker-compatible formats that are incompatible with docker (Im not 100% sure yet that docker itself cant create a tarball that would fail to `docker load`, but I dont want to subject Christoph to more experiments lol) https://github.com/moby/moby/issues/47517
- A PR exists in rules_oci to use a hermetic BSD tar instead of system tar (doesnt work on nixos though coz …

bazel: patch rules_oci to run tar with --no-xattrs

---

client/web-sveltekit/src/lib/search/input/SearchInput.svelte
client/web-sveltekit/src/routes/+layout.svelte
client/web-sveltekit/src/routes/MainNavigationEntry.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.gql
client/web-sveltekit/src/routes/search/SearchResults.svelte
client/web-sveltekit/src/routes/search/page.spec.ts
client/web-sveltekit/src/testing/integration.ts

Due to z-index setting, the search dropdown of the main navigation is hidden behind the search input on the search results page.
This commit solves this by introducing stacking contexts at the appropriate level:
- In the search input, the actual input needs a higher z-index to appear above the suggestion container. This only needs to work inside the search input so it should create a new stacking context.
- In the search results page, the (full) search input should appear above the search results list. Using `position: sticky` would cause the headsers to appear above the search input suggestions. Giving the search input container a higher z-index fixes that. But again, that only needs to work inside the search results itself. Because the search results page doesn't have its own container …

svelte: Fix main navigation dropdown hidden behind search input

---

cmd/cody-gateway/internal/httpapi/completions/anthropic.go
cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
cmd/cody-gateway/internal/httpapi/completions/flagging.go

Include traceID in blocked responses to simplify debugging - [Slack](https://sourcegraph.slack.com/archives/C1JH2BEHZ/p1710175075643709).
- e2e tests

Include traceID in blocked responses

---

cmd/frontend/auth/user.go
cmd/frontend/auth/user_test.go
cmd/frontend/internal/auth/openidconnect/user.go
schema/schema.go
schema/site.schema.json

This has not been used anywhere yet and I've gotten feedback that the name was confusing. So changing it here.
Existing test suites, code review.

oidc: Rename singleProvider property to singleIdentityPerUser

---

client/web-sveltekit/src/lib/Separator.svelte

Just a small thing I extracted from a larger PR. This:
1) Adds a hover interaction to the separator bar (like the React app, but symmetrical)
2) Uses an outline rather than a changing width so that the page doesn't re-flow on click
Before:
https://github.com/sourcegraph/sourcegraph/assets/12631702/9ea7d35c-8fbb-48cd-b578-e73fa84702f9
After:
https://github.com/sourcegraph/sourcegraph/assets/12631702/0b535a34-0b3e-46c9-984b-c288b093ee4b

Svelte: add hover to separator and remove size change

---

WORKSPACE

Use the latest buildifier. No mention of the crashing bazel fix in the changelogs
CI

bazel: buildifier 6.4.0
