sourcegraph/sourcegraph-public-snapshot

- .buildkite/pipeline.yml
- dev/sg/ci/subcommands.go
- dev/sg/internal/bk/BUILD.bazel
- dev/sg/internal/bk/bk.go
- dev/sg/internal/bk/create_build_opts.go
- Skip uploading of aspect steps if the env contains `DISABLE_ASPECT_WORKFLOWS`
- When `bazel-do` triggers a build, it ensures `DISABLE_ASPECT-WORKFLOWS` is set
- https://buildkite.com/sourcegraph/sourcegraph/builds/264767#_
- Tested locally and CI
> ci: bazel do - skip adding of aspect workflows

- internal/cody/subscription.go
My previous [PR](https://github.com/sourcegraph/sourcegraph/pull/60913/files) made changes to merge cody subscription details from multiple SAMS accounts associated with a single user. 
Bug reported by @bobheadxi [here](https://github.com/sourcegraph/sourcegraph/pull/60913/files#r1520705295).
By mistake I forgot to remove the limit = 1. This PR removes that.
Unit tests present.
> Remove limit while fetching sams account ids

- CHANGELOG.md
- cmd/worker/internal/authz/perms_syncer.go
- internal/database/perms_store.go
- internal/database/perms_store_test.go
Closes #61023 
Fixes an issue where multiple permission sync jobs are scheduled for users and repositories at the same time.
The existing SQL queries don't take into account that a permissions sync could be in progress or queued when checking for users/repos with the oldest permissions, which leads to a lot of overlapping permission syncs being scheduled. This could cause significant delays in the permissions sync system as a whole, since a single permissions sync now turns into 5+ consecutive syncs for the same user.
Verified on my local machine that multiple permission jobs are no longer scheduled for the same user/repo.
> Check for scheduled or processing jobs when scheduling permission syncs

- client/web/src/LegacyLayout.tsx
- client/web/src/nav/GlobalNavbar.tsx
- client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.story.tsx
- client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
We've removed "Own" as a named product, and have moved towards incorporating its features into the Code Search feature set. As such, we no longer need a link in the global nav bar to a landing page that doesn't exist.
Ran it locally, "Code ownership" no longer exists in the dropdown.
> Chore: remove Own from global navbar

- cmd/executor/internal/worker/cmdlogger/logger.go
- cmd/frontend/graphqlbackend/observability.go
- cmd/frontend/internal/auth/openidconnect/config.go
- cmd/frontend/internal/auth/saml/config.go
- cmd/gitserver/internal/server.go
- cmd/loadtest/main.go
- cmd/repo-updater/internal/scheduler/scheduler.go
- cmd/server/internal/goreman/proc.go
- cmd/worker/internal/executorqueue/external_emitter.go
- cmd/worker/shared/main.go
- dev/codeintel-qa/cmd/upload/upload.go
- dev/sg/internal/run/installer.go
- internal/batches/service/workspace_resolver.go
- internal/batches/store/changesets_test.go
- internal/codeintel/autoindexing/internal/background/scheduler/job_scheduler.go
- internal/database/migration/runner/runner.go
- internal/diskcache/cache.go
- internal/grpc/defaults/cache_test.go
- internal/repos/bitbucketserver.go
- internal/repos/gitlab.go
- internal/search/backend/horizontal.go
- internal/search/backend/index_options.go
- lib/output/output_unix.go
Now that we've updated to Go 1.22, we don't need to copy loop variables before
using them in goroutines.
I found these using the regex searches `go func\(\w+` and `\.Go(func\(\w+`. I
also simplified some non-loop vars when it made sense. 
Straight refactor, covered by existing tests
> Simplify goroutine params

- .github/workflows/buf-breaking-check.yml
- .github/workflows/licenses-check.yml
- .github/workflows/licenses-update.yml
- .github/workflows/pull-request.yml
- .github/workflows/scip-typescript.yml
- .github/workflows/team-labeler.yml
- .github/workflows/universal-ctags.yml
- .github/workflows/update-embeddings-list.yml
This pins the versions of the third-party actions, as recommended by GitHub. See https://github.com/sourcegraph/security-issues/issues/377 for more information.
Check if CI tests still operate.
> Pin third-party actions

- dev/ci/push_all.sh
Missed this on my previous PR (you can't see this being broken in a PR or main dry run) 😮‍💨 
Was accidentally dropped here: https://github.com/sourcegraph/sourcegraph/pull/60962/files#diff-08b887c877bc36e59a90a823b4211912dd155bd0c083a033352c0cd94f443137L106
CI
> fix: ci: restore pushing on prod registry

- cmd/frontend/internal/executorqueue/handler/handler.go
- cmd/frontend/internal/executorqueue/handler/multihandler.go
This is.. bad. This broke docker auth via executor secrets because the V0 payload didn't support it. This could also affect non-utf-8 encoded virtual machine file contents.
Verified that the new syntax works correctly.
> executors: Fix version detection for V2 payloads

- cmd/gitserver/internal/cleanup.go
- cmd/gitserver/internal/server.go
- doc/admin/observability/alerts.md
- doc/admin/observability/dashboards.md
- monitoring/definitions/git_server.go
- monitoring/definitions/shared/gitserver.go
- Removes duplicative disk IO panels
- Adds some warnings and next steps descriptions to the most critical things
- Hides the backend panel by default
- Adds a metric and alert for repo corruption events
Tried the dashboard out locally using `sg start monitoring`.
[Preview Link](https://docs.sourcegraph.com/@es/gitserver-dash)
> gitserver: Cleanup grafana dashboard

- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminLicenseKeyLookupPage.tsx
- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionsPage.tsx
- client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
- client/web/src/site-admin/sidebaritems.ts
- client/web/src/user/settings/sidebaritems.ts
https://github.com/sourcegraph/sourcegraph/pull/60911 renamed "Subscriptions" to "Enterprise licenses", but the two are not equivalent, as "subscriptions" are an entity above individual licenses - for example `Create new Enterprise license` is not equivalent to the previous `Create new product subscription`. This entity is important because there are some elements of these subscriptions that are more subscription-oriented, than license-oriented - for example, Cody Gateway rate limits exist at an "Enterprise subscription" level and are not necessarily tied to individual licenses (though they can affect what is evaluated at the "subscription" level).
In [RFC 885 Sourcegraph Enterprise Portal](https://docs.google.com/document/d/1tiaW1IVKm_YSSYhH-z7Q8sv4HSO_YJ_Uu6eYDjX7uU4/edit#heading=h.tdaxc …
> rename 'Enterprise licenses' to 'Enterprise subscriptions' to accurately represent enterprise accounts

- client/web-sveltekit/dev/graphql-type-mocks.cjs
- client/web-sveltekit/src/testing/integration.ts
Before this commit the "mock types" had been generated by simply applying `DeepPartial` (which is like `Partial` but applies recursively) to the existing GraphQL types.
This commit generates the TS types "from scratch". This allows us to customize how TS types for mocks are defined. Concrete differences (so far):
- Mock types for interfaces have a `__typename` field that is a union of the type names of all implementations of that interface. This should make it easier to define mocks of concreate types for fields that accept an interface.
- Fields that take an enum are now defined as string union, which allows speciying the enum value as string literal (with completion support), instead of having to import the actual enum.
Example of generated code:
```ts
export interface …
```
> svelte: Improve TS types for GraphQL mocks

- cmd/frontend/graphqlbackend/orgs.go
- cmd/frontend/graphqlbackend/orgs_test.go
- cmd/frontend/graphqlbackend/user.go
- cmd/frontend/graphqlbackend/user_test.go
This PR cleans up some Dotcom specific checks. It removes a check on:
- Listing organizations: allows site-admins on Dotcom to list organizations. People can make organizations still, so it makes sense we should be able to list them so we can remove them.
- User settings adminstration by a site-admin: on Dotcom we no longer have private code, so there shouldn't be any secrets related to codehosts in user settings.
CI tests.
> Clean-up Dotcom specific checks

- deps.bzl
- go.mod
- go.sum
We had a code path which was gated by the string representation of the parsed regex ".*". This string changed in go 1.22 which means we stopped using it. This update includes a fix which is robust to the version of go.
https://github.com/sourcegraph/zoekt/compare/371a303692de...cc5e093366ea
- https://github.com/sourcegraph/zoekt/commit/72423e1762 nix: use go1.22
- https://github.com/sourcegraph/zoekt/commit/acce0526a2 nix: use go1.22.1
- https://github.com/sourcegraph/zoekt/commit/755d68b13a bump versions on github actions
- https://github.com/sourcegraph/zoekt/commit/52a28e3f9e go.mod: update to go 1.22.1
- https://github.com/sourcegraph/zoekt/commit/cc5e093366 matchtree: do not depend on String for symbol all optimization
Test Plan: CI
> gomod: update zoekt to fix symbol .* perf regression

- client/web-sveltekit/src/routes/MainNavigationEntry.svelte
- client/web-sveltekit/src/routes/styles.scss
Fixes https://github.com/sourcegraph/sourcegraph/issues/60995
This PR adds some global focus ring styles to common focusable elements. This adds focus ring to most elements however during testing I found that Menu navigation dropdown doesn't work properly with keyboard navigation (Something that I will fix in later PR), this is only about styles.  
I'm not a fan of global styles even for focus-ring styles since there will be cases when global styles won't fit (some custom styles on chips button in combobox, etc) but this is the best that we can do at the moment I think.
https://github.com/sourcegraph/sourcegraph/assets/18492575/95b9171e-9012-4e2a-9823-4ee8614f1387
- Check that links, buttons and input elements (including checkboxes and radio buttons) have focus ring styles with no visual …
> Add basic focus ring styles to svelte button, links, input elements

- internal/database/executor_secrets.go
- internal/database/executor_secrets_test.go
Found this while debugging another issue:
When there are two executor secrets for both global scopes we currently support that have the same name, they will appear as both Global Secret, and Overwrites Global Secret in the UI.
So far so confusing, so let's fix that (because they're not actually overwriting anything, scopes are separate namespaces).
Turns out this also breaks detection for uniqueness of secret values in user namespaces, so when two global DOCKER_AUTH_CONFIG secrets exist (one for each scope), users cannot overwrite this secret value anymore, getting an error message like below.
Manually verified that things work correctly now and adjusted a test.
> executor: Fix global secrets across namespaces colliding

- lib/managedservicesplatform/runtime/env.go
- lib/managedservicesplatform/runtime/service.go
Dump service info and configuration options when executing a MSP runtime binary with the `-help` flag.
```none
$ go build -o .bin/telemetry-gateway github.com/sourcegraph/sourcegraph/cmd/telemetry-gateway
$ .bin/telemetry-gateway -help                                                                                   
SERVICE: telemetry-gateway
VERSION: 0.0.0+dev
CONFIGURATION OPTIONS:
- 'TELEMETRY_GATEWAY_EVENTS_PUBSUB_ENABLED': If false, logs Pub/Sub messages instead of actually sending them (default: "true")
- 'TELEMETRY_GATEWAY_EVENTS_STREAM_PUBLISH_CONCURRENCY': Per-stream concurrent publishing limit. (default: "250")
- 'MSP': indicates if we are running in a MSP environment (default: "false")
- 'ENVIRONMENT_ID': MSP Service Environment ID (default: "unknown")
- 'PORT': service port …
```
> msp/runtime: add -help handling for config options

- internal/workerutil/worker_test.go
Seems like this test was always wrong, thanks @camdencheek! The numWorkers variable hasn't been captured before so it always ended up being == NumTestRecords.
This revealed that the tracking of job start/end times at the millisecond precision we were doing here is just not reliable enough to not flake a lot. So I switched the approach here to tracking the actual concurrency seen.
Ran the test with --count=100 locally, no more flakes.
> worker: Fix test after go 1.22 upgrade

- cmd/frontend/auth/user.go
- cmd/frontend/auth/user_test.go
When the user is:
1. Already authenticated
2. Completed an auth flow using an already linked external identity/account
We should not fail the single-identity-per-provider check because that is not a new identity.
This addresses the issue in the following scnerio:
1. Sign in VSCode and dotcom using GitHub
1. Sign out VSCode but stay sign-in on sourcegraph.com
2. Try to sign in VSCode again using the exact same GitHub account
3. White auth error screen on sourcegraph.com.
CI and tested e2e locally
> auth: do not fail single identity per provider check if it's the same identity

- dev/ci/push_all.sh
The previous code was a bit convoluted and hard to follow the moment we started adding cases where it doesn't just look at the branch name. 
This is not great, but at least it's better and it won't push the `insiders` tag on internal releases. 
CI
> chg/ci: don't push insiders tag on internal rels

- internal/search/codycontext/query_transformer.go
- internal/search/job/jobutil/job.go
- internal/search/job/jobutil/job_test.go
This was the root cause of a bug where searcher and zoekt treated the pattern it received inconsistently. The way file:contains.content() works is it always takes a regex.
Additionally we came across a case for cody context not setting inputs as literal. This likely fixes a bug, but I did not test further. This came up when auditing direct creations of query.Pattern.
Test Plan: added a unit test which ensures searcher uses a regex for the pattern.
Stacked on https://github.com/sourcegraph/sourcegraph/pull/61100
Part of https://github.com/sourcegraph/sourcegraph/issues/60745
> search: set Regexp annotation on patterns for FileContainsPatterns

- cmd/cody-gateway/shared/config/config.go
- cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
https://www.anthropic.com/news/claude-3-haiku
This one is going to be enabled for free users as well as we want to experiment with it for both fast-completion (symf symbol expansion) as well as autocomplete.
As usual:
Not tested yet because my local env won't start up anymore but this just adds a string to some other strings.
```
curl -vS -X POST http://localhost:9992/v1/completions/anthropic-messages -H 'Authorization: bearer <TOKEN>' -d '{"stream":true,"max_tokens":50, "model": "anthropic/claude-3-haiku-20240307", "stop_sequences": [], "messages":[{"role":"system","content":[{"type": "text", "text": "You are Cody, an AI chat bot created by Sourcegraph."}]},{"role":"user","content":[{"type": "text", "text": "Who are you?"}]}]}' -H 'X-sourcegraph-feature: chat_completions'
```
> Add Haiku to Cody Gateway and PLG

- dev/sg/internal/release/release.go
Prior to this PR, a bunch of TODO were left in there. 
Locally tested, ran `go run ./dev/sg release [stuff] --help` to ensure it looks correct.
> fix/sg: doc usage of sg release commands

- cmd/symbols/internal/api/handler.go
- cmd/symbols/internal/database/store/search.go
- internal/search/result/file.go
- internal/search/result/file_test.go
- internal/search/result/symbol.go
- internal/search/zoekt/indexed_search.go
fixes #60698
This fixes the following bugs for unindexed symbol search:
1. Now we respect the limit given by "frontend". Before, the upper limit of unindexed symbol search was hard coded to 500. This limit could not be overwritten with the `count:` filter. 
2. Merge symbol matches properly, applying the same logic as we do for indexed search: Before, symbol matches within the same file were simply appended which created duplicates for AND/OR queries if separate terms of the query matched the same symbol.
Test plan:
- New unit test
- Partially covered by existing tests
> symbols: respect limits, merge properly

- .pre-commit-config.yaml
File is generated by pnpm so if `precommit` does find an issue its likely a false positive
On a branch where I ran `pnpm dedupe` precommit said there was an issue with `pnpm-lock.yaml`
> exclude pnpm-lock.yaml from precommit

- internal/codeintel/uploads/internal/commitgraph/commit_graph_test.go
- internal/gitserver/gitdomain/commit_graph.go
I had to track this down through the code, but having it in the doc string should make it easier for the next person.
Just a documentation change
> document the actual git command needed for ParseCommitGraph

- client/web-sveltekit/src/lib/repo/blob.ts
- client/web-sveltekit/src/lib/search/input/SearchInput.svelte
- client/web-sveltekit/src/lib/search/state.ts
- client/web-sveltekit/src/lib/shared.ts
- client/web-sveltekit/src/lib/utils/promises.ts
- client/web-sveltekit/src/lib/wildcard/menu/Menu.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
- client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
- client/web-sveltekit/src/routes/search/FilePathSearchResult.svelte
- client/web-sveltekit/src/routes/search/FileSearchResultHeader.svelte
- client/web-sveltekit/src/routes/search/PreviewButton.svelte
- client/web-sveltekit/src/routes/search/PreviewPanel.svelte
- client/web-sveltekit/src/routes/search/SearchResult.svelte
- client/web-sveltekit/src/routes/search/SearchResults.stories.svelte
- client/web-sveltekit/src/routes/search/SearchResults.svelte
- client/web-sveltekit/src/routes/search/SymbolSearchResult.svelte
- client/web-sveltekit/src/routes/search/page.spec.ts
- client/web-sveltekit/src/routes/search/searchResultsContext.ts
- client/web-sveltekit/src/testing/integration.ts
- client/web-sveltekit/src/testing/search-testdata.ts
- client/web-sveltekit/src/testing/testdata.ts
This implements the basics of the preview panel.
Followup tasks:
- Implement the codemirror extension that lets you cycle through matches within a file
- Add preloading on hover
- Make a more general "resizeable split" component
Loom walkthrough with manual testing and added a playwright test (yay!)
https://www.loom.com/share/c5e88700be014a52a6b8e794032a8894
> Svelte: implement preview panel

- dev/ci/internal/ci/pipeline.go
- dev/ci/internal/ci/release_operations.go
- release.yaml
Fixes #61066
Fixes #61067 
The issue with the promotion of the jaeger image is unrelated to this PR, gotta check why it wasn't part of the internal release. 
- Internal release showing the placeholders:
- ![CleanShot 2024-03-14 at 17 07 38@2x](https://github.com/sourcegraph/sourcegraph/assets/10151/c672ab90-78e9-4e41-b8e2-85f117fbf2f7)
- Promoted release showing the placeholders:
- ![CleanShot 2024-03-14 at 17 06 38@2x](https://github.com/sourcegraph/sourcegraph/assets/10151/fd79f3f1-cdce-4754-84fd-5b147d8e75b7)
> feat/rel: run tests + finalize steps

- cmd/cody-gateway/internal/httpapi/handler.go
> ⚠️ This PR is partly a conversation starter, and so feel free to suggest even better ways to clean up this part of the code. Or, if you believe things are fine as-is, I can drop it entirely. This is just in service of making it easier to land "background request sampling" discussed later.
It appears that over time we've added several common layers of HTTP middleware, but in a way that is increasingly difficult to maintain. This PR makes a few minor changes that lead to a net reduction in overall lines of code.
For reviewing, it may make more sense to look at the PR commit-by-commit.
**Minimize the use between `if` and `else` keywords.**
Something that stuck with me from _Code Complete_, was that if you use an `if/else` construct, and one of the code blocks is really short, you should …
> Cleanup Cody Gateway HTTP endpoint registration code

- client/web-sveltekit/src/lib/search/dynamicFilters/CountBadge.svelte
- client/web-sveltekit/src/lib/search/dynamicFilters/Section.svelte
- client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
- client/web-sveltekit/src/lib/search/dynamicFilters/index.ts
- client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
- client/web-sveltekit/src/routes/search/PreviewPanel.svelte
- client/web-sveltekit/src/routes/search/RepoSearchResult.svelte
- client/web-sveltekit/src/routes/search/SearchResult.svelte
- client/web-sveltekit/src/routes/search/SymbolSearchResult.svelte
This makes a handful of small styling updates to the Svelte implementation of the search results page to bring it more in line with the designs and the react app. It is not comprehensive, but it takes care of the big things.
Manual testing. See [Loom recording](https://www.loom.com/share/a5dd1ac1700d43be98ca483ec3c85f25)
> Svelte: search results styling updates

- dev/ci/runtype/runtype.go
in `sg ci build main-dry-run` we use the runtype branch value as part of the branch we push to remotely aka <runtype.Branch>/<original-branch>. With the regexp value this lead to an invalid branch and this `sg ci build main-dry-run` broke.
Tested locally
```
go run ./dev/sg/... ci build main-dry-run
Pushing 2f760d00227390cd45a13ecf91c535c559a2a6e2 to main-dry-run/wb/sg/fix-main-dry...
remote:
remote: Create a pull request for 'main-dry-run/wb/sg/fix-main-dry' on GitHub by visiting:
remote:      https://github.com/sourcegraph/sourcegraph/pull/new/main-dry-run/wb/sg/fix-main-dry
remote:
remote: GitHub found 80 vulnerabilities on sourcegraph/sourcegraph's default branch (8 critical, 16 high, 50 moderate, 6 low). To find out more, visit:
remote: …
```
> revert MainDryRun non capturing group

- .github/workflows/sg-binary-release.yml
Because of https://github.com/sourcegraph/sourcegraph/commit/82215eb8c1da895cdf2272863785b349d1a06bd4 we build `sg` releases with CGO enabled. 
But in CI when we need `sg` for pipelines for stateless agents, the glibc ends up being the wrong one. This PR ships a statically built one for these, as we absolutely do not care about watching files in CI. 
This is not the best solution, but that'll unblock https://github.com/sourcegraph/sourcegraph/issues/61061 for now. 
CI + will test the newly built binary in a stateless agent
- ✅ working as intended https://buildkite.com/sourcegraph/deploy-sourcegraph-k8s/builds/299#018e41f7-bce1-4c96-aafa-e8c88fef31c8/247-248
> feat/ci: ship a static variant of sg linux/amd64 on

- client/web-sveltekit/src/global.d.ts
The web app uses `window.context` and `pnpm check` (which runs `svelte-check`) currently reports errors related to accessing this property.
This PR extends this packages own declaration to match with the one in web.
Eventually we'll use `window.context` too but not yet. However it's still useful to do this now to make the output of `pnpm check` less noisy.
`pnpm check` doesn't report issues regarding `window.context` anymore.
> svelte: Update global Window definition

- dev/sg/internal/release/release.go
Introduced a regression in a previous PR that made the `--version` flag required, as it breaks the `--config-from-commit` flag. 
Now, the `create` and `promote-to-public` commands expects the `--version` flag to be provided, and everything else considers it optional. 
skipping `--version` on `create` fails as intended: 
```
~/work/sourcegraph S jh/rel/adjust-flags $ go run ./dev/sg release create --workdir=. --pretend        
NAME:
sg release create - Create a release for a given product
USAGE:
sg release create --workdir [path-to-folder-with-manifest] --version vX.Y.Z
CATEGORY:
4 - Utilities
DESCRIPTION:
See https://go/releases
OPTIONS:
--workdir value       Set the working directory to load release scripts from (default: ".")
--type value          Select release type: major, minor, …
```
> chg/rel: adjust version flag requirement in sg rel

- dev/managedservicesplatform/managedservicesplatform.go
- dev/managedservicesplatform/spec/environment.go
- dev/managedservicesplatform/stacks/cloudrun/cloudrun.go
- dev/managedservicesplatform/stacks/iam/BUILD.bazel
- dev/managedservicesplatform/stacks/iam/iam.go
- dev/managedservicesplatform/stacks/iam/iam_test.go
Closes https://github.com/sourcegraph/managed-services/issues/589, which blocks https://github.com/sourcegraph/managed-services/pull/655
This allows operators to specify volumes to mount from secrets. The configuration is intentionally limited for now, for example:
```yaml
secretVolumes:
myVolumeName:
mountPath: "foobar.pem"
secret: "foobar"
```
It has similar capabilities as `secretEnv`, e.g. being able to source from external secrets and automatically have the appropriate access provisioned.
n/a - we use this already internally with Redis certs. This just exposes the same functionality to operators
> msp: add support for secret volume mounts

- dev/ci/images/images.go
Closes #61159
The image doesn't exist on dockerhub anymore so it's safe to remove.
> remove jaeger image from deploy docker images list

- cmd/frontend/graphqlbackend/guardrails_test.go
This test fails for me when run via go test, but for some reason passes via bazel. I have no idea why, but the reason it fails locally for me is we don't actually try to speak to the attribution service if there are less than 10 lines in the snippet. So this is a terrible hack to fix that. It is a complete mystery to me how this test passes inside of bazel.
https://github.com/sourcegraph/sourcegraph/blob/4bca03435626b245c43cce3c6b5966e9a4ba0b7a/cmd/frontend/internal/guardrails/resolvers/resolver.go#L43-L47
Test Plan: Both of these now pass
```
go test ./cmd/frontend/graphqlbackend -run TestSnippetAttributionReactsToSiteConfigChanges
bazel test //cmd/frontend/graphqlbackend:graphqlbackend_test
```
> guardrails: fix TestSnippetAttributionReactsToSiteConfigChanges

- cmd/frontend/graphqlbackend/BUILD.bazel
- cmd/frontend/graphqlbackend/guardrails_test.go
- cmd/frontend/internal/completions/init.go
- cmd/frontend/internal/guardrails/init.go
We switch to using the passed in conftypes.UnifiedWatchable which allows us to have more gaurantees around when config is read after being watched. This allows us to simplify the implementation of syncConfMock and I believe make it correct.
Note: previously conf.Watch was run in a goroutine. However, the implementation of conf.Watch is to run your callback once synchronously, then in future call the callback async. Removing the extra goroutine was needed to make extra sure we didn't have a race in the tests.
When trying to work out why this test was failing for me in https://github.com/sourcegraph/sourcegraph/pull/61165 I noticed this simplification.
Test Plan: `go test -race -count=10 -run '(Snippet|Guardrails)'`
> guardrails: make graphqlbackend test race free

- client/web-sveltekit/src/lib/global-notifications/GlobalNotifications.svelte
- client/web-sveltekit/src/routes/search/SearchHome.svelte
- client/web-sveltekit/src/routes/search/SearchHomeNotifications.svelte
Closes https://github.com/sourcegraph/sourcegraph/issues/60731
Prior to this PR both home and top like notification were rendered within global top-style notification UI. This PR adds new UI on the home page below the search input 
- Run any staging with home page notifications (like k8s) 
- Check that notification are visible to you on the home page below the search page
- Check that you can't see the same notification in the global top panel.
> Svelte: Add below search home notification UI

- cmd/cody-gateway/internal/httpapi/embeddings/handler.go
- cmd/cody-gateway/internal/httpapi/handler.go
- cmd/cody-gateway/shared/config/config.go
Expose an additional Embeddings handler that does not implement rate-limiting (reduced overhead + we don't have token counts for our models).
This is proof-of-concept only - will be used for performance testing in staging (off by default). 
- old functionality still E2E tested
> Expose an embeddings handler that doesn't implement rate-limiting

- dev/ci/semgrep-scan.sh
This PR attempts to fix the baseline commit dynamically to reduce scanning files apart from the pull request.
> Semgrep: Fix baseline commit

- dev/ci/internal/ci/executor_operations.go
[Context](https://sourcegraph.slack.com/archives/C05RRHSQ3QD/p1710774833681369?thread_ts=1710770293.893109&cid=C05RRHSQ3QD)
This was an oversight. The `imageFamily` for internal releases should contain the word `internal`.
> release: properly generate image family for executors on docker mirror

- dev/ci/internal/ci/BUILD.bazel
- dev/ci/internal/ci/aspect_workflows.go
- dev/ci/internal/ci/aspect_workflows_test.go
Generated command was missing a `;`
CI and [bazel-do invoke](https://buildkite.com/sourcegraph/sourcegraph/builds/265638#018e55e9-270a-4234-b1d9-9da8b7c40f63)
> fix regression and add test

- cmd/frontend/graphqlbackend/BUILD.bazel
`rules_go` has support for sharding tests, got me curious to see how it affects one of our slowest go test suite. Without surprise, it's better. 
I only went to two shards, given Bazel runs as many targets as it can concurrently, it's most likely going to get us diminishing returns. 
We should expect to see https://buildkite.com/organizations/sourcegraph/analytics/suites/sourcegraph-bazel/tests/0189f3a8-2a0f-7780-b50b-b61fcfc916ee?branch=main going down in the upcoming days. 
local: 
- before: `//cmd/frontend/graphqlbackend:graphqlbackend_test                        PASSED in 107.6s`
- after: `//cmd/frontend/graphqlbackend:graphqlbackend_test                        PASSED in 69.6s`
CI:
- before: `//cmd/frontend/graphqlbackend:graphqlbackend_test                        PASSED in 207.2s`
- …
> chg/bzl: shard graphqlbackend go tests

- dev/tool_deps.bzl
- dev/tools/BUILD.bazel
As part of https://github.com/sourcegraph/sourcegraph/issues/61229 I need to be able to use `gh` directly from Bazel. We could assume the host always has it, but it's more reliable this way. 
- locally tested on darwin-arm64 
- ensured that the archives structure stays the same in zip and tar.gz
```
~/work/sourcegraph U main $ bazel run //dev/tools:gh
INFO: Analyzed target //dev/tools:gh (4 packages loaded, 10 targets configured).
INFO: Found 1 target...
Target //dev/tools:gh up-to-date:
bazel-bin/dev/tools/gh
Aspect @@rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of //dev/tools:gh up-to-date (nothing to build)
INFO: Elapsed time: 0.634s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: …
```
> feat/bzl: add runnable `gh` target

- dev/ci/images/images.go
- dev/ci/internal/ci/executor_operations.go
- dev/ci/internal/ci/images_operations.go
- dev/ci/internal/ci/legacy_operations.go
- dev/ci/internal/ci/misc_operations.go
- dev/ci/internal/ci/pipeline.go
- dev/ci/push_all.sh
- dev/ci/runtype/runtype.go
Closes #61208,#61110
This adds the Cloud Ephemeral runtype which is a runtype which:
- Matches on branches which starts with `cloud-ephemeral/`
- Does everything a main-dry-run does except pushes images to the registry `sourcegraph-ci/cloud-ephemeral`
* CI
* [Test run](https://buildkite.com/sourcegraph/sourcegraph/builds/265572)
> ci: add cloud ephemeral runtype to Cloud Ephemeral deployments

- release.yaml
I added a comment to include the link to the webhook URLs for testing and for live.
Also formatted the text a bit so it looks nicer.
Testing with #bolaji-release-testing channel. Will test further during the release.
> release: update formatting for slack automation

- cmd/frontend/graphqlbackend/schema.graphql
- cmd/frontend/graphqlbackend/user.go
- internal/cody/BUILD.bazel
- internal/cody/rate_limits.go
closes: https://github.com/sourcegraph/sourcegraph/issues/61055
This PR exposes a dotcom-only API for debugging purposes to easily surface the value of per feature rate limits config & usage for a user from the cody gateway redis storage. This API will only be used for debugging purposes. 
- Visit `/.api/console`
- Perform the following query:
``` graphql
query {
currentUser {
id
codyGatewayRateLimitStatus {
feature 
interval
limit
nextLimitReset
usage
}
}
}
```
- It should respond with the details as shown in screenshot above.
- If it returns in 401 error, make sure `CODY_GATEWAY_DOTCOM_ACCESS_TOKEN` is configured correctly.
> Expose Rate Limit Status from Cody Gateway

- cmd/executor/vm-image/_ami.push.sh
- dev/ci/internal/ci/executor_operations.go
> release: dont append buildkite build number for executor AMIs during internal release

- client/web-sveltekit/src/routes/search/SearchResults.svelte
This adds an `isolation: isolate` to the search results block so that the nothing from that block will be displayed above the search suggestions panel. 
Before: 
After:
> Svelte: isolate hover handle

- doc/admin/observability/dashboards.md
- monitoring/monitoring/documentation.go
While taking on the sync job to automatically port generated doc changes to github.com/sourcegraph/docs, I stumbled across a rendering issue, when the prom queries are involving backticks. 
I initially went for using \` but it's a bit of as reliable as using a code block, as not all markdown parsers handles it the same. Other options are to use double backticks, but, well, same thing. In the end code blocks are dumb and do exactly what we want. 
Before: 
After
[Preview Link](https://docs.sourcegraph.com/@jh/fix-monitoring-docs)
> fix/monit: print query details correctly in docs

- cmd/executor/vm-image/_ami.build.sh
#61263 catered for how we push the executor AMIs, however we didn't handle building these AMIs. This was an oversight that should be fixed by this PR.
I noticed this after creating [an internal release](https://buildkite.com/sourcegraph/sourcegraph/builds/265831#018e5bb1-9e40-400c-ae3c-a441b332b7f0/168) and watching Buildkite fail.
I noticed the image number was appended with the BUILDKITE_BUILD_NUMBER, however when publishing said images we look for images without the build number.
Creating another internal release and hopefully CI should pass now.
> release: update PKR_VAR_name when building executor AMIs

- client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
- client/web-sveltekit/src/lib/codemirror/StaticHighlightsPanel.svelte
- client/web-sveltekit/src/lib/codemirror/static-highlights.ts
- client/web-sveltekit/src/routes/search/FileSearchResultHeader.svelte
- client/web-sveltekit/src/routes/search/PreviewPanel.svelte
- client/web-sveltekit/src/routes/search/page.spec.ts
This implements the static highlights panel extension for Codemirror in Svelte, allowing a user to click through the matched ranges in the preview panel.
Added a playwright test for selection navigation buttons. 
Manual testing, short video demonstration below:
https://github.com/sourcegraph/sourcegraph/assets/12631702/2ba18811-0451-41e3-8470-2f6e7ed50f66
> Svelte: implement preview panel extension for match iteration

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
Just a small change to make the markdown rendering look nicer in the blob view. We already have the markdown styles, we just weren't applying them and were just rendering the raw HTML. Additionally, this adds a max width of `50rem` to the markdown column to match the behavior of the react app.
Before: 
After:
> Svelte: make markdown blob rendering consistent with react app

- cmd/cody-gateway/internal/httpapi/completions/anthropic.go
- cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
- cmd/cody-gateway/internal/httpapi/completions/fireworks.go
- cmd/cody-gateway/internal/httpapi/completions/openai.go
- cmd/cody-gateway/internal/httpapi/completions/upstream.go
This PR applies some general code cleanups and refactoring to `upstream.go`, which IMO is a bit too gnarly for being such a crucial part of the codebase.
Changes:
**Added a `getAPIURLByFeature(codygateway.Feature) string` function to the methods interface**
Added a new `getAPIURLByFeature` function to the `upstreamHandlerMethods[ReqT UpstreamRequest]` interface.
This removes one of the parameters to `makeUpstreamHandler`, and also makes more sense IMHO. Because the `upstreamHandlerMethods` interface is a facade in front of an LLM API, and so it seemed rather awkward to rely on a one-off function for determining the API URL to use.
As part of this, I also moved the package-level constants for the API URLs to just be constant literals in the `getAPIURLByFeature` functions. This may not be …
> Cleanup Cody Gateway upstreams.go

- cmd/cody-gateway/internal/httpapi/completions/anthropic.go
- cmd/cody-gateway/internal/httpapi/completions/anthropic_test.go
- cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
- cmd/cody-gateway/internal/httpapi/completions/anthropicmessages_test.go
- cmd/cody-gateway/internal/httpapi/completions/fireworks.go
- cmd/cody-gateway/internal/httpapi/completions/flagging.go
- cmd/cody-gateway/internal/httpapi/completions/openai.go
- cmd/cody-gateway/internal/httpapi/completions/upstream.go
This PR continues my crusade to tidy up the Cody Gateway upstream code and try to make our anti-abuse measures a bit more general.
The crux of this PR is the following:
```diff
-	validateRequest(context.Context, log.Logger, codygateway.Feature, ReqT) (int, *flaggingResult, error)
+	validateRequest(context.Context, log.Logger, codygateway.Feature, ReqT) error
+	shouldFlagRequest(context.Context, log.Logger, ReqT) (*flaggingResult, error)
```
Previously we were performing "abuse flagging" as part of the request `validateRequest` function. And also had an awkward function signature, where the `int` return value signified an HTTP status code (or defaulted to zero, which would then be defaulted again into `http.BadRequest`.)
So this PR changes three things:
Now, the function just returns an …
> Generalize Cody Gateway request flagging

- internal/httpcli/client.go
- internal/httpcli/client_test.go
From [another PR](https://github.com/sourcegraph/sourcegraph/pull/61280#issuecomment-2010517101) it wasn't exactly clear if changing the HTTP response from 501 to 400 would break existing code which used the `httpcli` client.
This PR adds some tests to pin down the expected behavior, and as it turns out, we do not rely on 400 responses.
```
--- PASS: TestRetryBasedOnStatusCode (0.11s)
--- PASS: TestRetryBasedOnStatusCode/StatusCode200 (0.00s)
--- PASS: TestRetryBasedOnStatusCode/StatusCode400 (0.00s)
--- PASS: TestRetryBasedOnStatusCode/StatusCode429 (0.05s)
--- PASS: TestRetryBasedOnStatusCode/StatusCode500 (0.03s)
--- PASS: TestRetryBasedOnStatusCode/StatusCode501 (0.00s)
--- PASS: TestRetryBasedOnStatusCode/StatusCode502 (0.03s)
```
Added more tests, and without any logic changes even!
> Add more tests for httpcli.NewRetryPolicy

- .aspect/workflows/config.yaml
- doc/BUILD.bazel
- doc/_generated.push.sh
- tools/md2mdx/BUILD.bazel
- tools/md2mdx/README.md
- tools/md2mdx/main.go
- tools/md2mdx/main_test.go
Fixes https://github.com/sourcegraph/sourcegraph/issues/61229
Fixes https://github.com/sourcegraph/sourcegraph/issues/61085
Fixes https://github.com/sourcegraph/sourcegraph/issues/61228
Adds a `//doc:generated.push` target, that gets triggered by the delivery feature, configured to only run when changes are detected. Basically, it sends a PR on the new docs repo, whenever changes to the generated docs is detected. 
Wrote a `md2mdx` which is more of a pile of hacks, but will buy us time while a better approach is figured out. 
Reviewers: please review as usual for the delivery part, but the new tool that processes the docs, keep in mind it's a hack so the KPI is that it works more than it's in a good shape. There's a tons of nit comments that could be made, but it gets the job done.
See …
> feat/ci: when detecting changes affecting the generated docs, push them to docs repo as a PR

- dev/ci/internal/ci/release_operations.go
The `sg release` tool expects the version to be specified when running a release test.
THe version exists in the environment so I'm guessing `$$` should be sufficient enough to reference the version lol.
Try another internal release.
> release: specify version when running release test

- internal/rockskip/server.go
logging migration to `sourcegraph/log`
CI
> logging: remove log15 usage in rockskip server

- dev/ci/internal/ci/release_operations.go
similar to #61317, we need to specify version when running `sg release finalize`.
Successful internal release.
> release: specify version when finalizing release

- cmd/frontend/graphqlbackend/user.go
Currently there is no guaranteed log line written when we update a user's Cody Gateway quota. (Perhaps we usually write something to the "Security Event Logs", but it's unclear what `auditlog-expansion` governs and if it is set for sourcegraph.com.)
This PR just adds a log line so that you can quickly grep through GCP logs to see a record of changes made to user quotas.
NA
> Log changes to a user's Cody Gateway limits

- internal/k8s/resource/BUILD.bazel
- internal/k8s/resource/container/BUILD.bazel
- internal/k8s/resource/container/container.go
- internal/k8s/resource/container/container_test.go
- internal/k8s/resource/container/example_test.go
- internal/k8s/resource/doc.go
This is the start of a series of packages to help create k8s resources with patterns and defaults common to Sourcegraph.
Throughout many of our K8s deployments, we have common settings such as security contexts, readiness probes, liveness probes, etc... 
We can abstract some if not most of these to make deploying on k8s easier in the future. While this is not the final layer of abstraction, it will be used by it.
Specifically, this pkg helps create k8s containers, with a few defaults baked in, while still allow a user to override if necessary. 
> k8s/resource: Add pkg for creating k8s container resources

- client/web-sveltekit/src/app.html
- client/web-sveltekit/src/app.prod.html
- client/web-sveltekit/src/lib/stores.ts
- client/web-sveltekit/src/lib/temporarySettings.ts
- client/web-sveltekit/src/lib/theme.ts
- client/web-sveltekit/src/routes/+layout.svelte
- client/web-sveltekit/src/routes/UserMenu.svelte
Until now selecting a different theme didn't persist it in temporary settings. This commit fixes it. I first tried an approach via context (hence the changes to setting the context) but that didn't work as expected (but the changes are still an improvement).
I also added a small piece of JavaScript to the HTML pages to set the selected theme as soon as possible. This does not have any visible effect yet because the style sheets are loaded lazily but in the future we could add a set of minimal styles to set the background color.
> svelte: Persist theme choice

- cmd/cody-gateway/internal/httpapi/completions/BUILD.bazel
- cmd/cody-gateway/internal/httpapi/completions/anthropic.go
- cmd/cody-gateway/internal/httpapi/completions/anthropic_test.go
- cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
- cmd/cody-gateway/internal/httpapi/completions/anthropicmessages_test.go
- cmd/cody-gateway/internal/httpapi/completions/flagging.go
- cmd/cody-gateway/internal/httpapi/completions/flagging_test.go
- cmd/cody-gateway/internal/httpapi/completions/openai.go
- cmd/cody-gateway/shared/config/config.go
This PR enables our flagging/abuse-detection logic for requests sent to OpenAI.
To do this, it was only a matter of updating the `OpenAIHandlerMethods`'s `shouldFlagRequest(...)` function. And having it call `isFlaggedRequest(...)`. However, the bulk of this PR is to do the wiring in such a way that making the necessary configuration data available makes sense.
1. Introduce `config.FlaggingConfig`
All of our anti-abuse parameters are part of `AnthropicConfig`. Rather than add the same fields to `OpenAIConfig` (and later, other LLM configuration objects), I moved them to a stand-alone `FlaggingConfig` struct.
These flagging configuration values can then be loaded in-bulk by calling this function:
```go
// loadFlaggingConfig loads the common set of flagging-related environment variables for …
```
> Enable flagging for OpenAI-routed LLM requests

- client/shared/BUILD.bazel
- client/shared/src/theme-types.ts
- client/shared/src/theme.ts
- client/web-sveltekit/src/lib/shared.ts
- client/web-sveltekit/src/lib/stores.ts
- client/web-sveltekit/src/lib/theme.ts
- client/web-sveltekit/src/routes/UserMenu.svelte
PR #61322 didn't quite work. The Svelte app was setting the capitalized theme name, but the React app expected a lower case name. Setting the theme in React would properly work in Svelte but not vice versa.
This commit makes two changes:
- The shares the Theme and ThemeSettings constants between Svelte and React so that we ensure using the same values.
- It updates the React version to normalize the theme settings value received from the server.
Set the theme in the Svelte app and verified in the dev tools that the lowercase theme name was sent.
> svelte: Fix theme persistence

- internal/completions/client/anthropic/anthropic.go
- internal/completions/client/anthropic/prompt.go
We are always using the message api so I think we need to always remove the whitespace only stop sequence (made a minor edit there to remove all whitespace).
> minor changes

- dev/nix/bazel.nix
- flake.lock
- flake.nix
Using my fork with open PR: https://github.com/NixOS/nixpkgs/pull/295615
Im needing 7.1 sooner than later, given its new features and this repo also using 7.1 (so all new features are fair game for it!)
Cached version is pushed to sourcegraph-noah.cachix.org, which I've added at the top here so you too can avoid building it locally :slightly_smiling_face: 
Tested locally :sunglasses:
> nix: bump to bazel 7.1

- client/web/dev/esbuild/server.ts
- sg.config.yaml
This commit updates the enterprise-sveltekit command set to work with the current esbuild setup. It adds a new command to start the vite build process. The build process is quite slow so this is not a good way to develop the SvelteKit application but it's as close to the real setup as possible.
```
sg start enterprise-sveltekit
```
> svelte: Update sg start enterprise-sveltekit command set

- client/web/src/enterprise/user/productSubscriptions/UserProductSubscriptionStatus.test.tsx
- client/web/src/enterprise/user/productSubscriptions/UserProductSubscriptionStatus.tsx
- client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionPage.test.tsx
- client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionPage.tsx
- client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
- client/web/src/enterprise/user/settings/UserEventLogsPage.tsx
- client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.test.tsx
- client/web/src/enterprise/user/settings/auth/UserSettingsPermissionsPage.tsx
- client/web/src/user/settings/routes.tsx
> v2t: add v2t to src/enterprise/user

- client/web-sveltekit/src/lib/logger.ts
One reason why the development server is relatively slow is that we are pulling in a lot of (transitive) dependencies that are not used. Specifically the whole wildcard package is included.
I used [dependency-cruiser](https://github.com/sverweij/dependency-cruiser) to find out why all of wildcard is included and eventually discovered that it was because of importing `eventLogger`.
`eventLogger` imports `observerQuerySelector` from `dom.ts` which in turn imports `useObservable` from `@sourcegraph/wildcard`, which of course imports all of wildcard:
Since `eventLogger` is deprecated and we'll have to implement proper support for event logging anyway I've removed the dependency for now. This avoids pulling in all of wildcard and reduces the number of request made for the homepage by almost …
> svelte: Remove transitive dependency on all of @sourcegraph/wildcard (via eventLogger)

- deps.bzl
- go.mod
- go.sum
https://github.com/sourcegraph/zoekt/compare/cc5e093366ea...f2577c25dc61
- https://github.com/sourcegraph/zoekt/commit/4448a4594e Expand Repository.MergeMutable to cover more fields
- https://github.com/sourcegraph/zoekt/commit/f2577c25dc Bump version of go-ctags
Test Plan: tested in zoekt repo
> gomod: update zoekt to bump go-ctags

- cmd/telemetry-gateway/internal/events/events.go
In https://sourcegraph.slack.com/archives/C06CCJR4K9R/p1711370770336949 the format string got redacted :)
n/a
> telemetry-gateway: fixup cancel cause recording

- WORKSPACE
- dev/schema_migrations.bzl
We use the GCS JSON API directly instead of gsutil or gcloud because:
- gsutil may spend up to a ~1m20s trying to contact metadata.google.internal
without a discovered way to disable that
- gcloud disallows unauthed access to an even public bucket
TODO: in future iterations we can explore how to properly invalidate this. For now we can force a refresh with `bazel sync`
`bazel run //internal/database/migration/shared:write_stitched_migration_graph` runs successfully and without a change to the file
> bazel: rework schema migrations reporule without gsutil

- internal/k8s/resource/pod/BUILD.bazel
- internal/k8s/resource/pod/example_test.go
- internal/k8s/resource/pod/pod.go
- internal/k8s/resource/pod/pod_test.go
- internal/maps/BUILD.bazel
- internal/maps/example_test.go
- internal/maps/maps.go
- internal/maps/maps_test.go
- Add the `pod` pkg that creates k8s pod resources with patterns and defaults common to Sourcegraph. 
- Add `maps` pkg with some helper functions to help manage merging maps inside of k8s resources.
> k8s/resource: Add pkg for creating k8s pod resources

- internal/search/job/jobutil/exhaustive_job_test.go
- internal/search/job/jobutil/job.go
- internal/search/job/jobutil/job_test.go
- internal/search/query/helpers.go
- internal/search/query/helpers_test.go
- internal/search/zoekt/query_test.go
Backport to 5.3 of https://github.com/sourcegraph/sourcegraph/pull/61301
This change updates file extension lang matching to be case-insensitive. This is more flexible and consistent with GitHub search also.
Fixes https://github.com/sourcegraph/sourcegraph/issues/60575
Ensure unit tests of all impacted compontents are updated and passing
Manually test locally for both content based and file based lang matching
> Search: [BACKPORT] make lang filters always case insensitive

- .aspect/bazelrc/ci.sourcegraph.bazelrc
- WORKSPACE
- client/shared/dev/BUILD.bazel
- client/shared/dev/runMochaTestsWithPercy.js
- dev/mocha.bzl
- sg.config.yaml
`bazel build` on percy mocha targets (such as //client/web/src/integration:integration-tests) no longer result in actually running the test!
Originally, we used `js_run_binary` with `build_test` as `js_test` doesnt support stamping, and we need to be able to read volatile variables for percy. 
Then, we worked around https://github.com/bazelbuild/bazel/issues/16231 in https://github.com/sourcegraph/sourcegraph/pull/58505 by not explicitly depending on the stamp variables, but exploiting a bit of a hack to read them anyways (will this work with RBE?)
Now, given that we're not explicitly stamping and still using the hack, we can use `js_test` instead, to avoid having the tests run as part of `bazel build`, instead only when we run `bazel test` (as is good :relieved:)
It is apparently …
> bazel: refactor percy mocha tests to js_test instead of js_run_binary + build_test

- client/web/src/user/settings/profile/UserSettingsProfilePage.tsx
Changed "contact support" link from `https://sourcegraph.com/contact` to `support@sourcegraph.com` email address.
Ran it locally, it looks good to me:
It doesn't affect enterprise because this is behind an "If dotcom" flag.
> Change "contact support" link to email address

- .aspect/bazelrc/ci.sourcegraph.bazelrc
- dev/ci/run-chromatic.sh
Closes https://github.com/sourcegraph/devx-support/issues/740
Also addresses the `npm package` copy failure we've been observing in CI
CI and https://buildkite.com/sourcegraph/sourcegraph/builds/266509#018e7bed-e339-419d-8857-f86d003e9b07
> ci: fix chromatic and add bazelrc flag

- deps.bzl
- go.mod
- go.sum
After investigating the performance impact of the List optimization, we noticed we did not in practice use the performance improvement. Additionally, in a large number of cases the more advanced synchronization was leading to worse performance. So this update includes two commits which fix the optimization and revert the concurrency changes.
https://github.com/sourcegraph/zoekt/compare/931974dd953e...8cf8887a903a
- https://github.com/sourcegraph/zoekt/commit/7621acc2c5 shards: selectRepoSet supports queries which are not wrapped in and
- https://github.com/sourcegraph/zoekt/commit/8cf8887a90 Revert "shards: respect scheduler and use smarter synchronization for List"
Test Plan: tested in zoekt and this CI
> gomod: update zoekt to fix List optimization

- deps.bzl
- go.mod
- go.sum
NOTE: This is not a backport from sourcegraph's main branch, but rather updating backports that have occurred on the zoekt sourcegraph-5.3 branch.
This includes an improvement performance improvement for List. This change was generated with "./dev/zoekt/update sourcegraph-5.3". The sourcegraph-5.3 branch tracks the version of zoekt used by the 5.3 release branch in sourcegraph.
https://github.com/sourcegraph/zoekt/compare/245e0cebf761...6364497e6146
- https://github.com/sourcegraph/zoekt/commit/8f6d308e8e shards: use selectRepoSet in List
- https://github.com/sourcegraph/zoekt/commit/2da0b9825a shards: respect scheduler and use smarter synchronization for List
- https://github.com/sourcegraph/zoekt/commit/31adf4c3db shards: selectRepoSet supports queries which are not wrapped in and
- …
> gomod: update zoekt to include List performance improvement

- dev/managedservicesplatform/operationdocs/index.go
- dev/managedservicesplatform/operationdocs/index_test.go
- dev/managedservicesplatform/operationdocs/operationdocs.go
- dev/managedservicesplatform/operationdocs/operationdocs_test.go
- dev/managedservicesplatform/operationdocs/testdata/TestRender/basic.golden
- dev/managedservicesplatform/operationdocs/testdata/TestRender/with_README.golden
- dev/managedservicesplatform/operationdocs/testdata/TestRenderIndexPage.golden
- dev/managedservicesplatform/spec/spec.go
This allows MSP operators to define a custom introduction to their service by writing a `README.md` file adjacent to their service specification in https://github.com/sourcegraph/managed-services. The README is parsed, stripped of the first header (which must be an H1 with the service name), all H2+ gets indented (to fit in nicely into the generated docs), and included under the `Service overview` section.
This closes https://github.com/sourcegraph/managed-services/issues/382 for now - while @chrsmith's idea to have a `/.msp/...` convention in source code repos, it's a bit finicky to reach upstream for the required files.
The custom README can be a large, detailed all-in-one page such that `go/msp-ops/<my-service>` can be used as a go-to reference for everything about that service, or …
> msp: support README.md in managed-services repo as mixins for generated docs

- cmd/executor/docker-mirror/_ami.build.sh
There is a bug in the 5.3 CI pipeline with `docker mirror build`  where it fails because the `workdir` already exists.
This also makes it consistent with `vm-image/_ami.build.sh`
```
Target //cmd/executor/docker-mirror:ami.build up-to-date:
bazel-bin/cmd/executor/docker-mirror/ami.build
Aspect @@rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of //cmd/executor/docker-mirror:ami.build up-to-date (nothing to build)
(13:48:00) INFO: Elapsed time: 30.101s, Critical Path: 0.02s
(13:48:00) INFO: 1 process: 1 internal.
(13:48:00) INFO: Build completed successfully, 1 total action
(13:48:00) INFO: Running command line: bazel-bin/cmd/executor/docker-mirror/ami.build dev/tools/gcloud dev/tools/packer
mkdir: cannot create directory 'workdir': File exists
Error: bazel exited with exit code: 1 …
```
> ci: create dir if does not exist

- cmd/frontend/hubspot/hubspotutil/hubspotutil.go
Add event type to HubSpot error logs. Help debug issues like [this one](https://sourcegraph.slack.com/archives/C05GJPTSZCZ/p1711488395693409).
CI
> add event type to HubSpot error logs

- internal/k8s/resource/pod/pod_test.go
- internal/k8s/resource/pvc/BUILD.bazel
- internal/k8s/resource/pvc/example_test.go
- internal/k8s/resource/pvc/pvc.go
- internal/k8s/resource/pvc/pvc_test.go
Add `pvc` pkg to define k8s persistent volume claims with patterns and defaults common to Sourcegraph.
> k8s/resource: Add pkg for creating k8s persistent volume claim resources

- cmd/frontend/graphqlbackend/schema.graphql
- cmd/frontend/graphqlbackend/user.go
- cmd/frontend/graphqlbackend/users_test.go
When debugging, I fairly regularly need to look up a user by an ID from a log message or a trace or something. In order to do that, I currently resort to a hack like writing a test like the following:
```go
func TestMarshalUserID(t *testing.T) {
t.Fatal(gql.MarshalUserID(38428))
}
```
then using the generated ID to query with GraphQL:
```graphql
query {
node(id:"VXHalsdgh=") {
...on User { ... }
}
}
```
This is not an obvious solution for what should be a simple operation, especially because when we're trying to look up a user by ID, we're frequently in a hurry, which then makes the most obvious solution just hitting the database directly.
This PR just adds `intID` as a queryable field on the `user()` GraphQL query. It's documented as for debugging to hopefully discourage people from …
> GraphQL: add ability to query by user ID for debugging

- cmd/frontend/graphqlbackend/schema.graphql
- cmd/frontend/graphqlbackend/user.go
- cmd/frontend/graphqlbackend/user_test.go
- cmd/frontend/graphqlbackend/users_test.go
Followup from https://github.com/sourcegraph/sourcegraph/pull/61424#discussion_r1541447702
Also moves the test from `users_test.go` to `user_test.go` , which is a more appropriate place for it.
Updated test, manually tested.
> GraphQL: rename intID to databaseID

- cmd/worker/internal/embeddings/repo/scheduler.go
- internal/embeddings/schedule.go
We return early, either if embeddings are disabled or if there are no repos matching any policy.
Before, we scheduled embeddings for all repos returned by `ListMinimalRepos(ctx, database.ReposListOptions{IDs: nil})` in `ScheduleRepositoriesForPolicy`. Reading the documentation of `RepoListOptions.IDs`  "When zero-valued, this is omitted from the predicate set", this might cause repos to get embedded even if embeddings are disabled and no policies are defined. This causes 1 call to gitserver per repo.
Test plan:
CI
> embeddings: don't schedule jobs if disabled

- dev/sg/msp/example/job.template.yaml
- dev/sg/msp/example/service.template.yaml
- dev/sg/msp/example/testdata/TestNewJob/dev/insert_environment.golden
- dev/sg/msp/example/testdata/TestNewJob/dev/spec.golden
- dev/sg/msp/example/testdata/TestNewJob/prod/insert_environment.golden
- dev/sg/msp/example/testdata/TestNewJob/prod/spec.golden
- dev/sg/msp/example/testdata/TestNewService/dev.golden
- dev/sg/msp/example/testdata/TestNewService/dev/insert_environment.golden
- dev/sg/msp/example/testdata/TestNewService/dev/spec.golden
- dev/sg/msp/example/testdata/TestNewService/prod.golden
- dev/sg/msp/example/testdata/TestNewService/prod/insert_environment.golden
- dev/sg/msp/example/testdata/TestNewService/prod/spec.golden
If opening a generated MSP service file in your editor, but as part of a different workspace/repo, then vscode doesnt pick up what schema file to use for it, resulting in no intellisense. The yaml langserver supports a magic comment to point to a relative file, that works in this case :slightly_smiling_face: 
Validated locally with local sg build and `sg msp init ...`
> msp: add yaml langserver magic comment for schema

- internal/k8s/resource/role/BUILD.bazel
- internal/k8s/resource/role/example_test.go
- internal/k8s/resource/role/role.go
- internal/k8s/resource/role/role_test.go
Add `role` pkg to define k8s roles with patterns and defaults common to Sourcegraph.
> k8s/resouce: Add pkg for creating k8s role resources

- internal/k8s/resource/secret/BUILD.bazel
- internal/k8s/resource/secret/example_test.go
- internal/k8s/resource/secret/secret.go
- internal/k8s/resource/secret/secret_test.go
Add `secret` pkgs to define k8s secrets with patterns and defaults common to Sourcegraph.
> k8s/resouce: Add pkg for creating k8s secret resources

- internal/k8s/resource/rolebinding/BUILD.bazel
- internal/k8s/resource/rolebinding/example_test.go
- internal/k8s/resource/rolebinding/rolebinding.go
- internal/k8s/resource/rolebinding/rolebinding_test.go
Add `rolebinding` pkg to define k8s relebindings with patterns and defaults common to Sourcegraph.
Full unit testing coverage as well as testable examples
> k8s/resource: Add pkg for creating k8s rolebinding resources

- client/web/src/enterprise/rbac/SiteAdminRolesPage.story.tsx
- client/web/src/enterprise/rbac/SiteAdminRolesPage.tsx
- client/web/src/enterprise/rbac/components/CreateRoleModal.story.tsx
- client/web/src/enterprise/rbac/components/CreateRoleModal.tsx
- client/web/src/enterprise/rbac/components/RoleNode.story.tsx
- client/web/src/enterprise/rbac/components/RoleNode.tsx
- client/web/src/enterprise/repo/settings/RepoSettingsLogsPage.story.tsx
- client/web/src/enterprise/repo/settings/RepoSettingsLogsPage.test.tsx
- client/web/src/enterprise/repo/settings/RepoSettingsLogsPage.tsx
- client/web/src/enterprise/repo/settings/RepoSettingsPermissionsPage.tsx
- client/web/src/enterprise/search-jobs/SearchJobsPage.story.tsx
- client/web/src/enterprise/search-jobs/SearchJobsPage.tsx
- client/web/src/routes.tsx
- client/web/src/site-admin/routes.tsx
> v2t: add v2t to src/enterprise/rbac, /repo, and /search-jobs

- internal/insights/query/streaming_query_executor.go
Fixes https://github.com/sourcegraph/sourcegraph/issues/61370
Simple fix to avoid failing if search API got results with alerts, log them instead and return list of repo
- Check that you can resolve repositories in the creation UI with query which produce search with alerts 
- To setup these alerts you can add an empty repo to you local instance
> Code Insights: Log code insights alerts instead failing while gathering repo list

- client/web/src/LegacyLayout.tsx
- client/web/src/integration/jscontext.ts
- client/web/src/marketing/components/SurveyRatingRadio.tsx
- client/web/src/marketing/page/SurveyForm.tsx
- client/web/src/marketing/page/SurveyPage.story.tsx
- client/web/src/marketing/page/SurveyPage.test.tsx
- client/web/src/marketing/page/SurveyPage.tsx
- client/web/src/marketing/toast/SurveyToast.story.tsx
- client/web/src/marketing/toast/SurveyToast.test.tsx
- client/web/src/marketing/toast/SurveyToastContent.tsx
- client/web/src/marketing/toast/SurveyToastTrigger.tsx
- client/web/src/marketing/toast/SurveyUserRatingToast.tsx
- client/web/src/routes.tsx
- client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
> v2t: add v2t to NPS surveys

- cmd/searcher/internal/search/BUILD.bazel
- cmd/searcher/internal/search/zoekt_search.go
- dev/check/go-dbconn-import.sh
- dev/linters/dbconn/dbconn.go
- internal/search/symbol/BUILD.bazel
- internal/search/symbol/symbol.go
- internal/search/zoekt/BUILD.bazel
- internal/search/zoekt/query.go
- internal/search/zoekt/zoekt.go
- internal/search/zoektquery/BUILD.bazel
- internal/search/zoektquery/query.go
In a recent incident it was bought up that hot fixing searcher had a risk since it speaks to the DB. I investigated and noticed it doesn't actually connect, but does have dbconn as an unused transitive dep.
This commit refactors out the bit of logic used by searcher into a pure package. To do so I did a few renames, but functionally there is no change in logic other than the searcher binary shedding some heavy dependencies.
Additionally I updated the go-dbconn-import check to ensure searcher isn't accidently using the database again.
Test Plan: CI
> searcher: remove unused dependency on dbconn pkg

- client/web/src/get-cody/GetCodyPage.tsx
- Closes https://github.com/sourcegraph/sourcegraph/issues/60679
Just a very simple two-line change.
Tested authed and un-authed with and without the change: I could repro the old behavior and saw that this change fixes it. See it work in this 1-min Loom: https://www.loom.com/share/056ebfe326244c18966e1500e735fa49
> PLG: Redirect user from /get-cody if unauthed

- client/web-sveltekit/src/routes/+layout.svelte
- client/web-sveltekit/src/routes/+layout.ts
- client/web-sveltekit/src/routes/Header.svelte
- client/web-sveltekit/src/routes/layout.gql
- client/web/src/nav/GlobalNavbar.tsx
- client/web/src/sveltekit/SvelteKitNavItem.tsx
- client/web/src/sveltekit/util.ts
Basically, when you opt into or out of the svelte experiment, it persists that choice. The rollout flag is now only effectively used if you have not done either of these actions. Once you opt in or out, that choice is remembered by saving a feature flag override.
Previously, enabling the feature was done with URL-level feature flag overrides, which is problematic because they don't stay enabled/disabled.
This should be the last thing needed before enabling by default on S2. Closes https://github.com/sourcegraph/sourcegraph/issues/61298
https://github.com/sourcegraph/sourcegraph/assets/12631702/038cfb5b-2d30-46a6-8299-7fde46562e77
> Svelte: persist opt in/out

- client/web/src/cody/subscription/CodySubscriptionPage.module.scss
- client/web/src/cody/subscription/CodySubscriptionPage.tsx
- Part of https://github.com/sourcegraph/self-serve-cody/issues/506
I had to add an unexpected CSS rule to get the alert to display correctly because of its parent having `display: flex`.
Unrelated: fixed a few warnings around aria labels to improve accessibility.
Ran locally. This is how it looks:
> PLG: Add "no subscription" alert

- internal/k8s/resource/service/BUILD.bazel
- internal/k8s/resource/service/example_test.go
- internal/k8s/resource/service/service.go
- internal/k8s/resource/service/service_test.go
Add `service` pkg to define k8s services with patterns and defaults common to Sourcegraph.
> k8s/resource: Add pkg for creating k8s service resources

- CHANGELOG.md
- client/web/src/repo/tree/TreePage.test.tsx
- client/web/src/repo/tree/TreePage.tsx
- client/web/src/repo/tree/TreePageContent.tsx
- client/web/src/repo/utils.tsx
Followup to PR #60909, which added a Commits button to the folders, and included the revision in it, exposing the shortcoming of the Commits button in the repo root page, which didn't include the revision.
Closes #60487
When viewing a repository root page, click the Commits button and ensure that the URL includes the current revision (branch, tag or commit).
> Commits buttons: handle selected revision and support Perforce terminology

- cmd/frontend/hubspot/contacts.go
Full discussion thread: https://sourcegraph.slack.com/archives/C01PQEVJ5A9/p1711377521550879
Context:
> Hi team - we're having a data discrepancy in Hubspot. The database is showing 0 contacts created via signup between 3/20 and 3/24 - can someone point me to the correct Looker table to get a good sense of how many contacts we should be seeing?
Solution:
>AHA, with [the new error logging](https://github.com/sourcegraph/sourcegraph/pull/61405/files) that I added yesterday deployed, I am finally able to find the errors associated with signups.
>
>...
>
>The new errors for signups are:
```error="json: cannot unmarshal number 7XXXXXXXXX into Go struct field ContactResponse.vid of type int32"```
>
>Basically—VIDs (or visitor IDs) are now numbers like 7,XXX,XXX,XXX. Int32s have a maximum value …
> switch hubspot response type to uint64

- internal/repos/awscodecommit.go
- internal/repos/azuredevops.go
- internal/repos/bitbucketcloud.go
- internal/repos/bitbucketserver.go
- internal/repos/exclude.go
- internal/repos/exclude_test.go
- internal/repos/github.go
- internal/repos/gitlab.go
- internal/repos/gitolite.go
- internal/repos/other.go
There was a bug in this logic: For some code host types, we would overwrite the value of exact if both Name and ID were specified in an exclusion rule, for example. Instead, we should OR match on _any_ given exact match. 
This is just a side-effect though, the actual improvement here is that we no longer need to iterate over thousands of rules for simple exact matches. We have a customer who wants to use potentially up to 20000 statements, and during code host syncing, this would need to run 20000 times, for a total of 400,000,000 exact comparisons. 
I added a benchmark for this. Before:
```
goos: darwin
goarch: arm64
pkg: github.com/sourcegraph/sourcegraph/internal/repos
BenchmarkExcludeExact-10            8205            144040 ns/op               0 B/op          0 allocs/op
PASS
``` …
> Fix and optimize repo exclusions

- internal/k8s/resource/storage/BUILD.bazel
- internal/k8s/resource/storage/example_test.go
- internal/k8s/resource/storage/storageclass.go
- internal/k8s/resource/storage/storageclass_test.go
Add `storage` pkg to create k8s storageclass with patterns and defaults common to Sourcegraph.
> k8s/resource: Add pkg for creating k8s storageclass resources

- internal/k8s/resource/serviceaccount/BUILD.bazel
- internal/k8s/resource/serviceaccount/example_test.go
- internal/k8s/resource/serviceaccount/serviceaccount.go
- internal/k8s/resource/serviceaccount/serviceaccount_test.go
Add `serviceaccount` pkg to create k8s service accounts with patterns and defaults common to Sourcegraph.
> k8s/resource: Add pkg for creating k8s serviceaccount resources

- schema/schema.go
- schema/settings.schema.json
We seem to have
- Feature flags: https://sourcegraph.com/docs/dev/how-to/use_feature_flags#when-to-use-feature-flags - **I don't think they fit here**
- Site config: https://sourcegraph.com/docs/admin/config/site_config - designed to be enabled/disabled by site admins. **At this point, I don't think this should be an admin-facing setting**
- Settings? https://sourcegraph.com/docs/admin/config/settings. Which seem to contain `experimentalFeatures` object that contains features similar to what we're building: https://sourcegraph.com/docs/admin/how-to/enable-experimental-feature. **Let's put it there**
The `schema.go` file is generated automatically.
N/A
> Add syntactic indexing experimental feature (disabled)

- dev/ci/internal/ci/changed/diff.go
These conditions were added so that we could remove the `prometheus-gcp` image and package and not let CI try and build it. Now that both have been removed we can remove these conditons
CI
> ci: remove conditions for wolfi prometheus gcp

- dev/ci/images/images.go
- dev/ci/internal/ci/legacy_operations.go
`blobstore2` isn't used anymore
CI
> ci: remove blobstore2 from SourcegraphDockerImagesMisc

- dev/ci/semgrep-scan.sh
The semgrep check fails on tags since it uses the branch refspec but on a tag those do not exist see https://buildkite.com/sourcegraph/sourcegraph/builds/266947#018e8a09-c8ad-4a3e-bf74-92cdb048f8da
CI and https://buildkite.com/sourcegraph/sourcegraph/builds/266955#018e8a2f-a110-409e-83c0-5d196b193857
> ci: set tag refspec for semgrep when working with tags

- cmd/batcheshelper/BUILD.bazel
- cmd/blobstore/BUILD.bazel
- cmd/cody-gateway/BUILD.bazel
- cmd/embeddings/BUILD.bazel
- cmd/executor/BUILD.bazel
- cmd/frontend/BUILD.bazel
- cmd/gitserver/BUILD.bazel
- cmd/loadtest/BUILD.bazel
- cmd/migrator/BUILD.bazel
- cmd/pings/BUILD.bazel
- cmd/precise-code-intel-worker/BUILD.bazel
- cmd/repo-updater/BUILD.bazel
- cmd/searcher/BUILD.bazel
- cmd/server/BUILD.bazel
- cmd/symbols/BUILD.bazel
- cmd/syntactic-code-intel-worker/BUILD.bazel
- cmd/telemetry-gateway/BUILD.bazel
- cmd/worker/BUILD.bazel
- dev/sg/BUILD.bazel
- docker-images/prometheus/cmd/prom-wrapper/BUILD.bazel
- internal/cmd/ghe-feeder/BUILD.bazel
- internal/cmd/search-blitz/BUILD.bazel
- internal/cmd/src-cli-version/BUILD.bazel
- internal/database/migration/shared/data/cmd/generator/BUILD.bazel
- internal/version/BUILD.bazel
Instead of having to declare the stamp vars on every go_binary (and risk forgetting one, like in https://github.com/sourcegraph/sourcegraph/pull/61480/files#r1543982602), we can stamp at the go_library declaration point instead.
Locally tested with `strings`
> bazel: move internal/version stamping to internal/version's go_library decl

- .aspect/workflows/config.yaml
- cmd/msp-example/BUILD.bazel
Stamps targets delivered by aspect workflows.
Adds x_defs to `msp-example` for version stamping
CI, tested in [266843](https://buildkite.com/sourcegraph/sourcegraph/builds/266843)
```sh
$ docker run --rm -it us.gcr.io/sourcegraph-dev/msp-example:ff102caaa6c0_266843 --help  
SERVICE: example
VERSION: jac-stamp_266843_2024-03-28_5.3-ff102caaa6c0
CONFIGURATION OPTIONS:
- 'STATELESS_MODE': if true, disable dependencies (default: "false")
- 'VARIABLE': variable value (default: "13")
- 'MSP': indicates if we are running in a MSP environment (default: "false")
- 'ENVIRONMENT_ID': MSP Service Environment ID (default: "unknown")
- 'PORT': service port (required)
- 'OTEL_SDK_DISABLED': disable OpenTelemetry SDK (default: "false")
```
> VERSION: jac-stamp_266843_2024-03-28_5.3-ff102caaa6c0
> aspect workflows: stamp delivery targets

- client/web/src/get-cody/GetCodyPage.tsx
This is a follow-up to https://github.com/sourcegraph/sourcegraph/pull/61470/. Raman reported [here](https://sourcegraph.slack.com/archives/C01KPE23H4M/p1711699203555329) that the redirect showed the wrong page.
It's a URL collision between the marketing site and the Sourcegraph webapp. The problem is that my solution used the `useNavigate` hook which does a soft redirect inside the React app, and the `/cody` page happens to exist there.
But the correct solution is to do a _hard_ redirect so that the load balancer has a chance to catch the request and serve the marketing page.
This PR replaces the soft redirect with a hard one.
Tested it locally; the redirect still works, and it reloads the whole page.
> /get-cody: Replace soft redirect with hard one

- internal/k8s/resource/configmap/BUILD.bazel
- internal/k8s/resource/configmap/configmap.go
- internal/k8s/resource/configmap/configmap_test.go
- internal/k8s/resource/configmap/example_test.go
Add `configmap` pkg to create k8s configmaps with patterns and defaults common to Sourcegraph.
> k8s/resource: Add pkg for creating k8s configmap resources

- internal/k8s/resource/ingress/BUILD.bazel
- internal/k8s/resource/ingress/example_test.go
- internal/k8s/resource/ingress/ingress.go
- internal/k8s/resource/ingress/ingress_test.go
Add `ingress` pkg to create k8s ingress with patterns and defaults common to Sourcegraph.
> k8s/resource: Add pkg for creating k8s ingress resources

- internal/k8s/resource/rolebinding/rolebinding_test.go
- internal/k8s/resource/statefulset/BUILD.bazel
- internal/k8s/resource/statefulset/example_test.go
- internal/k8s/resource/statefulset/statefulset.go
- internal/k8s/resource/statefulset/statefulset_test.go
Add `statefulset` pkg to create k8s statefulsets with patterns and defaults common to Sourcegraph.
> k8s/resource: Add pkg for creating k8s stateful set resources

- internal/k8s/resource/deployment/BUILD.bazel
- internal/k8s/resource/deployment/deployment.go
- internal/k8s/resource/deployment/deployment_test.go
- internal/k8s/resource/deployment/example_test.go
- internal/k8s/resource/serviceaccount/serviceaccount.go
- internal/k8s/resource/storage/storageclass.go
Add `deployment` pgk to create k8s deployment with patterns and defaults common to Sourcegraph.
> k8s/resource: Add pkg for creating k8s deployment resources

- deps.bzl
- go.mod
- go.sum
- internal/search/job/jobutil/job_test.go
- internal/search/zoekt/query_test.go
This updates zoekt to have one more commit. See details of commit for more information.
https://github.com/sourcegraph/zoekt/compare/8cf8887a903a...c39011a14191
- https://github.com/sourcegraph/zoekt/commit/c39011a141 all: use a faster vendored regexp/syntax/Regexp.String
Test Plan: CI
Part of https://github.com/sourcegraph/sourcegraph/issues/61462
> gomod: update zoekt to remove perf regression in go 1.22

- release.yaml
This checks that tags the last commit on the branch during finalization.
For safety I've also added a test to check that the tag doesn't exist before trying to tag
Closes #61071
* Internal release
- https://buildkite.com/sourcegraph/sourcegraph/builds/266962
* Promotion
- https://buildkite.com/sourcegraph/sourcegraph/builds/266966
* [qa-v5.3.666 tag](https://github.com/sourcegraph/sourcegraph/releases/tag/qa-v5.3.666)
> ci+release: update manifest to tag during finalization

- client/web/src/open-in-editor/OpenInEditorActionItem.tsx
- client/web/src/open-in-editor/editors.ts
- client/web/src/repo/blob/BlobPage.tsx
> v2t: add v2t to src/open-in-editor

- cmd/gitserver/internal/git/gitcli/BUILD.bazel
- cmd/gitserver/internal/git/gitcli/archivereader.go
- cmd/gitserver/internal/git/gitcli/archivereader_test.go
- internal/byteutils/BUILD.bazel
- internal/byteutils/nullscanner.go
Closes #61518 
We used `bytes.Fields` to parse the output from the `git` command, but `bytes.Fields` splits on all whitespace. This leads to erroneous file paths when the file paths have spaces in them, since we'll only be using the final path segment.
This PR passes the `--name-only` flag to the `git ls-tree` command so that we don't have to do any parsing to get the path.
Unit test added.
> [gitserver] ArchiveReader correctly handles paths with spaces

- dev/codeintel-qa/cmd/clear/BUILD.bazel
- dev/codeintel-qa/cmd/clone-and-index/BUILD.bazel
- dev/codeintel-qa/cmd/download/BUILD.bazel
- dev/codeintel-qa/cmd/query/BUILD.bazel
- dev/codeintel-qa/cmd/upload-gcs/BUILD.bazel
- dev/codeintel-qa/cmd/upload/BUILD.bazel
No longer needed since https://github.com/sourcegraph/sourcegraph/pull/60569
ctrl+f + bazel query to find any references
> chore: remove unused darwin-arm64 cross binaries for codeintel-qa

- dev/ci/internal/ci/release_operations.go
- release.yaml
release test will pull the migrator image for this release and then check whether the folder /schema-descriptions contains the json files for the current release version.
Closes https://github.com/sourcegraph/sourcegraph/issues/61068
Test locally
```
sg release run test --inputs=server=v5.3.666 --version=v5.3.666
👉 [     setup] Finding release manifest in "."
[     setup] No explicit branch name was provided, assuming current branch is the target: wb/release/schema-descriptions-test
[     setup] Found manifest for "sourcegraph" (github.com/sourcegraph/sourcegraph)
[      meta] Owners: @sourcegraph/release
[      meta] Repository: github.com/sourcegraph/sourcegraph
👉 [      vars] Variables
[      vars] version="v5.3.666"
[      vars] tag="5.3.666"
[      vars] …
```
> release: Add release test to check schema descriptions

- dev/sg/sg_rfc.go
In between things, noticed that `sg rfc` is annoying with positional flags, so made it sane. We somehow got used to this, and it stayed like this. Until now. 
before: 
```
$ sg rfc create "glorious changes" --private
Incorrect Usage: flag provided but not defined: -private
$ sg rfc create --help
NAME:
sg rfc create - Create Sourcegraph RFCs
USAGE:
sg rfc create [command options] --type <type> [title...]
OPTIONS:
--type value  the type of the RFC to create (valid: solution) (default: solution)
$ say "where the hell are you, damn private flag" 
$ sg rfc --help 
```
```
$ sg rfc --private create "glorious changes"
$ sg rfc create "glorious changes" --private
```
after: 
```
$ sg rfc create --private "glorious changes"
$ say "sanity restored"
```
> chore(sg): rfc flags are now position independent

- dev/ci/scripts/wolfi/update-base-image-hashes.sh
Wofli is currently timing out see [here](https://buildkite.com/sourcegraph/sourcegraph/builds/267161#018e9f87-33ff-457f-aac8-38fb8b41bc51) so we add some things to see WHY it is doing that
* Print out the commands
* Use switch instead of checkout since checkout can possibly hang when the repo is in a detached state
* swap out `:` for `true` since it is slightly more readable
CI
> wolfi: add debugging and use switch for new branch

- client/web/src/opencodegraph/global/ToggleOpenCodeGraphVisibility.tsx
- client/web/src/repo/blob/BlobPage.tsx
> v2t: add v2t to src/openCodeGraph

- CHANGELOG.md
- doc/admin/observability/dashboards.md
- internal/httpcli/client.go
- internal/httpcli/client_test.go
- monitoring/definitions/frontend.go
This PR adds a Prometheus metric that tracks the rate that Sourcegraph issues HTTP request that target external hosts (e.g. github.com, gitlab.com, etc.)
For every HTTP request, the metric tracks the hostname, HTTP method, and response code. 
I have also added a new "External HTTP Request Rate" section the frontend Grafana dasboard that plots this metric. See the example screenshot below.
- Some rote unit tests
- Generated the above screenshot on my local sourcegraph instance with `sg start monitoring`
> httpcli: add prometheus metric for monitoring the rate that Sourcegraph issues requests to external services

- cmd/cody-gateway/internal/httpapi/maintenance.go
- internal/sams/client.go
In https://github.com/sourcegraph/sourcegraph/pull/61514 I added a new codepath where we instantiate a SAMS client. However, when trying to use the new APIs it was failing with an odd error message.
After taking a closer look, apparently the `TokenURL` is a really important configuration setting when supplying OAuth client credentials 🤦 ...
This PR fixes that for the new callsite, but also updates `sams.NewClient` to supply a default value in case it is missed in the future. (Since it's the same URL for all callers of `sams.NewClient` throughout the repo.)
NA
> Fix SAMS client configuration; make more flexible

- client/web-sveltekit/BUILD.bazel
- client/web-sveltekit/dev/generate-graphql.ts
- client/web-sveltekit/dev/vite-graphql-codegen.ts
- client/web-sveltekit/src/lib/graphql/urql.ts
- client/web-sveltekit/src/lib/wildcard/Button.svelte
- client/web-sveltekit/src/lib/wildcard/menu/Menu.svelte
- client/web-sveltekit/src/routes/layout.gql
- client/web-sveltekit/vite.config.ts
This commit updates the bazel build file to execute `svelte-check` in CI.
To make this work correctly we need to run additional commands to generate all the files that are needed by the code. Specifically that's `svelte-kit sync` and the graphql code/type generation. The code was refactored to make that work.
This commit also fixes issues detected by `svelte-check`.
IMPORTANT
Running `svelte-check` in CI differs in two ways from running it locally:
1. Locally `svelte-check` will also check all local `@sourcegraph/*`, because they symlink the orginal source code. In CI/Bazel those dependencies are already built and therefore are not checked by Bazel. However, this is what we want because the dependencies do not always conform to the rules set by `svelte-check`.
2. Source files that are not …
> svelte/ci: Run `svelte-check` in CI

- release.yaml
Noticed we kept the placeholder after adding the first real test. This PR drops it. 
CI
> chore(rel): remove placeholder in release test

- CHANGELOG.md
- cmd/frontend/internal/dotcom/productsubscription/codygateway_graphql.go
- cmd/frontend/internal/dotcom/productsubscription/codygateway_graphql_test.go
- internal/licensing/codygateway.go
- internal/licensing/codygateway_test.go
Adds GPT3.5, GPT4 Turbo, GPT 4 to the list of supported chat models for enterprise ([thread](https://sourcegraph.slack.com/archives/C012NU3PXA9/p1712103525033819?thread_ts=1712094412.441679&cid=C012NU3PXA9)).
- CI
> Add OpenAI models to supported chat models for enterprise customers

- doc/admin/observability/alerts.md
- monitoring/definitions/git_server.go
Making sure this doesn't randomly trigger all the time.
Ideally, I would want this to read "more than 3 times in 30 minutes above threshold" or so, but not sure if that's expressable.
Code review.
> monitoring: Make gitserver alert less trigger-friendly

- dev/release/calendar.jsonc
- dev/sg/internal/release/BUILD.bazel
- dev/sg/internal/release/calendar.go
- dev/sg/internal/release/release.go
- go.mod
This PR adds a new subcommand to the `sg release` command. This command `cal` is used to send out calendar invites for upcoming releases. It also includes a new configuration file for defining the calendar dates and should always be in sync with the [Sourcegraph handbook release schedule](https://handbook.sourcegraph.com/departments/engineering/dev/process/releases/#release-schedule)
Sent out calendar invites for the monthly releases happening in April, 2024 and May, 2024
> release: add sg command for sending calendar invites

- dev/build-tracker/BUILD.bazel
- dev/build-tracker/background.go
- dev/build-tracker/main.go
James said I can enable this now :clueless:
Ran locally, no more panic
> build-tracker: fix nil pointer in old build purger & enabling auto-rollout with MSP

- dev/build-tracker/main.go
We can use `contract.RegisterDiagnosticsHandlers` later, requires more work due to gorilla/mux incompatibilities 
curl'd locally
> build-tracker: update healthz endpoint for MSP deployment expectations

- cmd/telemetry-gateway/BUILD.bazel
This was disabled while an [issue](https://github.com/sourcegraph/sourcegraph/pull/61511) was investigated.
The issue has been solved so it is safe to re-enable
CI
> telemetry-gateway: re-enable msp delivery

- doc/admin/observability/dashboards.md
- internal/rockskip/BUILD.bazel
- internal/rockskip/index.go
- internal/rockskip/search.go
- internal/rockskip/server.go
- monitoring/definitions/symbols.go
This adds basic metrics to Rockskip and exposes them in a new panel group "Rockskip" on the dashboard of the Symbol service.
Test plan:
- manual testing: I enabled Rockskip locally, browsed unindexed commits and verified that the dashboards make sense. For example: I navigated to unindexed repos which caused search request errors and triggered index jobs.
> symbols: add metrics and panels for Rockskip

- doc/_generated.push.sh
Fixes https://github.com/sourcegraph/devx-support/issues/769
Tested locally, to make sure we get the right if predicate, it's always confusing when dealing with exit code. 
CI
> fix(docs): no delivery if triggered without changes

- dev/sg/internal/release/config.go
@burmudar rightfully mentioned that if we don't have steps, the tooling would still appear to be working, which might be confusing, as well, nothing would happen, just green text and exit 0. 
CI
> chore(rel): exit if no steps are defined

- dev/ci/push_all.sh
Shrinks down the output from the "Push xyz images" buildkite annotation!
See screenshots above for tested results
> ci: make pushed images annotation collapsible

- dev/sg/sg_ops.go
Do the right thing if someone specifies the public docker hub registry.
```
👉 using Docker Hub registry index.docker.io/sourcegraph
👉 updating images to latest
⚠️ Registry credentials are not provided and could not be retrieved from docker config.
⚠️ You will be using anonymous requests and may be subject to rate limiting by Docker Hub.
❌ cannot load docker creds from store: failed to find store provider or credential helper for https://registry.hub.docker.com/v2
Error: bazel exited with exit code: 1
```
> sg: detect and use dockerhub registry

- dev/ci/internal/ci/release_operations.go
Closes https://github.com/sourcegraph/sourcegraph/issues/61063
Should be merged after `sourcergaph/sourcegraph` has been clearred in https://github.com/sourcegraph/sourcegraph/issues/61062
CI
https://github.com/sourcegraph/sourcegraph/issues/61062
> rfc-795: use docker hub for public releases

- doc/admin/observability/dashboards.md
- internal/rockskip/index.go
- internal/rockskip/search.go
- internal/rockskip/server.go
- monitoring/definitions/symbols.go
Follow up from [this comment](https://github.com/sourcegraph/sourcegraph/pull/61547#pullrequestreview-1977509426)
This adds a p99.9 and p95 panel to monitor how long index requests have been waiting on the queue.
Test plan:
> rockskip: monitor indexing queue

- cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
During the decommissioning of enterprise embeddings it was necessary to contiue generating community embeddings on sourcegraph.com in support of JetBrains users. Since all PLG users now rely on symf for context it is possible to disable embeddings from being generated on sourcegraph.com, however when disabling embeddings in the config the PLG rate limits are not read from the site config.  This directly access the site config to read the embeddings limits bypassing the fact that embeddings are disabled. 
Because there is still a internal usage of embeddings for benchmarking purposes I will not be removing the related embeddings code.  
```graphql
{
dotcom{
codyGatewayDotcomUserByToken(token:"REDACTED"){
username
id
codyGatewayAccess{
embeddingsRateLimit{
source
limit
intervalSeconds …
```
> Read PLG embeddings limits directly from site config 

- internal/codycontext/context.go
While comparing context retrieval strategies, I noticed that keyword context
was returning much smaller result snippets than we did from embeddings. In
general, providing more surrounding context to the LLM can only help the
response quality.
This PR increases the number of context lines we return to 20. The reasoning:
* We didn't have problems with embeddings exceeding the context window size
(7000 tokens by default!). So we can use at least as much context as we did for
embeddings.
* Each embedding chunk is roughly 1024 chars (see [Cody context napkin
numbers](https://docs.google.com/spreadsheets/d/1xt-vEbvuQ8OoHXjaP28_YRn83ao377QKxrLsZ4J_62Q/edit#gid=0)).
I tested a variety of file types (Go, Typescript, Markdown), and this roughly
corresponded to 20 lines. It's also a conservative …
> Cody: increase size of context snippet

- CHANGELOG.md
- internal/licensing/codygateway.go
- internal/licensing/codygateway_test.go
Issue https://github.com/sourcegraph/sourcegraph/issues/61291
Adds Claude 3 family of anthropic models to the list of supported chat models for enterprise ([thread](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1712251852944669?thread_ts=1711632452.407259&cid=C04MSD3DP5L)).
- CI
> Adding new anthropic claude 3 models family to supported chat models for enterprise customers

- cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
Requesting Antropic Messages API with no `"messages"` field (e.g., with deprecated `"prompt"` field instead) caused the request to fail ([thread](https://sourcegraph.slack.com/archives/C05497E9MDW/p1712067925436309)). Check for the required field and return the error before making a request to LLM.
- CI
- Tested manually with cURL command mentioned in the thread against locally running instance and Cody Gateway
|Before|After|
|--|--|
|Sourcegraph Cody Gateway: unexpected status code 400: {"type":"error","error":{"type":"invalid_request_error","message":"messages: Field required"}}%`|Sourcegraph Cody Gateway: unexpected status code 400: {"error":"\"messages\" field is required"}|
> Cody Gateway: Antropic messages handler returns error out if request doesn't have required "messages" field

- cmd/frontend/internal/auth/bitbucketcloudoauth/BUILD.bazel
- cmd/frontend/internal/auth/bitbucketcloudoauth/session.go
- cmd/frontend/internal/auth/bitbucketcloudoauth/session_test.go
https://sourcegraph.slack.com/archives/C03JR7S7KRP/p1712180759513679?thread_ts=1712168903.358759&cid=C03JR7S7KRP
When a user signs in to Sourcegraph using a bitbucket oauth provider, there must be a corresponding Sourcegraph user with a verified email as their bitbucket account. (See https://sourcegraph.com/docs/admin/auth#linking-accounts-from-multiple-auth-providers). 
In the case where there isn't a matching Sourcegraph user with a verified email, we attempt to return an error message that looks like:
`No Sourcegraph user exists matching any of the verified emails: $VERIFIED_EMAILS.\n\nFirst error was: $ERROR` .
This was the original logic to construct the list of verified emails for the error message
```go
verifiedEmails := make([]string, 0, len(attempts))
for i, attempt := range …
```
> auth: bitbucket: fix slice indexing error when constructing oauth error messages

- client/web-sveltekit/src/lib/Avatar.stories.svelte
- client/web-sveltekit/src/lib/Avatar.svelte
- client/web-sveltekit/src/lib/Commit.svelte
- client/web-sveltekit/src/lib/repo/HistoryPanel.svelte
- client/web-sveltekit/src/lib/repo/LastCommit.stories.svelte
- client/web-sveltekit/src/lib/repo/LastCommit.svelte
- client/web-sveltekit/src/routes/UserMenu.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/stats/contributors/+page.svelte
- client/web-sveltekit/src/routes/search/PersonSearchResult.svelte
This (small) PR adds the `--avatar-size` property to any instance of the `Avatar` svelte component where needed. 
Manual testing
> Svelte: Avatar size bug fix

- dev/managedservicesplatform/spec/spec.go
- dev/sg/msp/helpers.go
- dev/sg/msp/sg_msp.go
This change migrates `generate` and `tfc sync` to use our service/env argument getters so that we return more consistent error messages. Errors around non-existent or missing service/env arguments now also provide relevant lists of possible values, such as all available services or all available environments for a valid service argument (see test plan examples).
Hopefully this makes errors easier to understand, as the possible values should give a better hint as to what arguments the command expects.
> sg/msp: retrieve service/env more consistently, provide possible values in errors

- dev/ci/internal/ci/release_operations.go
backport of #61360
CI and tested previously
> backport #61360 change of release public registry

- client/web-sveltekit/src/lib/repo/LastCommit.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
Fixes https://github.com/sourcegraph/sourcegraph/issues/61612 where the last commit information was causing the History panel to render incorrectly and not fill the available space.
**Before:**
**After:**
manual testing
> Bug: fixes UI bug causing the history panel not to fill the full space

- internal/search/exhaustive/service/BUILD.bazel
- internal/search/exhaustive/service/service.go
- internal/search/exhaustive/service/service_test.go
This fixes a bug in the evaluation of the feature flag for Search Jobs in the backend, where we would evaluate to "false" if other experimental features were set but "SearchJobs" was unset.
As a consequence, it could happen that the UI elements for Search Jobs were visible, but the backend returned a warning nevertheless. 
Test plan:
> search jobs: fix feature flag eval in backend

- dev/managedservicesplatform/internal/resource/privatenetwork/privatenetwork.go
Minor change to allow option 2 as outlined in https://github.com/sourcegraph/managed-services/issues/660#issuecomment-2027394872, but also could be beneficial in the future to investigate using private google access for e.g. Telemetry Gateway publishing to Cloud Run, which is pretty high-volume, and even for simple things like traces/metric export (tracked in https://github.com/sourcegraph/managed-services/issues/1093)
Deployed to msp-testbed-robert
> msp/privatenetwork: allow PrivateIpGoogleAccess from subnet

- dev/build-tracker/BUILD.bazel
- dev/build-tracker/build/build.go
- dev/build-tracker/config/config.go
- dev/build-tracker/integration_test.go
- dev/build-tracker/main.go
- dev/build-tracker/server_test.go
Triggers a buildkite pipeline when a build.finished event is received from buildkite in order to collect metrics & information about the build (coming in a later PR).
The details we attach as part of the build can be iterated upon as needed. For the most part, we can get all the details of the build that ultimately is triggering this by using the buildkite cli to query the build by its ID from the `DEVX_TRIGGERED_FROM_BUILD_ID` env var
A drawback appears to be that it will always show the owner of the token as the author/creator of the build (although the committer is preserved in `BUILDKITE_BUILD_AUTHOR` env var of the jobs)
Depends on https://github.com/sourcegraph/managed-services/pull/1096
Tested with payloads fetched from the webhook log, and with a personal token (see builds here: …
> build-tracker: trigger build-metrics pipeline on build.finished

- client/web-sveltekit/src/lib/search/resultsIndicator/SuggestedAction.svelte
- client/web-sveltekit/src/lib/search/resultsIndicator/SuggestedAction.test.ts
- client/web-sveltekit/src/routes/search/StreamingProgress.svelte
This PR introduces a "Search Jobs" suggestion in the popover when necessary. Additionally, it includes the suggestion in the results indicator.
The message displayed in the results indicator: 
The message displayed in the popover:
Both of these messages will appear simultaneously when the popover is active. Although this simultaneous display shouldn't pose an issue, I'd appreciate thoughts on this approach.
The message will display under the following conditions:
The search is completed with error.
The search is in a loading state.
For reference, here's how it looks when the message does not display: 
Adjust existing unit tests.
> Svelte [ResultsIndicator]: Add 'Search Jobs' message to popover

- client/web-sveltekit/src/lib/search/resultsIndicator/SuggestedAction.svelte
Using `Object.hasOwn()` circumvents the type system, so we shouldn't use this in conditional statements, in general.
The change is self-explanatory in the diff view.
Manual testing
> Svelte [bug]: adjust conditional to stay consistent with types

- dev/managedservicesplatform/operationdocs/operationdocs.go
- dev/managedservicesplatform/operationdocs/operationdocs_test.go
- dev/managedservicesplatform/operationdocs/testdata/TestRender/basic.golden
- dev/managedservicesplatform/operationdocs/testdata/TestRender/multi_env_rollout.golden
- dev/managedservicesplatform/operationdocs/testdata/TestRender/resources.golden
- dev/managedservicesplatform/operationdocs/testdata/TestRender/with_README.golden
Updates MSP ops pages to include deployment info and links to delivery pipelines if applicable
Deployed in this handbook pr: https://github.com/sourcegraph/handbook/pull/8845
docs changes
> msp: update ops with deployment info

- dev/sg/sg_backport.go
Before the start of monthly releases, release branches were named in the semver format `<MAJOR>.<MINOR>`, however part of the changes that monthly releases bring, the release branch naming is now in the format `<MAJOR>.<MINOR>.<PATCH>`. 
This PR ensures the `sg backport` command works with this new logic.
Manual testing. Led to the creation of [this PR](https://github.com/sourcegraph/sourcegraph/pull/61682)
> backport: remove patch version check

- WORKSPACE
- cmd/server/macro.bzl
> bazel: bump rules_{oci,pkg}

- internal/codeintel/autoindexing/internal/background/scheduler/job_scheduler.go
- internal/codeintel/policies/internal/store/configurations.go
- internal/codeintel/policies/internal/store/configurations_test.go
- internal/codeintel/policies/shared/types.go
- internal/codeintel/policies/transport/graphql/root_resolver_policy_queries.go
Add support for retrieving policies which enable syntactic indexing.
The meat of the PR is in the tests, which I improved a little, but they require much more work to be considered "easy to read".
New tests
Existing tests
> Syntactic indexing support in policy matcher

- CHANGELOG.md
- internal/repos/bitbucketcloud.go
- internal/repos/bitbucketcloud_test.go
- internal/repos/testdata/sources/BITBUCKETCLOUD-LIST-REPOS/with-repos.yaml
- schema/bitbucket_cloud.schema.json
- schema/schema.go
This aligns the configuration for Bitbucket Cloud with most other code hosts where we allow to name repos explicitly. This makes it easier to test the connection for a single repo first, instead of having to sync potentially thousands of repos right away.
Closes https://github.com/sourcegraph/sourcegraph/issues/60794
Added a test using real-world data with VCR and verified manually on my local instance that I can successfully sync single repos.
> Add support for naming repo explicitly for Bitbucket Cloud

- client/web/src/LegacySourcegraphWebApp.tsx
- client/web/src/notebooks/GlobalNotebooksArea.tsx
- client/web/src/notebooks/blocks/file/NotebookFileBlock.tsx
- client/web/src/notebooks/blocks/query/NotebookQueryBlock.story.tsx
- client/web/src/notebooks/blocks/query/NotebookQueryBlock.tsx
- client/web/src/notebooks/blocks/symbol/NotebookSymbolBlock.tsx
- client/web/src/notebooks/createPage/CreateNotebookPage.tsx
- client/web/src/notebooks/index.ts
- client/web/src/notebooks/listPage/NotebooksGettingStartedTab.tsx
- client/web/src/notebooks/listPage/NotebooksList.tsx
- client/web/src/notebooks/listPage/NotebooksListPage.story.tsx
- client/web/src/notebooks/listPage/NotebooksListPage.tsx
- client/web/src/notebooks/listPage/NotebooksListPageHeader.tsx
- client/web/src/notebooks/notebook/NotebookComponent.story.tsx
- client/web/src/notebooks/notebook/NotebookComponent.tsx
- client/web/src/notebooks/notebookPage/DeleteNotebookModal.tsx
- client/web/src/notebooks/notebookPage/EmbeddedNotebookPage.tsx
- client/web/src/notebooks/notebookPage/NotebookContent.tsx
- client/web/src/notebooks/notebookPage/NotebookPage.tsx
- client/web/src/notebooks/notebookPage/NotebookPageHeaderActions.tsx
- client/web/src/notebooks/notebookPage/NotebookShareOptionsDropdown.tsx
- client/web/src/notebooks/notebookPage/NotebookTitle.tsx
- client/web/src/notebooks/notebookPage/ShareNotebookModal.tsx
- client/web/src/routes.tsx
> v2t: add v2t to notebooks

- dev/sg/internal/std/BUILD.bazel
- dev/sg/internal/std/prompt.go
- dev/sg/msp/sg_msp.go
As titled - we can now prompt you through service setup. This is a small QOL improvement that makes providing the required parameters a bit easier, as the setup flags experience has been a point of feedback from several MSP adopters.
As a follow-up, we can probably remove the flag-based setup entirely, as it should generally be a human-operator-only setup. Then we can expand the setup to include e.g. resource setup (postgres), and maybe an initial generate step as well.
> sg msp: add interactive version of 'sg msp init' and 'sg msp init-env'

- .github/workflows/pg-utils.yml
- dev/nix/pg-utils.nix
- flake.nix
Lets get rid of PG_UTILS_PATH! :allthethings: :tada: 
CI and a _lot_ of  `nix build .#pg-utils && ldd ./result/bin/pg_dump`
also tested e2e with the following diff: https://github.com/sourcegraph/sourcegraph/commit/61e0eb0d556dbfbcdae7a0c2cac1f5dd5cb85553
> nix: build pg-utils with nix & upload to GCS

- cmd/cody-gateway/internal/httpapi/completions/anthropic.go
- cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
- cmd/cody-gateway/internal/httpapi/completions/fireworks.go
- cmd/cody-gateway/internal/httpapi/completions/openai.go
- cmd/cody-gateway/internal/httpapi/completions/upstream.go
[Slack Thread
](https://sourcegraph.slack.com/archives/C05AGQYD528/p1712071741350299)
I am doing this so as to compute the average offset in the computed tokens with the usage report from messages api for how many tokens were used. 
The Bigquery query we can use to interpret this 
```
SELECT 
name,
JSON_EXTRACT(metadata, '$.model') AS model_name,
JSON_EXTRACT(metadata, '$.completion_token_count') AS token_count,
JSON_EXTRACT(metadata, '$.completion_character_count') AS character_count,
-- Add more JSON_EXTRACT lines here for other fields you're interested in
FROM 
telligentsourcegraph.cody_gateway.events
LIMIT 50;
```
Interpretting and computing this data for a few days can tell use the average offset which can help us understand if we can use the old tokenizer for abuse detection or do I …
> Adding an extra field for the tokenizer computed tokens for Anthropic API 

- cmd/symbols/parser/parser.go
We can remove it since it is only ever created and then closed, never read or written to. It seems like at some point we moved to using parseRequestOrErrors and didn't remove parseRequests.
> symbols: remove unused channel parseRequests

- cmd/symbols/internal/api/handler.go
- cmd/symbols/internal/api/handler_test.go
- cmd/symbols/shared/main.go
- cmd/symbols/shared/setup.go
- cmd/symbols/shared/sqlite.go
This PR removes the unused `ctagsBinary` field from symbols server and its
set-up commands. The binary that's actually used is loaded through a separate
codepath.
Covered by current tests. Tested manually with both symbols and rockskip.
> Symbols: Remove unused ctags config

- internal/search/codycontext/query_transformer_test.go
- internal/search/codycontext/stop_words.go
While digging into why we perform poorly on "Ownership" and "Changelog"
searches, I noticed we were removing key terms in these queries. This PR adapts
the stopwords list to avoid removing them.
This doesn't immediately fix the problem, as we still don't match on filenames
(like CODEOWNERS or CHANGELOG.md). But it's a step towards the solution.
Adapted unit test.
> Context: remove key words from stopwords

- internal/observation/context.go
We currently use a NoOpRegisterer which means we don't do any validation on the metrics passed in, leading to us not catching things like duplicate registration of metrics/etc. So we update the registerer to be one which does a few more tests on metrics designed to be used in test contexts.
Note we do not update TestContext since that may be used multiple times in the same process to test the same metrics registration paths. To be honest, we should remove TestContext and update all call sites to use TestContextTB.
Test Plan: CI. Only affects tests this change.
> observation: use pedantic prometheus registry for TestContextTB

- internal/codycontext/BUILD.bazel
- internal/codycontext/context.go
- internal/codycontext/context_test.go
- internal/search/codycontext/query_transformer.go
- internal/search/codycontext/query_transformer_test.go
Currently, Cody keyword context only matches on file contents. For many queries
it's critical to match the filename too. The reason we only matched contents is
purely historical -- I just chose the simplest implementation at first.
Examples of when this is important:
* "who owns third party licenses?" should match `third-party-licenses/CODEOWNERS`
* "grafana version deps.bzl" should clearly match `deps.bzl`
This PR extends the searches to match filename too. It doesn't immediately
improve results for most Ownership or Changelog queries, because Zoekt does not
count filename matches towards a result's score. I'll fix this in follow-up work. 
Adapted unit tests. Manually tested using local Cody Web using these queries:
* "tell me about admin/repo/perforce.md"
* "who owns third party …
> Context: match on filename

- schema/validation_test.go
Noticed this test failing once locally and worked out the source of the flakiness. Could reproduce with the below test plan.
Test Plan: "go test -race -count=100 ./schema" passes
> schema: remove non-determinism from TestSchemaValidationUUID

- client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
- client/web-sveltekit/src/routes/search/PreviewPanel.svelte
Fixes #61611 
In the file view it looked like text selection doesn't work. However, I did work but the decoration wasn't visible. That's because the text selection decoration is rendered "underneath" the content, but the content element has been given a background color, so the text selection decoration wasn't visible.
The fix is to set the background color on the container that renders the editor instead.
> svelte: Fix file view text selection issue

- client/web/src/repo/blob/codemirror/blame-decorations.tsx
#61661 changed how "blame recency" is calculated in the client. In a last minute change I flipped the meaning of the boolean parameter but forgot to update the callsite. That's why the colors are currently the opposite (most recent = gray, least recent = purpel).
Trivial change.
> web: Fix blame recency color "direction"

- client/web/src/enterprise/rbac/components/Permissions.story.tsx
- client/web/src/enterprise/rbac/components/Permissions.tsx
#60795 introduced the concept of permissions that only exists on `Dotcom`, however one thing we didn't take into consideration is how the frontend displays the role.
Turns out we get `allPermissions` from the generated `graphql-operations.ts` file which is statically generated at build time and doesn't know about permissions that only exist on `dotcom`. 
Manual testing?
Added a storybook also.
> rbac: check for undefined permissions in PermissionsList

- dev/nix/pg-utils.nix
- flake.nix
Turns out we can do this after all! And thankfully so, because our buildkite runners have an older glibc version than what Nix was building our bins against which was resulting in `dropdb: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32' not found (required by dropdb)` when bazel was running in buildkite
Much local `nix build`'ing, `ldd` and `patchelf`'ing
> nix: build pg-utils with nix [static edition]

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
Currently the "last commit" display in the bottom right shows the last commit of the parent folder, not of the file/folder itself.
This became apparent when opening the history. The top entry didn't match what was shown in the bottom right.
- Repo home page -> last commit
- Directory/file page -> last commit that changes the file
> svelte: Show correct last commit information

- cmd/symbols/parser/BUILD.bazel
- cmd/symbols/parser/observability.go
- cmd/symbols/parser/observability_test.go
- cmd/symbols/parser/parser.go
We are seeing lots of log spam related to cancelation of parse requests. We haven't fully tracked this down yet, but the behaviour of spamming logs in this case hides the real issue.
This adjusts the implementation in two places:
- We introduce a parseCanceled metric so we can still track this. This is used instead of parseFailed in case of cancelation. In this case we also do not emit the "Closing failed parser" even though we are. This is due to log spam.
- We introduce an ErrorFilter just for handleParseRequest that will elide Canceled from the logs. This is called per file. Note: we keep the error logging for canceled in the high level Parse handler which runs across all files.
Test Plan: go test. Unfortunetly that is as good as it gets for now, as I investigate the root cause further …
> symbols: canceling ParseRequest does not spam logs

- internal/search/job/jobutil/job.go
- internal/search/job/jobutil/job_test.go
- internal/search/job/jobutil/repo_pager_job.go
- internal/search/structural/BUILD.bazel
- internal/search/structural/structural.go
This is a refactor to use the repo pager for structural search. This will be useful to support
structural search in Search Jobs.
Test plan:
- manual testing: I compared result counts for a cross-repo structural search query of this PR vs main
> search: wrap structural search with repoPagerRob 

- internal/search/streaming/http/writer.go
This is a speculative change to reduce the chances of misuse of the streaming http event writer (SSE). We are seeing panics in attribution search since it is trying to write events once the request has finished.
From the stack traces it seems the http package safely handles calls to Write without panicing but does not do the same for Flush. This change also seems more correct.
Note: this does not address the root cause of the panics, but should make it far less likely to occur.
Part of #60439
> streaming: only call flush if writes succeeded

- .aspect/workflows/config.yaml
Gazelle and buildifier have been timing out lately where the bazel invocation is just hanging. 
We change the timeout of the gazelle and buildifier jobs so that the jobs get killed MUCH sooner than just waiting for hours on end.
CI
> ci: set timeouts - gazelle 5 min and buildifier to 2 min

- client/web/src/featureFlags/featureFlags.ts
- client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
- client/web/src/site-admin/backend.ts
- client/web/src/site-admin/components/RepoMirrorInfo.tsx
- cmd/frontend/graphqlbackend/repository_mirror.go
- cmd/frontend/graphqlbackend/repository_mirror_test.go
- cmd/gitserver/internal/BUILD.bazel
- cmd/gitserver/internal/server.go
- cmd/gitserver/internal/server_test.go
- internal/database/dbmocks/mocks_temp.go
- internal/database/gitserver_repos.go
- internal/database/gitserver_repos_test.go
- internal/types/types.go
This was an experiment from a while ago about storing the clone progress in the DB instead of making a request to gitserver to retrieve it. This has never been activated and is thus dead code, so removing it. With the switch to a dbworker we get better logging for free anyways.
Removed dead code, tests should cover any regressions.
> Remove clone progress DB experiment

- cmd/gitserver/internal/git/gitcli/archivereader.go
We already do that for the actual archive operation, but not here. To avoid accidentally generating more output than expected, wrapping the paths here with `:(literal)` as well.
Existing tests still pass.
> gitserver: Match paths in ArchiveReader validation literally

- client/web-sveltekit/src/app.prod.html
Closes #61637 
It appears that we are relying on the browser's default behavior for loading the favicon. Removing this (broken in production) link makes the favicon work.
Loading the SvelteKit app locally from the full devserver (`sg start enterprise-sveltekit`) shows the dev favicon (it didn't before).
> svelte: Show favicon in production

- cmd/gitserver/internal/cleanup.go
- cmd/gitserver/internal/cleanup_test.go
- cmd/gitserver/shared/shared.go
This PR simplifies the janitor so that it doesn't have to run clones out of band.
As a side-effect, this will prevent us to go over the configured concurrency for janitorial reasons. There are still a few other reasons but those will get eliminated later.
We used to reclone repos every 45 days, regardless of state. This is from the old dotcom, gitserver-is-only-a-cache days. In todays logic, this doesn't make a ton of sense since on most instances, all repos are expected to always be in a servable state.
Why don't we need this?
Many of the repos we keep don't actually need GC at all, so recloning is actually much more expensive for those. Especially for customers with many repos (and dotcom), it is expected that the majority of repos will get little to no changes.
In addition, we want to …
> gitserver: Don't reclone repos every 45 days

- WORKSPACE
- cmd/server/macro.bzl
Potentially causing excessive remote cache issues 
:clueless:
> Revert "bazel: bump rules_{oci,pkg}"

- client/web-sveltekit/src/routes/search/RepoRev.svelte
- client/web-sveltekit/src/routes/search/SearchResult.svelte
[Context](https://sourcegraph.slack.com/archives/C05MHAP318B/p1712667167930699)
When viewing the search result page for files, the icon and path aren't properly aligned. This fixes that.
| Before  |
|---|
| ![CleanShot 2024-04-09 at 14 08 26@2x](https://github.com/sourcegraph/sourcegraph/assets/25608335/b37f45b3-88bb-4880-b825-6f3ebc74ab60)  |
| After  |
| ![CleanShot 2024-04-09 at 14 08 16@2x](https://github.com/sourcegraph/sourcegraph/assets/25608335/97caf7a6-de0d-4bc3-b6a0-adcc072f4c61)  |
Manual testing
> code-search: fix vertical alignment in search results list

- cmd/symbols/parser/parser.go
Understanding how Parse works (and its callers) with respect to goroutines and channels is a sure path to the asylum. This is a short term fix around how it behaves when the context is canceled.
From what I can tell we can have a large number of parse requests go through handleParseRequest even once the context has been canceled, leading to large amounts of logging of errors which all amount to context canceled. This is a short term fix which drains the channel if we know we are just gonna fail our call to handleParseRequest.
Test Plan: go test. Didn't manual test, but the code change is minor enough that I trust it (famous last words).
> symbols: avoid spamming handleParseRequest on context cancelation

- internal/completions/client/azureopenai/openai.go
- internal/completions/client/openai/openai.go
- internal/completions/tokenizer/BUILD.bazel
- internal/completions/tokenizer/claude.go
- internal/completions/tokenizer/tokenizer.go
- internal/completions/tokenusage/BUILD.bazel
- internal/completions/tokenusage/tokenusage.go
- internal/completions/tokenusage/tokenusage_test.go
As I was testing the tokenization of different models and figuring out what to keep/remove in the current tokenization logic for Anthropic and OpenAI models I found out a couple of things
1. We can't remove the current anthropic token counting logic because the abuse detection logic depends on it([Slack Thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1712071741350299))
2. The current tokenization for abuse detection doesn't support anthropic claude 3 family of models because of the results of my token testing examples 
```
tikatest python tokentest.py         
File: activate.csh, Model: claude-instant-1.2, Usage: Usage(input_tokens=331, output_tokens=255)
File: activate.csh, Model: claude-3-haiku-20240307, Usage: Usage(input_tokens=364, output_tokens=406)
Usage difference for …
```
> Improving tokenization for OpenAI models and stop claude 3 tokenization

- .buildkite/pipeline.backcompat.yml
- dev/ci/internal/ci/config.go
There are  two problems here
Due to the 100 commit depth we have on aspect agents the `origin/main` branch or commit it points to might not exist. This is important because of the proximity of the 5.3.9104 branch and where a commit is that is being built. The repo is in a detached state so we might not have information locally on the commit that `origin/main` is at.
This is a backport. Why are we diffing against `origin/main` ? We should diff against the base branch which is 5.3.9104
1. Determine the base branch
2. Fetch the that boi
3. Diff
4. PROFIT
>[!NOTE]
> I will cherry-pick this onto main as well
CI
> backport: fix gen pipeline

- dev/ci/internal/ci/config.go
Sooooooooooooo. Backport builds are still failing see https://buildkite.com/sourcegraph/sourcegraph/builds/268392
The base branch is empty when it's a merge into a branch - when a PR for a backport gets merged into the backport branch ... In that case - what we actually want to do:
1. Diff with the previous commit on _this_ branch
2. NOT DIFF WITH origin/main ... right?
CI and attempting a merge into _this_ branch
> pipeline: more pipeline config fixes

- dev/sg/sg_rfc.go
Reverts sourcegraph/sourcegraph#61529
I managed to miss an edge case during the QA.
Test plan: CI
> Revert "chore(sg): rfc flags are now position independent"

- .aspect/bazelrc/ci.sourcegraph.bazelrc
Likely needed as part of https://github.com/sourcegraph/sourcegraph/issues/61246, but if not, it can always be used to determine why something was a cache miss 
Saw new artifact in CI
> test execution log artifact

- .aspect/bazelrc/ci.sourcegraph.bazelrc
Causing excessive log spam :disappointed: 
https://github.com/bazelbuild/bazel/issues/21820
CI
> ci: disable emitting execution log for bazel

- client/web-sveltekit/src/lib/search/constants.ts
- client/web-sveltekit/src/lib/search/dynamicFilters/index.ts
- client/web-sveltekit/src/lib/search/state.ts
- client/web-sveltekit/src/routes/search/+page.ts
While looking into https://github.com/sourcegraph/sourcegraph/issues/61636 I thought we might need to support more than two caching policies, which let me to rewrite how handle this URL parameter.
It turned out that the root cause for the linked issue is something different but I still think that the changed code introduces a nice layer of abstraction.
Manual testing. Selecting a search filter again reuses the cached result.
> svelte: Refactor search cache URL parameter processing

- doc/dev/how-to/add_support_for_a_language.md
Fixes ENG-23454
Updates the syntax highlighting docs to describes the steps based on tree-sitter grammars which is our preferred method.
None needed, just docs
> Update docs for adding syntax highlighting

- dev/ci/images/images.go
- dev/ci/internal/ci/images_operations.go
- dev/ci/push_all.sh
part of https://github.com/sourcegraph/sourcegraph/issues/61696
I don't think there's a way to test pushing to the new registry without rewriting the part to decide when to push images to prod registry, especially `docker-images-candidates-notest` is no longer supported.
https://sourcegraph.slack.com/archives/C04MYFW01NV/p1712789750549639
local testing of the added portion of the `push_all.sh` by `echo "${prod_registries[*]}"`, it works locally.
```
export DEV_REGISTRY="us.gcr.io/sourcegraph-dev"
export PROD_REGISTRY="index.docker.io/sourcegraph"
index.docker.io/sourcegraph
```
```
export DEV_REGISTRY="us.gcr.io/sourcegraph-dev"
export PROD_REGISTRY="index.docker.io/sourcegraph"
export ADDITIONAL_PROD_REGISTRY="us-docker.pkg.dev/sourcegraph-public-images/sourcegraph-public-images" …
```
> ci: publish release images to public artifact registry

- dev/ci/images/images.go
- dev/ci/internal/ci/images_operations.go
- dev/ci/push_all.sh
Reverts sourcegraph/sourcegraph#61764
https://buildkite.com/sourcegraph/sourcegraph/builds/268490#018ecdb6-8925-4a25-a070-0c1f6f05f1a2/401-483
needs to fix builder machine image to configure credhelper for new `us-docker.pkg.dev` registry
fix requires https://github.com/sourcegraph/infra-aspect-dev/pull/119, but let's revert for now to unblock main
CI
> Revert "ci: publish release images to public artifact registry"

- WORKSPACE
- dev/bazel_stamp_vars.sh
- dev/oci_deps.bzl
- docker-images/dind/BUILD.bazel
- docker-images/dind/Dockerfile
- docker-images/dind/build.sh
Google Container Registry doesn't like this image for some reason, so we're gonna hold out until we're moved to Artifact Registry
reverting
> Revert "bazel: migrate dind dockerfile to rules_oci"

- cmd/frontend/internal/rbac/resolvers/resolver.go
- internal/database/security_event_logs.go
RBAC changes can be sensitive and can have a big impact. This adds event logging for changes to RBAC.
CI tests.
> sec: emit security event for RBAC changes

- cmd/gitserver/internal/server.go
- cmd/gitserver/internal/server_test.go
- cmd/gitserver/shared/shared.go
After the PRs this is stacked on top of, the only option we passed to CloneRepo was Block: true. 
This means that the in-memory queue was no longer used and could be removed.
This makes for a single code path to clone a repo, and a single caller on the gRPC side as well, so nice and simple.
This'll help make improvements to the scheduler simpler without having to think about 10 different call paths.
Just removed dead code, E2E tests still pass.
> gitserver: Simplify clone

- dev/sg/dependencies/mac.go
https://github.com/sourcegraph/sourcegraph/pull/48807 changed `sg setup` to install postgres 12 instead of 15. Now that https://github.com/sourcegraph/sourcegraph/pull/61741 is merged, we must be running postgres 12 locally so that pg_dump will function correctly
@burmudar tested `brew install postgresql@12`
> sg: install postgres 12 instead of 15

- cmd/gitserver/internal/gitservice.go
- cmd/gitserver/internal/integration_tests/clone_test.go
- cmd/gitserver/internal/integration_tests/resolverevisions_test.go
- cmd/gitserver/internal/integration_tests/test_utils.go
- cmd/gitserver/internal/server.go
- cmd/gitserver/shared/shared.go
gitserver: Move gitservice off of server struct
To simplify the server struct, the gitservice HTTP handler for upload pack requests is now standalone.
CI still passes after moving around the code.
> gitserver: Move gitservice off of server struct

- cmd/frontend/backend/repos.go
- cmd/frontend/graphqlbackend/git_commit.go
- cmd/frontend/graphqlbackend/git_commits.go
- cmd/frontend/graphqlbackend/git_revision.go
- cmd/frontend/graphqlbackend/repository.go
- cmd/frontend/graphqlbackend/repository_comparison.go
- cmd/frontend/graphqlbackend/repository_text_search_index.go
- cmd/frontend/internal/httpapi/search.go
- cmd/gitserver/internal/integration_tests/resolverevisions_test.go
- internal/batches/service/workspace_resolver.go
- internal/batches/state/state.go
- internal/codeintel/autoindexing/internal/enqueuer/enqueuer.go
- internal/codeintel/shared/resolvers/gitresolvers/cached_resolvers.go
- internal/codeintel/uploads/internal/background/janitor/job_cleanup.go
- internal/codeintel/uploads/internal/background/processor/job_worker_handler.go
- internal/codemonitors/search.go
- internal/gitserver/commands.go
- internal/own/background/analytics.go
- internal/search/repos/repos.go
- internal/search/searcher/search.go
- internal/search/searcher/symbol_search_job.go
gitserver: Remove double negation for ensure revision
I _ALWAYS_ stumble over this double negation. "If not noensurerevision". huh?
Also, we should not encourage people to accidentally make the server do a resolve revision call which is generally costly, so the cheap option as the default seems more desirable.
For now, I haven't changed any of the values, but we should also do another review of the cases where we explicitly set it to true.
Just converted a bool, CI and E2E tests should catch any issues.
> gitserver: Remove double negation for ensure revision

- internal/codeintel/codenav/request_state.go
- internal/codeintel/uploads/internal/background/expirer/mocks_test.go
- internal/codeintel/uploads/internal/background/processor/job_worker_handler_test.go
- internal/codeintel/uploads/internal/background/processor/mocks_test.go
- internal/codeintel/uploads/internal/background/processor/scip.go
- internal/codeintel/uploads/internal/lsifstore/insert.go
- internal/codeintel/uploads/internal/lsifstore/insert_test.go
- internal/codeintel/uploads/internal/lsifstore/observability.go
- internal/codeintel/uploads/internal/lsifstore/store.go
- internal/codeintel/uploads/internal/store/commitgraph.go
- internal/codeintel/uploads/internal/store/commitgraph_test.go
- internal/codeintel/uploads/mocks_test.go
- internal/codeintel/uploads/shared/indexers2.go
Fixes https://github.com/sourcegraph/sourcegraph/issues/61422
When uploading syntacic indices we want to treat them as regular updates as much as possible to be able to reuse the logic in commitgraph.
The two important differences from precise uploads are:
- We don't write symbols for syntactic indices
- We don't return syntactic indexes from the annotated commit graph unless we're explictly requesting them
Added unit tests for index retrieval
> Ingesting syntactic indexes via upload

- sg.config.yaml
This is needed to actually see captured traces in Jaeger, so it's
not useful to have it be disabled by default.
n/a
> sg: Enable otel-collector in enterprise-codeintel preset

- client/web/src/enterprise/site-admin/dotcom/productSubscriptions/ModelBadges.tsx
- cmd/cody-gateway/shared/config/config.go
- cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
- internal/completions/client/fireworks/fireworks.go
- internal/completions/httpapi/chat.go
The base model wasn't useful for chat but now that Fireworks released the first IT version, let's use that instead :) 
https://twitter.com/FireworksAI_HQ/status/1778617118583586852
Trivial change, CI will test (and we will test on cody gatewat dev)
```
curl 'https://sourcegraph.test:3443/.api/completions/stream' -i \
-X POST \
-H 'authorization: token' \
--data-raw '{"messages":[{"speaker":"human","text":"What is your name?"}],"maxTokensToSample":30,"temperature":0,"stopSequences":[],"timeoutMs":5000,"stream":true,"model":"fireworks/accounts/fireworks/models/mixtral-8x22b-instruct-preview"}'
HTTP/2 200
access-control-allow-credentials: true
access-control-allow-origin:
alt-svc: h3=":3443"; ma=2592000
cache-control: no-cache
content-type: text/event-stream
date: Fri, 12 Apr 2024 09:06:15 …
```
> Replace Mixtral 8x22 with 8x22-instruct-preview

- client/web/src/cody/subscription/CodySubscriptionPage.module.scss
- client/web/src/cody/subscription/CodySubscriptionPage.tsx
- Reverts #61469 because we decided to not merge https://github.com/sourcegraph/self-serve-cody/pull/696 and close https://github.com/sourcegraph/self-serve-cody/issues/506 as a wontfix.
(I kept the other improvements that were in my PR.)
Note: enabled auto-merge.
Just a revert of a commit. No linter errors reassure me that it's good.
> Revert adding "no subscription" message

- dev/ci/push_all.sh
Previously we would pass >=1 values for the `--repository` flag to `oci_push` targets when pushing images. This isn't actually supported[[1]](https://sourcegraph.com/github.com/bazel-contrib/rules_oci@bde8b2e31977a7d74523e152509a80c9945cbeea/-/blob/oci/private/push.sh.tpl)[[2]](https://github.com/bazel-contrib/rules_oci/issues/248), resulting in all but the last value passed in a single `bazel run <oci_push target>` being ignored. This manifested in us not pushing some images to index.docker.io when a command looked like `bazel run //cmd/<target>:candidate_push --tag insiders --repository index.docker.io/sourcegraph/<target> --repository us-docker.pkg.dev/sourcegraph-public-images/<target>`
CI on main
> ci: separate combined --repository flags into individual commands in push_all.sh

- doc/admin/observability/alerts.md
- doc/admin/observability/dashboards.md
- monitoring/definitions/shared/go.go
- monitoring/definitions/zoekt.go
Noticed this omission when I was wondering if we had goroutine leaks. Our other services define this.
I added a simple way to indicate the container name in title since this is the first service we added which needs this.
Test Plan: go test. Copy paste generated query into grafana explore on dotcom.
> monitoring: add golang monitoring for zoekt

- monitoring/definitions/zoekt.go
The index_num_assigned metric no longer exists. This should fix a few all the graphs that you are able to select which indexserver to look at.
Test Plan: tested this metric had the requisite fields via dotcom's explore. Tried to test with local grafana setup but it seems to have regressed so will follow-up on that.
> monitoring: fix "instance" dropdown for Zoekt

- internal/batches/sources/sources.go
This seems to have meant to use && instead of || - in the current form this can panic if src is nil.
Test plan:
Code review, trivial change.
> Fix nil dereference from wrong bool operator

- internal/codycontext/context.go
While writing eval scripts for Cody context, I noticed that when searching
multiple repos, we sometimes we return greater than the intended number of
results. This PR makes a small fix so we always respect the result limits.
This is hard to check through automated tests since it requires a certain set
of concurrent steps to occur. I tested manually before and after the change and
this fixed it.
> Context: fix bug with result limits

- dev/ci/internal/ci/pipeline.go
- dev/ci/internal/ci/wolfi_operations.go
In https://github.com/sourcegraph/sourcegraph/pull/61845 we removed base images being build in CI - but only on PR pipelines. This also removes base image builds from the `main` pipeline as well.
Now that we're using bazel to build base images on the fly, there's no longer a need to build these base images in CI.
- CI
> Remove wolfi base image rebuilds on main

- internal/search/codycontext/job.go
- internal/search/job/jobutil/job_test.go
In #60106, we fixed a bug where the context search threw an error when the query
was composed entirely of stopwords. However, the queries were still returning
results (based on filename match). This means that for a stopwords-only query
like "what's going on?" we return a fairly random set of files, which confuses
the LLM.
Now we make sure to return an empty search, which returns no results.
Added a new unit test. Tested Cody web locally.
> Context: return no results for stopwords query

- WORKSPACE
- third_party/rules_apko/copy_dont_symlink_lockfile.patch
CI started failing with a bunch of the following for every apko target
```
...
(10:27:41) ERROR: /mnt/ephemeral/workdir/sourcegraph/sourcegraph/cmd/batcheshelper/BUILD.bazel:78:11: Action cmd/batcheshelper/wolfi_base_apko failed: missing input file '@@batcheshelper_apko_lock//:lockfile_copy'
(10:27:41) ERROR: /mnt/ephemeral/workdir/sourcegraph/sourcegraph/cmd/batcheshelper/BUILD.bazel:78:11: Action cmd/batcheshelper/wolfi_base_apko failed: 1 input file(s) do not exist
...
```
This line seemed suspect, so lets replace it with an actual full copy instead of :raised_eyebrow: symlink https://sourcegraph.com/github.com/chainguard-dev/rules_apko@1d78765293a0baf3f92ca49efa51d6c02b9c828e/-/blob/apko/translate_lock.bzl?L69
CI goes green again :sunglasses:
> bazel: patch rules_apko to copy, not symlink, lockfile

- dev/sg/internal/images/dockerhub.go
- dev/sg/internal/images/gcr.go
Docker image type has changed. Update the accepted types to fix the `sg ops update-images` command by including `application/vnd.oci.image.manifest.v1+json`
tested locally command ran successfully
> sg: add `application/vnd.oci.image.manifest.v1+json` to accepted image types for `ops update-images`

- internal/codeintel/uploads/internal/background/expirer/mocks_test.go
- internal/codeintel/uploads/internal/background/processor/mocks_test.go
- internal/codeintel/uploads/internal/background/processor/scip.go
- internal/codeintel/uploads/internal/lsifstore/BUILD.bazel
- internal/codeintel/uploads/internal/lsifstore/insert.go
- internal/codeintel/uploads/internal/lsifstore/observability.go
- internal/codeintel/uploads/internal/lsifstore/store.go
- internal/codeintel/uploads/mocks_test.go
Fixes https://github.com/sourcegraph/sourcegraph/issues/61822
Fixes ENG-23610
Mostly, this PR splits up the code involved in writing data to various tables into
smaller functions, each of which has its own span for traces. The patch respects
the changes made by Christoph for syntactic indexes.
With this patch, we can see more fine-grained information in Jaeger's statistics view
when traces are enabled.
Manually performed some uploads. Covered by existing tests.
> codeintel: Add fine-grained spans for uploads

- internal/uploadhandler/BUILD.bazel
- internal/uploadhandler/upload_handler_test.go
These aren't required anymore for the tests to pass, so we can remove them (and break a dependency from internal -> cmd).
Test plan:
Tests still pass.
> chore: Remove unnecessary mocks from uploadhandler tests

- dev/depgraph/main.go
This confused me:
```
terminal command () doesn't define an Exec function
```
Now it prints a help text.
Test plan:
Verified the above behavior by hand.
> depgraph: Fix spurious error when no subcommand name is passed

- internal/honey/non_sending.go
The documentation for fields already says that the returned map is not safe for concurrent modification.
However, I realized the variable assignment for the map should be protected by a lock too. This means that the Fields() call now needs to use a locking discipline as well.
N/A
> honey: add read locking to event.Fields call for NonSendingReader

- internal/highlight/highlight.go
While investigating a large number of errors in highlighting I noticed the vast majority where canceled. This commit adds special handling for it and in the process does a few other things to the observability here:
- Log duration in these errors. This is useful signal to understand if a slow request is being canceled, or we have bad debouncing in a client.
- Re-use the tracers logger. This has many more fields and avoids duplication.
- Downgrade cancel error to warning.
- Include error problem in logs.
- Factor out the snippet log field creation.
Note I didn't include snippet in the cancel log since it's unlikely to be related to the code being highlighted. Easy to add in if we find that is incorrect.
Test Plan: CI will exercise this code path. Otherwise I will follow-up on dotcom.
> highlight: share log attributes with trace and handle canceled

- WORKSPACE
- dev/oci_defs.bzl
Our rust binaries (e.g. scip-ctags/syntect_server) were being built in some mix of opt & fastbuild mode[1]. Unlike with Go where there is no release/debug mode flag, Rust requires opting into optimized release builds. We can do that automagically when building any oci_image target with the power of :sparkles: transitions :sparkles: 
This has the side-effect of our Go binaries no longer being stripped & containing debug symbols, see https://github.com/bazelbuild/rules_go/issues/3917
Also to note, [in Cargo.toml we opt into debug symbols in release mode](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@nsc/bazel-release-mode-rust/-/blob/docker-images/syntax-highlighter/Cargo.toml?L67%3A11-70%3A9). Is this preserved by this PR for bazel[2]? 
[1] `strings` on the binaries showed the …
> bazel: transition oci_image to opt/release mode for Rust

- internal/completions/client/anthropic/anthropic.go
- internal/completions/client/awsbedrock/bedrock.go
- internal/completions/client/azureopenai/openai.go
- internal/completions/client/openai/openai.go
- internal/completions/tokenusage/tokenusage.go
- internal/completions/tokenusage/tokenusage_test.go
This PR does two things
1. Fixes the Payload to be sent to Pings for llm_usage 
2. Fixes the token usage cache to use a more stable redis. 
3. Adds provider name to the redis cache key to make it easy to differentiate the keys 
- Run CI
> Fixing Redis usage and Payload Map structure for TokenUsage

- internal/batches/webhooks/BUILD.bazel
- internal/batches/webhooks/batch_change_test.go
- internal/batches/webhooks/changeset_test.go
Was just used for one marshal operation in testing, so this simplifies the dependency graph by not importing from cmd/frontend.
Test plan:
Tests still pass, code compiles.
> Break dependency of internal/batches/webhooks on cmd/frontend

- client/web/src/settings/SettingsArea.tsx
- client/web/src/settings/SettingsFile.tsx
- client/web/src/settings/SettingsPage.tsx
> v2t: add v2t to src/settings

- cmd/frontend/graphqlbackend/schema.graphql
Update GQL docs to explain the difference between two types of user activity statistics. This is a common source of confusion, and this appears to be the best place to document the difference. Open to suggestions for other spots.
Recent example: https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1711735853127489
CI
> Update GQL docs for user activity metrics

- cmd/telemetry-gateway/internal/events/events.go
- cmd/telemetry-gateway/internal/server/BUILD.bazel
- cmd/telemetry-gateway/internal/server/publish_events.go
- cmd/telemetry-gateway/internal/server/publish_events_test.go
- lib/errors/cockroach.go
We aggregate all errors on a single log entry to get accurate representations of issues in Sentry, while not generating thousands of log entries at the same time. Because this means we only get higher-level logger context, we must annotate the errors directly with some hidden details to preserve Sentry grouping while adding context for diagnostics.
We do this by using CockroachDB error's `WithSafeDetails` helper, which annotates an error with details that are _not_ rendered by `err.Error()` but _are_ included in Sentry reports (via the `Message` field). Currently, we annotate the event ID, feature, action, and source (see example output below)
Context on this request: https://sourcegraph.slack.com/archives/C06CCJR4K9R/p1713054354443579
_Super_ jank unit tests that try to emulate how we …
> telemetry-gateway: wrap publish errors in error details for Sentry

- dev/ci/images/images.go
This is required for `sg ops update-images` to update the image tag in the deploy-sourcegraph-docker repo.
- CI
- Confirmed that `sg ops update-images [...]` now includes caddy image
> Add caddy to DeploySourcegraphDockerImages

- cmd/frontend/graphqlbackend/BUILD.bazel
- cmd/frontend/graphqlbackend/org.go
- cmd/frontend/graphqlbackend/org_test.go
- cmd/frontend/graphqlbackend/schema.graphql
- cmd/frontend/graphqlbackend/site_flags.go
- internal/database/BUILD.bazel
- internal/database/dbmocks/mocks_temp.go
- internal/database/orgs.go
- internal/database/orgs_test.go
- internal/repos/gitlab.go
These checks for dotcom mode are no longer necessary, so let's remove the number of code paths.
Test plan:
Test suites are still passing, also code review.
> Remove unnecessary dotcom checks

- internal/batches/sources/BUILD.bazel
- internal/batches/sources/mocks_test.go
- internal/codeintel/codenav/gittree_translator.go
- internal/codeintel/codenav/gittree_translator_test.go
- internal/codeintel/codenav/service_ranges_test.go
- internal/codeintel/codenav/service_snapshot_test.go
- internal/gitserver/client.go
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
- internal/gitserver/mocks_temp.go
- internal/gitserver/observability.go
Diff already has an option for scoping to a specific path, so merging these two together, to simplify the API surface we need to create for the new gRPC APIs around diffs.
Adjusted a few tests, hoping that integration and E2E tests cover this. Also ran some git commands locally to check if they produce roughly equivalent output. Code reviews will help as well.
> Consolidate DiffPath and Diff methods

- client/web/src/auth/SignInPage.tsx
This PR makes the sign-in page always redirect if there is only a single sign-in provider, since there is nothing else to do on the sign in page otherwise.
Verified to work locally
> Redirect to sign-in provider when there is only one

- cmd/repo-updater/image_test.yaml
I just spotted that we never completed the follow-up of removing the `p4` test from repo-updater after we removed the `p4` binary in 5.3.
Context is [here](https://github.com/sourcegraph/sourcegraph/pull/60324) - we no longer required the p4 binary in this image, but due to some complexities around release branches we couldn't remove it until after the release. This is now long completed, so we should clean up the associated test that's been commented out.
- CI
> Remove p4 test from repo-updater image

- cmd/frontend/internal/bg/update_permissions.go
- internal/rbac/schema.yaml
- internal/rbac/types.go
Before this PR, RBAC permissions were automatically added to the User role and devs would have to explicitly declare permission namespaces that shouldn't be added to the user role.
This PR flips this logic by ensuring devs would explicitly have to specify permissions to be added to the User namespace.
[Context](https://app.incident.io/sourcegraph/incidents/292?source=slack_bookmark)
- Add unit test
> rbac: make user permissions additive

- cmd/frontend/graphqlbackend/repository_contributors.go
- internal/gitserver/commands.go
This uses our internal package to parse dates, instead of passing the date onto git directly. This makes for a cleaner API and the same date parsing across the product.
Test plan:
Tested the contributor count page by hand.
> Use time.Time in ContributorCount Git API

- cmd/frontend/internal/bg/store_token_usage_in_postgres.go
- internal/search/job/jobutil/log_job.go
- internal/telemetry/CODEOWNERS
- internal/telemetry/events.go
- internal/telemetry/telemetry.go
- internal/telemetrygateway/CODEOWNERS
- internal/updatecheck/client.go
I noticed the `telemetry.constString` type was wrongly exported in a previous PR (https://github.com/sourcegraph/sourcegraph/pull/61134). This type is intentionally unexported to prevent the exact use case the PR used the exported type for - this scenario (list keys and include it in metadata) is exactly the scenario where something bad might unexpectedly show up in our telemetry (an unexpected Redis key is matched, an unexpected value is provided to be stored, etc - the cause of multiple data leakage incidents in the past)
However, given the format I was unable to quickly come up with a better alternative. Moving it to private metadata is also not possible, as because judging from the description of #61134 we need this to be exported from on-prem as a business need.
For now:
1. Add loud …
> telemetry: unexport internal type, add SafeMetadataKey

- cmd/frontend/internal/telemetry/resolvers/telemetrygateway.go
- cmd/telemetry-gateway/internal/events/events.go
- cmd/telemetry-gateway/internal/events/events_test.go
- cmd/telemetry-gateway/internal/server/publish_events.go
- cmd/telemetry-gateway/internal/server/publish_events_test.go
- internal/telemetry/BUILD.bazel
- internal/telemetry/besteffort.go
- internal/telemetry/telemetry.go
1. Distinguish between retryable/nonretryable errors in Telemetry Gateway, and only report retryable errors to Sourcegraph instances after logging them. This prevents instances from endlessly retrying events that will never be accepted
2. Add callsite validation of feature/action in graphqlbackend and the backend telemetry recorder - we are seeing lots of events without these required fields
Thread: https://sourcegraph.slack.com/archives/C06CCJR4K9R/p1713249734994549?thread_ts=1713054354.443579&cid=C06CCJR4K9R
CI
> telemetry-gateway: distinguish between retryable/nonretryable errors, telemetry: add callsite validation of feature/action

- cmd/worker/internal/telemetrygatewayexporter/exporter.go
- doc/dev/how-to/telemetry_gateway.md
- sg.config.yaml
We have a continuous-deployed dev deployment of Telemetry Gateway available but it receives practically no traffic, partly because a) it only accepts dev-signed-licenses and b) nothing uses it by default.
This change makes it so that local dev (`sg start`, `sg start dotcom`, etc) exports events to this live dev instance by default, allowing us to more effectively dogfood changes before rolling them out to prod. Prod stability is especially important as we move towards a V2-telemetry-only world.
Docs have been updated to describe this, and showcase how to run and use local Telemetry Gateway as before.
Thread: https://sourcegraph.slack.com/archives/C05BGNBEPKL/p1713222710245669
Locally, `sg start`:
In dev logs:
> telemetry-gateway: use live dev instance locally by default

- internal/service/svcmain/svcmain.go
Since we switched away from single binary, we always pass down a single service. So we can simplify this logic a little bit.
Test plan:
sg start still works and the E2E / integration test suites are still passing.
> svcmain: Simplify service setup

- client/web/src/LegacyRouteContext.tsx
- client/web/src/LegacySourcegraphWebApp.tsx
- client/web/src/SourcegraphWebApp.tsx
- client/web/src/storm/pages/SearchPage/AddCodeHostWidget.tsx
- client/web/src/storm/pages/SearchPage/CodeSearchSimpleSearch.tsx
- client/web/src/storm/pages/SearchPage/SearchPage.tsx
- client/web/src/storm/pages/SearchPage/SearchPageContent.tsx
- client/web/src/storm/pages/SearchPage/SearchPageFooter.tsx
- client/web/src/storm/pages/SearchPage/SearchPageInput.tsx
- client/web/src/storm/pages/SearchPage/SimpleSearch.tsx
> v2t: add v2t to src/storm

- doc/_resources/templates/root.html
- doc/dev/background-information/architecture/index.md
- doc/dev/background-information/architecture/row_level_security.md
- doc/dev/background-information/bazel/containers.md
- doc/dev/background-information/bazel/faq.md
- doc/dev/background-information/bazel/index.md
- doc/dev/background-information/bazel/rust.md
- doc/dev/background-information/grpc_tutorial.md
- doc/dev/background-information/scim_api.md
- doc/dev/background-information/sg/index.md
- doc/dev/background-information/sql/index.md
- doc/dev/background-information/sql/upgrades_and_migrator_design.md
- doc/dev/how-to/add_permissions.md
- doc/dev/how-to/add_support_for_a_language.md
- doc/dev/how-to/cody_gateway.md
- doc/dev/how-to/debug_permissions.md
- doc/dev/how-to/index.md
- doc/dev/how-to/telemetry_gateway.md
- doc/dev/how-to/wolfi/add_update_images.md
- doc/dev/how-to/wolfi/add_update_packages.md
- doc/dev/index.md
- doc/dev/security/secret_formats.md
- doc/dev/setup/quickstart.md
This PR fixes a few issues with the legacy docs that are currently served on docs.sourcegraph.com: 
- When serving pages from the dev docs, a banner (orange) indicates when it was last refreshed and how to find up to date content.
- Because the banner sent users straight to the docsite v2, which doesn't have the dev docs anymore, this was creating broken links
- When serving pages from the normal docs, the banner is the same as before, but we force the link to the docs v2 root if and only if serving the resource estimator page.
- This is to avoid serving a broken link, as the resource estimator doesn't have yet an equivalent on the dev docs. 
- See https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1713333693488469
- A fresh copy of the latest dev docs, so at least the content is up to …
> Fix legacy docs

- CHANGELOG.md
- client/web/src/repo/blob/codemirror/codeintel/pin.ts
- client/web/src/repo/blob/codemirror/codeintel/token-selection.ts
Fixes #61964 
When upgrading and migrating rxjs methods, this way of "racing" the loading popover was incorrectly implemented. The condition needs to be reversed so that the observable completes once the non-loading tooltip was emitted.
Manual testing. Use token navigation to go to a token and press space. The expected popover appears.
> file view: Fix code intel popovers, pinned and token navigation

- cmd/gitserver/internal/git/gitcli/archivereader.go
- cmd/gitserver/internal/git/gitcli/archivereader_test.go
Removes path verification for ArchiveReader calls since there are edge cases that we're not handling correctly.
Manual tests that `src batch preview` works now.
> Remove path verification for archive reader

- client/web/src/auth/SignInPage.tsx
(cherry picked from commit 5653a5f75e0a3012df1cddf4f22d4240b7171693)
> [backport] Redirect to sign-in provider when there is only one (#61919)

- deps.bzl
- go.mod
- go.sum
- https://github.com/sourcegraph/zoekt/commit/ab1b8f0919 Tests: disable global git configs
- https://github.com/sourcegraph/zoekt/commit/59ab9491e1 Ranking: tidy up scoring code
- https://github.com/sourcegraph/zoekt/commit/43b92256ba Ranking: include filename matches in bm25
> gomod: bump Zoekt for BM25 score fix

- dev/ci/gitops/BUILD.bazel
- dev/ci/gitops/git_ops.go
- dev/ci/internal/ci/BUILD.bazel
- dev/ci/internal/ci/config.go
I needed the code that determines the latestTag for use in a branchTag in `sg` and it felt like a waste to just reimplement it elsewhere.
So I moved the git operations that the config was doing to its own package that can be imported from somewhere else.
CI
> ci: move git operations from ci config to it's own package

- dev/ci/internal/ci/release_operations.go
- tools/release/promote_images.sh
Part of https://github.com/sourcegraph/sourcegraph/issues/61696 
Basically, while we obviously do not push on the new GAR public registry when creating an internal release, we still need to also push the images there (next to the classic public registry) when promoting a release. 
CI
> chore(rel): also push promoted images on GAR

- client/web/src/auth/SignInPage.tsx
Reverts sourcegraph/sourcegraph#61927 due to https://sourcegraph.slack.com/archives/C02E4HE42BX/p1713367559532589?thread_ts=1713361578.175539&cid=C02E4HE42BX
> Revert "[backport] Redirect to sign-in provider when there is only one (#61919)"

- cmd/gitserver/internal/git/gitcli/BUILD.bazel
- cmd/gitserver/internal/git/gitcli/archivereader.go
- cmd/gitserver/internal/git/gitcli/archivereader_test.go
- cmd/gitserver/internal/git/iface.go
- cmd/gitserver/internal/server_grpc.go
- cmd/gitserver/internal/server_grpc_test.go
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
- internal/gitserver/v1/gitserver.proto
This didn't add a ton of benefits as the response will just be an empty archive and no error, but broke some callers of this, so we decided to remove it entirely.
Test plan:
Existing tests pass, adjusted tests to no longer account for the not found case.
> gitserver: Completely remove Archive path validation

- cmd/embeddings/shared/main.go
- cmd/precise-code-intel-worker/shared/shared.go
- cmd/repo-updater/shared/main.go
- cmd/worker/internal/permissions/perms_syncer_scheduler.go
- cmd/worker/shared/main.go
- internal/authz/providers/BUILD.bazel
- internal/authz/providers/authz.go
- internal/authz/providers/authz_test.go
This makes the dependency on conf clearer so that you understand that you must have a working connection to confserver when you're calling this function in the package.
Test plan:
Existing test suites
> Pass conf down to authz providers

- cmd/repo-updater/shared/BUILD.bazel
- cmd/repo-updater/shared/main.go
The default.NewServer registers reflection etc, we should use that instead.
Test plan:
Ran locally, still works.
> repoupdater: simplify gRPC server setup

- cmd/repo-updater/shared/main.go
This wasn't actually tracking what we think it would, and it was not used in any dashboard. Let's remove it.
Test plan:
Unused, code review.
> repoupdater: Remove incorrect and unused metric

- cmd/syntactic-code-intel-worker/shared/BUILD.bazel
- cmd/syntactic-code-intel-worker/shared/shared.go
- internal/codeintel/syntactic_indexing/jobstore/BUILD.bazel
- internal/codeintel/syntactic_indexing/jobstore/store.go
Found that we call SetProviders in an internal package, if someone decides to call NewStore from another binary we'll unset authz providers which can disable certain auth checks, so that felt a bit risky.
Test plan:
Just moved a bit of code around.
> Move authz.SetProviders call to cmd/ package

- client/web/src/auth/SignInPage.tsx
This PR makes the sign-in page always redirect if there is only a single sign-in provider, since there is nothing else to do on the sign in page otherwise.
Verified to work locally
Backport 5653a5f from #61919
> [Backport 5.3.9104] Redirect to sign-in provider when there is only one

- internal/gitserver/commands.go
Missed the case where rangeType is .. here.
Test plan:
No more failures from stencil query.
> gitserver: Make sure to always set comparison type

- cmd/frontend/internal/httpapi/httpapi.go
- cmd/frontend/internal/httpapi/search.go
- cmd/frontend/internal/httpapi/search_test.go
This refactors the anonymous interfaces defined in `searchIndexerServer` to be named types.
Anonymous interfaces don't support code navigation, at least not in Goland, and it was very tedious to use CMD+F the whole time.
Test plan:
pure refactor => CI
> search: refactor anonymous interfaces

- CHANGELOG.md
- client/web/src/components/DismissibleAlert/DismissibleAlert.tsx
- client/web/src/global/Notices.test.tsx
- client/web/src/global/Notices.tsx
- client/web/src/global/__snapshots__/Notices.test.tsx.snap
- client/wildcard/src/components/Alert/Alert.tsx
- schema/schema.go
- schema/settings.schema.json
Closes #59751 
- Added `variant` option for Notices. Defaults to default option for position.
- Added `styleOverrides` option to Notices with three fields:
- backgroundColor
- textColor
- textCentered
This means in the site-config a user can now specify notices as:
```json
{
"notices": [
{
"message": "THIS IS AN IMPORTANT NOTICE",
"location": "top",
"variant": "danger",
"styleOverrides": {
"backgroundColor": "#7f1d1d",
"textColor": "#fecaca",
"textCentered": true
}
}
]
}
```
resulting in the following notice
- Updated existing regression tests
- Manually tested with various site-config settings.
Backport ccba7d4 from #61338
> [Backport 5.3.9104] Notices: Add customization for background color, text color, and text position.

- cmd/cody-gateway/internal/dotcom/BUILD.bazel
- cmd/cody-gateway/internal/dotcom/dotcom.go
- cmd/cody-gateway/internal/dotcom/dotcom_test.go
- cmd/cody-gateway/internal/httpapi/attribution/handler_test.go
- cmd/cody-gateway/shared/config/config.go
- cmd/cody-gateway/shared/main.go
Add a header that we can use to identify Cody Gateway requests to sourcegraph.com - [context](https://sourcegraph.slack.com/archives/C05497E9MDW/p1713453541038879?thread_ts=1713431784.192999&cid=C05497E9MDW).
- local testing
> Support setting clientID for calls from Cody Gateway to sourcegraph.com

- cmd/gitserver/internal/server.go
- cmd/gitserver/internal/vcssyncer/git.go
- cmd/gitserver/internal/vcssyncer/syncer.go
Since we refactored VCSSyncer recently to take control of the remote URL, we now do redaction at this layer, so this TODO comment can be removed.
Test plan:
E2E test suite still passes.
> gitserver: Clean up output redaction

- client/web-sveltekit/package.json
- client/web-sveltekit/playwright.config.ts
- client/web-sveltekit/src/lib/navigation.ts
- client/web-sveltekit/src/routes/+layout.svelte
- client/web-sveltekit/src/routes/layout.spec.ts
- client/web-sveltekit/src/routes/search/page.spec.ts
- client/web-sveltekit/src/testing/integration.ts
Running playwright tests on the production build has been broken for some tests for two reasons:
- In the production build the app has knowledege about which routes are enabled. It assumes none are and so any navigation event results in the page reloading. This can have some unexpected effects on the state of the application.
- `this.page.addInitScript` returns a promise that has to be awaited. Otherwise we cannot be sure that it has executed before the other steps of the test. I don't know why that wasn't a problem in the development build.
To solve the first issue I added a new "preview" build which is identical to the production build except that every route is "enabled" and served normally. I've updated the playwright config to use that build instead. It can also be used "manually" by …
> svelte: Fix playwright tests

- cmd/gitserver/internal/search.go
- cmd/gitserver/internal/server.go
Now co-located with the code it is observing.
Test plan:
N/a, moved code only.
> gitserver: Move search observability

- cmd/gitserver/internal/integration_tests/clone_test.go
- cmd/gitserver/internal/lock.go
- cmd/gitserver/internal/main_test.go
- cmd/gitserver/internal/server.go
- cmd/gitserver/internal/server_test.go
Those two used to have separate mechanisms for locking and for making sure the operation keeps going in the background.
This PR unifies those two where possible.
Test plan:
The clone test covers this pretty well, and I made a few adjustments there to cover the new behavior.
Also, E2E tests will cover clone failures.
> gitserver: Simplify clone and update

- cmd/gitserver/internal/ensurerevision.go
- cmd/gitserver/internal/server.go
- cmd/gitserver/internal/server_test.go
- cmd/gitserver/internal/vcssyncer/git.go
- cmd/gitserver/internal/vcssyncer/instrumented_syncer.go
- cmd/gitserver/internal/vcssyncer/mock.go
- cmd/gitserver/internal/vcssyncer/packages_syncer.go
- cmd/gitserver/internal/vcssyncer/packages_syncer_test.go
- cmd/gitserver/internal/vcssyncer/perforce.go
- cmd/gitserver/internal/vcssyncer/syncer.go
Revspec updates never worked reliably. When there was _any_ operation in flight, we would just not fetch this revspec and return "all good".
This is only used by packages, an experimental feature.
Gitserver should not modify the authoritative data source for what versions exist. Instead, callers should add the version to the list of desired versions, and they'll eventually be part of the package when the next fetch occurred.
Anyhow, experimental, didn't work reliably, will be removed for now.
Test plan:
Existing test suites.
> gitserver: Remove revspec updates

- cmd/gitserver/internal/repo_info.go
- cmd/gitserver/internal/server_grpc.go
- cmd/gitserver/internal/serverutil.go
- cmd/gitserver/internal/statesyncer.go
After refactoring to use the same locker for both tasks, this no longer only resembles cloneInProgress, so cleaned this up a little.
Test plan:
Existing test suites.
> gitserver: Clarify what RepositoryLock indicates

- client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
- client/web-sveltekit/src/lib/codemirror/utils.ts
- client/web-sveltekit/src/lib/repo/FileHeader.svelte
- client/web-sveltekit/src/lib/stores.ts
- client/web-sveltekit/src/lib/web.ts
- client/web-sveltekit/src/routes/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.spec.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
- client/web/src/repo/blob/codemirror/linenumbers.ts
- package.json
- pnpm-lock.yaml
This commit removes the full page scrolling behavior for repo root, directory and file pages. The implementation had several issues.
In the new implementation the scroll container is CodeMirror itself. It provides the following behavior:
- Show the top of the file when navigating to a new file.
- Scroll the selected line into view when opening a URL containing a position.
- Do not scroll when selecting a line (currently broken).
- Restore previous scroll position when navigating backward or forward in the browser history.
- Toggling the blame view maintains the current line view (well, almost but that's as best as we can do at the moment).
Additional changes in this commit:
- Removed logic to enable/disable full page scrolling.
- Remove CSS for making elements `sticky`.
- Update "scroll …
> svelte: Remove full page scrolling of repo pages

- cmd/gitserver/internal/server.go
- cmd/gitserver/internal/server_test.go
- cmd/gitserver/internal/vcssyncer/git.go
- cmd/gitserver/internal/vcssyncer/instrumented_syncer.go
- cmd/gitserver/internal/vcssyncer/mock.go
- cmd/gitserver/internal/vcssyncer/packages_syncer.go
- cmd/gitserver/internal/vcssyncer/packages_syncer_test.go
- cmd/gitserver/internal/vcssyncer/perforce.go
- cmd/gitserver/internal/vcssyncer/syncer.go
Clone already did this, now Fetch does the same.
This will allow to also get access to the progress while it's happening, not only afterwards.
Test plan:
Existing clone / update tests still pass.
> gitserver: Add progressWriter to VCS fetch

- cmd/gitserver/internal/BUILD.bazel
- cmd/gitserver/internal/ensurerevision.go
- cmd/gitserver/internal/integration_tests/clone_test.go
- cmd/gitserver/internal/integration_tests/resolverevisions_test.go
- cmd/gitserver/internal/integration_tests/utils_test.go
- cmd/gitserver/internal/mocks_test.go
- cmd/gitserver/internal/repositoryservice.go
- cmd/gitserver/internal/server.go
- cmd/gitserver/internal/server_grpc.go
- cmd/gitserver/internal/server_test.go
- internal/gitserver/protocol/BUILD.bazel
- internal/gitserver/protocol/gitolite_phabricator.go
Just a simple name change to reflect the gRPC API surface in the service layer.
Test plan:
CI and go compiler
> gitserver: Rename RepoUpdate to FetchRepository

- dev/sg/sg_teammate.go
- lib/output/output.go
while looking into why certain github handles were not picked up and I noticed this was missing and it seems pretty useful
* Unit tests
* CI
* Locally
```
go run ./dev/sg teammate details william bezuidenhout
Name       : William Bezuidenhout
Slack      : william.bezuidenhout
Email      : william.bezuidenhout@sourcegraph.com mailto:william.bezuidenhout@sourcegraph.com
GitHub     : burmudar https://github.com/burmudar
Location   : Cape Town, South Africa 🇿🇦
Role       : Software Engineer
Description: William lives in the beautiful Cape Town, South Africa. He enjoys running and moutain biking and when the weather permits (and his motivation) he can be out riding some trail at a wine
farm or taking a leisure run. Besides the outdoor stuff, he loves to tinker and can often be found working on …
```
> sg: print teammate details to terminal

- dev/sg/BUILD.bazel
- dev/sg/main.go
- dev/sg/sg_images.go
- dev/sg/sg_images_test.go
Fixes https://github.com/sourcegraph/devx-support/issues/165
Adds a `sg images [build|list]` command. It has a `--load` flag that is turned on by default. We print out the `sg bazel` commands to teach users what's happening under the hood.
> feat(sg): add images [list|build] command

- dev/ci/internal/ci/pipeline.go
- release.yaml
- testing/tools/upgradetest/BUILD.bazel
- testing/tools/upgradetest/main.go
- testing/tools/upgradetest/release_test.sh
- testing/tools/upgradetest/test.sh
- testing/tools/upgradetest/tests-util.go
- testing/tools/upgradetest/tests.go
This PR introduces the `target-registry` and `from-registry` flags. These flags allow the specification of the image registry to pull from when running the upgrade test. `target-registry` sets the `migrator` image image registry as well as the `frontend` during the upgrade steps of the various upgrade test types. `from-registry` sets the image registry used to pull images on test env init -- initializing `pgsql`, `codeintel-db`, `codeinsights-db`, migrator`, and `frontend`. 
The following command works on main --
`bazel run //testing/tools/upgradetest:sh_upgradetest -- all -pv 5.3.9104 -svs 5.2.2 -mvs 5.1.0 -avs 5.1.0`
The command should work with new flag `bazel run //testing/tools/upgradetest:sh_upgradetest -- all -pv 5.3.9104 -svs 5.2.2 -mvs 5.1.0 -avs 5.1.0 -target-registry …
> feat(rel): plug upgradetest into release tests

- internal/updatecheck/client.go
Title says it all. 
Facing some issues on my testing in some instances but I don't have enough logging to be able to solve those issues so I am adding this PR
Just check the new logs on failure
> Adding logging for getLLMUsageData data failed

- dev/gqltest/search_test.go
- internal/search/codycontext/job.go
- internal/search/job/jobutil/job_test.go
This backport folds together these two PRs, which together fix a bug around
queries containing only stopwords:
* https://github.com/sourcegraph/sourcegraph/pull/61848
* https://github.com/sourcegraph/sourcegraph/pull/62026
Same test plan as original PRs
> [Backport 5.3.9104] Context: avoid panic on stopwords query (#62026)

- dev/oci_deps.bzl
This PR updates the gitserver base image - it downgrades curl to `8.6.0` due to a regression in curl `8.7.0` that affects  `git fetch`. As a side effect, a number of other packages are also upgraded but I don't foresee this being a problem assuming it passes all release tests.
[Context from Slack](https://sourcegraph.slack.com/archives/C02E4HE42BX/p1713775531525999)
Image hash taken from https://buildkite.com/sourcegraph/sourcegraph/builds/270158. Updated image url from dockerhub to us.gcr.io as we no longer push to Dockerhub.
Running affected `git fetch` against broken `sourcegraph/gitserver:5.3.9104` image:
```
Initialized empty Git repository in /data/repos/
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
fatal: unable to write request to remote: Broken pipe …
```
> Update gitserver image to pull in libcurl fix

- internal/profiler/BUILD.bazel
- internal/profiler/profiler.go
- internal/service/svcmain/svcmain.go
We currently have it implicitly enabled in dotcom mode, but this is a non-useful side-effect of that flag, and we should instead be explicit in the deployment, and remove that check here.
https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/18540 sets this env var explicitly.
Test plan:
Watch rollout of the deploy repo.
> dotcom: Remove side-effect of dotcom mode on GCP profiler

- client/web-sveltekit/src/lib/repo/FileHeader.svelte
- client/web-sveltekit/src/lib/repo/open-in-editor/OpenInEditor.svelte
Small fix for open in IDE icon position 
| ----- | ------ |
| <img width="379" alt="Screenshot 2024-04-22 at 18 06 54" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/3afa55ca-6571-481b-83f1-efb88a1763ef">  |  <img width="390" alt="Screenshot 2024-04-22 at 18 06 31" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/8af76755-bc4f-45f3-899d-6eec59264e4a"> |
| <img width="226" alt="Screenshot 2024-04-22 at 18 06 48" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/b9f8eff1-c086-4c6d-affb-113630c743ca"> |  <img width="257" alt="Screenshot 2024-04-22 at 18 06 40" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/ea8498a5-c54f-45c5-a9b6-966be525e7e7"> | 
- Check that the visually open in IDE icon looks correct
> Svelte [blob page]: Fix open in editor icon position

- internal/rcache/rcache.go
Fixing some methods for cache selection of key values stores for redis. 
- I tested it on the instance
> Fixing cache methods to use the right method to retrieve key value stores

- CHANGELOG.md
This PR adds some missing changelog entries for the April 22nd patch release.
Docs-only change
> Update changelog for patch release

- client/web/src/stores/navbarSearchQueryState.test.ts
- client/web/src/util/settings.ts
Fixes #61937 
It looks like we hardcoded keyword if the feature was enabled. This change honors an existing default
- Manual testing of different permutations of default and no-default settings
> KeywordSearch: Honor default search pattern type if present

- client/web-sveltekit/src/lib/Icon.svelte
Regression after https://github.com/sourcegraph/sourcegraph/pull/62012
In https://github.com/sourcegraph/sourcegraph/pull/62012 I changed Icon.svelte CSS variable API but didn't make a proper migration, so in this fix, I just bring back old variable support. 
So originally we have `--color` variable to set the color for `Icon.svelte` but this seemed a bit too generic so I wanted to rename it to `--icon-color` but we already have this variable as a design token (too bad, we should revisit our CSS color variables it looks a bit chaotic at the moment), eventually I ended up with `--icon-fill-color`, not ideal but doesn't overlap with other css variables.
- Check that icons have proper colors in different context (file tree extension icons, global nav icons color, etc.)
> Fix icons color

- cmd/gitserver/internal/git/gitcli/BUILD.bazel
- cmd/gitserver/internal/git/gitcli/command.go
- doc/admin/observability/dashboards.md
- monitoring/definitions/git_server.go
This PR adds additional observation tools and warning logs for git commands that required a lot of memory. That should help us better identify where potential for OOMs exists and what endpoints could benefit from optimization.
```
[    gitserver-0] WARN gitserver.cleanup gitcli/command.go:307 High memory usage exec request {"TraceId": "f70c73e500ed7831207ce9a7c6dc63fb", "SpanId": "705d1dcfd0b44a06", "ev.Fields": {"exit_status": "0", "cmd_duration_ms": "1944", "user_time": "234.915ms", "cmd_ru_minflt": "10231", "cmd_ru_majflt": "7", "duration_ms": "1944", "trace": "https://sourcegraph.test:3443/-/debug/jaeger/trace/f70c73e500ed7831207ce9a7c6dc63fb", "cmd_ru_maxrss_kib": "160672", "actor": "0", "traceID": "f70c73e500ed7831207ce9a7c6dc63fb", "repo": "github.com/sourcegraph/sourcegraph", …
```
> gitserver: RUsage and high mem exec logging

- dev/sg/main.go
As title. Instead of just assuming that sg.config.overwrite.yaml exists, check for it before watching.
Ran locally
> (sg/bug) check that sg overwrite file exists

- dev/managedservicesplatform/cdktf.go
- dev/sg/msp/helpers.go
- dev/sg/msp/sg_msp.go
- lib/output/line.go
- lib/output/style.go
Part of https://github.com/sourcegraph/managed-services/issues/599
See https://github.com/sourcegraph/managed-services/pull/1288 for how this mechanism will be used.
```sh
sg msp generate -all -category=test
```
> sg/msp: filter generated environments by category

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/RepositoryRevPicker.gql
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/RepositoryRevPicker.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/layout.gql
This updates the revision picker to support searching for commits by hash. This has been a long-standing product gap in the React webapp, and the same problem exists in the Svelte webapp. 
I did not fix this in the React webapp as well because our pagination logic is very tied to GraphQL pagination, and I couldn't come up with an easy way to add an item to the list that is outside of a paginated list of nodes.
Fixes https://github.com/sourcegraph/sourcegraph/issues/18792 in the Svelte webapp
Fixes https://github.com/sourcegraph/sourcegraph/issues/44881 in the Svelte webapp
https://github.com/sourcegraph/sourcegraph/assets/12631702/d2ea52e7-eded-42cb-a874-341002af8e15
> Svelte: allow picking by commit hash

- deps.bzl
- dev/tool_deps.bzl
- dev/tools/BUILD.bazel
- go.mod
- go.sum
- internal/appliance/BUILD.bazel
- internal/appliance/blobstore.go
- internal/appliance/blobstore_test.go
- internal/appliance/development.md
- internal/appliance/golden_test.go
- internal/appliance/helpers_test.go
- internal/appliance/kubernetes.go
- internal/appliance/kubernetes_test.go
- internal/appliance/reconcile.go
- internal/appliance/reconcile_test.go
- internal/appliance/spec.go
- internal/appliance/testdata/golden-fixtures/blobstore-default.yaml
- internal/appliance/testdata/golden-fixtures/blobstore-subsequent-disable.yaml
- internal/appliance/testdata/sg/blobstore-default.yaml
- internal/appliance/testdata/sg/everything-disabled.yaml
- internal/k8s/resource/deployment/deployment_test.go
- internal/k8s/resource/pod/example_test.go
- internal/k8s/resource/pod/pod.go
- internal/k8s/resource/pod/pod_test.go
- internal/k8s/resource/statefulset/statefulset_test.go
Use envtest (https://book.kubebuilder.io/reference/envtest.html) to start a real Kubernetes API server, backed by a real etcd instance, in tests. The only controller running is our appliance controller, so these tests assert on the changes our controller actually makes to Kubernetes API objects in response to some input, but don't depend on complex infrastruture like container runtimes or persistent volume controllers (since no such controllers are actually running, unlike in a useful Kubernetes cluster).
This commit adds a test harness to the appliance package:
* It starts the k8s API server only once, not once per test, as this is a relatively slow operation.
* Helper functions to run each test in a unique namespace to avoid inter-test dependency. This opens the door to parallelism, but …
> appliance: golden/snapshot testing

- .github/workflows/sg-binary-release.yml
We no longer require a build variant, and MSP is now included by default since https://github.com/sourcegraph/sourcegraph/pull/59087.
Remaining reference to the variant will be removed in https://github.com/sourcegraph/managed-services/pull/1288. Do not merge this until https://github.com/sourcegraph/managed-services/pull/1288 is merged.
https://github.com/sourcegraph/managed-services/pull/1288
> workflows: remove sg-msp variant from sg publish

- CHANGELOG.md
- cmd/gitserver/internal/repositoryservice.go
- cmd/gitserver/internal/server_grpc_logger.go
- cmd/gitserver/shared/shared.go
This PR builds on https://github.com/sourcegraph/sourcegraph/pull/61270, and adds the request logging funcionality to the repository grpc server in gitserver.
Local testing:
Ran `env SRC_GITSERVER_EXHAUSTIVE_LOGGING_ENABLED=true SRC_LOG_SCOPE_LEVEL=gitserver.gRPCRequestLogger=debug sg start` locally, and saw the following output from the logger in my terminal (note that specifically the repository service is mentioned):
```
[    gitserver-0] DEBUG gitserver.gRPCRequestLogger internal/server_grpc_logger.go:46 Handled FetchRepository RPC {"server": "gitserver.v1.GitserverRepositoryService", "method": "FetchRepository", "status": "OK", "traceID": "67f1aa837367fa7ea72b164e70a67419", "duration": "1.068438833s", "request": {"repoName": "github.com/sgtest/megarepo"}}
```
> gitserver: grpc: create exhaustive logger for repository service

- cmd/gitserver/internal/git/gitcli/command.go
This makes it more readable in honeycomb, and we do the same further down for traces.
Test plan:
Check out honey after rollout.
> gitserver: Record times in milliseconds

- cmd/repo-updater/internal/scheduler/scheduler.go
This should reduce some sentry error reporting for non-actionable errors.
Test plan:
Will see if sentry is more silent.
> Don't log when repo-updater shuts down

- client/shared/src/search/stream.ts
- client/web-sveltekit/src/lib/shared.ts
- client/web-sveltekit/src/routes/search/SearchAlert.svelte
- client/web-sveltekit/src/routes/search/SearchResults.svelte
- client/web-sveltekit/src/routes/search/page.spec.ts
Before this, we were completely ignoring any alerts that come from the search backend. This fixes that.
Added simple playwright test that ensures the alert is visible if it is sent on the stream.
> Svelte: render search alerts

- internal/database/migration/shared/data/stitched-migration-graph.json
- internal/database/schema.json
- internal/database/schema.md
- migrations/frontend/1713958707_search_jobs_add_index_on_state_col/down.sql
- migrations/frontend/1713958707_search_jobs_add_index_on_state_col/metadata.yaml
- migrations/frontend/1713958707_search_jobs_add_index_on_state_col/up.sql
- migrations/frontend/squashed.sql
The search jobs tables are missing an index on the state column that most worker tables have - the dequeue query on dotcom takes 12.07s at the moment.
Test plan:
`sg migration up --db frontend; sg migration undo`
> search jobs: add index on state column

- cmd/frontend/internal/inventory/BUILD.bazel
- cmd/frontend/internal/inventory/entries.go
- cmd/frontend/internal/inventory/inventory.go
- cmd/frontend/internal/inventory/inventory_test.go
This is just a couple of followups from #62011 that I had asked for. This is @bahrmichael's branch that I am just pushing up to get reviewed and merged. Consider it reviewed and approved by me, feel free to just stamp.
This:
- Removes the lockfile ignoring logic that was added in #62011 
- Fixes a race condition on a shared buffer by allocating a new buffer for each file
I'm not concerned about the perf of the allocation because it is a fixed-size allocation for each file (we process the file in a streaming manner) and there is already a network request for each file.
Bazel tests pass after re-enabling race detection.
> Code insights: followup from #62011

- wolfi-images/caddy.lock.json
Update caddy version to fix CVE-2023-45288
- CI
> Bump caddy to fix CVE-2023-45288

- client/web-sveltekit/src/lib/CodeExcerpt.stories.svelte
- client/web-sveltekit/src/lib/CodeExcerpt.svelte
- client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
- client/web-sveltekit/src/lib/Scroller.svelte
- client/web-sveltekit/src/lib/TabPanel.svelte
- client/web-sveltekit/src/lib/Tabs.svelte
- client/web-sveltekit/src/lib/global-notifications/DismissibleAlert.stories.svelte
- client/web-sveltekit/src/lib/global-notifications/DismissibleAlert.svelte
- client/web-sveltekit/src/lib/repo/FileHeader.svelte
- client/web-sveltekit/src/lib/repo/blob.ts
- client/web-sveltekit/src/lib/repo/utils.ts
- client/web-sveltekit/src/lib/search/CodeExcerpt.svelte
- client/web-sveltekit/src/lib/shared.ts
- client/web-sveltekit/src/lib/wildcard/Alert.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FilePreview.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/ReferencePanel.gql
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/ReferencePanel.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/ReferencePanelCodeExcerpt.gql
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/ReferencePanelCodeExcerpt.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/layout.gql
- client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
- client/web-sveltekit/src/routes/search/SymbolSearchResult.svelte
Closes #59138 
This PR adds a *very early* version of the reference panel.
| Status | Screenshot |
| Open reference panel, with reference | ![2024-04-24_21-47_1](https://github.com/sourcegraph/sourcegraph/assets/179026/8270866a-3d80-4545-a48c-346270a19a5f) |
| Open reference panel, without reference | ![2024-04-24_21-47_2](https://github.com/sourcegraph/sourcegraph/assets/179026/01b78324-ac63-4845-9532-9630b24e74d8) |
| Preview error | ![2024-04-24_21-47](https://github.com/sourcegraph/sourcegraph/assets/179026/61d0dddb-d041-455b-ab64-3ae83916999d) |
| No references found | ![2024-04-24_22-04](https://github.com/sourcegraph/sourcegraph/assets/179026/540a200a-33c1-46aa-840b-f96623040db2) |
Demo: 
https://github.com/sourcegraph/sourcegraph/assets/179026/742492ad-5a0b-462d …
> svelte: Add minimal reference panel

- release.yaml
After dabbling with various options to handle the missing `curl --fail-with-body` flag because the curl version that supports that older than what we have in CI, I couldn't let go of this feature, because it's so damn useful when trying to understand what went wrong. 
There are some ways to tame `curl` in doing that in earlier versions, but frankly, it's quite complicated and involves non trivial piping and toying with the output, which is really not what we want for the release manifests. 
I discovered that `wget` has what we want, and tested that on our agents, `wget` has those, so we're good.
> chore(rel): use wget instead of curl

- .aspect/bazelrc/ci.sourcegraph.bazelrc
May alleviate cache pressure, as well as potentially giving a slight boost to performance 
See https://github.com/aspect-build/rules_js/issues/1469 and https://sourcegraph.slack.com/archives/C04BWU1519D/p1713473625997359
CI passes green
> ci: don't remotely cache copy{dir,file} operations

- .github/workflows/sg-binary-release.yml
- dev/sg/internal/background/background.go
- dev/sg/main.go
- dev/sg/sg_doctor.go
- dev/sg/sg_version.go
We have nice release names in https://github.com/sourcegraph/sg/releases, but it's not actually programmatically available - this causes a discrepancy between the `sg` version one might pull, and the version of `sg` that is known in-code, and means that we can't do something like #62134.
This change adds a `ReleaseName` variable to be stamped at build/release time, and updates a few references to `BuildCommit` where I think it might be more prudent to report `ReleaseName` instead, and also fixes some yellow squiggles in my IDE on files I visited (sorry) and some noisy `-v` output (sorry again)
```
$ go build -ldflags "-s -w -X main.BuildCommit=$(git rev-list -1 HEAD .) -X main.ReleaseName=hello-world" -o ./sg ./dev/sg                       
$ ./sg version
hello-world
$ ./sg -v version …
```
> sg-binary-release: stamp with GitHub release name

- dev/sg/internal/release/config.go
- release.yaml
Requirement checks are now done for every phase. Because phases can be executed in different enviroments, it can happen that a check is mandatory at a given stage but problematic in another. For example we need `BUILDKITE_ACCESS_TOKEN` to create builds, but this env var is not set in CI, nor it's necessary at this stage. 
At first, I went for having a `requirements:` field on every phase, but this felt error prone, because you would repeat the same check, i.e. with `BUILDKITE_ACCESS_TOKEN` you'd need it on both `internal.create` and `promoteToPublic.create`. 
You could use the YAML features to avoid the repeatition, but they're extremely error prone and frustrating to work with. 
Instead, I kept the original idea that we want the requirements to be clear and at the top of the release …
> chore(rel): run requirements check for every command

- cmd/frontend/internal/embeddings/resolvers/BUILD.bazel
- cmd/frontend/internal/embeddings/resolvers/repo_embedding_jobs_test.go
- cmd/frontend/internal/embeddings/resolvers/resolvers_test.go
- internal/conf/BUILD.bazel
- internal/conf/computed.go
- internal/conf/computed_test.go
- internal/conf/embeddings.go
- internal/embeddings/background/repo/store_test.go
As we're evaluating the quality of Cody's context, it's really useful to be
able to compare against Enterprise embeddings. However, we completely disabled
Enterprise embeddings when we turned them off for customers.
This PR adds an environment variable `SRC_EMBEDDINGS_ALLOWED` that lets us
enable and test embeddings locally. It is not advertised and should never be
enabled in production use.
Local testing using the [context eval repo](https://github.com/sourcegraph/context-eval). The README now contains instructions
for how to run locally using `SRC_EMBEDDINGS_ALLOWED=true sg start`.
> Context: allow embeddings only for testing

- client/web-sveltekit/src/lib/search/input/SearchInput.svelte
- client/web-sveltekit/src/routes/search/+page.ts
Fixes https://github.com/sourcegraph/sourcegraph/issues/61636
Manually tested that hitting enter in the query bar re-submits the query. Verified that the only request made is a search request and `EditTemporarySettings`, which seems to be run after ever search request for reasons unbeknownst to me.
> Svelte: fix resubmit query

- client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
- client/web-sveltekit/src/lib/web.ts
This adds the "no newline at end of file" extension, which makes it so we do not incorrectly show an extra line at the end of the file when there is a trailing newline and adds a message if there is no trailing newline.
> Svelte: add no newline extension

- dev/sg/internal/rfc/rfc.go
- dev/sg/sg_rfc.go
We do this in the printer, where we have more control over interpreting the file titles.
Context: https://sourcegraph.slack.com/archives/C015P61EXV1/p1714085557621709?thread_ts=1714070620.515829&cid=C015P61EXV1
```
sg rfc list -s approved -s implemented -s done
```
Note that this only covers public RFCs, you need `-private` as well to get the private RFCs.
There are some recent RFCs at the bottom, so the format is still used :)
> sg/rfc: add -s for filtering by status(es)

- client/web-sveltekit/src/lib/repo/FileHeader.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.spec.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
This fixes some issues with the breadcrumbs in the file header:
1) The links did not preserve the current revision
2) The links assumed that if the current page was a blob, all parent breadcrumbs are also blobs. Everything but the last element in the path is guaranteed to be a tree.
Added a playwright test that we link back to a tree page correctly. Manually tested the current revision stuff.
> Svelte: fix file header links

- dev/sg/sg_update.go
MSP pins `sg` version per environment category to control rollout of changes: https://github.com/sourcegraph/sourcegraph/pull/62134
This allows users to update to a specified release (instead of always `latest`) with a new `-release` flag on `sg update`:
```
sg update -release ${release_name}
```
Example usage: https://github.com/sourcegraph/sourcegraph/pull/62134#discussion_r1580114111, details on how `sg msp` version pinning works: https://sourcegraph.notion.site/Deploying-new-versions-of-MSP-1808e7e45bd54f419dd93af542d99238#58dabe4992754ca18ed39bc212ccbbba
Install specified release:
```sh
$ go build -o ./sg ./dev/sg && ./sg install -f -p=false
$ sg version
unknown
$ sg update -r 2024-04-24-16-44-3623ecb2               
⚠️ Installing user-specified release "2024-04-24-16-44-3623ecb2" - …
```
> sg/update: allow users to specify a release with '-release'

- dev/managedservicesplatform/internal/resource/redis/BUILD.bazel
- dev/managedservicesplatform/internal/resource/redis/redis.go
Makes the downgrade option introduced in https://github.com/sourcegraph/sourcegraph/pull/62137 usable, since a tier change in Redis is a force-recreate situation (unlike Cloud SQL)
Documented this noob mistake in https://sourcegraph.notion.site/MSP-infrastructure-upgrades-1808e7e45bd54f419dd93af542d99238#545745ef335148d5a0e22655b216db29
No alerts fired during either of the above
> msp/redis: make tier changes graceful

- internal/rockskip/index.go
We have seen errors on S2 for inserting non-utf-8 data to the symbols table. `path` and `name` (symbol name) are the only user controlled fields. We already check for non-utf-8 content in go-ctags, so that leaves `path`, which is not required to be utf-8 compatible.
With this change we simply skip the path, which means that symbols within that path will not exist in the index. This is somewhat in line with ctags, where we skip indexing non-utf-8 content.
I believe this is an edge case and it is acceptable to skip those files to keep the code simple.
Alternatives:
- We could store arbitrary bytes `bytea` instead of `text` in Postgres.
Test plan:
CI
> rockskip: skip non-utf8 paths

- cmd/frontend/internal/codycontext/context.go
Exclude `.map` and `.min.js` files from keyword search behind getCodyContext. 
Tested manually with `getCodyContext` API for react repo.
Normal search gets results from `scheduler.profiling.min.js`
But `getCodyContext` does not:
Before:
> Exclude files for getCodyContext keyword search

- .buildkite/pipeline.backcompat.yml
Not needed since this build https://buildkite.com/sourcegraph/sourcegraph-backcompat/builds/30629
CI
> ci: remove softfail backcompat mitigation

- internal/codeintel/dependencies/internal/store/store.go
- internal/codeintel/dependencies/internal/store/store_test.go
The `packageRepoReferences` API lists repositories by doing a fuzzy search against the `name` argument but it doesn't sort them according to name or exact match.
This PR addresses the issue and first sorts the results by exact match and then by id asc
unit tests added
> Sort packages by exact match

- internal/appliance/BUILD.bazel
- internal/appliance/blobstore.go
- internal/appliance/config/BUILD.bazel
- internal/appliance/config/config.go
- internal/appliance/development.md
- internal/appliance/kubernetes.go
- internal/appliance/repo_updater.go
- internal/appliance/repo_updater_test.go
- internal/appliance/spec.go
- internal/appliance/testdata/golden-fixtures/blobstore-default.yaml
- internal/appliance/testdata/golden-fixtures/blobstore-subsequent-disable.yaml
- internal/appliance/testdata/golden-fixtures/repo-updater-default.yaml
- internal/appliance/testdata/golden-fixtures/repo-updater-with-no-resources.yaml
- internal/appliance/testdata/golden-fixtures/repo-updater-with-resources.yaml
- internal/appliance/testdata/golden-fixtures/repo-updater-with-sa-annotations.yaml
- internal/appliance/testdata/sg/repo-updater-with-no-resources.yaml
- internal/appliance/testdata/sg/repo-updater-with-resources.yaml
- internal/k8s/resource/container/BUILD.bazel
- internal/k8s/resource/container/container.go
- internal/k8s/resource/service/BUILD.bazel
- internal/k8s/resource/service/service.go
- internal/k8s/resource/serviceaccount/BUILD.bazel
- internal/k8s/resource/serviceaccount/serviceaccount.go
Create a "common" config struct+interface that can be embedded in service config, to get various facilities for free. The aim is to reduce the prospect for errors given how much service config the appliance will soon handle.
See changes to development.md for a full explanation of what I'm trying to do here.
Tests included.
> appliance: de-dup common service features

- dev/sg/internal/release/config.go
The update to requirements check introduced a regression where excluded requirements would short-circuit the function for requirement checking and return a nil error.
This allowed the `createRelease` function to be executed even when requirements were missing.
> release: fix regression in release requirements check

- dev/sg/internal/release/config.go
I didn't cover all the cases with the regression in my previous PR.
I cut an internal release earlier and realized some steps passed even though there were failures, so this should fix all those now.
> release: fix error handling with `sg release`

- cmd/frontend/internal/context/resolvers/BUILD.bazel
- cmd/frontend/internal/context/resolvers/context_test.go
Follow up to #61849. We pushed Cody ignore filtering down into the Cody search
job and added tests. In the shuffle, I removed this helpful GraphQL resolvers
test, which serves as an integration test for Cody ignore config. This PR
restores it and adapts it to use a real search client to exercise the filtering
logic.
Test-only change
> Context: restore Cody ignore integration test

- .aspect/bazelrc/remote_cache_for_local.bazelrc
- dev/remote_cache_local_env.sh
- dev/sg/sg_bazel.go
Using a GCS bucket + a custom credential helper, we can enable the remote cache for everyone without having to perform explicit authentication or setup. Authentication is fully delegated to `gcloud`. And because every teammate can access the secrets for the local env, they can also write on the cache. 
In case of emergency, `--disable-remote-cache` can disable the remote cache flags, and normal `bazel [cmd]` are unaffected. 
Bystanders that would like to test this: 
```
git fetch
git checkout jh/bzl/local-remote-cache
go run ./dev/sg bazel build //cmd/gitserver
```
💡 Additionally, this creates the incentive we were looking for to teach folks to use `sg bazel` over `bazel`.
Locally tested (and @eseliger tested it too, to avoid ending up in a scenario where I have special perms on that GCP …
> chore(sg): sg bazel uses remote cache by default (unless in CI) 

- .aspect/bazelrc/remote_cache_for_local.bazelrc
Observing weird behaviour, disabling the experimental flag.
CI
> chore(bzl): disable experimental flag async RC

- cmd/frontend/graphqlbackend/repository_contributors.go
- internal/codeintel/policies/internal/store/configurations_test.go
- internal/codeintel/uploads/internal/store/uploads_test.go
- internal/database/executors_test.go
- internal/insights/scheduler/backfill_state_inprogress_handler.go
- internal/insights/scheduler/iterator/repo_iterator.go
- internal/usagestats/usage_stats.go
- lib/codeintel/lsif/conversion/group.go
These were introduced in Go 1.21 and avoid int->float64->int conversions
> chore: Use min/max builtins over math.Max/math.Min

- dev/sg/sg_bazel.go
Fix a small bug, if you're not running `sg` at the root of the repo, the bazelrc path would be incorrect.
> bug(sg): fix issue where path to bazelrc would fail

- client/web/src/marketing/toast/CodySurveyToast.tsx
- client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
- client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx
- client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx
- client/web/src/user/settings/accessTokens/UserSettingsTokensArea.tsx
- client/web/src/user/settings/accessTokens/UserSettingsTokensPage.tsx
- client/web/src/user/settings/accessTokens/create.ts
- client/web/src/user/settings/auth/ExternalAccount.tsx
- client/web/src/user/settings/auth/ExternalAccountsSignIn.test.tsx
- client/web/src/user/settings/auth/ExternalAccountsSignIn.tsx
- client/web/src/user/settings/auth/UserSettingsPasswordPage.tsx
- client/web/src/user/settings/auth/UserSettingsSecurityPage.tsx
- client/web/src/user/settings/backend.tsx
- client/web/src/user/settings/emails/AddUserEmailForm.tsx
- client/web/src/user/settings/emails/SetUserPrimaryEmailForm.tsx
- client/web/src/user/settings/emails/UserEmail.tsx
- client/web/src/user/settings/emails/UserSettingsEmailsPage.tsx
- client/web/src/user/settings/profile/EditUserProfileForm.tsx
- client/web/src/user/settings/profile/UserSettingsProfilePage.test.tsx
- client/web/src/user/settings/profile/UserSettingsProfilePage.tsx
- client/web/src/user/settings/research/ProductResearch.test.tsx
- client/web/src/user/settings/research/ProductResearch.tsx
> v2t: add v2t to src/user

- client/web-sveltekit/src/lib/repo/FileHeader.svelte
- client/web-sveltekit/src/lib/wildcard/Button.svelte
- client/web-sveltekit/src/lib/wildcard/Input.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/Picker.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/tags/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/tags/+page.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/tags/page.gql
Closes #61633 
This uses a similar approach as the commits page, except that pagination works a little bit differently.
Note that unlike the React app, every submission adds a new history entry, but also search submission has to be done explicitly. We can iterate on either if desired.
- Scrolling loads more tags
- Search can be submitted via 'enter' or clicking the submit button
- Going back or forth restores previously loaded data and scroll position
> svelte: Add infinity scroll and search to tags page

- CHANGELOG.md
- internal/batches/state/state.go
- internal/batches/state/state_test.go
Closes #62133
The computation for parsing the changeset for a Pull Request was incorrect, this caused GitHub pull request with a status of `SKIPPED` to be treated as a state of `UNKNOWN`.
We also treated any changeset with at least one status of `UNKNOWN` to have an overall status of `UNKNOWN`, I changed that logic to prioritize `FAILED` and `PENDING` statuses ahead of `UNKNOWN`.
* Unit testing
> batches: fix changeset status computation for changesets with skipped ci checks

- client/web-sveltekit/src/lib/CodeExcerpt.svelte
- client/web-sveltekit/src/lib/search/resultsIndicator/ResultsIndicator.svelte
- client/web-sveltekit/src/routes/search/FileSearchResultHeader.svelte
- client/web-sveltekit/src/routes/search/RepoRev.svelte
- client/web-sveltekit/src/routes/search/SearchResult.svelte
More visual update goodness for search results.
Locally tested for visual changes.
> Svelte: Visual update for search results

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
Regression introduced by #62187 . The condition for checking `showCodeView` is the wrong way round.
Manually tested.
> svelte: Fix showing code intel hovercards

- client/web-sveltekit/src/lib/Hotkey.test.ts
- client/web-sveltekit/src/lib/Hotkey.ts
- client/web-sveltekit/src/lib/search/input/SearchInput.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/page.gql
Fixes problem which was introduced by https://github.com/sourcegraph/sourcegraph/pull/62234
The original PR doesn't set `allowDefaults` which prevents populating input from entering the symbol which also was registered as a shortcut. Also there is a fix for catching field-like events 
- Check that `/` focuses the search box input on the home, result and blob UI pages
- Check that if the search input already got focus entering `/` leads to the adding `/` to the input value
- Check that if other input or form elements have focus entering `/` doesn't lead to the focusing search box input
> Fix search box `/` shourtcut

- internal/k8s/resource/deployment/deployment.go
The default is 1 anyway, and if this field is explicitly set but also
managed by an HPA, configuration changes will cause downscale events.
Even when the HPA subsequently scales back out, there may have been a
period of service disruption as requests saturate the single replica.
Note that this change causes no golden fixture changes, proving that the Deployment.spec.replicas default is already being defaulted to 1 by the Kubernetes resource schema.
> appliance: remove default deployment replica scale

- client/web-sveltekit/src/routes/styles.scss
Prior to this PR it looked like kbd badge has a slightly off layout (it cuts the lower part of the symbol since we use box-shadow inset) 
| ------- | ------- | 
| <img width="360" alt="Screenshot 2024-04-30 at 14 17 42" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/964df1b2-eff6-4f96-b76e-433c568dacc0"> | <img width="372" alt="Screenshot 2024-04-30 at 14 17 35" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/2762c83e-39eb-452f-aba4-9699746f2193"> |
- Check that kbd badges in search box suggestions, filters and in search box trigger button on the blob UI pages look good.
> Svelte: Fix `kbd` badge styles for svelte version

- client/web-sveltekit/src/lib/CodeExcerpt.svelte
- client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
There was a [regression](https://github.com/sourcegraph/sourcegraph/pull/62168/files#diff-8ae1a53166d42f8d47a6b4ec281c89db4cab47aa9ef6fb8db9a04af94dbc0a54L99-R99) that caused the line numbers for plaintext lines and highlighted lines to disagree, causing shifts in the highlighted ranges and the line numbers when the syntax highlighted code snippets loaded. This fixes it. 
Before:
https://github.com/sourcegraph/sourcegraph/assets/12631702/a2d3096c-4c11-47d7-bc03-80610ea4c611
After:
https://github.com/sourcegraph/sourcegraph/assets/12631702/f0894dc8-8715-44cb-94ef-2f6046c2f59d
> Svelte: fix line numbering for highlighted search results

- internal/appliance/BUILD.bazel
- internal/appliance/blobstore.go
- internal/appliance/reconcile.go
- internal/appliance/spec.go
- internal/appliance/symbols.go
- internal/appliance/symbols_test.go
- internal/appliance/testdata/golden-fixtures/blobstore-subsequent-disable.yaml
- internal/appliance/testdata/golden-fixtures/symbols-default.yaml
- internal/appliance/testdata/golden-fixtures/symbols-with-storage.yaml
- internal/appliance/testdata/sg/symbols-default.yaml
- internal/appliance/testdata/sg/symbols-with-storage.yaml
- internal/k8s/resource/pod/pod.go
- internal/k8s/resource/pvc/pvc.go
- internal/k8s/resource/statefulset/statefulset.go
Closes  https://github.com/sourcegraph/sourcegraph-operator/issues/45
Needs to be rebased on another PR, but it's independent of that branch, so should be reviewable.
See golden fixtures
> appliance: deploy symbols service

- client/web-sveltekit/src/lib/search/dynamicFilters/CountBadge.svelte
Made the count badge text slightly more visible on search results filters.
Locally tested for visual change.
> Svelte: Badge count text color updated on search results

- cmd/frontend/internal/httpapi/httpapi.go
- internal/ssc/BUILD.bazel
- internal/ssc/ssc_proxy.go
- internal/ssc/ssc_proxy_test.go
> ~~ℹ️ This PR is stacked on top of https://github.com/sourcegraph/sourcegraph/pull/62255.~~
This PR adds an HTTP handler that will proxy HTTP requests sent to `http://sourcegraph.com/.api/ssc/proxy/*` to `https://accounts.sourcegraph.com/cody/api/v1/*`.
> **Why?**
> For a variety of reasons we are moving the SSC UI from accounts.sourcegraph.com into sourcegraph.com. It doesn't make a lot of sense to add Cody Pro-specific APIs to the Sourcegraph instance's GraphQL API, since the resolver step would just require us to translate/proxy the HTTP request anyways.
>
> So this "universal API proxy" approach is the simplest way to achieve the intended result. Although if this is too frightening, there are some alternatives we can pursue to make this more palatable...
This is done by introducing a …
> Add SSC backend API Proxy

- internal/appliance/blobstore.go
- internal/appliance/config/config.go
- internal/appliance/development.md
- internal/appliance/repo_updater.go
- internal/appliance/repo_updater_test.go
- internal/appliance/symbols.go
- internal/appliance/testdata/golden-fixtures/blobstore-subsequent-disable.yaml
- internal/appliance/testdata/golden-fixtures/repo-updater-default.yaml
- internal/appliance/testdata/golden-fixtures/repo-updater-with-no-resources.yaml
- internal/appliance/testdata/golden-fixtures/repo-updater-with-pod-template-config.yaml
- internal/appliance/testdata/golden-fixtures/repo-updater-with-resources.yaml
- internal/appliance/testdata/golden-fixtures/repo-updater-with-sa-annotations.yaml
- internal/appliance/testdata/golden-fixtures/symbols-default.yaml
- internal/appliance/testdata/golden-fixtures/symbols-with-storage.yaml
- internal/appliance/testdata/sg/repo-updater-with-pod-template-config.yaml
- internal/k8s/resource/pod/BUILD.bazel
- internal/k8s/resource/pod/pod.go
User deployments may need to set image pull secrets for private
registries, and/or node selectors/tolerations/affinities for use with
custom node pools. These are supported for all services in the helm
chart. Embed this in standard config so that all services get this for
free.
This is part of a stack, needs rebase when base branch merges.
> appliance: pod template standard config

- client/web-sveltekit/src/lib/Scroller.svelte
- client/web-sveltekit/src/lib/repo/GitReference.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/all/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/all/+page.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/all/page.gql
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/tags/+page.svelte
Closes #61634
Similar to #62257. I copied most of the code because I assume we'll redesign those pages anyway, so there is no point spending time to make these components reusable.
I implemented it such that the content is centered and the scrollbar is at the right edge of the screen. I added some padding so that there is some space between edge and content on smaller screens (I made the same change to the tags page).
I also updated the `GitReference` component to use `Badge` instead, which also affects the tags page.
| ![2024-04-30_16-12](https://github.com/sourcegraph/sourcegraph/assets/179026/80214c8c-6ae5-4cb6-b72e-652e80416f35) | ![2024-04-30_16-13](https://github.com/sourcegraph/sourcegraph/assets/179026/69a3e69a-d612-40ac-8d4f-67b994f4d443) | …
> svelte: Add infinity scroll and search to all branches page.

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileViewModeSwitcher.svelte
A few minor CSS tweaks to the code/blame view switcher.
> Svelte: Minor visual tweaks to code-blame switcher

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/Picker.svelte
Minor update that tones down the hover color on hovering revision items on the revision picker.
Manually checked locally for visual changes.
> Svelte: Hover BG color updated on revision items in revision picker

- client/web-sveltekit/src/lib/Icon.svelte
- client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.svelte
- client/web-sveltekit/src/lib/search/resultsIndicator/ResultsIndicator.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/RepositoryRevPicker.svelte
- client/web-sveltekit/src/routes/search/PreviewPanel.svelte
This fixes an issue with the sizing of the `Icon` component. There was a `size` prop, but it wasn't actually being respected. Additionally, it stops relying on the global `.icon-inline` class.
This changes the `Icon` component to use only CSS variables to set its size. By default, it uses the `--icon-size` variable. If in `inline` mode, it uses the `--icon-inline-size` variable. 
Before:
After:
> Svelte: fix icon sizing

- wolfi-packages/p4-fusion-sg.yaml
- wolfi-packages/p4-fusion.yaml
This PR is a precursor to a second PR that will drop the shell layer in between gitserver and p4-fusion. We will be able to track command outputs and resource requirements separately, so there should be no need for this additional layer of complexity that could potentially mess with process groups and exit code forwarding etc.
Test plan:
This just bumps the package and simplifies the path, a follow-up PR will make use of this new epoch.
> Simplify path mapping of p4-fusion package

- dev/sg/msp/BUILD.bazel
- dev/sg/msp/helpers.go
- dev/sg/msp/repo/repo.go
- dev/sg/msp/sg_msp.go
Despite recent efforts to surface service options in `sg msp` commands better, such as https://github.com/sourcegraph/sourcegraph/pull/61620, it seems "what is a service argument" remains a point of confusion. It's not helped that some of the command help texts are not super helpful.
This change:
1. Adds explicit lists of available services in help text when we can get it
2. Improves service ID completion so that it works in any subdirectory in the managed-services repo
```sh
Projects/sourcegraph/managed-services » cd services
sourcegraph/managed-services/services » sg msp ops -h
NAME:
sg managed-services-platform operations - Generate operational reference for a service
USAGE:
sg msp ops [command options] <service ID>
DESCRIPTION:
Directly view operational reference documentation for a …
```
> sg/msp: add service lists to help text, improve completions

- cmd/gitserver/internal/git/gitcli/odb.go
- cmd/gitserver/internal/git/gitcli/odb_test.go
- cmd/gitserver/internal/git/iface.go
- cmd/gitserver/internal/git/mock.go
- cmd/gitserver/internal/git/observability.go
- internal/gitserver/gitdomain/errors.go
- internal/insights/gitserver/BUILD.bazel
- internal/insights/gitserver/first_commit.go
- internal/insights/gitserver/first_commit_test.go
Part of [#61689](https://github.com/sourcegraph/sourcegraph/issues/61689)
This PR adapts the existing FirstEverCommit logic from the gitserver client to our new git cli backend. This is the first step as part of a set of stacked PRs to port the functionality to gRPC.
Existing `func (c *clientImplementor) FirstEverCommit()` implementation for reference: 
https://github.com/sourcegraph/sourcegraph/blob/412654f098492856f32a6c561eda471800924d71/internal/gitserver/commands.go#L1734-L1757
One of the existing tests that I ported called out that code insights depended on the formatting of a specific error string in order to detect if the repository was empty.
(Test in question):
https://github.com/sourcegraph/sourcegraph/blob/948848bca6e87e84878a9c1a9222d36734103fa2/internal/gitserver/commands_tes …
> gitserver: port FirstEverCommit functionality from client to git cli backend

- CHANGELOG.md
- internal/gitserver/BUILD.bazel
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
- internal/insights/gitserver/first_commit.go
Closes https://github.com/sourcegraph/sourcegraph/issues/61689
This PR switches the gitserver client implementation to use the new gRPC FirstCommitEver() method introduced in https://github.com/sourcegraph/sourcegraph/pull/62169 instead of shoving it through the `exec()` endpoint.
Unit tests
> gitserver: grpc: switch clientImplementor to use new dedicated gRPC method for FirstEverCommit

- internal/insights/gitserver/first_commit.go
- internal/insights/gitserver/first_commit_test.go
https://github.com/sourcegraph/sourcegraph/pull/62165#discussion_r1584695272
CI
> codeinsights: remove now useless empty repo string error check

- dev/ci/internal/ci/release_operations.go
Pass the `IS_DEVELOPMENT` flag into the `sg` commands
> release: allow development flag in release ops

- dev/build-tracker/BUILD.bazel
- dev/build-tracker/config/config.go
- dev/build-tracker/main.go
As we're changing the devx metrics pipeline to checkout devx-service instead of sg/sg (as we've no need for sg/sg anymore, and do need to checkout devx-service to `bazel run`), we need to change up the values we set for buildtracker to trigger the build for due to it now checking out a different repo
Non-critical, will need to test live to see how a real system reacts to the values
> build-tracker: change trigger-build values for not checking out sg/sg

- client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
- client/web-sveltekit/src/lib/Timestamp.svelte
- client/web-sveltekit/src/lib/blame/BlameDecoration.svelte
- client/web/src/repo/blob/codemirror/blame-decorations.ts
Adds a few visual tweaks to the blame panel 
- Fixes padding problem with gutters in blame UI
- Removes blame avatars
- Fixes width for dates (making it monospace)
- Make the blame panel a bit smaller by width (ideally we should make it resizable I think, made it smaller because it takes almost all width on my mid-size screen)
| -------- | ------- |
| <img width="1102" alt="Screenshot 2024-04-30 at 13 53 28" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/d6804e91-6615-4195-b350-45b00636b6f1"> | <img width="1114" alt="Screenshot 2024-04-30 at 13 52 48" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/6c513ebe-7f73-48ac-a96d-fa14e019bfae"> |
- Check git blame panel, make sure it looks ok
- Check other code mirror editors like file preview …
> [Svelte]: Visual fixes for svelte blame panel

- .aspect/bazelrc/ci.sourcegraph.bazelrc
Rebase mistake reintroduced the BEP file in `common` :facepalm: https://github.com/sourcegraph/sourcegraph/commit/b5cf7b8ab4545101048b2abcc0fd8b6a7d832a65
Undoing change reintroduced by mistake
> ci: don't emit bep for non-test commands

- dev/build-tracker/BUILD.bazel
- dev/build-tracker/main.go
- dev/build-tracker/server_test.go
- internal/testutil/istest.go
This isnt exactly convenient lol
```
DEVX_TRIGGERED_FROM_BRANCH_URL="/tree/main"
DEVX_TRIGGERED_FROM_BUILD_ID="018f343b-5cfc-420c-9353-02821de45533"
DEVX_TRIGGERED_FROM_BUILD_NUMBER="271872"
DEVX_TRIGGERED_FROM_COMMIT="6d7082d26ee772be9cd3fd2b463c0f33a95ee7dc"
DEVX_TRIGGERED_FROM_COMMIT_URL="/commit/6d7082d26ee772be9cd3fd2b463c0f33a95ee7dc"
DEVX_TRIGGERED_FROM_PIPELINE_SLUG="sourcegraph"
DEVX_TRIGGERED_FROM_PR_NUMBER="0"
DEVX_TRIGGERED_FROM_PR_URL="/pull/0"
```
Live :letsgo:
> build-tracker: fix convenience urls in env

- doc/dev/security/secret_formats.md
Based on the spacing, I suspect this was done by an overly-helpful markdown table editor plugin :)
- Docs - rely on CI
> docs: Fix Sourcegraph Secret regex format

- client/web-sveltekit/src/lib/shared.ts
- client/web-sveltekit/src/routes/search/FileSearchResultHeader.svelte
Followup from https://github.com/sourcegraph/sourcegraph/pull/62246/files#r1583375607
Now that we don't style the file name differently than the rest of the path, this component can be simplified a bit.
Quick manual test.
> Svelte: simplify file header

- internal/codemonitors/background/workers.go
- internal/codemonitors/search.go
- internal/conf/computed.go
- internal/search/commit/commit.go
- internal/search/job/jobutil/exhaustive_job.go
- internal/search/job/jobutil/job.go
- schema/schema.go
- schema/site.schema.json
This adds a couple of configuration options which will allow us to tune the cost of code monitors in the event that we are seeing issues. It does not change the default values.
Tested that the conf validation works and that the intervals actually updated.
> Code monitors: add some levers for tuning resource usage

- client/web-sveltekit/src/lib/Tabs.svelte
- client/web-sveltekit/src/lib/repo/LastCommit.svelte
- client/web-sveltekit/src/routes/svelte-overrides.scss
Some of the previous base font-size changes have meant certain elements need application of smaller fonts and padding.
> Svelte: Visual update to history and reference bottom panel

- sg.config.yaml
When testing a change I hit issues debugging zoekt. @ggilmore showed me how we can plumb the proper debug flags to zoekt.  This seems like it would be generally useful for local development.
- Debugged locally and it all worked!
> Pass go debug flags to zoekt to enable better debugging

- client/web-sveltekit/src/lib/Commit.svelte
Just fixes a tiny issue where a null commit body will be rendered as "null" rather than just hidden.
> Svelte: hide commit body if null

- client/web-sveltekit/src/lib/LoadingSpinner.svelte
- client/web-sveltekit/src/lib/search/resultsIndicator/ResultsIndicator.svelte
- client/web-sveltekit/src/routes/search/SearchResults.svelte
- client/web-sveltekit/src/routes/search/StreamingProgress.svelte
This removes some extra padding from the progress indicator and also simplifies some of the padding so it's symmetrical and doesn't rely on adding padding together to get the right layout. 
Before: 
After:
> Svelte: compress progress indicator

- client/web-sveltekit/src/lib/search/resultsIndicator/ProgressMessage.svelte
- client/web-sveltekit/src/lib/search/resultsIndicator/ResultsIndicator.svelte
- client/web-sveltekit/src/lib/search/resultsIndicator/SuggestedAction.svelte
- client/web-sveltekit/src/routes/svelte-overrides.scss
Follow up to https://github.com/sourcegraph/sourcegraph/pull/62317
Locally tested for visual changes.
> Svelte: Font size tweaks for results indicator

- client/web-sveltekit/src/lib/repo/LastCommit.gql
- client/web-sveltekit/src/lib/repo/LastCommit.svelte
Currently we are using `name`, which seems generated. We should try `displayName` first before falling back to `name`.
| ![2024-05-01_22-42](https://github.com/sourcegraph/sourcegraph/assets/179026/f3a04def-0e0a-49f2-acaf-51087b72ffe7) | ![2024-05-01_22-43](https://github.com/sourcegraph/sourcegraph/assets/179026/4a7ca5b8-e159-4779-8211-0f5c7472708a) | 
> svelte: Fix user name in "last commit" message

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
I believe we used to do this, maybe there was a regression.
| ![2024-05-01_22-39](https://github.com/sourcegraph/sourcegraph/assets/179026/0f17d4a4-de62-4827-af0e-55c67dbf7989) | ![2024-05-01_22-38](https://github.com/sourcegraph/sourcegraph/assets/179026/f521519f-6835-4e3a-bcb9-1d56f343a455) | 
> svelte: Set max width for repo page

- cmd/symbols/gitserver/client.go
- internal/batches/sources/mocks_test.go
- internal/gitserver/BUILD.bazel
- internal/gitserver/client.go
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
- internal/gitserver/gitdomain/log.go
- internal/gitserver/mocks_temp.go
- internal/rockskip/BUILD.bazel
- internal/rockskip/server_test.go
We want to migrate this call to gRPC. However, it isn't good practice to have to keep this process running for potentially hours, as any server restart will have to make the process start over.
With pagination here, we're not occupying a process slot on gitserver, and rollouts of gitserver should much less affect rockskip, as individual pages can be retried before being returned to the rockskip code.
Test plan:
Existing tests still pass, but not a Rockskip expert so requesting review from the owners.
> rockskip: Switch from long-running process to pagination

- cmd/frontend/graphqlbackend/external_account.go
- cmd/frontend/internal/app/ui/router.go
- cmd/frontend/internal/cody/subscription.go
- cmd/frontend/internal/cody/subscription_test.go
- cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user_test.go
- cmd/frontend/internal/httpapi/ssc.go
- cmd/frontend/internal/ssc/ssc.go
This PR reworks the way we identify the SAMS or SSC backends from within the Sourcegraph instance. Previously the configuration setting was just a hostname (e.g. `accounts.sourcegraph.com` or `accounts.sgdev.org`.) However, this lead to us hard-coding the HTTPS scheme whenever the hostname was referenced.
This unfortunately makes it impossible(*) to test Sourcegraph locally when running against a SAMS or SSC backend running on `localhost`. Fortunately, we recently added new site config settings, that specify the full HTTP origin. (scheme, domain, and port) So if we use those newer values, things "just work".
The newer configuration values (`dotcom.codyProConfig.*`) are currently not set for sourcegraph.com, and are only used by the new code related to serving the SSC UI from …
> Use newer config settings if available (allow local SAMS/SSC dev)

- client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
- client/web-sveltekit/src/lib/repo/FileDiffHunks.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
- client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
- client/web-sveltekit/src/routes/search/SearchResult.svelte
- client/web-sveltekit/src/routes/svelte-overrides.scss
Colors manually tested locally.
> Svelte: Revert code bg changes

- dev/ci/internal/ci/images_operations.go
- dev/ci/internal/ci/release_operations.go
- dev/ci/push_all.sh
- tools/release/promote_images.sh
For cloud-ephemeral we want release also to be pushed to it's registry so that people launch ephemeral environments for releases.
This refactor the promotion script to handle handle additional registries. As a follow up a util func will be added to handle formating of the additional registries to ensure they're separated by a ` ` so that array splitting can happen.
Part of https://github.com/sourcegraph/sourcegraph/issues/61086
Tested locally
vars
```
export VERSION=6.6.666
export PUBLIC_REGISTRY='index.docker.io/sourcegraph-dev'
export ADDITIONAL_PROD_REGISTRY="us.gcr.io/sourcegraph-dev us.gcr.io/sourcegraph/cloud-ephemeral"
export INTERNAL_REGISTRY="us.gcr.io/sourcegraph/internal"
```
```
./tools/release/promote_images.sh gitserver
--- Copying gitserver from private registry to public …
```
> release: handle more registries for promotion

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
Apply slight styling to active items in the file tree.
Tested locally for visual change.
> Svelte: Highlight file/dir name on selected item in file tree.

- client/web-sveltekit/src/lib/Commit.svelte
I noticed that the autor and committer avatars have different sizes.
| ![2024-05-02_08-39](https://github.com/sourcegraph/sourcegraph/assets/179026/0417c753-509c-4810-aabd-d9527f564871) | ![2024-05-02_08-40](https://github.com/sourcegraph/sourcegraph/assets/179026/f81fd8a2-07b6-41f9-938a-b581dc5a5a12) | 
Manual testing
> svelte: Fix author avatar size on commit page

- client/web-sveltekit/src/lib/Popover.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/RepositoryRevPicker.svelte
Prior to this Popover trigger was used as the only option for the popover target, it didn't fit in the revision popover trigger case, when the target should be a group of buttons to avoid visual overlapping, but trigger still should be different button (not both buttons). 
This PR introduces new prop for Popover to split trigger and target elements.
| -------- | ------- |
| ![image](https://github.com/sourcegraph/sourcegraph/assets/18492575/636f9f6a-1eba-48b3-a6df-941baf8a6e84) | <img width="804" alt="Screenshot 2024-05-02 at 13 42 57" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/4d062bd8-80f3-4e8a-9516-e2852ca0757a"> |
- Check Repository Rev Popover position
> Svelte: Support custom position target for Popover element

- .bazelrc
- docker-images/syntax-highlighter/BUILD.bazel
- docker-images/syntax-highlighter/README.md
- docker-images/syntax-highlighter/crates/scip-syntax/src/io.rs
- docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
- docker-images/syntax-highlighter/crates/scip-syntax/tests/integration_test.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/src/ctags.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/src/globals.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/syntect_html.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/syntect_scip.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/src/languages.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/src/lib.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/testdata/ts-tags.rs
- docker-images/syntax-highlighter/src/bin/scip-ctags.rs
- docker-images/syntax-highlighter/src/lib.rs
This avoids unnecessary formatting changes in unrelated PRs.
> chore: Enable rustfmt

- client/web/src/components/fuzzyFinder/FuzzyModal.tsx
This PR updates the link of the experimental badge for the fuzzy finder, which used to target a now non-existent github discussion. It looks like discussions have been disabled on sourcegraph/sourcegraph. Instead we now link to the community forum.
Covered by FuzzyFinder.test.tsx
> fix: update link for fuzzyfinder feedback

- client/web-sveltekit/src/lib/repo/DiffSquares.svelte
- client/web-sveltekit/src/lib/repo/FileDiff.svelte
- client/web-sveltekit/src/lib/wildcard/CopyButton.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/page.gql
- client/web-sveltekit/src/routes/search/FileSearchResultHeader.svelte
- client/web-sveltekit/src/routes/search/SearchResult.svelte
- client/wildcard/src/components/Button/Button.module.scss
This adds some style and functionality improvements to the commit page.
Styling:
- Commit and parent SHAs as badges
- Increased avatar size
- Proper status badges (added, deleted, moved)
- Normal font weight for file paths
Behavior:
- Add copy button for commit SHAs
- Add a link to browse files at the commit
- Add links to open commit at code host
- Split changed lines into added and removed
Obviously there is more that can and should be done (e.g. adding split view), but it's a start.
| Type | Screenshot |
| dotcom/React (for reference) | ![2024-05-02_14-52](https://github.com/sourcegraph/sourcegraph/assets/179026/db099f02-8a93-4116-91d1-0c5c0ed83df6) |
| Before | ![2024-05-02_14-52_1](https://github.com/sourcegraph/sourcegraph/assets/179026/2e10b7ef-eeba-48f0-bd8d-f76 …
> svelte: Make several improvements to the commit page

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/DiffView.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
- client/web-sveltekit/src/routes/svelte-overrides.scss
Visual updates to the code blame header for increased readability and clarity. Plus shadows!
> Svelte: Code blame header visual update

- client/web-sveltekit/src/lib/Timestamp.test.ts
- client/web-sveltekit/src/lib/Tooltip.svelte
When I encountered #62372 I also noticed that the tooltip on the smaller avatar component is not positioned correctly. That's because the first element child does not contribute to the layout when the style prop is set, and thus doesn't have any dimensions.
I don't know how often we'll run into this situation but it seemed reasonable to make the component a bit more resilient for such cases. With this change we continue to look for (first child) elements that are part of the layout.
| ![2024-05-02_09-02](https://github.com/sourcegraph/sourcegraph/assets/179026/82d42042-87f4-4793-b38e-daabf3323888) | ![2024-05-02_09-02_1](https://github.com/sourcegraph/sourcegraph/assets/179026/465fb6fd-8138-47c3-9a54-7f3a5d83290d) | 
> svelte: Improve tooltip target logic

- cmd/frontend/shared/BUILD.bazel
- cmd/frontend/shared/shared.go
- internal/conf/BUILD.bazel
- internal/conf/init.go
- internal/httpcli/BUILD.bazel
- internal/httpcli/external.go
- internal/httpcli/init.go
- internal/httpcli/redis_logger_middleware.go
- internal/httpcli/redis_logger_middleware_test.go
- internal/service/svcmain/BUILD.bazel
- internal/service/svcmain/svcmain.go
There was a weird dependency between internal/conf and internal/httpcli because
of a cyclic import. This is resolved by using conftypes instead, so we can properly
split those concerns.
Test plan:
Existing tests don't break.
> httpcli: Move init function from conf package into httpcli

- internal/embeddings/client.go
We don't really use embeddings right now and this lets me encapsulate the factory better in the next PR, as this is the only external caller of NewInternalClientFactory.
Test plan:
CI still passes.
> embeddings: Use default InternalDoer

- internal/httpcli/client.go
Not used anymore outside of this package, and is in line with what we do for the external doer factory.
Test plan:
CI passes, go compiler doesn't complain.
> httpcli: Unexport internal client factory

- internal/httpcli/client.go
We return right above if err == nil, so this check is redundant.
Test plan:
CI passes, no change in behavior.
> httpcli: Remove useless err check

- cmd/gitserver/internal/git/gitcli/odb.go
- cmd/gitserver/internal/git/gitcli/odb_test.go
- cmd/gitserver/internal/git/iface.go
- cmd/gitserver/internal/git/mock.go
- cmd/gitserver/internal/git/observability.go
Part of https://github.com/sourcegraph/sourcegraph/issues/62101
This PR ports the GetBehindAhead implementation from the gitserver client to the new gitserver.Backend interface.
Here is the original implementation from the client for reference:
```go
// GetBehindAhead returns the behind/ahead commit counts information for right vs. left (both Git
// revspecs).
func (c *clientImplementor) GetBehindAhead(ctx context.Context, repo api.RepoName, left, right string) (_ *gitdomain.BehindAhead, err error) {
ctx, _, endObservation := c.operations.getBehindAhead.With(ctx, &err, observation.Args{
MetricLabelValues: []string{c.scope},
Attrs: []attribute.KeyValue{
repo.Attr(),
attribute.String("left", left),
attribute.String("right", right),
},
})
defer endObservation(1, observation.Args{})
if err := …
```
> gitserver: grpc: port GetBehindAhead from client to gitcli backend

- internal/codeintel/codenav/iface.go
- internal/codeintel/codenav/mocks_test.go
- internal/codeintel/codenav/service.go
- internal/codeintel/codenav/transport/graphql/iface.go
- internal/codeintel/codenav/transport/graphql/mocks_test.go
- internal/codeintel/codenav/transport/graphql/root_resolver.go
- internal/codeintel/resolvers/BUILD.bazel
- internal/codeintel/resolvers/codenav.go
- internal/codeintel/uploads/BUILD.bazel
- internal/codeintel/uploads/internal/background/backfiller/mocks_test.go
- internal/codeintel/uploads/internal/background/expirer/mocks_test.go
- internal/codeintel/uploads/internal/background/processor/mocks_test.go
- internal/codeintel/uploads/internal/store/commitgraph.go
- internal/codeintel/uploads/internal/store/commitgraph_test.go
- internal/codeintel/uploads/internal/store/store.go
- internal/codeintel/uploads/mocks_test.go
- internal/codeintel/uploads/service.go
- internal/codeintel/uploads/shared/BUILD.bazel
- internal/codeintel/uploads/shared/types.go
There are lots of layers of indirection/plumbing for propagating
the various options/settings for matching uploads. There was also
a mix of terminology - 'toolName' in some places and 'indexer'
in some other places. 'exactPath' in some places and 'rootMustEnclosePath'
in other places. Grouping the various options into a struct provides
a central place to document how the path matching happens,
as well as special arguments such as `shared.SyntacticIndexer`.
This also makes it much easier to understand where the various
upload matching options are used via 'Find usages' in the editor.
As a nice side-effect, the noise of creating o11y-related K-V pairs
is also reduced.
> chore: Group upload matching options into struct

- client/web-sveltekit/src/lib/repo/FileTable.svelte
- client/web-sveltekit/src/lib/repo/api/tree.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
| Before | Header |
| ![2024-05-03_08-36](https://github.com/sourcegraph/sourcegraph/assets/179026/abb587e5-2711-422d-8072-b921c10ce157) | ![2024-05-03_08-36_1](https://github.com/sourcegraph/sourcegraph/assets/179026/efccb3e3-9d84-4c8e-ae5b-f1a3a263d415) | 
Manual testing
> svelte: Use file icons on tree page

- client/web-sveltekit/src/lib/TreeView.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
At the moment the selected entry is scrolled to the top or bottom of the sidebar, where it is not always that visible.
This commit changes the behavior so that it it's scrolled to the center when the selected entry changes 'indirectly' (e.g. going back and forth via browser history buttons).
- Selected a new entry via mouse and keyboard -> sidebar doesn't move
- Scroll selected entry out of view, selected a new entry, press back button -> selected entry is centered
> svelte: Improve file sidebar's scroll into view behavior

- client/web-sveltekit/src/lib/Commit.svelte
Right now the button is visible and clickable, which gives the impression that it's broken.
I also updated the commit hash to use the new badge style while I was at it.
| ![2024-05-02_20-36](https://github.com/sourcegraph/sourcegraph/assets/179026/c3f77fb6-3013-4bcd-bfe8-7021e44ec3d8) | ![2024-05-02_20-35](https://github.com/sourcegraph/sourcegraph/assets/179026/593ef9ac-e617-4339-8293-333859cf2e90) | 
Visual inspection
> svelte: Hide commit message toggle button when there is no commit message

- dev/sg/internal/release/config.go
- dev/sg/internal/release/release.go
- release.yaml
[Context](https://sourcegraph.slack.com/archives/C05RRHSQ3QD/p1714558200079689?thread_ts=1714493051.206709&cid=C05RRHSQ3QD)
Since the introduction of the `--development` flag for creating development releases, we've made it possible to have more than one release with the same version, however one of them can't be promoted (the development release).
Since this is mostly for testing, 
> release: disable promotion of development release & add --development flag to baseFlags

- cmd/frontend/hubspot/contacts.go
- cmd/frontend/internal/app/ui/handlers.go
- cmd/frontend/internal/auth/oauth/session.go
- cmd/frontend/internal/auth/openidconnect/middleware.go
- cmd/frontend/internal/auth/openidconnect/user_test.go
- internal/auth/userpasswd/handlers.go
Updates to cookies sent to HubSpot on user signups on dotcom. Changing property names and eliminating certain fields.
Low risk change that only affects dotcom. Confirmed it compiled and ran locally. CI.
> Updates to cookies sent to HubSpot

- CHANGELOG.md
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
Closes https://github.com/sourcegraph/sourcegraph/issues/62101
This PR swaps the gitserver client implemenation of GetBehindAhead to use the new bespoke endpoint introduced in #62216 instead of the all-encompasing `exec` endpoint.
- Unit tests
> gitserver: grpc: swap client implementation of GetAheadBehind from Exec to bespoke gRPC endpoint

- cmd/gitserver/internal/git/gitcli/archivereader_test.go
- cmd/gitserver/internal/git/gitcli/blame_test.go
- cmd/gitserver/internal/git/gitcli/command.go
- cmd/gitserver/internal/git/gitcli/diff_test.go
- cmd/gitserver/internal/git/gitcli/exec_test.go
- cmd/gitserver/internal/git/gitcli/odb_test.go
- cmd/gitserver/internal/git/gitcli/refs_test.go
- cmd/gitserver/shared/shared.go
This PR makes a change to how we spawn git processes, it puts them in separate process groups. This will allow us to track maxRSS reliably, and also lets us handle context cancellations a bit nicer; we can now 
- trigger a SIGTERM first for a more graceful shutdown
- later send a SIGKILL if that doesn't stop the process
- and make sure subprocesses are also always properly killed, by killing the group and not just the parent process
We've done a bit of back and forth here on Slack before on whether this has any other unintended side-effects, but the parent ID is untouched so the worst that could happen is that someone kills the process group where gitserver runs and the git processes aren't properly shut down by that. The pipes will break though so that should propagate quite okay.
In a …
> gitserver: Improve signal handling and maxRSS reporting

- doc/admin/observability/dashboards.md
- monitoring/definitions/shared/gitserver.go
Turns out I blindly copy-pasted this from elsewhere and the graphs always said
GraphQL operations, which is wrong and confused people.
Test plan:
Reads better now.
> gitserver: Fixup confusing label on monitoring dashboard

- cmd/gitserver/internal/git/gitcli/command.go
This doesn't work on linux, so turning off the noise.
Test plan:
CI.
> gitserver: Temporarily disable highmem reporting

- cmd/frontend/graphqlbackend/oobmigrations.go
- internal/oobmigration/runner.go
```
[         worker] 2024/05/03 18:51:35 goroutine panic: runtime error: invalid memory address or nil pointer dereference
[         worker] goroutine 948 [running]:
[         worker] runtime/debug.Stack()
[         worker]       /Users/erik/.asdf/installs/golang/1.22.1/go/src/runtime/debug/stack.go:24 +0x64
[         worker] github.com/sourcegraph/sourcegraph/lib/background.Go.func1.1()
[         worker]       /Users/erik/Code/sourcegraph/sourcegraph/lib/background/goroutine.go:19 +0x3c
[         worker] panic({0x105db5660?, 0x108af16d0?})
[         worker]       /Users/erik/.asdf/installs/golang/1.22.1/go/src/runtime/panic.go:770 +0xf0
[         worker] github.com/sourcegraph/sourcegraph/internal/oobmigration.(*Runner).Start.func1({0x17, {0x14002509260, 0xd}, {0x14002c864b0, 0x17}, …
```
> bug/release: Add nil check for undeprecated oob migrations

- client/web-sveltekit/src/lib/Popover.svelte
- client/web-sveltekit/src/routes/styles.scss
@fkling catch that now popover hides too fast when we use it with on hover mode because of standard non-zero offset. This PR just removes offset when the popover is used with onHover mode
- Check popover appearance manually
> [Svelte]: Fix popover onHover mode

- internal/appliance/repo_updater.go
- internal/appliance/symbols.go
- internal/appliance/testdata/golden-fixtures/symbols-default.yaml
- internal/appliance/testdata/golden-fixtures/symbols-with-storage.yaml
- internal/k8s/resource/container/container.go
- internal/k8s/resource/pvc/pvc.go
**appliance: use extracted redis/otel env vars everywhere**
**appliance: symbols: fix PVC name**
We need to set volumeClaimTemplates.metadata.name, and create a volume
mount with matching name, in order for k8s to actually mount the PVC at
the container's volumeMount.
> appliance: symbols: fix PVC name

- internal/completions/client/anthropic/anthropic.go
- internal/completions/client/awsbedrock/bedrock.go
- internal/completions/client/openai/openai.go
- internal/completions/tokenusage/tokenusage.go
Thanks to @rafax 
Next Steps:
- Try to make it work in Azure too(It didn't work in my tiny experiments)
- If you can't make something similar work in azure then write a separate tokenizer for azure
Tested locally with the entire debugger environment
> Fixing OpenAI TokenUsage to replace internally implemented token counter with openai response

- client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
- client/web-sveltekit/src/lib/repo/FileHeader.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/DiffView.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
- client/web-sveltekit/src/routes/svelte-overrides.scss
Shadow fixes and other minor styling adjustments to optimise for smaller screens.
> Svelte: Calm down shadows and strip down blame header

- client/web-sveltekit/src/routes/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FilePreview.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
- client/web-sveltekit/src/routes/search/+page.svelte
- client/web-sveltekit/src/routes/search/SearchResults.svelte
Closes #62429 
I originally thought we have to create the page title in data loaders and set it only in the root layout, but it appears that setting the title in the layout files is what's potentially problematic (sometimes the page title "reverts" to what's being set by the root layout when navigating to a new page).
Only setting the page title in `+page.svelte` files seems to solve the issue. At least for now I prefer that because it makes setting the page title very explicit and consistent.
I also changed the file preview logic to use the (newly refactored) component instead of the page component. Otherwise opening the preview updates the page title, which is not correct.
Note: One might think that having the title set in loaders would allow
us to "compose" the title hierarchically …
> svelte: Improve page title updates

- client/web-sveltekit/src/lib/Commit.svelte
- client/web-sveltekit/src/lib/search/input/SearchInput.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/page.gql
- client/web-sveltekit/vite.config.ts
This commit makes several changes to the commits page:
- Adds link to browsing files at this commit
- Adds link to open commit on code host
- Better layout for smaller screens
- Fix issue where loading indicator or error are not visible when the page is loaded with a file path (due to additional header)
- The 'open commit' link was moved from the `Commits` component to the commits page because it was only used there and it was not obvious that is controlled by the `alwaysExpanded` prop.
Additionally the way we load custom breakpoints was changed. Usually those need to be imported into every stylesheet, but the Svelte language server generates an error for `@use '$lib/breakpoints';`  (at least for me), which prevents other warnings like unused classes to be reported (I've tried various …
> svelte: Improve utility of commits page

- dev/sg/internal/cloud/BUILD.bazel
- dev/sg/internal/cloud/client.go
- dev/sg/internal/cloud/common.go
- dev/sg/internal/cloud/delete_command.go
- dev/sg/internal/cloud/deploy_command.go
- dev/sg/internal/cloud/instance.go
- dev/sg/internal/cloud/lease_command.go
- dev/sg/internal/cloud/list_command.go
- dev/sg/internal/cloud/list_versions_command.go
- dev/sg/internal/cloud/printers.go
- dev/sg/internal/cloud/status_command.go
- dev/sg/sg_cloud.go
Add `sg cloud lease` with the following flags to alter the deployment expiry time
* `--extend` extend the duration by golang parseable duration
* `--reduce` reduce the duration by golang parseable duration
* `--expire-now` sets the expire time to be now
Tested locally
```
go run ./dev/sg cloud lease --name "ff-eph17" --reduce "1h"
🧪 EXPERIMENTAL COMMAND - Do you want to continue? (yes/no) y
☁️ Fetched instance with name "ff-eph17"
Updating instance lease with the following values:
- Lease time 2024-05-03T21:00:59Z
+ Lease time 2024-05-03T20:00:59Z
☁️ Lease of instance "ff-eph17" extended by 1h0m0s
```
```
go run ./dev/sg/ cloud lease --name wb-sg-cloud-eph-delete --expire-now
🧪 EXPERIMENTAL COMMAND - Do you want to continue? (yes/no) y
☁️ Fetched instance with name …
```
> sg: cloud handle ephemeral lease extension/reduction

- dev/sg/internal/release/config.go
Fixes https://buildkite.com/sourcegraph/sourcegraph/builds/272793#018f4e91-24e0-480c-8926-460f1b728c14/180-208
Locally tested
> chore(rel): fix wrong stage name when checking reqs

- dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
- dev/managedservicesplatform/spec/service.go
- dev/managedservicesplatform/stacks/monitoring/monitoring.go
- dev/sg/msp/sg_msp.go
With https://github.com/sourcegraph/sourcegraph/pull/62325 landed, this updates a few references:
1. Service golinks don't work anymore: CORE-105
3. Alerts docs now point to the service handbook page
CI
> msp: update msp-ops links

- lib/managedservicesplatform/runtime/BUILD.bazel
- lib/managedservicesplatform/runtime/contract/BUILD.bazel
- lib/managedservicesplatform/runtime/contract/contract.go
- lib/managedservicesplatform/runtime/contract/diagnostics.go
- lib/managedservicesplatform/runtime/service.go
Allows services to adopt Sentry integration without buying into `runtime` entirely, similar to #61488 
n/a, just some minor refactoring
> msp/runtime: make Sentry contract integration usable without runtime

- cmd/executor/internal/worker/runtime/kubernetes.go
- cmd/executor/internal/worker/runtime/kubernetes_test.go
This fixes an issue that is generating failures on repos with spaces in their names.
Previously, we were passing the script name as a shell command with `-c`. However, that means it's subject to shell escaping. If we instead pass the file as a script for `sh` to run, it avoids the need to escape the file name and also reduces the surface area for injection attacks.
[Slack thread](https://sourcegraph.slack.com/archives/C02MR5PPMKJ/p1714772085831219)
Updated unit tests. I still want to test this end-to-end, but I'm struggling to get this all built and running locally, so I'm just going to test the image after-merge. It's a very small, high-confidence change, so I'm not terribly worried.
> Executors: run script as script, not as command

- internal/appliance/blobstore.go
- internal/appliance/config/config.go
- internal/appliance/defaults.go
- internal/appliance/gitserver.go
- internal/appliance/repo_updater.go
- internal/appliance/spec.go
- internal/appliance/standard_config_test.go
- internal/appliance/symbols.go
- internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-no-resources.yaml
- internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-resources.yaml
- internal/appliance/testdata/golden-fixtures/standard/symbols-with-custom-image.yaml
- internal/appliance/testdata/sg/standard/repo-updater-with-no-resources.yaml
- internal/appliance/testdata/sg/standard/repo-updater-with-resources.yaml
- internal/appliance/testdata/sg/standard/symbols-with-custom-image.yaml
- internal/k8s/resource/container/BUILD.bazel
- internal/k8s/resource/container/container.go
**appliance: refactor container config**
In preparation for adding a field for image overrides, move the
resources section into a new ContainerConfig field, to avoid cluttering
the top-level interface.
**appliance: container image config**
Add image defaults and overrides similar to the helm chart: we hardcode
our standard image repository and version-specific tags for each
component as defaults. We expose per-service overrides of the image and
its tag (although _not_ qualified by repository), and a global override
for the repository.
This commit does not support per-service overrides of the repository,
although this is something we could add in the future if there is
demand.
The appliance will need to support a range of SG versions. This commit
adds the beginnings of the scaffolding for …
> appliance: container image config

- internal/appliance/golden_test.go
- internal/appliance/kubernetes.go
- internal/appliance/testdata/golden-fixtures/blobstore/default.yaml
- internal/appliance/testdata/golden-fixtures/gitserver/default.yaml
- internal/appliance/testdata/golden-fixtures/gitserver/with-storage.yaml
- internal/appliance/testdata/golden-fixtures/repo-updater/default.yaml
- internal/appliance/testdata/golden-fixtures/standard/blobstore-subsequent-disable.yaml
- internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-no-resources.yaml
- internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-pod-template-config.yaml
- internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-resources.yaml
- internal/appliance/testdata/golden-fixtures/standard/repo-updater-with-sa-annotations.yaml
- internal/appliance/testdata/golden-fixtures/standard/symbols-with-custom-image.yaml
- internal/appliance/testdata/golden-fixtures/symbols/default.yaml
- internal/appliance/testdata/golden-fixtures/symbols/with-storage.yaml
Fix a bug in which ownerReferences were not being set on new objects created by the appliance. This meant that kubernetes garbage collection did not trigger (when the configmap is deleted, we expect owned objects to also be deleted).
envtest doesn't actually perform k8s GC, but the golden tests validate that the ownerReferences are in the expected place. I have manually tested the appliance against a real k8s instance to validate our model of how ownerReferences / GC works.
When we have e2e smoke tests against a "real" kube, not just envtest, we should be able to test this more behaviourally if we wish.
> appliance: fix owner references for new objects

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
Prior to this PR, it was possible to see this incorrect state when the bottom panel collapsed but some of the action tabs were selected
This happened because users' panels without saved layout in their local storage tried to calculate an initial layout automatically, and, despite the fact that the bottom panel has default size 1 (which is equal to its collapsed size 1), instead, it got a 1.09... value because the content panel had 90 as a default size and the rest space was distributed proportionally. 
So what we got at the end is 
- Content panel has 98.91... size
- Bottom panel has 1.09... size 
- Resize panels logic sees that panel has a bigger size than its collapsed size and fires onExpand callback 
- This callback set History tab selected
- As a result, a visually collapsed panel …
> [Svelte]: Fix default blob page panel distribution

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/all/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/tags/+page.svelte
- cmd/frontend/internal/app/ui/sveltekit/routes.go
(in preparation for the S2 rollout)
This commit enables the following routes via the `web-next-rollout` flag:
- repo home
- blob
- file
- branches
- tags
- commits
- commit
Question: Should we also enable the contributors page by default? It would be the only page left but it didn't receive any attention.
Inspected generated code.
> svelte: Enable repo routes by default

- WORKSPACE
- dev/schema_migrations.bzl
- internal/database/migration/shared/data/cmd/generator/consts.go
- internal/database/migration/shared/data/stitched-migration-graph.json
This PR does two things: 
- Bumps the minor number for the last manual bit for stitch graph
- Adds a new attribute on the `repository_rule` for fetching the migrations on GCS, as otherwise, it would just skip it unless you clear your cache, which could have dire consequences in CI. 
Locally tested (saw the invalidation)
Stitch graph will checked through review.
> chore(rel): bump minor for stitch graph + add support invalidating migrations repo rule

- internal/completions/client/fireworks/fireworks.go
1. Change the fine-tuned model for completions.
```
curl -vS -X POST http://localhost:9992/v1/completions/fireworks -H 'Authorization: bearer <SGD_TOKEN>' -d '{"stream":false,"max_tokens":50, "model": "accounts/sourcegraph/models/codecompletion-mixtral-rust-152k-005e", "stop_sequences": ["\n\n"], "prompt": "const value = ", "stream":false}' -H 'X-sourcegraph-feature: code_completions'
```
> Cody PLG: Change fine-tuned model identifier for completions

- release.yaml
@Chickensoupwithrice I completely missed that at review time, the annotation code was added on the `create` and `promote` steps, which are run locally and not in CI. 
Tested over https://buildkite.com/sourcegraph/sourcegraph/builds/273082
> chore(rel): remove broken annotation code

- release.yaml
earlier today, we ran into an issue 
Where the command to set the Git SHA when creating a release wasn't interpolating the GIT_SHA from Buildkite properly.
Local testing using a snippet and running it.
> release: wrap interpolated value with single quote

- cmd/gitserver/internal/server_grpc_logger.go
- internal/batches/sources/mocks_test.go
- internal/gitserver/client.go
- internal/gitserver/client_test.go
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
- internal/gitserver/mocks_temp.go
- internal/gitserver/observability.go
Part of https://github.com/sourcegraph/sourcegraph/issues/60654
This PR builds on https://github.com/sourcegraph/sourcegraph/pull/62216, and creates a new ChangedFiles method in the gitserver client that calls the new gRPC method that was introduced in https://github.com/sourcegraph/sourcegraph/pull/62216.
Note: This PR doesn't change / remove any existing callers of DiffSymbols. I made those changes in future stacked PRs to ensure that they're easy to review. 
New Unit tests
> gitserver: grpc: add new ChangedFiles method to gitserver client

- cmd/symbols/fetcher/BUILD.bazel
- cmd/symbols/fetcher/mocks_test.go
- cmd/symbols/gitserver/BUILD.bazel
- cmd/symbols/gitserver/client.go
- cmd/symbols/gitserver/client_test.go
- cmd/symbols/gitserver/observability.go
- cmd/symbols/internal/api/BUILD.bazel
- cmd/symbols/internal/api/mocks_test.go
- cmd/symbols/internal/database/writer/BUILD.bazel
- cmd/symbols/internal/database/writer/writer.go
- internal/gitserver/commands.go
Part of https://github.com/sourcegraph/sourcegraph/issues/60654
This PR builds on the new ChangedFiles method introduced in https://github.com/sourcegraph/sourcegraph/pull/62354, and changes the symbols service to use it instead of the old custom diff symbols method.
Existing CI pipeline
> symbols: replace usage of gitserver client's DiffSymbols method with new ChangedFiles method

- cmd/searcher/internal/search/BUILD.bazel
- cmd/searcher/internal/search/hybrid.go
- cmd/searcher/internal/search/hybrid_test.go
- cmd/searcher/internal/search/search.go
- cmd/searcher/shared/shared.go
Part of https://github.com/sourcegraph/sourcegraph/issues/60654
This PR replaces hybrid's search use of the gitserver.DiffSymbols endpoint with the new gitserver.ChangedFiles gRPC endpoint introduced in https://github.com/sourcegraph/sourcegraph/pull/62354.
Existing CI pipeline
> searcher: replace usage of gitserver.DiffSymbols with new gitserver.ChangedFiles client method

- cmd/worker/internal/embeddings/repo/BUILD.bazel
- cmd/worker/internal/embeddings/repo/handler.go
- cmd/worker/internal/embeddings/repo/handler_test.go
Part of https://github.com/sourcegraph/sourcegraph/issues/60654
This PR replaces the worker embedding job's use of the old gitserver.DiffSymbols endpoint with the gitserver.ChangedFiles gRPC endpoint introduced in #62354.
Existing CI
> worker: embeddings: replace usage of old gitserver.DiffSymbols client method with new gitserver.ChangedFiles method

- cmd/frontend/internal/app/jscontext/jscontext.go
When addressing the PR feedback for a recent change I merged https://github.com/sourcegraph/sourcegraph/pull/62322, I didn't account for a `nil`-check that was in an earlier rev of the code. (😓)
We shouldn't assume that the `codyProConfig` setting is available if we are running in "dotcom mode".
CI/CD
> Fix panic on startup

- CHANGELOG.md
- internal/batches/sources/mocks_test.go
- internal/gitserver/client.go
- internal/gitserver/commands.go
- internal/gitserver/mocks_temp.go
Closes https://github.com/sourcegraph/sourcegraph/issues/60654
This PR removes  the (now unused) DiffSymbols method from the gitserver client.
CI
> gitserver: grpc: remove now unused DiffSymbols func

- cmd/frontend/internal/telemetry/resolvers/BUILD.bazel
- cmd/frontend/internal/telemetry/resolvers/resolvers.go
- cmd/frontend/internal/telemetry/resolvers/telemetrygateway.go
I've added Sentry rule for the current scope `enterprise.telemetry` to go to #alerts-telemetry-gateway-prod
CI
> telemetry/resolvers: improve logging on RecordEvents errors

- deps.bzl
- go.mod
- go.sum
- internal/conf/computed.go
- internal/search/backend/metered_searcher.go
- internal/search/types.go
- internal/search/types_test.go
- https://github.com/sourcegraph/zoekt/commit/69068bff5b zoekt-mirror-gerrit: add an option to fetch meta/config branch
- https://github.com/sourcegraph/zoekt/commit/647e86c96a zoekt-indexserver: handle gerrit-mirror RepoNameFormat config
- https://github.com/sourcegraph/zoekt/commit/7c5b77843b gitindex: update remote.origin.url if clone already exists
- https://github.com/sourcegraph/zoekt/commit/9f35cb185d zoekt-mirror-gerrit: fix fetch for meta/config
- https://github.com/sourcegraph/zoekt/commit/4e674a4979 Rename UseKeywordScoring to mention BM25
Covered by CI
> gomod: Bump zoekt for UseKeywordScoring rename

- wolfi-images/batcheshelper.lock.json
- wolfi-images/blobstore.lock.json
- wolfi-images/bundled-executor.lock.json
- wolfi-images/caddy.lock.json
- wolfi-images/cadvisor.lock.json
- wolfi-images/cloud-mi2.lock.json
- wolfi-images/executor-kubernetes.lock.json
- wolfi-images/executor.lock.json
- wolfi-images/gitserver.lock.json
- wolfi-images/grafana.lock.json
- wolfi-images/jaeger-agent.lock.json
- wolfi-images/jaeger-all-in-one.lock.json
- wolfi-images/node-exporter.lock.json
- wolfi-images/opentelemetry-collector.lock.json
- wolfi-images/postgres-exporter.lock.json
- wolfi-images/postgresql-12-codeinsights.lock.json
- wolfi-images/postgresql-12.lock.json
- wolfi-images/prometheus.lock.json
- wolfi-images/redis-exporter.lock.json
- wolfi-images/redis.lock.json
- wolfi-images/repo-updater.lock.json
- wolfi-images/search-indexer.lock.json
- wolfi-images/searcher.lock.json
- wolfi-images/server.lock.json
- wolfi-images/sourcegraph-base.lock.json
- wolfi-images/sourcegraph-dev.lock.json
- wolfi-images/sourcegraph-template.lock.json
- wolfi-images/symbols.lock.json
- wolfi-images/syntax-highlighter.lock.json
Automatically generated PR to update package lockfiles for Sourcegraph base images.
Built from Buildkite run [#272971](https://buildkite.com/sourcegraph/sourcegraph/builds/272971).
- CI build verifies image functionality
> Auto-update package lockfiles for Sourcegraph base images

- dev/linearhooks/internal/handlers/handlers.go
- dev/linearhooks/internal/handlers/handlers_test.go
Previously, there were two similarly named functions
moveToNewTeam and moveIssueToTeam, this renames the first
one to identifyTeamToMoveTo
> chore: Rename function to reduce confusion

- internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
- internal/codeintel/codenav/internal/lsifstore/store.go
- internal/codeintel/codenav/service.go
Looks like I missed removing this usage of 'dump' here.
n/a
> chore: Rename locals id -> uploadID, dump -> upload

- internal/codeintel/codenav/BUILD.bazel
- internal/codeintel/codenav/service.go
- internal/codeintel/codenav/service_closest_uploads_test.go
Fixes GRAPH-563
The upload filtering code previously did checks whether:
- The commit corresponding to the upload actually existing on gitserver
- The path of interest had an associated SCIP document in that upload.
However, the second code path incorrectly only handled the case when
the first operation was a no-op. Consequently, it was possible to have
the following:
- Some uploads were filtered out due to the path not existing in the
wrong upload (not itself)
- Some uploads were not filtered out due to the path existing in the
wrong upload (not itself)
This PR is broken up into three commits.
- The first commits adds a negative test for the bug (I've triggered CI)
- The second commit simply adds comments related to aliasing to help
reason with the code and better understand the bug.
- …
> fix: Correctly filter uploads with commit and path existence checks

- client/web-sveltekit/src/lib/repo/DiffSquares.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/DiffSummaryHeader.svelte
- client/web/src/components/diff/DiffStat.module.scss
Minor visual change for diff summary.
Visual change tested locally.
> Svelte: Visual updates to diff summary

- client/web-sveltekit/src/lib/Commit.svelte
- client/web-sveltekit/src/lib/Icon.svelte
- client/web-sveltekit/src/lib/TreeNode.svelte
- client/web-sveltekit/src/lib/TreeView.stories.svelte
- client/web-sveltekit/src/lib/breakpoints.scss
- client/web-sveltekit/src/lib/repo/DiffSquares.svelte
- client/web-sveltekit/src/lib/search/SyntaxHighlightedQuery.svelte
- client/web-sveltekit/src/lib/search/input/SuggestionOption.svelte
- client/web-sveltekit/src/lib/styles/breakpoints.scss
- client/web-sveltekit/src/lib/styles/dropdown.scss
- client/web-sveltekit/src/lib/styles/popover.scss
- client/web-sveltekit/src/lib/styles/utilities.scss
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/all/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/stats/contributors/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
- client/web-sveltekit/src/routes/search/CommitSearchResult.svelte
- client/web-sveltekit/src/routes/search/PersonSearchResult.svelte
- client/web-sveltekit/src/routes/search/RepoSearchResult.svelte
- client/web-sveltekit/src/routes/search/StreamingProgress.svelte
- client/web-sveltekit/src/routes/search/TeamSearchResult.svelte
- client/web-sveltekit/src/routes/styles.scss
- client/web-sveltekit/vite.config.ts
Part of [#62428](https://github.com/sourcegraph/sourcegraph/issues/62428)
Until now we've simply imported the global `base.scss` file, which in turn imports a bunch of other files and defines global CSS classes. Many (most?) of them are actually not used.
This commit reduces to the number of imported files to the ones that contain styles that are used. My methodology was to inspect every file that `base.scss` imports and find out whether it defines custom properties (variables) or global classes. In some cases I extracted variables into their own files.
I can't guarantee that the included files only declare styles that are used, but it's a first step.
Compared all pages "side-by-side", switching between S2 and local tabs to catch any "drift", including the revision selector, search …
> svelte: Reduce imported global CSS

- .aspect/bazelrc/ci.sourcegraph.bazelrc
Misleading, this flag is overwritten by aspect workflows rosetta
CI
> chore: remove overridden repository cache flag from bazelrc

- dev/sg/internal/release/config.go
When a release is a development release, we should error out and inform them that promotion isn't possible.
Erroring out ensures no other step runs in the CI
> release: return an error when promoting a dev release

- client/web/src/cody/useCodyIgnore.tsx
Occasionally, Firefox cancels `ContextFilters` requests, resulting in an `NS_BINDING_ABORTED` error. This error can lead to inconsistent query results. To ensure that the Cody context filters values on the client remain up-to-date, this change modifies the fetch policy from the default `cache-first` to `cache-and-network`.
- CI
> Cody Ignore: use "cache-and-network" fetch policy for context filters query

- release.yaml
The introduction of the is_development field makes this logic wrong as we can now have multiple versions of a product in the release registry, albeit with different is_development values.
Plan is to fix this after the current release.
Manual testing
> release: disable promotion criteria validation

- internal/rockskip/server.go
- internal/rockskip/server_test.go
Adds a test for the ruler function and simplifies the function to remove tail
recursion.
A tiny warm-up as we work on improving Rockskip test coverage.
Added new test case.
> Rockskip: simplify ruler function

- client/web-sveltekit/src/lib/TreeNode.svelte
- client/web-sveltekit/src/lib/repo/api/tree.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/fileTreeStore.ts
While working on #62494 I noticed that the file tree didn't work as expected.
In particular, when being at the repo root and navigating to a file via the fuzzy finder the file tree would  switch to the parent directory, just like as if the file was directly navigated to.
However, what should happen is that the tree expands all directories to reveal the file, because the repo root is the top level directory and we should always be showing the most top level directory that was visited.
The issue is that we are not properly detecting the repo root level (I think we switched from using `'.'` to `''` at some point). To avoid this problem I'm now using a constant instead.
I also changed how the tree entries are scrolled into view. The current solution doesn't work for deeply nested entries …
> svelte: Fix file tree behavior

- internal/codeintel/codenav/iface.go
- internal/codeintel/codenav/transport/graphql/iface.go
- internal/codeintel/uploads/internal/store/store.go
- internal/codeintel/uploads/internal/store/util.go
I tried to change the types to reflect this post-condition
at the type-level in https://github.com/sourcegraph/sourcegraph/pull/62528, but ran into
problems with the available OrderedMap types, so just documenting
this in a comment for now.
n/a
> chore: Document post-condition for upload matching

- cmd/frontend/graphqlbackend/BUILD.bazel
- cmd/frontend/graphqlbackend/repository_contributors.go
- internal/database/BUILD.bazel
- internal/database/helpers.go
- internal/database/helpers_test.go
This allows usage of the function in places other than
the graphqlbackend package.
> chore: Move helper function to database package

- internal/codeintel/codenav/service.go
Other usages in the file use `s`.
> chore: Make receiver names consistent in codenav/service.go

- release.yaml
We didn't pass the `IS_DEVELOPMENT` env to buildkite which caused a failure when running release tests.
> release: pass in `IS_DEVELOPMENT_RELEASE` flag to buildkite

- client/web-sveltekit/BUILD.bazel
- client/web-sveltekit/package.json
- client/web-sveltekit/src/lib/Hotkey.ts
- client/web-sveltekit/src/lib/Tabs.svelte
- client/web-sveltekit/src/lib/TabsHeader.svelte
- client/web-sveltekit/src/lib/fuzzyfinder/FuzzyFinder.gql
- client/web-sveltekit/src/lib/fuzzyfinder/FuzzyFinder.svelte
- client/web-sveltekit/src/lib/fuzzyfinder/FuzzyFinderContainer.svelte
- client/web-sveltekit/src/lib/fuzzyfinder/keys.ts
- client/web-sveltekit/src/lib/fuzzyfinder/sources.ts
- client/web-sveltekit/src/lib/web.ts
- client/web-sveltekit/src/lib/wildcard/Input.svelte
- client/web-sveltekit/src/routes/+layout.svelte
- client/web/src/search/autocompletion/source.ts
- package.json
- pnpm-lock.yaml
Part of #62426
This commit adds a first version of the fuzzy finder. To get things moving quickly I'm using the same mechanism to fetch data as the search input.
Supported features:
- Repos, symbols, files search
- Automatic scoping of files and symbol search to current repository
- Activting search modes via keyboard shortcuts
- Keyboard support
Not yet supported:
- "All" search
- Result counts
- Scope toggle (i.e. search all files even when inside repository)
- Full a11y support
- Take into account visited repos/files
- Introduced separate tab headers component. In this case I wanted to reuse the same panel/UI and only change the data source.
- Added a function for formatting keyboard shortcuts that work with our hotkey implementation.
Follow up work:
- Cleanup and …
> svelte: First pass on fuzzy finder

- dev/linearhooks/config.example.yaml
- dev/linearhooks/internal/handlers/BUILD.bazel
- dev/linearhooks/internal/handlers/config.go
- dev/linearhooks/internal/handlers/handlers.go
- dev/linearhooks/internal/handlers/handlers_test.go
- dev/linearhooks/internal/lineargql/generated.go
- dev/linearhooks/internal/lineargql/gqltest/gqltest.go
- dev/linearhooks/internal/lineargql/operations.graphql
https://sourcegraph.slack.com/archives/C06GAS7FUGL/p1715062692858249
implements a `modifier` spec so we can override the project when moving the issue to another team
added tests and manual testing.
> dev/linearhooks: add support for project modifier

- internal/appliance/gitserver.go
Fix minor deprecation when calling the `intstr` pkg.
Previous tests apply
> fix: deprecation in pkg call

- dev/sg/generates.go
The command accepts `buf.gen.yaml` files, but the current completion provides generated Go files instead. The output is also provided in absolute-path format, which is difficult to read. This change addresses both issues, though the completion is a bit slow still.
Before (incorrect completions):
After (✅):
```sh
go build -o ./sg ./dev/sg && ./sg install -f -p=false # install globally
```
Running `sg gen buf` against some of the suggested targets works as expected
> sg gen buf: fix completions

- dev/sg/internal/cloud/BUILD.bazel
- dev/sg/internal/cloud/build_command.go
- dev/sg/internal/cloud/client.go
- dev/sg/internal/cloud/deploy_command.go
- dev/sg/internal/cloud/lease_command.go
- dev/sg/internal/cloud/list_command.go
- dev/sg/internal/cloud/list_versions_command.go
- dev/sg/internal/cloud/status_command.go
- dev/sg/internal/cloud/upgrade_command.go
- dev/sg/internal/repo/git_repo.go
- dev/sg/sg_cloud.go
There are times when you just want to create a cloud ephemeral deployment. Previously the only way to get a ephemeral build would've been to run `sg cloud deploy` and then get a deployment failure because a deployment already exists.
In this PR we add:
```
go run ./dev/sg cloud build
🧪 EXPERIMENTAL COMMAND - Do you want to continue? (yes/no) y
✅ Build 273307 created. Build progress can be viewed at https://buildkite.com/sourcegraph/sourcegraph/builds/273307
The build will push images with the following tag/version:  wb-sg-cloud-upgrade_273307_2024-05-08_5.3-6d0d9eac5838
Once this build completes, you can:
• create a deployment with this build by running  sg cloud deploy --version wb-sg-cloud-upgrade_273307_2024-05-08_5.3-6d0d9eac5838
• upgrade the existing deployment with this build by …
```
> sg: cloud ephemeral - add build and upgrade commands

- dev/ci/images/go.mod
- dev/ci/internal/ci/images_operations.go
- dev/ci/internal/ci/release_operations.go
This allows internal and promoted releases to also publish images to the Cloud Ephemeral registry
CI + the push all script was previously tested to handle multiple registries
> sg+release: push releases to the cloud ephemeral registry too

- lib/managedservicesplatform/cloudsql/BUILD.bazel
- lib/managedservicesplatform/cloudsql/cloudsql.go
- lib/managedservicesplatform/runtime/contract/BUILD.bazel
- lib/managedservicesplatform/runtime/contract/postgresql.go
Part of https://linear.app/sourcegraph/issue/CORE-96 - we want to be able to use the same Cloud SQL connection mechanism we use for MSP-provisioned databases to be able to connect to a database in another project (in this case, the database of interest is the Sourcegraph.com database).
Also see #62525 
CI - this is a refactor only
> msp/runtime: export Cloud SQL conection internals for direct usage

- cmd/enterprise-portal/BUILD.bazel
- cmd/enterprise-portal/CODENOTIFY
- cmd/enterprise-portal/README.md
- cmd/enterprise-portal/image_test.yaml
- cmd/enterprise-portal/internal/dotcomdb/BUILD.bazel
- cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
- cmd/enterprise-portal/main.go
- cmd/enterprise-portal/service/BUILD.bazel
- cmd/enterprise-portal/service/config.go
- cmd/enterprise-portal/service/dotcomdb.go
- cmd/enterprise-portal/service/service.go
- cmd/enterprise-portal/service/state.go
- go.mod
Closes https://linear.app/sourcegraph/issue/CORE-96 - this scaffolds an initial Enterprise Portal service, as described in [RFC 885](https://docs.google.com/document/d/1tiaW1IVKm_YSSYhH-z7Q8sv4HSO_YJ_Uu6eYDjX7uU4/edit#heading=h.tdaxc5h34u7q), with a test setup to verify that we are able to connect to the Sourcegraph.com database and query from it. This will be used to implement the read-only RPCs proposed in #62263 
```sh
bazel run //cmd/enterprise-portal:candidate_push --stamp -- --tag insiders --repository us.gcr.io/sourcegraph-dev/enterprise-portal
```
> enterprise-portal: initialize service with dotcom DB connection

- internal/conf/validate.go
- internal/conf/validate_test.go
> conf: redact `scim.authToken` in site config UI

- client/web-sveltekit/src/lib/search/input/SearchInput.svelte
Closes https://github.com/sourcegraph/sourcegraph/issues/62572
Not the ideal solution but cheap one, I'm curious what @fkling 
thinks about having this as standard behavior for suggestion logic.
https://github.com/sourcegraph/sourcegraph/assets/18492575/52247f4b-3dd9-40ee-b448-7a10ec7cb3f4
- Go to the search result page and try to submit a query 
- You should see no suggestions after the submit action 
- Suggestions should appear right after you interact with the input
> [Svelte]: Hide suggestion UI after query was submitted

- internal/appliance/BUILD.bazel
- internal/appliance/config/BUILD.bazel
- internal/appliance/config/config.go
- internal/appliance/config/embed.go
- internal/appliance/config/pgsql/postgresql.conf
- internal/appliance/defaults.go
- internal/appliance/pgsql.go
- internal/appliance/pgsql_test.go
- internal/appliance/reconcile.go
- internal/appliance/spec.go
- internal/appliance/testdata/golden-fixtures/pgsql/default.yaml
- internal/appliance/testdata/golden-fixtures/pgsql/with-storage.yaml
- internal/appliance/testdata/sg/pgsql/default.yaml
- internal/appliance/testdata/sg/pgsql/with-storage.yaml
- internal/k8s/resource/container/container.go
Add `pgsql` service definition.
Golden files
> appliance: add pgsql service definition

- cmd/gitserver/internal/git/iface.go
- cmd/gitserver/internal/server_grpc.go
- cmd/gitserver/internal/server_grpc_test.go
- internal/gitserver/v1/gitserver.proto
- internal/gitserver/v1/gitserver_grpc.pb.go
Part of https://github.com/sourcegraph/sourcegraph/issues/60411
This PR fixes up the GetObject gRPC server method by:
- Adding unit tests for it since there weren't any before
- Adding a check to fail early if the repository isn't cloned yet (like all of our other grpc methods do). 
New unit tests
> gitserver: grpc: fixup and add tests for GetCommit RPC

- internal/batches/types/scheduler/window/BUILD.bazel
- internal/batches/types/scheduler/window/config.go
- internal/batches/types/scheduler/window/config_test.go
- internal/batches/types/scheduler/window/time.go
- internal/batches/types/scheduler/window/window.go
This fixes an issue where we can potentially make no progress in the main loop of `Estimate`. Commentary inline.
Related [Slack thread](https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1713644445735079)
Added unit test for this case and fuzz test to search for other edge cases.
> Batch changes: make window ranges exclusive to avoid infinite loop

- client/wildcard/src/global-styles/jupyter.scss
This is just a quick followup from https://github.com/sourcegraph/sourcegraph/pull/62583 that reserves the right amount of space for cell outputs.
There is likely a second style pass we should take on this whole thing, but this one in particular is something I'd go as far as to consider a bug. 
Before: 
After:
> Web: small style fix for jupyter notebooks

- dev/managedservicesplatform/internal/resource/bigquery/bigquery.go
- dev/managedservicesplatform/operationdocs/operationdocs.go
- dev/managedservicesplatform/spec/environment.go
- dev/managedservicesplatform/stacks/cloudrun/cloudrun.go
- dev/sg/msp/helpers.go
This change adds a `locations: { gcpRegion: "...", gcpLocation: "..." }` configuration to centralize all location-related options. `gcpRegion` specifies regional preferences, while `gcpLocation` specifies multi-regional preferences (for resources that support it - only BigQuery in most cases).
Closes CORE-24 - see issue for some context.
```
sg msp generate -all # no diff
```
```
sg msp schema -output='../managed-services/schema/service.schema.json'
```
> msp: centralize and expose locations configuration

- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
This PR changes the implementation of CommitsUniqueToBranch to use the existing Commits API.
The range syntax HEAD..branch is equivalent to `branch ^HEAD` (see git log documentation). Commits also already handles subrepo perms correctly so we don't need to reimplement that in here.
We can then stitch together the expected response from that.
Test plan:
Verified the git command does the same, and the existing unit and E2E tests still pass.
> gitserver: Implement CommitsUniqueToBranch using Commits

- internal/batches/sources/mocks_test.go
- internal/codeintel/policies/matcher.go
- internal/codeintel/policies/matcher_common_test.go
- internal/codeintel/policies/matcher_retention_test.go
- internal/gitserver/client.go
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
- internal/gitserver/mocks_temp.go
- internal/gitserver/observability.go
This has only one caller and is now implemented using existing gitserver stuff, so I'm moving this custom response mapping to where it's used. One less API we need to expose via gRPC.
Closes https://github.com/sourcegraph/sourcegraph/issues/62102
Test plan:
Adjusted tests, and existing E2E tests still pass.
> gitserver: Move CommitsUniqueToBranch to callsite

- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
There used to be two implementations of this, one for with subrepo enabled, one for without. This PR aligns those two to both use the Commits method.
One code path less, and one API less that we need to port to gRPC.
Test plan:
Existing unit tests are still passing.
> gitserver: Always use Commits in HasCommitAfter

- internal/batches/sources/mocks_test.go
- internal/gitserver/client.go
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
- internal/gitserver/mocks_temp.go
- internal/gitserver/observability.go
- internal/search/repos/repos.go
- internal/search/repos/repos_test.go
This is only used in one place, so we're moving the implementation to the caller. Gitserver client only exposes gRPC methods without additional logic on top.
Closes https://github.com/sourcegraph/sourcegraph/issues/61688
Test plan:
Kept the existing tests but rewrote them to test Commits instead so we don't lose coverage for this.
> gitserver: Move implementation of HasCommitAfter to caller

- internal/gitserver/protocol/BUILD.bazel
- internal/gitserver/protocol/gitserver.go
- internal/gitserver/protocol/gitserver_test.go
Closes https://github.com/sourcegraph/sourcegraph/issues/60411
We didn't have any round trip tests for the GetCommit request or response type. This PR adds them.
New unit tests
> gitserver: grpc: create proto roundtrip tests for GetObject[Request/Response]

- internal/appliance/BUILD.bazel
- internal/appliance/defaults.go
- internal/appliance/reconcile.go
- internal/appliance/spec.go
- internal/appliance/syntect.go
- internal/appliance/syntect_test.go
- internal/appliance/testdata/golden-fixtures/syntect/default.yaml
- internal/appliance/testdata/golden-fixtures/syntect/with-replicas.yaml
- internal/appliance/testdata/sg/syntect/default.yaml
- internal/appliance/testdata/sg/syntect/with-replicas.yaml
A reasonably simple one, I think!
Closes https://github.com/sourcegraph/sourcegraph-operator/issues/40
> appliance: deploy syntect-server

- dev/backcompat/bazel-backcompat.sh
- dev/backcompat/flakes.json
- dev/ci/internal/ci/pipeline.go
Fixes https://github.com/sourcegraph/devx-support/issues/950
CI
> chore(ci): bump backcompat target to 5.4.0

- dev/sg/internal/cloud/build_command.go
- dev/sg/internal/cloud/common.go
- dev/sg/internal/cloud/delete_command.go
- dev/sg/internal/cloud/deploy_command.go
- dev/sg/internal/cloud/lease_command.go
- dev/sg/internal/cloud/list_command.go
- dev/sg/internal/cloud/status_command.go
- dev/sg/internal/cloud/upgrade_command.go
Remove the `EXPERIMENTAL Command` notice for all Cloud ephemeral commands
CI + Local tests
> sg: cloud - remove wip notice for ephemeral commands

- dev/build-tracker/bigquery.go
TIL BigQuery has a native "repeated" type, so we dont have to comma separate this out : )
Not impacting any existing data as the current version isnt live yet (due to an msp misconfiguration) and the bigquery tables not being created yet)
CI and live
> build-tracker: use repeated type for agent queues + deref strings

- internal/codeintel/uploads/internal/background/processor/job_worker_handler.go
The old implementation skipped over directory names that aren't known, because `git ls-tree` doesn't complain for unknown directories.
This PR restores this behavior.
Test plan:
Will check that sentry errors no longer occur.
> Fixup parseDirectoryChildren replacement

- cmd/gitserver/internal/git/git.go
- cmd/gitserver/internal/git/gitcli/archivereader.go
- cmd/gitserver/internal/server_grpc.go
This is how all the other commands do it, so let's do the same here, and unexport this function.
Test plan:
Git archive tests still pass.
> gitserver: Move spec arg safety check into git layer

- cmd/frontend/backend/inventory.go
- cmd/frontend/backend/repos_test.go
- cmd/frontend/graphqlbackend/git_commit.go
- cmd/frontend/graphqlbackend/git_commit_test.go
- cmd/frontend/graphqlbackend/git_tree.go
- cmd/frontend/graphqlbackend/git_tree_entry.go
- cmd/frontend/graphqlbackend/git_tree_test.go
- cmd/frontend/graphqlbackend/search_results_stats_languages_test.go
- cmd/frontend/internal/app/ui/raw.go
- cmd/frontend/internal/app/ui/raw_test.go
- cmd/gitserver/internal/integration_tests/tree_test.go
- cmd/worker/internal/embeddings/repo/handler.go
- cmd/worker/internal/embeddings/repo/handler_test.go
- internal/batches/sources/mocks_test.go
- internal/codeintel/autoindexing/internal/inference/iface.go
- internal/codeintel/uploads/internal/background/processor/job_worker_handler.go
- internal/codeintel/uploads/internal/background/processor/job_worker_handler_test.go
- internal/gitserver/client.go
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
- internal/gitserver/mocks_temp.go
- internal/own/background/analytics.go
- internal/own/background/analytics_test.go
There is potentially a lot of FDs in a repo, so we return an iterator instead to encourage callers to consume it one by one and not load all of it into memory.
Test plan:
Existing tests still pass.
> gitserver: Make ReadDir return an iterator on client side

- cmd/frontend/backend/inventory.go
- cmd/frontend/backend/repos_test.go
- cmd/frontend/graphqlbackend/git_commit.go
- cmd/frontend/graphqlbackend/git_commit_test.go
- cmd/frontend/graphqlbackend/git_tree.go
- cmd/frontend/graphqlbackend/git_tree_entry.go
- cmd/frontend/graphqlbackend/git_tree_test.go
- cmd/frontend/graphqlbackend/search_results_stats_languages_test.go
- cmd/frontend/internal/app/ui/raw.go
- cmd/frontend/internal/app/ui/raw_test.go
- cmd/gitserver/internal/integration_tests/tree_test.go
- cmd/worker/internal/embeddings/repo/handler.go
- cmd/worker/internal/embeddings/repo/handler_test.go
- internal/batches/sources/mocks_test.go
- internal/codeintel/autoindexing/internal/inference/iface.go
- internal/codeintel/uploads/internal/background/processor/job_worker_handler.go
- internal/codeintel/uploads/internal/background/processor/job_worker_handler_test.go
- internal/gitserver/client.go
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
- internal/gitserver/mocks_temp.go
- internal/own/background/analytics.go
- internal/own/background/analytics_test.go
We always ended the observation when the iterator is created before, this will make sure to track the time until the call to Close().
Test plan:
Code review, existing CI.
> gitserver: Fix duration reported for ChangedFiles

- cmd/gitserver/internal/ensurerevision.go
- cmd/gitserver/internal/postfetch.go
- cmd/repo-updater/internal/scheduler/scheduler.go
- cmd/repo-updater/internal/scheduler/scheduler_test.go
- internal/database/gitserver_repos.go
This is a small step towards making gitserver itself less dependent on Sourcegraph concepts like the database, by making the repo-updater scheduler (later, this can be coordinator) write to the DB instead.
Note: Until we decide what to do with ensurerevision which schedules out-of-band updates that affect concurrency and the control flow, I decided to inline this behavior there to make it very explicit.
Test plan:
Existing tests are still passing.
> gitserver: Move repo timestamp updates to caller

- cmd/gitserver/internal/git/git.go
- cmd/gitserver/internal/git/gitcli/BUILD.bazel
- cmd/gitserver/internal/git/gitcli/commits.go
- cmd/gitserver/internal/git/gitcli/commits_test.go
- cmd/gitserver/internal/git/gitcli/exec.go
- cmd/gitserver/internal/git/iface.go
- cmd/gitserver/internal/git/mock.go
- cmd/gitserver/internal/git/observability.go
- cmd/gitserver/internal/postfetch.go
This PR moves the implementation of LatestCommitTimestamp to the GitBackend interface. We get proper tracking of the command by that, including error logs, resource usage, invocation count etc.
Test plan:
Tests are still passing.
> gitserver: Implement LatestCommitTimestamp in backend

- cmd/gitserver/internal/git/gitcli/odb.go
- cmd/gitserver/internal/git/gitcli/odb_test.go
- cmd/gitserver/internal/server_grpc.go
- cmd/gitserver/internal/server_grpc_test.go
I messed up the error checking here, and the test for it as well, now gitserver properly returns FileNotFoundPayloads and RevisionNotFoundPayloads for this API.
Test plan:
Adjusted test suite and manually verified using the gRPC UI.
> gitserver: Fixup error codes for ReadDir

- cmd/gitserver/internal/git/git.go
- cmd/gitserver/internal/git/gitcli/refs.go
- cmd/gitserver/internal/git/gitcli/refs_test.go
- cmd/gitserver/internal/git/iface.go
- cmd/gitserver/internal/git/mock.go
- cmd/gitserver/internal/git/observability.go
- cmd/gitserver/internal/postfetch.go
- cmd/gitserver/internal/serverutil.go
- internal/fileutil/fileutil_test.go
This PR moves the implementation of ComputeRefHash to the GitBackend interface and reduces the amount of memory needed by it. We get proper tracking of the command by that, including error logs, resource usage, invocation count etc.
Since there is no 1000% guarantee that this didn't change the hash, I opted for resetting the last changed value and recomputing from scratch, by changing the path of the file to _v2.
Test plan:
Tests are still passing.
> gitserver: Implement RefHash in backend

- cmd/gitserver/internal/cleanup.go
- cmd/gitserver/internal/cleanup_test.go
- cmd/gitserver/internal/git/iface.go
- cmd/gitserver/internal/integration_tests/clone_test.go
- cmd/gitserver/internal/integration_tests/utils_test.go
- cmd/gitserver/internal/server.go
- cmd/gitserver/internal/server_grpc.go
- cmd/gitserver/internal/server_grpc_test.go
- cmd/gitserver/internal/server_test.go
- cmd/gitserver/shared/shared.go
Currently, the janitor doesn't use the observable backend wrapper, this PR makes all users of backend use the same factory function.
Test plan:
Tests are still passing.
> gitserver: Use the same GitBackendSource for all code paths

- cmd/gitserver/internal/cleanup.go
- cmd/gitserver/internal/cleanup_test.go
Using config is fairly convenient, but got somewhat out of hand. On dotcom, we call this millions of times, because the janitor runs frequently and there are a lot of repos.
Instead, for a few simple things we now use a different mechanism that has less overhead (also, we only abused the git config, those values are of no interest to git itself).
1. The timestamp for the last size calculation is now stored as the mtime of a magic file in the repo dir.
2. The repoType is only loaded when there is a reclone reason, and we might want to skip over Perforce repos
Test plan:
Added a basic test, and integration tests still pass.
> gitserver: Reduce number of git config invocations

- dev/build-tracker/bigquery.go
- dev/build-tracker/main.go
- dev/build-tracker/server_test.go
So the graphql API differs quite a bit :upside_down_face: not using that as a reference anymore
updated unit test based on live data
> build-tracker: fix handling of agent webhooks

- internal/rockskip/server.go
I couldn't help but make this change after seeing the algorithm in https://github.com/sourcegraph/sourcegraph/pull/62510. Feel free to just close this if this makes it less clear, but this kinda feels clearer in my head but I am probably weird.
Test Plan: TestRuler passes
> rockskip: ruler function is just bits.TrailingZeros

- deps.bzl
- dev/managedservicesplatform/internal/resource/sentryalert/sentryalert.go
- dev/managedservicesplatform/stacks/monitoring/sentry.go
- go.mod
- go.sum
Fixes issue in Sentry with conditions array not accepting an empty array even though it is an optional field in Sentry
https://github.com/sourcegraph/managed-services-platform-cdktf/pull/8
Also changes Sentry to send to slack an alert at most once every 60 mins instead of 15.
Sentry alerts were a bit spammy so this should reduce that somewhat
tested in msp-testbed-test
> sg/msp: upgrade sentry

- client/web-sveltekit/src/lib/wildcard/Markdown.module.scss
- client/wildcard/src/components/Markdown/Markdown.module.scss
This fixes an issue with Jupyter notebook rendering where the offset from the anchor can clip the left side of the header text. The issue is that we use `margin-left: 1rem;` to offset the anchor, but the anchor isn't guaranteed to be exactly 1rem wide. This makes the relationship explicit and adds a comment that those are linked.
Manually tested both rendered markdown and rendered notebooks in both the react and svelte webapp. No more clipping.
> Python notebooks: fix anchor offset

- testing/tools/upgradetest/tests-util.go
Last week, I ran into an obscure error where an internal release build had it's release tests failing. 
[Context](https://sourcegraph.slack.com/archives/C05DWT4ANHH/p1715011866175999)
This led to an hypothesis where we believe the version I was trying to release `5.3.666` was assumed by the tests to be behind the latest version `5.3.12303`. I added this check to ensure this doesn't repeat itself.
Will test during the release testing later.
> release(upgradetest): confirm postrelease version is newer than the latest sourcegraph version

- cmd/executor/docker-mirror/_ami.build.sh
- cmd/executor/docker-mirror/_ami.push.sh
- cmd/executor/vm-image/_ami.build.sh
- cmd/executor/vm-image/_ami.push.sh
[Context](https://sourcegraph.slack.com/archives/C072MK5LRA6/p1715270616345209)
We found out during the 5.4.0 release that the amis weren't named properly. Thus PR fixes that.
Below is the matrix for naming AMIs.
| Internal Release  | Public Release  |
|---|---|
| {IMAGE_FAMILY}-{BUILDKITE_BUILD_NUMBER}  | {IMAGE_FAMILY}  |
> release(executors): update ami naming

- doc/_resources/templates/document.html
- doc/docsite.json
Adds a `<meta>` that says everything is noindex/nofollow. 
The base branch of that PR is the branch served by the legacy docs, which is "frozen" on the commit just before we removed it from the main repo.
> feat(docs): make legacy docs noindex,nofollow 

- CHANGELOG.md
- internal/completions/client/awsbedrock/bedrock.go
URL Model names weren't path-escaped leading to issues with Bedrock provisioned throughput model names that include `:` and `/` characters. 
- Existing unit tests should pass
> URL Path Escape Model Name

- CHANGELOG.md
- client/web/src/repo/blob/codemirror/search.tsx
We already cycle through results when pressing the "normal" Enter key. This didn't work for the numpad enter key because `event.code` reports `NumpadEnter`, not `Enter`. `event.key` returns the same value for both keys.
This was adjusted in response to customer feedback.
> web: Cycle through in-file search results when pressing the numpad enter key

- dev/build-tracker/bigquery.go
- dev/build-tracker/main.go
🙃  would be useful to have..
Confirmed bigquery code handles time.Time natively by inspecting the code
> build-tracker: include timestamp in agent state change events

- dev/managedservicesplatform/stacks/monitoring/service.go
Noticed a typo while looking at a diff in the managed-services repo
ci
> sg/msp: fix typo in exernal_health_check description

- internal/codeintel/autoindexing/internal/inference/iface.go
Hi. It's me, crashy mc crasher.
This causes inference jobs to always return a context cancelled error. Not sure how that slipped through.
Luckily, we waited with merging this change until after the release so this shouldn't affect any customers.
Test plan:
Verified that locally inference works again.
> inference: Add missing defer

- CHANGELOG.md
- cmd/gitserver/internal/git/gitcli/refs.go
- cmd/gitserver/internal/git/gitcli/refs_test.go
In git, there exist two types of tags: Lightweight tags, those are boring old refs that live in refs/tags/ and point directly to a commit.
And then there are annotated tags, those live in refs/tags/ too, but they don't point to a commit directly, instead they point to a tag object, which then points to a commit object.
That is used to add a message to a tag.
However, we didn't detect lightweight tags correctly, so they would be reported as Type: Branch (as they point to a commit).
This PR fixes it.
Test plan:
Added tests and verified manually using gRPC UI.
> gitserver(ListRefs): Fix type detection for lightweight tags

- client/web-sveltekit/src/lib/Popover.svelte
- client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.gql
- client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.stories.svelte
- client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.svelte
- client/web-sveltekit/src/routes/+layout.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
- client/web-sveltekit/src/routes/layout.gql
- client/web-sveltekit/src/routes/search/RepoRev.svelte
- client/web-sveltekit/src/routes/search/SearchResults.svelte
Revert https://github.com/sourcegraph/sourcegraph/pull/61989
This reverts commit 0d8003f6553bd5bc39cb4d878b274c6698d93bf3.
It seems that this PR introduced a few problems with Popover styles and it also 
adds problematic data fetching on the search result page (we make too many requests as we render different search result blocks); there is also the problem that most of the requests for the repo rev tooltip fail because of auth error. 
I revert it for now, but will mark this one as something I check that will go to the June release since Jason did most of the work already, we just need to tune it a bit. 
- Check that Popover looks ok in the web app (repository revision, opt-in experiment tooltip, ...)
- Check that Search result repository doesn't produce a lot of queries as we render them
> Revert "Svelte [RepoPopover]: Instantiate the RepoPopover result across the web-app

- dev/sg/msp/sg_msp.go
Enables staged rollouts of workspace updates.
```
sg msp tfc sync -all -category=test
```
> sg msp: add category flag for 'tfc sync'

- dev/gqltest/README.md
This PR updates the README for GraphQL integration tests to encourage devs to
run them in CI instead of running locally. It also update the local
instructions to use the `backend_integration_test` target.
Tested these instructions manually
> Docs: update integration test instructions

- dev/sg/internal/cloud/BUILD.bazel
- dev/sg/internal/cloud/build_command.go
- dev/sg/internal/cloud/delete_command.go
- dev/sg/internal/cloud/deploy_command.go
- dev/sg/internal/cloud/ephemeral_command.go
- dev/sg/internal/cloud/lease_command.go
- dev/sg/internal/cloud/list_command.go
- dev/sg/internal/cloud/list_versions_command.go
- dev/sg/internal/cloud/status_command.go
- dev/sg/internal/cloud/upgrade_command.go
- dev/sg/sg_cloud.go
```
go run ./dev/sg cloud --help
NAME:
sg cloud - Install and work with Sourcegraph Cloud tools
USAGE:
sg cloud command [command options] [arguments...]
DESCRIPTION:
Learn more about Sourcegraph Cloud:
- Product: https://sourcegraph.com/docs/cloud
- Handbook: https://handbook.sourcegraph.com/departments/cloud/
COMMANDS:
install         Install or upgrade local `mi2` CLI (for Cloud V2)
ephemeral, eph  Set of commands that operate on Cloud Ephemeral instances
help, h         Shows a list of commands or help for one command
OPTIONS:
--help, -h  show help
```
And when you do `sg cloud eph` 
```
go run ./dev/sg cloud eph --help
NAME:
sg cloud ephemeral - Set of commands that operate on Cloud Ephemeral instances
USAGE:
sg cloud ephemeral command [command options] [arguments...]
DESCRIPTION: …
```
> sg: cloud - move all cloud ephemeral commands to a sub command `ephemeral`

- internal/appliance/defaults.go
- internal/appliance/spec.go
- internal/appliance/standard_config_test.go
- internal/appliance/testdata/golden-fixtures/blobstore/default.yaml
- internal/appliance/testdata/golden-fixtures/gitserver/default.yaml
- internal/appliance/testdata/golden-fixtures/gitserver/with-storage.yaml
- internal/appliance/testdata/golden-fixtures/pgsql/default.yaml
- internal/appliance/testdata/golden-fixtures/pgsql/with-storage.yaml
- internal/appliance/testdata/golden-fixtures/precise-code-intel/with-blobstore.yaml
- internal/appliance/testdata/golden-fixtures/redis/default.yaml
- internal/appliance/testdata/golden-fixtures/redis/with-storage.yaml
- internal/appliance/testdata/golden-fixtures/standard/blobstore-subsequent-disable.yaml
- internal/appliance/testdata/golden-fixtures/standard/blobstore-with-named-storage-class.yaml
- internal/appliance/testdata/golden-fixtures/standard/symbols-with-custom-image.yaml
- internal/appliance/testdata/golden-fixtures/symbols/default.yaml
- internal/appliance/testdata/golden-fixtures/symbols/with-storage.yaml
- internal/appliance/testdata/sg/standard/blobstore-with-named-storage-class.yaml
- internal/k8s/resource/pvc/pvc.go
Let Kubernetes choose its default storage class when one is not explicitly configured. See REL-16 for wider plans around StorageClasses at the appliance level.
Golden tests included
> appliance: default storageclass is nil

- client/web-sveltekit/src/routes/search/+page.ts
This updates the svelte webapp to respect the new `search.displayLimit`.
Followup from https://github.com/sourcegraph/sourcegraph/pull/60761
Added `search.displayLimit: 2000` to my settings, checked that the resulting search request had `displayLimit=2000` in the URL
> Svelte: follow up on display limit TODO

- cmd/appliance/shared/BUILD.bazel
- cmd/appliance/shared/config.go
- cmd/appliance/shared/shared.go
Allow a namespace to be configured, defaulting to all namespaces.
Without this setting, if an admin deploys the appliance with
namespace-scoped RBAC, it would throw errors due to not being able to
watch ConfigMaps in all namespaces.
Manually tested for now:
1. With default config, all namespaces are watched
1. With a particular namespace configured, that namespace is watched, but configmaps landing in other namespaces do not trigger the reconcile loop.
When we have blackbox/smoke tests, the code in this package will be better-tested.
> appliance: namespace scoping

- dev/build-tracker/main.go
Without this, this error won't be logged to Sentry, resulting in us missing it unless we check GCP
Discussed with @jac
> build-tracker: include error if failing to write to bigquery

- client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte
- client/web-sveltekit/src/routes/+layout.svelte
Closes: https://github.com/sourcegraph/sourcegraph/issues/62174
This PR fixes the problem with z-indexes, ideally, we shouldn't think about this if we were using the Modal component for the sidebar navigation panel (Modal would render this outside of the common DOM tree and hence there was no problem with z-index) but since we don't have Modal at the moment I tuned stacking layers a bit to fix it. 
- Check any popover element in the global header navigation, and make sure there are no unexpected overlaps between sidebar navigation, search input, and the main content.
> Svelte: Fix global header navigation layers

- dev/managedservicesplatform/internal/resource/deliverypipeline/deliverypipeline.go
Now that #62644 (CORE-23) is rolled out, this import block is no longer needed (and may even be disruptive when provisioning new rollout pipelines). The change was rolled out in:
- https://github.com/sourcegraph/managed-services/pull/1416
- https://github.com/sourcegraph/managed-services/pull/1417
- https://github.com/sourcegraph/managed-services/pull/1403
n/a
> msp/rollouts: remove Cloud Deploy target import

- dev/managedservicesplatform/stacks/cloudrun/internal/builder/job/job.go
- dev/managedservicesplatform/stacks/cloudrun/internal/builder/service/service.go
VPC direct egress is now GA: see example in https://registry.terraform.io/providers/hashicorp/google/5.29.0/docs/resources/cloud_run_v2_service#example-usage---cloudrunv2-service-directvpc and https://cloud.google.com/run/docs/configuring/vpc-direct-vpc
This also fixes the infinite `GA` -> `BETA` drift we have in TFC
n/a
> msp/cloudrun: use GA launch stage

- dev/gqltest/BUILD.bazel
- dev/gqltest/search_test.go
- dev/gqltest/symbol_search_test.go
This PR creates a new GraphQL integration test file focused on symbol search.
It exercises the same searches the web client uses for code navigation.
In a follow-up, we will add cases for older commits and enable Rockskip.
Added new tests
> Symbols: new backend integration test

- client/branded/src/search-ui/results/sidebar/SearchReference.tsx
In https://github.com/sourcegraph/sourcegraph/pull/13448 we introduced a configurable timeout. This PR updates a piece of documentation accordingly.
Documentation update. Should be covered by existing CI.
> fix: update search timeout docs

- dev/managedservicesplatform/internal/resource/deliverypipeline/deliverypipeline.go
- dev/managedservicesplatform/managedservicesplatform.go
- dev/managedservicesplatform/stacks/cloudrun/cloudrun.go
Adds the repository as an annotation to the delivery pipeline so that we can later query it e.g. from cloud-relay to include a link to the commit in the message we send to slack
I also tried adding annotations to the releases but unfortunately they don't get sent as part of the notification message
side note: the annotations support free-form text without the same limitations the labels have
part of CORE-36
locally tested
> sg/msp: add repo annotation to delivery pipeline

- cmd/frontend/external/session/session.go
- cmd/frontend/internal/app/sign_out.go
- internal/auth/userpasswd/handlers.go
- internal/auth/userpasswd/handlers_test.go
- internal/session/BUILD.bazel
- internal/session/session.go
- internal/session/session_test.go
- internal/telemetry/events.go
This change fixes telemetry for various sign-in, sign-up telemetry events - `session.SetActorFromUser` accepts a context and returns a new one, but never does anything to the returned context. It makes sense for this to authenticate the context because it is only ever used on a success case, and in turn this fixes telemetry by providing the telemetry SDK an actor to extract a user ID for.
For the events affected by `session.SetActorFromUser` I've incremented the event version to `2`.
1. Test on sign-in-success that a event with the user is recorded
2. Test on `session.SetActorFromUser` to verify context is authenticated
> fix/telemetry(auth): return authenticated context from session.SetActorFromUser

- cmd/gitserver/internal/git/observability.go
- internal/observation/observation.go
The ErrorsFilter function can be used to skip over well known errors for certain log targets. Multiple errors can all be collected in a wrapper, the ErrCollector.
The collector wraps the errors it found, but it doesn't implement Unwrap, so errors.Is and errors.HasType don't work properly here, they will only see the ErrCollector.
This PR adds Unwrap to the ErrCollector to fix that, and fixes the error code detection in gitserver git observability, and makes it less aggressive in what we skip.
Test plan:
Verified that the two errors are no longer erroneously logged.
> observability: Fix error checks in ErrorsFilter

- cmd/frontend/internal/httpapi/completions/handler.go
- cmd/frontend/internal/httpapi/completions/handler_test.go
Sets lower version constraints in test mode to enable clients testing. See [this](https://sourcegraph.slack.com/archives/C06Q9R098N4/p1715801118313989?thread_ts=1715038896.786949&cid=C06Q9R098N4) thread for more details.
- CI
> Cody Ignore: lower version constraint fot test mode

- .github/PULL_REQUEST_TEMPLATE.md
Provides guidance to cover the basics with pull request descriptions.
Before there wasn't any and the quality would vary a ton between authors. Now, with that in place, it's a visible reminder to cover the basics and mitigate the blank page syndrome.
I created a _how-to_ in Notion, blank for now that we can use to provide additional context.
CI
> chore(process): add structure guide for PRs

- client/web-sveltekit/src/lib/Popover.svelte
- client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte
- client/web-sveltekit/src/lib/navigation/GlobalSidebarNavigation.svelte
- client/web-sveltekit/src/lib/wildcard/menu/DropdownMenu.svelte
- client/web-sveltekit/src/routes/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/RepoSearchInput.svelte
While looking into #62713 I stumbled upon two z-index issues:
I'm worried that layering already gets out of hand and is difficult to understand. So this commit removes a bunch of z-index settings to simplifying this.
Most importantly:
- Instead of setting a z-index on the header to make the sidebar navigation work, we can "portal" the sidebar to the end of the document.
- Likewise the repo search input is portalled to ensure that it renders above all other content.
Opened popovers/tooltips/etc on various pages:
- Main search input/suggestions
- Global sidebar navigation
- User menu
- `experimental` popover
- Code intel hovercards
- Repo search input
- Tooltips
- Revision picker
> svelte: Fix various z-index/layering issues

- dev/managedservicesplatform/internal/resource/deliverypipeline/deliverypipeline.go
Changes the identifier used by targets to reference the custom target type they belong to. Previously this used `targetType.Name()` but should have been `targetType.Id()`. 
Fixes the following error encountered by `repoferee`
```
failed to validate custom target "projects/1058156036563/locations/us-central1/targets/prod-us-central1": failed to parse custom target type name referenced by target "projects/1058156036563/locations/us-central1/targets/prod-us-central1": invalid 3 name: invalid argument
```
docs:
Target:
> [custom_target_type](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/clouddeploy_target#custom_target_type) - (Required) Required. The name of the CustomTargetType. Format must be projects/{project}/locations/{location}/customTargetTypes/{custom_ …
> sg/msp: fix `CustomTargetType` reference in `Target` definition

- cmd/gitserver/internal/cleanup.go
The default buckets don't serve us too well for the jobs, most just report 5ms (the smallest default) all the time, and some always report 10s (the biggest default) - this should hopefully give us better insight.
Test plan:
Code review.
> gitserver: Adjust buckets for cleanup timing

- cmd/frontend/graphqlbackend/git_commits.go
- cmd/frontend/graphqlbackend/repository_comparison_test.go
- cmd/symbols/gitserver/BUILD.bazel
- cmd/symbols/gitserver/client.go
- internal/codeintel/policies/matcher.go
- internal/codeintel/policies/matcher_common_test.go
- internal/codeintel/uploads/service.go
- internal/gitserver/commands.go
- internal/gitserver/commands_test.go
- internal/insights/gitserver/client.go
- internal/own/background/recent_contributors.go
- internal/rockskip/mocks_test.go
- internal/search/repos/repos.go
This will be useful for commit searches, and is generally supported by git so why not support it here. That also lets you express `A..B` as `B, ^A` if you want to do less string concatenation, for example.
Test plan:
Made sure all existing callers pass a non-empty string to the slice if they specify the slice at all, and all existing tests still pass.
> gitserver: Allow multiple ranges to be passed to Commits

- cmd/gitserver/internal/git/gitcli/BUILD.bazel
- cmd/gitserver/internal/git/gitcli/command.go
- cmd/gitserver/internal/git/gitcli/diff.go
- cmd/gitserver/internal/git/gitcli/diff_test.go
- cmd/gitserver/internal/git/gitcli/exec.go
- cmd/gitserver/internal/git/gitcli/exec_test.go
- cmd/gitserver/internal/patch.go
- cmd/gitserver/internal/server_test.go
At some point in the past, we noticed that passing /etc/passwd and /dev/null to `git diff` allows to view the file contents, even though it's not part of the repo itself.
That allows to read arbitrary files on disk, so we had to add in-app validation for file paths, including relative paths.
That makes the validation much more complex and harder to reason about, and requires that we didn't make a mistake.
Instead, we switch to `git diff-tree` which validates paths are part of the tree properly.
By that, we can remove a bunch of complexity around git diff argument validation.
See here for the difference:
```
➜  sourcegraph git:(main) git diff-tree --find-renames --full-index --inter-hunk-context=3 --no-prefix -- /etc/hosts /dev/null
fatal: /etc/hosts: '/etc/hosts' is outside repository at …
```
> gitserver: Use git-diff-tree to simplify validation and improve security

- client/web-sveltekit/src/lib/Hotkey.ts
- client/web-sveltekit/src/lib/KeyboardShortcut.svelte
- client/web-sveltekit/src/lib/fuzzyfinder/FuzzyFinder.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
Fixes #62725 
This commit updates the repo sidebar to show the Linux specific keyboard shorcut for searching files.
I initially was just rendering it as a string, but I think makes sense to have some spacing between the individual parts, just like it was done in the sidebar. So I added a new component for rendering platform-specific keyboard shortcuts that applies this style.
The current code adds some negative padding, I don't know if that's really necessary.
| ![2024-05-16_15-39](https://github.com/sourcegraph/sourcegraph/assets/179026/c7b77573-4844-4c95-b7f5-ba3322da67bf) | ![2024-05-16_15-40](https://github.com/sourcegraph/sourcegraph/assets/179026/0f12e6f1-75c4-48f5-9ee6-d05cb9343220) | 
| …
> svelte: Show correct keyboard shortcut on Linux in "search files" button

- dev/managedservicesplatform/managedservicesplatform.go
- dev/managedservicesplatform/spec/environment.go
- dev/managedservicesplatform/spec/environment_test.go
- dev/managedservicesplatform/spec/rollout.go
- dev/managedservicesplatform/stacks/cloudrun/cloudrun.go
- dev/managedservicesplatform/stacks/cloudrun/internal/builder/builder.go
- dev/managedservicesplatform/stacks/cloudrun/internal/builder/job/job.go
- dev/managedservicesplatform/stacks/cloudrun/internal/builder/service/service.go
Closes CORE-121
The dependency on the generated `tfvars` file is frustrating for first-time MSP setup because it currently requires `-stable=false` to update, and doesn't actually serve any purpose for deploy types other than `subscription` (which uses it to isolate image changes that happen on via GitHub actions). This makes it so that we don't generate, or depend on, the dynamic `tfvars` file unless you are using `subscription`.
I've also added a rollout spec configuration, `initialImageTag`, to make the initial tag we provision environments with configurable (as some services might not publish `insiders` images) - see the docstring.
Inspect output of `sg msp generate -all`
> feat/msp: do not use tfvars file outside of deploy-type 'subscription'

- internal/k8s/resource/container/container.go
Since introducing the standard feature for container env vars in https://github.com/sourcegraph/sourcegraph/pull/62624, some test flakiness has been introduced. This is because container.go was iterating through an unsorted map, which made golden file assertions non-deterministic. This is fixed by sorting the map keys when appending user-provided env vars.
Ran `go test -count=10 -failfast ./internal/appliance` and it passed. Before this commit, 10 runs would reliably tease out the flake.
> appliance: fix test flakiness when container env vars are specified

- client/web-sveltekit/src/lib/search/input/SuggestionOption.svelte
- client/web-sveltekit/src/lib/search/input/Suggestions.svelte
Increases font size for search suggestions.
Locally tested for visual changes.
> Svelte: Increase search suggestions font size

- cmd/gitserver/internal/git/gitcli/diff.go
- cmd/gitserver/internal/git/gitcli/diff_test.go
When switching to git-diff-tree, I looked over the fact that it can only work with treeish-es, not with rangespecs.
This PR translates ranges to the corresponding equivalents according to the Git docs:
`..` -> `A B`
`...` -> `$(git merge-base A B) B`
Test plan:
Verified diffs are now generated properly again, also added another test to our suite.
> gitserver: Fix Diff generation

- dev/gqltest/README.md
For the reviewer: can you check if the link opens up the Form in the correct state for you?
(I used the 'Copy Form link' button.)
n/a
> docs: Add link to Entitle permission

- CHANGELOG.md
- cmd/frontend/auth/BUILD.bazel
- cmd/frontend/auth/auth_test.go
- cmd/frontend/internal/auth/httpheader/BUILD.bazel
- cmd/frontend/internal/auth/httpheader/middleware_test.go
- cmd/frontend/internal/auth/scim/BUILD.bazel
- cmd/frontend/internal/auth/scim/user_create_test.go
- internal/auth/userpasswd/BUILD.bazel
- internal/auth/userpasswd/handlers.go
https://github.com/sourcegraph/sourcegraph/pull/60339 introduced a new behavior that would always add a random suffix to usernames that are derived from email addresses.
The reason behind it seems to be that on dotcom, emails are from various domains and there are a lot of duplicates usually, and a lot of names that trigger our suspiciousness detection, like me@sourcegraph.com or me@sgdev.org.
For customer instances, this is not a real risk, and because of historic reasons, we depend on the username to be exactly what was given by the auth provider, so that bitbucket server permission syncing can work.
So this change for customer instances caused https://github.com/sourcegraph/sourcegraph/issues/62676.
To simplify the fix for this and make sure it can land in the next patch release, I …
> auth: Make username from email deduplication dotcom only

- doc/dependency_decisions.yml
Khroma and Elkjs were raising errors in the license checker: 
- ElkJS because its license is EPL-2.0 and we've never had that case before. 
- Added to allowed licenses. 
- Khroma is [MIT](https://github.com/fabiospampinato/khroma/blob/master/license) but the NPM package is not up to date with regards to that info, and thus the license checker returns "unknown" when querying NPM. 
- Manually assigned the license.   
CI, in particular the license check action
> chore(licenses): fix khroma and elkjs

- client/web/src/cody/subscription/CodySubscriptionPage.tsx
I accidentally negated a condition here: https://github.com/sourcegraph/sourcegraph/pull/62453/files#diff-e49c67a73cb92dfd40a6015761f04bc49b5e72bd3a22b7faa7dc7c5d1390a305L74. This is a fix to revert that.
- I merged the PR on May 15th, 9 am UTC
- Was probably released about 24h later.
- Was wrong for about 30 hours :/
It caused this:
to display like this for new users:
and vice versa.
It probably highly impacted our conversion rate for yesterday.
Why didn't we notice this in the code reviews: I probably messed it up when I was addressing feedback, and didn't wait for the re-review to move fast.
It worked before, I only changed it by accident.
> Fix a condition I negated by accident

- dev/sg/internal/cloud/artifact_registry.go
- dev/sg/internal/cloud/list_versions_command.go
if you didn't provide a regex this during filtering list-versions would break. This slipped through while doing last minute refactoring.
```
go run ./dev/sg cloud eph list-versions
☁️ Retrieved 543 docker images from registry "cloud-ephemeral"
Tag                                                Upload time          Image count
b6a5c7dd76f292ce90a6d3c4c029f072ad41848b_272681... 2024-03-15 11:19:33  48
wb-sg-cloud-eph-delete_271241_2024-04-29_5.3-76... 2024-03-15 11:19:33  48
2c328e9e7e08_265572                                2024-03-15 11:19:17  45
23fafbf0fa90eff28fe5ba8b3cdcd3bd09a313d3_269589... 2024-03-15 11:19:33  46
e90a171118c9_2024-03-15                            2024-03-15 11:19:17  45
6d88b156f78664c3a73b45693473ae7de58b25e4_270425... 2024-03-15 11:19:33  47
```
Tested locally
> fix(sg/eph): handle nil regex

- wolfi-images/batcheshelper.lock.json
- wolfi-images/blobstore.lock.json
- wolfi-images/bundled-executor.lock.json
- wolfi-images/caddy.lock.json
- wolfi-images/cadvisor.lock.json
- wolfi-images/cloud-mi2.lock.json
- wolfi-images/executor-kubernetes.lock.json
- wolfi-images/executor.lock.json
- wolfi-images/gitserver.lock.json
- wolfi-images/grafana.lock.json
- wolfi-images/jaeger-agent.lock.json
- wolfi-images/jaeger-all-in-one.lock.json
- wolfi-images/node-exporter.lock.json
- wolfi-images/opentelemetry-collector.lock.json
- wolfi-images/postgres-exporter.lock.json
- wolfi-images/postgresql-12-codeinsights.lock.json
- wolfi-images/postgresql-12.lock.json
- wolfi-images/prometheus.lock.json
- wolfi-images/redis-exporter.lock.json
- wolfi-images/redis.lock.json
- wolfi-images/repo-updater.lock.json
- wolfi-images/search-indexer.lock.json
- wolfi-images/searcher.lock.json
- wolfi-images/server.lock.json
- wolfi-images/sourcegraph-base.lock.json
- wolfi-images/sourcegraph-dev.lock.json
- wolfi-images/sourcegraph-template.lock.json
- wolfi-images/symbols.lock.json
- wolfi-images/syntax-highlighter.lock.json
Automatically generated PR to update package lockfiles for Sourcegraph base images.
Built from Buildkite run [#274765](https://buildkite.com/sourcegraph/sourcegraph/builds/274765).
- CI build verifies image functionality
> security: Auto-update package lockfiles for Sourcegraph base images

- docker-images/syntax-highlighter/Cargo.Bazel.lock
- docker-images/syntax-highlighter/Cargo.lock
- docker-images/syntax-highlighter/Cargo.toml
- docker-images/syntax-highlighter/src/lib.rs
- docker-images/syntax-highlighter/src/snapshots/syntect_server__tests__check_error.snap
Previously, if you made a malformed request, the actual error
would not be shown because the default anyhow to_string impl
would only show the top-most context attached to the error
(see: https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations),
which would be something like `/scip endpoint`.
Added snapshot test
> fix: Show full info for highlighter errors

- docker-images/syntax-highlighter/README.md
- docker-images/syntax-highlighter/load_test.lua
I noticed this tool `wrk` was mentioned in a blog post,
figured I'd add some brief docs on how it can be used
for load-testing the highlighter.
n/a
> chore: Document how to load test highlighter

- client/web/src/cody/team/CodyManageTeamPage.module.scss
- client/web/src/cody/team/CodyManageTeamPage.tsx
- client/web/src/cody/team/InviteUsers.tsx
- client/web/src/cody/team/TeamMemberList.tsx
- client/web/src/cody/team/WhiteIcon.tsx
@rrhyne left a bunch of feedback in [this figma](https://www.figma.com/design/FMSdn1oKccJRHQPgf7053o/Cody-PLG-GA?node-id=4658-19941&t=MhldUPrMz6gjSVBy-0) and [this Loom](https://www.loom.com/share/bb527ad52f4442bd9196e833a4e7be92) that I totally overlooked at first.
This PR contains all the fixes listen in the Figma and Loom (unless I mixed something).
This is a complete list:
- Page
- Added missing page title
- Removed "open in new" icon from "Manage subscription" link
- Made the "Add seats" button be of the "success" type (green) rather than "primary" (blue)
- Invites
- Fixed textarea label copy
- Added a red outline to textbox if the input has an error
- Made the error text replace the help text in case of an error
- Left-aligned "Send" button
- Team member list
- Converted the list to …
> Fix up "Manage team" page UI

- dev/sg/internal/backport/BUILD.bazel
- dev/sg/internal/backport/backport.go
Revert line that tries to fetch a specific remote branch that has never actually been pushed, back to fetching from the default remote.
I'm not 100% sure this fixes the underlying problem in https://linear.app/sourcegraph/issue/REL-38/having-trouble-back-porting-panw-pr-to-540-need-help, so let's execute the test plan pre-merge.
There don't appear to be many automated tests for backporting, which is fair enough as this is quite fiddly. We can manually test this by running a backport command pre-merge, and seeing if it fixes https://linear.app/sourcegraph/issue/REL-38/having-trouble-back-porting-panw-pr-to-540-need-help:
```
go run ./dev/sg backport <args>
```
> fix: backporting

- internal/completions/client/awsbedrock/BUILD.bazel
- internal/completions/client/awsbedrock/bedrock.go
- internal/completions/client/awsbedrock/bedrock_test.go
- internal/completions/client/azureopenai/BUILD.bazel
- internal/conf/computed.go
- internal/conf/computed_test.go
- internal/conf/conftypes/conftypes.go
- internal/conf/validation/BUILD.bazel
- internal/conf/validation/cody.go
- internal/conf/validation/cody_test.go
* Improve Bedrock ARN handling
* Fix up PR comments
(cherry picked from commit 6a7666c42cf349a6b702b8c72c9cc2c4e8421ad7)
This PR ensures that the Bedrock Provisioned Capacity ARN model IDs are handled correctly.
- added unit tests
- tested in sandbox environment
> Backport: Client Compatible Bedrock ARN handling (#62720)

- dev/gqltest/compute_test.go
- dev/gqltest/repository_test.go
- dev/gqltest/search_aggregations_test.go
- dev/gqltest/search_test.go
- dev/gqltest/symbol_search_test.go
Most of the tests aren't checking whether external services
can be brought up correctly, so re-using the schema type
makes the external service configuration more compact compared
to specifying anonymous types for guiding serialization
> chore: Simplify extsvc config in integration tests

- dev/sg/internal/cloud/common.go
- dev/sg/internal/cloud/deploy_command.go
- dev/sg/internal/cloud/instance.go
This PR fixes the following from this output
```
sg cloud eph deploy --version 5.4.0
✅ Version "5.4.0" found in Cloud ephemeral registry
Deploy instance details:
ID           : src-9cf5b905f9f966015d4a
Name         : william-bezu-5-4-0
InstanceType : internal
Environment  :
Version      : 5.4.0
URL          : https://william-bezu-5-4-0.sgdev.dev/
AdminEmail   :
CreatedAt    : 1970-01-01T00:00:00Z
DeletetAt    : 1970-01-01T00:00:00Z
ExpiresAt    : 0001-01-01T00:00:00Z
Project      : src-f54e076f7870a06f003c
Region       : us-central1
Status       : in progress
ActionURL    :
Error        :
✅ Deployment "william_bezu_5.4.0" created for version "5.4.0" - access at: https://william-bezu-5-4-0.sgdev.dev/
```
* the deployment name doesn't match to what cloud returns. We now santize the name the …
> sg: cloud ephemeral - handle empty times better and santizes name better

- client/web/src/cody/management/api/client.ts
While working on integrating the SSC REST API client hook (https://github.com/sourcegraph/sourcegraph/pull/62715) I spent longer than I would have liked trying to figure out why it wasn't working in some cases...
To cut to the punch line, there is a quirk of the `fetch()` API in that it won't send the "origin" header for `GET` or `HEAD` requests. And that lead to the Sourcegraph backend not treating the request as authenticated, even though we supplied the user's `sgs` session cookie.
After doing my best to understand how things all work, it looks like the simplest thing would be to just supply the `X-Requested-With` header. Which is how the backend authenticates HTTP requests based on the session cookie. (In addition to the `Origin` header if it is made available, which is why I didn't …
> Fix auth-related error in the SSC REST API client hook

- client/web/src/cody/management/CodyManagementPage.tsx
- client/web/src/cody/subscription/CodySubscriptionPage.tsx
- client/web/src/cody/util.ts
- client/web/src/jscontext.ts
- cmd/frontend/internal/app/jscontext/jscontext.go
- schema/schema.go
- schema/site.schema.json
For a long time, it was annoying that we couldn't properly test some SSC features because `https://accounts.sourcegraph.com/cody/subscription` (production URL) was hard-coded for the "Manage subscription" links.
This PR makes that setting dynamic.
Also:
- It wires up the "Create a Cody Pro team" button to pass an extra `?team=1` argument which we'll handle on the checkout page.
- It contains an unrelated event logging cleanup because the deprecation warnings made it difficult for me to focus on the linter warnings related to my PR.
**Note:** If `sscBaseUrl` is not configured in the site config, it falls back to the previously hard-coded URL `https://accounts.sourcegraph.com/cody`.
The PR consists of four individual commits to make the PR review easier.
Tested it manually: it works nicely.
> Make SSC base url dynamic

- dev/authtest/code_intel_test.go
- dev/gqltest/organization_test.go
- dev/gqltest/search_test.go
- dev/gqltest/site_config_test.go
- dev/gqltest/sub_repo_permissions_test.go
- internal/gqltestutil/settings.go
Multiple integration tests have essentially the same code for
modifying the site config, and then resetting it to it original
state. Refactor that out into a common method.
> chore: Factor out logic for modifying site config

- dev/authtest/code_intel_test.go
- dev/authtest/main_test.go
- dev/authtest/organization_test.go
- dev/authtest/repository_test.go
- dev/authtest/site_admin_test.go
- dev/ci/integration/executors/tester/init.go
- dev/codeintel-qa/internal/graphql.go
- dev/gqltest/main_test.go
- dev/gqltest/site_config_test.go
- dev/gqltest/sub_repo_permissions_test.go
- internal/cmd/init-sg/main.go
- internal/gqltestutil/client.go
These functions are used in test code, which makes it tricker to
pass in loggers for checking requests and responses. Instead, make
the API method-based. This introduces slightly more boilerplate
since Client construction is fallible (so you can't chain 
`NewClient(...).SignUp(...)`), but it allows calling code
to pass in loggers more easily for debugging test failures.
> chore: Remove client construction from SignUp/In funcs

- cmd/repo-updater/internal/gitserver/BUILD.bazel
- cmd/repo-updater/internal/gitserver/repositoryservice.go
This new client didn't have any retries set, so we would always fast-fail when gitserver is unavailable. That makes the operation more noisy than it has to be, and potentially all repos back in the fetch queue, because it thinks the fetch itself failed.
All these methods are safe to be called a second time, so we can safely do that.
This is an easy fix to ensure repo updater waits a bit for gitserver to be back online.
Test plan:
Verified locally that fetches don't immediately fail when gitserver is down.
> repoupdater: Add retry policy to repositoryservice

- client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/+layout.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/RepoSearchInput.svelte
Closes #62713 
Manually tested with default revision, selected branch and selected revision.
> svelte: Preserve current revision in repo search input

- CHANGELOG.md
- cmd/frontend/graphqlbackend/schema.graphql
- cmd/frontend/graphqlbackend/site.go
- internal/conf/computed.go
- internal/conf/computed_test.go
- internal/conf/conftypes/consts.go
- schema/schema.go
- schema/site.schema.json
CLOSE https://github.com/sourcegraph/cody-issues/issues/76 
See [the linked issue](https://github.com/sourcegraph/cody-issues/issues/76) for details.
Objectives:
Changes:
- Add `SmartContext` field to `CompletionsConfig` struct
- Implement `SmartContext()` method in `codyLLMConfigurationResolver`
- Set default `SmartContext` value to "enabled" if not provided, and "disabled" to disable the feature
- Update schema and documentation to describe `SmartContext` feature
- Update documentation of `chatModelMaxTokens` regarding how it would be overrides when `SmartContext` is enabled
1. Run `sg start` from this branch to start a Sourcegraph instance locally
2. Visit  https://sourcegraph.test:3443/api/console#%7B%22query%22%3A%22%23%20Type%20queries%20here%2C%20with%20completion%2C%20validation%2C …
> feat/cody: new site config for smart context

- cmd/gitserver/internal/git/gitcli/odb.go
- cmd/gitserver/internal/git/gitcli/odb_test.go
Unfortunately, some callers seem to be passing non-20-byte OIDs through api.CommitID fields.
We should ultimately clean that up, but in the meantime this should help make the error messages clearer and reduce noise from strange error messages.
Test plan:
Added tests to cover for the cases where this can happen.
> gitserver: Clean up some errors from improper API usage

- cmd/gitserver/internal/cleanup.go
- cmd/gitserver/internal/cleanup_test.go
- cmd/gitserver/internal/git/gitcli/BUILD.bazel
- cmd/gitserver/internal/git/gitcli/command.go
- cmd/gitserver/internal/git/gitcli/command_test.go
We still incur a ton of git config calls, those add pressure to the process spawning, so we instead do a much cheaper fs.Stat now to check for corruption.
Test plan:
Adjusted tests, CI and integration tests still pass.
> gitserver: Switch corruption logs to use separate file

- cmd/gitserver/internal/server.go
The syncer implementation already does redaction based on the remote URL it actually used, so this is redundant, and an unnecessary call to the database / KMS backend.
Test plan:
Code review, CI passes.
> gitserver: Remove unnecessary redaction

- cmd/gitserver/internal/git/gitcli/commitlog.go
I don't have a clue yet why this happens, but I'll let the two outputs below speak for themselves:
On my mac:
```
➜  sourcegraph git:(main) git log --format='format:%x1e%H%x00%aN%x00%aE%x00%at%x00%cN%x00%cE%x00%ct%x00%B%x00%P%x00' --after=2024-02-21T18:26:09Z --topo-order HEAD --name-only
➜  sourcegraph git:(main) git version
git version 2.45.1
```
In the latest gitserver docker image from main:
```
/data/repos $ git log --format='format:%x1e%H%x00%aN%x00%aE%x00%at%x00%cN%x00%cE%x00%ct%x00%B%x00%P%x00' --after=2024-02-2
1T18:26:09Z --topo-order HEAD --name-only
fatal: option '--name-only' must come before non-option arguments
/data/repos $ git version
git version 2.45.1
```
Test plan:
Verified the generated command runs alright inside our docker image.
> gitserver: Fix CommitLog on some git versions

- internal/repos/perforce.go
This doesn't actually add anything anymore, but it confused me into thinking we might be leaking the credentails somewhere.
Closes https://github.com/sourcegraph/sourcegraph/issues/62783
Test plan:
Dead code, CI still passes.
> Remove misleading logic to add credentials to clone URL

- client/web-sveltekit/src/routes/[...repo=reporev]/RepoSearchInput.svelte
The input is missing a trailing space. I messed that up when making changes to #62822.
Trivial change.
> svelte: Add tailling space to default repo search input

- client/web/src/cody/util.ts
We need a URL to point the user to the webpage to manage their Cody Pro subscription in a couple places. And to support testing in lower environments, we made that configurable in https://github.com/sourcegraph/sourcegraph/pull/62790/files#diff-70a08658447c0eeaf1f548b8e325cac30a08567323d32e50b1953786404a5b07.
There was a problem in that PR however, the "default" value in the `site.schema.json` doesn't do what you'd think. So at runtime the value for `frontendCodyProConfig.sscBaseUrl` was always always the empty string. This leads to confusing errors whenever you try to manage your Cody Pro subscription.
I tried to just update the Sourcegraph.com site config to supply that value like intended, however in doing that the Sourcegraph.com frontend jobs would start to crash loop. (Because only …
> Fix woes related to undefined frontendCodyProConfig.sscBaseUrl

- internal/conf/validation/highlight.go
- internal/highlight/BUILD.bazel
- internal/highlight/language.go
- internal/highlight/language_test.go
- schema/schema.go
- schema/site.schema.json
At the moment, too many fields are required, which means you need
to specify unnecessary fields when trying to modify only a single
field, such as mapping specific extensions to specific languages.
Fixes https://linear.app/sourcegraph/issue/GRAPH-612
Added unit tests for configuration initialization
> fix: Make most syntaxHighlighting config fields optional

- client/web/src/cody/subscription/CodySubscriptionPage.tsx
- client/web/src/cody/team/InviteUsers.tsx
- client/web/src/cody/team/TeamMemberList.tsx
Finally, I could start testing the experience end-to-end.
I found the first few mistakes during that.
Three changes:
1. Fixed a few copy-paste mistakes in the team member list action logging
2. The URL in the case of single users was wrong—now it works correctly. Plus the logging was likely suppressed by the "to" part because `event.preventDefault()` was not called.
3. Made the number of invites dynamic in the notification, pluralized:
The three changes are three commits in this PR to make the review easier.
Tested manually.
> SSC: Three small fixes for Teams & invites

- client/web-sveltekit/src/lib/repo/filePopover/FilePopover.gql
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/+page.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/+page.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commit/[...revspec]/page.spec.ts
It was reported ([Slack thread](https://sourcegraph.slack.com/archives/C05MHAP318B/p1716347339416449)) that we show the old commit data when navigating to a different commit page.
The page was explicitly implemented to show the previously loaded data in case there is an error when fetching more data. But this also affects normal page navigation.
In this commit the implementation was changed to return the previously loaded data when an error occurs, which simplifies loading state and data rendering on the page itself.
Manual testing + new integration test.
> svelte: Improve commit page loading state

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.spec.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/all/page.spec.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/page.spec.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/tags/page.spec.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/layout.spec.ts
- client/web-sveltekit/src/routes/search/page.spec.ts
The dev infra team is making progress on the Playwright in CI topic in https://github.com/sourcegraph/sourcegraph/pull/62683 and https://github.com/sourcegraph/sourcegraph/pull/62560. I want to help them merge their work into main as soon as possible.
To make sure they can run the right tests in the CI process (and enable the right merge blockers), I want to skip tests that are currently failing with playwright, and funnel them into new tasks for making them work again.
I created a new ticket for fixing the failing tests: https://github.com/sourcegraph/sourcegraph/issues/62821
- Disabled tests that were failing
> chore: skip failing tests

- client/web-sveltekit/src/lib/Commit.gql
- client/web-sveltekit/src/lib/Commit.svelte
It was reported ([Slack thread](https://sourcegraph.slack.com/archives/C05MHAP318B/p1716347420277679)) that the "byline" isn't correct when a commit has an author and a committer.
This fixes it.
| ![2024-05-22_10-30](https://github.com/sourcegraph/sourcegraph/assets/179026/0b0e32cc-14df-4910-888a-3ef549411373)| ![2024-05-22_10-24](https://github.com/sourcegraph/sourcegraph/assets/179026/4fd56dca-4641-48eb-9ad5-9d9376b1f504) | 
> svelte: Show correct byline when commit has author and committer

- client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.gql
- client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.svelte
- client/web-sveltekit/src/routes/search/RepoRev.svelte
The repo popover has deployed to S2, but it's not visible to anyone who is not a site admin because one of the GraphQL fields used is restricted to only site admins.
This updates the query to use a non-restricted field, and also fixes the code host capitalization while I'm at it.
Additionally, if there is an error, it now displays it in the popover so it should be easier to catch these in the future.
Manually tested it still works when I use a user with no site admin permissions. This is a great motivator for getting solid end-to-end tests working 🙂
> Svelte: remove site-admin-only data from repo popover

- .github/workflows/licenses-check.yml
Previously, if the license checking action failed, there was no actionnable instructions for the users. This PR adds a conditional step that posts a comment with a link to the how-to in Notion. 
I'm using this PR as a way to QA this, hence the few commits to QA each cases. 
CI + this PR itself (see commits)
> chore(gha): link to how-to when license check fail

- client/web-sveltekit/src/lib/repo/FileHeader.svelte
- client/web-sveltekit/src/lib/repo/filePopover/FilePopover.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts
This makes each dir entry in the file popover header a link, and allows wrapping so the full path is always visible. Uses the same wrapping logic as the file header so the slashes work right. Additionally, it linkifies the commit message to point to the same page as the OID link
Fixes SRCH-125, SRCH-126, SRCH-127, and SRCH-98
https://github.com/sourcegraph/sourcegraph/assets/12631702/2e773a3c-10c2-41d4-8ada-c2c6b43d5a9c
> Svelte: linkify and wrap dir entries

- dev/sg/msp/helpers.go
- dev/sg/msp/sg_msp.go
Nice-to-have summaries for adoption of various features:
1. Services vs Jobs
2. Rollout pipelines
3. Deploy types
4. Resource dependencies
> feat/sg-msp: add more stats to 'fleet' command

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.spec.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/branches/all/page.spec.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/tags/page.spec.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/layout.spec.ts
- client/web-sveltekit/src/routes/search/page.spec.ts
Follow up for #62820 to fix failing/skipped tests that are easy to fix (which is all but one).
Re-enabling the syntax highlighting error test should be done in a separate PR.
`pnpm test`
> svelte: Fix failing/skipped playwright tests

- dev/managedservicesplatform/spec/environment.go
Guards against another one of those "only fails at apply time" things (https://github.com/sourcegraph/managed-services/pull/1459)
https://github.com/sourcegraph/managed-services/pull/1459
> fix/msp/spec: validate against LivenessInterval that is too high

- .aspect/bazelrc/ci.bazelrc
- WORKSPACE
The bump in rules_js picks up a fix to prevent the `.../package (No such file or directory)` Bazel flake.
CI
> bazel: bump to latest aspect_rules_js, rules_nodejs, aspect_bazel_lib, aspect_rules_ts, aspect_rules_swc

- wolfi-packages/http-server-stabilizer.yaml
This PR doesn't update syntax-highlighter's lockfile;
that will happen in a separate PR after the package
gets published to our package repository.
Only a version bump; doesn't affect deployed versions, so n/a
> chore: Pull in latest http-server-stabilizer version

- client/web/src/cody/util.ts
I made this URL dynamic before, [here](https://github.com/sourcegraph/sourcegraph/pull/62790), but that didn't work [because](https://github.com/sourcegraph/sourcegraph/pull/62790#issuecomment-2123533378) the "default" value in the `site.schema.json` file doesn't do what I thought it did. So @chrsmith did a quick fix in https://github.com/sourcegraph/sourcegraph/pull/62835, but then we lost the ability to make this dynamic.
So this PR makes it dynamic again, this time with a working fallback.
I tried to do the same thing on the back end, but it didn't feel right.
1. I tried a transformation in `computed.go`:
```go
// GetCodyProConfig returns the CodyProConfig for the current site config,
// with some handy defaults.
func GetCodyProConfig(siteConfig schema.SiteConfiguration) (c …
```
> Make the URL dynamic, now with a fallback

- cmd/worker/internal/encryption/config.go
- cmd/worker/internal/permissions/config.go
- internal/codeintel/dependencies/internal/background/job_packages_filter.go
- internal/codeintel/ranking/internal/background/coordinator/config.go
- internal/codeintel/ranking/internal/background/exporter/config.go
- internal/codeintel/ranking/internal/background/janitor/config.go
- internal/codeintel/ranking/internal/background/mapper/config.go
- internal/codeintel/ranking/internal/background/reducer/config.go
- internal/codeintel/uploads/internal/background/backfiller/config.go
- internal/codeintel/uploads/internal/background/commitgraph/config.go
- internal/codeintel/uploads/internal/background/expirer/config.go
- internal/executor/types/cache.go
- internal/goroutine/recorder/recorder.go
I looked at background routines and noticed that many routines are running _very_ frequently, which can cause higher than necessary load, and also stress on redis to store all these runs.
I tried to put in some more sensible numbers (aligning it with what most other routines seem to use). For many instances, this will mean a 30x reduction in job invocations.
Test plan:
Code review from owners, and will watch S2 and dotcom for potential issues.
> worker: Reduce frequency of very frequently run jobs

- client/web/BUILD.bazel
- client/web/src/cody/team/TeamMemberList.test.ts
- client/web/src/cody/team/TeamMemberList.tsx
- client/web/src/cody/util.ts
This is a step toward https://github.com/sourcegraph/self-serve-cody/issues/725
The list of invitations used to look like this:
Now it looks like this:
which intends to match [this design](https://www.figma.com/design/FMSdn1oKccJRHQPgf7053o/Cody-PLG-GA?node-id=4658-18897&t=m1L9vFMX0uBbl2Y0-0).
Some other examples with the current solution are:
- Invite sent 5 seconds ago
- Invite sent 1 hour ago
- Invite sent yesterday
- Invite sent last week
@rrhyne, is this format fine?
- Added tests
- Tested it manually, it renders well.
> SSC: Fix invite date formatting

- client/web/src/cody/team/CodyManageTeamPage.module.scss
- client/web/src/cody/team/InviteUsers.tsx
- client/web/src/cody/team/TeamMemberList.tsx
Our notifications had no dark theme style, and they weren't design-approved.
This PR makes them match the [figma](https://www.figma.com/design/FMSdn1oKccJRHQPgf7053o/Cody-PLG-GA?node-id=4600-18103&t=0WJfuMjhfhwqZokw-0).
Caveats:
- I had no design for the error notification style, so I came up with my best reds that matched the other colors. I also still have no icon for that style.
- In the figma, there were illustrations on the left side of the notifications, but I assumed those were only for specific messages, so I left the checkmark and the crappy X I made.
Light theme looks:
Dark theme looks:
Tested with a temporary state to demo. See the screenshots.
> SSC: Fix notification colors

- wolfi-packages/s3proxy.yaml
- How was it PREVIOUSLY?
The blobstore container exposed port with test ssl keys configured
- How it will be from NOW on.
The blobstore will have just the http port (probably 9000) and we disabled the unused port(ssl)
Blobstore container had unused port open configured with test private keys. After [investigating](https://sourcegraph.slack.com/archives/C02UC4WUX1Q/p1716478617084139) about the unused port, we decided to remove config in the image from upstream `sourcegraph/s3proxy`
- CI 🟢 
Additional testing
```bash
docker exec -u 0 -it blobstore sh
curl -i -X PUT http://127.0.0.1:9000/create-bucket-test-2022-01-09-attempt0
```
> Update blobstore package to remove unused port + ssl properties

- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/stats/contributors/+page.ts
If no time/date is set we are passing an empty string to the server, which seems to be wrong. Instead we should be passing `null`.
Loading the contributors page doesn't show a GraphQL error anymore.
> svelte: Fix GraphQL error on contributors page

- doc/dev/background-information/bazel/containers.md
- docker-images/blobstore/s3_proxy_image_test.yaml
This test checks that the s3proxy service starts as expected, and that we're able to create an example bucket using a curl request. Previously we were running this manually whenever s3proxy was updated.
Also updated the bazel docs to mention a caveat of the setup steps.
- CI
- Running new test locally
> bazel: Add container test for s3proxy

- client/web-sveltekit/src/lib/repo/HistoryPanel.svelte
This updates the history panel entries to allowing closing the diff and commit view by clicking the same link again (i.e. the commit subject or the 'view at commit' button).
> svelte: Allow closing the diff and commit view from the history panel

- dev/sg/internal/std/prompt.go
Closes CORE-133
Fixes reading input for `sg msp init` prompts if the input has whitespace
locally tested
> sg/msp: fix init prompts breaking when encountering whitespace

- client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
- client/web-sveltekit/vite.config.ts
This adds a link to the repository's code-graph page to the repo navigation.
- added a flag to each menu item that specifies whether or not show the entry for non-admin users (defaults to `false`)
- updated vite's proxy configuration to properly load React repo pages from the server
| Normal user | Site admin |
| ![2024-05-24_14-12](https://github.com/sourcegraph/sourcegraph/assets/179026/e66d4892-0e3a-4765-bd51-a6f116c7e301) | ![2024-05-24_14-12_1](https://github.com/sourcegraph/sourcegraph/assets/179026/c90702a3-c5b1-4144-9b8e-053293f94e2a) | 
Manual testing. The link shows up and redirects to the React code graph page.
> svelte: Add link to code-graph page to repo navigation

- wolfi-packages/s3proxy.yaml
In our updated s3proxy package, the s3proxy binary had permissions 711 which prevented it from being run. Updated the package config to chmod it to 755.
- CI
> s3proxy: Fix permissions on s3proxy package binary

- dev/sg/internal/cloud/instance.go
- dev/sg/internal/cloud/printers.go
The reason field my contain `, conclusion` and sometimes it might not. This accounts for this case and gracefully handles it it is missing
Tested locally
Failure
```
go run ./dev/sg cloud eph status --name wb-feature-x --raw
❌ getting status of "wb-feature-x" failed
❌ failed to parse status reason: "step 1/3:creating instance, job-url:https://github.com/sourcegraph/cloud/actions/runs/9251869285, state:completed, conclusion:failure" 7
exit status 1
```
Fixed
```
go run ./dev/sg cloud eph status --name wb-feature-x --raw
✅ Ephemeral instance "wb-feature-x" status retrieved
Ephemeral instance details:
ID           : src-1eadb696458496ba7407
Name         : wb-feature-x
InstanceType : internal
Environment  : dev
Version      : wb-feature-x_275730_2024-05-27_5.4-d23e2bfd524d
URL          : …
```
> chore(sg): cloud ephemeral - account for conclusion field

- dev/ci/internal/ci/legacy_operations.go
- dev/ci/internal/ci/misc_operations.go
- dev/ci/internal/ci/pipeline.go
- dev/ci/push_all.sh
- dev/ci/runtype/runtype.go
Following up on [this thread](https://sourcegraph.slack.com/archives/C04MYFW01NV/p1712789750549639), the conclusion was to create a new runtype with the behavior of `main-dry-run` with `push_prod=true`. I created the run type and just included it everywhere the `main-dry-run` type was used. 
I don't understand how that accomplishes what `docker-images-candidates-notest` was doing, but c'est la vie.
Will run on buildkite.
(EDIT @jhchabran): https://buildkite.com/sourcegraph/sourcegraph/builds/275755#018fb9e2-98b1-45e7-b311-7d420c8edc8e
> feat(ci): docker-images runtype

- dev/sg/internal/cloud/instance.go
- dev/sg/internal/cloud/printers.go
Sometimes cloud ephemeral can return multiple job reasons seperate by `;`. In this PR we check for the presence of multiple job reasons and parse it accordingly.
Example of reason with multiple job reasons:
```
step 1/3:creating instance, job-url:https://github.com/sourcegraph/cloud/actions/runs/9255560228, state:completed, conclusion:failure; step 1/3:creating instance, job-url:https://github.com/sourcegraph/cloud/actions/runs/9177645150, state:completed, conclusion:failure; step 1/3:creating instance, job-url:https://github.com/sourcegraph/cloud/actions/runs/9161687255, state:completed, conclusion:failure
```
At the moment we're only interested in the last job and the overall status of all jobs.
Tested locally
Failure
```
Name                                     Expires At …
```
> sg: cloud ephemeral - handle multiple job reasons

- dev/migrations.bzl
- dev/tools/BUILD.bazel
- dev/tools/tool.bzl
Currently, we provide single-file tools such as `ctags`, `gsutil` etc via an `sh_binary` wrapper, to have a single target to reference that automatically does platform selection of the underlying tool. 
Due to some [unfortunate reason](https://github.com/bazelbuild/bazel/issues/11820), the underlying srcs (which is [a single file](https://bazel.build/reference/be/shell#sh_binary.srcs)) of an `sh_binary` are also exposed as outputs (rather than just as typical runfiles) alongside the script that wraps. This is _sometimes_ problematic when doing location expansion (e.g. `$(location ...)`) due to these only allowing a single output (dont ask why this works in some contexts but not others, I dont know). 
To address this, we create a wrapper macro + rule to replicate what we want from …
> bazel: add utility macro for wrapping single-file tools

- client/web/src/cody/management/api/client.ts
- client/web/src/cody/management/api/components/CodyProApiClient.ts
- client/web/src/cody/management/api/hooks/useApiClient.tsx
- client/web/src/cody/management/api/stripeCheckout.ts
- client/web/src/cody/management/subscription/new/CodyProCheckoutForm.tsx
- cmd/frontend/internal/ssc/ssc_proxy.go
We already have this on the old SSC front end since my earlier PR https://github.com/sourcegraph/self-serve-cody/pull/779. Now bringing the same feature to this page because we'll migrate our front end to this one, so we'll need it.
**Note:** This PR contains a bunch of random small fixes. Sorry for polluting the PR with so many little changes. I promise they are trivial, and I carefully checked the changes.
Tested that with the `?team=1` parameter, the page displays the seat number setting UI, and without it, it doesn't.
For the refactors, CI.
> SSC: Handle `team=1` input on checkout form

- client/web/src/cody/components/CodyAlert.module.scss
- client/web/src/cody/components/CodyAlert.tsx
- client/web/src/cody/invites/AcceptInvitePage.tsx
- client/web/src/cody/management/CodyManagementPage.tsx
- client/web/src/cody/management/subscription/new/CodyProCheckoutForm.tsx
- client/web/src/cody/team/InviteUsers.tsx
Contributes to https://github.com/sourcegraph/self-serve-cody/issues/725
We currently don't welcome the user when they first arrive at the Cody Management page. This PR adds a notification.
The changes, each in their own commits:
1. Add the notification to the /cody/manage page
2. Trigger the notification after a user signs up using our new checkout page (the old one is hosted on the SSC site)
3. Trigger the notification after a team invitee accepts the invitation
Unrelated change: fix a header style in the "Team invites" section
Note: for the pic, I used a 4x PNG. The graphic uses gradients that SVG doesn't seem to support (figma export messes up the pic).
- [2-min Loom](https://www.loom.com/share/17912a497b8443afbb2a1f483a78b719?sid=d30df717-7445-43b4-a08d-ca817bfa8013) where I demo …
> SSC: Add "Welcome to Cody Pro" banner

- .github/PULL_REQUEST_TEMPLATE.md
See https://www.notion.so/sourcegraph/Writing-a-changelog-entry-dd997f411d524caabf0d8d38a24a878c?pvs=4 for the context about this edit to the default template. 
This PR updates the default PR template to have a `## Changelog` section to guide teammates into writing entries which are then crawled in order to automatically generate the changelog in the docs repo. 
- Added instructions to guide teamates into writing changelog entries directly in their PR descriptions. 
No testing required, this is merely a content update of the PR template, there's nothing to break.
> chore(release): add changelog section to pr template

- dev/ci/helpers/BUILD.bazel
- dev/ci/helpers/bazeldo.go
- dev/ci/helpers/bazeldo_test.go
- dev/ci/internal/ci/BUILD.bazel
- dev/ci/internal/ci/bazel_helpers.go
- dev/ci/internal/ci/pipeline.go
- dev/sg/ci/BUILD.bazel
- dev/sg/ci/subcommands.go
Before this PR, you could end up pushing a `bazel-do` runtype build that is disallowed, which is not the nicest feedback loop as you'll only hear back about the problem once the CI picked it up.
Now the command straight up tells you before anything else. I also added a basic [How-to](https://www.notion.so/sourcegraph/Running-an-arbitrary-Bazel-command-in-CI-diagnosing-flakes-for-example-e0ae40ec6f3a4fd5a39a41d9681ec632?pvs=4) covering this and linked to it in the extended usage description. 
- Prevent pushing Bazel commands/flags that would end up being rejected by the CI due to the allow list. 
CI + locally tested.
> chore(local): catch bazel-do issues before push

- .tool-versions
- WORKSPACE
- docker-images/syntax-highlighter/Cargo.Bazel.lock
- docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/syntect_scip.rs
- docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
- docker-images/syntax-highlighter/rust-toolchain.toml
We're several months out of date.
> chore: Bump Rust version 1.73.0 -> 1.78.0

- internal/telemetry/sensitivemetadataallowlist/BUILD.bazel
- internal/telemetry/sensitivemetadataallowlist/redact.go
- internal/telemetry/sensitivemetadataallowlist/sensitivemetadataallowlist.go
- internal/telemetry/sensitivemetadataallowlist/sensitivemetadataallowlist_test.go
Fixes a regression from #62830 that caused us to remove all sensitive metadata in dotcom mode, even though we generally collect all sensitive metadata in dotcom. This also fixes export of actually-allowlisted private metadata from custom instances.
tl;dr we accidentally started removing all private metadata, all the time
New unit test covering the redact mode that was evaluated
> fix/telemetry: fix dotcom-mode sensitive metadata removal

- dev/sg/internal/run/sgconfig_command_options.go
- sg.config.yaml
Use shared credentials for local development - replaces #62952 
```
sg run enterprise-portal
```
> feat/sg/enterprise-portal: use externalSecret to configure SAMS client secret

- internal/appliance/config/defaults.go
- internal/appliance/config/spec.go
- internal/appliance/reconciler/BUILD.bazel
- internal/appliance/reconciler/cadvisor.go
- internal/appliance/reconciler/cadvisor_test.go
- internal/appliance/reconciler/golden_test.go
- internal/appliance/reconciler/reconcile.go
- internal/appliance/reconciler/testdata/golden-fixtures/cadvisor/default.yaml
- internal/appliance/reconciler/testdata/sg/cadvisor/default.yaml
- internal/k8s/resource/daemonset/BUILD.bazel
- internal/k8s/resource/daemonset/daemonset.go
- internal/k8s/resource/pod/pod.go
Closes https://linear.app/sourcegraph/issue/REL-54/service-definition-cadvisor.
There are a few intentional differences from our Helm chart:
* The cadvisor privileged option is removed. Cadvisor runs with a privileged containerSecurityContext by default, but the component is made opt-in (disabled by default).
* The PodSecurityPolicy is removed entirely, since it was removed from recent versions of Kubernetes.
> appliance: deploy cadvisor

- internal/codeintel/uploads/internal/background/processor/job_worker_handler.go
I misinterpreted what the client-side version of this did, and accidentally skipped over directories, which meant that it would not traverse deeply into folders. This caused uploads to be incomplete.
Might close GRAPH-632.
Test plan:
Manually verified the before and after behavior and they feel equal to me now from a quick debugger session.
But I don't see precise in my local instance, so perhaps this needs more work.
> uploads: Fixup nested code intel uploads

- cmd/gitserver/internal/server_grpc.go
Just adding a comment explaining why we have to re-cast `path` to a `[]byte` for the error message. 
N/A - just adding a comment
> gitserver: grpc: add comment to Stat implementation explaining why we cast the Path field to []byte

- cmd/frontend/graphqlbackend/repository.go
- cmd/frontend/graphqlbackend/repository_test.go
When the changelist mapper has not yet indexed a changelist ID for fast lookup, we try to find it via git log instead to bridge the time between a git fetch and the new commit SHAs being indexed better.
Test plan:
Verified locally that with an empty DB changelist IDs still show up.
> perforce: Add fallback logic for changelist mapper

- cmd/frontend/graphqlbackend/codeintel.codenav.graphql
- cmd/frontend/graphqlbackend/schema.graphql
- internal/codeintel/codenav/transport/graphql/observability.go
- internal/codeintel/codenav/transport/graphql/root_resolver.go
- internal/codeintel/resolvers/codenav.go
- internal/codeintel/resolvers/root_resolver.go
Let's merge a stub implementation with the types in place.
This will allow parallelizing the spike on syntactic and the work
on implementing the API for precise.
[Ran locally](https://sourcegraph.test:3443/api/console#%7B%22query%22%3A%22%23%20query%20GetRepoID(%24name%3A%20String!)%20%7B%5Cn%23%20%20%20repository(name%3A%20%24name)%20%7B%5Cn%23%20%20%20%20%20id%5Cn%23%20%20%20%7D%5Cn%23%20%7D%5Cn%5Cn%5Cnquery%20S()%20%7B%5Cn%20%20usagesForSymbol(range%3A%20%7B%5Cn%20%20%20%20repository%3A%20%5C%22github.com%2Fsourcegraph%2Fconc%5C%22%5Cn%20%20%20%20path%3A%20%5C%22pool%2Fpool.go%5C%22%5Cn%20%20%7D)%20%7B%5Cn%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20symbol%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%23%20%20%20%5C%22name% …
> codeintel: Add stub implementation for usagesForSymbol API

- internal/codeintel/codenav/transport/graphql/observability.go
Accidentally merged this while leaving the operation `nil`
- Fixed a bug in stub implementation of UsagesForSymbol
Open [https://sourcegraph.test:3443/api/console#%7B%22query%22%3A%22%23%20query%20GetRepoID(%24name[…]A%20%5C%22github.com%2Fvitejs%2Fvite%5C%22%5Cn%22%7D](https://sourcegraph.test:3443/api/console#%7B%22query%22%3A%22%23%20query%20GetRepoID(%24name%3A%20String!)%20%7B%5Cn%23%20%20%20repository(name%3A%20%24name)%20%7B%5Cn%23%20%20%20%20%20id%5Cn%23%20%20%20%7D%5Cn%23%20%7D%5Cn%5Cn%5Cnquery%20S()%20%7B%5Cn%20%20usagesForSymbol(range%3A%20%7B%5Cn%20%20%20%20repository%3A%20%5C%22github.com%2Fsourcegraph%2Fconc%5C%22%5Cn%20%20%20%20path%3A%20%5C%22pool%2Fpool.go%5C%22%5Cn%20%20%7D)%20%7B%5Cn%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20symbol%20%7B%5Cn%20%20%20%20%20%20%20%20name …
> fix: Initialize operation for UsagesForSymbol

- client/web-sveltekit/vite.config.ts
We still need to run `AutoImport` so that the `import` directives are generated, but we don't want to update the `.d.ts` file.
This currently breaks S2.
```
bazel build //client/web-sveltekit:web-sveltekit
```
runs without problem.
> fix: Icon auto-import in Bazel

- dev/managedservicesplatform/spec/environment.go
- dev/managedservicesplatform/spec/environment_test.go
- dev/managedservicesplatform/stacks/monitoring/job.go
Addresses problem noticed in https://github.com/sourcegraph/managed-services/pull/1486#issuecomment-2137887423
Unit tests
- Fixed an issue with output of `sg msp generate` for MSP jobs with particular schedules changing throughout the week
- MSP jobs schedules now must be between 15 minutes at the most frequent, and every week at the least frequent
> fix/msp: test for cron interval changes based on time, add more restrictions

- cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
- cmd/enterprise-portal/internal/dotcomdb/dotcomdb_test.go
- cmd/enterprise-portal/service/config.go
- cmd/enterprise-portal/service/dotcomdb.go
- sg.config.yaml
Since we are reading from the dotcom database for the time being, the dev and prod Enterprise Portal instances serve the same data. This change adds a configuration so that we can set up the dev instance to only serve data from licenses with the dev or internal tag, toggled by `DOTCOM_INCLUDE_PRODUCTION_LICENSES`
This will become a non-issue for Enterprise Portal when we have our own database in https://linear.app/sourcegraph/issue/CORE-100, but for now this helps make sure that the dev instance only serves dev data. This is fairly important since we grant Enterprise Portal scopes more liberally in accounts.sgdev.org.
Updated integration tests to use the dev-only mode.
Also tested locally: with `DOTCOM_INCLUDE_PRODUCTION_LICENSES=false`, endpoints return nothing, while with …
> feat/enterprise-portal: explicit opt-in to serve non-dev/non-internal data

- internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
- internal/codeintel/codenav/internal/lsifstore/locations_by_position_test.go
- internal/codeintel/codenav/internal/lsifstore/metadata_by_position.go
Fixes GRAPH-610
1. We prepend a markdown-formatted signature to the hover text if SignatureDocumentation field if present
2. If the field is absent, we fall back to old behaviour of assuming that signature documentation is already present in the hover text
SignatureDocumentation was added to SCIP format a while back but it's not yet being utilised by our indexers. One of the first to do so will be scip-java (https://github.com/sourcegraph/scip-java/pull/707) – with the plan for rollout being:
1. Merge this PR and wait for a Sourcegraph release
2. Merge scip-java PR and tag a release
3. (optionally) update the default scip-java image in SG
This change allows handling both new SCIP indexes (those that emit SignatureDocumentation), and the old ones, which have signature prepended to …
> feat(codeintel): If SignatureDocumentation is present in SCIP, use it for hover text

- internal/insights/gitserver/client.go
Forgot a case here when migrating the API to gRPC that could leave an empty ranges slice, which is now forbidden.
Thanks to Michael for reporting it!
Closes https://github.com/sourcegraph/sourcegraph/issues/62984
Test plan:
Verified manually that the page is broken before this change and works again after.
> insights: Fix overview page

- client/web-sveltekit/src/lib/search/dynamicFilters/Section.svelte
- client/web-sveltekit/src/lib/search/dynamicFilters/SectionItem.svelte
- client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
- client/web-sveltekit/src/lib/search/dynamicFilters/index.ts
- client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
This adds the `RepoPopover` hover info to the dynamic filters in the search sidebar (replacing the full repo name tooltip) and to the global header.
https://github.com/sourcegraph/sourcegraph/assets/12631702/0c16a1bc-bd0c-4589-af5f-61815956f36f
> Svelte: add repo popovers to repo name in header and in dynamic filters

- client/web-sveltekit/src/lib/Avatar.svelte
- client/web-sveltekit/src/lib/repo/LastCommit.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
This makes various tweaks and simplifications to the `LastCommit` component shown on the file page. 
- Uses the `Timestamp` component
- Removes a bunch of unnecessary DOM elements and styles in favor of just using flexbox well
- Removes the max width on the last commit component, allowing it to take up as much space as is available (but leaving a healthy gap from the tabs). This was the primary reason I tackled this PR. Most commits I see are truncated to the "barely useful" level
https://github.com/sourcegraph/sourcegraph/assets/12631702/94ba7ef3-e4fd-444b-a300-08cdd50982c8
> Svelte: simplify and grow last commit

- client/web-sveltekit/src/lib/Popover.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte
Fixes SRCH-449
Each commit is granular and has a useful message describing the change.
In short:
- Adds a `hoverDelay` parameter to `Popover` so each consumer doesn't need to do this manually
- Makes hovers only show when the mouse comes to rest
- Closes the popover when the window loses focus so we don't miss a mouseleave event and have popovers get stuck open
- Adds a delay to popover closing when the mouse leaves one of the target elements so there is room for error when moving the mouse from the trigger to the popover
- Adds preloading back to the file tree because the popover now does not create the element until the delay has passed
- Makes it so clicking the target closes the popover when hover is enabled.
Manual testing for feel. Would love if reviewers would pull this down and …
> Svelte: QoL fixes for hover popovers

- client/web/src/enterprise/batches/batch-spec/edit/library/comby.batch.yaml
- doc/dev/how-to/opentelemetry_local_dev.md
This PR refactors a batch changes example that uses `patterntype:structural` to
use regex instead. We no longer expose `patterntype:structural` by default, and
want to push users towards other pattern types.
Manually tested the batch changes template.
> Batch changes: remove structural search example

- dev/managedservicesplatform/spec/service.go
- dev/managedservicesplatform/spec/spec.go
Now that msp-ops pages are opt-in and requires you to provide a notion page ID, it's easy to miss providing one. Once a service gets a production environment, this should be required.
Closes https://linear.app/sourcegraph/issue/CORE-120
#62973 
- MSP services with production environments now must provide a `service.notionPageID` for go/msp-ops
> feat/msp/spec: require notionPageID if a production env is provisioned

- dev/managedservicesplatform/spec/spec.go
- dev/sg/msp/sg_msp.go
Simple way to test changes to validations, and maybe helpful for operators too.
Testing: https://github.com/sourcegraph/sourcegraph/pull/62972
```
Projects/sourcegraph/managed-services » sg msp validate
✅ [build-tracker] Validated
✅ [cloud-ops] Validated
✅ [cloud-relay] Validated
✅ [cloud-scheduler] Validated
✅ [cody-analytics] Validated
✅ [enterprise-portal] Validated
✅ [entitler] Validated
✅ [gatekeeper] Validated
✅ [linearhooks] Validated
✅ [msp-testbed] Validated
✅ [pings] Validated
✅ [releaseregistry] Validated
❌ [repoferee] Found valdiation errors
• environment "prod" in category "internal" requires 'service.notionPageID' to be set                                         
✅ [sams] Validated
✅ [sourcegraph-accounts] Validated
✅ [support-hygiene] Validated
✅ [support-integration] …
```
> feat/sg/msp: add 'sg msp validate' for validating service specifications

- dev/managedservicesplatform/operationdocs/diagram/diagram.go
- dev/managedservicesplatform/operationdocs/diagram/msp.go
Not specifying a `domain` config or using `EnvironmentDomainTypeNone` was causing a nil panic during diagram generation. This PR fixes that
Closes CORE-140
nil Domain or EnvironmentDomainTypeNone generates a diagram like so:
> sg/msp: fix nil `domain` and `EnvironmentDomainTypeNone` in diagram gen

- cmd/enterprise-portal/service/service.go
- cmd/enterprise-portal/service/state.go
Mostly to make it easier to spin up a prod environment for now; we can add this back later.
n/a
> feat/enterprise-portal: only do dotcomdb connection check on-demand

- cmd/frontend/hubspot/contacts.go
- cmd/frontend/internal/app/ui/handlers.go
- cmd/frontend/internal/auth/oauth/session.go
- cmd/frontend/internal/auth/openidconnect/middleware.go
- cmd/frontend/internal/auth/openidconnect/user_test.go
- internal/auth/userpasswd/handlers.go
Based on conversations with the marketing team, they would like the PrivateApp to update `first_source_url` contact property with the cookie `first_page_seen_url` on login/sign up flows. Since `last_page_seen_url` is updated every time seomeone goes to a new page, the `first_source_url` is not actually a source of truth using the backfill method they had planned to use. It becomes whatever page they were just on, not the first page they landed on.
Full thread [here](https://sourcegraph.slack.com/archives/C0678ATBXCG/p1716586196562439)
simple change, test via CI
> privateApp to set `first_source_url` contact property on HubSpot

- client/web-sveltekit/src/lib/TreeNode.svelte
This adds guidelines for open directories in the file tree. I recommend reviewing with whitespace changes hidden.
Fixes SRCH-443
Dark:
Light:
Manual testing. This is one where a screenshot test would be really nice 🙂
> Svelte: add lines to directory groups

- lib/errors/filter.go
- lib/errors/filter_test.go
I checked that this code is also not being used in our other packages. ([Sourcegraph query](https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/.*%24+%28HasTypePred+OR+IsContextError%29&patternType=keyword&case=yes&sm=0))
> chore: Remove unused code in errors package

- cmd/enterprise-portal/internal/dotcomdb/BUILD.bazel
- cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
- cmd/enterprise-portal/internal/dotcomdb/dotcomdb_test.go
- cmd/enterprise-portal/service/BUILD.bazel
- cmd/enterprise-portal/service/dotcomdb.go
- cmd/enterprise-portal/service/service.go
- lib/managedservicesplatform/cloudsql/BUILD.bazel
- lib/managedservicesplatform/cloudsql/cloudsql.go
- lib/managedservicesplatform/runtime/contract/BUILD.bazel
- lib/managedservicesplatform/runtime/contract/postgresql.go
- sg.config.yaml
During manual testing for https://github.com/sourcegraph/sourcegraph/pull/62934, I started realizing that I would run into database errors:
```
failed to deallocate cached statement(s): conn busy
```
Turns out, `pgx.Conn` is meant for non-concurrent use. What we really want is a connection pool, with an off-the-shelf offering from `pgxpool`.
Integration tests pass, now with more cases using `t.Parallel()`. Also ran a quick sanity check by hand:
```
sg start
```
```
for i in {1..10}; do curl --header "Content-Type: application/json" --header 'authorization: bearer $SAMS_TOKEN' --data '{"filters":[{"filter":{"is_archived":false}}]}' \
http://localhost:6081/enterpriseportal.subscriptions.v1.SubscriptionsService/ListEnterpriseSubscriptionLicenses & ; done
```
- The MSP runtime …
> feat/msp: use pgxpool instead of pgx.Conn

- lib/background/background.go
Goroutines names are generally defined statically so there should be nothing sensitive in there; this makes Sentry reports on unhealthy service shutdown more usable, i.e. not all redacted like https://sourcegraph.slack.com/archives/C073F0EFB43/p1717173450559609
n/a
> feat/lib/background: mark goroutine names as safe for Sentry

- dev/managedservicesplatform/stacks/monitoring/monitoring.go
Minor QOL improvement, when you're in the Slack channel the chances are good that you might want the ops docs at some point.
n/a
- MSP-provisioned alerts Slack channels now include a link to the service's generated operational docs for a service (go/msp-ops) in the channel description.
> feat/msp: add link to ops page in Slack channel description

- WORKSPACE
- client/browser/BUILD.bazel
- client/browser/config/BUILD.bazel
- client/web/BUILD.bazel
- client/web/dev/BUILD.bazel
- dev/esbuild.bzl
- dev/mocha.bzl
1.6.0 is the minimum rules_esbuild version that support bazel-lib 2.x. After this lands, I'll put up a PR to get onto bazel-lib 2.x and after that lands that unblocks upgrading to rules_oci 2 which resolves at least some caching issues with large image artifacts.
Also pins the esbuild toolchain to esbuild 0.19.2 which should be a no-op since LATEST_ESBUILD_VERSION for rules_esbuild 0.15.3 (the version currently on main) is 0.19.2.
Both @Strum355 and I tried bumping to rules_esbuild 0.17.0+ and hit build issues (with and without the sandbox plugin enabled that was added in that version) so there is work to do there to track down what changed in the ruleset that breaks this build.
CI
> build(bazel): bump to rules_esbuild 0.16.0

- cmd/cody-gateway/internal/actor/limits.go
- cmd/cody-gateway/internal/actor/limits_test.go
- cmd/cody-gateway/internal/httpapi/completions/upstream.go
- cmd/cody-gateway/internal/httpapi/embeddings/handler.go
- cmd/cody-gateway/internal/httpapi/embeddings/models.go
- cmd/cody-gateway/internal/httpapi/handler.go
- cmd/cody-gateway/shared/config/config.go
In https://sourcegraph.slack.com/archives/C05SZB829D0/p1715638980052279 we shared a decision we landed on as part of #62263:
> Ignoring (then removing) per-subscription model allowlists: As part of the API discussions, we've also surfaced some opportunities for improvements - to make it easier to roll out new models to Enterprise, we're not including per-subscription model allowlists in the new API, and as part of the Cody Gateway migration (by end-of-June), we will update Cody Gateway to stop enforcing per-subscription model allowlists. Cody Gateway will still retain a Cody-Gateway-wide model allowlist. [@chrsmith](https://sourcegraph.slack.com/team/U061QHKUBJ8) is working on a broader design here and will have more to share on this later.
To support this, we first need to extend Cody …
> feat/cody-gateway: support wildcard models

- cmd/cody-gateway/internal/httpapi/completions/anthropic.go
- cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
- cmd/cody-gateway/internal/httpapi/completions/flagging.go
- cmd/cody-gateway/internal/httpapi/completions/flagging_test.go
- cmd/cody-gateway/internal/httpapi/completions/google.go
- cmd/cody-gateway/internal/httpapi/completions/openai.go
- cmd/cody-gateway/shared/config/config.go
Cody Gateway may "flag" a request as a way to either identify clearly abusive traffic, and reject it before it reaches an LLM, or to allow for further analysis.
This PR adds the ability to specify a set of model names, and Cody Gateway will in-turn flag all requests for that specific model. This adds another knob for being able to identify abusive behavior and/or confirm that any sudden spikes in a particular LLM model are for legitimate reasons.
With this PR no "default" is provided. And a follow-up PR will need to be made in the `infrastructure` repo to add model names as applicable.
- Part of https://linear.app/sourcegraph/issue/PRIME-263/flag-all-opus-all-gpt4-models-4o-4-turbo-etc.
- https://github.com/sourcegraph/abuse-ban-bot/pull/19, which updates the logic so that flagging a …
> feat(cody-gateway): Add FLAGGED_MODEL_NAMES check

- dev/managedservicesplatform/spec/environment.go
- dev/managedservicesplatform/stacks/cloudrun/internal/builder/job/job.go
In a rushed POC of MSP jobs, I did some pretty bad copy-pasting (evidenced by all the service-specific docstrings I have removed in this PR) and made a bad configuration decision here, resulting in a few issues:
1. `schedule.deadline` is not actually applied to Cloud Run jobs, causing jobs to time out earlier than desired
2. `schedule.deadline` is not the right place to configure a deadline, because _all_ jobs need a configurable deadline, not just those with schedules. This change moves `schedule.deadline` to `deadlineSeconds`.
Closes CORE-145
```
$ sg msp generate gatekeeper prod
$ git diff
```
```diff                    
diff --git a/services/gatekeeper/service.yaml b/services/gatekeeper/service.yaml
index fd6a3812..ce4b02e3 100644
--- a/services/gatekeeper/service.yaml
+++ …
```
> fix/msp: make deadlineSeconds job-level configuration, apply in timeout

- client/web/src/cody/isCodyEnabled.tsx
- client/web/src/repo/tree/TreePage.tsx
- client/web/src/site-admin/RepositoryNode.tsx
- client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
- client/web/src/site-admin/routes.tsx
This PR fixes a bug in the site admin UI where we showed references to
embeddings even when they were disabled in site config.
In follow-up work, we plan to remove the embeddings logic completely.
Closes https://github.com/sourcegraph/cody-issues/issues/50
Manually tested!
> Embeddings: hide site admin references

- client/web-sveltekit/src/auto-imports.d.ts
- client/web-sveltekit/src/lib/Icon2.module.scss
- client/web-sveltekit/src/lib/Icon2.svelte
- client/web-sveltekit/src/lib/KeyboardShortcut.svelte
- client/web-sveltekit/src/lib/Popover.svelte
- client/web-sveltekit/src/lib/TabPanel.svelte
- client/web-sveltekit/src/lib/Tabs.svelte
- client/web-sveltekit/src/lib/TabsHeader.svelte
- client/web-sveltekit/src/lib/codemirror/SearchPanelView.svelte
- client/web-sveltekit/src/lib/fuzzyfinder/FuzzyFinder.svelte
- client/web-sveltekit/src/lib/fuzzyfinder/FuzzyFinderContainer.svelte
- client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte
- client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
- client/web-sveltekit/src/lib/wildcard/Switch.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
- client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/RepositoryRevPicker.svelte
- client/web-sveltekit/src/routes/svelte-overrides.scss
Closes https://linear.app/sourcegraph/issue/SRCH-78/svelte-improve-repository-revision-picker-ui
Just a package of small fixes in different places (group them in one PR to avoid having a lot of super small PRs before the release. These fixes include
- Add keyboard support for tabs 
- Fixes opt-in/out tooltips delays
- Add close-on escape feature to fuzzy finder and popover components
- Fix sidebar filters panel shadow problem 
- Add shortcuts to repo revision popover tabs and history and references tabs
- Manual testing of all changes listed above
> Svelte: Paper cuts for 5.5 release

- lib/managedservicesplatform/runtime/BUILD.bazel
- lib/managedservicesplatform/runtime/contract/diagnostics.go
- lib/managedservicesplatform/runtime/contract/diagnostics_test.go
- lib/managedservicesplatform/runtime/job.go
Currently we have a Service runtime entrypoint which parses env, creates a logger, initialises telemetry, creates the MSP contract, etc. according to MSP conventions.
However we don't have the equivalent for Jobs which requires operators to set up everything manually. 
This PR remedies the situation by adding a Job entrypoint which performs similar setup to the Service entrypoint.
Closes CORE-117
Successfully executed a mock job in GCP using this as an entrypoint
> msp/runtime: add Job runtime

- cmd/frontend/internal/dotcom/productsubscription/BUILD.bazel
- cmd/frontend/internal/dotcom/productsubscription/subscriptions_graphql.go
Adds a simple metric tracking usage of `productSubscriptionByDBID`. All GraphQL resolvers in this package use this at some point (including the Cody Gateway access and licenses resolvers, which is surprising), so this is a good place to record it.
The goal is to use this to pare down traffic to this endpoint, and eventually remove it, as part of https://www.notion.so/sourcegraph/Establish-Enterprise-Portal-as-the-enterprise-integration-platform-261f0be5a4a040088eceb59c5ac4a8b3?pvs=4
n/a
> chore/productsubscription: add metric tracking usage

- docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
- docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
Fixes https://linear.app/sourcegraph/issue/GRAPH-642/scip-syntax-index-fails-for-relative-workspace-path
Run `scip-syntax --language java --workspace .` and get an index with documents
Run `scip-syntax --language java` and get an error, rather than an empty index
Internal change. Implements QoL changes to the `scip-syntax` CLI
> fix(scip-syntax): Fixes a couple CLI annoyances

- internal/appliance/reconciler/blobstore_test.go
- internal/appliance/reconciler/cadvisor_test.go
- internal/appliance/reconciler/codeintel_test.go
- internal/appliance/reconciler/gitserver_test.go
- internal/appliance/reconciler/helpers_test.go
- internal/appliance/reconciler/pgsql_test.go
- internal/appliance/reconciler/precise_code_intel_test.go
- internal/appliance/reconciler/prometheus_test.go
- internal/appliance/reconciler/redis_test.go
- internal/appliance/reconciler/repo_updater_test.go
- internal/appliance/reconciler/standard_config_test.go
- internal/appliance/reconciler/symbols_test.go
- internal/appliance/reconciler/syntect_test.go
We observed a rare test flake in
TestNonNamespacedResourcesRemainWhenDisabled in which non-namespaced resources were apparently not deleted when assertions were made against golden fixtures. My theory for why this was happening, is that there was a race between the test goroutine and the reconciler running in the background.
The reconciler actually appears to emit 2 events per configmap creation. The second is probably a result of updating the currentVersion annotation at the end of the reconcile loop, which itself triggers another reconcile loop.
Our test code was waiting for the initial resources to be created by waiting for at least one reconcile event to appear. It was then waiting for only one more event. When we got unlucky, this event would be the 2nd event from the 1st configmap …
> chore(appliance): fix race condition in tests

- dev/sg/interrupt/interrupt.go
Previously the interrupts where executed serially. Although _quick_ this was not quick enough! Since you if pressed `ctrl+c` rapidly not all hooks would get executed.
Hooks now get executed concurrently. In my own testing I could reliably get the orphaned process issue by just pressing `ctrl+c` twice. With this change, even pressing it very quickly - it still executed all hooks and thus all process where cleaned up.
Tested locally
> sg: speed up interrupt execution

- dev/sg/internal/release/calendar.go
- tools/release/config/calendar.jsonc
[Slack Context](https://sourcegraph.slack.com/archives/C02E4HE42BX/p1717378098939399)
This PR renames the `Code Freeze event` sent when `sg release cal` is run to `Branch Cut`. This naming change reflects the correct action carried out during this event.
The concept of a Code Freeze doesn't exist during a release.
Manual testing
- Rename the calendar event `Code Freeze:` to `Branch Cut:`
> feat(release): rename code freeze event to `branch cut` event

- internal/uploadhandler/BUILD.bazel
- internal/uploadhandler/upload_handler.go
- internal/uploadhandler/upload_handler_state.go
Fixes [GRAPH-615](https://linear.app/sourcegraph/issue/GRAPH-615/enable-traces-for-upload-operations-by-default)
We've been getting more i/o timeout errors and similar lately.
Let's enable traces so that we have more information to go on
when investigating these kinds of errors. It might take some
rounds of iteration with adding more events etc to figure out
what exactly is going wrong.
Locally changed the backend to `jaeger` and performed an upload.
The trace showed up while the "sampling" was set to "selective" (not "all").
- Tracing is enabled for all SCIP index uploads by default
> chore: Enable traces for uploads

- internal/api/api.go
- lib/codeintel/precise/util.go
There is also a [`cmp.Or` function](https://pkg.go.dev/cmp#Or) but since that's a function and
not a macro, it would cause all comparisons to always happen,
so we don't use that for chaining results.
> chore: Use new cmp package to simplify comparisons

- doc/admin/observability/alerts.md
- doc/admin/observability/dashboards.md
- monitoring/definitions/git_server.go
This removes the critical alert from the 1s echo test, since it has a tendency to wake someone up in the middle of the night and turns our alerts into noise.
The warning still remains.
Alert removed and docs updated.
> Remove echo test alert

- cmd/gitserver/internal/integration_tests/clone_test.go
- cmd/gitserver/internal/server.go
- cmd/gitserver/internal/server_test.go
- cmd/gitserver/internal/vcssyncer/git.go
We made this preflight check always, and the doc string said that it's for "better error messages".
I checked on that, and the additional RPS claim and the additional latency of the iscloneable check plus load on the code host don't seem justified.
Error message before this change:
```
Error updating repo:
failed to clone dev.azure.com/sourcegraph-source/src-cli/src-cli: error cloning repo: repo dev.azure.com/sourcegraph-source/src-cli/src-cli not cloneable: failed to check remote access: fatal: Authentication failed for 'https://dev.azure.com/sourcegraph-source/src-cli/_git/src-cli/': exit status 128
```
Error message after this change:
```
Error updating repo:
failed to clone dev.azure.com/sourcegraph-source/src-cli/src-cli: clone failed. Output: Creating bare repo Created bare repo at …
```
> gitserver: Remove IsCloneable check from clone path
