sourcegraph/sourcegraph-public-snapshot

cmd/repo-updater/internal/gitserver/BUILD.bazel
cmd/repo-updater/internal/gitserver/observability.go
cmd/repo-updater/internal/gitserver/repositoryservice.go
cmd/repo-updater/internal/purge/purge.go
cmd/repo-updater/internal/repoupdater/server.go
cmd/repo-updater/shared/main.go
doc/admin/observability/dashboards.md
monitoring/definitions/git_server.go
monitoring/definitions/repo_updater.go
monitoring/definitions/shared/gitserver.go

Since we split out this service, we lost a few metrics on call counts and latencies.
This PR adds them back.
Closes #62785
Test plan:
Ran the dashboards locally and they return data. These dashboards are a 1:1 replica of the git service observability.

gitserver: Add observability for repo service

---

docker-images/syntax-highlighter/crates/syntax-analysis/src/globals.rs

I was indexing some projects and occasionally it'd fail with 
```
thread 'main' panicked at crates/syntax-analysis/src/globals.rs:191:17:
declare only one scope per match
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
With no extra information, circumventing the error handling in the levels above.
This PR uses anyhow's helpers to ensure that the errors are propagated
- N/A

Use anyhow context, bail, and ensure instead of panicking

---

dev/sg/internal/release/calendar.go
tools/release/config/calendar.jsonc

Before this PR, the `sg release cal` command only allowed one patch release per monthly release. This isn't always the case as sometimes, we have multiple patches in a month.
This PR updates the calendar config to allow multiple patch release events. This changes the structure of the config object to 
```json
...
{
"name": "July 2024 Release",
"branchCutDate": "2024-07-02T09:00:00-07:00",
"monthlyReleaseDate": "2024-07-05T09:00:00-07:00",
"patchReleaseDates": ["2024-07-22T09:00:00-07:00"]
}
...
```
Manual testing
- Multiple patch events can now be created with the `sg release cal` command

feat(release): allow creation of multiple patch release events

---

lib/managedservicesplatform/go.mod
lib/managedservicesplatform/runtime/internal/opentelemetry/BUILD.bazel
lib/managedservicesplatform/runtime/internal/opentelemetry/metrics.go
lib/managedservicesplatform/runtime/internal/opentelemetry/tracing.go

Right now these emit a bunch of metrics and traces _for exporting metrics and traces_ that aren't very interesting. In particular they make the GCP console trace view very annoying to use because it's just filled with a bunch of "export trace" and "export metric" traces.
This disables telemetry for both. We only care about actual failures, which we do log.
https://sourcegraph.com/github.com/googleapis/google-api-go-client/-/blob/transport/grpc/dial.go?L362-367
n/a

chore/msp/runtime: disable telemetry on Google Monitoring/Trace APIs

---

dev/managedservicesplatform/internal/resource/alertpolicy/alertpolicy.go
dev/managedservicesplatform/spec/monitoring.go
dev/managedservicesplatform/stacks/monitoring/custom.go

Follow-ups for #62885:
- Better docstrings for `mql`, `promql`
- `duration` -> `durationMinutes` to align with other config
- `alertpolicy.ResponseCodeMetric` -> `spec.CustomAlertCondition`: they're effectively the same type
Test plan: CI

chore/msp/spec: tidy up custom alerts spec

---

cmd/frontend/graphqlbackend/external_service.go
cmd/frontend/graphqlbackend/external_services.go
cmd/frontend/graphqlbackend/external_services_test.go

Closes https://linear.app/sourcegraph/issue/SRC-359/
In the case where a user clicks on the "test connection" button and the:
1) The request never completed within 15 seconds
2) The request failed with a [net.DNSerror.isNotFound](https://pkg.go.dev/net#DNSError) error
One pretty good guess is that the code host is not actually accessible to Sourcegraph over the network. This PR tweaks the error message to add this hint + a link to our troubleshooting documentation. (See https://github.com/sourcegraph/docs/pull/374)
Screenshots of this:
Recordings:
1. Testing with a bad domain name
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/5VKJ5spRdhDRvKQ0TTIe/cac620ed-d7be-4129-99bd-a6b5f85c70f0.mov">
</a>
</div>
<video …

cmd: frontend: add note that clarifies that your code host needs to be accessible over the network to test connection button

---

cmd/frontend/internal/app/ui/app.html
doc/_resources/assets/docsite.js
doc/_resources/templates/root.html

Plausible is no longer being used, so this removes it from the web app.
Loaded the page, ensured I did not see any errors.

Chore: remove plausible scripts

---

internal/codeintel/codenav/commit_cache.go
internal/codeintel/codenav/internal/lsifstore/BUILD.bazel
internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
internal/codeintel/codenav/internal/lsifstore/scan.go
internal/codeintel/codenav/service_new.go

We have had this type around for a while, but a bunch of code still uses
`map[T]struct{}` which makes the code harder to read.

chore(codeintel): Simplify map[T]struct{} logic to use Set

---

client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
client/shared/src/search/helpers.ts
client/shared/src/search/stream.ts
client/web-sveltekit/BUILD.bazel
client/web-sveltekit/package.json
client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
client/web-sveltekit/src/lib/telemetry2.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/OpenInCodeHostAction.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/RepoSearchInput.svelte
client/web-sveltekit/src/routes/search/SearchHome.svelte
client/web-sveltekit/src/routes/search/SearchResults.svelte
client/web/src/search/helpers.tsx
pnpm-lock.yaml

Completes [SRCH-68](https://linear.app/sourcegraph/issue/SRCH-68/svelte-migrate-telemetry-service-to-v2-events)
This PR simply adds yet another telemetry v2 usage to the svelte FE client. 
Manual testing of newly added events

Svelte: Add telemetry v2 to svelte client

---

internal/collections/set.go
internal/collections/set_test.go

The name Contains is also commonly used for checking if a
set contains an element in other languages, so it leads to
confusing auto-complete. Additionally, IsSupersetOf sounds
more expensive, which may be the case for this operation.

chore: Rename Contains to IsSupersetOf

---

internal/codeintel/codenav/service_new.go
internal/codeintel/codenav/service_new_test.go
internal/codeintel/codenav/transport/graphql/iface.go
internal/codeintel/codenav/transport/graphql/mocks_test.go
internal/codeintel/codenav/transport/graphql/root_resolver_definitions.go

Implementing precise usages on top of the existing APIs becomes easier
if they're all of the same shape.

chore: Make GetDefinitions API consistent with GetReferences etc.

---

internal/codeintel/codenav/request_state.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_new.go
internal/codeintel/codenav/transport/graphql/observability.go
internal/codeintel/codenav/transport/graphql/root_resolver.go
internal/codeintel/codenav/transport/graphql/root_resolver_definitions.go
internal/codeintel/codenav/transport/graphql/root_resolver_ranges.go
internal/codeintel/codenav/types.go
internal/observation/BUILD.bazel
internal/observation/fields.go
internal/observation/fields_test.go

Moving the common observability attributes code into helper methods makes
reading the observation related code less painful.
TODO:
will end up creating a slice on seeing duplicate keys for the fields common between
RequestState and PositionalRequestArgs.
@Strum355, do you know why we keep multiple values for the same key instead
of having overwriting semantics? You added this behavior here:
https://github.com/sourcegraph/sourcegraph/pull/29652

chore: Simplify RequestState/PositionalRequestArgs o11y code

---

cmd/frontend/graphqlbackend/codeintel.codenav.graphql
internal/codeintel/resolvers/codenav.go

We can add support for optional start/end later
in a backwards-compatible way. Making these non-optional
helps simplify the initial implementation.
Check that `sg start enterprise-codeintel` works locally.

chore(codeintel): usagesForSymbol - make start/end non-optional for now

---

dev/sg/ci/BUILD.bazel
dev/sg/ci/command.go
dev/sg/ci/subcommands.go
dev/sg/internal/bk/bk.go

Add command to list builds in various states on a pipeline. This makes it ever so slightly for ops like scenarios like finding all running builds to cancel etc.
Tested locally
```
go run ./dev/sg ci list-builds --state 'running'
✅ Fetched 2 builds for "sourcegraph" pipeline
Pipeline: sourcegraph
Build   Status    Author                   Commit          Link
276911  running   William Bezuidenhout     9a8cc2303bd8... https://buildkite.com/sourcegraph/sourcegraph/builds/276911
276910  running   Greg Magolan             59be5e4415ff... https://buildkite.com/sourcegraph/sourcegraph/builds/276910
```
- add `list-builds` subcommand to sg to list builds in various states

feat(sg: add `list-build` subcommand to ci

---

client/web-sveltekit/src/lib/TreeNode.svelte
client/web-sveltekit/src/lib/TreeView.svelte
client/web-sveltekit/src/lib/wildcard/Button.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte

After the changes to the file tree layout in #62981, we can clean up the styles and DOM a bit. These changes are partially in prep for experimenting with alternative "current path" representations. Comments inline.
Manual testing. There should be no change in behavior, just DOM/style simplification.

Svelte: clean up file tree

---

dev/sg/internal/release/BUILD.bazel
dev/sg/internal/release/release.go
dev/sg/internal/release/release_registry.go

Added a small command to fetch a list of versions from the release registry
- Output the list of versions with some cherry picked information
- Allow one to output the list in json and since the _fancy_ stuff printed on stderr you can `sg release registry list --format json | jq '.[] | .version`
Tested locally
```
go run ./dev/sg release registry list
✅ Fetched 31 versions from release registry
ID  Product             Version     Created                SHA
42  docker              v5.4.4217   2024-06-01T00:06:23Z   8826b10639682f465d365f7957a0f71014135dce
41  sourcegraph         v5.4.4217   2024-05-31T23:20:01Z   21cfcfea8dcf31d2a2a9c39d67c1e154a8c0e6c9
40  sourcegraph         v5.4.3842   2024-05-29T21:04:17Z   17a5fdb1d280ffe99f352a05967dbb89a09d692e
39  k8s                 v5.4.3643 …
```

sg: add command to fetch versions from release registry

---

cmd/enterprise-portal/internal/codyaccessservice/v1.go
cmd/enterprise-portal/internal/subscriptionsservice/v1.go

Missed this in #63045 , we aren't actually registering our OTEL handler for Connect yet
Part of CORE-161
n/a

fix/enterpriseportal: fix registration of connectRPC handler options

---

cmd/repo-updater/internal/scheduler/BUILD.bazel
cmd/repo-updater/internal/scheduler/scheduler.go
cmd/repo-updater/internal/scheduler/scheduler_test.go
cmd/repo-updater/shared/main.go

Currently, when repo-updater restarts it loses all intel it collected over time. That causes a large flood of git fetch requests after it restarts. Every repo will be enqueued for an immediate update.
This PR fixes that by populating the scheduler with an initial delay per repo that is calculated with the same heuristic that the scheduler uses when it's fully warmed up.
This should avoid fetching git repos that are very stale (most likely the majority on instances with many repos).
Test plan:
Ran it locally, verified the scheduler state using the instrumentation tool for it, the schedule looks as expected and most repos aren't scheduled for the next 8h.

repo-updater: Hydrate schedule on startup

---

client/web-sveltekit/src/lib/repo/open-in-editor/OpenInEditor.svelte

The editor button would wrap before the div would overflow, causing weird wrapping. This fixes that and also makes it a proper button.
Before:
After:
Manual testing + screenshots above.

Svelte: fix editor button styling

---

dev/managedservicesplatform/internal/resource/alertpolicy/BUILD.bazel
dev/managedservicesplatform/internal/resource/alertpolicy/customalert.go
dev/managedservicesplatform/internal/resource/alertpolicy/customalert_test.go

The GCP monitoring alert configuration expects, for some reason, a single-line PromQL query only, otherwise the threshold doesn't work. In configuration, however, we may want to write a multi-line query, for ease of readability. This change automatically flattens the PromQL query into a single line and strips extra spaces.
Part of CORE-161
Unit tests

fix/msp: flatten custom alert promQL query for GCP

---

cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
cmd/cody-gateway/qa/BUILD.bazel
cmd/cody-gateway/qa/README.md
cmd/cody-gateway/qa/e2e_test.go
sg.config.yaml

This change makes Cody Gateway always apply a wildcard model allowlist, irrespective of what the configured model allowlist is for an Enterprise subscription is in dotcom (see #62909).
The next PR in the stack, https://github.com/sourcegraph/sourcegraph/pull/62912, makes the GraphQL queries return similar results, and removes model allowlists from the subscription management UI.
Closes https://linear.app/sourcegraph/issue/CORE-135
In https://sourcegraph.slack.com/archives/C05SZB829D0/p1715638980052279 we shared a decision we landed on as part of #62263:
> Ignoring (then removing) per-subscription model allowlists: As part of the API discussions, we've also surfaced some opportunities for improvements - to make it easier to roll out new models to Enterprise, we're not including …

feat/cody-gateway: use wildcard for enterprise allowlists

---

lib/managedservicesplatform/cloudsql/BUILD.bazel
lib/managedservicesplatform/cloudsql/cloudsql.go
lib/managedservicesplatform/cloudsql/tracer.go

This is a simplified version of what we have for in-Sourcegraph db connections as well. They're not directly compatible because we use `pgx` hooks.
n/a

chore/msp/runtime: add args as trace attributes, clean up tracing code

---

.aspect/bazelrc/local.bazelrc
WORKSPACE

`exclude_declarations_from_npm_packages` is not an option anymore as from the output
```
ERROR: @aspect_rules_js//npm:exclude_declarations_from_npm_packages :: Unrecognized option: @aspect_rules_js//npm:exclude_declarations_from_npm_packages
```
Also upgraded to `rc3` while diagnosing this.
Closes https://github.com/sourcegraph/devx-support/issues/1005
Tested locally + CI
```
sg bazel test //internal/appliance/reconciler:reconciler_test
INFO: Invocation ID: 70da4295-36f2-43a8-a71e-9b11ae489657
WARNING: Build option --modify_execution_info has changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
INFO: Analyzed target //internal/appliance/reconciler:reconciler_test (0 packages loaded, 17313 targets configured).
INFO: Found …
```

bazel: rules_js rc3 and remove deprecated "exclude_declarations" option

---

client/web/src/cody/onboarding/CodyOnboarding.tsx

Closes https://linear.app/sourcegraph/issue/PRIME-299/unable-to-sign-into-cody-account-via-github
The problem is that in some cases, the Cody Management page (https://courcegraph.com/cody/manage) doesn't redirect requests to the `returnTo` URL passed to it.
The situation when this occurs is when the user has not completed the Cody onboarding flow in the browser they are seeing the page.
History of the bug:
- Originally, it worked, but only because of an apparently accidental, transient state in [this line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/c5c199e7e06349db85c79b5ece6e31512b4a3ff6#diff-d14b1d38e01f8217c9e449122cad5122L104) where the variable `completed` was initialized with the value of `true`.
- I made a change in December (in …

Fix Cody onboarding redirect problem

---

WORKSPACE
client/testing/BUILD.bazel
dev/esbuild.bzl
dev/mocha.bzl
package.json
pnpm-lock.yaml
third_party/rules_esbuild/BUILD.bazel
third_party/rules_esbuild/sandbox-plugin-fixes.patch

Sandbox escapes be-gone
Tested in CI and locally with `bazel build //client/...` as well as a lot of blood, sweat n tears tearing through failed sandboxes

chore(bazel): enable rules_esbuild sandbox with object-inspect workaround

---

client/web/src/external-account-modal/ExternalAccountsModal.tsx
cmd/frontend/internal/app/jscontext/jscontext.go

When a Sourcegraph license is expired or revoked and the instance reverts to free license, then `authz` (for permissions syncing) stops working as well. This means that there are no AuthProviders set up and the front-end code has `null` for these values.
The issue arrises from unitialised arrays in Go being marshalled as `null` instead of `[]`. This PR initialises the array explicitly, instead of relying on the empty value.
Tested locally with a revoked license.

Initialise authProviders array in Go code

---

client/vscode/src/backend/authenticatedUser.ts
client/vscode/src/extension.ts
client/vscode/src/settings/accessTokenSetting.ts
client/vscode/src/webview/commands.ts
client/vscode/src/webview/platform/AuthProvider.ts

This one is straightforward: changing the spelling of a variable. 
As I poked around in the vscode extension looking for what's going on with the authentication errors, the misspelling of `scretTokenKey` became difficult to ignore. So I fixed it. :-D
1. Build and run locally.
```
pmpn run build
```
2. Launch extension in VSCode: open the `Run and Debug` sidebar view in VS Code, then select `Launch VS Code Extension` from the dropdown menu. Verify expected behavior.

cleanup: fix typo: scretTokenKey --> secretTokenKey

---

dev/managedservicesplatform/stacks/monitoring/BUILD.bazel
dev/managedservicesplatform/stacks/monitoring/dashboard.go
dev/managedservicesplatform/stacks/monitoring/dashboard_test.go
dev/managedservicesplatform/stacks/monitoring/monitoring.go

1. The dashboard link still points to the old `go/msp-ops/...` which no longer work (CORE-105)
2. Alerts defined on top of the MSP defaults are probably of more interest, so let's sort these in front of the others
Unit/golden tests

feat/msp: update handbook link in alerts dashboard, sort custom alerts first

---

internal/completions/client/google/google.go
internal/completions/client/google/types.go

Add the missing `Model` field to the `googleRequest` struct to include the model name in the request to the Cody Gateway completion API.
This change ensures that the model name is properly included in the request, which is necessary for Cody Gateway to function correctly.
Verified connection to Gemini API directly works:
```sh
❯ curl -X 'POST' -d '{"messages":[{"speaker":"human","text":"Who are you?"}],"maxTokensToSample":30,"temperature":0,"stopSequences":[],"timeoutMs":5000,"stream":true}' -H 'Accept: application/json' -H 'Authorization: token $LOCAL_SG_TOKEN' -H 'Content-Type: application/json' 'https://sourcegraph.test:3443/.api/completions/stream?client-name=web'
```
Response:
```
event: completion
data: {"completion":"I","stopReason":"STOP"}
event: completion
data: {"completion":"I …
```

fix(Cody Gateway): add model field to Google completion request

---

dev/sg/cloudsqlproxy/cloudsqlproxy.go
dev/sg/msp/helpers.go
dev/sg/msp/sg_msp.go

I think finding the right permissions confuses people pretty often when first interacting with MSP. This adds a helper for annotating errors returned from points where we might be able to help out @DaedalusG, specifically for the situation in https://sourcegraph.slack.com/archives/C05GJPTSZCZ/p1717629546727829 😉 
It's a little wordy but:
```
sg msp pg connect sams prod
❌ possible permissions error, ensure you have the prerequisite Entitle grants mentioned in https://sourcegraph.notion.site/3e59b9ac3d414a5f8fb5911eed1e418a: find IAM output: gcloud: failed to access secret "iam_operator_access_service_account" from "sams-prod-ywuz": rpc error: code = PermissionDenied desc = Permission 'secretmanager.versions.access' denied for resource …
```

feat/sg-msp-pg: add suggestion to check msp-ops page on perms error

---

release.yaml

This PR will allow us to rerun failures in the last step of a release. Currently if release promotion fails during the git:tag step of finalize promotion we can't delete the tag in the remote repo and rerun the step, this suspected to be due to caching in the pipeline. 
See: https://buildkite.com/sourcegraph/sourcegraph/builds/277241#018feb0e-6800-4148-b83c-70f27b68094d
untested
- add force flag in git tag during finalize release promotion

fix(release): allow release tooling to rerun finalize promotion on err

---

release.yaml

Generate notes currently generates a changelog all the way from the tag `app-2023` ... which means the content is more than what is allowed by github - hard cap of 125000 characters.
CI
- remove `generate-notes` cli flag when promoting releases
- push only a single tag
- fix token name used in changelog generation

fix(release): remove generate-notes from github release creation

---

CHANGELOG.md
cmd/frontend/internal/auth/scim/BUILD.bazel
cmd/frontend/internal/auth/scim/user.go
cmd/frontend/internal/auth/scim/user_service.go
cmd/frontend/internal/auth/scim/user_test.go
cmd/frontend/internal/auth/scim/user_update_action.go

In the current implementation, we check if there's a user in the database already, and if so we add a random suffix to increase the chances of the insert/update to succeed.
However, we didn't check if the user that already exists is _the same user_. So for a first sync, usernames would look nice and tidy, but then on a second sync from the SCIM provider, every user would get a suffix.
This PR fixes that by adding a check for the user ID.
Test plan:
Added tests, verified SCIM sync doesn't modify usernames anymore locally.

scim: Fix random suffix added to every user on resync

---

.tool-versions
WORKSPACE
dev/ci/images/go.mod
go.mod
internal/cmd/progress-bot/go.mod
lib/go.mod

Bump for @evict 
CI passes with no complaints
- Bumped version of Go used to build to 1.22.4

chore(tooling): bump Go version to 1.22.4

---

dev/sg/internal/cloud/build_command.go
dev/sg/internal/cloud/deploy_command.go

Triggering cloud ephemeral builds on main is problematic since there are a bunch of specific conditions that get triggered because the branch is `main`
Tested locally
`sg cloud eph build`
```
./sg cloud eph build
⚠️ Triggering Cloud Ephemeral builds from "main" is not supported.
Alternatively, if you still want to deploy "main" you can do:
1. create a new branch off main by running  git switch <branch-name>
2. push the branch to the remote by running  git push -u origin <branch-name>
3. trigger the build by running  sg cloud ephemeral build
❌ failed to trigger epehemeral build for branch: cannot trigger a Cloud Ephemeral build for main branch
```
`./sg cloud eph deploy`
```
⚠️ Triggering Cloud Ephemeral builds from "main" is not supported.
Alternatively, if you still want to deploy "main" …
```

sg: deny cloud ephemeral builds from main

---

client/web-sveltekit/src/app.prod.html
client/web/dev/esbuild/server.ts
cmd/frontend/internal/app/ui/app.html
cmd/frontend/internal/app/ui/handlers.go
cmd/frontend/internal/app/ui/sveltekit/sveltekit.go
sg.config.yaml

This modifies our pattern for shipping a svelte-enabled HTML document by injecting the svelte-specific things into our primary `app.html` rather than trying to make `app.prod.html` match the behavior of the frontend `app.html`.
I could not figure out a "blessed" way to integrate this into the build system, so I went for the hacky way: render `app.prod.html` in a format that's easily parseable, then parse it in `frontend` and inject it into our `app.html` with the standard go template patterns.
Fixes SRCH-76
Manual testing with `sg start enterprise` and `sg start enterprise-sveltekit`. Manual inspection of the generated HTML and diffing against the previously generated HTML.

Svelte: inject into primary `app.html`

---

cmd/frontend/graphqlbackend/user.go
cmd/frontend/graphqlbackend/user_test.go

Previously it was possible to use the `updateUser` mutation to change user fields for SCIM managed users. We now reject these changes if the user is SCIM managed.
CI tests

fix(SCIM): don't allow SCIM users to change fields

---

docker-images/syntax-highlighter/Cargo.Bazel.lock
docker-images/syntax-highlighter/Cargo.lock
docker-images/syntax-highlighter/Cargo.toml
docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel
docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/io.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
docker-images/syntax-highlighter/crates/scip-syntax/testdata/package-info.java
docker-images/syntax-highlighter/crates/scip-syntax/tests/integration_test.rs
docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__java_files_indexing.snap
docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__java_tar_file_indexing.snap
docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__java_tar_stream_indexing.snap
docker-images/syntax-highlighter/crates/scip-syntax/tests/snapshots/integration_test__java_workspace_indexing.snap

Fixes GRAPH-651
Fixes GRAPH-650
New features:
- `index tar <input>` allows indexing tar archives when `input` is a file, and `stdin` when `input` is literal string `-`
- **BREAKING: Instead of flags controlling the type of input source, we now have subcommands: `index files`, `index workspace`, `index tar`**
Refactoring:
- Tests were improved, with helper functions broken down into composable pieces, and producing 1 snapshot per test, making it easier to manage
- Closures were removed from the indexing code, instead replaced with functions.
- Calls to `.unwrap` were replaced with better error handling code
- Path canonicalisation was replaced with path cleanup + absolutisation - to avoid following symlinks (which is what `canonicalize` would do)
Most of the refactoring was triggered by …

Syntactic Indexing: add TAR archive indexing mode to scip-syntax CLI

---

client/web-sveltekit/src/hooks.test.ts
client/web-sveltekit/src/hooks.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/tree/[...path]/+page.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.ts
client/web-sveltekit/src/routes/layout.spec.ts

Fixes SRCH-484. See that issue for more information about the problem.
Instead of hardcoding the routes that can contain file paths, I'm using the generated list of routes in `routes.ts` and extract any route that ends with a `[...path]` segment (which, so far at least, is used as the file path parameter).
This list is then used to hook into the routing process and encode the file path when any of the routes match. As mentioned in the `reroute` documentation, this does not affect the URL displayed in the browser. Because the file path is now URL encoded we need to decode it before we can process it further (I grepped for all occurrences of `params.path`). 
E.g. for https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web-sveltekit/src/routes/[...repo=reporev …

fix(search): Properly handle URLs with file paths that contain route segments

---

internal/database/external_accounts_test.go
internal/database/migration/shared/data/stitched-migration-graph.json
internal/database/schema.json
internal/database/schema.md
internal/users/stats.go
migrations/frontend/1717699555_fix_unique_index_for_scim_external_account_connection/down.sql
migrations/frontend/1717699555_fix_unique_index_for_scim_external_account_connection/metadata.yaml
migrations/frontend/1717699555_fix_unique_index_for_scim_external_account_connection/up.sql
migrations/frontend/squashed.sql

When the user external account entry for SCIM has been deleted in the past, updating the user again fails as the deleted record is found and then the insertion fails.
This PR fixes that by adjusting the unique index to only consider non-soft-deleted external accounts.
Closes SRC-383
Test plan:
Added a test suite for the DB method - it was untested before :(

scim: Fix user updates when SCIM was previously enabled

---

cmd/enterprise-portal/internal/codyaccessservice/v1.go
cmd/enterprise-portal/internal/samsm2m/samsm2m.go
cmd/enterprise-portal/internal/samsm2m/samsm2m_test.go
cmd/enterprise-portal/internal/subscriptionsservice/BUILD.bazel
cmd/enterprise-portal/internal/subscriptionsservice/v1.go

As we prepare to roll out https://github.com/sourcegraph/sourcegraph/pull/62934, this adds rudimentary audit logging that records the client and some session details on successful data access at the end of the RPC. The GraphQL resolvers generate an audit log on every resolver, so this maintains some parity.
I'm not sure there's a good way to generalize this better and reduce copy-pasta, open to ideas
n/a just logging additions

feat/enterprise-portal: rudimentary audit logging

---

dev/eslint.bzl

This regressed in https://github.com/sourcegraph/sourcegraph/pull/63022 where the custom `gather_files_from_js_providers` function that was copied over from rules_js 1.x was including runfiles (which would have also included all sources & transitive source implicitly as well).
Resolves eslint failures seen in https://buildkite.com/sourcegraph/sourcegraph/builds/277072#018fe743-abac-44d8-911b-d5a7ed425413 and observed locally:
```
(07:19:15) INFO: From ESLint client/wildcard/wildcard_lib_eslint-output.txt:
  |  
  | Oops! Something went wrong! :(
  |  
  | ESLint: 8.57.0
  |  
  | ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:
  |  
  | npm init @eslint/config
  |  
  | ESLint looked for configuration files in …
```

build(bazel): fixup custom eslint test rule after bump to rules_js 2

---

cmd/frontend/graphqlbackend/user.go
cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user_test.go
cmd/frontend/internal/httpapi/completions/limiter.go

See [this Slack thread](https://sourcegraph.slack.com/archives/C06062P5TS5/p1717624627412939) for some more context on this change.
Somebody pointed out that there is a Sourcegraph.com feature flag that appears to allow a user to bypass any Cody Pro rate limits that are imposed. (This was originally added in https://github.com/sourcegraph/sourcegraph/pull/58591 to facilitate testing when user limits were a new thing.)
However, at this point that capability has proven itself and so this escape hatch is no longer needed. However it sounds like this may never have worked correctly on Cody Gateway, by virtue of when feature flags get materialized, and where the specific Cody Gateway API call is made. ([Slack](https://sourcegraph.slack.com/archives/C06062P5TS5/p1717656566799539?thread_ts=171762 …

Remove references to 'rate-limits-exceeded-for-testing' feature flag

---

client/web-sveltekit/src/auto-imports.d.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte

See title.
Contributes to SRCH-467
| ![2024-06-06_19-11_1](https://github.com/sourcegraph/sourcegraph/assets/179026/cdecfff5-6e1e-468f-a9fe-364fee5b5cc9) | ![2024-06-06_20-30](https://github.com/sourcegraph/sourcegraph/assets/179026/f89fed96-b0c6-4dac-8eea-29f4d84fa2ec) |
Visual inspection.

svelte: Migrate repo sidebar toggle button to use lucide icon

---

client/wildcard/src/global-styles/highlight.scss
docker-images/syntax-highlighter/crates/syntax-analysis/queries/javascript/highlights-jsx.scm
docker-images/syntax-highlighter/crates/syntax-analysis/queries/tsx/highlights.scm
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/react.jsx
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/react.tsx
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__react.jsx.snap
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__react.tsx.snap

Update JSX/TSX highlighting to identify tag delimiters properly. 
- Unit tests pass
- Inspect snap file
- Update highlighting of JSX/TSX Tags to correctly label delimiters

fix(highlighting): Update JSX/TSX highlighting to more properly label tag  delimiters

---

CHANGELOG.md

Update changelog for 5.4 release to include the fix we did in https://github.com/sourcegraph/sourcegraph/pull/62345 and addressing feedback that I missed.

chore(graph): Add changelog entry for Python scip-ctags fix (second attempt)

---

cmd/gitserver/shared/BUILD.bazel
cmd/gitserver/shared/shared.go
cmd/gitserver/shared/testserver.go
cmd/symbols/gitserver/BUILD.bazel
cmd/symbols/gitserver/client.go
cmd/symbols/shared/BUILD.bazel
cmd/symbols/shared/main.go
dev/gitserverintegration/BUILD.bazel
dev/gitserverintegration/testtools.go
dev/rockskipintegration/BUILD.bazel
dev/rockskipintegration/main_test.go
internal/gitserver/v1/BUILD.bazel

This PR tinkers a bit with building a test helper to run integration tests that are still ~lightweight against a real gitserver.
The caller can either clone a real repo to disk / embed it in the git repo, or can create a small repo on the fly, and then get a running gitserver gRPC server that returns all the data required.
These tests should only exist outside of cmd/ and internal/, as there is a big potential to do cross-cmd imports from here, which can cause bad coupling. But for just these tests, that should be fine.
The most trivial rockskip indexing job that I put in here to POC this runs in 6.3s, including all setup and teardown. That seems very reasonable to me.
Test plan:
The POC test passes.

gitserver: Framework to support integration testing against gitserver

---

cmd/gitserver/internal/server_grpc.go

I think we do a decent job now, and most errors are properly converted with very few unknown errors returned, so I don't think this TODO is needed anymore.
Test plan:
CI passes after removal of comments.

gitserver: Remove comment about error checking

---

cmd/executor/docker-mirror/_ami.build.sh
cmd/executor/docker-mirror/_ami.push.sh
cmd/executor/vm-image/_ami.build.sh
cmd/executor/vm-image/_ami.push.sh
dev/ci/internal/ci/executor_operations.go

the executor image and docker mirror image should now follow the following naming convention:
Image family: `sourcegraph-executors-[nightly|internal|'']-<MAJOR>-<MINOR>`
Image name: `sourcegraph-executor-[nightly|internal|'']-<MAJOR>-<MINOR>-<BUILD_NUMBER>`
example:
Image family: `sourcegraph-executors-5-4`
Image name: `sourcegraph-executor-5-4-277666`
**`nightly` suffix**
Image family: `sourcegraph-executors-nightly-<MAJOR>-<MINOR>`
Image name: `sourcegraph-executor-nightly-<MAJOR>-<MINOR>-<BUILD_NUMBER>`
**`internal` suffix**
Image family: `sourcegraph-executors-internal-<MAJOR>-<MINOR>`
Image name: `sourcegraph-executor-internal-<MAJOR>-<MINOR>-<BUILD_NUMBER>`
** No suffix **
Image family: `sourcegraph-executors-<MAJOR>-<MINOR>`
Image name: …

release: never use build number in image family

---

client/web-sveltekit/src/lib/Popover.svelte
client/web-sveltekit/src/lib/TreeNode.svelte
client/web-sveltekit/src/lib/TreeView.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte

This updates the `Popover` component to accept a passed-in target rather than setting the target via an action. This allows us to pass in targets not owned by the `Popover` component, which is important for things like the file tree where the logical target is a wrapper around what the consumer has access to.
Manually tested. [Video walkthrough](https://share.cleanshot.com/K29H6Mvw).

Svelte: allow popovers to have external targets

---

cmd/enterprise-portal/internal/codyaccessservice/BUILD.bazel
cmd/enterprise-portal/internal/codyaccessservice/adapters.go
cmd/enterprise-portal/internal/codyaccessservice/adapters_test.go

I was doing a more in-depth, final check between the state of sync in dotcom and in Enterprise Portal, and found a discrepancy: we only return attributes if access is enabled, but there are Cody Gateway features that are enabled _even if Cody Gateway access is disabled_. This was also called out in https://github.com/sourcegraph/sourcegraph/pull/62934#discussion_r1625142452
See my comment in CORE-98 here: https://linear.app/sourcegraph/issue/CORE-98/enterprise-portal-use-portal-from-cody-gateway#comment-80991a40
Basic unit test to make sure the constructor doesn't blow up on any nil fields

feat/enterprise-portal: return all attributes, even when access is disabled

---

cmd/enterprise-portal/internal/codyaccessservice/adapters.go
cmd/enterprise-portal/internal/codyaccessservice/adapters_test.go
cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go

Quick fix in prep for rollout of https://github.com/sourcegraph/sourcegraph/pull/62934 - see https://linear.app/sourcegraph/issue/CORE-98/enterprise-portal-use-portal-from-cody-gateway#comment-1d627e80
Unit test

fix/enterprise-portal: ignore empty hashes for Cody Gateway access tokens

---

dev/ci/msp_deploy.sh

Encodes the commit_message as base64 to avoid issues with special characters breaking the deploy command
Part of CORE-172
CI
[_Created by Sourcegraph batch change `jac/msp-rollout-base64`._](https://sourcegraph.sourcegraph.com/users/jac/batch-changes/msp-rollout-base64)

msp/deploy: encode commit_message as base64

---

cmd/cody-gateway/internal/httpapi/completions/google.go
cmd/cody-gateway/internal/httpapi/completions/google_test.go

CONTEXT: https://sourcegraph.slack.com/archives/C05ABRRGB0B/p1717790701356599
Fix an issue where a valid Gemini response ends with new lines, causing a false alert.
Issue: We are seeing `*errutil.leafError: no Google response found` in Sentry complaining  when I run a command or chat in VS Code using google as provider.
Cause: Currently the code (added my me) would skip to the last line of the stream response and determine if the response is valid or not, which could be an issue because the stream API could ends the response with an empty new line, where our current logic would fail.
Changes included in this PR:
- Modify `parseGoogleTokenUsage` function to find the last non-empty line in the stream, to handle cases where the stream ends with a newline
- Add a test case to cover the …

Cody Gateway: handle streams with trailing newline in Gemini response

---

cmd/enterprise-portal/internal/database/migrate.go

Part of CORE-176
Reported in https://sourcegraph.slack.com/archives/C04MYFW01NV/p1718019777829589, let's disable DB migrate to prevent more people hitting into this.
`sg run enterprise-portal` starts without a local database named `enterprise-portal`.

enterprise-portal: temporarily disable local DB migrate

---

client/web/src/cody/team/TeamMemberList.tsx

Before this PR, the "Make admin" and "Revoke admin" button actions failed with an error.
Now they both work.
Tested both buttons, they work as they should:
(Note: the design is to be tweaked)
fix(plg): fixed "Make admin" and "Revoke admin" button actions

SSC: Fix "Make admin" and "Revoke admin" button actions

---

client/web/src/cody/subscription/CodySubscriptionPage.tsx

The "Create team" and "Upgrade to Pro" links currently point to the old SSC site.
This PR makes both of them point to the new PLG checkout experience, behind the feature flag.
Tested it manually, both buttons work now as they should
fix(plg): make upgrade links point to the right pages for Teams & Invites

SSC: Fix checkout links

---

client/web-sveltekit/src/lib/Popover.svelte

Closes [SRCH-504](https://linear.app/sourcegraph/issue/SRCH-504/popover-click-triggers-are-no-longer-working-properly) 
It seems that this problem was caused by slipped-out showOnHover check for hover-based trigger event listeners 
Manual testing

[Svelte]: Fix standard click-based popover flow

---

go.mod
internal/memcmd/BUILD.bazel
internal/memcmd/observer.go
internal/memcmd/observer_darwin.go
internal/memcmd/observer_darwin_test.go
internal/memcmd/observer_example_test.go
internal/memcmd/observer_linux.go
internal/memcmd/observer_linux_test.go
internal/memcmd/observer_test.go

This PR adds a new package memcmd, that adds a new abstraction called "Observer" that allows you to track the memory that a command (and all of its children) is using. (This package uses a polling approach with procfs, since [maxRSS on Linux is otherwise unreliable](https://jkz.wtf/random-linux-oddity-1-ru_maxrss) for our purposes).
Example usage
```go
import (
"context"
"fmt"
"os/exec"
"time"
"github.com/sourcegraph/sourcegraph/internal/memcmd"
)
func Example() {
const template = `
#!/usr/bin/env bash
set -euo pipefail
word=$(head -c "$((10 * 1024 * 1024))" </dev/zero | tr '\0' '\141') # 10MB worth of 'a's
sleep 1
echo ${#word}
`
cmd := exec.Command("bash", "-c", template)
err := cmd.Start()
panic(err)
}
observer, err := memcmd.NewLinuxObserver(context.Background(), cmd, …
```

feat/internal/memcmd: add internal/memcmd package to allow for memory tracking of exec.Cmd  processes

---

client/web/src/repo/stats/RepositoryStatsContributorsPage.tsx

Fixes SRCH-497
The contributors page currently fails to load properly because we are passing an empty date string by default. This fixes it.
https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/stats/contributors loads without error

fix(search): Contributors page errors with empty date string

---

client/web-sveltekit/package.json
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts

Closes SRCH-496
#63128 added a dedicated button for closing the bottom panel but clicking the button didn't cause the diff view to close. This commit fixes that.

fix(search/svelte): Hide diff view when closing bottom panel

---

WORKSPACE
doc/dev/background-information/bazel/containers.md
doc/dev/background-information/bazel/faq.md
doc/dev/background-information/sg/index.md
docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel
sg.config.yaml

Follow up https://github.com/sourcegraph/sourcegraph/pull/63085
rules_oci 2.0 brings a lot of performance improvement around oci_image and oci_pull, which will benefit sourcegraph. It will also make RBE faster and have less load on remote cache. 
However, 2.0 makes some breaking changes like 
- oci_tarball's default output is no longer a tarball
- oci_image no longer compresses layers that are uncompressed, somebody has to make sure all `pkg_tar` targets have a `compression` attribute set to compress it beforehand. 
- there is no curl fallback, but this is fine for sourcegraph as it already uses bazel 7.1.
I checked all targets that use oci_tarball as much as i could to make sure nothing depends on the default tarball output of oci_tarball. there was one target which used the default …

refactor: upgrade to rules_oci 2.0

---

dev/sg/internal/cloud/deploy_command.go
dev/sg/internal/cloud/upgrade_command.go

Encountered this error while doing my demo
```
{"SeverityText":"ERROR","Timestamp":1718110348252114099,"InstrumentationScope":"mi2.instance.create","Caller":"mi2/instance.go:478","Function":"main.glob..func26","Body":"new instance validation failed: slug (displayName) must be between 4 to 30 characters. Allowed characters are: lowercase letters, numbers, hyphen. Current: christoph-resolve-syntactic-symbol-at-request-range","Resource":{"service.name":"mi2","service.version":"2024-06-11-09-50-
```
So now we limit it to 30 chars and print a notice to inform the user that it has been truncated
Tested locally
```
go run ./dev/sg cloud eph deploy --name 'christoph-resolve-syntactic-symbol-at-request-range_277899_2024-06-11_5.4-f04d3b973a19' --version …
```

sg: cloud eph - set max deployment name

---

lib/managedservicesplatform/runtime/contract/BUILD.bazel
lib/managedservicesplatform/runtime/contract/contract.go
lib/managedservicesplatform/runtime/contract/postgresql.go

Closes https://linear.app/sourcegraph/issue/CORE-168
```
[enterprise-...l] DEBUG pgx.devtracer.enterprise-portal contract/postgresql.go:157 pgx.QueryStart
[enterprise-...l] ---
[enterprise-...l] SELECT count(*) FROM pg_indexes WHERE tablename = $1 AND indexname = $2 AND schemaname = CURRENT_SCHEMA()
[enterprise-...l] ---
[enterprise-...l]  {"args": ["{\"1082\":1,\"1114\":1,\"1184\":1,\"16\":1,\"17\":1,\"20\":1,\"21\":1,\"23\":1,\"26\":1,\"28\":1,\"29\":1,\"700\":1,\"701\":1}", "\"permissions\"", "\"idx_permissions_namespace\""]}
[enterprise-...l] DEBUG pgx.devtracer.enterprise-portal contract/postgresql.go:163 pgx.QueryEnd {"commandTag": "SELECT 1", "error": "<nil>"}
[enterprise-...l] DEBUG pgx.devtracer.enterprise-portal contract/postgresql.go:157 pgx.QueryStart
[enterprise-...l] --- …
```

feat/msp/runtime: PG_QUERY_LOGGING=true for local dev query logging

---

go.mod
internal/memcmd/BUILD.bazel
internal/memcmd/observer_linux.go
internal/memcmd/observer_linux_test.go

There was a goroutine leak in the Linux observation logic. 
https://github.com/sourcegraph/sourcegraph/blob/add4baa455ef86d60b59f7c0182839a7bb2a9e18/internal/memcmd/observer_linux.go#L122-L141
In observe, it was possible for the goroutine that produces collection events on a channel to block forever. If we exit early from the function, it was still possible for the channel to be full (because the consumer exited early), which causes the producer goroutine to block forever since there is no room in the channel. 
This PR fixes this issue by adding a `defer` statement that ensures that collection channel is drained before we exit - thus fixing the leak.
Added goroutine leak dector to linux tests - now see them pass.
A goroutine leak in the experimental linux memory observation logic has been …

fix/internal/memcmd: fix goroutine leak in linux observer

---

internal/memcmd/BUILD.bazel
internal/memcmd/observer_linux.go
internal/memcmd/observer_linux_test.go

This PR tweaks the memory observer implementation to ignore context cancellation if they only occurred if we explicitly called Stop (which calls the context's cancellation function). This helps to reduce logspam.
Unit tests
- Slightly improve logspam from Linux memory observation logic by ignoring context cancellation errors that occur when the user explicitly stopped the observer.

feat/internal/memcmd: ignore context cancellation errors from Stop()

---

cmd/gitserver/internal/git/gitcli/command.go

This PR changes the behavior of the git cli commands to ignore errors from the memory observer if they occurred due to cancellation. Such errors are expected if the user cancels the request, and so there is no reason to generate logspam.
Existing CI tests
This PR only reduces logspam, and as such doesn't need extensive new unit tests.
- Reduce logspam in the gitserver command functionality by ignoring memory observation errors if they occurred due to external context cancellation.

feat/gitserver: don't log memoryObservation error if it occured b/c context cancellation

---

doc/dev/how-to/cody_gateway.md

With these additions, the instructions on how to run Cody Gateway locally should be correct now.
The proposed changes work for me locally.

Extend instructions for running CG locally

---

internal/codeintel/codenav/transport/graphql/BUILD.bazel
internal/codeintel/codenav/transport/graphql/root_resolver.go

The function already has an earlier exit if `len(uploads) == 0`,
and packages have been removed/disabled.
n/a

chore: Remove dead code for Rust crates

---

cmd/frontend/graphqlbackend/batches.go
cmd/frontend/graphqlbackend/file.go
cmd/frontend/graphqlbackend/git_tree_entry.go
cmd/frontend/graphqlbackend/repository_comparison_test.go
cmd/frontend/graphqlbackend/virtual_file.go
cmd/frontend/internal/batches/resolvers/batch_spec_workspace_file.go
cmd/frontend/internal/batches/resolvers/batch_spec_workspace_file_test.go
internal/codeintel/resolvers/git.go
internal/codeintel/shared/resolvers/gitresolvers/tree_entry.go

In our backend, we mostly follow the convention that type names
for the resolvers match up with the types in the GraphQL API,
with the extra `Resolver` suffix. However, this is broken by the
`GitTreeEntryResolver` where there were no types called
`GitBlobResolver` or `GitTreeResolver`, since all functionality
was implemented on top of `GitTreeEntryResolver`.
Since Go supports implicit method forwarding for embedded structs,
I think we can improve the code consistency & readability by adding
these two stub resolver types.
As struct embedding is not a super common pattern, I've explicitly
mentioned that in the doc comments for `GitBlobResolver` and
`GitTreeResolver`.
Should be covered by existing tests.

chore: Add GitBlobResolver and GitTreeResolver for readability

---

internal/memcmd/observer_linux.go

This PR tweaks the logic in the linux memory observer that skips over context cancellation errors that occur when we deliberately stop the observer.
https://github.com/sourcegraph/sourcegraph/blob/553b5c55ac60986a3b8d3a1a0ba8b3118f94731b/internal/memcmd/observer_linux.go#L156-L172
Before it was possible for the above code to run after the context was cancelled, but before the explicitlyStopped channel was closed. This would cause the function to incorrectly keep the context cancellation error.
Now, we make sure to close the channel _before_ canceling the context in Stop - thus fixing the above issue. 
Existing unit tests (you can't really test a race condition like this).
This PR fixes a logspam bug in the linux memory observer that was due to do slightly faulty synchronizzation logic.

fix/internal/memcmd: close the explicit stop channel before cancelling context

---

cmd/gitserver/internal/git/gitcli/command.go
cmd/gitserver/internal/git/gitcli/command_test.go

This PR tweaks the logic in the gitserver new command logic to avoid printing errors from the memory observer if the context error is deadline exceeded.
Unit tests
- In the gitserver new command logic, logspam from the memory observer when the context error is deadline exceeded will no longer occur.

feat/gitserver: avoid logspam from deadline exceeded memory tracking errors

---

client/web-sveltekit/src/lib/search/resultsIndicator/ProgressMessage.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte

Fixes srch-516
Using vite's inspect plugin I found out that we are importing a lot of unnecessary components again, including `@sourcegraph/wildcard` and `@sourcegraph/branded`:
By removing those dependencies we speed up the development build significantly.
| ![2024-06-12_17-24](https://github.com/sourcegraph/sourcegraph/assets/179026/1d3935af-6dcf-4e35-9d0c-f8a2439e3757) | ![2024-06-12_17-40](https://github.com/sourcegraph/sourcegraph/assets/179026/ca5978f2-5109-4e37-91ea-16c96902511d) | 
| ![2024-06-12_17-27](https://github.com/sourcegraph/sourcegraph/assets/179026/fce354d6-01ca-4f93-9049-bdb7611e1231) | ![2024-06-12_17-39](https://github.com/sourcegraph/sourcegraph/assets/179026/f511a17a-c660-4423-bdba-133d43896e17) |
`pnpm build`

chore(search/svelte): Remove dependencies on barrel files to speed up dev build

---

client/web-sveltekit/BUILD.bazel
client/web-sveltekit/package.json
client/web-sveltekit/src/auto-imports.d.ts
client/web-sveltekit/src/lib/wildcard/language-icons.ts
pnpm-lock.yaml

Fixes GRAPH-620
Adds the icon for the Hack language to the Svelte UI
- Validate on UX
- Ensure client side tests pass
- Adds icon for the Hack language

feat(Search): Add icon for the Hack language

---

client/web/src/cody/team/TeamMemberList.tsx

The "Remove" button on the `/cody/team/manage` page didn't remove the user.
Turns out we made the wrong API call. Not sure if the state before this PR was a total hallucination or if it worked well with an earlier, WIP version of the API. But this PR fixes it in any case.
- **Note:** we still don't have a confirmation modal or similar for this action, though. Created https://github.com/sourcegraph/sourcegraph/issues/63240 to track this potential issue.
Did manual QA, it removes users nicely.

fix(plg): Fix "Remove team member" feature

---

client/web-sveltekit/BUILD.bazel
client/web-sveltekit/package.json
client/web-sveltekit/src/routes/+layout.svelte
client/web-sveltekit/src/routes/svelte-overrides.scss
pnpm-lock.yaml

This adds Roboto Mono as the default monospace font for the Svelte webapp. Previously, we were nominally using SF Mono, but that is not installed by default and we were not fetching it, so the figma designs looked different than what was being rendered in the web app. This uses FontSource packages for the font for easy self-hosting (no external requests).
Fixes SRCH-445
Manually tested that code is rendered with Roboto Mono. The font weighs ~30KB

Svelte: use Roboto Mono as monospace font

---

internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
internal/codeintel/codenav/internal/lsifstore/scan.go
internal/collections/BUILD.bazel
internal/collections/set.go
internal/collections/set_test.go

It's a bit weird that this was in the codeintel package.
Added new tests

chore: Move deduplicateBy to collections package

---

client/web/src/components/externalServices/ExternalServicePage.module.scss

PR #49682 made some CSS changes to hide the caret as well as bracket matching for this input. I assume that seeing those in a read-only input was confusing.
However, hiding the textarea element also breaks copying the input's value. Instead of hiding the textarea, we are now hiding the visiual representation of the caret.
A noteable difference in behavior now is that it's possible to focus the input via tab, but there is no visual indiciation that the editor has focus (since we hide the caret, as before).
Manual tested on https://sourcegraph.test:3443/site-admin/external-services/RXh0ZXJuYWxTZXJ2aWNlOjky

fix(search): Copy text from read-only code host configuration input

---

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.spec.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/stats/contributors/page.spec.ts

Of the last 10 failures, only two tests were flaking. This disables those tests until we can figure out why they were flaking.
CI passes with no flakes

Chore: disable flaky tests

---

client/web-sveltekit/src/lib/search/input/SearchInput.svelte

Fixes SRCH-541
Reported [here](https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1718328910576659)
The bug:
https://github.com/sourcegraph/sourcegraph/assets/12631702/78d69be1-e594-4551-b3cb-fdb6fcadbd2e
With the change in font, the minimum line-height to fit that font has also increased. 1.6 seemed to do the job.
I'm a little concerned about other places this might be a problem, but for now just doing the easy thing to make it feel less broken.
The input no longer scrolls and there is no change to the height of the element as a whole.

fix(svelte): scrolling search input

---

client/web-sveltekit/src/lib/KeyboardShortcut.svelte
client/web-sveltekit/src/lib/TabsHeader.svelte
client/web-sveltekit/src/lib/codemirror/SearchPanelView.svelte
client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
client/web-sveltekit/src/lib/search/input/ActionInfo.svelte
client/web-sveltekit/src/lib/search/input/Suggestions.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/RepositoryRevPickerItem.svelte
client/web-sveltekit/src/routes/styles.scss

The current keyboard shortcuts look pretty funky against the sleek new design IMO, so I took a few minutes (that turned into a couple hours) to implement the keyboard shortcut design from Figma. 
I manually checked every place we add keyboard shortcuts. Screenshots below.

Svelte: implement keyboard shortcut design

---

internal/search/codycontext/query_parser.go
internal/search/codycontext/query_parser_test.go
internal/search/job/jobutil/job_test.go

This adds a thin layer to expand a query with keywords which are not explicitly mentioned. As a first application, we detect if a README should be returned. See /vscode/src/chat/chat-view/context.ts for how a similar logic is implemented in the client.
Test plan:
- new and updated unit tests
- Cody web client: I tested the "what does this codebase do?" for `sourcegraph/sourcegraph` and `sourcegraph/zoekt` as selected context. For Zoekt we return `/README.md` in the top 3, which leads to a good answer. The Sourcegraph repo has many README files and our ranking ranks other README files higher, for example if they contain the string "README", which leads to a vague answer.
Addresses SPLF-94

context: detect if README is required

---

internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
internal/collections/set.go

The code earlier constructing the locations attaches the same
uploadID and path to all of them, so trying to use those while 
uniquing is wasteful. Let's stop doing that.

chore: Simplify location uniquing

---

internal/collections/slice_utils.go
internal/collections/slice_utils_test.go

This is useful for comparing SCIP occurrences with search ranges.
Added unit test and property-based test

chore: Add binary search function that returns range

---

client/web-sveltekit/src/lib/search/codemirror/suggestions.ts

This PR appends a trailing slash to org and directory suggestions so that we don't search in repos or directories that are a prefix of the current org/directory.

fix(svelte): Add trailing slash to group and directory suggestions

---

client/web/src/cody/management/api/react-query/callCodyProApi.ts

Fixes bug intorduced in https://github.com/sourcegraph/sourcegraph/pull/63231
Encode the URL search params added to `returnTo` search param value.
Previously the search param value hasn't been encoded resulting in URLs with broken search params , e.g. *"/sign-in?returnTo=/cody/manage?teamID=1&inviteID=2"* (note the second "?" making the search params invalid). 
- CI
- Tested manually:
- Make `signOutAndRedirectToSignIn` available in the window object, e.g. `window.signOutAndRedirectToSignIn = signOutAndRedirectToSignIn` in the *client/web/src/cody/management/api/react-query/callCodyProApi.ts*
- On "/cody/manage" page (any page works actually) ensure that a few search params are added to the URL
- call `signOutAndRedirectToSignIn` in the browser console
- ensure you have been sign out, …

PLG: encode URL search params

---

client/shared/src/react-shortcuts/keys.ts

Fixes srch-420
We've gotten feedback about single character shortcuts like `/` not working when num lock is turned on. I think it's generally OK to ignore *lock keys for these cases.
Code inspection, trivial change.

fix(search): Ignore *lock keys for keyboard shortcut matching

---

client/branded/src/search-ui/input/experimental/Suggestions.tsx
client/web-sveltekit/src/lib/search/SyntaxHighlightedQuery.svelte
client/web-sveltekit/src/lib/search/input/SuggestionOption.svelte

Fixes srch-404
Currently queries are assumed to be 'literal', but in the current apps we mostly use 'keyword' and 'standard'. Ideally we could pass the pattern type that was used for each history entry, but we don't have that information and cannot pass it easily.
Defaulting to the 'standard' or 'keyword' type is the next best option to ensure that regex literal in the query are properly highlighted.
I defaulted to 'standard' in the React app because it's still possible to opt out of keyword search.

fix(search): Improve syntax highlighting of search history entries

---

client/web/BUILD.bazel

A glob that doesn't match any files got introduced in https://github.com/sourcegraph/sourcegraph/commit/4077b3ec22dad1c93675fd3e33336a35019bac00#diff-f7c1ab1acb5e753bccdd4b092b0098fa58855899e8764b68829ada2ba9cea760R147 which appears to confuse Gazelle, leading to `sg bazel configure` not updating ts files. 
Fixes https://github.com/sourcegraph/devx-support/issues/1029
Locally tested: 
1. Dropped the offending glob 
2. rm'ed `client/web/src/cody/subscription/subscriptionSummary.ts` 
3. `sg bazel configure` 
4. Observed the build file being updated accordingly.

fix(ci): remove broken glob

---

deps.bzl
go.mod
go.sum

Updates the Goldmark markdown renderer to v1.7.2, which includes https://github.com/yuin/goldmark/pull/455, fixing the issue with single-tilde strikethroughs not rendering as strikethroughs as described by the Github Flavored Markdown spec.
Fixes SRCH-501
Ran it locally. Single-tilde strikethroughs render correctly.

Chore: update goldmark

---

client/branded/src/search-ui/input/codemirror/token-info.ts
client/shared/src/search/query/selectFilter.ts

Fixes srch-362
When the select filter value ends with a `.` *and* does not have a valid "top-level" value, e.g. `select:diff.` then the diagnostic message doesn't show a list of valid values. This commit fixes that.
Additionally it won't show an empty tooltip anymore when we don't have information for the hovered token.
| ![2024-06-14_13-53](https://github.com/sourcegraph/sourcegraph/assets/179026/40a1d42a-74ba-4d51-891c-b8db96c49f0f) | ![2024-06-14_13-54](https://github.com/sourcegraph/sourcegraph/assets/179026/5963deb2-1823-4f7d-9793-9a4671ab1069) | 
(notice the separator in the popover in the first screenshot)
This affects both the React and the Svelte app.
- Show useful valid values when an invalid `select:` value is entered
- Do …

fix(search): Better diagnostic message for invalid and incomplete select: filter value

---

cmd/cody-gateway/internal/httpapi/completions/fireworks.go
cmd/cody-gateway/shared/config/config.go
cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go
cmd/frontend/internal/httpapi/completions/codecompletion.go
internal/completions/client/fireworks/fireworks.go

1. Adds support for deepseek-coder model and updated Mixtral finetuned-FIM models identifiers hosted on Fireworks. 
2. Client side pull request: https://github.com/sourcegraph/cody/pull/4577
```
curl -vS -X POST http://localhost:9992/v1/completions/fireworks -H 'Authorization: bearer <SGD_TOKEN>' -d '{"stream":false,"max_tokens":50, "model": "accounts/sourcegraph/models/deepseek-coder-7b-base", "stop_sequences": ["\n\n"], "prompt": "const value = ", "stream":false}' -H 'X-sourcegraph-feature: code_completions'
```
```
curl -vS -X POST http://localhost:9992/v1/completions/fireworks -H 'Authorization: bearer <SGD_TOKEN>' -d '{"stream":false,"max_tokens":50, "model": "accounts/sourcegraph/models/custom-deepseek-1p3b-base-hf-version", "stop_sequences": ["\n\n"], "prompt": "const value = ", …
```

adding deepseek and lang specific mixtral for completions ab experiment

---

client/web-sveltekit/src/lib/search/dynamicFilters/Section.svelte
client/web-sveltekit/src/lib/search/dynamicFilters/SectionItem.svelte
client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte

This fixes the alignment of the icons in the dynamic filters sidebar by mvoing the icon out of the `label` span and directly under the section item flexbox. I did this by creating an `icon` slot, which also allowed me to simplify a bunch of other complex slot interactions.
Contributes to SRCH-531
Manually visually inspected each of the types of section items.

Svelte: fix sidebar icon alignment

---

cmd/frontend/internal/codycontext/context.go
cmd/frontend/internal/codycontext/context_test.go

Tiny refactor that makes it clear we only return one `FileChunkContext` per file match.

Context: simplify file chunk conversion

---

internal/database/permission_sync_jobs.go
internal/database/permission_sync_jobs_test.go

This PR changes the query that powers the "failed user sync count" on the permissions center to now properly ignore soft-deleted users. The admin can't take any action to remedy this, so there is no point in displaying it.
Unit tests
- The failed user permission sync count on the permission dashboard now properly ignores syncs from deleted users (which is the expected behavior).

fix/graphql/database: make count of failed user permissions syncs ignore soft deleted users

---

internal/database/permission_sync_jobs.go
internal/database/permission_sync_jobs_test.go

This PR changes the query that powers the "failed repository sync count" on the permissions center to now properly ignore soft-deleted repositories. The admin can't take any action to remedy this, so there is no point in displaying it.
Unit tests
- The failed repository permission sync count on the permission dashboard now properly ignores syncs from deleted repository (which is the expected behavior).

fix/graphql/database: fix repo permission sync count to ignore soft deleted repositories

---

internal/database/repos_test.go
internal/database/users_test.go

This is a small change that ensures that the user/repository not found error types fulfill the errcode.NotFound interface. This is a building block for https://app.graphite.dev//github/pr/sourcegraph/sourcegraph/63302
Unit tests
- Added unit tests to ensure that the database userNotFound and RepositoryNotFound error types fulfuill the errcode.NotFound interface.

feature/internal/database: add test to ensure that not found errors fulfiill errcode.NotFound

---

cmd/frontend/internal/authz/resolvers/BUILD.bazel
cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
cmd/frontend/internal/authz/resolvers/permissions_sync_jobs_test.go
cmd/frontend/internal/authz/resolvers/resolver.go
cmd/frontend/internal/authz/resolvers/resolver_test.go

Closes https://linear.app/sourcegraph/issue/SRC-421/customer-reported-an-issue-with-user-permissions-stats
This PR ensures that any non not-found errors that occur when fetching permission sync jobs are logged and added as error events in the trace. Before, these errors were silently swallowed which makes things exceptionally hard to debug.
This PR only changes the monitoring around this query - **it doesn't change the underlying behavior.**
**Note**: I spent a while reading up on how to communicate partial errors in our graphql API, but it seems like there isn't a clear consensus. 
- https://github.com/graph-gophers/graphql-go/issues/414
- https://spec.graphql.org/October2021/#sel-HAHlBNJDPEBAAADFBU-_D
According to the above, it seems like ideally we should be returning `null` in the …

fix/frontend/graphql: log and add trace events for all non-not-found errors that occur when fetching permission syncs

---

cmd/cody-gateway/internal/httpapi/completions/flagging.go
cmd/cody-gateway/internal/httpapi/completions/google.go
cmd/cody-gateway/shared/config/config.go

We recently noticed that 100% of all LLM requests routed to Google-provided LLMs were getting flagged, and for the same reasons ["high_max_tokens_to_sample","blocked_phrase"].
After FAR, FAR more head scratching than I care to admit to. I realized the problem: that we were never actually initializing the `Google.FlaggingConfig` settings. So when we were inspecting Gemini requests for potential abuse, we were comparing them against the zero-state for `flaggingConfig`. i.e. does this prompt have a higher `MaxTokensToSample` than 0?
🤦 Super easy mistake to make. We now confirm that _something_ is in the `flaggingConfig` before assuming it is legitimate.
Fixes https://github.com/sourcegraph/abuse-ban-bot/issues/32.
CI/CD

fix(cody-gateway): Fix Google flagging configuration

---

sg.config.yaml

`sg start dotcom` still fired up the `docsite` command, which is unecessary at this point. This PR removes it.

chore(local): remove docsite from dotcom commandset

---

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/ReferencePanel.svelte

Contributes to srch-578
Currently we keep showing the loading indicator even if no references have been found. This commit moves the info messages into the layout because the layout has information we need to properly distinguish the different states.
I think more refactoring is necessary to make this API better but that will be done as part of adding search-based code intel support.

fix(svelte): Fix reference panel loading/error state

---

docker-images/syntax-highlighter/Cargo.Bazel.lock
docker-images/syntax-highlighter/Cargo.lock
docker-images/syntax-highlighter/Cargo.toml
docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
docker-images/syntax-highlighter/crates/scip-syntax/src/evaluate.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/io.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
docker-images/syntax-highlighter/crates/scip-syntax/tests/integration_test.rs
docker-images/syntax-highlighter/crates/syntax-analysis/Cargo.toml
docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs

Fixes https://linear.app/sourcegraph/issue/GRAPH-688/refactor-syntax-highlighter-to-use-the-camino-library
We're already codifying and assuming that paths are utf8 only in a bunch of places. This library let's us make the utf8 check up-front and then not have to recheck over and over again.
This should purely be a refactoring, so all existing tests should continue to pass

syntax-highlighter: Use camino to make handling utf8 paths nicer

---

client/web-sveltekit/src/lib/global-notifications/GlobalNotifications.svelte
client/web/src/site/LicenseExpirationAlert.tsx
client/web/src/site/__snapshots__/LicenseExpirationAlert.test.tsx.snap

In response to some customer feedback that multiple users thought this meant their user's license was expiring, this updates the wording to clarify that it's the sourcegraph instance license that's expiring.
Fixes SRCH-513
N/A

Minor: update license wording

---

doc/dev/background-information/renovate.md
renovate.json

We haven't been using it _at all_ in this repo, and its just causing unnecessary CI builds
N/A

chore(ci): disable renovate

---

client/web-sveltekit/src/lib/search/input/SearchInput.svelte

Fixes srch-545
We are hiding suggestions until the user has interacted with the input (e.g. by clicking or typing), but, as it is not, it does not include clicking on the history button.
This commit changes that.
Manual testing. Clicking the history button without having interacted with the search input in any other way will now show history suggestions and focus in the input.

fix(svelte): History suggestions should show immediately when clicking the history button

---

internal/codeintel/codenav/BUILD.bazel
internal/codeintel/codenav/scip_utils.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/syntactic.go
internal/codeintel/codenav/transport/graphql/iface.go
internal/codeintel/codenav/transport/graphql/mocks_test.go

Closes https://linear.app/sourcegraph/issue/GRAPH-657/fetch-and-filter-scip-documents-based-on-candidate-files
Currently only testable via the site-admin API console

Filters candidate matches against syntactic SCIP documents

---

dev/sg/sg_db.go

Follow-up to https://github.com/sourcegraph/sourcegraph/pull/63320 as I noticed that the `UsageText` didn't include `sg db default-site-admin`. Additionally, it was quite verbose without providing much info, so I just dropped it in favour of highlighting notable commands.
Before: 
```
NAME:
sg db - Interact with local Sourcegraph databases for development
USAGE:
sg db delete-test-dbs
sg db reset-pg
sg db reset-pg -db=frontend,codeintel
sg db reset-pg -db=all
sg db reset-redis
sg db add-user -username=foo
sg db add-access-token -username=foo
COMMANDS:
delete-test-dbs                Drops all databases that have the prefix `sourcegraph-test-`
reset-pg                       Drops, recreates and migrates the specified Sourcegraph database
reset-redis                    Drops, recreates and …
```

chore(local): simplify 'sg db' inline help

---

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/tags/+page.svelte

The tags page contains a `:global` selector at the root level, which affects all elements that match the selector, even those not part of the page.
`:global` selectors always need to be scoped one way or the other.
Code inspection, trivial change.

fix(svelte): Properly scope global CSS selector

---

client/web-sveltekit/src/lib/wildcard/resizable-panel/PanelResizeHandleRegistry.ts

Fixes srch-507
The panels code prevents event propagation of mouse move events, which in turn seems to prevent SvelteKit from its own preloading logic.
Looking at the event handlers it seems they are global only (per document), so I don't think that stopping the propagation is necessary for the panel itself to work. However, I think it makes sense to stop any of default event behavior when the mouse is currently pressed, since that means the user is currently dragging a resize handler. Would love to get @vovakulikov's confirmation that my understanding is correct.
Manual testing. Changing the size of a panel (e.g. repo page) seems to work as expected. Hovering over a file tree entry preloads data and code now, as visible in the network tab.

fix(svelte): Data/code preloading doesn't work when using panels

---

dev/ci/push_all.sh
dev/tool_deps.bzl
dev/tools/BUILD.bazel

So I can measure the impact of changes on the individual `bazel run` invocations
main dry-run and seeing the output https://ui.honeycomb.io/sourcegraph/datasets/buildkite-pushall/result/bCLzgquaSdV?hideCompare

chore(ci): instrument push_all.sh commands in honeycomb

---

client/web-sveltekit/BUILD.bazel

Marks the `web-sveltekit:e2e_test` as flaky (tries them up to three times). It just failed main on this build http://github.com/sourcegraph/sourcegraph/commit/db7a268c34e7908e03477fedb166bcd0ed39b179
ci

chore(ci): mark web-sveltekit:e2e_test as flaky

---

client/web-sveltekit/src/lib/search/SymbolKindIcon.svelte

Fixes srch-601
| ![2024-06-19_21-15](https://github.com/sourcegraph/sourcegraph/assets/179026/2e3efa8a-826f-455a-a55c-055b6f82920e) | ![2024-06-19_21-15_1](https://github.com/sourcegraph/sourcegraph/assets/179026/cf93f744-d3f3-49e6-8593-dc28ecb43587) | 
Visual inspection

fix(svelte): Use correct symbol icon color

---

client/web-sveltekit/src/routes/[...repo=reporev]/RepoMenu.svelte

Two followups from implementing the repo menu:
1) Remove the rounded corners from the trigger button to match the rest of the header
2) Add an external link icon to the code host link
Visual testing

Svelte: repo header followups

---

client/web/src/integration/search-aggregation.test.ts
client/web/src/search/index.test.ts
client/web/src/search/index.ts
client/web/src/stores/navbarSearchQueryState.test.ts
client/web/src/stores/navbarSearchQueryState.ts

We plan to remove the 'Keyword Search' toggle as part of bringing the feature
to GA. Once the toggle is removed, the search UX will only represent `keyword`
(the default pattern type) and `regexp` (through the regex toggle), with no
visual indication for other pattern types. So if a user clicks on a link using
`patterntype:standard`, the search will just behave differently, without any
indication in the UX as to why.
This PR surfaces the `patterntype` filter in the search bar whenever it's not
`keyword` or `regexp`. That way, users can see an old pattern type is being
used and understand why the search behavior may be different.
Relates to SPLF-68
Added unit tests, manually tested search bar behavior with different pattern
types.

Search: surface pattern type in query input

---

cmd/cody-gateway/internal/httpapi/embeddings/metadata.go
cmd/frontend/internal/completions/resolvers/resolver.go
cmd/frontend/internal/httpapi/completions/handler.go
internal/completions/client/anthropic/BUILD.bazel
internal/completions/client/anthropic/anthropic.go
internal/completions/client/anthropic/anthropic_test.go
internal/completions/client/awsbedrock/bedrock.go
internal/completions/client/azureopenai/openai.go
internal/completions/client/azureopenai/openai_test.go
internal/completions/client/codygateway/codygateway.go
internal/completions/client/fireworks/fireworks.go
internal/completions/client/fireworks/fireworks_test.go
internal/completions/client/google/google.go
internal/completions/client/google/google_test.go
internal/completions/client/observe.go
internal/completions/client/openai/openai.go
internal/completions/client/openai/openai_test.go
internal/completions/types/types.go

This PR refactors the `CompletionsClient` interface, and all the corresponding call sites. There is no functional change, beyond bundling several function parameters into a new type.
See `internal/completions/types/types.go`. But the gist is this putting 3x parameters into a single `CompletionRequest` type.
```diff
Complete(
context.Context,
log.Logger
-           CompletionsFeature,
-           CompletionsVersion,
-           CompletionRequestParameters
+           CompletionRequest
) (*CompletionResponse, error)
```
As part of reworking the codepath between receiving a completion request, dispatching it to the right `CompletionsClient` implementation, and serving the request, I need some "hooks" to inject new information.
In a future PR I plan on adding a `*ServerSideModelConfig` as …

refactor(cody): Reshape the `CompletionsClient` interface

---

cmd/cody-gateway/internal/httpapi/embeddings/metadata.go
cmd/frontend/internal/completions/resolvers/resolver.go
cmd/frontend/internal/httpapi/completions/BUILD.bazel
cmd/frontend/internal/httpapi/completions/chat.go
cmd/frontend/internal/httpapi/completions/codecompletion.go
cmd/frontend/internal/httpapi/completions/get_model.go
cmd/frontend/internal/httpapi/completions/handler.go
internal/completions/client/anthropic/BUILD.bazel
internal/completions/client/anthropic/anthropic.go
internal/completions/client/anthropic/anthropic_test.go
internal/completions/client/awsbedrock/bedrock.go
internal/completions/client/azureopenai/openai.go
internal/completions/client/azureopenai/openai_test.go
internal/completions/client/codygateway/codygateway.go
internal/completions/client/fireworks/fireworks.go
internal/completions/client/fireworks/fireworks_test.go
internal/completions/client/google/google.go
internal/completions/client/google/google_test.go
internal/completions/client/observe.go
internal/completions/client/openai/openai.go
internal/completions/client/openai/openai_test.go
internal/completions/types/types.go

Minor refactoring to the `cmd/frontend/internal/completions` package.
When we call `newCompletionsHandler` one of the parameters is a function named `getModel`. This is called to determine which LLM model should be use to respond to the incoming completion request. And we have two implementations of this function, one for code completions and another for chats.
This PR just moves the logic for those two implementations into their own file (`get_model.go`), along with a couple of functions for which they were the only caller.
There were two minor functionality changes I made, which I'll call out in comments on this PR.
As we rework how LLM models and associated configuration flows throughout the backend, updating these functions will be a bit easier if they are pulled out like this rather …

Refactor the 'getModel' callbacks into their own file

---

internal/codeintel/codenav/transport/graphql/root_resolver.go

There could be various causes for the failure, so delegate the error
formatting to the inner error.
n/a

chore: Fix inaccurate error message

---

cmd/appliance/shared/config.go
cmd/appliance/shared/shared.go
internal/appliance/appliance.go
internal/appliance/html.go

Change default to "default", rather than all namespaces. Before, this config element was only used to tell the reconciler which namespaces to monitor for ConfigMaps.
Now, we repurpose it to tell the appliance frontend which namespace to _create_ the configmap in, so "all" makes no sense.
Follow-on to https://github.com/sourcegraph/sourcegraph/pull/63291.
Manual only, there are no automated tests for the frontend... yet. I deployed SG with and without APPLIANCE_NAMESPACE set, and it targeted the namespace as expected.

fix(appliance): target configured namespace

---

client/web-sveltekit/src/lib/KeyboardShortcut.svelte
client/web-sveltekit/src/lib/TabsHeader.svelte
client/web-sveltekit/src/lib/common.ts
client/web-sveltekit/src/lib/fuzzyfinder/FuzzyFinder.svelte
client/web-sveltekit/src/routes/svelte-overrides.scss

Closes srch-458
This implements the new fuzzy finder design, specifically:
- Backdrop and dropshadow
- Border radius
- Tab header (affects all tab headers)
- Options
Note 1: Some aspects of the options UI (such as how paths are rendered and highlighted), and the "footer" depend on how the highlighted parts are computed. This will change when the local matching and ranking logic is removed and will be updated when that happens.
Note 2: The symbol icon coloring was broken by #63288 and will be fixed in a separate PR.
| Panel | Before | After |
|--------|--------|--------|
| Repo (light) | ![2024-06-19_21-04](https://github.com/sourcegraph/sourcegraph/assets/179026/9fe0eae8-2ed5-4a93-917c-ec65a0c4b1ca) | ![2024-06-19_21-03](https://github.com/sourcegraph/sourcegraph/assets/179026/76f09568-024 …

chore(svelte): Update fuzzy finder designs

---

dev/nix/go_1_22.nix
flake.nix

Tired of seeing the go toolchain being easier to use than nix.
Test Plan: nix develop on linux amd64 and macbook arm64 followed by running "go test ./internal/search" working. Also confirming that "go env GOROOT" points into the nix store.

nix: use go1.22.4

---

client/web/src/cody/management/CodyManagementPage.tsx
client/web/src/cody/management/subscription/new/NewCodyProSubscriptionPage.tsx

The "Invite co-workers" flow was not up to spec.
This PR fixes it to match this spec:
* If you are a team of size seats = 1, then "Invite coworkers" should take you to the add seats page because you won't be able to invite anyone until you add seats
* If you are a team of size seats = N, and have M invited/accepted users where M < N, then you should see [this](https://www.google.com/url?q=https://www.figma.com/design/FMSdn1oKccJRHQPgf7053o?node-id%3D4143-5059%23845917232&sa=D&source=docs&ust=1718872555659671&usg=AOvVaw3vf3t-_T4rB5sWM-_kWWzE)
* If you are a team of size seats = N and have N invited/accepted users, then you should see [this](https://www.google.com/url?q=https://www.figma.com/design/FMSdn1oKccJRHQPgf7053o?node-id%3D5573-15751%23845918007&sa=D&source=docs&ust=1718872555659752& …

feat(plg): Tweak invite co-workers flow

---

client/web/src/cody/chat/CodyChatPage.tsx
client/web/src/cody/management/CodyManagementPage.tsx
client/web/src/cody/management/subscription/manage/CodySubscriptionManagePage.tsx
client/web/src/cody/management/subscription/new/CodyProCheckoutForm.tsx
client/web/src/cody/management/subscription/new/NewCodyProSubscriptionPage.tsx
client/web/src/cody/subscription/CodySubscriptionPage.tsx
client/web/src/cody/team/CodyManageTeamPage.tsx
client/web/src/cody/widgets/CodyRecipesWidget.tsx
client/web/src/get-cody/GetCodyPage.tsx

The original goal was to fix error messages being too close to headers.
This PR fixes that:
But then I noticed that several of the pages had different header styles, so I standardized them in this PR.
**Note:** This PR also makes sure that we use `CodyProRoutes` everywhere for URLs.
Manual QA and design review.
Instead of screenshots, I showed them in [this 30-sec Loom](https://www.loom.com/share/aa5156c6bcbd4d799db11e2bf4f1ec3f) because this way it's also easier to compare them to each other and see that they are indeed the same style.

plg(feat): Make page headers the same style

---

internal/gitserver/client.go

Was confused on reading some of our code, which is not
setting this value in the way that is expected when attempting
to handle range re-mapping for precise code nav.
Not sure if we need a test for this, I just tested with `git diff A..B -- <path>` locally.

chore: Add doc comment for DiffOptions.Paths

---

dev/managedservicesplatform/internal/resource/cloudsql/cloudsql.go
dev/managedservicesplatform/internal/resource/postgresqlroles/postgresqlroles.go

Wait for databases to be provisioned before granting database-specific roles to the operator access user. 
Re-apply fixed https://sourcegraph.slack.com/archives/C05E2LHPQLX/p1718850688397579, indicating a race condition on database creation. Diff looks good:
```diff
@@ -1447,10 +1472,15 @@
"path": "cloudrun/cloudrun-postgresqlroles-msp_iam-operator_access_service_account_table_grant",
"uniqueId": "cloudrun-postgresqlroles-msp_iam-operator_access_service_account_table_grant"
}
},
"database": "msp_iam",
+        "depends_on": [
+          "google_sql_database.postgresql-database-enterprise-portal",
+          "google_sql_database.postgresql-database-enterprise_portal",
+          "google_sql_database.postgresql-database-msp_iam"
+        ],
"object_type": "table",
"objects": [
], …
```

fix/msp/postgresqlroles: wait for databases to be provisioned

---

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte

Fixes srch-553
This commit changes the "selectline" handler to open the correct file when the file view is embedded.
Manual testing. Open reference panel, click on reference to open preview panel, click on line number in review panel.

fix(svelte): Open correct file from preview panel line number

---

lib/managedservicesplatform/runtime/contract/env.go

The runtime `Env` currently lacks a convenient method for getting a floating point env var. This PR adds a `GetFloat`method which will parse a float64 from a given env var
Part of CORE-181
locally tested 
values such as `10.2` and `infinity` were correctly parsed

msp/runtime: add `GetFloat` to runtime `Env`

---

internal/authz/register.go

Sourcegraph.com only has public repos, so it is safe to allow access to all repositories by all users.
This now-deleted code was originally added in https://github.com/sourcegraph/sourcegraph/pull/26345 to support private repositories on dotcom. We do not currently support private repositories on dotcom anymore, and when we do add back that feature, we can figure out how best to do it and will benefit from fewer special-cases for dotcom.
CI

allow repo access by default on dotcom

---

client/web-sveltekit/src/lib/fuzzyfinder/FuzzyFinder.svelte

Tiny change to increase font-size of byline on the items in the fuzzy finder.
Manually tested locally.

Svelte: Make the byline in the fuzzy finder items bigger

---

client/web/src/enterprise/batches/create/ConfigurationForm.tsx

Closes SRCH-534
> “Visibility” on the [create batch changes page](https://sourcegraph.sourcegraph.com/batch-changes/create) has been in [coming-soon limbo](https://www.notion.so/sourcegraph/Product-features-that-are-in-a-worrying-limbo-state-customer-GTM-feedback-ff3dbf0fa6714259b8628aa29d58c395?pvs=4#c9ffd448af444188873e989a7b7f13a0) for a long time.
> We will remove “coming soon” and the "private" option. We will not ship this enhancement in FY25. 
> (We will connect batch changes to chat/search workflows in the unified product, which will make it accessible to a lot more devs compared to today. This will entail a rethinking of the entire “create batch change” flow and many other things that will benefit customers and users by addressing the #1 feedback about batch changes (that it’s …

chore(batch-changes): remove visibility options from create batch changes page

---

cmd/enterprise-portal/internal/database/subscriptions.go
cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
cmd/enterprise-portal/internal/dotcomdb/dotcomdb_test.go
cmd/enterprise-portal/internal/subscriptionsservice/BUILD.bazel
cmd/enterprise-portal/internal/subscriptionsservice/adapters.go
cmd/enterprise-portal/internal/subscriptionsservice/mocks_test.go
cmd/enterprise-portal/internal/subscriptionsservice/v1.go
cmd/enterprise-portal/internal/subscriptionsservice/v1_store.go
cmd/enterprise-portal/internal/subscriptionsservice/v1_test.go

Follow-ups to https://github.com/sourcegraph/sourcegraph/pull/63173 I'm running into while working on CORE-169:
1. Intersect permission-allowed subscriptions, instead of always overwriting. I think this is probably desired behaviour, to still allow filtering by subscriptions. If no subscriptions are explicitly listed, _then_ the allowed subscriptions become the set of subscriptions to list.
1. If a permissions filter is used and the resulting subscription set is empty, we fast-exit with empty result
2. If no subscription list is provided, list all subscriptions. This is safe because permission filter has special fast-path above
3. Fix "is archived" support
Tests, and a manual check - with `sg start dotcom`, exchange for a token:
```sh
sg sams create-client-token \
-sams …
```

fix/enterpriseportal: ListEnterpriseSubscriptions fixes

---

client/web/src/cody/components/CodyAlert.module.scss
client/web/src/cody/invites/InviteUsers.tsx
internal/authz/register.go

Closes https://github.com/sourcegraph/sourcegraph/issues/63234
[Design](https://www.figma.com/design/FMSdn1oKccJRHQPgf7053o/Cody-PLG-GA?node-id=5556-13856&t=f13ek1ZSgoUdrH6z-0)
Adds a button to remove the remaining invites from a subscription. 
https://github.com/sourcegraph/sourcegraph/assets/25318659/679e19dd-0e0e-4561-8ac1-af1b6979ee73
**Known deviation from design (cc: @rrhyne)**
The “Remove User” success message and the “Remove Seats from Subscription” alerts are positioned differently than in the design. The “Remove User” banner, along with other user and invite list alerts, is placed above the users list, below the page title or the invites textbox if rendered. The “Remove Seats from Subscription” banner, along with other invite textbox alerts, is located above the invites textbox …

feat(plg): remove seats from subscription

---

cmd/frontend/graphqlbackend/codeintel.codenav.graphql
internal/codeintel/codenav/transport/graphql/root_resolver_usages.go
internal/codeintel/resolvers/codenav.go

Mostly a documentation-related PR, the implementation will be done later.
Fixes https://linear.app/sourcegraph/issue/GRAPH-697/add-symbolusagekind-to-usages
n/a

chore: Add SymbolUsageKind to GraphQL API

---

internal/codeintel/codenav/transport/graphql/root_resolver.go
internal/codeintel/codenav/transport/graphql/root_resolver_usages.go

Fixes https://linear.app/sourcegraph/issue/GRAPH-667/wrap-up-usage-results-in-graphql-resolvers
This allows us to actually return syntactic usages from the occurrences API. It does not implement pagination yet, but I think _that_ PR will be nicer to review after this one landed.
Requires #63268
Running queries against the site-admin api console

Wraps up syntactic usages in resolvers

---

client/web/dist/BUILD.bazel

When moving to ESBuild, the filenames for extension bundles changed, which led to broken bitbucket plugins for example. 
See [discussion](https://sourcegraph.slack.com/archives/C04MYFW01NV/p1718902092493689)
Inspected the relevant target to see the paths in their proper location.

fix(client): restore paths for extension bundles

---

WORKSPACE

Previously we were having soft-warnings around permissions in badly made npm packages
```
(21:31:30) WARNING: Remote Cache: /mnt/ephemeral/output/__main__/execroot/__main__/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/its-fine@1.1.1_react_18.1.0/node_modules/its-fine/src/index.tsx (Permission denied)
```
When trying to enable compact execution log, this becomes a hard fail
```
(14:44:58) ERROR: /mnt/ephemeral/workdir/sourcegraph/sourcegraph/BUILD.bazel:33:22: Extracting npm package its-fine@1.1.1_react_18.1.0 failed: IOException while logging spawn: /mnt/ephemeral/output/__main__/execroot/__main__/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/its-fine@1.1.1_react_18.1.0/node_modules/its-fine/dist/index.cjs (Permission denied)
```
This bump should fix that
CI still …

chore(bazel): bump rules_js to address permissions denied warning

---

.aspect/bazelrc/ci.sourcegraph.bazelrc
.aspect/workflows/config.yaml
.gitignore
dev/ci/internal/ci/images_operations.go

Second attempt at https://github.com/sourcegraph/sourcegraph/pull/61760, we can start using these to dig into action cache misses etc
CI passes green

chore(ci): emit compact executon log in CI

---

client/web/src/enterprise/batches/batch-spec/header/BatchChangeHeader.tsx

Closes SRCH-609
This removes the Beta badge from SSBC pages.
Accessing Batch Changes shouldn't display the Beta badge label anymore.
- Remove Beta badge from Batch Changes pages.

chore(batch-changes): remove beta badge from batch changes

---

cmd/enterprise-portal/internal/database/BUILD.bazel
cmd/enterprise-portal/internal/database/database.go
cmd/enterprise-portal/internal/database/databasetest/BUILD.bazel
cmd/enterprise-portal/internal/database/databasetest/databasetest.go
cmd/enterprise-portal/internal/database/internal/tables/BUILD.bazel
cmd/enterprise-portal/internal/database/internal/tables/tables.go
cmd/enterprise-portal/internal/database/migrate.go
cmd/enterprise-portal/internal/database/subscriptions/BUILD.bazel
cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go
cmd/enterprise-portal/internal/database/subscriptions/subscriptions_test.go
cmd/enterprise-portal/internal/subscriptionsservice/BUILD.bazel
cmd/enterprise-portal/internal/subscriptionsservice/adapters.go
cmd/enterprise-portal/internal/subscriptionsservice/mocks_test.go
cmd/enterprise-portal/internal/subscriptionsservice/v1.go
cmd/enterprise-portal/internal/subscriptionsservice/v1_store.go
cmd/enterprise-portal/internal/subscriptionsservice/v1_test.go

As we set up to introduce more tables to Enterprise Portal, I think it'll be more sustainable for things to get their own subpackages. No real code changes, just moving things around.
CI

chore/enterpriseportal: split database package

---

cmd/enterprise-portal/internal/database/BUILD.bazel
cmd/enterprise-portal/internal/database/database.go
cmd/enterprise-portal/service/service.go

Adds a clean shutdown for our primary DB handle, and removes some unused code.
`sg run enterprise-portal` and stop it

chore/enterpriseportal: properly close DB handle

---

lib/managedservicesplatform/go.mod
lib/managedservicesplatform/go.sum

Trying to address
GORM often gives no shit about versioning compatibility and may break things, let's downgrade the known good version first.
CI

lib/msp: downgrade GORM to 1.25.6

---

client/web-sveltekit/src/routes/navigation.ts
client/web/src/nav/GlobalNavbar.tsx
client/web/src/nav/__snapshots__/GlobalNavbar.test.tsx.snap
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx

The name of the product is "Cody", not "Cody AI". Also, "AI" just looks dumb and hype-y.
View the navbar and ensure it reads "Cody" not "Cody AI".
- In the navbar, Cody is now just "Cody" not "Cody AI".

"Cody" in navbar not "Cody AI"

---

cmd/frontend/internal/httpapi/completions/BUILD.bazel
cmd/frontend/internal/httpapi/completions/entconfig_anthropic_test.go
cmd/frontend/internal/httpapi/completions/entconfig_base_test.go
cmd/frontend/internal/httpapi/completions/get_model.go
cmd/frontend/internal/httpapi/completions/get_model_test.go
cmd/frontend/internal/httpapi/completions/handler.go
internal/completions/client/anthropic/prompt.go
internal/completions/client/awsbedrock/bedrock.go
internal/completions/client/google/prompt.go

The [Server-side Cody Model Selection](https://linear.app/sourcegraph/project/server-side-cody-model-selection-cca47c48da6d) project requires refactoring a lot of how the Completions API endpoint works for the Sourcegraph backend. It will need to update any place where we interact with the site config as it relates to LLMs, or any time we figure out which models can-or-can-not be used.
In order to safely land those refactoring without breaking existing users, who will be using the "older config format", we need tests. LOTS and LOTS of tests.
This PR adds the necessary infrastructure for writing unit tests against the Completions API, and adds a few basic ones for the Anthropic API provider. I wouldn't say it's as easy as we'd like to write these tests, but at least now it is _possible_. …

test(cody): Add unit tests for the Completions API

---

cmd/frontend/graphqlbackend/user_usage_stats.go
cmd/frontend/hubspot/hubspotutil/hubspotutil.go

Cody App was removed in June 2023 and is no longer in use.
CI

chore: remove obsolete tracking code for Cody App downloads

---

client/web/src/enterprise/batches/batch-spec/header/BatchChangeHeader.tsx

This PR removes the Beta badge from the Batch Changes pages. SSBC has been in Beta for sometime and this doesn't reflect the true status of the product.
Navigate to the `/batch-changes/create` page and the Beta badge shouldn't be there.
- the Beta badge is now removed from Batch Changes

chore(batch-changes): remove beta badge from Batch Changes page

---

internal/appliance/appliance.go
internal/appliance/config/BUILD.bazel
internal/appliance/config/dev_mode.go
internal/appliance/config/dev_mode_test.go
internal/appliance/config/spec.go
internal/appliance/dev/integrationtest/integration_test.go
internal/appliance/html.go
internal/appliance/reconciler/codeintel.go
internal/appliance/reconciler/gitserver.go
internal/appliance/reconciler/indexed_search.go
internal/appliance/reconciler/standard_config_test.go
internal/appliance/reconciler/testdata/golden-fixtures/codeintel/default.yaml
internal/appliance/reconciler/testdata/golden-fixtures/gitserver/default.yaml
internal/appliance/reconciler/testdata/golden-fixtures/indexed-search/default.yaml
internal/appliance/reconciler/testdata/golden-fixtures/indexed-search/with-replicas.yaml
internal/appliance/reconciler/testdata/golden-fixtures/standard/frontend-with-no-cpu-memory-resources.yaml
internal/appliance/reconciler/testdata/sg/standard/frontend-with-no-cpu-memory-resources.yaml
internal/appliance/web/template/setup.gohtml
internal/k8s/resource/container/container.go

**feat(appliance): local developer mode**
- Expose a toggle in the web UI to enable dev mode
- dev mode is currently defined as: no container resource
requests/limits
**fix(appliance): fix misconfigurations to 2 services**
Gitserver: the configured probe timeouts were too aggressive.
Indexed-search: the image name was wrong
Both of these were drift from Helm that we didn't catch. Luckily the
appliance is still pre-release!
---
Closes https://linear.app/sourcegraph/issue/REL-199/populate-accurate-list-of-versions-to-install
~Draft until base branch merged, but should be reviewable independently~
The behavior of the dev mode toggle is unit tested and golden tests cover its integration with the reconcile loop.
- Local developer mode for appliance config authors.

feat(appliance): local developer mode

---

cmd/frontend/graphqlbackend/user_usage_stats.go
cmd/frontend/graphqlbackend/user_usage_stats_test.go

Previously, all users were allowed to view a user's usage stats. This is an admin feature and it is not needed nor desirable for other users to be able to view a user's usage stats.
CI

fix(api): only allow a user or site admin to view that user's usage stats

---

cmd/frontend/graphqlbackend/git_tree_entry.go

This is a slow and CPU-intensive task, and there is little value in syntax-highlighting lockfiles. Just disable this on all instances, not only dotcom.
CI
- Syntax highlighting is disabled on lockfiles (such as `package-lock.json`) because it is CPU-intensive on these large files and very rarely desirable.

skip highlighting large lockfiles on all instances, not just dotcom

---

cmd/frontend/graphqlbackend/access_tokens.go
cmd/frontend/graphqlbackend/access_tokens_test.go

Previously, the code would prevent us from using the AccessTokensAdmin config setting on dotcom entirely, instead of just restricting it when site admins create an access token for a different user, which was the intent.
CI

clearer access tokens allow check on dotcom

---

cmd/frontend/enterprise/BUILD.bazel
cmd/frontend/enterprise/enterprise.go
cmd/frontend/internal/batches/resolvers/errors.go
internal/conf/computed.go

This is how it's done for Code Insights as well.
CI

chore: centralize logic for disabling Batch Changes on dotcom

---

.eslintrc.js

We do this many places in the code, so all this warning does is create lots of ESLint warnings that obscure more important warnings.
n/a

remove rule warning about React props spreading

---

client/web/dev/esbuild/config.ts
client/web/dev/utils/environment-config.ts

Cody App was removed in Dec 2023, and the `app/main.tsx` file has not existed for a long time.
n/a

remove unused CODY_APP esbuild config and entrypoint

---

cmd/enterprise-portal/internal/database/migrate.go
lib/managedservicesplatform/iam/database.go

Fix an issue with context propagation and add a little more detail on automigration steps
CI

chore/enterpriseportal: tweak maybeMigrate tracing

---

cmd/appliance/main.go
cmd/cody-gateway/main.go
cmd/frontend/BUILD.bazel
cmd/frontend/main.go
cmd/frontend/shared/BUILD.bazel
cmd/frontend/shared/service.go
cmd/frontend/shared/shared.go
cmd/sourcegraph/BUILD.bazel
cmd/sourcegraph/README.md
cmd/sourcegraph/main.go
dev/linters/dbconn/dbconn.go
internal/conf/deploy/deploytype.go
internal/repos/observability.go
internal/service/svcmain/svcmain.go
sg.config.yaml

This makes it easier to run Sourcegraph in local dev by compiling a few key services (frontend, searcher, repo-updater, gitserver, and worker) into a single Go binary and running that.
Compared to `sg start` (which compiles and runs ~10 services), it's faster to start up (by ~10% or a few seconds), takes a lot less memory and CPU when running, has less log noise, and rebuilds faster. It is slower to recompile for changes just to `frontend` because it needs to link in more code on each recompile, but it's faster for most other Go changes that require recompilation of multiple services.
This is only intended for local dev as a convenience. There may be different behavior in this mode that could result in problems when your code runs in the normal deployment. Usually our e2e tests should …

support fast, simple `sg start single-program-experimental-blame-sqs` for local dev

---

cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go
cmd/enterprise-portal/internal/database/subscriptions/subscriptions_test.go

We were aligned on using non-prefixed UUIDs internally, only prefixing them for external consumption. This lets us use the native UUID type.
Part of https://linear.app/sourcegraph/issue/CORE-155
CI, `sg run enterprise-portal`
`select * from enterprise_portal_subscriptions;` on dev shows we are using the non-prefixed UUDs only. Manual migration, since it doesn't seem like GORM can do this for you:
```
ALTER TABLE enterprise_portal_subscriptions ALTER COLUMN id TYPE uuid USING id::uuid;
```
Checked that data is intact.

feat/enterpriseportal: use UUID type for subscription ID

---

cmd/enterprise-portal/internal/database/migrate.go
lib/managedservicesplatform/iam/database.go

Follow-up to #63448 - we now get Redis spans, but not the database operations that happen throughout a migration. Maybe this will do the thing?
n/a

chore/enterpriseportal: propagate context to migration database context

---

cmd/cody-gateway/internal/httpapi/completions/anthropic.go
cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
cmd/cody-gateway/internal/httpapi/completions/fireworks.go
cmd/cody-gateway/internal/httpapi/completions/google.go
cmd/cody-gateway/internal/httpapi/completions/openai.go
cmd/cody-gateway/internal/httpapi/completions/upstream.go

Previously, there was no way to enable the "tracing" feature from Fireworks https://readme.fireworks.ai/docs/enabling-tracing This PR solves the problem by forwarding the `X-Fireworks-Genie` HTTP header to Fireworks if this HTTP header is set by the Gateway client.
Fixes CODY-2555
N/A

Gateway: forward X-Fireworks-Genie header from client

---

cmd/frontend/internal/app/jscontext/jscontext.go

[Slack Context](https://sourcegraph.slack.com/archives/C07KZF47K/p1719302853433329)
We have code monitoring disabled on Dotcom, however in jscontext, it's not disabled, this PR fixes that.
Starting a Sourcegraph instance in Dotcom mode, should result in `window.context. codeMonitoringEnabled` set to `false`.

chore(code-search): disable codemonitoring dotcom (jscontext)

---

sg.config.yaml

The `sg start web-standalone-prod` was set to target dogfood, which has been torn down a while ago. So this just can't work. 
CI

chore(local): drop now outdated web-standalone-prod

---

internal/codeintel/codenav/gittree_translator.go
internal/codeintel/codenav/gittree_translator_test.go
internal/codeintel/codenav/mocks_test.go
internal/codeintel/codenav/request_state.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_definitions_test.go
internal/codeintel/codenav/service_diagnostics_test.go
internal/codeintel/codenav/service_hover_test.go
internal/codeintel/codenav/service_new_test.go
internal/codeintel/codenav/service_ranges_test.go
internal/codeintel/codenav/service_stencil_test.go
internal/codeintel/codenav/transport/graphql/root_resolver_test.go

Previously, the code had several problems:
- There was code which seemed like it was handling path renames across
commits, but it was just a no-op. It was not documented why it was
implemented that way.
- The Position adjustment API and Range adjustment APIs were inconsistent.
- The Position and Range adjustment APIs suggested that they could
handle file renames, but they don't/cannot.
- The mocking logic was just returning wrong outputs (commits
instead of paths in one place).
This patch documents the rationale behind the lack of rename handling,
as well as adds a slow-but-correct form of Document checking.
Covered by existing tests? 🤷🏽

chore: Refactor and document GitTreeTranslator

---

.aspect/bazelrc/ci.sourcegraph.bazelrc

The "Delivery Manifest" bazel commands messing stuff up again :pensive: 
CI

chore(ci): emit compact executon log in CI for test + build commands only

---

internal/appliance/BUILD.bazel
internal/appliance/html.go
internal/appliance/web/template/layout.gohtml
internal/appliance/web/template/setup.gohtml

To avoid duplication of common elements from page to page.
In preparation for introducing some more pages, it made sense to extract a layout.
Relates to https://linear.app/sourcegraph/issue/REL-20/maintenance-ui-admin-must-configure-initial-password-on-first-boot but does not close it.
Manual only - we don't have automated tests for the appliance UI, yet.

chore(appliance): extract layout template

---

.bazelignore

Addresses the following error that was missed due to not happening to me locally, see original: https://github.com/sourcegraph/sourcegraph/pull/59638
```
ERROR: Traceback (most recent call last):
File "/Users/will/code/sourcegraph/client/backstage-frontend/node_modules/@sourcegraph/build-config/BUILD.bazel", line 9, column 22, in <toplevel>
npm_link_all_packages(name = "node_modules")
File "/private/var/tmp/_bazel_will/dcc801c077cac507d08c05a871989466/external/npm/defs.bzl", line 3214, column 13, in npm_link_all_packages
fail(msg)
Error in fail: The npm_link_all_packages() macro loaded from @npm//:defs.bzl and called in bazel package 'client/backstage-frontend/node_modules/@sourcegraph/build-config' may only be called in bazel packages that correspond to the pnpm root package or pnpm …
```

chore(bazel): add client/backstage-frontend to bazelignore

---

wolfi-images/defs.bzl

While staring at execution logs locally I noticed that the stamp files stable-status.txt and volatile-status.txt were inputs to targets such as `//wolfi-images/sourcegraph-base:wolfi_config`, causing these `yq` targets to be executed every time `--stamp` changes or stable stamp vars change. I don't know how this interacts with BwoB. Will ask in the Bazel slack for clarification https://bazelbuild.slack.com/archives/CA31HN1T3/p1719324079626239
`bazel build` on an oci_image target works fine, confirmed by CI

chore(bazel): don't stamp yq rule for wolfi base images

---

client/branded/src/search-ui/input/SearchBox.story.tsx
client/branded/src/search-ui/input/SearchBox.tsx
client/branded/src/search-ui/input/toggles/Toggles.test.tsx
client/branded/src/search-ui/input/toggles/Toggles.tsx
client/branded/src/search-ui/input/toggles/__snapshots__/Toggles.test.tsx.snap
client/shared/src/search/searchQueryState.tsx
client/vscode/src/webview/search-panel/SearchHomeView.tsx
client/vscode/src/webview/search-panel/SearchResultsView.tsx
client/vscode/src/webview/sidebars/search/SearchSidebarView.tsx
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
client/web/src/search/input/SearchNavbarItem.tsx
client/web/src/stores/navbarSearchQueryState.ts
client/web/src/storm/pages/SearchPage/SearchPageInput.tsx
client/web/src/util/settings.ts

Previously, enabling then disabling the regexp toggle would always set the
patterntype to `keyword`, even when the user has set
`search.defaultPatternType: standard`. Now, toggles always revert back to the
default pattern type.
To support this, this PR adds `defaultPatternType` to the nav bar query state,
which is updated every time there's a settings update. Having
`defaultPatternType` available also lets us fix another bug: when
the default pattern type has been set to `standard` we no longer awkwardly show
`patterntype: standard` in the search bar. (This confusing behavior was
introduced recently in #63326.)
**Overall, this PR set us up to remove `experimentalFeatures.keywordSearch`,
along with the keyword search toggle.** To opt out of keyword search, users can
just set …

Search: always respect default pattern type

---

cmd/frontend/BUILD.bazel
cmd/frontend/main.go
cmd/frontend/shared/BUILD.bazel
cmd/frontend/shared/service.go

This cuts building `./cmd/sourcegraph` from ~60s to ~6s when using `sg start single-program-experimental-blame-sqs` (which is dev only and never needs bundled assets).
n/a, dev experimental only

omit go:embed of big assets from `sg start single-program-experimental-blame-sqs`

---

client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
client/web/src/enterprise/code-monitoring/components/__snapshots__/FormActionArea.test.tsx.snap
client/web/src/enterprise/code-monitoring/components/actions/SlackWebhookAction.tsx

These features have passed the steps needed to take them out of beta. They have been feature-complete and in widespread use for more than a year with no outstanding issues, and they work well.
- https://linear.app/sourcegraph/project/slack-notifications-ga-code-monitoring-7dbb9fa13f62
- https://linear.app/sourcegraph/issue/SRCH-533/remove-beta-label-from-code-monitor-logs-tab
Closes https://linear.app/sourcegraph/issue/SRCH-533/remove-beta-label-from-code-monitor-logs-tab
Create a new code monitor with a Slack notif. Ensure it works e2e by pushing a commit that matches and watching it show up in Slack (https://sourcegraph.slack.com/archives/C68386Z5Z/p1719357942294309).
- Code monitoring Slack notifications, previously in beta, are now GA. This feature lets you post matching code changes …

remove beta labels for code monitoring Slack notifs & logs

---

client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionNode.tsx
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/utils.ts

The current "name" thing is not used anywhere for subscriptions - all internal capabilities and APIs depend use the UUID, and Enterprise Portal will use the UUID as well.
This change replaces all name/IDs with the UUID, prefixed in Enterprise Portal format, as we prepare to launch Enterprise Portal in more places (such as Cody Analytics: https://linear.app/sourcegraph/issue/CORE-101). This is particularly relevant for Cody Analytics so I can document how to find the UUID in a way that isn't "get it from the URL".
It's not super beautiful in the subscriptions list, but as we progress on the migration to Enterprise Portal I plan to replace the ID in the list with "Display name", which is a first-class citizen in Enterprise Portal.

feat/dotcom: show subscription UUID in Enterprise Portal format

---

client/web/src/enterprise/code-monitoring/components/FormTriggerArea.module.scss

The tooltips for autocomplete and diagnostics in the code monitor query editor were being chopped off due to an `overflow: hidden`. Now they show up.
Before (note the tiny vertical border that is part of the tooltip above the text):
After:
Hover over a diagnostic at https://sourcegraph.test:3443/code-monitoring/new and confirm the tooltip shows.
- Fixed an issue when creating or editing a code monitor that obscured helpful tooltips in the query editor.

fix chopped-off tooltips in code monitor query input

---

client/web-sveltekit/src/lib/repo/HistoryPanel.svelte
client/web-sveltekit/src/lib/repo/url.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/DiffView.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/OpenInCodeHostAction.svelte

Fixes srch-131
It was reported that the new web app doesn't preserve the selected lines when navigating to the corresponding file in the code host. This commit fixes that.
Additionally this commit adds file actions (most importantly the 'view in codehost' one) to the 'file at revision' view. I've excluded the 'open in editor' action from that view because I don't think it works with different commits (although that would also be a problem if someone was browsing the repo at a specific commit).
And while working on that I also fixed the 'view at commit' button in the history panel, which should not show 'close commit' when the inline diff view is open and the missing file icon in the inline diff view.
Manual testing:
- Selected lines are preserved
- The currently selected revision …

fix(svelte): Preserve selected lines in codehost URL

---

client/web-sveltekit/src/lib/repo/RepoPopover/RepoPopover.svelte
client/web-sveltekit/src/lib/repo/RepoStars.svelte

This is the only one I know of that's left from SRCH-551, so saying this fixes SRCH-551.
Before:
After:

Chore: fix repo stars alignment

---

client/web/src/enterprise/code-monitoring/CodeMonitoringLogs.tsx
client/web/src/enterprise/code-monitoring/components/logs/TriggerEvent.tsx
client/web/src/enterprise/code-monitoring/testing/util.ts

Fixes the "missing key" React warning.
Ensure no console warning

add React key to fragments in code monitoring logs

---

client/branded/src/search-ui/input/CodeMirrorQueryInput.tsx
client/branded/src/search-ui/input/codemirror/parsedQuery.ts
client/web/src/enterprise/code-monitoring/components/FormTriggerArea.tsx

This is part of the Keyword Search GA project (see background below). 
The core change is that we use the default pattern type consistently for the query input field and preview. Before, we hardcoded `literal` as the default and used `standard` for previews. 
This is does not affect existing code monitors.
Other fixes:
- show suggestions that were previously hidden
- highlight keyword queries correctly
Background:
- "keyword" will soon be the new default pattern type
- the default pattern type can be overridden in the user/global settings
- query fields in all of our products should respect the default
Test Plan:
- The unit test is currently "skipped" with the following comment
```
// TODO: these tests trigger an error with CodeMirror, complaining about being
// loaded twice, see …
```

code monitors: respect default pattern type

---

client/web/src/featureFlags/featureFlags.ts
client/web/src/site-admin/SiteAdminFeatureFlagsPage.tsx

ref CLO-380
on Cloud, customer changes to feature flags are overridden by our automation. let's add a warning message to avoid suprises.

cloud: add feature flags to show no edit warning

---

client/web-sveltekit/package.json
pnpm-lock.yaml

This upgrades SvelteKit for good measure. I think a lot of the fixes are not relevant to us but
https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fkit%402.5.8 is interesting and makes navigating around in the app after a dev server start less jarring.
`pnpm dev`, `pnpm build` and `bazel test //client/web-sveltekit:svelte-check`

chore(svelte): Upgrade SvelteKit

---

client/shared/src/settings/settings.tsx

This PR turns on the new Cody Web by default for everyone. It's still possible to opt-out to the old Cody Web with `"newCodyWeb": false` in your experimental features in settings.
I forgot that the dot com instance seeds its global settings and site configuration from files and 
doesn't allow us to override specific settings there; 
- Check that the new Cody Web client is available to you without any feature flag by default

Enable new Cody Web by default

---

client/web-sveltekit/src/lib/TreeNode.svelte

Bumped it up to `--secondary`. Also fixed the visual centering against the new lucide chevrons.
Fixes SRCH-485

Svelte: improve contrast for file tree guide line

---

cmd/enterprise-portal/service/service.go
cmd/msp-example/service/service.go
cmd/pings/service/service.go
cmd/telemetry-gateway/service/service.go
dev/build-tracker/main.go
dev/linearhooks/internal/service/service.go
lib/managedservicesplatform/runtime/contract.go
lib/managedservicesplatform/runtime/contract/contract.go
lib/managedservicesplatform/runtime/contract/contract_test.go
lib/managedservicesplatform/runtime/job.go
lib/managedservicesplatform/runtime/service.go

Splits the runtime contract into a JobContract and ServiceContract.
This lets better handle initialisation such as env vars which is conditional depending on the contract type.
ci

msp/runtime: split contract into JobContract and ServiceContract

---

client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.tsx

Closes https://linear.app/sourcegraph/issue/SRCH-620/cody-web-has-incorrect-initial-context-on-blank-repository-page
- Go to the repository root and open cody web, it should has only repository as initial context

Fix initial context for Cody Web on the repository page

---

client/web/src/cody/chat/CodyChatPage.tsx

The New Cody Web client doesn't work for non-auth users, we should never render 
new Cody web client for signed-out users and show cody landing page instead.
- Run local instance and sign out 
- Check that Cody Web page shows the welcome landing page

Cody Web: Fix Cody page for signed out users

---

cmd/enterprise-portal/internal/database/databasetest/databasetest.go
cmd/enterprise-portal/internal/database/internal/tables/tables.go
cmd/enterprise-portal/internal/database/subscriptions/BUILD.bazel
cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go
cmd/enterprise-portal/internal/database/subscriptions/subscriptions_conditions.go

The idea is to have a table of conditions which track reasons etc for major changes to a subscription. These aren't critical - important state still gets a subscription table time field for querying - but should match.
Closes https://linear.app/sourcegraph/issue/CORE-155
Apply https://github.com/sourcegraph/sourcegraph/pull/63452, then `sg run enterprise-portal`

feat/enterpriseportal: initialize subscriptions tables

---

client/web/src/LegacyRouteContext.tsx
client/web/src/cody/codyRoutes.tsx
client/web/src/nav/GlobalNavbar.test.tsx
client/web/src/nav/GlobalNavbar.tsx
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.test.tsx
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx

Previously, this took users to `https://sourcegraph.com/https://sourcegraph.com/cody`, which was because it used `<Navigate />` incorrectly. Now it correctly takes you to https://sourcegraph.com/cody.
Test locally in dotcom mode

fix Cody nav link for unauthed dotcom users

---

client/branded/src/search-ui/input/toggles/Toggles.test.tsx
client/branded/src/search-ui/input/toggles/Toggles.tsx
client/branded/src/search-ui/input/toggles/__snapshots__/Toggles.test.tsx.snap
client/web/src/stores/navbarSearchQueryState.ts

I noticed that the regexp toggle doesn't work anymore if `"search.defaultPatternType": "regexp"`. This is related to a recent change #63410.
We also append `patternType:keyword` in that case which I don't think we want, because we have an UI element to indicate that keyword search is active.
The question I don't know how to answer is: What should happen if `regexp` is the default and the user toggles keyword search off. Should we go back to `regexp` or to `standard`?
To reproduce the original problem, just configure regexp as default and toggle regexp on/off in the search bar.
Test plan:
- manual testing with default pattern type set to "keyword" and "regexp".

search: fix regexp toggle if regexp is default

---

client/web/BUILD.bazel
client/web/src/savedSearches/SavedSearchForm.test.tsx
client/web/src/savedSearches/SavedSearchForm.tsx

This is part of the Keyword GA Project.
Instead of hardcoding the pattern type to "standard" we use the default pattern type. This really only affects highlighting, because users are already forced to explicity state a pattern type by the GraphQL API.
Test plan:
I tested the following workflows:
1. Creating a saved search from search results page
2. Creating a saved search from the user menu
3. Editing an existing saved search after the default patternType had changed

saved searches: use default pattern type

---

CHANGELOG.md
schema/schema.go
schema/settings.schema.json

"lucky" was an experimental pattern type we added about 2 years ago. Judging from the git history and the current code, it was at some point replaced by "smart search" and "search mode", which we also plan to remove soon.
See https://github.com/sourcegraph/sourcegraph/pull/43140 for more context
Test plan:
CI

search: remove "lucky" from default pattern types

---

README.md
cmd/frontend/internal/batches/resolvers/resolver.go
internal/batches/sources/sources.go

@jamesmcnamara  reported a number of 401s when using a PAT that had access to the repositories affected by a Batch Change. I spent some hours looking into this and was amazed by what I found.
That error was happening because there was a leading whitespace in the token in 1password and apparently the github credential validator doesn't care about whitespaces however when this token is being used to push a change, it becomes a problem because the URL now looks like this:
```
https://%20ghp_....@github.com/sourcegraph-testing/markdowns
```
And that's what was calling your failing batch changes with the devx token. I'll push a fix to correct this.
* Added a credential with whitespaces and confirmed that the spaces were correctly removed.
- Whitespaces in Batch Changes …

fix(batch-changes): remove leading and trailing spaces from batch changes credentials

---

dev/sg/enterprise/sg_enterprise.go

Makes destructive updates usable in automation, such as GitHub actions
```
sg enterprise subscription update-membership -subscription-instance-domain='bobheadxi.dev' --auto-approve '...'
```

feat/sg: add -auto-approve option for 'sg enterprise' updates

---

package.json
pnpm-lock.yaml

Fixes [SRCH-627](https://linear.app/sourcegraph/issue/SRCH-627/cody-web-includes-false-code-context-preamble-is-unusable-for-many) 
`cody-web-experimental` 0.1.4 includes fixes for the including intro preamble when we have and when we don't have initial context for the cody chat, [commit with fix](https://github.com/sourcegraph/cody/pull/4605/commits/a0f1c8bdfa5e3aa2c71b024e3bf7d96f62ddaadd)
- Check that in blob UI Cody's chat constantly has context based on the repository which is currently open 
- Check that in Cody Chat standalone page chat has no predefined context and therefore builds prompt without any preamble (so it can answer generic questions properly)

Bump `cody-web-experimental` package version

---

dev/sg/msp/sg_msp.go

Currently the matrix is hardcoded in the msp repo. 
Service operators can forget to add or remove their service from the list.
GitHub supports dynamically generating the matrix from a previous jobs output ([example](https://josh-ops.com/posts/github-actions-dynamic-matrix/))
This PR adds an `sg msp subscription-matrix` command which will generate the matrix we need
Part of CORE-202
Output
```
{"service":[{"id":"cloud-ops","env":"prod","category":"internal"},{"id":"gatekeeper","env":"prod","category":"internal"},{"id":"linearhooks","env":"prod","category":"internal"}]}
```

sg/msp: generate github action subscription matrix dynamically

---

cmd/enterprise-portal/service/iam_model.fga
cmd/enterprise-portal/service/iam_model.fga.yml

Uses the guidance in https://openfga.dev/docs/modeling/testing to craft some rudimentary IAM model tests for Enterprise Portal IAM.
Not automated for now - the model tests must be run manually:
```
go run github.com/openfga/cli/cmd/fga@latest model test --tests='cmd/enterprise-portal/service/iam_model.fga.yml'
```
If we end up changing the model more I'll ask around in dev-infra to see how we should automate this.
CI and:
```
go run github.com/openfga/cli/cmd/fga@latest model test --tests='cmd/enterprise-portal/service/iam_model.fga.yml'
```

chore/enterpriseportal: add test for iam_model

---

dev/sg/enterprise/sg_enterprise.go

Using `append` on a variable, then sharing that variable, surprisingly seems to cause nondeterministic behaviour in the flags. This makes the shared flag set a function so that each command gets its own set to append to.
This is causing some flags to show up as non-existent in automation.
`sg enterprise subscription list -h` now has the correct flags

fix/sg: fix 'sg enterprise' per-command flags

---

client/branded/src/search-ui/components/FileContentSearchResult.test.tsx
client/branded/src/search-ui/components/FileContentSearchResult.tsx
client/vscode/src/webview/search-panel/alias/FileMatchChildren.tsx

Due to changes in the code base, the search extension code when run from `main` shows file names only in the search results page - no matches in the files. This is a regression from the behavior in the deployed extension.
Deployed extension:
Running from `main`:
Turns out the reason is because some shared code expects chunk matches, while the search queries were all returning line matches.
Added support for line matches in the shared code, and then fixed an issue with the search results display not keeping up with `MatchGroups`.
Build and run locally.
```
git switch peterguy/vscode-bring-back-matched-lines-in-search-results
pnpm run build
```
- Launch extension in VSCode: open the `Run and Debug` sidebar view in VS Code, then select `Launch VS Code Extension` from the …

fix(search): VSCode Search extension: bring back matched lines in search results. 

---

cmd/enterprise-portal/internal/database/internal/tables/tables.go
cmd/enterprise-portal/internal/database/subscriptions/BUILD.bazel
cmd/enterprise-portal/internal/database/subscriptions/license_conditions.go
cmd/enterprise-portal/internal/database/subscriptions/licenses.go

Closes https://linear.app/sourcegraph/issue/CORE-157
Potentially controversial decision: storing license data (the JSON data encoded into license keys, and the license key itself) in JSONB. The data in there isn't (and shouldn't be) interesting to query on - they're only used in the context of a single license, so you would never use it as conditions. The only one that might be useful is "license key substring" for parity with what we have today, but that's an internal-only use case and shouldn't be in the hotpath for anything super performance sensitive.
Conditions table is similar to the one introduced in https://github.com/sourcegraph/sourcegraph/pull/63453
CI

feat/enterpriseportal: init licenses tables

---

client/web/src/cody/chat/new-chat/NewCodyChatPage.tsx
client/web/src/cody/management/CodyManagementPage.tsx
client/web/src/cody/management/UseCodyInEditorSection.tsx
client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.tsx
client/web/src/repo/cody/AskCodyButton.module.scss
client/web/src/repo/cody/AskCodyButton.tsx

Improves the Cody PLG management page to have a more prominent link to Cody Web. Also renames `Ask Cody` to `Cody` for simplicity.
Closes https://linear.app/sourcegraph/issue/PRIME-396/improve-web-chat-link-on-cody-manage-page
View in dotcom mode and ensure section looks nice

link to Cody chat on the web from the Cody manage page

---

client/web/src/site-admin/SiteAdminFeatureFlagsPage.tsx

follow up https://github.com/sourcegraph/sourcegraph/pull/63484
got feedback from teammates that it shouldn't be `warning` but `info`
warning usually indicates something is wrong, this is not the case.
n/a

cloud: update feature flag warning severity

---

client/shared/src/codeintel/scip.ts
client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.gql
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.gql
client/web/BUILD.bazel
client/web/src/repo/blob/codemirror/codeintel/api.ts
client/web/src/repo/blob/codemirror/codeintel/occurrences.ts
client/web/src/repo/blob/codemirror/occurrence-utils.ts
schema/schema.go
schema/settings.schema.json

This integrates the new occurrences API into the Svelte webapp. This fixes a number of issues where the syntax highlighting data is not an accurate way to determine hoverable tokens.
(In the Svelte app only:)
Fixes SRCH-582
Fixes SRCH-162 (validated)
Fixes SRCH-299 (validated)
Fixes SRCH-223 (not validated -- do we know of any groovy repos we have with precise indexing set up?)
Missing any?
A bunch of manual testing that the files referenced in those issues now use the data from the occurrences API to provide more accurate hoverable token info. Once release tests are live, I plan to make a few end-to-end tests for all this. I attempted to make a playwright integration test for the hover ranges, but it turns out that it's quite difficult to target a specific text range in playwright. I've …

Codenav: use new occurrences API for symbol definitions

---

dev/sg/interrupt/interrupt.go

* Once all the hooks have finished we now os.Exit ensuring anything else non-process related quits.
* Reduce max interrupt count from 5 -> 2. Restoring what it was previously. This might lead to dangling processes.
[Issue](https://linear.app/sourcegraph/issue/DINF-74/sg-address-sg-hanging-around-after-ctrlc)
Tested locally
* sg - Always os.Exit once shutdown hooks have completed
* sg - Reduce max intterupt count from 5 to 2 to hard exit

fix(sg): reduce max interrupt count and os.Exit always

---

internal/codeintel/codenav/BUILD.bazel
internal/codeintel/codenav/internal/lsifstore/BUILD.bazel
internal/codeintel/codenav/internal/lsifstore/document_metadata.go
internal/codeintel/codenav/internal/lsifstore/document_metadata_test.go
internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
internal/codeintel/codenav/internal/lsifstore/lsifstore_documents_test.go
internal/codeintel/codenav/internal/lsifstore/observability.go
internal/codeintel/codenav/internal/lsifstore/store.go
internal/codeintel/codenav/mocks_test.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_closest_uploads_test.go
internal/codeintel/codenav/service_diagnostics_test.go
internal/codeintel/codenav/service_ranges_test.go
internal/codeintel/codenav/service_stencil_test.go
internal/codeintel/codenav/shared/types.go
internal/codeintel/codenav/transport/graphql/root_resolver_test.go
internal/codeintel/uploads/shared/types.go

Fixes https://linear.app/sourcegraph/issue/GRAPH-700
Previously, there were two code paths which were checking if certain
upload IDs containing a specific repo-relative path. One was using the
better GetPathExists API, the another one that I recently added was
much more stupid, it was deserializing the full SCIP Document.
However, using `GetPathExists` in a loop is also not great; we should
push the loop into the database. This patch replaces both of those usage
sites with a single function that handles bulk filtering, and replaces
the `GetPathExists` lsifstore method with `FindDocumentIDs`.
Q: Why are we returning document IDs if the caller doesn't need them?
A: Getting the document ID is essentially "free", so I thought it would be
better to return a mapping instead of a set.
However, I …

fix: Check (uploadID, path) pairs in bulk

---

client/web/src/integration/nav.test.ts
client/web/src/nav/GlobalNavbar.test.tsx
client/web/src/nav/GlobalNavbar.tsx
client/web/src/nav/NavBar/NavBar.tsx
client/web/src/nav/NavBar/NavDropdown.tsx
client/web/src/nav/UserNavItem.test.tsx
client/web/src/nav/UserNavItem.tsx
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.module.scss
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.test.tsx
client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx
client/web/src/routes.constants.ts

I found it annoying that it took 2 clicks to go to Cody chat: click **Cody** in the global navbar, then click **Web Chat**. Users rarely will visit their dashboard, and that's associated with their user anyway, so it should be under their user. Same 2-click annoyance applies to going to Code Search.
Moves some other links:
- Contexts, Search Jobs, Code Monitors, Notebooks --> moved to "Tools" global navbar item
- Cody dashboard --> moved to user nav item (in top right)
With minimize nav on and off, and with all states of dotcom and user-has-Cody-enabled, ensure matches expectations. The expectations are codified in the tests/
- Code Search and Cody now are one-click links in the global navbar. Other features are in the new "Tools" menu: search contexts, code monitors, search jobs, and …

make Cody and Code Search global navbar items one-click

---

client/branded/src/search-ui/input/CodeMirrorQueryInput.tsx
client/web/src/savedSearches/SavedSearchForm.module.scss

Fixes srch-646
This commit fixes how tokens are decorated in the query input. The "chip" style needs to have lower presedence than the syntax highlighting so that it doesn't get split across the individual parts of e.g. a repo filter.
This commit also removes the activeFilter extension. It was conflicting a bit with the filter decoration. This should be fine since it wasn't used for quite a while in the main search input either.
I also noticed an issue with the size of the CodeMirror input in the saved searches form. I couldn't enter any query actually because the input was too "narrow". Adding `flex:1` fixes that.

fix(search): Token decoration in keyword-enabled query input

---

dev/ci/internal/ci/bazel_helpers.go

Without `ci.sourcegraph.bazelrc` the bazel environment won't have the right credentials to access the db. This adds the rc to the bazel-do invocation.
For context - the `ci.sourcegraph.bazelrc` contains this following
```
common --test_env=PGUSER=postgres
common --test_env=PGPASSWORD=postgres
common --test_env=PGSSLMODE=disable
common --test_env=PGDATABASE=postgres
```
https://buildkite.com/sourcegraph/sourcegraph/builds/280332#01905ef3-1fce-4d76-bf5b-0530dc434cff
* sg - ensure bazel-do invocations use the ci sourcegraph bazelrc

fix(sg/bazel-do): use ci.sourcegraph.bazelrc with bazel-do

---

cmd/frontend/graphqlbackend/codeintel.codenav.graphql
internal/codeintel/codenav/observability.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/syntactic.go
internal/codeintel/codenav/transport/graphql/iface.go
internal/codeintel/codenav/transport/graphql/mocks_test.go
internal/codeintel/codenav/transport/graphql/root_resolver.go
internal/codeintel/codenav/transport/graphql/root_resolver_usages.go
internal/codeintel/resolvers/codenav.go

Closes https://linear.app/sourcegraph/issue/GRAPH-703/syntactic-filtered-search-based-usages
This initial implementation adds search-based usages for the new codenav API.
I'll work on a follow-up PR(https://github.com/sourcegraph/sourcegraph/pull/63509) to get us to feature parity with the current search-based implementation. https://linear.app/sourcegraph/issue/GRAPH-712/determine-usage-kind-for-search-based-usages-by-running-symbol-search
Additionally I've added an implementation note for when I work on pagination next cycle here: https://linear.app/sourcegraph/issue/GRAPH-696/implement-pagination-for-syntactic-and-search-based-usages
Using the API console

Search-based usages for new codenav API

---

cmd/frontend/internal/batches/resolvers/changesets_stats.go
cmd/frontend/internal/batches/resolvers/changesets_stats_test.go

Closes [SRCH-636](https://linear.app/sourcegraph/issue/SRCH-636/batch-changes-overflow-when-calculating-percent-complete)
Added unit tests

fix(batch-changes): fix zero division error resulting in wrong stats computaion

---

sg.config.yaml

As titled - in deployments we ran this by hand already. We use `|| true` to make the forced migration non-blocking if it fails in case it just works, though in local testing it seems that command is idempotent anyway
See https://github.com/sourcegraph/devx-support/issues/1070
```
sg run enterprise-portal
```
```
sql -d sourcegraph -c 'ALTER TABLE enterprise_portal_subscriptions ALTER COLUMN id TYPE uuid USING id::uuid;'
```

fix/enterpriseportal: forcibly run gorm-incompatible migration in local dev

---

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/ReferencePanel.svelte
client/web-sveltekit/vite.config.ts

This commit fixes an issue with layout shifting while loading data in the reference. The class/style was incorrectly applied causing additional padding to be added while data was loading. This commit fixes that and
- adds a divider between the last list item and the loader
- changes the default proxy to be S2. Dotcom didn't make sense anymore now that `pnpm dev:dotcom` does that explicitly.
Manual testing

fix(svelte): Reference layout shift while loading data

---

cmd/frontend/internal/httpapi/completions/handler.go
internal/completions/client/azureopenai/openai.go
internal/completions/types/types.go
internal/conf/computed.go
internal/conf/conftypes/consts.go
schema/schema.go
schema/site.schema.json

[Linear Issue 
](https://linear.app/sourcegraph/issue/CODY-2586/fix-completions-models-api-for-azure-to-use-the-right-model-with-the)
The purpose of this PR is to make a backwords compatible solution such that the completions logic in our codebase for azure supports both the completions API(which is old) and also supports the chat/completions API which is new. This way we can use models from both of them with autocomplete. 
NOTe: Since we can't figure out which model we are using because azure has the deployment name instead of model name and because of that we can't decide which API to use for which model we try with both of the APIs and then the API that works is cached for that model and then we used the cached API logic to choose the api to make subsequent completion calls this way we …

Fix azure completions api

---

cmd/telemetry-gateway/internal/events/events.go
cmd/telemetry-gateway/internal/server/publish_events.go
cmd/telemetry-gateway/internal/server/publish_events_test.go
cmd/telemetry-gateway/internal/server/server.go

To cover very slow requests we have RPC metrics, and I've added some logging on some points where a very slow processing time could be problematic.
CI

fix/telemetrygateway: reduce context cancellation error reports

---

client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
client/web-sveltekit/src/lib/shared.ts
client/web-sveltekit/src/lib/web.ts
client/web-sveltekit/src/lib/wildcard/menu/MenuRadioGroup.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
client/web/BUILD.bazel
client/web/src/repo/blob/codemirror/codeintel/debugOccurrences.ts

This implements the debug view for code intel ranges. Since we're doing work here, it's very useful to be able scan the info while exploratory testing and debugging.
Stacked on https://github.com/sourcegraph/sourcegraph/pull/63473
Note that this does _not_ use the snapshot API. After #63473, everything uses occurrences, so rather than rely on another API request, the only argument to the debug extension is a set of occurrences. This is particularly nice because it would be very easy to do things like:
- Show the occurrences as calculated from syntax highlighting data
- Show the occurrences before and after we make them non-overlapping
Fixes [an open issue that I cannot find]
https://github.com/sourcegraph/sourcegraph/assets/12631702/7a38af22-5361-47d1-a002-b538082f15aa

Svelte: add debug view for code intel occurrences

---

client/branded/src/search-ui/components/FileContentSearchResult.tsx
client/branded/src/search-ui/components/FilePathSearchResult.tsx
client/branded/src/search-ui/results/StreamingSearchResultsList.tsx
client/vscode/src/webview/search-panel/SearchResultsView.tsx

The VSCode Search extension does not support file preview, so hide it from the search results when the search originates from the VSCode Search extension.
Example showing the file preview links (before this PR):
Example without the file preview links (after this PR):
Including visual and functional tests of the file preview functionality.
```
git switch peterguy/vscode-hide-preview-file-link
pnpm run build
```
- Launch extension in VSCode: open the `Run and Debug` sidebar view in VS Code, then select `Launch VS Code Extension` from the dropdown menu.
- Run a search using the search bar.
- See that the file preview link 
The web app uses the branded components also, so run `sg start` or `sg start web-standalone`, do a search and see that the file preview link still exists. …

fix(search): VSCode Search extension: hide file preview link

---

client/web/src/integration/profile.test.ts
client/web/src/user/settings/backend.tsx

Fixes `Cache data may be lost when replacing the user field of a Query object. ...`
n/a

fetch User.id to suppress GraphQL cache warning

---

docker-images/syntax-highlighter/Cargo.Bazel.lock
docker-images/syntax-highlighter/Cargo.lock
docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
docker-images/syntax-highlighter/crates/tree-sitter-all-languages/src/lib.rs

Closes https://linear.app/sourcegraph/issue/GRAPH-718/dont-parse-every-file-twice-in-scip-syntax
While working on parallel scip-syntax I noticed we're re-parsing every file for both globals and locals generation. This PR makes it so we use the same parse tree for both. I've also made it so we don't re-initialize the language parsers for every file. The thread-local-storage aspect of this matters after merging #63536 
```
spring-framework on main [?]
❯ hyperfine --warmup 1 'git archive HEAD | scip-syntax-main index tar - -l java -o main.scip' 'git archive HEAD | scip-syntax index tar - -l java -o single-parse.scip'
Benchmark 1: git archive HEAD | scip-syntax-main index tar - -l java -o main.scip
Time (mean ± σ):      6.894 s ±  0.033 s    [User: 6.877 s, System: 0.093 s]
Range (min … max): …
```

perf(scip-syntax): uses the same parse tree for globals and locals

---

docker-images/syntax-highlighter/Cargo.Bazel.lock
docker-images/syntax-highlighter/Cargo.lock
docker-images/syntax-highlighter/Cargo.toml
docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel
docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
docker-images/syntax-highlighter/crates/scip-syntax/benches/symbol_parsing.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/evaluate.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/lib.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/scip_strict.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/scip_strict/context_error.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/scip_strict/format.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/scip_strict/parse.rs

Adds strict and performant symbol parsing/formatting for `scip-syntax`.
Parsing is "zero" allocation when the symbol does not contain escapes. (Technically it does allocate a Vec to hold the descriptors)
Final benchmark numbers:
```
symbol parsing/parse_v1/10000 [19.158 ms 19.231 ms 19.306 ms]
symbol parsing/parse_v1/100000 [252.10 ms 252.48 ms 252.86 ms]
symbol parsing/parse_v1/1000000 [2.9972 s 3.0033 s 3.0094 s]
symbol parsing/parse_v2/10000 [1.1307 ms 1.1357 ms 1.1413 ms]
symbol parsing/parse_v2/100000 [15.645 ms 15.670 ms 15.697 ms]
symbol parsing/parse_v2/1000000 [191.80 ms 192.11 ms 192.44 ms]
```
Some basic unit tests. Verified manually that it produces the same symbols as the existing parser for all of chromium.scip

scip-syntax: adds strict SCIP symbol parsing and formatting

---

docker-images/syntax-highlighter/Cargo.Bazel.lock
docker-images/syntax-highlighter/Cargo.lock
docker-images/syntax-highlighter/Cargo.toml
docker-images/syntax-highlighter/crates/scip-syntax/Cargo.toml
docker-images/syntax-highlighter/crates/scip-syntax/src/index.rs
docker-images/syntax-highlighter/crates/scip-syntax/src/main.rs
docker-images/syntax-highlighter/crates/scip-syntax/tests/integration_test.rs

Closes https://linear.app/sourcegraph/issue/GRAPH-694/process-documents-in-parallel-in-scip-syntax
Parallelizes syntactic indexing by splitting the different indexing modes into job producers and then consuming them from a pool of workers using the `rayon` library.
`scip-syntax` will use the maximum available parallelism by default. The `-j/--jobs` argument can be used to control the number of worker threads.
Benchmarking on `spring-project/spring-framework`:
```
spring-framework on main
❯ hyperfine -L num_threads 1,4,8,10  'git archive HEAD | scip-syntax index tar - -j {num_threads} -l java' 'scip-syntax index workspace ${PWD} -l java -j {num_threads}'
Benchmark 1: git archive HEAD | scip-syntax index tar - -j 1 -l java
Time (mean ± σ):      7.171 s ±  0.195 s    [User: 7.165 s, System: …
```

scip-syntax: implements parallel processing for workspace and tar commands

---

internal/authz/subrepoperms/sub_repo_perms.go

Randomly stumbled across this code, figured I could simplify the loop a bit.
Should be covered by existing tests?

chore: Simplify path trimming logic in perm checking

---

client/vscode/src/webview/sidebars/auth/AuthSidebarView.tsx

De-cluttering the authentication options for the VSCE. Private code is no longer hosted on sourcegraph.com, so it's confusing to be directed there.
Addresses (at least partially) #45757
```
git switch peterguy/vscode-address-confusing-auth-ux
pnpm build
```
- Launch extension in VSCode: open the `Run and Debug` sidebar view in VS Code, then select `Launch VS Code Extension` from the dropdown menu.
- See that the "Create an account" links are missing from the sidebar
- Remove links to create an account on sourcegraph.com because it no longer hosts private code.

chore(search): VSCode Search extension: Remove signup link for sourcegraph.com

---

.vscode/settings.json

Running `bazel build --output_groups=+types //client/vscode:vscode_typings` caused a format change to `.vscode/settings.json`. The contents of the file are the same; just an entry is now wrapped.
Shouldn't be any needed. Maybe ensure vscode settings work?

chore: preserve format imposed by bazel

---

client/wildcard/src/components/Typography/Label/Label.tsx

When our custom `<Label>` element is labelling a contenteditable element (like a CodeMirror editor), it previously just called `element.focus()`. This focused the element but put the cursor at the start. The native and expected behavior of `<label for="...">` is to focus and put the cursor at the end.
Also fix an issue where this code path would be followed even if the label had no ID, which could result in it erroneously selecting an element with an empty `aria-labelledby` attribute.
In the create/update saved search form, click on the label and ensure it focuses at the end of the CodeMirror component.

make `<Label>` element focus & select at end to match native label behavior

---

client/web/src/org/settings/members/OrgSettingsMembersPage.tsx
client/web/src/user/settings/emails/UserEmail.module.scss
client/web/src/user/settings/emails/UserEmail.tsx

- The buttons for resending the verification email, manually verifying a user's email, and removing a user's email were incorrectly styled and had no padding.
- The org members page had weird columns where a column that only ever had a single button took 50% of the width.
View these pages and ensure they look nicer.
- Minor cosmetic improvements to the pages for managing organization members and user email addresses.

cosmetic improvements to OrgSettingsMemberPage, UserEmail

---

client/vscode/package.json

They are no longer used from settings.json, so they should not appear in the settings.
```
git switch peterguy/vscode-remove-url-and-token-from-config
pnpm build
```
- Launch extension in VSCode: open the `Run and Debug` sidebar view in VS Code, then select `Launch VS Code Extension` from the dropdown menu.
- Navigate to the Settings page (Code --> Settings... or cmd + , on macOS), search for "sourcegraph" and verify that the access token and url are no longer present in the results.
- Remove access token and URL from extension settings because they are managed in the extension now.

chore(search): VSCode Search extension: Remove url and token from configuration

---

.pre-commit-config.yaml
dev/check-tokens.sh
dev/forbidcommit.sh

@chrsmith suggested this idea, which I like very much as well. 
Pretty straightforward: 
- if you're adding something you really don't want to commit and suspect your future self to forget about it, you can add `FORBIDCOMMIT` anywhere in your changes, and precommit will prevent you from accidentally committing it. 
- check is case insensitive.
I went for this instead of `NOCOMMIT` because it could be legitimately be used for a var with the number of commits for example. And that's not really something we want to add a pragma to disable the string itself for either.

chore(local): add FORBIDCOMMIT pragma to prevent accidental commits

---

cmd/frontend/graphqlbackend/org.go
cmd/frontend/graphqlbackend/org_test.go

Fixes https://linear.app/sourcegraph/issue/SRCH-655/site-admins-cant-add-users-wo-verified-emails-to-orgs-if-email-sending
As a site admin on a site with `email.smtp` configured in site config, try inviting a user who lacks a verified email directly. Confirm that it succeeds and does not error out due to not having a verified email.
- Fixed a bug where site admins could not directly add users to an organization if (1) email sending was configured for the instance and (2) the user had no verified email address.

fix bug preventing site admins from directly adding org members when email.smtp was set

---

internal/codeintel/codenav/service.go
internal/codeintel/codenav/syntactic.go
internal/codeintel/codenav/transport/graphql/root_resolver_usages.go

Closes https://linear.app/sourcegraph/issue/GRAPH-712/determine-usage-kind-for-search-based-usages-by-running-symbol-search
We do this by running a type:symbol search and marking all overlapping results as definitions
Here's an [example query to run in the API console](https://sourcegraph.test:3443/api/console#%7B%22query%22%3A%22query%20%7B%5Cn%20%20usagesForSymbol(range%3A%20%7B%5Cn%20%20%20%20repository%3A%20%5C%22github.com%2Fsourcegraph-testing%2Fpinned-zoekt%5C%22%5Cn%20%20%20%20path%3A%20%5C%22matchtree.go%5C%22%5Cn%20%20%20%20revision%3A%20%5C%22ab1b8f09199ea7a731fd80876fc5b0f376ff6882%5C%22%5Cn%20%20%20%20start%3A%20%7B%5Cn%20%20%20%20%20%20line%3A%20268%2C%5Cn%20%20%20%20%20%20character%3A%2032%5Cn%20%20%20%20%7D%2C%20end%3A%20%7B%5Cn%20%20%20%20%20%20line%3A%20268%5Ct%2C%5Cn%20% …

Marks search-based usages as definitions or references

---

client/web-sveltekit/.storybook/main.ts

Using unplugin icons with storybook results in build failures. This is a workaround I found in an issue about it.
`pnpm storybook` works.

fix(svelte): Fix unplugin icons usage in storybook

---

.vscode/settings.json
client/web/src/components/gitHubApps/CreateGitHubAppPage.tsx
client/web/src/enterprise/batches/settings/AddCredentialModal.module.scss
client/web/src/enterprise/batches/settings/AddCredentialModal.story.tsx
client/web/src/enterprise/batches/settings/AddCredentialModal.tsx
client/web/src/enterprise/batches/settings/BatchChangesCreateGitHubAppPage.tsx
client/web/src/enterprise/batches/settings/BatchChangesSettingsArea.story.tsx
client/web/src/enterprise/batches/settings/BatchChangesSettingsArea.tsx
client/web/src/enterprise/batches/settings/BatchChangesSiteConfigSettingsPage.tsx
client/web/src/enterprise/batches/settings/CodeHostConnectionNode.story.tsx
client/web/src/enterprise/batches/settings/CodeHostConnectionNode.tsx
client/web/src/enterprise/batches/settings/CodeHostConnections.tsx
client/web/src/featureFlags/featureFlags.ts
client/web/src/site-admin/SiteAdminGitHubAppsArea.tsx
client/web/src/site-admin/routes.tsx
cmd/frontend/graphqlbackend/githubapps.graphql

Closes SRCH-660
Closes SRCH-661
This PR adds the UI flow for adding a GitHub app as a Batch Changes credential. The actual functionality to create the GitHub app and store it's information will be done in a follow up PR.
https://github.com/sourcegraph/sourcegraph/assets/25608335/1089a363-070d-4fd8-8a03-af63cd378947

Implement UI for Github Apps <> Batch Changes integration

---

dev/ci/internal/ci/config.go

It was panicing using the wrong error value
CI
* ci - use correct err value to panic on

fix(ci): panic using correct err

---

cmd/frontend/internal/codycontext/context.go
cmd/frontend/internal/codycontext/context_test.go

Fixes SRCH-658
This fixes an issue with anchoring repos in the keyword search query used for cody context. 
Previously, we would use a `repo:` pattern like `repo:^(?:a)|(?:b)$`. However, the union operator binds loosely, so this is interpreted as matching `(^a)|(b$)` rather than `^(a|b)$`. 
This fixes the pattern so we add the anchors to every repo name. Alternatively, we could modify the behavior of `UnionRegExp`, but that seemed riskier. 
Quick manual test that context for `github.com/sourcegraph/docs` does not return any files from `github.com/sourcegraph/docsite`
- Fixes a bug that caused context to be fetched for Cody from irrelevant repos

Cody context: fix an issue with anchoring repo names

---

client/branded/src/search-ui/components/FileMatchChildren.tsx
client/branded/src/search-ui/components/SymbolSearchResult.tsx
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
client/web-sveltekit/src/routes/search/SearchResults.svelte
client/web/src/repo/blob/CodeMirrorBlob.tsx

Consistent naming of all code copied events. Prompted by a discussion in Slack: https://sourcegraph.slack.com/archives/C05BGNBEPKL/p1719562715227509
CI

(chore)analytics: consistent naming of web code copied events

---

internal/codeintel/codenav/commit_cache.go
internal/codeintel/codenav/gittree_translator.go
internal/codeintel/codenav/request_state.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_new.go
internal/codeintel/codenav/service_new_test.go
internal/codeintel/codenav/service_references_test.go
internal/codeintel/codenav/transport/graphql/iface.go
internal/codeintel/codenav/transport/graphql/mocks_test.go
internal/codeintel/codenav/transport/graphql/root_resolver.go
internal/codeintel/codenav/types.go
internal/codeintel/resolvers/codenav.go
internal/codeintel/uploads/internal/background/backfiller/mocks_test.go
internal/codeintel/uploads/internal/background/expirer/mocks_test.go
internal/codeintel/uploads/internal/background/processor/mocks_test.go
internal/codeintel/uploads/internal/store/commitgraph.go
internal/codeintel/uploads/internal/store/commitgraph_test.go
internal/codeintel/uploads/internal/store/misc.go
internal/codeintel/uploads/internal/store/misc_test.go
internal/codeintel/uploads/internal/store/store.go
internal/codeintel/uploads/mocks_test.go
internal/codeintel/uploads/service.go
internal/codeintel/uploads/shared/BUILD.bazel
internal/codeintel/uploads/shared/types.go

This reduces the chances for confusion with other ints/strings flying around.

chore: Use api.RepoID and api.CommitID in more places

---

client/web/src/components/FilteredConnection/FilterControl.tsx
client/web/src/components/FilteredConnection/FilteredConnection.tsx
client/web/src/components/FilteredConnection/ui/ConnectionForm.tsx
client/web/src/components/FilteredConnection/utils.ts
client/web/src/components/externalServices/ExternalServicesPage.tsx
client/web/src/enterprise/codeintel/configuration/pages/CodeIntelConfigurationPage.tsx
client/web/src/enterprise/codeintel/indexes/pages/CodeIntelPreciseIndexesPage.tsx
client/web/src/enterprise/executors/instances/ExecutorsListPage.tsx
client/web/src/enterprise/searchContexts/SearchContextsList.tsx
client/web/src/notebooks/listPage/NotebooksList.tsx
client/web/src/notebooks/listPage/NotebooksListPage.tsx
client/web/src/site-admin/SiteAdminFeatureFlagsPage.tsx
client/web/src/site-admin/SiteAdminMigrationsPage.tsx
client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
client/web/src/site-admin/SiteAdminPackagesPage.tsx
client/web/src/site-admin/SiteAdminRepositoriesContainer.tsx
client/web/src/site-admin/SiteAdminSlowRequestsPage.tsx
client/web/src/site-admin/SiteAdminSurveyResponsesPage.tsx
client/web/src/site-admin/packages/AddFilterModal.tsx
client/web/src/site-admin/packages/ManageFiltersModal.tsx
client/web/src/site-admin/packages/components/MultiPackageForm.tsx
client/web/src/site-admin/packages/components/SinglePackageForm.tsx
client/web/src/site-admin/packages/modal-content/AddPackageFilterModalContent.tsx
client/web/src/site-admin/packages/modal-content/EditPackageFilterModalContent.tsx

- Renames some types and fields for clarity:
- FilteredConnectionFilter -> Filter
- field name `values` -> `options`
- FilteredConnectionFilterValue -> FilterOption
- Avoids passing around unnecessary data
No behavior change. This makes it easier to use the FilterControl component.
Use existing filtered connections with filters (see the diff for a list of pages that contain this component).

clean up FilteredConnection filter types and code

---

client/web/BUILD.bazel
client/web/src/enterprise/insights/components/creation-ui/form-series/components/form-series-input/FormSeriesInput.tsx
client/web/src/enterprise/insights/components/creation-ui/form-series/components/form-series-input/get-pattern-type-filter.test.ts
client/web/src/enterprise/insights/components/creation-ui/form-series/components/form-series-input/get-pattern-type-filter.ts
client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
client/web/src/enterprise/insights/core/backend/gql-backend/methods/get-backend-insight-data/deserializators.ts
client/web/src/enterprise/insights/core/backend/utils/create-line-chart-content.ts
client/web/src/enterprise/insights/core/hooks/live-preview-insight/use-live-preview-series-insight.ts
client/web/src/enterprise/insights/pages/insights/creation/capture-group/components/search-query-checks/SearchQueryChecks.tsx
client/web/src/enterprise/insights/pages/insights/creation/capture-group/utils/search-query-validator.ts
client/web/src/enterprise/insights/pages/insights/insight/components/standalone-backend-insight/StandaloneBackendInsight.tsx
client/web/src/enterprise/insights/pages/landing/getting-started/components/dynamic-code-insight-example/DynamicCodeInsightExample.tsx
internal/database/migration/shared/data/stitched-migration-graph.json
internal/database/schema.codeinsights.json
internal/database/schema.codeinsights.md
migrations/codeinsights/1719914228_insight_series_modify_query/down.sql
migrations/codeinsights/1719914228_insight_series_modify_query/metadata.yaml
migrations/codeinsights/1719914228_insight_series_modify_query/up.sql
migrations/codeinsights/squashed.sql

This PR refactors insights to support the upcoming Keyword Search GA.
New insights are always persisted with `patternType:`.
Queries of existing insights are updated with `patternType:standard <query>` if they don't already specify a pattern type. This reflects the current default of the Stream API and thus, merely makes the pattern type explicit. 
Notes:
- The Insights UI has a lot of query input fields, but there are only 2 fields which allow the user to freely specify a pattern type: the interactive insight on the landing page and the query input field in the "Track Changes" creation form.
Test plan:
- existing tests pass without changes
- manual testing:
- I created a couple of insights and checked that the pattern type is persisted in the db. 
- I experimented with …

insights: persist patternType in db

---

client/web/src/cody/management/SubscriptionStats.tsx
client/web/src/cody/subscription/queries.tsx
cmd/frontend/graphqlbackend/user.go

We [announced unlimited autocomplete for Cody Free](https://sourcegraph.com/blog/making-cody-free-10x-better), but we still have a very high limit technically that we think virtually nobody will hit outside of abuse. It does not make sense to show a limit, though.
Now it always shows "N / unlimited" to all users. For Cody Free users, it no longer shows a limit. For Cody Pro users, it now shows the actual number of autocompletes they've done this month.
View page and ensure it shows correctly.

remove autocomplete limit from Cody dashboard page

---

client/vscode/CHANGELOG.md
client/vscode/package.json

Releasing the Sourcegraph Search VSCode extension
N/A: release

vsce: patch release v2.2.17

---

cmd/cody-gateway/internal/actor/productsubscription/enterpriseportal/BUILD.bazel
cmd/cody-gateway/internal/actor/productsubscription/enterpriseportal/enterpriseportal.go

See https://linear.app/sourcegraph/issue/CORE-203 - it seems the default keepalive and idle options are quite aggressive about keeping idle connections around without verifying them. This change tries to configure some options to ensure idle connections aren't retained for a long time.
`sg start cody-gateway` with `CODY_GATEWAY_ENTERPRISE_PORTAL_URL: https://enterprise-portal.sgdev.org:443` in override
```
[   cody-gateway] INFO cody-gateway.sources.worker.handler actor/source.go:154 Completed sync {"TraceId": "b30602af4f6f3269ed438c86ca37edcc", "SpanId": "154e7f8114b27cab", "handle.timeout": "2m0s", "source": "dotcom-product-subscriptions", "sync_duration": "800.20575ms", "seen": 161}
[   cody-gateway] INFO cody-gateway.sources.worker.handler actor/source.go:165 All sources synced …
```

fix/cody-gateway: use keepalive/idle timeout options for Enterprise Portal

---

client/web/src/repo/blob/CodeMirrorBlob.tsx

Closes srch-673
This disables the inline cody widget when new cody web is enabled. The widget doesn't work with the new sidebar.
Code inspection, it's a simple code change.

fix(search): Don't show inline cody widget when new cody web is enabled

---

cmd/frontend/internal/httpapi/completions/handler.go
internal/modelconfig/types/site_config.go

Couple of trivial changes I teased out of some stacked PRs.
- There were a couple of codepaths where we returned a non-200 in the Completions API but didn't have any logging statements.
- Adds the `ProviderOverride::DisplayName` field. This will allow Sourcegraph admins who provide custom providers the ability to give them friendly names. (So that this information is available so it can be more useful than the raw ID.)
Re: `ProviderOverride.DisplayName`, I don't expect this to be a required field. Or even used very often. But when debugging things, it seemed more helpful than just the opaque provider string like `anthropic-via-sourcegraph` or `anthropic-via-aws-bedrock`.
NA
NA

Trivial additions

---

cmd/enterprise-portal/internal/database/codyaccess/BUILD.bazel
cmd/enterprise-portal/internal/database/codyaccess/codygateway.go
cmd/enterprise-portal/internal/database/internal/tables/BUILD.bazel
cmd/enterprise-portal/internal/database/internal/tables/tables.go

Closes https://linear.app/sourcegraph/issue/CORE-159
I opted to prefix this table name with `codyaccess` instead of `enterprise_portal`, to reflect that it's a different component that owns this table.
CI

feat/enterpriseportal: init Cody Gateway Access table

---

cmd/frontend/internal/httpapi/BUILD.bazel
cmd/frontend/internal/httpapi/httpapi.go
cmd/frontend/internal/modelconfig/BUILD.bazel
cmd/frontend/internal/modelconfig/builder.go
cmd/frontend/internal/modelconfig/builder_test.go
cmd/frontend/internal/modelconfig/httpapi.go
cmd/frontend/internal/modelconfig/init.go
cmd/frontend/internal/modelconfig/service.go
cmd/frontend/shared/BUILD.bazel
cmd/frontend/shared/shared.go
internal/modelconfig/types/site_config.go

This PR exposes a new HTTP endpoint from the `frontend` that will return the LLM models currently supported by the Sourcegraph instance. (Or a 500 if Cody isn't enabled or not configured correctly.)
This endpoint will be used by Cody clients in order to fetch LLM models dynamically, so that new LLM models can automatically be picked up as they are available from Cody Gateway. The underlying data structures will also make it easier for the Sourcegraph instance to configure arbitrary LLM providers, customize model settings, etc.
```zsh
curl \
-H "Authorization: token ${SG_LOCALHOST_TOKEN}" \
https://sourcegraph.test:3443/.api/modelconfig/supported-models.json 
```
This PR is the latest (long) series of steps for enabling arbitrary LLM model configuration in the Sourcegraph backend. This PR …

feat(cody): Expose Sg modelconfig data via HTTP REST API

---

dev/rockskipintegration/main_test.go
internal/observation/observation.go

Closes https://linear.app/sourcegraph/issue/SRC-410/race-in-gitserver-observability
This PR adds a mutex to the internal/observation.ErrCollector type that makes it safe to use across multiple goroutines. 
(This could quite easily happen, as the FinishFunc's OnCancel method runs the logic that accesses/modifies ErrReporter in a separate goroutine:)
https://github.com/sourcegraph/sourcegraph/blob/fa46a26f7a7d3d13833cc7917aaee42d1c94eff9/internal/observation/observation.go#L156-L170
CI now passes and doesn't report race conditions
- Fixed a threadsafety issue in the internal/observation.ErrCollector type

fix/internal/observation: make ErrCollector type threadsafe

---

cmd/frontend/internal/modelconfig/siteconfig_completions.go
cmd/frontend/internal/modelconfig/siteconfig_completions_test.go
internal/modelconfig/types/configuration.go

This PR fixes a small oversight when we convert the site config's "completions" configuration data into the `modelconfig/types.SiteModelConfig` object.
PR https://github.com/sourcegraph/sourcegraph/commit/8e37fcac2632692e430f6b53722a99528df6902a#diff-3c40fc45ac5714fdcbcfb874321044afe3ef449134adcf519d4fba5b966cf18fR71 added a new `User` field to the site configuration, which is used by the Azure OpenAI API provider.
So this piece of data needs to be put into the `internal/modelconfig/types.AzureOpenAIProviderConfig` field so it can available when we refactor the `internal/completions/client/azureopenai` package.
Since rather than pulling this information from the `internal/completions.CompletionRequestParameters::User` we will instead pass the …

Pick up CompletionsConfig.User for the AzureOpenAI API Provider

---

internal/completions/client/azureopenai/openai.go
internal/completions/client/client.go

Fix an annoying inconsistency. There isn't a functional change here, but it's confusing and error prone enough that we need to make this fix.
`internal/completions/client/azureopenai/openai.go` exposes this function:
https://github.com/sourcegraph/sourcegraph/blob/da5968ba1ef1be0307a88b78ccb621a4ff1bef9f/internal/completions/client/azureopenai/openai.go#L116
Note the order of the parameters: `accessToken` and then `endpoint`.
This is where it is called. Notice the order of parameters `endpoint` and then `accessToken`.
https://github.com/sourcegraph/sourcegraph/blob/da5968ba1ef1be0307a88b78ccb621a4ff1bef9f/internal/completions/client/client.go#L40-L41
⚠️ So this is a bug, right?!? Due to some copy and paste error we're passing an access token to the parameter slot that should be an …

Fix annoying consistency

---

cmd/frontend/internal/modelconfig/siteconfig_completions_test.go
internal/modelconfig/types/site_config.go

Fixes a small design oversight when creating the `SourcegraphModelConfig`.
The `SourcegraphModelConfig` type contains all the configuration knobs for a Sourcegraph admin to control how the "Sourcegraph-supplied LLM models" should be used. For example:
- If set to `null`, then Sourcegraph will not provide any LLM models for the instance. And only the admin-supplied providers and models will be used.
- It can be configured to poll Cody Gateway to automatically include "new models" so they can be made available to users of the instance as soon as they are served from Cody Gateway.
However, there's something that is lost in translation between "site admin configuring how LLM models get picked up" and "generating the `types.ModelConfiguration` data structure needed at runtime".
In order to …

Add SourcegraphModelConfig.AccessToken

---

cmd/frontend/internal/modelconfig/siteconfig_completions.go
internal/modelconfig/types/configuration.go
internal/modelconfig/validation.go
internal/modelconfig/validation_test.go

While trying to use the `types.ModelConfiguration` data to configure completion providers, it became clear I missed something.
We expose the `types.GenericProviderConfig` as a bare-bones way to express LLM provider configuration, and it does great. But just knowing the (endpoint, access token) isn't enough to actually serve requests.
We need to know the _shape_ of API requests. e.g. if we should pass that endpoint/access to an OpenAI-compatible, Fireworks-compatible, or Google-compatible API provider.
> NOTE: An alternative approach would be to not add this field to `GenericProviderConfig` entirely, and instead add `AnthropicProvider *GenericProviderConfig`, `GoogleProvider *GenericProviderConfig`, etc. to the `ServerSideProviderConfig`. And essentially have the "service name" be implicit …

Add GenericProviderConfig.ServiceName

---

cmd/frontend/graphqlbackend/codeintel.codenav.graphql

Tried to structure the ordering guarantees as the cascade they form
1. Provenance
2. Repository
3. File
(Or would we group by repository first and then provenance?)
N/A

Documents that usages are first bucketed by provenance

---

client/web/src/enterprise/batches/settings/CommitSigningIntegrations.tsx

The Github failure alert shows up for non-commit signing failures, it should only show up when the kind is `COMMIT_SIGNING`

fix(batches): display failure alert depending on github app kind

---

cmd/worker/shared/BUILD.bazel
cmd/worker/shared/main.go
internal/codeintel/syntactic_indexing/scheduler_config.go
internal/codeintel/syntactic_indexing/scheduler_job.go

Fixes GRAPH-648 (hopefully)
The scheduler interval for syntactic indexing job was incorrect. 
I'm only assuming this will help – Robert suggested deploying this and testing, as from the cursory glance at the code it shouldn't produce _any_ metrics apart from the invocation count, because the feature is disabled on dotcom
- N/A
- We test in production 😎

Fix the scheduling interval for syntactic indexing

---

dev/sg/internal/run/logger.go
dev/sg/sg_start_test.go
lib/output/outputtest/buffer.go

Fixes DINF-82; This was very much a rabbithole. A few things: 
- The race that @bobheadxi mentioned here https://github.com/sourcegraph/sourcegraph/pull/63405#discussion_r1648180713 wasn't from `*output.Output` being unsafe, but `outputtest.Buffer` as it happened again (see [DINF-82](https://linear.app/sourcegraph/issue/DINF-82/devsgsg-test-failed-with-a-detected-race-condition))  
- There something messed up with `cmds.start()`, which sometimes ends up printing the command output _after_ the exit message instead of before. 
- The crude `sort.Strings(want|have)` that was there already fixes that. 
- And without the sleep, it's possible to read the output from the `outputtest.Buffer` before the command outputs get written to it. 
- The `time.Sleep(300 * time.Milliseconds)` …

fix(local): fix race in sg_start_test.go

---

internal/modelconfig/types/refs.go
internal/modelconfig/types/refs_test.go
internal/modelconfig/validation.go

The `ModelRef` encodes three pieces of information to represent the unique identity of the model. So far, we've only needed to pull out the `ProviderID` and `ModelID`. But now that I'm working on reading this data for the completion APIs, it's time to add the `APIVersionID` function too.
Note that these functions should really return an `(string, error)` since it's possible the `ModelRef` they are operating on is invalid. But as-is things will explode loudly enough it won't be too difficult to detect, and leaving the function return type as `string` makes it _much_ easier to use.
I also added a comment about something I'll address when I get to adding support for fetching new models dynamically from Cody Gateway. Right now there is a validation check that probably should exist but …

Add ModelRef.APIVersionID()

---

sg.config.yaml

Related to https://github.com/sourcegraph/cody/pull/4643
~Still stuck on https://sourcegraph.slack.com/archives/C01CSS3TC75/p1719502918899479, waiting on an answer about that.~
EDIT: Not all LLM tokens are in the secrets, but the anthropic one is there, allowing this to move forward.
Locally tested with the aforementioned PR

chore(local): add dotcom-cody-e2e commandset

---

client/web-sveltekit/BUILD.bazel
client/web-sveltekit/src/hooks.client.ts
client/web-sveltekit/src/routes/+error.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/-/commit/[...revspec]/page.spec.ts
client/web-sveltekit/src/routes/[...repo=reporev]/RepoNotFoundError.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/layout.spec.ts

Details about the probblem can be found in srch-527 (fixes srch-527).
This commit implements a workaround via the `handleError` hook. If this function returns an error then SvelteKit is using that instead of its own error object. So we unwrap the error object ourselves (since SvelteKit fails to do that due to bazel build issues) and ensure this way that the correct error is passed to our error template.
Coincidentally we disabled all error related tests in CI, so by enabling these tests again we should see whether this approach works.

fix(svelte): Render correct error page

---

client/web/bundlesize.config.js
client/web/src/cody/chat/new-chat/NewCodyChatPage.tsx
client/web/src/cody/chat/new-chat/components/chat-history-list/ChatHistoryList.module.scss
client/web/src/cody/chat/new-chat/components/chat-history-list/ChatHistoryList.tsx
client/web/src/cody/chat/new-chat/components/chat-ui/ChatUI.module.scss
package.json
pnpm-lock.yaml

This PR bumps `cody-web-experimental` package to 0.2.0 which includes
- Fixes for UI flashes
- Support openCTX mention providers
- Fixes for cursor jumping
- Fixes for style leaking 
Here as well I included a few minor UI fixes for the chat which close 
- [CODY-2721 ](https://linear.app/sourcegraph/issue/CODY-2721/investigate-a-lot-of-empty-chats-being-added-each-time-you-view-a)
- [SRCH-671](https://linear.app/sourcegraph/issue/SRCH-671/truncate-chat-message-in-history-pane-and-show-new-message-instead-of)
- [SRCH-674](https://linear.app/sourcegraph/issue/SRCH-674/dont-show-empty-chats-generated-by-cody-blob-ui-view)
- [SRCH-647](https://linear.app/sourcegraph/issue/SRCH-647/glitches-in-rounded-corners-of-mention-menu)
I will update the package for the Svelte version as a follow-up early …

Bump code-web-experimental version to 0.2.0

---

internal/modelconfig/types/configuration.go
schema/schema.go
schema/site.schema.json

This PR adds a new top-level field to the site configuration `"modelConfiguration"`
which is intended to replace the old `"completions"` field. For now, this is 100%
opt-in (beta feature) and customers should only use this new field if they have
talked with us to confirm it should work in their case.
Today, this configuration is unused, but in future PRs it will actually be used (planned for the 5.5.0 release.)
Additionally, `"modelConfiguration"` acts as a feature-flag. If it is set
and not `null`, then Cody will enable this whole new model configuration system
end-to-end which involves many new components:
* Clients will make use of a new `/.api/modelconfig/supported-models.json` endpoint to query which models the server has available.
* Cody will respect this new site configuration, …

add new "modelConfiguration" schema to site config

---

client/web-sveltekit/src/lib/Hotkey.ts
client/web-sveltekit/src/lib/Popover.svelte

Fixes srch-697
This commit makes two important changes:
- The popover component will now only register the ESC key handler when it is open (und unregister when it closes). This was done by exposing a new function that creates a hotkey without registering it. The existing `registerHotkey` function simply wraps the new function so that existing callsites are not affected by this change.
- The error message was turned into a warning and will now only be triggered in dev builds.
Existing unit test, manual testing.
Before this change: 
After this change: No messages.

fix(svelte): Fixes excessive 'the hotkey ... has already been registered' messages

---

cmd/frontend/internal/batches/resolvers/changeset_counts_test.go
cmd/frontend/internal/batches/webhooks/bitbucketserver_test.go
cmd/frontend/internal/batches/webhooks/github_test.go
internal/batches/reconciler/executor.go
internal/batches/reconciler/executor_test.go
internal/batches/service/service.go
internal/batches/sources/sources.go
internal/batches/sources/sources_test.go
internal/batches/sources/testing/BUILD.bazel
internal/batches/sources/testing/fake.go
internal/batches/syncer/syncer.go

This PR simplifies the Sourcer interface.
We added a couple of args and the `ForChangeset` and `ForExternalService` methods were looking a bit cumbersome to understand.
Existing tests should be passing.

chore(batches): simplify Sourcer interface

---

client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
client/branded/src/search-ui/results/filters/components/dynamic-filter/SearchDynamicFilter.tsx
client/branded/src/search-ui/results/filters/types.ts
client/shared/src/search/stream.ts
client/web-sveltekit/src/lib/search/dynamicFilters/CountBadge.svelte
client/web-sveltekit/src/lib/search/dynamicFilters/Section.svelte
client/web-sveltekit/src/lib/search/dynamicFilters/SectionItem.svelte
client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte
client/web-sveltekit/src/lib/search/dynamicFilters/index.ts
client/web-sveltekit/src/lib/wildcard/Badge.module.scss
client/web-sveltekit/src/routes/search/page.spec.ts

This adds snippets back to the search sidebar, which got missed when it was redesigned.
This includes some refactoring of the Svelte version to account for filter types that do not match 1:1 with the backend types. We initially tried to tie them tightly with the backend types so the backend is the source of truth, but I think we want to have the ability to introduce client-side-only filters, which we already sorta hackily do with the `type:` filters. And it's even more hacky with the `count:` filter in the React webapp (which doesn't look like it was ever implemented in the Svelte version).
In the React app, I made the minimum changes to get this working (no associated refactoring). 
Fixes SRCH-580
Added a couple of simple playwright tests. Manually tested that:
- Snippets in settings …

Search: restore snippets to filters sidebar

---

internal/batches/reconciler/executor.go
internal/batches/sources/azuredevops.go
internal/batches/sources/azuredevops_test.go
internal/batches/sources/bitbucketcloud.go
internal/batches/sources/bitbucketcloud_test.go
internal/batches/sources/bitbucketserver.go
internal/batches/sources/common.go
internal/batches/sources/gerrit.go
internal/batches/sources/gerrit_test.go
internal/batches/sources/github.go
internal/batches/sources/gitlab.go
internal/batches/sources/mocks_test.go
internal/batches/sources/perforce.go
internal/batches/sources/sources.go
internal/batches/sources/sources_test.go
internal/batches/sources/testing/fake.go

This PR allows the use of GitHub app installation token for Gitserver push to a codehost.
* Unit tests should be passing

feat(batches): allow use of github app token for gitserver push

---

cmd/cody-gateway/internal/actor/productsubscription/enterpriseportal/enterpriseportal.go

As titled - we ran into 1 occurrence of a sync failure again: https://sourcegraph.slack.com/archives/C076472745A/p1720278447544509
n/a

fix/codygateway: tweak enterprise-portal dial options

---

internal/batches/sources/sources.go

An earlier merge of my PR caused `main` to be broken due to an import change .
Manually built main to ensure there are no other broken imports and bazel is passing.

fix(batches): fix broken `ghauth` import

---

client/web/src/cody/chat/new-chat/components/chat-ui/ChatUI.module.scss
package.json
pnpm-lock.yaml

Bumps cody web experimental package to 0.2.1 which includes fixes for https://linear.app/sourcegraph/issue/SRCH-633/links-in-the-prompt-has-incorrect-url-in-cody-web
- Check that links in cody web context lists work properly

React app: bump cody web to 0.2.1

---

client/web-sveltekit/src/lib/repo/FileHeader.svelte

While adding a [file with a bunch of special characters in its name](https://sourcegraph.sourcegraph.com/github.com/sgtest/weird/-/blob/filenames/special-characters-~!%40%23%24%25%5E%26*()_+%3D-%60%7B%7D%5B%5D%5C%7C%22'%3F.%2C%3C%3E) to sgtest/weird, I noticed that clicking a link to the file is broken. 
This URI-encodes the path components so following the link does not yield a 404.
Quick manual test that I can click the file name in the header and it goes to the right place.

Svelte: encode path components in file header

---

client/web/src/site-admin/SiteAdminReportBugPage.tsx
cmd/frontend/internal/clientconfig/clientconfig.go
schema/schema.go
schema/site.schema.json

These commits do a few things:
---
46b1303e62ea7e01ba6a441cc55bbe4c166ef5ce corrects a few minor mistakes with the new site config which I introduced in #63654 - namely fixing `examples` entries and nullability in a few cases. Nothing controversial here, just bug fixes.
---
750b61e7dfa661338c9b40042087aed8e795f900 makes it so that the `/.api/client-config` endpoint returns `"modelsAPIEnabled": true,` if `"modelConfiguration"` is set in the site config. For context, `"modelConfiguration"` is a new site config field, which is not used anywhere before this PR, and has this description:
> BETA FEATURE, only enable if you know what you are doing. If set, Cody will use the new model configuration system and ignore the old 'completions' site configuration entirely.
I will send a change to the …

site config: minor fixes, make modelConfiguration enable new backend models API, initial self-hosted model config

---

internal/database/migration/shared/data/stitched-migration-graph.json
internal/database/schema.json
internal/database/schema.md
migrations/frontend/1720165387_notebooks_default_to_keyword_search/down.sql
migrations/frontend/1720165387_notebooks_default_to_keyword_search/metadata.yaml
migrations/frontend/1720165387_notebooks_default_to_keyword_search/up.sql
migrations/frontend/squashed.sql

Relates to https://github.com/sourcegraph/sourcegraph/pull/63472
This changes the default patternType of Notebooks from "standard" to "keyword". As a consequence, all new notebooks will default to keyword search. Existing notebooks will keep using standard search.
Test plan:
- I ran the migration locally and verified that new notebooks use "keyword" as default.

notebooks: set default pattern type to keyword

---

dev/sg/BUILD.bazel
dev/sg/sg_teammate.go

Drive by fix, dropped a few names who left the company and simplified commands. 
See DINF-106 
Before: `sg teammate time|details olaf` 
After: `sg teammate olaf` (shows both of the above) 
Locally tested + CI.

chore(local): simplify sg teammate

---

client/web/src/enterprise/batches/settings/CodeHostConnectionNode.tsx
client/web/src/enterprise/batches/settings/GitHubAppControls.tsx

Closes SRCH-702
This button adds a check button to the `GitHubApps` control that enables users to check if their GitHub app connection is accessible.

feat(batches): Add "check" action to validate Github apps connection

---

client/web-sveltekit/package.json
client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte
pnpm-lock.yaml

This commit updates cody web, making similar changes as [ed493c9](https://github.com/sourcegraph/sourcegraph/commit/ed493c9dd1d886f615efd1242f612ad320cde312) and a81d5e7. I wasn't quite sure about some styles, but I left comments on the respective PRs and tried to at match the styling.
Most importantly this also fixes cody web in the Svelte app which currently appears to be broken. I'd like to get this in as quickly as possible (hence stampers), styles can always be tweaked later.
- Fixed layout (chat container was overflowing).
- Set font family and size to the same we use in the Svelte app for consistency.

fix(svelte): Update cody web

---

client/web-sveltekit/src/lib/cody/CodySidebar.svelte
client/web-sveltekit/src/lib/repo/FileHeader.svelte
client/web-sveltekit/src/lib/repo/OpenCodyAction.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+page.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte

Based on #63677 
Closes srch-691
Closes srch-695
This adds the cody button to the repo "home page" so that cody can be opened from there.
This commit also makes it so that the cody button is hidden when the sidebar opens (like in the React app) and it adds a fixed height to the various headers so that they align well with the sidebar header and don't change size when the cody button is hidden when the sidebar is open.

feat(svelte): Add cody button to repo home page

---

client/web/src/enterprise/batches/settings/BatchChangesSettingsArea.story.tsx
client/web/src/enterprise/batches/settings/BatchChangesSiteConfigSettingsPage.story.tsx
client/web/src/enterprise/batches/settings/CodeHostConnectionNode.story.tsx
client/web/src/enterprise/batches/settings/CodeHostConnectionNode.tsx
client/web/src/enterprise/batches/settings/RemoveCredentialModal.story.tsx
client/web/src/enterprise/batches/settings/ViewCredentialModal.story.tsx
client/web/src/enterprise/batches/settings/backend.ts
cmd/frontend/graphqlbackend/batches.go
cmd/frontend/graphqlbackend/batches.graphql
cmd/frontend/internal/batches/resolvers/resolver.go

We now have the `gitHubApp` field that can be used instead. `isGitHubApp` was only introduced as part of the batch changes integration with github app, and is therefore not released yet.
Closes SRCH-704
Manual testing

chore: drop isGitHubApp field from batch changes credentials

---

client/web/src/enterprise/batches/settings/CodeHostConnectionNode.tsx
client/web/src/enterprise/batches/settings/GitHubAppControls.tsx

Closes SRCH-701
Ideally we would use a DismissibleAlert one level up the React component chain, but that's turning out too tricky for the time we have left: https://sourcegraph.slack.com/archives/C07A21XEP0T/p1720486350310899
Manual testing

fix: better alignemnt of github credentials and check success notice

---

dev/sg/internal/analytics/BUILD.bazel
dev/sg/internal/analytics/oauth.go

We missed during the review that we are not using the `open` helper that wraps using the right method depending on the OS, which means that `sg analytics` doesn't work on Linux as is.

chore(local): sg analytics use the proper open wrapper

---

client/web/src/storm/pages/SearchPage/KeywordSearchCtaSection.tsx

This removes the beta badge from the CTA on the main page.
Closes SPLF-131
Test plan:
- inspected page visually

keyword search: remove beta badge

---

client/web/src/cody/chat/new-chat/components/chat-ui/ChatUI.module.scss
package.json
pnpm-lock.yaml

Updating the `cody-web-experimental` package to the latest version which 
- Fixed problems with telemetry (now we send agent level of telemetry events with `Web.Cody` client name)
- Fixed remote repository context as you switch between chats 
- Added support for cody context filters in file and symbols mentions 
- Improved link rendering for remote files (no more "remote-file://" protocol prefixes.
Also, this PR adds some missing CSS token overrides for the LLM picker on dotcom.
Note: I, by accident, pushed the `0.2.2` version with the same build as I have published already in `0.2.1`. NPM doesn't allow to override the build with the same version, so I had to publish 0.2.3 to make it through to the Sourcegraph repo. This is why we jump from 0.2.1 to 0.2.3
-General manual checks for Cody …

Cody Web: bump cody web to 0.2.3

---

internal/redispool/redispool.go

When active client is 0, there is no limit to the amount of active clients which can lead to Redis quickly reaching it's MaxClient (10000 by default)
For more context see [this slack thread](https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1720448507809479)
CI
* redis-pool: set max active clients to 1000

chore(redis): set max active redis connections to 1000

---

dev/oci_deps.bzl

Patches CVE-2024-24790 by upgrading to 27-0-3 tag. However, the patched version has CVE-2024-24791 😟  and it doesnt have patch.
Build and test image locally.
- Go to `dev/oci_deps.bzl`
- Find the current tag example `docker:26.1.3-dind`
- Go to docker registry and search for updated tag and grab one example: `docker:27.0.3-dind`
- docker pull --platform linux/amd64 docker:27.0.3-dind
- Add `platforms = ["linux/amd64"],` to the oci_pull for building and testing locally
```bzl
oci_pull(
name = "upstream_dind_base",
digest = "sha256:2632da0d24924b179adf1c2e6f4ea6fb866747e84baea6b2ffaa8bff982ce102",
platforms = ["linux/amd64"],
)
```
- Run `sg images build dind`
- For testing, run `docker run --rm -it --entrypoint /bin/sh -v /var/run/docker.sock:/var/run/docker.sock dind:candidate`
- Test …

chore(security): Updated dind image to 27-0-3

---

cmd/frontend/internal/modelconfig/BUILD.bazel
cmd/frontend/internal/modelconfig/init.go
cmd/frontend/internal/modelconfig/siteconfig.go

This causes the `modelconfig` package to actually begin converting the new `"modelConfiguration"` site config which was introduced in #63654 into the internal data types we use for model configuration.
This is all pretty straightforward / lame type conversion code, but carefully written to preserve all the semantics we care about.
Written very carefully, and confirmed that this query:
```
curl -H "Authorization: token $(cat ~/local-token)" https://sourcegraph.test:3443/.api/modelconfig/supported-models.json
```
returns what I would expect with this site configuration:
<details>
<summary>site config</summary>
```
// Setting this field means we are opting into the new Cody model configuration system which is in beta.
"modelConfiguration": {
// Disable use of Sourcegraph's servers for model …
```

modelconfig: handle converting site config JSON -> internal data types

---

client/web-sveltekit/src/auto-imports.d.ts
client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
client/web-sveltekit/src/lib/blame/ReblameMarker.svelte
client/web-sveltekit/src/lib/blame/reblame.ts
client/web-sveltekit/src/lib/web.ts
client/web/src/repo/blob/codemirror/blame-decorations.ts

Closes srch-612
This commit adds a link next to the blame commit message that allows reblaming to a prior commit if available.
It extends the existing blame extension. This won't have any affect on the React app because it doesn't pass the configuration option needed to add the extra gutter.
Some notes:
- I originally used the tooltip component instead of `title` but somehow it starts to break when scrolling the document (tooltips don't show up anymore). I don't know if CodeMirror does anything to the DOM elements that causes this to fail.
- The reblame URL also selected the corresponding line so that the correct line is scrolled into view.
Manual testing

feat(svelte): Add reblame support to blame column

---

internal/byteutils/BUILD.bazel
internal/byteutils/lineindex.go
internal/byteutils/lineindex_test.go

This adds a line index utility. Frequently, I want to be able to efficiently index a file to extract a specific line or range of lines, but it's surprisingly tricky to get exactly right given weird definitions of "what even is a line" and edge conditions around out-of-bounds and such. 
So this adds a general-purpose utility to pre-calculate the locations of lines in the file, making extracting a line range a zero-allocation, `O(1)` operation.
Not implemented: the same index can also be used to find the line that contains an offset, which I've also needed to do before. But I'll save that for when I actually have an immediate use for it.
Added quickcheck tests, fuzz tests (particularly useful for finding out-of-bounds conditions), and a few manually-defined tests.

Backend: add line index

---

cmd/symbols/squirrel/util.go

The ctx parameter was unused, and I noticed that the parser is called without the request context. Fixing that here.
Test plan:
Code review and CI.

squirrel: Correctly use request context

---

cmd/enterprise-portal/internal/database/internal/upsert/BUILD.bazel
cmd/enterprise-portal/internal/database/internal/upsert/upsert.go
cmd/enterprise-portal/internal/database/internal/upsert/upsert_test.go
cmd/enterprise-portal/internal/database/subscriptions/BUILD.bazel
cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go
cmd/enterprise-portal/internal/database/subscriptions/subscriptions_test.go
cmd/enterprise-portal/internal/subscriptionsservice/adapters.go
cmd/enterprise-portal/internal/subscriptionsservice/v1.go
cmd/enterprise-portal/internal/subscriptionsservice/v1_test.go
lib/enterpriseportal/subscriptions/v1/subscriptions.pb.go
lib/enterpriseportal/subscriptions/v1/subscriptions.proto

Implements upsert for all the subscriptions fields in the DB client. As part of this I generalized the logic for building upsert DB interactions into a new `upsert` package, because this pattern is a common one we'll need to implement to maintain various AIP-update-compliant endpoints, which specifies various upsert behaviours: https://google.aip.dev/134
Part of CORE-216
Part of CORE-156
Integration tests against DB

feat/enterpriseportal: database layer for subscriptions upsert

---

cmd/frontend/graphqlbackend/git_commit.go
cmd/frontend/graphqlbackend/git_commit_test.go
cmd/frontend/graphqlbackend/perforce_changelist.go
cmd/frontend/graphqlbackend/perforce_changelist_test.go

Fixes SRC-431
Mutli-line perforce changelist descriptions were not being handle since the code implicitly assumed they could not exist. This change enables support for them. 
**Changelist view with both single and multiline commits**
**Changelist view with expanded commit message**
**Individual changelist item**
1. Update unit tests
2. Validate both P4 and non-p4 commits work
3. Validate on s2
- Properly render multi-line perforce changelist descriptions

feat(Source): Properly render multi-line changelist messages from Perforce

---

client/web-sveltekit/BUILD.bazel
client/web-sveltekit/package.json
client/web-sveltekit/src/auto-imports.d.ts
client/web-sveltekit/src/lib/search/input/SearchInput.svelte
pnpm-lock.yaml

We don't like the style/alignment of the Lucide case sensitivity and regex icons (the structural search icon seems fine). This commit switches them back to the MDI icons that we used before.
Solution or temporary workaround (tbd) for srch-544

chore(svelte): Use MDI icons for seach input pattern type toggles

---

client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
client/web-sveltekit/src/lib/search/BaseQueryInput.svelte
client/web-sveltekit/src/lib/search/input/SearchInput.svelte
client/web-sveltekit/src/lib/search/results.ts
client/web-sveltekit/src/lib/search/state.ts
client/web-sveltekit/src/routes/search/+page.ts
client/web-sveltekit/src/routes/search/page.gql
client/web-sveltekit/vite.config.ts

Closes srch-103
Currently we don't show the global context filter on the search home page or the search results page (global context is the default context).
This commit does two things:
- It prefills the search input on the search homepage with the user's default context (like the React app)
- It the logic that pre-processed the search query and removed the context filter if it was global.
In other words we simplify the query logic by showing/submitting the search query as is. Notably this doesn't affect how the search input works on repo pages.
- Opening the search home page pre-fills the query input with the default search context
- Submitting a query without a `context:` filter does not add a `context:` filter to the URL or the search input
- If a query contains `context:global` that …

fix(svelte): Prefill search home page query input with (default) context filter

---

cmd/frontend/internal/clientconfig/clientconfig.go
cmd/frontend/internal/completions/resolvers/BUILD.bazel
cmd/frontend/internal/completions/resolvers/resolver.go
cmd/frontend/internal/httpapi/completions/BUILD.bazel
cmd/frontend/internal/httpapi/completions/get_model.go
cmd/frontend/internal/httpapi/completions/handler.go
cmd/frontend/internal/modelconfig/siteconfig.go
internal/completions/client/BUILD.bazel
internal/completions/client/client.go
internal/completions/types/BUILD.bazel
internal/completions/types/types.go
internal/conf/computed.go

This PR has a single goal: pass a new `ModelConfigInfo` type, which has the `Provider` and `Model` we should use to serve a completions request, down into `client.Get()`
This PR explicitly only handles the case we care about for Self-hosted models, and all pieces of logic that I expect will be replaced/superseded by your work @chrsmith are annotated with `// TODO(slimsag): self-hosted-models:` comments so we can easily find and remove them when your work is ready.
Every location I have modified has been carefully wrapped in an if statement like `if conf.Get().SiteConfig().ModelConfiguration != nil` to ensure that this change _only_ affects people who set the new `"modelConfiguration"` site config property.
1. Configured `"modelConfiguration"` and removed `"completions"` in my dev …

pass ModelConfigInfo down to client.Get() for self-hosted-models

---

cmd/cody-gateway/internal/httpapi/BUILD.bazel
cmd/cody-gateway/internal/httpapi/diagnostics.go
cmd/cody-gateway/shared/BUILD.bazel
cmd/cody-gateway/shared/config/config.go
cmd/cody-gateway/shared/main.go
cmd/cody-gateway/shared/redis.go

Currently, nothing really tells that Cody Gateway needs redis, the env var for finding the address is hidden somewhere deep in the redispool package.
In practice, we only use one redis instance, but at some point we started using both redispool.Cache and redispool.Store, which means we maintain two connection pools, leading to more than expected connections.
Test plan:
Code review and CI.

codygateway: Use only one redis pool and make REDIS_ENDPOINT a clear requirement in config

---

cmd/repo-updater/shared/BUILD.bazel
cmd/repo-updater/shared/main.go
cmd/worker/internal/phabricator/BUILD.bazel
cmd/worker/internal/phabricator/job.go
cmd/worker/internal/phabricator/phabricator.go

This syncer doesn't depend on anything in repo updater, so we're moving it to worker instead, where it can selectively be disabled and is properly monitored.
Test plan:
CI passes, code review.

phabricator: Move syncer to worker

---

cmd/repo-updater/shared/main.go

Since we removed on-demand cloning, the scheduler is now expected to always contain all repositories. Thus, we no longer need to constrain the set of uncloned repos to a ginormous ID list.
Test plan:
CI still passes.

scheduler: Simplify query for uncloned repos

---

internal/uploadstore/gcs_client.go
internal/uploadstore/pool.go
internal/uploadstore/reader.go
internal/uploadstore/s3_client.go

These symbols aren't used outside of the package, so unexporting them for a cleaner API surface.
Test plan:
Go compiler doesn't complain.

Unexport some externally irrelevant symbols from uploadstore

---

package.json
pnpm-lock.yaml

Follow up for https://github.com/sourcegraph/cody/pull/4826
In the latest release, 0.2.4, we fixed the problem that @fkling found about links [here](https://linear.app/sourcegraph/issue/SRCH-633/links-in-the-prompt-has-incorrect-url-in-cody-web#comment-b9427c46); cody assistance can render links in its response via markdown, and in 0.2.3, these links had deep link vscode command, which didn't work properly in cody web. Now it renders plain links when it's rendered for Cody Web.
- Check that links that Cody assistance provides work properly and don't have any deep links command

Bump cody-web-experimental to 0.2.4

---

sg.config.yaml

https://github.com/sourcegraph/sourcegraph/pull/63736 removed rockskip files, which lead to `sg start` failing because it was still watching those. This PR removes the watch and lets `sg start` succeed again.
Existing CI, manual test of `sg start`

fix: remove watch path that's gone

---

client/web-sveltekit/package.json
pnpm-lock.yaml

Similar to https://github.com/sourcegraph/sourcegraph/pull/63742 this updates to the latest cody web version in the new web app.
Manual testing

chore(svelte): Update cody web version

---

internal/batches/reconciler/executor.go

This check was wrong as we create a non-credential source only when the ChangesetSource strategy isn't `GitHubApp`
Manual testing

fix(batches): enable check for creating source as non credential

---

wolfi-images/opentelemetry-collector.lock.json

We need to update the wolfi lock image for https://github.com/sourcegraph/sourcegraph/pull/63171 in order for `sg run` to work
We've made all the changes to the deployment repos for this to be pushed out in the release today. 
- fix(build): update wolfi lock for otel-collector

fix(build): update wolfi image lock for otel

---

internal/txemail/txemail.go

Before, the smtp.Dial function had no cancellation mechanism - meaning that you could be waiting for several minutes to try to establish a connection before it gives up. 
I work around this by establishing a TCP connection myself to the appropriate address, and using  [net.DialContext](https://pkg.go.dev/net#Dialer.DialContext) to cancel the dial process if either:
1. The parent context cancels
2. 30 seconds have passed 
Afterwards, we construct the smtp.Client ourselves using [smtp.NewClient](https://pkg.go.dev/net/smtp#NewClient)
This only changes what happens when we try to establish a connection - it doesn't change any behavior around sending emails afterwards.
Manual testing. 
1. On local dev, I edited the credentials in the [dev-private site configuration file …

fix/internal/txemail: add timeout for SMTP connection establishment

---

client/web-sveltekit/src/lib/repo/Permalink.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
client/web-sveltekit/src/routes/[...repo=reporev]/+layout.ts

Fixes srch-589
This implements the 'y' shortcut to navigate to the permalink page, just
like we have in the React app.
According to aria guidelines it should be possible to disable single
character shortcuts but this actually never worked for the 'y' shortcut
because it was implemented differently. So adding it without the option
to turn it off is at least not a regression.
For reference this the code handling the shortcut in the React app: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@d9dff1191a3bad812aa5b50315b8e77ee0e40e55/-/blob/client/web/src/repo/actions/CopyPermalinkAction.tsx?L64-77
When initially implementing this I noticed that there is a slight delay between pressing 'y' and the URL/UI updating. That's because SvelteKit has to wait for …

feat(svelte): Add 'y' shortcut to navigate to permalink 

---

cmd/frontend/internal/httpapi/completions/BUILD.bazel
cmd/frontend/internal/httpapi/completions/entconfig_anthropic_test.go
cmd/frontend/internal/httpapi/completions/entconfig_awsbedrock_test.go
cmd/frontend/internal/httpapi/completions/entconfig_azureopenai_test.go
cmd/frontend/internal/httpapi/completions/entconfig_base_test.go
internal/completions/client/azureopenai/BUILD.bazel
internal/completions/client/azureopenai/openai.go
internal/conf/computed_test.go

This PR adds more unit tests for the "Chat Completions" HTTP endpoint. The goal is to have unit tests for more of the one-off quirks that we support today, so that we can catch any regressions when refactoring this code.
This PR adds _another layer_ of test infrastructure to use to streamline writing completion tests. (Since they are kinda involved, and are mocking out multiple interactions, it's kinda necessary.)
It introduces a new data type `completionsRequestTestData` which contains all of the "inputs" to the test case, as well as some of the things we want to validate.
```go
type completionsRequestTestData struct {
SiteConfig schema.SiteConfiguration
UserCompletionRequest types.CodyCompletionRequestParameters
WantRequestToLLMProvider map[string]any
WantRequestToLLMProviderPath string …
```

Add more Completions handler tests

---

internal/codeintel/uploads/internal/background/commitgraph/job_commitgraph.go
internal/codeintel/uploads/internal/store/commitgraph.go
internal/codeintel/uploads/internal/store/observability.go
internal/codeintel/uploads/internal/store/uploads_test.go
internal/codeintel/uploads/service.go

Missed some places during https://github.com/sourcegraph/sourcegraph/pull/61131
n/a, updating comments only

chore: Replace 'dumps' terminology in comments

---

cmd/gitserver/internal/perforce/protects.go

Minor adjustment to decode the base64 encoded JSON directly to bytes instead of a string, and update the associated coment.
Existing test should still pass

Update comment and decode bytes instead

---

internal/env/env.go

When `internal/env/env.Get` detects a difference in between already registered descriptions, it panics (good). But the error message doesn't tell you what's the difference and you're left out to put a few prints for yourself in the code to try to understand what's wrong. 
See also: https://github.com/sourcegraph/sourcegraph/pull/63786
Before:
After: 
CI + local run 
- When conflicting env var are detected, print the two to ease debugging.

chore(config): clarify env var already registered panic

---

cmd/frontend/internal/codycontext/context.go
cmd/frontend/internal/codycontext/context_test.go

This PR fixes an important bug in #62976, where we didn't properly map the
symbol line match to the return type. Instead, we accidentally treated symbol
matches like file matches and returned the start of the file.
Add new unit test for symbol match conversion. Extensive manual testing.

Context: return lines around symbol match

---

internal/redispool/redispool.go

`REDIS_ENDPOINT` is now registered by gateway, but it is also registered in `internal/redispool` as the fallback for when the other values are not set.
The real fix would be to not have env vars in that package, and instead each service creates one instance of each of those two in their `cmd/`, but that's a lot of work so short-term fixing it by reading the fallback using os.Getenv.
Test plan:
`sg run cody-gateway` doesn't panic.

gateway: Don't panic because of duplicate env var registration

---

client/web-sveltekit/src/auto-imports.d.ts
client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
client/web-sveltekit/src/lib/repo/FileDiff.gql
client/web-sveltekit/src/lib/repo/FileDiff.svelte
client/web-sveltekit/src/lib/repo/FileDiffHunks.svelte
client/web-sveltekit/src/lib/repo/Permalink.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/-/commit/[...revspec]/page.spec.ts
client/web-sveltekit/src/routes/styles.scss
client/web-sveltekit/src/routes/svelte-overrides.scss

A couple of tweaks to the commit / diff view:
- Linking both file paths in the header for renamed files
- Collapse renamed file diffs without changes by default
- Move "no changes" out of `FileDiffHunks` to not render a border around the test.
- Add description for binary files
- Adjust line height and font size to match what we use in the file view
- Added the `visibly-hidden` utility class to render content for a11y purposes (I didn't  test the changes I made with a screenreader though)
Contributes to SRCH-523
Manual testing
| ![2024-07-11_15-25](https://github.com/sourcegraph/sourcegraph/assets/179026/b4b6444f-5aae-4cd4-acfd-7287df042a88) | ![2024-07-11_15-25_1](https://github.com/sourcegraph/sourcegraph/assets/179026/124b486f-0c73-447b-9879-81aac1 …

chore(svelte): Commit/diff style and behavior tweaks

---

client/shared/src/codeintel/legacy-extensions/util/api.ts
client/web/src/codeintel/ReferencesPanelQueries.ts
client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts
client/web/src/enterprise/insights/core/hooks/live-preview-insight/use-live-preview-lang-stats-insight.ts
client/web/src/enterprise/insights/pages/insights/creation/lang-stats/LangStatsInsightCreationPage.story.tsx
client/web/src/search/backend.tsx
client/web/src/search/results/StreamingSearchResults.test.tsx
client/web/src/search/results/components/search-results-info-bar/SearchResultsInfoBar.test.tsx
cmd/frontend/backend/go_importers.go
cmd/frontend/internal/compute/resolvers/resolvers.go
cmd/frontend/internal/compute/streaming/compute.go
internal/cmd/search-blitz/client.go
internal/cmd/search-blitz/search.graphql
internal/insights/query/streaming/search_client.go
internal/search/streaming/http/client.go

I went through all call sites of the 3 search APIs (Stream API, GQL API, SearchClient (internal)) and made sure that the query syntax version is set to "V3".
Why?
Without this change, a new default search syntax version might have caused a change in behavior for some of the call sites.
- No functional change, so relying mostly on CI
- The codeintel GQL queries set the patternType explicitly, so this change is a NOP.
I tested manually
- search based code intel sends GQL requests with version "V3"
- repo badge still works
- compute GQL returns results

chore(search): update search API call sites to set the version explicitly

---

dev/sg/main.go

The background publisher was started regardless if analytics was disabled or not. This PR makes it so that we only publish analytics if it is enabled.
To make it work and not duplicate the disabled analytics check, I moved the usershell + background context creation to happen earlier.
CI and tested locally
* sg - only start the analytics background publisher when analytics are enabled

fix(sg): do not try to publish analytics when it is disabled

---

client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte

We register ctrl+backspace to go to the repository root, but that should not trigger when an input field, such as the fuzzy finder, is focused.
Fixes srch-681

fix(svelte): Ctrl+backspace in fuzzy finder

---

cmd/frontend/graphqlbackend/search_results_test.go
internal/search/streaming/search_filters.go
internal/search/streaming/search_filters_test.go

The "Exclude" options in the filter panels are very useful, but many are specific to Go. This change generalizes them so they apply in many more cases:
* All files with suffix `_test` plus extension (covers Go, Python, some Ruby, C++, C, more)
* All files with suffix `.test` plus extension (covers Javascript, some Ruby)
* Ruby specs
* Third party folders (common general naming pattern)
Relates to SPLF-70
Added new unit test. Tested manually.

Search: make 'exclude tests' more general

---

client/common/src/util/highlightNode.ts
client/web-sveltekit/BUILD.bazel
client/web-sveltekit/prettier.config.cjs
client/web-sveltekit/src/lib/Tooltip.svelte
client/web-sveltekit/src/lib/dom.ts
client/web-sveltekit/src/lib/path/DisplayPath.stories.svelte
client/web-sveltekit/src/lib/path/DisplayPath.svelte
client/web-sveltekit/src/lib/path/ShrinkablePath.stories.svelte
client/web-sveltekit/src/lib/path/ShrinkablePath.svelte
client/web-sveltekit/src/lib/path/index.ts
client/web-sveltekit/src/lib/repo/FileHeader.svelte
client/web-sveltekit/src/lib/repo/Permalink.svelte
client/web-sveltekit/src/lib/repo/filePopover/FilePopover.svelte
client/web-sveltekit/src/lib/shared.ts
client/web-sveltekit/src/lib/wildcard/CopyButton.svelte
client/web-sveltekit/src/lib/wildcard/menu/MenuText.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/DiffView.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/page.spec.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts
client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
client/web-sveltekit/src/routes/search/FileSearchResultHeader.svelte
client/web-sveltekit/src/routes/search/SearchResult.svelte
client/web-sveltekit/src/routes/search/page.spec.ts
client/web-sveltekit/src/testing/search-testdata.ts

This adds two new components for the common situation of needing to display a styled path. 
- `DisplayPath` handles splitting, coloring, spacing, slotting in a file icon, adding a copy button, and ensuring that no spaces get introduced when copying the path manually
- `ShrinkablePath` is built on top of `DisplayPath` and adds the ability to collapse path elements into a dropdown menu
These are used in three places:
- The file header. There should be no change in behavior except maybe a simplified DOM. This makes use of the "Shrinkable" version of the component.
- The file search result header. This required carefully ensuring that the text content of the node is exactly equal to the path so that the character offsets are correct.
- The file popover, where it is used for both the repo name …

Svelte: add more general shrinkable path

---

client/web/src/enterprise/batches/settings/AddCredentialModal.tsx
client/web/src/enterprise/batches/settings/BatchChangesCreateGitHubAppPage.tsx

Closes SRCH-723
The baseURL for  GitHub apps defaults to `https://github.com` when no `externalServiceURL`, we somehow missed this during our testing.
Manual testing with the GHE instance.

fix(batches): the baseURL for github instance is now updated when creating a GitHub app

---

cmd/cody-gateway/internal/httpapi/completions/fireworks.go
internal/completions/client/fireworks/fireworks.go

1. Change model identifier for deepseek-coder-v2 model for fine-tuned models.
```
curl -vS -X POST http://localhost:9992/v1/completions/fireworks -H 'Authorization: bearer <SGD_TOKEN>' -d '{"stream":false,"max_tokens":50, "model": "fim-lang-specific-model-deepseek-stack-trained", "stop_sequences": ["\n\n"], "prompt": "const value = ", "stream":false, "languageId": "python"}' -H 'X-sourcegraph-feature: code_completions'
```
```
curl -vS -X POST http://localhost:9992/v1/completions/fireworks -H 'Authorization: bearer <SGD_TOKEN>' -d '{"stream":false,"max_tokens":50, "model": "fim-lang-specific-model-deepseek-logs-trained", "stop_sequences": ["\n\n"], "prompt": "const value = ", "stream":false, "languageId": "python"}' -H 'X-sourcegraph-feature: code_completions'
```

change model identifier for finetuned deepseek model

---

cmd/searcher/internal/search/zoekt_search.go
cmd/searcher/internal/search/zoekt_search_test.go
internal/search/job/jobutil/job_test.go

The feature `search-content-based-lang-detection` was never implemented for structural search. This PR fills in the missing pieces.
Fixes #61714
Relates to https://linear.app/sourcegraph/project/make-precise-lang-filtering-default-4f06cfa28567
Two new unit tests checking that the lang filters are now correctly passed to Zoekt.

Structural search: fix precise lang filtering

---

dev/nix/p4-fusion.nix

Failed run here https://github.com/sourcegraph/p4-fusion/actions/runs/9890851838/job/27320002177. 
I tried looking at the sha256 hashes here - https://filehost.perforce.com/perforce/r22.2/bin.macosx12arm64/SHA256SUMS
But there is no clear way to convert to the nix format. There is `nix hash convert` but it's not available in my nix version.
So ... I took the values reported in the workflow and used them in this PR
CI

fix(nix/p4-fusion): update p4-fusion helix-api hashes

---

client/web/src/enterprise/search-jobs/UsersPicker.tsx

This removes the label "admin" next to the user's name and email address. The label has no relevance for Search Jobs.
Test plan:
manual testing
**before**
**after**

chore(search_jobs): remove label "admin" from contact card

---

client/web/dev/BUILD.bazel
client/web/dev/esbuild/chunkCleaner.ts
client/web/dev/esbuild/config.ts
client/web/package.json
sg.config.yaml

when running esbuild in dev mode it continuoysly rebuilds and each time
it produces a bunch of chunk files in client/web/dist/chunks. Which
could lead to a very large chunk directory if the dev server is left
long enough.
Chunk-cleaner removes the dist/chunks directory upon esbuild start up.
**This introduces a ~500ms cost per esbuild.**
Tested locally + CI

fix(esbuild): add chunk cleaner plugin

---

cmd/telemetry-gateway/internal/server/samsm2m/samsm2m.go
cmd/telemetry-gateway/internal/server/server.go

As titled, not much to action about these.
n/a

chore/telemetrygateway: gracefully handle sams introspectToken cancelation

---

cmd/enterprise-portal/internal/database/BUILD.bazel
cmd/enterprise-portal/internal/database/codyaccess/codygateway.go
cmd/enterprise-portal/internal/database/databasetest/BUILD.bazel
cmd/enterprise-portal/internal/database/databasetest/databasetest.go
cmd/enterprise-portal/internal/database/internal/tables/custommigrator/BUILD.bazel
cmd/enterprise-portal/internal/database/internal/tables/custommigrator/custommigrator.go
cmd/enterprise-portal/internal/database/internal/tables/tables.go
cmd/enterprise-portal/internal/database/internal/utctime/BUILD.bazel
cmd/enterprise-portal/internal/database/internal/utctime/utctime.go
cmd/enterprise-portal/internal/database/migrate.go
cmd/enterprise-portal/internal/database/subscriptions/BUILD.bazel
cmd/enterprise-portal/internal/database/subscriptions/license_conditions.go
cmd/enterprise-portal/internal/database/subscriptions/licenses.go
cmd/enterprise-portal/internal/database/subscriptions/licenses_test.go
cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go
cmd/enterprise-portal/internal/database/subscriptions/subscriptions_conditions.go
cmd/enterprise-portal/internal/database/subscriptions/subscriptions_test.go
cmd/enterprise-portal/internal/database/types.go
cmd/enterprise-portal/internal/subscriptionsservice/adapters.go
cmd/enterprise-portal/internal/subscriptionsservice/v1.go

Implements CRUD on the new licenses DB. I had to make significant changes from the initial setup after spending more time working on this.
There's lots of schema changes but that's okay, as we have no data yet.
As in the RPC design, this is intended to accommodate new "types" of licensing in the future, and so the DB is structured as such as well. There's also feedback that context around license management events is very useful - this is encoded in the conditions table, and can be extended to include more types of conditions in the future.
Part of https://linear.app/sourcegraph/issue/CORE-158
Part of https://linear.app/sourcegraph/issue/CORE-100
Integration tests
Locally, running `sg run enterprise-portal` indicates migrations proceed as expected

feat/enterpriseportal: db layer for subscription licenses

---

client/web/src/cody/chat/new-chat/NewCodyChatPage.tsx
client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.tsx

Closes
https://linear.app/sourcegraph/issue/CODY-2847/change-experimental-labels-to-beta
- Check that the cody web page and cody web side panel have beta badges
(cherry-picked from commit fbb0a1fec167050a6312ae9ab76f00c1facf952d)
- Check that the side-panel Cody and Cody Chat page have beta product status badges

[Backport-5.5.x]: Move Cody Web to beta (#63806)

---

client/web-sveltekit/prettier.config.cjs
client/web-sveltekit/src/lib/graphql/urql.test.ts
client/web-sveltekit/src/lib/graphql/urql.ts
client/web-sveltekit/src/lib/repo/HistoryPanel.stories.svelte
client/web-sveltekit/src/lib/repo/HistoryPanel.svelte
client/web-sveltekit/src/lib/search/input/SearchInput.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/ReferencePanel.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.ts
client/web-sveltekit/src/routes/[...repo=reporev]/-/branches/all/+page.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/-/branches/all/+page.ts
client/web-sveltekit/src/routes/[...repo=reporev]/-/commit/[...revspec]/+page.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/-/commit/[...revspec]/+page.ts
client/web-sveltekit/src/routes/[...repo=reporev]/-/tags/+page.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/-/tags/+page.ts

In preparation for other work, this commit substantially refactors the "infinity query" store implementation. The internals have been changed completely which allows us to simplify its public API.
- Simpler configuration. Query responses and next variables are now processed and merged in a single function.
- Restoration support. So far pages/components had to implement restoring the state of an infinity store on their own. Now the restoration strategy is part of the configuration. Pages/components only have to get an opaque snapshot via `store.capture()` and restore it via `store.restore(snapshot)`.
- More predictable state. It wasn't always obvious if the store content stale data e.g. during restoring data. Now `data` will only be set when the data is 'fresh'.
- Smarter 'incremental …

chore(svelte): Refactor infinity query implementation

---

client/web-sveltekit/prettier.config.cjs
client/web-sveltekit/src/lib/repo/utils.ts
client/web-sveltekit/src/lib/search/input/SearchInput.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/+layout.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/RepositoryRevPicker.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/+layout.ts

This commit is in preparation for other work. It refactors how we work with resolved repository and resolved revision information.
The idea was that the top level repo loader should try to resolve the repository information and error if that wasn't possible. Not being able to resolve the revision was accepted, hence this check:
```js
// still render the main repo navigation and header
if (!isRevisionNotFoundErrorLike(repoError)) {
error(400, asError(repoError))
}
```
However the way it was implemented meant that we wouldn't pass any resolved repository information to the sub-pages/layouts when the revision couldn't be resolved, which seems wrong.
With these changes, the top level repo loader now provides a `resolvedRepository` object (where `commit`/`changelist` might be unset) and the …

chore(svelte): Refactor repo loaders

---

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts

These two tests seem to time out regularly (e.g.
https://buildkite.com/sourcegraph/sourcegraph/builds/282453#0190b9e2-2f71-4876-a84f-c40783e906c8)
CI

chore(svelte): Disable tests which time out

---

.github/workflows/pr-auditor.yml

Updates PR-auditor to use the PR-auditor from the devx-service
Once merged, this [PR](https://github.com/sourcegraph/sourcegraph/pull/63846) should fail

pr-auditor: use pr-auditor from devx-service

---

cmd/cody-gateway/internal/httpapi/completions/flagging.go

Requirements:
- Updating the error message to be more descriptive, since the current one is very vague and results in a lot of customer support requests. Example below:
- Updated message says:
- We blocked your request because we detected your prompt to be against our Acceptable Use Policy (https://sourcegraph.com/terms/aup). If you think this is a mistake, please contact support@sourcegraph.com and reference this ID: %s", traceID
manual testing

updated error messaging for blocked requests due to abuse

---

package.json
pnpm-lock.yaml

This PR upgrades the cody web experimental package to 0.2.5, in the new version we fixed
- Telemetry problem with init extension-related events (we don't send install extension events anymore)
- Most recent updates on LLM availability for enterprise instances 
- CI is green
- Manual check on basic Cody Web functionality (highly recommended)

Upgrade cody web experimental package to 0.2.5

---

cmd/worker/internal/batches/BUILD.bazel
cmd/worker/internal/batches/batches_test.go
cmd/worker/internal/batches/bulk_operation_processor_job.go
cmd/worker/internal/batches/janitor_job.go
cmd/worker/internal/batches/reconciler_job.go
cmd/worker/internal/batches/scheduler_job.go
cmd/worker/internal/batches/workspace_resolver_job.go
cmd/worker/internal/codemonitors/BUILD.bazel
cmd/worker/internal/codemonitors/codemonitor_job.go
cmd/worker/internal/codemonitors/codemonitor_job_test.go
cmd/worker/internal/insights/BUILD.bazel
cmd/worker/internal/insights/data_retention_job.go
cmd/worker/internal/insights/job.go
cmd/worker/internal/insights/job_test.go
cmd/worker/internal/insights/query_runner_job.go
cmd/worker/internal/own/BUILD.bazel
cmd/worker/internal/own/job.go
cmd/worker/internal/own/job_test.go
cmd/worker/internal/search/BUILD.bazel
cmd/worker/internal/search/job.go
cmd/worker/internal/search/job_test.go
internal/codemonitors/background/background.go

Relates to https://github.com/sourcegraph/sourcegraph/pull/63686
We check the ENVs added in
https://github.com/sourcegraph/sourcegraph/pull/63686 and disable the corresponding worker jobs if necessary.
New unit tests

chore(worker): disable jobs based on ENVs

---

internal/appliance/reconciler/frontend.go
internal/appliance/reconciler/kubernetes.go
internal/appliance/reconciler/standard_config_test.go

The appliance checks owner references, and only deletes (or updates) resources whose owner references matches the configmap being reconciled.
The current user interface to external databases, is for the admin to create secrets with a well-known name out of band (e.g. "pgsql-auth") and then disable the relevant backing services (e.g. pgsql). This commit fixes a bug in which the appliance would have deleted such secrets, leaving the admin unable to use external databases.
Discovered while investigating
https://linear.app/sourcegraph/issue/REL-14/ensure-pods-roll-when-referenced-secret-changes, but does not close it.
Test against a real k8s API server (envtest) included. Tests that exercise deletion, e.g. `TestApplianceTestSuite/TestResourcesDeletedWhenDisabled`, still pass.

fix(appliance): do not delete unowned resources

---

client/web/src/components/FilteredConnection/utils.ts
client/web/src/nav/GlobalNavbar.tsx
client/web/src/savedSearches/ListPage.tsx
client/web/src/savedSearches/graphql.mocks.ts
client/web/src/savedSearches/graphql.ts
cmd/frontend/internal/savedsearches/resolvers/resolvers.go
cmd/frontend/internal/savedsearches/resolvers/resolvers_test.go

- Don't show the Tools menu on dotcom for now, since there is only 1 item. Users can still access saved searches in their user menu.
- Fix an issue where non-site admins on dotcom would see an error at `/saved-searches` until they changed the Owner filter.
- Other minor code cleanups.
Try being a non-site admin and ensure that `/saved-searches` works.

misc saved searches followups

---

dev/sg/main_test.go
dev/sg/sg_backport.go
dev/sg/sg_images.go
dev/sg/sg_run.go

Noticed several `Usage` using newlines, which makes `-h` output pretty annoying to read as it breaks up the formatting. It tickled me enough to put a formatting check against it, and update the existing usages that were incorrect, to use `Description` or `UsageText` instead :-)
CI, `sg -h` is pretty(er) again (but still very long)

chore/sg: clean up help formatting

---

dev/sg/sg_start.go

`sg run` is supposed to be deprecated in favour of `sg start -cmd`, but the `sg start` completions don't work with `-cmd` like `sg run` does.
This change updates `sg start` completion to check for the `-cmd` flag, and if it is provided, offer completions for commands instead of command_sets_ (the default `sg start` behaviour).
- Completions for `sg start -cmd` now offer valid suggestions.

feat/sg: support correct completions on 'sg start -cmd'

---

client/web/src/cody/chat/new-chat/NewCodyChatPage.tsx
client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.tsx
package.json
pnpm-lock.yaml

S2 Cody Web is broken at the moment. New client-config handlers fail with 401 status because we don't send custom headers, this works for gql queries since they all are POST requests and the browser automatically sends an Origin header for them and this is enough for our auth middleware to check cookies, but with client-config which is rest it's not the case and we should send `X-Requested-Client: Sourcegraph` header to make our auth middleware to pass this query correctly 
Note that this problem doesn't exist in local builds since we proxy all requests and add `X-Requested-Client: Sourcegraph` in dev server. 
See Cody latest build PR for more details https://github.com/sourcegraph/cody/pull/4898
- CI is passing

Upgrade cody web experimental package to 0.2.7

---

cmd/frontend/graphqlbackend/codeintel.autoindexing.graphql

Ideally, we would introduce copies of the old names, deprecate the old ones,
migrate the frontend code, and cut over after a couple of minor releases.
I don't have time for that now, so just updating the docs a bit for clarity.
n/a

docs: Add alternate names and links in GraphQL docs

---

client/web/src/nav/new-global-navigation/NewGlobalNavigationBar.tsx

This was added to the old global navbar but not the one one by accident (by me).
Ensure that the new global navbar shows a Saved Searches link.

show saved searches in new global navbar

---

client/web-sveltekit/BUILD.bazel

Not sure if there's a cleaner way to disable these?
n/a

chore: Mark flaky web-sveltekit tests as manual

---

client/web/src/auth/ResetPasswordPage.tsx
cmd/frontend/internal/context/resolvers/BUILD.bazel
cmd/frontend/internal/context/resolvers/context.go
deps.bzl
go.mod
go.sum
internal/conf/computed.go
schema/schema.go
schema/site.schema.json

Integrates Cohere re-ranking [API](https://cohere.com/rerank) for server-side Cody Context ([RFC 969](https://linear.app/sourcegraph/project/v1-of-two-stage-intent-detection-context-retrieval-system-c4f7093e9eab/overview)). 
Before this PR, we only supported `identity` ranker (which returned all items in the input order), which is still the default choice (when Cohere API key is not provided). 
Closes https://linear.app/sourcegraph/issue/AI-134/add-non-poc-ranking
- tested locally, use 
```
"cody.serverSideContext": {
"reranker": {
"type": "cohere",
"apiKey": "TOKEN"
}
}
```
to test locally

Integrate Cohere re-ranking API

---

cmd/frontend/graphqlbackend/BUILD.bazel
cmd/frontend/graphqlbackend/graphqlbackend.go
cmd/frontend/graphqlbackend/modelconfig.go
cmd/frontend/graphqlbackend/site.go
cmd/frontend/internal/modelconfig/BUILD.bazel
cmd/frontend/internal/modelconfig/init.go
cmd/frontend/internal/modelconfig/resolver.go
internal/modelconfig/types/documents.go

We recently updated the completions APIs to use the `modelconfig` system for managing LLM model configuration. Behind the scenes, we automatically converted the existing site configuration ("completions config") into the newer format so things work as expected.
However, the GraphQL view of the Sourcegraph instance's LLM configuration was not updated to use the `modelconfig` system. And so fi the site admin and opted into using the new-style of configuration data, the data returned would be all sorts of wrong.
(Because the GraphQL handler looked for the "completions config" part of the site config, and not the newer "model configuration" section.)
This PR updates the `CodyLLMConfiguration` GraphQL resolver to return the data from the modelconfig component of the Sourcegraph instance.
Some …

Update CodyLLMConfiguration GraphQL object to be modelconfig aware

---

dev/sg/internal/analytics/background.go

Fixes https://github.com/sourcegraph/devx-support/issues/1097
Before
```
👉 [      step] Pretending to run step "github:pr"
[ github:pr] set -eu
[ github:pr] gh pr create \
[ github:pr]   --fill \
[ github:pr]   --draft \
[ github:pr]   --title "(internal) release_patch: build v5.5.1220" \
[ github:pr]   --body "Test plan: automated release PR, CI will perform additional checks"
[ github:pr] echo "🚢 Please check the associated CI build to ensure the process completed".
[ github:pr]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x1059c1380]
goroutine 42 [running]:
github.com/sourcegraph/sourcegraph/dev/sg/internal/analytics.processEvents({0x10b4a71d8, 0x1400188eaf0}, 0x1400330a140, {{0x10b482ed8?, …
```

sg: check for nil multiError

---

cmd/enterprise-portal/internal/database/subscriptions/license_conditions.go
cmd/enterprise-portal/internal/database/subscriptions/licenses.go
cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go
cmd/enterprise-portal/internal/database/subscriptions/subscriptions_conditions.go

Turns out, `gorm` does not auto-migrate constraints you've removed from the struct schema. You must drop them by hand, or run the commands to drop them explicitly.
```
sg start -cmd enterprise-portal
```
```
\d+ enterprise_portal_*
```
then, comment the custom migrations, and run `sg start -cmd enterprise-portal` again to re-do the migrations. The output of `\d+` matches. Unexpected constraints are gone.

fix/enterpriseportal: drop old gorm fk constraints

---

client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte

Two things related to [this thread](https://sourcegraph.slack.com/archives/C05D629GWJK/p1721255526975099)
First, fix the rev picker width in the sidebar.
Before:
After:
Second, make the search button stretch in the mobile version.
Before:
After:
Manual visual test.

Svelte: fix css selector

---

internal/codeintel/codenav/BUILD.bazel
internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
internal/codeintel/codenav/internal/lsifstore/store.go
internal/codeintel/codenav/mapped_index.go
internal/codeintel/codenav/mapped_index_test.go
internal/codeintel/codenav/mocks_temp.go
internal/codeintel/codenav/scip_utils.go
internal/codeintel/codenav/scip_utils_test.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_snapshot_test.go
internal/codeintel/codenav/service_syntactic_usages_test.go
internal/codeintel/codenav/syntactic.go

Precursor for https://linear.app/sourcegraph/issue/GRAPH-735/test-syntactic-usages
This PR introduces the `MappedIndex` abstraction, which wraps up an upload with a target commit. Its APIs then take care of mapping upload relative paths and repo relative paths, and ranges across commits.
My main motivation for making this change is that I can now test this logic in isolation (which this PR does), and also have an interface that is easy to fake and use to test syntactic usages.
Added unit tests for the `MappedIndex` component, manual testing of the GraphQL APIs show no changes in the syntactic usages output between this PR and master.

refactor(codeintel): Extracts a MappedIndex abstraction over uploads

---

cmd/frontend/graphqlbackend/cody_context.go
cmd/frontend/graphqlbackend/cody_context.graphql
cmd/frontend/internal/context/resolvers/context.go

Replaces the use of discarded/unused/filtered with a consistent use of ignored.

Unify naming of used/ignored context

---

client/web/src/cody/chat/new-chat/NewCodyChatPage.tsx
client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.tsx
package.json
pnpm-lock.yaml

backport https://github.com/sourcegraph/sourcegraph/pull/63863
S2 Cody Web is broken at the moment. New client-config handlers fail with 401 status because we don't send custom headers, this works for gql queries since they all are POST requests and the browser automatically sends an Origin header for them and this is enough for our auth middleware to check cookies, but with client-config which is rest it's not the case and we should send `X-Requested-Client: Sourcegraph` header to make our auth middleware to pass this query correctly
Note that this problem doesn't exist in local builds since we proxy all requests and add `X-Requested-Client: Sourcegraph` in dev server.
See Cody latest build PR for more details
https://github.com/sourcegraph/cody/pull/4898
CI

[Backport 5.5.x] Upgrade cody web experimental package to 0.2.7 (#63863)

---

client/vscode/src/backend/blobContent.ts
client/web/src/enterprise/codeintel/dashboard/backend.ts
client/web/src/integration/graphQlResponseHelpers.ts
client/web/src/repo/blob/backend.ts
client/web/src/repo/blob/definitions.ts
client/web/src/repo/blob/own/HistoryAndOwnBar.story.tsx
client/web/src/repo/blob/own/HistoryAndOwnBar.tsx
client/web/src/repo/blob/own/grapqlQueries.ts

Otherwise Apollo Client complains that it does not know how to cache the result because it does not know which repository ID to associate the result with.
CI

query Repository.id to support Apollo Client caching

---

cmd/frontend/internal/httpapi/completions/handler.go
cmd/frontend/internal/httpapi/completions/handler_test.go

Fixes CODY-2888
Previously, Sourcegraph Enterprise instances with context filters enabled rejected requests from all unknown clients out of concern that they might not respect context filters. This behavior makes it incredibly impractical to release now agent-based clients (CLI, Eclipse, Visual Studio, Neovim, ..) that do respect context filters out of the box thanks to the reused logic in the Cody agent.
This logic suffers from both false positives and false negatives:
- False negatives: upcoming Cody clients (CLI, Eclipse, Visual Studio) already support context filters out of the box thanks to using the Cody agent but they can't send requests unless we add a special case to them. It may require months for these clients to wait for all Enterprise instances to upgrade to a version that …

fix(cody): remove client check for context filters

---

cmd/frontend/internal/httpapi/completions/handler.go
cmd/frontend/internal/httpapi/completions/handler_test.go

Previously, Sourcegraph Enterprise instances with context filters enabled would reject requests from clients that specified a pre-release version like 1.2.0-alpha. This PR makes the version check more relaxed to permit versions like that.
Caught by @taras-yemets  in https://github.com/sourcegraph/sourcegraph/pull/63855/files#r1682690612 
See updated test case.

fix(cody): allow pre-release versions for clients

---

client/web-sveltekit/src/lib/repo/HovercardView.svelte
client/web-sveltekit/src/lib/styles/dropdown.scss

The box-shadow value for code intel hover cards is too dark, and makes the content directly below more difficult to read. 
Before:
After: 
I added a new scss variable so it can be re-used. I'm not sure I've put it in the best place in the codebase though, let me know if you think there's a better location for it. 
Manual/visual testing

Add separate shadow value for hovercards

---

dev/sg/internal/run/BUILD.bazel
dev/sg/internal/run/command.go
dev/sg/internal/run/run_test.go

Closes [DINF-58](https://linear.app/sourcegraph/issue/DINF-58/overwrite-ordering-in-sg)
https://github.com/user-attachments/assets/d8e59a5f-9390-47f7-a6a7-9ccbf97423f8
- Add a `commandset` to the `sg.config.overwrite.yaml`
- This commandset should depend on an existing command in the `sg.config.yaml` file.
- The commandset should also include an `env var` that should override what's set in the `command` contained in the `sg.config.yaml` file.
- Running `sg start <commandset name>` should allow the env ordering matrix shown below
```
Priority: overwrite.command.env > overwrite.commandset.env > command.env > commandset.env.
```
N/A

fix(sg): resolve overwrite `env` ordering in sg

---

dev/sg/internal/secrets/BUILD.bazel
dev/sg/internal/secrets/store.go
dev/sg/internal/secrets/store_test.go
go.mod

Secrets fetched from GSM should probably not be stored locally. As we increase the usage of fetching external secrets, this stuff is increasingly sensitive, particularly for SAMS stuff - every time it's used, we should ensure that the user has the required permissions, and also only store external secrets in-memory.
It looks like several other callsites make use of the persistence of other secrets e.g. those prompted from users, so this change specifically targets the `GetExternal` method. Additionally, I also added a check on load to delete any legacy external secrets that are stored to disk on load - we can remove this after a few weeks.
Unit tests asserts old behaviour and new desired behaviour
`sg start -cmd cody-gateway` uses external secrets and works as expected
After running `sg`, …

feat/sg: do not persist external secrets

---

internal/appliance/reconciler/BUILD.bazel
internal/appliance/reconciler/kubernetes.go

It turns out that Kubernetes objects constructed using client-go don't know their own TypeMeta. There is code in client-go that figures out which resource-scoped HTTP path to call on the kube-apiserver by looking up a mapping of Go object kinds to k8s kinds. A similar facility appears to be exposed to the user by apiutil.GVKForObject().
Closes https://linear.app/sourcegraph/issue/REL-275/reconciler-logs-dont-contain-resource-metadata
Ran `go test -v ./internal/appliance/reconciler`, saw kinds present in logs.

fix(appliance): resource kind present on reconciler logs

---

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts
client/web/src/repo/blame/hooks.ts
client/web/src/repo/blame/shared.ts

Contributes to SRCH-738
Notably, this does not yet identify the root cause of SRCH-738, but it does identify and fix some confounding bugs. It's possible that these actually also _cause_ some of the issues in SRCH-738, but I wanted to at least push these to dotcom, where we can reproduce some of the weirdness. At the very least, it doesn't explain the auth errors being reported.
Tested that, in the event of an error
1) we don't retry forever, and
2) we display the error to the user in an alert, but do not block viewing the rest of the page
Before:
After:
- Fixed an issue with blame view that can cause retry loops and error pages that block interaction with the rest of the UI

Blame: fix some issues with the stream

---

client/web/BUILD.bazel
client/web/src/auth/withAuthenticatedUser.test.tsx
client/web/src/auth/withAuthenticatedUser.tsx
client/web/src/enterprise/searchContexts/CreateSearchContextPage.tsx
client/web/src/enterprise/searchContexts/EditSearchContextPage.tsx
client/web/src/savedSearches/Area.tsx

This improves the typings to remove some inscrutable inferred types and some weird type errors if you didn't use React.PropsWithChildren. Also refactors the code and exposes a new component AuthenticatedUserOnly that's simpler and can be used when you don't need to do prop propagation of authenticatedUser.
CI

withAuthenticatedUser: use react-router-dom hooks & add test

---

internal/database/schema.json
internal/database/schema.md
migrations/frontend/1720651147_add_ips_to_sub_repo_perms_table/down.sql
migrations/frontend/1720651147_add_ips_to_sub_repo_perms_table/metadata.yaml
migrations/frontend/1720651147_add_ips_to_sub_repo_perms_table/up.sql
migrations/frontend/squashed.sql

This PR modifies the sub_repo_permissions database to store the ip addresses associated with each Perforce path rule, as part of the IP based sub repo permissions work. 
The new IP column is implemetned as a []text similar to the path column. The IP address associated with `paths[0]` is stored in the ips column in `ips[0]`. 
For example, the follownig proections table 
```
Protections:
read     user     emily   *                    //depot/elm_proj/...
write    group    devgrp  *                    //...
write    user     *       192.168.41.0/24     -//...
write    user     *       [2001:db8:1:2::]/64 -//...
write    user     joe     *                   -//...
write    user     lisag   *                   -//depot/...
write    user     lisag   *                    //depot/doc/...
super …
```

feature/db/sub_repo_perms: add IPs column to sub repo perms

---

client/web-sveltekit/src/lib/Avatar.svelte
client/web-sveltekit/src/lib/Commit.svelte
client/web-sveltekit/src/lib/repo/FileDiff.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/-/commit/[...revspec]/+page.svelte

I noticed that the commit page doesn't render well on mobile when the commit has a commit message.
This commit refactors how the `Commit` component is rendered, including on mobile, which affects both the commit**s** and the commit page.
The two most important changes:
- The component now uses CSS grid to be more flexible about how individual elements are arranged.
- On mobile we don't show expand the message inline anymore but instead show it full screen. I think that works well for the commits list too because now you can open and read a longer commit message without having to scroll the commits list itself.
Here are side by side comparisons. The differences in the non-mobile view are barely perceivable, it's mostly spacing changes.
| …

feat(svelte): Improve commit page layout on mobile

---

client/web-sveltekit/src/lib/Avatar.svelte
client/web-sveltekit/src/lib/repo/GitReferencesTable.svelte
client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
client/web-sveltekit/src/lib/wildcard/Button.module.scss
client/web-sveltekit/src/lib/wildcard/ButtonGroup.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/-/branches/all/+page.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/-/compare/[...rangeSpec]/+page.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/-/tags/+page.svelte

I just noticed that the revision pickers on the compare page don't work. That's because I made a last minute change to rename the parameter but forgot to acutally update the parameter when constructing the URL.
This also makes two additional changes:
- Remove `{@debug ...}` expression that was accidentally left in (I feel like Svelte should remove this in prod builds).
- Adds a `display` prop to button group, and the rev picker, which works the same as in `Button`. Setting `width: 100%` as done previously causes wrapping on the compare page. I don't think inline elements should be set to 100% width. But without it the button doesn't stretch in the sidebar. This new prop allows the caller to influence this behavior.
| …

fix(svelte): Fix and cleanup compare page

---

cmd/frontend/graphqlbackend/org.go
cmd/frontend/graphqlbackend/org_test.go
cmd/frontend/graphqlbackend/users.go

Previously, only site admins could see the members of an org, even of orgs that they were a member of. This restriction does not make any sense and makes the orgs feature broken on dotcom.
Added test.

allow non-site admins to list their orgs' members on dotcom

---

internal/codeintel/codenav/BUILD.bazel
internal/codeintel/codenav/syntactic.go

Closes https://linear.app/sourcegraph/issue/GRAPH-764/filter-syntactic-results-in-parallel
Cuts search time for large results in half. A lot more gains when combined with a smarter GitTreeTranslator

perf: Find syntactic matches concurrently

---

internal/suspiciousnames/names.go

This could be confused with an official global namespace.
CI

prevent orgs from being named "global" on dotcom

---

client/web/src/components/CopyableText.tsx

For some reason, the indication that the text was copied was removed for secrets. The indication does not show the secret value itself, so I don't see why that change was made. It is helpful to the user to give them feedback that the secret was in fact copied.
Click the copy button after creating an access token

show "Copied" indicator when copying an access token

---

client/web/src/prompts/DetailPage.tsx
client/web/src/prompts/ListPage.tsx
client/web/src/prompts/Page.tsx
client/web/src/prompts/PromptIcon.tsx
client/web/src/savedSearches/ListPage.tsx
client/web/src/savedSearches/Page.tsx
cmd/frontend/graphqlbackend/prompts.go
cmd/frontend/graphqlbackend/saved_searches.go
cmd/frontend/internal/prompts/resolvers/resolvers.go
cmd/frontend/internal/prompts/resolvers/resolvers_test.go
cmd/frontend/internal/savedsearches/resolvers/resolvers.go
cmd/frontend/internal/savedsearches/resolvers/resolvers_test.go

- Add spacing at bottom of page
- Fix viewerCanAdminister check to return `false` not an error when the user is not an administrator of a saved search or prompt
- Improve display of prompt description
In dotcom mode, try loading a prompt or saved search in incognito mode.

saved searches & prompt library fixes

---

cmd/frontend/graphqlbackend/default_settings.go
cmd/frontend/graphqlbackend/org.go
cmd/frontend/graphqlbackend/org_test.go
cmd/frontend/graphqlbackend/preview_repository_comparison_test.go
cmd/frontend/graphqlbackend/repository_comparison_test.go
cmd/frontend/graphqlbackend/repository_text_search_index_test.go
cmd/frontend/graphqlbackend/settings.go
cmd/frontend/graphqlbackend/site.go
cmd/frontend/graphqlbackend/site_admin_test.go
cmd/frontend/graphqlbackend/user.go
cmd/frontend/internal/prompts/resolvers/resolvers_test.go
cmd/frontend/internal/savedsearches/resolvers/resolvers_test.go
internal/database/executor_secrets_test.go

- skip graphqlbackend tests that use the DB when using `go test -short`
- fix race condition in (settingsResolver).Author
- fix OrgMembers.GetByOrgIDAndUserID mocks: The actual function returns a non-nil error (`database.ErrOrgMemberNotFound` type) when the user is not an org member. Our mocks should do the same for correctness.
CI

misc improvements to graphqlbackend

---

cmd/frontend/graphqlbackend/BUILD.bazel
cmd/frontend/graphqlbackend/default_settings.go
cmd/frontend/graphqlbackend/org.go
cmd/frontend/graphqlbackend/settings.go
cmd/frontend/graphqlbackend/settings_cascade.go
cmd/frontend/graphqlbackend/settings_cascade_test.go
cmd/frontend/graphqlbackend/settings_mutation.go
cmd/frontend/graphqlbackend/settings_subject.go
cmd/frontend/graphqlbackend/settings_subject_test.go
cmd/frontend/graphqlbackend/site.go
cmd/frontend/graphqlbackend/user.go
cmd/frontend/graphqlbackend/user_test.go

Previously, a user's or org's settings were protected from unauthorized access in the GraphQL API by access checks far from the actual `SettingCascade` and `LatestSettings` implementations in most cases. This did not present a security issue because on Sourcegraph.com we prevented users from getting a reference to an org they aren't in, and user settings had the right manual access checks.
But the access checks are too far away from the actual resolver methods (so it'd be easy to make a mistake) and were not consistently implemented. **Now, all checks for view-settings-of-subject access go through the same function, `settingsSubjectForNodeAndCheckAccess`.**
One substantive security change is that now site admins may NOT view the settings of an org they are not a member of. This is in line …

explicitly check viewer access to settings in GraphQL API

---

internal/requestclient/BUILD.bazel
internal/requestclient/http.go

https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/18673 configures this env var explicitly. This feels cleaner than having yet-another-dependence-on-this-env-var.
Test plan: Check in after rollout.

dotcom: Remove dotcom on-by-default Cloudflare trust mode

---

client/browser/src/integration/github.test.ts
client/browser/src/integration/gitlab.test.ts
client/browser/src/shared/platform/settings.ts

This API is deprecated (see https://github.com/sourcegraph/sourcegraph/pull/63935). The browser extension is still using it, and we need this PR to remove its usage, and then we need to publish it. Then we can pick up https://github.com/sourcegraph/sourcegraph/pull/63935 again.
Confirm that the browser extension uses the new GraphQL query (in the background page network devtools tab).

use the viewerSettings GraphQL API instead of the 5y+-deprecated viewerConfiguration API

---

internal/appliance/reconciler/frontend.go
internal/appliance/reconciler/frontend_test.go
internal/appliance/reconciler/testdata/golden-fixtures/frontend/after-create-pg-secret.yaml

Idea for https://linear.app/sourcegraph/issue/REL-14/ensure-pods-roll-when-referenced-secret-changes, does not close it though. Please see that issue for more context and alternative approaches considered.
This PR is designed to illustrate the idea more clearly than typing a description of it - do feel free to push back, just because it's already PR'ed doesn't mean it's "too late!". If the general approach is 👍, I can make similar PRs for the other services and their dependencies (basically everything that depends on codeintel/codeinsights DBs and Redis) to close this.
This approach is a bit of a departure from how our helm chart works. That hashes hashes values blocks to determine these annotations. The issue is, that these values blocks often contain references to secrets, and therefore …

feat(appliance): roll frontend deployment when pgsql secret changes

---

client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/page.spec.ts

The test that I enable in this PR has been skipped for a while, and has broken again with https://github.com/sourcegraph/sourcegraph/pull/63463, where we added another aria-label. This additional label lead to playwright rejecting the test, because it found two elements for one query.
This PR removes that label, since we already have a similar one at the button one level up. See screenshot below.
CI

chore(svelte): fix test by removing duplicate aria-label

---

cmd/frontend/internal/authz/webhooks/github.go
cmd/frontend/internal/authz/webhooks/github_test.go

Since permission sync jobs are database backed, we no longer need to sleep in the webhook handler goroutines, since the permission sync jobs have a sleep time themselves.
Tests still pass, no real functional changes.

[update] Remove sleep in goroutine for webhook handlers

---

client/shared/src/search/query/decoratedToken.test.ts
client/shared/src/search/query/decoratedToken.ts
client/shared/src/search/query/hover.ts
client/shared/src/search/query/metrics.ts
client/shared/src/search/query/predicates.test.ts
client/shared/src/search/query/predicates.ts
client/shared/src/search/query/scanner.ts
dev/gqltest/search_test.go
internal/database/repos.go
internal/database/repos_test.go
internal/database/schema.json
internal/database/schema.md
internal/search/job/jobutil/exhaustive_job_test.go
internal/search/job/jobutil/job_test.go
internal/search/query/BUILD.bazel
internal/search/query/predicate.go
internal/search/query/predicate_test.go
internal/search/query/types.go
internal/search/query/types_test.go
internal/search/types.go
internal/types/types.go
migrations/frontend/1721251474_create_gin_index_for_regex_kvps/down.sql
migrations/frontend/1721251474_create_gin_index_for_regex_kvps/metadata.yaml
migrations/frontend/1721251474_create_gin_index_for_regex_kvps/up.sql
migrations/frontend/squashed.sql

This adds support to searching for repo metadata with a regex pattern.
Background: repo metadata is a useful feature for shoehorning business-specific information into the search query language. It allows tagging repos with arbitrary metadata (think ownership info, quality info, 3rd-party system IDs, etc.). This ends up being a useful escape hatch to shim in functionality that is not natively supported in Sourcegraph. 
However it's currently limited to searching with an exact key/value pair. We've had a few requests to extend this to allow searching by pattern because it enables ingesting semi-structured data and making it searchable.
This adds the ability to use a `/.../`-delimited regex pattern to match against both keys and values. For example, `repo:has.meta(team:/^my\/org/)`
Fixes …

Search: add regex support to `repo:has.meta()`

---

deps.bzl
dev/sg/enterprise/sg_enterprise.go
dev/sg/sams/samsflags/BUILD.bazel
dev/sg/sams/samsflags/clientcredentials.go
dev/sg/sams/samsflags/localdev.go
dev/sg/sams/sg_sams.go
go.mod
go.sum

As it says on the tin - various commands related to SAMS can now target dev services integrated against SAMS-dev directly. See test plan for examples.
I've also refactored the `sg sams introspect-token` etc commands in preparation for introducing more `sg sams` commands - the existing commands are now collapsed into `sg sams token introspect` and `sg sams token introspect -p`
Part https://linear.app/sourcegraph/issue/CORE-220, a spike into polishing some local-dev DX for SAMS.
I also upgrade the glamour library because I noticed the JSON pretty-printing was no longer colored - the upgrade fixed that
All the below now work with no additional effort:
```sh
sg sams token introspect -p
sg enterprise subscription list -member.cody-analytics-viewer 'robert@sourcegraph.com'
```
You can use it …

feat/sg: allow sg commands to default to local-dev SAMS-dev credentials

---

cmd/repo-updater/shared/BUILD.bazel
cmd/repo-updater/shared/main.go

One less dotcom specific check, and makes it so we truly disable the batches background jobs as well.
Test plan: Still runs the batches jobs locally.

repoupdater: Make batches init jobs dependent on batches.IsEnabled

---

sg.config.yaml

Prototype what it might be like to have `sg` run `sourcegraph-accounts`. I think this would be a huge improvement over the multi-step, many-things-to-install process that currently exists for SAMS.
There are a couple of quirks, but I think I'll leave this here for now, as this is part https://linear.app/sourcegraph/issue/CORE-220, a timeboxed spike into polishing some local-dev DX for SAMS.
Also see https://github.com/sourcegraph/sourcegraph-accounts/pull/262
```
sg start sourcegraph-accounts
```
Go to 127.0.0.1:9991 and try to log in

feat/sg: prototype 'sg start sourcegraph-accounts'

---

dev/sg/sams/BUILD.bazel
dev/sg/sams/samsflags/clientcredentials.go
dev/sg/sams/sg_sams.go

Adds an equivalent to the curl command we currently share, but in `sg`. If we add a better API around this later it's just an in-place replacement.
Similar to https://github.com/sourcegraph/sourcegraph/pull/63883 this "just works" with zero configuration against SAMS-dev.
Part https://linear.app/sourcegraph/issue/CORE-220, a spike into polishing some local-dev DX for SAMS.
```
sg sams client create -redirect-uris='https://sourcegraph.test:3443/.auth/callback' robert-testing
```
if you hit an error loading the secret, e.g. targeting the prod instance, you get a suggestion to get Entitle access:
```
sg sams client create -redirect-uris='https://sourcegraph.test:3443/.auth/callback' -sams='https://accounts.sourcegraph.com' robert-testing
⚠️ Running sg with a dev build, following flags have …
```

feat/sg: add 'sg sams client create'

---

internal/database/sub_repo_perms_store_test.go

See https://sourcegraph.slack.com/archives/C03K05FCRFH/p1721387628038419
We'll see if this fixes the race condition?
I believe multiple tests are setting the mock configuration object via conf.mock - so hopefully removing the t.Parallel() call fixes the issue.
CI passes 
- A race condition in the sub_repo_permissions database store test suite has been fixed.

fix/database/sub_repo_perms: don't mark TestSubRepoPermsStore_GetByUserWithIPs as Parallel

---

cmd/enterprise-portal/internal/database/codyaccess/BUILD.bazel
cmd/enterprise-portal/internal/database/codyaccess/codygateway.go
cmd/enterprise-portal/internal/database/codyaccess/codygateway_test.go
cmd/enterprise-portal/internal/database/databasetest/databasetest.go
cmd/enterprise-portal/internal/database/internal/pgxerrors/BUILD.bazel
cmd/enterprise-portal/internal/database/internal/pgxerrors/pgxerrors.go
cmd/enterprise-portal/internal/database/internal/tables/tables.go
cmd/enterprise-portal/internal/database/internal/upsert/upsert.go
cmd/enterprise-portal/internal/database/migrate.go
cmd/enterprise-portal/internal/database/subscriptions/subscriptions.go

Implements Cody Gateway access in Enterprise Portal DB, such that it replicates the behaviour it has today, retrieving:
- Quota overrides
- Subscription display name
- Active license info
- Non-revoked, non-expired license keys as hashes
- Revocation + non-expiry replaces the existing mechanism of flagging licenses as `access_token_enabled`. Since we ended up doing zero-config for Cody Gateway, the only license hashes that are valid for Cody Gateway are non-expired licenses - once your license expires you should be switching to a new license key anyway.
It's fairly similar to the `dotcomdb` shim we built before, but for our new tables. See https://github.com/sourcegraph/sourcegraph/pull/63792 for the licenses tables.
None of this is going live yet.
Part of …

feat/enterpriseportal: db layer for cody gateway access

---

client/web/src/namespaces/useAffiliatedNamespaces.test.tsx
client/web/src/namespaces/useAffiliatedNamespaces.ts
cmd/frontend/graphqlbackend/prompts.graphql
cmd/frontend/graphqlbackend/saved_searches.graphql
cmd/frontend/internal/prompts/resolvers/resolvers.go
cmd/frontend/internal/prompts/resolvers/resolvers_test.go
cmd/frontend/internal/savedsearches/resolvers/BUILD.bazel
cmd/frontend/internal/savedsearches/resolvers/resolvers.go
cmd/frontend/internal/savedsearches/resolvers/resolvers_test.go
internal/database/prompts.go
internal/database/prompts_test.go
internal/database/saved_searches.go
internal/database/saved_searches_test.go

Anonymous visitors to Sourcegraph.com were unable to list all public saved searches (at https://sourcegraph.com/saved-searches) and prompts (at https://sourcegraph.com/prompts) for 2 reasons:
1. The namespace selector (filter) was broken for anonymous users and returned an error. Fixed this by just handling this case.
2. The GraphQL resolvers for `savedSearches` and `prompts` prevented anonymous users from listing items because there was no affiliated user and thus the anonymous user was essentially trying to list all. Fixed this by adding a new and well-tested code path for listing only public saved searches or prompts.
In dotcom mode, visit those 2 pages (`/saved-searches` and `/prompts`).

fix saved searches and prompts list page for anon users

---

cmd/frontend/graphqlbackend/org.go
cmd/frontend/graphqlbackend/org_invitation.go
cmd/frontend/graphqlbackend/org_test.go
internal/database/security_event_logs.go

Previously, the GraphQL API on dotcom only let org members query for an org (through `organization(name: ...)` or otherwise). This made sense as a strict security safeguard in a world where an org had only private resources, not public resources.
However, with search contexts, saved searches, and now the new prompt library, we want orgs on dotcom to be able to create things that (if we or they intentionally make them public) all users can see, and can see the association with the org owner. That requires all users to be able to query for the org and see its name.
We continue to enforce the secrecy of much org data: members (only org members can list the other members of the org), settings (only org members can view this).
**But the name, displayName, and existence of an org will now be …

support getting other orgs on dotcom from the GraphQL API

---

client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte
client/web-sveltekit/src/lib/wildcard/Toggle.svelte
client/web-sveltekit/src/routes/+layout.svelte
client/web-sveltekit/src/routes/layout.spec.ts
client/web/src/sveltekit/SvelteKitNavItem.module.scss
client/web/src/sveltekit/SvelteKitNavItem.tsx

This is the last bit of work before flipping the switch on dotcom. Implemented based on the behavior @taiyab and I aligned on this morning. Can definitely still use a little sparkle, but I'll let others follow up on that.
It adds a toggle button to all pages that we have a svelte version of. The toggle is off when you're in the react webapp and on when you're in the svelte webapp. It also updates the copy of the popover to be more appropriate for the dotcom crowd.
On a React page:
On a Svelte page:
Tested locally that I can enable/disable the toggle to switch between pages, that it is persistent, and that it looks relatively consistent between the versions.

Svelte rollout: add toggles for svelte-enabled pages

---

client/web-sveltekit/src/lib/search/dynamicFilters/Sidebar.svelte

Currently, svelte build of Sourcegraph is broken on s2 and dotcom for users who use Safari 17.3 and lower 
The problem is that we use the `Object.groupBy` method, which isn't supported in "old" Safari versions like 17.3 and lower.  See caniuse documentation about this here https://caniuse.com/?search=groupBy (in the old Safari version this method is actually named `groupToMap`
- Check basic functionality Search flow in Safari (especially in Safari 17.3)

Svelte: Fix Safari 17.3 groupBy usage

---

cmd/frontend/graphqlbackend/feature_flags.go
cmd/frontend/graphqlbackend/org.go
cmd/frontend/graphqlbackend/org_test.go
cmd/frontend/graphqlbackend/settings_mutation_test.go
cmd/frontend/graphqlbackend/settings_subject.go
cmd/frontend/graphqlbackend/settings_subject_test.go
cmd/frontend/graphqlbackend/user.go
cmd/frontend/graphqlbackend/user_test.go
internal/auth/orgs.go
internal/auth/site_admin.go

Followup from https://github.com/sourcegraph/sourcegraph/pull/63941.
I forgot to make it so site admins could list org members in that PR.
As for the new ability for site admins to see user and org settings: Site admins could already add themselves to orgs as members and see settings that way. I considered still keeping it stricter, but it is valuable for site admins to be able to view settings to help users troubleshoot.
In dotcom mode, as a site admin, view a user or org (that the site admin is not a member of). Confirm that the settings can be viewed.

allow site admins to list org members & view user/org settings on dotcom

---

client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
client/web/src/enterprise/batches/list/BatchChangeListPage.story.tsx
client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
client/web/src/namespaces/NamespaceArea.tsx
client/web/src/namespaces/routes.tsx
client/web/src/org/OrgsArea.tsx
client/web/src/org/area/OrgArea.tsx
client/web/src/org/area/OrgHeader.tsx
client/web/src/org/area/routes.tsx
client/web/src/org/settings/OrgSettingsSidebar.tsx
client/web/src/org/settings/routes.tsx

- Make it a React function component (not class componnt)
- Remove prop drilling for isSourcegraphDotCom to remove a bunch of code
- fix issue in Back button after clicking to an org from the site admin orgs page. Repro: 1. Go to /site-admin/organizations. 2. Click on an org. 3. Click the browser's back button. This was already being done for the user routes.
Repro described above

various OrgArea fixes

---

cmd/blobstore/internal/blobstore/blobstore_test.go
internal/codeintel/shared/lsifuploadstore/store.go
internal/object/config.go
internal/object/config_test.go
internal/object/gcs_client.go
internal/object/gcs_client_test.go

In this PR (https://github.com/sourcegraph/sourcegraph/pull/45042), it is noted that:
> Removed lifecycle configuration from uploadstore, instead relying just on our own
> builtin background worker to expire objects.
As a result, the `TTL` field on the GCS Client was not used anywhere. So this patch
removes the TTL field.

chore: Remove unused TTL in object.Storage config

---

internal/grpc/retry/retry_test.go

The reads for `s.streamFailureFunc` and `s.streamError` fields must be mutex protected
since another method may perform writes to those fields at the same time, and both
reads and writes must use the same mutex.
I ran `bazel test //internal/grpc/retry:retry_test --runs_per_test=100` and no longer see
a data race failure, but I see other errors, see [Slack thread](https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1721484109700539).

fix: Synchronize access to reads of fields in retry test

---

internal/grpc/retry/BUILD.bazel

See [Slack thread](https://sourcegraph.slack.com/archives/C05EMJM2SLR/p17214841097005390) for the many different failure modes this test is running into when running with
```
bazel test //internal/grpc/retry:retry_test --runs_per_test=100 --jobs=1
```
n/a

chore: Mark flaky test as manual

---

internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
internal/codeintel/codenav/internal/lsifstore/scan.go
lib/codeintel/lsif/conversion/group.go
lib/codeintel/lsif/conversion/group_test.go
lib/codeintel/precise/diff/diff.go
lib/codeintel/precise/query.go
lib/codeintel/precise/types.go
lib/codeintel/tools/lsif-index-tester/main.go
lib/codeintel/tools/lsif-repl/main.go

If you look at the code for `bulkMonikerResultsQuery` and `minimalBulkMonikerResultsQuery`,
you'll see that the last returned value is the `document_path`. The value returned
was directly used an `UploadRootRelPath` elsewhere. So it makes sense to rename
the field from URI to `DocumentPath`.

chore: Rename URI -> DocumentPath

---

internal/codeintel/codenav/internal/lsifstore/document_metadata.go
internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
internal/codeintel/codenav/internal/lsifstore/locations_by_position_test.go

There are many occurrences flying around, so add some prefix to identify
the fact that some values are used for lookups (whereas other values
are the results of the lookup -- these are not specially marked).

chore(codeintel): Rename local variables for clarity

---

internal/codeintel/codenav/BUILD.bazel
internal/codeintel/codenav/helpers_test.go
internal/codeintel/codenav/mapped_index_test.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_syntactic_usages_test.go
internal/codeintel/codenav/utils_test.go

Closes https://linear.app/sourcegraph/issue/GRAPH-735/test-syntactic-usages
Uses the new MappedIndex abstraction from #63781 to implement some proper unit tests for `syntacticUsagesImpl`.
PR adds a bunch of tests

Adds unit tests for syntactic usages

---

cmd/frontend/internal/httpapi/graphql.go

It's a bit unclear for users what the error message is for. This PR improves the error message by extending the GraphQL error message with additional context.
Linear issue: https://linear.app/sourcegraph/issue/SEC-1792/add-error-message-specifying-which-cost-setting-was-exceeded-in. 
CI tests

GraphQL: improve query cost violation message

---

dev/ci/push_all.sh
dev/ci/runtype/runtype.go

In order to run nightly vulnerability scans of Sourcegraph releases, we need to publish a new set of images whenever the release branch is pushed to.
Previously, this was implemented in https://github.com/sourcegraph/sourcegraph/pull/63379 but with RFC 795 the release branch format changed from 5.5.1234 to 5.5.x.
This PR updates the regex to catch this new format.
The end result of this is that whenever Buildkite runs on a branch matching `\d.\d.x`, it will push images to the `us.gcr.io/sourcegraph-dev/gitserver` registry with the tag `$branch-insiders`. 
I've also tagged this PR for backport as we want it on the current patch release branch 5.5.x :) 
- Test buildkite run on branch `will-0.0.x` (with modified regex to match that branch) …

Publish images for all commits on release branches

---

client/web/src/prompts/Area.tsx
client/web/src/savedSearches/Area.tsx
cmd/frontend/internal/app/ui/router.go

Also update page title.
Fixes https://linear.app/sourcegraph/issue/CODY-3026/when-the-new-fast-ui-is-enabled-the-new-button-on-saved-searches-and
CI

fix incorrect URL (/new) on saved search and prompt library pages

---

internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_new.go
internal/codeintel/codenav/types.go

We only need to two out of three for representing a document in an upload:
1. Upload root
2. RepoRootRelPath
3. UploadRootRelPath
For simplicity, drop the 3rd one, deriving it dynamically
from the other two as needed. Once https://github.com/sourcegraph/sourcegraph/pull/63965
lands, I'll mark `visibleUpload` as requiring exhaustive initialization.

chore(codeintel): Derive TargetPathWithoutRoot dynamically

---

client/web/src/enterprise/search-jobs/SearchJobsPage.tsx

The current description doesn't do a good job of explaining why Search Jobs is useful and how to create a job.
visual inspection

chore(search_jobs): improve description on main page

---

BUILD.bazel
dev/linters/exhaustruct/BUILD.bazel
dev/linters/exhaustruct/exhaustruct.go
dev/linters/exhaustruct/lint-config.yaml
dev/linters/go.mod
dev/linters/go.sum
linter_deps.bzl

For certain types, we do not want the zero-value initialization for structs.
This means we need to trade off readability vs exhaustive initialization checking,
as the Go syntax `Foo{Bar: bar}` is more readable, but doesn't do exhaustiveness
checking, and `Foo{bar}` does check for exhaustiveness but can be less readable
depending on context.
For now, the check is only introduced for one type, and is meant to be opt-in
so that code authors may choose for stricter checking.
This should trigger some build failures first, I'll fix those by addressing the lint.
EDIT: This is not triggering build failures because test files are ignored by default,
https://sourcegraph.slack.com/archives/C04MYFW01NV/p1721631774299489?thread_ts=1721611178.332129&cid=C04MYFW01NV

feat(build): Add exhaustruct linter (codeintel POC)

---

internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
internal/codeintel/codenav/internal/lsifstore/locations_by_position_test.go
internal/codeintel/codenav/internal/lsifstore/mocks/mocks_temp.go
internal/codeintel/codenav/internal/lsifstore/store.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_new.go
internal/codeintel/codenav/shared/types.go

Pass down semantic information down as much as possible,
delaying lossy conversion to table names till the very end.
I will be introducing the `exhaustive` linter in a future PR
(https://golangci-lint.run/usage/linters/#exhaustive)
so that we can get a static error if you don't switch exhaustively.

chore(codeintel): Pass UsageKind instead of raw column names

---

docker-images/syntax-highlighter/BUILD.bazel
docker-images/syntax-highlighter/crates/scip-syntax/BUILD.bazel

We don't appear to make use of the stamp values for any rust_binary targets, so lets not stamp it to save on cache invalidations
```
$ bazel build --stamp --workspace_status_command=./dev/bazel_stamp_vars.sh $(bazel query 'kind("rust_binary", //...)')
...
$ sha256sum bazel-bin/docker-images/syntax-highlighter/scip-ctags bazel-bin/docker-images/syntax-highlighter/crates/scip-syntax/scip-syntax bazel-bin/docker-images/syntax-highlighter/syntect_server
...
$ bazel build $(bazel query 'kind("rust_binary", //...)')
...
$ sha256sum bazel-bin/docker-images/syntax-highlighter/scip-ctags bazel-bin/docker-images/syntax-highlighter/crates/scip-syntax/scip-syntax bazel-bin/docker-images/syntax-highlighter/syntect_server
...
```
observe identical checksums

chore(bazel): disable stamping on rust_binary targets

---

internal/codeintel/codenav/internal/lsifstore/locations_by_position.go

Follow-up issue to fix this: https://linear.app/sourcegraph/issue/GRAPH-768/avoid-redundant-doc-reads-and-traversals
n/a

chore: Document tech debt wrt multiple doc traversals

---

cmd/frontend/internal/app/ui/router.go

Fixes [inc-313 ](https://sourcegraph.slack.com/archives/C07D8ETFAQP/p1721746352871739?thread_ts=1721745191.614829&cid=C07D8ETFAQP)
It should solve problems with the old auth flow in the new Svelte version. Currently, the go router doesn't know anything about post-sign-up flow, which is used in the JB Cody extension. Because of this, it passes it to the Svelte version which doesn't implement this route on the client (but the react version did have it on the client which is why it worked before, before we rolled out Svelte version by default)
- There is no good way to check this properly, but after this PR you have to see a react (old) version of the App when you go to the /post-sigh-up router

Bring back post-sign-up route to the backend router

---

cmd/frontend/internal/dotcom/BUILD.bazel
cmd/frontend/internal/dotcom/init.go
cmd/frontend/internal/dotcom/productsubscription/license_anomaly.go
cmd/frontend/internal/dotcom/productsubscription/license_check_handler.go
cmd/frontend/internal/dotcom/productsubscription/license_check_handler_test.go
cmd/frontend/internal/dotcom/productsubscription/license_expiration.go
cmd/frontend/internal/licensing/init/BUILD.bazel
cmd/frontend/internal/licensing/init/init.go

Adds the following toggles for various dotcom-mode online licensing capabilities:
- `DOTCOM_ENABLE_ONLINE_LICENSE_CHECKS=false` makes it so that the license check "pings" always return "you're good to go"
- `DOTCOM_ENABLE_ANOMALOUS_LICENSE_CHECKER=false` disables the Redis + event_logs thing looking for suspicious pings
- `DOTCOM_ENABLE_UPCOMING_LICENSE_EXPIRATION_CHECKER=false` disables Slack notifications for upcoming license expirations
All defaults still respect the existing behaviour. https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/18712 explicitly sets the toggles for online license checks, per the discussion in https://sourcegraph.slack.com/archives/C012NU3PXA9/p1721669308549559
All of the above capabilities are planned to be migrated to Enterprise Portal:
- …

feat/frontend/dotcom: add toggles for various online license checks

---

cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
cmd/enterprise-portal/internal/dotcomdb/dotcomdb_test.go

We need to ensure prod data does not end up in the dev Enterprise Portal instance once we start syncing. This change adds support for the DevOnly option in ListSubscriptions and strictly enforces it there (i.e. dev subscriptions cannot end up in the prod instance either).
I've tried to minimize the changes elsewhere to reduce the impact of this change for now.
Tests

feat/enterpriseportal: support DevOnly in list subscriptions

---

internal/usagestats/saved_searches.go

This makes it easier to chart this metric on a daily basis. Transmitting the count in a rolling 24-hour window is harder.
Note that this new usagestats schema for saved searches has not yet been released in a patch or stable release.
CI

track usage stats for saved searches in UTC day increments

---

internal/codeintel/codenav/BUILD.bazel
internal/codeintel/codenav/gittree_translator.go
internal/codeintel/codenav/gittree_translator_test.go
internal/codeintel/codenav/shared/types.go

Closes https://linear.app/sourcegraph/issue/GRAPH-742/simplify-gittreetranslator-implementation
- use unified diff format and 0 context lines to allow translation by just using hunk headers
- only request hunks per file once, and sync follow-up requests for the same file
- don't bother LRU caching the full hunk contents, just store 4 int32's per hunk
- replace linear search through sorted hunks with binary search
Current PR keeps the old PR and just proxies to the new implementation. Once this PR is reviewed and merged I'll remove the old API and update all callsites.
Idea is to make review easier.
I'd recommend just reviewing the new implementation, as the diff view on this is pretty useless.
New/existing tests

codeintel: GitTreeTranslator rewrite

---

internal/codeintel/codenav/BUILD.bazel
internal/codeintel/codenav/syntactic.go

Closes https://linear.app/sourcegraph/issue/GRAPH-767/search-based-run-occurrence-search-and-symbol-search-in-parallel
Covered by existing tests and checking the trace to see executes overlapping:

codeintel: runs occurrence and symbol search in parallel

---

internal/codeintel/codenav/gittree_translator.go
internal/codeintel/codenav/gittree_translator_test.go
internal/codeintel/codenav/service_ranges_test.go

Closes https://linear.app/sourcegraph/issue/GRAPH-769/fetch-diffs-in-batches
Covered by existing tests (noticeable because tests need updates as we now use the path out of the returned diff)

codeintel: fetches diffs from gitserver in batches

---

client/web/src/enterprise/search-jobs/SearchJobsPage.tsx

We have to use `debouncedSearchTerm` to give the paginated fetcher some time to fetch the new results.
visual inspection
https://github.com/user-attachments/assets/868ef23b-9ff0-4e18-86c2-daea42d476b7

fix(search_jobs): flickering placeholder component

---

dev/linters/exhaustruct/lint-config.yaml
internal/codeintel/codegraph/BUILD.bazel
internal/codeintel/codegraph/locus.go
internal/codeintel/codenav/internal/lsifstore/BUILD.bazel
internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
internal/codeintel/codenav/internal/lsifstore/scan.go

This patch changes the location querying code so that:
1. We're populating structures corresponding to SCIP instead of LSIF
(with "scheme" and "identifier" inside "MonikerData")
2. Avoid repeatedly allocating a constant string 'scip' for the scheme
only to throw it away later.
3. Makes the two queries and their scanning code more similar for easier
comparison. When I land precise usagesForSymbol, I will de-duplicate
some of the scanning code between these two queries.
I have avoided renaming all of the local variables to avoid creating more noise.
- This PR is stacked on top of https://github.com/sourcegraph/sourcegraph/pull/64001

chore: Make location fetching queries more uniform

---

internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
internal/codeintel/codenav/internal/lsifstore/locations_by_position_test.go
internal/codeintel/codenav/internal/lsifstore/mocks/mocks_temp.go
internal/codeintel/codenav/internal/lsifstore/observability.go
internal/codeintel/codenav/internal/lsifstore/store.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_hover_test.go
internal/codeintel/codenav/service_new.go
internal/codeintel/codenav/service_new_test.go

Monikers carry a bunch of redundant fields which basically consist of
information parsed out of the symbol name. This patch cleans up
some APIs to work with symbol names directly instead of monikers.
- This patch is stacked on top of https://github.com/sourcegraph/sourcegraph/pull/64026

chore: Change some APIs to use symbols instead of monikers

---

internal/extsvc/bitbucketcloud/client.go

A Bitbucket Cloud incident caused APIs to error which caused Bitbucket Cloud OAuth tokens to fail to refresh. This revealed that the Bitbucket Cloud client called `oauthutil.DoRequest` with a `nil` logger, causing a nil pointer dereference.
This PR simply creates the logger before calling `DoRequest`, which is what the other clients do.
No more cases of DoRequest with a nil logger.
- Fixed an issue where a Bitbucket Cloud OAuth token failing to refresh would crash the `worker` service.

fix(source): Fix issue where worker would crash if a Bitbucket Cloud token couldn''t be refreshed

---

cmd/worker/internal/codygateway/BUILD.bazel
cmd/worker/internal/codygateway/usageworker.go

Adds better observability, and follows more standard patterns. I don't know why I did it that way a year ago when I implemented this :facepalm:
Test plan: Code review to find behavior changes that CI cannot cover; also CI.

Make cody gateway usage worker a periodic routine

---

dev/ci/internal/ci/images_operations.go
dev/ci/push_all.sh

This PR is a second attempt at improving push_all.sh, continuing on from (and inspired by) https://github.com/sourcegraph/sourcegraph/pull/63391. As a recap, that PR uses [--script_path](https://bazel.build/reference/command-line-reference#flag--script_path) to emit a short bash script for every `oci_push` target, which essentially does minor setup + invokes the executable as if running `bazel run`.
While the idea in https://github.com/sourcegraph/sourcegraph/pull/63391 was good, it trades concurrent server locking with an equal amount of overhead in sequentially building the scripts. By observing the scripts<b>[1]</b> that it would emit, we can notice a few things:
- The path `/home/noah/.cache/bazel/_bazel_noah/8fd1d20666a46767e7f29541678514a0/execroot/__main__/bazel-out/k8-fastbuild/bin …

chore(bazel): rework push_all to improve concurrency by avoiding bazel server lock

---

wolfi-packages/s3proxy.yaml

We previously pinned the version of openjdk-11 in order to avoid a bad package signature. This is no longer required.
- CI
- Manually verify updated package

Unpin openjdk-11 version in blobstore package

---

wolfi-images/blobstore.lock.json

Update the version of openjdk-11 we use in the blobstore image.
We updated the blobstore image earlier today to try and fix this issue, but were thwarted by an old version pin. This has now been [removed](https://github.com/sourcegraph/sourcegraph/pull/64045), so updating packages fully resolves the issue.
This PR branch is not based off `main` as backporting package changes often results in merge conflicts. It was generated by checking our `5.5.x` and running `sg wolfi lock blobstore`.
- CI
- Run image locally

security: Bump openjdk-11 version in blobstore image

---

cmd/enterprise-portal/internal/codyaccessservice/v1.go

Since this queries BigQuery under the hood, it can be a bit slow, and if the client cancels there's no need for a Sentry report.
n/a

feat/enterpriseportal: ignore context cancellation error in GetCodyGatewayUsage

---

dev/ci/runtype/runtype.go

With the https://github.com/sourcegraph/sourcegraph/pull/63985/files PatchRelease is matched before InternalRelease leading to the wrong build being generated.
We therefore move the Promote and Internal Release runtypes higher in priority so that they get matched first.
```
export RELEASE_INTERNAL=true
export VERSION="5.5.2463"
go run ./dev/sg ci preview
```
👇🏼 
```
go run ./dev/sg ci preview
⚠️ Running sg with a dev build, following flags have different default value unless explictly set: skip-auto-update, disable-analytics
If the current branch were to be pushed, the following pipeline would be run:
Parsed diff:
changed files: [WORKSPACE client/web-sveltekit/BUILD.bazel client/web-sveltekit/playwright.config.ts client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte client/web- …
```

ci: make internal+promote release higher priority in runtypes

---

internal/appliance/appliance.go
internal/appliance/config/annotations.go
internal/appliance/json.go
internal/appliance/status.go

So that other appliance subpackages (notably reconciler) can import it without risking a circular dependency.
Relates to https://linear.app/sourcegraph/issue/REL-78/when-sourcegraph-frontend-is-down-a-user-trying-to-access-sourcegraph but does not close it. Bottom of a stack, likely more PRs incoming today.
This is a refactor, all tests continue to pass.

chore(appliance): expose status in config package

---

internal/updatecheck/handler.go

update version consts in updatecheck handler, temp solutions
see: https://linear.app/sourcegraph/issue/REL-145/release-tie-release-consts-to-release-registry
No test

bug/release: update version consts in updatecheck handler

---

client/web/src/repo/blob/codemirror/codeintel/occurrences.ts

Using the spread operator with large arrays can trigger a
stack overflow in Chrome/V8. For example, see:
- https://github.com/nodejs/node/issues/16870
In a highlighting context, we can have 10k-100k occurrences
in a file, so let's avoid using the spread operator.
Fixes https://linear.app/sourcegraph/issue/GRAPH-772
Manually tested against sample file.
- Fixes a Chrome-specific stack overflow when highlighting large files.

fix: Fix Chrome stack overflow during highlighting

---

internal/codeintel/codenav/internal/lsifstore/BUILD.bazel
internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
internal/codeintel/codenav/internal/lsifstore/mocks/mocks_temp.go
internal/codeintel/codenav/internal/lsifstore/observability.go
internal/codeintel/codenav/internal/lsifstore/store.go

Closes https://linear.app/sourcegraph/issue/GRAPH-766/batch-api-for-fetching-scip-documents
Tested by being used for the single-path retrieval path, will be tested more once its used in follow-up PRs with more batching

codeintel: allows batch retrieval of SCIP documents

---

internal/codeintel/codenav/BUILD.bazel
internal/codeintel/codenav/helpers_test.go
internal/codeintel/codenav/mapped_index.go
internal/codeintel/codenav/mapped_index_test.go

Closes https://linear.app/sourcegraph/issue/GRAPH-770/batch-api-for-mappedindex
Depends on #64024 
Added unit test

codeintel: Adds a batch api for fetching multiple documents to MappedIndex

---

deps.bzl
dev/bkstats/main.go
dev/build-tracker/build/build.go
dev/build-tracker/main.go
dev/buildchecker/main.go
dev/sg/internal/bk/bk.go
go.mod
go.sum

Closes [DINF-51](https://linear.app/sourcegraph/issue/DINF-51/failed-back-compat-doesnt-count-towards-branch-locking-quota)
If a back-compat step on main fails, the build is marked as having failed. However, we don't treat that as a failure in build-tracker, resulting in no #buildkite-main post and not counting towards failed build quota for locking main.
The reason why this was happening is that the Backcompat build wasn't linked to the main Sourcegraph build in anyway. However, when a backcompat fails the main build reflects the status of this failure, but we do not use this field when determining the status of a build, so it doesn't work for our use case.
We [instead do a walkthrough of all the jobs associated with a build to figure …

fix(build-tracker): Failed back-compat doesn't count towards branch-locking quota

---

dev/linters/exhaustruct/lint-config.yaml
internal/codeintel/codenav/internal/lsifstore/BUILD.bazel
internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
internal/codeintel/codenav/internal/lsifstore/locations_by_position_test.go
internal/codeintel/codenav/internal/lsifstore/mocks/mocks_temp.go
internal/codeintel/codenav/internal/lsifstore/observability.go
internal/codeintel/codenav/internal/lsifstore/scan.go
internal/codeintel/codenav/internal/lsifstore/store.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_hover_test.go
internal/codeintel/codenav/service_new.go
internal/codeintel/codenav/service_new_test.go
internal/codeintel/codenav/shared/types.go
internal/codeintel/codenav/types.go

For precise usagesForSymbols, we want to propagate usages everywhere
(with associated symbol names, not just 'Location' values). This PR introduces
the new Usage type, and unifies the old GetBulkSymbolUsages and
GetMinimalBulkSymbolUsages APIs into a single GetSymbolUsages API.
We convert the Usage values to Location to avoid changing a lot of code at once.
We also change the DB query to do grouping and aggregation for us
instead of doing it in Go code.

chore: Unify LsifStore.*SymbolUsages APIs into one

---

dev/ci/internal/ci/images_operations.go
dev/ci/push_all.sh

Second attempt at https://github.com/sourcegraph/sourcegraph/pull/64044, now that rate limit is set right. So lets boost the concurrency to all cores!
main dry-run https://buildkite.com/sourcegraph/sourcegraph/builds/284268#0190e9cf-b902-4f7c-a1ad-fca8700b8fa0

chore(bazel): rework push_all to improve concurrency by avoiding bazel server lock (round 2)

---

docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs

Sorry missed this during the review. No need to allow `rEfErEnCe` as the capture name. Noticed this while checking the samply profile and seeing string allocations (gets us back 20ms on spring-framework 🎉)

scip-syntax: uses `.starts_with` to check reference capture

---

cmd/appliance/shared/BUILD.bazel
cmd/appliance/shared/shared.go
internal/appliance/config/annotations.go
internal/appliance/healthchecker/BUILD.bazel
internal/appliance/healthchecker/health_checker.go
internal/appliance/healthchecker/health_checker_test.go
internal/appliance/healthchecker/probe.go
internal/appliance/reconciler/frontend.go
internal/appliance/reconciler/reconcile.go
internal/appliance/reconciler/testdata/golden-fixtures/frontend/adopt-service.yaml
internal/appliance/reconciler/testdata/golden-fixtures/frontend/after-create-codeinsights-db-auth-secret.yaml
internal/appliance/reconciler/testdata/golden-fixtures/frontend/after-create-codeintel-db-auth-secret.yaml
internal/appliance/reconciler/testdata/golden-fixtures/frontend/after-create-pgsql-auth-secret.yaml
internal/appliance/reconciler/testdata/golden-fixtures/frontend/after-create-redis-cache-secret.yaml
internal/appliance/reconciler/testdata/golden-fixtures/frontend/after-create-redis-store-secret.yaml
internal/appliance/reconciler/testdata/golden-fixtures/frontend/default.yaml
internal/appliance/reconciler/testdata/golden-fixtures/frontend/with-blobstore.yaml
internal/appliance/reconciler/testdata/golden-fixtures/frontend/with-ingress-optional-fields.yaml
internal/appliance/reconciler/testdata/golden-fixtures/frontend/with-ingress.yaml
internal/appliance/reconciler/testdata/golden-fixtures/frontend/with-overrides.yaml
internal/appliance/reconciler/testdata/golden-fixtures/standard/frontend-with-no-cpu-memory-resources.yaml

Relates to https://linear.app/sourcegraph/issue/REL-78/when-sourcegraph-frontend-is-down-a-user-trying-to-access-sourcegraph but does not close it.
Stacked on https://github.com/sourcegraph/sourcegraph/pull/64032 but can be reviewed independently. Commit log:
**Appliance points ingress-facing service to itself by default**
Not frontend.
**feat(appliance): healthchecker manages ingress-facing service**
Add a new background goroutine to the appliance. It does nothing until a
"begin" channel closes. The idea is that another part of the appliance
will close this channel if the configmap state is set to a post-install
value (or on startup if this is already the case when an appliance boots).
After this barrier is lifted, the healtchecker periodically checks the
readiness (using k8s conditions) …

feat(appliance): healthchecker manages ingress-facing service

---

docker-images/appliance-frontend/nginx.conf
internal/appliance/frontend/maintenance/maintenance.conf.template

Resolves request 4 of [REL-78](https://linear.app/sourcegraph/issue/REL-78/when-sourcegraph-frontend-is-down-a-user-trying-to-access-sourcegraph#comment-ae562c6d)
Hopes and Prayers 🙏
- feat(appliance): implement re-direct on all unknown endpoints

feat(appliance): implement re-direct on all unknown endpoints

---

sg.config.yaml

Changes in client-side code should not result in expensive rebuilds of `frontend` locally when using bazel with `sg start`. For some reason, iBazel still thinks it needs to be rebuilt (possibly it uses `query` instead of `cquery` and therefore doesnt resolve `selects`), but bazel underneath determines nothing needs to be rebuilt so theres very little cost
Command set with just `frontend`  in a `bazelCommands` section and then `sg start <command set>`

chore(local): use //cmd/frontend:frontend_nobundle for bazel commandsets

---

cmd/frontend/internal/telemetry/resolvers/resolvers.go
cmd/frontend/internal/telemetry/resolvers/telemetrygateway.go
cmd/frontend/internal/telemetry/resolvers/telemetrygateway_test.go

Adds a read-only "known baddies" list of feature/action combination where we know the event will produce marshalling or validation errors, and skips the error-logging step.
Note that the code fails the entire batch the way it works today, but in practice, none of our clients batch events yet, so this is something to fix when we start doing that.
```
sg start enterprise
```
```gql
mutation {
telemetry {
recordEvents(
events: [{feature: "cody.completion", action: "persistence:present", source: {client: "VSCode.Cody", clientVersion: "0.14.1"}, parameters: {version: 0, privateMetadata: 12}}]
) {
alwaysNil
}
}
}
```
get an error response, but does not record a log in `sg start` output

fix/telemetry: silence invalid events that we already know about

---

cmd/frontend/graphqlbackend/site_analytics.go
cmd/worker/internal/adminanalytics/BUILD.bazel
cmd/worker/internal/adminanalytics/job.go
cmd/worker/internal/adminanalytics/refresh_analytics_cache.go
cmd/worker/internal/adminanalytics/refresh_analytics_cache_test.go
internal/adminanalytics/BUILD.bazel
internal/adminanalytics/batchchanges.go
internal/adminanalytics/cache.go
internal/adminanalytics/cache_test.go
internal/adminanalytics/codeinsights.go
internal/adminanalytics/codeintel.go
internal/adminanalytics/codeintelbylanguage.go
internal/adminanalytics/codeinteltoprepositories.go
internal/adminanalytics/extensions.go
internal/adminanalytics/fetcher.go
internal/adminanalytics/notebooks.go
internal/adminanalytics/repos.go
internal/adminanalytics/search.go
internal/adminanalytics/users.go
internal/adminanalytics/users_test.go
internal/appliance/BUILD.bazel

Relates to #64041
This refactors the `adminanalytics` package to set the cache explicitly instead of implicitly relying on the global `redispool.Store`. The global store obfuscated the dependency and also made testing a bit awkward.
Test plan:
- I ran a local instance and checked for panics in the logs from the worker job that updates the cache on startup.
- Checked that the following GQL query returned results 
```GQL
query {
site {
analytics {
search(dateRange: LAST_MONTH, grouping: WEEKLY) {
searches {
nodes {
date
count
}
summary {
totalCount
totalUniqueUsers
totalRegisteredUsers
}
}
}
}
}
}
```
- I deleted the cache and ran the GQL query again and verified that cache had the following new entries
```
1) "adminanalytics:Search:Searches:LAST_MONTH:WEEKLY:nodes"
2) …
```

chore(frontend): use explicit cache for admin analytics

---

client/web-sveltekit/src/lib/codemirror/SearchPanelView.svelte

Switch from Lucide icons to MDI which look better in this case. 
Before:
After: 
Manual/Visual testing

Blob search: Fix incorrect icons in the blob search bar

---

deps.bzl
go.mod
go.sum

This only contains one commit which has a performance improvement experiment hidden behind an environment variable.
- https://github.com/sourcegraph/zoekt/commit/12ce07a298 index: experiment to limit ngram lookups for large snippets
Test Plan: CI

gomod: update zoekt for guardrails perf experiment

---

client/web-sveltekit/src/lib/navigation/UserMenu.svelte

Teams option in the user menu will be hidden when own is not enabled. 
Own Enabled: 
Own Not Enabled: 
Visual/Manual testing

Svelte Navigation: hide teams when own is not enabled

---

internal/codeintel/codenav/syntactic.go

Closes https://linear.app/sourcegraph/issue/GRAPH-771/chunk-syntactic-usage-tasks-and-use-batch-apis-to-handle-chunks
This is the last step for properly implementing #63971. We split the `candidateFiles` search produces into chunks and process these in parallel using the new batch api on `MappedIndex`.
Existing tests continue passing

codeintel: Speed up syntactic and search-based usages using batch APIs

---

internal/cmd/search-blitz/attribution.graphql

Cody doesn't set a limit, so we use the default that Cody Gateway sets. It uses a value of 4.
Test Plan: yolo

search-blitz: adjust limit for snippetAttribution to match gateway

---

cmd/appliance/shared/shared.go
internal/appliance/appliance.go
internal/appliance/config/annotations.go
internal/appliance/frontend/maintenance/src/OperatorStatus.tsx
internal/appliance/frontend/maintenance/src/WaitForAdmin.tsx
internal/appliance/healthchecker/health_checker.go
internal/appliance/healthchecker/health_checker_test.go
internal/appliance/healthchecker/probe.go
internal/appliance/json.go
internal/appliance/reconciler/reconcile.go
internal/appliance/status.go

Add basic health check to switch state to `waitForAdmin` after Sourcegraph frontend is ready. As noted in the code, this is a temporary health check and will/should be replaced with something more comprehensive in the near future.
Wait for admin page successfully appears when Sourcegraph frontend is "ready":
Tested locally

feat(appliance): add wait for admin state

---

internal/search/exhaustive/store/exhaustive_search_jobs.go
internal/search/exhaustive/store/exhaustive_search_jobs_test.go

Fixes SPLF-170
This fixes a bug in our status reporting where we would report a job as "queued" although it should be reported as "processing". In some cases this led to the state flip-flopping between "queued" and "processing".
This happens, for example, if a worker has just finished a repo-rev job (and set it to completed) but hasn't yet dequeued a new job. In this brief period we reported the entire search job as queued.
Test plan:
I ran the following search job which previously exhibited this behavior and verified that now it doesn't.
```
context:global r:^github\.com/sourcegraph/sourcegraph$@*refs/heads/* ghp_.+ patterntype:regexp
```

fix(search_jobs): prevent job state flip-flopping between 'queued' and 'processing'

---

deps.bzl
go.mod
go.sum

This includes a commit which hopes to improve the performance of a recent experiment to improve guardrails performance.
https://github.com/sourcegraph/zoekt/compare/12ce07a298ae...ebb3ca24249d
- https://github.com/sourcegraph/zoekt/commit/04e7057ffe Enabling numContextLines in non-json format
- https://github.com/sourcegraph/zoekt/commit/ebb3ca2424 index: use a random sample of ngrams when limiting
Test Plan: CI
Part of https://linear.app/sourcegraph/issue/CODY-3029/investigate-performance-of-guardrails-attribution-endpoint

gomod: update zoekt to include improvement to experiment

---

docker-images/syntax-highlighter/crates/syntax-analysis/README.md
docker-images/syntax-highlighter/crates/syntax-analysis/docs/locals-query-dsl.md
docker-images/syntax-highlighter/crates/syntax-analysis/queries/go/scip-locals.scm
docker-images/syntax-highlighter/crates/syntax-analysis/queries/java/scip-locals.scm
docker-images/syntax-highlighter/crates/syntax-analysis/queries/matlab/scip-locals.scm
docker-images/syntax-highlighter/crates/syntax-analysis/queries/perl/scip-locals.scm
docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs

Closes https://linear.app/sourcegraph/issue/GRAPH-774/see-if-we-can-get-away-with-2-visibilities-in-scip-syntax
Snapshots don't change
A couple hyperfine runs suggest this is also slightly quicker
```
spring-framework on  HEAD (9409543) [?]
❯ hyperfine --warmup 3 'git archive HEAD | scip-syntax index tar - -l java' 'git archive HEAD | scip-syntax-main index tar - -l java'
Benchmark 1: git archive HEAD | scip-syntax index tar - -l java
Time (mean ± σ):     909.9 ms ±   9.7 ms    [User: 7307.6 ms, System: 212.2 ms]
Range (min … max):   902.4 ms … 935.2 ms    10 runs
Benchmark 2: git archive HEAD | scip-syntax-main index tar - -l java
Time (mean ± σ):     939.6 ms ±   6.5 ms    [User: 7681.2 ms, System: 210.9 ms]
Range (min … max):   931.2 ms … 952.1 ms    10 runs
Summary
git archive HEAD | …
```

scip-syntax: Simplifies to two visibilities

---

client/web/src/enterprise/batches/settings/CodeHostConnections.tsx
client/web/src/enterprise/batches/settings/CommitSigningIntegrations.tsx
client/web/src/enterprise/batches/settings/github-apps-filter.test.ts
client/web/src/enterprise/batches/settings/github-apps-filter.ts

This is a follow up to https://github.com/sourcegraph/sourcegraph/pull/64120 so that it doesn't mix up alerts between commit signing and code hosts for site admins.
Manual testing + CI

fix: add commit signing filter to `credentialForGitHubAppExists`

---

internal/appliance/frontend/maintenance/src/Install.tsx

Resolves [REL-290](https://linear.app/sourcegraph/issue/REL-290/frontend-ui-pulls-sourcegraph-versions-to-install-from-release) by making a single request to the release registry to get a list of versions
manual tested
- feat(appliance): frontend pulls versions from relreg

feat/Appliance: Frontend Pulls Version Info from RelReg

---

client/web-sveltekit/src/auto-imports.d.ts
client/web-sveltekit/src/lib/navigation/MainNavigationLink.svelte
client/web-sveltekit/src/params/reporev.ts
client/web-sveltekit/src/routes/layout.spec.ts
client/web-sveltekit/src/routes/navigation.ts

This PR adds the `Tools` Menu Item back to the Global Navigation Bar of the svelte-kit web app, and removes the sub menus for both `Code Search` and `Cody` menu items.
Before:
After: 
Visual/manual testing
Passing CI

SvelteKit: Add 'Tools' Menu item back to global navigation

---

client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte

When clicking a menu item with no href, page refreshed every time. Now, menu items with no href cause no action when clicked. 
https://github.com/user-attachments/assets/abcc5164-64fa-4b37-8f8c-7df110bca23e
This is a follow up to this PR: https://github.com/sourcegraph/sourcegraph/pull/64134
Manual/Visual testing

SvelteKit: fix issue where clicking link with no href refreshed the page

---

internal/appliance/frontend/maintenance/src/Install.tsx

@DaedalusG was running into warnings in the console due to the releaseregistry containing 2 entries for v5.4.0 (one was a development build)
We're now filtering those
Manual testing
- fix(appliance): don't allow installation of development builds

fix(appliance): don't include is_development builds in list of versions

---

dev/linters/exhaustruct/lint-config.yaml
internal/codeintel/codenav/transport/graphql/root_resolver.go
internal/codeintel/codenav/transport/graphql/root_resolver_implementations.go
internal/codeintel/codenav/transport/graphql/root_resolver_references.go
internal/codeintel/codenav/transport/graphql/root_resolver_test.go
internal/codeintel/codenav/transport/graphql/root_resolver_usages.go
internal/codeintel/codenav/types.go
internal/codeintel/resolvers/BUILD.bazel
internal/codeintel/resolvers/codenav.go
internal/codeintel/resolvers/codenav_test.go

For https://github.com/sourcegraph/sourcegraph/pull/64126, I need to be able to
access some of these types in the codenav package directly, so move these
to avoid an import cycle: codenav -> resolvers -> codenav.

chore: Move codenav types to lower-level package

---

cmd/frontend/graphqlbackend/codeintel.codenav.graphql

I'm not actually sure if I can even guarantee the _at least_ part for syntactic usages right now. It would require particularily pathological circumstances, but because I have to stay within the given `context.Context` window, I might end up returning fewer syntactic results than requested.
I think that should be fixable in the future so I'd still like the spec to reflect the state we'd like to end up at.
Just a documentation/specification change

codeintel: document that pagination for usages might return extra results

---

cmd/appliance/shared/config.go
cmd/appliance/shared/shared.go
internal/appliance/appliance.go
internal/appliance/json.go

In the first UI, dev mode was a webform field. On reflection, it's probably simpler as an env var, since it is not expected that production users will enable this.
Appliance can be started by default, and also with APPLIANCE_NO_RESOURCE_RESTRICTIONS=true

fix(appliance): do not deploy in dev mode by default

---

cmd/appliance/shared/shared.go
internal/appliance/selfupdate/integrationtest/integration_test.go
internal/appliance/selfupdate/selfupdate.go

The helm chart will configure both the backend and frontend deployments to self-update: https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/513
Relates to https://linear.app/sourcegraph/issue/REL-302/self-update-should-update-appliance-frontend-too
Integration test against a real kubernetes API server included. I also kicked the tires in conjunction with the companion Helm PR.

feat(appliance): self-update can update multiple deployments

---

dev/ci/internal/ci/pipeline.go

Follow-up to [this comment](https://github.com/sourcegraph/sourcegraph/pull/63910#discussion_r1683190713) where the need was raised for having profiles for further inspection of problematic targets when run in isolation. 
Basically, every bazel-do will now collect the profile, and it'll be uploaded as a job artifact. 
See https://buildkite.com/sourcegraph/sourcegraph/builds/284913 for a test run.

chore(ci): pass --profile to bazel-do jobs

---

internal/requestclient/BUILD.bazel
internal/requestclient/http.go
internal/requestclient/http_test.go

Closes https://linear.app/sourcegraph/issue/SRC-454/extract-and-propagate-user-ip-address-throughout-the-request-lifecycle
According to [HTTP1.1/RFC 2616](https://www.rfc-editor.org/rfc/rfc2616): Headers may be repeated, and any comma-separated list-headers (like `X-Forwarded-For`) should be treated as a single value.
In section 4.2:
>   Multiple message-header fields with the same field-name MAY bepresent in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. **It MUST be possible to combine the multiple header fields into one"field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma.** The order in which header …

fix/internal/requestclient: read all instances of x-forwarded-for header, not just the first

---

cmd/customer-2315/main.go
cmd/customer-4512/main.go
internal/completions/client/azureopenai/openai.go

This PR adds special support for http requests to azure OpenAI and changes special customer configs to use HTTP instead of HTTPS.
Tested this PR locally

Adding HTTP Requests support for Azure OpenAI

---

.aspect/bazelrc/ci.sourcegraph.bazelrc

Our remote cache is more stable now, so we may be able to avail of BwoB better again 
CI

chore(bazel): re-enable remote caching of Copy{File,Directory,ToDirectory} actions

---

client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte

Before: 
After: 
Manual/Visual testing

Nit: adds space between tools menu item and dropdown icon

---

.github/workflows/cloud-gql-compat.yml

closes CLO-527
[context](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1721835847010889)
cloud uses a lot of the GraphQL API to pre-configure instances on customer behave, and it's very sensitive to breaking changes to the schema upstream.
currently, we have a [cronjob github actions](https://github.com/sourcegraph/controller/actions/workflows/srcgql-compat.yaml) that periodically check the schema compatibility every day.
such approach works but we're always playing catch up and will have to result in extra work on the product team to re-work the PR. it is much better to catch this in CI time within the monorepo.
This PR added a new github actions to the monorepo that will run on any `*.graphql` changes. Then it will remotely trigger the cronjob github action in sourcegraph/controller …

ci: add cloud controller gql compat test

---

cmd/frontend/internal/modelconfig/siteconfig_completions_test.go

There was some confusion about how a starcoder model would "come out" of the modelconfig system. Added a unit test and some clarifying comments to hopefully help out.
Just add tests for the sake of clarifying the code.
NA

Add unit test for modelconfig converting starcoder completion model

---

cmd/frontend/image_test.yaml
cmd/server/image_test.yaml
dev/oci_defs.bzl
internal/version/BUILD.bazel
internal/version/version.go

https://linear.app/sourcegraph/issue/DINF-111/rework-how-we-inject-version-in-our-artifacts
Pros:
- saves having to rebuild `bazel query 'kind("go_library", rdeps(//..., //internal/version))' | wc -l` == 523 Go packages when stamp variables cause a rebuild
- Cutting out GoLink action time when stamp changes but code is cached
Cons:
- Binaries themselves are no longer stamped, only knowing their version info within the context of the docker image
- A tad extra complexity in internal/version/version.go to handle this new divergence 
---
Before:
```
$ bazel aquery --output=summary --include_commandline=false --include_artifacts=false --include_aspects=false --stamp 'inputs(".*volatile-status\.txt", //...)'
Action: 1
Genrule: 2
Rustc: 3
ConvertStatusToJson: 88
GoLink: 383
```
After:
```
$ …
```

feat(bazel): read binary version info from accompanying files in OCI images instead of stamping //internal/version

---

internal/database/sub_repo_perms_store.go
internal/diskcache/cache.go

These functions return StoreOpts, but that wasn't immediately clear, so adding this small tweak here.
Test plan: Ci passes.

chore: Make return type more obvious

---

cmd/frontend/internal/auth/BUILD.bazel
cmd/frontend/internal/auth/init.go
cmd/frontend/internal/cli/BUILD.bazel
cmd/frontend/internal/cli/serve_cmd.go

Just a little cleanup which makes the main function a bit shorter and easier to understand that userpasswd is not different to other authn providers.
Test plan: Authn with builtin still works in CI integration tests.

chore: Init userpasswd provider where we initialize every other authn provider

---

cmd/frontend/internal/app/app.go
cmd/frontend/internal/auth/bitbucketcloudoauth/middleware_test.go
cmd/frontend/internal/auth/githuboauth/middleware_test.go
cmd/frontend/internal/auth/gitlaboauth/middleware_test.go
cmd/frontend/internal/auth/openidconnect/middleware_test.go
cmd/frontend/internal/auth/saml/middleware_test.go
cmd/frontend/internal/auth/session/BUILD.bazel
cmd/frontend/internal/auth/session/session.go
cmd/frontend/internal/auth/session/session_test.go
cmd/frontend/internal/auth/session/test_util.go
cmd/frontend/internal/auth/sourcegraphoperator/middleware_test.go
cmd/frontend/internal/auth/userpasswd/handlers_test.go
cmd/frontend/internal/cli/serve_cmd.go

This current code sets a global variable which couples the session package and the app package and the session package cannot work when the NewHandler method wasn't called yet.
This also used to wait for redis implicitly, without any indication of doing that.
To be more explicit about that, we now do that in the main function of frontend instead, and create the session store where required on the fly.
Test plan: Login still works, integration/E2E tests are passing.

chore: Remove redis init side-effect of app.NewHandler

---

cmd/frontend/internal/modelconfig/siteconfig.go
schema/schema.go
schema/site.schema.json

Previously, for providing self-hosted model' configuration (the models we've tested and believe work well), a site admin would use configuration like this:
```
"modelConfiguration": {
...
"modelOverridesRecommendedSettings": [
"mistral::v1::mixtral-8x7b-instruct",
"bigcode::v1::starcoder2-7b"
],
}
```
A few problems with this:
1. If you are NOT self-hosting models, you probably really should not be using this option, as it would set `serverSideConfig` options specific to self-hosting, but it's naming "recommended settings" which kind of suggests otherwise!
2. When self-hosting models, there is almost a 1:1 correlation of `provider` to actual API endpoint (because you have a single endpoint per model) - so not being able to configure the `mistral` or `bigcode` parts of the modelref above …

replace modelOverridesRecommendedSettings with selfHostedModels

---

cmd/frontend/graphqlbackend/codeintel.codenav.graphql
dev/linters/exhaustruct/lint-config.yaml
internal/codeintel/codenav/internal/lsifstore/store.go
internal/codeintel/codenav/observability.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_new.go
internal/codeintel/codenav/shared/types.go
internal/codeintel/codenav/transport/graphql/iface.go
internal/codeintel/codenav/transport/graphql/mocks_test.go
internal/codeintel/codenav/transport/graphql/root_resolver.go
internal/codeintel/codenav/transport/graphql/root_resolver_usages.go
internal/codeintel/codenav/types.go

This patch wires up the newly changed APIs in #64118 
to the GraphQL API, enabling precise support in the
usagesForSymbol API. It also handles pagination.
Fixes https://linear.app/sourcegraph/issue/GRAPH-573
Manually tested. Will add automated tests in follow-up PR.
- Adds support for precise code navigation to the experimental `usagesForSymbol` API,
which can be used to implement a reference panel or similar functionality.

feat: Add support for precise usagesForSymbol

---

internal/codeintel/codenav/transport/graphql/root_resolver.go

I think the span will not be terminated if we don't call `endObservation`.
Not the end of the world since this span likely won't be useful,
but we should avoid skipping calls to `endObservation` for consistency.
Stack on top of
- https://github.com/sourcegraph/sourcegraph/pull/64126
n/a

chore: Unconditionally call endObservation

---

cmd/frontend/graphqlbackend/codeintel.codenav.graphql

Noticed a TODO in the GraphQL schema docs, so figured I'd fill that out.
Stacked on top of
- https://github.com/sourcegraph/sourcegraph/pull/64150
- https://github.com/sourcegraph/sourcegraph/pull/64126 
n/a

docs: Specify matching behavior for usagesForSymbol(range:)

---

internal/search/result/match_test.go
internal/search/result/symbol.go
internal/search/streaming/search_filters.go

To implement `select:symbol.enum` filters, we look at each symbol's ctags 'kind' and check if it matches the filter value `enum`. We accidentally didn't include 'enum' in this match logic, so all these symbols were filtered away.
This PR fixes that, and adds a few improvements:
* Use a shared map between `symbol.LSPKind` and `symbol.SelectKind`, to avoid drift between these two conversions.
* Audit the ctags mapping from [sourcegraph/zoekt#674](https://github.com/sourcegraph/zoekt/pull/674) and add other missing kinds (besides enum)
Closes SPLF-178
Adapted unit tests. Manually tested `select:symbol.enum` before and after.
Fix a bug in `select:symbol.enum` filters where they returned no results

fix(search): correctly handle select:symbol.enum

---

sg.config.yaml

We don't need the docsite to run on most command sets, this PR simply removes it for those.
CI

chore(local): remove docsite from most commandsets

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-guides.yml

Follow-up to https://github.com/sourcegraph/devx-support/issues/1130 
Moving the doc links to a comment is merely a few lines of GitHub Script, so it's worth doing it for better merge commit messages. 
This PR itself was the test, as you can see below the comments that resulted from this new GH workflow. Btw, the second one is the one you'll see in the code here. I went for a oneliner to avoid cluttering the UI.

chore(ci): post instructions for PR sections in a comment

---

internal/bytesize/bytesize.go
internal/bytesize/bytesize_test.go
internal/extsvc/github/common.go
internal/memcmd/observer.go
internal/memcmd/observer_darwin.go
internal/memcmd/observer_linux.go
internal/memcmd/observer_linux_test.go

The old name 'Bytes' made it sound like it was supposed
to hold a []byte or a similar structure, whereas the type
actually represents a _size_ (in units of bytes).
n/a

chore: Rename type Bytes -> Size

---

cmd/frontend/graphqlbackend/codeintel.codenav.graphql

Really we just want to communicate that we might return a few more results than requested
Just a doc change

docs: Weaken guarantees for Usage cursor

---

dev/ci/internal/ci/images_operations.go
dev/ci/push_all.sh

Typo when copying the flags from somewhere else, names mismatched and didnt upload :facepalm: 
Also adding in proper BEP emitting, it appears the build_event_log.bin that was being output was actually for the honeyvent bazel invocation
CI main dry-run https://buildkite.com/sourcegraph/sourcegraph/builds/285375

chore(bazel): emit json profile for image push jobs (properly)

---

dev/sg/internal/cloud/build_command.go
dev/sg/internal/cloud/common.go
dev/sg/internal/cloud/deploy_command.go

Triggering cloud ephemeral builds on main-dry-run leads to unexpected results which is due to how the eventual pipeline is generated.
Closes DINF-165
The pipeline gets generated based on _what matches first_. We detect cloud ephemeral builds if there is an environment variable `CLOUD_EPHEMERAL=true`. We detect main-dry-runs if the branch prefix is `main-dry-run`...
Now due to the `main-dry-run` match happening before the cloud ephemeral match a Cloud Ephemeral build on a main dry run gets detected as _just_ a `main-dry-run` build.
Sure we can just move the Cloud Ephemeral match earlier, but it's difficult to say what else might break. We could also just add the we force the runtype to always be `CloudEphemeral` if we're on the Cloud Ephemeral pipeline, but I don't want to make the pipline …

fix(sg): cloud ephemeral - do no trigger builds on main-dry-run

---

internal/appliance/frontend/maintenance/src/Install.tsx

Basic fallback. See comments for a potential replacement. Even so, this gets us moving on day 0.
Closes https://linear.app/sourcegraph/issue/REL-313/handle-for-releaseregistry-down-in-install-page.
Manual tire-kicking with `pnpm run dev`, and hacking the hardcoded relreg URL to be invalid.

feat(appliance): version selector defaults when relreg down

---

cmd/frontend/internal/auth/oauth/middleware.go
cmd/frontend/internal/auth/openidconnect/middleware.go
cmd/frontend/internal/auth/providers/BUILD.bazel
cmd/frontend/internal/auth/providers/providers.go
cmd/frontend/internal/auth/saml/middleware.go

When exactly 1 auth provider is configured, Sourcegraph redirects users automatically to the IdP to speed up the sign-in process, so that users don't have to make an extra click to select the one and only sign-in provider.
SOAP is a special case though because it is hidden by default, but enabled on all cloud instances. That caused this auto redirect to never fire for Cloud, since there are technically two auth providers.
This PR fixes it by checking for the sourcegraph-operator query parameter which tells the UI to show the magic SOAP auth provider in the list.
Closes SRC-500
Test plan: Tested on a cloud instance that indeed there is no auto redirect. Then tested locally with SOAP configured that auto redirects happen after this PR, and that there is no auto redirect when the …

soap: Fix auto-redirect to IdP when SOAP is enabled

---

client/shared/src/codeintel/scip.ts
client/web-sveltekit/src/lib/codenav/ExplorePanel.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
client/web/src/repo/blob/codemirror/codeintel/occurrences.ts

This updates the new references panel to respect the provenance of an occurrence. 
Fixes SRCH-792
Followups:
- Need to fix pagination behavior. Before, the backend did not actually do any pagination, so I couldn't test this well. 
Quick manual test that find references now only returns precise references if the occurrence has a precise provenance.

Code intel: respect provenance when getting usages

---

release.yaml

Frontend assets are not embedded into the binary anymore instead they're added to the final container image at `/assets-dist`.
In this PR we check the directory inside the image for the marker instead of the binary
Closes DINF-176
Tested locally
```
sg release run test --version 1.2.3
👉 [     setup] Finding release manifest in "."
[     setup] No explicit branch name was provided, assuming current branch is the target: main
[     setup] Found manifest for "sourcegraph" (github.com/sourcegraph/sourcegraph)
[      meta] Owners: @sourcegraph/release
[      meta] Repository: github.com/sourcegraph/sourcegraph
👉 [      vars] Variables
[      vars] tag="1.2.3"
[      vars] config="{\"version\":\"v1.2.3\",\"inputs\":\"\",\"type\":\"patch\"}"
[      vars] git.branch="main"
[      vars] …
```

fix(release): check for marker in container files instead of binary

---

dev/sg/internal/cloud/client.go
dev/sg/internal/cloud/deploy_command.go
dev/sg/internal/cloud/instance.go
dev/sg/internal/cloud/instance_test.go
dev/sg/internal/cloud/printers.go

1. Make `sg cloud eph` instance status Reason simple string, as CloudAPI will take over and return Reason with job URL - no need to parse Reason anymore.
```sh
go run ./dev/sg cloud eph status --name ff-eph56
⚠️ Running sg with a dev build, following flags have different default value unless explictly set: skip-auto-update, disable-analytics
✅ Ephemeral instance "ff-eph56" status retrieved
Ephemeral instance details:
Name                                     Expires In           Instance status                          Details
ff-eph56                                 4h37m4.79031s        unspecified                              creation task is already running: https://console.cloud.google.com/workflows/workflow/us-central1/create-instance-c31bd1a4ea84/executions?project=michael-test-03 …
```

sg cloud eph: simplify status

---

internal/codeintel/uploads/internal/commitgraph/commit_graph.go
internal/codeintel/uploads/internal/store/BUILD.bazel
internal/codeintel/uploads/internal/store/commitgraph.go
internal/codeintel/uploads/internal/store/commitgraph_test.go
internal/codeintel/uploads/internal/store/util.go

A large sub-query was duplicated between two queries, making
the code harder to understand. This patch factors that out.
Ancillary changes:
- Added more doc comments
- Tweak tests to make failures easier to follow.

chore: Factor out sub-query for locating nearest uploads

---

internal/search/client/client.go
internal/search/query/transformer.go
internal/search/query/transformer_test.go

To ease the transition from older search semantics to keyword search, we [boost matches on phrases](https://github.com/sourcegraph/sourcegraph/pull/59940). For example if you search for `// The vararg opts parameter can include`, we ensure the match in the method comment is highest, even though there were no explicit quotes in the query. 
We decided to limit this boosting to searches with 3 or more terms. With 2 terms, it's possible there are a ton of phrase matches, which can drown out high quality 'AND' matches. However, we've seen a few dogfood examples with fewer terms where boosting would have been really useful.
This PR removes the 3 term restriction on boosting. To mitigate noise, it updates the phrase matching to only match on word boundaries. It also switches to matching on the …

search: apply phrase boosting to more queries

---

cmd/gitserver/internal/vcssyncer/perforce.go
schema/perforce.schema.json
schema/schema.go

Adds a `noConvertLabels` option to the p4-fusion config so that label conversion can be disabled if desired.
N/A

Add option for --noConvertLabels

---

internal/appliance/frontend/maintenance/src/Install.tsx
lib/codeintel/languages/extensions.go
lib/codeintel/languages/extensions_test.go

Part of [GRAPH-759](https://linear.app/sourcegraph/issue/GRAPH-759/issue-with-apex-extension-not-appearing-for-langapex)
Linguist only supports a subset of the file extensions often used for the Apex programming languages. This PR adds support for the main set commonly used.
**Key changes**
1. Adds all extensions for Apex
2. Update our logic to handle multiple extensions for one language
3. Update tests to ensure we only manually map languages if they don't exist OR have different extensions in go-enry (prevents us from duplicating entries completely from go-enry)

feat(search): Add support to all Apex language extensions

---

client/web-sveltekit/package.json
package.json
pnpm-lock.yaml

This PR brings the most recent version of @sourcegraph/cody-web package
- Improvements in how we fetch providers and debounce logic for their query 
- Fix with switching-chat actions and providers list 
- Manual checks over cody web (React and Svelte version)

Bump @sourcegraph/cody-web to 0.3.2

---

internal/appliance/frontend/maintenance/src/Frame.tsx

When the admin has first installed Code Search Suite, the appliance waits for the admin to click an "I'm ready" button. This causes the appliance to unblock a background thread that periodically checks the health of sg-frontend. When it is healthy, it ensures that the ingress-facing frontend is pointed to sg-frontend. And when it is not, it points to the appliance-frontend. Pointing to the appliance-frontend is its initial state pre-install, and given that we've just installed sg, the appliance switches the service over quickly.
Meanwhile, clicking this button transitions the frontend to a "refresh" state (this being one of the states in its state machine). This causes the UI to reload the web page. The reason we have to do this is that it is a way to "redirect to yourself". If the …

fix(appliance): reliably redirect to site-admin post-install

---

internal/appliance/auth.go

In order to reduce the cost of calls to auth-gated endpoints, cache valid admin passwords in-memory. The appliance's frontend calls auth-gated endpoints in a tight loop, and bcrypt checking is intentionally an expensive operation.
This could occasionally cause the appliance-frontend to disconnect from the backend. We observed frontend's nginx reporting an upstream connection close, and exec'ing into its pod and curling the backend regularly hung.
I collected two CPU profiles from the appliance backend: one without this commit, one with it. In both cases, SG was not being installed - the frontend was running, and I had a browser tab open, so that the browser was hitting the backend frequently via the nginx API proxy.
Without this fix:
With this fix:
See the test plan below for how I …

fix(appliance): cache authorization status

---

cmd/frontend/internal/modelconfig/init.go

The `frontend/internal/modelconfig` package exposes a service where any place in the codebase you can fetch the "currently supported LLM models". And that data will automatically be updated whenever the site configuration changes, and later, as new models are released on Cody Gateway.
However, the data structure is kinda complicated and requires careful configuration. e.g. to make sure that every model has a valid ModelReference, and that that ModelReference needs to refer to a ProviderID that is known, etc.
Previously, we were just silently ignoring any configuration errors. So if the site configuration data lead to an error when rendering/building the Sourcegraph instance's model configuration the site configuration data changes silently be ignored. This makes it much more difficult to …

Surface modelconfig validation errors

---

client/web-sveltekit/package.json
client/web-sveltekit/src/lib/cody/CodySidebar.svelte
client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/+page.ts
client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.tsx
package.json
pnpm-lock.yaml

Closes https://linear.app/sourcegraph/issue/SRCH-561/add-support-for-file-ranges-in-cody-web
- Check that you can mention files with ranges
- Check that as you open Cody chat on the blob UI page and you have selected lines in blob UI then chat should have an initial context mention with line range 
- Check that as you change line selection it updates mention file chip range (only if you don't have any other text)

Bump @sourcegraph/cody-web to 0.3.4

---

cmd/frontend/graphqlbackend/cody_context.go
cmd/frontend/graphqlbackend/cody_context.graphql
cmd/frontend/internal/context/resolvers/BUILD.bazel
cmd/frontend/internal/context/resolvers/context.go

Due to CORS rules, cody web cannot make requests to arbitrary URLs. Because of this, mentions for URLs do not currently work in Cody Web.
This adds a GraphQL endpoint to the cody context resolvers that resolves the contents of a mentioned URL.
Tested end-to-end with dev build of cody web.

Cody web: add server-side fetching for URL mentions

---

doc/dev/setup/quickstart.md

- Update the "getting started" link in the quickstart guide to point to the correct URL
- Remove the outdated developer help links as they are no longer relevant
Test the links manually

fix(docs): update quickstart guide links

---

cmd/frontend/internal/auth/oauth/middleware.go
cmd/frontend/internal/auth/openidconnect/middleware.go
cmd/frontend/internal/auth/providers/BUILD.bazel
cmd/frontend/internal/auth/providers/providers.go
cmd/frontend/internal/auth/saml/middleware.go

Reverts sourcegraph/sourcegraph#64184
The sourcegraph/sourcegraph#64184 is probably caused auth redirect on dot com. Revert it while we're fixing the original problem
CI

Revert "soap: Fix auto-redirect to IdP when SOAP is enabled"

---

internal/codeintel/uploads/internal/commitgraph/commit_graph.go
internal/codeintel/uploads/internal/store/commitgraph.go
internal/codeintel/uploads/internal/store/commitgraph_test.go
internal/codeintel/uploads/internal/store/util.go

When determining the set of visible uploads at a given commit,
we group uploads from scip-K and lsif-K for ranking purposes
to allow them to shadow each other. Generally, scip-K will end
up shadowing lsif-K, avoiding sending the client a mix of data
from a much older lsif-K index when newer data from a scip-K
index is available.
Fixes https://linear.app/sourcegraph/issue/GRAPH-787
The logic requires some final tie-breaking to avoid non-determinism
in case when there is a scip-K and lsif-K index at the same distance,
which I've done based on the upload_id in descending order
(upload IDs are monotonically increasing). Earlier, some code was
doing tie-breaking based on upload_id in _ascending_ order,
so I've changed that for consistency. This caused some test failures,
so I've updated the …

fix: Prefer SCIP uploads over LSIF uploads

---

dev/sg/internal/cloud/instance.go

Make ephemeral feature flag consistent across sg cli and CloudAPI:
- [get](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/sg/internal/cloud/instance.go?L193) is ok
- [set](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/sg/internal/cloud/instance.go?L206) was different 
- CloudAPI uses now [this](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/controller/-/blob/cmd/apiserver/api/v1/instance.go?L20)
[e2e against CloudAPI](https://github.com/sourcegraph/cloud/pull/12747)

ephemerals: fix feature flag name

---

deps.bzl
go.mod
go.sum
internal/codeintel/codenav/internal/lsifstore/locations_by_position.go

Right now, perf is dominated by slowness of gitserver, but let's
avoid the pessimization in the old code with multiple linear lookups.
Manually tested + covered by existing tests.

chore: Use binary search over symbols array

---

cmd/frontend/internal/auth/oauth/middleware.go
cmd/frontend/internal/auth/openidconnect/middleware.go
cmd/frontend/internal/auth/providers/BUILD.bazel
cmd/frontend/internal/auth/providers/providers.go
cmd/frontend/internal/auth/saml/middleware.go

This reverts commit https://github.com/sourcegraph/sourcegraph/commit/81585cb7ca98196695088d3b1a1038606ef2bcde.
Tested in dotcom mode locally after clearing cookies and no redirect happens now.

Reapply "soap: Fix auto-redirect to IdP when SOAP is enabled" (#64234) 

---

cmd/gitserver/internal/git/gitcli/diff.go
cmd/gitserver/internal/git/gitcli/diff_test.go

ResolveRevision additionally adds a "^0" to the spec to make sure we actually check if it exists. This is important, since most uses of the ChangedFiles API pass in commit shas which do not get resolved by git unless the "^0" is present.
I noticed this since hybrid search in searcher started to fail if the commit was missing. In particular Zoekt for empty repositories uses a fake SHA of 404aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa so when a repo started getting cloned hybrid search would fail until it was indexed. Hybrid search explicitly checks for the NotFound error, so hybrid search failing was a a regression from moving away from the SymbolDiff API.
Fixes https://linear.app/sourcegraph/issue/SPLF-166/hybrid-search-handles-missing-indexed-commit
added a test case which failed before this …

gitserver: RawDiff checks if commits exist

---

client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.tsx

With SRCH-802 we saw error messages when batch changes may still retry and resolve the problem. To give a better distinction between resolvable and non-resolvable errors, I'm changing the colour variation from error to warning if the changeset has not been marked as `FAILED` yet.
Before:
After:
Manual testing
- Batch changes that are still retrying now show a warning instead of an error.

fix(batches): show warning instead of error when the changeset status is not FAILED

---

internal/httpcli/client.go

In Go it's possible to have URLs without a valid host portion :shrug: . This has unintended side-effects when filtering hostnames. 
Tested that URLs that have no hostname are now blocked.

fix: block URLs without a hostname

---

client/web-sveltekit/src/routes/+layout.svelte

Fixes SRCH-831
Local test that the banner no longer flashes on refresh.

Svelte: fix welcome banner flashing on reload

---

client/web/src/repo/blame/shared.ts
cmd/frontend/internal/httpapi/httpapi.go

The URL path for streaming blame is ambiguous when the file path contains `/stream/`. The pattern looks like `/blame/<repo_name>@<revision>/stream/file/path.txt`. However, if the file contains `/stream/`, the revision is matched greedily up until the last stream, so we end up with a revision that looks like `81af3g/stream/my/path`, which is in invalid revision that results in a 404. 
This makes the URL pattern unambiguous by adding a `/-/` element after the revision, which is not allowed in a revision name and acts as a path separator. So now, the pattern looks like `/blame/<repo_name>@<revision>/-/stream/file/path.txt`.
Note, this is a public-facing breaking change, but I don't think it really matters since I don't expect any customers use our streaming blame API
Fixes SRCH-738
Tested …

Web: fix git blame for files that have `/stream/` in their path

---

client/web/src/cody/chat/new-chat/components/chat-history-list/ChatHistoryList.tsx
client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.module.scss
client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.tsx
client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.module.scss
client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebarWebChat.tsx
package.json
pnpm-lock.yaml

Closes https://linear.app/sourcegraph/issue/SRCH-720/new-chat-button-in-side-panel-view
Closes https://linear.app/sourcegraph/issue/SRCH-808/chat-history-in-side-panel-view
This PR does a few things 
- Updates Cody Web to 0.3.6 (this includes improvements around mentions UI, web url mention support, etc)
- Adds "create new chat" button to the sidebar cody chat UI
- Adds history chats UI to the sidebar cody chat UI (note that in GA we will rely on the new Tabs UI, this history UI is just a temporal solution for the Sourcegraph Aug release, in sep GA release it will be improved)
- General manual checks on Cody Web.
- Check that you can create a new chat from the sidebar chat UI
- Check that you can select chats from the history panel from the sidebar chat UI

Cody Web: Update Cody Web to 0.3.6 [React version]

---

internal/codeintel/codenav/service.go

The `getSourceRange` function can have a range translation failure,
in which case it would be wrong to propagate the range directly
without the commit information. So skip the ranges in that case.
n/a - we're not going to keep the GetHover and GetStencil APIs around
for much longer, but this is a quick fix

fix: Don't propagate un-translated source ranges

---

lib/servicecatalog/service-catalog.yaml

Searcher doesn't speak to the database nor has it for a long time. See https://github.com/sourcegraph/sourcegraph/pull/61463
Test Plan: The following command is empty
go run ./dev/depgraph/ summary internal/database | grep 'cmd/searcher'

servicecatalog: remove searcher dep on database

---

internal/codeintel/codenav/service_new.go

The cursor state can be "" when the data is exhausted.
n/a

chore: Remove incorrectly logged warning

---

deps.bzl
go.mod
go.sum

This only contains one commit which reduces how often we call scan in indexserver on dotcom.
- https://github.com/sourcegraph/zoekt/commit/acacc5eda1 shards: only trigger rescan on .zoekt files changing
Test Plan: tested in zoekt CI

gomod: update zoekt for shard scanning improvement

---

wolfi-packages/p4-fusion-sg.yaml

Update the p4-fusion wolfi package to use the latest version after the addition of the labels -> tags conversion feature.
Builds still pass.

Update p4-fusion-sg wolfi-package

---

client/web-sveltekit/src/routes/WelcomeOverlay.svelte

In response to [this request](https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1722633022111559), I modified the welcome banner to:
- Add a close button in the top right
- Close on click outside the banner
- Make the button primary rather than secondary
Fixes SRCH-837
Manual test
https://github.com/user-attachments/assets/b7d41ce0-5c85-4489-b0a6-f98e07113471

Svelte: make closing the welcome overlay more obvious

---

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileView.svelte

When I added this, for some reason I thought it was site admin only. As it turns out, it shouldn't be gated to site admins only, and it makes it particularly annoying on dotcom.
Quick manual check

Svelte: remove site admin gate on code intel preview

---

internal/conf/computed.go
schema/site.schema.json

Closes https://linear.app/sourcegraph/issue/GRAPH-784/default-scip-api-ff-to-on
Enable SCIP based APIs by default, as they're required for the web app refresh.
Things have been going fine on Dotcom and S2

Enable SCIP based APIs by default

---

cmd/worker/internal/executorqueue/reporter.go

Previously, for metrics reporting, we were querying the number of queued+errored
records every 5 seconds. For large queues + heavy contention, this scan itself takes
a few seconds, despite using an index. Reduce the frequency of this scan as we
don't need updates to the queue size every 5 seconds.
Check that frequency of `COUNT(*)` is reduced on Sourcegraph.com once
this patch makes its way to Sourcegraph.com

chore: Reduce frequency of COUNT(*) on lsif_indexes

---

cmd/searcher/internal/search/chunk_test.go
cmd/searcher/internal/search/search_regex_test.go

Column helper now returns 0 based indexes. FilterTar became a required function on diskcache.
Test Plan: go test -run '^$' -bench . ./cmd/searcher/internal/search
Fixes https://linear.app/sourcegraph/issue/SPLF-183/benchmarks-in-searcher-broken

searcher: fix benchmarks

---

internal/codeintel/resolvers/codenav.go

At the moment we decode via the "Std" encoding, which expects padding but we encode with "Raw" which doesn't add any.
Manual testing

fix: uses the same base64 for decoding we use for encoding the UsageCursor

---

internal/search/client/client.go
internal/search/client/client_test.go

In #64215, we removed support for smart search. We continued to allow the `smart` search mode, but just execute with `precise` behavior. However, we started to throw an error for `patterntype:lucky` (which is the old way of specifying smart search). It turns out that `lucky` made its way into some search links and settings, causing those searches to fail.
This PR restores support for `lucky`, and remaps it to `standard`. This preserves the semantics as much as possible (since smart search attempts a 'standard' search as its first rule).
Closes SRCH-840
New unit test case. Tested manually with `patterntype:lucky` and checked semantics match `standard.

Search: re-add support for 'lucky' patterntype

---

cmd/frontend/internal/licensing/init/BUILD.bazel
cmd/frontend/internal/licensing/init/init.go
cmd/frontend/internal/modelconfig/BUILD.bazel
cmd/frontend/internal/modelconfig/init.go

These imports don't seem to have side-effects so dropping them to keep the dependency graph simple.
Test plan: E2E CI still passes.

chore: Remove unnecessary _ imports

---

internal/search/query/transformer.go
internal/search/query/transformer_test.go

Follow up to #64207. In our old search semantics, quotes were interpreted literally. So a query like `"sourcegraph"` would match only strings like `fmt.Println("sourcegraph")`. Now, both single and double quotes are used for escaping, and mean that the contents should be searched exactly.
This PR makes sure to boost matches on quoted terms in result ranking. This way, users familiar with the old syntax are more likely to find what they're after.
Adapted unit tests. Re-tested all queries from #64207 manually, plus these ones:
* `'sourcegraph'`
* `"sourcegraph"`

Search: boost matches on quoted terms

---

cmd/frontend/internal/app/ui/router.go

Fixes srch-765
When navigating to `/cody/dashboard` and the new web app is enabled, the user gets a "Not found" error. This doesn't happen in the React app.
The page doesn't exist in the new web app, hence the server should fall back to the old web app but that doesn't happen.
Why? Because the server doesn't know about `/cody/dashboard` either. It only exists in the React app.
Instead the server interprets this path as a (non-existing) repository page. When the new web app is enabled, repository pages are handled by the new web app, but since neither the repo nor the page exist in the new web app, the aforementioned error is thrown.
Configuring this route on the server makes it so that the React app is served instead.
Manual testing. Going to https://sourcegraph.test:3443/cody/dashboard …

fix(svelte): Make /cody/dashboard work with the new web app

---

cmd/frontend/internal/executorqueue/handler/multihandler.go
cmd/frontend/internal/executorqueue/handler/multihandler_test.go
internal/workerutil/dbworker/store/mocks/mocks_temp.go
internal/workerutil/dbworker/store/observability.go
internal/workerutil/dbworker/store/store.go
internal/workerutil/dbworker/store/store_test.go

Running `COUNT(*)` on hot tables like lsif_indexes on Sourcegraph.com
shows up on profiles when the number of executors is bumped to
30+, and when the table has 100K+ jobs. So avoid `COUNT(*)`
where possible.
Added test for the new Store method

fix: Add Exists method to dbworker Store to avoid COUNT(*)

---

internal/search/job/jobutil/exhaustive_job.go
internal/search/job/jobutil/exhaustive_job_test.go
internal/search/job/jobutil/job.go
internal/search/job/jobutil/job_test.go

This closes a pretty big gap in the query validation for Search Jobs. We don't support repo search yet and searcher returned errors during execution, complaining about missing patterns. With this PR we fail during validation so users cannot even create these kinds of jobs. See new test cases.
Updated unit tests

fix(search_jobs): fail validation for repo searches

---

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte

We should probably redesign the whole loading state but this simple change is still better than the current behavior.
| ![2024-08-06_21-00_1](https://github.com/user-attachments/assets/015d47d3-9542-4d72-b422-56975723576c) | ![2024-08-06_21-00](https://github.com/user-attachments/assets/0e667bc2-496e-4169-806d-b49757681673) | 

fix(svelte): Center file tree loading indicator

---

cmd/frontend/internal/modelconfig/resolver.go
cmd/frontend/internal/modelconfig/resolver_test.go
cmd/frontend/internal/modelconfig/siteconfig_completions.go
cmd/frontend/internal/modelconfig/siteconfig_completions_test.go

::sigh:: the problem here is super in the weeds, but ultimately this fixes a problem introduced when using AWS Bedrock and Sourcegraph instances using the older style "completions" config.
AWS Bedrock has some LLM model names that contain a colon, e.g. `anthropic.claude-3-opus-20240229-v1:0`. Cody clients connecting to Sourcegraph instances using the older style "completions" config will obtain the available LLM models by using GraphGL.
So the Cody client would see that the chat model is `anthropic.claude-3-opus-20240229-v1:0`.
However, under the hood, the Sourcegraph instance will convert the site config into the newer `modelconfig` format. And during that conversion, we use a _different value_ for the **model ID** than what is in the site config. (The **model name** is what is sent to …

Return model IDs from GraphQL, not model Names

---

client/web/src/enterprise/own/RepositoryOwnEditPage.tsx
client/web/src/enterprise/own/RepositoryOwnPage.tsx

I noticed that my computer fans kept on spinning when visiting https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/own and https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/own/edit.
Long story short because we are not memoizing the breadcrumbs we are in an infinite update loop. The offending commit is
c42c57da1d23e4a4f470cb841301eda234853a53.
React profiler screenshot:
Manual testing. Fans stopped spinning.

fix(own): Prevent infinite UI update loop in own pages

---

client/web-sveltekit/dev/vite-sg-proxy.ts

I noticed that non-svelte repo subpages haven't been redirected to the React app in local development (it works as expected in production).
That's because the proxy doesn't know about them since they are not part of `knownRoutes`.
We could update the server code to include those routes as well but that seems heavey handed just to make local development work.
I think in this case it's fine to have manual entries for the handful of repo subpages that have not been migrated to Svelte yet.

chore(svelte): Add manual entries for repo sub pages to development proxy

---

dev/sg/internal/analytics/analytics.go
dev/sg/internal/analytics/bigquery.go

Closes DINF-193
OS information is now part of the `sg` analytics metadata.
Any `sg` operation now reports the os information.

feat(sg): report user os information via analytics

---

internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_syntactic_usages_test.go
internal/codeintel/codenav/syntactic.go
internal/codeintel/codenav/transport/graphql/iface.go
internal/codeintel/codenav/transport/graphql/mocks_test.go
internal/codeintel/codenav/transport/graphql/root_resolver.go
internal/codeintel/codenav/types.go

This change should not change any behaviour, but it prepares for syntactic/search-based pagination.
Both syntactic and search based usages now return a "NextCursor", which is `Some` if there are more results of their provenance to be had. For now they always return `None` which preserves the current behaviour. The logic in `root_resolver` implements a state machine that transitions the cursor through the provenances and makes sure to skip provenances if the cursor in the request starts a certain state.
Reviewer hint: I wouldn't bother with the diff view for `root_resolver.go`
Tests continue to pass, no behavioral changes

refactor: handles Cursor uniformly over all usage provenances

---

client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte

Cody's Web Sidebar in Svelte is not following the theme when tested locally. 
This PR fixes that. I have tested this with multiple builds both with & without the diff. 
Before:
After:

Fix Cody Web Svelte Sidebar

---

cmd/worker/internal/executormultiqueue/multiqueue_metrics_reporter.go
cmd/worker/internal/executorqueue/external_emitter.go
cmd/worker/internal/executorqueue/reporter.go
cmd/worker/internal/permissions/BUILD.bazel
cmd/worker/internal/permissions/bitbucket_projects_test.go
cmd/worker/internal/search/job.go
internal/codeintel/syntactic_indexing/BUILD.bazel
internal/codeintel/syntactic_indexing/scheduler_test.go
internal/codeintel/syntactic_indexing/store_test.go
internal/insights/background/queryrunner/worker.go
internal/own/background/BUILD.bazel
internal/own/background/background_test.go
internal/workerutil/dbworker/metrics.go
internal/workerutil/dbworker/store/mocks/mocks_temp.go
internal/workerutil/dbworker/store/observability.go
internal/workerutil/dbworker/store/store.go
internal/workerutil/dbworker/store/store_test.go
internal/workerutil/dbworker/store_shim.go

Previously, the QueuedCount method was confusing because:
1. By default, it actually returned the count for both the 'queued' and 'errored' states
(despite the name just have 'Queued').
2. There was an additional boolean flag for also returning entries in the 'processing' state,
but reduced clarity at call-sites.
So I've changed the method to take a bitset instead, mirroring the just-added Exists API,
and renamed the method to a more generic 'CountByState'.
While this does make call-sites a bit more verbose,
I think the clarity win makes the change an overall positive one.
However, if there is strong opposition, I'm open to re-considering/closing this PR.
This PR is stacked on top of:
- https://github.com/sourcegraph/sourcegraph/pull/64297
At the moment, there …

chore: Replace QueuedCount -> CountByState with bitset parameter

---

client/web-sveltekit/src/lib/cody/CodySidebar.svelte
client/web/src/cody/sidebar/new-cody-sidebar/NewCodySidebar.tsx

Fixes Cody Logo alignment to center for both React & Svelte Cody Sidebar header. 
Before:
After:

Center align Cody logo in Cody Web Sidebar

---

internal/codeintel/codenav/transport/graphql/root_resolver.go
internal/codeintel/codenav/types.go
internal/codeintel/resolvers/codenav.go

Adds a second function to determine the initial cursor based on the requested provenances.
N/A

refactor: steps the usage cursor provenance state in a single place

---

client/branded/src/search-ui/results/progress/StreamingProgressSkippedPopover.tsx
client/web-sveltekit/src/app.html
client/web-sveltekit/src/lib/LoadingSpinner.stories.svelte
client/web-sveltekit/src/lib/LoadingSpinner.svelte
client/web-sveltekit/src/lib/Popover.svelte
client/web-sveltekit/src/routes/search/+page.svelte
client/web-sveltekit/src/routes/search/+page.ts
client/web-sveltekit/src/routes/search/SearchResults.svelte
client/web-sveltekit/src/routes/search/StreamingProgress.svelte
client/web-sveltekit/src/routes/search/page.spec.ts
client/web-sveltekit/src/routes/search/searchJob.gql
client/web-sveltekit/src/routes/search/searchJob.ts
client/web-sveltekit/src/routes/styles.scss
client/web-sveltekit/src/testing/graphql-mocking.ts
client/web-sveltekit/src/testing/integration.ts

Closes srch-838
This commit extends the search progress popover and adds the search jobs section.
In the React version the UI for the popover differs slightly when search jobs are enabled vs not enabled.
I decided to ignore the differences and only impolemented the style used for the 'search jobs enabled' version, which makes the popover a bit more compact.
The logic for validating and creating a search job is encapsulated in a class which makes it easy to conditionally show the search jobs UI.
- Skipped items is now a list and uses `<details>` elements which is semantically more correct. We loose the styling of the chevron but I think that's OK.
- LoadingSpinner was updated to work inline.
- Logging was fixed (?) in the React version to send the correct meta-data.
- …

feat(svelte): Add support for creating search jobs from search results

---

client/web-sveltekit/src/lib/TreeNode.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/FileTree.svelte

Currently the link element doesn't extend to the full width of the sidebar. You can click outside of the actual text to navigate to the file, but it won't be preloaded.
Now the link occupies the full width.
| ![2024-08-07_12-24](https://github.com/user-attachments/assets/fb77ea1d-9ee1-47b7-82c2-4bad6badd2be) | ![2024-08-07_12-26](https://github.com/user-attachments/assets/70225bc6-b783-4649-91a3-485f93dcc9c5) | 

fix(svelte): Better preloading in file tree

---

client/web-sveltekit/src/lib/navigation.ts

Fixes srch-851
A consequence of https://github.com/sourcegraph/sourcegraph/pull/64272 is that redirecting to the cody marketing page on dotcom didn't work. That's because `/cody` is not provided by the server as a known page.
A simple fix would be to mark the link as external, but we'd have to keep in mind to do this in all places (present and future).
A more "central" fix is to add this page to a hardcoded list of known pages that are not provided by the server.
Manual testing

fix(svelte): Properly redirect to cody marketing page

---

internal/database/repos.go

I will be adding a fake repo store in a follow-up PR for codenav,
so I want to make sure the guarantees of the interface are
documented/agreed upon first.
n/a - only adding doc comments

chore: Add docs for RepoStore methods

---

dev/sg/sg_version.go

Context: As I was catching up with my Slack notifications, I spotted this [conversation](https://sourcegraph.slack.com/archives/C04MYFW01NV/p1721137862832899?thread_ts=1721136881.733869&cid=C04MYFW01NV) and this PR is a 5m fix to avoid the problem to happen again. 
What: If you haven't used `sg` in a while, it's easy to think that `sg version` refers to the currently deployed Sourcegraph instance and not the CLI. This commit adds a little preamble on stderr to not mess with script usage while still reminding the user that it's the CLI version that gets printed out.
Before: we printed the version without any context
After: we also print the following on stderr: `👉 Showing the current version of the sg CLI, if you're looking for deployed Sourcegraph instances version, please use `sg live` …

chore(local): clear ambiguity in between sg version|live

---

cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
cmd/enterprise-portal/internal/dotcomdb/dotcomdb_test.go

Several subscriptions, upon import, ran into conflicts even with the username - user display name - date format.
https://sourcegraph.sentry.io/issues/5688073768/?referrer=slack&notification_uuid=83d264fb-364a-4bc1-a5ab-9d7164a906cd&alert_rule_id=15193465&alert_type=issue
unit tests

fix/enterpriseportal/importer: make generated display name more unique

---

cmd/enterprise-portal/internal/database/importer/importer.go
cmd/enterprise-portal/internal/dotcomdb/dotcomdb.go
cmd/enterprise-portal/internal/dotcomdb/dotcomdb_test.go

Turns out, the `dev` tag is not a reliable indicator of whether a license is for dev use only - let's just import all subscriptions into prod, and drop the customer records from dev later.
CI

fix/enterpriseportal/importer: import all subscriptions

---

client/web-sveltekit/src/lib/CodeMirrorBlob.svelte
client/web-sveltekit/src/lib/codenav/ExplorePanel.svelte
client/web-sveltekit/src/lib/repo/blob.ts
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/+layout.svelte

This commit adds the necessary logic to open the explorer tab for multiple references and for implementations. I basically copied what @camdencheek did for the references tab.
Hover over `adapt` in http://localhost:5173/github.com/sveltejs/kit@65931f276ac2102032e3032c864a472eee19b7bb/-/blob/packages/kit/src/exports/vite/index.js?L890 and click 'got to definition'. The explore panel with should open with the definitions tab selected.
I wasn't able to test the find implementations logic because I don't know for which language we have this implemented.

feat(svelte): Support 'got to defintion' for multiple definitions and  'find implementations'

---

schema/site.schema.json

Changing azureUseDeprecatedCompletionsAPIForOldModels to default to trueso that customers who upgrade don't have to change siteadmin config
Tested locally

Changing azureUseDeprecatedCompletionsAPIForOldModels to default to true

---

cmd/enterprise-portal/internal/database/importer/BUILD.bazel
cmd/enterprise-portal/internal/database/importer/importer.go
lib/managedservicesplatform/cloudsql/tracer.go

This can generate 10k+ spans in production
Also added simple handling for `pgx.NamedArgs` here, since I notice those are missing
CI

fix/enterpriseportal/importer: disable query tracing when importing

---

cmd/frontend/graphqlbackend/external_account_data_resolver_test.go
cmd/frontend/internal/auth/gerrit/config.go
cmd/frontend/internal/auth/httpheader/provider.go
cmd/frontend/internal/auth/oauth/provider.go
cmd/frontend/internal/auth/openidconnect/config.go
cmd/frontend/internal/auth/openidconnect/middleware.go
cmd/frontend/internal/auth/openidconnect/middleware_test.go
cmd/frontend/internal/auth/openidconnect/provider.go
cmd/frontend/internal/auth/openidconnect/session.go
cmd/frontend/internal/auth/openidconnect/user.go
cmd/frontend/internal/auth/openidconnect/user_test.go
cmd/frontend/internal/auth/providers/mock_auth_provider.go
cmd/frontend/internal/auth/providers/providers.go
cmd/frontend/internal/auth/saml/config.go
cmd/frontend/internal/auth/saml/provider.go
cmd/frontend/internal/auth/sourcegraphoperator/config.go
cmd/frontend/internal/auth/sourcegraphoperator/middleware.go
cmd/frontend/internal/auth/sourcegraphoperator/middleware_test.go
cmd/frontend/internal/auth/sourcegraphoperator/provider.go
cmd/frontend/internal/auth/userpasswd/provider.go

This PR makes the calls to create the OIDC provider explicit, so that we don't need to implicitly need to call a Refresh method, even if we might end up not needing the `p.oidc`.
This is a start toward being able to create providers on the fly cheaply vs having a globally managed list of providers in memory.
We did call refresh everywhere we do now anyways to the best of my understanding, so a passive goroutine in the background to my best understanding didn't add a lot here.
Test plan: Auth with SAMS locally still works.

oidc: Don't require to run refresh on provider init

---

dev/oci_defs.bzl

This should resolve the Workflows delivery failure seen in https://buildkite.com/sourcegraph/sourcegraph/builds/286482#01912eb8-a1a9-48c6-81b0-4f5a09448bbb after landing the rules_oci 2 upgrade:
```
· Error: failed to compute runfiles hash for manifest: error concurrently hashing file /mnt/ephemeral/output/sourcegraph/__main__/execroot/__main__/bazel-out/k8-opt-ST-d57f47055a04/bin/dev/build-tracker/image_underlying/blobs/sha256/104f4630c01017c52e968bfe039f6eb7622ef1ad9d44d94d784cc9c39992961b: failed to open file /mnt/ephemeral/output/sourcegraph/__main__/execroot/__main__/bazel-out/k8-opt-ST-d57f47055a04/bin/dev/build-tracker/image_underlying/blobs/sha256/104f4630c01017c52e968bfe039f6eb7622ef1ad9d44d94d784cc9c39992961b for hashing: open …
```

fix(build): forward runfiles in custom oci_image_cross rule

---

client/web-sveltekit/src/lib/repo/HovercardContent.svelte

I don't know why but having `overflow-x` causes the content of the hovercard to not fully expand to the edges. It has something to do with the sizing of the `hr` element.
| ![2024-08-07_23-39_1](https://github.com/user-attachments/assets/5e02f369-bc33-49db-b69d-ec63afe5de17) | ![2024-08-07_23-39](https://github.com/user-attachments/assets/04c71fff-a232-4c8d-b0a5-3ea1d1659e29) | 

fix(svelte): Improve hovercard UI for search based info

---

client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte

Fixes srch-858
Currently the menu icon rotates when hovering over it. The animation should only target the Sourcegraph logo.
- Move icon color style prop into CSS declaration (avoids inserting an additional element)
- Let the animation target the link instead of the icon. There doesn't seem to be reason why we actually need to target the `svg` element via `:global`.

fix(svelte): Don't animate menu icon

---

dev/sg/internal/sgconf/config.go
dev/sg/sg_start.go
sg.config.yaml

Now that https://github.com/sourcegraph/sourcegraph/pull/64339 is merged, we can tell users more about what to expect with `sg start single-program-experimental-blame-sqs`. And as it's been in flight for a while now, it's safe to say that's it's time to give it a shorter name 😊. 
So it's been renamed from `single-program-experimental-blame-sqs` to `minimal`. And to ensure nobody is getting confused, a `deprecated` attribute has been added on the command sets, which is used here to indicate that the new alternative is `sg start`. 
❓ Thoughts about `sg start minimal`? `sg start single` perhaps? 
Running the old commandset: (ignore the yellow message, that's just a local warning from `sg`) 
Running the new commandset, with the preamble explaining what to expect: 

chore(local): rename experiment single-program commandset

---

internal/database/schema.codeinsights.json
internal/database/schema.codeinsights.md
internal/database/schema.codeintel.json
internal/database/schema.codeintel.md
migrations/codeinsights/1723117231_add_tenants_table/down.sql
migrations/codeinsights/1723117231_add_tenants_table/metadata.yaml
migrations/codeinsights/1723117231_add_tenants_table/up.sql
migrations/codeinsights/squashed.sql
migrations/codeintel/1723117227_add_tenants_table/down.sql
migrations/codeintel/1723117227_add_tenants_table/metadata.yaml
migrations/codeintel/1723117227_add_tenants_table/up.sql
migrations/codeintel/squashed.sql

In some deployments, these are running in separate instances. This migration makes sure that we can still reference the tenants from the tenant_id column reliably everywhere.
It's critical that this migration is a noop on instances that already have this table, so please double check me here during code review.
Test plan: Integration and E2E tests still pass, as this should be a noop.

tenant: Ensure tenant table also exists in codeintel and codeinsights DBs

---

client/web-sveltekit/src/lib/navigation/GlobalHeader.svelte

Fixes srch-859
Problem: Currently the sidebar can reopen in the following scenario:
- Go to search home and submit a search
- On the search results page click the menu icon to open the sidebar and click 'Code Search' to go back to search home.
- Execute a different query
- -> this brings you back to search results but with the menu sidebar open
Looking at the code it's understandable that this happens: We never close the sidebar. But this problem wasn't very visible because every entry in the nav sidebar either brings you to the React app or to a page with inline nav menu.
So this commit fixes the issue by closing the sidebar whenever we navigate to a different page.
Manual testing. I added a temporary nav entry that would bring me to the sourcegraph repo page. Clicking on it from the …

fix(svelte): Always close navigation sidebar when navigating to a different page

---

client/web-sveltekit/BUILD.bazel
client/web-sveltekit/README.md
client/web-sveltekit/package.json
client/web-sveltekit/svelte.config.js
sg.config.yaml

Fixes srch-867
This commit adds a new command, `web-sveltekit-prod`, which simplies builds the SvelteKit app and exits.
This command is now run by default when using `sg start`, so the assets will be available locally.
Note however that the build process is quite slow, which is why I didn't make it rebuild on file changes. Using the vite dev server, e.g. via `sg start enterprise-sveltekit`, delivers a much better experience.
To make the integration a bit more ergonomic, I made additional changes:
- When run via `sg` (determined by checking `DEPLOY_TYPE`) compiler warnings are not printed. That reduces noise in the `sg` output.
- I made similar changes to the svelte check bazel target to make it easier to spot actuall errors (warnings are still important to fix but since they don't cause …

build(svelte): Build Svelte app with enterprise runset

---

internal/database/dbconn/tenant_pprof.go
internal/diskcache/cache.go
internal/tenant/context.go
internal/tenant/context_test.go
internal/tenant/externalhttp_test.go
internal/tenant/grpc.go
internal/tenant/grpc_test.go
internal/tenant/http.go
internal/tenant/http_test.go

This updates `FromContext` to return an error instead of bool.
Follow-up from comment in [#64335](https://github.com/sourcegraph/sourcegraph/pull/64335#discussion_r1708886602)
Test plan:
CI

tenant: update FromContext to return error

---

client/web-sveltekit/src/lib/cody/CodySidebarChat.svelte
client/web/src/cody/chat/new-chat/components/chat-ui/ChatUI.module.scss

closes: https://linear.app/sourcegraph/issue/SRCH-866/improve-cody-web-theming-for-consistency-with-rest-of-product
This PR updates the Cody Web CSS based on the changes requested by @rrhyne.
Few buttons implemented in Cody doesn't satisfy the design requirements and do not use the css variable so we couldn't update them easily but rather had to override the styles. 
Before: 
After:
- Make Cody Web styles more accessible.

Fix Cody Web CSS

---

cmd/enterprise-portal/internal/codyaccessservice/v1.go
cmd/enterprise-portal/internal/codyaccessservice/v1_test.go
cmd/enterprise-portal/internal/database/codyaccess/codygateway.go
cmd/enterprise-portal/internal/database/codyaccess/codygateway_test.go
cmd/enterprise-portal/internal/database/importer/importer.go
cmd/enterprise-portal/internal/database/types.go

On double-checking the various Cody Gateway access management CRUD I noticed that I did not implement the ability to remove the override entirely properly - right now, removing a rate limit with `field_mask` and no values results in a zero-value rate limit rather than a null one as desired.
This change makes it so that if you provider a nil `*_rate_limit` object, all field paths for that object is also set to nil, removing the override and allowing the default active-license-plan-based rate limits to apply.
This also adds a minor adjustment to Cody Gateway to correctly handle zero durations for rate limit intervals, which should be treated as "no access".
Unit/integration tests, and a manual test:
- Check out https://github.com/sourcegraph/sourcegraph/pull/64090 and run `sg start dotcom` …

fix/enterpriseportal/codyaccess: allow removing rate limit overrides

---

WORKSPACE

Some analysis phase performance improvements in rules_js 2.0.0-rc9 that are worth picking up. rules_js is very close to 2.0.0 final now. Waiting on one last improvement requiring and API change for bzlmod.
CI

build(bazel): upgrade to latest aspect bazel-lib and rules_js rules

---

internal/search/query/BUILD.bazel
internal/search/query/transformer.go
internal/search/query/transformer_test.go

To ease the transition from older search semantics to keyword search, we [boost matches on phrases](https://github.com/sourcegraph/sourcegraph/pull/59940). This phrase boosting applied to all search types, including repo, and symbol searches. However, these search backends don't effectively handle the extra boosted OR clause, so it can hurt performance and ranking.
This PR limits the phrase boosting to text searches (`type:file` and `type:path`), as they benefit most from the boosting and can handle it efficiently.
Added test cases. Tested manually, specifically this query where we had regressed ranking:
```
type:repo "sourcegraph"
```

Search: avoid phrase boost for non-text searches

---

internal/diskcache/cache_test.go

I forgot this when I added the test, so we were basically testing the same thing twice.
updated unit test

tenant: update test to enforce tenant

---

sg.config.yaml

In https://github.com/sourcegraph/sourcegraph/pull/63946 we reworked how we handle assets, but we overlooked updating the target in `sg.config.yaml`.
CI + locally tested (made some changes on the home page, got reloaded as expected)

chore(local): fix outdated frontend target being used

---

cmd/syntactic-code-intel-worker/shared/shared.go

Connecting to the wrong DSN leads to a cryptic error:
```
Message:     {"SeverityText":"FATAL","Timestamp":1723196934012096886,"InstrumentationScope":"init db (syntactic-codeintel-worker)","Caller":"shared/shared.go:87","Function":"github.com/sourcegraph/sourcegraph/cmd/syntactic-code-intel-worker/shared.initCodeintelDB","Body":"Failed to connect to codeintel database","Resource":{"service.name":"syntactic-code-intel-worker","service.version":"286647_2024-08-08_5.6-34a7914fb884","service.instance.id":"syntactic-code-intel-worker-7bb9ccc75c-mkzpk"},"Attributes":{"error":"database schema out of date"}}
```
- existing tests should continue to pass

Use correct DSN for schema validation in syntactic worker

---

internal/redispool/keyvalue.go

All other methods take a pointer receiver, so we should be consistent and avoid
unnecessary copying.
Tiny warm-up as I get up to speed with Redis for the multi-tenancy project.
Covered by CI

Redis: always use pointer receiver in keyvalue

---

WORKSPACE

beta2 release came out yesterday. A few minor fixes on top of beta1.
https://github.com/bazel-contrib/rules_oci/releases/tag/v2.0.0-beta2
CI

build(bazel): upgrade to rules_oci 2.0.0-beta2

---

dev/backcompat/bazel-backcompat.sh
dev/backcompat/flakes.json

Backcompat test suite works by checking out the code at the previous minor release, injects the database schema from `HEAD` and run all Go tests. This ensures that the old code can run against the new schema, thus being backward compatible. 
We forgot to update this the last time, that's why I'm bumping by two tags here. 
CI

chore(ci): bump the tag on which backcompat operates

---

cmd/enterprise-portal/internal/database/codyaccess/codygateway_test.go
cmd/enterprise-portal/internal/database/importer/importer.go
cmd/enterprise-portal/internal/database/subscriptions/licenses.go
cmd/enterprise-portal/internal/database/subscriptions/licenses_test.go
cmd/enterprise-portal/internal/subscriptionsservice/BUILD.bazel
cmd/enterprise-portal/internal/subscriptionsservice/adapters.go
cmd/enterprise-portal/internal/subscriptionsservice/mocks_test.go
cmd/enterprise-portal/internal/subscriptionsservice/v1.go
cmd/enterprise-portal/internal/subscriptionsservice/v1_store.go
cmd/enterprise-portal/internal/subscriptionsservice/v1_test.go
cmd/enterprise-portal/service/service.go

This change follows https://github.com/sourcegraph/sourcegraph/pull/63858 by making the existing subscriptions APIs _read_ from the Enterprise Portal database, instead of dotcomdb, using the data that we sync from dotcomdb into Enterprise Portal.
Part of https://linear.app/sourcegraph/issue/CORE-156
Part of https://linear.app/sourcegraph/issue/CORE-158
Updated unit and integration tests

feat/enterpriseportal: existing subscriptions read APIs use enterprise portal DB

---

client/web-sveltekit/src/lib/codenav/ExplorePanel.svelte
client/web-sveltekit/src/lib/codenav/ExplorePanelFileUsages.svelte

The first version of the file tree for the revision panel had flat file names. This meant that files were not organized, they were very horizontal-space-sensitive, and you could not filter to a directory (only repo and file name).
This updates the file filter to be a full tree, which I find much easier to use.
[Video walkthrough](https://share.cleanshot.com/ZH4jqk3S)
Manual testing. See video.
- Update references panel in the rewrite to use a full file tree

Explore panel: more granular file tree

---

client/web-sveltekit/src/lib/TreeNode.svelte
client/web-sveltekit/src/lib/path/DisplayPath.svelte
client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/FileViewModeSwitcher.svelte
client/web-sveltekit/src/routes/search/+page.svelte
client/web-sveltekit/src/routes/search/CommitSearchResult.svelte
client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte
client/web-sveltekit/src/routes/search/FilePathSearchResult.svelte
client/web-sveltekit/src/routes/search/RepoSearchResult.svelte
client/web-sveltekit/src/routes/search/SearchResults.svelte
client/web-sveltekit/src/routes/search/SymbolSearchResult.svelte
client/web-sveltekit/src/routes/search/page.spec.ts
client/web-sveltekit/src/routes/search/searchResultsFocus.ts
client/web-sveltekit/src/routes/styles.scss
client/web-sveltekit/src/routes/svelte-overrides.scss
client/web-sveltekit/src/testing/search-testdata.ts

(Low priority, not needed for the Aug 7 release)
This adds support for navigating between search results with keyboard shortcuts. Similar to the React app, `j` or `down` means "next result", and `k` or `up` means previous results. To accompany this change, when a search is submitted, the first result is focused by default to facilitate iterating over results with the keyboard.
[Video walkthrough](https://share.cleanshot.com/N2tBbJ44)
Added a playwright test that steps through each type of search result and back. Lots of manual testing for feel.
- Added support for keyboard navigation between search results in the web app rewrite

Svelte: add support for navigating search results with the keyboard

---

client/common/src/util/markdown/markdown.ts
client/web-sveltekit/BUILD.bazel
client/web-sveltekit/src/app.html
client/web-sveltekit/src/lib/common.ts
client/web-sveltekit/src/lib/routes.ts
client/web-sveltekit/src/lib/search/SyntaxHighlightedQuery.svelte
client/web-sveltekit/src/lib/search/communityPages.ts
client/web-sveltekit/src/lib/wildcard/Markdown.svelte
client/web-sveltekit/src/params/communitySearchContext.ts
client/web-sveltekit/src/routes/[community=communitySearchContext]/+page.svelte
client/web-sveltekit/src/routes/[community=communitySearchContext]/+page.ts
client/web-sveltekit/src/routes/[community=communitySearchContext]/config.ts
client/web-sveltekit/src/routes/[community=communitySearchContext]/page.gql
client/web-sveltekit/src/routes/[community=communitySearchContext]/page.spec.ts
client/web-sveltekit/src/testing/integration.ts
client/web/src/sveltekit/routes.ts
cmd/frontend/internal/app/ui/sveltekit/BUILD.bazel
cmd/frontend/internal/app/ui/sveltekit/gen/gen_routes.go
cmd/frontend/internal/app/ui/sveltekit/routes.go
cmd/frontend/internal/app/ui/sveltekit/sveltekit.go
cmd/frontend/internal/app/ui/sveltekit/tags/tags.go

What: This PR does the bare minimum to migrate the current community search pages to Svelte. A better strategy for managing them is needed in the medium/long term.
How: The community pages live at the root (e.g. `/kubernetes`) which complicates things, but I'll get to that later. The page is implemented as a single parameterized route. A parameter matcher is used to validate the community name. Because these pages should only be accessible on dotcom the matcher also validates whether or not we are on dotcom (if not, the path will be matched against a different route).
The page config is stored in a separate module so that it's no included in every page and so that it can be used in the integration test.
The loader and page implementation themselves are straightforward. I made a couple of …

feat(svelte): Migrate dotcom community search pages to Svelte

---

internal/repos/BUILD.bazel

See https://buildkite.com/organizations/sourcegraph/analytics/suites/sourcegraph-bazel/tests/d047e8dd-c849-8a8b-8925-41c2b8e58ec9?branch=main, this particular test target tends to timeout on occasions, because it goes over the `short` timeout. 
By sharding it, we could hope it would be more stable. So, time will tell if that was worth it. Right now, analytics shows that it goes down to 10s with four shards, which is faster that most runs. 
CI

chore(ci): shard //internal/repos:repos_test

---

internal/database/migration/stitch/archives.go

These all fail and are only run outside of bazel (which is why we didn't notice it). I believe the root cause is google getting more strict with the URLs you pass it.
Should we consider removing these tests given no one has reported it not working? Or should we get it working in Bazel?
Test Plan go test ./internal/database/migration/stitch/

migration: fix stitch test cases

---

internal/database/migration/stitch/stitch_test.go

This change caches what we download from google storage aswell as using parallelism per subtest.
Before this change on my desktop computer this test would timeout after 10 minutes. It now takes 7s.
Test Plan: go test ./internal/database/migration/stitch

migration: make stitch tests run in 7s

---

cmd/cody-gateway/internal/actor/productsubscription/productsubscription.go
cmd/cody-gateway/internal/actor/productsubscription/productsubscription_test.go
cmd/enterprise-portal/internal/codyaccessservice/BUILD.bazel
cmd/enterprise-portal/internal/codyaccessservice/adapters.go
cmd/enterprise-portal/internal/codyaccessservice/adapters_test.go

This change ensure we correctly handle:
1. In Enterprise Portal, where no active license is available, we return ratelimit=0 intervalduration=0, from the source `PLAN` (as this is determined by the lack of a plan)
2. In Cody Gateway, where intervalduration=0, we do not grant access to that feature
Unit tests

fix/enterpriseportal, fix/codygateway: zero-value durations and missing active licenses

---

internal/codeintel/codenav/BUILD.bazel
internal/codeintel/codenav/commit_cache.go
internal/codeintel/codenav/gittree_translator.go
internal/codeintel/codenav/service.go
internal/codeintel/codenav/service_deps.go

In codenav, we use very few APIs from gitserver, so let's use a more
narrow interface (which we can potentially fake in the future) instead
of depending on gitserver.Client directly.

chore: Replace gitserver.Client -> minimalGitserver in codenav

---

schema/settings.schema.json

The search clients [default to using Zoekt's ranking](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f010787579fc0b88ef945a6cfd0091c58eefceeb/-/blob/client/web-sveltekit/src/routes/search/FileContentSearchResult.svelte?L29-29) if this setting is unset, but it's documented as defaulting to ordering by line number. Just fixes the default in the schema, which is only used for documentation.
Fixes https://linear.app/sourcegraph/issue/SRCH-869/modify-search-blitz-to-support-fully-custom-queries
N/A

Chore: fix default value for clientSearchResultRanking

---

release.yaml

This PR adds the ability to use `--type minor` when running `sg release create` during the release process. 
For the time being this step is the _same_ as `--type patch` which is the default, however this allows us to differentiate the two types now and prepares for when/if the two types diverge. This also clears up the some confusion as the `sg release` command _can_ accept `--type minor` already and one would expect that to be the choice when you are in fact cutting a minor type. 
Closes: https://linear.app/sourcegraph/issue/REL-351/sourcegraphsourcegraph64377-fixrelease-add-minor-step-to-internal
Tested locally with `--type minor` tag.
```shell
➜  sourcegraph git:(08-08-jdp_release_minor-flag-addition) sg release create --version 5.6.877 --type minor
👉 [     setup] Finding release …
```

fix(release): add `minor` step to internal release create command

---

dev/ci/annotate-cloud-ephemeral.sh
dev/sg/internal/cloud/build_command.go

fixed typo. these commands are under `sg cloud eph`
CI

sg/cloud: fix eph cmd typo

---

internal/ratelimit/globallimiter.go
internal/redispool/keyvalue.go
internal/redispool/keyvalue_test.go

Our redis `KeyValue` interface has a built-in way to prefix all keys. This is helpful for integration tests, to contain all keys within a test namespace. 
This PR solidifies the implementation by pushing down the prefixing as much as possible. In doing so, it fixes a bug with the `Keys()` method where we forgot to prefix the pattern. This makes it easier to add new methods to the interface without forgetting to add the prefix.
Added a new unit test `TestKeyValueWithPrefix`

Redis: refactor key prefixing

---

cmd/frontend/internal/cli/http.go

Fixes CODY-3267
Previously, requests to `/api/` matched the new `publicrestapi` module, which meant that requests to the GraphQL `/api/console` no longer worked. This PR fixes the problem by narrowing the prefix-match to `/api/v1` so that it no longer matches `/api/console`.
I kept the scope of this PR narrow and only fixed the /api/console bug. I will share a separate RFC to seek input on the tradeoffs between /api/v1 and /.api. I can make that change separately if there's wide consensus in #wg-architecture that we want to keep all API endpoints (public and internal-facing) under /.api.
Ran `sg start minimal` and confirmed that I'm able to visit the URL https://sourcegraph.test:3443/api/console 
On the main branch, the same URL leads to a 404 page.
I also confirmed that the …

fix/API: make requests to `/api/console` work again

---

internal/codeintel/codenav/service.go
internal/codeintel/codenav/transport/graphql/iface.go
internal/codeintel/codenav/transport/graphql/mocks_test.go
internal/codeintel/codenav/transport/graphql/root_resolver.go

Closes https://linear.app/sourcegraph/issue/GRAPH-797/return-all-search-based-results-if-syntactic-is-not-requested
Making sum-types like a caveman...
Manual testing via API. I can't make the web app do a search-based usages request at the moment.

fix: return all search-based results if no syntactic provenance is requested

---

dev/sg/ci/subcommands.go
dev/sg/generates.go
dev/sg/internal/generate/generate.go
dev/sg/internal/migration/squash.go
dev/sg/internal/run/BUILD.bazel
dev/sg/internal/run/command.go
dev/sg/internal/run/helpers.go
dev/sg/sg_doctor.go
dev/sg/sg_version.go
internal/lazyregexp/lazyre.go

Closes DINF-78
The output of `sg gen` is a bit hard to read when there's an error, this is because the new line character `\n` isn't rendered as a new line. It turns out the `%q` formatting directive used to quote a string doesn't render the `\n` character as a new line.
| Before |
|---|
| ![CleanShot 2024-08-12 at 11 17 57@2x](https://github.com/user-attachments/assets/e03ec503-e437-4b68-80b3-fe34ac8848fb)  |
| After  |
|---|
| ![CleanShot 2024-08-12 at 10 53 35@2x](https://github.com/user-attachments/assets/5b7aac63-27b6-4de0-9c56-3b739f0ee0f9)   |
I also added a func to extract error messages from a bazel command to avoid long output message when a bazel command fails and give the user relevant messages related to the error. 
| Before  |
|---| …

fix(sg): make `sg gen` output more readable

---

cmd/frontend/internal/httpapi/BUILD.bazel
cmd/frontend/internal/httpapi/httpapi.go
cmd/frontend/internal/llmapi/BUILD.bazel
cmd/frontend/internal/llmapi/chat_completions_handler.go
cmd/frontend/internal/llmapi/chat_completions_handler_test.go
cmd/frontend/internal/llmapi/httpapi.go
cmd/frontend/internal/llmapi/utils_test.go

Previously, it took ~6 seconds for a single edit/test/debug feedback loop in the `llmapi` module. After this change, it's now 1-2s.
The reason the feedback loop was slow was that we depended on the `//cmd/frontend/internal/modelconfig` target, which transitively brings in `graphqlbackend` and all the migration code, which adds huge overhead to Go link times. It was relatively easy to untangle this dependency so I went ahead and removed it to boost my local feedback loop.
Green CI.
To measure the timing, I ran the tests, made a tiny change and ran the tests against to measure the total time to build+test.
```
❯ time go test -timeout 30s github.com/sourcegraph/sourcegraph/cmd/frontend/internal/llmapi
ok  	github.com/sourcegraph/sourcegraph/cmd/frontend/internal/llmapi	2.394s
go test …
```

chore/API: speed up edit/test feedback loop for llmapi module

---

client/web-sveltekit/src/lib/Tooltip.svelte
client/web-sveltekit/src/lib/dom.ts

Fixes srch-744
It seems that the code for testing whether the target element is part of the layout didn't work in hovercards because it (possibly?) runs before the hovercard is rendered.
Moving the logic to `onMount` + `await tick()` seem to work, although that might still be a coincidence.
Hovering over the 'precise' badge shows the corresponding tooltip.

fix(svelte): Fix tooltip in hovercards

---

client/shared/src/codeintel/api.ts
client/shared/src/codeintel/legacy-extensions/language-specs/languages.ts

Fixes srch-882
I noticed that the button wasn't shown anymore (neither in Svelte nor in React). It seems that this broke when we switched from using the file extension to getting the language(s) from the server.
The server sends back capitalized names which we compare against lowercase IDs.
If there there is a new/modern way to find out whether a language support 'find implementation' or not, please let me know. For the time being this seems to be a simple fix to get it working again like it before. Alternatively we can also compare the stylized name.
Hovering over a Go interface (e.g. https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/conf/server.go?L12) shows the 'find implementations' button in the hovercard again)

fix(web): Show 'Find implementation' button for languages that support it

---

internal/database/schema.json
internal/database/schema.md
migrations/frontend/1723557836_faster_soft_delete_trigger_for_permissions/down.sql
migrations/frontend/1723557836_faster_soft_delete_trigger_for_permissions/metadata.yaml
migrations/frontend/1723557836_faster_soft_delete_trigger_for_permissions/up.sql
migrations/frontend/squashed.sql

We believe the migration to add tenant_id is failing on dotcom is due to this trigger which runs for any possible change to a row. Instead it only needs to run if the deleted_at column changes. So this migration just adjusts each trigger to only run if deleted_at is changed.
We don't need to change the trigger function, since the trigger functions only read deleted at.
If this doesn't resolve our issue, we will need to look into a statement level trigger for all our triggers.
Test Plan: CI and then will test safely on larger instances.

migration: specify column for soft delete triggers

---

dev/ci/internal/buildkite/buildkite.go
dev/ci/internal/ci/misc_operations.go

Closes DINF-198
CI
```
{
"label": ":bazel::broom: Go mod tidy",
"key": "bazel-go-mod",
"command": [
"./dev/ci/bazel-gomodtidy.sh"
],
"timeout_in_minutes": "5",
"retry": {
"automatic": [
{
"limit": 1,
"exit_status": "*"
},
{
"limit": 1,
"exit_status": -1
}
]
},
"agents": {
"queue": "aspect-small"
}
},
```

ci: set go mod tidy step timeout

---

cmd/enterprise-portal/internal/routines/licenseexpiration/BUILD.bazel
cmd/enterprise-portal/internal/routines/licenseexpiration/licenseexpiration.go
cmd/enterprise-portal/internal/routines/licenseexpiration/licenseexpiration_test.go
cmd/enterprise-portal/internal/routines/licenseexpiration/mocks_test.go
cmd/enterprise-portal/internal/routines/licenseexpiration/store.go
cmd/enterprise-portal/service/service.go

- The time.Second frequency is too frequent to be checking if the job should be run, I think I set this in testing
- Adjust the Slack messaging to say `Active license`
- Adjust the Slack messaging to include the Salesforce subscription ID
Tests

fix/enterpriseportal: adjust job check frequency, tweak messaging

---

client/web-sveltekit/src/lib/TreeNode.svelte

I think I broke this when doing some refactoring to make the file tree usable in the ref panel. Currently, the guide lines only go one level of depth. 
Fixes https://linear.app/sourcegraph/issue/SRCH-890/fix-file-tree-guidelines
Screenshot for proof in both the file sidebar and the ref panel:

Svelte: fix file tree guide lines

---

cmd/enterprise-portal/internal/codyaccessservice/v1.go
cmd/enterprise-portal/internal/subscriptionsservice/v1.go
cmd/enterprise-portal/internal/subscriptionsservice/v1_test.go

Staging this PR in case we don't find a way to unblock https://sourcegraph.slack.com/archives/C079SAU0E72/p1723573784387739?thread_ts=1723566345.486509&cid=C079SAU0E72. If this passes CI first, I'll roll this out to Enterprise Portal to unblock TS/CE
This is needed because we can't roll out https://github.com/sourcegraph/sourcegraph/pull/64450 due to a stuck migration
n/a

fix/enterpriseportal: [MUST REVERT LATER] relax scopes for write operations

---

client/web-sveltekit/src/lib/cody/CodyChat.svelte
client/web-sveltekit/src/lib/cody/CodySidebar.svelte
client/web-sveltekit/src/lib/routes.ts
client/web-sveltekit/src/routes/cody/chat/+page.svelte
client/web-sveltekit/src/routes/cody/chat/+page.ts
client/web/src/sveltekit/routes.ts
cmd/frontend/internal/app/ui/sveltekit/routes.go

Closes #srch-906
This commit adds the cody chat page to svelte. This is simply reusing the existing wrapper around the React component and renders it in a standalone page.
| React | Svelte |
| ![2024-08-13_17-13](https://github.com/user-attachments/assets/a0f1e867-495d-44c2-965a-fce240ce630c) | ![2024-08-13_17-13_1](https://github.com/user-attachments/assets/08b5701f-463e-48da-bb0a-3ff9038f4259) |
When merged this will cause the cody chat page to be handled by new web app on dotcom by default. 
- Verified that chat loads and the tabs are clickable.
- Verified that the scroll behavior works as in the React app.
- Verified that the sidebar chat still works as expected (scroll behavior, default context loading/switching)

feat(svelte): Add cody chat page

---

cmd/appliance/shared/config.go
cmd/appliance/shared/shared.go
internal/appliance/appliance.go
internal/appliance/frontend/maintenance/src/Install.tsx
internal/appliance/json.go
internal/appliance/routes.go
internal/appliance/selfupdate/BUILD.bazel
internal/appliance/selfupdate/selfupdate.go
internal/appliance/selfupdate/selfupdate_test.go
internal/appliance/selfupdate/testdata/releases.json

Probably easiest to review commit-by-commit:
**chore(appliance): version list obtained from backend**
Instead of calling release registry directly from the frontend. This
commit is just preparation for a fallback mechanism for users that do
not want the external dependency on release registry.
**feat(appliance): optionally load pinned releases file**
Instead of calling release registry. This is a fallback mechanism for
airgap users.
**feat(appliance): respect pinned release versions during self-update**
---
Relates to https://linear.app/sourcegraph/issue/REL-200/airgap-fallback-for-appliance-dependency-on-release-registry and https://linear.app/sourcegraph/issue/REL-268/airgap-fallback-for-appliance-self-update.
See companion PR https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/5 …

feat(appliance): optionally load pinned releases file

---

internal/download/BUILD.bazel
internal/download/download.go
internal/download/download_test.go

Closes DINF-182
Before `sg start otel` would fail if `.bin` did not exist. We now create the destination directory if it doesn't exist
1. `rm -rf .bin`
2. `sg start otel`
and unit tests + CI
* when downloading files, ensure the directory we download to exists

chore: download - ensure dir exists when writing to dst

---

client/web-sveltekit/src/lib/blame/reblame.ts

Did a ripgrep to see if there are any other `console.log` statements that should be removed but this was the only one.
code inspection, trivial change

fix(svelte): Remove unnecessary console.log statement

---

cmd/cody-gateway/internal/httpapi/BUILD.bazel
cmd/cody-gateway/internal/httpapi/diagnostics.go
cmd/cody-gateway/shared/main.go
cmd/frontend/internal/cli/serve_cmd.go
internal/metrics/store/BUILD.bazel
internal/metrics/store/store.go
internal/ratelimit/globallimiter.go
internal/rcache/rcache.go
internal/redispool/keyvalue.go
internal/redispool/keyvalue_test.go
internal/redispool/mocks.go
internal/redispool/redispool_test.go

We want to discourage direct usage of the Redis pool in favor of routing all calls through the main `KeyValue` interface. This PR removes several usages of `KeyValue.Pool`. To do so, it adds "PING" and "MGET" to the `KeyValue` interface.
New unit tests for `MGet` and `Ping`.
Manually tested Cody gateway changes:
```
$ sg start cody-gateway
$ curl -X GET localhost:9992/-/healthz
```

Redis: remove some direct pool usages

---

internal/database/users.go

When a user is deleted and then undeleted, the original web sessions prior to the deletion are able to be reused. This is inconsistent with the behaviour for access tokens: access tokens are revoked on user deletion, but web sessions are not.
This makes it so that deleting the user account also forces a sign out for that account.
It does this by setting `invalidated_sessions_at=now()`, which is exactly the same thing that `InvalidateSessionsByIDs` does:
https://github.com/sourcegraph/sourcegraph/blob/cbd12608b5a5f65f07c878aaeaf6e3e9e678809c/internal/database/users.go#L1040-L1045
This change should be covered by the below existing test: https://github.com/sourcegraph/sourcegraph/blob/cbd12608b5a5f65f07c878aaeaf6e3e9e678809c/internal/database/users_test.go#L741
* Deleting a user will now …

Invalidate sessions on user deletion

---

internal/database/schema.json
internal/database/schema.md
migrations/frontend/1723557836_faster_soft_delete_trigger_for_permissions/down.sql
migrations/frontend/1723557836_faster_soft_delete_trigger_for_permissions/up.sql
migrations/frontend/squashed.sql

The improvement to the triggers I tried to ship yesterday failed on dotcom. This is because it has the same issue as the tenant_id column where we can't acquire the ShareRowExclusiveLock for multiple important tables in a transaction without deadlocking. We use the same technique where we commit and restart the transaction. This is safe to do since even if it fails, the migration is idempotent and partial migration still works.
Additionally after reading the documentation on triggers more deeply [1], I noticed we can add in a WHEN clause to triggers. We already have this in the functions, but this should be more efficient.
I didn't want to remove the condition from the functions just yet, since that makes the migration more risky under partial failure.
CI. Also added BEGIN and COMMIT to …

migrations: commit between table locks and use when condition for triggers

---

internal/ratelimit/globallimiter.go
internal/rcache/fifo_list.go
internal/rcache/rcache.go
internal/redispool/keyvalue.go
internal/redispool/keyvalue_test.go
internal/redispool/mocks.go

This PR makes `WithPrefix` visible on the `KeyValue` interface. Previously, we had other interface implementations that did not support `WithPrefix`, but now `redisKeyValue` is the only implementation. `WithPrefix` is currently just used in tests, but it's broadly useful and will help clean up a bunch of places that wrap Redis and manually add key prefixes.

Redis: expose KeyValue.WithPrefix

---

dev/ci/internal/ci/images_operations.go
dev/ci/push_all.sh

We're currently evaluating only pushing on Dockerhub when releasing, as everything else uses GCR, but until then, we lower the concurrency to 4 when pushing there, and we keep 8 on the others. 
Follow-up to https://github.com/sourcegraph/devx-support/issues/1163
CI

chore(ci): lower concurrent jobs when pushing to dockerhub

---

.github/workflows/scip-go.yml
internal/codeintel/autoindexing/internal/inference/libs/indexes.go
internal/codeintel/autoindexing/internal/inference/testdata/go_files_in_root.yaml
internal/codeintel/autoindexing/internal/inference/testdata/go_modules.yaml

Partly reverts https://github.com/sourcegraph/sourcegraph/pull/62753
due to https://github.com/sourcegraph/scip-go/issues/119 which is blocked
on upstream https://github.com/golang/go/issues/68877
n/a - covered by existing tests

chore: Downgrade auto-indexing scip-go SHA and pin version in CI

---

cmd/enterprise-portal/internal/subscriptionsservice/testdata/TestRenderLicenseKeyCreationSlackMessage.golden
cmd/enterprise-portal/internal/subscriptionsservice/v1.go
cmd/enterprise-portal/internal/subscriptionsservice/v1_test.go

We require a message on license creation, might as well include it
Unit test

fix/enterpriseportal: add license creation message to Slack webhook

---

cmd/pings/BUILD.bazel
cmd/telemetry-gateway/BUILD.bazel

As part of https://linear.app/sourcegraph/issue/DINF-200/stop-pushing-to-docker-hub-for-non-release-main-builds
Sistered https://github.com/sourcegraph/managed-services/pull/1951
Confirmed images are pushed to this registry

chore(msp): use us.gcr.io/sourcegraph-dev for pings and telemetry-gateway msp_delivery step

---

lib/process/pipe.go

I just learnt of this function and the first hit in our codebase of "<-.*Done" was this in my editor and its an example of AfterFunc!
https://pkg.go.dev/context#AfterFunc
Looks like there are lots of places we can use this. From what I can tell this avoids spawning goroutines until ctx is done and uses some funky internal stuff so its likely more efficient than yet another goroutine waiting on Done. It also reads nicer.
Test Plan: CI

lib/process: use context.AfterFunc

---

client/web/src/enterprise/site-admin/dotcom/productSubscriptions/EnterprisePortalEnvSelector.tsx
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminCreateProductSubscriptionPage.tsx
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminGenerateProductLicenseForSubscriptionForm.tsx
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminLicenseKeyLookupPage.tsx
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductLicenseNode.tsx
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionNode.module.scss
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionsPage.tsx

Closes most of https://linear.app/sourcegraph/issue/CORE-250/dotcom-address-post-launch-management-ui-feedback except for a question for design - I'll spin that out into a separate issue if needed
1. Fix dark mode subscription list view background
2. Add more detailed tooltip for EP env dropdown
3. Add license creation message to license node
4. Add more telemetry on internal usage
```
sg start dotcom
```

feat/dotcom: UX tweaks for subscription management

---

client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.ts

We currently redirect from a `commit` to a `changelist` when the current project is a perforce depot. This PR adds a similar redirect from `commits` to `changelists`.
Manual testing
CI passing

[Sveltekit]: Perforce - redirect from `commits` to `changelists` url when necessary

---

client/web/src/components/gitHubApps/CreateGitHubAppPage.tsx
client/web/src/enterprise/batches/settings/AddCredentialModal.tsx

We have decided to add an experimental label so that customers know that the GitHub Apps integration for Batch Changes may have rough edges.
The plan was initially to add a beta label, but that was unfortunately not added yet.
We plan to remove this or lift it to beta once we've seen customers be successful with the GitHub Apps for Batch Changes integration.
Site Admin Dropdown:
Site Admin Modal:
Commit signing (which is beta and should not have the experimental label):
User Settings:
Manual testing + CI
- fix(batches): add experimental label to GitHub apps integration

fix(batches): add experimental label to GitHub apps integration

---

client/web/src/site-admin/SiteAdminPingsPage.tsx

Updating docs to include that we collect ip address of the instance (`remote_ip` in pings)
CI

Update `SiteAdminPingsPage.tsx` to include collection of ip address

---

cmd/enterprise-portal/internal/codyaccessservice/v1.go
cmd/enterprise-portal/internal/subscriptionsservice/v1.go
cmd/enterprise-portal/internal/subscriptionsservice/v1_test.go

Reverts sourcegraph/sourcegraph#64453, as indicated we need to.
Closes https://linear.app/sourcegraph/issue/CORE-248
Test plan: confirm https://github.com/sourcegraph/sourcegraph/pull/64450 is rolled out

Revert "fix/enterpriseportal: relax scopes for write operations"

---

dev/managedservicesplatform/spec/environment.go
dev/managedservicesplatform/stacks/monitoring/job.go

Closes https://linear.app/sourcegraph/issue/CORE-237/error-creating-alertpolicy-with-an-invalid-duration-value-of-24h10m
GCP no longer allows alert policies on missing metrics for durations > 23h30m. Since the introduction of the MSP job runtime, jobs can depend on Sentry execution check-ins instead to be notified on missing job runs.
```
go build -o ./sg ./dev/sg && ./sg install -f -p=false
sg msp generate -all
```

fix/msp/jobs: do not provision job absence alert for crons over 23h30m

---

cmd/cody-gateway/internal/actor/productsubscription/enterpriseportal/BUILD.bazel
cmd/cody-gateway/internal/actor/productsubscription/enterpriseportal/enterpriseportal.go
lib/managedservicesplatform/clients/BUILD.bazel
lib/managedservicesplatform/clients/clients.go
lib/managedservicesplatform/go.mod

These have worked pretty well for Cody Gateway - this change exports these from the MSP lib so that they can be used elsewhere.
Closes https://linear.app/sourcegraph/issue/CORE-203
n/a

lib/msp: new clients library with recommended dial options

---

internal/extsvc/bitbucketserver/client.go

This is currently only used in the connectivity check, but could be a massive footgun if someone ever used it - the `ps` is NOT passed to `send`, it's assigned to the `Values` property of the struct that is sent there, so `ps` will always be empty.a
Test plan: CI passes.

bitbucket: Fix UserPermissions not returning anything

---

.pre-commit-config.yaml

Part of https://github.com/sourcegraph/devx-support/issues/1164
Also updated:
- precommit as we were using a 2019 version
- updated buildifier hook  as we were 2 major versions behind
Modified a Bazel file locally and the Buildifier hook kicked in

chore(precommit): update precommit and remove trailing whitespace hook

---

wolfi-packages/p4-fusion-sg.yaml

This is to use the new p4-fusion version that does not fetch labels when `noConvertLabels` is set.
Builds pass

Update p4-fusion wolfi image

---

cmd/frontend/graphqlbackend/cody_context.go
cmd/frontend/graphqlbackend/cody_context.graphql
cmd/frontend/internal/codycontext/BUILD.bazel
cmd/frontend/internal/codycontext/context.go
cmd/frontend/internal/context/resolvers/context.go
internal/cast/BUILD.bazel
internal/cast/cast.go
internal/cast/cast_test.go
internal/codeintel/autoindexing/internal/background/dependencies/BUILD.bazel
internal/codeintel/autoindexing/internal/background/dependencies/job_dependency_indexing_scheduler.go
internal/types/types.go

This adds the ability to filter cody context by a file pattern. We build on top of this to support [directory mentions](https://github.com/sourcegraph/cody/pull/5210#issuecomment-2291438393) in Cody Chat. 
Tested as part of [this PR](https://github.com/sourcegraph/cody/pull/5210#issuecomment-2291438393)

Cody: add file pattern filter to context resolver

---

internal/telemetry/sensitivemetadataallowlist/sensitivemetadataallowlist.go
internal/telemetry/sensitivemetadataallowlist/sensitivemetadataallowlist_test.go

PR adds `otherCompletionProviders` as an allowlisted key for `privateMetadata`.
Updated test to validate multiple allowlisted keys for one feature

add `otherCompletionProviders` to `privateMetadata` allowlist

---

cmd/enterprise-portal/internal/subscriptionlicensechecksservice/mocks_test.go
cmd/enterprise-portal/internal/subscriptionlicensechecksservice/v1.go
cmd/enterprise-portal/internal/subscriptionlicensechecksservice/v1_store.go
cmd/enterprise-portal/internal/subscriptionlicensechecksservice/v1_test.go
cmd/enterprise-portal/service/config.go
cmd/enterprise-portal/service/service.go

The existing handler has a similar escape hatch - when enabled, all checks return healthy.
unit tests

feat/enterpiseportal: add checks bypass toggle as escape hatch

---

client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminCreateProductSubscriptionPage.tsx

See https://linear.app/sourcegraph/issue/CORE-256 and https://sourcegraph.slack.com/archives/C05GJPTSZCZ/p1723835604698979?thread_ts=1723834983.348549&cid=C05GJPTSZCZ
There is no backend validation for this.
n/a

fix/dotcom: do not require Salesforce subscription ID

---

cmd/executor/internal/apiclient/queue/client.go
cmd/executor/internal/worker/command/command.go
cmd/searcher/internal/search/search_regex.go
dev/sg/internal/run/command.go
dev/sg/internal/run/logger.go
internal/goroutine/periodic.go
internal/goroutine/periodic_test.go
internal/observation/observation.go
internal/workerutil/worker_test.go

This is the result of updating the relevant callsites from
```shell
git grep '<-.*Done' | grep -v case
```
to use context.AfterFunc instead of directly spinning up a goroutine to wait for Done.
Test Plan: close code review and CI

all: use context.AfterFunc

---

dev/sg/sg_migration.go

I keep typing "sg migrate up" instead of "sg migration up" since that just make more sense to my mind.
Test Plan: yolo

sg: add migrate alias for migration subcommand

---

dev/sg/sg_migration.go
internal/database/migration/cliutil/BUILD.bazel
internal/database/migration/cliutil/tenant.go
internal/database/migration/cliutil/tenant_down.sql
internal/database/migration/cliutil/tenant_up.sql

This adds a new command to "sg migration" which will enable RLS on the tenant_id column. It relies on the introspection features already present in our migration store to automatically update any table which has the "tenant_id" column.
Additionally we provide functionality to disable the enforcement via the "--disable" flag.
Test Plan: "go run ./dev/sg migration enforce-tenant-id" with and without "--disable" specified. Then inspected the DB state to confirm the migrations run correctly.
Fixes https://linear.app/sourcegraph/issue/SPLF-211/easy-way-to-enable-rls-enforcement-for-dev

sg: add migration enforce-tenant-id command

---

internal/completions/client/openai/openai.go
internal/completions/client/openai/openai_test.go
internal/completions/client/openai/types.go

Fixes CODY-3194
Previously, using `/chat/completions` with OpenAI models always returned an empty completion because we were reading a non-existent `"text"` property instead of the nested `"message": { "content": ...}` property.
This PR fixes the bug and adds a test case to demonstrate how we parse a real-world OpenAI response.
See new test cases.
I also manually verified this fixes the bug with an e2e local instance sending requests to OpenAI
```
❯ curl 'https://sourcegraph.test:3443/.api/completions/stream?api-version=1&client-name=defaultclient&client-version=6.0.0' \
-H 'Content-Type: application/json' \
-H "Authorization: token $HURL_token" \
--data-raw '{
"maxTokensToSample": 4000,
"messages": [
{
"speaker": "human",
"text": "Respond with \"no\" and nothing else."
}
],
"model": …
```

fix/openai: non-streaming LLM response

---

dev/sg/main.go

If they are configured, there is no point warning about the defaults being different. In my case I configure these flags via envvars, so I don't need to be warned about it all the time.
Test Plan: I ran an sg command with and without envvars configuring and it didn't and did warn respectively.
``` shellsession
sourcegraph on  main [$] ❄️ sourcegraph-dev-env took 44s 
❯ env | grep ^SG
SG_DISABLE_OUTPUT_DETECTION=1
SG_SKIP_AUTO_UPDATE=1
SG_DISABLE_ANALYTICS=1
sourcegraph on  main [$!] ❄️ sourcegraph-dev-env took 19s 
❯ sg migrate up
⚠️ Running sg with a dev build, following flags have different default value unless explictly set: 
✅ Connection to frontend succeeded
✅ Connection to codeintel succeeded
✅ Connection to codeinsights succeeded
✅ Schema(s) are up-to-date!
sourcegraph on  main …
```

sg: do not warn about dev build if flags are configured

---

.github/workflows/scip-go.yml

This is a partial cherry-pick of only the github actions change, and not the indexex.go change (which conflicts).
(cherry picked from commit badd28ec24af693cdb4203fbc70d166069fa765b)
Test Plan: scip-go in this CI is green.

chore: pin scip-go version in CI (#64477)

---

internal/completions/client/openai/BUILD.bazel
internal/completions/client/openai/openai_test.go

Following up on code review comment https://github.com/sourcegraph/sourcegraph/pull/64473#discussion_r1721604646
Green CI.

fix: use `logtest.Scoped(t)` for tests

---

dev/ci/semgrep-scan.sh

This PR attempts to handle GHAS check to be non-zero exit code in semgrep scan script
- CI 🟢 
- chore(security): Fix GHAS check as non-zero exit code

chore(security): added better GHAS check
